### ISSUE TITLE
Project Details/Feature Picker: feature count is innacurate

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#100]
By selecting and deselecting features a few times, was able to get an inaccurate feature count. See screenshots. Only 2 features are selected, yet the top bar shows "3 selected." 

Also, in some cases, selecting a new feature caused the previously selected feature to become deselected. Can't reproduce this behavior consistently, though. 

![screen shot 2016-09-15 at 3 13 50 pm](https://cloud.githubusercontent.com/assets/12552247/18569588/618bd7c0-7b58-11e6-86b8-7f6f10fd5120.png)
![screen shot 2016-09-15 at 3 14 01 pm](https://cloud.githubusercontent.com/assets/12552247/18569590/634e59f2-7b58-11e6-8be8-4520adcc3695.png)

**Comment by vikasrohit** [comment]
@fnisen I have tried to reproduce the issue with multiple and quick enable/disable and select/unselect actions. Not able to reproduce the original issue, however, fixed issue with switch button which was causing the button to keep the state of the last action i.e. if user has enabled a feature and then selects another feature which is not enabled yet, it was still showing the switch button in enabled state.

**Comment by vikasrohit** [comment]
Tracking with Asana task https://app.asana.com/0/95614844085038/182825171197138

**Comment by fnisen** [comment]
Thanks @vikasrohit. Maybe that was the root cause. Can you please merge? I'll try to reproduce after that.

**Comment by vic-appirio** [comment]
The styles are fixed in the PR #114

**Comment by fnisen** [comment]
Not seeing any issues after the recent update, so will close this.
