### ISSUE TITLE
Chrome and Firefox does not have a clear text button

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1000]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com using Chrome and Firefox
Click Start a project  
Select any project type  
In the Project Name field type anything
Do the same steps above using Edge or IE and notice the Project Name textbox then compare it to FF and Chrome

### Expected behavior  
Project Name field in Chrome and FF should also have a clear text button like in Edge and IE.

### Actual behavior  
Project Name field in Chrome and Firefox does not have a clear text button

### Screenshot/screencast
IE
![clear ie](https://user-images.githubusercontent.com/1199534/28538943-8a97c5cc-70e2-11e7-843e-2c2aa4e701b3.png)

Edge
![clear edge](https://user-images.githubusercontent.com/1199534/28538971-9dd50758-70e2-11e7-91c5-32ae700dbf45.png)

Chrome
![clear chrome](https://user-images.githubusercontent.com/1199534/28539002-b7ac72ec-70e2-11e7-8d91-634316b52488.png)

FF
![clear ff](https://user-images.githubusercontent.com/1199534/28539012-c6676968-70e2-11e7-8790-a21790bc6a76.png)

#### Environment
Windows 10 Pro, Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Firefox 54.01
- User role: None
- Account used: None

**Comment by gondzo** [comment]
this is a browser feature in IE/Edge, no need to port it to Chrome, FF
