### ISSUE TITLE
Connect logo has white background in restore session screen

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1001]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com  
Click Start a project  
Select any project type  
Fill in on any details
Close the page
Go to https://connect.topcoder-dev.com  
Click Start a project  
On the restore session screen notice the Connect logo

### Expected behavior  
The logo should be consistent, there should be not white background and should also be colored. 

### Actual behavior  
Connect logo has white background.

### Screenshot/screencast
![logo white](https://user-images.githubusercontent.com/1199534/28539514-87c20ed2-70e4-11e7-9498-357f04bdba72.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment]
we should not be using a png image here

**Comment by fnisen** [comment]
Logo positioning is not per design; it should be in the corner, as on this page: https://accounts.topcoder-dev.com/connect. 

@gondzo just FYI: I asked @sirakovaDimitrina to fix it earlier on this issue: https://github.com/appirio-tech/connect-app/issues/1003. In general, we need logo cleanup on a few "logged out" pages, including the spec page. So, we can just fix this one as a one-off and have Didi do the rest or have her do the full cleanup.

**Comment by vic-topcoder** [comment]
the background doesn't match the latest design as well.

**Comment by vikasrohit** [comment]
@fnisen I think we can close it as we are already dealing with logo issues in #1003

**Comment by fnisen** [comment]
Fair point, closing.
