### ISSUE TITLE
Redundant presence of 'Project Estimates' on Project utline panel for Other Design project

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1002]
### Expected behavior
Any field which doesn't have any significance or usage in that particular page, should be removed.For 'Other Design' project option, there are no option to reflect any value for 'Project Estimate'.Hence, 'Project Estimate' should be kept hidden for 'Other Design Project'

### Actual behavior
Unnecessary presence of 'Project Estimate' details in Project Outline panel for 'Other Design Projects'.

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com.
- Click 'Start a Project'.
- Chose 'Other Design Project'.
- Observe & try to identify any relevance of 'Project Estimate' in Project Outline.

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/20595047/28539516-93fc98bc-70cf-11e7-8b34-7344acd3dd0a.png)
![image](https://user-images.githubusercontent.com/20595047/28539522-980f9134-70cf-11e7-8fbd-25bb715f6948.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1
- User role (client, copilot or manager): Not Logged In
- Account used: -NA-

**Comment by gondzo** [comment]
I think this would just complicate the implementation with no actual benefit
@fnisen thoughts ?

**Comment by fnisen** [comment]
@gondzo not sure if you're for or against. I agree with the critique. Let's not have the estimate panel on projects that don't have fixed pricing. So currently the ones with pricing would be: 
- Wireframes
- Visual design
- Front-end prototype
Everything else we're still custom scoping.

**Comment by fnisen** [comment]
Working correctly, thanks.
