### ISSUE TITLE
Fix logo styling and position on "Welcome back" page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1003]
Logo on this page https://www.screencast.com/t/Rfbde2M0 is incorrect. 

All logged-out pages should follow the format for the logo shown here: https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fM0l0aWJ1WVpGZWs

Logo asset is here: https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fN1VNdTctVnVORG8

**Comment by fnisen** [comment]
Can you please edit the logo on all logged out pages, for example: http://connect.topcoder-dev.com/new-project, http://connect.topcoder-dev.com/new-project/visual_prototype

**Comment by sirakovaDimitrina** [comment]
@fnisen  Of course,

**Comment by vic-topcoder** [comment]
The page background isn't correct, seems like somebody did create .png from .svg assets

**Comment by fnisen** [comment]
@sirakovaDimitrina I'm not seeing this in Dev. 
![screen shot 2017-08-07 at 8 06 34 pm](https://user-images.githubusercontent.com/12552247/29054600-f460b6e8-7bab-11e7-92da-c895169fbb40.png)

Also, it looks like you added the color logo to the other pages. We need the black-and-white one please, from Vic's design.

**Comment by vikasrohit** [comment]
@fnisen @vic-topcoder are we good on this? I think we need black and white logo while it is color one which in place right now.

**Comment by fnisen** [comment]
@vikasrohit no, I don't see any fixes in dev still.

**Comment by vikasrohit** [comment]
Fixes are there. But they are not doing what we need. It is in fact hiding the Welcome Back! header. I have to fix the styles. @vic-topcoder Can you please share the latest design for this page?

**Comment by fnisen** [comment]
@vikasrohit logo and designs are here: https://drive.google.com/drive/u/0/folders/0B1LbmKnex41feUhoanRsdG10Qkk, although I don't see the specific design for that page. Please comment back if you need it.

**Comment by vikasrohit** [comment]
<img width="898" alt="screen shot 2017-08-14 at 7 24 00 pm" src="https://user-images.githubusercontent.com/2417632/29274733-6b272efe-8126-11e7-8291-28ae4475b285.png">


This is what I have right now in my dev. Let me know if that does not looks as per design. Please note I have used my own designing skills 😬 , so please feel free to suggest changes or let me know the design specs.

**Comment by fnisen** [comment]
@vikasrohit OK will bug Vic. It looks fine, but a few small things are off. Thanks for trying.

**Comment by fnisen** [comment]
@vikasrohit for this one, I'm not seeing your changes in Dev. Can you push them please? This is how the page looks currently: 

![screen shot 2017-08-22 at 9 58 17 am](https://user-images.githubusercontent.com/12552247/29577484-750e0546-8720-11e7-8c99-7b1ee27834b8.png)

**Comment by vikasrohit** [comment]
I don't remember adding two different versions of the page. Only thing that was different for logged in and logged out users, was the presence of close button when logged in. I am not sure when this change went through. My style changes are still not merged into dev yet.

**Comment by vikasrohit** [comment]
@fnisen I have synced both logged in and logged out views. Only differences are the presence of close button and missing white(actually it is very light gray) background in logged in view. The reason of missing background in logged in view is the modal overlay which using the same color as of that box which has that light gray background logged out view. So, it is not differentiable in logged in view. I am also merging the changes in dev now.

**Comment by vikasrohit** [comment]
Changes should be in dev now.

**Comment by fnisen** [comment]
Thank you--looks good.
