### ISSUE TITLE
Long Project Name Fills entire Navigation Layout hiding Dashboard,Specification, Messages and Account Tabs 

### ISSUE THREAD

**Issue by m-prabhu** [appirio-tech/connect-app#1005]
### Expected behavior
Project Specification Page Top Navigation banner should show Project Name along with Navigation components like Dashboard, Specification,Message and Account Tabs.

### Actual behavior
Long Project Name occupies entire navigation banner and make other Navigation elements ( Dashboard, Specification,Message and Account Tabs) invisible

### Steps to reproduce the problem
- goto https://connect.topcoder-dev.com
- click start a project
- select 'software development'
- provide a long project name like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and save the project
- Fill remaining details and create a project
- while registration stage login with detials 'pshah_customer/topcoder123'
- project will be created and project specification will be displayed.
- As shown in attached screenshot, the project name will fill the entire navigation pane make other Navigation elements ( Dashboard, Specification,Message and Account Tabs) invisible
  

### Screenshot/screencast
![selection_042](https://user-images.githubusercontent.com/30400318/28539880-e09796e4-70d0-11e7-87a3-9bcb6be9c2dd.png)
![selection_044](https://user-images.githubusercontent.com/30400318/28539898-eefe0b78-70d0-11e7-96bf-8ad0aab53536.png)

--

#### Environment
- OS:Windows 7 32 bit
- Browser (w/version): Firefox 54, Chrome 59
- User role (client, copilot or manager):customer
- Account used: pshah_customer/topcoder123

**Comment by vic-topcoder** [comment]
That's an extreme case - nobody creates a project with a single word of 300characters. I'd say out of scope for that case, but long names should scroll into the input.
