### ISSUE TITLE
Password field is not clearing out when user enter invalid password

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1009]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login'

- Scroll the page (important)

- Enter username as 'pshah_manager' and password as '4234234324'

- Click Login

Actual Result(s)
-----------------------------------------------------------------
- Password field is not clearing out when user enter invalid password

Expected Result(s)
-----------------------------------------------------------------
- Password field must clearing out when user enter invalid password

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2Fconnect.topcoder-dev.com%2F

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![14](https://user-images.githubusercontent.com/4592712/28540227-24f8456c-70d2-11e7-9763-ad4b239ca7ac.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):**  Non Logged in
- **Account used:** N/A

**Comment by fnisen** [comment]
Should have commented on this sooner, but I don't think clearing is good UX, as mentioned here: https://github.com/appirio-tech/connect-app/issues/1013. If a user has a long password and makes a typo, it should be easy for them to fix their mistake. 

@sdgun please let me know if you have a good counterargument; otherwise I'd like to revert this change. (Will still give credit for the original bug, b/c I didn't catch this sooner).

**Comment by sdgun** [comment]
@fnisen better to clear the password field if the password is completely or partially wrong when triggering the login button 

1. User won't need to clear the invalid password, because there is no clear button for the password field
2. Most of the websites do clear the password field if it is wrong. I think it is a feature if we convert the text field into password field
2. If password partially wrong/typo your point is also correct specially for mobile devices; if it is a device with keyboard user can easily type the password again (because this login page has the show feature)

https://stackoverflow.com/questions/6540615/should-password-fields-retain-their-values-if-a-form-does-not-pass-validation

> The answers submitted by @NickHeidke and @Chris Lively were both great and led me to a few conclusions that I would like to share.
> 
> First of all, regarding usability: the ONLY place where it might be appropriate for a password field to retain its value is on a "sign-up" form, when the form does not pass validation, and the validation issue is NOT related to the password or confirm password. It is definitely not appropriate for a "log-in" form, "change password" form, or probably any other place. Therefore, the fact that Html.Password ignores the ModelState makes perfect sense.
> 
> Second, regarding security: unless carefully implemented, a "sign-up" form will be saved in your browser's navigation history. Pressing "Back" will resend your password, which would probably fail validation, and return the form with your password filled out. The fact that the password is filled out is NOT a security breach though, because its the same password that the browser already saved and sent. You can "View Source" to see the password, but you could view the page request to see the password too (for example, using FireBug).
> 
> Granted, it is easier and more obvious to "View Source" when you see a password filled out, but I'd say the better solution is implementing the "sign-up" form in a way that isn't saved to browser history; for example, the PRG Pattern with a Validation workaround, but that is a whole different topic!
> 
> My conclusion is this: password fields should almost always be clear when shown. If you want to increase usability and don't want to make users retype their passwords, try to use client-side validation first! And finally, if you really know what you're doing, and really want to increase usability, it's ok to persist the values on a sign-up form. But it probably isn't the best idea.


https://ux.stackexchange.com/questions/39999/why-do-most-create-account-forms-clear-the-password-fields-upon-wrong-validation

**Comment by fnisen** [comment]
@sdgun good points, thanks for taking the time. 

@vikasrohit how does this work behind the scenes? Do we store the password locally in order to show it after failed validation? Is this a security risk?

**Comment by vikasrohit** [comment]
@fnisen we are not storing password locally. Its in the angular's internal model which is rendering the values. And as we are not doing any direct form post, instead we are posting via ajax request, I don't think it would cause form post when hitting back button. Even reloading the same page again does not cause any form submission. I guess its only matter of clearing angular's model after such API calls, if we do not want to pre fill the password. 
I don't see any major security issue here. Its user's machine and he can see any details using firebug.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Can you please update so that we don't clear the password form? Discussed the UX with Vic, and he agrees.

**Comment by vikasrohit** [comment]
Done. Changes should be in dev.

**Comment by fnisen** [comment]
Nice, thank you.
