### ISSUE TITLE
General: "Walkthrough" page not working

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#101]
I logged in as a completely new user and saw the "No results" state below. But, I'm supposed to be seeing the "Walkthrough" page that was implemented as part of this challenge (design below): https://www.topcoder.com/challenge-details/30055089/?type=develop

![screen shot 2016-09-15 at 3 54 35 pm](https://cloud.githubusercontent.com/assets/12552247/18570245/29c637c2-7b5d-11e6-9f3b-3d20268f8802.png)
![f18d7946-8ca9-4132-8755-b92b357a5ebb](https://cloud.githubusercontent.com/assets/12552247/18570274/5a334062-7b5d-11e6-820e-55642dde61ab.png)

**Comment by mahestro** [comment]
Yeah! Right now it's not hooked in the projects page, just as demo if you go directly to projects/walkthrough. I don't think it was implemented. Doesn't seem difficult though, using the project lenght/count to determine wether to show the walkthrough or not.

I can take it if the code gods won't oppose or have a different approach :) @vikasrohit @parthshah

**Comment by parthshah** [comment]
All yours... :) !
Is this for all user role types or just customers?

**Comment by mahestro** [comment]
True! This beautiful walkthrough seems tailored for customers, a friendly experience. I'm not sure if copilots are going to be creating projects in a daily basis actually. Please chime in @fnisen :)

**Comment by fnisen** [comment]
Good points guys.... 

1. This screen is intended for "first time" customer users (copilots or managers would get training). We don't want them to get into the app and wonder what to do... this is our "light touch" onboarding for now. So, let's display it only for the customer role and before the customer has any projects. If they've already created a project or been added to a project, we should just show the project listing (and, once it's built, the project card view)
2. It should not replace "no results" when a user has explicitly run a search. So, if a user goes to the search bar, initiates a search, and they don't have any projects or don't have any results, we should still show "No results." However, their default view, whenever they go back to "Projects," should be the walkthrough screen and not the Project Listing, until they actually have projects.

**Comment by fnisen** [comment]
@mahestro on a related note, can you please set the default URL for users with projects to be /projects? Otherwise they're currently seeing a blank screen.

**Comment by mahestro** [comment]
Ok.
