### ISSUE TITLE
'Create New Account' form allows special symbols & numbers in name

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1014]
### Expected behavior
First and Last name should only allow alphabets.Symbols should definitely be taken care of through validation.

### Actual behavior
First & Last name fiels allowing 'Symbols' and 'Numbers' to enter.

### Steps to reproduce the problem
- Go to url https://accounts.topcoder-dev.com.
- Start a project.
- Select any project.
- Fill the details and click 'Continue'.
- Try entering symbols and numbers in first and last name of newly opened window to create an account.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28541627-510c25e2-70d7-11e7-9bdc-310115ce8867.png)
![image](https://user-images.githubusercontent.com/20595047/28541648-67c3a184-70d7-11e7-8ace-57a783bdb8ba.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Firefox 54.0.1, Chrome Version 59.0.3071.115
- User role (client, copilot or manager): Not logged in
- Account used: -NA-

**Comment by chq-matteo** [comment]
Relevant
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
https://softwareengineering.stackexchange.com/questions/330512/name-validation-best-practices

**Comment by gondzo** [comment]
Agree, but I'm not sure if there are any validations for this in backend.
@fnisen any ideas ?

**Comment by fnisen** [comment]
@gondzo we don't do any name validation, except for lengths (64 characters); it's impractical to figure out an appropriate format, especially with our user base, as the articles @chq-matteo linked show (thanks for chiming in!). I wouldn't accept this as a bug unless there's justification for the type of validation we need.
