### ISSUE TITLE
Country drop down is too big to handle

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1015]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register new account

- Type 's' and it will expand the country drop down

Actual Result(s)
-----------------------------------------------------------------
- Country drop down is expanding too big

Expected Result(s)
-----------------------------------------------------------------
- Country drop down is too big so must have default 10-15 visible and all the others must access via a drop down with scroll bar

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2Fconnect.topcoder-dev.com%2F

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![15](https://user-images.githubusercontent.com/4592712/28541959-4b2f772c-70d8-11e7-88c7-c3a32c0e15f9.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):**  Not logged in
- **Account used:** N/A

**Comment by sdgun** [comment]
![2017-07-25_9-28-30](https://user-images.githubusercontent.com/4592712/28555170-ab15a5c4-711b-11e7-915e-d6ca20eb8d64.jpg)

**Comment by sdgun** [comment]
https://www.screencast.com/t/ynjEeiIBBuO

**Comment by fnisen** [comment]
Hmm... component is now bumping the Register button. @vic-topcoder what's the right way to handle this? 

![screen shot 2017-08-01 at 6 25 24 pm](https://user-images.githubusercontent.com/12552247/28853646-da521b58-76e6-11e7-9301-bfeeb125e14e.png)

**Comment by vic-topcoder** [comment]
Auto-suggest should provide you with a space big enough to find the data. The drop-down can have a scroller to accommodate additional results. We should use a consistent component for all cases that behaves the same; in our case that is [React Select](http://jedwatson.github.io/react-select/). 

What is the component used in that case? It seems like some sort of wrong HTML/CSS rules to me.

**Comment by fnisen** [comment]
@gondzo can you please update the component?

**Comment by gondzo** [comment]
that's for react, accounts app is in angular.
what is exactly wrong with the styling of the dropdown ?

![image](https://user-images.githubusercontent.com/3051646/28898521-b0c38b9a-77e6-11e7-8f71-eef22cae6002.png)

**Comment by vic-topcoder** [comment]
The drop-down is not displayed over the components, but pushes them - it is displayed as inline/block instead of absolutely positioned element (that covers other elements).

**Comment by vic-topcoder** [comment]
or just looks like it, but the drop-down ending at the Register button is super wired - I'd extend the dro down to use more of the usable space

**Comment by gondzo** [comment]
nothing gets pushed down. it has a max-height of 300px. Change to 350 to cover the register button as well ?
![image](https://user-images.githubusercontent.com/3051646/28898892-7ae0d918-77e8-11e7-9e75-e9d70b8cb258.png)

**Comment by vic-topcoder** [comment]
Yeah, that looks better. Thank you.

**Comment by vikasrohit** [comment]
Just for information, we already have a [issue](https://github.com/appirio-tech/connect-app/issues/137) for replacing the dropdown component, with react-select, in connect app.

**Comment by fnisen** [comment]
Thanks all.
