### ISSUE TITLE
Continue button is disabled after restoring session even when the required fields and selection are already filled up.

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1016]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com 
Click Start a project  
Select any project type  
Fill up all the details until Continue button is enabled.
Close the page
Go to https://connect.topcoder-dev.com or restore closed page
Click Start a project
Click 'Continue where I left off' to restore session
Notice the Continue button

### Expected behavior  
The Continue button should be enabled since all the fields and selection are all filled up.

### Actual behavior  
The Continue button is disabled from the restored session. It only gets enabled when you add a new character or change the existing one. If you delete and retype the values the button would still be disabled as if the restored values are invalid.

### Screenshot/screencast
https://youtu.be/Ab42YsNQtJk

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by fnisen** [comment]
Working correctly now, thanks.
