### ISSUE TITLE
Country field filters all result containing with the typed letter instead of country that only begins with the typed letter.

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1017]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com 
Click Start a project  
Select any project type  
Fill up all the details until Continue button is enabled.
Click Continue
In the registration page type 'y' in the Country field and wait for the dropdown results
Observe the result

### Expected behavior  
The result should only filter countries beginning with the typed letter (in this case 'y') so that the user can locate his/her selection faster.

### Actual behavior  
The textbox shows all countries containing the typed letter which requires the user to type more instead of just clicking on the filtered result by just typing one letter.

### Screenshot/screencast
![country](https://user-images.githubusercontent.com/1199534/28553050-30d5544a-7124-11e7-8640-5f6c11e37fd4.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by fnisen** [comment]
@macs054 @gondzo should have commented earlier, but I disagree with the original bug. Yes, the list is overly long, but in the current implementation, I can't find certain countries. For example, try typing "Republic" into the country form. Nothing comes up now. Yet there are dozens of countries that start with "Republic of..." Same happens with countries with compound names. If I type in "Tobago," I get nothing. Compare the fix we've implemented with the original component here: https://accounts.topcoder.com/member/registration.

**Comment by chq-matteo** [comment]
@fnisen tag me when you decide if keep this or roll back
Screenshot of the pitfall (they don't start with what the user would expect)
![2017-08-02](https://user-images.githubusercontent.com/6654800/28858782-566d0a06-7753-11e7-80ef-c3935ff7cb4d.png)

**Comment by fnisen** [comment]
@chq-matteo Yeah, I see the issue, but at least they can find the country. Can we use this component instead: http://jedwatson.github.io/react-select/

cc @gondzo

**Comment by gondzo** [comment]
@fnisen rolled back the country search feature

**Comment by fnisen** [comment]
Thank you.
