### ISSUE TITLE
Clear button does not close the dropdown result in IE11

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1018]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com 
Click Start a project  
Select any project type  
Fill up all the details until Continue button is enabled.
Click Continue
In the registration page type 'y' in the Country field and wait for the dropdown results
Click the 'x' button to clear textbox

### Expected behavior  
The dropdown result should close after clearing the text

### Actual behavior  
The dropdown result stays even after clearing the textbox.

### Screenshot/screencast
https://youtu.be/51xnZsiHNiI

#### Environment
- OS: Windows 10 Pro
- Browser: Edge 38.14393.0.0, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment]
clear button is an IE/Edge feature
