### ISSUE TITLE
Project Listing: redesign

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#102]
Add project ID as primary column, move type as tag under the title, move cost.

**Comment by vic-appirio** [comment]
![264df700-ce0c-4696-aec8-bcb39162688e](https://cloud.githubusercontent.com/assets/8484061/18697347/2ae1a2ec-7f75-11e6-93db-3cb747ebce51.png)

We discussed the updates to the list view. It makes sense to expose the project ID at the first column, then move the project type as a tag underneath the title, and remove the REF code from the end of the table. The project ID would be more than enough to figure out the project in question. If we have a Reference code, we would display it underneath the title, after the project type. Those changes are minimal, but increase the scalability of the projects and allow for better use of white space.

https://drive.google.com/drive/folders/0B1LbmKnex41fZ2s3VkI4bGk3OHM?usp=sharing

**Comment by parthshah** [comment]
@mahestro can we run an F2F for this?

**Comment by fnisen** [comment]
@parthshah one question: with this redesign, can we make the reference code searchable? It doesn't make sense the way it is currently (sortable in its own column) because we don't have any restrictions for the code's syntax.

**Comment by fnisen** [comment]
We don't need this until after the beta, I think. Let me know if you disagree.

**Comment by parthshah** [comment]
Let's tackle project search functionality after beta. We can make name, description, ref code and any other field searchable through Elasticsearch

**Comment by vikasrohit** [comment]
@vic-appirio @fnisen I have noticed that the background color (blue) is same for all project types right now. I guess, we need different colors for different types, right?

**Comment by vikasrohit** [comment]
I have pushed my changes (only for styling) to dev. Please let me know your feedback. I may need to cross check margin-padding with specs, however, other than that it should include all changes.

**Comment by fnisen** [comment]
Thanks @vikasrohit. A few comments: 
1. Yes, please add the colors for different project types
2. Also, can we highlight new projects with the blue side bar? (Vic has it for the first few projects in his design)
3. Rename "Project ID" to "ID"
4. For the sort ("Latest first"), take out "Name Z-A"

**Comment by vikasrohit** [comment]
2. How to determine which projects are new?
4. Okay, but didn't understand the reason of removing the Z-A sorting while we have A-Z sorting.

**Comment by vikasrohit** [comment]
Done. Changes are in dev with assumption that any project which was created in last hour(configurable), is considered as new project for showing the blue bar in the left.

**Comment by vikasrohit** [comment]
@fnisen @parthshah Can we close this one? IMO, we need changes in API for supporting that new criteria and we can handle that later.

**Comment by parthshah** [comment]
We don't support "new" project aka read flag. There is considerable work required on the API to support such a feature. We should tackle this as a future enhancement if required.
