### ISSUE TITLE
When user get back to the 'Select your project type' section again icons are loading

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1021]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start New Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Click 'Change Project Type' and observe the icons when loading

Actual Result(s)
-----------------------------------------------------------------
- When user get back to the 'Select your project type' section again icons are loading
- Console error displayed: Warning: Formsy: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

Expected Result(s)
-----------------------------------------------------------------
- Must not load the icons again and again when user go back to the 'Select your project type' section

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/new-project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![16](https://user-images.githubusercontent.com/4592712/28554665-5f3564c6-7118-11e7-9da7-d742f4c48516.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by fnisen** [comment]
I'm still seeing a reload. I don't think we're caching the icons.

**Comment by gondzo** [comment]
We're actually not caching any static resources (images, fonts, css). We should discuss what should be cached and how long. Maybe just enable caching for all items in src/assets for 24hrs ?
@fnisen @vikasrohit what do you think ?

**Comment by fnisen** [comment]
@vikasrohit I think this is related to the Cloudfront/S3 issue you found. I'll let you resolve this. I'm in favor of caching static resources, but am not sure about the best way to do it with our setup.

**Comment by vikasrohit** [comment]
Yes, I think it should be mostly resolved with caching resolution. Even with current implementation, I can see icons loading again very quickly once loaded. I think we can close this issue safely.

**Comment by fnisen** [comment]
Agreed.
