### ISSUE TITLE
'Continue' button activates even if only 'Project Name' is entered - Other Design Project

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1022]
### Expected behavior
Likewise in all project types, 'continue' button should get activated only on furnishing details like 'Project Name','Description','Goal','User' etc.

### Actual behavior
For 'Other Design Project', 'Continue' button gets activated even if only 'Project Name' is filled.

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com
- Start a Project.
- Chose 'Other Design' Project.
- Fill something in only 'Project Name' field.
- Scroll down to check the status of 'Continue' button.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28555028-b74668d4-711a-11e7-8b4f-1a9a5d908cb4.png)
![image](https://user-images.githubusercontent.com/20595047/28555035-be17a3ee-711a-11e7-8d5a-b7a903e274f6.png)
![image](https://user-images.githubusercontent.com/20595047/28555040-ca1543a4-711a-11e7-8377-60c670f18573.png)
![image](https://user-images.githubusercontent.com/20595047/28555046-cd2fa4f8-711a-11e7-90c9-76b4d5c4280e.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1
- User role (client, copilot or manager): Not logged in
- Account used: -NA-

**Comment by gondzo** [comment]
@fnisen what are the required fields here ?

**Comment by fnisen** [comment]
Good catch. "Ref code" and "Notes" are optional. Everything else is required. Our pattern has indeed been only activating the button if required fields are filled out.

**Comment by fnisen** [comment]
Functionally it's correct, but I'm seeing some consistently weird behavior for validation on all the fields. They will turn blue when a line of text is deleted and then turn red when I click out. I think they should be consistently red. @vic-topcoder? 

![screen shot 2017-08-01 at 6 07 03 pm](https://user-images.githubusercontent.com/12552247/28853297-6e0c63d8-76e4-11e7-8729-013e61aebb32.png)

**Comment by vikasrohit** [comment]
@fnisen It should be fixable quickly as we are explicitly overriding border styles for error elements when they have focus. @vic-topcoder If we always want to show error styles even if it is focused, please let me know.
On the other hand, accounts-app forms are not showing error state for the elements themselves even if they are NOT focused. So, we need to fix [that](https://github.com/appirio-tech/accounts-app/issues/151) as well based on our conclusion here.

**Comment by vikasrohit** [comment]
@vic-topcoder @fnisen  bump up

**Comment by vic-topcoder** [comment]
Good catch guys. Error fields should be always reflecting the error in all states. A focused field that has an error should have red outline. Only when the validation passes we should have a normal blue (active) outline. Applies to all instances.

**Comment by vikasrohit** [comment]
Fixed. @fnisen @vic-topcoder Please let me know if you still see such issues. If they exists, can we please create a separate issue for that so that we can better track it.

**Comment by fnisen** [comment]
@vikasrohit it's working correctly now, but I'm seeing a weird side-effect. When I delete the text in a field and the validation error comes up, the title of the question below will flicker on and off. It doesn't seem like it should be rerendered each time like this.

**Comment by vikasrohit** [comment]
@fnisen Can you please share a video of the effect? I am seeing okay except that it moves down to accommodate the validation error.

**Comment by fnisen** [comment]
@vikasrohit yes, here you are: https://www.screencast.com/t/pw3hoKcguD. Please watch the "Who are the users of your application?" line for the flicker.
