### ISSUE TITLE
Must have some space in between the error and controllers

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1023]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start New Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Fill all the required fields and click 'Continue'

- When the registration page comes fill all the required details without first and last name

- Click 'Register' and observe

Actual Result(s)
-----------------------------------------------------------------
- No space in between the error and controllers
- Check the error message ("Email address 'dilhani@qa.team' has already been registered, please use another one.") and the first and Last name fileds

Expected Result(s)
-----------------------------------------------------------------
- Must have some space in between the error and controllers

URL where the Bug Appears
-----------------------------------------------------------------

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![2017-07-25_9-35-09](https://user-images.githubusercontent.com/4592712/28555374-16e807a0-711d-11e7-95e6-da4e3e268e6e.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by vic-topcoder** [comment]
This is the old registration form, not the one we styled for Connect.

**Comment by fnisen** [comment]
@gondzo let's give credit for this b/c we might have reverted to the old form temporarily during the bug hunt, but this shouldn't be an issue now.
