### ISSUE TITLE
Can register a new user without first and last names

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1024]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start New Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Fill all the required fields and click 'Continue'

- When the registration page comes fill all the required details without first and last name

- Click 'Register' and observe

Actual Result(s)
-----------------------------------------------------------------
- Can register a new user without first and last names

Expected Result(s)
-----------------------------------------------------------------
- Must validate the first and last names before creating new user. Only one of the first or last name is required to identify the user if not can't identify the user at all

URL where the Bug Appears
-----------------------------------------------------------------

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![2017-07-25_9-38-30](https://user-images.githubusercontent.com/4592712/28555365-112933a2-711d-11e7-89b2-015268ea1efe.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by chq-matteo** [comment]
I think that this is not part of the connect platform
See
https://accounts.topcoder-dev.com/member/registration

**Comment by chq-matteo** [comment]
@gondzo missing url and the steps described refer to non existant items

**Comment by chq-matteo** [comment]
There is no

- start new project
- wireframe in dashboard
- create project
- continue
- registration prompt

![virtualbox_topcoder_30_07_2017_22_52_37](https://user-images.githubusercontent.com/6654800/28757082-cc07250a-757b-11e7-83e8-779a815c49f5.png)
![virtualbox_topcoder_30_07_2017_22_52_47](https://user-images.githubusercontent.com/6654800/28757083-cc0e3dfe-757b-11e7-81d6-e9acf40cafa7.png)
![virtualbox_topcoder_30_07_2017_22_53_05](https://user-images.githubusercontent.com/6654800/28757084-cc196846-757b-11e7-9a79-50a0cec72c04.png)
![virtualbox_topcoder_30_07_2017_22_53_29](https://user-images.githubusercontent.com/6654800/28757085-cc216c62-757b-11e7-92f6-ef4262028c59.png)

**Comment by gondzo** [comment]
looks like old connect UI got deployed to dev environment. I'll try to get the new one back asap.
You don't need the connect-app here. The goal is just to add validation to first&last name (non empty)

**Comment by fnisen** [comment]
Working correctly, thanks.
