### ISSUE TITLE
JS/HTML codes are allowed in the text fields

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1025]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start New Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Fill ("><script>alert("cookie: "+document.cookie)</script>) to all the required fields and click 'Continue'

- Login as Manager and create the project

- Check on the messages

Actual Result(s)
-----------------------------------------------------------------
- JS codes are allowed in the text fields

Expected Result(s)
-----------------------------------------------------------------
- Must restrict the JS codes are in the text fields if not it will convert the JS codes and display in text fields
- "><script>alert("cookie: "+document.cookie)</script>   --> ">!  (eg: https://connect.topcoder-dev.com/projects/1305)

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/projects/1305

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![2017-07-25_9-47-27](https://user-images.githubusercontent.com/4592712/28555553-5170a37c-711e-11e7-8170-a855ea7818f6.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Manager
- **Account used:** pshah_manager/topcoder123

**Comment by gondzo** [comment]
inputs are escaped by react so XSS isn't an issue here
