### ISSUE TITLE
[$20] 'Select your project type' page background color difference in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1026]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start New Project'

- Check the page background > gray; also can't see the circle in the icon

Actual Result(s)
-----------------------------------------------------------------
- 'Select your project type' page background color difference in IE11. It is gray color

Expected Result(s)
-----------------------------------------------------------------
- 'Select your project type' page background color must white and there is a gray circle around the icon

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/projects/?page=1&sort=createdAt+desc

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![21-chrome](https://user-images.githubusercontent.com/4592712/28555767-a374fd5c-711f-11e7-99a5-39a913a65ccd.jpg)
![21-ie11](https://user-images.githubusercontent.com/4592712/28555768-a3760968-711f-11e7-9851-ce47df2d85d3.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by mkesselaers** [comment]
Can I work on this one, please?

**Comment by gondzo** [comment]
this one is available for pickup

**Comment by kevinkid** [comment]
Still working on this one , might need help running it on windows . Am getting ReactHotAPI is not a function .

**Comment by kevinkid** [comment]
Yeah i cant finish this on time .

**Comment by mish24** [comment]
I want to work on this, not for the competition, just to get started with the project

**Comment by kevinkid** [comment]
Please give it a try and give updates on your progress @mish24

**Comment by mish24** [comment]
It's weird. Both the pages are showing the same gray background with no circle.

**Comment by gondzo** [comment]
Right, this might have been fixed by #1170
