### ISSUE TITLE
Project doesn't get created in mentioned case

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1027]
### Expected behavior
The newly created project should be listed on dashboard, if all project details are filled in logged-off mode but at final stage of 'Continue' with signing in as a 'Already existing user'. 

### Actual behavior
The project is neither created nor listed..

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com/.
- Start a Project.
- Chose wireframe project. (In example, project name given is 'Wireframe Project for sample')
- Fill all details and continue.
- On a new page generated after clicking 'Continue', go with 'Sign In' option for alreay user.
- Enter user credentials : username as 'pshah_customer' and password as 'topcoder123'.
- Look for a title of newly created project in a displayed dashboard.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28555870-1cb44f56-7120-11e7-9330-8f80394e825d.png)
![image](https://user-images.githubusercontent.com/20595047/28555882-2f572fa2-7120-11e7-9565-df74044b6877.png)
![image](https://user-images.githubusercontent.com/20595047/28555919-60ba27d4-7120-11e7-87e2-8247762744e4.png)

--

#### Environment
- OS: Windows8.1
- Browser (w/version): Firefox 54.0.1, Chrome Version 59.0.3071.115
- User role (client, copilot or manager): client
- Account used: pshah_customer

**Comment by gondzo** [comment]
I can't reproduce this
