### ISSUE TITLE
'Continue where I left off' button still displayed even user created project with those data

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1028]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start New Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Enter all the required data and click Continue

- Click Login and login as Manager

- It will redirect the page to the Project page

- Click + New Project

- Click 'Continue where I left off' button

- Chnage some data and create a project

- Click + New Project again and observe

Actual Result(s)
-----------------------------------------------------------------
- 'Continue where I left off' button still displayed even user created project with those data

Expected Result(s)
-----------------------------------------------------------------
- After creating a project with past data; system must clear the data so that user can starts with a new one

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/projects/?page=1&sort=createdAt+desc

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![22](https://user-images.githubusercontent.com/4592712/28556087-8eafa2b2-7121-11e7-8d79-d614908df080.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by sdgun** [comment]
https://www.screencast.com/t/eTngh66TX

**Comment by vikasrohit** [comment]
Known issue #965
