### ISSUE TITLE
'Login' and 'Register for Free' button hovering color issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1030]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login'

- Hover over 'Register for Free' button

- Click 'Register for Free' button

- Hover over 'Login' button

Actual Result(s)
-----------------------------------------------------------------
- When user hover over 'Login' or 'Register for Free' buttons color of the button won't turn into blue color

Expected Result(s)
-----------------------------------------------------------------
- When user hover over 'Login' or 'Register for Free' buttons color of the button must turn into blue color

URL where the Bug Appears
-----------------------------------------------------------------
http://accounts.topcoder-dev.com/connect
http://accounts.topcoder-dev.com/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![24 1](https://user-images.githubusercontent.com/4592712/28567932-b2792dc8-7151-11e7-928b-75f8fd5aff1a.jpg)
![24](https://user-images.githubusercontent.com/4592712/28567934-b29f440e-7151-11e7-8881-4b512ed23e6c.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by sdgun** [comment]
https://www.screencast.com/t/gU7GSldJd5k

**Comment by vikasrohit** [comment]
@fnisen @gondzo  I think we can close this. These buttons are intentionally made different than standard buttons.

**Comment by fnisen** [comment]
Yes, agree.
