### ISSUE TITLE
Change Connect front page to marketing page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1031]
@vic-topcoder what do you think about this as UX: 
- Redirect connect.topcoder.com to https://www.topcoder.com/about-topcoder/connect/
- Rewire all buttons on that marketing page to deep link to the project menu, so you start a project right away in Connect

**Comment by vic-topcoder** [comment]
In terms of content that page provides more information on what you're going to experience on Connect. Makes sense to provide a well structured portal for Connect and try to convert people through content. Our current landing page was put simply out of necessity for a logged in state. In that case landing on `connect.topcoder.com` without being logged in should do something - either redirect to the new marketing page, or display login window. I'm concerned about the redirects between domains and logged in/out state.

That's a deeper discussion than an issue on GitHub - I'll need more time to think about it.

**Comment by fnisen** [comment]
Yeah, agree... just opened this so we can track it as something to address eventually.
