### ISSUE TITLE
Email tips texts are wrapped in IE

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1032]
### Steps to reproduce the problem  
Go to https://accounts.topcoder-dev.com/connect/registration using IE
Click on the 'Your email' field
Take note of the text popup 'Email Tips' and observe its layout
Repeat the above steps using FF, Chrome or Edge
Compare the 'Email Tips' between IE and the 3 other browsers

### Expected behavior  
The Email Tips texts should not move next line until the end of the panel.

### Actual behavior  
The Email Tips text are wrapped and moves next line early.

### Screenshot/screencast
IE
![email](https://user-images.githubusercontent.com/1199534/28589688-bafb7806-71b1-11e7-87e2-857616203b9a.png)

FF, Chrome, Edge
![email other](https://user-images.githubusercontent.com/1199534/28589662-a57009a2-71b1-11e7-8733-fd36d844aab6.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment]
Wrapping isn't a problem. 
Font looks different though.

**Comment by sirakovaDimitrina** [comment]
@fnisen Different browsers have different between letter spaces.

**Comment by fnisen** [comment]
@sirakovaDimitrina @vic-topcoder I think the underlying issue may be how fonts are being served, as Vic mentioned here: https://github.com/appirio-tech/connect-app/issues/501

**Comment by sirakovaDimitrina** [comment]
@fnisen All the fonts are loading correctly.
![img_04082017_013132_0](https://user-images.githubusercontent.com/10530059/29046226-29c51c8e-7bcf-11e7-8aff-3c4d4a5dccd3.png)

**Comment by fnisen** [comment]
OK, thanks @sirakovaDimitrina. So you don't see any problems? Then we can close this ticket.
