### ISSUE TITLE
Other Design's Project Name field error message is empty

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1033]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com 
Click Start a project  
Select Other Design
Type anything in the Project Name field then delete all of it
Notice the error message

### Expected behavior  
There should be text in the error popup.

### Actual behavior  
The error popup is empty.

### Screenshot/screencast
![empty](https://user-images.githubusercontent.com/1199534/28590213-ee329946-71b3-11e7-9b34-d1df005e6434.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by fnisen** [comment]
Copy should read: "Please provide a name for your project" (not "to your project")

**Comment by vikasrohit** [comment]
@fnisen Updated the copy. changes should be in dev now.

**Comment by fnisen** [comment]
Working well. Closing.
