### ISSUE TITLE
Change project outline component to match design

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1038]
@vic-topcoder what was your original thinking for the "Project outline." This is how it looks in Dev: 
![screen shot 2017-07-25 at 1 48 11 pm](https://user-images.githubusercontent.com/12552247/28593072-02f67d4e-7140-11e7-8056-5d17d14514d9.png)

However, in your design, you had: 
![screen shot 2017-07-25 at 1 49 19 pm](https://user-images.githubusercontent.com/12552247/28593097-14def072-7140-11e7-9b15-83f69004d09e.png)

Did you want the "type", "size", and "work" rows?

**Comment by vic-topcoder** [comment]
Actually - I didn't want too much details. The whole point of the outline was to carry over a small preview of what you're building - title and description of the project, plus estimate. The repetition of details like type, size and work requested are secondary and I wouldn't show them. Furthermore, transitioning towards a fluid project structure, those properties are not important for the customer to see.

**Comment by gondzo** [comment]
@fnisen should we remove these as part of the bug bash ?

**Comment by fnisen** [comment]
@gondzo yes please. So, we only want the sections Vic mentioned (title, description, estimate). If there's no estimate for that project type, then we don't need to show that either.

**Comment by fnisen** [comment]
Styling is off. Please follow the spec here: https://drive.google.com/open?id=0B1LbmKnex41feUhoanRsdG10Qkk. Noticing two issues in particular: 
1. The project name shifts from being center-aligned to being left-aligned as it gets longer
2. There is too much blank vertical space between the title and description.

**Comment by vikasrohit** [comment]
Should we move it back to TODO or are we good with this?

**Comment by fnisen** [comment]
@vikasrohit still not done, so I'll shift to To-Do
