### ISSUE TITLE
Activation link sent to the email is not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1039]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register

- Enter valid data and register for an account

- Go to email and click on the activation link

Actual Result(s)
-----------------------------------------------------------------
- Activation link sent to the email is not working, it will load the page forever. If the process is a success user must display a message "Your account is activated" but in this case no message or info displayed

Expected Result(s)
-----------------------------------------------------------------
- Clicking on the activation link send to the email must work If the process is a success user must display a message "Your account is activated"

URL where the Bug Appears
-----------------------------------------------------------------

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![25](https://user-images.githubusercontent.com/4592712/28593492-18b10e46-71aa-11e7-99be-7186af4e5ac9.jpg)

Hi qatesttc, 
Thanks for joining Topcoder! Please confirm your email address and activate your account by clicking this link: 
 https://api.topcoder-dev.com/pub/activation.html?code=13JBUMSIJIT&retUrl=https://connect.topcoder-dev.com (https://api.topcoder-dev.com/pub/activation.html?code=13JBUMSIJIT&retUrl=https://connect.topcoder-dev.com) 
If you have any trouble with your account, you can always email us at support@topcoder.com. (mailto:support@topcoder.com) 
Regards, The Topcoder team 

If you didn't register for Topcoder, please ignore this message.

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by gondzo** [comment]
I don't get an enpty page, but it hangs on success page forever.
https://www.screencast.com/t/0UxNh2CULSo

**Comment by vikasrohit** [comment]
Activation link would not longer be sent to connect registered users. It would only contain activation code which user has to paste into PIN verification screen. fyi @fnisen

**Comment by fnisen** [comment]
Yes @vikasrohit is correct. This is a known issue, and I've already asked Sudo to fix it, but let's count it for the bug hunt. Assigning it to myself for tracking.

**Comment by fnisen** [comment]
Fixed. New template is active in Dev and email flow is working correctly.
