### ISSUE TITLE
'Update email and send a new PIN' button activated for an invalid email address

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1040]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register

- Enter valid data and register for an account

- Click Edit from the next screen to change the email address

- Enter 'dil2@qa'

- Check the 'Update email and send a new PIN' button

Actual Result(s)
-----------------------------------------------------------------
- 'Update email and send a new PIN' button activated for an invalid email address

Expected Result(s)
-----------------------------------------------------------------
- 'Update email and send a new PIN' button must not activated for an invalid email address

URL where the Bug Appears
-----------------------------------------------------------------
http://accounts.topcoder-dev.com/connect/pin-verification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![26](https://user-images.githubusercontent.com/4592712/28593696-f0baecda-71aa-11e7-9141-65f220f57bfb.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by fnisen** [comment]
@gondzo can you please verify that we're using the same validation rules as on the Registration form?

**Comment by vikasrohit** [comment]
@fnisen @gondzo I have cleaned up the email validations as per #1091. FYI, now it would validate the email availability even before user clicks on update button. So, the button would be disabled until user has entered a valid available email. Lets discuss in #1091 if this is not desired behaviour.

**Comment by fnisen** [comment]
Thanks a lot @vikasrohit! Yup, that's the behavior I would want.
