### ISSUE TITLE
'Email or password is required' should be 'Email is required'

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1042]
### Steps to reproduce the problem  
Go to https://accounts.topcoder-dev.com/connect/registration
Click Login
Click 'Reset your password here?'
In the Email field press space
Click Reset Password

### Expected behavior  
Error message should be 'Email is required'

### Actual behavior  
Error message is 'Email or password is required', it should just be 'Email is required'.
### Screenshot/screencast
![reset email](https://user-images.githubusercontent.com/1199534/28595299-e41b99dc-71c5-11e7-8ddd-95e3c85c1ea4.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by fnisen** [comment]
@gondzo this is not styled correctly. Can you please pass to Didi if needed?

**Comment by vic-topcoder** [comment]
The error message doesn't follow the UI Kit system as well. The message should be under the field to which it applies, and the filed should partake the appropriate style.

**Comment by gondzo** [comment]
@sirakovaDimitrina can you add the appropriate styling ?

**Comment by fnisen** [comment]
Here's the latest (incorrect) style I'm seeing: 

![screen shot 2017-08-03 at 10 09 16 am](https://user-images.githubusercontent.com/12552247/28938365-b9ed24fe-7842-11e7-9c83-35c56df132c8.png)

**Comment by sirakovaDimitrina** [comment]
@fnisen I can not the rename 'Email or password is required', to 'Email is required'.

**Comment by vikasrohit** [comment]
@sirakovaDimitrina I have changed the copy and fixed the styles as well.

@fnisen @vic-topcoder Email validations (required and a valid email) would be rendered against the field as per our style, however, whenever we get error from server it is shown at common place which is top of the form because we do not know which field has caused the server error or it might not be related to any field at all. And this common error place does not have red background box and I think it is across the accounts app right now. Please let me know if we want to style that common error similar to what we show against each field.

**Comment by fnisen** [comment]
@vikasrohit what's an example of a common error that would not be against the field? Seems like the only issues are around the email address itself--that it can't be found in our system.

**Comment by vikasrohit** [comment]
The common example is any server error, e.g. if API is down or there is any runtime error at API for the current input.

**Comment by fnisen** [comment]
Hmm... what happens on the other forms, such as Registration, when there is a server error? Does the message show up in a different place (i.e., not next to the form field)?

**Comment by fnisen** [comment]
@vikasrohit ☝️

**Comment by vikasrohit** [comment]
Yes, @fnisen. Even on registration page, if there is a server error it would be rendered at common place which just above the first form field.

**Comment by fnisen** [comment]
@vikasrohit OK, I see. Then please follow your recommendation and style the common error similar to what we show against each field.

**Comment by vikasrohit** [comment]
Changes should be in dev now.

**Comment by fnisen** [comment]
@vikasrohit styling is correct now, thanks. Can you please make one more update? Can you please use our generic copy for all the catch-all messages, similar as you did for Registration? Right now I'm seeing "Failed to fetch."

![screen shot 2017-08-23 at 5 32 57 pm](https://user-images.githubusercontent.com/12552247/29644218-40b5f2ae-8829-11e7-9984-60848044dca1.png)

**Comment by vikasrohit** [comment]
@fnisen Updated the common error message for forgot password, reset password and pin verification page as well. However, I haven't update the login page though because it would require some more changes to render the common error and I don't want to take a risk to breaking things as of now.

**Comment by fnisen** [comment]
Well done, thanks! One copy tweak: "We weren't able to send **a** reset link..."

**Comment by vikasrohit** [comment]
should be done in dev now.

**Comment by fnisen** [comment]
Looks good, thank you!
