### ISSUE TITLE
SSO login form is not centered in IE

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1043]
### Steps to reproduce the problem  
Go to https://accounts.topcoder-dev.com/connect/registration on IE
Click Single Sign On
Take note of the positioning of the form
Repeat the steps above using Chrome, FF, or Edge
Compare the positioning of the SSO form

### Expected behavior  
The login form should be centered.

### Actual behavior  
The login form is not centered like in other browsers.

### Screenshot/screencast
IE
![sso ie](https://user-images.githubusercontent.com/1199534/28596336-9c35d998-71ca-11e7-873f-82e0ea88c71e.png)

FF, Chrome and Edge
![sso other](https://user-images.githubusercontent.com/1199534/28596342-a0b6665e-71ca-11e7-815d-131e85341a00.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by sirakovaDimitrina** [comment]
@fnisen This page can not be found

**Comment by vikasrohit** [comment]
I think bug reporter pasted screenshots of two different URLs which looks same. However, I think the issue might still be there for /sso-login/ page as well.

**Comment by macs054** [comment]
Hi, I'm the one who reported the bug. It seems that the SSO button was totally removed from the login screen. But you can still access it here: https://accounts.topcoder-dev.com/sso-login/

**Comment by fnisen** [comment]
@vikasrohit please let @sirakovaDimitrina know if you want this fixed on the member side. We don't need it for Connect right now. Otherwise I'll close.

**Comment by vikasrohit** [comment]
If it is a quick fix, @sirakovaDimitrina can you please fix and close it? Otherwise, I think we can close it for now.
