### ISSUE TITLE
Privacy Policy's default font color is blue in SSO login page on FF

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1044]
### Steps to reproduce the problem  
Go to https://accounts.topcoder-dev.com/connect/registration on FF
Click Login
Click Single Sign On
Scroll down the page until you see the page footer with the Privacy Policy link
Take note of the Privacy Policy's font color when default and hovered.
Repeat the steps above in Chrome, IE, or Edge

### Expected behavior  
The Privacy Policy font color should be gray and should change to blue when you hover.

### Actual behavior  
The Privacy Policy font color is blue. When hovered it turns gray for a bit then changes back to blue.

### Screenshot/screencast
https://youtu.be/0bbRs-Tzdo4

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by sirakovaDimitrina** [comment]
@fnisen This issue is for old registration form

**Comment by fnisen** [comment]
@sirakovaDimitrina you're right, we've deprecated that page. I'll close this.
