### ISSUE TITLE
SSO page font styling is different from other browsers

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1045]
### Steps to reproduce the problem  
Go to https://accounts.topcoder-dev.com/connect/registration on IE
Click Single Sign On
Observe the styling of font in the whole page
Repeat the steps above using Chrome, Edge, or Firefox

### Expected behavior  
Font styling should be the same with other browsers.

### Actual behavior  
See screenshot for comparison
1. Has darker color
2. Font family is different
3. Font color is not gray
4. Has darker color

### Screenshot/screencast
IE
![ie sso fonts](https://user-images.githubusercontent.com/1199534/28597370-0558b1a2-71d0-11e7-9506-f51993b4d3b9.png)
Chrome, Edge, FF
![sso other](https://user-images.githubusercontent.com/1199534/28597320-d5f9f2c2-71cf-11e7-9934-737f938fd98f.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by sirakovaDimitrina** [comment]
@fnisen This issue is for old registration form

**Comment by fnisen** [comment]
@sirakovaDimitrina yes, same issue as for 1044. I'll close this. Thanks.
