### ISSUE TITLE
'Reset Password' text have single quotes in the title

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1046]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Reset your password here?

- Enter 'dil002@qa.team' > Reset Password

- Click the link of the email

- Check the opened page title > 'Reset Password'

Actual Result(s)
-----------------------------------------------------------------
- 'Reset Password' text have single quotes in the title

Expected Result(s)
-----------------------------------------------------------------
- No need to have single quotes in 'Reset Password' text 
- All the other titles won't have anything like this

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/reset-password?token=SgEyno&handle=dil44234324

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![28](https://user-images.githubusercontent.com/4592712/28602958-cf2e7c56-71de-11e7-937d-81b5a3f2cdd5.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by fnisen** [comment]
Also fixed by @vikasrohit with some copy changes on that page.
