### ISSUE TITLE
Asks for entering security PIN instead of asking "click on the activation link in your email" for email verification

### ISSUE THREAD

**Issue by meontechno** [appirio-tech/connect-app#1048]
### Steps to reproduce the problem

- Open URL https://connect.topcoder-dev.com

- Click on **Start a project**

- Choose website option and click on **Create project**

- Fill in all the project details and click on **Continue**

- Fill in your name, country, nickname, email, password and click on **Register**

- Now a page appears asking for security PIN that is supposed to be sent to the registered email address

### Expected behavior
After creating a project and filling in personal details for registration and click **Register**, It should display a message asking the user to click on the activation link sent to the email address for account activation

### Actual behavior
It asks the user to enter the security PIN sent to the email address. But there is an activation link sent to the email instead of the security PIN. 

### Screenshot/screencast
**_Page asking for entering security PIN_**
![pinsent](https://user-images.githubusercontent.com/24816337/28605274-933cba7c-7185-11e7-903b-cac5d2646780.PNG)

**_My email inbox_**
![emailverification](https://user-images.githubusercontent.com/24816337/28605326-e084b00a-7185-11e7-8865-e1cf511aa8e4.PNG)

**_After clicking on the activation link in the email_**
![activation](https://user-images.githubusercontent.com/24816337/28605410-658562d6-7186-11e7-9423-3389b5289890.PNG)

![creatingprojectsuccess](https://user-images.githubusercontent.com/24816337/28605413-703a1c3a-7186-11e7-8f78-1b68ce651ea6.PNG)

**Still the security PIN page remains as it is after refreshing**
![pinsent2](https://user-images.githubusercontent.com/24816337/28606027-c928e008-7189-11e7-805e-2eafe72576fa.png)

--

#### Environment
- OS: Windows 10 Home
- Browser (w/version): Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- User role (client, copilot or manager): 
- Account used: NA

**Comment by gondzo** [comment]
duplicate of #1041
