### ISSUE TITLE
'nickname' is displayed instead 'Username' in the registration page

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1049]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register for free

- Observe 'Pick a nickname'

Actual Result(s)
-----------------------------------------------------------------
- 'nickname' is displayed instead 'Username' in the registration page

Expected Result(s)
-----------------------------------------------------------------
- 'nickname' must rename to 'Username' to be consistant with other locations
- In the login page it is displayed as 'Username'

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![30](https://user-images.githubusercontent.com/4592712/28606292-de6d746e-71f3-11e7-8cf0-0bd303a5a766.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by fnisen** [comment]
Looks correct now. I believe @vikasrohit fixed this along with other copy changes on the form.
