### ISSUE TITLE
'Uncaught SyntaxError: Invalid or unexpected token' displayed when user click on Login

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1052]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login'

Actual Result(s)
-----------------------------------------------------------------
- 'Uncaught SyntaxError: Invalid or unexpected token' displayed in the console log and when user click on Login it won't load any content instead it will display a blank empty page
- Issue Happens: EDT 3:00 AM Wednesday 2017/07/26

Expected Result(s)
-----------------------------------------------------------------
- Must display the login page without any issue when user click on the 'Login' button

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/#!/connect?retUrl=https://connect.topcoder-dev.com/

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![31](https://user-images.githubusercontent.com/4592712/28608336-9ea832ec-71fd-11e7-807c-013cf097b675.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by sdgun** [comment]
https://www.screencast.com/t/c8snEMt4ne

**Comment by gondzo** [comment]
I can't reproduce it any longer.
@vikasrohit Could this have been related to the backend API issues ?

**Comment by vikasrohit** [comment]
This happened to me as well. It was due to a bad build been deployed to dev. I rebuild and deployed, it vanished. It was a temporary env issue.
