### ISSUE TITLE
Can register a new user without 'Country' field

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1053]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register for free

- Fill all the required fields

- Clear the country selection from the (x)

- Click Register button and observe

Actual Result(s)
-----------------------------------------------------------------
- Can register a new user without Country, but when user click Register without filling anything 'Country' field is recognized as a required field

Expected Result(s)
-----------------------------------------------------------------
- Must validate the 'Country' field before creating a new user

URL where the Bug Appears
-----------------------------------------------------------------
http://accounts.topcoder-dev.com/#!/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![33](https://user-images.githubusercontent.com/4592712/28623933-12ca0a9c-7235-11e7-8305-2ae3fde51c84.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:**  IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by sdgun** [comment]
https://www.screencast.com/t/iVIocKw9QJh

**Comment by rushikesh90** [comment]
@gondzo I am not sure what is expected here. Can you explain?

**Comment by gondzo** [comment]
Country field ahould be validated -not empty.

**Comment by rushikesh90** [comment]
Is the issue browser or OS specific because I cant find the X on chrome and ubuntu.

**Comment by gondzo** [comment]
It's IE11 issue. 
You can just hide the clear button in IE `::-ms-clear { display: none; }` or catch the clear event and update selected country field. Either is fine.
Also, when submitting the form validate the country isn't empty

**Comment by rushikesh90** [comment]
If country is empty , register button is disabled. Do you need any more validation?

**Comment by gondzo** [comment]
That is fine, no extra validation is needed

**Comment by vikasrohit** [comment]
@gondzo we have this type of issues in past as well. I think the best solution is to get rid of the X button for IE or any other browsers which have this additional behaviour for text boxes. These can be removed with browser specific css rules. We should apply the same fix every where we have such issues because of browser's X button.

**Comment by fnisen** [comment]
@gondzo I don't have IE 11. Can you please just verify that the "X" button is removed, as Vikas suggested? That's been our standard fix for this.

**Comment by gondzo** [comment]
The X icon is removed in IE11

**Comment by fnisen** [comment]
Thank you!
