### ISSUE TITLE
Some icons/arrangement are different from the provided prototype

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1058]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start a Project'

- Compare the icons with https://projects.invisionapp.com/share/QJBRJ4ITF#/screens/234311826 (Website, app, Front-end Prototype, 

1. Wireframes
2. Visual Design
3. Front-end prototype
4. Software development
5. Website
6. Infographic
7. App
8. Other design

Actual Result(s)
-----------------------------------------------------------------
- Some icons are different from the provided prototype
- https://projects.invisionapp.com/share/QJBRJ4ITF#/screens/234311826

Expected Result(s)
-----------------------------------------------------------------
- Icons must match with the provided prototype
- Arrangement must also match with the prototype

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/new-project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![34](https://user-images.githubusercontent.com/4592712/28611247-c5f68640-7208-11e7-942c-1f803b994448.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by gondzo** [comment]
@fnisen was updating the icons in scope ?

**Comment by fnisen** [comment]
@gondzo yes, in scope, so let's give credit, but no need to fix. Looks like we changed the order and the current one is correct. The icons are slightly different, but generally correct.
