### ISSUE TITLE
[$100] Error message is not displayed if user enters wrong PIN so many times

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1059]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register for Free

- Fill all the required data and click Confirm

- Once the PIN is requesting enter wrong PINs multiple times (10-20 times)

- Observe

Actual Result(s)
-----------------------------------------------------------------
- Error message is not displayed if user enters wrong PIN so many times

Expected Result(s)
-----------------------------------------------------------------
- Error message must display if user enters wrong PIN so many times ("Whoops, you entered the wrong PIN too many times. If you still can't get your PIN, please contact support@connect.com")
- This attempt must not exceed more than 3-5 attempts

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/pin-verification

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![34 1](https://user-images.githubusercontent.com/4592712/28624199-01096f86-7236-11e7-839d-17e408fefb5c.jpg)

https://www.screencast.com/t/FFFpEC0fW8VC

Expected Error message:

![34 2](https://user-images.githubusercontent.com/4592712/28624214-129dd9b2-7236-11e7-99de-9e0e8ea36159.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by gondzo** [comment]
@vikasrohit do we have support for this in API? did we drop this along the way ?

**Comment by vikasrohit** [comment]
Not as of now. We might have to put this in front end for now. @fnisen what is your opinion?

**Comment by fnisen** [comment]
Good point. Yes, we should have a block just so someone doesn't maliciously hammer the API. @vikasrohit I think we do have something like this for Password Reset, for example, where we lock you out for some time after 10 attempts. It's probably best to do this at the API level, so I should pass it to Sudo, right? We don't need it for the release, but would be good to add soon so we don't forget.

**Comment by vikasrohit** [comment]
Yes, ideal place for the check is in API.

**Comment by fnisen** [comment]
Can you work on this or does it need to be done by Sudo or Kohata-san?

**Comment by vikasrohit** [comment]
For API level changes, we need Sudo or Kohata-san.

**Comment by vic-topcoder** [comment]
The whole point of this lock is to make sure no brute-force attacks can happen. @mtwomey something to think about

**Comment by gondzo** [comment]
So the goal here is to add a limit for the number of wrong PINs ( 10 by default). When the limit is reached an error message will be displayed along with a back-off timer (countdown). When the timer expires, user can enter the PIN again.
@mtwomey Does this approach make sense ?
Also, we don't have a way to get to the pin verification page directly, so if the user closes the page before entering a valid PIN, the account will remain inactive forever and the email will not be available for new accounts.

**Comment by vikasrohit** [comment]
> Also, we don't have a way to get to the pin verification page directly, so if the user closes the page before entering a valid PIN, the account will remain inactive forever and the email will not be available for new accounts.

Yes, that is inherent in the flow and limited by API and security risks.

**Comment by gondzo** [comment]
@all Prize increased

**Comment by HammadSiddiqui** [comment]
I think this issue should have been a part of the accounts.topcoder repo

**Comment by mkesselaers** [comment]
I already submitted a PR against the accounts repo for this issue.
https://github.com/appirio-tech/accounts-app/pull/171

**Comment by gondzo** [comment]
@mkesselaers this looks good, but the backoff timer feature is missing.

> When the limit is reached an error message will be displayed along with a back-off timer (countdown). When the timer expires, user can enter the PIN again.

**Comment by mkesselaers** [comment]
@gondzo, OK, will prepare the change. I had based myself on the Expected Results from the initial ticket, instead of reading everything.

**Comment by gondzo** [comment]
Thanks

**Comment by mkesselaers** [comment]
PR has been updated.

**Comment by gondzo** [comment]
Looks good. Thanks.
