### ISSUE TITLE
Project listing: Long project names should be truncated in project lists

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#106]
![image](https://cloud.githubusercontent.com/assets/1987710/18641136/dca9c72e-7eb8-11e6-9143-aab60f8e16ea.png)
@mahestro assigning this one to you. Hopefully we can use the same logic that was used for the nav bar.

**Comment by parthshah** [comment]
@vic-appirio @fnisen please correct me if I am wrong but the design calls for truncating the name? and not wrapping it correct? 
@mahestro - re-opening this bug. Quite okay if we need to use the community to fix this.

**Comment by mahestro** [comment]
Good catch @parthshah, it was a quick fix to make it look good. The design has one line, I fixed it.

https://gyazo.com/1fcc6dfeb7d2afa529d1ec63e62383a8

**Comment by parthshah** [comment]
💰

**Comment by vic-appirio** [comment]
Fixed in the PR #114
