### ISSUE TITLE
[$30] Paragraphs are not divided in the 'PROJECT OUTLINE' section for 'Description'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1064]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Login as a valid user: pshah_manager/topcoder123

- Click + New Project

- Fill all the required data

- Enter two paragraph description to the  'Description' section

- Check the 'PROJECT OUTLINE' section

Actual Result(s)
-----------------------------------------------------------------
- Paragraphs are not divided in the 'PROJECT OUTLINE' section for 'Description'

Expected Result(s)
-----------------------------------------------------------------
- Must divide the paragraphs in the 'PROJECT OUTLINE' section for 'Description'

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/projects/?page=1&sort=createdAt+desc

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![37](https://user-images.githubusercontent.com/4592712/28668980-de50786c-72ef-11e7-8be1-9b0d621d4776.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Manager
- **Account used:** pshah_manager/topcoder123

**Comment by sirakovaDimitrina** [comment]
In order to get space between the two paragraphs in the right section like in the left section you need to separate the text in separate paragraphs. The text now is in one box and this is why there is no space between the paragraphs. 
![screen shot 2017-08-02 at 11 16 49 pm](https://user-images.githubusercontent.com/10530059/28893196-36792a46-77d9-11e7-8d26-d5a70a4b72e3.png)
See attached file

**Comment by gondzo** [comment]
Changes merged.
