### ISSUE TITLE
Previous email address PIN code is accepted when user change the email address

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1066]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click Login > Register for free

- Fill all the required data

- Enter email as dil777@qa.team

- Now click edit and change the email as dil666@qa.team

- Now system will notify the email has changed and check the mail for the PIN

- Now copy and paste the PIN code for the previous mail (dil777@qa.team) and click Verify

Actual Result(s)
-----------------------------------------------------------------
- Previous email address PIN code is accepted when user change the email address

Expected Result(s)
-----------------------------------------------------------------
- Previous email address PIN code must not accept to the new changed email

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
https://www.screencast.com/t/5bSIHanRgL

Hi dil7777, 
Thanks for joining Topcoder! Please confirm your email address and activate your account by clicking this link: 
 https://api.topcoder-dev.com/pub/activation.html?code=**13JBVEPZ2OK**&retUrl=https://connect.topcoder-dev.com (https://api.topcoder-dev.com/pub/activation.html?code=**13JBVEPZ2OK**&retUrl=https://connect.topcoder-dev.com) 
If you have any trouble with your account, you can always email us at support@topcoder.com. (mailto:support@topcoder.com) 
Regards, The Topcoder team 

If you didn't register for Topcoder, please ignore this message.

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by gondzo** [comment]
this should be fixed in backend API. change of email address should result in a new token being sent.
@fnisen

**Comment by fnisen** [comment]
@vikasrohit would this go to you or Sudo?

**Comment by vikasrohit** [comment]
@fnisen I think it would be Sudo. However,  I think we are sending the same PIN to new email address as well.

**Comment by fnisen** [comment]
Turns out the behavior is according to the service design, so will close this one.
