### ISSUE TITLE
Even though user deleted the email address from the change email page; still the account is verified

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1067]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click Login > Register for free

- Fill all the required data

- Enter email as dil444@qa.team

- Now click edit and delete the email

- Now copy and paste the PIN code and click Verify

Actual Result(s)
-----------------------------------------------------------------
- Even though user deleted the email address from the change email page; still the account is verified

Expected Result(s)
-----------------------------------------------------------------
- Must check the email field before verification; if user deleted the email must validate the email field before continue

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![38](https://user-images.githubusercontent.com/4592712/28670246-7616b076-72f5-11e7-94b5-fa54952ca753.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by sdgun** [comment]
https://www.screencast.com/t/1UTgmMgP6

**Comment by gondzo** [comment]
We are sending the same activation code to both addresses

**Comment by gondzo** [comment]
will be handled by #1066
