### ISSUE TITLE
[$400] New project screens

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1071]
This is a placeholder issue for a bug bash to track related issues.

Fixing all of the following bugs is in scope
- [x] #981
- [x] #983
- [x] #992
- [x] #1001
- [x] #1002
- [x] #1016
- [x] #1021
- [x] #1022
- [x] #1033
- [x] #1038

**Comment by shizhouxing** [comment]
Please assign this ticket to me, thank you.

**Comment by shizhouxing** [comment]
@gondzo The issues in this ticket are now ready for review.

**Comment by gondzo** [comment]
thanks. I'll review them shortly. In the meantime, you can work on other issues.

**Comment by shizhouxing** [comment]
@gondzo Any feedback on this ticket? I see that two of my PRs were closed.

**Comment by gondzo** [comment]
all the fixes have been merged, and the ticket is marked as accepted.
