### ISSUE TITLE
[$180] Login screens

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1072]
This is a placeholder issue for a bug bash to track related issues.

Fixing all of the following bugs is in scope
- [x] #1009
- [x] #1013
- [x] #1042
- [x] #1046
- [x] #1047

**Comment by chq-matteo** [comment]
#1042 is an issue with topcoder dev api 
request
```
https://api.topcoder-dev.com/v3/users/resetToken?email=&resetPasswordUrlPrefix=http%3A%2F%2Flocalhost%3A3100%2Fconnect%2Freset-password
```
response
```
{"id":"-3b6efae:15d7a37286a:5d84","result":{"success":true,"status":400,"metadata":null,"content":"Email or password is required"},"version":"v3"}
```
### Workaround
We could make an adhoc check, but...

**Comment by chq-matteo** [comment]
https://github.com/appirio-tech/connect-app/issues/1009
Clear password on failed login
![password](https://user-images.githubusercontent.com/6654800/28748352-e5f096c0-74b5-11e7-8c22-21fb03f2bf15.gif)

https://github.com/appirio-tech/connect-app/issues/1013
Notice that username is wrong when empty
![virtualbox_topcoder_29_07_2017_22_11_13](https://user-images.githubusercontent.com/6654800/28748244-13710bdc-74b3-11e7-9339-fe3c397fe9e4.png)

https://github.com/appirio-tech/connect-app/issues/1042
Issue with api server, in the app we just print out the error message from the server

https://github.com/appirio-tech/connect-app/issues/1046
Reset password quotes
![virtualbox_topcoder_29_07_2017_23_31_47](https://user-images.githubusercontent.com/6654800/28748361-2c5e1646-74b6-11e7-885e-4f3c86e79fca.png)

https://github.com/appirio-tech/connect-app/issues/1047
Redirection / Intermediate page
![interim](https://user-images.githubusercontent.com/6654800/28748271-bfb0ebce-74b3-11e7-944d-037120d3cebf.gif)

**Comment by chq-matteo** [comment]
@gondzo for #1042 the issue is with the topcoder api server, we could check if the error message is 'email or password...' and change it ourself
for #1047 it seems to me that there's no interim page

**Comment by chq-matteo** [comment]
@gondzo I made a pull request on `appirio-tech:feature/copy-change-pin-verification`

**Comment by gondzo** [comment]
for #1042, just validate the field before submitting the form. We'll update the error message in backend separately

for #1047 I can still see it in dev - https://connect.topcoder-dev.com
Can you make pull requests to dev, that is the one currently deployed and up to date.

**Comment by chq-matteo** [comment]
@gondzo 
1. Ok
2. I'm pretty sure it is not dev branch for the accounts-app repository (http://accounts.topcoder-dev.com)

**Comment by gondzo** [comment]
OK, I'll double check the correct branch

**Comment by chq-matteo** [comment]
fixed #1042 
![virtualbox_topcoder_30_07_2017_11_07_54](https://user-images.githubusercontent.com/6654800/28752074-683f8f9e-7517-11e7-8143-1deb29cd53d3.png)

**Comment by chq-matteo** [comment]
@gondzo I looked into #1047, that 'page' is actually a view that autohides when the requested page finish loading, it is not a redirect. I think it was put there to give immediate feedback to the user. I can remove it if you want, but it does serve a purpouse I think

**Comment by gondzo** [comment]
yes, please do remove it, but pay attention not to break community login pages (/member)

**Comment by chq-matteo** [comment]
So it will be visible only on /member pages and not /connect pages, right?

**Comment by gondzo** [comment]
right, the community pages should not be changed.

**Comment by chq-matteo** [comment]
https://github.com/appirio-tech/accounts-app/pull/141
