### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1074]
This is a placeholder issue for a bug bash to track related issues.

Fixing all of the following bugs is in scope
- [x] #974
- [x] #975
- [x] #979
- [x] #984
- [x] #987
- [x] #988
- [x] #989
- [x] #990
- [x] #994
- [x] #998
- [x] #1003
- [x] #1005
- [x] #1020
- [x] #1023
- [x] #1026
- [x] #1029
- [x] #1030
- [x] #1032
- [x] #1042
- [x] #1043
- [x] #1044
- [x] #1045
- [x] #1050
- [x] #1062
- [x] #1063
- [x] #1064
- [x] #1092

**Comment by vic-topcoder** [comment]
All issues fixed or non-relative anymore
