### ISSUE TITLE
Copy changes for new "Log in" page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1085]
### Current page
![screen shot 2017-07-25 at 2 47 53 pm](https://user-images.githubusercontent.com/12552247/28793081-ab3447fc-75e6-11e7-8eb7-7d93f7430227.png)

### Changes
1. Headline should be: "Log in to Topcoder"
2. Remove sub-headline ("Crowdsourcing for your winning project")
3. For the reset instructions, change to: "Forgot your password?" (link). Remove the rest.
4. Change button to: "Log in" (two words)

**Comment by vikasrohit** [comment]
Done

**Comment by fnisen** [comment]
Looks good, thank you.
