### ISSUE TITLE
Copy changes for new "Reset password" page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1086]
### Current page
![screen shot 2017-07-25 at 2 48 10 pm](https://user-images.githubusercontent.com/12552247/28793515-0ba73422-75e8-11e7-95b7-86c6e73c6d53.png)

### Changes:
1. Change headline to: "Reset your password"
2. Remove subheadline "It's ok, happens to all of us"
3. Change button to: "Get reset link"
4. Change help copy to: "Enter your email address, and we'll send you a link to reset your password. If you don’t see an email from us right away, wait for a few minutes or check your spam folder. If you don’t receive a message or need help with your account, please contact support@topcoder.com."

**Comment by vikasrohit** [comment]
Done. Should on dev now.

**Comment by fnisen** [comment]
Perfect, closing.

**Comment by vikasrohit** [comment]
Done.
