### ISSUE TITLE
Auto-login user after password reset in Connect

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1087]
Currently, when a user sets a new password (after clicking the reset link), we show a green dialogue on the page saying "Logging you in...". However, the user is then taken back go the Login page, rather than being logged into Connect. This is where they end up: 

<img width="581" alt="screen shot 2017-07-31 at 2 31 14 pm" src="https://user-images.githubusercontent.com/12552247/28799314-f05bc240-75fc-11e7-9f4f-bf7a00fff3a4.png">

Can you please log them in automatically?

**Comment by vikasrohit** [comment]
@fnisen The behaviour you are seeing is the fallback way which I have implemented when we are facing issue in automatic login. So, it means there was some error while automatically login. I would check it again.

**Comment by fnisen** [comment]
@vikasrohit you're correct. It worked correctly this time. One note: "log in" in the above message should be two words. Can you please update?

**Comment by vikasrohit** [comment]
Done. Fixed other typo as well it was rendering 'Loggin you in...' instead of 'Logging you in...'. 😬

**Comment by fnisen** [comment]
Perfect, thanks.
