### ISSUE TITLE
Change "Back on Track" reset password confirmation

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1088]
@vikasrohit this page is not following the recent style changes. Who would be the one to fix this, you or Didi? 

![screen shot 2017-07-26 at 1 41 59 pm](https://user-images.githubusercontent.com/12552247/28799787-cfaa5b4a-75fe-11e7-9ba6-bc84b544ad6c.png)

**Comment by vikasrohit** [comment]
Didn't get it @fnisen. What exactly is not as per style? From DOM structure, it seems similar to other pages.

**Comment by fnisen** [comment]
@vikasrohit so you're using the form component, with "Back on Track!" as the headline and the rest of the message as the second-level headline? OK, I get it. 

Then, just two changes please: 
1. For the headline, write it as "Back on track" (sentence case, no exclamation point)
2. Put a period at the end of the sub-headline ("contact us at support@topcoder.com.")

Thank you.

**Comment by vikasrohit** [comment]
@fnisen Done the requested changes. However, just to clarify, the message is not second level heading actually. font size is same, however, color for second level headline is bit different. We have removed the second level headline from most of the screens except /reset-password screen.

**Comment by fnisen** [comment]
Got it, thanks.
