### ISSUE TITLE
Copy & functional changes for "Set password" page (after clicking reset link)

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1089]
<img width="1023" alt="screen shot 2017-07-31 at 12 30 57 pm" src="https://user-images.githubusercontent.com/12552247/28801121-db6b7a3a-7604-11e7-9dc8-121fd85702bf.png">

Would like a bunch of changes here: 
1. Remove "Log in" button in top right corner (not needed; user is the process of resetting password)
2. Change headline to: "Set new password" (remove quotation marks)
3. Change sub-headline to: "Create a new password for your account"
4. Add the password tooltip that we use on the Registration page to guide the user to have the right password; make sure the button activates only if the user passes validation
5. Change button to: "Set password."

**Comment by vikasrohit** [comment]
@fnisen Are changes described in #1086 different than this?

**Comment by vikasrohit** [comment]
Done. Should be there on dev.

**Comment by fnisen** [comment]
Perfect, closing.
