### ISSUE TITLE
Dashboard/Team management: UX for Member/Copilot role selection is confusing

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#109]
<img width="429" alt="screen shot 2016-09-19 at 5 43 45 pm" src="https://cloud.githubusercontent.com/assets/12552247/18653768/ed2a7e36-7e90-11e6-8319-5b7b3bd927bc.png">

Right now when I mouseover "Member" and "Copilot," both of them are shown as selectable, but only clicking on one of them (the grey one) actually changes the selection. @vic-appirio what is the UX here that you wanted?

**Comment by vic-appirio** [comment]
Gray one is selected (active); You should be able to click on the white one to select it. In the attached image, it is visible that Theo is a Copilot (being added as Copilot).

I wanted to allow managers only to select/modify the option of adding people while in team management. We decided that only Managesr and Copilots can use the switch. Once a member is added, in order to switch the user role you have to:
1. Remove user
2. Add user with the appropriate role

**Comment by fnisen** [comment]
Thanks @vic-appirio. 

@mahestro assigning to you to fix the UX to work as Vic is describing. Thanks.

**Comment by mahestro** [comment]
Hey @vic-appirio @fnisen about "We decided that only Managesr and Copilots can use the switch". Does it mean clients cannot add team members?

Also, off topic, comes to my mind, if a client wants to invite someone, this someone must have a tc account, if not he won't show up in the options. Is it planned to add member invitations by email? where they first register then they're automatically assigned to the team they were invited to.

**Comment by fnisen** [comment]
@mahestro clients can add, but they can't designate someone as a copilot. Anyone they add will be a regular project member. 

Yes, we're planning to add invitations by email--good note.

**Comment by fnisen** [comment]
@mahestro this is still not working correctly. Both grey and white parts are selectable.

**Comment by mahestro** [comment]
Hmm, strange. I see it working. I didn't fix it but I realized it was working when I was checking. I still see it working.

**Comment by fnisen** [comment]
Here is a video showing it not working: http://screencast.com/t/cywHpfWun. Please provide counterevidence if you have it. :)

**Comment by mahestro** [comment]
I see pat_monahan has a manager role. I was testing with all roles. Customers are the only ones who cannot set the new member as copilot/member, according to this from Vic "We decided that only Managesr and Copilots can use the switch" - unless this rule changed.
