### ISSUE TITLE
Sync email field validations with register page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1091]
Continuing the email validations cleanup from https://github.com/appirio-tech/connect-app/issues/1040#issuecomment-319530724

fyi @fnisen @gondzo

**Comment by vikasrohit** [comment]
Done.

**Comment by fnisen** [comment]
@vikasrohit the format validation works well. It's fast and the button activates/deactivates correctly. However, I'm seeing an issue with the email validation itself. There is a check on whether the email address is being reused, but it's delayed, so I can click the PIN button before the verification comes back. I'm able to get into a state like the screenshot below. "Currently we can't update your email" is the response b/c the email address is taken; "That email address is already taken" is what you get when the initial validation is completed. Also, "Currently we can't update your email" is sticky--it never goes away, even if I start editing the email address.  

Also, the "support@topcoder.com." link is missing from the copy below the button. 

![screen shot 2017-08-02 at 9 29 11 am](https://user-images.githubusercontent.com/12552247/28884168-ae88ac56-7765-11e7-9430-d790a23bf4d8.png)

**Comment by vikasrohit** [comment]
- Make the email check virtually instantaneous, if that's possible

Not possible because its an network call to validate the email availability. I can remove the this validation. In that case user would come to know about email being reused only after hitting the button.

**Comment by vikasrohit** [comment]
Done

**Comment by fnisen** [comment]
Yup, that works, thanks. @vic-topcoder this is another place where we'd need an inline loader b/c it's not clear right now that a check is happening.
