### ISSUE TITLE
create project in logged out state: not matching design

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1092]
Logged out project creation screens are not following the design. Must fix - background, spacing, footers, logo (and serving as a back button).

Current:
![i525 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/8484061/28893974-31418844-7788-11e7-9675-4ef4f4d89d75.png)
![i524 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/8484061/28893975-31501a58-7788-11e7-9d60-43f8837b1338.png)
![i526 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/8484061/28893976-3152e86e-7788-11e7-8349-5d14cd1b416a.png)

Expected:
![transitional-project-creation-spec-transitional-step1](https://user-images.githubusercontent.com/8484061/28894012-49086826-7788-11e7-8446-a114b07bd7e8.png)
![transitional-project-creation-spec-transitional-step2](https://user-images.githubusercontent.com/8484061/28894014-4c646b1e-7788-11e7-92ef-367572a68605.png)

The logo should be a link to the home page.

**Comment by fnisen** [comment]
Not seeing the new logo (black) logo in Dev.

**Comment by sirakovaDimitrina** [comment]
@vikasrohit Can you take care of the logo.

**Comment by fnisen** [comment]
@sirakovaDimitrina please don't close; I close the issues when I test.

**Comment by vikasrohit** [comment]
Logos are updated.

**Comment by fnisen** [comment]
Beautiful!
