### ISSUE TITLE
Copy updates on various Connect pages

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1096]
@vikasrohit it looks like you skipped the first three sections of my sheet. Can you please make the following changes: 

1. http://connect.topcoder-dev.com/
Headline change: “Topcoder Connect: the easiest way to go from idea to app”
First line: same as now
Second line: “Connect guides you through the entire crowdsourcing process, from entering requirements to receiving final deliverables, and it facilitates collaboration between your project team and Topcoder community members working on your project.”
“Learn more about crowdsourcing”: change to “Learn more about Connect” and change link to https://www.topcoder.com/about-topcoder/connect/ (does not exist in dev)

2. http://connect.topcoder-dev.com/new-project
Infographic: “Present your data in an easy-to-understand and interesting way.”
Front-end Prototype: “Translate designs to a web (HTML/CSS/JavaScript) or mobile prototype.”
Please decrease the spacing between the last project row (the white box shown when a project is highlighted) and the “Looking for something else…” line. It’s easy to miss on a small screen. Take out about half of the current spacing.

3. All project spec pages (e.g., http://connect.topcoder-dev.com/new-project/visual_prototype)
Change top paragraph to say: “Please answer a few basic questions about your project and, as an option, add links to supporting documents in the “Notes” section. If you have any files to upload, you’ll be able to do so later.” [This paragraph is generic and can be used for all the spec docs]

**Comment by vikasrohit** [comment]
Seems like I forgot to merge the branch where I made the changes. 😬  Now merged, it should be done unless there is a difference between doc shared in #960 vs the copy pasted here.

**Comment by fnisen** [comment]
@vikasrohit yes, the copy was the same and I'm seeing it now. A few follow ups please: 
1. The "Topcoder Connecs: the easiset..." headline is not center-aligned
2. The "Start a project button" and "Learn more about Connect" link are out of alignment with the image on the left. Can you please raise them a little bit, so that the link is bottom-aligned with the image? 
3. Take off the "." on the Inforgraphic and Front-end Prototype descriptions on /new-project (none of the other descriptions have periods).

**Comment by vikasrohit** [comment]
Done. Should in dev.

**Comment by fnisen** [comment]
Looks good, thank you.
