### ISSUE TITLE
Set new password page: button should not activate until validation has been passed

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1097]
![screen shot 2017-08-03 at 1 38 45 pm](https://user-images.githubusercontent.com/12552247/28942708-35f84354-7851-11e7-8cb8-6387dcd03dfb.png)

**Comment by vikasrohit** [comment]
Done. Changes should be in dev.

**Comment by fnisen** [comment]
Perfect, thank you.
