### ISSUE TITLE
Design for chatbot project

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1098]
We're going to be adding the IBM chatbot project shortly and need to: 
1. Modify the project menu
2. Create an icon

In fact, we can add two project types: Cognitive Chatbot (described here: https://www.topcoder.com/what-can-you-do/cognitive-solutions/) and an IBM-branded chatbot. We can maybe use the same icon, but with an IBM logo. 

Thanks!

**Comment by vic-topcoder** [comment]
We can close this now...
