### ISSUE TITLE
Sticky side bar leaves stickiness

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1105]
Continued discussion from https://github.com/appirio-tech/connect-app/issues/889#issuecomment-320852803
The position isn't right and once the side bar is updated through the main form, the element isn't sticky anymore.

![screen shot 5](https://user-images.githubusercontent.com/8484061/29057333-7944a916-7bbe-11e7-9a50-7201bec47ed4.png)
![screen shot 6](https://user-images.githubusercontent.com/8484061/29057334-7954314c-7bbe-11e7-80d5-c1b0c6ed281c.png)

fyi @vic-topcoder @fnisen @gondzo

**Comment by mtwomey** [comment]
Closing, @vikasrohit Please advise if you disagree.

**Comment by mtwomey** [comment]
Note - there still appears to be a small issue where when the form is first opened, it's not sticky. We'll address this in a new issue if needed.
