### ISSUE TITLE
Dashboard/Team Management: unable to join project created by another manager

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#111]
http://screencast.com/t/zwpRmqINovg

Issue seems to be that there's no project owner, just another manager on the project.

**Comment by parthshah** [comment]
@fnisen - Yep thats correct. Issue is with the copy .. "Once you join the project you’ll be responsible for carrying over all orders from .. {owner.name}" . In this case there is no owner? How do you want to change this copy?

**Comment by fnisen** [comment]
@parthshah can we change this to the more generic: 
"Once you join, your name will appear here and all project team members will be notified. Are you sure you want to join?"
