### ISSUE TITLE
Unsaved content warning not appearing for logged in 'New Project' flow

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1110]
When user open the New project modal by using the 'New project' button from the topbar after logging in and closes the modal or refreshes the page after reaching the project details page, it does not show the Unsaved content warning which we show when the same flow is done using /new-project URL.

fyi, @fnisen

**Comment by fnisen** [comment]
Can you please give more detail on this one?

**Comment by vikasrohit** [comment]
@fnisen as per our discussion in https://github.com/appirio-tech/connect-app/issues/1037#issuecomment-324561554 we have removed the unsaved content warning from /new-project flow (it doesn't matter if user is logged in or logged out). Now I am wondering how we should handle it when user is logged in and wants to create project from 'New Project' button, I think we are not saving incomplete project in this case, hence, we need to show the unsaved content warning here, right?

**Comment by fnisen** [comment]
@vikasrohit yes, I see. Good point. In this case, let's show the warning b/c the project is not being saved in local storage, same as we had been doing if you closed the tab before saving changes on the Specifications page.

**Comment by vikasrohit** [comment]
@fnisen I have implemented the functionality, however, I would like to get it tested before merging into dev. And right now test01 env is being used for penetration testing, so I am not sure how can I deploy it for your testing without merging into dev.

**Comment by fnisen** [comment]
Sure. Do you want to wait until test01 is clear and then use it?

**Comment by vikasrohit** [comment]
I am inclining towards deploying it to dev because test01 is going to be freed at least 2 weeks later. We have to just make sure that we don't deploy the dev changes to production, until we find this change stable. More or less it is stable, I just want to make sure of edge cases.

**Comment by vikasrohit** [comment]
Deploying to dev. Please let me know if you face any blocker.

**Comment by fnisen** [comment]
@vikasrohit one of the edge cases is the "Back" action. In that case we don't seem to be wiping the data; I can select another project and the data is still there. However, once I click "Back," if I start another project and then close it, I don't get the warning. Maybe just show the warning and wipe the data on "Back," as well, to be consistent?

**Comment by mtwomey** [comment]
@vikasrohit Let's go ahead and deploy please. Don't worry about the penn-testing. Kindly advise if you have and concerns.

**Comment by vic-topcoder** [comment]
@vikasrohit is this released? please update the status
