### ISSUE TITLE
analytics error on connect

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1111]
Following error is appearing since last few releases for connect. May be it is breaking the analytics for the application.

<img width="1280" alt="screen shot 2017-08-11 at 9 15 53 am" src="https://user-images.githubusercontent.com/2417632/29200792-dd7feb8e-7e75-11e7-8d84-78bad2a1b18e.png">

fyi @fnisen @mtwomey

**Comment by fnisen** [comment]
Any idea what is throwing this error? I don't recognize that library.

**Comment by vikasrohit** [comment]
@fnisen I tried to debug it today and found that it is something related to drift integration of segment. Did we do something related to drift in segment? I am not able to find any instance of drift in code, though.

**Comment by fnisen** [comment]
@vikasrohit Drift is installed on our marketing pages (on WordPress), but not in Connect itself. You can see an example here: https://www.topcoder.com/about-topcoder/connect/ (it's the chat widget in the lower right-hand corner). Joey said that Sumit's team helped with the installation. Can you please check with Sumit regarding what was done? 

We don't have a dedicated support person, but you can try the main channels on their page: https://segment.com/contact

**Comment by vikasrohit** [comment]
@fnisen I talked with the team here, they are just supporting the Drift operations, they didn't integrated this though. May be its about the script which we use in our pages. We might need to update it in Connect to be in sync with its server side. I would try that.

**Comment by fnisen** [comment]
OK, sounds good. Will you give that a try? I checked with Joey again and he said quesks (James Marquez) was likely the copilot who did the work. You can also try checking with him (he's part of our Slack). I think he did Segment integration for the marketing pages originally.

**Comment by vikasrohit** [comment]
@fnisen I tried the latest script block from segment, however, it still didn't work. I have raised an support issue(no link or email generated for the raised issue) with segment and their github(https://github.com/segmentio/analytics.js/issues/553) repo as well. But I am still to hear from them.

**Comment by fnisen** [comment]
Thank you very much @vikasrohit.

**Comment by vikasrohit** [comment]
@fnisen @ajefts found root cause. It is because of Google Tag Manager integration, which is calling drift methods without verifying if drift is actually available for the application.

![screen shot 2017-09-13 at 13 03 18](https://user-images.githubusercontent.com/2417632/30365346-0f3bcb4c-9885-11e7-8f75-9f7a729aeca4.png)

Need to update that code to have a check of existence on `window.drift` before calling any method on it.

**Comment by fnisen** [comment]
Nice work!

**Comment by mtwomey** [comment]
This appears to be fixed. I'm going to close for now. Please re-open if it reoccurs  @vikasrohit

**Comment by vikasrohit** [comment]
Yes, it was fixed last week.
