### ISSUE TITLE
Save incomplete project even if there is no change in form

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1114]
As of now, it saves the incomplete project only when there is a change in project details form. This is not creating any significant problem right now, however, when combined with #1037 it can cause problems. e.g. if user changes to a product template which does not contain goal or users field, changes  for #1037 would not copy them from previous product information. However, the local storage still contains the missing field (e.g. goal) and if user has all other information filled and hits 'Continue' button, it would create the project with that spurious field.

fyi, @fnisen Let me know what do you think. Should we fix this? If issues is still unclear, let me know.

**Comment by fnisen** [comment]
@vikasrohit yes please, can you explain this one again, in light of the fixes we made for #1037

**Comment by vikasrohit** [comment]
@fnisen Its more of how it is implemented in code. In short, if you change product type by clicking `Change project type` button on project details page and the new project type you select, does not have a field that previous one has, and the user clicks 'Continue' button, it would persist the project with new project type but still have the values from old project type.
Now I am realizing that we should indeed fix it.

**Comment by fnisen** [comment]
OK, thanks. Please go ahead.

**Comment by vikasrohit** [comment]
Fixed.

**Comment by fnisen** [comment]
@vikasrohit can you please test this one b/c it requires checking the API? I've you've tested already, please close.

**Comment by vikasrohit** [comment]
Checked on dev (with issue being fixed) comparing against production (where it is not fixed yet). It seems to work fine as I was expecting.

**Comment by vikasrohit** [comment]
While doing the changes for https://github.com/appirio-tech/connect-app/issues/1104, I have to revert changes made for this issue. Reopening it to analyze further.

**Comment by vic-topcoder** [comment]
@vikasrohit what's the status of this one?

**Comment by vikasrohit** [comment]
It is very specific use case and mostly does not do any serious harm except adding few spurious fields to project's details json. And as we haven't received any issue due to this, I think we can safely close it now.
