### ISSUE TITLE
Dashboard: status panel incorrect for user role

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#112]
<img width="412" alt="screen shot 2016-09-19 at 6 20 10 pm" src="https://cloud.githubusercontent.com/assets/12552247/18654407/c52e531c-7e95-11e6-914f-d7a91ae0b031.png">

Three issues in the above screenshot: 
1. User should not see a "dropdown" version of the status b/c it's not editable for them. Only the manager and copilot should be able to edit status. 
2. Topcoder Direct link should not be visible; only visible to managers and copilots
3. Salesforce link should not be visible; only visible to manager and copilots. Also "Salesforce" is misspelled.

**Comment by parthshah** [comment]
@ajefts / @fnisen how do we link to Salesforce opportunity? What reference id / url do we use?

**Comment by mahestro** [comment]
@fnisen, about #2 & #3. Should these links be visible (to copilots and managers) project role or general role wise?

Project role: this is my project (owner, member) as copilot or manager.
General role: this could or could not be my project but I still can see the links, as copilot or manager.

**Comment by fnisen** [comment]
@parthshah don't know. Maybe @mdesiderio can help. 

@mahestro good point. Now that I think about it, copilots don't need the Salesforce link b/c they won't have access to Salesforce anyway. So, let's do this: 

1. Direct link: 
    - I assume managers are Direct admins and so will always have access to any Direct link, so we can use "General role." Is that correct @ajefts? 
    - Copilots would not be able access Direct until they join/are added to the project, so we should use Project role. @ajefts can you also please confirm?
2. Salesforce link: 
    - General role only for manager
    - Copilots should not see it

**Comment by mdesiderio** [comment]
@fnisen @ajefts @parthshah 

I need more background on this, maybe we should discuss, here are some questions:

- The Salesforce -> Connect integration that we've created, creates a link between LEADS

**Comment by fnisen** [comment]
@mdesiderio 

1. Yes, sorry, we meant Lead and incorrectly put Opportunity in the copy
2. Yes, purely internal for our CAs
3. I see. OK, let me check about the need and urgency of this before you do a lot of work.

**Comment by parthshah** [comment]
I am going to split this issue into multiple issues so we can close the ones that are done. 
I've fixed point # 2 listed in the original post.
