### ISSUE TITLE
Do not show section number when there is only one section

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1125]
If the product template has only one section, no need to render section number in left side panel.

<img width="351" alt="screen shot 2017-08-17 at 2 50 24 pm" src="https://user-images.githubusercontent.com/2417632/29405417-7773e5ee-835b-11e7-8f92-5da436ef4520.png">

**Comment by vikasrohit** [comment]
Fixed.

<img width="353" alt="screen shot 2017-08-17 at 3 00 58 pm" src="https://user-images.githubusercontent.com/2417632/29405903-fc165768-835c-11e7-96b8-13dfd0b9c1c4.png">

fyi @fnisen

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev.

**Comment by fnisen** [comment]
Working, thank you.
