### ISSUE TITLE
Checkbox group type questions not removing unselected items

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1127]
While creating a new project, unselecting a checkbox from a checkbox group does not work as expected. It should remove the unchecked item, however, it is still persisting it.

Steps:
1. Go to http://connect.topcoder-dev.com/new-project/watson_chatbot
2. Select all values in 'Capabilities' question
3. Refresh the page, choose to 'Continue where I left off'  and notice that all values are still there, which okay
4. Now uncheck the last item (i.e. custom) from the list
5. Refresh the page again, choose to 'Continue where I left off' and notice that it still has all values for the capabilities question.

Screencast: https://screencast.com/t/v6KVRpbWCM6A

fyi @fnisen

**Comment by vikasrohit** [comment]
Fixed. Deployed to dev.

**Comment by fnisen** [comment]
Working correctly.
