### ISSUE TITLE
Dashboard: remove Challenges in Nav and Budget in Project panel

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#113]
<img width="1270" alt="screen shot 2016-09-19 at 6 43 15 pm" src="https://cloud.githubusercontent.com/assets/12552247/18654835/03526ce8-7e99-11e6-9477-167a9418bda2.png">

Two updates please: 
1. Remove "Challenges" from the Nav. We don't need it for any roles. It won't be active at launch. 
2. Remove Budget from the Project panel. Decided not to support that for now.

**Comment by mahestro** [comment]
Done. I commented them out with TODOs hints to be enabled again once needed in the future.
