### ISSUE TITLE
Chatbot: "Save changes" button is enabled, but not working when validation is triggered

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1133]
### Steps to reproduce the problem
- Go to created Chatbot project and edit spec to delete info in some text sections
- Notice validation is triggered
- Try "Saved changes" button; it does not work, but is enabled

In other project types, we keep the Save Changes button enabled and allow it to work (without validation being triggered) when text sections have been cleared

![screen shot 2017-08-21 at 11 17 06 am](https://user-images.githubusercontent.com/12552247/29532976-96bb9aa8-8664-11e7-8742-ecdcf105204f.png)

**Comment by vikasrohit** [comment]
@fnisen As I mentioned in #1131, there two possible fixes for this. I am assuming the first one which is 

> Either don't make them required, for editing, as we are doing for other project templates

to be consistent with other product templates. I have also fixed the generic bug which was there and causing the enabled button even with validation errors. So, we should be good now.

**Comment by fnisen** [comment]
@vikasrohit it's working, but confirmation is saying "Project submitted," rather than "Project saved." 

![screen shot 2017-08-22 at 11 09 21 am](https://user-images.githubusercontent.com/12552247/29580352-9c3cb0c2-872a-11e7-8a30-27e3717242da.png)

**Comment by vikasrohit** [comment]
Fixed. I guess now we would never have 'Project Submitted' message as it is already submitted when created the project and when we create a project we show different toaster which says `Project {project_name} created`.

**Comment by fnisen** [comment]
@vikasrohit it's working. One issue I'm noticing though: 

- Clearing info from the "Description" field throws a validation error; this doesn't occur when clearing other text fields.

**Comment by vikasrohit** [comment]
Description is still required in edit mode as well. Do you want it to be optional when editing?

**Comment by fnisen** [comment]
Perfect, thanks.
