### ISSUE TITLE
Update copyright year on spec footer

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1134]
Can you please make the year dynamic? 

![screen shot 2017-08-21 at 11 18 48 am](https://user-images.githubusercontent.com/12552247/29533051-e3fe2ba0-8664-11e7-9cdc-0ea37061d4b5.png)

**Comment by vikasrohit** [comment]
Done. Should be in dev by EOD.

**Comment by fnisen** [comment]
@vikasrohit working fine. I'm sorry for the double work, but to make it consistent with the Login/Reg pages, can you please use this format: 

![screen shot 2017-08-22 at 11 33 04 am](https://user-images.githubusercontent.com/12552247/29581302-aefdaa1a-872d-11e7-8f0a-73564828d51b.png)

Thank you!

**Comment by vikasrohit** [comment]
Okay. Done. But we do have another variant of footer component which has full version of copyright.
<img width="302" alt="screen shot 2017-08-23 at 10 45 13 am" src="https://user-images.githubusercontent.com/2417632/29599880-392c1538-87f0-11e7-88a1-b18b1cbd4e53.png">

**Comment by fnisen** [comment]
Fair point. You can change that one too to be consistent. The "(c) Topcoder 2017" should be good to use everywhere. Thank you.

**Comment by vikasrohit** [comment]
Okay, Should be there in dev by EOD.

**Comment by fnisen** [comment]
Looking good, thank you!
