### ISSUE TITLE
Chatbot: copy changes on spec

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1135]
1. Remove "(Change to text box)"

2. Add period at the end of the "Are you planning question"

![2017-08-21_1114](https://user-images.githubusercontent.com/12552247/29533741-23679b66-8668-11e7-9e2d-affa9e9d582c.png)

**Comment by vikasrohit** [comment]
Done. Should be in dev by EOD.

**Comment by fnisen** [comment]
Perfect, thanks.
