### ISSUE TITLE
Code highlight style fixes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1140]
@gondzo please update the style for the code block to match the rendering:
![screen shot](https://user-images.githubusercontent.com/8484061/29639403-7dbed806-880f-11e7-9c4d-a7aca9323bd8.png)

I used:
![screen shot 1](https://user-images.githubusercontent.com/8484061/29639406-8263fe5e-880f-11e7-8d80-9f12470f9cc8.png)

We need to add Roboto Mono regular font, and provide support for Mac and Windows fallback (SF Mono, Consolas)

**Comment by fnisen** [comment]
Background color is incorrect (see below); inspector shows we're using "#ddd." Can you please match to Vic's specs above? 

<img width="736" alt="screen shot 2017-09-05 at 3 34 39 pm" src="https://user-images.githubusercontent.com/12552247/30086479-0f5cb6a8-9250-11e7-8e48-35bce3ee77dc.png">

**Comment by fnisen** [comment]
@gondzo block is correct when posted, but still incorrect when composing.

**Comment by fnisen** [comment]
Now correct--thanks!
