### ISSUE TITLE
required validation on checkbox-group is causing errors in loading application

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1141]
<img width="387" alt="screen shot 2017-08-24 at 11 50 35 am" src="https://user-images.githubusercontent.com/2417632/29652310-83900314-88c2-11e7-8fc4-309f0e369e61.png">

fyi @fnisen

**Comment by vikasrohit** [comment]
Fixed

**Comment by fnisen** [comment]
Thank you.
