### ISSUE TITLE
Update logos to be monochrome (consistent with other pages)

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1143]
Using color logos on these pages: 

![screen shot 2017-08-24 at 1 49 54 pm](https://user-images.githubusercontent.com/12552247/29688114-6c6ba7e0-88d3-11e7-8d28-55afdaf02db0.png)

![screen shot 2017-08-24 at 1 50 03 pm](https://user-images.githubusercontent.com/12552247/29688117-6f6a4898-88d3-11e7-802f-055807d8d38e.png)

**Comment by vikasrohit** [comment]
Done. Changes should be in dev by EOD. @fnisen I have also updated few styles of wizard steps to make them consistent. Specifically, I tried to position the logo on same height so that user don't notice any change in logo position when moving between steps. However, the incomplete project confirmation page, has different styling (white background at padding of 20px), hence it requires the logo to be at different height.

**Comment by fnisen** [comment]
@vikasrohit thank you--the positioning is spot on. 

However, now that the logos are there, I've noticed the one on the accounts app is not as sharp as the one on the project creation flow. Have a look: 

Project creation:
<img width="90" alt="screen shot 2017-08-30 at 9 29 40 am" src="https://user-images.githubusercontent.com/12552247/29883706-f2505482-8d65-11e7-927c-cc01a5a7d7a7.png">

Accounts app:
<img width="97" alt="screen shot 2017-08-30 at 9 29 49 am" src="https://user-images.githubusercontent.com/12552247/29883708-f5125f26-8d65-11e7-9727-a11828849023.png">

**Comment by vikasrohit** [comment]
It is very difficult to escape from your eyes. Its a png in accounts app. 😬 I didn't find svg at that time  so used the available one. I would fix it today. BTW, we have a lot of changes pending to push to prod for account app. Connect changes were published to production with Matt's push for fixing thread permissions issue.

**Comment by vikasrohit** [comment]
Done. Changes should be in dev by EOD.

**Comment by fnisen** [comment]
I expect you to maintain this level of vigilance when I'm gone. 😀 

Sweet, they match now! The positioning is slightly different, but I'll let that go. : ) 

Yes, please push accounts app to prod; if you see any merges that didn't come from us, please check with the relevant folks as needed.
