### ISSUE TITLE
Project Details/ Feature Picker: Adding / Clicking on a custom feature leaves the feature picker modal unresponsive

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#115]

**Comment by vikasrohit** [comment]
@vic-appirio While working on this issue, I found that we don't have any way to edit a custom feature once it is added/saved. I mean once the user hits the Save Feature button, design shows the feature in non editable form. Only thing user can do is to disable/enable the feature. So, it seems like right now only way to edit a custom feature is to delete/disable it and then re-add it by copy pasting the description. It seems unnecessary steps to me just to edit the description of a custom feature.

cc: @parthshah @fnisen

**Comment by vikasrohit** [comment]
I found a workaround. User can use the switch button to disable the feature, which would bring the custom feature in editable form and user can update the title/description and then save the feature again. However, with this workaround, there is one limitation. If user closes the feature picker dialog or refreshes the page after disabling the feature, he/she will loose the content of that custom feature.

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/184327383400572

**Comment by parthshah** [comment]
I agree this interaction is definitely confusing. Toggle button in case of custom features should imply that the feature is no longer required and can be deleted. There wouldn't be a way to enable this feature in the future .. one would have to create a new feature.
Reg. editing an existing feature - custom features should always be rendered as a form in feature picker. A user with edit permissions would be able to edit all fields of the feature.

**Comment by vikasrohit** [comment]
@parthshah I have created #125 for this and already committed my changes for that. Please let me know if I should revert the changes or wait for @vic-appirio for respond?

**Comment by vic-appirio** [comment]
Commented at #125 → Let's try to mimic the regular feature experience so that the user can always edit the form. The difference is the "delete" button at the end of the feature.

**Comment by vikasrohit** [comment]
Done. Changes are in dev.
