### ISSUE TITLE
Leaving a project (manager) not working

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1154]
### Expected behavior
Log in as manager → leave a project that you joined → You left the project

### Actual behavior
Leaving a project doesn't work (after refresh or anything)

Screen recording: https://www.dropbox.com/s/hd31vgougo8vm5v/leave%20project%20bug.mov?dl=0

**Comment by vikasrohit** [comment]
@vic-topcoder Can you please share the console logs, if possible? I am able to successfully leave a project in dev. It must be some edge case.

**Comment by vic-topcoder** [comment]
I checked the project a day later, and I was removed. Not sure what exactly happened. If you want to trace exactly what was the event stack, can you do that from the back-end? Right now I'm out of the project I had problems leaving. This might have something to do with the project being too big and having a lot of Discuss threads that I was authorized to view after joining the project. Not sure how we deal with this.

**Comment by vikasrohit** [comment]
Ohk. It might be issue in reaching to api server. It might have taken time to get connected to the API. Its is difficult to trace it from backend. If you face such issue in future, please take screenshot of console tab for me. It would be great if you can check the network tab as well at that time. 😬
