### ISSUE TITLE
Image upload not functioning as intended

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1162]
### Actual behavior: 
User has to add an image URL in order add an image
![screen shot 2017-09-06 at 11 07 52 am](https://user-images.githubusercontent.com/12552247/30137724-842b9c32-9319-11e7-9020-697cedcff20d.png)

### Expected behavior: 
User should be able to drag and drop or upload an image file (similar behavior to GitHub)

@gondzo is it possible to change this fairly easily? If not, let's turn off the image upload button for now b/c the UX is not intuitive.

**Comment by gondzo** [comment]
@fnisen you can drag and drop an image directly to the post editor

**Comment by fnisen** [comment]
@gondzo can you please turn off image upload entirely for now? I'm worried the migration will be too much of a hassle once we move off Discourse in a few months. We can turn it on again once we have the new system ready.

**Comment by fnisen** [comment]
Sorry about the extra work.

**Comment by fnisen** [comment]
Verified that it's off--thank you.
