### ISSUE TITLE
ProjectWizard steps have misaligned title in modal mode

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1164]
<img width="1280" alt="screen shot 2017-09-08 at 9 25 03 am" src="https://user-images.githubusercontent.com/2417632/30195554-a2a17b0a-9477-11e7-9cdc-c983fb4fccde.png">

fyi @fnisen

**Comment by vikasrohit** [comment]
It seems style change to fix style of new project wizard steps, caused this. Will take care of it.

**Comment by vikasrohit** [comment]
Fixed.

**Comment by fnisen** [comment]
Yes, looks much better.
