### ISSUE TITLE
[$60] Fonts are not loading correctly

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1165]
It seems fonts are again failing to load on production and dev environments.

<img width="1265" alt="screen shot 2017-09-08 at 5 02 33 pm" src="https://user-images.githubusercontent.com/2417632/30209858-a3d73588-94b7-11e7-96a7-418da9668dcc.png">
@mtwomey Do you have any idea about this? Can it be because of our new deployment tool i.e. circleci?

fyi, @fnisen @vic-topcoder

**Comment by mtwomey** [comment]
It's unclear to me if this is still indeed not functioning as desired or where the fix is (Victor suggests the fix is in webpack).

**Comment by mtwomey** [comment]
![screen shot 2017-09-25 at 2 24 27 pm](https://user-images.githubusercontent.com/7715262/30826835-91cbb6ae-a1fd-11e7-95e9-672fc9e66426.png)

**Comment by mtwomey** [comment]
Also - this may have to do with the circleCI deploy.

**Comment by vikasrohit** [comment]
I think it started to happen after circeCI migration, not sure though.

**Comment by gondzo** [comment]
can we use test01 environment for testing the fix for this one ?
@vikasrohit @mtwomey

**Comment by vikasrohit** [comment]
@gondzo we are using test01 for internal testing and it is kind of freezed environment. We should not use it until further update.

**Comment by gondzo** [comment]
Looks good. It's fixed and deployed in test02
