### ISSUE TITLE
Two tiered menus

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1170]
Intuitive menus w/o cheesecake factory look and feel

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-1

**Comment by vic-topcoder** [comment]
@vikasrohit let's get the new styles for the 2-step menu for project creation implemented. Attached is the html+css package from @sirakovaDimitrina. A prototype of the expected experience is here: https://invis.io/DZD1VC6PE#/248795103_main_Project_Menu

For the prototype, the elements on the 2nd row open with a menu, while the elements on top are direct links to project specification. Let me know if you have any questions on that one.

I assume that we can use @sirakovaDimitrina for style refinements on the existing controls, so feel free to create sub-tasks and assign accordingly.
[sub-menu-cards.zip](https://github.com/appirio-tech/connect-app/files/1294425/sub-menu-cards.zip)

**Comment by vikasrohit** [comment]
@vic-topcoder is it possible to track it in github only? or may be you can track it in aha for your stuff, but for development I would like to stick with github unless there is a very good reason to switch to aha. 😬

**Comment by vikasrohit** [comment]
@fnisen  @vic-topcoder  Are we okay to render Chatbot now in the project category list?
Is the project category and product types are final ones as depicted in the designs or they need to be altered?

**Comment by vic-topcoder** [comment]
Let me confirm the menu structure and I'll update you. Right now where we have a sub-menu the button label should be "Select project" vs. "Create project" on the 1st level cards (that open the project creation).

**Comment by dmessing** [comment]
testing 1 two three

**Comment by vic-topcoder** [comment]
Discussed with Joey; project structure as follow:

Main page: 4 projects on first row: 

Visual Design

- App
- Website
- Chat bot

Categories - 2nd row:

- Design
- Development
- QA

Categories:

Design

- Wireframes
- Visual design
- Other

Development:

- Front-end prototype
- Front-end development
- Integration/API
- Development iteration/sprint (figure out name with Adam)

QA:
- no change

**Comment by vikasrohit** [comment]
> Main page: 4 projects on first row:

It seems we have only 3 on first row and 3 on second row.

We don't have project questions templates for Front-end development, Integration/API and Development iteration/sprint. So we have to either come up with new question templates or use the default one which we use for generic software development (which itself is not listed in the new layout)

**Comment by vikasrohit** [comment]
We need copies for descriptions of these categories and sub categories.

**Comment by vikasrohit** [comment]
@vic-topcoder Do we need to update the deep link URL? I mean right now it is /new-project/<product> e.g. /new-project/wireframes or /new-project/visual_design_prod. However, after we introduce project category in before actual product (sub category), ideal URL would be /new-project/<project_category>/<product> e.g. /new-project/visual_design/wireframes or /new-project/visual_design/visual_design_prod and directly entering /new-project/visual_design should land user to product(or sub category) selection screen for Design category. However, if we do that, our existing marketing deep links (which are like /new-project/**visual_design_prod** or /new-project/visual_design/**wireframes**) would fail as it would not treat the bold portion as project category not a sub category or product.
fyi @dmessing

**Comment by vikasrohit** [comment]
@vic-topcoder  @dmessing  I have deployed the current WIP to dev environment for testing purposes.

**Comment by vic-topcoder** [comment]
Latest design: https://projects.invisionapp.com/share/U3DJPB4DR#/screens/254024918
Latest styles: 
[sub-menu-cards 2.zip](https://github.com/appirio-tech/connect-app/files/1313259/sub-menu-cards.2.zip)

The new projects should use the generic project forms

- [ ] Fix the background color to $tc-gray-neutral-light
- [ ] Vic to deliver the final icons
- [ ]  Vic to figure out the final project types on Development

**Comment by vikasrohit** [comment]
@vic-topcoder for changing the background color we have to change it for all pages as it is right now using browser's default body color.

**Comment by vikasrohit** [comment]
@vic-topcoder the issue with setting background color is that it has to be set on root element (for us it is `div.main-wrapper`) of the DOM and we can't select (via css selector) parent element through child element. i.e. we can do `div.main-wrapper > .ProjectWizard` to apply specific class to .ProjectWizard but can't do vice versa. Only solution is to grab the route in our root component (`Layout.jsx` component for connect) and check if the current root maps to /new-project and then apply specific class to the `div.main-wrapper` div. And to check the route in our Layout component, we have to make it router aware by wrapping it in HOC withRouter.
