### ISSUE TITLE
Bring back "Submit for review" button on Specification page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1174]
This was the default feature  -> ask Vikas how to roll back. We need to figure out where the code is.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-22

**Comment by vikasrohit** [comment]
Changes are in dev env for review.

**Comment by vic-topcoder** [comment]
I don't see it in dev right now. Is the button back in latest dev? @vikasrohit
