### ISSUE TITLE
Create projects as Draft

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1175]
Set the newly created project status flag to "Draft".

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-21

**Comment by mtwomey** [comment]
@vikasrohit I understand this is basically a review to the previous behavior. Please confirm if you have enough info to proceed.

**Comment by vikasrohit** [comment]
Yes, I have required information.

**Comment by vikasrohit** [comment]
Changes are deployed to dev env for review.
