### ISSUE TITLE
Project creation: New project modal is not closed after project is created

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#118]
This was working before, but is now broken: http://screencast.com/t/1R0dctrU

Modal should close and the user should be taken to the Project dashboard.

**Comment by fnisen** [comment]
Still broken: http://screencast.com/t/9H4NYM2k

**Comment by vikasrohit** [comment]
@fnisen its working fine for in dev.

**Comment by fnisen** [comment]
@vikasrohit still seeing problems. Now there is a blue line at the top and bottom of the modal, the slider does not look right, and page loading is not uniform (elements seem to randomly turn on): http://screencast.com/t/gPMknDDyQSl

**Comment by vikasrohit** [comment]
@fnisen I guess, Luis has already pointed about the blue line around the modal. And IMO, slider is not looking right because it has some static images to load, which some time takes time.
