### ISSUE TITLE
Fix the salesforce lead link for the new org

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1181]
It is right now pointing to old salesforce org. It should point to topcoder salesforce org instead of appirio org.

**Comment by gondzo** [comment]
I think this one would be too complex to set up and verify to be a community task. @vikasrohit can you take this one, or get write some pointers for the expected changes. Do we only need to change salesforceLead.orgId in tc-project-service configuration ?

**Comment by vikasrohit** [comment]
Sorry @gondzo. Missed to update the status here. It is fixed now. Waiting to go to production.

**Comment by vic-topcoder** [comment]
@vikasrohit Did we deploy this one? Please close if it is in production - I thought it is part of the release
