### ISSUE TITLE
Unwanted "unsaved content alert" when user creates project after logging in

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1183]
If user tries to create project after logging in, `unsaved content alert` is shown when user clicks on 'Continue' button. This alert should only be shown when user is moving away from the application not when they are moved because of project creation.

fyi @vic-topcoder @mtwomey @dmessing I have fixed this a hotfix, but not deployed to production yet. I think it should be updated as hotfix, but it still want to keep all on same page before going for it.

**Comment by vikasrohit** [comment]
https://github.com/appirio-tech/connect-app/tree/hotfix/unnecessary-unsaved-content-alert

**Comment by vic-topcoder** [comment]
Great - @mtwomey please advise for best course of action.

**Comment by vikasrohit** [comment]
Deploying to production, Please let me know if things are not working after this. We can revert it.

**Comment by mtwomey** [comment]
@vikasrohit Sounds good with this plan. Kindle close once confirmed.
