### ISSUE TITLE
project menu icons - update

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1185]
Let's replace the icons on the project menu with the latest and grates from the package. I've renamed them to follow a strict(er) naming convention. All icons begin with the `product-` prefix and go on to add the category - design, dev, qa - so we can keep an eye for them and make sense in source code. For category of work the name patter ins `product-cat-` and category-specific name "dev, design, qa". This will allow us to keep adding more products and keep things organized.

- [x] Replace project icons with [project menu icons.zip](https://github.com/appirio-tech/connect-app/files/1322267/project.menu.icons.zip)

**Comment by vikasrohit** [comment]
Fixed icons in dev.

**Comment by vikasrohit** [comment]
@sirakovaDimitrina You can take over it to fix the second item in the checklist.
