### ISSUE TITLE
Button text on category cards should read "View all" (hover on Design in the InVision prototype)

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1191]
Carried forward from #1184 
Button text on category cards should read "View all" (hover on Design in the InVision prototype)

**Comment by vikasrohit** [comment]
@vic-topcoder Should we keep `Select Project` for project categories which has only one product i.e. App, Website and Chatbot?

**Comment by vikasrohit** [comment]
Fixed in dev.

**Comment by vic-topcoder** [comment]
Yes, that is great.
