### ISSUE TITLE
[$20] Code block styling

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1192]
Using code blocks with large content will break page layout. We should probably force wrap on the <pre> tags in the posts, or add scrolling?
![image](https://user-images.githubusercontent.com/3051646/30773825-20bd5b6e-a079-11e7-962f-7a18c2e7df5e.png)

@vic-topcoder any ideas ?

**Comment by vikasrohit** [comment]
Sorry to jump in @gondzo @vic-topcoder However, I do remember that we added horizontal scroll long time back to resolve this issue #619. I think it was done for comments only, may be we need to apply the same for post as well.

**Comment by vic-topcoder** [comment]
Add horizontal overflow for code blocks.

**Comment by HammadSiddiqui** [comment]
Can you give instructions to replicate this scenario?

**Comment by gondzo** [comment]
In the project dashboard create a new post with a code block that has a
single long line (larger than page width)

**Comment by HammadSiddiqui** [comment]
@gondzo 
While trying to create a new post, I am getting an error "Failed to create topic in Discourse: Unable to create discourse user"

**Comment by gondzo** [comment]
Looks good
