### ISSUE TITLE
[$250] Upgrade Webpack to v3 (latest)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1196]
We need to match the Webpack and stack to community-app as we currently use Webpack 1. There are great features like tree-shaking and ES6 native support, plus multiple optimizations. 

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-36

**Comment by gondzo** [comment]
Majority of changes should be made to https://github.com/appirio-tech/webpack-config repository (feature/connectv2 branch), as well as webpack.config.js in connect-app repo.

**Comment by mhikeo** [comment]
@vic-topcoder @gondzo Can I request for access on the following?
* community-app
* https://topcoder.aha.io/features/TCCONNECT-36

**Comment by gondzo** [comment]
What do you need community-app for ?
There is nothing in aha.io that isn't in this thread

**Comment by mhikeo** [comment]
I thought we need to match how it is being done in community-app. Anyways, I'll proceed with the task. Thanks.

**Comment by gondzo** [comment]
This is the community app repo > https://github.com/appirio-tech/topcoder-app

**Comment by vikasrohit** [comment]
@gondzo community app which @vic-topcoder mentioned is https://github.com/topcoder-platform/community-app

**Comment by gondzo** [comment]
@all prize increased and this is now available for pickup.

**Comment by vic-topcoder** [comment]
@birdofpreyru - please advise if there's anything we can do to help align the system. I know we're already discussing it, would be nice to lay out what's needed in here for community
@mtwomey FYI

**Comment by gondzo** [comment]
just following the webpack migration guide should be enough > https://webpack.js.org/guides/migrating/

**Comment by birdofpreyru** [comment]
Well, just mechanical update to Wepback 3 can be done following the migration guide. Also, I'd say, break dependency on https://github.com/appirio-tech/webpack-config and do a local webpack config, properly split for dev / prod builds configurations.

But then, what we actually put into the config is related to other staff we discuss about styles, etc.

**Comment by birdofpreyru** [comment]
Here is how Webpack is currently configured in Community App:
https://github.com/topcoder-platform/community-app/tree/develop/config/webpack

**Comment by birdofpreyru** [comment]
Here is how Webpack is currently configured in Community App:
https://github.com/topcoder-platform/community-app/tree/develop/config/webpack

Most of its content is actually about making all stuff like CSS Modules, Hot Module Reloading in dev, inline svg, etc. to work together.

**Comment by maxceem** [comment]
I'm quite familiar with community app webpack config, just want to clarify what we need for connect-app.
1. @gondzo said that changes have to be made to https://github.com/appirio-tech/webpack-config repository, though if understood correctly @birdofpreyru proposed to break dependency on that repo and move config to the connect-app, which way is preferred?

2. Should we just update config following https://webpack.js.org/guides/migrating/ or should we introduce some stuff which is not used in connect-app but used in community app?

Thank you.

**Comment by birdofpreyru** [comment]
I'd say:
- Break dependency;
- Use community-app config as the reference how it should be structured. Probably, don't yet introduce the things that are not used in connect-app, but  keep it as easy as possible to add them in future. Also, ensure that the version you compose now does not break the present version of connect-app.
But, wait for confirmation from @vic-topcoder and @gondzo

**Comment by maxceem** [comment]
3. As I understand we have to use JS instead of CoffeeScript for Webpack config, correct?

**Comment by maxceem** [comment]
12 hours have passed, though I've done the majority of changes.
I use approach advised by @birdofpreyru, so I removed dependency from https://github.com/appirio-tech/webpack-config and moved config to the connect-app project.
Unfortunately my timezone is exactly 12 hours opposite to NY, so I couldn't wait for confirmation.

Currently just working on the minor issues
- favicon
- hot reloading

Going to submit in few hours.

**Comment by gondzo** [comment]
Thanks for the update. IMO this is a good approach, with appirio-tech/webpack-config we are using a custom branch for connect anyway so there is no reason to keep the dependency.

**Comment by gondzo** [comment]
3. Yes, JS for the webpack config is fine.

**Comment by maxceem** [comment]
I've fixed everything and was ready to make a pull request when realized that I removed npm-shrinkwrap.json and cannot easily create it because of peer dependencies conflicts.

Can I keep this task, and resolve conflicts, create npm-shrinkwrap.json and submit PR tomorrow morning? 
Thank you.

**Comment by gondzo** [comment]
Yes, that's fine

**Comment by maxceem** [comment]
I'm a little bit confused about NPM version and `npm-shrinkwrap.json` file.
Which NPM versions we have to use to work on this project and in particular create `npm-shrinkwrap.json` file?
Project readme requires us to use npm v3, though `npm-shrinkwrap.json` already contains unresolved issues in opinion of npm v3 so I think `npm-shrinkwrap.json` couldn't be created using v3.

I see in `npm-shrinkwrap.json` file history that some time ago npm v5.3 has been used to update dependencies after a fresh install. But even if I update `npm-shrinkwrap.json` without my changes using npm v5.3 it looks like there are too many updates. Not only minor version updates but also `fsevents` comes back, even though, it was removed some time ago according to history.

Could you please help me to clarify what is the regular workflow which is followed to update `npm-shrinkwrap.json` file.

**Comment by vikasrohit** [comment]
@maxceem Try with node v8.5.0 and npm v5.3.0, it should work.

**Comment by gondzo** [comment]
Also, general workflow to update shrinkwrap would be
- npm install with old npm-shrinkwrap (with --no-optional to skip fsevents) 
- update package.json, remove npm-shrinkwrap
- npm install with new package json
the new npm-shrinkwrap will have just the minimal diff

**Comment by gondzo** [comment]
Change is merged to dev.
