### ISSUE TITLE
Update the project type tags for new project types

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1197]
<img width="391" alt="screen shot 2017-09-26 at 2 02 39 pm" src="https://user-images.githubusercontent.com/2417632/30850552-79a5f8b6-a2c3-11e7-8714-a05adc9b5737.png">
Notice missing colored tags for website and app project types.

@vic-topcoder We need possibly new colors and copy for project type tags for the new project types. Right now we have following map for project types to colors:
<pre>
const projectTypeClassMap = {
  'generic': 'purple-block',
  'visual_design': 'blue-block',
  'visual_prototype': 'blue-block',
  'app_dev': 'green-block'
}
</pre>

**Comment by vic-topcoder** [comment]
That's a minor issue and we'll probably switch the type tags in the upcoming project structure refactoring. the color coding issue would persist, you are correct, if we use tags. I'll close this issue and put an update request in Aha!. Thanks!
