### ISSUE TITLE
Dashboard/Status updates: Coder Bot comments being autogenerated

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#120]
<img width="753" alt="screen shot 2016-09-20 at 4 14 12 pm" src="https://cloud.githubusercontent.com/assets/12552247/18692895/63267f74-7f52-11e6-978f-120f7b2bd679.png">

Coder Bot is automatically appearing in status update comments for some reason.

**Comment by vikasrohit** [comment]
It seems like there are some posts, with userId being 'system', for the topic. @mdesiderio do you know any reason for these dummy posts? or is it an error on front end which is posting empty posts, with userId being 'system'?

**Comment by fnisen** [comment]
Investigated some more. Posts are appearing after page reload, both for the poster and those reading the post. Here is an example: http://screencast.com/t/LZaUFQtHHjw. They don't appear when the post is first made.

**Comment by vikasrohit** [comment]
Change are in dev.
