### ISSUE TITLE
Back button does not work on wizard pages

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1205]
Clicking back button should reload the page

**Comment by vikasrohit** [comment]
I did check the issue @vic-topcoder It is not a quick fix. Basically we have to determine wizard step from URL to get it done.

**Comment by vikasrohit** [comment]
@vic-topcoder I have somehow managed to get the behaviour. However, it still needs more testing. I am expecting some edge cases here which I am not certain of before hand. It would be great, if you can play around with it in dev and see if it matches with your expectations. I am deploying the feature temporarily into dev env.

**Comment by vikasrohit** [comment]
@vic-topcoder Did you get chance to play with it?

**Comment by vic-topcoder** [comment]
yeah. The back button of the wizard works. We have to fix the browser back/forward buttons next. Opening a new issue
