### ISSUE TITLE
Project dashboard doesn't display the new project type

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1207]
We must say what the project template is on the dashboard. Please add the missing title and reuse the project icon/description as the other projects.

![screen shot 1](https://user-images.githubusercontent.com/8484061/31004005-573d9adc-a4a7-11e7-8db2-f98cda39f7ae.png)

Expected
![screen shot 2](https://user-images.githubusercontent.com/8484061/31004053-8dd78b34-a4a7-11e7-8b61-a8948a13f3b8.png)

**Comment by vikasrohit** [comment]
Should be fixed in dev now.

**Comment by vikasrohit** [comment]
Closing
