### ISSUE TITLE
Dashboard/Status updates: new status composer should not be shown expanded

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#121]
The new status composer should just show the subject field at first and then expand once a user clicks into it. See second column in design below. 

![222a7753-cdb9-4f05-9f2a-c94893276fc6](https://cloud.githubusercontent.com/assets/12552247/18692961/ddfe8174-7f52-11e6-8407-486b97e9afb8.png)

**Comment by vikasrohit** [comment]
@fnisen Fixed with catch that right now it would collapse the composer even if any of the input or textarea contains some text. Though it should not take much time to fix that as well, however, it would be better to track it separately.

**Comment by fnisen** [comment]
@vikasrohit OK, let me check it out once it's deployed and see if we need another issue.

**Comment by vikasrohit** [comment]
Done. Changes are in dev.
