### ISSUE TITLE
Filter project types in admin view

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1212]
Fix all the missing project types listed in the admin view filter

![screen shot 1](https://user-images.githubusercontent.com/8484061/31104397-9ada89ca-a791-11e7-8868-865927bbcdc8.png)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-70

**Comment by vikasrohit** [comment]
Changes done in feature branch. Waiting for the current milestone of 'chatbot' to be delivered first before getting this one merged into dev.

**Comment by vic-topcoder** [comment]
Can we roll it with Chatbot release please?

**Comment by vikasrohit** [comment]
Merged changes into dev for releasing it in current release.
