### ISSUE TITLE
Project card view

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1217]
Display the project details as a card with status update for better user experience

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-4

**Comment by vic-topcoder** [comment]
Design here: https://drive.google.com/drive/folders/0B1LbmKnex41fcDc0eVFPcldLckU?usp=sharing

**Comment by mtwomey** [comment]
@vikasrohit Can we please refresh the status on this one? I feel like I've already seen something for this, or am I confused?

**Comment by vikasrohit** [comment]
@mtwomey You might have seen it in dev because my branch was there in dev for some time. 😬  

It is mostly done, I am open for any suggestion or issues if changes do not met the specs.

**Comment by vic-topcoder** [comment]
@vikasrohit can we get the feature in Dev so I can review? Thanks

**Comment by vikasrohit** [comment]
@vic-topcoder Changes are in dev now. I had to upgrade react-components repo as well to react-router v4 to get it working in dev.

**Comment by vikasrohit** [comment]
Done all points except followings:

>  Project icon should be displayed in a 32x32 px square

It is already 32x32 icon, let me know if missed something here.

> Space between project icon and project title/project date is 10px

It was already 20px as per design. I have updated to be 10px. Let me know if I misunderstood things here.

> Project status label doesn't match design (we need a new style definition) - text size and text color;

I am not able to see much different there. Only difference I could found was the font face, changed it to roboto-regular from roboto-medium. Event latest from google drive specs shows this style for status label:
`font-family: Roboto-Regular;
font-size: 11px;
color: #262628;
line-height: 20px;`

> Project cards should be listed by latest updated - the projects with latest activity should be at the top.

I would be easier from implementation view, if we can change default sorting for both customers and managers. I don't see any -ve of sorting by updated date even for managers. Please let me know if think otherwise.

> Canceled projects should be hidden from customer view. We should keep only draft, in review, reviewed, active, paused, and completed projects.

I might be missing some product value here, but I didn't understand why we should hide Cancelled projects from customers? As as customer I would like to have it visible to track if I have created a project in past no matter if I or topcoder cancelled the project.

**Comment by vic-topcoder** [comment]
Bottom-up:

- Canceled projects are quite few in the system, they don't hold value as there's no conversation or reason put in the project itself. Most of the time those are test/temporary projects. The value is to not pollute the space with old unused projects. The card view of projects provides value as it is a project dashboard - as a customer you see all the active projects and what has happened on them, so you can react. A list of canceled projects is of no use as we don't deliver value in them for the customer. The second implementation of filters on projects should help focus between projects in different statuses.

As we don't support deletion of projects, we should have a mechanism to clear the interface for customers. The problem arises for active customers with more than 6 projects. The next iteration of projects would modify the structure and logic of a project, as we want to focus on product status instead of project status. In that case a project becomes a container that might have or no active products. The project can also be extended with more products and become active again. Right now we have a unidirectional flow, and that doesn't reflect the nature of projects.

I would want us to have another status - archived - that hides the projects that are not active from the system so customers can go and reference them.

Short answer is - hide less important projects and allow customers to discard test projects from the system without losing actual data (cancel instead of delete).

- Customers and managers should have different rules for the interface. Let's keep these rules flexible

**Comment by vic-topcoder** [comment]
Icon and project header title/time - I did dig deeper into design/implementation and figure it out:

The icon is 32x32 px block in a 40px tall block, and the thing that bother me is the vertical-align of a 32px into 40px - it is top, but should be vertical center. Let's get the spacing between icon and title/time block back to 20px as it was wired in the iteration (sorry for changing it - this is final!). If we have a 4px margin-top that'll do.
![screen shot 21](https://user-images.githubusercontent.com/8484061/32678326-c8ca7220-c616-11e7-9159-a4a7c16b1ea0.png)
![screen shot 22](https://user-images.githubusercontent.com/8484061/32678348-d300f37c-c616-11e7-90a8-da0f20ddf357.png)

**Comment by vic-topcoder** [comment]
- [ ] Project navigation should always be next to the logo (40px between logo and navigation). This can be done if we move the navigation within the logo container and space the 3 big containers evenly through flex layout. Small changes in the CSS would be needed - display: inline-block; vertical-align: top; to make sure all elements are correctly aligning as the screenshots below:

![screen shot 15](https://user-images.githubusercontent.com/8484061/32678487-64de1978-c617-11e7-9d21-2a9c8b85ed65.png)

**Comment by vic-topcoder** [comment]
Great progress, thank you very much for the good work! 👍

**Comment by vikasrohit** [comment]
>  Let's change the minimum height of the project description to be only 1 line of text. We should make the project description a mandatory field as it is very important.
Okay,

**Comment by vikasrohit** [comment]
Done with all points. I think only pending query is following:

> Project cards should be listed by latest updated - the projects with latest activity should be at the top.

I would be easier from implementation view, if we can change default sorting for both customers and managers. I don't see any -ve of sorting by updated date even for managers. Please let me know if think otherwise.

For hiding cancelled project for customers, I have created separate [ticket](https://github.com/appirio-tech/connect-app/issues/1302) to track it better.

**Comment by vic-topcoder** [comment]
Thanks @vikasrohit - good progress on this one. Let's try to get the project sorting working as well. Our next iteration on the cards would be to add some of the owner capabilities (delete project) so customers can clean up their project card view.

**Comment by vikasrohit** [comment]
@vic-topcoder Sorting is working. It is same for managers and customers though. My question is should be keep same sorting for all users or should we keep sorting at creation date for manager which is the default behaviour right now.

**Comment by vic-topcoder** [comment]
Let's keep the default manager sorting by creation date, and the client view as "latest updated first"

**Comment by vic-topcoder** [comment]
Otherwise I love it, closing - the customer card view works as intended.
