### ISSUE TITLE
Dashboard/Status updates: posts in one thread should be "compressed"

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#122]
Posts are currently shown fully expanded, as below, but should be shown compressed, with an option to see "more replies," as in the third column of the attached design. 

<img width="736" alt="screen shot 2016-09-20 at 4 57 25 pm" src="https://cloud.githubusercontent.com/assets/12552247/18693020/62838c28-7f53-11e6-9aa7-1b4b9ec5088b.png">

![222a7753-cdb9-4f05-9f2a-c94893276fc6](https://cloud.githubusercontent.com/assets/12552247/18693045/94b4842c-7f53-11e6-8c9d-c9e47ed1a8b9.png)

**Comment by vikasrohit** [comment]
@fnisen we don't have support for paging (both for topics and posts) yet in messaging api, hence can't really do paging kind of thing here. Do you want me fake the paging? I mean render a few (lets say 5) messages/comments and render all comments/messages once user clicks on the load more button.

**Comment by fnisen** [comment]
@vikasrohit not urgent to hack it right now

@mdesiderio would we be able to add paging to messaging API?

**Comment by mdesiderio** [comment]
@vikasrohit @fnisen 

I have implemented pagination for the message service, but unfortunately Discourse doesn't provide traditional limit / offset or page / page size type of pagination, it is a little more complicated than that.

1- Whenever a topic is retrieved from the API you will have 3 new fields

totalPosts: Convenience field that represents the total number of posts the topic has;
retrievedPosts: Convenience field that represent the total number of posts retrieved for this topic. 
postIds: Array containing a list of post ids associated with the topic in chronological order.

Note: The first call to get a topic will always return 20 posts. There is no way to change that.

2- When the frontend needs the next N posts, it should look at the postIds array, and determine the next N post ids that it wold like to retrieve;

3- Make a call to: /v4/topics/:topicId/posts?postIds=:postId1,:postId2,:postId3, ... postIdN
This will retrieve a list of posts containing the posts requested in the post Ids parameter.

E.g: {{URL}}/v4/topics/173/posts?postIds=460,461,462,463
This would retrieve posts 460, 461, 462, and 463 that are associated with topic 173

Arguably I could implement a more traditional pagination on the api layer, however that would require multiple extra calls to Discourse, and that could affect performance rendering pagination pointless.

**Comment by fnisen** [comment]
Thanks @mdesiderio. I would prioritize performance. 

@vikasrohit, @parthshah let us know what you think

**Comment by mdesiderio** [comment]
@vikasrohit unfortunately I don't see any options to reverse the order that comes from Discourse, the only way I can think of right now is to use the same approach that I described before using the post ids to fetch posts in the reverse order.

**Comment by vikasrohit** [comment]
Oh...then I have to make two calls to get initial set of posts. 😞 
Anyway, even if do that, I have another problem which inclusion of non 'post' type posts in totalPosts count. How can I determine the number of posts with type 'post'

**Comment by vikasrohit** [comment]
@fnisen @vic-appirio  I am almost done with the changes to facilitate the required behaviour. Do we need the same changes in Discussions tab?

**Comment by vikasrohit** [comment]
Changes are working in dev.
