### ISSUE TITLE
Project ref code and name text box are not vertically aligned

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1221]
After recent release, these two text box are failing to align vertically.

<img width="1016" alt="screen shot 2017-10-03 at 5 03 09 pm" src="https://user-images.githubusercontent.com/2417632/31123313-05defc44-a85d-11e7-8fd3-34fcdd41c4a9.png">

fyi @vic-topcoder

**Comment by vic-topcoder** [comment]
The HTML of the control is very awkward. We need to refactor the react control template to allow for regular styling.

**Comment by vic-topcoder** [comment]
@sirakovaDimitrina please advise on what the HTML control for the input should look like so we can have a straight-forward styling. Right now there are negative margins and other artifacts that affect rendering.
