### ISSUE TITLE
Chatbot project creation specification updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1222]
Clone it from the Watson chatbot, with the following changes:

- Remove "Watson" from the header (page title becomes "Let's setup your Chatbot project"
- Remove "Do you have an existing IBM Bluemix account?" question

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-74

**Comment by vikasrohit** [comment]
Done. You can play with changes in dev.
