### ISSUE TITLE
Chatbot project card on main menu

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1224]
The chatbot needs to copy the existing IBM Chatbot card with new content.

Title: "Chatbot"

Text: "Build, train and test a custom conversation for your chat bot"

 

Use the existing chatbot icon from the Watson chat bot card.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-72

**Comment by vikasrohit** [comment]
Done.
