### ISSUE TITLE
Create new generic project type on Connect

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1225]
We must have the new project type on the Project services - generic chatbot - "Chatbot"

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-71

**Comment by vikasrohit** [comment]
@vic-topcoder we already have `chatbot` project category support in our previous release for two tier menu. `chatbot` is a generic category for all chatbot products that we might support in future. Watson chatbot `watson_chatbot` is one of those products. And now we have a new generic chatbot product so it could be given an unique id something like `generic_chatbot`.

**Comment by vic-topcoder** [comment]
Connected to #1223. I'll update you on this tomorrow.
