### ISSUE TITLE
Google Analytics ID + Click ID integration for marketing

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1227]
We need to add the collection of information for Marketing with the full integration of Google analytics ID + Click ID for Greg's team

We need to capture the Google Analytics Click ID (GCLID) and Google Analytics Client ID (GACID) on form submissions. These come from two cookies: `_gacid` and `_gclid`. Google assigns a GACID to everyone on the internet, so we should always be able to capture that. GCLID is only set if a user clicks on one of our paid ads, so many/most lead records will be blank here.

We need to capture this data and feed it into corresponding fields in the lead object within Salesforce. I'm not sure if that presents any challenges with feeding this work to the community, as they obviously don't have access to our Salesforce org. That's about all the technical detail I have, but Harshit set this up on our Instapage LPs and can share his approach if need be.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-75

**Comment by vic-topcoder** [comment]
Hey guys, let's figure out what is the scope of this data capture and how we can send this to SFDC.

**Comment by mtwomey** [comment]
@vikasrohit Do you understand how the current Salesforce integration w/Connect works and is this enough information to proceed? If not, we may need to loop back with Greg and Harshit

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey I know about salesforce integration pretty well, however, I am not sure about the actual requirement around Google Analytics. I am under impression that all analytics work is handled via segment (which in turn talks with Google analytics) and it is handled via Parallel Path guys. I will talk with Harshit for getting more information on this.

**Comment by vic-topcoder** [comment]
Thanks @vikasrohit. Greg mentioned Harshit knows what the issue is.

**Comment by harshitmehta123** [comment]
For instapages we captured the value of the cookies, put them in hidden fields and sent it to salesforce via instapge inbuilt integrations.

**Comment by vic-topcoder** [comment]
@harshitmehta123 do you know what is needed as data from Connect? What do we need to capture and send? Can you discuss with @vikasrohit and resolve please? Thanks!

**Comment by vikasrohit** [comment]
@vic-topcoder Discussed things with Harshit. I think I know the details.

**Comment by vic-topcoder** [comment]
Please proceed with it after the "Real World Testing" release
