### ISSUE TITLE
Remove chatbot project category screen on back button

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1229]
On clicking back button from generic chatbot project there's a new category view for chatbots. We don't want to have a category for chatbots, and thus this screen should not exist.

![screen shot 1](https://user-images.githubusercontent.com/8484061/31208939-de85fce8-a93c-11e7-8f24-426064a735cd.png)

Expected: Clicking on back button should show the main project list page
![screen shot 2](https://user-images.githubusercontent.com/8484061/31208940-e1bfb7f0-a93c-11e7-89ab-141398c0c4ce.png)
![screen shot 3](https://user-images.githubusercontent.com/8484061/31208944-e47c3ec8-a93c-11e7-89b5-a51be2eb4fad.png)

**Comment by vikasrohit** [comment]
Thanks for catching it. Fixed it now.
