### ISSUE TITLE
Project Wizard breaks browser navigation - back and forward

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1233]
The users should be able to navigate between the wizard pages using just the browser back and forward buttons. Any time we see a new page, it should behave with the browser default history - we must fix this. It is very very important as everybody uses back and forward buttons on browsers!

**Comment by vikasrohit** [comment]
How it is different from #1205

**Comment by vic-topcoder** [comment]
The browser navigation buttons are different from the wizard back button.

Wizard back button:
<img width="89" alt="screen shot 2017-10-06 at 8 54 44 am" src="https://user-images.githubusercontent.com/8484061/31286763-0c4e0fde-aa74-11e7-96a5-f26abcdf2be1.png">
Browser navigation buttons:
<img width="416" alt="screen shot 2017-10-06 at 8 54 50 am" src="https://user-images.githubusercontent.com/8484061/31286770-12a55392-aa74-11e7-879d-063a85c5c8ab.png">


The wizard back button behavior is correct at the moment (image 1), but the browser navigation buttons (2) do nothing to navigate between pages/screens when in the wizard. This is bad UX as people use the browser navigation to get between pages. Right now when you click on the back button, in logged out state the URL bar string is changing, but the page is not reloading/responding to the change. In Logged in view nothing seems to happen - no URL bar text is changing, nor the pages are changing.

We have to support native browser navigation when going between pages, at all times. The browser navigation is important and going between pages should create history of all pages visited. That behavior is disabled for the moment.

Wizard back button behaves differently as it provides a "bubble up" navigation outside from a project template creation form to category, and wizard main page. This behavior is working as it should in #1205. We don't want to modify this button.

**Comment by vikasrohit** [comment]
@vic-topcoder I think we created #1205 for handling the browser back button only. Anyway, I have already implemented that behaviour in the [feature branch](https://github.com/appirio-tech/connect-app/tree/feature/back-forward-button-project-wizard) and got it deployed to dev environment for a particular day. I want to make sure it does not break anything else, hence, would like some one else to play with it before getting it merged into dev.
I would deploy it again today to dev so that you can test the feature, if you get some time.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey I have got it merged into dev. Would it be okay to release this with https://github.com/appirio-tech/connect-app/milestone/15 release? If not, I have to revert it back.

**Comment by vic-topcoder** [comment]
Works good to me - navigates between the pages ok. Only exception is the missing "incomplete project" page that doesn't show. I'll add another issue to close this one.
