### ISSUE TITLE
Deep link doesn't open proper page if a project was not completed and user clicks "Create New Project"

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1235]
When a user has canceled a project creation and they go to a specific deep link (https://connect.topcoder.com/new-project/watson_chatbot) the system shows the correct "Unfinished screen"

![screen shot 5](https://user-images.githubusercontent.com/8484061/31294364-7923449c-aa8f-11e7-9af0-4801c24dee92.png)

Upon clicking on "Create a new project" the system ignores the deep link and redirects to the project main screen.

![screen shot 6](https://user-images.githubusercontent.com/8484061/31294394-94996670-aa8f-11e7-97ed-46d10da8a4b0.png)

The system should respect a deep link (direct link) and load an empty form for that URL instead of home screen. Expected to see:

![screen shot 7](https://user-images.githubusercontent.com/8484061/31294423-ad94b210-aa8f-11e7-961c-473afcd7f20c.png)

This is a new case for deep links only. The "Create a new project" should redirect to main screen if we don't have a request for a specific project creation form.

Can we add this logic check to the incomplete project verification? If a request is for a valid project form, load the form. If it is not, load the main project selection page.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey more or less this is something I am talking about in #1104. May be my description was not straightforward. Now I will augment this issue with more details.

> When a user has **canceled** a project creation and they go to a specific deep link 

What does the cancel mean? 

> Can we add this logic check to the incomplete project verification? If a request is for a valid project form, load the form. If it is not, load the main project selection page.

If we consider, user closing the tab/browser as cancel intent (for my previous question), then I am not able to understand the existence of 'Incomplete Project' screen at all. If we alway load the form for a valid deep link, would user ever land on incomplete project screen?

That is why I am suggesting [this](https://github.com/appirio-tech/connect-app/issues/1104#issuecomment-329694958)

**Comment by vic-topcoder** [comment]
> What does the cancel mean?

Cancel means the customer has opened a project creation form, entered some details, but didn't use the "continue" button.

>If we consider, user closing the tab/browser as cancel intent 
This is true

>If we alway load the form for a valid deep link, would user ever land on incomplete project screen?
That is not the behavior that we anticipate. The particular case here is when the new project creation form is triggered through a deep link. Most of the time the project creation would start from a  "Create project" button (main page).

>  I am not able to understand the existence of 'Incomplete Project' 
It is a storage of the form data from a previously created project. Clicking on "continue from where I left off" restores previous session details. So far this works as expected - the user is redirected back to the project creation form with the session data pre-populated.

>@vic-topcoder I think two tier menus, is good opportunity to handle this issue. I am thinking if we should directly show the project details form when user is coming back to the new project flow for the same project category and product i.e. if user has accessed /new-project/visual_design/wireframes previously and closed the tab and opens the same marketing link (/new-project/visual_design/wireframes) or refreshed the page somehow, we should take user to the project details form. However, if user clicks some different marketing link e.g. /new-project/visual_design/visual_design_concepts, we should show the incomplete project confirmation to user.

This is the same behavior we're describing in here. This is important as there are hidden deep links that customers may lose if the system redirects them back to main project menu instead to the correct project form.

Hope this explanation is clear(er) for what the case is.

**Comment by vikasrohit** [comment]
@vic-topcoder I have updated your comment to do some formatting. 😬

**Comment by vikasrohit** [comment]
Should be fixed and changes available in dev env.

**Comment by vikasrohit** [comment]
Verified on production. Seems to work fine to me.
