### ISSUE TITLE
Steps needed to push Dev to Release 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1236]
We changed the generic "chatbot" project category to "all-chatbots", and "generic_chatbot" project type to "chatbot"; "watson_chatbot" remains the same.

In order to update the Elastic Search (ES) cache for the changes on the existing chatbot projects, we had to recreate the whole cache. @mtwomey wrote a tool to do so.

For the push to production, we have to:

1. Deploy the project service;
2. Update the Database records of all existing `chatbot` projects to match the new `all-chatbots`;
3. Update the ES cache so projects will be listed on main page;
4. Update CloudFront servers (reload cache).

@vikasrohit - is there a way to partially update existing ES cache to reflect the updates on the old DB records? If so - how do we do it? We have only 2 projects that are `watson_chatbot`. The DB update is super quick, but the update of ES cache is slow. Please ping @mtwomey if we have a better solution, because he wrote a tool to update the cache.

**Comment by vikasrohit** [comment]
I got better idea @vic-topcoder @mtwomey. I am never in favour of direct updating database (updating ES is okay as it it not a source of truth and can be updated to facilitate new use cases). And as far as tool for updating index in ES for project is concerned, I think we already have one here https://github.com/topcoder-platform/tc-project-service/tree/dev/migrations.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey if you still think the database update worth it, I think we can use https://github.com/parthshah/aws-es-cli to update  records selectively instead of rebuilding whole index. I have done one member index update in past using this utility.

**Comment by vikasrohit** [comment]
@vic-topcoder as per slack discussion I am doing changes to allows us achieving SEO friendly URLs without updating database here #1240
