### ISSUE TITLE
Connect Admin role

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1243]
Create a new high level Connect Admin role that can do everything in the system faster and doesn't go through typical user flows

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-13

**Comment by vikasrohit** [comment]
@vic-topcoder Once we do it, we might have to run a batch job which updates existing user's (who already have Connect Manager and Administrator roles) role to give them admin role.

**Comment by vikasrohit** [comment]
Feature is in dev. @vic-topcoder Let me know if you face any issue with it. Right there is only one user(vikasrohit14) with 'Connect Admin' role. I have added a new user `tc_connectAdmin` for this purpose but I am not able to assign the role to this user as it seems admin app in dev is broken and it is not allowing me to do any operation. Meanwhile, you can try with `vikasrohit14`.

**Comment by vikasrohit** [comment]
Found following issue after introducing Connect Admin role:

- [ ] Duplicate buttons for removing a team member
<img width="352" alt="screen shot 2017-12-12 at 5 13 06 pm" src="https://user-images.githubusercontent.com/2417632/33883015-229a64ba-df60-11e7-8ce4-66918700ff19.png">

**Comment by vikasrohit** [comment]
Fixed duplicate Remove button issue in dev.

**Comment by vic-topcoder** [comment]
@mtwomey - can you review that the Connect Admin role is different than the "administrator" role. I would like to have a consensus from the team and review before we release.

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey In Connect, right now `Connect Admin` role has same privileges as of and `administrator`. The difference in these two roles is the ability to access other topcoder applications. `Connect Admin`s can not access other topcoder applications as administrator unless they have `administrator` role as well.

**Comment by vikasrohit** [comment]
@vic-topcoder Can you please review it?

**Comment by mtwomey** [comment]
@vikasrohit Thank you - I think we're all set on this one!
