### ISSUE TITLE
Admin view of projects

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1244]
Reuse the grid view of projects to allow for admin functions - add/modify organizations, set project status. We can either allow this view on the current project view, or switch to a new page URL, reusing the same components (the question is why an admin should navigate to 2 pages).

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-17

**Comment by vic-topcoder** [comment]
Design here: https://drive.google.com/drive/folders/0B1LbmKnex41fcDc0eVFPcldLckU?usp=sharing

**Comment by vikasrohit** [comment]
I think this is overall change for admin view of project listing and is being handled via #1376

**Comment by vic-topcoder** [comment]
Duplicate, closing
