### ISSUE TITLE
Admin can set status without joining the project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1245]
Admins should have edit permissions enabled at all times for all projects. The system should not generate notifications unless we specifically establish so (An admin just canceled your project, and admin edited somebody's post - we should keep admin activity inconspicuous).

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-18

**Comment by vic-topcoder** [comment]
Design spec is here: https://drive.google.com/drive/folders/0B1LbmKnex41fcDc0eVFPcldLckU?usp=sharing

**Comment by vikasrohit** [comment]
@vic-topcoder Feature is almost there with #1307 being deployed to production. Now I think only thing remaining in this issue is to keep Admin's activity silent, right?

**Comment by vic-topcoder** [comment]
Correct! I'm writing up new features for the next iteration, keeping admin actions silent would be one of them.

**Comment by vikasrohit** [comment]
Okay. Let me when you have something to put on my plate.

**Comment by vikasrohit** [comment]
I think this change is being handled via #1376 (sub issue number 12)

> Status icon - update with the status icons with the latest from customer list view. Admins should be able to set the project status through the same drop-down menu as in project details page directly on the grid. On hover spell the current project status as tooltip (In Review, etc.).

**Comment by vic-topcoder** [comment]
Yes, duplicate
