### ISSUE TITLE
Send project owner's user @handle to SFDC project lead object

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1247]
when a lead is created in SFDC from connect, we want to set the lead's handle in SFDC linking to its profile page to be able to open profile page quickly.

Nikita: I will create a field on SFDC ..on lead object..with the API name handle

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-76

**Comment by vikasrohit** [comment]
Picking this one in current release as we are adding two fields to SFDC integration in current release under #1270
