### ISSUE TITLE
Feature picker || Custom feature is shown as form even after adding the feature

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#125]
As per design the custom feature should be shown in the same way we are showing standard features i.e. without any form. However, right now we are showing the custom feature in a form. Once added, user does not have any option to save that feature so does not makes sense to show the feature in the form.

<img width="634" alt="screen shot 2016-09-21 at 1 04 35 pm" src="https://cloud.githubusercontent.com/assets/2417632/18701759/fdec7d52-7ffb-11e6-810f-5c421f9b9e7e.png">

**Comment by vikasrohit** [comment]
cc: @fnisen @vic-appirio @parthshah

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/184327383400574

**Comment by parthshah** [comment]
My 2 cents.. custom features should be shown as a form always. The form should be disabled (for updates) if the user does not have edit access to the project.

**Comment by vikasrohit** [comment]
Makes sense, but once the feature is added, there is no save/update button (only delete button is there) for the user when user has the edit access. So, to enable the user update the custom feature we need to show save/update button along with the delete button.

**Comment by parthshah** [comment]
Just like regular features we should have auto-save / update for custom features. NOTE: for now auto-save will save it back to specification page user would still have to click save to persist it to DB.

**Comment by vikasrohit** [comment]
Okay, should we then remove the save button altogether. I mean to be consistent, should we remove the save button which we show initially?

**Comment by fnisen** [comment]
I don't completely understand the question, so my two cents may not be helpful, but there is actually a two part experience: 
- Creating the feature, which has the save button (and no pill selector) and adds the feature to your list and turns it "on": 

![0476f095-cd4d-4145-b301-743df2fee6e6](https://cloud.githubusercontent.com/assets/12552247/18721588/003bfb7a-7fe6-11e6-8302-4bc569c467d9.png)

- Turning the feature on and off with the pill selector and (separately) deleting it from your list of potential features:
 
![b1a04033-f1d7-4ae6-b962-513d492e7aad](https://cloud.githubusercontent.com/assets/12552247/18721626/248de6fa-7fe6-11e6-9967-7636a82e3a48.png)

**Comment by vic-appirio** [comment]
It seems like the problem is the description field not being able to be edited once the feature is created. What we can do is to follow the regular pattern and always show the text area - being editable. This is to say that a custom feature would behave like a regular feature with the addition of a "Delete" button underneath. @fnisen would that be a solution? Good point, @vikasrohit @parthshah

**Comment by parthshah** [comment]
@vic-appirio / @fnisen regular features are defined by the application and users can enable / disable them for their project. Custom features behavior is a little different in that the user is defining the feature. Since the feature is specific to the project if a user decides to disable the feature, the feature is deleted. Delete custom feature & disabling would have the same effect.

**Comment by fnisen** [comment]
@vic-appirio can we treat the custom feature as "disposable"? Do you need to be able to edit it or can you just recreate a new one? If we don't want to make it disposable, I would add an edit option, next to delete. 

Either way, I would get rid of the pill b/c turning off the feature has the same effect as deleting it, following @parthshah's explanation.

**Comment by vikasrohit** [comment]
@vic-appirio @fnisen please check the behaviour of the feature picker for custom feature now in dev. And let me know where we want to go from there. Please try to add a custom feature, then edit it (via workaround of disabling the feature, edit the text and reenable the feature) and removing the feature completely by clicking on 'Delete feature' button.

**Comment by vic-appirio** [comment]
@vikasrohit @parthshah we did play with the interaction and discussed with @fnisen. We decided to simplify the feature creation;

**Create flow:**

1. The User clicks on "Create a custom feature" button
2. The User enters feature title
3. The User clicks on "Save Feature
4. System creates the new feature and displays the screen (similar to the regular feature).

**Selection a feature:**
1. The User selects the feature from the left menu
2. The User enables the feature through the slider
3. (Optional) User adds additional notes.

**Rename a custom feature** (optional step, we can skip this one)
1. The User clicks on pencil icon on custom feature
2. System displays the create feature form with the title of the feature
3. The user finishes editing through either "save" or "cancel" buttons

**Delete a custom feature**
1. The user clicks on the trash can icon
2. The system displays the delete alert
3. The user ends the action throughs either "cancel (default)" or "delete feature" buttons

——— 
Prototype: https://topcoder.invisionapp.com/share/5P8RNYM49#/192599284_Feature_-_On
——— 
Screens:
![feature - custom feature create](https://cloud.githubusercontent.com/assets/8484061/18936121/c9347c38-8599-11e6-96ea-afd025ede502.png)
![feature - custom feature off](https://cloud.githubusercontent.com/assets/8484061/18936124/c949acd4-8599-11e6-8c34-eddbcaac5b11.png)
![feature - custom feature options](https://cloud.githubusercontent.com/assets/8484061/18936126/c94abf7a-8599-11e6-9028-441c05023b69.png)
![feature - delete custom feature](https://cloud.githubusercontent.com/assets/8484061/18936122/c946fc6e-8599-11e6-8859-b6b2bbf15c4a.png)
![feature - off](https://cloud.githubusercontent.com/assets/8484061/18936123/c949383a-8599-11e6-8112-e971976fc42d.png)
![feature - on](https://cloud.githubusercontent.com/assets/8484061/18936125/c94a132c-8599-11e6-8fbb-ff4f68468e78.png)

**Comment by vikasrohit** [comment]
It seems completely new scope of work. So, we should not reopen the existing issue for this, rather create a new issue to track it.

Further, with this flow, I am seeing a usability issue from my point of view. It requires now few extra clicks to add a custom feature with notes. Why can't user add a custom feature with notes/description.

**Comment by vikasrohit** [comment]
Further, this new flow would invalidate the few of bugs identified in the bug hunt.

**Comment by fnisen** [comment]
@vikasrohit booking time to discuss this one with you. I think it's less complicated than it seems and will be easier to talk through.

**Comment by fnisen** [comment]
@vikasrohit confirming that we agreed on the implementation during our call. Per our Slack chat, will leave it up to you to decide whether you need API changes.

**Comment by vikasrohit** [comment]
Changes are in dev. Most of the things are working.

@parthshah for now I haven't used debounced method for change event of the formsy form. Rather I have directly associated the change handler to the on change event of the text area.

**Comment by vikasrohit** [comment]
Closing the issue as new design/flow is implemented and working fine. Any issue with that flow should be reported separately.
