### ISSUE TITLE
Notification content templates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1251]
We must define new email templates for notifications that are user friendlier. Allow to modify notifications frequency or go to notifications center on Connect.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-60

**Comment by vic-topcoder** [comment]
Design: https://drive.google.com/drive/folders/0B1LbmKnex41fVUpBQzBVdkpLOGs?usp=sharing

**Comment by gondzo** [comment]
@vic-topcoder in Profile and Settings screen, where does clicking the X icon lead to ?

**Comment by gondzo** [comment]
also, about the logo, we have the color logo, greyscale with 'CONNECT' text and in this design it is greyscale without any text. Should we change any of those ?

**Comment by gondzo** [comment]
There are some entities in notification texts: https://monosnap.com/file/E5EGLb4VvRsTE8p3pGDnWnnanQCml4
Are they supposed to be links or just bold text? @vic-topcoder 
If it's just bold, does the entire notification body link to the specific item (project, message, etc)?

**Comment by gondzo** [comment]
@vic-topcoder for each notification, there is a checkmark and a blue left border. What does the border represent ? clicking the checkmark will just mark it as read ?
