### ISSUE TITLE
Set project status without joining project (Admins + Managers)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1255]
Version 1 - allow admins to quickly set project status without joining project; limit the amount of emails sent during admin actions, set project organization as flag;

Created from Aha! https://topcoder.aha.io/features/AVD-23

**Comment by mtwomey** [comment]
@vic-topcoder Shouldn't this issue be under the other milestone?

**Comment by mtwomey** [comment]
@gondzo See Staus dropdown below. It should be available for admins, even if they haven't joined the project.
![screen shot 2017-11-07 at 4 51 25 pm](https://user-images.githubusercontent.com/7715262/32522188-f375e1ea-c3db-11e7-904a-aae8d92abf4b.png)

**Comment by vic-topcoder** [comment]
This is repeated, right. Closing it. We're working on it at #1303
