### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1259]
Create integration with the browser to send push notifications to the desktop. Would be used in a mobile app context as well

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-64

**Comment by kevinkid** [comment]
Please assign me this issue

**Comment by vikasrohit** [comment]
@kevinkid Thanks for your interest. However, only things marked with `community-task` label are usually available for community to pick up and that too only when there is some challenge is in progress for those tasks.

**Comment by kevinkid** [comment]
Got it !
