### ISSUE TITLE
Update react-router to v4 

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1266]
Target version is react-router v4.2.0
Related issue #1196

**Comment by gondzo** [comment]
This is now complete and merged to test02 branch. Are we OK for merging to dev? @vikasrohit @mtwomey

**Comment by vikasrohit** [comment]
If routing is working fine there, I guess we can merge.

@mtwomey I am okay with it as we don't have any major release coming up which can conflict with this change.

**Comment by gondzo** [comment]
Yes, router push is the major difference. Instead of router.push, we are using history.push . Also we are using react-router-dom instead of react-router module.
