### ISSUE TITLE
Project sidebar visual updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1268]
It's nice to reuse the same component from the user project view cards in the project dashboard. Beyond that, the links should be fixed to look like real links.

Design is here: https://drive.google.com/drive/folders/0B1LbmKnex41fcDc0eVFPcldLckU?usp=sharing

**Comment by vikasrohit** [comment]
@vic-topcoder Didn't get where we are to use cards view in side bar? Only changes I can see in the proposed design are:

1. % completeness of the project (I am not sure how would we determine it)
2. Hyperlink styles

**Comment by vikasrohit** [comment]
@sachin-maheshwari one thing which I got clarified while working on other updates of project listing, we do have % completeness for a project which is active and we do have a component (`ProgressBar`) for that as well. However, that component is showing horizontal bar based progress.
I have to modify that component to support circular progress bars as well, so you can use `ProgressBar` in https://github.com/appirio-tech/connect-app/tree/feature/project-listing-updates branch.

**Comment by vikasrohit** [comment]
@sachin-maheshwari These are 3 different issue. And scope of this issue is only to handle the sidebar in the project dashboard. The designs shared by Vic are for all other tasks as well. Card view is being handled by separate [issue](https://github.com/appirio-tech/connect-app/issues/1217) and changes for grid view are handled by another.

**Comment by vic-topcoder** [comment]
@sachin-maheshwari - the changes on this issue are for the project dashboard page:
![transition-updates-dashboard-update](https://user-images.githubusercontent.com/8484061/32392939-dfff0d7a-c094-11e7-83b5-43c0d83c2700.png)

The header of the left column needs to be updated to use the component from the card view on project list (customers).

![transition-updates-home---customer](https://user-images.githubusercontent.com/8484061/32392971-f4cc6ad6-c094-11e7-8e8b-98828f958b7f.png)

If we can't calculate/get the data from direct/ on what is the project % completed, we should use a solid blue circle and spell the progress as "Active".

There's need to update the progress icons everywhere (be consistent) accordingly; look at the admin overlay from project grid:
![project-status-drop-down](https://user-images.githubusercontent.com/8484061/32393038-43804f6c-c095-11e7-9d7b-c9e94c6d2455.png).

All icons are included in the attached specification folder. Make sure you download it on your local machine and navigate to ~/Assets/Status icons/
![screen shot 7](https://user-images.githubusercontent.com/8484061/32393077-6b56bbf2-c095-11e7-9c40-874e01815783.png)

**Comment by sachin-maheshwari** [comment]
PR - https://github.com/appirio-tech/connect-app/pull/1292

**Comment by sachin-maheshwari** [comment]
@vic-topcoder, project delete icon I didn't find in new design. Are we deprecating it ? or should be come on mouseover (as per current UI of 'Links') for particular 'state' and 'role' (i.e. draft and owner - same as per current logic).

**Comment by vic-topcoder** [comment]
Project delete icon is "canceled.svg".

Small updates on the side bar:
- [ ] When adding a link, the react control should update itself without reloading the whole page, or without the need to reload. Right now the link doesn't appear in the control until the page is reloaded.
- [ ] Project description text should be auto height controller. Minimum 1 line of text, maximum 4 lines, limit text excess with ellipsis and "read more" link (keep current behavior). There is a big gap right now between project status and description.
Current:
![screen shot 17](https://user-images.githubusercontent.com/8484061/32631205-56e075be-c554-11e7-83d9-9d170329fee9.png)
Expected:
![screen shot 18](https://user-images.githubusercontent.com/8484061/32631175-4719859e-c554-11e7-8e08-ba4670ba6751.png)

- [ ] Project title should be text-size: 15px; line-heigh: 20px; font-weight: 500 (medium)
![screen shot 20](https://user-images.githubusercontent.com/8484061/32631186-4bf5fb4c-c554-11e7-86db-46ae6e5fec9c.png)

**Comment by sachin-maheshwari** [comment]
@vic-topcoder, OK I'll incorporate the suggested changes ASAP.

**Comment by sachin-maheshwari** [comment]
Incorporated all suggested changes in PR - https://github.com/appirio-tech/connect-app/pull/1301

**Comment by sachin-maheshwari** [comment]
@vic-topcode, there is one pending task, white left right padding in Project delete confirmation box, at which I am still working... 
![projectdeleteicon](https://user-images.githubusercontent.com/6467888/32716020-697eca9e-c87a-11e7-860f-44be3baf6b06.png)
![prjectdeleteconfirmation](https://user-images.githubusercontent.com/6467888/32716021-69e0e95e-c87a-11e7-9af8-fba848c92de8.png)

**Comment by vic-topcoder** [comment]
Thanks @sachin-maheshwari, how are the other tasks standing? Please aslo take a look at #1303 - Administrators lost the ability to change the project status through a drop-down. We should bring that functionality back.

**Comment by vic-topcoder** [comment]
Closing this issue and will create new for visual fixes
