### ISSUE TITLE
[$50] Error in console when navigating to /login

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1276]
RedirectComponent doesn't return anything thus when navigate /login there is error in console:
`Error: RedirectComponent(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by vic-topcoder** [comment]
@mtwomey @vikasrohit FYI

**Comment by gondzo** [comment]
Thanks @zjuasmn
