### ISSUE TITLE
[$50] Console errors when viewing project specifications

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1277]
When opening project specifications there are warning in browser console:
```Warning: Failed prop type: Invalid prop `value` of type `string` supplied to `SpecFeatureQuestion`, expected an array.```

```Warning: Failed prop type: Invalid prop `addedFeatures` of type `string` supplied to `FlattenedFeatureList`, expected `array`.```

```Warning: Failed prop type: The prop `children` is marked as required in `FileList`, but its value is `undefined`.```

**Comment by vic-topcoder** [comment]
@vikasrohit @mtwomey FYI
