### ISSUE TITLE
Project cards icons are spaced wrong

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1279]
### Expected behavior
Icons should be 32px x 32px block 30px from top  and heading 20px underneath.
<img width="826" alt="screen shot 2017-10-23 at 10 59 56 am" src="https://user-images.githubusercontent.com/8484061/31896417-b62b17fc-b7e1-11e7-9031-bc2681cc2950.png">
<img width="427" alt="screen shot 2017-10-23 at 11 00 06 am" src="https://user-images.githubusercontent.com/8484061/31896422-b8f0ffb0-b7e1-11e7-934b-bcb60df927f0.png">
<img width="423" alt="screen shot 2017-10-23 at 11 00 13 am" src="https://user-images.githubusercontent.com/8484061/31896423-b9034a58-b7e1-11e7-8835-bc0aae3983f4.png">

### Actual behavior
The spacing is wrong - height and padding should be changed.

<img width="800" alt="screen shot 2017-10-23 at 11 00 32 am" src="https://user-images.githubusercontent.com/8484061/31896437-c4ea3ebc-b7e1-11e7-909c-6d286fdf547b.png">

@gondzo reassign/open for Community to fix

**Comment by gondzo** [comment]
Change is merged to dev.
