### ISSUE TITLE
Project Status: Only show Status change dropdown icon (caret) to managers & copilots

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#128]
![image](https://cloud.githubusercontent.com/assets/1987710/18707788/45e2a67c-8015-11e6-83ec-e92a7ba68d96.png)

@vikasrohit hoping you can use your css wizardry to fix this. 
Dropdown should be active & control should be visible to managers & copilots added to the project.

**Comment by vikasrohit** [comment]
Done. Changes are in dev. Tracking with asana task https://app.asana.com/0/95614844085038/184520055700212
