### ISSUE TITLE
Spelling mistake on 'Specification' page 

### ISSUE THREAD

**Issue by sachin-maheshwari** [appirio-tech/connect-app#1280]
### Expected behavior
'timing'

### Actual behavior
'timeing '

### Steps to reproduce the problem
https://connect.topcoder.com/projects/{projectid}/specification

### Screenshot/screencast
![connect_specification](https://user-images.githubusercontent.com/6467888/31949279-972d8a7c-b8f6-11e7-9a0e-d32391bf355d.png)

--

#### Environment
- OS: Any
- Browser (w/version): All 
- User role (client, copilot or manager): Any
- Account used: Any

**Comment by gondzo** [comment]
Change is merged to dev.
