### ISSUE TITLE
Change Watson Chatbot project title

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1283]
The project title for IBM Watson projects should change from
"Let's setup your Watson Chatbot project"
to
"Chatbot powered by IBM Watson®"

There are no other changes to the form or description. URL stays the same. Can we get this changes and deployed to production for tomorrow, Nov 1st, 9am PST?

@mtwomey FYI

**Comment by vikasrohit** [comment]
@vic-topcoder That title is a generic title which just replaces the project type in the placeholder i.e. it is a string template like `Let's setup your %project_type_brief% project`. If we have to update this for a particular project type, we have to support it for all project types and use the current template as default for all project types where we don't have specific title.

**Comment by vikasrohit** [comment]
Done as I described above. Will deploy it to production by EOD.

**Comment by vic-topcoder** [comment]
Looks great, awesome job, @vikasrohit
