### ISSUE TITLE
File list should include the created date and owner

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#1289]
### Expected behavior
The specifications files need to have the timestamp they were created and who created them.

### Actual behavior
The file listing does not have any timestamps or owner,   I can see it in the payload but it does not display in the view.   This should be a super easy fix and is very important to have.  If the customer says I just uploaded a new file you cant figure out what one it is.

### Steps to reproduce the problem
add a file
### Screenshot/screencast
![image](https://user-images.githubusercontent.com/1180747/32389629-4ce99d98-c099-11e7-9029-1e52c7341c82.png)

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vic-topcoder** [comment]
@gondzo - let's find how easy it is to add the "last updated" timestamp underneath the file size. Request design support from DaraK if you need help with the design/styles.

The goal is to show to the user when was the file last uploaded, if we overwrite files.

Secondary question: Can we also retrieve the user who uploaded the document? Can we also display that as a tooltip on hover over the update date?

**Comment by gondzo** [comment]
I think both are possible.
One more thing to consider regarding files is linking to them. The links expire after 10 minutes so they can't be shared at all - can't post the link in connect topic, can't add a link in the sidebar, can't share it via email. Can we explore any other strategies for accessing uploaded files? I know they are hosted on aws which makes it a bit more difficult...
@vic-topcoder @mtwomey @vikasrohit @dmessing

**Comment by vic-topcoder** [comment]
I think we should explore, but let's do that in another issue. @gondzo - what would be the ETA on this issue alone?

**Comment by vic-topcoder** [comment]
Ideally the update date should be underneath the size label - right aligned.
![screen shot 16](https://user-images.githubusercontent.com/8484061/32522406-06f08410-c3cc-11e7-9cd9-4ff9fa50ec72.png)

**Comment by gondzo** [comment]
this is now implemented and merged to dev. 
![image](https://user-images.githubusercontent.com/3051646/32589193-fe9fc8a0-c4c7-11e7-88af-90fe09513a48.png)
![image](https://user-images.githubusercontent.com/3051646/32589227-2ee2cb98-c4c8-11e7-9cc1-371d58c1dc7e.png)

@vic-topcoder @kbowerma Let me know if this looks good and if we can close this.

**Comment by vic-topcoder** [comment]
@gondzo the text size seems a bit small - let's make sure it's 13px. That's the only thing, looks great!

**Comment by gondzo** [comment]
Done. 
![image](https://user-images.githubusercontent.com/3051646/32613617-46f4bd06-c520-11e7-880e-aa8639e05c9d.png)

Closing.

**Comment by vic-topcoder** [comment]
great! Can we get this in DEV? Thanks.

**Comment by gondzo** [comment]
It should be in dev already

**Comment by vic-topcoder** [comment]
🥇
