### ISSUE TITLE
Navigation / Search: Persist filter state

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#129]
Project filters do persist state, but when I do a search and go to a project, coming back through clicking the "Projects" link the search bar is not displaying the search term, but the list view is filtered.

https://monosnap.com/file/Jen8EL5uCm2mCksN9128ohlP18puf3

**Comment by fnisen** [comment]
@vic-appirio I'm actually seeing them persist in my own testing. Would you have a video example of them not working?
