### ISSUE TITLE
Incomplete project is dropping ref code

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/connect-app#1290]
### Expected behavior
If I have a ref code and I get directed to connect it should carry it through when I get to the new project page.  This should work with the incomplete work as well.

### Actual behavior
Visting the page doesn't work

### Steps to reproduce the problem
- Start a project in connect
- Don't submit the project,  navigate off of the page
- Navigate back to this URL: https://connect.topcoder.com/new-project/?refCode=topgear
- Click start new project and you lose the code

### Screenshot/screencast
Attach or link a resource.
<img width="1173" alt="screen shot 2017-11-03 at 3 19 16 pm" src="https://user-images.githubusercontent.com/664840/32392167-d91f7d44-c0aa-11e7-9962-2575cfd11d7a.png">
--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vic-topcoder** [comment]
@vikasrohit - is this fixed? @mtwomey please review and close if deployed.

**Comment by vikasrohit** [comment]
@vic-topcoder It should be fixed in dev not in production.

**Comment by vic-topcoder** [comment]
@mtwomey - can we verify and deploy to production?

**Comment by vikasrohit** [comment]
@vic-topcoder is it required to get it before Project listing update milestone? If no, it would go along with it automatically.

**Comment by vic-topcoder** [comment]
ok, gotcha. We can release this within the full release.

**Comment by vikasrohit** [comment]
@vic-topcoder I would like to close issues only after release and verifying on production. If we close them before production release, we can miss these items in sanity testing on production.

**Comment by vic-topcoder** [comment]
OK.

**Comment by vic-topcoder** [comment]
It is still valid, tested today and the ref code from the URL parameter is not saved.

**Comment by vikasrohit** [comment]
Should be fixed now. However, there is one use case where I need opinion.

1. user has an incomplete project (with a ref code) e.g. a `real_world_testing` project with ref code `qa`
2. user lands on incomplete project screen when trying to load a deep link for another project type e.g. https://connect.topcoder-dev.com/new-project/wireframes?refCode=ibm
3. Now user chose to `Continue where I left Off` and landed on project intake form which has details, including ref code, loaded from incomplete project while the URL still has the new refCode

Now if user creates the project, it persists it with old ref code not the new one.

What is expected here:

1. Update the URL in step#3 to have the refCode with incomplete project's refCode OR
2. Update the loaded project's refCode with new one

**Comment by vikasrohit** [comment]
Deployed to production.

fyi @mtwomey @vic-topcoder
