### ISSUE TITLE
Two toaster are being shown when user updates a project's specs

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1296]
When user goes to edit the project immediately after creating it, it shows two toaster messages when user hits `Save Changes` button on the Specification tab. It does not show the toaster for project creation after user is redirected to the project details page after project creation.

<img width="1280" alt="screen shot 2017-11-09 at 4 13 45 pm" src="https://user-images.githubusercontent.com/2417632/32602909-e658b936-c56d-11e7-9773-bf713fa5421e.png">

**Comment by vikasrohit** [comment]
@sachin-maheshwari can you please check if we are getting this issue only after our recent changes for the milestone https://github.com/appirio-tech/connect-app/milestone/14 or is it there before these changes. I doubt this is happening because of react router upgrade.

**Comment by sachin-maheshwari** [comment]
@vikasrohit, i'll verify this today.

**Comment by vic-topcoder** [comment]
What is the status? Please review & close

**Comment by sachin-maheshwari** [comment]
didn't get sufficient time to look into this due to others major issues, trying to close this ASAP.

**Comment by vic-topcoder** [comment]
The problem seems to be the second "project was updated" fired after "project was created". Might be some sort of logic, not sure. It is not high priority as the toaster messages just disappear.
