### ISSUE TITLE
[$50] Add style and support for <sup> or <sub> text on Connect

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1299]
We need to format special characters as superscript/subscript in Connect and have no CSS styles for them. The case in question is the Watson Chatbot project.

- [ ] add support for `<sup>` and `<sub>` in Connect
- [ ] make sure the style works for any instance and makes the wrapped content 50% smaller:
`text-size: 0.5em;` and vertical position reflects the intended purpose`vertical-align: text-top`; or `vertical-align: text-bottom;`

Expected:
![screen shot 8](https://user-images.githubusercontent.com/8484061/32679879-f7774e9e-c61c-11e7-9d3a-454acdac3d89.png)
![screen shot 7](https://user-images.githubusercontent.com/8484061/32679886-fd842d3e-c61c-11e7-8f4f-ef05397df354.png)

**Comment by vic-topcoder** [comment]
@gondzo For adding <sup> on the ® mark in Watson Chatbot we need to pass that in the string in Connect - can you make sure once we have the CSS support in place we can get this added to the title of the watson chatbot project? Thanks!

**Comment by vic-topcoder** [comment]
@gondzo - what is the status of this one? Should we move it to the next milestone or it will be done within this one?

**Comment by vic-topcoder** [comment]
Moved to track into a new release

**Comment by gondzo** [comment]
@vic-topcoder Just to confirm, we need support for static and config strings only, not user input like project name, desctiption, etc ?

**Comment by sumitdaga** [comment]
can you please explain what needs to be done ..i didn't get it exactly?

**Comment by Sande3p** [comment]
verification: https://i.gyazo.com/58c9618b7d6c69070212e92337be42f5.png

**Comment by gondzo** [comment]
@Sande3p We need to add sub/sup styles for the entire project (top level styles) and update the title at 
https://connect.topcoder.com/new-project/watson_chatbot to make the 'R' symbol a <sup>R</sup>. That config is in https://github.com/appirio-tech/connect-app/blob/602be8692eec5a36c493f3f239b3e439b11da553/src/config/projectWizard/index.js

**Comment by Sande3p** [comment]
done.
verification: https://i.gyazo.com/4014614341b7af915a9e3047756b5934.png

**Comment by Sande3p** [comment]
@gondzo please check the updated commit.
