### ISSUE TITLE
Incomplete project screen is not appearing even though we have incomplete project in local storage

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1300]
After recent changes, it happens to fail to load the incomplete project screen.

**Comment by vikasrohit** [comment]
Investigation revealed that because we are clearing the redux state when user opens the new project wizard, it is discarding the incomplete project stored in the local storage.

fyi @vic-topcoder @mtwomey @sachin-maheshwari

**Comment by vic-topcoder** [comment]
Can we fix it?

**Comment by vikasrohit** [comment]
Yes, it was fixed in previous release.
