### ISSUE TITLE
Hide Cancelled projects from Customers view

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1302]
As per requirement originally mentioned [here](https://github.com/appirio-tech/connect-app/issues/1217#issuecomment-343281040) and with detailed description [here](https://github.com/appirio-tech/connect-app/issues/1217#issuecomment-343567281), creating separate ticket because this change is sufficiently complex to get it tracked separately.

**Comment by vikasrohit** [comment]
fyi @vic-topcoder @mtwomey @sachin-maheshwari

**Comment by vikasrohit** [comment]
Done. Should be up in dev.

**Comment by vic-topcoder** [comment]
ok. Closing
