### ISSUE TITLE
Bring back project status drop-down

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1303]
With the new design of the project status we lost the ability to change project status for managers.

Let's bring it back as without this we cannot release the milestone. This is crucial.
- [x] Bring back project status management drop-down for managers
- [x] Allow all managers to change status even without joining a project
![screen shot 7](https://user-images.githubusercontent.com/8484061/32746530-c80692a0-c86a-11e7-9c85-f764852f932a.png)
Expected:
![screen shot 8](https://user-images.githubusercontent.com/8484061/32746617-11ffe2b2-c86b-11e7-9d02-924f32e4fd83.png)
Design details are at #1245 and #1244.

**Comment by vikasrohit** [comment]
Yep @vic-topcoder We noticed that yesterday, and @sachin-maheshwari is working on that.

**Comment by vic-topcoder** [comment]
There is a regression in the visual style as well.

[ ] - Project status has double padding, making it too tall. It should be 40px tall, including the borders.

Current:
![screen shot](https://user-images.githubusercontent.com/8484061/32813857-24f59816-c961-11e7-8105-d827aaf34ed9.png)
Expected:
![screen shot 1](https://user-images.githubusercontent.com/8484061/32813872-3f15d5ee-c961-11e7-8c06-2d9a9e880b5d.png)
