### ISSUE TITLE
[$30] Fix alignment of disclaimer on project creation form

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1304]
Disclaimer should be left aligned. It is right now coming as right aligned. #1294

**Comment by shubhendusaurabh** [comment]
@gondzo I don't see the disclaimer on chatbot page. Is the text to be added or have I missed something?
![chatbot](https://user-images.githubusercontent.com/1818387/33182909-cb0b057e-d09b-11e7-9379-7f21a70d918e.png)

**Comment by Sande3p** [comment]
I think I know how to get this issue fixed. @shubhendusaurabh are still working on this?
