### ISSUE TITLE
refCode is not being carried forward to the project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1306]
With upgrade to `react-router` v4, we have [lost the ability to get parsed query param from `location` object](https://github.com/ReactTraining/react-router/issues/4410) which is causing the missing refCode when creating a project from deep link with ref code.
Also, due to one of the changes in previous releases, it was overriding the utm code from the project state.

fyi @vic-topcoder @mtwomey @sachin-maheshwari

**Comment by mtwomey** [comment]
@vikasrohit This still doesn't appear to work, can you please confirm again on your end?

**Comment by vikasrohit** [comment]
@mtwomey Should be fixe now with https://github.com/appirio-tech/connect-app/issues/1290

**Comment by mtwomey** [comment]
@vikasrohit Thank you - I see it working now!
