### ISSUE TITLE
Allow all managers to change status even without joining a project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1307]
Carried forward from #1303 to get better tracking for major features/changes.

fyi @vic-topcoder @sachin-maheshwari

**Comment by vic-topcoder** [comment]
Just tested it - we're halfway there. Right now I can change project status only once, and after that it is impossible to modify it.

[ ] - Enable project status drop-down for Managers at all times

There are styling issues with the drop-down:
[ ] - Menu font size is too small, should be 13px
[ ] - Active icon is missing, use the attached one

[active.svg.zip](https://github.com/appirio-tech/connect-app/files/1471944/active.svg.zip)

**Comment by vikasrohit** [comment]
@vic-topcoder the original purpose of restricting changes to certain states from other states was to prevent project being in inconsistent state e.g. if a project is cancelled, why would a manager change it to any status? We don't allow that in Direct, so we should be consistent. Further, we are syncing Direct project status with Connect project status. Right now the sync between Direct and Connect project is only limited to when a project is made active in Direct we update the same in Connect. However, down the road we might have more sync between these two applications, so it does not make sense to allow changing to certain project status from other statuses.

**Comment by sachin-maheshwari** [comment]
Meanwhile I have allowed all the managers to  changes the status on any state. It is working for all status except status change to "Active" state from any state, getting following error from backend API - "Only assigned topcoder-managers or topcoder admins should be allowed to launch a project"

**Comment by vikasrohit** [comment]
@sachin-maheshwari to fix this, we have to update the project service, which is preventing any non team member to change project status to active. This is specific check for active status only.

**Comment by vic-topcoder** [comment]
Only Admins can change project status to Active without joining project
