### ISSUE TITLE
Remove budget fields and add description to QAaS project intake forms

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1309]
Right now QAaS projects also have the budget fields, but we don't need them. The project is based on a product and we would need to provide a quick quote.

- [x] Keep budget estimate section only for the following projects:
- App
- Software/ Front-end
- Software/ Back-end & API
- Software/ Development Integration

- [x] All projects should have a Description field - currently missing in QAaS projects

- [x] Project description should be a mandatory field

- [x] Project description should be at least 120 characters to pass validation.

**Comment by vikasrohit** [comment]
> Project intake and specification forms should be identical. Please verify before closing the issue.

They are supposed to be different in terms of questions rendered. I mean new project form has fewer fields of what we have in specification form. And all fields shown in new project form are always required while user can save the form without all required information filled in the specification form, however, in specification form user can't submit for review until all required sections are completed.
Let me know if I mis interpreted the statement.

**Comment by vikasrohit** [comment]
> Keep budget estimate section only for the following projects:
We are already not showing the budget estimate section for non visual design projects.

**Comment by vikasrohit** [comment]
Added description fields to QAAS products

Adding character limit on description in separate issue #1323

**Comment by vic-topcoder** [comment]
Confirmed with Joey - budget is required only when projects are submitted for review. This means budget fields appear ONLY on specification, NOT on project creation forms.

We don't want budget on App projects; just on the initially listed ones (App ,Software/ Front-end, Software/ Back-end & API, Software/ Development Integration).

>...Budget estimate section is what we show in the project side bar ...

This is the project quick quote - displaying price estimate for the customer based on scope parameters.

**Comment by vic-topcoder** [comment]
- [ ] Remove budget estimate section from Website specification page

**Comment by vikasrohit** [comment]
> Remove budget estimate section from Website specification page

Just a heads up, I have to create new project template for website projects. It is not an issue at all, only thing is that you have to maintain a separate project template for website projects.
