### ISSUE TITLE
Navigation: top fixing position

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#131]
The sticky panels are affixed under the top navigation. They should stay 20px below the top-most element (if there's no nav, viewport, otherwise - top nav)

**Comment by mahestro** [comment]
Not sure if I followed. The two columns layout pages (dashboard, messages) are the ones with two sticky components (nav and left column). Do you mean there should be a 20px gap between the nav and the left panel displayed content? Something like this.

http://take.ms/s8RKy

Let me know @vic-appirio

**Comment by vic-appirio** [comment]
When the side panel is shorter than the viewport, it should stick at the top, with a visible gap of 20px between the side panel and the top navigation.

![screen shot 2016-09-21 at 6 53 09 pm](https://cloud.githubusercontent.com/assets/8484061/18734814/d020abf6-802c-11e6-9f18-e082e0dabe10.png)


When the navigation is taller than the viewport, it should scroll with the content and affix at the bottom.

![screen shot 2016-09-21 at 6 52 25 pm](https://cloud.githubusercontent.com/assets/8484061/18734818/e0dd5aca-802c-11e6-9261-2b67588d2df3.png)

This behavior copies the Facebook side column one

**Comment by mahestro** [comment]
Got it! Thanks.
