### ISSUE TITLE
Navigation is not scaling well for responsive design

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1310]
Top bar navigation with search bar is not scaling well for smaller screen sizes. The search bar obscures the navigation and is not scaling well. By design, the search bar should be centered.

This behavior is caused by non-equal `flex-grow: 1/0` and setting width at the parent container of the logo. Cleaning those two will help with the responsiveness of the layout.

Current:
![screen shot 30](https://user-images.githubusercontent.com/8484061/32813045-feaccf34-c95c-11e7-8a6a-9b5fe9d9210f.png)
Expected:
![screen shot 1](https://user-images.githubusercontent.com/8484061/32813048-06c9e7b0-c95d-11e7-9cf3-fca95e92da94.png)
Note: calculate your deserved `min-width` as I set it just for example.

Test the responsiveness of the layout and limit the viewport to `min-width: 768px` as we aim to be tablet-friendly. Making the window smaller is not optimized yet.

**Comment by vikasrohit** [comment]
@vic-topcoder Fixed. I didn't need to specify min-width of the logo-wrapper to get it fixed tough.
