### ISSUE TITLE
[$50] Product cards are not responsive

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1311]
The product cards are fixed width and do not use the available space well. We might want to convert them to a responsive cards (min-width: 280px, max-width: 460px) to better utilize the space available.

**Comment by sumitdaga** [comment]
do you mean these cards? https://goo.gl/RucM4i

**Comment by Sande3p** [comment]
verification: https://i.gyazo.com/26c89000658bb3fbb6936c884492dca8.png

**Comment by gondzo** [comment]
Thanks @Sande3p
