### ISSUE TITLE
[$30] Sidebar links menu

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1313]
When there is a link with text spanning more than 2 lines, the line-height is not optimal for reading. Fix the styling so the line-height is 20 pixels. Introduce additional space between the elements.

Current:
![screen shot 20](https://user-images.githubusercontent.com/8484061/32813280-2c4f43da-c95e-11e7-9cbe-5be81ab449e9.png)
Expected:
![screen shot 19](https://user-images.githubusercontent.com/8484061/32813283-309f3e0e-c95e-11e7-8166-959314b1ebf5.png)

**Comment by sumitdaga** [comment]
can you provide test logins where projects are already created, etc?

**Comment by gondzo** [comment]
You can log in with pshah_manager/topcoder123 or create your own account

**Comment by sumitdaga** [comment]
https://goo.gl/3ZWtVB

**Comment by sumitdaga** [comment]
possible to see these "sidebar links menu" without creating a project/loggin in?

**Comment by gondzo** [comment]
thanks @sumitdaga 
In the future, please create pull requests from your forked repository, no need to create branches in this one.

**Comment by sumitdaga** [comment]
thank you @gondzo 
cool! ...will keep that in mind
