### ISSUE TITLE
[$60] Replace SVG used as css-backgrounds with active SVG in HTML

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1314]
We have used .png and .svg as CSS background elements. This technique is not optimal (additional round-trip to the server, multiple images, lack of control of the SVG properties, etc.) and we should replace all the SVG and PNG background images with active SVG inserted in the code. This allows us to control the properties with CSS.

Example:
![screen shot 16](https://user-images.githubusercontent.com/8484061/32813350-8eb36ea2-c95e-11e7-97dd-6c00996dd119.png)

Expected SVG as:
![screen shot](https://user-images.githubusercontent.com/8484061/32813376-bd6a934c-c95e-11e7-8bd9-8ac0bbb80117.png)

Project status drop-down:

![screen shot 18](https://user-images.githubusercontent.com/8484061/32796665-4678cf9a-c924-11e7-867f-f0a16a1dcf5c.png)

[ ] - The down caret symbol should be included as .SVG too and modify the color through `fill: #HEX` 

![screen shot 16](https://user-images.githubusercontent.com/8484061/32796676-4af4c8c6-c924-11e7-968d-4d424a3fa0b9.png)

NOTE: Make sure the inserted SVG uses specific class modifier. Having all SVG with the same class is bad - we can't isolate a single SVG.

@birdofpreyru - please advise on the SVG technique used in the tc-community-app

**Comment by vikasrohit** [comment]
we can always isolate it with parent class selector e.g.`new-project-icon svg`

**Comment by birdofpreyru** [comment]
@vic-topcoder @vikasrohit 
[`babel-plugin-inline-react-svg`](https://www.npmjs.com/package/babel-plugin-inline-react-svg)

Just drop this plugin into Babel setup, and then you can do:
```js
import MyLovelySvg from 'path/to/my-lovely.svg';

export default function Component () {
  return (
    <div>
      <MyLovelySvg />
    </div>
  );
}
```

and it also allows to pass in props, as for a regular React component.

**Comment by vikasrohit** [comment]
@vic-topcoder @birdofpreyru we are using [svg-react-loader](https://github.com/jhamlet/svg-react-loader) for loading SVG as inline object.

**Comment by birdofpreyru** [comment]
@vikasrohit doing it via Babel plugin is better, cause unlike Webpack loader, it will work exactly the same both server- and client-side.

**Comment by vikasrohit** [comment]
Though we are not using server side rendering right now in connect, it makes sense.

@vic-topcoder However, we should update our existing component `SVGIconImage` to use this babel plugin, if we really want this right now. This would prevent refactoring at multiple places and would abstract exact path details of the file from the caller.

**Comment by birdofpreyru** [comment]
@vikasrohit I briefly looked at the code, it looks to me, that you should just get rid of `SVGIconImage` - no need for that once you switch to babel-plugin-inline-react-svg

**Comment by vikasrohit** [comment]
@birdofpreyru I am just trying to avoid exposing the exact path of the image every where. With abstraction of `SVGIconImage` we can just pass the svg file name directly to the caller component instead of importing the svg in the caller. Further, I would require lot of refactoring if just remove SVGIconImage from the picture and directly import images in calling components.

**Comment by vic-topcoder** [comment]
I trust you guys can handle the technical details. Replacing the SVG is important, but not a high priority. That's why the issue is available for the community - I would suggest we do a code refactor branch at some point where all the images are going to be replaced, so we don't end up with a code that uses 3/4/5 different implementations of image inclusion.

@gondzo, @mtwomey - please feel free to chime in

**Comment by vikasrohit** [comment]
> so we don't end up with a code that uses 3/4/5 different implementations of image inclusion.

Exactly, that is why I am trying to use an abstraction layer of SVGIconImage component. We can change this component's implementation as we want, provided we maintain the contract of the props.

**Comment by gondzo** [comment]
We should update SVGIconImage to render the svg instead of an image with svg background.

**Comment by Sande3p** [comment]
verification: https://i.gyazo.com/e48ed4976dd56cfe354a53f66ebcd6fb.png
