### ISSUE TITLE
[$30] Project type icon should display appropriate tooltip on hover

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1315]
Hovering over the project type icon right now displays the icon name. It should be replaced by the appropriate project type - same as the project title from the project creation catalogue.

Current:
![screen shot 24](https://user-images.githubusercontent.com/8484061/32813450-1a667354-c95f-11e7-8f0a-af54e5ebe63e.png)

Expected: 
![screen shot](https://user-images.githubusercontent.com/8484061/32813572-ce96d51c-c95f-11e7-922c-a8045cd67a2d.png)

Must support all major browsers.

**Comment by Sande3p** [comment]
verification: https://i.gyazo.com/2f5ddde72559c0291a92ef59d60db01b.png

**Comment by gondzo** [comment]
Thanks @Sande3p
