### ISSUE TITLE
Project status menu drop-down is not fixed

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1316]
The drop-down is not to specification.

- [x] Text size should be 13 pixels
- [x] Title should be black
- [x] Missing "Active" icon
[active.svg.zip](https://github.com/appirio-tech/connect-app/files/1473094/active.svg.zip)

Expected (except the missing icon!):
![screen shot 17](https://user-images.githubusercontent.com/8484061/32814078-43b3d3ac-c962-11e7-809a-e0c22748f43b.png)

**Comment by sachin-maheshwari** [comment]
done. PR - https://github.com/appirio-tech/connect-app/pull/1324

**Comment by vic-topcoder** [comment]
Great job, @sachin-maheshwari!
