### ISSUE TITLE
[$30] Post composer/reply formatting options background issue

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1317]
The post composer formatting buttons have a white background on a slight gray background, but they should be transparent and blend with the background.
![screen shot 22](https://user-images.githubusercontent.com/8484061/32814274-24b6b23e-c963-11e7-8d32-e75f466b3148.png)

- [x] Remove background of formatting buttons

**Comment by gondzo** [comment]
Thanks @Sande3p
