### ISSUE TITLE
Move "My projects" switch on top navigation for Managers & Copilots

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1319]
Currently the switch to filter only the users' project is hidden under the Filters menu. We want to move it permanently on the main navigation next to the new project button.

Current:
![screen shot 2](https://user-images.githubusercontent.com/8484061/32814614-eac623c8-c964-11e7-92bb-a0227b161382.png)

Expected:
![screen shot 4](https://user-images.githubusercontent.com/8484061/32814773-4c4ce3ac-c965-11e7-90d5-0a215aef1690.png)

- [x] The switch should not count as a filter in the menu!
- [x] Hide the username of all users in the main top bar - to be consistent within the whole app.

**Comment by vikasrohit** [comment]
I have analyzed all tasks under this issue and seems like I can do that, please let me know if no one has picked this yet.

**Comment by gondzo** [comment]
Please go ahead, this was not assigned yet.

**Comment by vikasrohit** [comment]
Cool, Thanks.

@vic-topcoder Please let me know which milestone you want to move it to.

**Comment by vikasrohit** [comment]
Should be deployed on dev for testing.

**Comment by vic-topcoder** [comment]
Will close when the #1367 gets fixed as well. Functionality is completed though.
