### ISSUE TITLE
Project creation: add a URL for the project creation modal page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#132]
cc @mahestro

**Comment by fnisen** [comment]
Think it's worth adding a URL b/c this just a page intended to look like a modal. Would help with tracking.

**Comment by parthshah** [comment]
we started off with a separate page with a URL for create project, then it was moved to a modal and now we want to move it back to a page?

**Comment by fnisen** [comment]
Well when you put it that way.... Tt's not a modal in the traditional sense. It's a full page modal, so it's still essentially a page. We're just hiding the nav and introducing the "x" for navigating back.

**Comment by vikasrohit** [comment]
If we create it as a page, we have couple of concerns:

1. We have to propagate the page specific details to the topbar which we are anyway doing now after the new combined topbar
2. Another concern is that with a complete page, closing the modal would cause the complete state change while being a modal, it just hides itself without any state reload.

**Comment by parthshah** [comment]
@fnisen as we discussed offline, we'll wait to hear back from you before making any changes.

**Comment by fnisen** [comment]
Guys, discussed this with Vic and Tony, and thought about it some more. tldr: this is not important right now and we'll likely need to change this experience soon anyway. I'll close the issue. Sorry for the back and forth.

More detail: Right now everyone will be accessing "new project" via the button/modal, so we don't need a separate page. Even if we were to send people to a page from the marketing site, it would only be a smooth experience if they are already logged in (b/c all of Connect is behind log in). We will probably need to create some logged out experience later and can create a separate page at that point, if needed. We're also likely to add more options to the creation page, such as other offering types, so that will again mean reworking the page.
