### ISSUE TITLE
Customer navigation link "Getting started" is wrong

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1320]
The "Getting started" link on the customer navigation is wrong. Should open "https://www.topcoder.com/about-topcoder/connect/" in all cases, right now it leads to the dev server. Not sure if that's a bug, but would be nice to view the correct page at all times.

**Comment by vikasrohit** [comment]
@vic-topcoder I am not sure how this can treated as wrong? We always try, whenever possible, to prepare dynamic URLs based on environments, so that we accidentally don't do any damage to production. I can hard code this.

**Comment by vikasrohit** [comment]
Hard code the domain.
