### ISSUE TITLE
Remove customer-specific navigation from logged out state

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1327]
Currently in logged out state visitors see "My projects/Getting started/Help" links. those should be hidden.
Current:
![screen shot 3](https://user-images.githubusercontent.com/8484061/32867084-f0404b9c-ca1f-11e7-817b-8a4d0ea86e80.png)

Expected:
![screen shot 6](https://user-images.githubusercontent.com/8484061/32867096-fe135980-ca1f-11e7-9f66-d737a033eda0.png)

**Comment by vikasrohit** [comment]
Nice catch @vic-topcoder Thanks
