### ISSUE TITLE
Webpack config - adding React-CSS-Modules

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#133]
Moving in with adding react-css-components we'll need (I assume) to cleanup the webpack config file. Currently we do import and rely on the config from https://github.com/appirio-tech/webpack-config. What are the other Pros and Cons of creating a stand-alone webpack config instead of using this one? If we want to clean up and fine-tune the environment, we won't break the existing apps. We can remove the obsolete QA environment as well (in the original file). We can stop using coffee script - transition to ES2015

**Comment by parthshah** [comment]
webpack config was introduced by Nick & Andrew I believe, @vic-appirio maybe you were part of those discussions? I dont have a strong opinion on this right now but I believe the idea is to have a consistent approach to build all our webapps. webpack config is versioned so making a breaking change shouldn't break all other apps unless those apps are upgraded to the latest version at which point we would test that app anyway.

**Comment by vic-appirio** [comment]
There is a need to introduce new plugins and processors with react-css-modules, add webpack-stylelint so we can automate the code; it is really hard to understand how to do that. Moving the webpack.config.js to a modular per-project structure would be better, we can use https://github.com/survivejs/webpack-merge to create modular architecture/templates into the `./config` folder. Moving away from another dependency and loading a ton of jade-related dependencies is a plus.

I spend some time cleaning and organizing the package.json and we can reduce the structure/dependencies. I updated all of our dependencies and the package seems a bit smaller, but still requires a lot of things. Started working here: https://github.com/appirio-tech/connect-app/tree/react-css-modules. @fnisen that's one of the reasons I asked you about the license; I did edit the read.me file.

**Comment by mahestro** [comment]
Private task in progress - Sky.

Requirements: https://docs.google.com/document/d/1EJT9dpfgoroAc3TCVQgwB16z-9LOdbzlfrrv24Gcp5Q/edit

**Comment by fnisen** [comment]
@vic-appirio can I close this issue?

**Comment by vic-appirio** [comment]
not yet. There's a small change needed. @mahestro we need some changes so that the .svg are loading correctly - right now the resources are not picked up at my local environment. Can you put another task as I have a bit more requirements:

- [ ] Fix the path resolution for resources within CSS - right now the path alias works with "require", but for resources it is not; thus we can't load the appropriate .SVG icons; Ideally we'll have the [react-svg-loader](https://github.com/jhamlet/svg-react-loader) picking up the resources and loading icons as React components;

- [ ] Add [StylelintFMT](https://github.com/morishitter/stylefmt) to the project - on save we can automatically format the (S)CSS the way we want it.

**Comment by vic-appirio** [comment]
Merged into #511
