### ISSUE TITLE
The same project is shown multiple times

### ISSUE THREAD

**Issue by ThomasKranitsas** [appirio-tech/connect-app#1334]
### Expected behavior
`/projects` should show only the newly fetched projects.

### Actual behavior
The newly fetched projects are actually added to the view, as a result, the same projects are shown multiple times.

### Steps to reproduce the problem
- Go to https://connect.topcoder.com
- Open a project or click `NEW PROJECT`
- Go back to `/projects`

### Screenshot/screencast

http://take.ms/36Zls

--

#### Environment
- OS: macOS High Sierra v10.13.1
- Browser (w/version): Google Chrome Version 62.0.3202.94

-- 

This may be related to #1333

**Comment by vikasrohit** [comment]
Thanks @ThomasKranitsas for noticing it quickly. Just got it patched with ref to #1333
