### ISSUE TITLE
Filters are not being maintained on page refresh

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1335]
### Expected behavior
Filters should be retained on page refresh

### Actual behavior
All applied filters are reset on page refresh

### Steps to reproduce the problem
- Login as Manager/Copilot.
- Add any filter(e.g. list all draft projects) using Filters toolbar.
- Refresh the page.
- Observe that filters applied in previous steps, are removed

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot or Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
fyi @vic-topcoder @mtwomey

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey Managed to fix it. Please let me know, if you want to get it deployed it has hotfix.

**Comment by vic-topcoder** [comment]
Yes - let's deploy

**Comment by vikasrohit** [comment]
Deployed and tested on production.
