### ISSUE TITLE
Provide card view switch for Managers

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1336]
As a Manager I want to be able to switch between grid and card view for projects so I can see what my customers see.

**Comment by vikasrohit** [comment]
Do we have interface designed for showing the switch for the two views?

Ideally, it would have been great if we could have analyzed this requirement when we added support for Card Views. That helps better code organization in first place and avoids tech debts.

**Comment by vic-topcoder** [comment]
I'm building the design requirements on the side. It is part of the admin grid view interface. Here's the preview. We have to finalize the design and requirements for the next release; talked with @mtwomey to improve our process with QAaS.
![screen shot 2](https://user-images.githubusercontent.com/8484061/33103149-7f4c7a5e-ced5-11e7-922e-9b7ff37ab1bd.png)

**Comment by vikasrohit** [comment]
Okay, Thanks. So should I wait for final designs before getting started? Would you add the label `Aha! Ready to develop` when it has all requirements?

**Comment by vic-topcoder** [comment]
Correct, the label will change. I'll add the final requirement later

**Comment by vikasrohit** [comment]
I think this change is being handled via #1376 

Personally it seem quite difficult to determine which issue I should work on when we are launching community challenge for the sub set (as separate issue) of already existing issue (without referring it new issue). I am trying to link all existing issues with the new issue which community is already working on.

**Comment by vic-topcoder** [comment]
yes, duplicate. It is already in dev.
