### ISSUE TITLE
Fix the user menu drop-down width.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1337]
### Expected behavior
Menu should be wide enough to fit all text

![screen shot 3](https://user-images.githubusercontent.com/8484061/33047420-7737419e-ce0a-11e7-8e7b-ae5cf418f66e.png)

### Actual behavior
Menu is too short and elements break 

![screen shot 2](https://user-images.githubusercontent.com/8484061/33047422-7a61d604-ce0a-11e7-9e11-596b28bb36e6.png)

### Steps to reproduce the problem
Log in as user; click on user avatar

**Comment by vikasrohit** [comment]
Fixed. @vic-topcoder This issue is not in dev or production. This was issue with my feature branch which has changes for #1319. I have fixed it there, so it should not be there when it goes to dev/production.
