### ISSUE TITLE
[$60] Project creation outline panel should use the project dashboard styles

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1338]
Project creation outline panel isn't following the appropriate styles. We should reuse the project dashboard header styles.

Current:
![screen shot 8](https://user-images.githubusercontent.com/8484061/33047700-fd4fe2b2-ce0b-11e7-9b56-f34b19ef2b59.png)

Expected:
![screen shot 9](https://user-images.githubusercontent.com/8484061/33047703-0077fe02-ce0c-11e7-99f3-677f47a0f787.png)

**Comment by vic-topcoder** [comment]
@gondzo I can't see this in Dev right now

**Comment by vic-topcoder** [comment]
![screen shot 4](https://user-images.githubusercontent.com/8484061/33285520-665a4f76-d367-11e7-9a76-8282b9a9eaa7.png)

**Comment by gondzo** [comment]
The change is in dev branch, but not in dev environment, I'm not sure why.
@mtwomey @vikasrohit Is there any issue with deployment from circleci to aws ?

**Comment by vikasrohit** [comment]
I think changes are now in dev after your revert of revert PR. 😬 Cache needed to be cleaned in cloudfront to get it reflected. I cleared it now and I can see the changes now.

Reopening the issue so that @vic-topcoder can verify before closing it.

**Comment by vic-topcoder** [comment]
Verified
