### ISSUE TITLE
Navigation: Not updating on back button

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#134]
The top navigation doesn't detect the use of back button to display the appropriate state.

https://monosnap.com/file/FO7dt1lOrZwsUJ19XDcLqjruTGJKAd

**Comment by mahestro** [comment]
It happened to me a few times. I think it was with the customer role. Which roles does your test user have on this test? @vic-appirio

**Comment by fnisen** [comment]
@mahestro from the video capture, I can see Vic is using the manager role.

**Comment by vic-appirio** [comment]
I was with manager role. Didn't test exclusively with all possible roles. The same applies for regular user as well.

**Comment by parthshah** [comment]
Yep I am able to reproduce this will all users. The component isn't updating on the back button trigger. Will have to re-wire Topbar somewhat to listen to events from route changes.

**Comment by mahestro** [comment]
@parthshah Thanks for the heads-up. No wonder why this task has zero activity, no one has been able to fix it :P
