### ISSUE TITLE
Discourse topics user management

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1346]
Discourse supports groups for managing user permissions, but we are now manually managing user permissions for each topic which is causing a lot of edge cases.

We can simply create a user group for each topic and manage the group instead of updating the topic itself. We can make these changes in a shorter challenge or a private task. What do you think @mtwomey @vic-topcoder @vikasrohit

**Comment by gondzo** [comment]
I've just noticed there are even categories in discourse (user groups and topics can be added to a category). We can use that to simply have one user group in a discourse topic for one connect project, so that would greatly simplify things.

**Comment by vikasrohit** [comment]
I liked the idea about group @gondzo in fact it is really good solution for the problem. However, I didn't understand how categories are going to help us.

> We can use that to simply have one user group in a discourse topic for one connect project

**Comment by vikasrohit** [comment]
For categories based solution, we have to add a new category to each new topic?

**Comment by gondzo** [comment]
For categories we add one category per connect project and add one user group. Then we just assign all topics in a project to that category.

**Comment by gondzo** [comment]
@mtwomey What do you think about this one. Should we go for it ?

**Comment by vic-topcoder** [comment]
@gondzo is this relevant? We're getting rid of Discourse so please close if you see fit

**Comment by gondzo** [comment]
this one is still doable and worth it in the short term IMO. it will affect adding/removing users from a project. right now if a project has 20 topics we have to make 20 calls to discourse so we could add the user to all topics and that takes a while, so it can fail in case we have too many topics on a project.
@vikasrohit do you think we should do this?

**Comment by vic-topcoder** [comment]
What is the technical cost of doing this issue? Time/effort wise.

**Comment by vikasrohit** [comment]
Yes, @gondzo I am still in. I think we should do this and I think it won't take much time, something around 3-4 days should be good enough and I guess $400-$500 would be good enough for the prize money. One thing though, how would it affect the existing messages? I mean do we need to run a batch job to create groups for existing messages? If yes, I guess that would be the costlier part.

**Comment by gondzo** [comment]
yes, we would need to do a batch job to add current topics to categories - either via api calls or directly to the discourse db.
I'll add this one to CF8

**Comment by vic-topcoder** [comment]
Let's review what is the effort/cost before we go further. @mtwomey FYI.

**Comment by gondzo** [comment]
@vikasrohit the existing messages can't simply be added to categories because we are using private topics, so we need to recreate all posts/topics via the discourse api. There would be no downtime while creating the new topics and we would be able to easily revert to the current behavior without changing any data, just by reverting tc-message-service. Once we have tested the new behavior, we can delete the old data in discourse (doesn't hurt even if we leave it in). Sounds ok? 
fyi @mtwomey

**Comment by vikasrohit** [comment]
@gondzo I am not much comfortable in this approach because it would recreated new ids for every topic/post. I guess, it would also change the timestamps for all of them. Let me know if I misunderstood the approach.

**Comment by maxceem** [comment]
@vikasrohit yes, you are right ids will be changed. Regarding timestamps, API lets us update them so we can copy one of the timestamps `created_at` or `updated_at` of existent posts and put to both `created_at`/`updated_at` of the new one.

**Comment by gondzo** [comment]
@maxceem worked on this one and built a good solution, but it requires running a batch job against Discourse and would probably require some downtime, so it's better to leave this unsolved and wait for migration from discourse
FYI @vic-topcoder @vikasrohit @mtwomey

**Comment by vikasrohit** [comment]
In addition to downtime, we might get that batch job failed for production data and may have to revert it back to a previous backup. And during this whole process we might loose few messages.

IMO, we should hold on this for now. @gondzo Please don't discard the changes though, please keep them in the separate branch.

**Comment by gondzo** [comment]
ok, closing this one

**Comment by gondzo** [comment]
ok, closing this one
