### ISSUE TITLE
Move enhanceDropdown HOC to Dropdown component in react-components

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1349]
- [x] Extract enhanceDropdown HOC in separate file in react-components repo
- [x] Use enhanceDropdown HOC to get dropdown behaviour in react-components/Dropdown
- [x] Use `Dropdown` component from react-components library instead of using custom one hosted in connect-app and remove the one exists in connect-app

**Comment by vic-topcoder** [comment]
@gondzo @vikasrohit what is the status on this one? We did replace the dropdown component already?

**Comment by vikasrohit** [comment]
I did all of the changes, however, they got reverted by community to ease their task. I have to look into it again to check what is overall status with this.

**Comment by vikasrohit** [comment]
It seems the changes are there. May be they were reverted again. So, I think it good to close now. @gondzo Do you remember anything about this issue?

**Comment by gondzo** [comment]
we had double components in react components and connect repos, but the changes are merged now. closing.
