### ISSUE TITLE
[$60] Move ProjectCard and its related components to better location

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1350]
May be src/projects/components (a new folder for having all project related common components) instead of src/projects/list/components/Projects

**Comment by vic-topcoder** [comment]
@vikasrohit what is the status on this one?

**Comment by vikasrohit** [comment]
It is a tech-debt and we haven't started on this.

**Comment by amitpatra** [comment]
Please assign me. As I don't have repo access at this moment, so cant assign myself. Thanks.

**Comment by amitpatra** [comment]
@andela-jomadoye You should not pickup issue and work on them when some with no access to repo has already commented in issue about assigning the issue to them. I believe that it is against the rule as specified in the thread(https://apps.topcoder.com/forums/?module=Thread&threadID=920569&start=0). Thanks.

**Comment by andela-jomadoye** [comment]
@amitpatra Apologies, I saw `OpenForPickup` on the ticket and started working on it then raise PR. I did not see your comment. I have already raised R for this one.
I am working on issue 1994 do you want to work on that, I can un-assign myself and assign you to that. Is that okay?

**Comment by amitpatra** [comment]
@andela-jomadoye No problem :) BTW I have picked up another issue :).
