### ISSUE TITLE
[$60] Don't wrap ProjectCard in Link, instead handle click event

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1351]
Right now to make complete card clickable, we are wrapping complete card in `Link` element which creates non w3 compliant markup because it finally causes nested hyperlinks.
We need to instead make card clickable by handling onClick event.

**Comment by gondzo** [comment]
@vikasrohit I'm opening this one for the community

**Comment by vikasrohit** [comment]
👍

**Comment by gondzo** [comment]
created a followup item #1592
