### ISSUE TITLE
Extract constant for page size of load projects calls

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1352]
Right now its hardcoded anywhere we are passing page size. We need to extract it as constant, it would be easy to manager later when we would make page size dynamic as well.

**Comment by sachin-maheshwari** [comment]
PR - https://github.com/appirio-tech/connect-app/pull/1429

**Comment by sachin-maheshwari** [comment]
not sure if it is known behavior -  corresponding back-end API is giving maximum 20 results even offset value is > 20.  
https://api.topcoder-dev.com/v4/projects/?limit=50&offset=0&fields=id,name,description,members,status,type,actualPrice,estimatedPrice,createdAt,updatedAt,details&sort=updatedAt+desc
