### ISSUE TITLE
Flicker in load more button for the card view

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1353]
There is a noticeable flicker on projects listing page, when we do 'Load More' action, for a customer. This is happening because we are scrolling to top of the page on every route change and on project listing page we are scrolling it back to the user's last scroll position.

**Comment by sachin-maheshwari** [comment]
We have enhancement ticket https://github.com/appirio-tech/connect-app/issues/1373 on project listing, I believe this issue will be covered in that.
