### ISSUE TITLE
Home page: Should display Projects

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#136]
Since all that we have as a home page is projects view, let's make it our home page by default. Currently we have a blank page and there's no way to get to "Projects" section. The top nav logo should also lead to the Projects (home).

**Comment by fnisen** [comment]
Stating it more plainly:
- User logs in: taken to /projects by default
- User clicks top nav logo: taken to /projects, as well

**Comment by parthshah** [comment]
How does one get to the new home page on connect?

**Comment by fnisen** [comment]
Just to clarify, this is not a new home page. Project Listings is the home page. 
There are three ways to get there:
1. Upon first logging in, automatically taken there
2. Whenever the user navigates to a project from listings, the nav shows Projects/"Project name." Clicking on Projects gets them back to the listings
3. Clicking on the Connect logo

**Comment by fnisen** [comment]
Logged out home page will be connectv2.topcoder.com (and then connect.topcoder.com). We're running a challenge to create a simple page to put there. 

By the way, the logout button in the user menu doesn't seem to be clearing cookies consistently. I'll occasionally be redirected to the member dashboard and still be logged in.
