### ISSUE TITLE
Project name gets cut off when a link is opened from post on the project dashboard.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1362]
Currently the project name is shown in only 1 line on the project dashboard, and gets cut off if you open a new link within the dashboard, or resize the window. Upon returning to the project dashboard, the project name gets cut to the first word.

![screen shot 12](https://user-images.githubusercontent.com/8484061/33346219-cbc69964-d443-11e7-91cc-aea4e14d1b44.png)
![screen shot 13](https://user-images.githubusercontent.com/8484061/33346220-cbd7a632-d443-11e7-825e-06ff9415cba0.png)

To reproduce, resize the window on a project. 

Expected behavior:

Project name should not be cut on a project card and project dashboard. If the name requires 2 or more lines, show the lines.

**Comment by vikasrohit** [comment]
@sachin-maheshwari Can you please look into it? We are using `react-text-truncate` library to truncate the text. I think there should be some configuration param to handle this scenario.

**Comment by sachin-maheshwari** [comment]
@vikasrohit,  as explored the component react-text-truncate, there is issue with logic if your are using this component for < 2 lines.

**Comment by sachin-maheshwari** [comment]
@vic-topcoder , as mentioned above if we use react-text-truncate component with > 1 lines it'll resolve atleast 'the project name gets cut to the first word" issue. PR - https://github.com/appirio-tech/connect-app/pull/1385
I also tried below with expected behavior (without truncating). Please suggest.
![withouttruncating](https://user-images.githubusercontent.com/6467888/33369062-75ea1f94-d519-11e7-8008-97bd171d4375.png)

**Comment by vikasrohit** [comment]
@vic-topcoder I think we would need to truncate the project name for project card's header at least, if we don't want it to be truncated on the dashboard side panel.

@sachin-maheshwari I guess, we can use the library to truncate text when we have to do it for multi line text and when we have to truncate it for single line(e.g. for project name on project listing page in list view), we can use simple CSS solution (we already have mixin, in tc-ui, for that).

**Comment by vic-topcoder** [comment]
I want to show the full project name whenever possible, so please make sure we're not truncating on cards at all times. We must limit the project name field to a certain length vs. truncating text from the interface. Can we get the fix into Dev so I can see how it looks? Thanks

**Comment by sachin-maheshwari** [comment]
@vic-topcoder deployed my changes on Dev, please verify. Will we fix the "limit the project name field " issue separately or should fix in this issue ? How much limit we are planning for project name field ? I think 128 characters length would be sufficient or we can take decision by analyzing longest "completed" project name data from database.

**Comment by vic-topcoder** [comment]
This is not fixed in Dev right now. The project name gets cut on both dashboard and project cards. Please fix for Monday morning release

**Comment by sachin-maheshwari** [comment]
@vic-topcoder , my changes are not currently on dev. As checked further, in CircleCI my changes were in build#598, which is overwritten by build#599 (feature/performance-testing).

**Comment by vikasrohit** [comment]
@sachin-maheshwari I have taken latest from dev into performance-testing branch, so now even if dev's build get overridden by performance-testing build, your changes would still be there.

**Comment by vic-topcoder** [comment]
I'm going to close this issue and create another to solve the problem with the project name
