### ISSUE TITLE
[$20] Spacing of label for "My Projects" switch is off

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1367]
Label should be right-aligned and 5px from the switch

 

Screen Shot 1.png (https://topcoder.aha.io/attachments/6493654103444777670/token/7bf82582feece5cf8f1f8028ebfb47e3488bae5b4317922fff35a34ab694f5f1.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-105

**Comment by iversonLv** [comment]
Can I take this? Is it for Bug Bash5?

**Comment by gondzo** [comment]
Sure

**Comment by aretheregods** [comment]
No one had accepted this, so I accepted it and finished it.

**Comment by iversonLv** [comment]
@aretheregods I have submit a PR, you can assign yourself if my solution is rejected.
Thanks.

**Comment by iversonLv** [comment]
As I have no permission to assign myself, so I leave comment here, copilot @gondzo accept me to take this ticket.

**Comment by aretheregods** [comment]
Okay, I'll unassign it.

**Comment by gondzo** [comment]
@iversonLv you have to accept the onvitation in the email

**Comment by iversonLv** [comment]
Ops, the email is treated spam..
Thanks for your tips.
