### ISSUE TITLE
[$50] Improve the design of the link modal interface

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1369]
Let's design the link formatting interface to be with a better UX/UI. Ideally I would see the input field and buttons to format/cancel/delete/close the input. The functionality is ok, but the UI is a bit confusing to use at first glance.

Screen Shot 9.png (https://topcoder.aha.io/attachments/6493656257511491266/token/9b77a3a583d8c39256da3672e23c6cbda7e84a75ce349e7ce3daee65b402440b.download?size=original)
Screen Shot 8.png (https://topcoder.aha.io/attachments/6493656257578539631/token/44209c5b0b0752ff2bf632569162d644ea835bc4948ccaf72fa9022f6a2b8cfd.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-108

**Comment by gondzo** [comment]
Also, clicking the link button without selecting any text does nothing. Should we show some toast message to guide the user to first select the text that should be the link text?

**Comment by gondzo** [comment]
@vic-topcoder What is that middle icon in https://topcoder.aha.io/attachments/6493656257511491266/token/9b77a3a583d8c39256da3672e23c6cbda7e84a75ce349e7ce3daee65b402440b.download?size=original

**Comment by vic-topcoder** [comment]
This removes the link, but until you click it, you can't figure it out.
