### ISSUE TITLE
Project Filters: Use react-select for multiple select

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#137]
We need to be able to stack several project type and states on the filters. We should "react-select" for multiple

**Comment by mahestro** [comment]
Cool! What other features should we consider for this? I was playing with the component and it has several options:

- Searching (autocomplete).
- Multiple stacking (adding tags with x icons to delete).
- Clear all (x at the end of the dropdown component).

http://jedwatson.github.io/react-select/

What do you have in mind for a design of the tags? @vic-appirio

**Comment by fnisen** [comment]
This one is not needed for the beta release, by the way, so please don't work on this ahead of other things @mahestro

**Comment by mahestro** [comment]
@vic-appirio Hey amigo, hang around this fun issue when you have a chance. Check my previous comment.

**Comment by vic-appirio** [comment]
Not needed for the beta; I'd love to have:
- multiple select
- clear (reset);

The behavior from Multiselect example is ideal from my understanding.

![screen shot 2016-10-13 at 4 27 16 pm](https://cloud.githubusercontent.com/assets/8484061/19370682/1034d0b4-9162-11e6-9b4e-1f840a5e94f5.png)

Styled:
![screen shot 2016-10-13 at 4 29 14 pm](https://cloud.githubusercontent.com/assets/8484061/19370702/33f65194-9162-11e6-9de4-290d78525f27.png)

**Comment by vikasrohit** [comment]
@fnisen This one is good candidate for a stand alone F2F code challenge I guess. We should scope all instances of dropdown, used in the application, to be updated with react-select. It should be done in a way which does not require too many changes in the way dropdown is being used in application i.e. SelectDropdown component from react-components repo should be used for all instances and this component should be updated without altering too much in its API (props).

what do you think @gondzo

**Comment by vic-topcoder** [comment]
@gondzo let's break this into action plan for community fixes please.
