### ISSUE TITLE
Admins should be able to add people to a project without joining

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1371]
Admins should have the "Add member" feature working on a project without joining.

Screen Shot 7.png (https://topcoder.aha.io/attachments/6493677285403981893/token/e09aec5eb695e347150715b885475b5a79d1a13183696a51a73d3d876a57f39d.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-110

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by vikasrohit** [comment]
@vic-topcoder Should we allow admins to remove customers as well? Right now even managers don't have that privilege.

**Comment by vic-topcoder** [comment]
Yes, please! There are several recent cases where the owner was a manager and we had to remove him from the owner role.

**Comment by vikasrohit** [comment]
Done. Changes should be in dev.
