### ISSUE TITLE
[$120] Replace project paging with lazy loading

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1373]
Replace the project paging control with a lazy load that would allow to show more projects when the end of the current list is reached. The goal is to reduce the reloading and multiple clicking.

1. Show 20 projects to start with (faster page load) and a button "show more projects". Once the button is clicked, keep auto-loading projects when the user approaches the end of the page.
2. When the user reaches the end of all projects, display a label  "No more [project\_type] projects".
3. Preserve the position of the scroll so when the user comes back they would see the state of the page when they clicked on a project. 

Final design from here:  [https://drive.google.com/drive/folders/1AbIzCycuhTBh7WNCiaD0mYVMXjeGSdd3?usp=sharing](https://drive.google.com/drive/folders/1AbIzCycuhTBh7WNCiaD0mYVMXjeGSdd3?usp=sharing) This is a sketch live design, make sure to download the folder and open the index.html to explore all the artboards.

transition-updates-project-grid-full-list---admin-copy.png (https://topcoder.aha.io/attachments/6493702295804433116/token/52f5d31028a1591d8d45555cb3ef02eb31401df74039c489f3dafcd2d86f6f80.download?size=original)
transition-updates-project-grid-full-list---admin.png (https://topcoder.aha.io/attachments/6493702296587651430/token/a5a408dab12813f3ea7cc15bb45cad3b64af57a68e761e0da099801aa02830d5.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-115

**Comment by maxceem** [comment]
Browser URL is getting updated with the current page number. So let's say we scroll 10 pages with lazy load so in the browser URL it will be `page=10&sort=updatedAt%20desc&status=in%28draft%2Cin_review%2Creviewed%2Cactive%2Ccompleted%2Cpaused%29`.

If we **reload** the page with such URL or share the URL with somebody who opens it. We are supposed to show page number 10 to a user in such case.
- Should we just show page 10 and after lazy load page 11, 12 and so on? Though in this case user cannot see the beginning which can quite confusing.
- Or should we initially load 10 pages? It can be quite a lot, as a user already could be on page 100 or something.
- Or just remove page number from the URL, so if user **reloads** the page or open page by the link, he starts scrolling from the beginning. As for me, this the best solution.

**Comment by maxceem** [comment]
## Implementation notes:
- Infinite scrolling implemented for both `grid` and `card` view
- `page` param was removed from the URL
- **NOTE** As I don't have a user with proper credentials to test `grid` view I tested solution by temporary patching some `isPowerUser` flags in the code. If you could share credentials for a powerful user I can test in real conditions.


## Fixes
- When go to the next page `&status=in%28draft%2Cin_review%2Creviewed%2Cactive%2Ccompleted%2Cpaused%29` was added to the URL. Though it shouldn't. This part of requests is just inner mechanism of filtering canceled projects for regular users.


## Possible issues

- On the projects list page, in `cards view` mode, there is warning in browser console:
  ```
  warning.js:35 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See ProjectCard > Link > a > ... > ProjectCardBody > Link > a.
  ```

- Looks like some projects in the list cause the next three warning in `grid view`:

  ```
  Warning: Failed prop type: The prop `handle` is marked as required in `UserWithName`, but its value is `undefined`.

  warning.js:35 Warning: Failed prop type: The prop `firstName` is marked as required in `UserWithName`, but its value is `undefined`.

  warning.js:35 Warning: Failed prop type: The prop `lastName` is marked as required in `UserWithName`, but its value is `undefined`.
  ```

  I blame project with id `271`, because he has `Unknown` value is the `Customer` column.

**Comment by vic-topcoder** [comment]
> If we reload the page with such URL or share the URL with somebody who opens it. We are supposed to show page number 10 to a user in such case.

That's a great question. There are 2 possible cases:
1 A. User is in the system, scrolls to a page, goes into project, hits the browser back button. In that case the user should preserve their spot on the page. Ideally the list would be persisted.
1 B. User is in the system, scrolls to a page, goes into project, hits the "View all projects" - same behavior (preserve active page).

2 A. The user is in the grid, hits reload of the page - reload the feed from the beginning.
2 B. User uses filters/search after being deep in the feed - reload the feed from the beginning.
2 C. Sharing URL from within the system - I'd assume the user wants to share a specific project instead of a specific page. With a dynamic system it is hard to preserve the same project order for a long time; too many project activity is happening at the same time. In that case loading the project grid from the beginning probably would be best.

The best would be to use the third approach. The only case to keep the spot on the feed is when you enter a project and come back

**Comment by maxceem** [comment]
> The best would be to use the third approach. The only case to keep the spot on the feed is when you enter a project and come back

Great, this exactly how I did it.

**Comment by gondzo** [comment]
looks good. merged to bugBash05.

**Comment by sachin-maheshwari** [comment]
@gondzo I found one issue in corresponding changes (in card view)- new project is not coming in project listing if you hit/browse "VIEW ALL PROJECTS" link (from project detail/dashboard page) immediately after creating new project.

Also in grid view, I am getting following error  -

ProjectsGridView.jsx:181 Uncaught (in promise) TypeError: Cannot read property 'firstName' of null
    at Object.renderText (ProjectsGridView.jsx:181)
    at renderColumn (ListItem.jsx:19)
    at Array.map (<anonymous>)
    at new ListItem (ListItem.jsx:25)
    at eval (createClassProxy.js:95)
    at instantiate (createClassProxy.js:103)
    at ListItem (eval at proxyClass (createClassProxy.js:NaN), <anonymous>:4:17)
    at eval (ReactCompositeComponent.js:305)
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:304)
