### ISSUE TITLE
[$120] Add project status filters as tabs for project grid

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1375]
Display the project status filters as tabs on top of the project grid. The goal is to allow managers/admins to quickly switch between the different statuses.

Final design from here:  [https://drive.google.com/drive/folders/1AbIzCycuhTBh7WNCiaD0mYVMXjeGSdd3?usp=sharing](https://drive.google.com/drive/folders/1AbIzCycuhTBh7WNCiaD0mYVMXjeGSdd3?usp=sharing) This is a sketch live design, make sure to download the folder and open the index.html to explore all the artboards.

transition-updates-project-grid-full-list---admin-copy.png (https://topcoder.aha.io/attachments/6493699665354541653/token/1c74d154d50c092c23331b41c6071eaf3653747c13573851db0ec685b2215aee.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-113

**Comment by gondzo** [comment]
@shubhendusaurabh These should not be added to ProjectsCardView, but to ProjectsGridView as shown in the designs. Can you please update the PR ?

**Comment by shubhendusaurabh** [comment]
@gondzo Updated.

**Comment by gondzo** [comment]
thanks
