### ISSUE TITLE
[$400] Update Manager/Administrator project grid view

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1376]
Update the project grid view to match the final design from here:  [https://drive.google.com/drive/folders/1AbIzCycuhTBh7WNCiaD0mYVMXjeGSdd3?usp=sharing](https://drive.google.com/drive/folders/1AbIzCycuhTBh7WNCiaD0mYVMXjeGSdd3?usp=sharing) This is a sketch live design, make sure to download the folder and open the index.html to explore all the artboards.

 

Changes:

1. Replace the project type with the appropriate project type icon.
2. Project title is only 1 line, cut the characters with "…" to fit.
3. Move the project ref code in line with the project title.
4. Remove the project creation date, Add project description up to 2 lines, cut the overflow with "…"
5. Only one timestamp column. Allow the viewers to sort by a drop-down by
  1. Last updated (default)
  2. Oldest first
  3. Newest first

6. Add the user that performed the timestamp action (last update by, created by)
7. Customer column - remove avatar, allow for bigger space, remove user @handle, replace by project segment (when supported). On hover show the full customer data (avatar, names, handle, link to SFDC record (if any)).
8. Managers column - show only avatars, list the first 3 managers as avatars, add the number of remaining managers
9. Status icon - update with the status icons with the latest from customer list view. Admins should be able to set the project status through the same drop-down menu as in project details page directly on the grid. On hover spell the current project status as tooltip (In Review, etc.).
10. Completed and Canceled projects should have a darker gray background.
11. Projects with unread posts/activity/notifications should have a blue 2px left border.

 

transition-updates-project-grid---all-statuses.png (https://topcoder.aha.io/attachments/6493699253561054095/token/4d9af08c08129e471096a522ca0d77b82924f9066f36b539e9269d1ab8f7d11e.download?size=original)
transition-updates-project-grid-full-list---manager.png (https://topcoder.aha.io/attachments/6493699258205115707/token/e8d2d7afe5535a2313cb9b2e0f1bdb5913ef8e5f07e8a8d7b7846831ab212882.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-112

**Comment by Colinh84** [comment]
@gondzo Working on this one, but do not have permissions to self-assign yet..

**Comment by Colinh84** [comment]
@gondzo I am currently unable to proceed with this issue as I do not have read access to the google drive link posted above with the final designs file, also none of the testing accounts I have access to (Sky_, christina_uw, cp-superstar, pat_monahan) are admin accounts, so I am unable to test the necessary admin project views..

**Comment by Sande3p** [comment]
@gondzo please clarify the status of this issue. Is this open-for-pickup or on-hold?

**Comment by gondzo** [comment]
@Colinh84 you should be able to access the directory now and you can use pat_monahan/topcoder123! to log in as admin. Also please assign the issue to yourself if you want to work on it

**Comment by gondzo** [comment]
@Sande3p it's taken by @Colinh84

**Comment by Colinh84** [comment]
@gondzo ok thanks, I have access now. Also, I do not have permissions to self-assign the issue.

**Comment by gondzo** [comment]
you need to accept the invitation in the email first

**Comment by Colinh84** [comment]
@gondzo got it, thanks.

**Comment by Colinh84** [comment]
@gondzo For clarification, are the changes shown on the artboards for the top bar and filters bar also in scope on this issue?

**Comment by gondzo** [comment]
No those are handled in separate tickets

**Comment by Colinh84** [comment]
@gondzo There is one requirement that cannot be met here without adding lots of overhead: "Add the user that performed the timestamp action (last update by, created by)".

The /v4/projects/? search API does not provide "createdBy" or "updatedBy" fields for the returned projects. These data fields are only available by requesting the individual project API /v4/projects/{:id}; I do not think it is good practice to make an additional API request per each search result for this small detail..

**Comment by Colinh84** [comment]
@gondzo for part 10: "Customer column - remove avatar, allow for bigger space, remove user @handle, replace by project segment (when supported)",
 I am not sure where to find this "project segment", is it implemented in the API yet? I can put the dropdown in, but it won't do anything at the moment.. Unless I overlooked something, and you can tell me where I can find the "project segment" details.

**Comment by gondzo** [comment]
I'm not sure either. @vikasrohit is project segment something related to salesforce ?

**Comment by Colinh84** [comment]
@gondzo Another thing, for 14 "Projects with unread posts/activity/notifications should have a blue 2px left border.", I do not see how this would be possible. I have combed through the APIs, and the only place where posts/activity/notifications are flagged as unread is in the "read" field of posts returned from the /v4/topics/?filter API. It looks like I would have to make an API call for each project on the listing to find out if there are unread posts for that project, and then as soon as I make one of these API request the "read" field automatically sets to "true"; so in other words, if you even try to find out if there are unread posts, you can only see the unread status once and then they are immediately marked as read.

**Comment by gondzo** [comment]
@Colinh84 you can just set some dummy data for project segment for now, we don't have it yet.
You can skip the #14, we'll handle it separately.

**Comment by vikasrohit** [comment]
@vic-topcoder might know better.

**Comment by gondzo** [comment]
1-3 done
4 - some descriptions are over two lines > http://pokit.org/get/img/3403f4e10d01985ccc1727f961d27346.jpg
5-11 done
12 - tooltip is missing
13- ok
can you please update the PR and create a PR against bugBash05 branch, not dev

**Comment by Colinh84** [comment]
@gondzo merge conflicts and fixes have been completed, new PR against bugBash05 branch created.

**Comment by gondzo** [comment]
@Colinh84 project status filter styling is off after the merge
before merge > 
![image](https://user-images.githubusercontent.com/3051646/33830736-a18cbe94-de75-11e7-96fc-aa28d330408c.png)
after merge > 
![image](https://user-images.githubusercontent.com/3051646/33830751-b3537c3a-de75-11e7-9718-4a0dd56910cf.png)

Also, can you update ProjectListNavHeader to not require a full reload and not to add current view to url. Just wire the switchViews function to Projects.jsx and update the view. Also, in case user is not power user, card view should always be displayed, without ProjectListNavHeader 
I can increase payment for these changes +$100

**Comment by Colinh84** [comment]
@gondzo The status filter bar before merge was a duplication of the status filter bar that I had already implemented in my solution, so it was removed.  Should all of the statuses shown in the before merge be present? In the final design files I worked from, only the ones shown in the after merge picture were present.

**Comment by gondzo** [comment]
I see. You can show all the statuses, like before the merge.

**Comment by Colinh84** [comment]
@gondzo Alright, all of the requested changes have been implemented into the PR branch.

**Comment by gondzo** [comment]
Thanks. Looks good with just one minor issue: Clear all button in the filters does not work after the merge. Can you please take a look ?

**Comment by Colinh84** [comment]
@gondzo The clear all button has now been fixed in the PR.

**Comment by vic-topcoder** [comment]
I checked the development so far, and there are a bit of visual inconsistencies from the specification. Please compare the specification and the visual styling and make sure they match - bakcground colors, text size/weight/color.

Another point on scaling - certain columns should always be fixed-width - project icon, managers, and status. ID should always fit exactly the content, and description should grow most of all, followed by customer column.

**Comment by vic-topcoder** [comment]
I've fixed some style issues, but there are new bugs opened for this component - code style, use of rgba or hex colors in SCSS, project status menu in cancel mode is not visible, tooltip should not be hard coded in the grid component, the grid component in general is too hard to read, ideally should be broken down into smaller components/reuse our existing components. @gondzo please work with on the additional issues and code quality with @Colinh84. We're getting there, but let's try to fix everything before we release.

**Comment by Colinh84** [comment]
@vic-topcoder Regarding "use of rgba or hex colors in SCSS" - There are only 3 color hex codes in my scss files, which are all unique and do not match to any variable in tc-includes. There is also only 1 rgba value which does not match any variable. If you are concerned about hex and rgb values in scss files, check out the rest of the codebase where there are 94 instances of hex over 23 component scss files, and also 45 instances of rgb values over 23 other scss files.

"project status menu in cancel mode is not visible" - I do not know what you mean here, I am able to open the project status menu on cancelled projects without a problem in my testing.

I have simplified the ProjectGrid component as much as possible in my latest PR. There are a few new components for tooltips and the project manager avatar layout. The rest of the grid columns already are using existing components or are too simple to have their own.

**Comment by vic-topcoder** [comment]
for #1447 use UID: `pat_monahan`. As for the rest of the issues - they are pretty valid and we cannot release until those are fixed. The `rgba` colors should be matched to the existing color variables. I captured this issue at #1443 and it is in the entire app source code. If you have a color mismatch please point out which are the colors in question that need to be matched to the set color palette in the $tc-colors variables.
