### ISSUE TITLE
Tech Debt || Get rid of nested form element for projects with App Screens section

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1388]
<img width="1280" alt="screen shot 2017-11-30 at 2 30 11 pm" src="https://user-images.githubusercontent.com/2417632/33422272-293041ac-d5db-11e7-89b5-6211093fb50c.png">

carried from #832

**Comment by vic-topcoder** [comment]
@vikasrohit @gondzo what is the status of this one? Can we close it?

**Comment by vikasrohit** [comment]
@gondzo we need to handle this only if this does not require too much refactoring, otherwise we can close it as `won't fix`.

**Comment by gondzo** [comment]
ok, closing - it would require a lot of refactoring for the scope screen
