### ISSUE TITLE
Icon on project overview is not correct

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1392]
Fix the icon with the correct one from project card:

![screen shot 1](https://user-images.githubusercontent.com/8484061/33449851-e2ab805a-d5be-11e7-8ace-f020cdf261cb.png)

![screen shot 2](https://user-images.githubusercontent.com/8484061/33450312-3f7f560c-d5c0-11e7-9eb6-9b0b2d595d8a.png)

Should be `product-qa-website-performance.svg` 
![screen shot 3](https://user-images.githubusercontent.com/8484061/33450378-742d0552-d5c0-11e7-92c5-92271a6d4288.png)

**Comment by vikasrohit** [comment]
Fixed. Changes should be in dev by EOD.
