### ISSUE TITLE
Want to be able to add / update products by only updating / adding to the connect templates

### ISSUE THREAD

**Issue by mtwomey** [appirio-tech/connect-app#1396]
Right now when we add products, we also need to update tc-project-service and tc-message-service? 

@vikasrohit Would like to get your thoughts on this in general. Good idea? Bad idea?

Thanks

**Comment by vikasrohit** [comment]
@mtwomey I don't think we need to do any change in project service or any other service unless we introduce new project type/category. We already have some code for supporting future feature of having multiple products per project that is why we have notion of project type (or category) and product type. Project type is the major category like dev, design, qa, chatbot, website etc while products are the specific offering that we are presenting to customers e.g. wireframes, api development, real world testing etc. Whenever, we add a new product offering in existing project category, we don't need to make any change in project service, message service or tc-connect-notifications. However, if we introduce a new project type/category, we do have to make changes in tc-project-service and tc-connect-notifications, I am not sure about tc-message-service though. And if want to remove this dependency as well, we have to keep project type and product mappings in a common config like a separate npm module, a separate API or using some configuration mgmt tools/services.

**Comment by vic-topcoder** [comment]
The project catalogue is growing fast, and we need to make sure R&D is not manually releasing or editing project types and product definitions. The need is to allow multiple sources to submit their own specification and they may introduce changes. Right now the deployment of a new project or product is dependent on the services Matt mentioned.

**Comment by vikasrohit** [comment]
That is what I am try to convey that **_there is no service change required when you add new product in existing project category_.** Definitely we should make changes to make it independent for introduction of new project category as well but that would require lot of changes and rethinking how we assume project category and products. Organizations support and more fine grained roles management are also needed to allow non R&D member to do those changes, otherwise any one can make new project wizard look bad for all people.

**Comment by vikasrohit** [comment]
@mtwomey @vic-topcoder I think we can eliminate most of the dependency on tc-project-service and tc-message-service for new product addition, if we start persisting products in database. I would suggest having a new service for controlling the products catalogue. This service can be enhanced in future to support organization in which case it would return only those products which are available for the particular organization.

**Comment by vic-topcoder** [comment]
Moved as Epic to Aha!
