### ISSUE TITLE
[$40] Reference field "&" character is represented as HTML entry

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1397]
![screen shot](https://user-images.githubusercontent.com/8484061/33501913-18910648-d693-11e7-90fa-507115838fca.png)

Entered `Vic R&D` as Ref code, on project details page it reads `Vic R&amp;D`. We need to make sure such html character conversions don't show up in our fields.

Expected: `Vic R&D`

**Comment by kondakovdmitry** [comment]
The conversion from `&` to `&amp;` occurs in the v4 `projects` API. In request the connect-app sends `&`, but receives `&amp;` in response. E.g. (note the values in **bold**):

Request:
PATCH https://api.topcoder-dev.com/v4/projects/2115/
{"param":{"name":"Test project 112","details":{"utm":{"code":**"R&D pr"**},"appDefinition":{"primaryTarget":"phone","goal":{"value":"It will be cool.","seeAttached":false},"users":{"value":"People.","seeAttached":false},"budget":"","budgetType":"","whenToStart":"","deadline":"","features":{},"notes":""},"designSpecification":{"fontStyle":"","colors":"","iconStyle":"","notes":""},"devSpecification":{"platform":"","offlineAccess":"","securityLevel":"","notes":""}},"description":"Some description..."}}

Response:
{"id":"90005b23-e986-4f42-913e-8a1f96bada7e","version":"v4","result":{"success":true,"status":200,"content":{"id":2115,"directProjectId":12320,"billingAccountId":null,"name":"Test project 112","description":"Some description...","external":null,"bookmarks":[],"utm":null,"estimatedPrice":null,"actualPrice":null,"terms":[],"type":"app_dev","status":"draft","details":{"products":["frontend_dev"],"appDefinition":{"primaryTarget":"phone","goal":{"value":"It will be cool.","seeAttached":false},"users":{"value":"People.","seeAttached":false},"budget":"","budgetType":"","whenToStart":"","deadline":"","features":{},"notes":""},"utm":{"code":**"R&amp;amp;D pr"**},"hideDiscussions":true,"designSpecification":{"fontStyle":"","colors":"","iconStyle":"","notes":""},"devSpecification":{"platform":"","offlineAccess":"","securityLevel":"","notes":""}},"challengeEligibility":[],"cancelReason":null,"createdAt":"2017-12-05T22:42:07.000Z","updatedAt":"2017-12-05T22:57:45.000Z","createdBy":40152018,"updatedBy":40152018,"members":[{"id":3266,"userId":40152018,"role":"customer","isPrimary":true,"deletedAt":null,"createdAt":"2017-12-05T22:42:07.000Z","updatedAt":"2017-12-05T22:42:07.000Z","createdBy":40152018,"updatedBy":40152018,"projectId":2115}],"attachments":[]},"metadata":{"totalCount":1}}}
