### ISSUE TITLE
Support sample file for file upload section

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1400]
This is to enable user to download a template file for more detailed questionnaire for new or complex project templates. Use case came up when creating specification template for `performance-testing` offering, it contained many sections which either could not be supported because of the type of questions not supported in connect or they are dynamic.

**Comment by vikasrohit** [comment]
@vic-topcoder Capture few requirements when discussing with Dhanesh for performance testing template. Please feel free to move it appropriate milestone as per your planning or close it if you think we don't need it.

**Comment by vic-topcoder** [comment]
thanks @vikasrohit - I don't want users to download and fill a form from a project file - this would reduce the transparency of data. Ideally all data would be added to Connect and we should build the fields required to capture it. Moved to a new milestone for tracking.
