### ISSUE TITLE
Support for grouped questions for standard question types

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1401]
This is to enable the project templates which contains questions which are grouped together under single heading. Right now we support grouping at section and subsection level only. It would be good if we can support grouping e.g. multiple text boxes in single major question and each text box has its own label.

<img width="561" alt="screen shot 2017-12-04 at 1 16 42 pm" src="https://user-images.githubusercontent.com/2417632/33541499-66008f70-d8f5-11e7-8d25-b409b3569bf9.png">

**Comment by vikasrohit** [comment]
@vic-topcoder Capture few requirements when discussing with Dhanesh for performance testing template. Please feel free to move it appropriate milestone as per your planning or close it if you think we don't need it.

**Comment by vic-topcoder** [comment]
Thanks @vikasrohit
