### ISSUE TITLE
Duplicate projects in "customer" project listing immediately after creating a project.   

### ISSUE THREAD

**Issue by sachin-maheshwari** [appirio-tech/connect-app#1402]
Once you navigate the "view all projects" immediately after creating a project, there would be duplicate projects in project cart view. Once you reload the page, projects listing will be OK.

Before adding new project :-
![projectslistbefore](https://user-images.githubusercontent.com/6467888/33543920-de1ac62a-d8fe-11e7-8fdf-e438d57db3a5.png)

After adding new project :- 
![projectslistingafter](https://user-images.githubusercontent.com/6467888/33543948-f5e7c85c-d8fe-11e7-80ba-a89a306577d9.png)

**Comment by vikasrohit** [comment]
Thanks @sachin-maheshwari for finding it. It seems to be there because of keepPrevious flag. I guess we need to update the [reducer](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/reducers/projectSearch.js#L48) to handle this.

**Comment by vic-topcoder** [comment]
@sachin-maheshwari what is the update on this issue?

**Comment by sachin-maheshwari** [comment]
@vic-topcoder, doing unit testing..

**Comment by sachin-maheshwari** [comment]
There were couple of more scenarios which i covered in PR - https://github.com/appirio-tech/connect-app/pull/1456

**Comment by vikasrohit** [comment]
@sachin-maheshwari Can you please add those additional scenarios, which you got fix with your PR, in original issue description?

**Comment by sachin-maheshwari** [comment]
Additional scenarios - In description I mentioned create "new" project case but if you navigate from project listing to project detail page and come back on listing again, you will get duplicate projects.
We have another open enhancement ticket https://github.com/appirio-tech/connect-app/issues/1373 in which most of issues mentioned here are covered - which are not covered I have added note for same.
