### ISSUE TITLE
Project details/Feature picker: remove notes heading

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#141]
<img width="639" alt="screen shot 2016-09-21 at 4 27 17 pm" src="https://cloud.githubusercontent.com/assets/12552247/18732507/a4d652f2-8018-11e6-8a49-46a7328176b6.png">

Each of the feature notes section has a heading: "Describe your objections for creating this application." Can you please remove it? We don't need it and the copy is confusing.

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/185074826551492

**Comment by vikasrohit** [comment]
Changes are in dev.
