### ISSUE TITLE
Build connect design specification delivery portal/website on dev server

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1412]
We want to use final deliverables from Sketch, which are simple .html pages. Sharing with community is always hard and requires a lot of hand-holding, so we should be able to have a simple web server under `connect.topcoder-dev/designs/` where each design deliverable would be accessible in its own folder. Ideally it would be super easy to just add a folder to the space and have a dynamic page list all folders available so community members can access the specification online or download the .zip file for local use. Live spec example at `http://vic-tor.com/export-test/`. Example for main catalogue page would be `http://community-app.topcoder.com/`. I would prefer a simple auto-generated page if possible, though.

**Comment by vic-topcoder** [comment]
@mtwomey - please reassign to whomever can help. Let me know if you want to cover this deeper on our next meeting. More tasks might be needed and setup of environment. Let's discuss this before commencing any work.

**Comment by vic-topcoder** [comment]
@gondzo @birdofpreyru @vikasrohit @sachin-maheshwari @mtwomey @RishiRajSahu - we discussed the goal to build a shared repo of self-dependent React components, and document the design and code. In #1424 we mentioned several solutions. Let's figure out what's the best place to host such a documentation and keep it current.

**Comment by birdofpreyru** [comment]
Yeap, I've just started to move it on my side, as I promised in the other ticket.
Here I have the first package, where I am going to spawn out the very generic stuff from Community App:
https://www.npmjs.com/package/topcoder-react-utils
at the moment it does not have much, just the Babel and ESLint confings, and customized `<Link>` and `<NavLink>` components; but it gonna be more interesting soon.

**Comment by vic-topcoder** [comment]
> Yeap, I've just started to move it on my side, as I promised in the other ticket.

Great work, let's keep things in sync!

I'm working with the designers to build a centralized library of symbol components for all apps. If we are starting with the buttons, then let's think of how to add the design spec to the live component. I honestly don't have a great solution, my idea was to export the components with Sketch Measure as stand-alone html pages and put them on a server for people to have access to them without the need to have Zepplin/Abstract/Marvel/InVision access. Any ideas on how we can improve spec sharing?
