### ISSUE TITLE
Last Updated column in grid view is not accurate

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#1414]
### Expected behavior
When displaying the grid view of the project the actual Last Update Value may not be accurate. 
![image](https://user-images.githubusercontent.com/1180747/33610941-6a209c6a-d992-11e7-82c6-3c474e944d96.png)
Note project 4625 Bancolombia ... Says November 16 however if you open that project you can see it is actually today December 5

### Actual behavior
Describe.
![image](https://user-images.githubusercontent.com/1180747/33611042-b75773e6-d992-11e7-9360-4d3bbc973e14.png)

### Steps to reproduce the problem
 find a list of projects that are active
 confirm the last update value is correct

### Screenshot/screencast
https://connect.topcoder.com/projects/4625/

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vic-topcoder** [comment]
@kbowerma the update timestamp is changed when a new user joins a project. @vikasrohit please review and reassign if needs fixing. @mtwomey FYI

**Comment by gondzo** [comment]
can we close this now?

**Comment by vic-topcoder** [comment]
@vikasrohit

**Comment by vic-topcoder** [comment]
@vikasrohit can you please confirm this is completed? Close if so.

**Comment by vikasrohit** [comment]
@vic-topcoder I know this issue was there when reported. I think it is not reproducible right now, @RishiRajSahu tried to reproduce it today. May be it was a temporary error in message queue.

**Comment by vic-topcoder** [comment]
ok, closing. Thanks!
