### ISSUE TITLE
[Suggestion] Make project description textareas larger

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#1418]
### Expected behavior
User should be able to comfortably read the content of the specs section. The descriptions text areas should allow more space or maybe make it long by default and add an edit feature to each field 🤔

### Actual behavior
Two lines seem too small to read all the content. I remember there used to be an expandable feature right down the corner of the text area but it's gone now. At least I could expand the text area to read all the content.

### Steps to reproduce the problem
- Go to specs page of any project.
- See any of the text areas on the page.

### Screenshot/screencast
- [Sample](http://take.ms/luv6gt)

---

#### Environment
- OS: Mac
- Browser (w/version): Chrome
- User role (client, copilot or manager): Copilot
- Account used: mahestro

**Comment by vic-topcoder** [comment]
I guess there's a regression bug occurring. We use a react component that should auto-size all text areas that have content to display the maximum content at a time.

@gondzo - probably a good candidate for community to figure out why the text area auto-resize plugin stopped functioning?

**Comment by gondzo** [comment]
fixed already
