### ISSUE TITLE
Project status composer should not be collapsed when it contains content

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#142]
With reference to #121 should we restrict the composer not to collapse when it has some content (either in title or the post) and user clicks outside of the composer? Just for information, user would get it expanded anyway when clicks back on the title.

**Comment by vikasrohit** [comment]
cc: @vic-appirio @fnisen @parthshah

**Comment by fnisen** [comment]
@vikasrohit yes, that's right. Once there's content, no need to collapse it anymore. It should just be collapsed initially. By the way, I noticed the "x" to close is not working right now.

**Comment by vikasrohit** [comment]
There is not way, on dashboard, to get the composer back once closed. So should we keep the close button here? We do have a way(plus icon in left panel) in messaging tab for showing the composer.

**Comment by vic-appirio** [comment]
By design the composer can collapse, preserving the content, but only the title will be visible. On click the full form appears. On blur the composer collapses. When navigating away, the content is lost; we should display an alert that there's unposed update and they'll lose the content if navigate away.

This is the default UX at Facebook. Look at the specification for example of those 4 states.

**Comment by vic-appirio** [comment]
Also: InVision prototype: https://topcoder.invisionapp.com/share/868IT4EJW#/181948484_Feed_-_New_Post

**Comment by vikasrohit** [comment]
Changes are in dev. @fnisen @vic-appirio  Can you please let me know if we need close button for composer?
>There is no way, on dashboard, to get the composer back once closed. So should we keep the close button here? We do have a way(plus icon in left panel) in messaging tab for showing the composer.

@vic-appirio for showing the alert when navigating away from the page, I guess it would be better to track that separately.

**Comment by fnisen** [comment]
@vikasrohit discussed this issue with @vic-appirio. We'll follow your recommendation and simplify: can you please remove "x" button (close) from the composer, both for status updates and messages?

**Comment by vikasrohit** [comment]
@fnisen Did you check the latest behaviour? Current implementation follows the facebook UX (except the gray overlay behind the composer). I have to revert all the changes I did to make it work. :(

**Comment by fnisen** [comment]
@vikasrohit yes, I checked, of course. The main difference with Facebook is that the "x" is always clickable and has an action (the grew overlay is removed)--whether you have content in the composer or not. For us, the "x" only has an action when there is no content in the composer. Also, in the Messages section, the "x" currently is never clickable--I'm not able to collapse the composer, and I think that's what we want, so the "x" is not needed. Let me book a quick meeting with you to discuss this and agree on an approach. Don't want us fixing it over and over.

**Comment by fnisen** [comment]
@vikasrohit as discussed during our meeting, confirming that the feature is working is expected (in local). Thanks.

**Comment by vikasrohit** [comment]
Changes are now in dev. I have cross checked the same.
