### ISSUE TITLE
Silent the notifications for admin activity

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1421]
TBD

**Comment by vikasrohit** [comment]
@vic-topcoder Can you please add more details here? I have extracted this feature as separate issue because part(admin can change status by going into project details page) of #1245 is already developed  and part (admin can change status by list page itself without going into details page) is being developed via community.

**Comment by vic-topcoder** [comment]
If an administrator is performing actions on a project where they're not joined, the system should not trigger notifications. This would reduce noise. The idea is that we want to allow admins to act on projects without disturbing or triggering unnecessary noise. The missing one is managing team members right now, or editing the project specification, or any of the posts.

If an Admin spots a typo or wrong link, they should be able to edit the post to fix the problem. I don't want to trigger a notification to the end user that the post was edited necessarily.

**Comment by vikasrohit** [comment]
@vic-topcoder If we don't trigger any notifications for cases like admin added/removed a member or edited a post etc, it would cause confusion. No one would know how a team member got added/removed or who edited some post (may be it was not a typo but admin thought otherwise).

We definitely need to have an audit trail for all actions and this should be visible to at least all admins. Instead of creating a separate audit system, we can simply show all notifications generated after admin actions, however we can show some kind of visual indication on those notifications/posts that it was edited by an admin.
