### ISSUE TITLE
Unify .svg resource loading and use

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1422]
We should refactor the use of SVG images in all components to be consistent. SVG images are text-based vector data that shouldn't be included as CSS backgrounds or <IMG> elements. This will allow us dynamic modifications with CSS and JS - drawing/animation/color change, transformations, etc..

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-39

**Comment by gondzo** [comment]
duplicate of #1442
