### ISSUE TITLE
Consistent code style & code reviews

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1423]
We should have a consistent code formatting and code style guide across all components. Currently there are quite a few variations and we must fix that.

JS - bring all components to React 16

SCSS - small modular pieces of code; too many heavily nested and complex files; break down to components; use variables

HTML - clean and improve the semantic use of HTML tags and set standards for custom HTML tags (do we use them, or not; how do we use them, consistency)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-43

**Comment by gondzo** [comment]
one common issue is usage of wrong z index - we need some guide on acceptable values for components/page elements

**Comment by vic-topcoder** [comment]
How many different elements we have? I'd say let's set 
- z-index: 80-100 for tooltips,
- z-index: 100+ for dropdown menus,
- z-index: 1000+ for modals,

**Comment by gondzo** [comment]
we have a bunch of other z indexes used for disabling content, for example disabling post editor during the api call to post a reply. is 50-70 ok for these?

**Comment by vic-topcoder** [comment]
Sure. As long as we list all the index ranges and put it front and center as documentation, we're good. Please make a note on the wiki (https://github.com/appirio-tech/connect-app/wiki) for the Z-index ranges.
