### ISSUE TITLE
Performance baseline

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1425]
We should be testing our components and interface for performance baseline and prevent degradation. All new features/fixes that are introduce shouldn't create regress in performance - there should be an automatic solution to help us with that.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-41

**Comment by gondzo** [comment]
setting up automatic page load measurement  will be a separate task, so lets keep it out of the bug bash for now.
