### ISSUE TITLE
Need design for the case when there is no project status on the dashboard

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#143]
Right now we are showing only the composer which itself would not be visible(for non copilot and non manager users) after changes for #105. So, it would look odd with empty space. I guess we should have some kind of placeholder for that. And same thing goes for the messaging tab.
@vic-appirio Please let me know I missed these empty state placeholders from the design.

**Comment by vikasrohit** [comment]
cc: @parthshah @fnisen

**Comment by fnisen** [comment]
![b3f2a941-1ff4-494e-a218-e91a5959ca28](https://cloud.githubusercontent.com/assets/12552247/18767852/74319d00-80d6-11e6-8af5-75cf83aa63bc.png)

Hey @vikasrohit, you're right. I noticed this too as soon as we cleaned out the mock data. Please see design above. We have auto-generated "Coder cards" (at the bottom of the updates) that can appear. A few of them are special cards with buttons. I'm thinking we would send a few system messages (as Coder cards) based upon certain actions (e.g., project creation). I assume this is easy. We can use basic message cards to start (not create special cards with buttons). Please let me know your thoughts.

**Comment by parthshah** [comment]
@vikasrohit - the first 2 cards (from the bottom) can be static.
@mdesiderio we should generate these Coder Bot messages asynchronously when the project is created, specs completed, etc. What user should we use to POST these messages?

**Comment by parthshah** [comment]
fixed.

**Comment by vikasrohit** [comment]
@parthshah I am still seeing empty right section, with customer login (christina_uw) for project id 285
