### ISSUE TITLE
connect email notification should have the project name.

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#1430]
### Expected behavior
I have several projects running in connect and some have the same co-pilot.   If I read the email alone I don't know what project is for.   Please add the project name in the title or the body of the email

### Actual behavior
the email does not contain the project name

### Steps to reproduce the problem
add a comment in connect 
see the emails

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/1180747/33720442-91b0c546-db29-11e7-968d-d8418d1a4f42.png)

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vic-topcoder** [comment]
Once we can start work on the email notification system, the email template would be redesigned to provide maximum clarity on event and details. Thanks for reporting, @kbowerma
