### ISSUE TITLE
Discussions Pane Sorting

### ISSUE THREAD

**Issue by rsial2** [appirio-tech/connect-app#1432]
Please sort the discussions list by most recent discussions first:
![image](https://user-images.githubusercontent.com/5807576/33849936-c791f468-de77-11e7-812f-a121e1c94ffe.png)

**Comment by vic-topcoder** [comment]
It might be related to #441. Thanks for reporting @rsial2 - due to the deprecation of this particular feature it would be with a lower priority from product stand point.

**Comment by rsial2** [comment]
That issue pertains to projects in the project listings page, not discussions in one project. Also I thought you brought the discussions pane back for new projects?

**Comment by vic-topcoder** [comment]
No - we're not bringing the discussions pane back. The need for listing all discussions at the same page requires a slightly different approach - a way to sort through the project dashboard posts. That is a feature that is under consideration at the moment.

**Comment by rsial2** [comment]
But you said you were going to bring it back? What's the point in using Connect if we can't have conversations that are clear and easy for clients to understand and track. Removing the discussions pane was a huge step back in usability.

**Comment by gondzo** [comment]
Do we have any data on weather there are any active projects that use discussions? @vic-topcoder @mtwomey 
if not, can we remove them completely now?

**Comment by vic-topcoder** [comment]
there are still projects that use the panes. Do not remove them yet.
