### ISSUE TITLE
[$200] Page update reload suggestion

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1437]
Detect when a page has been updated while the user is browsing, and display a prompt to reload the page to update with the latest content. Specifically useful for discussions on the home feed.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-9

**Comment by gondzo** [comment]
we don't have any strategy for this yet, but with changes for #1525 we could refresh the project page if there is a new notification for the project being displayed

**Comment by gondzo** [comment]
@vic-topcoder does the above approach look fine? any suggestions on what to do if user has unsaved changes in a form (posting comment, editing spec, etc)?

**Comment by vic-topcoder** [comment]
Here is the prototype for the interaction: https://invis.io/B9997WQJW#/202782585_Refresh_Feed_-_Step_01

Should function the same way as in Facebook/Google. 

- When on top of a page and new update is present, reload page
- When scrolled in a page, display reload suggestion button
- When posting or using dropdown menus, do not change UI until action is completed, after that follow the above rules.

**Comment by gondzo** [comment]
Prize increased

**Comment by passimm** [comment]
hi gondzo, just sent a PR for this: https://github.com/appirio-tech/connect-app/pull/1647/commits
your comments are welcome. thanks

**Comment by passimm** [comment]
just realized i forget to take care of
"When posting or using dropdown menus, do not change UI until action is completed, after that follow the above rules."

i will update the PR later...

**Comment by passimm** [comment]
PR updated.
have one pending issue. it's difficult to track whether Notification/user profile dropdown is expanded. they are using appirio-tech-react-components:Dropdown, which neither allows add click listener, nor registered to react-redux... could you shed light on how to track whether Dropdown is opened?

**Comment by passimm** [comment]
hi @gondzo any idea about that?

**Comment by gondzo** [comment]
I think we can ignore the dropdowns for now and fix that later

**Comment by passimm** [comment]
@gondzo PR updated. please help review. thanks!

**Comment by gondzo** [comment]
merged to bugBash07. closing
