### ISSUE TITLE
Loading more results in the grid triggers an error (500)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1441]
Right now when you try to load more projects, there's a 500 error.
![screen shot 3](https://user-images.githubusercontent.com/8484061/33969646-4a507396-e023-11e7-81e9-d77ae9275b37.png)
![screen shot 4](https://user-images.githubusercontent.com/8484061/33969651-4c53137e-e023-11e7-83ef-a0001b94a4d3.png)

**Comment by ThomasKranitsas** [comment]
I can't reproduce this but it seems like it's happening because `lastEditor` is not defined.
I've added a check that will render `Unknown` instead of crashing the app if it's not defined.
