### ISSUE TITLE
[$400] You can't use .svg as background images. All icons in the interface should be inserted as inline HTML/SVG tags.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1442]
Multiple instances of using .svg images as background images in CSS. WE DO NOT ALLOW THAT.

We should always use the SVG react include way so we can modify the SVG properties. Please fix all of the instances where we have inserted .SVG as css `background: url(..)`

Example
![screen shot 5](https://user-images.githubusercontent.com/8484061/33971283-86253d58-e02c-11e7-9e33-7fa787b21aec.png)

@vikasrohit @gondzo please make sure our acceptance of a bug solution doesn't break this rule.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder @gondzo  there are 106 occurrences of SVGs in SCSS. This will take some time to be fixed.

Is that urgent for 05 or can be moved to 06?

**Comment by vic-topcoder** [comment]
Moving to 06

**Comment by vic-topcoder** [comment]
@vikasrohit @birdofpreyru @gondzo @ThomasKranitsas - let's make sure that we're using a standard way of inserting .SVG into the code. This is a good candidate to refactor the entirety of .SVG used in Connect and create a documented way for further reference.

We discussed component vs. directly passing .SVG to webpack - do we have a consensus on how we should proceed with this one going forward?

The problem I see with the component is that it wraps the .SVG into a `<i>` tag with the same class all the time (`class=icon`) which makes it hard to modify the individual properties of the .SVG images passed. 

I guess that probably wrapping the SVG in `<object />` is probably the best - we can cache the resources and reduce code generation - than use of `<svg>` directly. Reference: https://svgontheweb.com/#implementation.

- [ ] We need to use only one standard throughout all Topcoder react apps.
- [ ] We need to generate unique class for each .SVG so we can access and modify it through CSS.
- [ ] The refactor should happen system-wide for all instances of .SVG images.
- [ ] We should document the correct way to insert SVG assets into react components as part of the task.

**Comment by birdofpreyru** [comment]
We use [babel-plugin-inline-react-svg](https://github.com/kesne/babel-plugin-inline-react-svg) inside Community App. It works good and with no visible issues; I believe the last time we talked about it related to Connect App, the main point about keeping using a dedicated component for SVGs in Connect App was that it will demand less re-factoring.

**Comment by gondzo** [comment]
ok, let's adopt community app approach with babel plugin.
refactoring will affect a lot of files so please rebase your PR against dev branch before submitting

**Comment by kevinkid** [comment]
There are a lot of unused css, what should i do with them? I was thinking of commenting them to ease someone else's time the next time there changes to be made, instead of them trying to figure out the path relative to the svg icon.

**Comment by vic-topcoder** [comment]
@kevinkid - yes, comment out the unused code and leave a `// TODO: unused css` on the top

**Comment by kevinkid** [comment]
Can we make an exception for the  ` ProjectListProjectColHeader `  component ?

**Comment by vic-topcoder** [comment]
Please fix the PR - it's breaking right now.

**Comment by vic-topcoder** [comment]
Ok, I'm reviewing the PR now, and it is not using the https://github.com/kesne/babel-plugin-inline-react-svg method as far as I can tell. The whole point of this code refactor is to come to a standard implementation of how we include SVG files into components.

Right now I see a lot of new container components that wrap a single .SVG into JSX component.

```jsx
import React from 'react'
import Web from '../../assets/images/tech-32-outline_desktop.svg'

class IconWeb extends React.Component {

  constructor(props) {
    super(props)
  }

  render() {
    const {className} = this.props
    return(
      <object>
        <Web className={className}/>
      </object>
    )
  }
}

export default IconWeb
```

I thought the whole idea is to add the `babel-plugin-inline-react` and remove all wrappers and static declarations of icons/icon components.

Aren't we going to directly import the .SVG icons when needed into the react components themselves?

```jsx
import React from 'react';
import CloseSVG from './close.svg';

const MyComponent = () => <CloseSvg />;
```

@birdofpreyru can you please advise on how we should refactor the code to match the community app standard?

As I understand the method via the direct import, you'll transform an SVG as a component directly where you need it, and adding a class name that you need would happen during declaration. This would free us of wrapping any .SVG into components and we should actually clear all the icon components from the system.

It is great that you have cleaned up the .CSS files, now we have to actually refactor the rest of the code. 

- [ ] All icon components, plus icon component declaration file should be eliminated.
- [ ] All .SVG should be consistently in the same folder `./src/assets/icons`, we should leave `./src/assets/images` for any raster/vector images that we use to load as content (front page, Coder the Bot avatar, etc.).

Example: 
Avatar component from community-app: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/components/Avatar/index.jsx

```jsx
/**
 * Avatar
 *
 * Description:
 *   Reusable user avatar. Depending on wether or not an image URL is
 *   provided, it will display the user's profile picture, or a default
 *   user avatar.
 *
 * Styling:
 *  By default the avatar is round-shaped. Custom styling may be applied using
 *  react-css-super-themr.
 *
 * Usage:
 *   <Avatar url={imgUrl} theme={customeTheme} />
 *
 * Props:
 *    - theme: Object, optional. Parent-provided theme.
 *    - url: String, optional. Image URL.
 */

import PT from 'prop-types';
import React from 'react';
import { themr } from 'react-css-super-themr';
import DefaultAvatar from '../../../assets/images/ico-user-default.svg';
import defaultStyle from './style.scss';

function Avatar({ theme, url }) {
  return url
    ? <img alt="Avatar" src={url} className={theme.avatar} />
    : <DefaultAvatar className={theme.avatar} />;
}

Avatar.defaultProps = {
  customStyles: null,
  theme: {
    avatar: '',
  },
  url: null,
};

Avatar.propTypes = {
  theme: PT.shape({
    avatar: PT.string.isRequired,
  }),
  url: PT.string,
};

export default themr('Avatar', defaultStyle)(Avatar);
```

Notice the use of DefaultAvatar - directly imported .SVG, that is than used as component ` : <DefaultAvatar className={theme.avatar} />;` and a className attribute is assigned. We do not user react-themr at the moment, so the className would be static. This would allow us to access the svg properties and modify them via CSS.

**Comment by birdofpreyru** [comment]
@vic-topcoder it would be ideal to already try to setup [topcoder-react-utils](https://www.npmjs.com/package/topcoder-react-utils) as a dependency of Connect App, and adopt Babel configs from there in Connect App (it might demand some work, cause those configs use Babel plugins to support CSS modules, thus any CSS code written before without CSS modules in mind should be wrapped into `:global` blocks, to keep it working).

Anyway, related to the SVG icons, to do them the same way as in Community App, we need:
- Install [babel-plugin-inline-react-svg](https://www.npmjs.com/package/babel-plugin-inline-react-svg) as dependency and add it to Babel configs of Connect App (configs from `topcoder-react-utils` already have it done);
- Then just import and use any SVGs as regular react components:
```jsx
import React from 'react';
import SomeIcon from './some-icons.svg';

export default function Example() {
  return <SomeIcon className="someClass" />;
}
```

**Comment by kevinkid** [comment]
I was trying to avoid duplicate code for icons reused across different components, let me get rid of the global icon component.

**Comment by birdofpreyru** [comment]
@kevinkid no need to wrap. That Babel plugin will embed SVGs directly into the page markup, so they'll be automatically cached as a part of JS bundle; and with proper server-side rendering they'll be pre-rendered into the page from the very beginning.

**Comment by vic-topcoder** [comment]
thanks @birdofpreyru! I'll open a new issue where you can sync with @gondzo, @vikasrohit and @RishiRajSahu on how to do the migration towards `topcoder-react-utils`.

**Comment by kevinkid** [comment]
I have updated the PR for review @vic-topcoder

**Comment by vic-topcoder** [comment]
Thanks! I'll review shortly.

**Comment by vic-topcoder** [comment]
Looks great so far! Good job! Couple of small .SVG missed, and top navigation is broken. Once we fix those we're ready to roll.

I might do additional refactoring myself to remove the duplicate icons and put all the file type icons in a subfolder to make it easy to maintain the SVG resources going forward. That'll be out of the scope of the current refactor though.

- [ ] PNG wrapped in SVG - should be clean SVG
![screen shot 2018-01-18 at 8 11 29 am](https://user-images.githubusercontent.com/8484061/35108446-73ee3848-fc28-11e7-9676-110eff013059.png). Replace with this one - 
[grid-list-ico.svg.zip](https://github.com/appirio-tech/connect-app/files/1643583/grid-list-ico.svg.zip)

- [ ] Missing icon on top bar, use `icon-chat-active.svg` for Discussions bar. 

- [ ] Filter icon on main navigation is using CSS to add the .PNG. Replace with 
[ui-filters.svg.zip](https://github.com/appirio-tech/connect-app/files/1643634/ui-filters.svg.zip)

- [ ] View switch tab uses the icons as CSS background
![screen shot 2018-01-18 at 8 36 29 am](https://user-images.githubusercontent.com/8484061/35109252-b08486ca-fc2a-11e7-96bd-ed302194b5eb.png)
![screen shot 2018-01-18 at 8 35 46 am](https://user-images.githubusercontent.com/8484061/35109254-b1bb524e-fc2a-11e7-84ef-cd1401270349.png)

Those should be clean .SVG

**Comment by vic-topcoder** [comment]
Great! Good to merge. I'm adding the latest dev and fixing some small things.
