### ISSUE TITLE
Don't use random color numbers

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1443]
In your SCSS you should only use `$tc-[color-variable]` for specifying colors. Failure to do so breaks the consistency of code and makes it super hard to modify later. Only place you're allowed to use numerical values for colors are `box-shadow` - we don't have a mixin yet, but we should include one.

Please follow the https://github.com/appirio-tech/connect-app#code-style for all bugs. We might need to be more restrictive on the use of colors.

If you search the source code for `background: #` or `background: rgba` you'll find a lot of these.

This is from the current bug bash round:
![screen shot 9](https://user-images.githubusercontent.com/8484061/33971519-a91e50aa-e02d-11e7-9ecb-63dfdcc29b2c.png)

And search result
![screen shot 10](https://user-images.githubusercontent.com/8484061/33971533-bc5101fe-e02d-11e7-944a-78908ea311b9.png)
![screen shot 11](https://user-images.githubusercontent.com/8484061/33971534-bc632cee-e02d-11e7-85b2-b6c4b9e4b7e5.png)

@vikasrohit @gondzo please make sure we do not accept code that introduces random colors and color values in the SCSS.

**Comment by vikasrohit** [comment]
@gondzo can we run a task for this?

**Comment by vic-topcoder** [comment]
@ThomasKranitsas Ping me if you find colors that are not matching and need help to match to existing palette.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder can you give me a link to the palette that the app uses?
I'm using this https://github.com/appirio-tech/styles/blob/master/styles/topcoder/_tc-styles.scss but some variables are missing (eg `$tc-accent-blue-70`)

**Comment by vikasrohit** [comment]
@ThomasKranitsas https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss is that latest set of colors we are using in Connect.

**Comment by gondzo** [comment]
Looks good. Thanks

**Comment by vic-topcoder** [comment]
👍
