### ISSUE TITLE
Add tooltip hint for manager user avatar as well

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1444]
We don't have a hover hint tooltip for the project managers. Please reuse the tooltip hint for customer.

Depends on fixing #1445 first

**Comment by ThomasKranitsas** [comment]
@vic-topcoder how do you want to show multiple managers?

**Comment by ThomasKranitsas** [comment]
@vic-topcoder @gondzo 

1. Should I show one tooltip for all managers or one for each manager?

2. What details should I show? (avatar, first/last name, handle)?

**Comment by gondzo** [comment]
1. I think one for each manager is better
2. Avatar, full name, handle should be enough

**Comment by vic-topcoder** [comment]
We have double avatars after the tooltip, plus we want to have the email address on each user, especially customers. The email is the most needed piece of data for the connect managers.
![screen shot 5](https://user-images.githubusercontent.com/8484061/34226020-3a743ac0-e57d-11e7-8ccd-ec5e3379ce79.png)

@ThomasKranitsas - please add the email address back

**Comment by ThomasKranitsas** [comment]
Oh, sorry! I've added double avatars to check how it looks with 3 managers... I forgot to remove it.

The email should be there if it's available.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder should be fixed now. Sorry about that! 🙂

The code for the email is here: https://github.com/appirio-tech/connect-app/blob/bugBash05/src/components/User/UserTooltip.jsx#L38
If the user details object contains the email, the tooltip will show it.

**Comment by vic-topcoder** [comment]
But aren't all users registered with an email? I don't see it still. @gondzo - why the user details object may not contain email?

**Comment by gondzo** [comment]
we have to add email to the fields we want from the api >
https://github.com/appirio-tech/connect-app/blob/dev/src/api/projectMembers.js#L8
- I think it's just add 'email' to the list but I'm trying to find the api
docs to confirm

**Comment by vic-topcoder** [comment]
This is the tooltip:
![screen shot 6](https://user-images.githubusercontent.com/8484061/34228764-bcefe518-e586-11e7-90b7-2d435221a91e.png)
This is the data object:
![screen shot 1](https://user-images.githubusercontent.com/8484061/34228791-d4203c24-e586-11e7-9bcd-6b57c69ef290.png)

I would expect to see "connect_dev_manager@mailinator.com"

**Comment by vic-topcoder** [comment]
I think we were getting the email before this changes - check the old tooltip code

**Comment by ThomasKranitsas** [comment]
![download](https://user-images.githubusercontent.com/4612921/34229136-ddaf845c-e5db-11e7-9528-11d120501566.png)

That's the data the reaches the `ProjectsGridView` component...

**Comment by ThomasKranitsas** [comment]
If I hardcode the email in the user object, it renders correctly.

![projects - topcoder 2017-12-20 23-27-07](https://user-images.githubusercontent.com/4612921/34229539-59df11c2-e5dd-11e7-9da4-97cf20c50aaf.png)

**Comment by vic-topcoder** [comment]
I see. Cool. Hope we can get the API to return the user email.

**Comment by ThomasKranitsas** [comment]
I don't know where the API repo is. If you give me the repo, I may be able to fix it 🙂

**Comment by gondzo** [comment]
@vic-topcoder The api won't return email fields. If it does than we expose all users emails which is not good. This would require backend changes as well, so can we leave it for 06 ?

**Comment by vic-topcoder** [comment]
I guess so. I'll open a new ticket for retrieving user emails from managers and admins.
