### ISSUE TITLE
Grid error message is not centered

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1446]
Should be centered at all times (resize your window)

![screen shot 3](https://user-images.githubusercontent.com/8484061/33971814-3d8e6e5e-e02f-11e7-9ff5-f2acf6fe1420.png)

**Comment by ThomasKranitsas** [comment]
![projects - topcoder 2017-12-19 21-01-41](https://user-images.githubusercontent.com/4612921/34174054-4435e572-e500-11e7-9bc3-864ae87bef8e.png)


Fixed 🙂
