### ISSUE TITLE
Project grid click zone must increase

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1452]
Right now only the title of the project is clickable. We want to make it easy for managers to click on ID, icon, title, description in order to get to the project details section.

**Comment by ThomasKranitsas** [comment]
![projects - topcoder 2017-12-19 17-36-46](https://user-images.githubusercontent.com/4612921/34165000-c0ee7704-e4e3-11e7-9a89-d9b80fa3d073.png)

The area in the red rectangle is now clickable.

**Comment by vic-topcoder** [comment]
awesome
