### ISSUE TITLE
Filter menu doesn't persist when creating new project menu is opened

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1455]
The filters menu doesn't persist state when the project creation window is opened, or the user navigates to a project details page.

Expected: For the duration of the user sessions, persist the state of the filters menu (open or close).

**Comment by vikasrohit** [comment]
I think we should keep it for Community fixes 06 as 05 is already in progress and expected to be released by coming Monday/Tuesday.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder do you want me to fix this for 05 or leave it for 06?

**Comment by vic-topcoder** [comment]
If it is a quick fix, please go ahead.
