### ISSUE TITLE
Fix price quote mechanism

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1458]
All projects should display price quote depending on selection of questions. We need to extend the configuration JSON to be able to define price variables per multiple questions. Ideally through selection of different questions the price of a project would be changed.

 

What I imagine is:

- Project base price - the minimum price for each project, 
- Price modifiers - property of different question answers - quoteUp or quoteDown with amount. These would add or subtract from the price calculated

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-130

**Comment by vikasrohit** [comment]
@vic-topcoder Implemented the changes and it should be there in dev until the feature branch is deployed. Right now it uses the mechanism only for design products for which we are supporting right now. We can now apply the logic to other products as well. New config parameters are:

`basePriceEstimate`, `baseTimeEstimateMin` and `baseTimeEstimateMax` in src/config/projectWizard/index.js for the product we want to show the estimate.

Right now it considers only `radio-group` and `tiled-radio-group` type of questions for calculating price and time estimates. And for these questions, we have to add following properties to each option of the question

`quoteUp` the amount by which base price should be increased if the option is selected
`minTimeUp` the amount by which min time estimate should be increased if the option is selected
`maxTimeUp` the amount by which max time estimate should be increased if the option is selected

**Comment by vic-topcoder** [comment]
Cool
