### ISSUE TITLE
Code refactor to load cleaner JSON files instead of repeated JS functions

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1462]
Right now each specification .js file reuses the same functions (more or less) - ideally we can have only 1 smart specification parser where we pass the JSON specification object. This is important to allow us to store the specification in the DB going forward.

DRY! (Don't Repeat Yourself)

![](https://topcoder.aha.io/attachments/6499504410623292806/token/5ee53fd63d25b5632ee77584e08964ef2915c4bc8ef328b170933ddc55e181db.download?size=original)

Screen Shot 7.png (https://topcoder.aha.io/attachments/6499504410623292806/token/5ee53fd63d25b5632ee77584e08964ef2915c4bc8ef328b170933ddc55e181db.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-131

**Comment by RishiRajSahu** [comment]
Moved common functions inside index.js

**Comment by RishiRajSahu** [comment]
@vic-topcoder  changes are deployed to milestone's feature branch - 'feature/project_configuration_documentation' and deployed to dev.
