### ISSUE TITLE
Add routes for notification actions

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1464]
We need to add these routes for handling notification onClick events
- go to specific post by id
- go to project file list

**Comment by vic-topcoder** [comment]
@gondzo - our posts do support projectID/#postID format for links in emails so users can click and scroll back to the post target for the notification.

**Comment by maxceem** [comment]
1. **go to specific post by id** - may I get an example link from email?
    For example for this project https://connect.topcoder-dev.com/projects/2193
    Link to the topic **test**
    Should it be https://connect.topcoder-dev.com/projects/2193#1535 or https://connect.topcoder-dev.com/projects/2193#feed-1535
   The second link I've got from the topic date, see http://take.ms/I41P6
    Actually both of these link **don't scroll** to the topic. Do you have any link which does scroll?

2. **go to project file list** -  as I understand there is no such link so far
    So we have to open project **specifications** and scroll to **project files** http://take.ms/QngQW
    Correct?

**Comment by gondzo** [comment]
1. Neither of those work. I just checked some emails in prod, and none of the links scroll to the topic so we need to implement this as well. I think we had this feature sometime back, not sure when it was removed.
2. Right we don't have this route, this needs to be implemented from scratch

**Comment by maxceem** [comment]
1. Could please share any link example from the production, just for reference. In case I find some pieces in the existent code.

**Comment by gondzo** [comment]
I just added you to a test project on prod. the link is like https://connect.topcoder.com/discussions/{topicId} and it just redirects to the project page

**Comment by gondzo** [comment]
This one is implemented and merged to dev, we have direct links from notifications to project dashboard, specification, files, topics and posts
