### ISSUE TITLE
Respect notification settings when displaying notifications

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1466]
Endpoint that fetches unread notifications should be updated to respect user settings for Web. Currently all notifications are displayed

**Comment by vic-topcoder** [comment]
Awesome. We might want to make certain notifications persistent (always on) on the web - I didn't see that option in the front-end of the system.

I will update the structure of the notification settings for language on the switches in another task. Right now I have yet not figured out which notifications do we support in the app on launch.

![screen shot 1](https://user-images.githubusercontent.com/8484061/34124800-1ce9c154-e3e9-11e7-8f81-d6c8d38c9755.png)

- [ ] Add the "Always on" label style for notification settings.
