### ISSUE TITLE
Notification icons

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1467]
Currently, we have the next notification icons http://take.ms/rdNhx
They don't directly match to events we have and there is no information in notification matrix about them.
Right now we're using the available icons but should ideally specify exact icons for each event.

**Comment by vic-topcoder** [comment]
Icons seem fine. Yes - I'm not concerned if we have different icons. Please make sure we can specify the icons and include them as .SVG on the front-end as to be able to modify the .SVG properties via SCSS.
