### ISSUE TITLE
Response to your post

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1468]
We have two notifications for posts
- [Who] responded to your post
- [Who] responded to your post

What should we consider a reply to a post? 
- Any comment added to a topic is response to first post in the topic or
- Any comment added to a topic is response to previous comment in the topic

**Comment by vic-topcoder** [comment]
A response to Your posts means - any comment made on a topic you created - post number 0 - you're the author of that topic. It should trigger a single notification for each response, and bundle post activity at certain period - if you have a high activity happening on the site, the system should delay and bundle the notifications as to not overwhelm the user. Clicking on a single or bundled notification would load the feed to the first new post, which means the first new post should be visible if the feed has more than the collapsed view allows. The goal is to allow the user to jump back into the discussion without reading the full discussion as a set of notifications.

**Comment by gondzo** [comment]
we have implemented the logic for post replies, but we don't yet have support for bundling notifications. can we create a new issue to add this later on ?

**Comment by vic-topcoder** [comment]
Yes - add it to https://github.com/appirio-tech/connect-app/milestone/36
