### ISSUE TITLE
[$400] User mentions in the posts

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1469]
Should we use user handles for generating mentions or full names ?

**Comment by vic-topcoder** [comment]
It should be `@username` format that ideally would be replaced with the `Full Name` to be readable - Facebook like. The `@username` mentions are not yet available in the system - save for later, but let's think about how we can solve this.

**Comment by gondzo** [comment]
If we use @handle for user mentions and display full name in the notifications, I'm not sure it will be obvious for the users that we have this feature. maybe we need to add mentions support to the post editor, similar to how it's implemented in github ?

**Comment by vic-topcoder** [comment]
I was aiming for the way it is implemented in Facebook and Dribbble - upon using the `@username` the system replaces/renders the mention as `First name Last name`. Check this demo from draftjs - https://www.draft-js-plugins.com/plugin/mention - I'm fine if we use this plugin as is. Remember - in Connect the names are more important for our customers than @username, and they don't use the latter that often, or at all. The goal is to make it easy for people to communicate :)

**Comment by gondzo** [comment]
This requires several steps:
- add mentions plugin to post editor (allow mentions for project members only)
- add mentions parsing to notifications server
- add mentions notifications to connect app

**Comment by vikasrohit** [comment]
@gondzo I would suggest if we can keep `@username` in the actual message being posted to the message api. And replace it with user's full name when fetching the messages from the API. This is to allow showing latest value of the user's full name. I know user's full name is not something which can change frequently, however, I am thinking from the perspective of having a generic approach to replace placeholders in the messages e.g. we can have `${project_title}` as one of placeholder which can be resolved to the latest project title when fetching the messages.

**Comment by gondzo** [comment]
that would be fine in the app, but the the emails would be sent with @username instead of full name

**Comment by vikasrohit** [comment]
We have to apply the same process of replacing the placeholders, which we would do in API while fetching messages via API, before sending the emails as well. I know right now it is not possible because discourse is doing that, but we can do this once we get rid of discourse and take control of sending emails.
I guess, for now you can proceed with your current approach, we can revisit it later after getting rid of discourse.

**Comment by passimm** [comment]
I have made a PR: https://github.com/appirio-tech/connect-app/pull/1594
1) use draft-js-mention-plugin in post editor
2) use "@F_NAME L_NAME" in textbox
3) replace with @handle before sending to backend

**Comment by passimm** [comment]
notifications server code change will be sent out later..

**Comment by vic-topcoder** [comment]
Ideally the behavior is to use `@handle` to lookup user and replace it with "First name Last name" so if I type

"Hey @gondzo how are you doing?" → the system would render "Hey **Samir Godzetovic** how are you doing?

**Comment by passimm** [comment]
@vic-topcoder updated.
now select in handle and render in fullname.

**Comment by gondzo** [comment]
looks good. 
@vic-topcoder why would we use handles at all when typing mentions? we can go straight to full name as the mention plugin will offer suggestions anyway.

**Comment by passimm** [comment]
i cannot fix a lint error in PR: https://github.com/appirio-tech/connect-app/pull/1597
even with 'eslint-disable-line'... could you help me with that? many thanks.

  /* eslint-disable */
  onSearchChange = ({value}) => {
    this.setState({
      suggestions: defaultSuggestionsFilter(value, this.mentions)
    })
  }
  /* eslint-enable */

**Comment by passimm** [comment]
@gondzo updated two PRs:
connect: https://github.com/appirio-tech/connect-app/pull/1597
notification server: https://github.com/topcoder-platform/tc-notifications/pull/17

please help review. thanks.
the Bug Bash almost comes to end. i still get last chance to update PRs tomorrow...it would be very helpful if you could review this  ASAP ^_^

**Comment by gondzo** [comment]
@passimm I've added a few fixes to both PRs and merged everything. looks good, but there are still a few issues. the most obvious one is that mentions component will add the mention to last editor on the page, and not the one that is currently active. can you take a look and submit another PR?

**Comment by gondzo** [comment]
@vic-topcoder right now we are using handles when looking up mentions, and then replacing them with full user names for display and sending @userId to server. discourse replaces @userId with @handle (and adds a link to user profile), so the final message is displayed with handles again. this will need more work to get it working properly

**Comment by vic-topcoder** [comment]
I see. Let's work on this one until it is done properly. Keep in mind that we plan to replace Discourse as back-end at some point, so we should be able to change the back-end at some point without having to modify the front-end too much.

**Comment by passimm** [comment]
@gondzo looking at the issue.

**Comment by passimm** [comment]
@gondzo, fixed this issue. 
mention plugin should be initialized per component.
https://github.com/appirio-tech/connect-app/pull/1599

please help review. thanks.

**Comment by passimm** [comment]
@gondzo, i saw one of your commit to notificationserver:
https://github.com/topcoder-platform/tc-notifications/commit/83d0ea8aad36a9c21bd401da84a65e22ec275a93

you modify original PR: extract 'const regexUserId = /@([a-zA-Z0-9-_.{}\[\]]+)/g;' and then use it as handle.
however in our connect-app, we pass mentions as **@userId, not @handle:**

    _const userIdMap = _.reduce(this.state.suggestions, (obj, item) => {
      obj[encodeContent(item.name)] = item.userId
      return obj
    }, {})
      
    for (const item in userIdMap)
    {
      content = content.split('@' + item).join('@' + userIdMap[item])_

Looks like there Am I missing anything?

**Comment by gondzo** [comment]
the messaging backend we use (discourse) will (transparently) replace @userid with @handle so the notifications server will not get the userId. If you refresh the page after you add a comment on a topic, you'll notice that it doesn't say @fullName or @userId, but it's @handle. IMO it will be best to use @full name for the mentions all the time, but we'll need a way to parse that later on. I'm wondering if there is some metadata that we can attach to draftjs content so we could get userId, but always display full name

**Comment by vic-topcoder** [comment]
Looks good and almost there. One small remarks:

1. When I want to later edit my post I lose the @mention plugin in the system, see attached
![screen shot 2018-01-12 at 3 59 20 pm](https://user-images.githubusercontent.com/8484061/34910057-8adaa07e-f862-11e7-8b64-0d4a6ee3ac83.png)

Let's keep the @mention as rendered on the post while editing, and make sure the @mention plugin also work for the post editing

**Comment by gondzo** [comment]
@vic-topcoder I've pushed a few changes and we should be good to go on this one.
- suggestions are rendered as full name-handle so it's easier to search
- editing works properly
- allowed mentions are only project members - maybe we should change this in the future to add admins/managers, etc
- adding @memberThatIsNotPartOfTheTeam to post body won't be considered a mention

**Comment by passimm** [comment]
@gondzo, did you solve "mention plugin lost when editing previous feed"? i'm still looking into it...

**Comment by passimm** [comment]
please ignore last... I saw your fix. seems like I forgot to pass AllMembers for some other components.

**Comment by vic-topcoder** [comment]
@gondzo we should count project members as anybody that has joined a project, correct?

**Comment by gondzo** [comment]
yes
