### ISSUE TITLE
Profile is not completed

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1470]
When should we generate this notification? We don't have the option to remove it after user does fill out the profile. 
Can we leave this notification for later ?

**Comment by vic-topcoder** [comment]
This should be generated when the user profile is not completed once per login, until they complete their profile (all required fields). This is a feature that captures the need, but can be fulfilled only after we have a profile in place - save it for later.

**Comment by gondzo** [comment]
I don't think we're ready for this one yet

**Comment by vic-topcoder** [comment]
Moving it. We need the profile page first. :)
