### ISSUE TITLE
Lazy-loading on project grid is very slow and blocks scrolling of the page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1472]
On reaching the end of the page on project grid view (after clicking "load more projects" button), the page pauses and I can't scroll, and when the loading is done, the page jumps very quickly. This behavior is supper erratic and doesn't allow for smooth UX while scrolling.

The goal is to remove the rendering pause while data is being fetched, so the page never freezes/jumps up and down. If possible - expand the preload zone of the grid or bring more details in one call so that the performance of the page is better.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder maybe we can render some placeholders while new data is loading?

**Comment by vic-topcoder** [comment]
Placeholders would be nice, but the pause and jump in rendering is what worries me. The goal is to reduce the jitters while scrolling. Haven't done deeper investigation on what causes that behavior. I would assume there are some calculations performed by the browser as the grid is getting bigger, and the browser redraws the interface very slow on horizontal resize as well.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder @gondzo fyi the app was making multiple calls to the API... That was causing a lot of jittering... After my fix, the app was working smoothly... Let me know if you still see any performance issue...

I improvised for the placeholder design... Should look like this:
![projects - topcoder 2017-12-20 01-40-26](https://user-images.githubusercontent.com/4612921/34184125-c99a63ac-e526-11e7-9b36-9ac56a5c5769.png)

 Let me know if you don't like it 🙂

**Comment by vic-topcoder** [comment]
Awesome!

**Comment by vic-topcoder** [comment]
There are still some issues with loading, but the current optimization is much better. I'll mark this as accepted.
