### ISSUE TITLE
Make reference codes searchable in Connect

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1479]
### Expected behavior
When a user searches for a reference code, the system should list all the results with the matching code. This is very important for administrators - reference codes are special tags to find projects within the system.

Maybe we can also employ the keyword for filtering `ref:`, so if I want to search for a specific reference code (R&D 17) I could type `ref:R&D 17` in the search field.

### Actual behavior
The system doesn't search for reference code.

**Comment by gondzo** [comment]
@vic-topcoder ref codes are now included in the search (keyword search). do we still need to support ref:keyword?

**Comment by vic-topcoder** [comment]
support for `ref:` would be nice, but it is not a priority. I would not consider it a primary feature.

If I search for "HPE" on Dev, I see a lot of projects that I can't figure out why they are in my list. Look at the screenshot:
![screen shot 2018-01-26 at 3 11 29 pm](https://user-images.githubusercontent.com/8484061/35464560-64098ad4-02ab-11e8-9ca2-173b0940ee3e.png)

I am more concerned on what results we list, and why do I see them as the keyword is not highlighted in the returned results. I don't see why the second entry, "ts/fda" would be no match. Can we make sure that only relevant information entries are displayed? At the moment the search seems to return random results at best.

![screen shot 2018-01-26 at 3 15 14 pm](https://user-images.githubusercontent.com/8484061/35464623-c4baf98a-02ab-11e8-946d-196ee46d9ed1.png)

**Comment by chongluo** [comment]
Can you please clarify the goal of this fixing? Do you want to add ref search function?
After some investigation, I found the result returned from backend and there is no control on FE (for the returning result). Do you want to filter the result on front-end? If so, what is the criterial. Also a document about the backend api will greatly help. Where can I find it?

**Comment by gondzo** [comment]
@chongluo this one involves updating search logic at https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/list.js
keyword search is returning results that aren't exactly relevant to the keywork entered. I don't have a strategy/requirements for fixing this now so I'm removing it from the bugBash for now.

**Comment by gondzo** [comment]
@vic-topcoder the change in the backend that added searching by ref codes was causing issues in prod so I have reverted it temporarily until it's fixed properly

**Comment by vic-topcoder** [comment]
Ok, sounds good to me. We can fix this in CF8

**Comment by vikasrohit** [comment]
@gondzo removing this from cf09 as we are already working on this in private task.
