### ISSUE TITLE
Project Details page loading scrolled down if the project listing page was scrolled down

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#148]
Title is hard to get, just see this: http://take.ms/MmQuA

**Comment by vic-appirio** [comment]
There's something with react-sticky probably. The position of the left panel depends on it - discussed at #131

**Comment by fnisen** [comment]
@vikasrohit yes, I can't reproduce either, although it was happening to me earlier. This must have been fixed as part of some other work. Closing. Thanks.
