### ISSUE TITLE
Project owner

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1487]
Let’s say we have a project created by manager and a copilot is added to it. Who is actually project OWNER in that case? 
We require a user with customer role and isPrimary flag to be set to consider the user an owner.
@vic-topcoder @vikasrohit

**Comment by vikasrohit** [comment]
> We require a user with customer role and isPrimary flag to be set to consider the user an owner.
What is the current behaviour you are seeing @gondzo ?

**Comment by gondzo** [comment]
It's not an issue in connect-app, but I'm asking as it's needed in notifications where we should create a notification for project owner that hist project is created. That is a bit confusing when a manager or a copilot create a project - there is no owner and hence no notification.

**Comment by vikasrohit** [comment]
I guess that is okay because we even don't create lead in salesforce when a manager creates a project. But it is @vic-topcoder's call.

**Comment by gondzo** [comment]
So when a manager or admin creates a project there should be no
notifications at all?

**Comment by vic-topcoder** [comment]
Once we can bundle the notification we might want to create a system notification for Connect Admins - X-number of new projects created on the system. For the moment - no notification if admin/manager creates a project.

**Comment by gondzo** [comment]
status: we do generate the notification for manager user that his project is created - IMO it's a minor issue and we can remove the feature after the initial release ?

**Comment by vic-topcoder** [comment]
ok, create a reminder issue in https://github.com/appirio-tech/connect-app/milestone/36 please. Thanks!
