### ISSUE TITLE
Messaging: empty state for messaging tab

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#149]

**Comment by fnisen** [comment]
@vikasrohit FYI

**Comment by vic-appirio** [comment]
Let's have a default message that welcomes the user and allows for more help (do we have help for messaging in Connect? Do we need one?). This would resolve the issue of an empty page.
![messages empty](https://cloud.githubusercontent.com/assets/8484061/18804151/2e088150-81ac-11e6-8e27-71d82382258f.png)

When the user deletes the welcome message we can should them the compose form. Or the message can be deleted after the user creates their first message (which would be awesome). @fnisen @parthshah @vikasrohit what you think?

**Comment by parthshah** [comment]
@vikasrohit - check if the messages array is empty and show this default message other wise show the topics / posts ?

**Comment by fnisen** [comment]
Guys, can you please not implement this just yet... want to review/revise with Vic on Monday.

**Comment by vikasrohit** [comment]
Sure @fnisen Not started working on this yet.

**Comment by vic-appirio** [comment]
Let's add a message by coder on the landing page; and have the discussion composer available.

After the user opens the page, she should be able to compose a message right away, and can dismiss the greeting by Coder.

Once the new discussion topic is composed, the Coder message is automatically hidden.

Speck is here: https://drive.google.com/drive/folders/0B1LbmKnex41femttcVlPbVZobjA?usp=sharing

**Comment by vic-appirio** [comment]
@fnisen reassign for implementation.

**Comment by fnisen** [comment]
Thanks @vic-appirio. Ready for you, @vikasrohit.

**Comment by vikasrohit** [comment]
Changes are in dev. However, it shows the empty state even when the feeds are loading. It seems to be a bug with HOC used for showing loading spinner. I need @parthshah's help for that.
