### ISSUE TITLE
Connect Admin and Managers can see the user email address

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1496]
We should modify the API to present email address of all members (customers, managers, copilots, etc.). The case we need this is for the user tooltip on project details and subsequently for project details.

The problem right now is that the API doesn't support such data.
What we want to see:
![screen shot 3](https://user-images.githubusercontent.com/8484061/34230232-442f9aaa-e58c-11e7-8a21-2a29890a6dd0.png)

**Comment by gondzo** [comment]
Duplicate of #1535 ?

**Comment by vic-topcoder** [comment]
Yes. Closing
