### ISSUE TITLE
Dropdown menu doesn't take viewport bounds into consideration.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1497]
The drop-down should take into account the viewport bounds. Right now it is positioned via static CSS and gets cut at the end of the project grid.

Current:
![screen shot 4](https://user-images.githubusercontent.com/8484061/34233684-bd636f28-e59b-11e7-8c9e-0028dcd373bd.png)

Expected:
The menu would show on top of the click target when the viewport bounds would clip it with standard position.
![screen shot 5](https://user-images.githubusercontent.com/8484061/34233704-d9b6080c-e59b-11e7-8a74-d7b3c45773be.png)

Desired behavior: https://reactstrap.github.io/components/dropdowns/ - check the menu when the trigger (button) is very close to the browser borders.

Another example is https://tympanus.net/codrops/2013/05/23/tooltip-menu/; check the demo.

Ideally the solution for positioning the dropdown menu would be the same used for displaying tooltips.

Requirement - follow TC SCSS/HTML/JS best practices.

**Comment by maxceem** [comment]
As a quick solution, I propose to make the next. When we click in the top half of the screen - open dropdown **down**. If we click in the bottom half of the screen - open dropdown **up**, check video http://take.ms/QJfs5

To make it work more elegant way when it's open up only if it cannot fit down it's better to use some existent implementation of dropdown as there are a lot of edge cases usually.
