### ISSUE TITLE
Project list sort dropdown is not mis-aligned

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1502]
After latest release, it seems the sort dropdown got mis aligned.

<img width="203" alt="screen shot 2017-12-21 at 12 28 49 pm" src="https://user-images.githubusercontent.com/2417632/34244300-ad81ccf8-e64a-11e7-87b1-8602d4ca8984.png">

@gondzo can you please move it appropriate community milestone?

fyi, @vic-topcoder

**Comment by gondzo** [comment]
@vikasrohit is this still an issue with latest grid changes ?

**Comment by vikasrohit** [comment]
Nopes, I guess that filter has moved to different column. :) closing. Thanks
