### ISSUE TITLE
Still seeing double managers on grid in Dev

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1505]
![screen shot 3](https://user-images.githubusercontent.com/8484061/34268780-e14a1c3e-e636-11e7-9774-a8e3dd897a3b.png)
![screen shot 4](https://user-images.githubusercontent.com/8484061/34268810-f76a4598-e636-11e7-9824-8e1b037c8d93.png)

Can we verify those projects (screenshots) if there's something wrong with double managers?

**Comment by ThomasKranitsas** [comment]
@vic-topcoder where do you get that? I can't reproduce that.

**Comment by vic-topcoder** [comment]
My local environment

**Comment by ThomasKranitsas** [comment]
Can you please make sure you have the latest code?

I just checked with the `dev` branch and worked correctly.

You can verify that by checking `/src/projects/list/components/Projects/ProjectManagerAvatars.jsx` line 10 or 11.. If you see something like `managers.push(managers[0])` then you don't have the latest code.
