### ISSUE TITLE
Should we have some help text for email settings

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1506]
I am assuming that we are pointing to https://www.topcoder.com/settings/email/ from notification settings page right now because we don't have the email notifications settings right now in connect, only web notifications setting is available. So, I guess it would be better to have a help icon with tooltip saying something like _"Right now we are working on supporting email notification settings for projects. You can configure newsletter email settings via this link"_

<img width="662" alt="screen shot 2017-12-22 at 8 55 58 am" src="https://user-images.githubusercontent.com/2417632/34284300-e13bae18-e6f6-11e7-98fb-676f53ff8f7f.png">

fyi @gondzo @vic-topcoder

**Comment by vic-topcoder** [comment]
Created a ticket to move change help text and link #1513
