### ISSUE TITLE
Dismissing a notification from the dropdown closes the menu

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1508]
### Expected behavior
Dismissing a notification within the dropdown menu should reorder the items without closing the menu. The items underneath the notification should move up to take the available space.

### Actual behavior
Dismissing a notification closes the notifications dropdown menu

### Steps to reproduce the problem
- Open the notifications menu
- Dismiss a notification

**Comment by maxceem** [comment]
Quick fix. Just bring back the old custom implementation of Dropdown which has performance issues.

**Comment by vic-topcoder** [comment]
@maxceem - what are the performance issues of the old Dropdown? Is is safe to bring it back? How can we fix the dismissal of the menu with the component currently used?

**Comment by vikasrohit** [comment]
I would have suggested to fix the optimized implementation as it was implemented to reduce tech debt and now we have again introduced tech debt.
