### ISSUE TITLE
Rename "tcwebservice" to Coder Bot

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1509]
### Expected behavior
When the system posts (Coder Bot) I would like to see the name 

### Actual behavior
Currently the post author is listed as "tcwebservice"
![screen shot 7](https://user-images.githubusercontent.com/8484061/34284726-07644ee2-e689-11e7-9511-0b29f2cf65da.png)

**Comment by gondzo** [comment]
There are no more messages by Coder Bot in the notifications. We're already creating notification for project updates (status changes) so coderbot messages would be just duplicates
