### ISSUE TITLE
Replace Notifications center help text

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1513]
Please replace the notifications center text
"Answer just a few questions about your application. You can also provide the needed information in a supporting document—upload it below or add a link in the notes section."

with

"Notifications are a great way to get back to what matters. Somethimes things can be a bit overwhelming, we get it, so here you can turn off the things that bugg you. You can always turn them back on later. To modify your email notifications please follow <this link>" where <this link> is link to email settings from the bottom of the page.

![screen shot 5](https://user-images.githubusercontent.com/8484061/34284973-d223c88c-e68a-11e7-9e89-a30b38455a61.png)

**Comment by gondzo** [comment]
looks good.
