### ISSUE TITLE
Submit for Review not active

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1522]
Submit project for review is not active even when all fields are filled out
Sample project > http://connect.topcoder-dev.com/projects/2246/specification

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey @gondzo I think this one is critical as it prevents customers to submit projects for review. Hence, I am considering it as hotfix and will apply it to production as soon as fix works.

**Comment by vikasrohit** [comment]
Deployed as hotfix on production and dev both.
