### ISSUE TITLE
Reply notifications are not triggered/displayed

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1524]
### Expected behavior
When there's a reply to a thread on a project I'm member of, I should get a notification

### Actual behavior
Nothing happens

**Comment by vic-topcoder** [comment]
in #1468 we talked about response to Your post. When there is a response to a post in the project we still want to trigger a notification. The difference is in the language

1. Response to MY post:
- "Somebody responded to your post"

2. Response in my PROJECT:
- "Somebody responded to a post"

These can be simplified as only 1 notification "Somebody responded to a post" under the project. The nuance is subtle, but could help better drive the users' attention. We haven't talked about ranking of notifications at the time being, but it is good to make a note.

**Comment by gondzo** [comment]
this happened due to a config issue (wrong admin token). Works properly now.
