### ISSUE TITLE
Auto-update notification list

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1525]
### Expected behavior
I would expect to receive new notifications without having to reload my page. Should happen when my notifications dropdown is hidden (bell icon shows a badge), notifications dropdown is opened (a new item is added at the top of the notifications list), notifications home page (new item is added at the top of the list).

### Actual behavior
I have to manually reload the page to see new notifications

Can we implement the notification interface to be polling the service at regular intervals so that people will receive notifications without reloading the interface? This is very important and people we heard this complaint from our users before.

@gondzo - before we can implement this via web sockets, what would be the complexity to refresh behind the scenes to see if there are new notifications, and update the interface? If it is very complex to fix - let's move to CF6, but this is a priority. Ideally we can launch with auto-updates to notifications and update/upgrade system later.

**Comment by gondzo** [comment]
It shouldn't be too hard to add regular interval polling as we have a nicely structured global store for the notifications. I'll try to get this in before the release

**Comment by vic-topcoder** [comment]
Please make sure there are no flickers reloading the interface :)

**Comment by ThomasKranitsas** [comment]
@vic-topcoder @gondzo I've set the interval to 1 min.
You can update it by changing the `REFRESH_NOTIFICATIONS_INTERVAL` in `/src/config/constants.js` line 355

**Comment by vic-topcoder** [comment]
Oh, so cool. Let me see how it works.
