### ISSUE TITLE
Show all notifications per project on the dropdown menu

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1527]
### Expected behavior
Would expect to see the same behavior for notifications on dropdown menu and notifications center. When there are up to 10 notifications, we see them all, and when the notifications are >10 we show an element that allows to see them all (and a count of how many more notifications in that project).

### Actual behavior
The dropdown shows only the 2 latest notifications in the dropdown, and no indicator there are more notifications.

### Screenshot/screencast
![screen shot 20](https://user-images.githubusercontent.com/8484061/34314494-031509e4-e729-11e7-9342-af6caa7d89d1.png)

![screen shot 21](https://user-images.githubusercontent.com/8484061/34314489-feff10fc-e728-11e7-97c3-1781c44a3a4e.png)

Expected to see this element:
![screen shot 22](https://user-images.githubusercontent.com/8484061/34314523-3885af16-e729-11e7-85e3-dc949519cda7.png)

**Comment by vic-topcoder** [comment]
Failure to show that there are more notifications would confuse the users, as we do not support "new" notifications #1529

**Comment by ThomasKranitsas** [comment]
@vic-topcoder currently, the app shows 2 notifications per source and 10 in total. Do you want me to show 10 notifications per source and remove the total limit?

**Comment by gondzo** [comment]
let's use 10 per source limit and remove global limit. also, add the "View (total-numDisplayed) older notifications" link at the bottom should be updated
@ThomasKranitsas

**Comment by vic-topcoder** [comment]
@gondzo - that's correct. Thanks!
