### ISSUE TITLE
Being added to a project doesn't trigger a notification

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1528]
### Expected behavior
When somebody adds me to a new project, I should get a notification so I can start participating in the project

### Actual behavior
Notification is not triggered

### Steps to reproduce the problem
- Log in as "Pat Monahan", add "Christina" to a new project
- Log in as "Christina" and check for notification - missing.

### Screenshot/screencast
![screen shot 24](https://user-images.githubusercontent.com/8484061/34314735-ba78b520-e72b-11e7-9df2-8e525f8fbd52.png)

**Comment by gondzo** [comment]
Looks like it is specific to christina_uw account. I can't reproduce it with other accounts (pshah_*)

**Comment by vic-topcoder** [comment]
Why is that occurring for this account?

**Comment by gondzo** [comment]
no idea, looking into it..

**Comment by gondzo** [comment]
this one was also happening due to a configuration issue. works properly now.
