### ISSUE TITLE
[$600] Detect if a notification has been seen vs. new notifications

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1529]
### Expected behavior
When the system sends out new notifications that I haven't see, I want the bell icon to have a red badge and the new notifications the have blue left border to indicate I haven't seen them.

The red badge would disappear once I open the drop-down menu.

The blue border would disappear once I click on the notification or visit the target location.

### Actual behavior
This doesn't exist currently

**Comment by gondzo** [comment]
@vic-topcoder do we need to remember which notifications are seen (save to database), or just consider new notifications since page load as non-seen?

**Comment by vic-topcoder** [comment]
Ideally we want to have a flag so if I have multiple instances or something else happens it won't be artificial. I can open and close the notifications menu, but that shouldn't change the status of the notification being seen.

**Comment by tpwwu** [comment]
@vic-topcoder consider that this is the first time I open the page, and there are some unread notifications. Should the red badge and blue border appear?
If so, i open the  drop-down menu, then, red badge disappear and blue border is still there.
Now, I refresh the page or open the page in another tab, what status do you expect?

**Comment by vic-topcoder** [comment]
> Now, I refresh the page or open the page in another tab, what status do you expect?

This would clear the blue border of the posts that were previously on the page. If there are new posts since you were on the page, you'll see the new post with a blue border.

Any notification that is for that particular page should be considered "viewed" - if there are still notifications you haven't seen, the red dot remains. If all notifications were for the page you just refreshed, the red dot would disappear.

**Comment by zjuasmn** [comment]
My approach is:
1. add a new array state 'touchedIds' to notification store to store visited or clicked notification in current session. 

2. add a new state 'lastVisited' to notification store. When user click the dropdown, update 'lastVisited' to the latest notification time. The red dot only appears when 'lastVisited' is early than latest notification time.

![image](https://user-images.githubusercontent.com/4462778/37189372-f660cc4a-238e-11e8-8296-d76e5af2b9dc.png)
