### ISSUE TITLE
Mismatch between project type icon on details and projects grid

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1531]
### Expected behavior
Each project would have the correct icon --  actual project template (product) -- in all interface instances.

### Actual behavior
On the project grid the icon displayed is the section icon vs. the actual project template (product) icon displayed on the project details page.

![screen shot 3](https://user-images.githubusercontent.com/8484061/34316406-b392435c-e749-11e7-8ea7-19778fc849de.png)
![screen shot 2](https://user-images.githubusercontent.com/8484061/34316407-b3a52d46-e749-11e7-9992-83423a4a61bd.png)

**Comment by gondzo** [comment]
looks good.
