### ISSUE TITLE
[$40] Unify the use of the Avatar component on project grid and cards

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1533]
### Expected behavior
I would expect to see the same avatars on all instances of the interface.

### Actual behavior
On the project grid we render empty avatar, but we have a specific component that renders different color and user initials on the project cards view. Please replace the avatar on project grid to match.

The avatar should fit 30 x 30 px on the Grid.

- [ ] Reduce the overlap of avatars to 5px (from 10)
- [ ] Make sure there's enough space between additional number (4+) managers on a project

![screen shot 1](https://user-images.githubusercontent.com/8484061/34316481-5f061c44-e74b-11e7-94fc-702f09a22293.png)
![screen shot 2](https://user-images.githubusercontent.com/8484061/34316482-5f190476-e74b-11e7-969f-df933139ab74.png)
![screen shot 3](https://user-images.githubusercontent.com/8484061/34316483-5f2a6dba-e74b-11e7-8484-0ef089175c5b.png)

**Comment by maxceem** [comment]
@vic-topcoder Could you please clarify 
> Make sure there's enough space between additional number (4+) managers on a project

Not sure how to see the issue.

**Comment by gondzo** [comment]
created a followup issue #1593
