### ISSUE TITLE
[$200] Update the user tooltip with a unified component in all instances

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1534]
Let's use the same component consistently in the system. 

Hovering over the user avatar in short form (picture only) I want to see the full details of the user.

Hovering over the extended user avatar (picture and name/handle) should be the same.

Right now the projects grid auto-generates the HTML for each user and displays it on hover. We should be smarter and not generate too much HTML for the browser - this slows down performance and tracing the DOM/manipulations.

**Comment by gondzo** [comment]
the scope here are avatars in project listing (grid and card view), project members list in project details and avatars in topic posts on project dashboard

**Comment by passimm** [comment]
hi, here is my understanding of the request, not sure i understand correct. could you correct me or shed more light?

1. we're already using a component "<UserTooltip>" in projectGridView. the component itself needs no change.
2. we should leverage this component in other places whenever a user avatar/name/handle is displayed.

**Comment by vic-topcoder** [comment]
1. The tooltip component should be smart enough to detect viewport edges. This will allow the tooltip to be always visible in all cases. Right now the tooltip isn't smart enough and always shows in the same position (above the item). Check http://wwayne.com/react-tooltip/ for viewport detection. Adding the tooltip in the grid component generates a tooltip with data for each avatar, on every row, and this increases the amount of HTML generated. Parsing the HTML and CSS for all the extra tooltips slows down page performance. The goal is to reduce the generated code significantly. More about smarter tooltip strategies here: https://medium.com/@CunningFatalist/tooltip-best-practices-3155f8daa6dc. I like the idea of reusing the data for tooltips through UID, assigned for each unique avatar. We have a lot of avatars that are repeated throughout the grid, so we don't need to transmit that code over and over again, or render it all the time. The idea of a single HTML component that is updated through event handler is even better, as long as we don't transmit all the data needed all the time. Ideally we can have:
    - One HTML component that is positioned, displayed, and modified with appropriate data through event handler.
    - All the tooltip data is transferred alongside the project data so we don't do too many additional calls to the server. Ideally the tooltip data is available as an array of UID data for each avatar. This data is used to render all the Avatars and populate the tooltip on hover. Also - if we can use local store to keep this that for later use it'll be great - cache optimization. The grid is heavily used by small amount of users, so caching the data makes a lot of sense for them.

2. Yes - the tooltip component should be using other components to render different content in different cases. Right now we want to attach the tooltip component to all instances of avatars so we display the data consistently. Tooltip should use controlled components to render what is needed.

**Comment by maxceem** [comment]
@vic-topcoder
1. Could please share with me any existent case when tooltip should behave smartly to respect viewport edges but it doesn't.

2. I'm checking existent implementations if any fit our requirements. Is that ok, or you prefer improving our own implementation?

**Comment by gondzo** [comment]
1. I think this is one of the cases 
![image](https://user-images.githubusercontent.com/3051646/34821382-ccde1500-f6c3-11e7-8d11-afe0981b537e.png)

2. either is fine IMO

**Comment by vic-topcoder** [comment]
I was thinking that the tooltip positioning would be a generic utility that can be shared with the dropdown menus. Ideally we can use this to provide edge detection for all such components in the future.

We have user avatars and the tooltips should be attached to all instances of avatar without username. This includes the cards view. That's where we can have all corners cases top/bottom right/left

We also have to fix the project status dropdown (you did some calculations to change the position based on height).

![screen shot 2018-01-11 at 3 53 31 pm](https://user-images.githubusercontent.com/8484061/34853346-1accc56c-f6e8-11e7-97e5-111b91945a7a.png)
![screen shot 2018-01-11 at 3 53 46 pm](https://user-images.githubusercontent.com/8484061/34853348-1ae06482-f6e8-11e7-8232-d31ab9287e8b.png)
![screen shot 2018-01-11 at 3 53 18 pm](https://user-images.githubusercontent.com/8484061/34853349-1af1e69e-f6e8-11e7-82bc-787fbedfa098.png)
![screen shot 2018-01-11 at 3 54 39 pm](https://user-images.githubusercontent.com/8484061/34853350-1b041602-f6e8-11e7-8f31-ef339484b3dc.png)
![screen shot 2018-01-11 at 3 55 35 pm](https://user-images.githubusercontent.com/8484061/34853351-1b150318-f6e8-11e7-8bee-dc6b33070e2a.png)

**Comment by maxceem** [comment]
I've checked several existent general utilities which looks like provide this behavior and tried to fix the one which looks the best for this. But with no luck so far. All of them have issues for our case. I have to get a couple of days rest so I will unassign this task from me for now. If nobody picks up, I will come back to it after rest.

**Comment by anonymousjaggu** [comment]
@vic-topcoder can I am not able to understand this issue, can you please make clear this issue to me

**Comment by anonymousjaggu** [comment]
@gondzo can you tell me the exact requirement for this

**Comment by gondzo** [comment]
Just read the above comments - the tooltip is displayed when hovering user avatars in project listing and project details pages. We should update the code to use one component for all instances and improve it per the above requirements (viewport edges, single html for all avatars, etc)

**Comment by maxceem** [comment]
**Update**
Looks like I've found a good package [react-popper](https://github.com/souporserious/react-popper) which wraps [popper.js](https://popper.js.org/) and now reimplementing Tooltip.

There were few others which didn't work in some reasons FYI:

Git | Add/remove node | Auto-align | Demo | Comments
-|-|-|-|-
[react-popover](https://github.com/RobertMenke/react-popover) | - | Yes | - | -
[react-tiny-popover](https://github.com/alexkatz/react-tiny-popover) | Yes | Yes | [demo](https://alexkatz.github.io/react-tiny-popover/) | Doesn't support React v15 - submitted a [PR](https://github.com/alexkatz/react-tiny-popover/pull/8) and published fork in [npm](https://www.npmjs.com/package/@maxceem/react-tiny-popover). But still has some issues and cut popup. Also recalculates position during resizes due to absolute positioning.
[react-awesome-popover](https://github.com/vaheqelyan/react-awesome-popover) | Yes | Yes | [demo](https://jsfiddle.net/vaheqelyan/6qogfdkr/17/show/light/) | Doesn't support React 15
[react-popover](https://github.com/littlebits/react-popover) | Yes | Yes | [demo](https://littlebits.github.io/react-popover/) | Even on their demo has some issues when we there is a scrollbar on the page and we move popup to the right.

**Comment by vic-topcoder** [comment]
Sounds cool, let's do it! Can we also use this utility for modals and dropdowns?

**Comment by maxceem** [comment]
> Hovering over the extended user avatar (picture and name/handle) should be the same.
Not sure what should be in a tooltip in such case. As all the information which we usually show in the tooltip is already displayed.

**Comment by maxceem** [comment]
@gondzo Looks like previously I've posted [PR](https://github.com/appirio-tech/connect-app/pull/1587) requests against `dev` branch instead of `bugBash06`. And now there are no changes for issue #1533 - **Unify the use of the Avatar component on project grid and cards**. But changes in the current issue would rely on them.

Do you thing is it possible to get that PR applied to `bagBush06` branch in some way?

**Comment by gondzo** [comment]
You can create a pr to dev, bugBash06 is merged there

**Comment by maxceem** [comment]
@vic-topcoder just in case want to tag you regarding this question:

> Hovering over the extended user avatar (picture and name/handle) should be the same.

Not sure what should be in a tooltip in such case. As all the information which we usually show in the tooltip is already displayed.

For example, here http://take.ms/r9wbV all the information is already displayed, which we usually show in tooltip http://take.ms/mJv3J.

**Comment by vic-topcoder** [comment]
> extended user avatar

I meant for when we're going to add more information, pulled from SalesForce. That's for the future.
