### ISSUE TITLE
Replace email sender [Epic]

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1536]
_**For discussion puproses - we might need to move this to a new dedicated milestone**_

Replace the emails for notifications to be send through the notification center vs. the current Discourse email events.

- [x] Email templates

- [x] Email infrastructure

~~- [ ] Email settings~~ (Now being handled via https://github.com/appirio-tech/connect-app/milestone/50)

~~- [ ] Email bundling~~(Now being handled via https://github.com/appirio-tech/connect-app/milestone/50)

- [x] Track emails being opened/not opened;

**Comment by gondzo** [comment]
we need to develop email delivery for notifications before moving onto this one

**Comment by vic-topcoder** [comment]
Let's move it into a new milestone and break it down piece by piece. Discussed with @mtwomey and it will take some time to figure out what we have currently; before we proceed with actual development.

**Comment by vikasrohit** [comment]
@vic-topcoder only two things are pending now from the list:
1. Enabling email settings in connect which I think should be quick. Correct me @gondzo if I am wrong here.
2. Email bundling.

**Comment by gondzo** [comment]
Agree on email bundles.
At the moment we send only messaging emails and nothing for other project updates, so we need to enable email settings in connect and update tc-notifications to send emails based on those email settings.

**Comment by vikasrohit** [comment]
Pending items are now being handled via https://github.com/appirio-tech/connect-app/milestone/50).
