### ISSUE TITLE
[$250] Redesign and remove unnecessary project activity cards from Dashboard 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1538]
All project activity cards that are posted by Coder must be dismissible, so the users can focus on the communication stream. This should take effect on all new projects, and if possible we can clean the old projects.

The goal is to hide posts from Coder the Bot on the dashboard feed (system posts).
![notification card](https://user-images.githubusercontent.com/8484061/35463158-2afb0576-02a4-11e8-986d-26f528557243.png)

Final design: https://drive.google.com/drive/folders/1KMol1fOfOjhBMV6GFY1uh6_2N0Ae6esh?usp=sharing

Please reuse the existing resources, make sure to import the SVG as component directly, no CSS backgrounds. Icon fill should be done through CSS class.

or download the speck as .zip
[Notification Card Final.zip](https://github.com/appirio-tech/connect-app/files/1669355/Notification.Card.Final.zip)

**Comment by gondzo** [comment]
Is this covered by the changes in #1566 @vic-topcoder

**Comment by vic-topcoder** [comment]
This is covered partially. I want to redesign the remaining notification posts to be dismissible from the dashboard when the user reads them. We did remove the user activity and admin activity posts already, so I'm going to add the design for this one by EOD tomorrow.

**Comment by gondzo** [comment]
@vic-topcoder ☝️ 
move this to CF7?

**Comment by gondzo** [comment]
@vic-topcoder do we have the designs for this one?

**Comment by vic-topcoder** [comment]
We actually do! All project activity cards that are posted by Coder must be dismissible, so the users can focus on the communication stream. This should take effect on all new projects, and if possible we can clean the old projects.

The goal is to hide posts from Coder the Bot on the dashboard feed (system posts).

Final design: https://drive.google.com/drive/folders/1KMol1fOfOjhBMV6GFY1uh6_2N0Ae6esh?usp=sharing

Please reuse the existing resources, make sure to import the SVG as component directly, no CSS backgrounds. Icon fill should be done through CSS class.

or download the speck as .zip
[Notification Card Final.zip](https://github.com/appirio-tech/connect-app/files/1669347/Notification.Card.Final.zip)

**Comment by jyoti0208** [comment]
Want to work on this but not able assign this to me.

**Comment by vic-topcoder** [comment]
@gondzo - any progress on this one?

**Comment by gondzo** [comment]
@vic-topcoder not yet, I've missed this one.
What do we do when the user clicks the close icon? Just hide it for that session, or hide if permanently? If it's the latter one, we should wait until we move off discourse - we don't have any per user/post storage where we could store this flag and I don't have any good ideas on how best to implement it.

**Comment by vic-topcoder** [comment]
Hide it permanently. By default we should show only the latest status update card if it wasn’t seen/dismissed yet.

**Comment by gondzo** [comment]
@vikasrohit does this feature fit in with the model you're building for moving from discourse ?

**Comment by gondzo** [comment]
on second thought, we already have these same events in notifications, so we don't need coder-bot posts at all. when viewing project dashboard, we can use unread project activity notifications for that project and show the latest one as the card in the top. when clicking the close icon, we'd mark the notification as read. makes sense ? @vic-topcoder

**Comment by vic-topcoder** [comment]
That’ll b the best! Let’s reuse the notifications!

**Comment by asadath1395** [comment]
Hi
What exactly is the task here? Can someone explain clearly

**Comment by Colinh84** [comment]
@vic-topcoder @gondzo There seems to be a problem with the notifications API where every request always returns `{"items":[],"offset":0,"limit":1000,"totalCount":0}` even when there should be notifications for an action. I have not even seen a single notification in the past 3 days with any user. This task is not possible to complete at the moment without the notifications working if you want the events in notifications to replace the coder-bot posts as discussed above..

**Comment by Colinh84** [comment]
@zjuasmn This issue is not open for you to take. I am still waiting on a response from @vic-topcoder or @gondzo. I actually have a solution ready to go but need to test it with the notifications API which is not working right now.

**Comment by gondzo** [comment]
@Colinh84 notifications are now working properly

**Comment by Colinh84** [comment]
@gondzo I'm not sure that it is working.. If I create a new project or make changes to an existing one, a notification is still not generated. Every request to `https://api.topcoder-dev.com/notifications?read=false&limit=1000` returns an empty response of `{"items":[],"offset":0,"limit":1000,"totalCount":0}` for all test users such as `pshah_customer`, `pshah_manager` and `pat_monahan`..
In any case, I was able to test my solution with dummy data and it works.

**Comment by Colinh84** [comment]
@gondzo You are correct, it is working now as you described. I retested my solution with the live API and it is still working. However, there may be another problem with the API as making a request to the mark as read endpoint generates an XML parsing error in the console from the API response:
`XML Parsing Error: no element found
Location: https://api.topcoder-dev.com/notifications/11849/read`
Not a critical error, as the notification still gets marked as read, but might be something to look into..
