### ISSUE TITLE
[$40] Provide link to manage profile from user dropdown

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1539]
### Expected behavior
The Connect customers should be able to modify their profile and account settings. Let's provide them with a link to the Connect app to manage their settings through the user dropdown.

![screen shot 5](https://user-images.githubusercontent.com/8484061/34316613-08cdd3f4-e74f-11e7-9520-0d389c491620.png)

Expected:
![screen shot 6](https://user-images.githubusercontent.com/8484061/34316615-0a1dc066-e74f-11e7-854d-750d3b31a3d1.png)
should lead to https://www.topcoder.com/settings/account/

We need to rebuild the interface in the settings section so we don't navigate to a new app, but this is a shortcut to provide functionality until we have the interface in place.

@mtwomey let's discuss the best approach to expose the account and profile settings in Connect; and app-specific settings

**Comment by vikasrohit** [comment]
Apologies @vic-topcoder for chiming in, however, my two cents about this topics is that the more interfaces we create around common features such as profile management, we might end up situation where when we update something in backend for such interfaces, we might not know all places where there are being used. We faced this with login pages with multiple applications across the topcoder.

**Comment by gondzo** [comment]
@vic-topcoder should we show the profile settings screen in the connect app (it's hidden now, but it's not wired to the api), or just link to https://www.topcoder.com/settings/profile/

**Comment by vic-topcoder** [comment]
As of right now, the solution I suggested here is to direct people to the Topcoder community app / Settings page `https://www.topcoder.com/settings/profile/`. There is no easy way for people that are part of Connect to find and modify their profiles. I wanted to allow them to use the same interface inside Connect as well (which would point to the same API), so we can have only the elements that are relevant for the Connect user. We also need to support different fields for the Connect user profile vs. the Topcoder competitor profile.

**Comment by vikasrohit** [comment]
@vic-topcoder Agree with need of separate profile page for Connect users as they are customers not members. However, my only concern is to avoid the state in future where we think to consolidate the two profile pages into one just like we are facing for two separate logins for members and connect users. We started with two separate logins for these two types of users with exactly same intention as we have for profile section.

**Comment by vic-topcoder** [comment]
The separation between profile and accounts is a deeper topic and not part of the issue, and we'll have to talk it through :) Thanks for your notes @vikasrohit, it is useful!

**Comment by tpwwu** [comment]
@vic-topcoder just to make sure, the link is https://www.topcoder.com/settings/profile/, and text should be` Profile Setting`

**Comment by tpwwu** [comment]
PR: https://github.com/appirio-tech/connect-app/pull/1582
