### ISSUE TITLE
[$60] Skip notifications for managers

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1545]
Skip creating notifications for managers/admins when they are creating a project

**Comment by shubhendusaurabh** [comment]
@gondzo which notification are we talking about here?
Is it the message from Coder Bot in dashboard page?

**Comment by gondzo** [comment]
notifications in the top right corner
the change needs to be made to this repo > https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/connectNotificationServer.js

**Comment by maxceem** [comment]
Done by PR to tc-notifications https://github.com/topcoder-platform/tc-notifications/pull/12

**Comment by maxceem** [comment]
I've forgotten to commit updated event config file with my PR. It didn't break anything btw, just didn't make an effect. So I've added a missed file in this PR https://github.com/topcoder-platform/tc-notifications/pull/14 to `tc-notifications`. Also fixed few lint errors.
