### ISSUE TITLE
[$100] Do not show notifications for actions that I do on the system

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1546]
### Expected behavior
When I create a new post, I don't want to get a notification that I created a new post. 

### Actual behavior
Currently I get a notification that I created a new post.

Login with Christina Underwood account and create  a new post. You'll get a notification.
![screen shot 1](https://user-images.githubusercontent.com/8484061/34360763-a2513680-ea18-11e7-9508-ccefb0a1ef4c.png)

**Comment by gondzo** [comment]
the change should be made at https://github.com/topcoder-platform/tc-notifications/tree/dev/connect

**Comment by passimm** [comment]
hi gondzo and vip-topcoder,
    i have made a [https://github.com/topcoder-platform/tc-notifications/pull/11](PR) to fix this. However I'm not authorized to remove "Open for Pickup" tag. Could you help:
1) grant access to me
2) remove the tag

Many thanks!

**Comment by chq-matteo** [comment]
@passimm have you requested access to the repo in the challenge forum?
you can mention people with @gondzo

**Comment by gondzo** [comment]
@passimm you should have access now

**Comment by passimm** [comment]
@gondzo thanks. have access now.
i'm fixing PR

**Comment by passimm** [comment]
@gondzo. fixed comment. thanks.
https://github.com/topcoder-platform/tc-notifications/pull/13

**Comment by passimm** [comment]
@gondzo could you help take a look at the PR. thanks
https://github.com/topcoder-platform/tc-notifications/pull/13

**Comment by passimm** [comment]
@vic-topcoder @gondzo 
kindly ping for
topcoder-platform/tc-notifications#13

**Comment by gondzo** [comment]
this is now working properly for all events (project status, project members, posts, mentions) - no notifications for your own actions
