### ISSUE TITLE
Project title is incorrect on notification section.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1553]
### Expected behavior
Created a project with a title "Chatbot project for notification testing" (https://connect.topcoder-dev.com/projects/2357/#comment-6758) but on the notification center the title of the project is only "project". I'd expect the title to be the same "Chatbot project for notification testing" in all instances.
![screen shot 3](https://user-images.githubusercontent.com/8484061/34373198-a5adf2f2-ea8e-11e7-880d-41f2709494b8.png)

@gondzo FYI

**Comment by gondzo** [comment]
This is now fixed (need to clear all earlier notifications for this to take effect)

**Comment by vic-topcoder** [comment]
👍
