### ISSUE TITLE
[$50] If there's a new notification for the same page, clicking on the notification should reload the page to show the updated information

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1562]
### Expected behavior
When a user is on the dashboard and they receive a notification for a new post on the same page, clicking on the notification should reload the page and scroll to the new content.

### Actual behavior
Clicking on a notification while in the same page doesn't reload the page and thus one can't see the new posts. The notification just scrolls to the latest loaded comment on the page

**Comment by anuradevtc** [comment]
I didn't receive write access, can I push an pull request without even assigning here?

**Comment by anonymousjaggu** [comment]
@gondzo how to check that ? can you please share the details where can I check this or any screenshots

**Comment by gondzo** [comment]
when you have a notification for a project that you have currently open, then clicking the notification should reload the project page (right now it does nothing as the route stays the same)

**Comment by anonymousjaggu** [comment]
can I get any UI navigation for this or the steps how to get new notifications for the logged in credentials

**Comment by vic-topcoder** [comment]
You'll need to log as 2 users so you can trigger a notification on a project page.

- With both accounts log in and open a project. Both accounts should be part of the project. We use 'christina_uw' and 'pat_monahan'
- Clear all notofications for user 1, stay on the project page
- With user 2, create a new post and/or reply. This will trigger a notification to user 1
- User 1 would see the notification for a reply within the project. Click on the notification for a new reply. The page would scroll to the last reply loaded on the page.

This is what the fix must do - if the user is on the same page for which a notification is triggered, clicking on it should reload the page to display the new item. Right now pages don't update until hard refresh from the user.

Hope that helps

**Comment by anonymousjaggu** [comment]
I am getting this while trying to login 
{valid: false, reasonCode: "ALREADY_TAKEN", reason: "Handle 'pat_monahan' has already been taken"}
and not able to proceed

**Comment by gondzo** [comment]
you should log in, not try to register a new user > https://accounts.topcoder-dev.com/#!/connect?retUrl=https://connect.topcoder-dev.com/
