### ISSUE TITLE
Post order on dashboard is not right

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1565]
Latest posts are not on top of the post feed. Reported for https://connect.topcoder.com/projects/4840 and several other projects.

We must display the latest posts on top of the feed and make sure that they are ordered by activity. Is this still a bug?

>An issue I just saw - I posted the "Challenge Live" project update - but it is now at the bottom of the lists of updates? When I returned to the project I thought it was missing until I scrolled to the bottom. The Copilot didn't see so they also posted the same message. https://connect.topcoder.com/projects/4840

Can we investigate and find out what is the root cause of this?

@vikasrohit @gondzo @mtwomey FYI

**Comment by vic-topcoder** [comment]
Post order should be "most recent first" where any comments on a post would push the post at the top of the feed. If you open https://connect.topcoder.com/projects/4279 you'll see how the posts are not ordered by post date/activity date.
![screen shot 5](https://user-images.githubusercontent.com/8484061/34430408-b2263b2a-ec19-11e7-9ed9-1f26d5b860ed.png)

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey I  am still debugging it, trying to reproduce the problem on local. Will  be working on it tomorrow as well.

**Comment by vic-topcoder** [comment]
Thanks!

**Comment by vikasrohit** [comment]
Github issue#1565, Post order on dashboard is not right
- [x] Fetched all posts of a topic to determine the lastActivityAt field for a topic, earlier it was using only first 20 posts for the calculation which was causing wrong lastActivityAt for topics having more than 20 posts.
- [x] Handled `removed_user` post by discourse admin which was posted when a user is removed from the allowed users list of the topic. It was also the reason of wrong calculation of lastActivityAt field for a topic.
- [x] Found new system message `user_left` post by discourse admin which was posted when system removes itself from the topic. It was also the reason of wrong calculation of lastActivityAt field for a topic.
- [x] Used `updated_at` field for calculating the `lastActivityAt` field value to correctly sort the topics/posts which are edited
- [x] Fixed breaking unit tests and added/updated unit tests to more rigorously test the logic

**Comment by vic-topcoder** [comment]
Oh my, this one seems quite epic! Great job, @vikasrohit! We also stopped posting messages for users joining or leaving a project, correct? This should also reduce the number of posts and not conflict the sort order.

**Comment by vikasrohit** [comment]
> We also stopped posting messages for users joining or leaving a project, correct?

@vic-topcoder yes that is one but not deployed to production yet because I didn't fix that as hotfix. So, it should be there in dev but not on production. It should go to production with upcoming `community fixes 06` milestone release.
