### ISSUE TITLE
Remove system activity posts on dashboard for notifications launch

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1566]
Let's start with the removal of 

Ownership related posts
Team member, copilot, and manager  joined/left project posts

These are now all covered by notifications anyway, and they create too much noise on the dashboard.

![screen shot 1](https://user-images.githubusercontent.com/8484061/34420527-ed4a37ca-ebbe-11e7-875a-f88bf3e5d9da.png)
![screen shot 2](https://user-images.githubusercontent.com/8484061/34420528-ed5daf44-ebbe-11e7-9150-710b15100606.png)
![screen shot 3](https://user-images.githubusercontent.com/8484061/34420529-ed75e49c-ebbe-11e7-8fc4-d2d64af0216e.png)

We want to keep:
- Project is created, ready for specification
- Project is in review
- Project is active (work started on project)
- Project is completed

I think it should be easy to turn those off. @vikasrohit I'm assigning it to you, but feel free to reassign if appropriate.

**Comment by vikasrohit** [comment]
Done. Changes should be there on dev.

**Comment by vic-topcoder** [comment]
Awesome.

**Comment by gondzo** [comment]
@vikasrohit Looks like this didn't go to prod. What are the relevant commits here ?

**Comment by vikasrohit** [comment]
Yes, it seems the changes were not deployed when release went to production. Create [PR](https://github.com/topcoder-platform/tc-connect-notifications/pull/79) for it, however, I would like to do this deployment on Monday to avoid any issues on production during weekend. If it is urgent, you can merge the PR and it should be good to go.

**Comment by vikasrohit** [comment]
Deployed on production now. Verified as well. I am not seeing the team activity anymore. Please let me know if you still the team activity cards for any activity from now on.
