### ISSUE TITLE
Post title should be editable after project is created

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1567]
Seems like editing the project title is not reflected everywhere when it is done after project is created. Adam wanted to change a project title after it was created. The title of his project is changed in the interface, but the system still displays the original title in all project reference links.

Look at https://connect.topcoder.com/projects/4840
![screen shot 4](https://user-images.githubusercontent.com/8484061/34420724-f355d57e-ebbf-11e7-87ef-744c9c07f4f5.png)

- [ ] Project title should be editable after project is created - it is not unique field and we must not lock the public editing project title. This means title field stays editable all the time.

- [ ] Title should be the say everywhere in the system when it is displayed - interface, links, url, etc.

**Comment by gondzo** [comment]
This one won't be so easy - Coderbot messages are generated on specific events (project owner changed, in review, etc). To have them updated on the fly would require a LOT more API calls. 
We'll have the same issue with notifications - data is fetched at the time notification is generated, not at the time of display

**Comment by vic-topcoder** [comment]
Yeah, we should research further what are the complications with title. Ideally the interface is rendering the data based on some ID that is unique, while things like title, description, names can change, and the interface would re-render them based on the changes. There can be a case where team member changes names, so all posts done by the user should be rendered at the time a change is detected. It is the same for project Title and Description.

**Comment by gondzo** [comment]
Solving those cases would require a good deal of reworking the api details - if we have 100 notifications for 50 different projects that's a lot of calls to the projects service just to fetch project names. Same thing with all user details, messages, etc

**Comment by vikasrohit** [comment]
I know the trouble with updating project title. However, I don't think makes sense to allow editing a system message manually to reverse a mistake in setting up the project. And the other way is to do automatically update all the system message automatically, when updating the project title, and as @gondzo said it is really overkill to achieve that.
And anyhow we should do this behind the scene thing, with only admin power and through admin tool. I mean this operation should be achieve through support staff with proper logging. Also, despite all efforts, we can't change the project name in the emails that already sent. We can make changes to our code bot messages such that we parse the project link at run time in the front end app, however, when you send an email you have to parse the project link at the time of sending the email which can not be updated later.

And this problem will not be limited to title only, we might request for certain customer has changed his/her first name or last name, which we are posting in coder bot messages and customer want to see updated name in the messages as well.

**Comment by gondzo** [comment]
I agree @vikasrohit 
we are already rendering up to date project name in the grid/cards view and project details, ie dynamic content, but for static content like messages and notifications it would be really tricky to support this.
@vic-topcoder can we close this one as not feasible?

**Comment by vic-topcoder** [comment]
Yes, if we do whatever we need to support dynamic project title. Thanks guys

**Comment by vikasrohit** [comment]
Sorry to comment on a close issue, however, I think one way to increase the reach of dynamic title (considering the frequent demands of editing project titles) is to persist title in the message as variable i.e. something like `${project_title}`, and replace it actual project title when returned via the API endpoint. However, this still won't fix the emails that were sent with old project title.
