### ISSUE TITLE
[$50] Fix jumping footer when toggle filters

### ISSUE THREAD

**Issue by ThomasKranitsas** [appirio-tech/connect-app#1569]
### Steps to reproduce the problem
- Login as copilot/manager
- Toggle the filters
- Notice the footer

### Screenshot/screencast
http://take.ms/NnxbZ

**Comment by tpwwu** [comment]
@gondzo May I fix this? looks like @ThomasKranitsas assigned himself 1 month ago

**Comment by gondzo** [comment]
Yes
