### ISSUE TITLE
Project grid and project details don't list the correct managers

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1572]
### Expected behavior
Managers listed on the project list don't match with the actual project managers list.

Look at https://connect.topcoder.com/projects/4656

![screen shot 6](https://user-images.githubusercontent.com/8484061/34430473-59f91764-ec1a-11e7-93a8-21e20edb6864.png)

![screen shot 7](https://user-images.githubusercontent.com/8484061/34430475-6175a5e8-ec1a-11e7-880b-7a81bbd4253d.png)

**Comment by gondzo** [comment]
@vikasrohit can you take this one as it requires access to prod

**Comment by vikasrohit** [comment]
@vic-topcoder Patched it on production.

**Comment by vic-topcoder** [comment]
I still see it for couple of active projects: 4749 and 4705. Did we refresh the cache?

<img width="1166" alt="screen shot 2018-01-08 at 11 47 56 am" src="https://user-images.githubusercontent.com/8484061/34689463-7b388196-f46a-11e7-8d0b-9fb1eaa91972.png">
<img width="1162" alt="screen shot 2018-01-08 at 11 47 13 am" src="https://user-images.githubusercontent.com/8484061/34689471-809d9f86-f46a-11e7-92ec-028f35864cb3.png">

**Comment by vikasrohit** [comment]
@vic-topcoder both projects seems okay to me. They are showing correct managers. However, it seems like Grid is either using different Avatar component or using different set of props to the same Avatar component than what is used in project details' team management section.

**Comment by vic-topcoder** [comment]
So - upgrading the grid to use the proper avatar component should fix it? I think this ticket is in regards with project list first and foremost, so I won't close it until we have the same avatars/numbers on the Grid as in the project dashboard.

**Comment by vikasrohit** [comment]
Yes, it should. @vic-topcoder  I found that managers count is always correct for me between list and dashboard pages. However, there is a different in the way Avatar component is used in both places. List page supplies a placeholder image to Avatar component while dashboard does not. When we don't provide any image URL to Avatar component, it creates a avatar from user's initials.
So, let me which one we want to keep.

**Comment by vic-topcoder** [comment]
We're replacing the avatar on the grid to be the same component, so this should fix the problem. I'll close this issue and open a new one during testing if need be.
