### ISSUE TITLE
[$30] Customer name overflows into managers

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1573]
### Expected behavior
When a customer name(s) are too long, hide them with an ellipsis. (…)

![screen shot 1](https://user-images.githubusercontent.com/8484061/34430513-bd535b26-ec1a-11e7-93f4-7ce9151717b6.png)

**Comment by anuradevtc** [comment]
!

**Comment by anonymousjaggu** [comment]
@gondzo can you please provide the credentials for it?
for a new user I can't see this detail

**Comment by gondzo** [comment]
you can log in with pat_monahan/topcoder123!
