### ISSUE TITLE
Comment count is wrong on production

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1579]
### Expected behavior
Comment count should be correct.

### Actual behavior
Login to Connect, go to https://connect.topcoder.com/projects/4762 and see the wrong number of counts. Once clicking on "load older comments" the counter is reset to 0

### Screenshot/screencast
<img width="738" alt="screen shot 2018-01-03 at 12 26 59 pm" src="https://user-images.githubusercontent.com/8484061/34538583-c7ac4e0a-f081-11e7-8d04-488558edc56b.png">
<img width="756" alt="screen shot 2018-01-03 at 12 27 08 pm" src="https://user-images.githubusercontent.com/8484061/34538585-c8f6c98e-f081-11e7-96e0-bbc073ecb917.png">

**Comment by gondzo** [comment]
@vikasrohit can you take this one as it will probably require some investigation with prod environment?

**Comment by vikasrohit** [comment]
@vic-topcoder @mtwomey Fixed and patched the production.
