### ISSUE TITLE
[$40] Managers counter not correct on project list / Production

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1580]
### Expected behavior
When there are 3 managers the list should show 3 avatars. If there are 4+ managers, we should see the additional number after the (3) avatars of the first managers.

### Actual behavior
The third avatar is displayed as "+1"
<img width="1174" alt="screen shot 2018-01-03 at 12 33 39 pm" src="https://user-images.githubusercontent.com/8484061/34538722-5c46ef70-f082-11e7-9dc3-0e9a2d3d5db5.png">
<img width="186" alt="screen shot 2018-01-03 at 12 31 22 pm" src="https://user-images.githubusercontent.com/8484061/34538693-3a3f1cd6-f082-11e7-955c-52487f1d75d1.png">

**Comment by tpwwu** [comment]
Sorry I have not got permission on this repo so I could not change tags.
But I have created a fix https://github.com/appirio-tech/connect-app/pull/1581

**Comment by tpwwu** [comment]
@gondzo do you mind helping me update tag, many thanks
