### ISSUE TITLE
[$40] Project status dropdown in Cards view is not working

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1592]
Project status dropdown in the cards view is not wired to the correct actions and clicking any option throws an error. It should behave the same as the dropdown in the grid view - change status without changing route to project details

**Comment by anonymousjaggu** [comment]
@gondzo can you please share the navigation screen with url, it would help me to check the exact place.

**Comment by gondzo** [comment]
go to project listing https://connect.topcoder.com/projects?sort=updatedAt%20desc&status=active as a manager or admin, switch to card view and try to change project status - the dropdown is unresponsive. orbaby just need to set onclick handler or something like that. it's working properly in the grid view
![image](https://user-images.githubusercontent.com/3051646/34979026-6abbec90-faa0-11e7-8ec7-7605778677bd.png)

**Comment by gondzo** [comment]
fixed in dev.
