### ISSUE TITLE
[$40] User avatar with rating

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1593]
With changes to #1533 we use a single avatar component everywhere except for the user tooltip in files list.  we have another avatar component that (UserAvatar) that is identical, except that it takes user rating into consideration (and it's used in files list only). IMO we don't care about user ratings and it would be ok to just remove this redundant component and use a single avatar component everywhere. @vikasrohit @vic-topcoder ?

**Comment by vikasrohit** [comment]
I am okay (in fact would encourage to do that) with getting rid of UserAvatar component. If needed we can support the user ratings in the consolidated Avatar component to be ensured. I can not remember the uses of the avatar component with ratings in connect, may be @vic-topcoder remembers this one.

**Comment by vic-topcoder** [comment]
I think it might have to do with search, but I'm not sure. I'd rather have only 1 avatar component that can be reused for multitude of cases, including the search. Topcoder is using different version of our components anyway. @vikasrohit - please chime in on this one.
