### ISSUE TITLE
IBM Chatbot project creation form updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1595]
@vikasrohit - Pat requires minor changes to the IBM chatbot form. He wants to add 2 fields:

After "Do you have an existing IBM Cloud (formerly IBM Bluemix) account?

1. Does your organization currently have a chatbot? [ Yes, No ] (required)

2. If yes, can you provide some brief specifics about your current chatbot? [text input] (optional)

![screen shot 2018-01-09 at 12 26 15 pm](https://user-images.githubusercontent.com/8484061/34741693-5405dd98-f538-11e7-80e4-69231e6faf6f.png)

The fields should be added for new IBM chatbot projects, no need to update existing projects.

Let's get it released after we implement it, not waiting for a another release.
Thanks!

**Comment by RishiRajSahu** [comment]
@vikasrohit - Made the changes please review https://github.com/appirio-tech/connect-app/pull/1601

**Comment by RishiRajSahu** [comment]
Done and tested. Deployed on prod.

**Comment by vic-topcoder** [comment]
Great!
