### ISSUE TITLE
[$60] Search box performance issue

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1603]
Typing in the project search box causes too many renders and the performance is bad. There are a lot of PROJECT_SUGGESTIONS_SEARCH_SUCCESS actions, but those are useless as there is no autocomplete support in the projects search box.

http://take.ms/iN4sf
reported by @ThomasKranitsas

**Comment by chongluo** [comment]
I would like to assign this issue to myself, however the forum is not working so that I could not find the place to post my handle. Can you you please grant me access to the repo?

**Comment by gondzo** [comment]
added. you can assign it to yourself now

**Comment by chongluo** [comment]
Thanks!

**Comment by chongluo** [comment]
I could not see the search bar on UI. How can I access to the page shown in the video?
