### ISSUE TITLE
Allow managers/admins to assign Manager role to people added to a project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1604]
This is a shortcut to get the desired effect of adding a manager to a project. Right now we can't list all the managers in the system (#1370), so let's just try to work backwards - assign a user to a manager role per project. This is internal need and should not be visible to anybody that is not a manager.

Once the system verifies that the user can be a Manager, we'll show success message. Otherwise show warning "This user can't be added as a Manager to the project".

Implementation: Ask a field for member role "Manager" in the user management interface:
![screen shot](https://user-images.githubusercontent.com/8484061/34964203-4039769e-fa01-11e7-8587-87e809c6bba9.png)

**Comment by vikasrohit** [comment]
@RishiRajSahu Can you please take care of the front end stuff? I would take care of back end.

**Comment by RishiRajSahu** [comment]
Sure. I'll do it.

**Comment by vikasrohit** [comment]
@RishiRajSahu Backend changes are done. Now if you try to add a user, who does not have any of the privileged roles (manager or admins), as manager, API will throw 400 error with appropriate error message. Let me know if you face any issue with it. Changes are deployed into dev.

**Comment by RishiRajSahu** [comment]
@vikasrohit Have made changes for UI side. Tested on local machine and below are the test observations - 
1.member - Could only add a member
2.copilot - Add Copilot & Member tab
3.Manager - Add Copilot, Member, Manager tab
4.Manager trying to add non-manager role member - Valid error message is shown

Please review at https://github.com/appirio-tech/connect-app/pull/1617

**Comment by vic-topcoder** [comment]
@gondzo - can merge in DEV please?
