### ISSUE TITLE
[$400] Missing notifications for email responses

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1605]
If a user responds to a post via email, no notification is triggered. Emails are handled by discourse, so I'm not sure how we can process this kind of events.

**Comment by vic-topcoder** [comment]
We can't right now, we have to use our own email system. This is a known issue for quite some time. That's the reason next on the list is to replace the email system to be handled not by Discourse.

**Comment by gondzo** [comment]
I found a possible workaround - discourse has web hooks that can notify a listener for any events. Probably not worth the effort at this point?

**Comment by vic-topcoder** [comment]
It might be 2 months before we can get this working. How much of an effort would be to have the web hooks from discourse? If it is relatively easy, probably worth doing it (get it in CF7)

**Comment by gondzo** [comment]
It won't be too hard, we just need to add a simple endpoint to the messaging service.  We can handle it in CF7.

**Comment by vic-topcoder** [comment]
Let's do it!

**Comment by passimm** [comment]
hi gondzo, could you share git repo path of Discourse service, as well as the branch where we should submit PR?

**Comment by gondzo** [comment]
@passimm it's this one https://github.com/topcoder-platform/tc-message-service
when you deploy it locally, you can access the discourse admin portal so you can configure the necessary webhooks

**Comment by lifeNrun** [comment]
Can you provide user information for login verification in  https://accounts.topcoder-dev.com/connect?

**Comment by gondzo** [comment]
sure.
pshah_manager/topcoder123
pshah_copilot/topcoder123

**Comment by kevinkid** [comment]
If someone likes a topic post should we consider that a response?

**Comment by vic-topcoder** [comment]
no. We're planning to disconnect from Discourse at some point, so that's not feature we'll cary over.

**Comment by kevinkid** [comment]
Is there need to add an endpoint to the tc-messaging service @gondzo? Am initializing the webhook on server startup and shifting that responsibility to the topcoder-platform/tc-bus-api.

**Comment by kevinkid** [comment]
Noted vic-topcoder, its ready for review.

**Comment by gondzo** [comment]
I think we can close this since it will be solved with migration from discourse. Agreed @vic-topcoder ?

**Comment by vikasrohit** [comment]
Agreed with @gondzo

**Comment by gondzo** [comment]
ok, closing this one.
