### ISSUE TITLE
Project navigation showing Discussion tab at all times, shouldn't 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1609]
### Expected behavior
I should see Discussion tab only when there was a discussion created before. All new projects shouldn't have this tab. The goal is to eliminate that section permanently

### Actual behavior
I can see discussions tab at all times, in all projects.

**Comment by gondzo** [comment]
this is not broken, you're just loading old projects (project listing returns only old projects, I might have broken that today)

**Comment by gondzo** [comment]
works properly
