### ISSUE TITLE
Canceling a project is impossible when the project is at the bottom of the viewport

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1612]
### Expected behavior
When canceling a project, I should see the full menu wherever the project is in the grid/viewport edges.

### Actual behavior
When trying to cancel a project at the bottom of the grid, the interface is partially obscured and can't be used.

### Steps to reproduce the problem
-  Try to cancel a project at the bottom of the viewport

![screen shot 2018-01-18 at 5 46 47 pm](https://user-images.githubusercontent.com/8484061/35130866-e51343d4-fc77-11e7-96e7-25a66ad5fd85.png)

**Comment by gondzo** [comment]
fixed

**Comment by vic-topcoder** [comment]
I still see this in my local environment btw.

**Comment by gondzo** [comment]
fixed
