### ISSUE TITLE
Eliminate use of Icons from "appirio-tech-react-components"

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1621]
With the unified .SVG use we still have several uses of the outdated `appirio-tech-react-components`.

Search the source for
``` jsx
import { Icons } from 'appirio-tech-react-components'

``` 
and you'll identify all the places we need to be modified.

Please copy all missing .svg files into the Connect app and remove the use of the component. This would complete the use of  non-standard .SVG imports.

**Comment by gondzo** [comment]
we're still using a lot of components from that repository. do you mean to just stop using icons from there?

**Comment by vic-topcoder** [comment]
Yes, just the icons, as we replaced them with the .SVG import plugin

**Comment by gondzo** [comment]
fixed in dev
