### ISSUE TITLE
File sharing token expires after 10-15 min. if the page is not reloaded

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1625]
### Expected behavior
The files sharing links should always be accessible within the project

### Actual behavior
Customers/people have to reload the page to be able to download attached files within the project specification page

Can we find a way to fix the links not working after a set time?

@mtwomey @gondzo @vikasrohit FYI

**Comment by gondzo** [comment]
Duplicate. It is tracked under #1607 which should be closed by the end of week

**Comment by vic-topcoder** [comment]
Cool!
