### ISSUE TITLE
[50$] Project status icons are misaligned after the SVG refactor

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1627]
### Expected behavior
The SVG icons should be center-aligned to the text.

### Actual behavior
Icons are not aligned

### Expected:
![screen shot 2018-01-24 at 11 45 21 am](https://user-images.githubusercontent.com/8484061/35353470-2479f878-00fc-11e8-83ee-9d19475cb071.png)

### Current:

Text center is in Red, icon center is in purple. They should align.
![screen shot 2018-01-24 at 11 48 19 am](https://user-images.githubusercontent.com/8484061/35353603-8344a312-00fc-11e8-9f67-58233a9ccad0.png)

**Comment by vic-topcoder** [comment]
We should also look into updating the menu to match the design. The "Cancel project..." and "Pause project..." invoke modal so that's why they're separated from the rest of field. I'll have Yoki work on a better modal design for the interaction as canceling a project is very slow at the moment.

**Comment by gondzo** [comment]
@kevinkid this is not fixed. also, there is no PR for this change?

**Comment by vic-topcoder** [comment]
I actually fixed this in release - updated the SVG icons and the appropriate CSS for the components
![screen shot 2018-02-05 at 3 07 22 pm](https://user-images.githubusercontent.com/8484061/35833500-6809db10-0a86-11e8-8ef6-c1f3a6047404.png)
