### ISSUE TITLE
Landing page: wire buttons

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#164]
"Register for free": https://accounts.topcoder-dev.com/connect/registration
"Learn more about crowdsourcing": https://www.topcoder.com/what-can-you-do/

**Comment by vikasrohit** [comment]
@mahestro @fnisen Taking this one as #165 is related to this and we might incur conflicts if two different people work on this.

**Comment by vikasrohit** [comment]
Changes are ready. Waiting for the Bug hunt to conclude before merging the changes in dev.

**Comment by vikasrohit** [comment]
Changes are in dev.
