### ISSUE TITLE
Navigation: modify logged out nav to remove "Register" button

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#165]
When a user logs out from Connect, they should be taken to the logged out home page/landing page (connectv2.topcoder-dev.com). The nav on this page should only have the Login button, as shown here: http://take.ms/Pr1y2. (The Register button is available on the page itself, so it's not needed in the Nav).

cc @mahestro

**Comment by fnisen** [comment]
I've assigned the issue of updating links to Luis, but feel free to claim it @vikasrohit: https://github.com/appirio-tech/connect-app/issues/164

**Comment by vikasrohit** [comment]
Changes are ready. Waiting for the Bug hunt to conclude before merging the changes in dev.

**Comment by vikasrohit** [comment]
Changes are in dev.
