### ISSUE TITLE
Back to project navigation doesn't reload the project with grid [bug]

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1655]
### Expected behavior
When clicking the "View all projects" link on top left within a project, the page should load the project list/grid view.

### Actual behavior
The page fails to load although the navigation changes.

### Steps to reproduce the problem
- Open a project
- Click on comment filed
- Click on "View all porjects" link

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/8484061/35586226-227bf65e-05af-11e8-98d7-e8bb35be5671.png)

**Comment by gondzo** [comment]
fixed in dev @vic-topcoder
