### ISSUE TITLE
Setup issue - data['justExtract'] should NOT have additional properties

### ISSUE THREAD

**Issue by arun1595** [appirio-tech/connect-app#1660]
I cloned the repo, ran `npm install` and `npm start` to find the above error.

I am running node v5.12.0 and npm 3.8.6

The error is thrown at the following config present in `config/webpack/default.js`

```
new ExtractCssChunks({
  filename: '[name].css',
  justExtract: true
})
```
I tried googling the error and looks like an issue with `ExtractTextPlugin` but couldn't figure out the solution.

Any help would be appreciated.

Thanks!

**Comment by vikasrohit** [comment]
Can you please try upgrading your node and npm versions?

**Comment by arun1595** [comment]
@vikasrohit Thanks for the response. Doesn't the app use Node v5?

I tried to run the app on node v 8.9.1 and npm 5.6.0 but I am still getting the same error. 

What could I be possibly missing?

**Comment by birdofpreyru** [comment]
@arun1595 that `justExtract: true` option just should not be there anymore, it comes from an outdated code. Where have you encounter it?

**Comment by arun1595** [comment]
@birdofpreyru My bad :see_no_evil: 

You're right, I had forgotten to pull the latest version of the codebase.

Closing this issue as it was a fault on my side.

Thanks @birdofpreyru

**Comment by vikasrohit** [comment]
Thanks @birdofpreyru for jumping in and the help.
