### ISSUE TITLE
Status update cards should have owners

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1662]
Replace the anonymous "Coder the Bot" with the actual user that changed the status.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-132

**Comment by gondzo** [comment]
@vic-topcoder is this about the notification text or the topic on the dashboard feed?

**Comment by vic-topcoder** [comment]
That's the name of the system bot - system profile - should be "Coder the Bot" instead "coder bot" - everywhere where the system is represented by the robot, This includes alerts, notifications, posts, emails, etc.

**Comment by gondzo** [comment]
@vikasrohit can you take this one, I'm not sure where should this be fixed.

**Comment by vikasrohit** [comment]
@RishiRajSahu Would you be able to handle it?

**Comment by RishiRajSahu** [comment]
sure. @vic-topcoder if this issue is about showing owners on status update cards OR changing 'coder bot' to 'Coder the Bot' , I think the later changes are already done.

**Comment by vic-topcoder** [comment]
This one is to display who canceled the project, when canceled.

**Comment by vikasrohit** [comment]
@vic-topcoder I think we would be generically showing all coder bot message actions with owner details e.g. project status changed to 'in_review' or 'completed' or any other valid status.

**Comment by vic-topcoder** [comment]
The request that I captured was about canceling project status or other important changes. Seems like team members don't quite understand what is the cause/reason for cancelling a project when it is done by a customer, or why a project is paused, and they were looking for a way to display that data cleaner in the project feed.
