### ISSUE TITLE
Loading many topics blocks connect from displaying data

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1681]
When there are a lot of discussion threads on a project we render the view after we retrieve all the data. This effectively breaks the user experience. We need to come up with an optimization to improve the user experience.

Couple of ideas: 
- Pull the first 5 topics to render, then lazy-load the rest.
- Check if there are ways to optimize the API response - polling the DB and constructing the response takes whooping 10 seconds.

![screen shot 2018-02-05 at 6 37 57 pm](https://user-images.githubusercontent.com/8484061/35839323-a7549b84-0aa4-11e8-9885-682cd91f53c3.png)

**Comment by vikasrohit** [comment]
I don't think we can do much here without replacing the discourse. I am working on replacing the discourse, however, that is not a trivial job. It needs very careful replacement. I have almost finished the new schema to store required information from existing discourse database. My next step would be to design a ETL job, to get the data from discourse to our new schema.

On the other hand, @vic-topcoder, we are thinking of [increasing page size to 50 for loading the projects on listing page ](https://github.com/appirio-tech/connect-app/issues/1575), which might present us similar issues in future. So, we should be careful with such changes.

**Comment by gondzo** [comment]
this is now fixed. we're still loading all data, but it's just one single api call to discourse - super fast.
