### ISSUE TITLE
Show a progress indicator while loading topics on the project dashboard page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1682]
### Expected behavior
While I'm waiting for the system to display the topics, the progress indicator (spinning wheel) should show up in the center of the page.

### Actual behavior
The dashboard shows blank

**Comment by gondzo** [comment]
It's still there, but the gif image gets corrupted during build, not sure why
https://connect.topcoder.com/37d723924c4eb62e5b141fec944d9302.gif

**Comment by vic-topcoder** [comment]
Try with this one
![37d723924c4eb62e5b141fec944d9302](https://user-images.githubusercontent.com/8484061/35891753-b22e570a-0b5a-11e8-8dbc-48b326682232.gif)

**Comment by vic-topcoder** [comment]
I'm not sure why it might get corrupted as well.

**Comment by gondzo** [comment]
fixed in bugBash07 and deployed to dev

**Comment by vic-topcoder** [comment]
Can we get this as a hotfix into production?
