### ISSUE TITLE
[$60] Don't hide "Old" notifications when there are no notifications displayed in the notifications drop-down

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1683]
### Expected behavior
I want to see all notifications I haven't dismissed in the notifications drop-down.

If there are older notifications that are not displayed, when I dismiss my notifications I want to see them into the drop down instead.

The dropdown menu should never be empty when there are notifications that are not dismissed.

### Actual behavior
The dropdown menu shows nothing, but there is a link for "Older" notification.

![screen shot 2018-02-01 at 7 29 54 am](https://user-images.githubusercontent.com/8484061/35888889-43b233ca-0b4e-11e8-9bf6-4d478bd7509f.png)

At the notification center I can't see any of the notifications - all are hidden.
![screen shot 2018-02-01 at 7 24 29 am](https://user-images.githubusercontent.com/8484061/35888912-530429dc-0b4e-11e8-97ab-537fe2d57ea0.png)

**Comment by vic-topcoder** [comment]
The goal is to keep showing the latest unread notifications until all are dismissed; i.e. keep populating the list with notifications. At some point the "older" notifications would disappear, and I'll still see notification messages.

**Comment by zjuasmn** [comment]
What is the expected behavior of clicking 'view XXX older notifications'?

**Comment by zjuasmn** [comment]
Currently `old` means notification created 2 days ago and there is an array state maintaining old notifications. Should we remove it ?

**Comment by vic-topcoder** [comment]
Yes. We don't care about the age of the notification to determine if it is "old" or "new". All notifications that have been seen are deemed "old", and they should follow the rules or the system above: the project group should show the 10 most resent notifications (regardless of age) and hide the 11+ notification(s). Making a notification as read from the 10 top (visible) should load the next notification from the hidden section.

New notifications are ones that haven't been seen by the customer and should be designated with the red dot on the bell, and a left blue border on the notifications page (we don't support that yet I think, might be wrong).

Thanks!

**Comment by gondzo** [comment]
fixed
