### ISSUE TITLE
IBM Chatbot content updates [HOTFIX]

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1684]
@vikasrohit please update the disclaimer text at the bottom of the Watson Chatbot to say "IBM is receiving compensation from Topcoder for referring customers to Topcoder." and deploy to production? It is important to have it Monday Morning please.
![screenshot](https://user-images.githubusercontent.com/8484061/36067786-9e5a3326-0e79-11e8-9d75-55b3de28dd02.png)

**Comment by RishiRajSahu** [comment]
@vic-topcoder I have fixed this in a hotfix branch created from master and created a pull request here - https://github.com/appirio-tech/connect-app/pull/1686 . Please review and merge to master as I am not able to merge it.

**Comment by RishiRajSahu** [comment]
verified on prod.

**Comment by vic-topcoder** [comment]
Looks good. Thanks @RishiRajSahu
