### ISSUE TITLE
User is not listed in notification

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1693]
### Expected behavior
I should know who did what on notifications I receive
![screen shot 2018-02-15 at 10 27 02 am](https://user-images.githubusercontent.com/8484061/36273886-d145879e-123a-11e8-915f-3ef9eb4262c6.png)

### Actual behavior
In most notifications the user doing the action is missing.
![screen shot 2018-02-14 at 4 08 51 pm](https://user-images.githubusercontent.com/8484061/36273909-e35bc344-123a-11e8-96f2-0c8f7d69f544.png)

**Comment by gondzo** [comment]
this is fixed already, try generating some new ones

**Comment by vic-topcoder** [comment]
Yes, works fine, verified. Closing this one
