### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1696]
There are a lot of problems with IE11. It is one of our target browsers so we must fix it.

- [x] Dev server isn't showing under IE11

- [x] Navigation is off in all states,

- [x] bell icon,

- [x] project navigation
- [ ] notifications, notification settings

- [ ] Order of project filter tabs is wrong

- [ ] Tooltip position is wrong

- [ ] Project creation side panel - text is covering the title/icon

- [ ] Project dashboard - missing elements
- [ ] Project description
- [ ] Project status

- [ ] Project email settings is not visible

- [x] Cards are displayed inline instead of a grid

- [x] User avatars are running outside of card bounds

![img_3412](https://user-images.githubusercontent.com/8484061/36276959-4f2c0e72-1244-11e8-80f5-1860f6c8107b.jpg)
![img_3414](https://user-images.githubusercontent.com/8484061/36276960-4f407952-1244-11e8-9f2c-aa858bb73e28.jpg)
![img_3416](https://user-images.githubusercontent.com/8484061/36276961-4f57b414-1244-11e8-8c62-115925b05a08.jpg)
![img_3418](https://user-images.githubusercontent.com/8484061/36276962-4f6bcd14-1244-11e8-9731-2fd405b966b5.jpg)
![img_3419](https://user-images.githubusercontent.com/8484061/36276963-4f806594-1244-11e8-9f9c-abc02917067c.jpg)
![img_3420](https://user-images.githubusercontent.com/8484061/36276964-4f93f3e8-1244-11e8-9efc-63d0733008a9.jpg)
![img_3421](https://user-images.githubusercontent.com/8484061/36276965-4fa625fe-1244-11e8-91e2-513295778a1f.jpg)

**Comment by kapilgorve** [comment]
@vic-topcoder can you assemble screenshots with issues ? I will be able to quickly identify issues.

**Comment by vic-topcoder** [comment]
done

**Comment by veshu** [comment]
@vic-topcoder What are the issue marked with ticked checkbox meaning?

**Comment by kapilgorve** [comment]
I have been able to resolve the issues which have been ticked.

**Comment by veshu** [comment]
means these ticked issues need not to be fixed?

**Comment by gondzo** [comment]
@veshu - it's a F2F, all issues are in scope

**Comment by gondzo** [comment]
fixes are merged to dev. closing
