### ISSUE TITLE
Browser's logging not showing file name.

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#1697]
After adding topcoder-react-utils as dependency for webpack config its seems the browser logging for dev env is not showing file name instead it is showing minified js file name.

### Expected behavior
Enabling proper logging(with file name) in browser's console for smoother development process

#### Environment
dev

**Comment by gondzo** [comment]
I've noticed this as well and looking into the possible fixes

**Comment by RishiRajSahu** [comment]
cool !

**Comment by maxceem** [comment]
Fixed by #1699

**Comment by gondzo** [comment]
closing
