### ISSUE TITLE
Messaging: "No comments yet" shown even when comments have been added

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#170]
![screen shot 2016-09-27 at 5 31 52 pm](https://cloud.githubusercontent.com/assets/12552247/18896678/6942e718-84d8-11e6-8109-66d4a2de07ee.png)

To reproduce: log in as patrick_monahan. Go to project "Wed 2:11pm project" and view Dashboard.

**Comment by fnisen** [comment]
![screen shot 2016-09-28 at 6 54 27 pm](https://cloud.githubusercontent.com/assets/12552247/18938371/08389cee-85ad-11e6-837d-aacca7cd495f.png)

Still seeing this bug in Dev.

**Comment by vikasrohit** [comment]
Right now I am not counting the original post with the feed/thread. Do you like to count original post in the feed/thread as comment?

**Comment by fnisen** [comment]
You're right, sorry, that was a dumb example. I am seeing it though after there has been been one comment, not counting the original post: 

<img width="771" alt="screen shot 2016-09-29 at 10 39 37 am" src="https://cloud.githubusercontent.com/assets/12552247/18965236/3074cf8c-8631-11e6-81b7-77684584946b.png">
<img width="1194" alt="screen shot 2016-09-29 at 10 39 24 am" src="https://cloud.githubusercontent.com/assets/12552247/18965243/329a869e-8631-11e6-82ce-60c937121ac1.png">

**Comment by vikasrohit** [comment]
Okay. Got it. It seems build is not latest on the dev. May be travis build was disabled for bug hunt.

**Comment by vikasrohit** [comment]
Changes are now in dev and I have tested both issues:

1. No comments yet, message when there is a comment (project id 303)
2. Comments count is greater than the actual comments (project id 303)
