### ISSUE TITLE
[$40] avatar component doesn't display correct user

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1702]
The avatar on the top bar should show my picture and be consistent throughout the system.

At the moment the top bar and the post composer card show different image/avatar than the one on the side bar

![screen shot 2018-02-21 at 6 28 16 pm](https://user-images.githubusercontent.com/8484061/36516967-35132ee4-1735-11e8-84ee-da5dd54421e1.png)

**Comment by gondzo** [comment]
@vic-topcoder this is an issue with the members API and I think it's happening in dev only. it's returning null for photo url
![image](https://user-images.githubusercontent.com/3051646/36601993-0f87f1ea-18b7-11e8-8707-27d33f768fdc.png)

**Comment by vic-topcoder** [comment]
It is odd as sometimes the picture is loaded, and sometimes it isn't. Look at the left hand side where the avatar is loaded (red box and arrow). @mtwomey FYI

**Comment by gondzo** [comment]
It's an api issue for sure. These two requests return different results
http://api.topcoder-dev.com/v3/members/_search?query=handle:pat_monahan&fields=userId,handle,photoURL,firstName,lastName,details,email
and
http://api.topcoder-dev.com/v3/members/pat_monahan

**Comment by gondzo** [comment]
first request fetches data from elasticsearch, and the second one from dynamoDB. any ideas how are those two synced @mtwomey @vikasrohit

**Comment by vikasrohit** [comment]
IMO, we should fetch [member profile](http://api.topcoder-dev.com/v3/members/pat_monahan) from elastic search as well, that way both would be in sync. And if we get any issue with data between elastic search and dynamo db, we would have clear path(sync data from dynamo to elastic search) of fixing the issue.

**Comment by gondzo** [comment]
Removing this item from CF08 - we'll need to run a separate challenge for this one

**Comment by gondzo** [comment]
this should be fixed in member service https://github.com/appirio-tech/ap-member-microservice/issues/150

**Comment by vikasrohit** [comment]
@vic-topcoder @gondzo moving it to back log instead of keeping it in every release.

**Comment by vikasrohit** [comment]
Closing as it has been fixed in https://github.com/appirio-tech/ap-member-microservice/issues/150 by fetching data for both endpoints via ES.
