### ISSUE TITLE
[$50] jumping sidebar when scrolling when description text has very long words

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1703]
### Update:

The issues is caused by long string in project description https://connect.topcoder-dev.com/projects/2788. This is not a real world text sample so it is an edge case. We need to extend the CSS coverage of the sidebar to deal with very long words as this is what causes sidebar to come out of alignment and jump around when scrolling.
_____

After the IE11 fixes the sidebar is jumping during scroll, and that's very apparent at narrow window size.
![screen shot 2018-02-21 at 6 33 32 pm](https://user-images.githubusercontent.com/8484061/36517121-e8f53d44-1735-11e8-91e6-40164739265e.png)
![screen shot 2018-02-21 at 6 33 41 pm](https://user-images.githubusercontent.com/8484061/36517123-e90b68b2-1735-11e8-8b11-513d1ff9acc0.png)

**Comment by gondzo** [comment]
@vic-topcoder I don't think this is introduced by ie11 changes. sidebar styling is really bad on small resolutions, even in prod. for example 
![image](https://user-images.githubusercontent.com/3051646/36602491-751303d2-18b8-11e8-9aee-21f8c98d7c9f.png)
It's not an easy fix, but IMO we should introduce min width for the body and that would solve a lot of issues with the site on mobile (can't read/write posts on mobile)

**Comment by vic-topcoder** [comment]
I figure out that the cause is the super long string in the particular project that is causing the jump in smaller sizes. Compare this
![screen shot 2018-02-23 at 11 13 40 am](https://user-images.githubusercontent.com/8484061/36612422-6df2579c-188b-11e8-9b48-9ddb432637be.png)

to the project in question (https://connect.topcoder-dev.com/projects/2788)
![screen shot 2018-02-23 at 11 20 04 am](https://user-images.githubusercontent.com/8484061/36612466-879e9958-188b-11e8-83dc-5d64542a141a.png)

We need to verify with real content and fix the plugin that resizes the text to fit within the sidebar to not cause such resizes. Other than that I think it won't happen with actual text.

Lowering the priority, but still a good thing to check for next CF

**Comment by iversonLv** [comment]
@gondzo can I try this ticket?
I found you are assigned the ticket.
I think you are the PM/COPILOT for the project, the assginee could be assigned my self?

Thanks.
