### ISSUE TITLE
[$30] Tooltip inside project dashboard is cropped by the sidebar

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1708]
### Expected behavior
The tooltip should be above all elements and not be clipped by the parent container (position: absolute; z-index: 100) 

@gondzo - what was the z-index order table? Let's put that as a reference on the Wiki please.

### Actual behavior
Hover over the avatar on dashboard to observe.
![screen shot 2018-02-26 at 6 25 04 pm](https://user-images.githubusercontent.com/8484061/36707333-b3789e7c-1b22-11e8-9f46-ca226d402677.png)

**Comment by gondzo** [comment]
Thanks for adding the info to the wiki @vic-topcoder 
https://github.com/appirio-tech/connect-app/wiki/Community-Work-Read-Me-First!
