### ISSUE TITLE
[$40] Window-Manager – Need to click “Cancel” button Two times to close the “You are currently uploading. If you choose "OK"” prompt

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1718]
_From @youdare on February 18, 2018 16:19_

Summary:
Window-Manager – Need to click “Cancel” button Two times to close the “You are currently uploading. If you choose "OK"” prompt

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123
3.Create the project.
4.Go To Project specification
5.Click File and upload multiple file
6.Close the Upload prompt
7. App will display message as “You are currently uploading. If you choose "OK"” or Cancel button 
8.Click Cancel button

### Expected Result ###
Window-Manager – Need to click “Cancel” button only one  times to close the “You are currently uploading. If you choose "OK"” prompt
### Actual  Result ###
Window-Manager – Need to click “Cancel” button Two times to close the “You are currently uploading. If you choose "OK"” prompt

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#247_

**Comment by zjuasmn** [comment]
issue related to <https://github.com/filepicker/filepicker-js/issues/36>
