### ISSUE TITLE
Navigation flickers on scroll within project pages

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#172]
### Expected behavior
The top navigation should never flicker or change position while the user scrolls

### Actual behavior
Currently the navigation flickers when the user starts scrolling on the pages with 2 columns and sticky panel - dashboard, settings, messages. Recording is here 

### Steps to reproduce the problem
- Open a project
- Start scrolling slowly with the mouse wheel

### Screenshot/screencast
https://monosnap.com/file/sDIssk4NNMhYeUnYh7y7T3QgT5rY0G

--

#### Environment
- OS: Mac OS
- Browser (w/version): Safari 10, Chrome 53, probably Firefox (can't login!)
- User role (client, copilot or manager): manager
- Account used: pat_monahan

**Comment by vikasrohit** [comment]
@vic-appirio I have committed the changes and made a PR, please review it.

**Comment by vic-appirio** [comment]
resolved
