### ISSUE TITLE
[$40] Notification count >= 11 also showed in Notification center

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1720]
_From @bikakk on February 18, 2018 15:41_

### Reported URL ###
https://connect.topcoder-dev.com/notifications

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Now generate notification for one project in such a way that it should trigger more than 11 notifications
4. Now goto notification center b clicking on view all notifications
5. observe all the 12 notifications are shown

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
•	Notification center is accessible and shows the correct number ≤ 10 per project, all notifications ≥ 11 are hidden

### Actual  Result ###
Notification >=11 for a project are not hidden and it is showing all the notifications for the same project.

### Screenshots ###

[Notification center.docx](https://github.com/topcoderinc/connect-test-cycle-1/files/1734838/Notification.center.docx)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

_Copied from original issue: topcoderinc/connect-test-cycle-1#244_

**Comment by zjuasmn** [comment]
Notification >= 6 in dropdown should also be hidden.

**Comment by gondzo** [comment]
fixed
