### ISSUE TITLE
[$40] Red dot on the bell icon should be removed when there is no new notifications

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1721]
_From @bikakk on February 18, 2018 15:9_

### Reported URL ###
https://connect.topcoder-dev.com/projects/2608

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Trigger a notification for any of the project and observe the red dot on the bell icon for the indication of new notification triggered
4. Click on View all notification and make note of the count of all notifications
5. close the notifications 
6. Observe the Bell icon

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
If there is no new notification then white bell icon should display (Old notifications (white bell icon)

### Actual  Result ###

Red dot on the bell icon should be removed when there is no new notifications.
Here as per go to the notifications page and observed there are only 11 notifications displayed. Now close the notification window and observe still the red dot is not removed even there is no new notification triggered.

### Screenshots ###

[Red dot.docx](https://github.com/topcoderinc/connect-test-cycle-1/files/1734818/Red.dot.docx)

https://youtu.be/T-tw62ll7uc

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

_Copied from original issue: topcoderinc/connect-test-cycle-1#241_

**Comment by zjuasmn** [comment]
This issue is part of #1529
