### ISSUE TITLE
[$50] Not able to edit Project name and reference code once it is submitted for review

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1725]
_From @bikakk on February 18, 2018 13:39_

### Reported URL ###
https://connect.topcoder-dev.com/projects/2632/specification

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Create a new project and submit it for Review
4. Not goto specifications and try to edit the project name and reference code

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
Project name and reference code can be edited at all states

### Actual  Result ###
Not able to edit Project name and reference code once it is submitted for review

### Screenshots ###
[project name Edit.docx](https://github.com/topcoderinc/connect-test-cycle-1/files/1734761/project.name.Edit.docx)

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

_Copied from original issue: topcoderinc/connect-test-cycle-1#228_

**Comment by sumitdaga** [comment]
@gondzo @vic-topcoder 
i don't see the 'submit for review' button on the specification page

**Comment by vic-topcoder** [comment]
Try to open a project with a customer account. Only customers/team members can submit a project for review. Manager/Copilot user can't submit a project for review

**Comment by vikasrohit** [comment]
Just for reference, it was not an issue and rather a feature implemented via https://github.com/appirio-tech/connect-app/issues/671 and https://github.com/appirio-tech/connect-app/issues/654.
