### ISSUE TITLE
[$60] New page reload suggestion is not triggered for Response Edit

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1729]
_From @bikakk on February 18, 2018 12:23_

### Reported URL ###
https://connect.topcoder-dev.com/projects/2608

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com 
2. Login as pshah_customer
3. Open the project where post has been already created and response was posted
4. Now click on Edit comment against any post
5. Edit the comment and Save change
6. Make sure other team member page is already opened the with same project
7. Now goto other team member/manager page and observe the suggestion for "Reload page to view updates"

### Expected Result ###

As per doc: https://docs.google.com/document/d/1OBUhMGUtqU-Eqpufaom_eAKDbLiR8mq6syb-PSavXDI/edit
Should trigger new page reload suggestion for project members currently on the feed for Response Edit

### Actual  Result ###

Reload page to view updates suggestion is not triggered for response Edit. But if create a new comment then the suggestion is triggered.
Attache the detailed video.

### Screenshots ###

https://youtu.be/D_gvMRjjgm0

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 7 64 bit

Browser: Chrome 64.0

_Copied from original issue: topcoderinc/connect-test-cycle-1#219_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 23, 2018 2:1_

@vic-topcoder

**Comment by vic-topcoder** [comment]
Valid

**Comment by narekcat** [comment]
@vic-topcoder @gondzo 
Hi, I try to reproduce this issue, but can't, because notifications doesn't working.

**Comment by gondzo** [comment]
@narekcat notifications are now working properly

**Comment by narekcat** [comment]
@vic-topcoder @gondzo challenge of this bag bush is already in review phase, but some of issues, like this one, isn't fixed yet. Can I work on it ?

**Comment by gondzo** [comment]
yes, all the remaining issues will be open until Friday
