### ISSUE TITLE
[$60] Creating a new project from continuation does not redirect to Dashboard.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1731]
_From @macs054 on February 18, 2018 12:17_

### Reported URL ###
https://connect.topcoder-dev.com/new-project/app

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pshah_manager/topcoder123
Open new project window (Create new project app)
Select App
Type anything on the Project Name
Close the new project window
Open new project window
Click 'Continue where I left off'
Complete the required fields
Click Continue
Message will appear that project is created

### Expected Result ###

After the project is created the user must be redirected to the new project's dashboard.

### Actual  Result ###

The page stays put after the project is created which is not the usual behavior when creating a new one.

### Screencast ###

https://youtu.be/clhuUpg3tws

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2

_Copied from original issue: topcoderinc/connect-test-cycle-1#217_

**Comment by Huiqi** [comment]
I would like to work on it. But I can't assign it to myself. Any one can give me the permission please?

**Comment by Huiqi** [comment]
But I found this bug can not be reproduced. Maybe it has been fixed?

**Comment by Saoskia** [comment]
Definitely not fixed, I just reproduced it myself.

**Comment by narekcat** [comment]
I couldn't find solution, something mysterious.
