### ISSUE TITLE
[$80] Question field is checked under design specifications/devlopment specification even if no question is answered

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1733]
_From @gargsaurabh86 on February 18, 2018 8:50_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2603/specification/

### Reproduction Steps ###
1. Login to application pshah_customer/ topcoder123
2. Create a new project by clicking on + button OR directly go to project specification using above URL
3. Provide all valid details to create the project
4. Go to specification once the project is created

### Expected Result ###

Question fields should be unchecked for design specification and devlopment specification sections as the questions are not answered yet

### Actual  Result ###

*Enter the expected result here.*
Question fields are checked as highlighted in the attached screenshots

![screenshot-connect topcoder-dev com-2018 02 18-08-41-17](https://user-images.githubusercontent.com/29735376/36350062-a712a86c-1488-11e8-98f9-5cab6de513f5.png)

### Issue Information ###

Frequency: Always

Device: *device used for testing*

OS: *operating system used on test*

Browser: Chrome

_Copied from original issue: topcoderinc/connect-test-cycle-1#197_

**Comment by zjuasmn** [comment]
Those checks are valid by design since those sections is not required in specification.
What is the expected fix? Fix the question config? or just remove check mark for no-required section?
