### ISSUE TITLE
[$60] Window-Copilot – Not able to view notification from the Notification page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1736]
_From @youdare on February 18, 2018 7:26_

Summary:
Window-Copilot – Not able to view notification from the Notification page

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_copilot/topcoder123
3.Go to notification page
4.Access the notification

### Expected Result ###
Window-Copilot – Should able to view notification from the Notification page
### Actual  Result ###
Window-Copilot – Not able to view notification from the Notification page

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#188_

**Comment by vic-topcoder** [comment]
_From @youdare on February 18, 2018 7:28_

https://youtu.be/mdLrPvwBO0I

**Comment by vic-topcoder** [comment]
_From @sdgun on February 21, 2018 6:23_

There is no specific test data or a direct URL provided to reproduce this issue. Incomplete bug report. When I click on a notification it will open the project related to that.

This Notification may be related to a deleted project.

**Comment by vic-topcoder** [comment]
_From @youdare on February 21, 2018 14:56_

@sdgun  Just now tried same step mentioned in the defect able to reproduce the issue.
Please check video in comment

**Comment by zjuasmn** [comment]
Is it a valid issue?  The project related to the link is remove by somebody. Showing 404 is not a bug

**Comment by gondzo** [comment]
I think this is the case when you get a notification on a project but someone removes you from the project before you visit the notification. showing 404 is correct here IMO
@vic @zjuasmn
