### ISSUE TITLE
[$60] App is logging out then logging in again after closing new project window

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1737]
_From @macs054 on February 18, 2018 6:59_

### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc&status=active

### Reproduction Steps ###
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Click All Projects tab
Scroll down and click 'Load more projects'
Switch to Tile View
Scroll down and click the New Project tile
Close the new project window

### Expected Result ###

Should return to the previous page

### Actual  Result ###

App is logging out then logging in again

### Screencast ###

https://youtu.be/msNzTr6VcZQ

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome 64.0.3282.140, Edge 38.14393.0.0, Firefox 58.0.2t

_Copied from original issue: topcoderinc/connect-test-cycle-1#184_

**Comment by narekcat** [comment]
I find out bug associated this issue, but my solution fixes it too.
## Reproduction Steps
Go to https://connect.topcoder-dev.com/
Login as pat_monahan/topcoder123!
Click All Projects tab
Scroll down and click 'Load more projects'
Switch to Tile View
Scroll down to New Project button
Switch to List View
Scroll down and you can see that new project doesn't loading
See attachment
![topcoder_connect_doesnot_load_projects](https://user-images.githubusercontent.com/11549629/37209595-4189cc6e-23bf-11e8-88f1-33a9bc1aef82.png)
