### ISSUE TITLE
[$50] Window-Manger – When we select the same project status application should not show message to user as “Project updated”

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1738]
_From @youdare on February 18, 2018 6:19_

Summary:
Window-Manger – When we select the same project status application should not show message to user as “Project updated”
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_manager/topcoder123 and Verify the filter order
3.Go to any project and select the same status
Example: If project in draft select draft

### Expected Result ###
Window-Manger – When we select the same project status application is shows message to user as “Project updated”
### Actual  Result ###
Window-Manger – When we select the same project status application should not show message to user as “Project updated”

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#180_

**Comment by vic-topcoder** [comment]
_From @youdare on February 18, 2018 6:21_

https://youtu.be/6FRDMb8GzAc

**Comment by gondzo** [comment]
we're not showing any messages when updating project status. closing.
