### ISSUE TITLE
lose should be loose

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#174]
### Expected behavior
lose should be loose

### Actual behavior
Incorrect spelling

### Steps to reproduce the problem
Create a new project
Delete it
Observe the delete confirmation message.

### Screenshot/screencast
Attach or link a resource.

--
![image](https://cloud.githubusercontent.com/assets/5114190/18927372/3c72cb48-85d9-11e6-8ff3-42f13615ae0e.png)

#### Environment
- OS: Mac OS 10.11.5
- Browser (w/version):  Mac OS 10.11.5 Chrome 53
- User role (client, copilot or manager): Client
- Account used: christina_uw

**Comment by fnisen** [comment]
Spelling is correct: http://www.merriam-webster.com/dictionary/lose
