### ISSUE TITLE
validation needed for comments

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1746]
_From @winterflame on February 17, 2018 19:23_

### Reported URL ###
*https://connect.topcoder-dev.com/projects/2502*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pat_monahan/topcoder123!
2. create a new project (id is 2502)
3. then go to https://connect.topcoder-dev.com/projects/2502
4. enter "<script>alert(100);</script>" as comment title and body , post it, observe

### Expected Result ###

*should validate the input properly.*

### Actual Result ###

*See screenshot, body is empty.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#55_

**Comment by vic-topcoder** [comment]
_From @winterflame on February 17, 2018 19:24_

<img width="713" alt="me" src="https://user-images.githubusercontent.com/4590317/36344845-3b125ca2-145b-11e8-82cb-42609638f0ac.png">

**Comment by gondzo** [comment]
this is not a bug, backend will remove dangerous info from the comments
