### ISSUE TITLE
should validate project name 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1747]
_From @winterflame on February 17, 2018 19:5_

### Reported URL ###
*https://connect.topcoder-dev.com/projects/2502*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_customer/topcoder123
2. select App as the project type
3. create a new project with title "<script>hello</script>"
4. fill other fields properly, proceed, observe

### Expected Result ###

*should validate the input so that the project name can be shown.*

### Actual Result ###

*See screenshots, cannot see project name.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#42_

**Comment by vic-topcoder** [comment]
_From @winterflame on February 17, 2018 19:9_

<img width="1241" alt="ee1" src="https://user-images.githubusercontent.com/4590317/36344693-2a55493a-1459-11e8-8cf6-d40d16810071.png">


<img width="1107" alt="ee2" src="https://user-images.githubusercontent.com/4590317/36344694-2a8f5c24-1459-11e8-845b-287a28ab0d6b.png">

**Comment by gondzo** [comment]
not a bug IMO, there is no security issue here
