### ISSUE TITLE
swetaipec:   on picking device as Tablet showing the validation msg "Please select at least 1 device"

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#175]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to pick device
5. Select Tablet

Expected Result: should not displayed validation msg
Actual Result: showing Validation msg

Enviroment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18927481/ce5caf88-85d9-11e6-8935-793b411ffc01.png)

**Comment by parthshah** [comment]
@vikasrohit please work on this one too. It might be an IE only issue. I am not able to reproduce it on chrome

**Comment by vikasrohit** [comment]
@parthshah I have tried in the environment (Windows/Chrome) specified in issue description, but not able to reproduce. I also tried to check it for IE, however, after chrome test, I am not able to login in browserstack's browsers.

**Comment by fnisen** [comment]
Not able to reproduce either in both browsers. Might have been fixed along with something else. Closing.
