### ISSUE TITLE
[$30] error occurred while cancel project 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1750]
_From @winterflame on February 17, 2018 18:24_

### Reported URL ###
*https://connect.topcoder-dev.com/projects/2179/*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. go to https://connect.topcoder-dev.com/projects/2179/, first change it to completed status
3. then select "CANCELLED", click Cancel Project button, select an option, click "Cancel Project", observe

### Expected Result ###

*No error shown.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#21_

**Comment by vic-topcoder** [comment]
_From @winterflame on February 17, 2018 18:24_

<img width="1192" alt="e2" src="https://user-images.githubusercontent.com/4590317/36344286-d25895bc-1452-11e8-86b1-d2e05262cc83.png">

**Comment by gondzo** [comment]
user should not be able to change status to canceled from completed? @vic-topcoder

**Comment by vic-topcoder** [comment]
No completed project can be cancelled. Completed is the ultimate end state and can't be reopened. Cancelled might actually be bought back to live. I would like us to rethink the project flow in the future to clean up the system a bit. Cancelling a project currently asks way to many reasons and the UX isn't effective enough.

**Comment by Colinh84** [comment]
@gondzo What is the $ value of this issue?
