### ISSUE TITLE
get error after adding member to project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1753]
_From @winterflame on February 17, 2018 18:0_

### Reported URL ###
*https://connect.topcoder-dev.com/projects/2357*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. go to https://connect.topcoder-dev.com/projects/2357
3. on left side, click to add member
4. enter "test" then select test_1024 to add, observe

### Expected Result ###

*should add user "test1234" to project.*

### Actual Result ###

*See screenshot.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#8_

**Comment by vic-topcoder** [comment]
_From @winterflame on February 17, 2018 18:1_

<img width="1400" alt="e" src="https://user-images.githubusercontent.com/4590317/36344055-973a282c-144f-11e8-9f33-d627a3b10ef2.png">

**Comment by gondzo** [comment]
not a bug, the error was displayed correctly
