### ISSUE TITLE
[$50] Copyright year should be updated

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1756]
_From @kaygee1 on February 17, 2018 18:0_

Open Open https://connect.topcoder-dev.com/
Click on Login and see the copyright info

actual - it is © Topcoder 2017

expected - it should be © Topcoder 2018

![2](https://user-images.githubusercontent.com/5115050/36344050-788c5838-143a-11e8-8068-89477d06bb99.png)

_Copied from original issue: topcoderinc/connect-test-cycle-1#7_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 19, 2018 20:20_

Only functional and UI accepted

**Comment by vic-topcoder** [comment]
_From @kaygee1 on February 20, 2018 3:3_

@sdgun 
Yes, but see the Spec - The last bullet point on the spec - it very clearly asks the tester to test if 
Miscellaneous:
Footer links work
Copyright year is current

**Comment by vic-topcoder** [comment]
_From @sdgun on February 20, 2018 3:16_

Accepted

**Comment by gondzo** [comment]
https://github.com/appirio-tech/accounts-app/
