### ISSUE TITLE
The focus can be set

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#176]
### Expected behavior
The focus can not be set.

### Actual behavior
The focus can be set.

### Steps to reproduce the problem
- Access application link https://connectv2.topcoder-dev.com/projects.

- Login as pat_monahan / topcoder123!.

- Press click on the top right of page near My projects text.

### Screenshot/screencast
![focus](https://cloud.githubusercontent.com/assets/5114907/18927490/ea0a9494-85c4-11e6-9df8-6a9a970e1678.png)

#### Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
Mozilla Firefox 48.0.2
manager role
pat_monahan/ 

topcoder123!

**Comment by fnisen** [comment]
No hover state for "My projects": http://screencast.com/t/h5ukFowa

**Comment by vic-appirio** [comment]
Captured as an issue; closing. This is a duplicate
