### ISSUE TITLE
[$30] Dashboard icon is active on the discussions page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1761]
_From @arun1595 on February 17, 2018 20:33_

### Reported URL ###
https://connect.topcoder-dev.com/projects/800/discussions

### Reproduction Steps ###
1. Go to https://connect.topcoder-dev.com/
2. Click 'Login' button in the top right.
3. Login with the following credentials.
username - pshah_manager
password - topcoder123
4. Go to https://connect.topcoder-dev.com/projects/800/discussions

### Expected Result ###
The discussions icon should be **active**(with `#fda464` color)

### Actual  Result ###
The discussions icon is inactive(greyed out), the dashboard icon is active even though I am on the discussions tab

### Screenshots ###

![image](https://user-images.githubusercontent.com/7039523/36345351-a4ede156-13f6-11e8-8c92-46a88ac15568.png)

### Issue Information ###

Frequency: Always

Device: HP 

OS: Ubuntu 16.04 LTS

Browser: Google Chrome | 63.0.3239.132 (Official Build) (64-bit)

_Copied from original issue: topcoderinc/connect-test-cycle-1#78_

**Comment by iversonLv** [comment]
Seem it's created PR from @arun1595 first. My bad.
I close the PR and assign to @arun1595 

Thanks.

**Comment by iversonLv** [comment]
I have no permission to close the PR, @copilot and @PM, please ignore my PR.
