### ISSUE TITLE
[$60] Post feed->Create new post->User do not have option to cancel the post

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1766]
_From @gargsaurabh86 on February 18, 2018 0:55_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/1299

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_copilot/topcoder123
2. Select any project and navigate to its details page like https://connect.topcoder-dev.com/projects/1299
3. Start entering "Share the latest update with the team"

### Expected Result ###

As per specs: Post feed->Create new post-> Should be able to cancel post

### Actual  Result ###

Not able to cancel post. As there is no cancel button.

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347110-f974f016-1446-11e8-9f7b-4691ed03a192.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

_Copied from original issue: topcoderinc/connect-test-cycle-1#122_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 21, 2018 10:22_

Clicking on a empty space will hide the form

**Comment by vic-topcoder** [comment]
_From @gargsaurabh86 on February 22, 2018 11:58_

@sdgun if you follow steps 3 i.e. enter something in form then you won't be able to hide form when clicking on empty space.

Thanks.

**Comment by vic-topcoder** [comment]
_From @gargsaurabh86 on February 22, 2018 15:4_

@sdgun waiting for reply. Thank you.

**Comment by gondzo** [comment]
@iversonLv when you write something to the post and click cancel, the editor is discarded correctly, but when leaving the page we still get the unsaved message warning. can you please take a look?
![image](https://user-images.githubusercontent.com/3051646/37565371-822c0292-2aa8-11e8-9f8e-e9954979f2b2.png)
