### ISSUE TITLE
[$30] Window-Member – Project Name and Which is your primary device target? Is getting overlapped after submitting fore review.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1767]
_From @youdare on February 18, 2018 2:36_

Summary:
Window-Member – Project Name and Which is your primary device target? Is getting overlapped after submitting fore review.

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a Web project with larger description and Project name
4.Go to specification and Enter the required information
5.Click “Submit For Review”
6.Observre the UI

### Expected Result ###
Window-Member – Project Name and Which is your primary device target? Should not get overlapped after submitting for review.
### Actual  Result ###
Window-Member – Project Name and Which is your primary device target? Is getting overlapped after submitting fore review.

 ### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36347656-a6baa17c-1482-11e8-88f6-793070eac8bc.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#140_

**Comment by zjuasmn** [comment]
@sumitdaga you need to put a long text in project name and submit it than click specification again to see it.
