### ISSUE TITLE
[$40] No edit option for 1st post in discussion

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1772]
_From @gargsaurabh86 on February 18, 2018 18:55_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/665/discussions/2432

### Reproduction Steps ###
1. Login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123
2. Navigate to Discussion like https://connect.topcoder-dev.com/projects/665/discussions/
3. Create a new discussion
4. Post on that discussion 2-3 replies
5. You will see edit option against all replies 
6. Observe Chat post 

### Expected Result ###

Edit option should appear in 1st reply/post as well

### Actual  Result ###

Edit option does not appear in 1st reply/post 

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36355574-23580472-14dd-11e8-91e7-437ef24fdefa.png)

### Issue Information ###

Frequency: Always
Device: Desktop
OS: Windows 10
Browser: Edge

_Copied from original issue: topcoderinc/connect-test-cycle-1#267_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 22, 2018 16:9_

Can be seen in few more instances

https://connect.topcoder-dev.com/projects/800/discussions/2267
https://connect.topcoder-dev.com/projects/800/discussions/2265

But for some of the items, edit button is there

https://connect.topcoder-dev.com/projects/800/discussions/2106
https://connect.topcoder-dev.com/projects/800/discussions/2076

**Comment by sumitdaga** [comment]
@gondzo @vic-topcoder 
it seems the first post can be edited using the edit icon at the very top to the right of the discussion title ....

**Comment by vic-topcoder** [comment]
This is a bug for the very first instance of a reply on a post. Look closer at the attached screenshot. The zones highlighted in yellow should contain edit icon in both cases, but there's not one in the first instance.

**Comment by andela-jomadoye** [comment]
Screenshot attached below
<img width="1680" alt="screen shot 2018-03-08 at 10 06 04 pm" src="https://user-images.githubusercontent.com/26272732/37176544-f54ac512-231c-11e8-867f-cd7c29362d85.png">
