### ISSUE TITLE
[$15] tooltip should be corrected

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1780]
_From @winterflame on February 19, 2018 10:2_

### Reported URL ###

*https://connect.topcoder-dev.com/projects/2679/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project (select App as project type), then upload a text file, click the Edit icon
3. check the tooltip for the 2 icons

### Expected Result ###

*Should have correct tooltips.*

### Actual Result ###

*See screenshots.*

### Screenshots ###

<img width="756" alt="t1" src="https://user-images.githubusercontent.com/4590317/36372119-094bd96a-159f-11e8-8be4-7c7bf55a2964.png">
<img width="757" alt="t2" src="https://user-images.githubusercontent.com/4590317/36372120-0992154c-159f-11e8-8dfd-66d85c0ff15d.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#310_

**Comment by gondzo** [comment]
yes
