### ISSUE TITLE
[$40] Wireframe project with 15 screens but only 10 impotance

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1782]
_From @gargsaurabh86 on February 19, 2018 18:3_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2695/specification/

### Reproduction Steps ###
Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
1. Create a new Wireframe project with 15 screens
2. Navigate to Specifications
3. Go to App Screens section
5 Start adding screen
6 Check the dropdown of Screen importance

### Expected Result ###

The list should have 15 importance based on number of screens

### Actual  Result ###

Only upto 10 importance

### Screenshots ###
![image](https://user-images.githubusercontent.com/29735376/36391525-c5d667d6-159e-11e8-98a1-e3634152f834.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

_Copied from original issue: topcoderinc/connect-test-cycle-1#351_

**Comment by vic-topcoder** [comment]
valid

**Comment by zjuasmn** [comment]
Why importance should based on number of screens? what if some user with 15 screen select a screen with importance 15 and change the number of screens to 10?

**Comment by sumitdaga** [comment]
even my first impression was that this is a scale from 1 to 10 ...so nothing to do with the number of screens

**Comment by vic-topcoder** [comment]
If you have defined 15 screens, you should not be able to reduce the number of screens without first deleting the extra screens. The system should display a warning "You have {number of } extra screens defined. Please remove them to be able to switch to lower screen number for your project".

**Comment by elfman** [comment]
@vic-topcoder @gondzo I don't know what to fix.
1. when project has more then 10 screens, the options of 10 screens is not available, so user can not change it to 10.
2. why should the screen importance based on the numbers of screen? screen importance is not unique, they can have the same importance.

so what should I fix?

**Comment by gondzo** [comment]
@vic-topcoder the issue reported here is that screen importance dropdown should have the same number of options as number of defined screens. that's not really useful IMO - no one will bother ordering the screens that much and the current 10 options are more than enough (and also we already have saved projects with screen importance being 0-10 so it would create validation issues with old projects)
please close if you agree with the above.
