### ISSUE TITLE
[$30] Window-Member – Load more button should be disabled if we don’t have more project to display

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1788]
_From @youdare on February 17, 2018 23:32_

Summary:
Window-Member – Load more button should be disabled if we don’t have more project to display
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2.Log in with pshah_customer/topcoder123
3.Create 19 project 
4.Click Load more button
### Expected Result ###
Window-Member – Load more button should be disabled if we don’t have more project to display

### Actual  Result ###
Window-Member – Load more button is not disabled if we don’t have more project to display
App is displaying Welcome to Connect! I’m Coder the Robot. I see you have no projects yet. To get you started, press the “New Project” icon and let’s build something. Message with no option to create new project or Asking user to click “+” to create project
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346673-f166aa32-1468-11e8-973a-fdb86c5d2051.png)
![image](https://user-images.githubusercontent.com/31862600/36346677-f80f7cf6-1468-11e8-995d-cbcde6407e9d.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#101_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 20, 2018 19:58_

After clicking on the button error is handled properly, so not a bug.

**Comment by andela-jomadoye** [comment]
Hi @vic-topcoder and @gondzo,

There is an error thrown when the application tries to load more projects by pressing the `Load more projects` button. By default, this is what the app displays if there are no more projects to display, it hides the `Load more project` and shows `No more projects`
<img width="1680" alt="screen shot 2018-03-09 at 12 37 24 am" src="https://user-images.githubusercontent.com/26272732/37182636-898ef6fc-2332-11e8-86c6-ba58eac379e4.png">
 A new ticket should be created to fix the `load more projects` button error or this ticket can be updated to reflect this issue.

The code for toggling when the `Load more projects` should be displayed can be found [HERE](https://github.com/appirio-tech/connect-app/blob/3abdc8206d21ab455cd147dbbd2f906e50790894/src/projects/list/components/Projects/ProjectsCardView.jsx#L66) and [HERE](https://github.com/appirio-tech/connect-app/blob/3abdc8206d21ab455cd147dbbd2f906e50790894/src/projects/list/components/Projects/ProjectsCardView.jsx#L67). 

Below is a screenshot of the error thrown 
<img width="580" alt="screen shot 2018-03-09 at 12 53 52 am" src="https://user-images.githubusercontent.com/26272732/37183053-861b6d82-2334-11e8-9dcf-8e48ddb7f632.png">

I would be interested in making an attempt to fix this if my claims are confirmed by you.
Thanks.

**Comment by vic-topcoder** [comment]
@vikasrohit - can you help elaborate on this issue? Thanks

**Comment by vikasrohit** [comment]
To me this seems to be issue with dropdown component and I don't think this issue is creating troubles in fixing this issue. If the button is disabled, its click won't work anyway. It is the dropdown component that is picking up click event on HTML body. We can create separate issue for that to get the dropdown fixed. @gondzo can you please take care of that?
