### ISSUE TITLE
[$60] click on the notification message should dismiss the modal

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1790]
_From @winterflame on February 19, 2018 9:39_

### Reported URL ###

*https://connect.topcoder-dev.com/projects/2652/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project, then update the project (e.g. edit project details) so that some notifications are received
3. go to specification page: https://connect.topcoder-dev.com/projects/2652/specification
4. click the Bell icon, click on the notification message on the modal, observe

### Expected Result ###

*Click on the notification detail should dismiss the modal.*

### Actual Result ###

*See screencasts, if it is already on the current specification page, it won't dismiss the modal.*

### Screencasts ###
https://youtu.be/Z5sEDGXfFqE

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#306_

**Comment by vic-topcoder** [comment]
by design the notifications are not dismissed when clicking on them.

**Comment by elfman** [comment]
I haven't got the repo permission yet, can I take this issue?

**Comment by elfman** [comment]
I tried the steps in this issue, but do not receive any notification. I also login in as another member of the project, still not see any notification.

In the `Network` tab in `Developer Tools`, I can see the request of  notifications always return no items. Does something I do wrong?

**Comment by anonymousjaggu** [comment]
Not able to see the red dot with notification after creating or editing project

**Comment by andirkh** [comment]
same here, not able to see the notification

**Comment by gondzo** [comment]
notifications are now working properly @anonymousjaggu

**Comment by anonymousjaggu** [comment]
Thanks for the update

**Comment by Gauravseta** [comment]
@gondzo near to complete it. PR soon
