### ISSUE TITLE
[$120] Not working feed : Member of a project - 2+ views - show what’s new since last time I viewed the feed

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1792]
_From @gargsaurabh86 on February 20, 2018 1:1_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2724

### Reproduction Steps ###
Login as customer on Chrome 
Add Copilot pshah_copilot as member to project like https://connect.topcoder-dev.com/projects/2724/ and stay on dashboard of project i.e. https://connect.topcoder-dev.com/projects/2724/
Open Edge browser and login as copilot
If Copilot is newly added then create 2+ views to above project dashboard by moving back to All projects then to this project couple of times 
Now 4th time stay on All projects
Go to Customer view in Chrome and update Spec and also comment
Now come back to member view and Navigate to Project dashboard page

### Expected Result ###

As per Spec: Feed: Member of a project - 2+ views - show what’s new since last time I viewed the feed
This is not a notification.

### Actual  Result ###

Not working feed: There is no section on the page that show what’s new since last time I viewed the feed
### Screenshots ###

https://youtu.be/TCiE2YxWv-Q

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 10

Browser: Chrome, Edge

_Copied from original issue: topcoderinc/connect-test-cycle-1#375_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 23, 2018 2:0_

@vic-topcoder

**Comment by vic-topcoder** [comment]
Valid

**Comment by gondzo** [comment]
Prize increased @all

**Comment by Colinh84** [comment]
@gondzo this issue is now solved with improvements to my solution to issue #1538, since they are both related to showing system notifications in a new feed box to replace coderBot.
