### ISSUE TITLE
[$60] Chat bot Project Specification - question count is not changing for "What capabilities does the chatbot need to support?" question

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1794]
_From @gargsaurabh86 on February 19, 2018 23:17_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2723/specification/

### Reproduction Steps ###
1. Login as pshah_manager/topcoder123
2. Navigate to any chatbot project for example https://connect.topcoder-dev.com/projects/2723/specification/
3. observe that question section is having total 5 question to answer
4.  Description is a mandatory field. keep all other 4 questions as answered.
5. observe the count, count shows 2/5 instead of 1/5 (which is wrong)
6. check any check box for What capabilities does the chatbot need to support? question
7. observe the count, count still remains 2/5
8. Remove the check to unanswer the question
9. observe the count

### Expected Result ###

questions Count should be 1/5

### Actual  Result ###

questions count is 2/5

### Screenshots ###

screenshots to follow

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows

Browser: Chrome

_Copied from original issue: topcoderinc/connect-test-cycle-1#372_

**Comment by vic-topcoder** [comment]
_From @gargsaurabh86 on February 19, 2018 23:37_

Question "What capabilities does the chatbot need to support?" is always counted as 1 even if not answered.
https://youtu.be/kVL9nQIZftE

**Comment by tpwwu** [comment]
@vic-topcoder i think this is because the second question `What capabilities does the chatbot need to support?` is not required.
