### ISSUE TITLE
[$60] Issue with Wireframe project adding number of screens

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1796]
_From @gargsaurabh86 on February 19, 2018 17:58_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2695/specification/

### Reproduction Steps ###

1. Log in to https://connect.topcoder-dev.com/ with pshah_manager/topcoder123
2. Create a new Wireframe project
3. Navigate to Specifications
4.  How many screens do you need designed? As **15**
5 Go to App Screens section
6 Start adding screen

### Expected Result ###

User is able to add 15 screens and their details

### Actual  Result ###

User is able to add only 10 screens and their details and post that Define another screen button is disabled.

Screenshots
Comment section

Issue Information
Frequency: Always

Device: Desktop

OS: Window 7

Browser: Chrome

_Copied from original issue: topcoderinc/connect-test-cycle-1#350_

**Comment by vic-topcoder** [comment]
_From @gargsaurabh86 on February 19, 2018 17:59_

![image](https://user-images.githubusercontent.com/29735376/36391495-a77f94ce-159e-11e8-9f3a-28dada0bebb0.png)

**Comment by vic-topcoder** [comment]
_From @sdgun on February 22, 2018 11:7_

This happens when user selects 10 screen project and switch to the 15 screens and try to add 15 screens. So when user switch to the 15 screens section 'Save button' must enable and user should able to save before adding screens

**Comment by sumitdaga** [comment]
i think this issue is present anywhere where user needs to define number of screens , for ex even in visual design .,..and so not limited to wireframes

**Comment by sumitdaga** [comment]
@gondzo @vic-topcoder 
the user it seems will need to save changes in the first section for  it to work ...so if user changes the number of screens from 10 to 15 and "save changes" , then he will be able to define 15 screens!

please clarify what fix do you expect if at all!

**Comment by vic-topcoder** [comment]
If you change the number of screens on the page you should be able to define 15 screens BEFORE you save the changes.
