### ISSUE TITLE
No Reload suggestion for project members

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1797]
_From @gargsaurabh86 on February 19, 2018 15:37_

### Reported URL ###
*URL where the issue occured, if applicable*
https://connect.topcoder-dev.com/projects/2666

### Reproduction Steps ###
1. Login as manager pshah_manager / topcoder123 in one browser and pshah_customer / topcoder123 in another browser
2. navigate to a project which is currently in draft state for both manager and customer (in this case https://connect.topcoder-dev.com/projects/2666)
3. Make sure pshah_manager is added to the member list as manager and pshah_customer is the owner of the project
4. As manager , change the project status from draft to in review
5. A notification is generated to the owner
6. Now go back to pshah_customer logged in browser
7. wait for sometime

### Expected Result ###

As per spec : should trigger reload suggestion for project member currently on the feed

### Actual  Result ###

There is no reload suggestion to reload the page. Also, when you click on notification bell icon you can see the project status is changed

### Screenshots ###
 
![image](https://user-images.githubusercontent.com/29735376/36385492-a4b01804-158a-11e8-9783-2ce7537732eb.png)

*Paste screenshots here.*

### Issue Information ###

Frequency: Always

Device: Desktop

OS: Windows 7

Browser: IE11

_Copied from original issue: topcoderinc/connect-test-cycle-1#330_

**Comment by vic-topcoder** [comment]
_From @sdgun on February 23, 2018 2:0_

@vic-topcoder

**Comment by vic-topcoder** [comment]
valid

**Comment by gondzo** [comment]
page reload suggestions are created for feed updates only. closing
