### ISSUE TITLE
[$15] Wrong grammar on Submit for review page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1799]
_From @8unn on February 19, 2018 8:29_

### Reported URL ###
https://connect.topcoder-dev.com/projects/2677/specification

### Reproduction Steps ###
1.Login as: pshah_copilot/topcoder123
2.Go to the above URL.
3.Scroll down to the bottom, to Project files,Submit a review.
### Expected Result ###

The sentence should be grammatically correct.It should be-"In order to submit your project, please fill in all the required information. **Once you do that, we"ll be able to give you a good estimate.**"

### Actual  Result ###

It's not grammatically correct. It's-"In order to submit your project please fill in all the required information. Once **that** you do that we"ll be able to give you a good estimate."

### Screenshots ###

![image](https://user-images.githubusercontent.com/32297688/36368410-17963780-157d-11e8-942c-c78696767e49.png)

### Issue Information ###

Frequency: *Always*

Device: *Desktop*

OS: *Windows 10*

Browser: *Chrome Version 64.0.3282.140 (Official Build) (32-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#304_

**Comment by anonymousjaggu** [comment]
@gondzo @vic-topcoder can I pick this issue

**Comment by iversonLv** [comment]
@gondzo @vic-topcoder 
I think today is challenge launched day, so I could assign myself, right?
And @anonymousjaggu asked 3 days ago that the challenge is not launched, yet.
