### ISSUE TITLE
[$50] Edit link option not coming for member

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1801]
_From @gargsaurabh86 on February 18, 2018 3:25_

### Reported URL ###
*URL where the issue occured, if applicable*

### Reproduction Steps ###
1. Login as https://connect.topcoder-dev.com as pat_monahan/topcoder123!
2. open any project or https://connect.topcoder-dev.com/projects/2560
3. join the project if not already joined
4 . Create new links if old links not present 
5. Now hover mouse over added link

### Expected Result ###
As per specs: Links: All project members can edit the link

### Actual  Result ###

Edit option was not present ony delete is present

### Screenshots ###

*Paste screenshots here.*
![image](https://user-images.githubusercontent.com/29735376/36347875-be1802a6-145a-11e8-90e6-bbf98b41035a.png)

### Issue Information ###

Frequency: *how often the issue occurs*

Device: *device used for testing*

OS: *operating system used on test*

Browser: Edge

_Copied from original issue: topcoderinc/connect-test-cycle-1#152_

**Comment by narekcat** [comment]
Hi @vic-topcoder , I search over past challenges, but can't find any design of edit link option. Are there any design for this option ? Can I use add link option design ?

**Comment by vic-topcoder** [comment]
Don't think we have a design. It should be the same edit icon for your own posts/comment
![screen shot 2018-03-08 at 8 48 27 am](https://user-images.githubusercontent.com/8484061/37163798-8ccb7744-22ad-11e8-92b4-249d097a0ee4.png)
