### ISSUE TITLE
[$70] user should not be able to click "Add File" button if the user does not have edit permission to the project 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1802]
_From @winterflame on February 18, 2018 1:18_

### Reported URL ###

*https://connect.topcoder-dev.com/projects/2498/specification*

### Reproduction Steps ###
1. login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123 
2. create a new project
3. then login using another user who has no manage permission to this project, go to https://connect.topcoder-dev.com/projects/2498/specification
4. scroll down, click Add File button, observe

### Expected Result ###

*should disable the Add File button.*

### Actual Result ###

*See screenshot, it's clickable.*

### Screenshots ###

*Please check comment section.*

### Issue Information ###

Frequency: *Always*

Device: *Mac Pro*

OS: *Mac OS 10.13.3*

Browser: *Firefox 58.0.2(64-bit)*

_Copied from original issue: topcoderinc/connect-test-cycle-1#126_

**Comment by vic-topcoder** [comment]
_From @winterflame on February 18, 2018 1:19_

<img width="1367" alt="dis" src="https://user-images.githubusercontent.com/4590317/36347224-db636350-148c-11e8-9e99-bd6ba0f3adfb.png">

**Comment by vic-topcoder** [comment]
_From @winterflame on February 18, 2018 2:18_

Currently user is able to add file to the project which he/she only has view permission.

**Comment by arun1595** [comment]
@vic-topcoder I have submitted a [PR](https://github.com/appirio-tech/connect-app/pull/1844) addressing this issue. Do have a look when you have a chance.

Thanks!

**Comment by tpwwu** [comment]
![arun1595 commit bc5c495](https://user-images.githubusercontent.com/35114666/37139468-3f6bb3a0-22ae-11e8-9b8d-9c708d06942a.png)

I use a different strategy to check user permission compared to arun1595 commit bc5c495
