### ISSUE TITLE
[$100] Window-Member – Project is not created successfully, If user tries to create project without log in.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1805]
_From @youdare on February 18, 2018 0:0_

Summary:
Window-Member – Project is not created successfully, If user tries to create project without log in.
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Click “Start A Project”
3.Create a project
4. Application will ask for the Registration
5.Fill the registration form and Enter the verification code
6.Application will direct to created project page
### Expected Result ###
Window-Member – Project is not created successfully, If user tries to create project without log in.

### Actual  Result ###
Window-Member – Project is not created successfully, If user tries to create project without log in.
Getting below error message
### Screenshots ###

![image](https://user-images.githubusercontent.com/31862600/36346819-c9cd4c20-146c-11e8-8e84-b10b3371bc12.png)

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

 

_Copied from original issue: topcoderinc/connect-test-cycle-1#108_

**Comment by vic-topcoder** [comment]
Let's investigate this one

**Comment by mhikeo** [comment]
@vic-topcoder A bit confused with the Expected Result. Kindly clarify. Thanks.

**Comment by vic-topcoder** [comment]
This  was captured by our community bug testing challenge, the issue is to investigate/reproduce the issue.

When a new user creates a project and then registers for Connect, the system should retain all the project information during registration. After successful registration a new project under the newly registered account will be created, and the system will display the new project dashboard page.

Here is reported that the system isn't redirecting to the new project dashboard, or the project isn't created.

Let me know if you can't reproduce the issue, it might not be a valid one after all.

@gondzo FYI
