### ISSUE TITLE
[$100] Reply not working sometimes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1809]
Joey is reporting he is unable to get the reply field active/working sporadically. 

> Another issue I have is responding to posts. I'm not able to click into the messaging error and get a cursor to start typing. It's sporadic, after a few refreshes I can usually get it to work. Thoughts?

<img width="560" alt="screenshot" src="https://user-images.githubusercontent.com/8484061/37047897-359df0f6-2121-11e8-9867-fac22f4c19ac.png">

**Comment by vic-topcoder** [comment]
@gondzo @mtwomey @cwdcwd can we look into this one?

**Comment by zjuasmn** [comment]
It is the placeholder that cover the textarea
