### ISSUE TITLE
Long Usernames are not displayed in one line

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#181]
Description
-----------------------------------------------------------------
Long Usernames are not displayed in one line

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user (christina_uw or pat_monahan)
- In the Dashboard
- Check the Customer column

Expected Result(s)
-----------------------------------------------------------------
- Must display in one line

Actual Result
-----------------------------------------------------------------
- Long Usernames are not displayed in one line

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_4-43-35](https://cloud.githubusercontent.com/assets/4592712/18935688/53592ef8-85ff-11e6-9163-8ec948cd87a0.png)

**Comment by mahestro** [comment]
This is the first time it was reported. Valid granted to this user.
