### ISSUE TITLE
[$40] A User should not be able to update or remove files from a project if he/she does not have edit permission to the project

### ISSUE THREAD

**Issue by arun1595** [appirio-tech/connect-app#1846]
### Expected behavior
A User who only has view access to a project should not be able to edit or remove files from the specification.

### Actual behavior
A user who is not a member of a project can edit and remove uploaded files.

### Steps to reproduce the problem
- Go to http://localhost:3000/projects/2498/specification
- Login to https://connect.topcoder-dev.com/ using pshah_manager/topcoder123
- Scroll down to the files section and you can find the edit and delete icons enabled for pshah_manager who's a non-member

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/7039523/37137046-1a45a19e-2272-11e8-91d4-1da7330792b5.png)

#### Environment
- OS: Ubuntu 16.04 
- Browser (w/version): Google Chrome 64.0.3282.186

**Comment by vic-topcoder** [comment]
@arun1595 Thanks for filing the issue!
@gondzo can we verify this and add it to the bug fixes if not covered? thanks!

**Comment by arun1595** [comment]
@vic-topcoder I have a submitted a [PR](https://github.com/appirio-tech/connect-app/pull/1848) addressing this issue. Check it out and let me know if I missed something. Thanks!
