### ISSUE TITLE
Unable to login to Topgear.topcoder.com using Microsoft Edge 38 and  Internet Explorer: 11

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#1860]
### Expected behavior
Describe.
Topcoder member should login successfully in  Microsoft Edge 38 and  Internet Explorer: 11.

### Actual behavior
Describe.
Topcoder member is not able to login successfully in  Microsoft Edge 38 and  Internet Explorer: 11.

### Steps to reproduce the problem
- TBD.
- TBD.
- TBD.

### Screenshot/screencast
Attach or link a resource.
topgear.topcoder.com/
--

#### Environment
- OS: Windows 10
- Browser (w/version): Microsoft Edge 38.14393.2068.0
                                    Internet Explorer: 11.2068.14393.0
- User role (client, copilot or manager): 
- Account used:  Wipro topgear.topcoder

Note: Topcoder member able to login successfully in Microsoft Edge 40.15063.674.0

**Comment by vic-topcoder** [comment]
This issue was moved to appirio-tech/accounts-app#182
