### ISSUE TITLE
Search button is not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#188]
Description
-----------------------------------------------------------------
Search button is not working

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (christina_uw or pat_monahan)
- In the Projects
- Click on 'Search' field
- Enter 'sdgun' 
- Click Search button

Expected Result(s)
-----------------------------------------------------------------
- Must display the search result

Actual Result
-----------------------------------------------------------------
- Search button is not working 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_4-46-08](https://cloud.githubusercontent.com/assets/4592712/18935736/a95e0436-85ff-11e6-8397-a21a9fdd11e3.png)

**Comment by parthshah** [comment]
Assigning to Vic to fix css issue.

**Comment by vic-appirio** [comment]
Thanks. Will investigate and try to fix.

**Comment by vikasrohit** [comment]
Changes are in dev.
