### ISSUE TITLE
Project status change didn't trigger Slack notification

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1890]
### Expected behavior
When a project in connect goes from "In Review" to "Reviewed" it should trigger a notification into Topcoder's Slack channel `#connect-copilots`

### Actual behavior
https://connect.topcoder.com/projects/5144 didn't trigger slack channel notification

Can we review and see if our Slack integration is working?

**Comment by vikasrohit** [comment]
@vic-topcoder Investigated the issue and found that either our slack incoming webhook is deleted in Slack or its URL has been changed. I tried to find the existing incoming hook but there is no non private integration for that. However, there are few private integrations which I can't see inside. For the time being I have added new incoming webhook and updated/deployed the tc-connect-notifications application to use this new webhook. Need to debug how the webhook got deleted in first place.

**Comment by vic-topcoder** [comment]
Thanks @vikasrohit!
