### ISSUE TITLE
Project reference code isn't showing in SFDC

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1891]
### Expected behavior
Projects created with a reference code should pass the code to SFDC (full code).

### Actual behavior
I see that a lead came in for the chatbot today but the full reference code is not showing in SFDC.

Here's the connect project: https://connect.topcoder.com/projects/5160/specification

Here's the link they used to create the project through the Watson landing page:
https://links8.mixmaxusercontent.com/ucRQHCrk2q7XPgDNi/l/BJhNtR7wTPbnXwJO1?messageId=X2oyW6JoHxKzdesHy&rn=iU2Zy9WZHBicvR3YpZlI&re=gIt92YuIXZk92Yw9GdAV2Zy9WZnZnI&sc=false

leads to "http://watson.topcoder.com/?refCode=IBM-CB-18-001"

We have the IBM team using specific links so that we can track the referrals back to a specific rep. Can you please check this to see why the full reference code wouldn't come across?

Joey Poarch

**Comment by vikasrohit** [comment]
@vic-topcoder There is a limit of 7 characters for REF code as per https://github.com/appirio-tech/connect-app/issues/655.

**Comment by vic-topcoder** [comment]
I thought we had a limit only on the front-end, not the back-end? Can we change the limit to something more useful like 32 characters?

Is the limit at the back end as well?
If the limit is increased, can the data be transferred without a problem?

Let's solve this quickly - increase the limit and make sure we store and pass the data to SFDC. Thanks!

**Comment by vikasrohit** [comment]
@vic-topcoder  No, we don't have limit in backend. However, that deep link is not hitting the backend directly. So, front end is getting rid of extra characters. Let me know if we really want to go with 32 character limit, IMO it is too long. And our UI does not show more than 7 characters at a time.

**Comment by vic-topcoder** [comment]
Let's go with the upper limit of 32 characters, please. We must support the data for IBM and future projects. Our partners use the ref numbers for tracking and they are quite long sometimes.

**Comment by vic-topcoder** [comment]
Also - let's deploy to production once we have this fixed. Joey is expecting more projects with ref codes, we must fix this quickly.

**Comment by jpoarch** [comment]
@vikasrohit - what's the latest with the fix? Thanks!

**Comment by vikasrohit** [comment]
@jpoarch Deployed to production.

@vic-topcoder I have not touched any UI point where it might look bad because of increased number of characters in the ref code.

**Comment by vic-topcoder** [comment]
That's ok :) Thanks!

**Comment by jpoarch** [comment]
Awesome - thanks!










On Fri, Mar 16, 2018 1:44 PM, Vic G. notifications@github.com  wrote:
That's ok :) Thanks!
