### ISSUE TITLE
When Admin/Manager change the project status to 'Active' still the "Project is available for review" message displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1902]
## Rarget URL

https://connect.topcoder-dev.com/projects/3980

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_customer/topcoder123)
3. From the 'Dashboard'
4. Create a New Project
5. Fill all the details and click Submit for Review
6. In Another browser Login as a valid user (pshah_manager/topcoder123)
7. Click on the same project and Change the status to Reviewed
8. Check the notification in both accounts
9. Now from Admin login Change the status to Active
10. Check the notification in the admin login "Project is available for review"

## Actual Result(s)

- When Admin/Manager change the project status to 'Active' still the "Project is available for review" message displayed

## Expected Result(s)

- Must hide the notification or
- Must display the "Project is Approved by xxxx"

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 64.0.3282.140 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![1](https://user-images.githubusercontent.com/4592712/37670315-f8913b52-2c36-11e8-887e-33d8ab5cc30d.jpg)

**Comment by gondzo** [comment]
fixed
