### ISSUE TITLE
File download is not working

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1903]
## Rarget URL

https://connect.topcoder-dev.com/projects/3980/specification

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_customer/topcoder123)
3. From the 'Dashboard'
4. Create a New Project
5. Go to Specification tab and fill all the required details + upload some files and click Save
6. In Another browser Login as a valid user (pshah_manager/topcoder123)
7. Click on the same project
8. Try to download the files

## Actual Result(s)

- File download is not working

## Expected Result(s)

- Must able to download the files

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 64.0.3282.140 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
https://www.screencast.com/t/LBEZNcFl

**Comment by gondzo** [comment]
this is expected in dev environment - as long as we get redirected to target url it's fine.
