### ISSUE TITLE
[Response edit] When user edit the response; No notifications displayed to project members

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1906]
## Rarget URL

https://connect.topcoder-dev.com/projects/3981

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_customer/topcoder123)
3. Go to the 'Dashboard'
4. Click on a project (eg: A)
5. Post a comment on the Dashboard
6. In Another browser Login as a valid user (pshah_manager/topcoder123)
6. Click on the same project (eg: A)
7. Reply to that post
8. Go to 'pshah_customer' Dashboard and check
9. Go to pshah_manager and Edit the reply
10. Go to pshah_customer and check notifications

## Actual Result(s)

- When user edit the response; No notifications displayed to project members
- Can see the bell icon have a red dot but expanding won't display any message

## Expected Result(s)

- Should trigger post notification to all project members but not the response author.

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 64.0.3282.140 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
https://www.screencast.com/t/btnDzuTzcG

**Comment by gondzo** [comment]
fixed
