### ISSUE TITLE
Some times error message displayed while trying to update the notifications

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1907]
## Target URL

https://connect.topcoder-dev.com/projects/3981

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_customer/topcoder123)
3. Go to the 'Dashboard'
4. Click on a project (eg: A)
5. Post a comment on the Dashboard
6. In Another browser Login as a valid user (pshah_manager/topcoder123)
6. Click on the same project (eg: A)
8. Go to 'pshah_customer' Dashboard and Edit some Replies
9. Go to pshah_manager check

## Actual Result(s)

- Failed to load notifications. Cannot find notification rule for eventType 'notifications.connect.project.post.edited' version '2'.

## Expected Result(s)

- Must not display an error

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 64.0.3282.140 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![8](https://user-images.githubusercontent.com/4592712/37685651-34f0b6a6-2c62-11e8-9c13-de4149e6d845.jpg)
https://www.screencast.com/t/8aiUtcAfOY

**Comment by gondzo** [comment]
fixed
