### ISSUE TITLE
'View older comments' option is not displayed on FF

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1908]
## Target URL

https://connect.topcoder-dev.com/projects/3981

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_customer/topcoder123)
3. Go to the 'Dashboard'
4. Click on a project (eg: A)
5. Post a comment on the Dashboard (Must have more then 5 comments or replies)
6. In Another browser (Firefox) Login as a valid user (pshah_manager/topcoder123)
6. Click on the same project (eg: A)
8. Check the comments section

## Actual Result(s)

- 'View older comments' option is not displayed on FF

## Expected Result(s)

- Must display the 'View older comments' option

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** FF 59.0.1

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![9 1](https://user-images.githubusercontent.com/4592712/37689972-312b3a78-2c76-11e8-8656-2d64d6bd2238.jpg)
![9 2](https://user-images.githubusercontent.com/4592712/37689973-314571b8-2c76-11e8-9db9-7ae231a409ef.jpg)

**Comment by gondzo** [comment]
this is no longer an issue with the updated UI
