### ISSUE TITLE
New QA Intake Form - SFDC Accelerator

### ISSUE THREAD

**Issue by wdprice** [appirio-tech/connect-app#1910]
### Expected behavior
Require creation of a new project intake form visible under the QA submenu. The basic questions are contained in the attached xls document. No additional fields are required at this time past the basic questions.

### Actual behavior
N/A

### Steps to reproduce the problem
N/A

### Screenshot/screencast
Attach or link a resource.
[Salesforce_Testing_Topcoder_Q_V0.2.xlsx](https://github.com/appirio-tech/connect-app/files/1831747/Salesforce_Testing_Topcoder_Q_V0.2.xlsx)

**Comment by vic-topcoder** [comment]
Icon for the new product/project type
[product-qa-sfdc-accelerator.svg.zip](https://github.com/appirio-tech/connect-app/files/1832003/product-qa-sfdc-accelerator.svg.zip)

**Comment by vic-topcoder** [comment]
@wdprice please confirm what is the title and the description for the new product card.

Example with the new icon
![screen shot 2018-03-20 at 8 47 55 pm](https://user-images.githubusercontent.com/8484061/37693894-fc2a3784-2c7f-11e8-96b1-fff5d624d65c.png)

**Comment by RishiRajSahu** [comment]
A quick raw thing for you two to review - http://connect-test02.topcoder-dev.com/

**Comment by RishiRajSahu** [comment]
![change-02](https://user-images.githubusercontent.com/11248478/37763487-3d34ff32-2de5-11e8-9539-15357aa90e81.png)

**Comment by vic-topcoder** [comment]
From Will:
> Replace all instances of `salesforce` in the page copy with `Salesforce.com`. Do not change the title

@RishiRajSahu - can you please make the changes and merge with Dev so we can do a release? Thanks!

**Comment by RishiRajSahu** [comment]
Done and merged to dev - https://github.com/appirio-tech/connect-app/pull/1919
