### ISSUE TITLE
Updated QA Intake Form - Performance Testing

### ISSUE THREAD

**Issue by wdprice** [appirio-tech/connect-app#1911]
### Expected behavior
- Performance Testing tile should be exposed in the QA submenu.
- Questions on the form should be updated according to the attached xls. 
(No new questions, all rows correspond to an existing question. Text in red represents a question in which the wording was changed or spelling fixed. All items in red should be updated.)

### Actual behavior
N/A

### Steps to reproduce the problem
N/A

### Screenshot/screencast
Attach or link a resource.
[performancetestingintakeupdates.xlsx](https://github.com/appirio-tech/connect-app/files/1831839/performancetestingintakeupdates.xlsx)
--

**Comment by RishiRajSahu** [comment]
@wdprice Merged the required changes for enabling performance testing with rephrased questions as provided in attachement - https://github.com/appirio-tech/connect-app/pull/1915. 
Please review on dev.
