### ISSUE TITLE
6 notification items displayed in the notification drop down for one project

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1912]
## Target URL

https://connect.topcoder-dev.com/projects/3983

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_manager/topcoder123)
3. Go to the 'Dashboard'
4. Click on Notification symbol
5. Check the section "Let's setup your App project - Manager"
6. 6 items displayed

## Actual Result(s)

- 6 notification items displayed in the notification drop down for one project

## Expected Result(s)

- Notification dropdown is accessible and shows the correct number ≤ 5 per project, all notifications ≥ 6 are hidden.

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 64.0.3282.140 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![11](https://user-images.githubusercontent.com/4592712/37693459-be489470-2c8d-11e8-888e-db4dd0ce6cce.jpg)

**Comment by gondzo** [comment]
tracked in #1720
