### ISSUE TITLE
If the notifications are combined with the old one; Must move the notification to the last position if there are new updates

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1914]
## Target URL

https://connect.topcoder-dev.com/projects/3983

## Steps to Reproduce

1. Open the web application
2. Login as a valid user (pshah_customer/topcoder123)
3. Go to the 'Dashboard'
4. Create a Project
5. Now Add a manager to the project
6. Now using Manager and Customer account do some changes like Upload a file and change the spec and also add a new link to the project (eg: Project A)
7. After doing some changes
8. Login as 'pat_monahan'
9. Join to the Project
10. Go to pshah_customer and check the notification and order

## Actual Result(s)

- Combined notifications are not moved to the list; So as per the updated time it won't move to the last position

## Expected Result(s)

- If the notifications are combined with the old one; Must move the notification to the last position if there are new updates

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 64.0.3282.140 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![13](https://user-images.githubusercontent.com/4592712/37695831-3331095e-2ca0-11e8-9532-7e86f1e59d4d.jpg)

**Comment by gondzo** [comment]
not an issue anymore. closing
