### ISSUE TITLE
[$20] Gap in project status drop-down menu

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1917]
### Expected behavior
By design there shouldn't be big gap between menu title and menu options.
![screen shot 2018-03-22 at 2 23 30 pm](https://user-images.githubusercontent.com/8484061/37799323-a1c2d14e-2ddc-11e8-8393-02f999286e04.png)

### Actual behavior
![screen shot 2018-03-22 at 2 22 18 pm](https://user-images.githubusercontent.com/8484061/37799327-a3fc6830-2ddc-11e8-8ad9-232d76c54156.png)

**Comment by PrakashDurlabhji** [comment]
assign ourself not wrking? @gondzo  not able to click it

**Comment by PrakashDurlabhji** [comment]
@vikasrohit @gondzo 
MR raised.

#2142 
Any more issues i can work on? any more open for pickup?
