### ISSUE TITLE
When I join a project, the side bar doesn't automatically update to show me I've joined

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1918]
### Expected behavior
As manager/copilot, join a project. The system should automatically update the sidebar to show that I've joined.

### Actual behavior
The page needs to be manually reloaded before the change is displayed.

**Comment by vikasrohit** [comment]
@vic-topcoder This is because of discourse call lag. It would be fixed with discourse migration.

**Comment by vic-topcoder** [comment]
Let's not tie the front-end update to be dependent on the back-end (Discourse). This is what the promise pattern is all about - optimistic about the update going through. The user should immediately see the change reflected on the front-end even it will take a while for Discourse (or our in-house solution) to complete the work. This approach applies to any back-end dependent actions.

**Comment by vikasrohit** [comment]
@vic-topcoder Ideally we should not show false information to the user i.e. until the process is completed in the backend we should not show the user being added to the team as it would give them false impression if the backend operation fails.

Anyway, now it should be pretty quick to add team member as not it does not wait for discourse operation to add user to appropriate topic. So, users won't be able to notice the time lag.
One improvement we can do is to add loading icon to show the progress but that is UX question for you. :)
