### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1922]
Marvel app - https://marvelapp.com/14i7h0d6 

The scope is to update the existing connect app with new responsive designs for mobile. All screens shown in the marvel app are in scope :
landing page, 
project list, 
menu, 
notifications, 
project details, 
new project

Major requirement is to have desktop and mobile views share the same logic (containers, components) and not have duplicate views. Existing components should be refactored as needed to support such use case. Many of the features in mobile design are just scaled down version of desktop views, so simply using media queries should be enough in most cases.

Mobile view will NOT have these features that are available in desktop version:
Project search filter
Projects Grid view for admin users
Create new project
Specifications screen
Discussions screen

Login/Register features are part of the accounts app, they are external to the connect-app and don’t need to be updated. Mobile designs don’t introduce any new assets so all existing icons and fonts should be reused.

**Comment by maxceem** [comment]
Do you have Zeplin or sources in another format where I can get font sizes etc?

**Comment by maxceem** [comment]
@gondzo What about tablet resolutions in between current desktop implementation and mobile resolution?

**Comment by maxceem** [comment]
3. There are landing page and project list page in mobile design while in desktop it's the same page. As we come to the landing page after login, how do we come to the project list page?

**Comment by maxceem** [comment]
4. How do we get to the Create new project screen in the mobile version?

**Comment by gondzo** [comment]
2. Tablet resolutions should keep the same latout as desktop IMO. @vic-topcoder can you confirm

**Comment by gondzo** [comment]
3. Those are the same pages in mobile as well

**Comment by gondzo** [comment]
4. By clicking on the new project card in project listing

**Comment by maxceem** [comment]
> 3. Those are the same pages in mobile as well

Design looks a little bit different 
![image](https://user-images.githubusercontent.com/146016/38085309-93df6cd0-3382-11e8-8051-ced365c5574a.png)

Different font sizes, and also a little bit different information is displayed. If it's the same page, could please clarify which design to follow.

**Comment by vic-topcoder** [comment]
Correct - 768 and up should be Desktop, and all should be visible

**Comment by RishiRajSahu** [comment]
@maxceem go with the left one. as this is the standard card we are having on desktop.

**Comment by maxceem** [comment]
Thank you! Just still wondering if you have any source files where I can get font sizes, real sizes of elements, maybe some icons and so on...?

**Comment by RishiRajSahu** [comment]
@maxceem your mail id ? I will forward them

**Comment by maxceem** [comment]
@RishiRajSahu maxceem@gmail.com

**Comment by RishiRajSahu** [comment]
sent.

**Comment by maxceem** [comment]
@vic-topcoder @RishiRajSahu
 
On the tablet filters doesn't fit 
![image](https://user-images.githubusercontent.com/146016/38126569-1095cb2e-3424-11e8-8c91-10c87be7a90c.png)

See desktop
![image](https://user-images.githubusercontent.com/146016/38126587-209eeb86-3424-11e8-85fd-7e07ebcbd12d.png)

Do you have any preferences how to deal with it?

**Comment by RishiRajSahu** [comment]
@maxceem we are not showing this complete nav bar for mobile/tablet, that is the reason we have designs with default card view for clients on mobile/tablet.
Hope this answers.

**Comment by maxceem** [comment]
@RishiRajSahu Probably better let's use numbers, rather than mobile/tablet/desktop labels.

**vic-topcoder previously said:**
> Correct - 768 and up should be Desktop, and all should be visible

I think this a good way to go. We use provided mobile design until 768px.

But that filter doesn't fit 768 px, probably can show some shotter version of the filter from 768 untill 992?

FYI there is list of breakpoints which are being used in the app now.
```
$screen-lg: 1360px;
$screen-rg: 992px;
$screen-md: 768px;
$screen-sm: 640px;
$screen-xs: 320px;
```

**Comment by gondzo** [comment]
Let's hide the all projects filter option for <992px

**Comment by maxceem** [comment]
5. Should mobile menu **push** the below content when it's opened like it's on the topcoder.com or overlay on top of the website?

6. There is no Copyrights footer in the mobile design, should I keep the one from desktop resolution?

**Comment by gondzo** [comment]
5. Push 
6. Yes please

**Comment by maxceem** [comment]
@gondzo is it ok in some places to use https://github.com/contra/react-responsive

For example: Project list is displayed like a table but in mobile it has to be cards which already have. To adjust design using CSS is not easy in this case. So probably it would be easier to control output with React in this case. And in few other minor cases.

**Comment by maxceem** [comment]
8. There is not Add link button for links 
![image](https://user-images.githubusercontent.com/146016/38131369-6a4f97a2-3439-11e8-979a-c8a7e1acfa5b.png)

But we have + button to add links in desktop resolution. Should I add "add link" button simillar to memebrs in mobile design?

**Comment by RishiRajSahu** [comment]
8. yes you can add similar button with text 'Add New Link'

**Comment by gondzo** [comment]
7. Yes

**Comment by maxceem** [comment]
@gondzo should it work like an accordion (one opened at time), or several can be opened same time?

![image](https://user-images.githubusercontent.com/146016/38135432-96714ab8-344a-11e8-9c57-c149819b68f0.png)

**Comment by maxceem** [comment]
11.
Where should link **Getting Started** lead to?

![image](https://user-images.githubusercontent.com/146016/38138678-b3036fee-345e-11e8-95a4-9fed96e63a66.png)

**Comment by maxceem** [comment]
@gondzo 

> Let's hide the all projects filter option for <992px

Unfortunately, it's not enough 

![projects - topcoder 2018-03-30 22-31-11](https://user-images.githubusercontent.com/146016/38141335-32e44610-346a-11e8-9005-d4884c47b240.png)

**Comment by gondzo** [comment]
9. I think either is fine
10. Let's not have a fixed toolbar in mobile view
11. Dead link for now

@vic-topcoder any suggestions about the project filter at 768>resulotion<992

**Comment by maxceem** [comment]
12. We can click on notifications and go to some pages like specifications for which we don't have mobile design yet. Should I remove links from notifications for now in mobile resolution?

13. There is some difficulty in using project list in card view. If we open project status dropdown, and after want to close it, we have to click somewhere. But as full cards are links there is almost no space to click without proceeding to the project details page. In the mobile resolution I think it would be even more obvious issue, as there is almost no other space except cards.
Maybe we can make only the header of the card clickable? I think this can make sense for all resolutions.

    ![image](https://user-images.githubusercontent.com/146016/38161454-7370dd64-3501-11e8-8b8e-523c83f36e07.png)

**Comment by gondzo** [comment]
12. Yeah, let's remove the links in mobile for now, we'll have to figure out a way to handle the links properly based on which pages are implemented and which are not.

13. That's a good idea IMO

**Comment by maxceem** [comment]
Suvbmitted [PR](https://github.com/appirio-tech/connect-app/pull/1933)

**Comment by gondzo** [comment]
Thanks for the quick PR @maxceem 
Looks like the topics/comments on project dashboard are hidden in the mobile view (screens 5-8) and we do need them in mobile view. I guess the misunderstanding is that is said `Discussions screen` is not in scope but that isn't about discussions on the dashboard, but the discussions tab available on old projects only (ex https://connect.topcoder-dev.com/projects/800 )

**Comment by gondzo** [comment]
Btw, I have merged the PR into a feature branch feature/connectMobile and you can push any new changes there directly. Also, I have created a milestone called Mobile connect where I'll add all individual issues so we don't put everything in this one long issue

https://github.com/appirio-tech/connect-app/milestone/49

**Comment by maxceem** [comment]
14. At the link list, there is edit/delete functionality in desktop, it's supposed to be hidden at Mobile as we don't have "mouse hover" event, correct?

15. If there are too many links, not all links are shown and **View all** button is shown. Though it looks broken in Desktop. So I'm fixing it and displaying for mobile slightly bigger, makes sense?

![qqqq - topcoder 2018-04-02 14-04-59](https://user-images.githubusercontent.com/146016/38185159-6316413c-367f-11e8-9308-27fa4420a295.png)

**Comment by RishiRajSahu** [comment]
14. we can keep it hidden for now.
15. fine.


other than if found below two issues on dev env,
-Landing page navigation is broken on mobile
-Also 'getting started' takes us to https://www.topcoder.com/about-topcoder/connect/ on desktop so it should be same for mobile as well.

**Comment by maxceem** [comment]
@RishiRajSahu 
> -Landing page navigation is broken on mobile

Could you please clarify this as I cannot find the place where navigation is broken for mobile.

**Comment by RishiRajSahu** [comment]
@maxceem actually its not correctly aligned.

<img width="508" alt="screen shot 2018-04-02 at 2 32 22 pm" src="https://user-images.githubusercontent.com/11248478/38190634-c24b7d90-3682-11e8-92b8-9b333444b902.png">
<img width="496" alt="screen shot 2018-04-02 at 2 32 35 pm" src="https://user-images.githubusercontent.com/11248478/38190635-c28366b0-3682-11e8-8f0e-cab4aee5953c.png">

**Comment by maxceem** [comment]
Thanks, found that another user has a slightly different view, fixing...

**Comment by RishiRajSahu** [comment]
@maxceem expanding/collapse icons are opposite on project details page.

**Comment by RishiRajSahu** [comment]
@maxceem logout on mobile is redirecting to new page.

**Comment by maxceem** [comment]
Fixed everything until this moment. 

Also adjusted for mobile resolution message when there are no notifications.

![image](https://user-images.githubusercontent.com/146016/38193878-e9ae73b4-36a6-11e8-8aba-b46d3a94fbb9.png)
