### ISSUE TITLE
Reduce emails when joining a new project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1928]
If you join a new project the system sends out emails for each new discussion topic joined. Is there a way to reduce the number of emails (eliminate the joining discussion emails)?

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-29

**Comment by vikasrohit** [comment]
We can close this one as after getting rid of discourse, we are not sending emails for all messages that were posted before user's joining the project.
