### ISSUE TITLE
Profile drop down won't work in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#193]
Description
-----------------------------------------------------------------
Profile drop down won't work in IE11

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (christina_uw or pat_monahan)
- In the Projects
- Click on 'Profile' picture

Expected Result(s)
-----------------------------------------------------------------
- Must display the Help and Logout

Actual Result
-----------------------------------------------------------------
- Profile drop down won't work in IE11

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** christina_uw or pat_monahan

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_4-47-21](https://cloud.githubusercontent.com/assets/4592712/18935774/e64f598a-85ff-11e6-9ada-feeaa8995d32.png)

**Comment by vic-appirio** [comment]
Similar to the rest of the drop-down issues.

**Comment by vic-appirio** [comment]
Investigate if it is a layout issue; if it's JS related reassign to @vikasrohit

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev.
