### ISSUE TITLE
Project status menu doesn't close on tap outside

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1942]
### Expected behavior
Tapping outside of the project status drop-down menu should close the menu.

### Actual behavior
tapping outside does nothing
![img_3550](https://user-images.githubusercontent.com/8484061/38344472-a0ccf7b2-383e-11e8-8537-700eeed4cb2f.png)

**Comment by RishiRajSahu** [comment]
Not reproducible on android chrome browser.

**Comment by maxceem** [comment]
This is fixed in Dropdown component from react-components repo.
Submitted [PR](https://github.com/appirio-tech/react-components/pull/286)  react-components.
