### ISSUE TITLE
Collapse the empty space on the project cards

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1943]
### Expected behavior
In portrait mode the empty space of the project cards (all projects) is not needed. Collapse the card min-height to allow higher content density on the feed page. This applies only for portrait mode - vertical scrolling.
![img_3551](https://user-images.githubusercontent.com/8484061/38344591-36e88072-383f-11e8-82a5-d775339f67df.png)

**Comment by RishiRajSahu** [comment]
I see it's a common bug for both desktop and mobile.

**Comment by maxceem** [comment]
@RishiRajSahu if we remove the height for desktop it will looks like this, rows have various heights:

![image](https://user-images.githubusercontent.com/146016/38362372-31e1d8de-3903-11e8-8102-70c01bb6e70c.png)

**Comment by RishiRajSahu** [comment]
@vic-topcoder this is looking even more inconsistent. should we stick to the previous design ?

**Comment by RishiRajSahu** [comment]
@maxceem project description has limit of 160 chars, the image you have pasted has description of very few words. I think we can show only 160 chars for description for each card and beyond that can show 'read more' this way we will always have consistent view. could you check on that once ?
@vic-topcoder what say ?

**Comment by maxceem** [comment]
@RishiRajSahu @vic-topcoder just to not, that in general 160 characters not always mean fixed number of lines, so it can be let's say 3, 4 or 5 lines.

For now, we cut text after 8 lines no matter how many characters.

**Comment by maxceem** [comment]
Just synthetic examples of the worst situation with various 160 characters:

- wide card:

   ![image](https://user-images.githubusercontent.com/146016/38364891-f16610cc-390c-11e8-9228-ace4f1ad669c.png)

- narrow card:
   
    ![image](https://user-images.githubusercontent.com/146016/38364931-159f949a-390d-11e8-9a8d-1758f70f96b9.png)

If we put limit to 4 lines:

- wide card:

    ![image](https://user-images.githubusercontent.com/146016/38365018-5eda9b96-390d-11e8-8af9-0701a2731ee8.png)


- narrow card:
    
    ![image](https://user-images.githubusercontent.com/146016/38364987-480a7b84-390d-11e8-9637-14ec0c562088.png)

**Comment by vic-topcoder** [comment]
on Desktop we need to keep the card as is. The design is taking into account variable size and responsive.

Only change on mobile portrait mode please.
