### ISSUE TITLE
When scrolling project dashboard messages left column and right column width are being changing

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1945]
### Expected behavior
When scrolling project dashboard messages, the width of the messages and project details stays same and space between them is not changed.

### Actual behavior
During scrolling on big resolution space between dashboard message and project details block is changing together with messages and project details width.

When the window size is smaller than 1100px messages and project details start overlap during scrolling.

### Steps to reproduce the problem
- Open project with messages https://connect.topcoder-dev.com/projects/2633
- Make sure browser window width is more than 1100px
- Scroll 
- Make windows width is less than 1100px and scroll again to see how they can overlap.

### Screenshot/screencast
http://take.ms/8gI36

#### Environment
**Note** cannot reproduce with FireFox
- OS: macOS v10.13.3
- Browser (w/version): Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- User role (client, copilot or manager): manager
- Account used: pshah_manager

**Comment by maxceem** [comment]
Can reproduce it in FireFox 59.0.2 (64-bit) on the small screen http://take.ms/ZHrkE

**Comment by maxceem** [comment]
The bug is only reproducible if project description contains long string without spaces. 

![test - topcoder 2018-04-07 20-25-17](https://user-images.githubusercontent.com/146016/38454864-db7999d2-3aa1-11e8-8545-d0ef2618bb28.png)

**Comment by maxceem** [comment]
Also, this bug is reproducible on the specification page when **Submit for review** button is shown for the project owner user: http://take.ms/c6TJH

**Comment by gondzo** [comment]
this is no longer an issue. closing
