### ISSUE TITLE
[$70] Copilot don't have access to the projects which are available to pick up

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1946]
### Expected behavior
I'm not sure. One of two:
- copilot doesn't see notifications `Project is available for pickup` if he doesn't have rights to access it
- if copilot see notification `Project is available for pickup`, when he go to the project, he can access it.

### Actual behavior
Copilot user has notifications that says `Project is available for pickup`. After clicking such notifications I see Error 404 - page not found. Though project exists and manager can access it. No copilots are assigned yet.

### Steps to reproduce the problem
- Login as a copilot.
- Open notifications and click any notification which says `Project is available for pickup`
- Instead of project page, Error 404 page will be shown and in console there will be error 403 while accesing project endpoint like `https://api.topcoder-dev.com/v4/projects/3943/`.

### Screenshot/screencast
http://take.ms/IFoxt

#### Environment
- OS: macOS v10.13.3
- Browser (w/version): Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- User role (client, copilot or manager): copilot
- Account used: pshah_copilot

**Comment by vic-topcoder** [comment]
@gondzo @vikasrohit - what's the status on this one?

**Comment by vikasrohit** [comment]
@maxceem it requires the project status to be in `reviewed` status. Any other status on the project, would deny a copilot to access the project.

**Comment by gondzo** [comment]
this is no longer an issue. reviewed projects can be seen by the copilots.

should we show a different message to a copilot if the project is already taken and moved to active state? @vikasrohit

**Comment by rmjmccormick** [comment]
@vikasrohit @gondzo to clarify, do you mean (a) a different notification to "Project is available for pickup" on the notification page or (b) a pop-up message informing the co-pilot the project has been taken if/once they click on "Project is available for pickup" notification?

**Comment by vikasrohit** [comment]
(b). I think right now we show 403 for such cases which is not clear for the copilots.

**Comment by vic-topcoder** [comment]
In that case I would show a message in the lines of "This project is not yet reviewed. Once it is available for pickup you will be able to view and join it." instead of throwing 403.

**Comment by gondzo** [comment]
@vikasrohit Should we update project service to return an error message based on project status?

**Comment by gondzo** [comment]
Related tc-project service issue https://github.com/topcoder-platform/tc-project-service/issues/105

Once that is completed, we'll be able to update the frontend to show the error message

**Comment by vikasrohit** [comment]
Thanks @gondzo for creating the issue, however, when I tried to implement that in the project service, I found that I have to change in core library's permission module or refactor the way we are handling the permissions in the service. So, I think it would be better if we can validate the project's status on the frontend when there is 403 in calling project api and show message accordingly.

**Comment by gondzo** [comment]
With 403 only, we don't know if project is not in review yet or is already taken by a different copilot

In the backend we'd have to change the error message in the permissions for project.view https://github.com/topcoder-platform/tc-project-service/blob/dev/src/permissions/project.view.js , not in the controller/service. Should be fairly easy?

**Comment by vikasrohit** [comment]
Oh, got it. Front end does not know the status of the project without calling the API.

@gondzo, Can you please get it implemented it in project service?

**Comment by vikasrohit** [comment]
I think that would be a good question for @rmjmccormick  and @vic-topcoder

**Comment by gondzo** [comment]
@vikasrohit done, backend will return one of three error messages for copilot:
`Copilot: Project is already claimed by another copilot`
`Copilot: Project is not yet available to copilots`
`Copilot: Project has already started`

all of them are prefixed with `Copilot:`. Can you update the UI to show those error messages for copilots?

**Comment by vikasrohit** [comment]
Cool. We can move this issue to CF 10 where I am trying to group all pending tasks for the upcoming release.

**Comment by rmjmccormick** [comment]
> One more thing about copilot access - service will allow only one copilot to claim the project, but with multiple phases it would make sense to have multiple copilots. Should we keep this as is and let managers assign other copilots or we need to update this policy?

@gondzo @vikasrohit This came up yesterday on a demo on Monday with the business. It's a good point and we need to consider further. For the time being, I'd leave as it please.

**Comment by vikasrohit** [comment]
Yes, we have that mind while brainstorming for the project plan. We thought of having separate teams per phases but left it out of scope because it needs more brainstorming.

**Comment by gondzo** [comment]
The task here is to show a custom error message from the api in case the error message starts with "Copilot:"

**Comment by andela-jomadoye** [comment]
@gondzo Do you have any mockup or idea of how the `Custom Error message` should be displayed?

**Comment by gondzo** [comment]
It can be similar to the 404 screen but include the error message text
