### ISSUE TITLE
Filters don't fit the tablet resolution screen.

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1947]
@vic-topcoder could you please advise how to deal with the next thing.

Filters on the tablet resolution doesn't fit the window screen. There is too much stuff.

On the tablet filters doesn't fit 
![image](https://user-images.githubusercontent.com/146016/38126569-1095cb2e-3424-11e8-8c91-10c87be7a90c.png)

See desktop
![image](https://user-images.githubusercontent.com/146016/38126587-209eeb86-3424-11e8-85fd-7e07ebcbd12d.png)

### Steps to reproduce the problem
- Open parjects list as a manager 
- Switch to Card view
- Resize browser window until 768px wide
- There is too much stuff on the filters row to fit to the screen

### Screenshot/screencast
http://take.ms/IFoxt

**Comment by RishiRajSahu** [comment]
@maxceem for <=768px will share the designs soon.

**Comment by vic-topcoder** [comment]
let's collapse the tabs that can't fit under a drop-down wit title "More". Similar to Google

![screen shot 2018-04-09 at 3 10 38 pm](https://user-images.githubusercontent.com/8484061/38525726-376d0ae6-3c08-11e8-9c40-a13059b3947b.png)
