### ISSUE TITLE
Cannot add a new member using copilot role

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1948]
### Expected behavior
Not sure. One of two:
1. A user with copilot role doesn't have a button to add new members.
1. If a user with copilot role has a button to add new members he has to be able to do it.

### Actual behavior
A user with copilot role cannot add a new member even he can open a form for adding new members.

### Steps to reproduce the problem
- Login as a `pshah_copilot`
- Open any project, for example, https://connect.topcoder-dev.com/projects/4765
- Click "+" to add project member.
- Start typing a name of any user
- In the browser console you can see that all requests to get a list of user for autocomplete fail with error 403. And in the returned json there is a message `You don't have permission to perform this operation`.
- As no users can be found for autocomplete, add button will never be active.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/146016/38486787-9d60f526-3c10-11e8-8ede-4618a00bf8ea.png)

#### Environment
- OS: macOS v10.13.3
- Browser (w/version): FireFox 59.0.2 (64-bit)
- User role (client, copilot or manager): copilot
- Account used: pshah_copilot

**Comment by vic-topcoder** [comment]
We modified the behavior - only admins and managers can perform that action. The menu button for adding new member should not be visible to any other user role besides manager/administrator.
