### ISSUE TITLE
Handle discourse users created via email

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1950]
Currently when an user replies to the notification email sent by connect messaging system (discourse), there are two scenarios when discourse creates a new discourse user in its system with a non numeric username which is essential for Connect's front end to render the author details for topic/posts:
1. User has email forwarding enabled which causes the post created from different email address than the original one where original email was sent.
2. User adds other users in the thread of notification email and those new users replies to any of the email.
Now because it creates new discourse users(who may not even have topcoder account) with non numeric user name, front end breaks as it tries to pull the member profile details using those usernames. This is the error which we see in such cases:
```javascript
{
    "id": "-3e7c913c:162aa79b06f:-4b18",
    "result": {
        "success": true,
        "status": 500,
        "metadata": null,
        "content": "{\"root_cause\":[{\"type\":\"number_format_exception\",\"reason\":\"For input string: \\\"<NON_NUMERIC_USERNAME>\\\"\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"members3\",\"node\":\"00kmoaYpTkqwaJ__APPQZw\",\"reason\":{\"type\":\"number_format_exception\",\"reason\":\"For input string: \\\"<NON_NUMERIC_USERNAME>\\\"\"}}]}"
    },
    "version": "v3"
}
```
As as resolution, we need to support handling unkown users in front end. So, we need to do following steps to handle such cases:
1. Do not pass the non numeric usernames of topic/posts to the member search API when loading member details via `loadMembers` action.
2. Render the generic `Connect User` as user for all such topic/posts when rendering the author details for them. We are already doing this for some exceptional cases where user object is null. So, either that behaviour would just work if don't try to search for such users as mentioned in step 1 or we might have to extend that logic for such users.

From the products' feature perspective, we have to think how we should support such users. Ideally we would like to treat two different emails appearing because of email forwarding to be the same user and new users included in the mail thread to be a valid Connect user and a team member of the project. But all of these requires much more thought process and decision making.

fyi @vic-topcoder @mtwomey @cwdcwd @gondzo @jpoarch

**Comment by cwdcwd** [comment]
is this a Discourse specific issue, @vikasrohit, that will go away once we're off Discourse?

**Comment by vic-topcoder** [comment]
If an email is from an unknown origin or user is not registered, we should not post, or break the system. 

We should not try to parse the people on a thread of an email, or use any of the quoted content. As I see it, it is really about trying to create a post via email, and if you're using an email that doesn't match any of our records, the system should send back a message for an error.

**Comment by vikasrohit** [comment]
Closing the issue as now we don't have discourse and new messaging system does not automatically creates a new user when there is a mismatch in emails. It silently ignore the email right now, we have to send reply email with error message to complete this use case.
