### ISSUE TITLE
Project list grid view for tablet resolution

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1952]
@vic-topcoder Could you please advise how to deal with project list grid view for resolutions from 768px till 1174px (tablet, small desktop)?

Currently at this resolution range grid view is cut by windows screen:

![image](https://user-images.githubusercontent.com/146016/38606764-82f67310-3da9-11e8-9f68-33940651aada.png)

For resolutions 1174px and up it looks good:

![image](https://user-images.githubusercontent.com/146016/38606056-a59510f4-3da7-11e8-8b75-d13b57b9b703.png)

Should we switch to crad view for such resolution? Or try to fit grid making cells smaller?

**Comment by vic-topcoder** [comment]
We're working on the mobile design challenge right now, the project grid for admins is one of the screens we're going to attack on the next iteration, after the design is completed. You can leave this one out for the moment

**Comment by maxceem** [comment]
@vic-topcoder @RishiRajSahu 

Provided mobile design is for screens < 768px.
Currently implemented desktop grid view requires screen >= 1180px.

So there is an unhandled range 768px - 1180px, see http://take.ms/A5Yqz

I've handled it on my taste the next way, see http://take.ms/l0ibe
- < 1180px - hide `ID` column
- < 1160px - hide `Managers` column
- < 1024px - hide `Status` column
- < 992px - switch to mobile view, but keep margins around table
- < 768px - remove margins around table, so complitely switch to mobile design

Let me know if you would like another bahavior.
