### ISSUE TITLE
'Submit for review' button is not enabled in visual-design project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1953]
### Expected behavior
'Submit for review' button should be enabled once all required information is captured.

### Actual behavior
Even after putting in all required information, the button is in disabled mode.

### Steps to reproduce the problem
- As a customer, create or edit a visual-design type project.
- Fill all required information i.e. left panel should have all sections checked.
- Notice that the button is not enabled yet..

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): client
- Account used: Customer reported

fyi, @jpoarch @vic-topcoder @gondzo

**Comment by gondzo** [comment]
@RishiRajSahu @vikasrohit I'm not able to create visual design projects in dev anymore. 
POST https://api.topcoder-dev.com/v4/projects/ returns a 422

**Comment by RishiRajSahu** [comment]
@gondzo fixed it. you can create now.

**Comment by gondzo** [comment]
@RishiRajSahu I'm not sure how to get the 'Submit for review' button on any project type. For example https://connect.topcoder-dev.com/projects/6551/scope - all items are filled in scope and phase spec tab. Same thing for app project type https://connect.topcoder-dev.com/projects/6552

**Comment by RishiRajSahu** [comment]
@gondzo only owner and customer can submit for review, https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/ProjectSpecSidebar.jsx#L118

**Comment by gondzo** [comment]
ok, this is no longer an issue. closing
