### ISSUE TITLE
[$30] Search results are not visible on any status filter other than 'All Projects'

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1954]
### Expected behaviour
Should show search results in all project status filters.

### Actual behavior
It does not apply the text filter with any specific project status filter except 'All Projects'.

### Steps to reproduce the problem
- Login into Connect as manager.
- Make sure you have a project status filter, other than 'All Projects', selected.
- Now do a text search from the top bar.
- Notice there is no effect of search on the projects shown in the grid. Now if you select 'All Projects' filter, it would show you the search results.

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): manager
- Account used: vikasrohit

fyi @vic-topcoder @jpoarch @gondzo I think we should fix the text message in case of no results found something like 'No results found with current search criteria, please try relaxing the filters' because without such information user might be confused when he/she searches from top bar while being on particular status filter and there is no result for that particular status but there are results for different project status. User might miss to click on appropriate status filter unless we notify them with more detailed message.

**Comment by vic-topcoder** [comment]
Yes - I would expect the system to show results per each filter. If I'm in "active" and search, I don't want to see results for All, but just the active tab I'm in.

If there are no results in the tab, the message to go to All projects tab and/or change search criteria would be really helpful.

**Comment by vikasrohit** [comment]
Cool.
> If there are no results in the tab, the message to go to All projects tab and/or change search criteria would be really helpful.

**Comment by vikasrohit** [comment]
@rmjmccormick Could you please suggest a copy for following situation?
> If there are no results in the tab, the message to go to All projects tab and/or change search criteria would be really helpful.

**Comment by rmjmccormick** [comment]
@vikasrohit how about the below?

No results found based on current search criteria. Please modify your search criteria and/or search across all projects by selecting the "All Projects" filter.

**Comment by vikasrohit** [comment]
👍
@gondzo please open it for pickup if we haven't handled this in our private tasks.

**Comment by gondzo** [comment]
We should just show the suggestion message if there are no search results (we did fix the search api, but still, if there are no results for a specific phase, this suggestion would be helpful)
`No results found based on current search criteria. Please modify your search criteria and/or search across all projects by selecting the "All Projects" filter.`

**Comment by jankyzhang** [comment]
I am working on this - please assign when provided access.

**Comment by vikasrohit** [comment]
@jankyzhang thanks for the PR. Could you please also make the `All Projects` text in the message, a hyperlink clicking on which would select the `All Projects` tab.

**Comment by jankyzhang** [comment]
@vikasrohit , 
Thanks for the reply . 
I fix it right now .

**Comment by jankyzhang** [comment]
@zjuasmn Please add the "Ready for Review" label. 
I cant assign myself.
Thanks
