### ISSUE TITLE
[$50] Notifications drop-down should work at all times (even if there's no data)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1958]
I should be able to see the notifications UI loading even if there's no data. If there are no messages or error, we should display a message in the notifications drop-down/page/mobile view, not throw errors.

Right now if there are no notification messages, I can't use the interface anywhere.

**Comment by mfikria** [comment]
I am working on it

**Comment by zjuasmn** [comment]
@vic-topcoder Cannot reproduce issue. It works on latest dev branch
![image](https://user-images.githubusercontent.com/4462778/42322074-a4685bc2-808d-11e8-9392-86e194b768c4.png)

**Comment by vic-topcoder** [comment]
If you block the notification server, or disable the data, the notifications menu isn't rendered. This is dependency that causes the interface to shift when the notification service is back online, as then suddenly the notification icon is rendered on the top bar. The ticket tries to deal with that rendering issue.
