### ISSUE TITLE
New project incomplete message

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1959]
@gondzo 
There is no design for the message which is shown when project creation wasn't finished.
So I've adopted existent desktop design using styles from other mobile pages. Please, let me know if you would like to make any changes.

The existent desktop version can be seen here https://connect.topcoder-dev.com/new-project/incomplete

Mobile portrait:

![image](https://user-images.githubusercontent.com/146016/39031512-466e8c9a-449b-11e8-95f4-d67dd864efce.png)

Mobile landscape:

![image](https://user-images.githubusercontent.com/146016/39031520-54313ed6-449b-11e8-946c-4c0b00d94605.png)

**Comment by RishiRajSahu** [comment]
That's fine with me. just take care of the connect logo we show on desktop version on this page.

@vic-topcoder please provide your view.
