### ISSUE TITLE
Notifications clarifications

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1962]
@RishiRajSahu @vic-topcoder 

1. Do I understand it correctly that provided screens of notifications for mobile are for dropdown which is openned when we press notification bell at the topbar. For mobile we don't have a separate page with all notifications, or have? See the next question.

2. What should happen when a user pressed **Read all notifications**?

    ![read-all-not](https://user-images.githubusercontent.com/146016/39037685-c73dbcb6-44b3-11e8-9e87-b3b44183d714.png)

3. Which of these screens should be shown when there are no notifications?

    ![image](https://user-images.githubusercontent.com/146016/39037737-f58f0c3c-44b3-11e8-83d3-42e36b3ba1e7.png)

4. There some differences in notification settings pages, which probably has to be unified:

     ![notification-settings](https://user-images.githubusercontent.com/146016/39037970-b844b7cc-44b4-11e8-8eeb-e0fd0078c4bd.png)

    a) text sould be shown from Desktop version?
    b) world icon can keep from the Desktop version?
    c) for switch we use existent component from [react-components/components/SwitchButton](https://github.com/appirio-tech/react-components/tree/feature/connectv2/components/SwitchButton), should we keep it?
     d) bottom line is solid in Desktop, should I use same solid line for mobile here?
     e) link has underline on Desktop, as we don't use underline usually, should I remove underline for Desktop same like for mobile?
     f) for mobile there is standard big button, should I make same for Desktop?

**Comment by RishiRajSahu** [comment]
1. Yes point 2. image is to be used when clicking bell icon.
2. Let's have text as 'View all notifications' similar to desktop, and on clicking it point 3. right image will open, with top area similar to image posted in point2.
3. Left one
4. a.Yes
b.Yes, desktop one
c.use existing
d.use desktop one
e.use desktop one
f. use mobile one i say

**Comment by vic-topcoder** [comment]
**For p1 and p2**: On mobile we should have only one notification center - the current screen should behave as the full experience as it makes no sense to have a double experience - minimal and full. Thus I'd expect the "Read all" not to be on the screen, but load the full list of the notifications with the "read older notifications" at the bottom of the sections when we have them.

**p3**: The screen on left.

**p4**:
> a) text sould be shown from Desktop version?

yes
> b) world icon can keep from the Desktop version?

yes
>c) for switch we use existent component from react-components/components/SwitchButton, should we keep it?

Most definitely. No changes
> d) bottom line is solid in Desktop, should I use same solid line for mobile here?

Do not modify the style from Desktop. If there's a style established, and design doesn't match, the code style takes precedence in general.

> e) link has underline on Desktop, as we don't use underline usually, should I remove underline for Desktop same like for mobile?

We rarely use underline in our links. This is a consistency question - let's remove the underline.

> f) for mobile there is standard big button, should I make same for Desktop?
Use the button style from Desktop

**Comment by vic-topcoder** [comment]
Seems like this isn't implemented/updated yet. Right now notifications are very hard to use on mobile, since I have to click on "read all notifications" which loads the screen, and I still see old notifications, that I have to click again in order to read.

What is the desired experience on mobile:

When I tap on the notification icon, I should see ALL notifications (notification center view) and not the drop-down screen that leads me to ALL notifications. 

On the ALL notifications screen (notification center) I should always see the last 10 notifications for each project. Right now older notifications are hidden even there are no 10 newer notifications. This must be fixed for all devices.

Tapping on a notification should also dismiss the notification (as I've seen the target, hope we can trigger "seen" from the target and dismiss the notification).

**Comment by gondzo** [comment]
Correct @maxceem - all notifications are displayed when clicking the bell icon, no need to go into notifications center

**Comment by maxceem** [comment]
> Tapping on a notification should also dismiss the notification (as I've seen the target, hope we can trigger "seen" from the target and dismiss the notification).

@vic-topcoder This behavior shouldn't depend on the mobile/desktop view and suppose to already work. I've tried a few notifications and it works for me. Do you have any particular case, which doesn't dismiss the notification when clicking them? Probably it makes sense to create another issue if there is such a case.

**Comment by vic-topcoder** [comment]
I'll have to check again, but last time notifications were not dismissed after opening the target.
