### ISSUE TITLE
New project: form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1963]
@RishiRajSahu @vic-topcoder 

1. On the mobile design create project form there are much more fields, than currently for Desktop.

   Desktop:

   ![image](https://user-images.githubusercontent.com/146016/39044491-dacec950-44c2-11e8-8105-35328590d8b1.png)

   Mobile:
   
    https://marvelapp.com/chdbdcj/screen/41458519

   What is way go to here?
   
   a) on mobile show same fileds as on desktop now (I'm going with for now)
   b) on mobile show more fields, on desktop same as now
   c) on mobile show more fields, and add more fields for desktop

**Comment by maxceem** [comment]
2. On mobile design there are no button to go back/cacnel of creating a new project. Is that correct?

    Desktop has BACK and ESC buttons:

    ![image](https://user-images.githubusercontent.com/146016/39044750-ab1b80f8-44c3-11e8-9a4f-28253a3c2166.png)

    Mobile doesn't have any:

    ![image](https://user-images.githubusercontent.com/146016/39044797-c81f40ae-44c3-11e8-9cc7-a231a39a51b2.png)

**Comment by vic-topcoder** [comment]
The mobile design actually shows the conversion of the elements in this case - how all types of components would fit within mobile interface. The one form is not designed to replace the existing elements.

The content on Desktop should dictate the conversion, using the design as a guide on how each element type converts. Does that make sense to you @maxceem ?

**2.** Let's add the back button as arrow without label only. That's the style conversion - just use the icon (close, back arrow).

**Comment by maxceem** [comment]
1. Makes sense, thank you.

**Comment by maxceem** [comment]
2. @vic-topcoder  I'm not sure what is best place for the BACK button. Could you please advise:

   a) Standard position like other pages 10px from left, 10px from top:

    ![image](https://user-images.githubusercontent.com/146016/39080445-54348b56-4561-11e8-95a6-cc44c00529b9.png)

   b) Adjust for the current page: 20px left and vertically align with header.

     ![image](https://user-images.githubusercontent.com/146016/39080456-8b8774a6-4561-11e8-83d0-3447838c9b86.png)

    c) Same like b) but on the right side:

      ![image](https://user-images.githubusercontent.com/146016/39080463-bc1f945e-4561-11e8-8001-46a41c6b7ffc.png)

**Comment by vic-topcoder** [comment]
Option b looks the best! Thanks
