### ISSUE TITLE
New project: form on tablet

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1964]
@RishiRajSahu @vic-topcoder 

For the create new project form. There are mobile designs for screens < 768px.

![form-tablet-min](https://user-images.githubusercontent.com/146016/39049177-f2701acc-44d2-11e8-9df6-7c94004aef98.png)

And currently, this form supports screen sizes >= 1040px.

![image](https://user-images.githubusercontent.com/146016/39049205-1e42b042-44d3-11e8-81f0-39e1b76e35b6.png)

What I do here is let page shrink until 992px (this value is used at some other places). And from the 992 until 768 I hide the right column.

See the video: http://take.ms/6F61y

Let me know if you prefer another behaviour.

**Comment by vic-topcoder** [comment]
agreed
