### ISSUE TITLE
New project: form, required fields

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1966]
@RishiRajSahu @vic-topcoder 

At mobile design required fields are marked with red asterisks, while at existent desktop designs - no.
Probably it's better to unify this. What is the best way?

Mobile 

![image](https://user-images.githubusercontent.com/146016/39049760-60f7bc6e-44d5-11e8-8f77-95479d6e567a.png)

Desktop 

![image](https://user-images.githubusercontent.com/146016/39049775-7185e09c-44d5-11e8-83e1-3d6caf69e6d6.png)

a) follow desktop design everywhere **without** asterisks
b) follow mobile desgin everywhere **with** astersks
c) keep desktop without asterisks, while adding asterisks on mobile

**Comment by vic-topcoder** [comment]
Asterisks should be show on all required fields, regardless of device. Not sure if the fields in the mobile design are "required" in the form. @vikasrohit please chime in.

**Comment by vikasrohit** [comment]
I think we need to add the asterisks to desktop version as well.
