### ISSUE TITLE
New project: slider select

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1968]
@RishiRajSahu @vic-topcoder 

There is component from `react-components` which doesn't have mobile design provided and doesn't fit mobile screens as it is.

Minimal mobile screen `320px` (iPhone 5):

![image](https://user-images.githubusercontent.com/146016/39080539-44388ed0-4563-11e8-8ad0-b7e686a05f0d.png)

Regural mobile screen `375px (iPhone 6/7/8):

![image](https://user-images.githubusercontent.com/146016/39080547-63bb28ee-4563-11e8-9981-c00b5c3a5e5b.png)

I may restlye to something like this (screen 320px)

![image](https://user-images.githubusercontent.com/146016/39080691-9712a0de-4566-11e8-97bb-981b61635e1a.png)

**NOTE**
This component comes from [react-components/../SliderRadioGroup.jsx](https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Formsy/SliderRadioGroup.jsx). It's implemented using third party [rc-slider](https://www.npmjs.com/package/rc-slider) but use it almost as a static picture, allmost all interactions are disabled.

I can just overwrite its styles.
Or as `rc-slider` isn't fully used, it could make sense to rewrite this component without `rc-slider` just using CSS styles and simple logic in component. Also, removing `rc-slider` and its dependencies will save 24kb gzipped https://github.com/appirio-tech/connect-app/issues/1629.

![rc-slider](https://user-images.githubusercontent.com/146016/39080613-abdbb764-4564-11e8-81c7-bb147a65aee7.png)

**Comment by vic-topcoder** [comment]
I was thinking to replace this slider to be just a radio group, as in a mobile view you can see 4 radio selects one under the other. A slider doesn’t make sense in mobile context. If you can contextually render the slider as radios, in a group, that’ll be the best. 

If it isn’t possible, the last style you suggested is the best option indeed!
