### ISSUE TITLE
Notifications dropdown logic

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1969]
@vic-topcoder @gondzo 

Notifications dropdown especially for mobile currently have quite intricate logic, not sure if it still desired behavior.

1. First, we show not more than `5` notifications per source in the desktop dropdown, and the same approach I use for the mobile dropdown. And we don't show **view older notifications** for sources, only one global button **Read all notifications**.
    
   ![read-all](https://user-images.githubusercontent.com/146016/39094487-d02c1236-4662-11e8-8c23-4aa115ec21c6.png)

2. When user presses **Read all notifications** button. We show user `all` notifications per source, but not old. And if some source has old notifications button to view old notification for source appears.

   ![view-older](https://user-images.githubusercontent.com/146016/39094535-909163e6-4663-11e8-909d-4d3e019fb11e.png)

3. Finally user can press **view older notifications** button, to see old notifications for particular source.

   ![view-older-open](https://user-images.githubusercontent.com/146016/39094539-a4eb0eb4-4663-11e8-8694-0994a63d6207.png)

4. Currently OLD notifications are filtered not by time (like not older than 2 days), but just not more 10 per source. So first 10 messages per source are treated as new, and the rest is old. I've fixed it to use date instead, is that correct?

5. As we don't show old notifications in dropdowns by default there could be situataion, when all notifications are old but we have some unread. So we don't show "Empty" message, but also don't have notifications to show. Only show "View older button". How the best to deal with it?

   ![empy-old-desktop](https://user-images.githubusercontent.com/146016/39094604-7cbfc942-4664-11e8-836c-2e1fe8dd1651.png)

    ![empy-old-mobile](https://user-images.githubusercontent.com/146016/39094611-96bb871e-4664-11e8-9dbc-018b9bea191b.png)

   In mobile dropdown we can press **Read all notifications** and will see the next:

    ![image](https://user-images.githubusercontent.com/146016/39094708-8fbbd5f2-4666-11e8-9f4b-5972a349d43d.png)

6. In mobile dropdown there is the button **Read all notifications**. When user press it and we show to the user all notifications. How long this decision should stand? Until page reload, page change (no real reload), dropdown open/close.

7. Realated question for **View older notifications**. When user press it, how long we have to show them opened? 
    For example on notifications page, we show notifications which user already opened, until user reloads page in the browser
   
    ![image](https://user-images.githubusercontent.com/146016/39094671-0059fc90-4666-11e8-9165-2fc3a80a5d34.png)

**Comment by RishiRajSahu** [comment]
1,2,3 are the functionality already agreed upon.
4.Have you already changed it ? what should be the definition of new and old as per your new logic, could you please share the source link ?
5, 6 @vic-topcoder should be the right person to decide on this.
7. Are you suggesting something like notifications getting erased once the user has marked it as read ?

**Comment by gondzo** [comment]
@maxceem for 1-5 we don't need the old vs new logic at all, only these rules:
- dropdown shows 5 newest notifications per source
- notifications center shows 10 latest notifications per source. clicking view older will show all notifications for that source.

for 6-7 there is no need to retain state for clicks on the 'view older'/'read all' link. if user navigates away and comes back to notifications center, again show the 10 notifications per source.

**Comment by maxceem** [comment]
@gondzo do I understand it correctly that there is no need show **Read All Notifications** link on mobile?

![](https://user-images.githubusercontent.com/146016/39037685-c73dbcb6-44b3-11e8-9e87-b3b44183d714.png)

There is also related comment from **vic-topcoder** https://github.com/appirio-tech/connect-app/issues/1962#issuecomment-385578219.

**Comment by gondzo** [comment]
Right, we'll show the full notifications list (as in the notification center)

**Comment by maxceem** [comment]
@gondzo It looks like when we click the bell on mobile, we actually show notification center page adopted for mobile. As notification center page for desktop has the same logic as now we implement for mobile technically it makes sense to adopt desktop page rather then adopt dropdown as were done before.

The URL will be also changing when we click the bell on mobile.

Is that ok if I go with this approach?

**Comment by maxceem** [comment]
@gondzo ok, I see a downside if we go to the separate page. If we close notifications center on mobile, we have to go to the proper page back. Also some states could not persist, so it could really feel like going to another page rather then open/hide panel like it's done now. So I keep the current approach so far.

**Comment by maxceem** [comment]
@gondzo One more thing, `/notifications` page so far cannot be reached from mobile, but if we open it by direct link, it's not adopted for mobile. So the question if we just should redirect a user to the notification center page and adopt it still stays.

**Comment by gondzo** [comment]
It's fine the way it is now, no need to adapt to small screens as the page isn't reachable except by direct link
