### ISSUE TITLE
My project link on mobile

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1972]
@vic-topcoder @gondzo 

There is **My projects** link on mobile:

![image](https://user-images.githubusercontent.com/146016/39122356-393ce6e6-4727-11e8-9c95-caf3dd819380.png)

Where should it lead to? Should it behave like an ordinal link or like a switch, similar to desktop:

![image](https://user-images.githubusercontent.com/146016/39122398-613c36d8-4727-11e8-9350-e24bad9c504b.png)

For now I just make it an ordinal link which leads to All Projects which belongs to the current user: `/projects?memberOnly=true&sort=updatedAt%20desc`.

Though there is some unclear behavior appears.
- If user clicks this link on mobile, then we go to URL `/projects?memberOnly=true&sort=updatedAt%20desc` with param `memberOnly=true`
- now user doesn't have a way, to remove this param. If use continue applying any other filters, they will be always added to `memberOnly=true`, so filter by My Projects will always stand

Two ways of solving which comes to my head also have some downsides:
- Make **My projects** link work not like link, but like a switch in mobile menu, so we can toggle it, though by design it's not intuitive
- Try to remove this param`memberOnly=true`on mobile device if other filters are apllied, but this behavor will be different from desktop experience than. As on desktop when we apply other filters ther are combined with **My projects**.

**Comment by vic-topcoder** [comment]
This should be "All Projects" instead of My Projects" `https://connect.topcoder-dev.com/projects`. Good catch!
