### ISSUE TITLE
Project specification: submit for review on mobile

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1974]
@vic-topcoder @gondzo 

1. On the project specification page, there is submit for review block which has two designs. Which design to follow, or what is the idea behind?

    ![image](https://user-images.githubusercontent.com/146016/39168549-e24f6cfa-47c6-11e8-8f80-a2e763057238.png)

2. On the desktop this block just has a text and button, unlike mobile which provides the summary information. Probably this has to be unifyed. Which way to make it, mobile or desktop?

    Desktop view:

    ![image](https://user-images.githubusercontent.com/146016/39168617-21493300-47c7-11e8-998d-b92847dc131e.png)

3. I'm not sure that duration and budget are already properly calculated. As I only can see it 0 or undefined in the state so far.

    ![budget](https://user-images.githubusercontent.com/146016/39168879-228802b8-47c8-11e8-9586-3bc12d769554.png)

**Comment by RishiRajSahu** [comment]
1. We need both design, right side one is used when the user is scrolling the page.
2. Showing project estimate is already there for desktop as well, try creating some design project on dev you will get it. So both desktop and mobile are in sync with respect to showing project estimate.
3. We are static values from JSON file https://github.com/appirio-tech/connect-app/blob/master/src/config/projectWizard/index.js#L94 it doesn't depend upon the fields present in the project object which you mentioned.
