### ISSUE TITLE
Project specification: features don't have mobile designs

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1975]
@vic-topcoder @gondzo 

On the specification page there is big UI component to add features which looks like this:

![image](https://user-images.githubusercontent.com/146016/39169027-b0dad630-47c8-11e8-871c-6273ec9e151b.png)

To open it you can go to this project specification https://connect.topcoder-dev.com/projects/4852/specification and click **Add / Edit features** button:

![add-feature](https://user-images.githubusercontent.com/146016/39169086-ed176cbc-47c8-11e8-9fc0-eca88e649e9c.png)

Mobile designs for this feature are not provided and I don't see an easy direct way to adjust it for mobile, could you please advise here?

**Comment by gondzo** [comment]
that feature will be deprecated and we don\t need it on mobile. can we just show a message that editing features isn't supported on mobile?

**Comment by maxceem** [comment]
Yes, I will show some message on mobile.
