### ISSUE TITLE
specification: not able to delete custom feature 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#198]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create project
4. go to Specification
5. Feature requirements
6. add/edit feature 
7. create custom feature
8. delete custom feature

Expected Result: must be delte feature
Actual Result: Not able to delete 

Enviroment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18928419/a3672a48-85dd-11e6-85d4-61684b1c1ad0.png)

**Comment by vikasrohit** [comment]
Fixed with #125
