### ISSUE TITLE
Fix sorting for notifications

### ISSUE THREAD

**Issue by mtwomey** [appirio-tech/connect-app#1980]
When a user views his notifications in Connect, the notifications are "grouped" by project. These should be sorted as follows:

1. The Projects themselves should be ordered as follows: The project that has the most recent notification should be on top.
2. Within a given project, the notifications should be ordered from most recent to oldest.

**[Example of the notification area I'm referring to - not currently ordered correctly]**
![image 3](https://user-images.githubusercontent.com/7715262/39440595-f8240424-4c70-11e8-9ea8-fd68c5547a8c.png)

**Comment by gondzo** [comment]
This is now fixed
