### ISSUE TITLE
Card views in mobile view should be tappable, not only their title

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1981]
### Expected behavior
I want to load the project details when I tap on the card, not only on the title

### Actual behavior
Project loads only when I tap on the project title.

**Comment by maxceem** [comment]
@vic-topcoder this was previously discussed here: https://github.com/appirio-tech/connect-app/issues/1922#issuecomment-377677075 see the item 13

The main reason of making it this way:
> There is some difficulty in using project list in card view. If we open project status dropdown, and after want to close it, we have to click somewhere. But as full cards are links there is almost no space to click without proceeding to the project details page.

![](https://user-images.githubusercontent.com/146016/38161454-7370dd64-3501-11e8-8b8e-523c83f36e07.png)

**Comment by vic-topcoder** [comment]
I would use the "Project Status" title as a dismissible trigger, and add a close icon on the menu, or just disable the project status change on the card, but leave it only on the project dashboard. The goal is for our customers (who can't change status at all) to be able to use the cards to navigate to their project(s).

**Comment by maxceem** [comment]
Ok. I've disabled status change on the cards view.
