### ISSUE TITLE
Project status is missing in mobile view

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1990]
There's no project status icon in mobile view. There's space on the right, but nothing gets rendered. Either remove the space, or show the status icons.
![img_0024](https://user-images.githubusercontent.com/8484061/39556355-a83027c0-4e34-11e8-83ba-ce1617dea5a0.png)

**Comment by RishiRajSahu** [comment]
@vic-topcoder yeah we missed this in designs as well. Should the status icon be lower right corner or should be aligned with project name ?

**Comment by vic-topcoder** [comment]
There's only need for a project status in several cases:
1. Listing all projects - the status icon helps to identify current project status
2. Changing project status directly from the project grid.

Those cases are not that often and on mobile we can actually better use the space on the right to list more details. I would say - remove the space on the right (in red) and allow the card to flow freely. Also - reduce the space between the filter drop-down and the list.

**Comment by RishiRajSahu** [comment]
okay, got it that just the extra space on the right is to be removed. did i got it right ? what you mean't by free flow, does this means allowing text to free flow ?

**Comment by vic-topcoder** [comment]
Yes, that's right.

**Comment by RishiRajSahu** [comment]
1.Removed extra space on right from project-grid in mobile view. 
2.Removed extra space between the filter drop-down and the list.

Changes deployed to dev.
