### ISSUE TITLE
"Error Page" and "Welcome Page" pages to be made responsive

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#1992]
### Expected behavior
Error page on connect should be responsive.
Welcome Page/No Projects page should be responsive

### Actual behavior
Describe.

### Steps to reproduce the problem
- On Mobile, Create a new connect user and login, Unresponsive welcome page will be rendered

### Screenshot/screencast
<img width="368" alt="screen shot 2018-05-07 at 6 22 12 pm" src="https://user-images.githubusercontent.com/11248478/39702821-a3bb0136-5223-11e8-95f5-11ae531db986.png">

![no_projects_page](https://user-images.githubusercontent.com/11248478/39702693-4d31735e-5223-11e8-8639-0725f7aaaa8f.png)

**Comment by vic-topcoder** [comment]
Assign to DaraK for quick design and let's keep pounding on them. The Community is doing a great job so far!

**Comment by RishiRajSahu** [comment]
Done ! merged to dev - https://github.com/appirio-tech/connect-app/pull/2008
