### ISSUE TITLE
[$50] Created post by non-member of the project breaks posts feed

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1994]
### Actual behavior
If we create a post in some project by the user, who is not a member of the project (like admin), then:
- the created post is not displayed after posting looks finished
- if we reload the page, posts feed will be never loaded, see for example https://connect.topcoder-dev.com/projects/4963
- there is an error in console which prevents loding:
   ```
    Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'user.firstName')
   ```

![non-member-post](https://user-images.githubusercontent.com/146016/39954385-2147a700-55f1-11e8-8c9a-0b85bafd4d62.png)

### Expected behavior
Possible fixes:
- don't let a user create posts or make comments unless he is a member of the project
- fix the bug, so if some post is created by non-member, posts have to be still loaded. Also, this could make sense, if some user were a member, created a post and left the project. So this bug has to be fixed anyway.

### Possbile fix
I think the reason of the issue is that we only get informatino about members of the project, and we try to display a post from the non-member user, there is no data for him loaded which causes the error.

#### Environment
- Account used: suser1

**Comment by andela-jomadoye** [comment]
@mhikeo @gondzo @vic-topcoder @maxceem 
Please what is the password for the suser1 User?

**Comment by gondzo** [comment]
I've posted test user accounts in challenge forum
