### ISSUE TITLE
Implement secondary tool bar with menu component from component library

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1997]
Please, confirm if I understand correctly the task regarding secondary tool bar:

![image](https://user-images.githubusercontent.com/146016/40158289-32d74744-59d6-11e8-8db0-f0cb4d1c5413.png) 
from https://marvelapp.com/8a94680/screen/41372266

1. Roues for tabs:
    - Dashboard `projects/1234`
    - Scope `projects/1234/scope`
    - Project Plan `projects/1234/plan`

2. **Dashbord** leads to the current dashboard without changes for now.

3. **Scope** is a dead link for now.

@RishiRajSahu @gondzo

**Comment by RishiRajSahu** [comment]
1. 
    - Dashboard `projects/1234` - route is fine
    - Scope `projects/1234/scope` fine
    - Project Plan `projects/1234/plan` fine

2. **Dashbord** Use this prototype https://marvelapp.com/8a94680/screen/41500618 (Exclude channels, new team members view, unread/recent/oldest filter for post)
3. **Scope** is a dead link for now. - NO, use basic questions as described to you by gondzo.

**Comment by maxceem** [comment]
4. Our existent primary toolbar sticks to the top and always visible during scrolling. What is expected behavior when we have a new secondary toolbar? Should secondary toolbar be always visible during scrolling or be scrolled together with content?

**Comment by RishiRajSahu** [comment]
4. Let's keep it scrollable with content.

**Comment by RishiRajSahu** [comment]
Secondary toolbar is in place, for the missing functionality created the separate issue #2064
