### ISSUE TITLE
Project Plan tab

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1998]
Questions regarding Project Plan page:

![image](https://user-images.githubusercontent.com/146016/40158506-7cdb4524-59d7-11e8-9a60-3b8f8bac391d.png)

1. Should the left sidebar be implemented?

2. As we don't have API yet: 
    2.1. I can output to phase posts ALL posts of the project for now
    2.2. I can output to specification tab the same specification of the project
    2.3 The rest data will be mocked for now

cc @RishiRajSahu @gondzo

**Comment by RishiRajSahu** [comment]
Closing as it's implemented and pushed to dev.
