### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#1999]
As I see there will be quite big changes in project structure.

Do I understand it correctly, that we will keep backward compatibility, so old project has to be displayed as they are?

This will include:
1. Adjusting secondary top bar with the next list of tabs:
    
    ![image](https://user-images.githubusercontent.com/146016/40163698-12a692e0-59ea-11e8-8a61-2a71a82f6568.png)

2. All these tabs has to display same pages as they are now. So all according actions/reducers/containers/components should be left untouched. And if any are required for the new approach, they probably have to be reimplemented to not mingle with the old ones. Unless they can be reused without changes.

cc @RishiRajSahu @gondzo

**Comment by RishiRajSahu** [comment]
I think there is no need of having old navigation back for old project we can simply keep these navigations in new secondary tool bar and add discussions tab there only, though we have to modify logic in code to render old data in new UI. will discuss more about this offline on slack
