### ISSUE TITLE
New dashboard page

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2000]
Question regarding new dashboard page https://marvelapp.com/8a94680/screen/41500618

1. **Channels** in the left bar skip for now.

2. **Links**  in the left bar. Should we use new style or old? Can we still edit links here?

3. **Topcoder members list** in the left bar. Should we display? If yes using old style for memebers or new?

4. **Project team** in the left bar, display with old style or new?

5. **Work in progress** shows mocked data for now.

6. **View all** link next to **Work in progress** follows to **Project Plan** tab, right?

7. **Posts** has to be displayed with the new styles without unread/recent/oldest filters for now, correct?

8. **Final Deliverable** showed with the same components as posts but and use some mocked data.

cc @RishiRajSahu @gondzo

**Comment by RishiRajSahu** [comment]
1.yes, skip for now
2.new style and editable
3.leave it as old style
4. 3 & 4 will be implemented together later, will update you on this.
5. as for old project which are active there will always be a single stage and that will be shown here as WIP
6. Right
7. Correct
8. its using the same component as 7, does this answers your query ?
9. Layout should be with respect to the new design, stick to left

**Comment by maxceem** [comment]
10. The left column now looks quite high https://marvelapp.com/8a94680/screen/41500618. Do I understand it correctly that it doesn't have to stick to screen anymore when we scroll? So it will be scrolled together with the main content?

**Comment by maxceem** [comment]
9. So on the big screen it will look like this, correct? (design inside columns will updated of course)
    
     ![image](https://user-images.githubusercontent.com/146016/40224828-ec318afe-5ab9-11e8-8cac-d759841fb8cb.png)

**Comment by maxceem** [comment]
11. **Project in Topcoder Direct** and **Saleseforce Lead** are not presented in the new design. Should they be removed? 
      ![image](https://user-images.githubusercontent.com/146016/40225824-b6b54ad4-5abc-11e8-9b5c-ed2f9776b30d.png)

**Comment by vikasrohit** [comment]
11. No they should not be removed and remained as is.

**Comment by RishiRajSahu** [comment]
10. Yes, scroll it with the screen
9. So on the big screen it will look like this, correct? (design inside columns will updated of course)
    - Agree, just take care of the extra space aside the topic cards.

**Comment by maxceem** [comment]
11. > Agree, just take care of the extra space aside the topic cards.
   
     Not sure I get you. Which space are you talking about? Should topic cards be fluid like this?
    
     ![image](https://user-images.githubusercontent.com/146016/40228358-a666f824-5ac3-11e8-99be-476a7d4f940a.png)

**Comment by vic-topcoder** [comment]
The cards should be static max size as per design; expanding them would not help the user to navigate better or improve the readability, on the contrary, it'll make the lines way to long to comfortably read.

The sidebar should keep the current behavior - when it is taller than the viewport height, please scroll the content until the footer is shown, and make it sticky. The goal is to avoid visual gaps.

The secondary tabs should be above the content - there's the drop shadow at the bottom - and ideally we can make it fixed at the top, so people can navigate between the project pages easily. If the page is too long, they have to scroll back to the top before navigating away.
