### ISSUE TITLE
New Dashboard: Posts

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2003]
1. How user can create a new topic on the dashboard?

   Currently it's done like this:
    
   ![image](https://user-images.githubusercontent.com/146016/40265447-f69d0cbe-5b6a-11e8-84fd-2614141b59a7.png)

   In the new design I cannot recognize how to create a new topic: https://marvelapp.com/8a94680/screen/41500618

2. Is there a way to edit/remove existent topic.

    Currently we have edit icon to edit/remove topics:
     
     ![image](https://user-images.githubusercontent.com/146016/40265469-6eb78a44-5b6b-11e8-9fbe-07a0ab5a7448.png)

    So user can edit both the title and comment:

     ![image](https://user-images.githubusercontent.com/146016/40265477-8861b294-5b6b-11e8-928f-aa85c93fafe7.png)

    Also user can remove the topic if there are no comments yet.

    Is it still posibble in the new design? https://marvelapp.com/8a94680/screen/41500618
    I see there a way to edit/remove comments but not the topic title.

cc @RishiRajSahu

**Comment by maxceem** [comment]
3. Currently, first comment which comes with the topic title is displayed in a special way:

    ![image](https://user-images.githubusercontent.com/146016/40265525-80ace70c-5b6c-11e8-8b24-361a0c5b7a19.png)

   In the new design, there is no place to make the first comment special. Should be the first comment displayed together with the rest of comments?

    ![image](https://user-images.githubusercontent.com/146016/40265539-f225f2a2-5b6c-11e8-9ac4-215621c30581.png)

**Comment by vikasrohit** [comment]
1. Please keep the same new topic box in new design as well. We don't need to alter that for first release.

2. In new designs body of the topic is kept as separate post which is what our message api supports as well. Can you please put the edit icon just next to the topic title and allow inline edit there? We can improve this later on with feedback from Victor.

3. Yes, your understanding is correct. And our API, in fact, does not tightly couple the body of the topic from the topic itself.

**Comment by maxceem** [comment]
4. In the current code of posts output, there is a line which is supposed to output project specification next to posts https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/FeedContainer.js#L466. 
   To this code to be ever called some topic has to have `spec` property though for me it never has it
   
    ![topics-no-spec](https://user-images.githubusercontent.com/146016/40404814-5b452ef2-5e8c-11e8-9cbc-b39f8b661cf3.png)

   I'm going to remove this line and `ProjectSpecification` component with its dependencies as it is only referred here.

   Do you know any conditions I'm missing when such component has to be outputed?

   cc @RishiRajSahu

**Comment by vikasrohit** [comment]
I am also unable to recall it. Please remove it as I don't think it make sense to have project specification in feeds.

**Comment by vic-topcoder** [comment]
> How user can create a new topic on the dashboard?

Let's stick with the current model for the time being. We haven't had the opportunity to discuss or explore channel management in depth for the time being.

> Is there a way to edit/remove existent topic.

What Vikas already said - use the pencil and x-mark icons from our existing styles at the top right portion (moving the post count to the left) on hover.
![screen shot 2018-05-25 at 2 01 07 pm](https://user-images.githubusercontent.com/8484061/40566136-1fa43304-6024-11e8-8191-bfc57ab663e6.png)


> Should be the first comment displayed together with the rest of comments?

No, this is one of the issues with our current design. Keeping the first post in the channel/topic quickly loses contextual value in long/older communication threads.

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder for the updates. However, in the last section @maxceem wants to confirm that if we need to show the first post of the topic as regular post of the topic which scrolls normally like other posts which is something you are also trying to convey. So, I think we all are saying same thing which is NOT to render the first post of the topic as topic body and rather show it as a regular post which scrolls like other posts.

**Comment by vic-topcoder** [comment]
@vikasrohit correct.

**Comment by maxceem** [comment]
1. We have some dropdown menu to edit/delete comments

    ![comment-edit](https://user-images.githubusercontent.com/146016/40701722-97de8afe-6411-11e8-8c3c-2b9844ea80fc.png)

   Dropdown looks like this:

    ![image](https://user-images.githubusercontent.com/146016/40701882-44d3945c-6412-11e8-9d81-2be2bcdfbe73.png)

   What do you think about reusing this approach to post topics? Rather than showing edit and delete buttons, show the same three dots button with dropdown menu.
