### ISSUE TITLE
Filter by project type

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2006]
Currently, we can filter by project type. And I'm trying to understand where it will come from the DB.
Note, that we need here human readable title for project type together with project type id.

![image](https://user-images.githubusercontent.com/146016/40276904-f3df9a72-5c47-11e8-9973-094a5cc86eda.png)

In the new `project_templates` schema there is a `category` property which maps to project type:

![image](https://user-images.githubusercontent.com/146016/40276914-1f42018c-5c48-11e8-8f55-95beb84139b3.png)

Though I have concern here. 

1. Does `category` property should map to human-readable project type or project id:

    ![category](https://user-images.githubusercontent.com/146016/40276938-84a6fb54-5c48-11e8-8e09-e726312a26e6.png)

2. If `category` maps to id how to get title? Or if maps to title, how to get id? I think we don't wanna store this mapping in the source code, otherwise we will have to update it all the time. So both project type title and project type id has to be stored in DB somewhere.

cc @RishiRajSahu

**Comment by maxceem** [comment]
The same questions other words:

1. What should `category` in `project_templates` contain? Project type **id** or project type **title**? See screenshot:
   
    ![](https://user-images.githubusercontent.com/146016/40276938-84a6fb54-5c48-11e8-8e09-e726312a26e6.png)

2. For project filters we need to know all possbile project type ids and project type titles:

    ![](https://user-images.githubusercontent.com/146016/40276904-f3df9a72-5c47-11e8-9973-094a5cc86eda.png)

    We use project type titles to show items of the filter for users. And we user project type ids, to create a filter query to the DB when user pick some filter. So each project type has to have both id and title for human.

    Where these values will comes from? So far they are stored in json, but as want to get all data from DB they are suppose to be stored in DB.

**Comment by maxceem** [comment]
@RishiRajSahu just want to give you some thoughts to consider.

We also have `project` schema with type property `type` which corresponds to `project_category.categoryId` in the new schema, see

<img width="705" alt="type_category" src="https://user-images.githubusercontent.com/146016/40337996-5fcb68e8-5da5-11e8-9942-0c996f9884a5.png">

So it look like we have two names for the same entity `type` and `category`.
Though I don't see any easy and robust way to unify it without changing existent data. So probably to keep it current would be the best.

**Comment by RishiRajSahu** [comment]
@maxceem are you suggesting to have a same attribute name 'category' at both project_template and project ? I have planned for having `type` as `long` type to map to `project_category` table same as `category` field in `project_templates`.

**Comment by vikasrohit** [comment]
@maxceem I would like to keep it as `type` for now in projects as it would require migration for old data. We can handle that later.
@RishiRajSahu I think we should not have `long id` field in categories table. We should just keep a text id (which would be exactly what we have in projectWizard/index.js and project.type) and its display name as fields which would allow us to use the current data as is without any data migration.

**Comment by maxceem** [comment]
@vikasrohit @RishiRajSahu if we don't update `project.type` then it sounds like a good idea to keep `category` in `project_templates` same as `type` i. e. `project_categories.categoryId` and without `long id` as mentioned @vikasrohit.

Maybe even call `category` => `type` inside `project_templates` and call the `project_categorie` table `project_types`? It's just a proposition to consider. This way we keep names same across DB and don't have to do the migration.

**Comment by vikasrohit** [comment]
I am Okay with changing category => type. Nice suggestion @maxceem. Our backend is already in progress with category name, but it won't take much efforts to update it before merging it in our code base.

**Comment by RishiRajSahu** [comment]
@vikasrohit @maxceem 
i am renaming -

> table `project_category` to `project_types` , 
> `category` to `type` in `project_template`

attributes of `project_types`

> `id` - long
> `typeId` - varchar(255)
> `typeName` - varchar(255)

Revising the solution for actual concern of this git issue - 

> we will be having a separate endpoint to fetch all the rows of `project_types` table to get data for project type filter on UI.

**Comment by RishiRajSahu** [comment]
After multiple iteration of discussions we finalised on having the below schema - 
`project_types ` with attributes `key` , `displayName`
`project_templates` have `category`

There is also an endpoint in place to fetch the required data for filter by project type.

All the changes are pushed to dev so closing the issue.
