### ISSUE TITLE
Scope tab

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2009]
In general, scope tab should looks like current specification tab.

1. Should left sidebar style be adjusted to look same like new dashboard and project plan pages?
    Should be left sidebar stick to right, like https://marvelapp.com/8a94680/screen/41500618 ?
    Currently, scope tab looks like this (ignore minor visual issues):

     ![image](https://user-images.githubusercontent.com/146016/40406366-f90b5dd6-5e92-11e8-9c25-f7e2d365e663.png)

**Comment by RishiRajSahu** [comment]
As we don't have designs yet for scope, let's keep the sidebar similar to dashboard and project-plan page to be consistent.

**Comment by vic-topcoder** [comment]
> Should left sidebar style be adjusted to look same like new dashboard and project plan pages?

Yes. Ideally the frame for the whole project would follow the same structure so the user doesn't perceive any visual jump of the big elements while navigating between pages (navigation, sidebar, main content area). 
![screen shot 2018-05-25 at 2 06 33 pm](https://user-images.githubusercontent.com/8484061/40566290-de0ff0e4-6024-11e8-9ef5-219409383af8.png)

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder for the design.

@maxceem please don't worry about the UI changes in this screen. We are not focusing on that for the first release. Please use the same UI as we have today for the specification tab. We would do those UI tweaks later.
