### ISSUE TITLE
Project plan API endpoints

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2013]
1. At the dev env, `POST /v4/projects` endpoint doesn't support `version` and `key` properties 

    ![image](https://user-images.githubusercontent.com/146016/40642209-f7dcf4fe-634e-11e8-8f03-044ca6729cc2.png)

**Comment by maxceem** [comment]
2. At the dev env, `POST /v4/projects/{projectId}/phases` endpoint requires `startDate` and `endDate` though we don't define them during project creation.

**Comment by maxceem** [comment]
3. At the dev env, `GET /v4/projectTemplates` doesn't return `aliases` array. This array's first element is required to form URL during project creation.

**Comment by maxceem** [comment]
4. At the dev env, `GET /v4/projectTemplates` doesn't return `info` and `icon`. They are not critical. So I show nothing in the place of `info` and show some fallaback icon instead of real project type icon.

**Comment by maxceem** [comment]
5. **Important** Creating projects http://take.ms/Osm2e or getting project details http://take.ms/j1vHx started returning error 504 Gateway, though project list is still working http://take.ms/kTKkv

**Comment by RishiRajSahu** [comment]
@maxceem all the above mentioned issues are resolved except point 2, it too will be resolved soon use dummy dates meanwhile to stay unblocked.

**Comment by maxceem** [comment]
1. At the dev env, `POST /v4/projects` endpoint `version` is allowed now, but `key` it still returns `not allowed`.

**Comment by RishiRajSahu** [comment]
1. Instead of `key` its `templateId`

**Comment by maxceem** [comment]
![image](https://user-images.githubusercontent.com/146016/40654763-d1195362-6371-11e8-88a0-94cf0f681099.png)

6. At the endpoint `GET /v4/projectTemplates`.
    Icon contains relative path `../../assets/icons/product-cat-website.svg`. Do you think it can contain icon "id" `product-cat-website` instead, so after it is resolved in this component https://github.com/appirio-tech/connect-app/blob/feature/project_plan_v3/src/components/ProjectTypeIcon.jsx?

7. At the endpoint `GET /v4/projectTemplates`.
   `scope.sections` currently contains `sections` which are supposed to be at the `product_template` insted of shorter list of questions from`basicSections`.

**Comment by maxceem** [comment]
8. Do we have an endpoint to get `project_template` by `key` instead of `id`. The reason is that for old projects we only know `project_template.key` which is holded in `project.details.products[0]`. We don't have `templateId` property for old projects.

**Comment by maxceem** [comment]
9. Looks like dev backend got broken again:
    - I have 504 Gateway error for projects/{projectId} endpoint http://take.ms/YhirhA
    - GET productTemplates returns error http://take.ms/elI9J
    - GET projectTemplates returns error http://take.ms/Hanqy
    - also error during creating project http://take.ms/Z1xOk

**Comment by maxceem** [comment]
10. Do we have some endpoint to get `project_categories`?

**Comment by RishiRajSahu** [comment]
7.Yes, it should be `basicSections` only will update the template
8.For old projects rendering we need `sections` which are now present at product_template and we can fetch that using templateID present at project 
10.No we don't have yet, you can read it as static data from file as of now
11. is it working now? it could be side-effect of the changes going on for the project service

**Comment by maxceem** [comment]
8. > For old projects rendering we need sections which are now present at product_template and we can fetch that using templateID present at project
    
   Do I understand it correctly, that new property `templateId` will be populated for old projects?

.

11. > is it working now?

    No, still doesn't work http://take.ms/VPI9H

**Comment by maxceem** [comment]
8. > we can get it from details.products for old projects
     
    Not sure I've got you. `templateId` contains `project_template.id`, while `details.products[0]` contains `project_template.key`.

**Comment by maxceem** [comment]
12. [This is not critical, just fyi]. As we discussed with @RishiRajSahu questions in project plan which duplicate questions in the scope has to have `hidden: true` property and after will be hidden on the project plan tab.

     ![hidden-fields](https://user-images.githubusercontent.com/146016/40715067-01f23042-6437-11e8-8dbc-99e3821a8890.png)

**Comment by maxceem** [comment]
13. [Minor issue FYI] At the current project template in the `scope.sections[0].title` is empty. 

      ![empty-title](https://user-images.githubusercontent.com/146016/40758808-a9e90a48-64c1-11e8-992f-e4a20af6bb0b.png)

      This leads to header being empty and at sidebar there is no section title.

      ![no-titles](https://user-images.githubusercontent.com/146016/40758869-e8dddeea-64c1-11e8-8fc4-c8c4fdd76b34.png)

**Comment by RishiRajSahu** [comment]
@maxceem will update.

**Comment by RishiRajSahu** [comment]
Closing as all the points are covered which were asked during the development.
