### ISSUE TITLE
Base estimation at Project Templates

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2016]
Currently, some subtypes have properties with base estimations:
- `basePriceEstimate`
- `baseTimeEstimateMin`
- `baseTimeEstimateMax`

![image](https://user-images.githubusercontent.com/146016/40695048-fd8d06a2-63f1-11e8-9181-efbfa6cc6dae.png)

By logic they have to be properties of the model `project_templates`.

Should they be added to the model?

**Comment by RishiRajSahu** [comment]
@vikasrohit @vic-topcoder do we need these `base duration` and `base price` for connect-v3 as well ? With budget and duration for phase in place i don't see need for this, still need your view on this.

**Comment by vikasrohit** [comment]
@RishiRajSahu I think we would still need the logic for estimation of certain fixed priced products. I think it is more a product question now, but till we support better automatic estimation for all products, I think we need these fields somewhere in our templates which estimation component should read and show estimates.

fyi @rmjmccormick

**Comment by RishiRajSahu** [comment]
@sumitdaga we need estimation to be present on creation wizard(according to default phase-products ) and on scope page wrt all the products present for the project.

**Comment by gondzo** [comment]
As of right now, we don't have any questions that would affect estimate in phase specifications, so the only questions that affect the estimate are in project specification (create project form). Also, in phase specification tab we won't ever display any estimate so I'm not sure if it makes sense to just include that estimate in the overall project estimate?
I've added back the logic to show estimate for project.details.product[0]. Sounds good @RishiRajSahu @vikasrohit ?

**Comment by RishiRajSahu** [comment]
@gondzo i have added questions for phase which would affect the project estimate for `Visual Design` use this project for dev work http://local.topcoder-dev.com:3000/projects/6435/plan . Yes we don't show estimate in phase specifications tab but we may have questions there which can contribute to project estimate, like in the project i just shared with you. so we have to check through each phase of project to find the estimate and add that estimate to the scope page's estimate, hence show the summed up value of estimates on scope page in left area.

Hope this helps !

**Comment by maxceem** [comment]
As we are moving from hardcoded JSON files to the data which is coming from DB, there should be a place where we store:
1. project estimations which are shown during creation wizard
    Please review the first comment in the current issue https://github.com/appirio-tech/connect-app/issues/2016#issue-327548174.
    So far estimations come from hardcoded JSON which we have to remove from the source code:  https://github.com/appirio-tech/connect-app/blob/dev/src/config/projectWizard/index.js#L143-L145
    The question here is: Where estimations will be stored in the DB? 

2. product estimation based on questions answers
    How to get data about duration and money from questions?
    
    ![image](https://user-images.githubusercontent.com/146016/41906732-392f38f8-7971-11e8-8fc1-135aa645f6c4.png)

    There are some propertes I'm not sure what is the meaning:
    - `minTimeUp` - looks like min time in days
    - `maxTimeUp` - looks like max time in days
    - `quoteUp` - looks like money estimation

    But `minTimeUp == 3`/`maxTimeUp == 5` doesn't match `desc: "7-10 days"`.
    Also `desc: "5-7 days"` has all values for `minTimeUp`/`maxTimeUp`/`quoteUp` as zero, which doesn't look correct.
   
     Please, clarify where the estimation values has to come from. As I think parsing string `desc: "7-10 days"` is not the best way, and `minTimeUp`/`maxTimeUp`/`quoteUp` look a little bit confusing.

**Comment by RishiRajSahu** [comment]
@gondzo @maxceem For this release due to anomalies in requirement we are hiding the scope section from everywhere i.e. from creation wizard and scope page, so leave the current logic as it is for now and just hide it on UI. We will include it in next release, @rmjmccormick could you please keep it in your notes so that we don't lose it for the next release ?

**Comment by maxceem** [comment]
For now we hide estimation UI, done via https://github.com/appirio-tech/connect-app/commit/7705849a125ab3bf01b47df472c440372d4f5740

**Comment by RishiRajSahu** [comment]
Closing this one as already fixed as per the requirement of this release, and opened a new issue #2100  to make that part of next release and keep track of it.
