### ISSUE TITLE
Need to fix tool tip text for new posts and replies switch button

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2018]
### Expected behavior
Tool tip text should display when user enable/ disable the switch button(New posts and replies)
 
### Actual behavior
Tool tip text not displaying when user enable/ disable the switch button(New posts and replies)

#### Environment
- OS: Windows
- Browser (w/version): Chrome
- User role (client, copilot or manager):
- Account used:

**Comment by vikasrohit** [comment]
I think we don't need tooltip for enabled switches. Intent of the tooltip is to let user know that why they can not select the disabled switches.

**Comment by vikasrohit** [comment]
Release is deployed to the production with the fix.
