### ISSUE TITLE
Post release fix: Email settings language update

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2020]
After the addition of the email notifications we removed the email settings page, but we still don't allow our customers to opt-out from email campaigns, i.e. we don't expose all email settings at the same page.

In the long run we have to be consistent and allow the customers to see and control all emails from a single interface, so we'll have to replicate (add) the missing features before we remove the link.

Please remove the last sentence, as we do not show the link to the community email settings anymore.

From this:
> Notifications are a great way to get back to what matters. Sometimes things can be a bit overwhelming, we get it, so here you can turn off the things that bug you. Once off, you won’t get any notifications of that category until you turn it back on. To manage your email notifications, follow the link at the bottom of the page.

to this:

> Notifications are a great way to get back to what matters. Sometimes things can be a bit overwhelming, we get it, so here you can turn off the things that bug you. Once off, you won’t get any notifications of that category until you turn it back on.

**Comment by vic-topcoder** [comment]
@vikasrohit what is our status on this one?

**Comment by vikasrohit** [comment]
Hotfix for copy change is applied on production. Do we need to add the link back as well? Adding the link back seems contradicting the copy update.

**Comment by vic-topcoder** [comment]
No, we don't need the link back. The emails lead back to the appropriate settings if a user wants to unsubscribe (most common path).
