### ISSUE TITLE
[$20] Correct Notifications page title

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2026]
The notification page title reads "Notification Settings", it should be just  "Notifications"

![screen shot 2018-06-06 at 2 02 15 pm](https://user-images.githubusercontent.com/8484061/41065101-6629319a-6992-11e8-85b3-be9007e7861d.png)

**Comment by Gauravseta** [comment]
@gondzo can you please tell how to assign this issue to myself? github is not having same UI as before. please help thanks

**Comment by Gauravseta** [comment]
@gondzo read the rules ,  i am confused .
Is the approach same as in other bug bashes?
e.g Fork the repo and work on my forked repo then raise PR on main repo once finished?
OR
Create branch on main repo itself and no need to fork because circleCI tests are to be passed ?

thanks

**Comment by gondzo** [comment]
fork&submit a PR - that will execute circleCI tests as well

**Comment by Gauravseta** [comment]
@gondzo PR has been raised 
#2134

**Comment by Gauravseta** [comment]
@gondzo I couldnt submit txt file on the challenge page. Though 20$ are being reflected on my payments page. but it shows status "accuring" . Can you please help me submit the file? shall i mail it? First time i saw "accuring" ever. thanks

**Comment by gondzo** [comment]
No need to submit anything. Payment is already processed. Accuring status might be related to your payment method (minimum amount for payment?)

**Comment by Gauravseta** [comment]
@gondzo thanks. i will check what does it exactly mean and wait till next month for release of money.
