### ISSUE TITLE
Unhandled error in Project plan

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2029]
Navigating to Project plan tab with App phase causes this warning and error:
Warning: Failed prop type: The prop `attr.icon` is marked as required in `PhaseCard`, but its value is `undefined`.
    in PhaseCard (created by ProjectStage)

Uncaught TypeError: Cannot read property 'match' of undefined
    at new ProjectTypeIcon (ProjectTypeIcon.jsx:1744)

Tab navigation is broken afterwards

**Comment by RishiRajSahu** [comment]
Fixed. Updated the `App` project-template in DB.
