### ISSUE TITLE
New post card doesn't display all formatting correctly.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2034]
### Expected behavior
Post cards should display the formatting correctly, supporting all the options we enabled with the new composer (old composer with extended formatting)

### Actual behavior
Only Underline works, check the post with formatting on https://connect.topcoder-dev.com/projects/6398
![screen shot 2018-06-13 at 9 42 38 am](https://user-images.githubusercontent.com/8484061/41365522-73e5ba22-6eee-11e8-98a8-f1e53c0b48eb.png)

**Comment by gondzo** [comment]
Here are the styles we had previously https://github.com/appirio-tech/connect-app/blob/b31dd8a8d3fc1b2ec74c61cc053c4dbfc266663b/src/components/Feed/draftjs.scss#L86

can you check why are they not applied anymore and bring them back if necessary

**Comment by sumitdaga** [comment]
@gondzo  
also it would be helpful if you could may be point me to a commit when this was working

**Comment by gondzo** [comment]
It was working at commit b31dd8a8d3fc1b2ec74c61cc053c4dbfc266663b

**Comment by RishiRajSahu** [comment]
@rmjmccormick working fine in dev now. closing.
