### ISSUE TITLE
Members should not be able to add other members to a project

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2037]
We had a bug/discussion about limiting member management to only copilots and managers. Right now a customer can still add members to project, which is not what we need.

Expected: the customers can't add new members to their projects. The + button should be hidden for regular customers. Tested with Christina user
![screen shot 2018-06-13 at 9 54 11 am](https://user-images.githubusercontent.com/8484061/41366124-fb3fd8c6-6eef-11e8-91f2-030ab7af1127.png)

**Comment by vikasrohit** [comment]
We haven't change team management in the project plan release, so moving the issue to community fix milestone.

**Comment by RishiRajSahu** [comment]
@rmjmccormick its part of community fixes, right ?

**Comment by rmjmccormick** [comment]
@RishiRajSahu as discussed, please prioritise this. Thank you.

**Comment by RishiRajSahu** [comment]
@rmjmccormick fixed and pushed changes to dev. Please verify and close the issue.

**Comment by rmjmccormick** [comment]
@RishiRajSahu Thank you.
