### ISSUE TITLE
Messages with a time gap of 10+ min should show the avatar and time stamp.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2039]
### Expected behavior
When a user posts multiple messages and the time difference between them is bigger than 10 minutes, the messages should not be bundled. The messages with a time gap of 10+ min should show the avatar and time stamp.

### Actual behavior
All messages by the same author are bundled regardless of time interval between them

![screen shot 2018-06-13 at 4 23 59 pm](https://user-images.githubusercontent.com/8484061/41383584-4ed8e730-6f26-11e8-917b-ee43ea321536.png)

Expected (mock design):
![screen shot 2018-06-13 at 4 27 45 pm](https://user-images.githubusercontent.com/8484061/41383670-c0a61c34-6f26-11e8-9916-8d7006ba25a8.png)

**Comment by sumitdaga** [comment]
@vikasrohit  @RishiRajSahu @gondzo  
also in mobile no matter the time difference between successive posts by the same user, they are all rendered separately with user avatar and time stamp as of now ...
should this remain as it is on mobile for now? or something else ?

**Comment by gondzo** [comment]
I think we should follow the same logic in mobile. Can you confirm @RishiRajSahu

**Comment by vikasrohit** [comment]
Yes, same logic of grouping messages in 10 minutes should be applicable to both desktop and mobile versions.

**Comment by sumitdaga** [comment]
ok, i will update the PR accordingly ...
just to be sure ...it was not at all grouped on mobile till now (all posts were separate) ...
not sure if it was by mistake or intentional ...
but we want the same behaviour on both mobile and desktop?

**Comment by RishiRajSahu** [comment]
Yes, same behaviour for mobile as well.

**Comment by gondzo** [comment]
looks good. merged to dev. closing

**Comment by vikasrohit** [comment]
@gondzo what made us to reopen this issue?

**Comment by RishiRajSahu** [comment]
was partially committed earlier, now its fixed and merged to dev. Closing.
