### ISSUE TITLE
"swetaipec"  message: not able to add second new post as save button is disabled 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#204]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create project
'4. go to specification
5. update specification
6. go to message
7. Add first message
8. add second message

Expected Result: should be able to add message
Actual Result: save button is disable 

Enviroment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18928676/bf828fbe-85de-11e6-84c3-373fe00fdc32.png)

**Comment by vikasrohit** [comment]
@mahestro this one is related to #173 IMO, this should be fixed with that. Can you please do me a favour by testing in Windows environment?

**Comment by vikasrohit** [comment]
@fnisen, @parthshah is working on messaging issues.

**Comment by parthshah** [comment]
Should be resolved now.

**Comment by fnisen** [comment]
Yes, working for me. Thanks.
