### ISSUE TITLE
Post time stamp should show actual time

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2040]
### Expected behavior
According to the redesign the time stamp on the post cards should follow display the actual time as h:mm am/pm

### Actual behavior
We display hours ago vs. actual time
![screen shot 2018-06-13 at 4 23 59 pm](https://user-images.githubusercontent.com/8484061/41383726-fa65c2ee-6f26-11e8-8c75-cf32972f6499.png)

Expected
![screen shot 2018-06-13 at 4 27 45 pm](https://user-images.githubusercontent.com/8484061/41383734-014cd516-6f27-11e8-9b27-dbfadfabd40f.png)

**Comment by gondzo** [comment]
looks good. closing

**Comment by sumitdaga** [comment]
@RishiRajSahu @vikasrohit @gondzo 
after this it is not possible for the user to know the date of the post on mobile because we are not separating the posts by date on  mobile but only on desktop
do you see this issue?

**Comment by RishiRajSahu** [comment]
@sumitdaga please file a new issue for that under 2.4.3 milestone and tag it with `Projectplan` . Also put the expected and current behaviour images
