### ISSUE TITLE
Project plan list - price is not aligned with footer

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2042]
### Expected behavior
The price should align on the list items and the footer.

![screen shot 2018-06-13 at 4 35 43 pm](https://user-images.githubusercontent.com/8484061/41383928-0433637a-6f28-11e8-91c7-02e93251ec94.png)

Expected:
![screen shot 2018-06-13 at 4 37 30 pm](https://user-images.githubusercontent.com/8484061/41383940-19cdbee2-6f28-11e8-833f-84d35aff2aff.png)

**Comment by rmjmccormick** [comment]
See also Spent$ not aligned with list items and footer.

![spent not aligned with footer](https://user-images.githubusercontent.com/39598852/41528502-9144abaa-72ea-11e8-9f8d-56cb680a0835.png)

**Comment by RishiRajSahu** [comment]
@rmjmccormick yeah I took note of that as well ! thanks for mentioning.

**Comment by gondzo** [comment]
looks good. closing
