### ISSUE TITLE
The project phase header should expand/collapse the details view

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2043]
### Expected behavior
When I click on the header I would expect the details to show or hide. I expect the whole header to be responsive. This is even more valid for mobile view, where tapping on the header loads the details in a new page.

### Actual behavior
Only the arrow expands the details right now, somewhat limiting the interaction

**Comment by sumitdaga** [comment]
@RishiRajSahu @gondzo @vic-topcoder 
should i also add a pointer cursor on the whole header?

**Comment by RishiRajSahu** [comment]
No, let's keep it as it is. As we have other action icons on phase card for eg - edit icon for phase.

**Comment by gondzo** [comment]
Looks good @sumitdaga 

@RishiRajSahu we don't have loading new page in mobile for expanding the phase header. Should we implement that? If yes, how should it work?

**Comment by RishiRajSahu** [comment]
@gondzo what is mean't by new page ? sorry, didn't got you.

**Comment by RishiRajSahu** [comment]
@gondzo got it ! we have designs for opening it on a new page already for mobile and tab both - 
https://marvelapp.com/8a94680/screen/41372923
https://marvelapp.com/8a94680/screen/41372922
Deisgns are showing timeline tab which is not included right now, I hope we can show the posts and specifications though.

**Comment by gondzo** [comment]
OK, closing
