### ISSUE TITLE
Expanded project cards do not follow the spacing according to design spec.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2044]
### Expected behavior
![screen shot 2018-06-13 at 4 42 09 pm](https://user-images.githubusercontent.com/8484061/41384097-cfd88ef6-6f28-11e8-8d5e-3a18045a3808.png)

### Actual behavior
![screen shot 2018-06-13 at 4 42 57 pm](https://user-images.githubusercontent.com/8484061/41384115-e1429df8-6f28-11e8-918f-88c9258c3b89.png)

**Comment by vikasrohit** [comment]
@RishiRajSahu please mark this and similar issues for community fix. We can get them done via tasks.

**Comment by gondzo** [comment]
Looks good. closing
