### ISSUE TITLE
[Specification] Previous data displayed in 'Add Custom Features' fields

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#205]
Description
-----------------------------------------------------------------
[Specification] Previous data displayed in 'Add Custom Features' fields

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/336)
- Click Specification
- Scroll down and in the 'Feature requirements'
- Click Add/Edit Features
- Scroll down and click Add Custom features
- Enter data and click Save Feature
- Click Add Custom features

Expected Result(s)
-----------------------------------------------------------------
- Must clear the previous data

Actual Result
-----------------------------------------------------------------
- Previous data displayed in 'Add Custom Features' fields

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
http://www.screencast.com/t/zf1q4xtnFmXz

**Comment by vikasrohit** [comment]
Fixed with #125
