### ISSUE TITLE
Updating Phase Card Status

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2050]
As part of this release how should we mark a phase as `Active` ? Currently the phase(s) created by default are in planned state, should we provide a UI to manager/copilot to update phase status along with budget, duration etc ? could we have designs in case any specific UX is required for updating the phase ?

**Comment by vikasrohit** [comment]
I would suggest we use the same edit phase screen for now, just use a simple dropdown there to change the status of the phase. If time permits or in next release, we can use similar dropdown, in the phase card header, which we are using for changing project status on the project listing page.

**Comment by rmjmccormick** [comment]
@vikasrohit @RishiRajSahu thanks, agree with your suggested approach Vikas. Please proceed as such. FYI, Vic is on leave this week, back on Monday 25th...

**Comment by sumitdaga** [comment]
@gondzo  
for the dropdown here i think we will need to use the [SelectDropdown](https://github.com/appirio-tech/react-components/tree/feature/connectv2/components/SelectDropdown) component from appirio-tech  
the SelectDropdown component from this repo throws an error , mostly because it is wrapped in formsy and expects validation , etc

**Comment by vikasrohit** [comment]
Yes, SelectDropdown from react-components repo is what we should use. The one in this repo is deprecated and kept only for not breaking things.

**Comment by sumitdaga** [comment]
it seems the SelectDropdown from appirio-react-components does not allow to pass selectedOption as a prop  ...
is that correct?

**Comment by RishiRajSahu** [comment]
@sumitdaga if it doesn't support selectedOption as a prop, use SelectDropdown component from this repo.

**Comment by RishiRajSahu** [comment]
Closing as the changes are pushed to dev by @vikasrohit
