### ISSUE TITLE
Update Specifications tab to allow for file upload in topfear-dev product

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2053]
Users should be able to upload information relating to their project in the specifications tab. 

At the moment, there is now file upload interface to allow users to do so.

![project specs](https://user-images.githubusercontent.com/39598852/41405127-4992eafc-6fc9-11e8-9d16-c1c6eddbc79c.PNG)

**Comment by RishiRajSahu** [comment]
Updated the product-template to provide option of file upload for topgear-dev.
