### ISSUE TITLE
Update default $ value in Project Status bar

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2054]
Currently, the Spent $ amount in the Project Status bar defaults to "$undefined" as opposed to "$0"

![dashboard - spent](https://user-images.githubusercontent.com/39598852/41410152-c6ae8e9c-6fd8-11e8-916b-ba97121810ac.PNG)

**Comment by RishiRajSahu** [comment]
Fixed with latest changes merged to dev. Closing the issue.

**Comment by rmjmccormick** [comment]
The amount listed next to Spend$ needs to be responsive to the amount of money actually spent to date on the project - in the case of the example, $2500

![project plan alignment](https://user-images.githubusercontent.com/39598852/41528146-877cd300-72e9-11e8-99e1-ecad506f7ed8.PNG)

**Comment by RishiRajSahu** [comment]
@rmjmccormick currently logic for spent is to show only the spent of delivered and active phases not planned, and ideally also this should be the case, what say ? So now arises a new question of not showing the spent field for editing for the phases which are in planned state, should we do that or it will implicit for a manager to not change spent field for planned phase ? Should we create a new issue for that  ? Also wrt alignment bug there is already an issue open #2042

**Comment by RishiRajSahu** [comment]
@rmjmccormick yes it wouldn't be implicitly understood, I also have the same view. Okay, if you decide to show spent field in edit form of phase only for active phase that won't be big change, just create an issue for the same and tag me.

**Comment by gondzo** [comment]
closing this one. @rmjmccormick let's create a new issue if we need to change spent field value
