### ISSUE TITLE
Updating Project-Templates to have fields to hide/disable the project

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2056]
We need to update each of the project template with hidden/disabled attribute after adding these to backend model of project template.

**Comment by vikasrohit** [comment]
@RishiRajSahu we have default `false` value for both these fields. So we just need to set them true for specific templates. No need to touch templates which are neither disabled nor hidden.

**Comment by RishiRajSahu** [comment]
@vikasrohit agree ! so we can close the issue once the changes are pushed to backend.

**Comment by vikasrohit** [comment]
Changes are pushed to the dev environment for the backend.
