### ISSUE TITLE
Verify if very old discussions tab is visible after project plan changes

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2059]
We used to have a separate tab for non customer facing discussions which was discarded later on, however, few old projects are still using that tab for communication between managers and copilots. We need to validate that if that tab is still available after refactoring done for project plan.

fyi @RishiRajSahu

**Comment by vikasrohit** [comment]
Verified and it is working however, style for the edit icon is off.

https://connect.topcoder-dev.com/projects/6404/discussions can be used for testing in dev.

<img width="1280" alt="screen shot 2018-06-18 at 3 30 08 pm" src="https://user-images.githubusercontent.com/2417632/41530075-9cfdff56-730c-11e8-8ea6-2600836b9fb1.png">

**Comment by sumitdaga** [comment]
@vikasrohit  @RishiRajSahu 
![discussions tab test 18-06-2018 15_26 - topcoder - google chrome 2018-06-20 15 19 00](https://user-images.githubusercontent.com/7769148/41651151-7d573a40-749d-11e8-9e48-897e702d4e05.png)

this is how it looks to me and the dropdown menu position also seems wrong to me when the icon is clicked

**Comment by sumitdaga** [comment]
i am hoping my PR fixes this issue without causing any side effect

**Comment by RishiRajSahu** [comment]
@sumitdaga replied on PR

**Comment by RishiRajSahu** [comment]
Closing. Pushed to Dev.
