### ISSUE TITLE
Make Secondary Tool Bar Fixed For Easy navigation

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2064]
The secondary tabs should be above the content - there's the drop shadow at the bottom - and ideally we can make it fixed at the top, so people can navigate between the project pages easily. If the page is too long, they have to scroll back to the top before navigating away.

Ref - https://github.com/appirio-tech/connect-app/issues/2000#issuecomment-390333779

**Comment by gondzo** [comment]
it should not be fixed on mobile

**Comment by gondzo** [comment]
looks good. closing

**Comment by gondzo** [comment]
@sumitdaga the other content should move down, not be covered by the navigation bar
![image](https://user-images.githubusercontent.com/3051646/41782949-eaffcbda-763b-11e8-8c63-462f0ebf012c.png)
![image](https://user-images.githubusercontent.com/3051646/41782972-fcabd13a-763b-11e8-9cd0-984c0db6b4b8.png)
