### ISSUE TITLE
[$120] Show phase details in new page/tab

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2066]
Tapping on the project phase header should open phase details in new page on mobile, new tab on desktop
https://marvelapp.com/8a94680/screen/41372923
https://marvelapp.com/8a94680/screen/41372922
Designs are showing timeline tab which is not included right now - show posts and specifications only for now.

**Comment by asadath1395** [comment]
@gondzo Can you point me to any project which has that kind of phases, not able to find one

**Comment by meggamind** [comment]
want to work on this issue, but not able to change label or assign myself

**Comment by meggamind** [comment]
@gondzo Is there is a zeppelin access, will be helpful and easier to get the height and widths

**Comment by meggamind** [comment]
@gondzo the only thing to implement is timeline, right? The language is a bit confusing, sorry

**Comment by meggamind** [comment]
or do we have to just fix the opening of the link in new page and tab?

**Comment by vikasrohit** [comment]
1. No need to add timeline tab, it is a new feature in development.
2. I guess no need to change the behaviour on desktop. @RishiRajSahu @rmjmccormick could you please confirm that?
3. On mobile, tapping (anywhere except the Edit icon) on a particular phase, should load the phase with tabs (as shown in https://marvelapp.com/8a94680/screen/41372923 for portrait view and https://marvelapp.com/8a94680/screen/41372922 for landscape view) in complete viewport. Right now when user taps on the phase, it just expands the phase card below the phase header, it does not hide the other parts of the page. So, essentially on mobiles, it is a new page/view where we would show the phase in expanded form and nothing else. There would be a back button in the header which would allow users to go back the project plan page.
Hope, things are clear now.
fyi @gondzo

**Comment by rmjmccormick** [comment]
@meggamind No change to behaviour on desktop required.

**Comment by gondzo** [comment]
We already use a library - react-responsive

**Comment by meggamind** [comment]
Still working on it. Will get done soon.

**Comment by meggamind** [comment]
@rmjmccormick @vikasrohit @gondzo 
let me know if this is acceptable or any changes need to be made 
https://github.com/appirio-tech/connect-app/pull/2225

**Comment by vikasrohit** [comment]
@gondzo should we mark it as ready for review?

**Comment by meggamind** [comment]
I think the build fail, i'll update the lint error. Also would it better to just make a new container for the route /phase/:phaseId?

**Comment by meggamind** [comment]
@gondzo @vikasrohit Any review update on this?

**Comment by meggamind** [comment]
@gondzo A bit curious, this was part of https://www.topcoder.com/challenges/30068015/?type=develop, which is closed and I didn't not submit anything. Can I still get paid for this? Do I need to do anything?
