### ISSUE TITLE
Missing image button in posts formatting tool bar

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2068]
As per the visual design, Post formatting tool bar should include the option to upload an image by clicking on the relevant button.

https://marvelapp.com/8a94680/screen/41372955 

Current version in dev does not include this option. See below:

![missing image](https://user-images.githubusercontent.com/39598852/41650554-9b509790-747e-11e8-9b47-1d7247fdb386.png)

**Comment by rmjmccormick** [comment]
OK - let's discuss next meeting and slate for release in 2.4.4 or 2.4.5 please

**Comment by vikasrohit** [comment]
@rmjmccormick closing the issue as we don't have any simple way to enable the images in posts. We should take care of it some next releases.

**Comment by rmjmccormick** [comment]
@vikasrohit this is listed in Aha, yes.
