### ISSUE TITLE
Formatting of $ amount displayed

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2069]
Design prescribes a comma between the thousands digit and hundreds digit, as per below:

![example](https://user-images.githubusercontent.com/39598852/41652068-68d61e6c-7482-11e8-9362-9eb982c4f145.PNG)
 
Please update formatting to reflect design. Thank you.

![paid amount formatting](https://user-images.githubusercontent.com/39598852/41652087-786ac7c4-7482-11e8-90aa-58e15b7b3286.png)

**Comment by RishiRajSahu** [comment]
Fixed and merged to dev.
