### ISSUE TITLE
Unresolved style name

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2076]
Console error when navigating to project plan page
https://connect.topcoder-dev.com/projects/6371/plan
`Uncaught Error: Could not resolve the styleName 'planned'.`

**Comment by sumitdaga** [comment]
![selection_105](https://user-images.githubusercontent.com/7769148/41834273-4953b55c-7871-11e8-9be9-8fc4f2f3ffed.png)
![selection_106](https://user-images.githubusercontent.com/7769148/41834276-4b7cc094-7871-11e8-8886-68c9486c4f51.png)

status returns a value "Planned" but css does not have that style ...
should i just add a empty .planned style in css ...
or something else should be done?

@RishiRajSahu @gondzo

**Comment by vikasrohit** [comment]
@sumitdaga it must be happening only for old projects (projects created before Friday June 22, 2018). If you try to create a new project, it should not have this issue as now we don't set the status value to be `planned`.

**Comment by sumitdaga** [comment]
@vikasrohit 
ok, in that case i think it would be best to add a dummy `.planned { }` css to remove this error for old projects for now and remove this css later 
is that ok?

**Comment by vikasrohit** [comment]
I don't think so, you can simply update the status of project instead. Now we have the status dropdown which can set it to the correct value.

**Comment by RishiRajSahu** [comment]
@vikasrohit @sumitdaga it seems this error will be there in dev only anyway, as in prod we don't have statuses concept yet, so for handling console errors on dev we can add `.planned { }` so that other console errors are not hidden because of this, right @vikasrohit ?

**Comment by RishiRajSahu** [comment]
Closing this, Please use new project on dev to find out remaining console errors and log them in separate issue.
