### ISSUE TITLE
Console error on dashboard

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2078]
Console error thrown when visiting dashboard for project
https://connect.topcoder-dev.com/projects/6398
```Uncaught (in promise) TypeError: Cannot read property 'firstName' of undefined```

**Comment by RishiRajSahu** [comment]
@gondzo is it fixed ?

**Comment by gondzo** [comment]
this is fixed already by https://github.com/appirio-tech/connect-app/commit/7a623588fa87ecc3969a9a68def8397b6cdf589e
