### ISSUE TITLE
"swetaipec"  message: cross button not working on second new  status post  

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#208]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create project
4. go to message
5. post a message
6. click on post new message icon
7. click on cross icon 

Expected Result: should be able to close window
Actual Result: cross button not working 

Enviroment: windows 7, chrome latest 
![image](https://cloud.githubusercontent.com/assets/16131461/18928784/3be4d210-85df-11e6-99e2-5a24267a001c.png)

**Comment by fnisen** [comment]
@vikasrohit I think this was already fixed locally.

**Comment by vikasrohit** [comment]
Yes, it is fixed with #142
