### ISSUE TITLE
[$70] User alert for dirty phase(s)

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2086]
If user has edited the phase and without saving the form, switches the tab from `Project Plan` user should be shown warning for unsaved changes for the phase(s)

**Comment by mhikeo** [comment]
Unable to replicate issue. Working as expected.

**Comment by vikasrohit** [comment]
@mhikeo we are still the issue in dev environment. Could you please attach a video where it is working for you?
