### ISSUE TITLE
Mobile UI : Phase status showing wrong 2.4.3

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2088]
**### Expected behavior**
**Describe:**

Phase status should show properly for new project in Mobile UI.

Project Name : Test Mobile project for 2.4.3

**### Actual behavior**
**Describe:**

Phase status showing wrong for new project in Mobile UI. 
Project Name : Test Mobile project for 2.4.3

![mobile ui project _test mobile project for 2 4 3](https://user-images.githubusercontent.com/30447858/41863274-dbe2e5bc-78c3-11e8-8f7b-87c74d52f4f4.PNG)
![phase status showing wrong for new project in mobile ui](https://user-images.githubusercontent.com/30447858/41863287-e33113d4-78c3-11e8-85d1-0422777bb173.PNG)
![phase status showing wrong for new project in web ui](https://user-images.githubusercontent.com/30447858/41863293-e702e2ee-78c3-11e8-9f83-e911f07b37ff.PNG)

**Overall Description :**

I have created new project in Mobile UI, I have compare the project plan with Mobile UI with web UI with same project.

Project Name : Test Mobile project for 2.4.3

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please fix the above bug.

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 Fixed and pushed changes to dev.

**Comment by deepakanbarasan1** [comment]
Now Phase status looks same in Mobile and Web UI.
![phase status showing wrong for new project in mobile ui_bug fixed](https://user-images.githubusercontent.com/30447858/41905042-9dc41424-7957-11e8-9086-e296965a968b.PNG)

Web UI

![phase status showing wrong for new project in web ui_bug fixed](https://user-images.githubusercontent.com/30447858/41905097-c28f2d70-7957-11e8-961c-e4ee4546cd8b.PNG)
