### ISSUE TITLE
Customer sees "Add phase" button in project plan

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2090]
### Expected behavior
Customers should not be presented with the "Add phase" button when they navigate to the project plan. Tested with "Christina Underwood" account.

**Comment by vikasrohit** [comment]
@vic-topcoder I think we should handle this in this release itself. It does not require much efforts.

**Comment by RishiRajSahu** [comment]
Verified the changes on dev. closing.
