### ISSUE TITLE
[$30] There should be only 1 message to dismiss on a project dashboard.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2091]
### Expected behavior
When the user comes back and there's a project status update message, they can dismiss it. There should be only 1 message at all times. In effect if there have been several messages, we want to replace them with only the latest.

### Actual behavior
Upon dismissal of the last status update message, the previous one is loaded and the user has to click unspecified number of times to clear them old.

### Steps to reproduce the problem
Change a project status several times and view the project as a member. Try dismissing the messages to observe the behavior.

### Screenshot/screencast
![screen shot 2018-06-25 at 7 56 06 pm](https://user-images.githubusercontent.com/8484061/41886980-8d42368e-78b3-11e8-8f2c-efda4c39a0aa.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-474

**Comment by maxceem** [comment]
Note, to test it, we can mark two milestones as completed at the same time which will produce two notifications.

**Comment by maxceem** [comment]
This is one is open for pick up now.

**Comment by khushimehta03** [comment]
i wish to work on it and complete this time @maxceem

**Comment by maxceem** [comment]
This issue is now opened for pick due to inactivity.

**Comment by sumitdaga** [comment]
Can you assign me ?

**Comment by sumitdaga** [comment]
@maxceem  
how to mark a milestone complete?

**Comment by maxceem** [comment]
@sumitdaga you can use this project or create a new one http://local.topcoder-dev.com:3000/projects/7300/plan

- Go to Plan tab (if not yet)
- Open two phases which are `In Progress` state
- There would be milestones which have `Mark as completed` or `Complete Review` buttons which will complete milestones. Note some buttons require one more click to confirm the action.
- Click these two buttons one by one fast to complete two milestones at the same time. There would be two notifications.

See demo video https://monosnap.com/file/OORAzuTp9CwtBD3CpdB7fA6nS3eCBQ

Also if you already don't have active phases for a project, you may need to add a new phase using the `Add New Phase` button at the bottom.
After you've added phase, you have to activate it to be able to complete milestones. To activate phase, click on the pencil on the phase, and after choose status `In Progress`. After that, you could complete milestones inside.

Let me know if it helps.

**Comment by sumitdaga** [comment]
@maxceem  
thats for your input
ok i was able to reproduce just like the demo video you shared  (initially i think the red boxes in the screenshot shared by vic-topcoder confused me)  
but i am not sure why this is an issue ...how likely is a user to complete two milestones like that so fast and more over the notification popups dis appear on their own ...
whats wrong with that ?  
or may be @vic-topcoder  means something else ...  
one user changes project status several times and another user sees this notification when he/she opens that project ?  not sure !  
let me know, thanks!

**Comment by maxceem** [comment]
@sumitdaga you have a good concerns regarding the issue.

I cannot find any other real-world case of showing multiple notifications except errors (red notifications) which is not easy to reproduce.

So I made up that demo to be able to reproduce the behavior for testing.

As I it seems to me, there should be some parameter for the plugin which we use to show notifications to allow not more than one notification at time, which has to resolve this issue.

> one user changes project status several times and another user sees this notification when he/she opens that project

I think one user cannot cause appearing additional notifications for another user.

**Comment by maxceem** [comment]
@sumitdaga as you are right, that this issue is not clean. Could you please submit your PR to this branch https://github.com/appirio-tech/connect-app/tree/issue-2091 instead of `cf12`. As we would like to keep it separate for now. Thanks.

**Comment by sumitdaga** [comment]
@maxceem  
to show these alerts, this library is being used  https://github.com/juliancwirko/react-s-alert   
and i think it is instantiated differently(with different config options) at different places ...so i think its important to first identify what exactly needs to be solved  ... and then solving it should be straightforward enough as the library provides many config options

**Comment by maxceem** [comment]
@sumitdaga I've checked that out, actually it looks like it's configured only in one place for the whole project https://github.com/appirio-tech/connect-app/blob/dev/src/components/Layout/Layout.jsx#L26.
And in other places, we only call actions to show alerts without additional configs.
So, for now, it's ok to make the same behaviour for the whole project. We will keep it in a separate branch for now `issue-2091` though.

**Comment by sumitdaga** [comment]
@maxceem  
ok sorry, i didn't carefully check the library 
raised a PR at #2516

**Comment by maxceem** [comment]
It's done now in branch https://github.com/appirio-tech/connect-app/tree/issue-2091 for now.
