### ISSUE TITLE
Phase duration - negative number

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2092]
When setting the phase duration (number of days in a phase), user is given the option of selecting a negative value for number of days (-1 day in below example).

Phase duration cannot be a negative number or nil and should be one day (1) or above 

![image](https://user-images.githubusercontent.com/39598852/41896144-1a6e91b8-7924-11e8-9bc7-492f5cec42fe.png)

**Comment by RishiRajSahu** [comment]
@rmjmccormick Should this be applied to `SPENT`  `BUDGET`  `STATUS`  `PROGRESS` as well ?
what I think is -
```
Duration - 1 or more
Spent - 0 or more
Budget- 0 or more
Progress- 1 or more
```

Does this sounds good to you ?

**Comment by rmjmccormick** [comment]
@RishiRajSahu Agreed, but for Progress which should be 0 or more (as you can have 0% progress). Thanks.

**Comment by RishiRajSahu** [comment]
@rmjmccormick Fixed the issue and pushed to dev. Please verify and feel free to close the issue.

**Comment by rmjmccormick** [comment]
@RishiRajSahu Looks good! Thanks. Closing this issue.
