### ISSUE TITLE
Update URL to project creation footer link "Get in touch with us"

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2095]
Let's replace the current URL at the "Get in touch with us" footer with `https://topcoder.com/contact?utm_source=Connect&utm_medium=Referral&utm_campaign=FooterContact` and push to production as hot fix.

![screen shot 2018-06-26 at 11 01 04 am](https://user-images.githubusercontent.com/8484061/41930587-53b54834-7930-11e8-9167-d5e0a209a315.png)

**Comment by vikasrohit** [comment]
@vic-topcoder we are going to release it tomorrow with our scheduled release. Let me know if we still want it as hotfix.

**Comment by rmjmccormick** [comment]
Working in prod.
