### ISSUE TITLE
Mobile UI : Phase status showing wrong (Progress0)

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2096]
**### Expected behavior**
Describe:

Phase status should show properly for new project in Mobile UI.
Project Name : Test Mobile project for 2.4.3

**### Actual behavior**
Describe:

Phase status showing wrong for new project in Mobile UI. 
Project Name : Test Mobile project for 2.4.3
Wrong Status : **Progress0**
Correct Status : Progress

**Overall Description :**

I have created new project in Mobile UI, I have compare the project plan with Mobile UI with web UI with same project.
Project Name : Test Mobile project for 2.4.3

Phase status showing wrong in Mobile UI (Progress0) 

![each phase card should have basic details about the phases_mobile ui_progess0](https://user-images.githubusercontent.com/30447858/41932112-bba6a1c8-799d-11e8-8d58-18e08124af07.PNG)
**Web UI**
![each phase card should have basic details about the phases_web ui](https://user-images.githubusercontent.com/30447858/41932125-c4d7ca38-799d-11e8-9837-114ba5ec7ff2.PNG)

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please fix the UI issue

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 Fixed and pushed to dev. Verify and close if looks good to you.

**Comment by deepakanbarasan1** [comment]
Bug Fixed 

Phase status should show properly for new project in Mobile UI.
Project Name : Test Mobile project for 2.4.3
![mobile ui_phase status showing wrong_bug fixed](https://user-images.githubusercontent.com/30447858/41978880-5c7b3288-7a40-11e8-926d-8c3ab00ac0c3.PNG)

**Comment by deepakanbarasan1** [comment]
Bug Fixed

Phase status should show properly for new project in Mobile UI.
Project Name : Test Mobile project for 2.4.3
