### ISSUE TITLE
Show all active phases on dashboard

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2097]
Right now only single first phase of project is visible on dashboard. Show all active phase on Dashboard with earliest to be completed at top i.e. sorted in order of increasing end date.

**Comment by maxceem** [comment]
I've added hiding of `work in progress` title when there are no active phases via https://github.com/appirio-tech/connect-app/commit/1cada44549b1e94567b2e26f17238a0cd2683850

**Comment by RishiRajSahu** [comment]
thanks @maxceem , Nice catch !

**Comment by RishiRajSahu** [comment]
Pushed and verified on dev.
