### ISSUE TITLE
Hiding Unplanned phases from customer

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2099]
Currently we are showing all the phases to the customer, i.e. for manager and customer are able to see all the phases included unplanned, but we want to show unplanned only for managers and not to customers. For customers unplanned phases must be hidden.

Incase, if all the phases are unplanned for a project, manager will be able to see them all and customer will see no phases instead this screen will be shown to him/her - https://marvelapp.com/8a94680/screen/43925162

**Comment by maxceem** [comment]
done via https://github.com/appirio-tech/connect-app/commit/6100d918bb108980a29fc14ea40f9e875d6cc7f3

**Comment by RishiRajSahu** [comment]
LGTM.
