### ISSUE TITLE
Rename labels in phase editor, and add title as editable

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2103]
Small changes to the phase properties UI:

- [x] Rename the labels to match the screenshot
![screen shot 2018-06-28 at 11 16 46 am](https://user-images.githubusercontent.com/8484061/42068092-c3c5b1ac-7afe-11e8-8d5f-82a502ab4a54.png)

| From: | To: |
| --- | --- |
| Duration | Duration (days) |
| Spent | Paid to date (US$) |
| Budget | Price (US$) |
| Progress | Progress (%) |

- [x] Let's add the title of the phase as variable, text input, with limit of 48 characters (To fit a single line of text in desktop (full width). This is very important as a most projects reuse development and design iterations, and those must be labeled to avoid confusion with the customer.

**Comment by RishiRajSahu** [comment]
@rmjmccormick @vic-topcoder fixed with 1378060e5f91e44fe8efc313a3db71c3f946c536. Pushed to dev.
