### ISSUE TITLE
Phase editor cancel doesn't dismiss changes that trigger warning

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2104]
When I open the phase properties UI editor, change some properties, and don't want to modify anything, I press on "Cancel" button. I expected the fields would be reset to default.

Right now if there are warnings triggered on the interface, they are not dismissed on Cancel.
![screen shot 2018-06-28 at 6 30 50 pm](https://user-images.githubusercontent.com/8484061/42068536-6682df62-7b01-11e8-8c4b-3e45a8ade1df.png)

**Comment by RishiRajSahu** [comment]
fixed with 410345f1b8d813fea203184b3376a45a7d849867
