### ISSUE TITLE
[$40] User tooltip under text

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2105]
### Expected behavior
When I hover the user on the sidebar, the tooltip should be displayed on top of all elements (highest z-index)

### Actual behavior
![screen shot 2018-06-28 at 11 35 34 am](https://user-images.githubusercontent.com/8484061/42068564-9717f572-7b01-11e8-9e05-7bf2e049c200.png)

**Comment by gondzo** [comment]
see the guide for z indexes > https://github.com/appirio-tech/connect-app/wiki/Community-Work-Read-Me-First!

**Comment by sumitdaga** [comment]
@gondzo 
there is a console warning and a error when the dashboard page loads ...can you see this too?
at least for this project http://local.topcoder-dev.com:3000/projects/6446

**Comment by vikaskyadav** [comment]
You can increase the z-index to some greater value
