### ISSUE TITLE
Add file attachments to project Scope section

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2106]
### Expected behavior
On project scope tab I should be able to add as many supporting documents as I want. This is the files section at the base of the current scope documents. Let's bring this back to the scope section please.

![screen shot 2018-06-28 at 6 34 31 pm](https://user-images.githubusercontent.com/8484061/42068626-eb976916-7b01-11e8-88c3-e296d98e090c.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-276

**Comment by vikasrohit** [comment]
@vic-topcoder Right now we show every field, that is in scope of the project, at the time of project creation. So, bringing files section in scope would bring it to the creation wizard as well. I think that is why we separated the project scope from the specifications.

Technically we can achieve the requirement of having something in project scope but not visible on project creation wizard form. I am assuming that as the direction, and would get the logic updated.

@RishiRajSahu Please take it into our plate for 2.4.4

**Comment by vic-topcoder** [comment]
I think it is even better if we can provide customers with the opportunity to attach files during creation, that is a feature requested from the architects quite often.

**Comment by vic-topcoder** [comment]
@rmjmccormick let's discuss this. Adding files to a newly created project is very important. I would assume it is technically possible to store the files under a temporary project, and in line with the changes to project creation flow (register and login before completing project creation) this would be viable.

**Comment by vikasrohit** [comment]
Yes, it is technically possible. However, we always evaluate the efforts required against the value of the feature. If it requires significant efforts for a feature that might not be used frequently or might be dropped after couple of releases, I would just waste the efforts.
In this particular case, if we allow file uploads for non logged in users, there are chances that people would start adding files but not completing the project and we would get those temporary files piled up. To get rid of them, we have to put some logic in some application to clean that up periodically. Another drawback is that any one can upload files after this change, and some can just fill our storage by calling those file upload endpoints.
@mtwomey do you think it could be handled without much overhead?

**Comment by vikasrohit** [comment]
@vic-topcoder @rmjmccormick @acshields I think we should have a separate discussion on supporting the attachments for project creation wizard, original issue is to support attachments in scope section of the project which we can achieve by updating the templates. However, to avoid redundant efforts, we are waiting for #2162 and #2161 to be closed as soon as possible so that we can update the templates in one go.

**Comment by vikasrohit** [comment]
Added file attachment section for all visible project templates on production. Let me know if you are not seeing it for any specific one.
