### ISSUE TITLE
Label inconsistencies on the UI

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2107]
Several inconsistency issues with our labeling, let's fix those please:

| Location | Current  label | Expected label |
| --- | --- | --- |
[ Project plan tab / progress bar | Budget | Price (US$) |
| New phase window | Add New Stage | Add a new phase |
| Scope tab / sidebar | Specifications| Sections |
| Post card / edit menu | Edit post | Edit title |
| Post card title / edit menu | Save changes (button) | Update title |
| Post card / edit post menu | Edit comment | Edit post  |
| Post card / edit post menu | Delete comment | Delete post  |
| New Post thread placeholder | Share the latest project updates with the team | Start a new discussion  |
| New post thread expanded / title placeholder | Share the latest project updates with the team | Add your discussion title  |
| New post thread expanded / text area placeholder | [empty] | Add your first post  |
| Phase status | Unplanned | Draft |
| Phase first post | Welcome!!! Please use this channel for communication around the phase. | This is the beginning of your phase discussion. During execution of this phase, all communication regarding it will be conducted here - phase updates, questions and answers, general updates, etc. If you haven't already, do please take a moment to review the form in the Specification tab above and fill in as much detail as possible. This will help get started faster. Thanks! |

**Comment by vic-topcoder** [comment]
@rmjmccormick please feel free to modify the text in order to improve the language, and/or add any other textual discrepancies we might have in the UI.

**Comment by rmjmccormick** [comment]
@vic-topcoder updated with a few small edits and further changes we discussed last night

**Comment by RishiRajSahu** [comment]
FYI @rmjmccormick  @vic-topcoder 

Project plan tab / progress bar - **Not Found this one**
New phase window - **Done and pushed to dev**
Scope tab / sidebar - **Done and pushed to dev**
Post card / edit menu - **Done and pushed to dev**
Post card title / edit menu - **Done and pushed to dev**
Post card / edit post menu - **Done and pushed to dev**
Post card / edit post menu - **Done and pushed to dev**
New Post thread placeholder - **Done and pushed to dev**
New post thread expanded / title placeholder - **TBD**
New post thread expanded / text area placeholder - ** and pushed to devDone**
Phase status - **TBD**
Phase first post - **This needs to be done in backend so created separate issue #2133**

**Comment by rmjmccormick** [comment]
@RishiRajSahu Looking good - appreciate it

Re first item, see below - replace "Budget" with "Price (US$)" in edit Phase interface as per attached screenshot

![image](https://user-images.githubusercontent.com/39598852/42270672-bc52bc58-7f81-11e8-8b22-4e0da7f8574a.png)

**Comment by RishiRajSahu** [comment]
All is done. 
created separate issue for - 
New post thread expanded / title placeholder - #2158 
Phase first post - This needs to be done in backend so created separate issue #2133
