### ISSUE TITLE
New project wizard inconsistencies

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2109]
The new project interface is different from the one on production. Please bring it back to standard project listing for the time being. We will have to use the project categories to modify what design, development or QA projects the users can create. Thew changes removed our project categories and is inconsistent with production. I understand the design change to use more of the free space, but the order and project structure of the catalog should not change.

**Comment by vikasrohit** [comment]
Apologies, if I misunderstood this but this is done as per plan and was conveyed to all people involved in the discussions. We had the epic for showing project templates instead of project types and that is what we iterated many times in the calls. It was a logical and required step for introducing default project plan per project. We cant not revert this without reverting all changes for project plan.
Maximum we can do is to show the project templates based on project categories. And these changes would take time as we already refactored components around the project creation wizard to support the templates and removed the second step in the wizard completely as it does not make sense to have it after having project templates.

fyi @rmjmccormick

**Comment by vic-topcoder** [comment]
Our new catalog of solutions is quite extensive, it builds upon all the projects we currently have, and adds probably the same amount of new projects. Listing them all on the main page would be overwhelming.

**Comment by vikasrohit** [comment]
That is something different and we can't say it inconsistency from the production because they are representing different things and as per plan we have changed it to the current state of project templates instead of category and sub category.
We can group the project templates again based on their category, but as I said, that would again introduce a 3 step wizard instead of 2 step wizard which we have after 2.4.3 release.

@rmjmccormick 
**Summary:** Assuming that direction, we are going to group the project templates and show one addition step in creation wizard to reduce the overwhelming nature of the templates.

**Comment by rmjmccormick** [comment]
@vikasrohit Summary sounds good. We can discuss in some more depth on the call later if necessary.

**Comment by vic-topcoder** [comment]
Let's recreate the project catalog experience from Production to Development, it should not affect the deeper structure of a project with the new project plan section. @vikasrohit can you please communicate with @maxceem to explain what needs to be completed?

The Connect project catalog is organized through a JSON configuration object, currently retrieved via the new API. We have to manually sync Production and Development. Currently we support more projects on Production than listed on Dev - we have to recreate the catalog as-is in order to move forward.

### Catalog on Dev (single page)
![screen shot 2018-07-03 at 3 40 45 pm](https://user-images.githubusercontent.com/8484061/42247862-9203ebfc-7ed7-11e8-8334-c425cd165862.png)

### Catalog on Production (2 pages, using categories, shows more projects)
![screen shot 2018-07-03 at 3 41 07 pm](https://user-images.githubusercontent.com/8484061/42247876-9fb33618-7ed7-11e8-8b80-d66ffa4c4049.png)
![screen shot 2018-07-03 at 3 41 10 pm](https://user-images.githubusercontent.com/8484061/42247878-a1cb4ab2-7ed7-11e8-95e7-d268a3699253.png)
![screen shot 2018-07-03 at 3 42 19 pm](https://user-images.githubusercontent.com/8484061/42247888-b315101e-7ed7-11e8-873c-61bc183a9855.png)
![screen shot 2018-07-03 at 3 42 22 pm](https://user-images.githubusercontent.com/8484061/42247890-b45417fe-7ed7-11e8-9f05-0cf0444d398b.png)


### **N.B.**! Let's also make sure we're supporting all the hidden projects -chatbot and enterprise forms - as the company is using them

**Comment by maxceem** [comment]
So as per my understanding, we have to reimplement the project creation wizard same as it was before to become 3 steps:
1. On the first step, we show the list of categories, which can be retrieved using new API for `project_categories`.

2. Note, that DB has only `categoryId` and `categorName`:
    
   ![image](https://user-images.githubusercontent.com/146016/42250432-783e596e-7f63-11e8-8227-82e1621d183d.png)

   While we also need `icon` and `info` properties to render the category on the first step:

    <img width="333" alt="category-fields" src="https://user-images.githubusercontent.com/146016/42250481-d921bed8-7f63-11e8-9aa0-6ba80461ba21.png">

3. Currently, if category has only one `project_template`, when we click category, the second step is skipped and we directly go to the 3rd step with the form. Such behaviour is for `App`, `Website` and `Chatbot` categories. While `Design`, `Software Development` and `QA` categories has the second step to choose `project_template`.
     Should we keep this behavior or always show the second step even if there is only one `project_template`?

**Comment by vikasrohit** [comment]
Perfect understanding @maxceem 

1. Correct. Only the table name is now `project_types` and we already have REST endpoints for that e.g. `GET /v4/projectTypes` to fetch all available project types.

2. Yes, we need to add more attributes to the project types now. I think we need to add `question` attributes as well along with `icon` and `info`. I would do those changes in next couple of hour and you can access them in dev env.

3. We should keep the same behaviour i.e. skip the second step if there is only template in that category.

**Comment by maxceem** [comment]
4. I've noticed that by code, categories/projectTypes can be also `hidden`/`disabled`.
    In JSON there is a category which is `hidden`:

     <img width="688" alt="category-hidden" src="https://user-images.githubusercontent.com/146016/42263559-fb3524fa-7fa0-11e8-9ad0-03fe841648db.png">

      And in the old code there is a lines for categories items:
     ```js
     // don't render disabled items for selection
    // don't render hidden items as well, hidden items can be reached via direct link though
    if (item.disabled || item.hidden) continue
     ```

    Will it be supported by server?
    Should we keep supporting it in frontend?

**Comment by maxceem** [comment]
5. **Important**. pojectTypes will also need to have `aliases: ['all-analytics']` property. We need it to build SEO friendly links for selected projectTypes.

     Current JSON

     <img width="711" alt="project-type-aliases" src="https://user-images.githubusercontent.com/146016/42267951-eecb2fb4-7fac-11e8-8d5e-2f5a2f0ddadd.png">

    How it's being used in URL when we choose `Software Development` project type:

     <img width="1077" alt="alias-in-url" src="https://user-images.githubusercontent.com/146016/42268034-2077b56e-7fad-11e8-84d6-1354c8f519e0.png">

**Comment by vikasrohit** [comment]
@maxceem changes are in dev. You can access the updated project types now.

**Comment by vikasrohit** [comment]
4. Yes, we need it, but I missed that in backend updates. Will do it in some time.
5. It is supported by backend now.

**Comment by vikasrohit** [comment]
4. Done. It is supporting `disabled` and `hidden` fields now.

**Comment by maxceem** [comment]
6. Project template for `Website` has `aliases: ["all-websites"]`:

   ![image](https://user-images.githubusercontent.com/146016/42272432-a362e89e-7fb8-11e8-8135-6555b658e678.png)

   But it has to be `aliases: ['website', 'website_development']`:
   
   ![image](https://user-images.githubusercontent.com/146016/42272530-f12a2600-7fb8-11e8-8909-b8ac7d2d0b1a.png)

**Comment by vikasrohit** [comment]
Ohk. Fixed.

**Comment by maxceem** [comment]
7. Recently adding a New Phase was implemented which uses some parts of the wizard.
   Should it be updated or just keep working as now? So when we add a phase we choose a productTemplate directly wihtout dividin templates in categories?

**Comment by maxceem** [comment]
Done in [wizard-with-types](https://github.com/appirio-tech/connect-app/tree/feature/wizard-with-types) branch.

7. Adding new phases keept as it is.

**Comment by vikasrohit** [comment]
> Adding new phases keept as it is.

Yes, that is okay. We have to support categories for product templates in backend to categorize the product templates. We would take care of it as separate task.

**Comment by RishiRajSahu** [comment]
@rmjmccormick @vic-topcoder changes are pushed to dev. Verify on your side and feel free to close the issue.

**Comment by rmjmccormick** [comment]
@RishiRajSahu Thanks. However, we appear to be missing some the QA projects? Clicking on QA takes me straight to the Real Word Testing specs page.

![image](https://user-images.githubusercontent.com/39598852/42313083-2984a726-8042-11e8-8d5a-f245656c299b.png)
![image](https://user-images.githubusercontent.com/39598852/42313126-455e8656-8042-11e8-80ff-4105d9dcec71.png)

Expected flow (as in Prod)

![image](https://user-images.githubusercontent.com/39598852/42313268-9ac11708-8042-11e8-89b6-21ffcde9d51c.png)
![image](https://user-images.githubusercontent.com/39598852/42313296-ab3311a4-8042-11e8-97b2-49f1d8a85981.png)

**Comment by RishiRajSahu** [comment]
@rmjmccormick yeah that's known because we haven't added templates for all QA projects yet other than real world testing we have yet to add them.  I will add them in some time and let you know.

**Comment by rmjmccormick** [comment]
@RishiRajSahu Thanks

**Comment by vic-topcoder** [comment]
Just listed the missing hidden projects in #2160 - seems you guys are working on bringing them back to DEV.
