### ISSUE TITLE
[Specification] After Deleting the deleted custom feature is displayed in EDIT Mode

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#211]
Description
-----------------------------------------------------------------
[Specification] After Deleting the deleted custom feature is displayed in EDIT Mode

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/336)
- Click Specification
- Scroll down and in the 'Feature requirements'
- Click Add/Edit Features
- Scroll down and click 'Add Custom Features'
- Enter data and click 'Save Feature'
- Now select a feature
- Click Delete Custom Features and click 'Delete Custom Features' button
- Clsoe the popup

Expected Result(s)
-----------------------------------------------------------------
- Must clear the screen

Actual Result
-----------------------------------------------------------------
- After Deleting the deleted custom feature is displayed in EDIT Mode

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_0-59-32](https://cloud.githubusercontent.com/assets/4592712/18936159/b2729002-8602-11e6-8140-9a02f32465fb.png)

**Comment by vikasrohit** [comment]
Fixed with #125
