### ISSUE TITLE
Add a notification to reload page when phase dates are changed (order is changed) but not rendered.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2110]
If I change the start date of a phase to be before the current phase, I have to manually reload the page to see that the order would change. This might not be clear enough and would be nice to add some sort of reminder that the phase order is changed and the user should reload the page, something like "Phase order is changed, please reload page to view changes"

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/729247f072eb06ee19afbb244766f0d90e38b049

![image](https://user-images.githubusercontent.com/146016/42564998-d491cae4-8534-11e8-9e53-e5f57cb6cfc1.png)

See the demo video http://take.ms/SPljk

**NOTE** I think we can just reload phases instead.

**Comment by vikasrohit** [comment]
Okay. Thanks @vic-topcoder for the explanation, we would take care of transition in upcoming release. Do you want me to track that in github or is it something you already have tracked in aha?

**Comment by vic-topcoder** [comment]
Yeah, let's add this as a new issue for the future. Thanks!

**Comment by vikasrohit** [comment]
Closing as separate issue is capture for tracking the smooth transition effect on automatic reload.
