### ISSUE TITLE
Post composer footer on post cards - fixes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2111]
The avatars were not visible when I was dealing with the previous issues, due to a service being down. This should not happen - not rendering the avatar placeholder when we have a service down is bad practice!

The problem now is the padding on the left side, which pushes the author avatar 10px to the left and breaks the alignment. Let's fix that and go back to the original specification (20px padding from the left edge to the post author avatar image)

Current:
![screen shot 2018-06-28 at 7 41 44 pm](https://user-images.githubusercontent.com/8484061/42070475-6d2cbbf8-7b0b-11e8-808b-e98eb0f40742.png)

Expected:
![screen shot 2018-06-28 at 7 42 01 pm](https://user-images.githubusercontent.com/8484061/42070477-71b87fcc-7b0b-11e8-8fc6-e2d47594ff03.png)

Original design:
![screen shot 2018-06-28 at 7 41 31 pm](https://user-images.githubusercontent.com/8484061/42070484-77facf7a-7b0b-11e8-8ab2-aa72aedab4fb.png)

**Comment by vikasrohit** [comment]
> This should not happen - not rendering the avatar placeholder when we have a service down is bad practice!

**Comment by vic-topcoder** [comment]
Let's use a placeholder that would be replaced by the element we're requesting as resource later. This should be part of the component design - all elements to be loaded with a simple placeholder. Anything that takes time to load and is inserted/updates the UI after the initial page load would cause jumps and shirts in the UI, and we don't want that. The goal is to have a progressive enhancement of the UI.

**Comment by RishiRajSahu** [comment]
@vic-topcoder 
1. Regarding aligned of avatar in post composer its getting tracked here https://github.com/appirio-tech/connect-app/issues/2480
2. Showing user/bot initials incase image is not getting fetched
