### ISSUE TITLE
Channels section which provides quick links to the dashboard topics/message

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2112]
### Provided design
https://projects.invisionapp.com/share/HUF7VSJMF#/screens/272160157

### Questions

As topics and channels are same thing, in all questions words channel or topic means same.

1. I see channels start from `#`. Is it added automatically to `channels` or user has to add `#` by himself?

2. Channels has `star` near the title. 
     
     <img width="809" alt="star" src="https://user-images.githubusercontent.com/146016/42074529-50badaf6-7b9f-11e8-943a-f5fe0a5ba5e9.png">

    What does star do when user cliks?

3. Currently topic titles has `edit dropdown` on the right side, while in the new design there is `fullscreen` button. Should we keep them both or just `fullscreen` button? Not sure how to put them both if ti's needed.

    <img width="781" alt="edit-dropdown" src="https://user-images.githubusercontent.com/146016/42074647-babdea9c-7b9f-11e8-8744-e58021ae01fe.png">

4. So far we don't show for topics created data and posts quantity like on provided designs. Should it be added?

5. Should all `channels` be listed at the sidebar?

    ![image](https://user-images.githubusercontent.com/146016/42074791-80838e76-7ba0-11e8-8692-bc3a1c7edbd8.png)

6. What do numbers in red circles next to channels in sidebar mean?

7. Why `#Admins` channel doesn't have a red circle next to it, while `#Project plan` channel has red circle even its values is `0`?

**Comment by maxceem** [comment]
8. How to get starred channels/threads/topics from the server and save to the server. Currently, I don't see any properties which may refer to star.

    ![image](https://user-images.githubusercontent.com/146016/42146953-bc6eb442-7dfd-11e8-96c8-ddbf45875cb0.png)

**Comment by maxceem** [comment]
9. What do you think would be the correct approach to count `unread` messages for channels?
    - **A**. count how many posts of the channel has `read: false` property
      - in this case I think we will need to implement some code which will mark posts read in some situations
    - **B**. count how many notifications about the new messages for the topic we have, so counter will be resetted together with notifications
       - in this case, we already have code which handles marking notifications as read
       - but as I noticed all such notifications are marked as read as soon as we open the page with topics

**Comment by vic-topcoder** [comment]
@vikasrohit - can you help please?

**Comment by maxceem** [comment]
10. What would be the way to identify public/private topics using data from the server?

**Comment by maxceem** [comment]
4. Please, confirm that at the channel/thread date we show the date of the latest post in the thread, correct?

    <img width="691" alt="thread-date" src="https://user-images.githubusercontent.com/146016/42194117-f937a1c0-7ea4-11e8-8240-30df67204d15.png">

**Comment by vic-topcoder** [comment]
>4. Please, confirm that at the channel/thread date we show the date of the latest post in the thread, correct?

Actually, it is the other way around. Thread was created on Jul 3 and has 2 posts in total. The date in the middle (May 14) is the first post date.  It is similar to how Slack groups messages by day. If you keep scrolling messages, the date behaves like a sticky header for the entire view of the messages posted during this date. If we keep posting, the messages from Today would eventually go under the card header, hence the "Today" header would replace May 14.

Does this make sense to you?

**Comment by maxceem** [comment]
4. Let me ask the question another way:
    I understand that that dates at the middle work kind of like sticky dates at the slack:
      
    <img width="671" alt="stick-date" src="https://user-images.githubusercontent.com/146016/42252012-249921c2-7f6d-11e8-9714-420288364bfa.png">

    The question is what date should be displayed under the topic title:
    - thread creation date
    - latest comment date
    - latest comment update date

    <img width="681" alt="topic-date" src="https://user-images.githubusercontent.com/146016/42252040-4f304758-7f6d-11e8-9d72-5edd73e8b5bf.png">

     From your reply I understand it has to be `thread creation date`, so I just want to confirm that we are on the same page here.

**Comment by maxceem** [comment]
10. As I understand when we click on the channel link at the sidebar, the page has to scroll to the particular channel, correct?

11. There is also a fullscreen mode with the channels at the sidebar. It feels like in fullscreen mode, clicking the channel has to show that channel in the fullscreen mode. And also currently viewing channel has to be highlighted with the gray color, correct?

      ![image](https://user-images.githubusercontent.com/146016/42302854-37a48f16-8050-11e8-9312-06f40abba49e.png)

**Comment by vic-topcoder** [comment]
>4. ...From your reply I understand it has to be thread creation date, so I just want to confirm that we are on the same page here.

Correct - thread creation date.

>10. ...the page has to scroll to the particular channel...

Correct

>11. ...in fullscreen mode, clicking the channel has to show that channel in the fullscreen mode. And also currently viewing channel has to be highlighted with the gray color...

Correct! The fullscreen mode behaves as a dedicated chat interface. Clicking on the channel on the left would reload the appropriate thread on the right, and scroll to the beginning of the new messages, or the end of the conversation (if no new messages are available) - Slack-like.

**Comment by RishiRajSahu** [comment]
> How to get starred channels/threads/topics from the server and save to the server. Currently, I don't see any properties which may refer to star.

We need backend changes for that I will discuss this with @vikasrohit and will update you

> What would be the way to identify public/private topics using data from the server?

I think private topics are for managers/copilots so we can handle it on UI itself please refer issue 
description for more details

**Comment by maxceem** [comment]
> I think private topics are for managers/copilots so we can handle it on UI itself please refer issue
description for more details

I mean, I don't see any property like `isPrivate` in the data which comes from sever for topics. So we know at frontend that particular topic has to be displayed with the `lock` icon.

**Comment by RishiRajSahu** [comment]
@maxceem okay got it, we have to have some field on the topic response data to identify first whether the topic is private or not.

**Comment by RishiRajSahu** [comment]
@maxceem let's keep the below three points out of scope of this task, we will need proper planning and scoping of these three tasks. We will pick this in next release

1.Identifying private topics on UI  - we don't even have UI yet to mark topic as private
2.Identifying starred topics on UI 
3.Showing count for unread messages for channels

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick

**Comment by maxceem** [comment]
@rmjmccormick Done via https://github.com/appirio-tech/connect-app/commit/dbd2f3e826e0289ad61be54346ad6e2c708c9227. You may apply [PR#2222](https://github.com/appirio-tech/connect-app/compare/issue-2112-fix?expand=1)

The result looks like this
![image](https://user-images.githubusercontent.com/146016/43064186-cf260f9c-8e90-11e8-9cb4-5239b6cb106a.png)

**Comment by RishiRajSahu** [comment]
@rmjmccormick pushed to dev. please verify and feel free to close.

**Comment by rmjmccormick** [comment]
Looks good. Thank you all.
