### ISSUE TITLE
Expandable topic/message card which allows user to view topic in full browser viewport

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2113]
### Provided design
https://projects.invisionapp.com/share/HUF7VSJMF#/screens/272160156

### Questions
1. Do I understand it correctly, that in fullscreen mode on the left sidebar we show only `channels` and `latest files`? And hide everythng else.

**Comment by RishiRajSahu** [comment]
yes once you click on expand icon for topic/channel on dashboard page it expands in new fullscreen mode and left sidebar has the contents you mentioned.

**Comment by vikasrohit** [comment]
> And hide everythng else.

To make all on the same page, we don't need to update the existing left side bar when posts are maximized, rather it would be a complete new component which would occupy the complete view port hiding the dashboard.

**Comment by vic-topcoder** [comment]
That approach is fine by me. Please see the link I added to the prototype transition in #2112

**Comment by maxceem** [comment]
2. Could you please, help me to find the source of`fullscreen` button 

     <img width="792" alt="fullscrean" src="https://user-images.githubusercontent.com/146016/42196249-907c419e-7eaf-11e8-904d-05718342d322.png">

3. How this should work at mobile? I found this design for mobile https://marvelapp.com/8a94680/screen/43925279/handoff, is it correct?

**Comment by RishiRajSahu** [comment]
@vic-topcoder could you reply  on that ? 
@maxceem yeah #3 is correct this is how channel expands as per designs for mobile. is there any thing to be taken care of wrt design ?

**Comment by maxceem** [comment]
> @maxceem yeah #3 is correct this is how channel expands as per designs for mobile. is there any thing to be taken care of wrt design ?

Looks like for mobile we will have the same way of writing posts as for desktop. Currently, for mobile we write posts using full-screen editor 

![image](https://user-images.githubusercontent.com/146016/42199469-369b1cb0-7ec1-11e8-9bb1-7967a3de5769.png)

**Comment by RishiRajSahu** [comment]
yeah so there are two things, 
1.One is the expanded view of topic on mobile and 
2.Posting new topic or post on mobile.

for 1, we have design and for 2, we will keep it same way as current.

**Comment by maxceem** [comment]
regarding 2. we create new posts the current way in fullscren, but we reply to post in a new way as on the new design, correct?

<img width="424" alt="reply-on-mobile" src="https://user-images.githubusercontent.com/146016/42200857-c190c4b8-7ec7-11e8-8704-26368a8f45ac.png">

**Comment by RishiRajSahu** [comment]
@maxceem let's keep the same view for reply as well, could we do that because we don't have designs for posting a replying yet

**Comment by maxceem** [comment]
@RishiRajSahu yes, we can use current way of posting reply.

4. Another question here, currently posts and comments on mobile devices have the next design:

![image](https://user-images.githubusercontent.com/146016/42208824-c272c38c-7edf-11e8-8453-0c8b67015612.png)

While in provided design posts and comments looks similar to current desktop design:

![image](https://user-images.githubusercontent.com/146016/42208891-e7e84150-7edf-11e8-9576-4f9a3c7cde02.png)

Should design for mobile devices be updated?

**Comment by maxceem** [comment]
5. For the fullscreen mode. Do I get it right that:
    - thread topic (header) has to be fixed at the top
    - comment editor (footer) has to be fixed at the bottom
    - comments should be scrolling in between
    - comment dates have to "sitck" to the header when scrolling simmilar to Slack 

     <img width="1051" alt="fullscreen-behavior" src="https://user-images.githubusercontent.com/146016/42213260-d2f0386a-7eea-11e8-9a18-ff28c070d4d2.png">

**Comment by RishiRajSahu** [comment]
@maxceem 
4.yes we need to update mobile design as well, but create a separate issue for that under 2.4.4 milestone
5.yes you got it right, similar to the slack

**Comment by maxceem** [comment]
@RishiRajSahu thanks

5. Small clarification. Unlike Slack we have toolbars with button under the comment input field, which appears when we place cursor inside an input field.

    ![image](https://user-images.githubusercontent.com/146016/42213906-a0c87cd8-7eec-11e8-8070-f7ed9ffcaa35.png)

    So in our case, the footer will expand up when we place cursor and comments will move up a little bit at the same time as less space for them. Correct?

**Comment by maxceem** [comment]
4. I've created an issue for mobile comments https://github.com/appirio-tech/connect-app/issues/2125
    I'll update mobile design first before contiuning this issue, because I excpect that doing it another order will cause unnecessary work.

**Comment by vic-topcoder** [comment]
@maxceem - let's use this for fullscreen icon:
> 3. ...
[ui-fullscreen.svg.zip](https://github.com/appirio-tech/connect-app/files/2160097/ui-fullscreen.svg.zip)
![screen shot 2018-07-03 at 8 50 42 am](https://user-images.githubusercontent.com/8484061/42230577-32f26348-7e9e-11e8-8ab1-9e24293bc6fd.png)

>5. ...we have toolbars with button under the comment input field, which appears when we place cursor inside an input field.

Correct. The goal is to allow the users to use the formatting tab instead of figuring out Markdown formatting commands.

**Comment by vic-topcoder** [comment]
Please consider also this screen for editing/deleting interaction: https://marvelapp.com/8a94680/screen/45153771

This is a comparison before-after to see how different elements actually https://marvelapp.com/8a94680/screen/45153777

**Comment by maxceem** [comment]
Here I haven't implemented transition like was mentioned https://tympanus.net/Development/AnimatedGridLayout/.

There are some differences in between the provided website and our site implementation:
- when they show fullscreen they use block level scroll, while we use browser level scroll even in fullscreen mode which in my opinion is a much better approach. Though it brings some tricky moments to implement the transition, as during showing fullscreen, we have to scroll browser to the top and at the same moment show transition.

It's hard to tell for sure the complexity of implementing such transition in our case, but some test&try will be needed.

Probably this can be postponed in favor of other milestone tasks, or I can give it a try if you wish.

**Comment by RishiRajSahu** [comment]
@maxceem that's fine for now as we have other priority tasks, but to keep track of this you can add it as a new issue to https://github.com/appirio-tech/connect-app/milestone/56

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick
