### ISSUE TITLE
New files section which allows user to view all files uploaded in project in reverse chronological order

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2114]
### Questions
1. I believe it's already implemented 

    ![image](https://user-images.githubusercontent.com/146016/42075084-cf688f18-7ba1-11e8-994b-c2eb151922de.png)

    It's showing list of latest files fist:
    ```js
    const attachments = _.sortBy(project.attachments, attachment => -new Date(attachment.updatedAt).getTime())
    ```

    Could you please provide details if something has to be updated in existent behavior.

2. Uploading file for project phases looks like is not supported server-side:
    - Open project http://local.topcoder-dev.com:3000/projects/6415
    - Go to project plan
    - Open phase specification and click `Add File`
    - During adding file you'll see error in console `Error: Request failed with status code 404`
    - Frontend looks like correctly format request and sends file to `https://api.topcoder-dev.com/v4/projects/6415/phases/219/products/214/attachments` but server fails with error `Not found`

**Comment by vic-topcoder** [comment]
The menu should list all the files as downloadable links. I would imagine we should reuse the Links behavior/component to populate the menu with the files attached to the project. This includes the "view more" link that would allow to switch between short view and full list.

**Comment by maxceem** [comment]
Mainly, it was done during big Project Plan changes, I've just slightly adjusted styles.

There are few more styles which I'm not sure whether we should changes:

3. Section headers are bold in provided design. Should we make them bold?

    <img width="357" alt="headers" src="https://user-images.githubusercontent.com/146016/42143539-216b2c42-7de8-11e8-8532-ff772a5bf4a5.png">

4. Currently, we show counter with the number of files next to the header. Should we keep them or remove?

    <img width="334" alt="numbers" src="https://user-images.githubusercontent.com/146016/42143591-876be856-7de8-11e8-9b89-c141e08bc296.png">

**Comment by vikasrohit** [comment]
@maxceem thanks for the information.

Please follow the style as per new design i.e. make the headers bold

Please keep the counter for the headers.

**Comment by RishiRajSahu** [comment]
merged to dev.
