### ISSUE TITLE
Updated progress component to show progress bar instead of progress circle

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2115]
### Questions
1. Could you please provide a design for updated component and clarify which component has to be updated.

    I've found this design https://projects.invisionapp.com/share/HUF7VSJMF#/screens/274095568 where there is **additional** component with a bar which shows progress in days. But circle progress in percentage stands.

**Comment by RishiRajSahu** [comment]
@maxceem the design you found is for project-plan. Use this design for dashboard - https://marvelapp.com/8a94680/screen/41500618.

**Comment by vic-topcoder** [comment]
Try this (handoff) https://marvelapp.com/8a94680/screen/41500618/handoff

**Comment by maxceem** [comment]
2. In mobile resolution, `10% done` become hidden same like for main progress bar. Let me know if it's not desired behavior, see http://take.ms/Pow0N

**Comment by vikasrohit** [comment]
@maxceem That is desired behaviour as per designs.

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick
