### ISSUE TITLE
Overlap buttons in mobile version of Connect site.

### ISSUE THREAD

**Issue by coderReview** [appirio-tech/connect-app#2116]
### Expected behavior
When opening the connect site, the help button and write new post button should not overlap.

### Actual behavior
When opening the connect site, the help button and write new post button are overlapping.

### Steps to reproduce the problem
- Open connect in mobile
- Go to project page

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/5925442/42120603-6b0d8ba6-7bf4-11e8-89cc-e2e25ecb08ba.png)

#### Environment
- OS: iOS or Android
- Browser (w/version): Safari, Chrome

**Comment by vikasrohit** [comment]
@vic-topcoder @rmjmccormick how do we want to handle it? Move the New post icon to the left?

**Comment by rmjmccormick** [comment]
@vikasrohit @vic-topcoder Could you move the Help icon to the left rather, as New Post on the right is default in many other mobile messaging applications (e.g. Outlook)

**Comment by vikasrohit** [comment]
@rmjmccormick that is something we haven't added. It is added by marketing team, I guess. They do it via Segment-GTM integration.

**Comment by rmjmccormick** [comment]
@vikasrohit meaning you can't move it to the left - OK. Let me discuss with Vic later then.

**Comment by vic-topcoder** [comment]
We should hide the direct chat service (drift) from all but the project creation. It duplicates the system posting service and is confusing - why would we want customers to communicate through the chat vs. post messages on the platform.

**Comment by vikasrohit** [comment]
Agreed @vic-topcoder. I think that case we have to ask marketing team to remove the chat option for all urls except /projects/new-wizard.
@rmjmccormick we might need your help there to ask marketing team about this.

**Comment by rmjmccormick** [comment]
@vikasrohit I have raised this with Marketing. Will keep you posted.
