### ISSUE TITLE
Need support for hiding scope questions on creation wizard

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2119]
Need a new flag (may be `showOnCreation`) in the project template's questions which allows us to hide/show the fields on creation wizard.

This is a pre-requisite for #2106

**Comment by RishiRajSahu** [comment]
@vikasrohit sure will take care of this !

**Comment by maxceem** [comment]
1. There is a section to submit files during project creation. File uploading currently is not supported during project creation. Should this be supported, or files uploading is one of the sections which will be hidden?

   ![image](https://user-images.githubusercontent.com/146016/42266994-728da50a-7faa-11e8-8049-33fc703ef4bb.png)

**Comment by vikasrohit** [comment]
@maxceem For the this release we are not going to release the file upload in creation wizard. And we can simply disable the attachments field to be rendered on creation wizard but still show on scope tab.

**Comment by maxceem** [comment]
Please, let me know which way we'd like to use here:
- just hide file uploading during creation but show on the spec
- implement a common feature (flag in project templates) which will hide any question during creation but still shows on the spec. This is way will require us to change data (not model) on the server.

**Comment by vikasrohit** [comment]
Second approach is the way to go.

**Comment by maxceem** [comment]
I propose to add a property `hiddenOnCreation` for such questions. 

For example for App project template:

<img width="620" alt="hidden-on-creation" src="https://user-images.githubusercontent.com/146016/42566172-4cae4bda-8538-11e8-8aef-badea7d2db4b.png">

Could somebody add this property for some project template for testing?

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/5e0bfab21bd6e7ffa6208ce000f28c1c489a70a2

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick
