### ISSUE TITLE
New updated team management view

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2121]
Team management view has to be enhanced as per the designs here - https://marvelapp.com/8a94680/screen/41500618 . refer comments section for more details.

**Comment by RishiRajSahu** [comment]
@maxceem please keep this change separated from other issues, create a separate feature branch for this issues exclusive.

**Comment by vikasrohit** [comment]
Yes, and also, keep it low priority as compared to bugs in the project plan features.

**Comment by vikasrohit** [comment]
@gondzo please keep the changes for this issue in a separate feature branch so that we can merge it as per our release plan.

**Comment by vic-topcoder** [comment]
Let's add the requirements for team management and how we plan on splitting/organizing teams. Delay this until we have the requirements completed.

**Comment by vikasrohit** [comment]
Removing from CF 10.

**Comment by vikasrohit** [comment]
@vic-topcoder moving this out of 2.4.5. Let me know if we have the final requirements here.

**Comment by maxceem** [comment]
@RishiRajSahu looks like this is already on DEV.

**Comment by vikasrohit** [comment]
Closing
