### ISSUE TITLE
[$20] ProgressBar component style fix for 100% value

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2122]
### Expected behavior
https://marvelapp.com/8a94680/screen/41372957

### Actual behavior
Right borders are not curved when progress is 100%

### Screenshot/screencast
<img width="792" alt="screen shot 2018-07-02 at 3 00 06 pm" src="https://user-images.githubusercontent.com/2417632/42156478-cf2a6648-7e08-11e8-87c4-0745456afd45.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by vikasrohit** [comment]
@RishiRajSahu please close it if it is duplicate.

**Comment by RishiRajSahu** [comment]
@vikasrohit its a bug and new captured yet.
