### ISSUE TITLE
Roboto bold font possible mismatch

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2124]
I'm not sure if this mismatch can bring any visible issues but probably makes sense to fix.

In `tc-ui` package there is [roboto-bold](https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/mixins/_typography.scss#L27-L30) mixin defined as:
```
@mixin roboto-bold {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  font-weight: 600;
}
```

In the `connect-app` we import Roboto Bold font the next way:
```
@include font-family('Roboto', 700, normal, '../assets/fonts/roboto/', 'roboto-bold');
@include font-family('Roboto', 700, italic, '../assets/fonts/roboto/', 'roboto-bolditalic');
```

So when we import bold font we define its weight as `700`, but when we use the font we require weight `600`.

By quick test in Chrome I don't see any side effects or bugs cased by this mismatch. Not sure how exactly browser match fonts in such cases. But, probably, it could make sense to fix this mismatch to avoid design issues.

cc @RishiRajSahu

**Comment by vic-topcoder** [comment]
Yeah, bold should be `700`! Let's fix the mixin, good catch!

**Comment by maxceem** [comment]
Fixed by [PR](https://github.com/appirio-tech/tc-ui/pull/23) to `tc-ui`.

**Comment by vic-topcoder** [comment]
Great!
