### ISSUE TITLE
Update post/comments design for mobile devices

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2125]
Designs https://marvelapp.com/8a94680/screen/43925278/handoff

**Comment by vic-topcoder** [comment]
good catch, updated!

**Comment by vic-topcoder** [comment]
I would like to update the header on all platforms to display the post count and creation date on the same line. If the post title is too big than we should fold the title in more lines.
![screen shot 2018-07-05 at 12 30 09 pm](https://user-images.githubusercontent.com/8484061/42343852-477d1594-804f-11e8-81ab-49c649ecac4f.png).
Also - for the time being, let's remove the `#` in front of the thread title. I'm not sure we're ready to use this as it is not implemented (fast search or reference threads with #).

2. Dropdown is ok
3. Keep button as is for the moment
4. That's fine I guess. The other approach is to display the menu for posts at all times so users can see/know they can access the editing options
5. Agree - the goal is to use the exact same components to build the interface. Rendering wise we should be using the same elements, but there are specific requirements to mobile post composer vs. desktop one, so we can't rely on the same approach there.

**Comment by vic-topcoder** [comment]
Initially I wanted to have Edit and Delete as icons on hover, but if you ignore those and replace the icons with the menu, it should look like this. The order would be:

- Meta data
- Menu / or icons
- Fullscreen (when available)
 
![screen shot 2018-07-05 at 7 03 20 pm](https://user-images.githubusercontent.com/8484061/42356236-40dbfa3e-8086-11e8-9087-1f577ace80a1.png)

**Comment by RishiRajSahu** [comment]
merged to dev.
