### ISSUE TITLE
Project listing page is rendered in project creation process

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2126]
### Expected behavior
Project listing page should not be visible

### Actual behavior
Project listing page is visible for some time before redirecting to the newly created project.

### Steps to reproduce the problem
- Create a new project
- Observe the page after hitting the `Continue` button the creation form

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  Any

**Comment by gondzo** [comment]
it's not fixed yet. also, if the project isn't created (api error), we close the project wizard and move to project listing page - should we fix this as well?

**Comment by vikasrohit** [comment]
@gondzo is it moving to listing page or the page from where user started the project creation wizard? I think we are okay if we taking user back to the page from where user started the project creation. @rmjmccormick could you please suggest a better way to handle the error use case?

**Comment by andela-jomadoye** [comment]
I can do this, I'll work on it.

**Comment by vikasrohit** [comment]
@gondzo I know we haven't merged the PR for this issue yet, but we have started seeing login page instead of project listing page now when user clicks on a project from the listing page.

**Comment by gondzo** [comment]
@vikasrohit let me know if you still see the login page when opening project details

**Comment by vikasrohit** [comment]
Thanks @gondzo. It seems to be working on dev now. 👍
