### ISSUE TITLE
[$50] When there are more posts hidden on a card from the same day, the "load earlier posts" button should be under the time stamp

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2128]
### Expected behavior
The time stamp should always be on top if there's more content, even if the button "load earlier posts" is present. The time stamp on the top determines when the last event happened. If the hidden posts were before the current day, the time stamp should indicate the last day of the messages we can load. The "load earlier posts" button should never be above the timestamp.

### Actual behavior
The "load more" posts button is on top of the time stamp, but it should be under.
![screen shot 2018-07-03 at 3 25 20 pm](https://user-images.githubusercontent.com/8484061/42247553-290a4b74-7ed6-11e8-8dc7-691e3f224b13.png)
![screen shot 2018-07-03 at 3 25 29 pm](https://user-images.githubusercontent.com/8484061/42247558-2f3b5b64-7ed6-11e8-9c13-ce813abbf94f.png)

### Steps to reproduce the problem
Go to https://connect.topcoder-dev.com/projects/6446, expand the active phase to observe the behavior.

**Comment by mshaaban0** [comment]
@vic-topcoder Can you please share the credentials used to reproduce the issue?

**Comment by gondzo** [comment]
you can use pshah_manager/topcoder123 and post messages on a project to reproduce the issue
