### ISSUE TITLE
Transactional emails come with a title "no-reply", but should say Topcoder

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2129]
### Expected behavior
When we receive an email from Topcoder, the transactional email should be from a trusted provider - Topcoder, Topcoder newsletter, Topcoder Project, etc.

Expected to see something like this:
![screen shot 2018-07-03 at 3 35 37 pm](https://user-images.githubusercontent.com/8484061/42247703-ce08f828-7ed6-11e8-9dcb-1633df7ce5dd.png)
![screen shot 2018-07-03 at 3 35 26 pm](https://user-images.githubusercontent.com/8484061/42247710-d0563c08-7ed6-11e8-884e-ae82d6948f4e.png)

### Actual behavior
The email is from "no-reply"

![screen shot 2018-07-02 at 9 46 31 am](https://user-images.githubusercontent.com/8484061/42247651-95b0df18-7ed6-11e8-9659-e79be33a4209.png)

**Comment by vikasrohit** [comment]
just fyi @vic-topcoder, the first mail in the 
![screen shot 2018-07-02 at 9 46 31 am](https://user-images.githubusercontent.com/8484061/42247651-95b0df18-7ed6-11e8-9659-e79be33a4209.png)
 is not sent from connect, it is sent by Marvel. 😬 

And our emails are from trusted provider. Most of the time user validates the provider by looking the mail headers 
<img width="411" alt="screen shot 2018-07-04 at 11 18 14 am" src="https://user-images.githubusercontent.com/2417632/42258969-fdbd1df6-7f7b-11e8-9e37-8df975a86c26.png"> which says that it is sent from our own domain which is good way to establish trust.

**Summary:** Anyway, we can change the name of the sender. I would do that.

**Comment by vic-topcoder** [comment]
+ @rmjmccormick 

I think we can extend the Coder the bot persona and send messages from him, probably a `coderbot@topcoder.com` so we can also register a Gravatar and make sure we have a better representation in certain email clients. We could also keep the reply-to different from the original sender. This would satisfy the requirement I think.

**Comment by vikasrohit** [comment]
Closing as deployed into dev.
