### ISSUE TITLE
"swetaipec"  after submitting for review , should not be able to update specification 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#213]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create project
4. go to specification
5. update spcficiation 
6. submit for review
7. update optional specification

Expected Result: should not be update spcification after submiting for review

Actual Result: able to update 

Environment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18929029/4928f194-85e0-11e6-93fe-44282186252a.png)

**Comment by fnisen** [comment]
You can only submit for review once, but you can update specs after submitting for review. For example, what if you found another document you wanted to attach/upload--you should be able to do that (and can then message your copilot or manager, asking them to check the updated specs).

**Comment by mahestro** [comment]
Thanks for the behavior confirmation.

Not valid for the bug count.
