### ISSUE TITLE
Long project name breaks markup on mobile devices

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2130]
When we open a project page with the long name, the primary toolbar gets broken on mobile resolutions and horizontal scroll appears:

![image](https://user-images.githubusercontent.com/146016/42251574-b6d5bfee-7f6a-11e8-8360-02955981900a.png)

For example, see the project https://connect.topcoder-dev.com/projects/2871

**Comment by maxceem** [comment]
Fixed via https://github.com/appirio-tech/connect-app/issues/2130

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick
