### ISSUE TITLE
Project progress logic extension

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2147]
Let's address several cases for the project progress bar in order to upgrade the user experience and alleviate customer anxieties.

- [x] Do not show progress bar when there are no active or planned phases. This means we show progress only where there is a progress to show.
![screen shot 2018-07-05 at 6 50 57 pm](https://user-images.githubusercontent.com/8484061/42355907-6bd68922-8084-11e8-948e-63dba6975358.png)
![screen shot 2018-07-05 at 6 51 33 pm](https://user-images.githubusercontent.com/8484061/42355915-731ad1c0-8084-11e8-9d54-c8a5bd434aa2.png)

- [x] When no payment has been reported on a phase, do not display "Spend $0". Only show the spending after it is being recorded on the phase.

- [x] Display progress bar reaching 100% when the customer loads the page for the first time so they can understand all the work is done, and then hide it on subsequent loads. We might have to display a message for the customer that all the work is done and upon clicking OK button to hide the progress bar. This one I have to provide design for tomorrow.

- [x] Do not calculate progress for draft phases. Right now any new phase added in Draft mode is for planning purposes and should not modify the UI for the customer, including the progress bar.

- [x] When project reaches 100%, the rounded corners on the right are missing
![screen shot 2018-07-05 at 6 21 06 pm](https://user-images.githubusercontent.com/8484061/42355118-3335a3ae-8080-11e8-807c-820436aeab19.png)

**Comment by vikasrohit** [comment]
>Do not show progress bar when there are no active or planned phases. This means we show progress only where there is a progress to show.

#2167

> When no payment has been reported on a phase, do not display "Spend $0". Only show the spending after it is being recorded on the phase.

#2168

> When project reaches 100%, the rounded corners on the right are missing

#2122 

> Do not calculate progress for draft phases. Right now any new phase added in Draft mode is for planning purposes and should not modify the UI for the customer, including the progress bar.

#2166 

> Display progress bar reaching 100% when the customer loads the page for the first time so they can understand all the work is done, and then hide it on subsequent loads. We might have to display a message for the customer that all the work is done and upon clicking OK button to hide the progress bar. This one I have to provide design for tomorrow.

I am not sure how to achieve this. It would require capturing the user's response on the alert message and store it in database to be able to show different behaviour after first load and I am not certain how much it makes sense to pollute the data model with unrelated data for enabling fancy UI tweaks. How would the application should behave when there are multiple customer role user in the team and one of the has already viewed the project before others.

**Comment by RishiRajSahu** [comment]
> Display progress bar reaching 100% when the customer loads the page for the first time so they can understand all the work is done, and then hide it on subsequent loads. We might have to display a message for the customer that all the work is done and upon clicking OK button to hide the progress bar. This one I have to provide design for tomorrow.

@vic-topcoder as we have agreed on not showing progress bar when all phases are delivered here - 
https://github.com/appirio-tech/connect-app/issues/2234 , I am closing this issue. Feel free to open a new issue if there are any further changes needed wrt UI when progress bar reaches 100%.
