### ISSUE TITLE
When adding a new phase, there is a gap between top bar and side bar

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2149]
### Expected behavior
The interface shouldn't jump and shift around

### Actual behavior
![screen shot 2018-07-05 at 7 29 40 pm](https://user-images.githubusercontent.com/8484061/42356891-eef4609a-8089-11e8-8313-0c10c7a25554.png)

**Comment by RishiRajSahu** [comment]
@vic-topcoder not reproducible.
