### ISSUE TITLE
[Specification] Can't close the 'Project Features' popup

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#215]
Description
-----------------------------------------------------------------
[Specification] Can't close the 'Project Features' popup

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/336)
- Click Specification
- Scroll down and in the 'Feature requirements'
- Click Add/Edit Features
- Scroll down and Enable "Messaging" and add text
- Click on "Profiles"
- Click "Messaging" again
- Try to close the popup from (x) button

Expected Result(s)
-----------------------------------------------------------------
- Must able to close the popup from X button

Actual Result
-----------------------------------------------------------------
- Can't close the 'Project Features' popup

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_1-05-21](https://cloud.githubusercontent.com/assets/4592712/18936176/d5670692-8602-11e6-8af2-c4f5dc6ec2b4.png)

This is a common issue; when user enter a NOTE; user can't close the popup

**Comment by vikasrohit** [comment]
Fixed with #224
