### ISSUE TITLE
Opening project creation briefly displays the login window

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2152]
I can't reproduce it at the moment, but this morning before I created https://connect.topcoder-dev.com/projects/6545 I briefly was flashed the login window while loading the new project wizard. I saw the same on Rory's screen. @vikasrohit what would cause such a flash to your best knowledge?

**Comment by vikasrohit** [comment]
I think it is because of the same reason as of #2126

**Comment by RishiRajSahu** [comment]
Not reproducible anymore. Seems to be fixed with #2126 . Closing.
