### ISSUE TITLE
[$25] Disable user select for tabs

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2154]
### Expected behavior
Should not be able to select the text from the tabs

### Actual behavior
![screen shot 2018-07-05 at 7 40 29 pm](https://user-images.githubusercontent.com/8484061/42357162-60c39f46-808b-11e8-8444-1138af65baa4.png)

- user avatar
![screen shot 2018-07-05 at 7 41 36 pm](https://user-images.githubusercontent.com/8484061/42357195-86bcb746-808b-11e8-9569-f7fc17cf6039.png)

- tabs
![screen shot 2018-07-05 at 7 41 31 pm](https://user-images.githubusercontent.com/8484061/42357198-8c198d36-808b-11e8-905e-05ae5203d6d4.png)

- switch
![screen shot 2018-07-05 at 7 41 26 pm](https://user-images.githubusercontent.com/8484061/42357204-950fe110-808b-11e8-969d-c3b93e5120ad.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-477

**Comment by zjuasmn** [comment]
work on it.

**Comment by maxceem** [comment]
@zjuasmn it's on you.

To let me assign you for clearance, please, accept the invitation to this repo, which has to come to your email.
Thanks.

**Comment by zjuasmn** [comment]
It’s done and ready for review https://github.com/appirio-tech/connect-app/pull/2598

**Comment by maxceem** [comment]
it's already in the dev for a while, so I'm closing it.
FYI @RishiRajSahu
