### ISSUE TITLE
Toggle text area placeholder for New post thread expanded & collapsed.

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2158]
The required behaviour is for `Title` Textarea, it should show different placeholder in collapsed and expanded state

### Expected behaviour
Text area placeholder for New post thread collapsed - Start a new discussion
Text area placeholder for New post thread expanded - Add your discussion title

### Current behaviour
Text area placeholder for New post thread collapsed - Start a new discussion
Text area placeholder for New post thread expanded - Start a new discussion

**Comment by maxceem** [comment]
I'm sure I got where can I find `Add your discussion title`, did you mean `Add your first post`?

Collapsed New post thread:

![image](https://user-images.githubusercontent.com/146016/42546697-0e73341c-84f1-11e8-8792-c899502587dc.png)

Expanded New post thread:

![image](https://user-images.githubusercontent.com/146016/42546722-2b4a7c4e-84f1-11e8-9681-e323caf5bd66.png)

![image](https://user-images.githubusercontent.com/146016/42546735-366e910a-84f1-11e8-8d20-0213b864f60f.png)

**Comment by RishiRajSahu** [comment]
Done.
