### ISSUE TITLE
Project scope unification and questions updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2162]
With specifications out of the way, we must collect all the project relevant information to bring sales on platform. Let's review and finalize what the project scope questions would be included.

As I see it, we have to update the general questions in line with the document from Morgan, but most of those questions are obsolete as they are very work-specific. We need to collect information:

- Validate the sale
- Close the sale
- Help the customer identify what project template they need
- Additional scope information to help start the project planning/modification
- Collect files and resources

Let's validate an updated unified project scope by end of next week.

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder. It is very critical for the production release.

**Comment by RishiRajSahu** [comment]
moving this to 2.4.5

**Comment by vikasrohit** [comment]
Moving to backlog for the time being. @vic-topcoder @acshields please feel free to move it 2.4.6 milestone if you want to keep in active milestones to not forget about it. :)

**Comment by vic-topcoder** [comment]
moving to productboard
