### ISSUE TITLE
Which phases(wrt status) to be included in calculating project progress ?

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2166]
Should we include planned phases in project progress or should include just the active phases?
if we are using planned phases as well for duration and if planned phase start and enddates are passed, 
it will included as 100% progress for that phase

if we go for using active phases only, then it doesn't make sense to show 1 day of duration for draft and planned phases for which duration is not set, which in turn also contradicts the logic of having default 1 day duration for a phase and having check of `min value 1` for duration field in phase edit form

@vic-topcoder @rmjmccormick

**Comment by rmjmccormick** [comment]
@RishiRajSahu @vikasrohit thanks Gents. I'm not sure I follow the reasoning in your second paragraph above - why would this not make sense and/or contradict the logic? 1 day of duration as default is just a placeholder - in itself it is meaningless and could just as well be zero or 10 or any other number. The important point is that once a project is toggled from draft to active, the duration field should be changed from 1 to the applicable number .

**Comment by RishiRajSahu** [comment]
![screen shot 2018-07-09 at 2 59 27 pm](https://user-images.githubusercontent.com/11248478/42442996-e553a39a-8389-11e8-9a09-e1b83be2fdb0.png)


http://local.topcoder-dev.com:3000/projects/6566/plan

@rmjmccormick 
to keep it simple using the screen-shot, does the above behaviour looks correct to you ? my question is should we also exclude `Planned` phases from calculations ?

**Comment by rmjmccormick** [comment]
@RishiRajSahu the issue with this example is the fact that the "Planned" state of the project was not toggle to "Active" in time - as in, on July 6 App should have automatically toggled to Active, which would have made all the other elements you highlight sync up.
Can we discuss please? This is not a good example to use imho.

**Comment by RishiRajSahu** [comment]
@rmjmccormick yes we don't have any logic in place for handling the automatic toggling of phase from planned to active once the startDate of a phase is arrived.

Suppose the planned phase startDate is not yet arrived in such cases if including planned phase is correct ?

**Comment by vikasrohit** [comment]
> App should have automatically toggled to Active

There is no such feature yet in our application @rmjmccormick. If need that we have to implement a very minimal lifecycle management engine just like we do for challenges and that has to be taken care separately after giving more thoughts on future possibilities around that.

**Comment by rmjmccormick** [comment]
> If need that we have to implement a very minimal lifecycle management engine just like we do for challenges and that has to be taken care separately after giving more thoughts on future possibilities around that. > 

@vikasrohit @RishiRajSahu this should be the direction of travel, as ultimately Connect should be as self-serve as possible, including for co-pilots. We can discuss tomorrow to plan for future inclusion.

**Comment by rmjmccormick** [comment]
> Suppose the planned phase startDate is not yet arrived in such cases if including planned phase is correct ?> 

@RishiRajSahu Yes, in this instance, I would want the duration of the planned phase included in the total number of days and on the project status timeline.

**Comment by RishiRajSahu** [comment]
Thanks @rmjmccormick that's helpful, also i have summarised my understanding here

**Project Status Section -**

- Duration text On left (Days X of Y)- 

Actual duration(X) to be calculated wrt active and completed phases
Total duration(Y) to be calculated wrt planned, active and completed phases

- Progress text on right

Progress % to be calculated with arithmetic average of active and completed phases only

**Phase Card**

- Progress % 

to be calculated for active phase using progress field value or counting days from startDate

**Bottom summary bar**

- total days text ( Y Days)- 

Total duration(Y) to be calculated wrt planned, active and completed phase

**Comment by rmjmccormick** [comment]
@RishiRajSahu Yes, that's correct. Last point - it's important that each of these calculations is responsive to changes in the underlying phase statuses (i.e. if a planned phase is moved back to draft (unlikely) or deleted (more likely), the total duration calculations should update automatically)

**Comment by RishiRajSahu** [comment]
@rmjmccormick thanks for confirming !, and yes agree to what you mentioned regarding responsiveness of data shown wrt to any changes in phases I had that in mind too.

**Comment by RishiRajSahu** [comment]
@rmjmccormick fixed and pushed to dev with https://github.com/appirio-tech/connect-app/commit/7af60b119ac9402e5c3b6062d080a3e0c5121fe6. All mentioned in above 3 points is taken care.
