### ISSUE TITLE
Sorting not working on status date

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#217]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. go to project listing page
4. click on status date column

Expected Result: sorting must be working on column
Actual Result: sorting not working

![image](https://cloud.githubusercontent.com/assets/16131461/18929242/54019f5c-85e1-11e6-9308-bb4fe5736d9c.png)

**Comment by fnisen** [comment]
@mahestro we can allow this one.

**Comment by parthshah** [comment]
Fixed
