### ISSUE TITLE
Long project description causing screen freeze on mobile - Hot Fix

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2171]
For the project-6362 which has very long description is causing the dashboard UI to be freeze while rendering.

**Comment by RishiRajSahu** [comment]
hot-fixed with https://github.com/appirio-tech/connect-app/pull/2169

**Comment by vikasrohit** [comment]
Thanks @RishiRajSahu and @maxceem for acting quickly on it.
