### ISSUE TITLE
Routing notifications

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2175]
With the new project plan screens our old routing for notifications doesn't work properly. All topic/post notifications lead to project dashboard, but the topic could be in one of the project plan screens, not the dashboard.

We don't send phaseId when generating events for notifications so it is a bit hard to keep track where exactly a notification should lead to. Any ideas @vikasrohit @maxceem @RishiRajSahu

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-468

**Comment by vikasrohit** [comment]
@gondzo we have phase id inside the tag field of the topic e.g. a topic for phase id 123 would have tag `phase#123`. Could we use that property to locate the exact topic/post on the project plan page?

**Comment by gondzo** [comment]
Yup, we can use that, we just have to update message service to send tags to the bus and update tc-notifications to parse tags into phaseId.

**Comment by vikasrohit** [comment]
Okay. Let me know if we can get that done via task, if not I can do those changes tomorrow.

**Comment by gondzo** [comment]
will be done via task, along with #2178

**Comment by vikasrohit** [comment]
@gondzo can we close this separately from #2178? It would allow us to keep #2178 from out of scope of current release.

**Comment by maxceem** [comment]
@vikasrohit having this issue implemented will let us work on other issues related to phase post notifications:
- https://github.com/appirio-tech/connect-app/issues/2604
- https://github.com/appirio-tech/connect-app/issues/2177
- https://github.com/appirio-tech/connect-app/issues/2575

Do you think it would be better to handle it ourself or via F2F?

**Comment by vikasrohit** [comment]
@maxceem I am okay with any of the approaches as it should be trivial to add the support for sending the tags of the topic with every bus event payload.

**Comment by vikasrohit** [comment]
@maxceem can we work on this now?

**Comment by maxceem** [comment]
@vikasrohit yeah, will take care about it.

**Comment by maxceem** [comment]
@vikasrohit I've created a PR for tc message service: https://github.com/appirio-tech/tc-message-service/pull/87

Currently, `tc-notifications` service already includes the whole message payload into notification content https://github.com/topcoder-platform/tc-notifications/blob/dev/src/app.js#L53

So the notification content will look like this:
```json
{
  "tags": [
    "phase#123"
  ],
  "userId": "40011578",
  "phaseId": "123", // this we can add, but looks like there is no need
  "topicId": 10,
  "migration": true,
  "projectId": "1",
  "timestamp": "2019-03-20T05:01:58.168Z",
  "topicTitle": "phase.name",
  "userHandle": "magrathean",
  "postContent": "post body",
  "projectName": "test",
  "userFullName": "F_NAME L_NAME",
  "initiatorUser": {
    "handle": "magrathean",
    "status": "ACTIVE",
    "userId": 40011578,
    "lastName": "L_NAME",
    "firstName": "F_NAME"
  },
  "toTopicStarter": true,
  "initiatorUserId": "40011578"
}
```

So I propose to not extract `phaseId` inside notifications service and handle it inside Connect app instead. 
Because anyway, we will get `tags` in Connect app. Also, Connect already knows about the `tags`, while tc-notification so far is now aware of what is inside tags so we would keep it uncoupled.

**Comment by vikasrohit** [comment]
Yep, Agreed. We are already in efforts to decouple the `tc-notifications` from connect specific logic. So, this would help in those efforts.

**Comment by maxceem** [comment]
@vikasrohit I think we can treat this issue as fixed:
- we send `tags` from message service now and get in Connect App
- in this commit https://github.com/appirio-tech/connect-app/commit/8dcd19220114016b3376f9e6d7d59f609ce4ceac I've implemented conditional routing depend on if notification for `dashboard post` or `phase post`

For now, notification about `phase post` scrolls to the phase, but not yet open Discussion tab and doesn't yet open/scroll to particular post. This would be handled in a separate issue https://github.com/appirio-tech/connect-app/issues/2575.

**Comment by vikasrohit** [comment]
👍
