### ISSUE TITLE
[$50] Specification of a delivered phase should be read-only

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2184]
We don't want customers to be able to change the specification after the phase is started (active and delivered) - this would reduce the value of our records and any potential disputes that might arise.

**Comment by andela-jomadoye** [comment]
The approach I used to solve this was to disable the `Save changes` button on the project specification page whenever the project is active or completed. hence the user cannot make any changes by saving his/her updates.

**Comment by vikasrohit** [comment]
We should disable the complete form when the phase status is `completed`.
