### ISSUE TITLE
[$40] Update end date of a phase when a phase is marked as delivered

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2187]
Continuing from #2183, only thing in the scope of this issue is to update the end date when user is marking a phase completed.

fyi @rmjmccormick @RishiRajSahu

**Comment by vikasrohit** [comment]
@rmjmccormick Do we need this feature after reading [comment](https://github.com/appirio-tech/connect-app/issues/2183#issuecomment-404394049)?

**Comment by rmjmccormick** [comment]
> we found that we can utilize the actual end date (which are keeping as a separate field in each milestone as completion date) to determine when the phase was actually delivered. 

@vikasrohit Yes, this should work. To test my understanding, with the new milestones, if a project ends "on time" (i.e. neither earlier nor later than planned) actual end date = completion date?

**Comment by rmjmccormick** [comment]
![image](https://user-images.githubusercontent.com/39598852/42818096-46df99ce-89d0-11e8-964d-2ad8fd183dce.png)

@vikasrohit - we are looking to remedy this type of situation essentially (instances in which projects are delivered before their planned end date...)

**Comment by andela-jomadoye** [comment]
Just to clarify @gondzo.

When the user delivers a project phase, you want to update the EndDate of the phase in the redux store with the current time the phase was delivered?

**Comment by sumitdaga** [comment]
@rmjmccormick  @gondzo 
what if a phase is in planned stage and is marked as delivered?

**Comment by rmjmccormick** [comment]
@sumitdaga the user journey you describe should never happen. The correct journey is planned --> in progress --> delivered. 
Given the flexibility in the UI, it is technically possible for co-pilots to go directly from planned --> delivered but they should not be doing this.

**Comment by jomadoye** [comment]
Hi @Gauravseta Are you still working on this?

**Comment by Gauravseta** [comment]
@jomadaye yes

**Comment by gondzo** [comment]
@Gauravseta any progress on this task?

**Comment by Gauravseta** [comment]
@gondzo yes working on it.will post minor doubts in few hrs.

**Comment by Gauravseta** [comment]
@gondzo kindly check the PR.

#2239

**Comment by Gauravseta** [comment]
@gondzo payments are  not reflected yet in my profile whereas it has been marked PAID. can you please check?

**Comment by Gauravseta** [comment]
@gondzo sorry .its being reflected now. thanks
