### ISSUE TITLE
[$100] New component for tiled checkbox group is needed

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2188]
We need a new component in react-components repo for enabling users to select multiple options from the available options. UI should be similar to the existing tiled-radio-group component.

fyi @gondzo

**Comment by gondzo** [comment]
The component should be added to https://github.com/appirio-tech/react-components/tree/feature/connectv2/components

**Comment by vikasrohit** [comment]
It would be great if we can reuse some of the code from the `tiled-radio-group` component to allows us changing only in one place for updating the styles of both tiled radio and tiled checkbox components. May be just have one component and control the multi selection with a prop? @gondzo what do you think?

**Comment by gondzo** [comment]
Agreed, it's easier to modify the tiled-radio-group than create a new component from scratch

**Comment by gondzo** [comment]
Default properties should be added so the component stays as is if no new properties are passed by the caller (we don't want to modify all code that already uses tiled-radio-group)

**Comment by jomadoye** [comment]
@amitpatra are you still working on this :-)?

**Comment by gondzo** [comment]
This is now open for pickup

**Comment by vikasrohit** [comment]
Just a health check, are things good with this task? Any questions or clarifications needed?

**Comment by meggamind** [comment]
@vikasrohit  I'm just setting up to use the reac-components library locally. 
Any page that I can direct to in the connect app to look at current check box?

**Comment by vikasrohit** [comment]
Currently we are using standard checkbox component which you can see in Specification tab of `Website Development` phase under `Development Specification` section of project https://connect.topcoder-dev.com/projects/6583/plan. Similarly you can see the current tiled radio group in action in the same project's same phase but in `Design Specification` section.

**Comment by meggamind** [comment]
Oh sorry I meant tiled radio. Thanks

**Comment by meggamind** [comment]
@vikasrohit  I'm supposed to use 'feature/connectv2' branch right? I'm not able to compile react-components library. npm run dev or npm build dev. 

ERROR in Cannot find module 'coffeescript'
 @ ./example.js 13:0-35

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 13:13-35

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 105:27-79

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 108:28-82

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 109:27-79

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 110:36-97

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 112:23-67

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 114:26-76

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 115:21-61

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 116:26-76

ERROR in Cannot find module 'coffeescript'
 @ ./components/Router/Router.jsx 117:22-64

ERROR in Cannot find module 'coffeescript'
 @ ./components/SearchBar/SearchBar.jsx 21:14-41

**Comment by meggamind** [comment]
@vikasrohit Any idea how am i supposed to use the react component locally?

**Comment by vikasrohit** [comment]
You can follow the instructions mentioned in the README to start the example app on your local. It should have many of the components listed there. If tiled radio is missing, you can add that to the example app by adding the new component examples in ExampleNavContainer component.

**Comment by Gauravseta** [comment]
@gondzo can i try with this? if @meggamind dont wish to

**Comment by meggamind** [comment]
@Gauravseta I'm still working on this.

**Comment by gondzo** [comment]
@meggamind any progress on this one?

**Comment by jomadoye** [comment]
I am available to work on this :-)

**Comment by meggamind** [comment]
@gondzo Adding example in the react-components, give me 3 hours

**Comment by meggamind** [comment]
@gondzo  I don't have permission for react-components project. Can you grant me access I want to make the PR

https://github.com/appirio-tech/react-components/tree/feature/connectv2/components

**Comment by vikasrohit** [comment]
Permission added. You can fork and create PR now.

**Comment by meggamind** [comment]
@gondzo @vikasrohit  

https://github.com/appirio-tech/react-components/pull/289

**Comment by meggamind** [comment]
@vikasrohit @gondzo PR is up for this please let me know if any change is needed
