### ISSUE TITLE
Progress bar at the sidebar is not dynamically updating on changes

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2189]
This can be reproduced in [dashboard-improvements](https://github.com/appirio-tech/connect-app/tree/feature/dashboard-improvements) branch where the progress bar is shown in the sidebar.

For example this project http://local.topcoder-dev.com:3000/projects/6436/plan

If we edit some phases we will see the effect on the big progress bar, but progress bar at the sidebar won't be updated until we reload the page.

There are two things causing this issue:
1. `shouldComponentUpdate` in `ProjectInfoContainer` prevents component from redrawing, which can be easily fixed by adding `|| !_.isEqual(nextProps.phases, this.props.phases)`. 
2. The upper fix is not enough because during phase editing, `UPDATE_PHASE_SUCCESS` reducer mutates state, so upper check doesn't have any effect.

**Comment by maxceem** [comment]
I've fixed the 2nd item in the `dev` branch as it's a general issue, I've created [PR](https://github.com/appirio-tech/connect-app/pull/2191)

After the PR is merged to the `dev` branch. I can merge `dev` branch into `feature/dashboard-improvements` and fix the first item of this issue.

**Comment by maxceem** [comment]
Fixed item 1 via https://github.com/appirio-tech/connect-app/commit/5b2ce9bff45023e4f7301a76112dca8f8d15f348

So it's done.

**Comment by RishiRajSahu** [comment]
Closing as pushed to dev . fyi @vikasrohit @rmjmccormick
