### ISSUE TITLE
Select a product  button not visible in Mobile UI

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2190]
**Expected behavior : 
Describe :**

Adding a phase should ask user to select a product for the phase.

**Actual behavior :
Describe:** 

Select a product button not visible, when user adding a new phase in Mobile UI

**Screen Shot for reference :**

![select a product button not visible in mobileui](https://user-images.githubusercontent.com/30447858/42632473-eb71655a-85fa-11e8-8a7a-0fd38b72fddb.PNG)

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please fix the above issue.

**Comment by vic-topcoder** [comment]
The button should be visible only on a hover in the card (white with drop shadow)

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 As per design, button should be visible on hover only. won't fix. closing.
