### ISSUE TITLE
Edit post functionality on Project dashboard

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2193]
When editing a post in Project dashboard, the button I click on to validate the edits in the post should read "Update post" NOT "Update title". See below screenshot.

![image](https://user-images.githubusercontent.com/39598852/42692139-e594f466-86aa-11e8-9936-b75446524fe0.png)

**Comment by RishiRajSahu** [comment]
@rmjmccormick fixed this issue with https://github.com/appirio-tech/connect-app/commit/6c5ecd10788bf576ba0af57bc4b4e0d2c24cac2d. Please verify and feel free to close.

**Comment by rmjmccormick** [comment]
Looks good @RishiRajSahu
