### ISSUE TITLE
Reload only the update phases section

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2195]
### Expected behavior
It should reload only the phases section instead of providing the the Reload button to reload the complete page when user has edited the start date or duration of a phase in a way which changes the order of the phases. It should have TBD transition.

### Actual behavior
Right now we are showing a button to reload the complete page when phase is updated for start date or duration.

### Steps to reproduce the problem
- Update start date or duration of any phase in project plan of a project
- Notice, we are showing a button to reload the complete page (it is implemented as per #2110)

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot, Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
Designs for the transition are needed to proceed further.

**Comment by vic-topcoder** [comment]
moved to productboard
