### ISSUE TITLE
Rendering milestone(s) only if required to be part of timeline

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2196]
There are milestones associated with timeline which needs to rendered in specific scenarios otherwise not. 
For eg.` final-fixes` milestone will be required only if in the delivery milestone user asks for final fixes else not. we need to take care of rendering of such milestones and having `hidden:true` flag in their templates

Backend changes needed are tracked here - https://github.com/topcoder-platform/tc-project-service/issues/111

fyi @vikasrohit @rmjmccormick

**Comment by maxceem** [comment]
This is done by the next commit https://github.com/appirio-tech/connect-app/commit/923a32fc7f7f9a0c8db2cf08c60ea2e190bbe125#diff-39dc6ecd00afee3bae091cb2f2181199R72 and already in the `dev` branch.
