### ISSUE TITLE
[$35] Post contents - link & mention styling

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2201]
- [x] Links styling is broken in the latest connect, it's displayed as a black text and no underline
![image](https://user-images.githubusercontent.com/3051646/42900409-1f18894c-8ac9-11e8-9f06-5df233024d72.png)
- [x] @mention - (should be bold)

continued from https://github.com/appirio-tech/connect-app/issues/2301

**Comment by vikasrohit** [comment]
Thanks @gondzo  for reporting the issue.

@RishiRajSahu I think it is because of the same cause which prevented the other styles to be broken in dev. Does that fix resides in our 2.4.4 PR?

fyi @rmjmccormick

**Comment by billsedison** [comment]
The link style is also incorrect if I manually add a link to a text. 
![image](https://user-images.githubusercontent.com/5657467/42924902-c9b71b12-8b5e-11e8-80fd-70f6eed6ee53.png)

The link style is correct in the edit mode, but incorrect in the display mode.

Edit mode
![image](https://user-images.githubusercontent.com/5657467/42924945-f1c82fd8-8b5e-11e8-9018-0354c10cc8a5.png)


Display mode
![image](https://user-images.githubusercontent.com/5657467/42924964-0afd398a-8b5f-11e8-90b1-22f79c9d67b1.png)

**Comment by maxceem** [comment]
Could you please mention what is desired style for this link?
1. normal style
2. hover style

Currently, during editing the link color is `#5e93c5` which is not on our [palette](https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss). And on hover the color becomes `#7eadda` which is not on out palette too. And there is no underline.

I cannot grab the color from the marvel as it doesn't have handoff styles for the link https://marvelapp.com/8a94680/screen/45153777/handoff 

cc @vikasrohit

**Comment by vikasrohit** [comment]
@maxceem I think we need to use https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_buttons.scss#L13 or https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_buttons.scss#L164. Former one requires setting of color for the links in non hover mode as well because somehow that is missing in `tc-ui` as of now. Essentially, I think, link should be rendered as we are rendering them in `Links` section in the left panel of the dashboard.
@vic-topcoder correct me if I am wrong here.

**Comment by khushimehta03** [comment]
@maxceem I am working on this issue, please assign it to me , thanks

**Comment by khushimehta03** [comment]
@maxceem please release me ,so it is open again,as i wont be able to complete.

**Comment by Gauravseta** [comment]
@maxceem can you please assign it to me as it is open for pickup. thanks

**Comment by maxceem** [comment]
Sure @Gauravseta it's yours.

I've also sent an invitation for you to this repo so I could also assign you to the issues for clearance.

**Comment by Gauravseta** [comment]
<img width="575" alt="2201" src="https://user-images.githubusercontent.com/16337895/45382999-97b4fa00-b627-11e8-8fb4-c45cc887d733.png">


it has been made similar to links color on left side panel.
@maxceem raising PR for it

**Comment by Gauravseta** [comment]
@maxceem PR raised

**Comment by maxceem** [comment]
@Gauravseta I've reviewed the PR, please have a look https://github.com/appirio-tech/connect-app/pull/2502#pullrequestreview-155332373

**Comment by maxceem** [comment]
@Gauravseta FYI. There was a commit done to the `cf12` branch connected to the second part of this issue making `@mention` bold. I think the change in that commit will help you to make mentions bold, see https://github.com/appirio-tech/connect-app/blob/cf12/src/components/Feed/FeedComments.jsx#L288
So don't forget to pull the latests changes from `cf12`.

I think it should be enough to adjust this line
```
itemContent = itemContent.replace(mardowLink[0], mardowLink[1])
```

This line now replaces mention link with text. While we can replace link with `**link text**`, as double ** makes text bold in Markdown syntax.

**Comment by Gauravseta** [comment]
@maxceem sure will see immeditaly

**Comment by Gauravseta** [comment]
@maxceem i am able to transform it into bold for first occurrences , but not if it is repeated again in the line later. working on this as well as my other issue

**Comment by maxceem** [comment]
@Gauravseta ah, good catch. Thanks for having a look on that. Most likely modificator `g` have to be used together with `.exec` method of regexp to find all matches. See https://stackoverflow.com/questions/6323417/how-do-i-retrieve-all-matches-for-a-regular-expression-in-javascript
