### ISSUE TITLE
[Add a Team Member] - the image is not displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#221]
Expected behavior

- The team member image is not displayed.

Actual behavior

- Display the image in section.

Steps to reproduce the problem

- Login into application as manager.

- Edit any existing project(own project).

- Set focus on Add a Team Member and select a member(eg. test0828).
 

Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: pat_monahan

![member-team](https://cloud.githubusercontent.com/assets/5114907/18929445/2a302e8c-85cd-11e6-92f4-e90dd3914e60.png)

**Comment by fnisen** [comment]
Likely a bug in the Dev environment
