### ISSUE TITLE
Connect logo is not aligned on "Add a New Phase" popup

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2215]
When creating a new phase on the project plan page, logo is not aligned with the close button.

![image](https://user-images.githubusercontent.com/146016/42993397-d68b7ace-8c3d-11e8-81ce-9507898890af.png)

**Comment by vikasrohit** [comment]
Thanks @maxceem for reporting this. Would like to provide a quick fix for this or we can move this to the next milestone.

**Comment by vikasrohit** [comment]
Working fine. Closing.
