### ISSUE TITLE
[$60] Delete topic option

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2217]
### Expected behavior
There should be a delete topic option on the dashboard

### Actual behavior
There is only edit topic title in the dashboard stream

![image](https://user-images.githubusercontent.com/3051646/43001070-325c25ac-8c24-11e8-833e-53123e0add1a.png)

**Comment by vikasrohit** [comment]
@gondzo I have moved this to CF 10.

**Comment by andela-jomadoye** [comment]
@gondzo  @vikasrohit For this ticket do you also need the functionality of the delete topic to be implemented? or you just want a delete topic option to be displayed.

**Comment by gondzo** [comment]
Implement the full feature
