### ISSUE TITLE
Cannot see "submit" button when creating a post on a mobile device

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2220]
On the mobile devices when we add post we don’t see the Submit button initially, we have to scroll to it see screencast http://take.ms/RZewv. This comes from the fact that browser counts the height ignoring top and bottom panels which can be dynamically hidden during scrolling.

I’ve already raised it before https://github.com/appirio-tech/connect-app/issues/2131, but that time I got a response that we can skip that for now. Probably it makes sense to raise it again.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-397

**Comment by vikasrohit** [comment]
@maxceem do you think you have a quick fix for the issue? If yes, I would keep it in 2.4.4, otherwise will move this issue to the next milestone.

**Comment by maxceem** [comment]
@vikasrohit probably this would require some research. It has to deal with some mobile browsers peculiarities.

**Comment by vikasrohit** [comment]
Got it. Moving to next release.

**Comment by RishiRajSahu** [comment]
working fine on dev.
