### ISSUE TITLE
Post title appears out of the post title field

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2224]
**Expected behavior :** 
Describe : Post title should not appears out of the post title field.

**Actual behavior**
Describe.
Post title appearing out of the pos
![validate the post title field maximum characters appears out of the post field](https://user-images.githubusercontent.com/30447858/43082765-73bd27c2-8eb2-11e8-8a2b-904d54d849c9.PNG)
t title field

Screenshot/screencast
Attach or link a resource.

**Comment by RishiRajSahu** [comment]
@DeepakAnbarasa : Few things to be noted - 
1.The string you put for title is long string without **_spaces_**, if title has spaces between the words it won't appear out of the post UI.(anyway longest word of english could be accommodated with in the title and it won't appear out)
2.Special characters are allowed in topic title -  as it sometimes needed for example `!` is needed in welcome posts(would be helpful if you specify which subset of special chars to be allowed)
3.Currently there is not limit on title length, and it won't appear out of UI as long as spaces are present between english words

**Comment by RishiRajSahu** [comment]
Able to create topic with special char mentioned in Description, Yes user can enter special chars, may be it was due to some network issue. 
![screen shot 2018-07-24 at 2 20 24 pm](https://user-images.githubusercontent.com/11248478/43127338-e48c164e-8f4c-11e8-8b76-9a949d0db67b.png)

**Comment by rmjmccormick** [comment]
@deepakanbarasan1 @RishiRajSahu I am comfortable with the UI as is. The likelihood of a user wishing to enter a single uninterrupted line of characters as a title is very remote, so I see no need to limit the title length. Thanks both.
