### ISSUE TITLE
[$90] Calculate progress of phases based on number of completed milestones

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2226]
We should now calculate the progress of a phase which active and has milestones, by calculating the duration of completed milestones against total duration of milestones.

fyi @RishiRajSahu @rmjmccormick

**Comment by RishiRajSahu** [comment]
@mhikeo you can create new website or VD kind of project.

**Comment by gondzo** [comment]
@mhikeo are you still working on this?

**Comment by mhikeo** [comment]
@gondzo Yes. I will be pushing in 2 hours.
