### ISSUE TITLE
Rendering Timeline's Milestones when startDate of phase is NULL

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2229]
Below two scenarios to be considered while rendering timeline and milestones.

1. When startDate is Null - 
      Don't consider the date values present in timeline and milestone objects instead use system current date same as phase to render them

2. When startDate of phase is updated  - 
      Update the startDate of timeline and milestone as well, and render considering the date values persisted

**Comment by KevinLeigh** [comment]
@gondzo Hey there, I take it the changes for this issue will be off of `feature/timeline-milestone` ?

**Comment by gondzo** [comment]
Yes, all issues in this challenge are based on that branch

**Comment by RishiRajSahu** [comment]
@KevinLeigh keeping this issue on hold for now, will update you sooner.

**Comment by KevinLeigh** [comment]
@RishiRajSahu Sure all good, thank you for the update.

**Comment by KevinLeigh** [comment]
@RishiRajSahu Hey there, any update on the above issue?

**Comment by RishiRajSahu** [comment]
@KevinLeigh closing this ticket as we have changed the functionality at backend to always have startDate set, so this case won't arise anymore to handle null startDate.
fyi @vikasrohit

**Comment by KevinLeigh** [comment]
@RishiRajSahu Thank you for the update, much appreciated

**Comment by KevinLeigh** [comment]
Its better that way :)

**Comment by RishiRajSahu** [comment]
@KevinLeigh there will be more issues related to timeline-milestones feature, so keep an eye. :)
