### ISSUE TITLE
[$60] Don't include hours when persisting date fields for timeline and milestones

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2230]
Right now, when a POST call for timeline and milestone is made the hours are also getting persisted along with date, need to remove hours from the timestamp getting persisted.

**Comment by KevinLeigh** [comment]
Hey there, where are timeline and milestones POST request being called?

**Comment by gondzo** [comment]
All api calls are detailed here - https://github.com/appirio-tech/connect-app/tree/feature/timeline-milestone/src/api

**Comment by KevinLeigh** [comment]
@gondzo Thank you for the update, will I have to create PR from `feature/timeline-milestone` ?

**Comment by gondzo** [comment]
Yes

**Comment by KevinLeigh** [comment]
@gondzo Thank you for the update, I have created PR addressing this issue.
