### ISSUE TITLE
[$20] Add link button text

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2232]
Add link button text should be `Add link` instead of `Adding link` 

![image](https://user-images.githubusercontent.com/3051646/43139471-14137966-8f52-11e8-838d-3a6f2cd55245.png)

**Comment by jomadoye** [comment]
@Manoj85 No need to raise empty PR.
@gondzo You should clear your cache, this typo does not exist on the master branch. This issue is unable to reproduce.

**Comment by jomadoye** [comment]
@Manoj85 I see you raise empty PR, if you cannot fix this issue please assign me as I have some spare time now, and would want to work on it, thanks
cc @gondzo
