### ISSUE TITLE
Delivery milestone - manager and copilot views

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2233]
Managers and copilots don't have any useful info in the delivery milesone
![image](https://user-images.githubusercontent.com/3051646/43140338-0f79e640-8f54-11e8-8895-da9b21ace5ac.png)

@RishiRajSahu should we just display some custom message here for managers and copilots?

**Comment by vic-topcoder** [comment]
Managers are supposed to upload the final deliverable into the milestone to complete it

**Comment by gondzo** [comment]
OK, let's show the same interface for managers as customers here.
Same thing for copilots @vikasrohit ?

**Comment by vic-topcoder** [comment]
Yes - in this case we have to show a message to the copilot that the customer is presented with a choice.

**Customer view**:
![screen shot 2018-07-27 at 12 03 08 pm](https://user-images.githubusercontent.com/8484061/43341816-79cbc1ec-9195-11e8-9c30-8c9c12055f45.png)

**Copilot view**:
![screen shot 2018-07-27 at 12 05 34 pm](https://user-images.githubusercontent.com/8484061/43341830-8181bea0-9195-11e8-8dd3-549ced894b56.png)


@rmjmccormick @acshields  please advise on the language. For the time being I put "The customer has yet to respond to the final deliverable accetance. Please communicate with them if there’s a problem and they need help to make the final decision. Once they respond you’ll see a link to upload the final deliverables here." 

It might be good to customize the milestone description per user role as well. In that case
> "We completed all the development successfully. Once **you accept** the code we will deliver the final source files as a ZIP compressed folder here."

 can be modified to explain to the Copilots what is going on and we can transform it to 

> "We completed all the development successfully. Once **the customer accepts** the code we will deliver the final source files as a ZIP compressed folder here."

**Comment by rmjmccormick** [comment]
@vic-topcoder 
Just correcting a small typo:

"The customer has yet to respond to the final deliverable acceptance. Please communicate with them if there’s a problem and they need help to make the final decision. Once they respond you’ll see a link to upload the final deliverables here."

**Comment by vikasrohit** [comment]
Done and deployed to dev.
