### ISSUE TITLE
Project plan progress reporting - logic updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2234]
So, we did start fixing the project plan progress bar. The logic is not yet finalized as I see it, because we show progress bar even if no phase actually had started work. It makes no sense to show progress for an activity that hasn't started yet.

![screen shot 2018-07-24 at 9 37 55 am](https://user-images.githubusercontent.com/8484061/43153228-8b5a5f62-8f25-11e8-846a-e3c459174d93.png)

Can we expand the logic behind when the customer is going to see a project progress bar?

- If a project has all the phases in planned state, the work hasn't started. We show no progress bar.
- If a project has an active phase, work is under way and we show progress bar.
- If a project has all the work completed (all phases are delivered) we do not show progress bar.

Also - when there's a progress bar, do not show items that have no value `NaN% done` should never be displayed.

**Comment by vikasrohit** [comment]
Can we simplify the logic by hiding the progress bar for customer whenever the progress is 0? Does that misses any edge case?

fyi @rmjmccormick @acshields

**Comment by RishiRajSahu** [comment]
@vic-topcoder fixed this and pushed to dev. Showing progress bar only if there is at-least one active phase for a project otherwise not.

**Comment by vikasrohit** [comment]
Okay. I think @RishiRajSahu made changes as per your suggestion.

**Comment by vic-topcoder** [comment]
Great, thanks guys!
