### ISSUE TITLE
[$80] Show the confirmation modal before accepting the final deliverables

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2235]
as per designs we need to show the modal
<img width="596" alt="screen shot 2018-07-25 at 11 49 36 am" src="https://user-images.githubusercontent.com/2417632/43183275-28afa8ee-9002-11e8-8a0c-308043d2ffb1.png">
before recording the response of the customer for accepting the designs.
It needed to be asked for both design delivery and code delivery but with different texts.

For design flow see https://marvelapp.com/8a94680/screen/41373095
For dev/code flow see https://marvelapp.com/8a94680/screen/45398424 (it does not show the confirmation modal but we need to show a similar confirmation modal we are showing for design delivery.)

Note: We might need create a new milestone type now for code delivery to have different text in the confirmation modal. If that is the only option to fix the issue, we should try to reuse the common functionality between design and code delivery milestones.

fyi @RishiRajSahu @gondzo @acshields @rmjmccormick

**Comment by rashmi73** [comment]
@gondzo i wish to work on it. please assign it to me.because i am not able to assign it.I have started working on this.

**Comment by gondzo** [comment]
@rashmi73 You have to accept the invitation in your email first

**Comment by rashmi73** [comment]
@gondzo @vikasrohit can you please tell exactly on which click dialog is to be shown? I am bit confused. also currently where similar modal is shown?

**Comment by gondzo** [comment]
When the customer clicks on the 'Complete Review' button. That should be handled in the MilestoneTypeFinalDesigns component - there are examples of confirmation dialog in that same component (DotDialog)

**Comment by rashmi73** [comment]
@gondzo i am working on it..was not able to connect to backend hence development stopped.

**Comment by meggamind** [comment]
@gondzo @rashmi73  Confused, should I work on this or no?

**Comment by rashmi73** [comment]
@meggamind as it was open for pickup and u assigned urself so it goes to you for 24hrs.I am working simulatenously too as i already started,if u fail then atleast i can raise PR.

**Comment by meggamind** [comment]
ok I'll start working on it

**Comment by meggamind** [comment]
@gondzo  I changed a couple of flags to show the button and I could see the confirmation dialog. So I'm guessing if the issue exist might be because of the wrong phase or something. Can you please make a project which has that button and does not show the confirmation dialog? 

<img width="777" alt="screen shot 2018-07-29 at 5 09 02 pm" src="https://user-images.githubusercontent.com/10702944/43372117-232c1b84-9352-11e8-9560-ccd3ceeafebb.png">

**Comment by vikasrohit** [comment]
@meggamind Please see the original issue description. The modal you are sharing is not the one we are concerned. The modal we want to add, comes in Delivery milestone when customer is about to accept the deliverables. To reach to that point you can create any design project and follow its milestones till end and you would see the place where there is button `Complete review` for customers, we need to show this modal on click of that button to prevent accidental completions of milestones.

**Comment by vikasrohit** [comment]
@meggamind @gondzo we need to wrap the tasks in next 12-18 hours. Let me know if it is still possible for this task, otherwise we might have to remove it from bug bash.

**Comment by meggamind** [comment]
@vikasrohit  I reach this screen and then how do I move from one milestone to another to see those buttons? 

<img width="805" alt="screen shot 2018-07-30 at 1 52 09 am" src="https://user-images.githubusercontent.com/10702944/43387401-30b5d60c-939b-11e8-922a-252bf1b008ff.png">

**Comment by meggamind** [comment]
@vikasrohit Sorry but I'm again confused. @gondzo in the above messages said that the fix is needed in MilestoneTypeFinalDesigns component, but from what I understand from your comment and the title is that the fix is needed in MilestoneTypeDelivery component. The last milestone as shown in the image above. Is that correct? if so so the fix is to add the complete review button (which does not exist in MilestoneTypeDelivery component as of now), along with the modal which is then followed by the 'design acceptance' modal with 'request review' and 'Mark as completed' buttons?

**Comment by vikasrohit** [comment]
My bad @meggamind @gondzo is correct here. It needs changes in `MilestoneTypeFinalDesigns` component.

**Comment by vikasrohit** [comment]
Also, there is some bug right now in the API which is causing the milestones not in active state. Let us know your test project id, we can make them active from backend.

**Comment by meggamind** [comment]
the bug might have something to do with milestone status always being as reviewed
Project ID - 6744

**Comment by meggamind** [comment]
@vikasrohit So does this look good ?
<img width="858" alt="screen shot 2018-07-30 at 3 17 54 am" src="https://user-images.githubusercontent.com/10702944/43392111-7ddd01d8-93a7-11e8-8a4a-f759e427f63b.png">

**Comment by vikasrohit** [comment]
Yes, it is because of that. We are making changes to complete that functionality. Your project now should have active milestone.

**Comment by vikasrohit** [comment]
@meggamind the modal you shown is for `checkpoint-review`, we need different text and colors for `design-review` milestone.
https://user-images.githubusercontent.com/2417632/43183275-28afa8ee-9002-11e8-8a0c-308043d2ffb1.png

**Comment by gondzo** [comment]
@meggamind all projects should have the first milestone activated now. all you need to do is set the phase to 'In Progress'

**Comment by meggamind** [comment]
https://github.com/appirio-tech/connect-app/pull/2252

**Comment by meggamind** [comment]
@vikasrohit @gondzo PR is up for this let me know if any change is needed

**Comment by gondzo** [comment]
@vikasrohit IMO what's left here is to customize the message in delivery milestone. Should we introduce a new milestone type `delivery-dev` and customize the message based on type? We don't need to add a new milestone component to do that.

**Comment by gondzo** [comment]
oh, I didn't notice this is already discussed in 2267. Closing this one
