### ISSUE TITLE
Enabling Project Feature fails and crashes app, requiring browser refresh

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/connect-app#224]
In Project specification under the add/edit features section, if you select any menu option from the left menu, click the enable toggle, and fill in the Notes.. input too quickly, then click another option from the left menu, it gives a JS error in console and all links/buttons in the app become inoperable, requiring a browser refresh to resume.

### Expected behavior
Enabling a feature and adding to the Notes.. section should not crash the app.

### Actual behavior
Working too quickly enabling a feature crashes the app

### Steps to reproduce the problem
- Create a new project.
- navigate to connectv2.topcoder-dev.com/projects/{xxx}/specification page for project
- Scroll to "feature requirements" section and click "Add/Edit Features" button.
- Click any menu item from the left.
- Click the top-right slider to enable feature.
- Edit the Notes.. input with a few words of text, then click on another option from the menu on the left. (Do this fairly quickly, taking up to a few seconds)
- When other menu item is selected, the checkmark next to the feature you just left disappears, and all links and buttons are now inoperable.
- There is an error in the console:
```javascript
FlattenedFeatureList.jsx:32 Uncaught TypeError: Cannot read property 'categoryId' of undefined
```
### Screenshot/screencast
http://i.imgur.com/BRnr5Qj.png
--

#### Environment
- OS: Win10
- Browser (w/version): Chrome 53
- User role (client, copilot or manager): client
- Account used: christina_uw

**Comment by vikasrohit** [comment]
@parthshah as discussed Removed debounced method and directly put the change handler on the formsy's onChange event. However, I didn't see any benefit of keeping the change handler to formsy form in contrast to keeping it on text area. In both cases, EditProjectForm is re-rendered on every key press of in the text area.

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev now.
