### ISSUE TITLE
Text of the milestone should be displayed as per status of milestone

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2240]
Right now we are showing the 'Dummy text' always for a milestones, we need to render the text of milestone as per the status of milestone.

**Comment by meggamind** [comment]
@RishiRajSahu Is this what is expected? [https://ibb.co/mzNag8](url)

**Comment by RishiRajSahu** [comment]
@meggamind I am updating text in milestone-templates with actual data, will give you heads up once its done.

**Comment by RishiRajSahu** [comment]
Working fine on dev. closing.
