### ISSUE TITLE
Quick Link : Query : Usage of unnecessary empty space in UI

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2242]
Expected behavior : 
Describe : Quick links should be displayed in the same line, Until unless there is no empty in same line.

Actual behavior
Describe.

Quick links are appearing in multiple lines.

Description :

If project have more Channels links, as per current UI users has to scroll more. If it is in single line scroll will be reduced.

Screen Shot  : 
![channels section which provides quick links to the dashboard topics message_empty space](https://user-images.githubusercontent.com/30447858/43265584-c98a20aa-9106-11e8-881e-932ad3f38893.PNG)

**Comment by deepakanbarasan1** [comment]
@vic-topcoder  Please check

**Comment by vic-topcoder** [comment]
The text should use the entire space available - 100% of the parent container.

**Comment by vikasrohit** [comment]
@gondzo I think this hasn't been done yet, handling via tasks.

**Comment by vikasrohit** [comment]
@deepakanbarasan1 changes are deployed to the dev env. Please let us know if does not work for you.

**Comment by vikasrohit** [comment]
@deepakanbarasan1 I am closing it for now, to reduce the number of open issues, as it seems to work fine for me. Please feel free to reopen it if it does not work.

**Comment by deepakanbarasan1** [comment]
@vikasrohit  and @RishiRajSahu  Looks good in Mobile and WebUI

**Web UI :** 
![quick link query usage of unnecessary empty space in ui _web ui](https://user-images.githubusercontent.com/30447858/43835574-13f7cb28-9b30-11e8-96f7-63e119e0590c.PNG)

**Mobile UI :**
![quick link query usage of unnecessary empty space in ui _mobile ui](https://user-images.githubusercontent.com/30447858/43835598-266bb198-9b30-11e8-9eea-57f24255df39.PNG)

**Comment by vikasrohit** [comment]
Thanks @deepakanbarasan1 for verification.
