### ISSUE TITLE
[$50] Milestone contents are out of bounds

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2246]
### Expected behavior
Milestone contents should be within the parent container

### Actual behavior
Milestone content overflows the parent container if the text is long

![image](https://user-images.githubusercontent.com/3051646/43328888-6c5efe8c-91bf-11e8-86a3-34586cd033ee.png)

Test the UI for all cases, after fixing the issue for both Website and Visual Design projects

**Comment by vikasrohit** [comment]
Good catch @gondzo

**Comment by PrakashDurlabhji** [comment]
@gondzo @RishiRajSahu can you please check why loader keeps on loading ? is there any issue at backend or front end?

while visitng any project.
e.g. http://localhost:3000/projects/6731

took latest from "feature/timeline-milestone".
please guide asap

**Comment by gondzo** [comment]
fixed @PrakashDurlabhji , api was returning an error message

**Comment by PrakashDurlabhji** [comment]
@gondzo everything has been implemented by me..waiting for your approval.

**Comment by gondzo** [comment]
first option seems the best. if the url cant fit in the first line, it should move to the second line.

**Comment by RishiRajSahu** [comment]
@PrakashDurlabhji yeah agree with @gondzo suggested, if its done on your side please create a PR.

**Comment by PrakashDurlabhji** [comment]
@RishiRajSahu yes its done.will raise PR within half hr

**Comment by PrakashDurlabhji** [comment]
@RishiRajSahu @gondzo PR has been raised.
#2250

**Comment by PrakashDurlabhji** [comment]
@gondzo @RishiRajSahu @vikasrohit  again backend not giving data? did anyone changed backend?

**Comment by vikasrohit** [comment]
@PrakashDurlabhji it might be because we are continuously working on the backend fixes as well. Please let me know if you it is blocking any Work In Progress for you. Also, please let me know which endpoint is not giving results.

**Comment by RishiRajSahu** [comment]
@PrakashDurlabhji URL which you put on next line should be aligned properly with the title.

<img width="802" alt="screen shot 2018-07-30 at 4 36 46 pm" src="https://user-images.githubusercontent.com/11248478/43394366-21b2e320-9418-11e8-924f-c93f2744e07c.png">

**Comment by PrakashDurlabhji** [comment]
@RishiRajSahu @gondzo unable to see milestones under timeline tab. spinner keeps on loading. backend proper?

**Comment by PrakashDurlabhji** [comment]
I guess
action : LOAD_PRODUCT_TIMELINE_WITH_MILESTONES_SUCCESS

doesnt have payload object present because no response is being received from backend hence spinner loading.

@gondzo @vikasrohit @RishiRajSahu can you please look into it on priority so i can proceed. thanks

**Comment by gondzo** [comment]
@PrakashDurlabhji any specific project? they load fine for me at http://local.topcoder-dev.com:3000/projects/6746/plan

please post api endpoint and response details if you have any doubts about the api

**Comment by RishiRajSahu** [comment]
@PrakashDurlabhji create a new project its working fine, I just created VD project successfully.

**Comment by PrakashDurlabhji** [comment]
@gondzo @RishiRajSahu i will try the url u gaveme.
and update PR

**Comment by PrakashDurlabhji** [comment]
@RishiRajSahu @gondzo PR updated.

**Comment by RishiRajSahu** [comment]
Fixed via https://github.com/appirio-tech/connect-app/pull/2250.
