### ISSUE TITLE
[$50] Updating phase to be delivered on completion of last milestone

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2249]
We need to make PATCH call for marking phase as delivered when the last milestone is marked as complete. Also, `Delivered` option from the dropdown of phase status is to be removed.

**Comment by jomadoye** [comment]
@RishiRajSahu Can I start work on this?

**Comment by gondzo** [comment]
@jomadoye yes, I've added the prize details. 
It should be really simple - just call the updatePhase action if updateProductMilestone action is successful with last milestone being updated to the complete status

**Comment by jomadoye** [comment]
@gondzo Please I am still not very clear on this ticket. any extra clarification/details would be helpful.

**Comment by Gauravseta** [comment]
@gondzo shall i work on it?

**Comment by jomadoye** [comment]
@Gauravseta I have un-assigned myself.

**Comment by Gauravseta** [comment]
@gondzo working on it. near to complete it.

**Comment by Gauravseta** [comment]
@gondzo  I hope it is considered in bug bash itself?

**Comment by RishiRajSahu** [comment]
@Gauravseta as per your previous update, if it's completed ? if yes, create a PR for it.

**Comment by gondzo** [comment]
Done and deployed to dev

**Comment by Gauravseta** [comment]
@gondzo apology for delaying it and not even completing , any more issues? i am genuinely interested and wud deliver on time as m in need of money and good knowledge.
