### ISSUE TITLE
Don't show edit icon for completed milestones

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2251]
- [x] User should not be allowed to edit the completed milestones.
- [x] Customers should never be allowed to edit milestones.

<img width="945" alt="screen shot 2018-07-30 at 4 35 02 pm" src="https://user-images.githubusercontent.com/11248478/43393947-908accba-9416-11e8-81c7-3916263f6cbe.png">

**Comment by PrakashDurlabhji** [comment]
@gondzo @vikasrohit any amount for this? thanks

**Comment by PrakashDurlabhji** [comment]
@gondzo @vikasrohit any amount for this? thanks

**Comment by gondzo** [comment]
@PrakashDurlabhji prize info added. please add the PR in the next 12h

**Comment by RishiRajSahu** [comment]
Fixed with https://github.com/appirio-tech/connect-app/commit/74592e9a05ab241d403e66eee9b769c8f3291ed1
