### ISSUE TITLE
Copilots should be able to see phases even if they are unplanned

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2255]
Right now, copilot is also seeing the system message which we are showing to the customers when all phases in the project plan are in unplanned state.

fyi @rmjmccormick @acshields @RishiRajSahu

**Comment by vic-topcoder** [comment]
The Copilots should be able to edit the phase properties as well. This is important as they have to be able to manipulate the phase in order to report progress or update status (duration, cost) for the customer.

**Comment by vikasrohit** [comment]
@vic-topcoder it was false alert. I added a copilot as customer which caused this issue. It requires the user to be added to the team with copilot role.

No fix needed, it is working fine.

**Comment by vic-topcoder** [comment]
Just checked with DaraK, and in fact she can't edit the phase properties. She is a Copilot on the project.

![connect phase](https://user-images.githubusercontent.com/8484061/43547008-df4bcb28-958e-11e8-941a-b7f8e1669143.png)

**Comment by vikasrohit** [comment]
@vic-topcoder I tried with my copilot account on production and it seems to work fine as expected for me. I need some time to debug it more.

**Comment by vic-topcoder** [comment]
thanks!

**Comment by vic-topcoder** [comment]
Yes, it's working now. Thanks!

Just for consistency - what are the privileges that are needed to allow copilots to edit milestones? I was able to add her as a Copilot to the project (which means she has a `copilot` rights). Do we have to verify all our copilots have the rights necessary before we release the milestone interface to the public?

@acshields FYI

**Comment by vikasrohit** [comment]
@vic-topcoder we have a known issue with respect to the addition of a new team member for a project where we can not determine the role of the user being added because we never allow seeing roles of any user by any user (except system administrators not to be confused with any connect specific role), so we can not apply validation when you are adding a non copilot as copilot to the team. However, when that user logs in and tries to see the project, he/she would be limited to non copilot and non manager capacity because he/she does not have required user role.
> Do we have to verify all our copilots have the rights necessary before we release the milestone interface to the public?

Most of the copilots already have appropriate roles, only few exceptions might be there which we can always take care of as adhoc basic. I don't see any reason to wait for that before release.
