### ISSUE TITLE
Customer can see the `Add specification document link` button for specification milestone

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2256]
fyi @RishiRajSahu

**Comment by PrakashDurlabhji** [comment]
@gondzo @vikasrohit wont there be any more open for pickup issues?

**Comment by gondzo** [comment]
not at this time @PrakashDurlabhji

**Comment by maxceem** [comment]
As we are not showing `Add specification document link` to the customer, do we show anything else expect of milestone description? Maybe progress bar so the customer is aware of how long it may take?

<img width="785" alt="screen shot 2018-08-04 at 10 58 25 am" src="https://user-images.githubusercontent.com/146016/43671910-9361f694-97d5-11e8-98f0-07f29d72998c.png">

**Comment by vikasrohit** [comment]
I don't think a progress bar would make sense here. @rmjmccormick @acshields Let me know if you think otherwise.
@maxceem we will create separate issue for handling this if required.

**Comment by maxceem** [comment]
After this fix, there is a new case which didn't happen before where we don't have anything inside milestone expect of the description.

In this case, the blue line looks like has to be completely hidden. This will require some refactoring of the milestone components, will do it here https://github.com/appirio-tech/connect-app/issues/2293

![](https://user-images.githubusercontent.com/146016/43671910-9361f694-97d5-11e8-98f0-07f29d72998c.png)

**Comment by rmjmccormick** [comment]
@maxceem @vikasrohit @acshields A progress bar is a good suggestion; however, on balance, this could result in over-saturation in terms of usage of space within the milestone components and lead to sub-optimal UX for the customer. Thus, not needed. Thanks for the suggestion though @maxceem .
