### ISSUE TITLE
Better organization of phase catalog page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2260]
### Expected behavior
Let's try to better organize/sort the available phases (products) on the "Add a phase" page

Follow https://marvelapp.com/8a94680/screen/46279602

![product catalog](https://user-images.githubusercontent.com/8484061/43476660-f8e26e2a-94ad-11e8-9e48-9ecc22d94c3a.png)

**Comment by vikasrohit** [comment]
we already have this in plan @vic-topcoder https://github.com/appirio-tech/connect-app/issues/2139
