### ISSUE TITLE
Leads in salesforce getting created from ask.topgear@wipro.com.

### ISSUE THREAD

**Issue by NikitaJain-TC** [appirio-tech/connect-app#2261]
### Expected behavior.
These are not exactly leads but pieces of projects which are using connect and as a result of which leads are created in sfdc and hubspot.

### Actual behavior
Hundreds of leads created in SFDC.

### Steps to reproduce the problem
- Create a project in connect from ask.topgear@wipro.com.
- A lead gets created in SFDC which should not

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by rmjmccormick** [comment]
@acshields Let's speak about this before we do anything please.

**Comment by acshields** [comment]
Sounds good @rmjmccormick

**Comment by vikasrohit** [comment]
Leads are not created for topgear user now.
