### ISSUE TITLE
Timeline fixes (bucket of smaller things)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2268]
There are several small issues we have to fix on the timeline interface:

- [x] Enable phase timeline description to be edited or change the explanation to be more user friendly @rmjmccormick @acshields 

- [x] Hide "Specification" tab on timeline for the time being. Based on our feedback from customers the forms we currently have do not really help to collect the information we need and we wanted to lighten up the UX for the end customer.

- [x] Make the "Add specification document" for the first phase options. This means the Copilot/Manager can mark the phase complete without attaching a document

- [x] Fix phase time calculation of the phase - right now the logic is still broken and we do not update the days left/elapsed.

- [x] We do have 250% completed on a phase based on the logic not working
![screen shot 2018-08-02 at 6 41 41 am](https://user-images.githubusercontent.com/8484061/43587704-b0127ca8-961f-11e8-8630-d446745c7771.png)

- [x] Completing a milestone should update the time calculated and record the completion date. Right now it doesn't update the date on the left side.
![screen shot 2018-08-02 at 6 38 34 am](https://user-images.githubusercontent.com/8484061/43587729-bc0b62e0-961f-11e8-8dba-a32b6fcb48ca.png)

- [ ] The milestones order is static - we can't be breaking the timeline based on the completion date (part of the logic fixes). The order of milestones on the timeline can't be changed!
![screen shot 2018-08-02 at 6 52 52 am](https://user-images.githubusercontent.com/8484061/43588155-bb1c75da-9620-11e8-8963-045f79c50c3a.png)

- [x] Delivery interaction background color and button do not match - follow the design specification
![screen shot 2018-08-02 at 6 40 48 am](https://user-images.githubusercontent.com/8484061/43587811-ea7707a6-961f-11e8-9015-5f8a90b62cf4.png)

- [x] Final fixes - the Submit request button doesn't work with only 1 final fix request. It should be enabled once we have a text in the first input.
![screen shot 2018-08-02 at 6 42 46 am](https://user-images.githubusercontent.com/8484061/43587795-e3e1d024-961f-11e8-8a1f-90539592b8dc.png)
![screen shot 2018-08-02 at 6 43 41 am](https://user-images.githubusercontent.com/8484061/43587840-fc72c3b4-961f-11e8-84fb-f2d1ad8c1c4d.png)

- [x] Expanding the phase causes the active tab to lose focus
![screen shot 2018-08-02 at 6 56 41 am](https://user-images.githubusercontent.com/8484061/43588387-3e9630b8-9621-11e8-8544-a93645e6015b.png)

- [x] Trigger updates of the interface based on changes. Similar to posts on the dashboard, the project plan interface should be added to the auto-update process/events. 

- [x] Once a milestone is completed, remove the hover color as it is not editable anymore
![screen shot 2018-08-02 at 6 50 09 am](https://user-images.githubusercontent.com/8484061/43588032-76de72ce-9620-11e8-99c5-361e1d1653a2.png)

- [x] Link type should support GitHub; we have only Marvel at this point.

- [x] Phase card should be with rounded corners. Right now that is missing. Let's verify that the components are developed against the design specification https://marvelapp.com/8a94680 (QA)

**Comment by maxceem** [comment]
> Completing a milestone should update the time calculated and record the completion date. Right now it doesn't update the date on the left side.

I think these [two lines](https://github.com/appirio-tech/connect-app/blob/dev/src/api/timelines.js#L42-L43) are causing this. They were added due to the backend [issue](https://github.com/topcoder-platform/tc-project-service/issues/117) which looks resolved now, so we can remove these two lines.

**Comment by maxceem** [comment]
> Expanding the phase causes the active tab to lose focus
This has the same cause by routing same like these two issues https://github.com/appirio-tech/connect-app/issues/2270 and https://github.com/appirio-tech/connect-app/issues/2269

**Comment by maxceem** [comment]
> Trigger updates of the interface based on changes. Similar to posts on the dashboard, the project plan interface should be added to the auto-update process/events.

Do you have an example when interface is not updated other than Milestone dates?

**Comment by vikasrohit** [comment]
> Enable phase timeline description to be edited or change the explanation to be more user friendly 

@vic-topcoder It is separate set of efforts to make the description editable. However, we can update the copy as required.

> We do have 250% completed on a phase based on the logic not working

Fixed by @gondzo 

> Fix phase time calculation of the phase - right now the logic is still broken and we do not update the days left/elapsed.

I didn't get it @vic-topcoder I don't see a place where we are showing the days left for a phase.

>  Completing a milestone should update the time calculated and record the completion date. Right now it doesn't update the date on the left side.

@vic-topcoder we have the logic in place, I am not sure how that edge case is happening. Can you please let us know the project or use case where that happened? (I am assuming that you are testing things on dev env, not on local)
@maxceem even after getting rid of those two lines, it won't affect the logic as the backend now does not support passing `endDate` and passing `completionDate` is optional when you are passing `status` as `completed`.

> The milestones order is static - we can't be breaking the timeline based on the completion date (part of the logic fixes). The order of milestones on the timeline can't be changed!

@vic-topcoder Again are you testing it on dev or local? I don't think this exists on dev environment.

 
> Expanding the phase causes the active tab to lose focus

I think we already have separate issue to track that. #2270 

> Trigger updates of the interface based on changes. Similar to posts on the dashboard, the project plan interface should be added to the auto-update process/events.

That  is again a separate set of requirements and should be handled separately.
@maxceem I think the requirement is to show alert message (with button to refresh the page) when some other team member has updated the phase/timeline/milestone of the same project while the user is on the project plan tab.

Other mentioned issues should be doable. @maxceem Would you be able to wrap them? Please create separate issues for the items in the list which has clear requirements and fix them in single feature branch.

**Comment by maxceem** [comment]
@vikasrohit yes, will handle them start tomorrow morning.

**Comment by vic-topcoder** [comment]
All is tested on DEV

> Do you have an example when interface is not updated other than Milestone dates?

It is filed as another issue: #2269. In general the interface is very jumpy and doesn't feel stable.

> Enable phase timeline description to be edited or change the explanation to be more user friendly

We had a discussion yesterday and the plan for the existing phases catalog on Connect is to introduce a generic dev iteration template with preset 3,4 or 5 steps. Being a generic development iteration template it would be really valuable to allow managers/copilots to edit the phase explanation, and we should aim to enable this sooner than later. The change is probably mostly on the back-end, as I don't know if we store a unique copy, but I imagine this should be part of the phase properties management process. Let's cover this in a separate issue if it is possible.

> I didn't get it @vic-topcoder I don't see a place where we are showing the days left for a phase.

I was talking about this duration of days calculated. It should point to how many days the phase would take to be completed. By the way, when there is a single day, it should say `1 day` instead of `1 days`. Once we complete all the milestones the duration would change if we delivered the work earlier. If we started with 28 days, but delivered 5 days earlier, this day count should say `23 days • Month 1-23 • # posts`.
![screen shot 2018-08-03 at 10 49 38 am](https://user-images.githubusercontent.com/8484061/43657514-efb1e614-970a-11e8-9279-f6896bbaa160.png)

The same rule applies for the milestone - on delivery replace the planned date with the actual delivery date.
![screen shot 2018-08-03 at 10 53 34 am](https://user-images.githubusercontent.com/8484061/43657729-7be83e9e-970b-11e8-9fd8-b1528484aecd.png)

> The milestones order is static - we can't be breaking the timeline based on the completion date (part of the logic fixes). The order of milestones on the timeline can't be changed!
@vic-topcoder Again are you testing it on dev or local? I don't think this exists on dev environment.

I am testing on DEV. The interface is not responsive to changes and without constant reloading things are breaking. I took screenshots from 
https://connect.topcoder-dev.com/projects/6706

**Comment by vikasrohit** [comment]
@maxceem are you done with the changes for removing the route for phases?

**Comment by maxceem** [comment]
@vikasrohit no, I was waiting for confirmation that I can do that.
Also, could reference any reasons why it was added? Probably if I remove it, we have to fix some other issue, which was fixed by adding such routing.

**Comment by vikasrohit** [comment]
Okay, #2066 was the reason to have that route. It should only be activated for mobile views, not for the desktops.

**Comment by gondzo** [comment]
It was added for mobile - phase details are shown in a separate page. On desktop the route will just expand the phase details. IMO we should just remove the redirect on clicking the phase header on dashboard

**Comment by vikasrohit** [comment]
Also, could you create issue and start for
>  Fix phase time calculation of the phase - right now the logic is still broken and we do not update the days left/elapsed

Vic has added more details for it in his comments. So, just need to ensure that we are showing the phase start-end date range, in the phase card header, as per the actual duration of the phase i.e. when a phase has  timeline and in turn milestones, we should write that date range as start date of the first milestone to completion date of the last milestone.
Also, show the completion date instead of end date in the milestone's date in the left section of the timeline.

**Comment by maxceem** [comment]
@vikasrohit @gondzo Is that ok, if I completely remove routing for phases and open the page on mobile fullscreen without routing?
This way it's now done for posts when we make them fullscreen. We open posts on mobile fullscreen without routing.

@gondzo 
> IMO we should just remove the redirect on clicking the phase header on dashboard

As I understand by current logic we are supposed to change route when we expand (open fullscreen) on mobile. As we still can expand (open fullscreen) on dashboard we are supposed to change routing there too. If we keep routing for phases.

**Comment by gondzo** [comment]
Sure, removing the route is fine too

**Comment by maxceem** [comment]
@vikasrohit  
> Also, could you create issue and start for
> Fix phase time calculation of the phase - right now the logic is still broken and we do not update the days left/elapsed

Done https://github.com/appirio-tech/connect-app/issues/2286

I'll add your comment there and ask some additional question there.

**Comment by vikasrohit** [comment]
Closing as all issues from this bucket are resolved. Please feel to create new issues if any issue is found related to them.
