### ISSUE TITLE
Editing phase and timeline interface is jumping/disappearing

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2269]
When I'm editing a phase properties, or milestone properties, the interface jumps around, I lose visibility of the other milestones (on a project with many milestones), and tab focus is lost. The interface is very unstable to work with.

Used https://connect.topcoder-dev.com/projects/6899/plan with Pat Monahan
![screen shot 2018-08-02 at 4 03 09 pm](https://user-images.githubusercontent.com/8484061/43615664-9d1d5246-966d-11e8-9803-18c1f656ed78.png)
![screen shot 2018-08-02 at 4 03 13 pm](https://user-images.githubusercontent.com/8484061/43615665-9d35b14c-966d-11e8-84a2-809855c2cdce.png)
![screen shot 2018-08-02 at 4 03 20 pm](https://user-images.githubusercontent.com/8484061/43615666-9d48144a-966d-11e8-8a46-3b1dee8a8bc8.png)

**Comment by vikasrohit** [comment]
@gondzo I think is again happening because of dedicate route for the phase details. I think we should not route user to that route when it is on desktop.

**Comment by maxceem** [comment]
This is fixed by PR https://github.com/appirio-tech/connect-app/pull/2294

**Comment by vikasrohit** [comment]
Its working fine. Closing. We do have another issue with jumping screen which is captured here #2325

**Comment by vikasrohit** [comment]
@maxceem it seems the modal we are showing when user is tapping on a particular phase card, is not scrollable. Can you please check that?

**Comment by maxceem** [comment]
@vikasrohit I'm not sure if this is the issue you saw.

When phase is smaller than the mobile screen, currently we can see underneath the popup and there is no scroll as there is nothing to scroll:

![image](https://user-images.githubusercontent.com/146016/43893019-2ed6c7a2-9c00-11e8-9218-efc016566678.png)

I've fixed it, so phase covers the whole screen even if there is not enough content, now it looks like this, but there is still no scroll as all the content fits the screen.

![image](https://user-images.githubusercontent.com/146016/43893117-7950959c-9c00-11e8-9904-c3318d648078.png)

In the situations when phase has content more than for a screen there is always working scrolling, checked in Chorme, FF, iOS Simulator, Android Device.

**Comment by vikasrohit** [comment]
Yep, it seems to be working on the actual device, I think it was not working in chrome when enabled responsive mode.
