### ISSUE TITLE
Expanding the phase window from dashboard on desktop computer leads to project plan (Shouldn't)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2270]
On desktop browser, expanding the project phase (active) should stay on the dashboard. Right now it leads to the project plan section (changes tabs) and it is confusing (I didn't click on a tab, but to expand the accordion. Why is it happening?).

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-251

**Comment by vikasrohit** [comment]
@gondzo I think it appeared after we fixed the issue with new page opening for phase click. We need to stop routing to new route when the phase card is clicked on the dashboard.

**Comment by maxceem** [comment]
This is fixed by PR https://github.com/appirio-tech/connect-app/pull/2294

**Comment by RishiRajSahu** [comment]
working fine. closing.
