### ISSUE TITLE
Complete the generic phase templates requirements

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2271]
Let's complete the generic dev iteration templates and verify with Kyle that those are ok to start with. https://docs.google.com/spreadsheets/d/1SXZjX5TlbfFa7IuifOseCKqvqkytxeXUEH3A1rL0CCw/edit#gid=782784012

We have to have a start, report, and delivery milestones.

For design - we have 1 template and will allow the copilots to modify the duration. We have to verify with Trevor if checkpoint will be a customer-facing step.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-252

**Comment by vikasrohit** [comment]
I think this is shipped with 2.4.4. Please feel free to reopen it if we are still missing something.
