### ISSUE TITLE
[$50] Edit milestone on mobile devices

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2272]
Currently editing milestone on mobile devices is done in a halfway:

1. We cannot see edit button as there is no hover effect on mobile to show it. Though we can still click on the title which will cause hover to work and show an edit button. It feels like it has to be done some more mobile-friendly way or disabled completely.

   ![image](https://user-images.githubusercontent.com/146016/43636923-0a58d23a-9746-11e8-9e15-334991837816.png)

2. Edit form is too narrow. Probably labels have to be on separate lines on mobile resolutions:

    ![image](https://user-images.githubusercontent.com/146016/43636885-ee24ac06-9745-11e8-8070-46d6de53527c.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-446

**Comment by RishiRajSahu** [comment]
@maxceem yeah it needs to be handled in more mobile friendly way, @vic-topcoder inputs ?

**Comment by RishiRajSahu** [comment]
@vic-topcoder please provide your input.

**Comment by maxceem** [comment]
So as I understand we show it similar way as a topic on mobile screens. I mean the header and close button.

And the rest of the form we keep the same, just make it wide for the full screen keeping standard paddings on the sides.

![image](https://user-images.githubusercontent.com/146016/45217344-52ff2b00-b2d6-11e8-8848-b06f179b810b.png)

**Comment by maxceem** [comment]
To sum up:
1. on mobile we should always show the edit icons for milestones (not only on hover). Note, only powerful user can see it now and it shold be like that.
    
      ![image](https://user-images.githubusercontent.com/146016/46139333-db8f3c80-c280-11e8-94ee-d4bbce3e0038.png)

    - but don't show blue background

2. when clicking edit on mobile we should show edit form full screen, similar to like we do when we click topics on the `Dashboard` tab and topics are shown fullscreen with header and cross on the right

     ![image](https://user-images.githubusercontent.com/146016/46139154-602d8b00-c280-11e8-8278-71f8baa557da.png)
    
     - we can reuse [MobilePage](https://github.com/appirio-tech/connect-app/blob/dev/src/components/MobilePage) component to show full screen like it's done for posts.

3. we keep milestone edit form as it is now

**Comment by vic-topcoder** [comment]
I'd like that, yes, for all 3 points.

**Comment by khushimehta03** [comment]
@maxceem assign me . thanks

**Comment by maxceem** [comment]
As the issue hasn't been completed during 12 hours and no comment was provided, this issue is now open for pick up.

**Comment by Gauravseta** [comment]
@maxceem pls assign this to me.i will complt this in 12hrs now.previous issue i was actively working on but it was difficult.pls giv me this

**Comment by Gauravseta** [comment]
@maxceem PR ready #2619

**Comment by maxceem** [comment]
@Gauravseta I think it could be something with your local installation or internet connection. You may try:
- remove `node_modules` folder and run `npm i` again
- [clear npm cache](https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache)

**Comment by maxceem** [comment]
@Gauravseta I've review your PR, please have a look https://github.com/appirio-tech/connect-app/pull/2619#pullrequestreview-164556574

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
