### ISSUE TITLE
Milestone on mobile devices

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2273]
Milestones on mobile devices have several visual issues. See project for testing https://connect.topcoder-dev.com/projects/6706

1. The header looks like sticks to the edges and has too big space between lines

   ![image](https://user-images.githubusercontent.com/146016/43638542-df6e742a-974b-11e8-8938-fbfd1814cc3e.png)

2. The blue line is not straight across all milestones:

    <img width="389" alt="line1" src="https://user-images.githubusercontent.com/146016/43638612-1ed333c6-974c-11e8-9509-ada45e73f5ff.png">

3. Links are going to the second line when there is a title, should they?

     <img width="399" alt="links2" src="https://user-images.githubusercontent.com/146016/43638717-73008462-974c-11e8-98b9-f2953c984511.png">

4. Links are being cut by the screen.

5. At the last milestone, the long link also looks like forces its container width be extended beyond the screen. Expected looks would be like this: gray and blue background are not cut by the screen and has some space on the right side.

    ![image](https://user-images.githubusercontent.com/146016/43638912-151ff174-974d-11e8-8742-f9158339e2f3.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-257

**Comment by maxceem** [comment]
@vikasrohit  @RishiRajSahu could please have a look on this items 1, 3 and 4. 
Items 2 and 5 looks like a clear bugs for me with only one correct solution, so you may skip them.

**Comment by RishiRajSahu** [comment]
it seems we don't have designs for 
1.Long header text
3.Links with title
4.Long text of deliverable link

as per me

1. we put proper spacing between and around the header text, assuming if its longer than two lines show elipses
3.showing them on next line seems the correct way to me
4.it could be wrapped

still needs @vic-topcoder inputs on this before starting dev work.

**Comment by maxceem** [comment]
6. Adjust **add design** link and fake text with the circle for small screens as described in the next comment https://github.com/appirio-tech/connect-app/issues/2288#issuecomment-411371798

**Comment by vikasrohit** [comment]
@maxceem do we have any thing pending this issue now?

**Comment by maxceem** [comment]
@vikasrohit I'll test it out.

**Comment by maxceem** [comment]
@vikasrohit almost all issues are fixed, only one statys, and I've added a few not critical:

1. Still stays, let me know if you'd like me to fix it as Rishi suggested or in another way.

7. Delivery milestone is shown with a big space:

    ![image](https://user-images.githubusercontent.com/146016/44441998-28d51a00-a602-11e8-9217-04c5723d363d.png)
    
    See project http://local.topcoder-dev.com:3000/projects/6706/plan, the first phase.

8. `Complete review (7h delay)` doesn't fit the button width

      ![image](https://user-images.githubusercontent.com/146016/44442050-7f425880-a602-11e8-9478-4e39821d29c4.png)

9. Two buttons in confirmation dialog doesn't fit the line 

     ![image](https://user-images.githubusercontent.com/146016/44442068-a39e3500-a602-11e8-8354-32fcbf91014a.png)

10. Items in extension requests don't fit the line

      ![image](https://user-images.githubusercontent.com/146016/44442095-bca6e600-a602-11e8-976a-55ea101bd579.png)

**Comment by vikasrohit** [comment]
Thanks @maxceem which one of these is from the issues mentioned in the original list?

And could you please start closing these pending items as well as per priority we have? Let me know if you have any question for these pending items.

**Comment by maxceem** [comment]
The 1st item is from the original list.

Ok, I'll close as per the list.

- Regarding 3 and 4 I'm thinking to put buttons in two lines and space between them
- Regarding 5 I think to make radio buttons in one column

Let me know if you'd like it to be done other way.

**Comment by vic-topcoder** [comment]
I've added the specifications for RUX #2312

**Comment by vikasrohit** [comment]
@maxceem I am okay with your assumptions to fix the issues. Only thing to keep in mind is that primary button should be in the first line when wrapping the buttons in two lines.

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder for the designs.

**Comment by maxceem** [comment]
6. How to deal with long button names which don't fit mobile screen. Note, I suppose the minimal supported resolution is 320px.

     - `Add specification document link`
        ![image](https://user-images.githubusercontent.com/146016/44575652-06d4c680-a7bf-11e8-8b69-39a3c922cdf5.png)
     - `Complete review (158h remaining)`
        ![image](https://user-images.githubusercontent.com/146016/44577059-ae9fc380-a7c2-11e8-8a34-36b9f0a1a59e.png)

**Comment by maxceem** [comment]
Everything except 6 is done

1. Looks like this
     ![image](https://user-images.githubusercontent.com/146016/44574777-eefc4300-a7bc-11e8-827f-88f474ae04a3.png)

5 Extension labels are aligned like this https://monosnap.com/file/KB7Aabd2S3ZrZ0PfeXZhkbqocehhKC


7 Fixed `Please select all 5 designs to ...` warning.
     ![image](https://user-images.githubusercontent.com/146016/44577103-cd05bf00-a7c2-11e8-925d-5ce32a471251.png)

**Comment by acshields** [comment]
For Pt. 6, I would do the following: Shorten "add specification document link" to "add specification." Shorten "complete review 158h remaining" to "complete review Xh." For the long phase titles, shorten them from "Design Iteration (short) phase" to "Design Phase (S)"

**Comment by maxceem** [comment]
Thank you @acshields 

All the items in this task are fixed.

**Comment by maxceem** [comment]
@RishiRajSahu Put edit icon to the space between title and progress:

![screen shot 2018-08-29 at 17 33 44](https://user-images.githubusercontent.com/146016/44779317-c48df980-abb1-11e8-82af-e56f94a20c12.png)

**Comment by RishiRajSahu** [comment]
@maxceem Everything working fine except the final design selection UI.

**Comment by RishiRajSahu** [comment]
<img width="390" alt="screen shot 2018-08-30 at 10 31 09 am" src="https://user-images.githubusercontent.com/11248478/44830574-ea61df80-ac3f-11e8-8893-5ae565493e1f.png">


@maxceem, Yeah going as per designs only, 
- blue line is not required as per designs for mobile
- Centre the review button

I think that completes it.

**Comment by maxceem** [comment]
@RishiRajSahu  Centered.

![image](https://user-images.githubusercontent.com/146016/44831167-e346cb80-ac57-11e8-99fe-08cff06145e1.png)

**Comment by maxceem** [comment]
@RishiRajSahu restricting phase titles to two lines on mobile devices by adding ellipsis:

![image](https://user-images.githubusercontent.com/146016/44831904-1c346f80-ac5b-11e8-96d1-d5fc16c772ea.png)

Let me know if you'd like it to be pushed directly to `dev`.

**Comment by RishiRajSahu** [comment]
LGTM, if you have created a feature branch then raise the PR.

**Comment by RishiRajSahu** [comment]
pushed to dev. working fine.
