### ISSUE TITLE
Automatically change project status based on project plan activity

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2275]
Right now we introduce multiple levels of status changes that are all manual. This increases the project managers work and we can do some simple automations in order to prevent errors.

- **Switching phase status to Planned**
It makes sense to switch the project status to "in review" when we have a project stage that is planned - the customer can now see and contact the project managers and discuss details.

- **Starting work on a project phase**
This should automatically update the project to "Active" state as we have work under way.

@rmjmccormick @acshields please feel free to chime in.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-259

**Comment by rmjmccormick** [comment]
@vic-topcoder just to confirm you are referring to the project-level statuses on the left sidebar? As in, in both your example cases, when a given phase is planned or in progress, this should automatically trigger a change to the project-level status as appropriate?
If so, I wholeheartedly agree.
I'd also add one final use case - when all project phases are marked as "delivered", and there are no remaining draft or planned phases, the project-level status should flip to completed.

**Comment by vikasrohit** [comment]
> It makes sense to switch the project status to "in review" when we have a project stage that is planned - the customer can now see and contact the project managers and discuss details.

I think we should mark the project as `reviewed` instead of `in_review` because `in_review` is the status which is set when customer clicks on `Submit for Review` button and we use this status to post a message to the slack channel where our managers can look for new projects. However, if we set project's status to `reviewed` it would post message to the copilots channel in the slack which would tempt copilots to claim the project which technically would work fine but as now we have multiple phases per project, we might have to think about a new flow around copilots claiming phases instead of projects.

> I'd also add one final use case - when all project phases are marked as "delivered", and there are no remaining draft or planned phases, the project-level status should flip to completed.

I think it would cause some issue for long running projects where there might be a case where all phases are marked as complete. Now if the customer or manager want to have more work included in the project, they would add the phase later but if we mark the project as completed they won't be able to mark the project active again.

**Comment by rmjmccormick** [comment]
> I think it would cause some issue for long running projects where there might be a case where all phases are marked as complete. Now if the customer or manager want to have more work included in the project, they would add the phase later but if we mark the project as completed they won't be able to mark the project active again.> 

@vikasrohit Good point, as we saw last week through that email exchange with Joey Poarch! Though, we should be urging managers to close out projects and starting an entirely new project where the delay between the original project closing and the new "additional" piece of work exceeds 3 months. Keeping projects open has implications for revenue recognition (we can only recognise fully on project closure).

**Comment by vikasrohit** [comment]
I don't think we have time to close this out before Aug 09. Targeting it for next release.

**Comment by maxceem** [comment]
As I understood from the discussion only two cases from the first comment has to be implemented https://github.com/appirio-tech/connect-app/issues/2275#issue-347486852

Done via https://github.com/appirio-tech/connect-app/commit/fa31fe0904e105333566bbf10aef9cd81f03d82a

Note, to avoid any unwanted affects during:
- **Switching phase status to Planned**
    I only switch projects to `reviewed` state if it was previously in `draft` or `in_review` state
- **Starting work on a project phase**
    I only switch projects to `active` state if it was previously in `draft`, `in_review` or `reviewed` state

**Comment by vikasrohit** [comment]
> Note, to avoid any unwanted affects during

Perfect.

> I only switch projects to reviewed state if it was previously in draft or in_review state

Lets keep the project in `in_review` state as originally suggested by @vic-topcoder until we get confirmation about changing it to `reviewed`.

**Comment by maxceem** [comment]
Done.

Note, that technically now we swtich project to `in_review` status while phase is swtiched to `reviewed` status.

**Comment by vic-topcoder** [comment]
@acshields FYI

- A project with `in review` state communicates to the customer that we're working on it; no copilots are added yet. This is the preliminary stage to define scope and size, and proceed further (close the sale)
- A project with `reviewed` state means a copilot is now going to self-assign themselves (sale is closed), work specification will be determined
- A project with `active` state means work is underway.

For the phase states we have only the 4 designed so far:
- `Draft` - invisible to customer; planning and adjusting the project plan (edit phase and milestones) - everything should be visible to manager
- `Planned` - visible to customer; work hasn't started yet; further changes based on customer feedback can be implemented
- `Active` - work is underway
- `Delivered` - the customer has accepted final deliverables; we can close the phase (recognize revenue).

So the switching between states for a project should really take care to only move the project status in sync with the phase status, but never auto close a project (for long running projects we don't want to close them but provide more options to add work). Once a project is closed, it can't be reopened (problems with our integration systems and other).

@maxceem - good catch on the additional logic!

**Comment by vikasrohit** [comment]
Working fine in dev. Closing.

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields as discussed changed logic to move project to `reviewed` state instead of `in_review` when any phase is marked as planned first time.

**Comment by vic-topcoder** [comment]
Correct! Thanks for catching that @vikasrohit
