### ISSUE TITLE
Hide "Specification" tab on timeline for the time being

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2276]
Hide "Specification" tab on timeline for the time being. Based on our feedback from customers the forms we currently have do not really help to collect the information we need and we wanted to lighten up the UX for the end customer.

Comes from https://github.com/appirio-tech/connect-app/issues/2268

**Comment by vikasrohit** [comment]
@maxceem we need to hide the Specification tab only for customers, not for managers and copilots. Could you please fix that?

**Comment by maxceem** [comment]
Done by https://github.com/appirio-tech/connect-app/commit/9f98dce3a543835f5d7dfe4c7f33535d16218258

**Comment by vikasrohit** [comment]
Working fine now. Closing.
