### ISSUE TITLE
Make the "Add specification document" optional

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2277]
Make the "Add specification document" for the first phase optional. This means the Copilot/Manager can mark the phase complete without attaching a document

Comes from https://github.com/appirio-tech/connect-app/issues/2268

**Comment by vikasrohit** [comment]
@maxceem it seems to work fine, however, `community-work` and `community-review` has `Add Link` optional as well. Just wanted to make sure that it is not the side effect of this change?

**Comment by maxceem** [comment]
@vikasrohit No, these two milestones had optional link initially by design as discussed with Rishi.

**Comment by vikasrohit** [comment]
Okay.
