### ISSUE TITLE
Phase card should be with rounded corners

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2278]
Phase card should be with rounded corners. Right now that is missing. Let's verify that the components are developed against the design specification https://marvelapp.com/8a94680 (QA)

Comes from https://github.com/appirio-tech/connect-app/issues/2268

**Comment by vikasrohit** [comment]
Seems good to me. @vic-topcoder your designer eyes please.

**Comment by vikasrohit** [comment]
Closing. @vic-topcoder please create new issue if you think it needs more changes.
