### ISSUE TITLE
[$30] Unify close button for mobile fullscreen popups

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2279]
I've noticed that we have several full-screen popups on mobile devices with the various ways of closing them. Probably iwe can unify it in some way.

1. Create a new post: cross on the left

   ![image](https://user-images.githubusercontent.com/146016/43672067-a5fcf170-97d8-11e8-9391-93f336e17815.png)

2. Post view: cross on the right

    ![image](https://user-images.githubusercontent.com/146016/43672074-bcc1d57e-97d8-11e8-831c-fcee01f93130.png)

3. Phase view: arrow on the left

    ![image](https://user-images.githubusercontent.com/146016/43672091-ffea8530-97d8-11e8-9bf7-1126899bfe63.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-264

**Comment by vikasrohit** [comment]
Good catch @maxceem. @vic-topcoder Let us know where do you want to put the close button.

**Comment by vikasrohit** [comment]
@vic-topcoder your input needed

**Comment by maxceem** [comment]
@vikasrohit  I can pick up this one, as soon as we agree on how we unify the button.

**Comment by vic-topcoder** [comment]
Arrow and close are different patterns. They should not be mixed.

- Arrow is for iOS going back

- Cross - should be on the top right side, I'd prefer if we use only 1 SVG and manipulate the fill with CSS

Good catch @maxceem

**Comment by maxceem** [comment]
As I understand for cases 1 and 2 we keep cross but put it on the right side.
And case 3 stays as it is.

**Comment by vic-topcoder** [comment]
Yes.

**Comment by vikasrohit** [comment]
Moved to next release.

**Comment by maxceem** [comment]
@vic-topcoder 
> I'd prefer if we use only 1 SVG and manipulate the fill with CSS

Is your intention just to reuse the same SVG file? Or you'd like to make both crosses the same size? If so, which size would you prefer to use?

**Comment by prasadadarkar30** [comment]
@maxceem  I am working on this can u assign me.

**Comment by Gauravseta** [comment]
@maxceem will i get to work on this if prasad fails to complete it? thanks.i have started working on it and see if prasad fails then i will raise PR immediately in case.

**Comment by maxceem** [comment]
@Gauravseta hmm. Ok if you already done it then it would be yours in case prasadadarkar30 doesn't provide the solution. But please, don't do like this to other issues as it not really per Bag Bush rules. Trying to keep the process fair to everyone as much as possible. Thanks.

**Comment by maxceem** [comment]
@Gauravseta ok, I've got you. Let me discuss it with the team first before I confirm this to you, as it doesn't directly fit the current Bug Bash rules we have. I'll update on this today.

**Comment by maxceem** [comment]
@Gauravseta As promised I'm back with the answer for you. We've discussed the possibility of "booking" issues like this. There would be many edge case situations which could lead to confusions and participants disappointment if we let to do like this. We cannot let participants to book issues. So in case any issue is not finished and is opened for pick up again, anyone who comments the first **after issue become open** would be considered as the one who took the issue. Thanks.

**Comment by prasadadarkar30** [comment]
it is too difficult releasing it , if anyone wish to then they can take it.@maxceem

**Comment by PrakashDurlabhji** [comment]
@maxceem wish to work on it .give it to me thank you.

**Comment by maxceem** [comment]
Sure @PrakashDurlabhji it's yours.

Btw, if you accept the invitation to this repo from GitHub I could assign you to this issue. Though it's not required.

**Comment by PrakashDurlabhji** [comment]
@maxceem Pr has been done and in 1st case cross button is taken to the right as discussed in comments above.

**Comment by maxceem** [comment]
@PrakashDurlabhji I've reviewed your PR, please have a look https://github.com/appirio-tech/connect-app/pull/2503#pullrequestreview-155333625

**Comment by PrakashDurlabhji** [comment]
@maxceem commented at PR

**Comment by maxceem** [comment]
@vic-topcoder This is how it looks after provided fix:

![image](https://user-images.githubusercontent.com/146016/45581787-606c7480-b8d7-11e8-80b8-30a4978339d6.png)

![image](https://user-images.githubusercontent.com/146016/45581789-6cf0cd00-b8d7-11e8-99ed-04c5912ad4ac.png)

Note. Cross sizes has also became same.

Looks good to me, so I'm merging PR, let me know if there is anything to adjust.
