### ISSUE TITLE
Delivery milestone background color and button do not match

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2280]
Delivery interaction background color and button do not match - follow the design specification

![image](https://user-images.githubusercontent.com/146016/43672122-cf6aff9c-97d9-11e8-99ba-0a1695f65ea0.png)

Design https://marvelapp.com/8a94680/screen/41372952

Comes from https://github.com/appirio-tech/connect-app/issues/2268

**Comment by maxceem** [comment]
I see that the background doesn't match the design, but the buttons look same like in design for me. Please let me know if I miss something.

**Comment by vikasrohit** [comment]
@vic-topcoder I can not see difference in buttons, need your designer eyes.

**Comment by vikasrohit** [comment]
@vic-topcoder changes are deployed to dev. Please let us know if it is still missing some design specs.

**Comment by vikasrohit** [comment]
@vic-topcoder closing the issue, please create a new issue if you think it is still not matching the designs.
