### ISSUE TITLE
Completing a milestone should update the date

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2287]
Completing a milestone should update the time calculated and record the completion date. Right now it doesn't update the date on the left side.

Comes from https://github.com/appirio-tech/connect-app/issues/2268

**Comment by maxceem** [comment]
There is an issue on the backend which is still valid for `endDate` https://github.com/topcoder-platform/tc-project-service/issues/117

Meanwhile, there is a thing to clarify.
What is the difference between `endDate` and `completionDate`? When we complete the milestone, should we update them both or only `completionDate`? and keep the `endDate` just as it was planned?
If we update them both, than `completionDate` feels like doesn't have an additional value.

**Comment by maxceem** [comment]
2. There is kind of issue with how startDate/endDate are currently calculated.
    Let's say today is `August 4`.

    <img width="567" alt="plan1" src="https://user-images.githubusercontent.com/146016/43674296-6813dd66-9804-11e8-963c-50161b7f45fa.png">

    I click `Mark as completed` so the milestone will be completed today on `August 4` and next milestone starts the next day `August 5`

    <img width="567" alt="plan2" src="https://user-images.githubusercontent.com/146016/43674319-b20e40aa-9804-11e8-955e-9076fefb9bc5.png">

    In this case we end up with currently active milestone which will start only tomorrow. More than that, if I try to complete this milestone now, I'll get fare validation error from the server, that completionDate has to be more or equal than startDate. As current startDate = August 5, and the completionDate I'm trying to set is today `August 4`.

   It looks like we have change the way how startDate/endDate are calculated so that endDate of the prvous milestone is equal to the startDate of the next milestone. Maybe you have any other ideas of how to solve it?

**Comment by RishiRajSahu** [comment]
@maxceem 
Your understanding is correct, `endDate` is calculated as per planned, while `completionDate` is actual completion date

Also, validation error from server is fare as you said, if it would have been 5 Aug and then we have tried marking it as completed it would be successful, but here as today is still 4 Aug which is less than start date so its giving error. To handle this, @vikasrohit should we **_set the `startDate` of next milestone to be same as `completionDate` of current milestone_** to enable user for completing the task on same day ? I see there is no information loss or ambiguity w.r.t. to UX if we set `completionDate` and next milestone's `startDate` with same value, correct me if I missed any edge case ?

**Comment by vikasrohit** [comment]
@maxceem for now, please don't send the `completionDate` along with `status` field when you are marking the milestone as complete. This would set the today as `completionDate` for the milestone without firing the validation. However, that would lead to slightly inconsistent data in database where `startDate` would be greater than the `completionDate`. To fix that, we are thinking of introducing a new field called `actualStartDate` which we would set for a milestone when the milestone is marked as active. So, when rendering the timeline on frontend, we would give preference to the `actualStartDate` and `completionDate`, when present, over the `startDate` and `endDate` which actually acts like scheduled start and end dates.

**Comment by maxceem** [comment]
@vikasrohit I did update only `status` without `completionDate` when we mark milestone as complete. And it did work as excpected.

The only thing we end up with non-logical timeline dates.

1. The first milestone has to start on `14 August`
2. I mark the phase as `In Progress` which makes the first milestone active even though the start date is `14 August`
3. I mark the first milestone as completed. So backend set a completed date and adjust next milestones accordingly
    ![image](https://user-images.githubusercontent.com/146016/43716098-69b9f490-99b5-11e8-9212-96c0f0cff4a3.png)

4. We end up with the timelines dats as 14, 7, 12.    

I think the issues here is not with completedDate actually. Probably when we mark a phase as `in progress` we change startDate of the first milestone as today, and all the following milestones accordingly.

**Comment by maxceem** [comment]
>  I have also noticed that first milestone is showing September instead of August, do you know what is the reason there?

You are right, so there is no issue in the situatian I showed before. The start date was really 14 September in that phase, so first milestone started 14 September. When I marked it as completed it updated all the follwoing dates according to today date as excpected. So everything were correct.

**Comment by vikasrohit** [comment]
@maxceem how can we verify the changes made for this issue? I am trying to verify the changes in dev env.

**Comment by maxceem** [comment]
@vikasrohit Ok, I think here I didn't solve the issue listed here about updating UI, and instead refactored code to match current backend behavior regarding marking a milestone as complete. The actual issue with updating UI is listed as a separate common issue here https://github.com/appirio-tech/connect-app/issues/2291.

**Comment by vikasrohit** [comment]
Okay. Nothing to verify there then, closing the issue.

**Comment by vikasrohit** [comment]
> Good catch there @maxceem I would do those changes in backend asap. I have also noticed that first milestone is showing September instead of August, do you know what is the reason there?

Fixed that in backend.
