### ISSUE TITLE
Milestones with progress get visually broken on small screens

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2288]
When there is a progress bar inside milestone it makes timeline look broken on small screens

![image](https://user-images.githubusercontent.com/146016/43674960-28819c92-980e-11e8-9546-0a3deca8a79f.png)

**Comment by vikasrohit** [comment]
@maxceem Can we fix this as well? I am seeing this for 411x731 resolution which I think chrome is using for Pixel 2 device.

**Comment by maxceem** [comment]
@vikasrohit I've forgotten to list that one under https://github.com/appirio-tech/connect-app/issues/2273

Will fix it here.

**Comment by vikasrohit** [comment]
👍

**Comment by vikasrohit** [comment]
I think that is okay for the time being. Only thing is that could we reduce the screen limit more to hide that? I mean instead of 992px, can we hide it somewhere around 768px?

**Comment by maxceem** [comment]
768 I think too late in some situations. This is the 800px and we have to hide I think:

![image](https://user-images.githubusercontent.com/146016/43833254-c1995f10-9b3c-11e8-9276-f41267d0da2e.png)

`992px` is one of the predefined breakpoints. but I can just hide it at a custom breakpoint, let say at 840px, see

![image](https://user-images.githubusercontent.com/146016/43833317-ef86fcd4-9b3c-11e8-97ef-a0d24a479638.png)

**Comment by vikasrohit** [comment]
Understood. However, I think ideally, we should not have situation where we have to hide this element in desktop views (where we are showing the left panel) i.e. > 768px. In mobile view it would already remove the left panel so we would get more space to show the element, but we have to hide it in mobile view after certain width. On the desktop views (where we are showing the left panel), we might try to adapt the elements to adjust as per width, may be we can reduce the width of the button in this case below 992px.

> 992px is one of the predefined breakpoints. but I can just hide it at a custom breakpoint, let say at 840px, 

No, please use standard breakpoints only, I don't want to introduce a new breakpoint.

**Summary**: Please leave it as you committed already i.e. hide for < 992px if it seems difficult or time consuming for now to the way I described above. We can take care of it when handling mobile views specifically.
