### ISSUE TITLE
Milestone extension doesn't work as backend doesn't let update endDate

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2289]
Currently, milestone extension doesn't work due to backend doesn't let update `endDate` see https://github.com/topcoder-platform/tc-project-service/issues/117

Will be that issue fixed for backend? Or it's not an issue and we have to update `duration` instead of `endDate` when a user requests milestone extension?

**Comment by RishiRajSahu** [comment]
@maxceem, as per my understanding we first send the patch request for existing milestone for which we want to extend with `duration` as param, then During approve, we are making another patch for next milestone with `startDate` param. As per latest changes in backend when

**Comment by RishiRajSahu** [comment]
@maxceem, as per my understanding we first send the patch request for existing milestone which we want to extend with `duration` as param, then During approve, we are making another patch for next milestone with `startDate` param. As per latest changes in backend when you pass duration to be updated for a particular milestone all the next milestone's cascaded updates will be done implicitly.

we are not allowing dates to be updated directly from UI anymore.

**Comment by vikasrohit** [comment]
>  During approve, we are making another patch for next milestone with startDate param

@RishiRajSahu I don't think you will be able to do that as we are not allowing the updates in `startDate` and `endDate`.

I think to achieve the use case, we have to just update the milestone's `details` json with flag indicating that extension is requested, and on approve, just patch the milestone with updated `duration` field only.

**Comment by maxceem** [comment]
Done by updating `duration` of the current milestone only. Other milestones are updated cascading by the server.

There is another issue, that the dates of following milestones are not updated in the UI after server implicitly updates them. I create a separate issue to handle this one and other similar cases https://github.com/appirio-tech/connect-app/issues/2291

**Comment by vikasrohit** [comment]
Working fine after refreshing the page. As said above, need #2291 to be fixed to reflect the changes immediately.
