### ISSUE TITLE
Post styling with code block

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2290]
### Expected behavior
Post should be contained within the main body, with scrollbar if necessary

### Actual behavior

![image](https://user-images.githubusercontent.com/3051646/43677524-89f06180-9803-11e8-9656-424f9a80283d.png)

**Comment by vikasrohit** [comment]
@gondzo fixed and patched on production. Please let us know if it is still not working.

**Comment by vikasrohit** [comment]
Just as reference of the duplicate #2310
