### ISSUE TITLE
When server updates milestones cascading, UI has to be updated for changed milestones

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2291]
There are several cases when we update one milestone, and its UI is updated correctly. 
But at the same time server updates cascading other milestones, but UI is not updated automatically. 

The cases:
1. We complete milestone so the next milestone dates are moved.
2. We extend milestone.
3. We change the duration of milestone manually.

Comes from https://github.com/appirio-tech/connect-app/issues/2268 and https://github.com/appirio-tech/connect-app/issues/2289#issuecomment-410597026

**Comment by vikasrohit** [comment]
@RishiRajSahu are we not handling this by calling the `GET /v4/timelines` endpoint again after such updates?

**Comment by vikasrohit** [comment]
@maxceem what is your investigation about this issue? How much time it would take to fix this?

**Comment by maxceem** [comment]
@vikasrohit I'm going to fix this one till the EOD

**Comment by maxceem** [comment]
One more case:
4. When we update startDate and status of the phase. Frontend also updates timeline dates and change the status of the first milestone to active. Timeline dates are updated in UI, but first milestone doesn't because active in UI until we reload the page.

**Comment by vikasrohit** [comment]
is it ready for review @maxceem ?

**Comment by maxceem** [comment]
No, only one item is done so far. Was doing the relative issue first, continue with this one now. I'll let you know when this is ready.

**Comment by maxceem** [comment]
@vikasrohit I've done with the fixes for all cases of this issue. So it's ready for review. 

But there appear to be some user experience issue after the fixes.
See the video when we update milestone duration http://take.ms/N3cV8

The process is like this:
1. We update milestone duration, so milestone is being updated and we show loader only for the milestone.
2. As soon as the milestone is updated we have to update the whole timeline because we know that dates of other milestones are updated by the server. So we trigger timeline reloading and we show loader now for the whole timeline.

So we end up having two loader indicators one by one.

There are three ways to deal with it:
1. Keep two loaders as it's done now.
2. Update timeline silently in such cases without showing the loader. This is potentially risky way, as while we update timeline in background if takes time. A user may open something or start editing something, and when the silent update is finished we update UI which can end up in loss of user actions.
3. We show the loader indicator for the whole timeline from the beginning rather than showing two loader indicators like in item 1.
    - The drawback of this approach is that if we don't update duration when edit milestone than we show loader indicator only for a milestone as we don't have to update timeline in such case. And if we did update duration for the milestone, we show loader indicator for the whole timeline, which is inconsistent.
    - OR we can always show a loading indicator for the whole timeline when updating milestones no matter if the duration was changed or not which is consistent. But it is less nice for user to see loading indicator for the whole timeline when he updates just one milestone.

**Comment by vikasrohit** [comment]
Got it @maxceem. I think the last option in your suggestions list is best from the options.
I have one more option which we might try. Can we show the loader only for the milestone and keep it loading (if we dispatch a chained promise for the two actions i.e. single chained promise of patching milestone and fetching loading timeline again) until we get the new timeline back. It would not silently call the timeline but it would silently update the timeline UI.

**Comment by maxceem** [comment]
@vikasrohit if we keep loader only for the updated milestone we have same drawbacks as the 2nd option with a silent update. The thing is, that if we don't block the UI for milestones which are being updated user can start interacting with them. And when the timeline update is finished we redraw updated milestones which will lead to the loss of the changes made by a user while the request was processed by the server.
There is only a small chance for this to happen. But if it happens it would be hard to track and reproduce related issues.

If you like the last option, which sub-option you prefer 3.1 or 3.2?

**Comment by maxceem** [comment]
@vikasrohit done

**Comment by vikasrohit** [comment]
@maxceem seems to work fine mostly, however, I think we might need to scroll back to the original position because now if I am marking a milestone as complete which is in the last of the timeline, it scrolls me back to the top of the timeline once the milestone is updated and timeline is refreshed.

**Comment by vikasrohit** [comment]
Closing the issue as its work is done. Created separate issue #2325 for scrolling back to the milestone.
