### ISSUE TITLE
Update phase, timeline and milestone sequentially instead of parallel

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2292]
There is some limitation of the backend which doesn't let us update phase, timeline and milestone in parallel see https://github.com/topcoder-platform/tc-project-service/issues/118#issuecomment-410433410

So we have to update them sequentially instead, see https://github.com/topcoder-platform/tc-project-service/issues/118#issuecomment-410611581

**Comment by vikasrohit** [comment]
@maxceem just to be sure, we only need to make timeline and milestone call sequential, we can still do phase and timeline calls in parallel.

**Comment by maxceem** [comment]
This issue on the backend is no more reproducible, probably has been fixed https://github.com/topcoder-platform/tc-project-service/issues/118#issuecomment-410908746

I'm marking this issue as **invalid** for now.

**Comment by vikasrohit** [comment]
Closing
