### ISSUE TITLE
Need to think how would we handle reactivating an active phase

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2298]
How milestones should behave when one reactivate a phase e.g. first change the status of the in progress phase to the `draft` and then `in progress` again. Right now it rebuilds the milestones from scratch and looses all data in the milestones previously set. IMO, that should be the way it should, however, we can either show a alert message about this or just don't allow moving back to any other status from `in progress` status. We can introduce a new status `paused` to facilitate the use case where manager/copilot wants to pause the time line for some time due to unavoidable circumstances.

we should also not allow changing the startDate of the phase once it is marked `in progress`.

fyi @rmjmccormick @RishiRajSahu @acshields @vic-topcoder

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-285

**Comment by RishiRajSahu** [comment]
@maxceem as discussed offline - 
**if phase has timeline -**  and user choose `In Progress` we have to show alert with warning, as soon as phase is active we disable status select and show tooltip when user hovers it, that status is controlled by timeline. Same like we show tooltip for duration and progress.

**Comment by maxceem** [comment]
@RishiRajSahu replaced browser confirmation dialog with the modal popup with styles predefined in the connect-app

![image](https://user-images.githubusercontent.com/146016/43987250-93718c14-9d50-11e8-820c-9d18277311d1.png)

**Comment by RishiRajSahu** [comment]
Extended fix for this one is covered in https://github.com/appirio-tech/connect-app/issues/2350
