### ISSUE TITLE
[PROJECT] No First name and Last name displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#230]
Description
-----------------------------------------------------------------
[PROJECT] No First name and Last name displayed

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/336) - Created By You (pat_monahan)
- Click Dashboard
- In the "PROJECT TEAM"
- Add Team Members
- Check the First name and Last name displayed

Expected Result(s)
-----------------------------------------------------------------
- Must display the first name and last name

Actual Result
-----------------------------------------------------------------
- No First name and Last name displayed

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_5-16-10](https://cloud.githubusercontent.com/assets/4592712/18936302/dbc69c72-8603-11e6-86a1-54923aa7759c.png)

**Comment by fnisen** [comment]
This is happening b/c of the Dev environment, in which names are masked.
