### ISSUE TITLE
Show phase specification tab to managers and copilots

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2300]
Let's keep the specification tab still visible for managers and copilots. There is valuable information that can be used during project upgrade process.

Right now we hide the specification tab for everybody (after the fix), but it should be only hidden from customers really.

@acshields FYI

**Comment by maxceem** [comment]
Done by https://github.com/appirio-tech/connect-app/commit/9f98dce3a543835f5d7dfe4c7f33535d16218258

**Comment by RishiRajSahu** [comment]
Done and merged to dev.
