### ISSUE TITLE
Remove workaround for retrieving timeline

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2303]
Previously there was an issue on the backend https://github.com/topcoder-platform/tc-project-service/issues/116 which causes us to use a workaround and make one more additional API request https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/productsTimelines.js#L38.

As the backend issue is now fixed, we can remove this workaround.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-290

**Comment by maxceem** [comment]
There appears to be another issue in the backed, so we have to keep the workaround for now https://github.com/topcoder-platform/tc-project-service/issues/159

**Comment by vikasrohit** [comment]
It is fixed and deployed to the production with 2.4.4
