### ISSUE TITLE
When update only status of phase, it's not updating in UI

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2304]
When editing phase and update only the `status` UI is not updated until page reload.

To reproduce:
1. Open any project with phases https://connect.topcoder-dev.com/projects/6967/plan
2. Click **edit** phase and change only the Status
     
     <img width="761" alt="only-status-phase" src="https://user-images.githubusercontent.com/146016/43756598-fda1dc26-9a47-11e8-9619-898baf99c7ae.png">

3. Click **update milestone**
4. Click **edit** phase again and you will see that status field back to previous value.
5. Reload the page, and open edit form again. Value of the status shown updated as expected.

**Comment by vikasrohit** [comment]
I saw this yesterday when testing something else on dev env. Thanks @maxceem for filing it. Is it possible to get it done EOD today?

**Comment by maxceem** [comment]
I think yes, will put it on the short list.

**Comment by maxceem** [comment]
@vikasrohit done

**Comment by vikasrohit** [comment]
Thanks @maxceem. Do you think the changes to the SelectDropdown can affect other places where it is used right now or the changes are backward compatible?

**Comment by maxceem** [comment]
It's being used only in two more places, I've checked them and didn't find any new issues caused by my changes. By logic, it also doesn't have to break anything aka backward compatible.

**Comment by vikasrohit** [comment]
👍

**Comment by vikasrohit** [comment]
Working fine. Closing.
