### ISSUE TITLE
[$60] Radio slider UI is disturbed on production

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2305]
<img width="1280" alt="screen shot 2018-08-07 at 12 27 34 pm" src="https://user-images.githubusercontent.com/2417632/43759698-acc4f2b6-9a3d-11e8-9c72-7c3b0317c776.png">

fyi @RishiRajSahu @gondzo

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-292

**Comment by simranb86** [comment]
@gondzo Please assign me this - i don't see i have rights to assign myself.

**Comment by simranb86** [comment]
@gondzo getting below issues (not sure if README.md is updated and the code base is run as it is). Kindly confirm

found 141 vulnerabilities (31 low, 87 moderate, 20 high, 3 critical) in 14092 scanned packages
  run `npm audit fix` to fix 109 of them.
  26 vulnerabilities require semver-major dependency updates.
  6 vulnerabilities require manual review. See the full report for details.

**Comment by simranb86** [comment]
Also there is huge list of peer dependencies in the current code base. 

Build failed with error code: 1
npm WARN draft-js-link-plugin@1.2.2 requires a peer of draft-js@0.10.1 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js-link-plugin@1.2.2 requires a peer of react@15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN draft-js-link-plugin@1.2.2 requires a peer of react-dom@15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-responsive@4.1.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@0.9.1 requires a peer of react@^0.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-select@0.9.1 requires a peer of react-dom@^0.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-switch-button@1.1.2 requires a peer of react@^0.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN connect-app@1.1.0 No repository field.
npm WARN connect-app@1.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/tc-accounts/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@3.13.1 (node_modules/tc-accounts/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@3.13.1 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by simranb86** [comment]
@gondzo with fresh setup also i get same issues, looks like setup guide needs clear steps or some guidance on above issues, hence opening for others.

**Comment by Gauravseta** [comment]
@gondzo it shud look properly now.
#2436

**Comment by simranb86** [comment]
@gondzo @Gauravseta Did you get above issues like me while setting env? If yes, could you suggest the fix for the same. It would help me get env in place for future tickets.

**Comment by gondzo** [comment]
@simranb86 no, I didn't get such errors. Can you post the full build log and node/npm versions. build log should be similar to https://circleci.com/gh/appirio-tech/connect-app/2135?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by vikasrohit** [comment]
@simranb86 Do you have latest node running on your machine? I am using v8.5.0, so try that if you can.

**Comment by simranb86** [comment]
@vikasrohit thanks - that did the trick.

**Comment by simranb86** [comment]
@gondzo is this open for pickup again as i see you removed "Ready for Review" ?

**Comment by Gauravseta** [comment]
@simranb86 no it is not..as i am updating PR.
