### ISSUE TITLE
*High Priority* Formatting in Messaging (CSS Issue) 

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2310]
### Expected behavior
Text in messaging should fit within the parameters of the white messaging box (post card), and have scrolling behavior.

![image](https://user-images.githubusercontent.com/41118149/43794406-fd57940a-9a32-11e8-947a-577ecbf771f8.png)

### Actual behavior
Currently text in messaging is spilling over the parameters of the post card and is not scrolling.

<img width="954" alt="screenshot" src="https://user-images.githubusercontent.com/41118149/43793804-77ba8632-9a31-11e8-85e9-3b2d53a16853.png">

--

Identified Issue Location
https://connect.topcoder.com/projects/5732

**Comment by vikasrohit** [comment]
Patched on production.
