### ISSUE TITLE
[$60] System spell check is not working with post composer

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2311]
### Expected behavior
When typing a message in the post composer, the system should be able to highlight the misspelled words. This feature is working in the basic draft.js. It is really important to enable spell check as it prevents typos when our managers/copilots message customers.

Side question: is there a plugin for Draftjs that allows for Grammerly integration, or third-party spelling and grammar suggestions?

### Actual behavior
System spell check (while typing) isn't working on Connect.
![image](https://user-images.githubusercontent.com/8484061/43794620-b79c3f8c-9a33-11e8-8f05-055171de3699.png)

FYI @acshields

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-299

**Comment by KevinLeigh** [comment]
PR created here -> https://github.com/appirio-tech/connect-app/pull/2411/
