### ISSUE TITLE
Remove unwanted calls to get phase products

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2315]
Remove unwanted call to get phase products, as now phase can return products on passing `fields`.

For now to get a project with phases and products we make multiples calls:
- get list of phases (1 call)
- for each phase get list of products (`phases.length` calls)

Now API supports `fields` query param when requesting the list of phases `/v4/projects/6976/phases?fields=status,......,products` which can let us get `products` list optionally. So we can replace multiple calls with one.

Should list in `fields` param all the phase properties we need + `products`.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-302

**Comment by vikasrohit** [comment]
👍

**Comment by maxceem** [comment]
It's done, but there is some issue server-side which prevents of doing it the best way https://github.com/topcoder-platform/tc-project-service/issues/160

For now, I'm making a request without encoding `field` param, like this:
```
https://api.topcoder-dev.com/v4/projects/6978/phases?fields=products,budget,createdAt,createdBy,details,duration,endDate,id,name,progress,projectId,spentBudget,startDate,status,updatedAt,updatedBy
```

When server issue is fixed, this [line](https://github.com/appirio-tech/connect-app/commit/02831ad6740da5134de440a0eb9365b3a2918c33#diff-4aca581cc63538723f149e6202550e93R74) should be uncommented to make request in a safe way with encoded `field` param like this:
```
https://api.topcoder-dev.com/v4/projects/6978/phases?fields=products%252Cbudget%252CcreatedAt%252CcreatedBy%252Cdetails%252Cduration%252CendDate%252Cid%252Cname%252Cprogress%252CprojectId%252CspentBudget%252CstartDate%252Cstatus%252CupdatedAt%252CupdatedBy
```

**Comment by vikasrohit** [comment]
@maxceem I have added decoding logic for fields, so now you have to update the code back to what it ideally should be. 😬 Let me know if still not behaving as expected.

**Comment by maxceem** [comment]
@vikasrohit it works! So now fields param is encoded.

**Comment by RishiRajSahu** [comment]
Done and pushed.
