### ISSUE TITLE
Updating phase start date when when marking it as active

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2319]
By default the `startDate` of the phase is set as the creation Date or, if adding explicitly, one day more than the latest `endDate` of all existing milestones.

When we mark phase as active the timeline's first milestone's startDate gets updated with the current Date but the phase startDate doesn't obeys this. So when marking phase as active the `startDate` of phase should also be updated with current Date

**Comment by vikasrohit** [comment]
fyi @acshields @vic-topcoder @rmjmccormick

**Comment by RishiRajSahu** [comment]
Seems to be working fine in dev.
