### ISSUE TITLE
[$50] Reduce number of calls to fetch the auth token

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2320]
### Expected behavior
Ideally we should send only one call to the identity api to get refreshed token

### Actual behavior
it is making more than one call, when user refreshes the page

### Screenshot/screencast
<img width="1246" alt="screen shot 2018-08-06 at 2 52 18 pm" src="https://user-images.githubusercontent.com/2417632/43821389-a75aae64-9b06-11e8-983e-2355746ae133.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-305

**Comment by vikasrohit** [comment]
@maxceem do you have idea about how to fix this situation? It is not on priority, but we can take care of it in next release.

**Comment by maxceem** [comment]
@vikasrohit I don't have ideas from the top of my head as I've never got in touch with authorization in the connect-app. So as it has minor priority, probably I'll try to dig it the last after the rest of tasks in this milestone.

**Comment by vikasrohit** [comment]
Makes sense.

**Comment by vikasrohit** [comment]
Moving one release further.

**Comment by nahidshahin** [comment]
@maxceem I want to work on this issue, can you please assign it to me?

**Comment by KevinLeigh** [comment]
Hey there @nahidshahin, if you cannot complete this issue please assign to me. Thank you

**Comment by maxceem** [comment]
@nahidshahin, please, update if you still working on this issues and the reasons for delay if any. Otherwise the I'll have to open this issue to pick up in 1 hour.

**Comment by maxceem** [comment]
Due to inactivity of the previous participant, this issue is now open for pick up.

**Comment by vigneshTheDev** [comment]
Hi, I would like to work on this. Can you please assign this to me?

**Comment by vigneshTheDev** [comment]
I started working on it.

**Comment by maxceem** [comment]
@vigneshTheDev it yours since you've commented. To make it more clear I can assign you to this issue in the interface. To do so, please, accept the invitation to this repo which has to pop up to you email. Thanks.

**Comment by KevinLeigh** [comment]
@maxceem Hey there, please see comment here -> https://github.com/appirio-tech/connect-app/issues/2320#issuecomment-419962126

**Comment by maxceem** [comment]
@KevinLeigh as I've mentioned in another issue comment https://github.com/appirio-tech/connect-app/issues/2279#issuecomment-419857847 we cannot let participants claim issues before the current participant asked to unassign him or someone from team marked the issue as open for pick up.

So the first who claims issue after it's become open for pick up, get it.
Thanks.

**Comment by KevinLeigh** [comment]
@maxceem Thank you for the update, I understand :)

**Comment by maxceem** [comment]
@vigneshTheDev Ok, thanks for the update. Can we still avoid calling the function to get token twice to keep it clear? 

Also, if I've got it right, in case token is not expired we don't make an actual API call at all. 
But what if a token is already expired, could it be that we make am API call twice?

**Comment by vigneshTheDev** [comment]
> Can we still avoid calling the function to get token twice to keep it clear?

This is not recommended because this will require checking if the token is expired in many places wherever the getFreshToken is called. This includes all the future uses of the function as well. This moves the concern from a single point to multiple points.
To avoid confusion, can we log it when it's taken from the cache and when actual call is made? Please confirm if we still want to avoid the call?

> But what if a token is already expired, could it be that we make an API call twice?

Still, the API is not called twice as[ the Promise](https://github.com/appirio-tech/accounts-app/blob/15f6c61c871470c297405d4670b4bf33717e2bfd/core/auth.js#L244) for the ongoing API call is cached.

**Comment by maxceem** [comment]
@vigneshTheDev got it. Please, hold on a little bit with this issue I'll look into details you've provided.
Meanwhile, I think you can pick up other issues if you see any available and interesting for you, as looking into this may take a while, but I hope to update on this today.

**Comment by vikasrohit** [comment]
Agreed.

**Comment by maxceem** [comment]
@vigneshTheDev thank you for looking into this issue and your feedback. As research for this issue has been done but no fix implementation is required I'm thinking about providing the compensation for this issue as $50 for the research part. 
Let me know if it feels fair for you or no. If you have any concerns regarding it please don't hesitate to reach back with your thoughs.

**Comment by vigneshTheDev** [comment]
Thank you @maxceem, yes it's fair.
