### ISSUE TITLE
Adding ability of requesting extension for each milestone

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2321]
We should allow each milestone to request for extension.

fyi @vikasrohit

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-306

**Comment by maxceem** [comment]
Do we need the ability to extend Delivery milestone?

![image](https://user-images.githubusercontent.com/146016/44499483-a0648100-a6b6-11e8-863a-0b4bead4c096.png)

**Comment by maxceem** [comment]
@vikasrohit Done for each milestone except Delivery one as we probably don't need it there. Please let me know if we also need an extension for the delivery milestone.

**Comment by vic-topcoder** [comment]
@acshields  FYI

I think we do not need extension for delivery

**Comment by vikasrohit** [comment]
Agreed with both @maxceem and @vic-topcoder. However, the purpose of this ticket is to add that capability to every milestone component (or rather in the common Milestone component) so that we can enable disable that as per requirements.
@maxceem as we discussed that we are going to have `metadata` on `milestoneTemplates` which would give us the capability of adding more configuration options for milestones. We would use that to enable/disable the `Request Extension` feature to be generic.

**Comment by vikasrohit** [comment]
@maxceem I think we are okay for now, we would take care of moving it to a common place which is controllable via config, later after we are done with ability of `metadata` and started using it in at least one other use case.

**Comment by maxceem** [comment]
@vikasrohit so far all the logic for extension moved to one HOC, but we still has to insert variables in each milestone type into the places where we want to show `extension requests dialog`, `extension confirmation dialog` and a `button to show extension request` as places can be different depend on milestone type structure.

Also we have to control the blue line and dots which goes along these dialog for each milestone type individually. We can still try generalize this in the future if there is need.

We can for sure implement control the visibility of this feature by `metadata` as you mentioned above.

**Comment by vikasrohit** [comment]
Agreed on all points. 👍

**Comment by vikasrohit** [comment]
@maxceem it seems it is not refreshing the status of approved extension for `community-work` milestone. It shows correct values after refreshing the page and if user clicks the `Approve Extension` button again after first click (because of the issue), it keeps the dates of the next milestone unmoved.

**Comment by maxceem** [comment]
@vikasrohit I went through all the milestones, it did happen to me once for `phase-specfication` but I couldn't reproduce the second time for any milestone including `phase-specfication`, `community-work` and `final-designs`. 

So far I suspect that server returns not-updated timeline after we update milestone like in this issue https://github.com/topcoder-platform/tc-project-service/issues/159 but I haven't caught the requests yet as I cannot reproduce it one more time so far.

In case you will reproduce it again, could you please log responses of the two requests like this:
- patch milestone
- get timeline

![image](https://user-images.githubusercontent.com/146016/44512323-b5f49d80-a6ec-11e8-85ab-567619d12caa.png)

I'll also keep trying to reproduce it.

**Comment by maxceem** [comment]
I've cought it.

The requests are called one by one:
![image](https://user-images.githubusercontent.com/146016/44512713-07e9f300-a6ee-11e8-9201-54325947aee6.png)

- `PATCH https://api.topcoder-dev.com/v4/timelines/986/milestones/4526` with data
   ```
    {
  "param": {
    "details": {
      "content": {
        "extensionRequest": null
      }
    },
    "duration": 8
  }
   }
   ```

   Returns correct updated response
   ```
    {
  "id": "d9118731-bd50-4718-a68b-b7a3b6ebea37",
  "version": "v4",
  "result": {
    "success": true,
    "status": 200,
    "content": {
      "id": 4526,
      "name": "Timeline start (design)",
      "description": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
      "duration": 8,
      "startDate": "2018-08-23T00:00:00.000Z",
      "actualStartDate": "2018-08-23T00:00:00.000Z",
      "endDate": "2018-08-30T00:00:00.000Z",
      "completionDate": null,
      "status": "active",
      "type": "phase-specification",
      "details": {
        "content": {
          "extensionRequest": null
        }
      },
      "order": 1,
      "plannedText": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
      "activeText": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
      "completedText": "Specification is completed. We're now working on the design options.",
      "blockedText": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
      "hidden": false,
      "createdAt": "2018-08-23T07:55:51.000Z",
      "updatedAt": "2018-08-23T07:56:37.000Z",
      "createdBy": 40152933,
      "updatedBy": 40152933,
      "timelineId": 986
    },
    "metadata": {
      "totalCount": 1
    }
  }
   }
   ```

- `GET ttps://api.topcoder-dev.com/v4/timelines?filter=reference%3Dproduct%26referenceId%3D2061`
    returns not-updated data: extended milestone is not extended yet, and the dates for following milestones are not updated yet.
    ```
    {
  "id": "2b4093a7-0ff8-4807-a675-28f893ea38d1",
  "version": "v4",
  "result": {
    "success": true,
    "status": 200,
    "content": [
      {
        "createdAt": "2018-08-23T07:55:51.000Z",
        "updatedAt": "2018-08-23T07:55:51.000Z",
        "id": 986,
        "name": "Welcome to the Design Iteration (long) phase",
        "description": "This is the first stage in our project. We’re going to show you the detailed plan in your timeline, with all the milestones.",
        "startDate": "2018-08-23T00:00:00.000Z",
        "endDate": null,
        "reference": "product",
        "referenceId": 2061,
        "createdBy": 40152933,
        "updatedBy": 40152933,
        "milestones": [
          {
            "updatedBy": 40152933,
            "hidden": false,
            "endDate": "2018-08-27T00:00:00.000Z",
            "completedText": "Specification is completed. We're now working on the design options.",
            "activeText": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
            "timelineId": 986,
            "description": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
            "type": "phase-specification",
            "duration": 5,
            "createdAt": "2018-08-23T07:55:51.000Z",
            "createdBy": 40152933,
            "name": "Timeline start (design)",
            "plannedText": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
            "actualStartDate": "2018-08-23T00:00:00.000Z",
            "details": {
              "content": {
                "extensionRequest": {
                  "duration": 3
                }
              }
            },
            "completionDate": null,
            "id": 4526,
            "blockedText": "We are preparing the final specification for the design work. Your copilot will communicate the details of the phase on the Posts thread before we begin work.",
            "startDate": "2018-08-23T00:00:00.000Z",
            "status": "active",
            "order": 1,
            "updatedAt": "2018-08-23T07:56:34.000Z"
          },
          {
            "updatedBy": 40152933,
            "hidden": false,
            "endDate": "2018-09-03T00:00:00.000Z",
            "completedText": "Great news! Designs are ready for review and selection.",
            "activeText": "We're currently designing the proposals. We will update this milestone with a list of all these soon.",
            "timelineId": 986,
            "description": "We will be designing several independent proposals in accordance with your specifications for you to choose from.",
            "type": "community-work",
            "deletedBy": null,
            "duration": 7,
            "createdAt": "2018-08-23T07:55:51.000Z",
            "deletedAt": null,
            "createdBy": 40152933,
            "name": "Design development",
            "plannedText": "We will be designing several independent proposals in accordance with your specifications for you to choose from.",
            "actualStartDate": null,
            "details": {},
            "completionDate": null,
            "id": 4527,
            "blockedText": "We're currently designing the proposals. We will update this milestone with a list of all these soon.",
            "startDate": "2018-08-28T00:00:00.000Z",
            "status": "reviewed",
            "order": 2,
            "updatedAt": "2018-08-23T07:56:17.000Z"
          },
    ```

Here is related code https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/productsTimelines.js#L235-L250

**Comment by vikasrohit** [comment]
Ohk, understood. I am thinking of keeping a reference to the timeline in phase/product so that we don't have to look for it by LIST operation and rather we should always GET it by id. That should resolve the issue as it always fetches data from database which always up to date.

**Comment by vikasrohit** [comment]
@maxceem for this particular case, I think we can always call [get timeline by id](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/productsTimelines.js#L79) instead of loading timeline by reference and referenceId, right? We always know the timeline and product id in this action. So, I guess you can use that to fix the situation here.

**Comment by maxceem** [comment]
@vikasrohit good solution. Done it for extension and also for milestone updates, as when we update milestone duration, we also have to update the whole timeline.

**Comment by vikasrohit** [comment]
👍

**Comment by RishiRajSahu** [comment]
working fine on dev. closing.
