### ISSUE TITLE
Two milestones are active at the same time when phase is made active twice

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2323]
### Expected behavior
It should not activate and update the start date of the first milestone when there is already an active milestone for the timeline.

### Actual behavior
It activates and updates the start date of the first milestone even if there is already active milestone.

### Steps to reproduce the problem
- Add a new phase to a project
- Mark phase `In Progress`
- Notice the timeline being active now and first milestone being active as well
- Now mark the first milestone complete
- Update the phase status to be `draft`
- Update the phase status to be `In progress` again
- Notice the timeline, it now has two active milestones
- Also notice that it updates the start date of the first milestone to current date as well

### Screenshot/screencast
<img width="776" alt="screen shot 2018-08-08 at 2 28 53 pm" src="https://user-images.githubusercontent.com/2417632/43827421-69dd6232-9b17-11e8-953a-b3a7c772ff5e.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot/Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
It turns out that backend changes are not required as we are making call on front end to update the status of the first milestone.

**Comment by RishiRajSahu** [comment]
done and merged to dev.
