### ISSUE TITLE
Spinner stepUp and stepDown button not available in mobile UI to edit basic detail (duration) of the milestone

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2326]
**Expected behavior :** 
Describe : Spinner stepUp and stepDown button should available in mobile UI to edit basic detail (duration) of the milestone.

**Actual behavior**
Describe: Spinner stepUp and stepDown button not available in mobile UI to edit basic detail (duration) of the milestone.

**Description :**

Spinner stepUp and stepDown button not available in mobile UI to edit basic detail (duration) of the milestone. It's actual behavior for Duration field ??

**Test Feature :** 
Ability   to allow copilot/manager to edit basic details (start date, duration, texts,   status etc) of the milestone
--
**Project Name** : Test project for V 2.4.4 Mobile UI Phase timeline - Front end test

**Mobile UI :** 

![spinner stepup and stepdown button not available in mobile ui to edit basic detail duration of the milestone_mobile ui](https://user-images.githubusercontent.com/30447858/43847485-542be904-9b4e-11e8-9a00-ad53e6a27953.PNG)
**Web UI :**
![spinner stepup and stepdown button not available in mobile ui to edit basic detail duration of the milestone_web ui](https://user-images.githubusercontent.com/30447858/43847505-5f4b3d80-9b4e-11e8-9750-e3ba642e47f8.PNG)

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please check

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 browsers have different way of rendering depending upon the devices, Please verify the mobile related issues on actual device also. If you open this on actual device and try to edit the duration field the numeric keypad appears on screen. This is something we don't control.

Feel free to open any other device related issues after verifying them on actual mobile device.
