### ISSUE TITLE
Start-End date summary on phase card, not reflect the duration as per milestones in the timeline : Mobile UI

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2327]
**Expected behavior :** 
Describe : Start-End date summary on phase card, should reflect the duration as per milestones in the timeline : Mobile UI

**Actual behavior**
Describe: Start-End date summary on phase card, not reflect the duration as per milestones in the timeline : Mobile UI

**Test Feature :** Start-End date summary on phase card, should reflect the duration as per milestones in the timeline

**Description :**

Start-End date summary on phase card, not reflect the duration as per milestones in the timeline : Mobile UI. It's actual behavior for this field ??

**Project Name :** Test project for V 2.4.4 Mobile UI Phase timeline - Front end test

**Mobile UI :** 
![start end date summary on phase card should reflect the duration as per milestones in the timeline_mobile ui](https://user-images.githubusercontent.com/30447858/43848329-5365cc72-9b50-11e8-8121-500bb58c1f25.PNG)

**Web UI :**
![start end date summary on phase card should reflect the duration as per milestones in the timeline_web ui](https://user-images.githubusercontent.com/30447858/43848352-6072fc8c-9b50-11e8-8f22-d589d1fb5c64.PNG)

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please check

**Comment by vikasrohit** [comment]
@deepakanbarasan1 we don't have that for mobile view by design https://marvelapp.com/8a94680/screen/41372923. Please feel free to reopen the issue if you were concerned about something else.
