### ISSUE TITLE
Checkpoint-review : Design Link should not appears out of the Design link field

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2329]
**Expected behavior :**
Describe : Checkpoint-review : Design Link should  appears in the Design link field.

**Actual behavior**
Describe: Checkpoint-review : Design Link should not appears out of the Design link field.

Test Feature : Wiring  component for checkpoint-review

**Description :**
Checkpoint-review : Design Link should not appears out of the Design link field.

Project Name : Test project for V 2.4.4 Mobile UI Phase timeline - Front end test
Phase : Visual Design
Milestone : Checkpoint-review

**Screen shot :
![checkpoint review design link should not appears out of the design link field](https://user-images.githubusercontent.com/30447858/43858144-e5f8aa2c-9b6a-11e8-8c50-767162ef7146.PNG)
**
**Checkpoint-review link title/ URL/ Edit button/ Cancle button should be aligned properly.**

**Moblie UI :**
![checkpoint-review link title url edit button cancle button should be aligned properly_mobile ui](https://user-images.githubusercontent.com/30447858/43858167-f5d4ff04-9b6a-11e8-8514-3432da4e24d0.PNG)

**Web UI :**
![checkpoint-review link title url edit button cancle button should be aligned properly_web ui](https://user-images.githubusercontent.com/30447858/43858179-02154256-9b6b-11e8-872e-3c6a97c81ee8.PNG)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-313

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please check

**Comment by deepakanbarasan1** [comment]
Wiring  component for checkpoint-review : Mobile View
Fields not aligned properly
Screen shot : 
![checkpoint review design link should not appears out of the design link field_button not aligned properly](https://user-images.githubusercontent.com/30447858/43858717-5b31dfec-9b6c-11e8-9044-4dcf4337d913.PNG)

**Comment by vikasrohit** [comment]
@vic-topcoder How would like to design this case? Ellipsis the link text?

**Comment by vikasrohit** [comment]
@maxceem for now, could you please ellipsis the link text so that it does not go out of the bounds?

**Comment by maxceem** [comment]
Done.

Wide Desktop

![image](https://user-images.githubusercontent.com/146016/43881723-bcd9cc78-9bdf-11e8-94c0-c162b46a7d17.png)

Narrow Destop

![image](https://user-images.githubusercontent.com/146016/43881747-cf532890-9bdf-11e8-920c-311be1171c17.png)

Mobile 375px

![image](https://user-images.githubusercontent.com/146016/43881781-e8ea61c4-9bdf-11e8-8e02-f0618464433d.png)

**Comment by vikasrohit** [comment]
@deepakanbarasan1 Could you please verify this now? It should be fixed in dev.

**Comment by vic-topcoder** [comment]
> @vic-topcoder How would like to design this case? Ellipsis the link text?

The URL is see important than the name of the Link. The URL is secondary and helps to identify the location for multiple marvel prototypes. I would hide the URL to leave space for the title. Title should be  link and clickable.

Check the iPhone screen where the URL is not visible
![iphone 8 copy 2](https://user-images.githubusercontent.com/8484061/43905128-3b705c7c-9ba5-11e8-99fa-972bd55f90d8.png)
![iphone 8 copy 3](https://user-images.githubusercontent.com/8484061/43905129-3b843256-9ba5-11e8-83a4-71b3af7711e0.png)

**Comment by maxceem** [comment]
@vic-topcoder @vikasrohit Updated with priority to the title and made title a link.

Wide Desktop

![image](https://user-images.githubusercontent.com/146016/43934308-5bb2d974-9c81-11e8-8a0c-7274524c1d43.png)

Narrow Desktop

![image](https://user-images.githubusercontent.com/146016/43934323-6ce95eac-9c81-11e8-97a0-81ef1bccc102.png)

Wide mobile 640-768

![image](https://user-images.githubusercontent.com/146016/43934340-80fe89b2-9c81-11e8-979f-b687ff2eaec2.png)

Narrow mobile less than 640

![image](https://user-images.githubusercontent.com/146016/43934368-9f73e928-9c81-11e8-884d-b5a49e63bd9c.png)

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder for the input.

@maxceem it looks great now. Thanks for proactively fixing this as per updated requirements. 👍

**Comment by vikasrohit** [comment]
@deepakanbarasan1 could you please verify this now? it is deployed to the dev.

**Comment by vic-topcoder** [comment]
@maxceem that looks fabulous!

**Comment by deepakanbarasan1** [comment]
Looks good

**Comment by vikasrohit** [comment]
Thanks @deepakanbarasan1
