### ISSUE TITLE
Checkpoint-review : Selected designs should have blue background

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2330]
**Expected behavior :** 
Describe : Selected designs should have blue background

**Actual behavior**
Describe: Selected designs should not have blue background

Test Feature :  Wiring  component for checkpoint-review 

**Description :**

**Checkpoint-review :** Selected designs should have blue background. It's actual behavior for this field ??

Project Name : Test project for V 2.4.4 Web UI Phase timeline - Front end test
Phase : Visual Design 17 daysAug 8-241 post
Milestone : Checkpoint-review

**Web UI :** 
![checkpoint review selected designs should have blue background](https://user-images.githubusercontent.com/30447858/43859278-dabea55a-9b6d-11e8-8c9b-5a7bd597cd65.PNG)

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please check

**Comment by vikasrohit** [comment]
Thanks @deepakanbarasan1 

[Here](https://marvelapp.com/8a94680/screen/41372918) is the design that we have to refer to fix the issue.

**Comment by maxceem** [comment]
Done. Also fixed the same issue for final-designs milestone when choosing winners.

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 are you verifying the issues which are already open. Please check the existing issues before opening a new one.

**Comment by vikasrohit** [comment]
@deepakanbarasan1 Could you please verify it? We have got this fixed in dev.

**Comment by deepakanbarasan1** [comment]
@vikasrohit  Looks good 
![checkpoint-review selected designs should have blue background_](https://user-images.githubusercontent.com/30447858/43907286-bbcbdb7c-9c12-11e8-9a60-fa2c386ea249.PNG)
