### ISSUE TITLE
Phase card cuts dropdown and tooltips

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2332]
![image](https://user-images.githubusercontent.com/146016/43878415-96635c16-9bd1-11e8-8f2a-7a348e5e1d26.png)

There was another issue https://github.com/appirio-tech/connect-app/issues/2278 which has two ways to be solved:
1. A quick one, using `overflow: hidden`.
2. A complicated one, adjusting all the inner blocks corners for various situations.

As I didn't find any issues that time I chose the quick one with `overflow: hidden`. 
But now due to the cutting issue, have to solve the https://github.com/appirio-tech/connect-app/issues/2278 the second way.

**Comment by vikasrohit** [comment]
Working fine now. Closing.
