### ISSUE TITLE
Backward compatibility - Add support to migrate old projects to new data model

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2335]
Aha! Link: https://topcoder.aha.io/features/TCCONNECT-207

Is there 2 way sync?  This is added to the git description.

**Comment by ajefts** [comment]
Testing adding a comment to the git issue.

**Comment by RishiRajSahu** [comment]
moving this to 2.4.5

**Comment by vikasrohit** [comment]
It has been developed already and we have already upgraded first project successfully.
