### ISSUE TITLE
Provide the same ability from the UI for managers

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2337]
Aha! Link: https://topcoder.aha.io/requirements/TCCONNECT-207-2

**Comment by RishiRajSahu** [comment]
@acshields Does this issue map to some feature in aha ? if yes, could you please add some details ?

**Comment by RishiRajSahu** [comment]
Found the related issue  #2336 . Moving this to backlog.

**Comment by acshields** [comment]
Hi @RishiRajSahu - I think that this was just a test that Tony was doing on some configurations between Github and Aha.  It can be disregarded.
