### ISSUE TITLE
[$75] Add tooltip to the disabled `Delivered` item in the phase status

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2339]
## Task

Add tooltip to the disabled `Delivered` item in the phase status select, same like disabled duration has:

![image](https://user-images.githubusercontent.com/146016/43939835-0c514ffa-9c9f-11e8-8473-404ef31df7e9.png)

## Note

It appeared that `ToolTip` component doesn't work inside `Dropdown` component, probably it has to be fixed inside `appirio-tech-react-components` first.

@vikasrohit
Continues https://github.com/appirio-tech/connect-app/issues/2248#issuecomment-411692163

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-319

**Comment by vikasrohit** [comment]
Moved to next release.

**Comment by jomadoye** [comment]
I am working on this, please assign me @maxceem

**Comment by Gauravseta** [comment]
@maxceem on how many issues will jomaday work? multiple allowed?

**Comment by jomadoye** [comment]
@Gauravseta I am done working on my last issues, I just need to raise PR from my fork as maxceem has informed me, I think that is a new rule, I am already working on this. thanks.

**Comment by jomadoye** [comment]
PR has been raise @maxceem, Please assign this ticket to me, thanks.

**Comment by maxceem** [comment]
@jomadoye okay, here we kind of on the edge of rules but as jomadoye already finished another issue and even tried to push just was confused that this time doesn't have rights to do that and raised a question about providing his work. I think it would be fair enough this time to let him work on this one. I know it's a little bit harder with new rules to follow the things for me also. 

@jomadoye the issue is yours. But to actually assign you to this issue please accept an invitation to this repo. Thanks.

**Comment by jomadoye** [comment]
I have accepted the invitation to this repo, thanks. @maxceem

**Comment by jomadoye** [comment]
@maxceem I just noticed the `Delivered` is not disabled 
<img width="785" alt="screen shot 2018-09-10 at 12 15 02 am" src="https://user-images.githubusercontent.com/26272732/45276174-a4521a80-b48e-11e8-827e-ced17f9e23ec.png">
Is there a specific user I should login with?

**Comment by jomadoye** [comment]
@maxceem login with copilot and visit https://connect.topcoder-dev.com/projects/6605 the `delivered` should be enabled

**Comment by maxceem** [comment]
@jomadoye ok, got it. This option will be disabled for all new projects which have a timeline with milestones. As old projects don't have it this option is enabled for them. Please, create a new project with any user, it has to be disabled there.

**Comment by jomadoye** [comment]
@maxceem What message do you want me to display on the tooltip, also I noticed this statement `same like disabled duration has` where can I see the disabled duration, thanks.

**Comment by maxceem** [comment]
@jomadoye You may use the next text for tooltip: `Phase delivery status is controlled by the statuses of individual milestones`
Regarding durtation, check the screenshot in the issue description there is `DURATION (DAYS)    17` with a tooltip shown.

**Comment by vikasrohit** [comment]
@maxceem Slight modification to the text `Once activated, phase delivery is controlled by the milestones.`
Also, just want to make sure that this option is disabled only when there is a timeline associated with a phase i.e. it should NOT disable the `Delivered` status option when there is no timeline associated with the phase, this is for backward compatibility.

**Comment by jomadoye** [comment]
@maxceem does this work 
<img width="872" alt="screen shot 2018-09-10 at 1 26 22 am" src="https://user-images.githubusercontent.com/26272732/45277942-b6d15180-b498-11e8-852a-e48ed0e60a01.png">.
The tooltip is on the drop down not the `disabled` option.

**Comment by maxceem** [comment]
@jomadoye No, the idea here is to explain to a user why he cannot choose the `Delivery` option. So it only has to appear when we put the mouse cursor on the disabled `Delivery` option.

**Comment by maxceem** [comment]
@jomadoye are you still working on this issue? Please update or I'll have to open it to pick up for other participants. Thanks.

**Comment by rashmi73** [comment]
@maxceem can you please assign it to me as it is now 24hrs approx. 12 hr deadline is reached long back . thanks

**Comment by maxceem** [comment]
@rashmi73 as I've mentioned in another issue comment https://github.com/appirio-tech/connect-app/issues/2279#issuecomment-419857847 we cannot let participants claim issues before the current participant asked to unassign him or someone from team marked the issue as open for pick up.

So you'll have to claim it again after the issue is open for pick up if nobody claims it before you.
It's needed to keep the process fair to everyone.
Thank you.

**Comment by suppermancool** [comment]
@maxceem pls assign to me

**Comment by maxceem** [comment]
@suppermancool it's yours since you've commented. To make it more clear I can assign you to this issue in the interface. To do so, please, accept the invitation to this repo which has to pop up to your email. Thanks.

**Comment by suppermancool** [comment]
@maxceem i don't see any invitation, can you send me again, i just updated my github email 1 week ago, so i'm not sure . Did it affect my handle on topcoder for this challenge?

**Comment by suppermancool** [comment]
my email should be dat.nguyen.supper@gmail.com

**Comment by maxceem** [comment]
Ok. I'll check it in a while, meanwhile the issue is on you already. So you
can start working on it.

**Comment by suppermancool** [comment]
@maxceem the tooltip should show like this right?

<img width="974" alt="screen shot 2018-09-11 at 6 26 40 pm" src="https://user-images.githubusercontent.com/5815182/45357400-51907400-b5f0-11e8-9c57-c022c80e49a7.png">

**Comment by suppermancool** [comment]
@maxceem ready for review on
https://github.com/appirio-tech/connect-app/pull/2500

**Comment by vikasrohit** [comment]
@suppermancool Please use the updated copy as mentioned in https://github.com/appirio-tech/connect-app/issues/2339#issuecomment-419791184

**Comment by maxceem** [comment]
@suppermancool yes tooltip looks as expected on your screenshot. Please, just update the text as **vikasrohit** mentioned previously in https://github.com/appirio-tech/connect-app/issues/2339#issuecomment-419791184

**Comment by suppermancool** [comment]
@maxceem @vikasrohit updated in last commit, pls check, thanks

**Comment by maxceem** [comment]
@suppermancool I've reviewed the PR, please, have a look https://github.com/appirio-tech/connect-app/pull/2500#pullrequestreview-154988041

**Comment by maxceem** [comment]
@suppermancool thanks for quick update. Merged PR.
