### ISSUE TITLE
Development Iteration 3 and 4 Milestones there is no timeline tab

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2341]
**Expected behavior :**
Describe : Development Iteration 3 and 4 Milestones should have timeline tab

**Actual behavior**
Describe: Development Iteration 3 and 4 Milestones there is no timeline tab

Test Feature :  For each phase, there should be a timeline tab which should show the templated timeline for the phase as configured in product templates

**Description :**
Development Iteration 3 and 4 Milestones there is no timeline tab. It's actual behaviour for this field ??

Project Name : Test project for V 2.4.4 Web UI Phase timeline - Front end test
Phase : Development Iteration 3 and 4 Milestones

**Web UI :**
![for each phase_development iteration 3 and 4 milestones there is no timeline tab](https://user-images.githubusercontent.com/30447858/43958063-b363d1a0-9cc7-11e8-9934-6f97ad0a5eb0.PNG)

First character should start with upper case for all Milestones. Standard Format
Compare with Website Development phase and  Visual Design phase.

![first character should start with uppder case for all milestones](https://user-images.githubusercontent.com/30447858/43958102-e582dbf4-9cc7-11e8-8fc8-f421c9bfe277.PNG)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-320

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please check

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 please verify and close if working fine.

**Comment by vikasrohit** [comment]
These were temporary errors during the development. Closing them out as they are working fine now on production.
