### ISSUE TITLE
Delivery Links are not appear under Delivery Milestone in Mobile UI

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2342]
**Expected behavior :**
Describe : Delivery Links should appear under Delivery Milestone after adding a link in Mobile UI

**Actual behavior**
Describe: Delivery Links are not appear under Delivery Milestone in Mobile UI fter adding a link.

Test Feature :  Wiring component for design delivery

**Description :**

Delivery Links are not appear under Delivery Milestone in Mobile UI fter adding a link.

Project Name : Test project for V 2.4.4 Mobile UI Phase timeline - Front end test
Phase : Visual Design

**Mobile UI :**
![delivery links are not appear under delivery milestone in mobile ui_before add a link](https://user-images.githubusercontent.com/30447858/43967657-85da3b82-9ce2-11e8-9cfd-be6ccb36cdd9.PNG)

**Usage of unnecessary empty space**
![delivery links are not appear under delivery milestone in mobile ui_empty space](https://user-images.githubusercontent.com/30447858/43967677-94d2f5de-9ce2-11e8-9d5b-562f9c576bf4.PNG)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-321

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please check

**Comment by RishiRajSahu** [comment]
@deepakanbarasan1 please verify and close if working fine.

**Comment by gondzo** [comment]
I think this one is working fine

**Comment by vikasrohit** [comment]
Okay, @deepakanbarasan1 can you please verify it again and close the issue if not happening now?

**Comment by vikasrohit** [comment]
Marking as won't fix as it seems to be working fine. @deepakanbarasan1 please feel free to reopen it if you see this again.
