### ISSUE TITLE
[$40] remove unwanted comma from number format in id column

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#2343]
remove unwanted comma from number format in id column

![image](https://user-images.githubusercontent.com/1180747/43968462-c3807f6a-9c8c-11e8-8077-6fb4dcf8d7d8.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-322

**Comment by vikasrohit** [comment]
@vic-topcoder let us know if we have any specific reason to keep the comma.

**Comment by PrakashDurlabhji** [comment]
@gondzo MR done.
please check
