### ISSUE TITLE
Last Update column in project list view is not pulling the right value.

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#2344]
### Expected behavior
The last update column in the project list view should not pull from the create date of the newest card.   It should pull from the latest comment on any card.  This is extemely import becuase a manager or co-pilot would want to use this list view to see is they have anything to read or respond to.   Right now this column value give dis-information.

### Actual behavior
The newest created card date is used but not any comment

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/1180747/43969462-ce4a4f5e-9c8f-11e8-9d3b-13cd50ddc9ef.png)

![image](https://user-images.githubusercontent.com/1180747/43969515-02581056-9c90-11e8-9362-114f8c713415.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-415

**Comment by kbowerma** [comment]
@dmessing , @acshields ,  @ajefts 

I want to reiterate how important this one is.  Below is screenshot of my current workflow and one of my customers (only 6 not 8 ).   I want to look at one view and determine what needs my attention but the last update column is not accurate.   So I open each one of these ones by one and look at it and respond.  Before I  get to the bottom of the list which takes at least 30 minutes I already have some responses to my responses.  If I could see this list accurately sorted by the real last update and who did it.   It would save me hours each day.   The alternative is I work from email which is not leveraging the power of the platform.   I would request to set this as a priority since it seems like a relatively easy fix.



![image](https://user-images.githubusercontent.com/1180747/44158833-5ad30300-a07b-11e8-988c-5ead6c57175d.png)

**Comment by vikasrohit** [comment]
Sorry to delayed response, however, this feature is not a quick fix and right now it is behaving as per design because we never included the messaging updates in project update calculation. That actually requires coordination between two separate modules(databases) i.e. project data is in single database while messages for that project are using a separate service (database) so we can not read the message update time in a straight forward db query to get the last updated value.
However, I have a solution for that which is to keep a date `lastActivityAt` in project database which would be updated every time the project is update or its related entities (right now it would be only topics/posts for the project) are created/updated/deleted via bus events. And if we need to keep the actor data as well, we can keep `lastActivityUserId` as well. Further, after these changes are in place we might need to do a batch update to generate the initial value for these new fields.

@acshields @vic-topcoder let us prioritise this as it seems to be causing practical issues to the users.

**Comment by vic-topcoder** [comment]
By design (UX) the messages should be included in the updates on posts, files, changes in specification, project phase/milestone. Also projects with updates since the last time should be outlined with a blue bar on the left.
![screen shot 2018-08-28 at 7 58 48 am](https://user-images.githubusercontent.com/8484061/44731583-5b669300-aa98-11e8-923b-be9ed6e87183.png)

**Comment by vikasrohit** [comment]
Just for reference, we have this feature request since very long via https://github.com/appirio-tech/connect-app/issues/1415. And as I said, it need significant efforts to get it working which might affect other priority work (new reg flow). fyi @vic-topcoder @acshields

**Comment by maxceem** [comment]
Probably, as a quick workaround we can use notifications for this:
- we can highlight with blue line the projects which have some updates
- also, we can replace **last updated** date with the last notification date and even the name of the one who triggered notification
- the only limitation I see in this approach, is that we cannot sort projects using such **last updated** date, as projects come sorted from the server, which is not aware of updates as mentioned above. So if there are any updated projects which are not displayed on the first page, they won't show up on the first page if we sort by **last updated**.

**Comment by vikasrohit** [comment]
> we can highlight with blue line the projects which have some updates

Yes, we can do that.

But as you said, using it for sorting won't work which is required to improve the UX which is the actual problem because of incorrect last updated date.

**Comment by RishiRajSahu** [comment]
@vic-topcoder regarding - 
> By design (UX) the messages should be included in the updates on posts, files, changes in specification, project phase/milestone.

@vic-topcoder could you confirm in the below list of events to update the projects listing view, some events are already handled in current implementation for example changes on scope page. Also if I missed any operation please add it to the list

1. Project Updates - Updates on scope page 
2. File Updates 
3. Links Updates
4. Member Updates
5. Phase Updates(startDate, duration, budget, status, Progress, excluding Title)
6. Phase specification Updates
7. Phase posts Updates 
8. Phase timeline Updates (startDate only)
9. Phase milestone Updates (Duration Only, excluding texts and title)
10. Dashboard Posts Updates

Please add more if I missed some operation

**CC** - @acshields @kbowerma

**Comment by acshields** [comment]
@RishiRajSahu - the list above looks good.

**Comment by vic-topcoder** [comment]
> regarding the blue line for the projects. Should it be there as long as a project has any unread notifications? Or there is some other condition to show/hide it?

Yes - the line should be there to indicate unread notifications. Only for projects I'm member of, I guess, as we do not keep track of non-member notifications per project.

> could you confirm in the below list of events to update the projects…

All are correct; also milestone status change inside a phase (milestone is active, completed, the customer can interact with the milestone now, ready for acceptance).

**Comment by vikasrohit** [comment]
@maxceem I think the only missing piece here is `ready for acceptance` thing as `customer can interact with the milestone now` is essentially the `waitingForCustomer` event for which we already have [support](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/busApi.js#L456) in project service. And I am not sure about that as well. @vic-topcoder Could you please elaborate more on that?

**Comment by maxceem** [comment]
@vikasrohit we implemented setting `waitingForCustomer` in a way which includes all the cases when we are waiting for customer reaction see https://github.com/appirio-tech/connect-app/issues/2471#issuecomment-418969657

Including the case `ready for acceptance`. Let me know if some cases are desirable.

**Comment by vikasrohit** [comment]
@maxceem Thanks for pointer. Now I understood what Vic meant by `read for acceptance`, so I think we are covered now as we have implemented the logic for sending the notification whenever `waitingForCustomer` flag is set to true.

**Comment by maxceem** [comment]
@RishiRajSahu added an option to sort projects by the latest activity via PR https://github.com/appirio-tech/connect-app/pull/2535

![image](https://user-images.githubusercontent.com/146016/45793267-e9165680-bcc3-11e8-92ee-944a4353c620.png)

**Comment by maxceem** [comment]
@RishiRajSahu I've fixed the user which is displayed when we sort by activity. Now the correct user is being shown instead of updatedBy user - fyi.

**Comment by RishiRajSahu** [comment]
thanks @maxceem I have made the changes to make `Last Updated` reflect the changes as per the field `lastActivityAt` .

**Comment by deepakanbarasan1** [comment]
Working fine on development  environment
