### ISSUE TITLE
Copy `details.content` from completed milestone to the next milestone `details.prevMilestoneContent`

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2345]
When we mark a milestone as completed we should copy `details.content` from completed milestone to the `details.prevMilestoneContent` of the next milestone.

**Comment by maxceem** [comment]
Done in two ways:
- first I did requests to update current milestone and next milestone in parallel, but there is an issue at backend when updating milestones in parallel https://github.com/topcoder-platform/tc-project-service/issues/162
- so with the second commit, I've made requests sequential: first, compete the current milestone, after, update next milestone

**Comment by RishiRajSahu** [comment]
closing as changes are in dev and working fine.
