### ISSUE TITLE
Update `checkpoint-review` milestone type to use links list from `prevMilestoneContent`

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2346]
Currently, `checkpoint-review` milestone gets the list of links from manager first, and after it lets the customer to select best links.

After we introduced https://github.com/appirio-tech/connect-app/issues/2345 we can create a list of links in the previous milestone and in `checkpoint-review` milestone, only select links.

**Comment by maxceem** [comment]
Done.

Currently, I still support the old style of `checkpoint-review`.

There are two components:
- `<MilestoneTypeCheckpointReview>`  - old style component which lets manager add links
- `<MilestoneTypeCheckpointReviewOnly>` - new style component which gets links list from `details.prevMilestoneContent`

Both of them have milestone type `checkpoint-review`. The proper component is being chosen in not 100% reliable way as a temporary solution until we settle down with milestones behaviour.
To detect old/new style we check `_.get(milestone, 'details.prevMilestoneContent.links[0].type') === 'marvelapp'` if there is a design link in the provided list of links from the previous milestone.

**Comment by vikasrohit** [comment]
Thanks @maxceem. I am going to merge this in dev and validate it on dev. And if it works as expected, we need to extend this behaviour to final-designs as well.

**Comment by RishiRajSahu** [comment]
@vikasrohit done for final-designs as well with https://github.com/appirio-tech/connect-app/commit/d2b26ca7faedc904cf9e6536487f318743f06757

**Comment by RishiRajSahu** [comment]
closing as changes are in dev.
