### ISSUE TITLE
Show inline message instead of popup when we try to active phase

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2350]
If during editing milestone user selected `In Progress` status. On click of `update phase` hide the existing buttons, show an inline modal with two buttons `Ok` and `Cancel` - inline modal should warn the user about the action and show these two new buttons, on click of `Ok` it makes an api call to update, on cancel bring back the previous button and restore the dropdown.

Inline modal texts:
title - `You are about to activate the phase`
description - `This action will permanently change the status of your phase to Active and cannot be undone.`

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-328

**Comment by RishiRajSahu** [comment]
working fine on dev. closing.
