### ISSUE TITLE
Duplicate notifications emails messages and no discussions added.

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#2356]
@acshields,  @mtwomey, @dmessing

### Expected behavior
When a user adds a discussion thread they should get a response of the post and a single notfication messages.

### Actual behavior
customer created a discussion response and I got  14 emails but the message never posted all with separate message ids here are the first three:
https://connect.topcoder.com/projects/6626#comment-82825
https://connect.topcoder.com/projects/6626#comment-82824
https://connect.topcoder.com/projects/6626#comment-82826

The links just show the spinner and he may have deleted them.   However none of the post still exists here is the sample clipped from email:
```

There is a problem in the project descrition:

​

T-Mobile uses git flow and every story is developed on its own branch which is named by convention to contain the story, defect, or task id as the first characters followed by a “:”.

We do not necessarily name our branches with the Rally Artifact ID and this should not be used as a key.

The plugin should inspect each commit message for an Artifact ID:

​

US19675: Completed testing of data sevice

US20183; TA1132: Adding new data service for project catalog.

DE666: Fixed defect. Problem was reg-ex was incorrect.

​

The pre-receive hook can query the commit messages for individual rally artifacts, then verify them with Rally that they do exist are not now merely being spoofed to bypass the commit checker hook

US00000: Pushing my changes outside of any assigned story

The hook should be configurable to check if the story is in progress , and/or if the commit author is assigned to the story. These should be optional configurations.

​Visit Message or reply to this email to respond.

```

### Steps to reproduce the problem
Not sure

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

Aha! Link: https://topcoder.aha.io/requirements/TCCONNECT-350-4

**Comment by kbowerma** [comment]
Now this project wont load:   https://connect.topcoder.com/projects/6626

**Comment by mtwomey** [comment]
@vikasrohit Yeah, if you look at this - it's like the same thing posted over and over in what appears to be a single comment (somehow). Any thoughts on what went haywire here?

**Comment by kbowerma** [comment]
@mtwomey 
The project will load now but we have the message repeated 14 times.   Is there anyway someone can go into the back end and edit so the message is only their once

**Comment by vikasrohit** [comment]
@kbowerma Deleted the duplicate thread from 6626 project, however, I didn't find a project where there are 14 duplicate messages. Can you please help in locating that project?

**Comment by kbowerma** [comment]
@mtwomey, @vikasrohit   I caught one mid-flight right now.   I clicked post and nothing happens.    Your instinct is to click post again.   Even if you try to reload you get a warning 
![image](https://user-images.githubusercontent.com/1180747/44150011-a5c97014-a063-11e8-821a-816eb4862f6a.png)


here is the error message:
```
Uncaught TypeError: e.props.toggleNotificationRead is not a function
    at main.94afa754558b608a598d.js:134
    at n (main.94afa754558b608a598d.js:21)
    at r (main.94afa754558b608a598d.js:6)
    at t.value (main.94afa754558b608a598d.js:134)
    at e.notifyAll (main.94afa754558b608a598d.js:40)
    at r.close (main.94afa754558b608a598d.js:67)
    at r.closeAll (main.94afa754558b608a598d.js:21)
    at r.perform (main.94afa754558b608a598d.js:21)
    at o.perform (main.94afa754558b608a598d.js:21)
    at o.perform (main.94afa754558b608a598d.js:21)
```

**Comment by kbowerma** [comment]
@vikasrohit look at 6626 . dont you see the repeating message?    I have 14 emails that all say 
```
There is a problem in the project descrition:

​

T-Mobile uses git flow and every story is developed on its own branch which is named by convention to contain the story, defect, or task id as the first characters followed by a “:”.

We do not necessarily name our branches with the Rally Artifact ID and this should not be used as a key.

The plugin should inspect each commit message for an Artifact ID:

​

US19675: Completed testing of data sevice

US20183; TA1132: Adding new data service for project catalog.

DE666: Fixed defect. Problem was reg-ex was incorrect.

​

The pre-receive hook can query the commit messages for individual rally artifacts, then verify them with Rally that they do exist are not now merely being spoofed to bypass the commit checker hook

US00000: Pushing my changes outside of any assigned story

The hook should be configurable to check if the story is in progress , and/or if the commit author is assigned to the story. These should be optional configurations.
```

**Comment by vikasrohit** [comment]
@kbowerma Got it. I was looking for duplicate threads, it was rather duplicate posts. I managed to delete them.
Also, as we have pushed the release to production and it supposed to fix the issue of posting messages, could you please let us know if things are working fine now at your end. Ideally, it should not show post button enabled till message is posted and should reflect the posted message immediately after successful post.

**Comment by mtwomey** [comment]
@kbowerma On this one, our expectation is that it's been fixed with the last release. Was this a one-time occurrence on your end, or have you seen it in the past week? @vikasrohit Can you please clarify a bit more what in the latest release we believe has fixed it?

**Comment by vikasrohit** [comment]
@mtwomey we are positive that it is fixed with https://github.com/appirio-tech/connect-app/issues/2123 and it is deployed to the production.

**Comment by mtwomey** [comment]
Awesome, thanks @vikasrohit @kbowerma See above, I'm going to close this one out. Please keep us in the loop if you notice anything funny related to this.
