### ISSUE TITLE
[$100] Allow adding files to project through the dashboard sidebar.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2358]
### Expected behavior
We have the new file listing on the sidebar. It would be nice to add the functionality for our users to add files to the list directly (not going to other tabs and pages). It should function the same way as adding a new link to the links menu.

Current is on the left, proposed is on the right.
![screen shot 2018-08-13 at 3 12 30 pm](https://user-images.githubusercontent.com/8484061/44060992-681cf12c-9f0b-11e8-89cd-ade6209afb47.png)

@acshields FYI

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-433

**Comment by vikasrohit** [comment]
Marking it for 2.4.5. Would analyze it later and see even if possible with the next release.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas @gondzo Hey Guys, is this still be worked on? If not can it be assigned to me please ?

**Comment by nahidshahin** [comment]
@gondzo @ThomasKranitsas can you assign the issue to me, please?

**Comment by gondzo** [comment]
removing from milestone, will fix this internally
@KevinLeigh I'll still add $80 payment as most of the work is actually done here.

**Comment by KevinLeigh** [comment]
Thank you @gondzo, much appreciated.

**Comment by RishiRajSahu** [comment]
@gondzo can we create a new issue for whatever is left in this issue so that we can include that in upcoming CF ? could we merge the partial changes to dev or we need complete changes to push it.

**Comment by gondzo** [comment]
fixed and merged to dev

**Comment by vikasrohit** [comment]
Closing as working as per requirements.

**Comment by vikasrohit** [comment]
fyi @vic-topcoder @acshields for now it using `+` icon instead as we have already got changes for that. We can do quick fix after the release for the new design where we are directly showing the file upload component in the left panel.
