### ISSUE TITLE
Final designs - on winner selection UI is breaking 

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2359]
On Final designs milestone, winner selections UI is breaking if the title is long.

<img width="882" alt="screen shot 2018-08-14 at 11 50 34 am" src="https://user-images.githubusercontent.com/11248478/44076491-fff195cc-9fbd-11e8-8973-1afec181aa40.png">

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-337

**Comment by maxceem** [comment]
For big and narrow screens I've fixed it:

![image](https://user-images.githubusercontent.com/146016/44079245-1faafd8c-9fdb-11e8-9f7a-a99777edbc45.png)

But I'm not sure how to render it for mobile devices. Looks like we have to choose whether display name or text `Purchase for $100`:

![image](https://user-images.githubusercontent.com/146016/44079144-e8b851da-9fda-11e8-8d52-5b7e7fd3dd52.png)

**Comment by maxceem** [comment]
Fixed for mobile devices.

Edit mode:

![image](https://user-images.githubusercontent.com/146016/44086830-71cd550a-9ff0-11e8-8e0e-db21ac4dc134.png)

View mode:

![image](https://user-images.githubusercontent.com/146016/44086844-85072326-9ff0-11e8-9b88-c3f4fecc3988.png)

**Comment by RishiRajSahu** [comment]
In view mode we don't show the text.

**Comment by maxceem** [comment]
Done, in view mode

![image](https://user-images.githubusercontent.com/146016/44088113-8a0fc964-9ff4-11e8-80a0-ffe9005ee7b8.png)

**Comment by vic-topcoder** [comment]
For mobile we can get rid of the marvel icon to save space
