### ISSUE TITLE
[Search] Long search terms cover search button and clear icon

### ISSUE THREAD

**Issue by Colinh84** [appirio-tech/connect-app#236]
### Expected behavior
Long search terms should not cover the search button or clear icon, and should instead be scrollable with text cursor

### Actual behavior
Long search terms cover the search button and clear icon.

### Steps to reproduce the problem
- Enter a long search term in the top search box at https://connectv2.topcoder-dev.com/projects/
- Search box allows ttped text to cover clear icon and search button.

### Screenshot/screencast
Attach or link a resource.
![5](https://cloud.githubusercontent.com/assets/2287621/18930316/272a9b32-85fa-11e6-8bec-1981ac860750.png)

--

#### Environment
- OS: Win10
- Browser (w/version): Chrome 53
- User role (client, copilot or manager): client
- Account used: christina_uw

**Comment by fnisen** [comment]
<img width="624" alt="screen shot 2016-10-13 at 2 03 16 pm" src="https://cloud.githubusercontent.com/assets/12552247/19366928/e282e020-914d-11e6-8376-d5284e1b0c8f.png">

@sirakovaDimitrina, @vic-appirio still seeing this issue.

**Comment by vic-appirio** [comment]
The text should never cover the clear icon; reassigning for @sirakovaDimitrina to fix

**Comment by fnisen** [comment]
Thanks @vic-appirio and @sirakovaDimitrina.

**Comment by vic-appirio** [comment]
Fixed in react-components
