### ISSUE TITLE
When we add links and `GET_NOTIFICATIONS_PENDING` action happens, it refreshes form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2362]
When we click add links and open form to add link in any of the milestones with such functionality. 

![image](https://user-images.githubusercontent.com/146016/44128874-f180de2a-a077-11e8-92fb-8e76477cc29f.png)

If during links adding action `GET_NOTIFICATIONS_PENDING` happens, it closes adding link form, see video http://take.ms/GgqLd

cc @RishiRajSahu

**Comment by vikasrohit** [comment]
@maxceem the same thing is happening when you just hover over any milestone's title. Could you please get it fixed in both cases?

**Comment by maxceem** [comment]
@vikasrohit thanks for the catch! It will help a lot to fix it for both cases.

**Comment by maxceem** [comment]
Done with PR https://github.com/appirio-tech/connect-app/pull/2370

**Comment by maxceem** [comment]
@vikasrohit yes, the issue was very common for anything which triggers milestone render.

**Comment by vikasrohit** [comment]
Cool. Its working fine for me now. Thanks.
