### ISSUE TITLE
Warning: You are about to manually change the start/end date

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2363]
There is a situation where I get this warning without changing dates:

![image](https://user-images.githubusercontent.com/146016/44131345-ec096c5c-a084-11e8-98c0-70eecba967c2.png)

## How to reproduce

1. Create a new **Visual Design** project
2. Add a new product **Design Iteration (long)**
3. Open edit form for **Design Iteration (long)** and change status to **In Progress**
4. The warning will be shown even I didn't change the starting date.

Is it desired behavior or no?

cc @RishiRajSahu

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-340

**Comment by maxceem** [comment]
@RishiRajSahu Hmm, actually I cannot reproduce this again, probably it was some particular situation connected with dates in the previous phase. But I didn't change date manually.

**Comment by maxceem** [comment]
Can reproduce it again:
1. Create a new **Visual Design** project
2. Completed all the milestones of the phase
3. Add new phase **Design Iteration (short)**
4. Try to change status to `In Progress` of the phase
    
    ![image](https://user-images.githubusercontent.com/146016/44134316-f48e78ba-a096-11e8-885f-f5bc7219dfee.png)

5. Looks like a new phase has been created with `startDate` before the finish of the first milestone.

**Comment by vikasrohit** [comment]
@maxceem @RishiRajSahu I think we are good for now. Warning is just an indication to the user about a possible overlap. It is not preventing them to update the phase, so we can take care of it later.

**Comment by vikasrohit** [comment]
Closing the issue for now as it does not harm the usability. We can take this up later when we have reports about this causing confusion or issues to the users.
