### ISSUE TITLE
Complete/Delivery milestone is not marked as completed after clicking complete

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2364]
## How to reproduce

1. Create a new **Visual Design** project
2. Complete all the milestones of the phase without requesting final fixes
3. End up with such situation:
    
    ![image](https://user-images.githubusercontent.com/146016/44134212-4c8e7ae8-a096-11e8-91f2-bb484219d248.png)

**Comment by maxceem** [comment]
Same for **Design Iteration (short)** product:

![image](https://user-images.githubusercontent.com/146016/44134420-7331e616-a097-11e8-86f2-f073680e92d7.png)

**Comment by vikasrohit** [comment]
@RishiRajSahu Haven't you fixed this yesterday evening?

**Comment by maxceem** [comment]
Fixed with PR https://github.com/appirio-tech/connect-app/pull/2373

@RishiRajSahu FYI fixing this issue also fixed two issues you've texted me:
1. phase not getting marked as delivered on completing final-fixes milestone
2. on accept in delivery milestone it should mark itself and phase as delivered

**Comment by vikasrohit** [comment]
Working fine. Thanks.
