### ISSUE TITLE
Menu popup for a post is not completely visible

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2365]
<img width="788" alt="screen shot 2018-08-15 at 11 59 21 am" src="https://user-images.githubusercontent.com/2417632/44134477-c924c31e-a082-11e8-80b1-356df139dc19.png">

@maxceem Can you please get it resolved quickly (EOD today)?

**Comment by maxceem** [comment]
@vikasrohit yes, will fix it asap

**Comment by maxceem** [comment]
Fixed by PR https://github.com/appirio-tech/connect-app/pull/2367, keeping in mind this one https://github.com/appirio-tech/connect-app/issues/2310

See video http://take.ms/mDdYn

**Comment by vikasrohit** [comment]
Thanks @maxceem for keeping #2310 in mind, otherwise it could have created a regression of a high priority issue.

**Comment by vikasrohit** [comment]
Working fine. Thanks.
