### ISSUE TITLE
[$50] Directly opened `/notifications` page is empty

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2372]
If we open the page with notifications directly by the URL it will show nothing.

Reproducible at DEV and PROD:
https://connect.topcoder.com/notifications
https://connect.topcoder-dev.com/notifications

![image](https://user-images.githubusercontent.com/146016/44141892-0db069f6-a0b1-11e8-87fc-f3c10c49d52d.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-345

**Comment by sumitdaga** [comment]
@gondzo 
what should be the base branch for this issue?
dev or cf11
