### ISSUE TITLE
Progress bar at the sidebar is not dynamically updating on changes in timeline/milestones

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2374]
Same issue https://github.com/appirio-tech/connect-app/issues/2189 is happening now when timelines/milestones are updated and it has to update progressbar, but progressbar is not updated on the sidebar.

@RishiRajSahu it's not a regression, just because the left sidebar uses `shouldComponentUpdate` method which prevents from updates. As now we added timelines/milestones which has to affect progress bar at left sidebar, but sidebar is not aware of it yet.

**Comment by maxceem** [comment]
Done via PR https://github.com/appirio-tech/connect-app/pull/2375

**Comment by vikasrohit** [comment]
Thanks @maxceem.

**Comment by vikasrohit** [comment]
Working fine. Thanks.
