### ISSUE TITLE
[50] Code should be preformatted in post cards.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2378]
### Expected behavior
When people paste code, it should be preformatted block (no line merging). The code should be readable as a code, and the box should scroll horizontally to accommodate long lines of text.

Ideally we can have a better code support (syntax highlight, and line numbers).
![image-1](https://user-images.githubusercontent.com/8484061/44174930-7baa5100-a099-11e8-8890-276b4d3033d2.png)

### Actual behavior
Code is wrapped to fit inside the box. Bad for UX/radability

### Current
![image-3](https://user-images.githubusercontent.com/8484061/44174909-6b927180-a099-11e8-9a79-1532cb45146c.png)

### Expected
![image-2](https://user-images.githubusercontent.com/8484061/44174915-6fbe8f00-a099-11e8-8562-e998ec89c326.png)

Aha! Link: https://topcoder.aha.io/requirements/TCCONNECT-351-3

**Comment by gondzo** [comment]
The scope here is to only update styling for the code block card, we'll add syntax highlighting in a separate ticket if needed

**Comment by MonicaMuranyi** [comment]
I would like to assign this issue to myself but I don't have the permissions to do so.

**Comment by MonicaMuranyi** [comment]
Do I need an account to https://secure.aha.io in order to work on this issue?

**Comment by gondzo** [comment]
No, there is no other info in the aha! ticket. Scope is just to update styling for the code block to keep the preformated text, and scroll the box horizontally if the width is larger than container
