### ISSUE TITLE
[$80] Filter by search term/ref code is not persistent on the search bar

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2391]
When manager filters the project list (search term, or click on ref code), and then opens a project, clicking on the back link doesn't persist the filter on the search bar, but the view is filtered. You have to manually enter a value to have the clear the view.

I've selected `TMUS` as ref code, and this is the view. Screenshot when I clicked back from a project.
![screen shot 2018-08-16 at 9 16 54 am](https://user-images.githubusercontent.com/8484061/44221157-77337600-a135-11e8-97a8-42525f994247.png)

### Expected
When the views are filtered, the filter should always be persisted/populated in the search bar.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-355

**Comment by rashmi73** [comment]
@gondzo working on it actively.

**Comment by sumitdaga** [comment]
@gondzo 
let me know if i can take this ?

**Comment by Gauravseta** [comment]
@gondzo even m waiting for same

**Comment by Gauravseta** [comment]
@gondzo please assign it to me or is it like whoever takes it when marked open?

**Comment by Gauravseta** [comment]
@sumitdaga how can u take while it is not marked open for pickup? @gondzo is it valid?

**Comment by gondzo** [comment]
@Gauravseta - it should have been marked as open for pickup long time ago, sumitdaga asked to work on it first so it should go to him first. 
self assigning issues to yourself when they aren't open for pickup won't be accepted anymore.

**Comment by Gauravseta** [comment]
@gondzo i guess u misunderstood. because issue was not taken by me ever. it was with rashmi73 , and sumit daga commented and even i commented. then i was waiting for it to be made open for pickup from rashmi73 and sumitdaga took it directly assigning to himself. hence i commented that how can he take it while it is not made open for pickup..because even i was waiting for this issue. even i could have  assigned to myself directly but i did not . i was waiting for it to  be open for pickup

**Comment by sumitdaga** [comment]
@gondzo  
i think the best solution here would be if the SearchBar from [here](https://github.com/appirio-tech/react-components/blob/master/components/SearchBar/SearchBar.jsx) can accept an initial term  
As of now it looks for its value from the query string which is not set when we go back from the project detail page  

are we allowed to make changes to appirio tect react components?

**Comment by sumitdaga** [comment]
@gondzo  
meanwhile i have raised a PR with another solution which i think has no other side effects
