### ISSUE TITLE
[$50] Website project icon is incorrect

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2395]
<img width="207" alt="screen shot 2018-08-20 at 11 10 48 am" src="https://user-images.githubusercontent.com/2417632/44322209-d52fc880-a469-11e8-8812-2a6d46bf91d4.png">

It should be the icon which we are showing on new project catalog

<img width="226" alt="screen shot 2018-08-20 at 11 15 22 am" src="https://user-images.githubusercontent.com/2417632/44322315-669f3a80-a46a-11e8-9e91-8543752188ab.png">

fyi @RishiRajSahu

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-365

**Comment by vikasrohit** [comment]
@amitpatra You need to get project template by fetching the `templateId` from project instead of looking for it at `details.products[0]`. We have pushed a latest [commit](https://github.com/appirio-tech/connect-app/commit/cb78bf9afe89d2914a0b8174f6ffa15396f808be) in dev branch which is going to be merged in the cf11 branch as well. You can take a look at [this](https://github.com/appirio-tech/connect-app/commit/cb78bf9afe89d2914a0b8174f6ffa15396f808be#diff-f2b41d03ed428dc9945ddfd8b21012eb) how we are fetching the project templates now with backward compatibility.

**Comment by amitpatra** [comment]
Hi, it appears that `item` doesn't have a `templateId` key. So how can we fetch the `templateId`?

**Comment by amitpatra** [comment]
Made a fresh pull request. Please review. Thank you.
