### ISSUE TITLE
Refactor the way we are storing project template id while creating project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2396]
This is a refactoring task to get rid of accessing `details.products[0]` to store the id of the template selected for a new project. It is also [storing](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/create/components/ProjectWizard.jsx#L253) wrong value (project template key instead of product id) in this field which is causing projects created via logged out flow to fail to load.

fyi @maxceem @RishiRajSahu

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-366

**Comment by maxceem** [comment]
@vikasrohit I'll take a look at changes and test it to make sure we are sage here.

**Comment by maxceem** [comment]
@vikasrohit I've checked everything that could be affected by the changes and everything works well for me.

There is just only one enhancement comment: https://github.com/appirio-tech/connect-app/pull/2397#pullrequestreview-148314378

And one small issue:

- Icons in the project list are not rendered properly for new projects

    ![icons](https://user-images.githubusercontent.com/146016/44441720-aac44380-a600-11e8-8f67-9533b10748f1.png)

     See lines https://github.com/appirio-tech/connect-app/blob/feature/refactoring-way-to-store-template-id/src/projects/list/components/Projects/ProjectsGridView.jsx#L54-L55

     Note, there is a related issue, but I thinkg it's not the same, as the next issue happenes before this change, but probably both of these issues have the same solution https://github.com/appirio-tech/connect-app/issues/2395

Let me know if you'd like me to fix it or you want to take care about it youreself.

**Comment by vikasrohit** [comment]
Closing the issue as changes are deployed to the dev env and seems to work fine.
