### ISSUE TITLE
'New Project button text issue in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#240]
Description
-----------------------------------------------------------------
'New Project button text issue in IE11

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on '+ New Project'
- Click (x) button to close the pop up
- Check the '+ New Project' button

Expected Result(s)
-----------------------------------------------------------------
- Must display in WHITE

Actual Result
-----------------------------------------------------------------
- 'New Project button text issue in IE11

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2016-09-29_4-47-212](https://cloud.githubusercontent.com/assets/4592712/18936374/68a96c32-8604-11e6-917a-6b9050d2e248.png)

**Comment by vic-appirio** [comment]
Invalid. Closing
![screen shot 2016-10-10 at 2 12 18 pm](https://cloud.githubusercontent.com/assets/8484061/19251309/9289e610-8ef3-11e6-8bfd-100e00141308.png)
