### ISSUE TITLE
Timeline content updates

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2400]
Let's work on updating the timeline a bit further. We talked about

### Implemented:
![screen shot 2018-08-20 at 3 36 25 pm](https://user-images.githubusercontent.com/8484061/44370370-d2939a00-a48e-11e8-8a82-608f1def60bc.png)

### Expected:
![screen shot 2018-08-20 at 3 37 21 pm](https://user-images.githubusercontent.com/8484061/44370400-f3f48600-a48e-11e8-89c0-cee6bcc5f8e4.png)

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Remove the welcome paragraph with title (Welcome to…phase)

- [ ] Add all the milestone state messages to the templates, so when the customer goes to the timeline for the first time they would see helpful text. Follow the content templates from https://docs.google.com/spreadsheets/d/1NTpMtOfABCi1dPrBEEFgc4iGs2HEVKSZuhSrwYzMCJE/edit?usp=sharing
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-374

**Comment by vikasrohit** [comment]
> Add all the milestone state messages to the templates

They do already @vic-topcoder. That is where those are copied from, to the actual milestones as well. Its only by design, we were not showing the text until phase i.e. timeline is active. Let us know if we are sure to show the planned text even for non active phases.

**Comment by vic-topcoder** [comment]
Let's show the planned state during draft stage please - it makes no sense to hide the text as the managers would edit the timeline and adjust it while in draft mode/inactive.
@acshields FYI

**Comment by vikasrohit** [comment]
Okay.

@gondzo there are two things to be done in the scope of this issue:

- [ ] Remove the welcome paragraph with title (Welcome to…phase)
- [ ] In draft state of phase, show text of the milestones and enable the edit options for milestones as well.

Please feel free to create separate issues if you think it would be better.

**Comment by RishiRajSahu** [comment]
Done with https://github.com/appirio-tech/connect-app/commit/0f7b0340fab7679b7ddba6a0c1fef637ad850186.
