### ISSUE TITLE
Add notification visual cues to project plan cards

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2401]
### Expected behavior
It is not immediately obvious if there are new items (post, timeline change) for the user since last time they visited the system. This is why we designed a visual cues (red dots) to point their attention towards the items that have changed.

- Collapsed card - the red dot is at displayed at the right top corner to indicate this card has new content:
![screen shot 2018-08-20 at 3 42 57 pm](https://user-images.githubusercontent.com/8484061/44370592-bd6b3b00-a48f-11e8-9e33-442d229a6f18.png)

- Expanded card - the dot is used to highlight any tab that has new content (Timeline is first, so if the dot is there, it should auto disappear).
![screen shot 2018-08-20 at 3 44 04 pm](https://user-images.githubusercontent.com/8484061/44370640-ed1a4300-a48f-11e8-9ba9-d1cb838c861d.png)

This should be triggered by our notifications (event) platform and also available as notifications in the list.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-375

**Comment by maxceem** [comment]
@vikasrohit I've checked again, any notifications don't come on DEV for now.

**Comment by vikasrohit** [comment]
@maxceem I fixed the notifications in dev. Please let me know if you are still facing the same issue.

**Comment by maxceem** [comment]
Done for posts.

**Comment by maxceem** [comment]
Reverted commit in a common branch and created a separate branch for this issue https://github.com/appirio-tech/connect-app/tree/issue-2401

**Comment by vikasrohit** [comment]
@maxceem Could you please create a separate issue for handling the cues for timelines tab? We would close this issue for now and will take care of the timelines tab in next release.

**Comment by maxceem** [comment]
@vikasrohit Created a new issue https://github.com/appirio-tech/connect-app/issues/2455

**Comment by vikasrohit** [comment]
Thanks @maxceem. Closing this one as it seems to work fine with only catch that the cue appears bit late after the page load, but I think we can handle that separately and when reported by end users if they found that not fruitful.
