### ISSUE TITLE
Clearing 'Description'; still display the "Project Name" cleared previously

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#241]
## Description

Clearing 'Description'; still display the "Project Name" cleared previously
## Steps to Reproduce
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click '+ New Projects"
- Enter all the required data
- Clear the 'Project Name' from (x) clear button
- Now delete the 'Description' from keyboard
- Check the 'Project Name'
## Expected Result(s)
- Must not display the cleared "Project Name" 
## Actual Result
- Clearing 'Description'; still display the "Project Name" cleared previously
## Environment
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

**Comment by sdgun** [comment]
http://screencast.com/t/G3WWcbMtou3

**Comment by fnisen** [comment]
Fixed as part of https://github.com/appirio-tech/connect-app/issues/238
