### ISSUE TITLE
Remove specification milestone duration (timeline starts)

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2412]
Remove specification milestone duration (timeline starts). When we have a timeline start most of the time we don't want to set a timeline for the customer to complete a specification. The goal is to flip the switch once the specification is ready and the copilot can start the challenges on the platform. We already made the specification document optional, so let's remove further constraints from the system and make sure that the first checkpoint is the agreement on specification, which would record the start of work and transition into the next milestone in the timeline.

from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-378

**Comment by vic-topcoder** [comment]
I'll defer the decision to @acshields; I'm fine if the specification milestone has a duration.

**Comment by acshields** [comment]
I am a fan of keeping things simple - Let's keep the specification milestone with a duration. If there is a duration that is used today, then let's keep that in place.  If not, make the default duration 2 days.

**Comment by vikasrohit** [comment]
Yes, it has duration of 2 days and that is completely configurable via data entry without any code change.

**Comment by vikasrohit** [comment]
Closing
