### ISSUE TITLE
Remove delivery milestone duration (timeline ends)

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2413]
Remove delivery milestone duration (timeline ends). Once the work is done we do a deliver as a single point in time, and the customer has no further option to extend/expand request for fixes. The delivery literally marks the end of the phase and provides a link (or links) to the customer to download their artifacts/deliverables.

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-379

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields I didn't understand this requirement.  Our delivery milestone is dynamic i.e. it renders itself immediately after `final-designs`, in a design phase, with option to either accept the designs or request for final fixes. Only after user chose one of these option, we know where to move in the timeline. If user choses to request fixes, we move backward and enable the `final-fix` milestone instead and disable the delivery milestone and if user choses to accept the designs, we keep the delivery milestone active, but manager has to add the links of the final deliverables so we keep this milestone open till manager adds the links. So, in nutshell, we need a valid duration for this milestone to be rendered correctly. Right now we have only 1 day (which is the minimum duration in our system for a milestone) as default duration for all types of timelines and I am not seeing any side effect of it.

**Comment by vic-topcoder** [comment]
The delivery milestone should not have a duration as it will expand the phase duration? Or we have a standard 1-3 days for code delivery? I'm not sure if delivery blocks any of the phases that follow.

Deferring to @acshields

**Comment by acshields** [comment]
Hi @vikasrohit - I think your explanation above makes sense.  Let's leave the delivery milestone as-is with a default duration of 1 day.

**Comment by vikasrohit** [comment]
Thanks @acshields . Closing the issue.
