### ISSUE TITLE
Remove messages for adding a phase to a project plan

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2415]
Remove messages for adding a phase to a project plan. This is done by managers and makes no sense as I can see what I've just added. The customer can't see a phase when it is in draft state (as added) and it makes no sense to dispatch this message.

![screen shot 2018-08-06 at 2 51 25 pm](https://user-images.githubusercontent.com/8484061/43744296-44883d98-998e-11e8-8895-9bc5e7bb623b.png)

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-381

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields I think it is always good give an acknowledge of what user has done especially when user is not able to immediately locate the changes made by his last action e.g. in our case if the phase list to too long (as it is in the attached screenshot), it is very difficult for me to see if my phase is successfully added or not. And anyway, we are always showing such messages on almost every interaction e.g. we show that project is updated when spec is updated. It is just an  immediate feedback of operation being successful, not a notification which persist for the creating user.
So, IMO, this requirement is conflicting.

**Comment by vic-topcoder** [comment]
The visual message when a new phase was added is useless as it doesn't provide additional value; it detracts the user.

**Comment by acshields** [comment]
I have heard feedback from Kyle that he sometimes has difficulty identifying whether a new phase has been successfully added. @vic-topcoder - I understand your point about the message, but I am wondering if there is another way to show a new phase has been added (i.e. shaded box, different text color, etc.) that would indicate a new phase has been added & is unedited? What are your thoughts on that from a user experience?   If something like this isn't possible, then I say let's keep the alert message for the time being and monitor.

**Comment by vic-topcoder** [comment]
The interface lacks transitions, which doesn't help to identify when a new item has been added or removed. At the current state the only thing we can do is to create an outline. Ideally I would love to start polishing such experiences and have the time to implement them correctly, with the user being able to see the change from initial state to complete state.

The message doesn't actually identify which is the new phase added, but confirms a new phase added, so it is distracting from the core problem - being the change.

I would expect a new phase to be added to the bottom of the project plan, and the transition to be animated. Before we can do that, we can do a color transition to identify a newly added phase (fade from blue to gray)

![screen shot 2018-08-28 at 9 37 05 am](https://user-images.githubusercontent.com/8484061/44737252-4b55b000-aaa6-11e8-87f7-cdc6e9cb9d9d.png)
![screen shot 2018-08-28 at 9 38 51 am](https://user-images.githubusercontent.com/8484061/44737227-40028480-aaa6-11e8-9944-e3353610e19a.png)
![screen shot 2018-08-28 at 9 39 14 am](https://user-images.githubusercontent.com/8484061/44737230-4133b180-aaa6-11e8-9dab-e33d66f26c0e.png)

**Comment by vikasrohit** [comment]
@acshields @vic-topcoder First of all I am still not convinced of getting rid of only phase added alert message because it does not make sense to me to introduce alert system in first place and then not using it considering it distracting the user. We introduce the alert system in https://github.com/appirio-tech/connect-app/issues/52 and updated its style from toaster to bottom left in 2.4.3 release. So, I am not sure where else that notification system would be used if we don't use it in such cases.

Anyway, if we are still positive about this we can try to implement the color fading as suggested to indicate the newly added phase. We are also tracking adding transitions here https://github.com/appirio-tech/connect-app/issues/2195, so if we need that please let us know the transition designs.


> I have heard feedback from Kyle that he sometimes has difficulty identifying whether a new phase has been successfully added

@acshields  we have an issue #2427  logged which we are not yet able to reproduce but it can be a reason why user might have difficulty in identifying the new phase. 

> I would expect a new phase to be added to the bottom of the project plan

@vic-topcoder this has some edge cases when user has changed the dates (directly or indirectly via milestones) of phase in a way which changes the order of phases and then tries to add a new phase, in this case the new phase might get added either in between or would move upwards after page refresh. It is related to #2427

**Comment by acshields** [comment]
@vikasrohit - For now, let us keep the phase added alert in place.

**Comment by vikasrohit** [comment]
Okay, Closing the issue for now. Please feel free to reopen or create new one later when required.
