### ISSUE TITLE
Remove the "submit for review" button from project scope

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2417]
Remove the "submit for review" button as our project scope has the exact same data from project creation. This makes no sense at the moment. We're going towards a state where all the project scope data would be submitted at one step and once project is completed it would be ready for review (generate project plan)

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-383

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields Agree that right now we don't have any thing different in project after project creation and that is because we haven't identified the scope and product questions yet via #2161 and #2162. If we have that separation, we would have some questions (in fact we do have some questions in phase specs but that is hidden right now for customers) which would be visible only after project creation. So, IMO, doing the changes for this issue is temporary and we have to revert them as soon as we have a single question which we don't ask on project creation.
I would like to proceed for this work only and only if we are 100% sure that we never ever have a situation where there are extra set of questions which we don't ask on creation but ask in project scope or any where else after creation. The reason behind that is that it requires changing the default status of project after creation to be `in_review` which actually breaks a lot of thing e.g. the workflow which sends slack notifications, with this change it would start sending slack notification for every project coming into the system even if they are spam or test projects.

**Comment by vic-topcoder** [comment]
@acshields - "IBM Chatbot" and "Azure Marketplace" projects - would they need a "submit for review" process? I'm in favor of merging project creation and scope capture.

**Comment by acshields** [comment]
@vic-topcoder - I am a fan of that as well.  However, in order to avoid rework on this issue, let's put it on-hold.  I feel like the question over scope vs. product questions will get discussed in the product summit we are having in two weeks.

**Comment by vic-topcoder** [comment]
I'm cool with that!

**Comment by vikasrohit** [comment]
Moving it to backlog

**Comment by vic-topcoder** [comment]
Moved to productboard
