### ISSUE TITLE
[60$] Hide 0$ as cost/estimate

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2418]
Hide $0 as cost/estimate from the customer. Our customers should only see data that is relevant.

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-384

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields This portion (Price/cost/estimate) of the phase card is still not clear. We just hardcoded few things there. We need a better logic there to show the price. In the original designs in marvel, it used to show 2 different types of pricing statuses `Quoted`, `Fully Paid` and `$xxx remaining`. I think right now it shows `Quoted` in every situation except when the phase is active and there is some budget and spent amount set.

So, it would be better if we can reiterate on the logic for the section.

**Comment by vic-topcoder** [comment]
The change request is to add a case where to render the price to the end user. Similar to how we hide the phase while it is in `draft` mode, we should hide the price if the dollar value is == 0; this way the customer doesn't see a 0 cost (free!). Does this make sense?

**Comment by vikasrohit** [comment]
Yes, that do. But the question is that do we have any logic in mind for showing the text (`Quoted`, `Fully Paid`) for the price/cost/estimate? I am assuming that as we don't have any payment logic to the phases, we can safely assume that it would always be `Quoted` until the first cent is spent.

**Comment by vic-topcoder** [comment]
For the time being we do not have any info from SFDC if/how much is paid on a project. We do have the "amount paid" in the phase manually managed, so I think we're good for the moment
