### ISSUE TITLE
[$20] Do not display project status bar twice on the Project Scope tab

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2419]
Do not display project status bar twice on the Project Scope tab. This makes no sense (Hide one of the two progress bars). @acshields I'm leaving you to pick which one of the progress bars should stay. I would probably hide the big progress bar as the jump from the sidebar to the main space would be too much).

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-385

**Comment by vikasrohit** [comment]
@acshields let us know which one we want to keep or hide.

**Comment by acshields** [comment]
Per our conversation this morning, hide the larger progress bar and display the progress bar that is in the sidebar.

**Comment by maxceem** [comment]
Just to confirm. If I understood it correctly it's about removing the progress bar from **Project Plan** tab, not **Project Scope**.

![progress](https://user-images.githubusercontent.com/146016/45009251-a143ce00-b039-11e8-97f0-69c0f3b1e89a.png)

**Comment by vikasrohit** [comment]
@maxceem I don't think we show progress bar on `Scope` tab. We are only showing this extra progress bar on `Plan` tab, so we just need to get rid of that.

**Comment by jomadoye** [comment]
Please assign this to me, I am working on this

**Comment by jomadoye** [comment]
@maxceem I am done fixing this issue, but I do not have access to push my branch.please give me access 
<img width="728" alt="screen shot 2018-09-09 at 11 30 41 pm" src="https://user-images.githubusercontent.com/26272732/45275041-6d790600-b488-11e8-9ba3-1be14902bd2a.png">

**Comment by maxceem** [comment]
@jomadoye Please, don't push directly to this repository. Instead fork this repo, do changes in your fork and after create a PR to this repo. You may refer to this doc for help https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by maxceem** [comment]
@jomadoye Please, resolve lint errors before the PR can be merged.
