### ISSUE TITLE
Hide project status from customer

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2420]
Hide project status from customer. We build the new progress bar at the moment and it would be sufficient for communication. The project status should be visible for managers and copilots. Also - let's make sure we tackle the logic of switching project status based on the dependent phase status.

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-386

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields I didn't get this requirement. Does it meant to get rid of the project status from the left panel in project details and status in project card in list/grid view? If yes, I am not sure how that would help customers or any user. IMO, status is critical thing to know about no matter who the user is.

**Comment by vic-topcoder** [comment]
Deferring to @acshields:

My logic is that there are way too many status changes currently and the customer doesn't need to focus on PROJECT status, rather see when the phases are ready to be worked on, and monitor their progress. This, combined with the progress bar on the right side makes it easier for a customer to understand what's going on.

![image](https://user-images.githubusercontent.com/8484061/44501659-0c0d0680-a643-11e8-9ba3-43b01608330e.png)

vs.

![image](https://user-images.githubusercontent.com/8484061/44501671-14fdd800-a643-11e8-940f-9d27aa7e5970.png)

**Comment by acshields** [comment]
Let's keep this as-is for the time being - Per our conversation this morning, it seems like we need to have some additional conversations to uncover the value of this field.

**Comment by vic-topcoder** [comment]
@acshields test one

**Comment by vikasrohit** [comment]
Moving to backlog for time being

**Comment by vic-topcoder** [comment]
Moved to productboard
