### ISSUE TITLE
Rename `Channels` and `Posts` to `Discussions` 

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2421]
Rename `Channels` and `Posts` to `Discussions` to keep things consistent.
![screen shot 2018-08-06 at 3 45 06 pm](https://user-images.githubusercontent.com/8484061/43744660-d77037d6-998f-11e8-8c07-15fddd4f5231.png)

Continued from #2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-387

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields we already have the label `Discussions` for a tab which is visible to only very very very old projects and I have seen active projects (e.g. https://connect.topcoder.com/projects/1288) with that tab enabled. If you think this change does  not cause confusions to those project members, we are good with the requirements here.

**Comment by vic-topcoder** [comment]
This is in a sense update of the feature we had :) Those projects ideally would be upgraded to the new system.

**Comment by vikasrohit** [comment]
Agreed @vic-topcoder. However, as per my understanding after reading the mangers (for those legacy projects) views, these projects are not going away very soon. Also, `Discussions` tab is a legacy thing that is there, which we have hidden for all new projects but they would remain there for older ones to keep there records. So, if we are okay with renaming `Channels` to `Discussions` even for such projects, we are good here.

**Comment by RishiRajSahu** [comment]
fixed with https://github.com/appirio-tech/connect-app/commit/81103631b04dd3c6cfc0d812ecb1e56b5713421c
