### ISSUE TITLE
[$80] Maintain the phase card height when updating milestone/timeline

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2422]
### Expected behavior
It should not change the height of the card when showing loading icon while doing updates to milestones/timelines

### Actual behavior
It reduces the height when loading icon comes into picture and then increases the height back to original when it goes away.

### Steps to reproduce the problem
- Update a milestone
- Observe the loading icon and phase card

### Screenshot/screencast
https://screencast.com/t/tZV3Qt6g (updating milestone)

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot or Manager
- Account used: N/A

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-388

**Comment by vikasrohit** [comment]
@gondzo  fyi

**Comment by gets0ul** [comment]
https://www.screencast.com/t/Oqs9IayL  
  
Please check if this is correct as expected. Thanks

**Comment by vikasrohit** [comment]
Thanks @gets0ul for demo video. It seems their is still some jump when loading icon is rendered. Please see the second time you updated the milestone in your demo, it shifted the screen up by some pixels.

Also, can you please add demo with marking a milestone complete? That is the most frequent use case we want to take care.

**Comment by gets0ul** [comment]
Thanks for the feedback @vikasrohit. 
I'll add the demo on milestone marking.

**Comment by gets0ul** [comment]
Marking milestone as completed:  
https://www.screencast.com/t/Rm4Rbggn7W  
https://www.screencast.com/t/1eQum8So  

Please check. Thanks.

**Comment by vikasrohit** [comment]
Thanks @gets0ul for the updated video. It seems good to me except that there is still a bit of scroll after loading icon goes away. Please notice the scroll on the right side, ideally it should not jump at all. I think we applied a fix in past to scroll to the current phase card after update, so I think that fix might be causing this. Can you please check and remove that logic and see if that stops this jumping?

**Comment by gets0ul** [comment]
Without scrolling. PR is updated.  

https://www.screencast.com/t/zwlLZIt43P

**Comment by gondzo** [comment]
@gets0ul prize updated as the effort required was somewhat bigger than I expected
