### ISSUE TITLE
Merge two milestones implementations:`checkpoint-review` and `final-designs` into one

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2429]
From here https://github.com/appirio-tech/connect-app/issues/2361#issuecomment-413091916

> we also need to remove the additional new milestones created for both checkpoint and final-designs which we created to support the data pushed from add-links , as its hard to maintain almost similar component. we can use logic in actual checkpoint-review and final designs milestones to render data for both old and new timelines, so that maintenance is easy for the components.

Agree on this, already few changes had to dpulicate into two components.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-393

**Comment by vikasrohit** [comment]
@maxceem Its not about merging `checkpoint-review` and `final-designs` into one, I they have different purposes and behaviour. Though, we can use same component for them as well by using hoc(s) for rendering the design selection portion in the milestone. I think while this would also be a good refactoring, however, the point we raised in https://github.com/appirio-tech/connect-app/issues/2361#issuecomment-413091916 is to use single component for read only and non read only modes e.g. merging `MilestoneTypeFinalDesignsSelectionOnly` and `MilestoneTypeFinalDesigns` into one i.e. using `MilestoneTypeFinalDesigns` even for SelectionOnly mode. Similarly for `MilestoneTypeCheckpointReviewOnly` and `MilestoneTypeCheckpointReview`.

**Comment by vikasrohit** [comment]
@maxceem Apologies, I think I misread your description. Saw the changes after posting the comment 😬, seems like you have done exactly what I described above. Thanks.

**Comment by maxceem** [comment]
@vikasrohit yeah, I just was not clear in this issue description...

**Comment by maxceem** [comment]
@RishiRajSahu this is already in `dev` branch and can be closed.

**Comment by RishiRajSahu** [comment]
@maxceem thanks for bringing it to attention.
