### ISSUE TITLE
After left the project , project list is not updated without refresh the page 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#243]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to Specification
5. update specification
6. Submit for review
7, back to project listing 
8. Left the project
9. open left project from the list

Expected Result: left project should not be displayed in the list
Actual Result: showing in the list & on opening throwing 404 error
 

Environment: windows 7, chrome latest

![image](https://cloud.githubusercontent.com/assets/16131461/18930686/b630fb64-85e6-11e6-9d80-ca9c1e2831cb.png)

**Comment by mahestro** [comment]
Valid. Could be reproduced by chance.
