### ISSUE TITLE
Hot reloading often doesn't work

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2435]
So far hot reloading often fails to reload only updated components and usually updates the whole app. Which increases development time especially when doing a lot of small changes like fixing SCSS styles.

In particular, if there are some components which are controlled by the state, their state is lost after hot reloading. So we have to repeat some clicks just to come back to the previous place.

There are many warning in console like:
```
React Hot Loader: this component is not accepted by Hot Loader.
```

Here are some test measurements:
- Updating component controlled by state ~18 sec, demo https://monosnap.com/file/Xaf7pRce0g73waE6blReKclSXmWXuN
- Updating component controlled by redux ~13 sec, demo https://monosnap.com/file/gfHUXW0CmRd9GJ5NBScDaD7bvZcJVU
- Updating SCSS style ~12 sec, demo https://monosnap.com/file/MWeU0gjxUvQ9cbDEWvzj4rFfX6Ltye

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-396

**Comment by maxceem** [comment]
I've fixed in the branch https://github.com/appirio-tech/connect-app/tree/feature/improve-hot-realoding

Measurements after the fix:
- Updating component controlled by state ~6 sec, demo https://monosnap.com/file/xIHoriwiaeoOk6xufVLI2zPLnaHVpx
- Updating component controlled by redux ~6 sec, demo https://monosnap.com/file/bYHHxmz6CvRz2Gi4GYFX49FcDkoGrv
- Updating SCSS style ~6 sec, demo https://monosnap.com/file/MWeU0gjxUvQ9cbDEWvzj4rFfX6Ltye

Additionally, source maps are currently disabled, which makes it not that comfortable to debug code some time. So I've enabled `cheap-module-eval-source-map` (see https://webpack.js.org/configuration/devtool/).
Looks like it doesn't affect time during hot reloading:
- Updating component controlled by redux ~6 sec, demo https://monosnap.com/file/20yDr5W9BvSkI0lOieZPAX6OEM5uTN

**Comment by maxceem** [comment]
I've merged the branch https://github.com/appirio-tech/connect-app/tree/feature/improve-hot-realoding to my current working branch https://github.com/appirio-tech/connect-app/tree/feature/v2-4-5-part2

As it speeds up developing and also to verify that there are no side effects in this update during working on other issues.

**Comment by vikasrohit** [comment]
Okay, No issues @maxceem. Btw good capture again.

Btw when we are at developer issues, we also need to fix the source map to be available on dev and prod builds both. It makes life easy when we are debugging things on production. @maxceem do you think we could have any potential performance issue if we enable source map on production?

**Comment by maxceem** [comment]
@vikasrohit 

Regarding source maps on production, I'll research a little to be sure. So far only one performance drawback I can think about is whether source maps are downloaded by browser by default or no. Other than that I don't think there could be any performance issues.

**Comment by vikasrohit** [comment]
Okay, Thanks @maxceem. These changes are really helpful and it is good to document issue and the fixes via videos as well. Thanks again.

**Comment by maxceem** [comment]
@RishiRajSahu this is already in dev branch and can be closed.

Created a follow up issue https://github.com/appirio-tech/connect-app/issues/2534
