### ISSUE TITLE
Color change for date of the completed milestone

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2446]
When a milestone is in any state but completed, the date on the left should be colored with $tc-gray-30 to illustrate a planned date state. Once the milestone is completed, the date would be final (day of competition) and should use $tc-black as color.

Continued from #2333

**Comment by RishiRajSahu** [comment]
Done with https://github.com/appirio-tech/connect-app/commit/781f0877599ae22a86837be10515de15f86b300c
