### ISSUE TITLE
Phase form is not showing updated values

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2448]
### Expected behavior
It should maintain the update values in the form after the update

### Actual behavior
It is showing old value after successful update.

### Steps to reproduce the problem
- Update any active phase's Spent money and/or Price fields
- Click on the Edit icon again
- Notice that value in form is the one before the update, please try closing the form again and reopen it again if its showing correct value.

### Screenshot/screencast
https://screencast.com/t/IqKAAtVXus0

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot or Manager
- Account used:  N/A

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-400

**Comment by maxceem** [comment]
Can reproduce it, fixing it...

**Comment by maxceem** [comment]
Fixed by unmounting `EditStageForm` instead of hiding by CSS which updates form by values from the store properly. In case we see similar issues in other places, we can also consider fixing `TCFormFields.TextInput` which feels like doesn't properly support defining default values by props.

**Comment by vikasrohit** [comment]
Okay. @maxceem Can you please create issue in react-components repo for fixing the TextInput?

**Comment by maxceem** [comment]
@vikasrohit Done https://github.com/appirio-tech/react-components/issues/294. Though we can probably leave it until we come across with this issue in some other place. As TCFormFields.TextInput` is used in many places, so updating its behavior may bring some other issues if some component relies on the current behavior.

**Comment by vikasrohit** [comment]
Thanks. Yes, makes sense.

**Comment by RishiRajSahu** [comment]
working fine on dev.
