### ISSUE TITLE
Can't scroll down the page when user click 'Add' from Project Team

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#245]
## Description

Can't scroll down the page when user click 'Add' from Project Team
## Expected Result(s)
- Must able to scroll the page down
## Actual Result
- Can't scroll down the page when user click 'Add' from Project Team
- If the user scroll up then he/she able to scroll down
## Steps to Reproduce
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name
- In the Project Team
- Click ADD
- Scroll down the page
## Environment
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by sdgun** [comment]
![2016-09-29_1-55-54](https://cloud.githubusercontent.com/assets/4592712/18936405/9f678e16-8604-11e6-892a-fbca80ea9803.png)

**Comment by sdgun** [comment]
http://screencast.com/t/Qbvro9ZrF1ao

**Comment by vikasrohit** [comment]
Related issue #465
