### ISSUE TITLE
Phase progress is updated when `spentBudget` or `budget` fields are updated

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2450]
Ideally it should not update the phase/project progress when updating the other fields. It is happening for a project which has at least active phase and is not update on the day of testing. When updating `spentBudget` or `budget` fields (or may any other allowed field update in the phase edit form), it updates the progress of the phase. Most of the time it actually reduced the progress.

fyi @RishiRajSahu

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-403

**Comment by RishiRajSahu** [comment]
@vikasrohit I think that was due to duration and other fields which should be disabled for timeline enabled phase were enabled somehow due to dependent repo changes not deployed on dev. I tried it on dev and its working fine. Also tested for older project which doesn't have timeline.

**Comment by RishiRajSahu** [comment]
@vikasrohit can we close this ?

**Comment by vikasrohit** [comment]
For now we can close it. Possibly it is fixed with #2449 and https://github.com/appirio-tech/connect-app/commit/70c9e85cb83017844d9de46cc83252bf24128938

**Comment by RishiRajSahu** [comment]
@vikasrohit yeah verified it on dev with few projects. Working fine.
