### ISSUE TITLE
Cannot load uploaded file at the DEV env

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2451]
This issue on the DEV environment.

If I upload file to some project specification https://connect.topcoder-dev.com/projects/7247/attachments/1238
and after try to load it, I get error
```xml
<Error>
<script type="text/javascript" charset="utf-8" id="zm-extension"/>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
projects/7247/projects/ADfmutB3QaL4ODkvO5xw_test2.txt
</Key>
<RequestId>FCA3A1BFD3001A9E</RequestId>
<HostId>
QrhbQhl9FqUxAAcphPUzwzUUaWrWzZMaKhk0bmcAv3ODcpzge6FTgtpeT+tqu9qCd03L5bw2T6I=
</HostId>
</Error>
```

This issue happens to me on for local deployment and for https://connect.topcoder-dev.com.

Is it a know issue and uploading files doesn't work on DEV? Or this can fixed for DEV?

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-404

**Comment by gondzo** [comment]
In dev files aren't actually uploaded to aws, only a link is generated. Do we need to enable uploads to test something?

**Comment by maxceem** [comment]
I wanted to test one small thing but managed to verify it by code. So currently there is no need for testing files uploading.

**Comment by vikasrohit** [comment]
Yes, unless it is not verifiable via code, we can keep it disabled. However, I would like to get this behaviour controlled via an env variable so that we can deploy the build as per requirements.

**Comment by maxceem** [comment]
This issue is duplicate of https://github.com/appirio-tech/connect-app/issues/2156.

**Comment by RishiRajSahu** [comment]
yep, closing it.
