### ISSUE TITLE
[$50] Edit phase Form for smaller screen sizes

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2454]
Currently, Edit phase form is not perfectly displayed on the desktop having fields not properly aligned in some situations, like status on the screen below:

![image](https://user-images.githubusercontent.com/146016/44769147-3b1cfe00-ab96-11e8-90fc-78c3570e387f.png)

And when we shrink the window the form doesn't adapt properly

Screen width 768px:

![image](https://user-images.githubusercontent.com/146016/44769198-669fe880-ab96-11e8-93be-07465400763d.png)

Min screen width 320px (mobile):

![image](https://user-images.githubusercontent.com/146016/44769215-7f100300-ab96-11e8-8f3c-8833d580f167.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-407

**Comment by RishiRajSahu** [comment]
@vic-topcoder please provide inputs on this.

**Comment by vic-topcoder** [comment]
We should switch to the minimal layout mode if possible: label on top of fields so we can use the maximum space available, example:
![screen shot 2018-09-27 at 7 41 56 am](https://user-images.githubusercontent.com/8484061/46153903-e3bb8d80-c228-11e8-9c5c-edb47545f075.png)

**Comment by maxceem** [comment]
To sum up:

1. For > 1024px:

    ![align-102](https://user-images.githubusercontent.com/146016/46388491-0523ea00-c6ff-11e8-9588-3c5cc4e77a7f.png)

    - align labels and fields without using magic numbers, width for "columns" can be defined through

2.  < 1024:

     ![](https://user-images.githubusercontent.com/8484061/46153903-e3bb8d80-c228-11e8-9c5c-edb47545f075.png)

    - switch to minimal layout where labels and values are places on new lines

**Comment by RishiRajSahu** [comment]
@maxceem yeah looks good to do that way. thanks @vic-topcoder  !

**Comment by iversonLv** [comment]
@maxceem  It’s done and ready for review


Thanks.

**Comment by maxceem** [comment]
@iversonLv I've made a review, please have a look https://github.com/appirio-tech/connect-app/pull/2600#pullrequestreview-164482660
Thanks.

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
