### ISSUE TITLE
Add notification visual cues to phase timeline tab

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2455]
This is the second part of this issue https://github.com/appirio-tech/connect-app/issues/2401

Add the red dot to highlight that `Timeline` has some updates.
When we open such tab we have to mark the related notifications as read and hide the red dot as we already saw the updated content.

![image](https://user-images.githubusercontent.com/146016/44770657-4c1c3e00-ab9b-11e8-8c2a-315b6ad67685.png)

This issue requires support of additional event types which is tracked by the next issue https://github.com/appirio-tech/connect-app/issues/2426

continued from https://github.com/appirio-tech/connect-app/issues/2301

**Update:** Restricting the scope of the issue to timeline tab only. We would handle the specification tab separately later as that tab might be revamped soon or later.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-408

**Comment by maxceem** [comment]
@RishiRajSahu 
I've tried to run connect-app using branch https://github.com/appirio-tech/connect-app/tree/feature/plan-timeline-events-settings where new notifications are implemented.

But new notifications never come when I activate phases or complete milestones by manager user and check for notifications by customer user. I used this project for testing http://local.topcoder-dev.com:3000/projects/7279

Is there any chance these events weren't added to Kafka, or currently some version of `tc-project-service` deployed which doesn't support these events yet?

**Comment by RishiRajSahu** [comment]
@maxceem yes there could be two possibilities - 
- These events weren't added to kakfa
- Notifications service is not able to listen to kafka

I have to check, will let you know soon.

**Comment by vikasrohit** [comment]
@maxceem I am able to see the phase completed/activation and milestone completed/activation web notifications for my project when I perform the action as copilot and check the notifications as customer.

**Comment by maxceem** [comment]
To sum up.

The whole list of notification types when we have to add a cue to `Timelines` tab is:
- `connect.action.timeline.adjusted`
- `connect.action.timeline.milestone.transition.active`
- `connect.action.timeline.milestone.transition.completed`
- `connect.action.timeline.milestone.waiting.customer`

All of these notififications with mentioned types we will mark as read when we open `Timelines` tab.

So far it can be implemented similar way as it done now for `Discussions` tab.

**Comment by RishiRajSahu** [comment]
@maxceem yeah the list looks good, however other than above events, i found few milestones events as well - 
`connect.action.timeline.milestone.added` NOT NEEDED
`connect.action.timeline.milestone.removed` NOT NEEDED
`connect.action.timeline.milestone.updated` NEEDED

out of which we can use `connect.action.timeline.milestone.updated` for showing timeline cue, as for remaining two we haven't yet provided any functionality yet on UI.

**Comment by maxceem** [comment]
@RishiRajSahu as far as I see neither of these events are now handled by `tc-notifications` https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/constants.js or `connect-app` https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js

`connect.action.timeline.milestone.added`
`connect.action.timeline.milestone.removed`
`connect.action.timeline.milestone.updated`

So I guess before handling this issue we have to add them there. Correct?

**Comment by vikasrohit** [comment]
Yes, @maxceem we need to listen events and store in database before they can reach to connect app. And that is the tricky part, because we don't want to show these notifications in connect app.

**Comment by vikasrohit** [comment]
@maxceem can we add a new parameter in event config in connect app, which would say if the event has to be rendered in notification panel or not. We can mark that flag as false when we want to use the particular event for some other purpose in the app.
Btw, we can use `connect.action.timeline.adjusted` for any timeline changes for now and we are listening for this event in connect app as well.
For Specification tab, we need to check for `connect.action.project.product.update.spec` to show visual cue.

**Comment by maxceem** [comment]
> can we add a new parameter in event config in connect app, which would say if the event has to be rendered in notification panel or not.

@vikasrohit 
Yes, just let me vefiry I got you right:
- we add some flag inside `connect-app` notification configuration https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js
   which if present will let us keep a notification in the Redux store. But notification wouldn't be shown on notifications lists.
- I think we can name like `hidden`, example configuration would look like:
   ```
    {
       eventType: 'notifications.connect.project.submittedForReview',
       hidden: true
    }
   ```

> Btw, we can use connect.action.timeline.adjusted for any timeline changes for now and we are listening for this event in connect app as well.

Yes, but it's not handled by `tc-notifications` so far, see https://github.com/topcoder-platform/tc-notifications/issues/72

**Comment by vikasrohit** [comment]
> Yes, but it's not handled by tc-notifications so far, see topcoder-platform/tc-notifications#72

Got it. I think reason that it is not handled in tc-notifications right now is that now we are consuming this event in [project service](https://github.com/topcoder-platform/tc-project-service/blob/dev/src/events/timelines/index.js#L169) itself and raising another meaningful event `PROJECT_PLAN_UPDATED` for the connect. So, that way connect app actually don't need to listen to the time adjusted event directly.
However, I guess now we should listen this event in `tc-notifications` for all users and keep its notification hidden in connect app so that we can use that event to show updates in timeline. If you think that works, let me know, I can do the changes in `tc-notifications` today.

**Comment by vikasrohit** [comment]
Or if you think you can make the changes in `tc-notifications` please feel free to make a PR.

**Comment by maxceem** [comment]
@vikasrohit yeah, I can handle it myself. Will raise a PR soon.

**Comment by maxceem** [comment]
Everything looks ready for this issue. But as we will need to dismiss notifications after we open corresponding tabs to remove `cue`. It's better to handle this issue after https://github.com/appirio-tech/connect-app/issues/1985 is done.

**Comment by maxceem** [comment]
There are two events currently doesn't come to the Connect App:
- `connect.action.timeline.adjusted` issue https://github.com/topcoder-platform/tc-notifications/issues/72
- `connect.action.timeline.milestone.waiting.customer` issue https://github.com/topcoder-platform/tc-project-service/issues/231

Also, it looks like so far there is no way to trigger `connect.action.project.product.update.spec` for `Specification` tab, as we don't have a form there, only file uploading.

**Comment by vikasrohit** [comment]
@maxceem I have fixed the issue with event `connect.action.timeline.milestone.waiting.customer`, it was a bug within the [code](https://github.com/topcoder-platform/tc-project-service/commit/22415e4cc8f28c6d4b4c16f850674b1d463b891d).
Further, I am able to see `connect.action.timeline.adjusted` event in tc-notifications database, so I think it should be visible in connect-app as well. Can you please debug it one more time to see if you are getting the event now.

`connect.action.project.product.update.spec` event can be raised by updating one of the product template to have a additional text field apart from file upload. And when you update that text field, it should raise the event.

**Comment by vikasrohit** [comment]
@maxceem Do you think we can take this one in next CF?

**Comment by maxceem** [comment]
@vikasrohit yes, as we already fixed message service to send required data.

**Comment by vikasrohit** [comment]
Great!! Please feel free to include it in CF.

**Comment by maxceem** [comment]
@vikasrohit I've done in this PR https://github.com/appirio-tech/connect-app/pull/2939 for all three tabs `Timeline` (done and tested), `Discussion` (was done before - tested), `Specification` (done, but this case never happens as we don't have anything to edit on this tab to trigger this kind of notifications) 

There is one tricky moment regarding the `Timeline` tab. When we expand phase, the `Timeline` tab is visible, so we mark all notifications related to this tab as read immediately. So cue disappears also immediately and as a result, we don't see it at all. See demo video with explanation
https://monosnap.com/file/JVKBTbSJRNJbU9Jbgz5yHM9y56LceB

**Comment by vikasrohit** [comment]
Thanks @maxceem I have gone through the issue with timeline tab. I think we have couple of options for that:

1. Hide the red dot after some delay (5 seconds)
2. Show a red dot on the specific milestone and fade that away with some delay (5 seconds) OR flash the background of the appropriate milestone so that user can notice something changed with that milestone
3. We can show a simple notification bar just below the Timeline tab which says something like `Timeline has been modified since you last visited the phase.            Mark as Read X` and let the user explicitly mark the notification as read. Other option within this approach could be to auto hide this after some delay (e.g. 5 seconds)

Anyway, we can mark this issue closed after we release the changes to the production and we need to file another issue with the problem we are facing now and work towards that in next release.

**Comment by maxceem** [comment]
@vikasrohit created a follow-up issue https://github.com/appirio-tech/connect-app/issues/2966

**Comment by vikasrohit** [comment]
@maxceem is it possible to quickly add delay for hiding timeline tab's red dot?

**Comment by maxceem** [comment]
@vikasrohit done in commit https://github.com/appirio-tech/connect-app/commit/8ce335ea4343ec49930fc5666017b14fa9b92ccf in `dev` branch.
Demo video https://monosnap.com/file/9Ij7HHyt9PWBDmyM9cBbxix08po6b6

**Comment by vikasrohit** [comment]
Awesome, Thanks!!!

**Comment by vikasrohit** [comment]
Looking good to me in dev. Closing the issue.
