### ISSUE TITLE
Edit message (sample feature)

### ISSUE THREAD

**Issue by vic-tian** [appirio-tech/connect-app#2460]
Feature ideas can be named however you'd like. We recommend focusing on the broad capability you'd like to make available to the user. This can help your team avoid making assumptions about the best solution before you've finished researching the need you'll be looking to address.

Each field below maps to a data column you can add to your Features/Releases boards to help with prioritization and planning.

Under Insights below, you'll see everyone who's ever requested this feature, what they said about, and how important it is to them – based on user insights on the Research board that have been linked to this feature idea. More info: http://bit.ly/pb-link-user-insights

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-422

**Comment by vic-topcoder** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1226227
