### ISSUE TITLE
[$30] Complete milestone for customer shouldn't have blue line

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2466]
### How to reproduce:
- Create project with type **App**
- Complete all milestones except of the milestone with title **Complete**
- View project with customer user and he will see:
   **Actual behaviour**:
   ![image](https://user-images.githubusercontent.com/146016/45009611-b7eb2480-b03b-11e8-934f-bd6654616637.png)
   There shouldn't bee blue line along description of this milestone.

    **Expected**:
    ![image](https://user-images.githubusercontent.com/146016/45009666-0ac4dc00-b03c-11e8-9a0c-3e4a17e8f800.png)

- Note. For manager user this milestone is displayed correctly.
   ![image](https://user-images.githubusercontent.com/146016/45009634-dea95b00-b03b-11e8-9971-06832d0d554b.png)

**Comment by PrakashDurlabhji** [comment]
@maxceem can you please assign it to me thanks

**Comment by maxceem** [comment]
@PrakashDurlabhji  just in case, you don't have to wait to be assigned to the issues and can already work on it as described in the new Bag Bush rules. Thanks.

**Comment by gurmeetb** [comment]
@PrakashDurlabhji are you working on this ? If not, please flag @maxceem to release it to me. 

@maxceem Kindly assign me if this gets free.

**Comment by PrakashDurlabhji** [comment]
@gurmeetb PR raising within 20mins @maxceem actively working on it.

**Comment by PrakashDurlabhji** [comment]
@maxceem done Pr raised

**Comment by maxceem** [comment]
@PrakashDurlabhji There is an issue with the PR, I've logged it here https://github.com/appirio-tech/connect-app/pull/2495#pullrequestreview-154598957.

Also, the way of implementing it now is not desirable. Please reuse the current approach of controlling the blue line by reusing component `<DotIndicator>`.

So there is no need to edit CSS stules. The way to do it as it's already done for other places is the next.
All the changes has to be done inside component `MilestoneTypeDelivery` https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx which is responsible for showing this milestone.
1. Update this line https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx#L206 with `<DotIndicator hideFirstLine={currentUser.isCustomer} hideDot>` which will hide the beginning of the blue line for customer user and line next to description. Please note, that as a blue line has to be hidden only if there is nothing except of the description. So you may need to adjust the condition `hideFirstLine={currentUser.isCustomer}`.
2. You may need to configure some properties of the `DotIndicator` on the other lines. And maybe you may also need to wrap the next line with `DotIndicator` too https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/timeline/milestones/MilestoneTypeDelivery/MilestoneTypeDelivery.jsx#L333. After making the change mentioned in the point 1 you may check if any other changes are need.

Please, have a look what props `DotIndicator` may accept https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/timeline/DotIndicator/DotIndicator.jsx

Meanwhile I'll close the PR as it has issue and uses new aproach instead of reusing existent code.

If you have questions regarading this task, feel free to raise them here.
Thanks.

**Comment by PrakashDurlabhji** [comment]
@maxceem will raise PR again immediately

**Comment by maxceem** [comment]
Due to inactivity, this issue is now open for pick up.

Please, refer for this comment https://github.com/appirio-tech/connect-app/issues/2466#issuecomment-420618772 for the recommended approach to resolve this issue.

Also note, the blue line has to be hidden if only description is shown for the milestone. If there are other elements are going after description the blue should stay as it is.

**Comment by suppermancool** [comment]
@maxceem pls assign to me

**Comment by maxceem** [comment]
@suppermancool done

**Comment by suppermancool** [comment]
@maxceem ready for review in https://github.com/appirio-tech/connect-app/pull/2512

**Comment by maxceem** [comment]
@suppermancool reviewed the PR, please, have a look https://github.com/appirio-tech/connect-app/pull/2512#pullrequestreview-155350007

**Comment by suppermancool** [comment]
@maxceem done, pls check, thanks
