### ISSUE TITLE
Newly added phase doesn't take into account the updated endDates of a phase if milestone is extended

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2467]
### Expected behavior
A new phase has to be added after the latest end date of phases in the project.

### Actual behavior
A new phase ignores end data of the phases which time was previously extended.

### Steps to reproduce the problem
- Create **App** type project http://local.topcoder-dev.com:3000/new-project/app

    ![image](https://user-images.githubusercontent.com/146016/45011542-a1e26180-b045-11e8-9fc6-50777e9e80e4.png)

- Note, **App Design** phase has the latest end date `Oct 6`.
- Active **QA & Bug Fixes** phase.

   ![image](https://user-images.githubusercontent.com/146016/45011600-f7b70980-b045-11e8-9f63-d9d9c00464bc.png)

- Extend the first milestone of the phase **QA & Bug Fixes** by 3 days for 4 times. It has to ends on `Oct 9` later than **App Design** phase.

   ![image](https://user-images.githubusercontent.com/146016/45011673-53819280-b046-11e8-9ff1-969d3214f4bf.png)

- A a new phase, for example `RUX Iteration`. It has start date `Oct 7` but expected start date is `Oct 10`.

   ![image](https://user-images.githubusercontent.com/146016/45011737-a3605980-b046-11e8-8960-fe63a2c8ad36.png)

#### Environment
- OS: All
- Browser (w/version): All
- User role (client, copilot or manager): All
- Account used: pshah_manager

Related issue https://github.com/appirio-tech/connect-app/issues/2427

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-437

**Comment by RishiRajSahu** [comment]
@maxceem able to reproduce it, so our current logic before adding a new phase calculate the latest endDate of existing phase, instead it should calculate the latest end date for a phase calculated wrt to durations of milestones.

**Comment by maxceem** [comment]
I think this one has the same reason as https://github.com/appirio-tech/connect-app/issues/2554 so they have to be handled together.

**Comment by RishiRajSahu** [comment]
working fine on dev. closing.
