### ISSUE TITLE
Settings for project plan events in notification settings page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2468]
This is a task in continuation with #2178 where we are now raising new set of events and to let the user control them via settings, we need to add the settings.

fyi @gondzo @RishiRajSahu

**Comment by vikasrohit** [comment]
@gondzo I have added the settings for new project plan related events.

I am wondering now, should we keep those settings by default disabled or enabled? It seems that our settings system in `tc-notifications` considers missing settings as enabled, right? Let me know what changes we need if we want to keep the emails for new events off by default.

fyi @vic-topcoder @acshields

**Comment by gondzo** [comment]
correct, all notifications are enabled by default. We don't have an option to have them disabled by default, that is something we would have to add to tc-notifications if it's really needed.

**Comment by vikasrohit** [comment]
@gondzo just to close the thread, we are okay with enabled email notifications by default. Only thing is that we need to fix is to allow bundling settings per event group. I have created [issue](https://github.com/appirio-tech/connect-app/issues/2522) to track that.

**Comment by vikasrohit** [comment]
Closing the issue as requested feature is implemented
