### ISSUE TITLE
[Project Featuers] - inform the user as must to press the x to back

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#247]
Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: pat_monahan

--------------------------------------------------------------------

Steps to reproduce the problem

- Login into application as manager.

- Go to Specification

- For Feature requirements press Add / Edit Feature.

- Select Email Login as example.

---------------------------------------------------------------------

Actual

- No information for user as must "x" close the window to back.

Expected

- Inform the user about back.

![infor](https://cloud.githubusercontent.com/assets/5114907/18930980/edb6f14c-85d2-11e6-9fde-b07fb19b5d5d.png)

**Comment by fnisen** [comment]
@vic-appirio have gotten this feedback, as well, from one of our early users. Let's add the button as you suggest.
