### ISSUE TITLE
[$50] Remove additional call to create product when adding phase

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2470]
When adding a new phase to project we make backend calls for both phase and product creation, with [this](https://github.com/topcoder-platform/tc-project-service/issues/163) new change in backend we can now remove the additional call to create product.

**Comment by simranb86** [comment]
Please assign me this.

**Comment by maxceem** [comment]
@simranb86 you may use this user `pshah_manager`/`topcoder123`

**Comment by simranb86** [comment]
Thanks - Could you also guide how do i reach this page where we add phases ? I don't see any projects so tried to Create new project which would not work - just shows rotating circle forever...

**Comment by maxceem** [comment]
You can create a new project, or use this one I've just created http://local.topcoder-dev.com:3000/projects/7274/plan

Go to the `Plan` tab. At the bottom, there will be `Add New Phase` button.

![image](https://user-images.githubusercontent.com/146016/45276052-bebddf80-b4f2-11e8-8f28-a738f509435a.png)

**Comment by simranb86** [comment]
@maxceem not sure but i always see blank screen for Projects

![noprojectsshown](https://user-images.githubusercontent.com/40840038/45277479-a5fafd00-b4e5-11e8-965d-9a48ced4b042.jpg)

**Comment by maxceem** [comment]
@simranb86 could you share what errors do you have on the `Console` tab? As it works well for me with the same user.

**Comment by maxceem** [comment]
@simranb86 Ok I think I've got it. Try to access your local deploying using address http://local.topcoder-dev.com:3000 instead of http://localhost:3000. To do so you have to add into your `/etc/hosts` the line `127.0.0.1 local.topcoder-dev.com`.

**Comment by simranb86** [comment]
Sorry @maxceem same behavior - attaching new logs. I am not sure but my env never works, even during last bash i had similar issue for setup and after 2 days i had to leave the ticket open. 

Any more suggestions i could try ?

[local.topcoder-dev.com-1536591111278.log](https://github.com/appirio-tech/connect-app/files/2367119/local.topcoder-dev.com-1536591111278.log)

![errorsnapshot](https://user-images.githubusercontent.com/40840038/45305311-9f957100-b537-11e8-9dc1-b48adfc756e9.jpg)

**Comment by simranb86** [comment]
@maxceem finally got it working, will push PR in 2-3 hrs. Sorry for the delay.

**Comment by maxceem** [comment]
@simranb86 as you didn't provide the update during the last 12 hours I have to open this issue for everyone to pick up.

**Comment by maxceem** [comment]
@rashmi73 it's yours.

I've also sent an invitation for you to this repo so I could also assign you to the issues for clearance.

**Comment by simranb86** [comment]
Thanks @maxceem yes working on it. 

> @simranb86 as you didn't provide the update during the last 12 hours I have to open this issue for everyone to pick up.

@maxceem no issues. Sorry couldn't provide since headed to work early morning, just came back and saw the note. BTW, I thought Topcoder Bug Bash always had 24 hrs window to push PR so not sure why you are talking about 12 hours ? Did Topcoder change its Bug Bash rules ?

**Comment by maxceem** [comment]
@simranb86 For the Bug Bash for Connect App there has been always (as long as I know) rules with the 12h window for PR see https://github.com/appirio-tech/connect-app/wiki/Bug-Bash-Rules. For this particular challenge, we've slightly modified them as participants cannot assign issues themselves, but the 12h window stays as in original Bug Bash rules for Connect App and is also mentioned in the challenge spec https://www.topcoder.com/challenges/30070926
These rules do not represent the overall Topcoder Bug Bash rules.

**Comment by maxceem** [comment]
@rashmi73 there are two more hours left before the end of 12 hours time for task. Please, don't forget to update with a comment if you need more time for this issue, or it would be open for pick up for everybody in 2 hours. Thanks.

**Comment by maxceem** [comment]
@rashmi73 no worries, as you've updated on this it will stays on you, you can take your time to finish the issue.

**Comment by rashmi73** [comment]
@maxceem working on it actively. PR within few hrs just stuck at minor thing

**Comment by rashmi73** [comment]
@maxceem i dont think i will be able to solve it immediately this one, so releasin it and now open for pickup

**Comment by Gauravseta** [comment]
@maxceem please give me thanks

**Comment by Gauravseta** [comment]
@maxceem to my assumption, also looking at backend changes required for this issue, comments on backend issue ticket.

To my assumption:
1. I need to remove the call to following method:
"return createPhaseProduct(project.id, phase.id, {
      name: projectTemplate.name,
      templateId: projectTemplate.id,
      type: projectTemplate.key || projectTemplate.productKey,
    })"

rather calling createPhaseProduct , i will pass "projectTemplateId" in Api call "return createProjectPhase(project.id, param)"

where param is object which contains projectTemplateId, so i dont have to call "createPhaseProduct".

so concluding ,i feel its removal of actual API "axios.post(`${PROJECTS_API_URL}/v4/projects/${projectId}/phases/${phaseId}/products`, { param: product })"

and not the removal of createProduct method call as mentioned in title?

am i correct? i am raising PR for it

**Comment by maxceem** [comment]
@Gauravseta if I understand your comment correctly - you are right.

> and not the removal of createProduct method call as mentioned in title?

Note, that in the title it's just description, not the method name. So we have to remove the additional call for creating a product when we are creating a phase. As we can now create a product together with phase due to a new change in the backend. And I think you've got it right.

Just to resolve possible confusion note, that method named `createProduct` https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/project.js#L334 is actually for adding a new phase with a product to the project and it should stay there.

So I think most likely all the changes will happen in `createProjectPhaseAndProduct` https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/project.js#L379 and relative APIs calls which this method does.

**Comment by Gauravseta** [comment]
@maxceem near to complete it.

**Comment by Gauravseta** [comment]
@maxceem Pr raised , pls checl

**Comment by maxceem** [comment]
@Gauravseta I've reviewed the PR, please check https://github.com/appirio-tech/connect-app/pull/2521#pullrequestreview-155769947

**Comment by Gauravseta** [comment]
@maxceem @gondzo  this is not paid yet. is it going to reflect in my account some time later?

**Comment by maxceem** [comment]
@Gauravseta has to be paid now, please check.
