### ISSUE TITLE
[$50] Adding field `details.metadata.waitingForCustomer` when marking the milestone for ready for review

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2471]
Need to add additional metadata field when making request to backend for marking the milestone ready for review so that we can notify customer about the action from backend.

related backend change - https://github.com/topcoder-platform/tc-project-service/issues/169

**Comment by maxceem** [comment]
@RishiRajSahu As I understand the full list of situations when we are waiting for customer action and probably have to add `details.metadata.waitingForCustomer` field is:
1. Non-customer user requests extension
2. `checkpoint-review` or `final-designs` milestone type is activated  we are waiting for customer to choose designs (milestone status becomes `active` and links are already provided i. e. `details.prevMilestoneType==='add-links'`)
3. for old way of working of `checkpoint-review` or `final-designs` milestone types. When links weren't intially provided (`details.prevMilestoneType!=='add-links'`) so they are added inside the milestone and after we call `moveToReviewingState()` method so customer can start choosing desgins
4. `delivery-design` or `delivery-dev` milestone type is activated and customer has to accept work or request fixes

Let me know if there is any other case you can think about, or some of these cases shouldn't be supported.

5. Should we mark `details.metadata.waitingForCustomer` as `false` when customer accomplishes his task so we can notifiy the manager back?

**Comment by RishiRajSahu** [comment]
@maxceem  Agree for 1 to 4, regarding point 5, yes we should do that as well.

**Comment by rashmi73** [comment]
I would like to work on it @maxceem

**Comment by maxceem** [comment]
@rashmi73 just in case, you don't have to wait to be assigned to the issues and can already work on it as described in the new Bag Bush rules. Thanks.

**Comment by vikasrohit** [comment]
> it as described in the new Bag Bush rules

@maxceem @rashmi73 Just to be clear, we haven't updated the generic rules for bug bash, it is just this particular challenge is using the slightly modified version of our standard bug bash in topcoder product development.

**Comment by gurmeetb** [comment]
@rashmi73  are you still working on this ? If not, please flag @maxceem to release it to me. 

@maxceem Kindly assign me if this gets free.

**Comment by rashmi73** [comment]
@gurmeetb just stop commenting everywhere.its clearly mentioned by @maxceem on some other issue that , once marked open for pickup, who ever comments after that will be given the issue. and i am working on it. near to complete it

**Comment by rashmi73** [comment]
@maxceem ready for review it is. Pr raised

**Comment by maxceem** [comment]
@rashmi73 Good start, but only one case out 5 required is currently implemented, refer for datils https://github.com/appirio-tech/connect-app/pull/2496#pullrequestreview-154929810

If you have any questions about other cases, please feel free to ask for clarifications.

**Comment by rashmi73** [comment]
@maxceem going on work

**Comment by nahidshahin** [comment]
@maxceem I want to work on it please

**Comment by maxceem** [comment]
it's on you now @nahidshahin

**Comment by gurmeetb** [comment]
@maxceem i was in queue first to take over this.

**Comment by gurmeetb** [comment]
@maxceem Ah ok, thanks for pointing to the rule, wasn’t aware of that.

**Comment by nahidshahin** [comment]
@maxceem add PR https://github.com/appirio-tech/connect-app/pull/2520

**Comment by maxceem** [comment]
@nahidshahin I've made a review, please check https://github.com/appirio-tech/connect-app/pull/2520#pullrequestreview-155767835

**Comment by nahidshahin** [comment]
checking
