### ISSUE TITLE
Handling phase discussions tab for drafted phases

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2477]
Do not make a welcome post to the phase discussion (Posts tab) before the phase is active.

![screen shot 2018-09-07 at 2 11 00 pm](https://user-images.githubusercontent.com/11248478/45208327-ed944580-b2a7-11e8-83fb-8960b0a0ba7d.png)

continued from https://github.com/appirio-tech/connect-app/issues/2301

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-450

**Comment by RishiRajSahu** [comment]
@vic-topcoder how should we handle UI in that case as per me there are two options - 
1.Keeping Discussions disabled with tool-tip saying 'Discussions will be available once phase is acitvated' OR 'Activate phase to enable discussions`
2.Hide Discussions tab for Drafted phase.

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields  I am not sure if this requirement. I think, copilots and managers need to discuss things before activating a phase, so where would they these discussions if implement this requirement?

**Comment by vikasrohit** [comment]
@RishiRajSahu @maxceem  Please hold on this, until we get confirmation.

**Comment by vic-topcoder** [comment]
Discussions should always be active when the customer can see it. It makes sense to be able to compose a message and then switch the phase into Planned phase, but that's probably overdoing it.

I'd say - let's hide the discussion until a phase is in Planned or further state.

This ticket originally addressed a different issue - the automatic first post in the thread. We DON'T WANT an automatic first post ever on a discussion tab - it makes no sense. I want this to be replaced with a better designed empty state that would encourage the customer to post any questions about the phase. Does this make sense?

**Comment by vikasrohit** [comment]
@vic-topcoder @acshields I still not fully convinced with this feature requirement. It is very common to use the discussions in draft phase well because copilots and managers can discuss things before activating the phase for customers. If we hide the discussions in draft mode, we would encourage the copilots and managers to use other modes of communication (outside of Connect) to discuss things before activating a phase.

**Comment by vic-topcoder** [comment]
Exposing managers-only discussion to customers is not great either. I think this is a deeper discussion on how we build connect to be the default communication platform.

**Comment by vikasrohit** [comment]
Okay @vic-topcoder @acshields  Let us know what is the final direction we should go for.

**Comment by vikasrohit** [comment]
Closing the issue as with upcoming changes for the project plan, we are going to restructure the the way we are showing the phases, milestones and their discussions.
