### ISSUE TITLE
[Project Dashboard] Status Dropdown UI/UX issue

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#248]
### Expected behavior
Drop down should appear fully

### Actual behavior
Drop down not appear appear fully when link tabs are open

### Steps to reproduce the problem
1 Go to project dashboard
2 Create new link
3 Try change status

### Screenshot/screencast
Attach or link a resource.
![screenshot 13](https://cloud.githubusercontent.com/assets/8684209/18931088/4b7839ce-85fd-11e6-8f68-464925d033e4.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/8684209/18931090/4bc91394-85fd-11e6-9953-e5abc1d60322.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version):Google Chrome Version 53.0.2785.116 m (64-bit)
- User role :Manager
- Account used: Pat Monahan

**Comment by fnisen** [comment]
Yeah, am seeing it work correctly. Closing.
