### ISSUE TITLE
[$35]  Align user avatar in the post composer correctly

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2480]
User avatar in the post composer (footer) is not aligned with the avatar from the actual post.

https://github.com/appirio-tech/connect-app/issues/2301

**Comment by maxceem** [comment]
@RishiRajSahu There is one more thing. When user doesn't have and image avatar defined. It's not displayed next to composer at all, see for example as `pshah_manager`:

![image](https://user-images.githubusercontent.com/146016/45215152-28f63a80-b2cf-11e8-9801-7f1fa2a40fc8.png)

I don't remember what was the reason to remove avatar in such case. But probably it's not desired, and we have to put it back even if user doesn't have an image avatar. So intials has to be displayed instead of the image as at other places.

**Comment by gurmeetb** [comment]
@maxceem Is this open for pickup ?

**Comment by maxceem** [comment]
@gurmeetb not yet, but will be open soon after the relative challenge run.

**Comment by gurmeetb** [comment]
Thanks @maxceem for quick response.

**Comment by maxceem** [comment]
@gurmeetb just want to let you know that challenge is planned to be started on Monday. The Bug Bash process will be slightly changed.

**Comment by maxceem** [comment]
@gurmeetb  The challenge is on.
Important! There is a change in the Bug Bash process, please read the new rules in the challenge spec carefully, before starting work on issue https://www.topcoder.com/challenges/30070926/?type=develop&noncache=true
Thank you!

**Comment by arun1595** [comment]
@maxceem I would like to tackle this issue.

**Comment by gurmeetb** [comment]
@maxceem Can I work on this now ?

**Comment by gurmeetb** [comment]
Thanks

**Comment by gurmeetb** [comment]
@maxceem I am new to this app, could you guide how do I land the page to see the issue ?

**Comment by iversonLv** [comment]
@maxceem I think I could get the ticket as per Bug bash rule: 12hr is gone and there is no PR

**Comment by gurmeetb** [comment]
It’s done and ready for review

**Comment by gurmeetb** [comment]
@iversonLv when it was assigned I was sleeping - logically I started working only 3 hrs back and there is PR moved in. 

@maxceem @vikasrohit  12 hrs rule will not work. You need to take into consideration ppl from around the globe take part so we should have 24 hrs rule.

**Comment by maxceem** [comment]
@gurmeetb got your PR, thanks.

Btw, you don't have to wait to be assigned to the issue to work on it. As soon as you made your comment with the intention to pick up the issue, it's yours and you can start working on it. Also, time starts from that moment and you have 12h to accomplish the issue or make a comment if need more time.

**Comment by maxceem** [comment]
@gurmeetb I've checked your PR, please have a look https://github.com/appirio-tech/connect-app/pull/2493#pullrequestreview-154590660

**Comment by maxceem** [comment]
@gurmeetb I've checked your updated PR, please have a look https://github.com/appirio-tech/connect-app/pull/2493#pullrequestreview-154911945
