### ISSUE TITLE
[$20] Redirect to current project after creating a new project

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2483]
Currently, if we open some [project](http://local.topcoder-dev.com:3000/projects/7271) and after click "+" icon to create a new project, the URL will be like this:
```
http://local.topcoder-dev.com:3000/new-project/?returnUrl=http://local.topcoder-dev.com:3000/projects/7271
```

After succesfull project creation we will be redirecting back to the project which was previously opened instead of the project we've just created.

It feels for me like not desired behaviour, but I'm not sure.

**Comment by vikasrohit** [comment]
@maxceem I think we have this logged somewhere in github, but none the less it seems that it is not desired behaviour now. So, you can get it fixed in the bug bash.

**Comment by akmarif** [comment]
@maxceem could you please assign it to me?

**Comment by maxceem** [comment]
@akmarif you can already work without waiting for the assignment. But to let me assign it to you please, accept an invitation you have to get from GitHub.

**Comment by maxceem** [comment]
@akmarif as this issue is very small and wasn't completed in 12 hours without any comment I'm opening it to pick up for everyone.

This issue is now available to pick up.

**Comment by anonymousjaggu** [comment]
@maxceem please assign me

**Comment by maxceem** [comment]
@anonymousjaggu it's on you since you've commented. To make it more clear I can assign you to this issue in the interface. To do so, please, accept the invitation to this repo which has to pop up to your email. Thanks.

**Comment by maxceem** [comment]
I see it's done by PR https://github.com/appirio-tech/connect-app/pull/2498

@anonymousjaggu please, better comment to the issue when you create a PR as described in the Bag Bush rules published in the challenge spec. As I didn't see any updates here, I was going to unassign you from this issue in two hours :-) This time I saw your PR in the list but could easily miss it.

**Comment by maxceem** [comment]
@anonymousjaggu I've reviewed your PR, please have a look https://github.com/appirio-tech/connect-app/pull/2498#pullrequestreview-154966349

**Comment by maxceem** [comment]
@anonymousjaggu There is a couple of small issues with the raised PR. One of them I cannot merge PR because of conflict. Please, let me know if you will be available to resolve them.

**Comment by anonymousjaggu** [comment]
ok will fix this

**Comment by maxceem** [comment]
The previous participant didn't resolve merge conflicts and asked to be unassigned.

So this issue is now open for pick up.

**Comment by PrakashDurlabhji** [comment]
@maxceem can u please assign to me?

**Comment by PrakashDurlabhji** [comment]
@maxceem Pr raised. please check
