### ISSUE TITLE
[$40] Correcting final fixes `Add` button styling

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2484]
This is in continuation of https://github.com/appirio-tech/connect-app/issues/2301 list-

![screen shot 2018-09-07 at 4 34 56 pm](https://user-images.githubusercontent.com/11248478/45215731-fc84f300-b2bb-11e8-8a47-3dbbd68c2709.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-457

**Comment by RishiRajSahu** [comment]
@vic-topcoder could you please provide exact details ?

**Comment by maxceem** [comment]
@vic-topcoder @vikasrohit @RishiRajSahu 

In FireFox it looks even slightly worse, and same for remove "-" button.

![image](https://user-images.githubusercontent.com/146016/45291745-9ef3df00-b525-11e8-9ac2-197b32306087.png)

There are three ways to solve it:
1.  Just adjust styles to match desgin as close as possible including:
    - make sure the buttons are circle (not oval)
    - make sure there is not boder like if FireFox
    - make sure the "-" and "+" signs are vertically and horizontaly centered

    Note, Currently "+" and "-" are done by text chaacters.

2. We already have an SVG for ["+"](https://github.com/appirio-tech/connect-app/blob/dev/src/assets/icons/ui-16px-1_bold-add.svg) and ["-"](https://github.com/appirio-tech/connect-app/blob/dev/src/assets/icons/ui-16px-1_bold-delete.svg) signs in project. Where the "+" sign is being used for creating new projects. But I'm not sure if these are the same SVG which we need and if it's desirable to reuse them.

      ![image](https://user-images.githubusercontent.com/146016/45291998-5be63b80-b526-11e8-8316-afb41395d826.png)
     
      If we use these SVGs for "+" and "-" signs, we still have to make sure that we don't have any of the issues from the point 1.

3. Probably somebody can provide correct SVG for these buttons as SVGs are not available trought [Marvel Handoff](https://marvelapp.com/8a94680/screen/41372926).

**Comment by vic-topcoder** [comment]
Let's fix the CSS styles of the buttons. I'd like to keep using the SVG icons and build a straight logical system for small circular buttons. Right now the styles break. This means going with @maxceem's suggestion for **point 2**.

The correct SVG should be already in the project assets folder, no?
[small plus and minus 16px.zip](https://github.com/appirio-tech/connect-app/files/2389971/small.plus.and.minus.16px.zip)

**Comment by vikasrohit** [comment]
@RishiRajSahu please remove the Blocked status if we have the requirements clear now.

**Comment by maxceem** [comment]
To sum up:
1. We already have an SVG for ["+"](https://github.com/appirio-tech/connect-app/blob/dev/src/assets/icons/ui-16px-1_bold-add.svg) and ["-"](https://github.com/appirio-tech/connect-app/blob/dev/src/assets/icons/ui-16px-1_bold-delete.svg) signs in project.
2. We can reuse these SVGs to recreate + and - buttons in [MilestonePostEditText](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/timeline/MilestonePostEditText) component. (Note, Currently "+" and "-" are done by text characters but has to be done using SVG.)
3. We have to match design here https://marvelapp.com/8a94680/screen/41372926, in particular:
    - make sure the buttons are circle (not oval)
    - make sure there is not border like if [FireFox](https://user-images.githubusercontent.com/146016/45291745-9ef3df00-b525-11e8-9ac2-197b32306087.png)
    - make sure the "-" and "+" signs are vertically and horizontaly centered
    - keep these buttons as `<button>` HTML tag unless it's impossible to match the design using button tag in some reason.
4. Use variables for colors in SCSS from https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss. 
5. Test it crossbrowser.

**Comment by prasadadarkar30** [comment]
@maxceem pls assign me.i wish to work on it.

**Comment by maxceem** [comment]
As the issue hasn't been completed during 12 hours and no comment was provided, this issue is now open for pick up.

**Comment by rashmi73** [comment]
@maxceem pls assign this to me.

**Comment by rashmi73** [comment]
@maxceem actively on this. saw how to solve it, using svg. also it is a css change and need to test well.so i hope i will be given enough time.
also can you please give me link to project in which i can see add button as i am not able to see "Add" button in any of project. i searched many . can u please tell project number so i can raise PR immediately. thanks

**Comment by maxceem** [comment]
@rashmi73
- login with user `pshah_customer`/`topcoder123`
- open project http://local.topcoder-dev.com:3000/projects/7422/plan on `Project Plan` tab
- open `Visual Design` 
- at the bottom you will see the ability to add final fixes:
   ![image](https://user-images.githubusercontent.com/146016/46843238-6422e680-ce04-11e8-8f50-c8bc74f6adae.png)
- if you accidentally lose the ability to add final fixes here (submit them or somebody else modifies project), you can check this [Guide](https://github.com/appirio-tech/connect-app/wiki/Milestones) on how to get final fixes milestone (`MilestoneTypeFinalFixes `) by yourself

**Comment by rashmi73** [comment]
@maxceem actively working on it. PR within few hrs

**Comment by rashmi73** [comment]
@maxceem still workinh .few more hrs. internet connectivity issue at my place. hence lost many hrs

**Comment by maxceem** [comment]
@rashmi73 I've checked provided PR, please have a look https://github.com/appirio-tech/connect-app/pull/2629#pullrequestreview-165061310

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
