### ISSUE TITLE
[$40] Consider Planned phases for calculating Project progress

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2488]
Current implementation of calculation project progress doesn't consider planned phases its only considering `Active` and `delivered`. It should consider planned phases as well. Please find the screen shot for existing behaviour.

![screen shot 2018-09-10 at 2 31 37 pm](https://user-images.githubusercontent.com/11248478/45287702-8e803c00-b506-11e8-94be-c0cea4b01d8d.png)

**Current Behaviour -** 

Project Progress = (100 + 100 + 100 + 82)/4 = 96

**Expected Behaviour -** 

Project Progress = (100 + 100 + 100 + 82 + **0**)/**5** = 76

**Comment by RishiRajSahu** [comment]
fyi @maxceem

**Comment by iversonLv** [comment]
@maxceem I would like to work on it

**Comment by iversonLv** [comment]
It’s done and ready for review
