### ISSUE TITLE
[Specifications] - when press on specification the title is hidden

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#249]
Expected behavior
- Display the title of specification on the top of section.

Actual behavior
- The title is not displayed on the top of section.

Steps to reproduce the problem
- Login into application as manager.
- Edit an existing project eg. test.
- Select Specifications tab.
- From the left Specifications section press on "2.Design Specification / Questions".

Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: pat_monahan

![a](https://cloud.githubusercontent.com/assets/5114907/18931226/efc2f2b4-85d3-11e6-9e19-d66c2d7de91c.png)

![b](https://cloud.githubusercontent.com/assets/5114907/18931237/f5e4d78e-85d3-11e6-9c63-eda51aa72607.png)

![c](https://cloud.githubusercontent.com/assets/5114907/18931240/fc38486e-85d3-11e6-9481-33c310fbbd5d.png)

**Comment by vikasrohit** [comment]
Done. Changes are in dev.
