### ISSUE TITLE
Default bundling to 24 hours for all users

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2505]
To reduce the chances of email flood to the customers we are going to set frequency of emails to `daily` from immediate.

fyi @acshields @vic-topcoder

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-476

**Comment by acshields** [comment]
Hi @vikasrohit - Great call out.  In rating this through I am in agreement with you that we need to build the capability to select notification per bundling feature prior to go-live.

**Comment by vikasrohit** [comment]
@acshields It would need time to get that capability done and I am almost certain that we can't do that in this release. So, we have to release with instant email notifications for all new events. However, there is a positive here, we send all emails in single email thread i.e. subject remains same for all emails, so essentially it would group all notification emails in single email thread, so most probably their inbox won't be cluttered.

**Comment by vikasrohit** [comment]
@acshields I am able to get the bundling per notification group, working. #2522 details the requirements and solution.
Hopefully we should be able to get it in our upcoming release.

**Comment by acshields** [comment]
@vikasrohit - Awesome!

**Comment by vikasrohit** [comment]
Done.
