### ISSUE TITLE
[$20] Draft phases should not have value other than 0 for progress field

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2506]
When the phase is in draft status for more than a day, the `progress` field gets updated with non-zero value. 

Expected - Draft phases should always have value 0 for `progress` field.

![screen shot 2018-09-12 at 12 52 24 pm](https://user-images.githubusercontent.com/11248478/45413005-b81b9d80-b695-11e8-924e-d2b6e462ad7a.png)

**Comment by RishiRajSahu** [comment]
fyi @maxceem

**Comment by Gauravseta** [comment]
@maxceem assign me thanks

**Comment by nahidshahin** [comment]
@maxceem I want to work on it, please

**Comment by maxceem** [comment]
@nahidshahin Please, claim for issues which are open for pick up. Another participant is already working on this issue.

**Comment by Gauravseta** [comment]
@maxceem pls check PR , which is raised

**Comment by maxceem** [comment]
@RishiRajSahu provided fix will definitely fix the issue, but I cannot reproduce it to verify.

For example, this project https://connect.topcoder-dev.com/projects/7264/plan has several Draft phases started some time ago, but progress is 0 for them without a fix yet.

I've checked several projects but couldn't find any with such issue, maybe you have any for reference?

**Comment by RishiRajSahu** [comment]
@maxceem change the startDate of draft phase to older value and you shouldn't see any change in progress it should be 0 always.

**Comment by Gauravseta** [comment]
@maxceem @gondzo this is not paid yet. is it going to reflect in my account some time later?

**Comment by maxceem** [comment]
@Gauravseta it's in the process now, I'll update on this shortly when it has to appear on your account.

**Comment by maxceem** [comment]
@Gauravseta has to be paid now, please check.

**Comment by Gauravseta** [comment]
@maxceem thanks.it is visible now.
