### ISSUE TITLE
[$40] Jumbled/Incorrect Words Appearing in Projects

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2518]
Words are becoming jumbled when creating a Connect project on a customers behalf.
<img width="1103" alt="screen shot 2018-09-14 at 11 18 07 am" src="https://user-images.githubusercontent.com/41118149/45559825-5aec2d00-b7f8-11e8-8a29-803875bffa02.png">

(https://connect.topcoder.com/projects/7060)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-480

**Comment by maxceem** [comment]
It's on you, you can work on it.

**Comment by gets0ul** [comment]
How to reproduce this issue?  
Any screencast?

**Comment by maxceem** [comment]
[Create a new project](http://local.topcoder-dev.com:3000/new-project) include in all the fields special characters, for example, `&`.

After the project is created go to the `Scope` tab and `&` will be replaced with `&amp;`.

See screencast https://monosnap.com/file/QTSn1Q1tFMLI4XunpVgCdWH0CuaJow

You can check the sceenshot of issue in the top comment, to get a hint which other characters are replaced with their HTML numeric entities.

**Comment by gets0ul** [comment]
@maxceem PR is done and ready for review.  
Thanks

**Comment by maxceem** [comment]
@gets0ul I've reviewed the PR, please have a look https://github.com/appirio-tech/connect-app/pull/2602#pullrequestreview-164484153
Thanks.

**Comment by maxceem** [comment]
@RishiRajSahu fyi, it's done and has to work good for all the characters. Though the solution is to handle it in every place individually https://github.com/appirio-tech/connect-app/pull/2602/files. I don't see a better way for this so far.

**Comment by RishiRajSahu** [comment]
@maxceem agree and looks good to me.
