### ISSUE TITLE
Clicking on 'Save Changes' button 2-3 times will display 'Project updated.' message 2-3 times

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#252]
## Description

Clicking on 'Save Changes' button 2-3 times will display 'Project updated.' message 2-3 times
## Expected Result(s)
- Must display only one time
## Actual Result
- Clicking on 'Save Changes' button 2-3 times will display 'Project updated.' message 2-3 times
## Steps to Reproduce
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name
- Click 'Specification'
- In 'App Definition'
- Fill all the required details
- Click 'Save Changes' button 2-3 times
## Environment
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by fnisen** [comment]
Button is not disabled right away. You can get in a few clicks before it becomes greyed out.

**Comment by vikasrohit** [comment]
Done. Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit this is not working quite correctly. Here is the error behavior: 
1. Make a change to the spec of any project (say in the notes) 
2. Hit save; button is temporarily greyed out, but then blue again
2. Hit save again; button is now greyed out and stays grey until you make a change

**Comment by vikasrohit** [comment]
Yes, I saw that. And I cross checked that this behaviour is there well before this  change. And I tried to get rid of that, however, was not able to do so in time. Hence, I thought of closing this issue and created separate issue for tracking that. Anyway, I would try to fix this on Monday, if I am not able to close that, I would create separate issue for that.

**Comment by vikasrohit** [comment]
@fnisen tried again, however, seems like it needs more efforts. Created separate issue https://github.com/appirio-tech/connect-app/issues/542 to track it.
Closing this one.
