### ISSUE TITLE
Need bundling support for email group

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2522]
### Expected behavior
User should be able to configure different bundling behaviour per event group e.g. `Post and replies` could be immediate delivery events while `Project plan` events could be bundled by 24 hours.

### Actual behavior
As of now it allows same bundling setting for all events i.e. if user chose to bundle by 24 hours, it would bundle all events by that duration.

### Steps to reproduce the problem
- Open [Notification Settings](https://connect.topcoder.com/settings/notifications) page after logging in and observe that we have only global level of bundling support

### Screenshot/screencast
<img width="855" alt="screen shot 2018-09-17 at 10 59 30 am" src="https://user-images.githubusercontent.com/2417632/45607250-c9cfbd00-ba68-11e8-95c5-fcfced526f7a.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-481

**Comment by vikasrohit** [comment]
fyi @acshields @vic-topcoder @RishiRajSahu  @gondzo

**Comment by acshields** [comment]
@vikasrohit - Love the design and logic outline above.  I just went into Connect to try & find how to access the Notification Settings page from a project and I couldn't locate it.  I assumed it would be under Profile/Settings.  Where is it?

**Comment by gondzo** [comment]
@acshields click the notifications icon, click all notifications and then click the notifications settings button

**Comment by acshields** [comment]
Hi @vikasrohit @vic-topcoder - Per our conversation this morning:

1. I liked the second option you showed me (where the user can select which notification types they want bundled, but they can only set one cadence for the bundles to be sent). See design above.

2. We need to add language/direct link to the notifications tab that indicates to the customer that they have the option to modify notification settings, as the current workflow is not intuitive.

<img width="1420" alt="screen shot 2018-09-18 at 10 21 54 am" src="https://user-images.githubusercontent.com/41118149/45705362-4082be00-bb2e-11e8-9028-c29543ff9301.png">

3. @vic-topcoder - Do you think we need the "Web" notifications selection? Matt raised a good point stating that now that we will have email notification on/off/bundled options we should make web notifications required.  Thoughts?

**Comment by vic-topcoder** [comment]
There are certain notifications we should make standard (always on) for the web, and there are some that might be optional. I want us to review what notifications are optional and what do they deliver to the end customer. We might want to expand the notification options for the managers and admins as well.

Certain notifications should also be updating the tab title: from `Topcoder Project` to `(4) Topcoder Project` which will indicate there's new activity on Topcoder. This is pretty popular UX pattern in major apps.

I am not sure if we want to expose the notification settings so prominently, but rather figure out what is not working and what is the best general starting point for the notifications. I would probably move the notification settings at the bottom of the drop down, or use a settings icon. This is really tied to how often we expect people to be modifying their notifications.

![screen shot 2018-09-18 at 1 34 52 pm](https://user-images.githubusercontent.com/8484061/45714858-ac255500-bb47-11e8-89c7-786c44f910f8.png)

**Comment by vikasrohit** [comment]
@vic-topcoder Moved the notification settings discussion to a separate issue #2526  to keep the scope of the issue lean.

**Comment by vikasrohit** [comment]
> I liked the second option you showed me (where the user can select which notification types they want bundled, but they can only set one cadence for the bundles to be sent). See design above.

For this option here is the final UI what it look like

![notification_settings_bundling_option2](https://user-images.githubusercontent.com/2417632/45733741-7d6ab580-bbff-11e8-9bb3-970d6810af9d.png)

> Do you think we need the "Web" notifications selection? Matt raised a good point stating that now that we will have email notification on/off/bundled options we should make web notifications required. Thoughts?

I collected data from production database about usage of web notifications and found that only one user (apart from @vic-topcoder 😬 ) has opted out for few web notifications. Event that user has not disabled all web notifications, but only project status changes related events are disabled for him.

**Comment by vic-topcoder** [comment]
The interface is slightly confusing with the emails, as the best way is to actually allow certain emails to be bundled vs. certain emails arriving as they happen. If we want to allow granularity of email bundling we should replace the 2 switches with a simple drop-down to control both subscription to email and email frequency:

Desktop:
![screen shot 2018-09-19 at 8 56 56 am](https://user-images.githubusercontent.com/8484061/45765542-1b538580-bbea-11e8-8708-b572d1d61152.png)

and translating that to mobile:
![screen shot 2018-09-19 at 8 57 29 am](https://user-images.githubusercontent.com/8484061/45765555-23132a00-bbea-11e8-98b2-9486bf0a56ec.png)

**Comment by vikasrohit** [comment]
@vic-topcoder Seems like a good option to achieve granular control over cadence of email bundling. However, I have already made changes for the screen I have shared and these changes are not something only UI specific, we need to make backend aware of these as well so that it can read the correct setting and respond accordingly. To store bundling at per notification group level, we need to throw away the current code and recode to have settings as per new UI.  And if we like to have this UI go live with this release, it has to be delayed because it need time to adjust for this and testing (which is the most critical part for email notifications).
@vic-topcoder  @acshields I am assuming that this is the  way to go for enabling bundling per notification group and starting working on it. Only exception would be that color theme would not be green as shown in the new design, and it would follow the current blue theme.

**Comment by vic-topcoder** [comment]
This is a UX pattern I grabbed from a different place, to not redo it with our UI Kit. This is a conversation starter and based on what Ariel and you guys say we can go forward

**Comment by vic-topcoder** [comment]
@acshields please indicate any content changes to the notification title and description, otherwise the content can be selected in Handoff state of the Marvel link.

Updated visual specification for desktop: https://marvelapp.com/3e3085h/screen/48110584

Icons .SVG pack
[notification settings icons.zip](https://github.com/appirio-tech/connect-app/files/2403487/notification.settings.icons.zip)

Preview:
![email notifications no nav](https://user-images.githubusercontent.com/8484061/45853534-c6ebfb00-bcfa-11e8-95aa-dab5077fdfa4.png)

**Comment by maxceem** [comment]
Have a couple of questions regarding new design:
1. Would you like to make Select dropdown as per design here? Or reuse existent design for Select dropdown? 
   ![image](https://user-images.githubusercontent.com/146016/45947616-85738c80-c027-11e8-9fb2-e3bca9de3abf.png)
   ![image](https://user-images.githubusercontent.com/146016/45947625-902e2180-c027-11e8-9d00-69dd68b74452.png)

2. Switch buttons currently are implmented without label on it `on`/`off`. Would you like to reuse current design or implement new one?
     ![image](https://user-images.githubusercontent.com/146016/45947700-ce2b4580-c027-11e8-9b11-c2442fe6871d.png)

**Comment by vikasrohit** [comment]
@maxceem both components should be reused, no need to implement new ones right now.

**Comment by vic-topcoder** [comment]
@maxceem Please follow the design for the drop-down (select) component; it is important to match with the design. Reuse the functionality of the components. The On/Off labels are secondary at this point. Thanks!

**Comment by vikasrohit** [comment]
@vic-topcoder We don't have time for this release to use the new design and behaviour for the dropdown and when we do it, we have to do it across the board, so it is a time consuming process. Right now we are sticking with whatever look we have in our application for the dropdowns.

**Comment by vikasrohit** [comment]
@maxceem Please leave the system notifications section out of scope as well.

**Comment by vikasrohit** [comment]
Closing as required features are completed and will create new issues if any issues/enhancement needed.
