### ISSUE TITLE
[$50] Use productCategories instead of projectTypes for product classification

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2524]
## Overview

When we add a new phase to a project we see the list of products which is divided into categories:

![image](https://user-images.githubusercontent.com/146016/45727864-1ac1eb80-bbf8-11e8-9f3f-ef7bc74536a4.png)

It suppose to use `productCategories` to devide products into these sections and show titles of the sections. But instead it uses `projectTypes` now.

![image](https://user-images.githubusercontent.com/146016/45728204-9e300c80-bbf9-11e8-94f6-9c1ce4ceace8.png)

This most likely happens due to a confusion caused by the current code. Inside code we use term `projectCategories` instead of `projectTypes` so it's easy to confuse **project***Categories* with **product***Categories*.

### 1. Products on the "add a new phase" popup should be categorised using `productCategories`.

- Action `loadProjectsMetadata` already loads all the metadata using `/v4/projects/metadata`. The only thing it doesn't populate Redux Store with `productCategories` https://github.com/appirio-tech/connect-app/blob/cf12/src/reducers/templates.js#L21. So it has to be adjusted to populate `templates.productCategories` in Redux Store.
- After that we have to adjust code of "add a new phase" [popup](https://github.com/appirio-tech/connect-app/blob/cf12/src/projects/create/components/SelectProductTemplate.jsx) to use `templates.productCategories` instead of `templates.projectCategories`.

### 2. Rename `projectCategories` to `projectTypes` everywhere in project code

This has to be done in the Redus Store `templates.projectCategories -> templates.projectTypes` and in all relative places to avoid future confusion.

## References:
- https://github.com/appirio-tech/connect-app/issues/2472 - implementation of loading metadata using `/v4/projects/metadata`
- https://github.com/appirio-tech/connect-app/issues/2139 - implementation of categories on "add a new phase" popup

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-482

**Comment by vikasrohit** [comment]
> After that we have to adjust code of "add a new phase" popup to use templates.productCategories instead of templates.projectCategories.

@maxceem  last instance of `templates.projectCategories` in above statement should be `template.projectTypes`

I didn't understand the second requirement to rename projectCategories to projectTypes. I think we need both projectTypes and productCategories.

**Comment by maxceem** [comment]
@vikasrohit yeah, it all about confusion brought by the terms we are using `projectCategories` vs `projectTypes`.

 > @maxceem last instance of templates.projectCategories in above statement should be template.projectTypes

Currently, in our code and Redux Store we have only `templates.projectCategories` which is now being used on the "add a new phase" popup:

![image](https://user-images.githubusercontent.com/146016/45731530-a5134b00-bc0a-11e8-801f-bb6ae3ba0754.png)

Note, it's **project***Categories* not **product***Categories*. And this `projectCategories` is actually same as `projectTypes` in the API:

![](https://user-images.githubusercontent.com/146016/45728204-9e300c80-bbf9-11e8-94f6-9c1ce4ceace8.png)

> I didn't understand the second requirement to rename projectCategories to projectTypes. I think we need both projectTypes and productCategories.

Yes we need both `projectTypes` and `productCategories`. 
But as I said currently we only have `templates.projectCategories` in our Redux Store which is actually `projectType` in our new naming. So I think we should rename `templates.projectCategories` to `templates.projectType`. And additionally load `templates.productCategories`.

Let me know if there is still confusion.

**Comment by maxceem** [comment]
@mhikeo it's on you since you claimed it. 
To let me assign you, please, accept the invitation to this repo, which has to come to your email.
Thanks.

**Comment by maxceem** [comment]
As the issue hasn't been completed during 12 hours and no comment was provided, this issue is now open for pick up.

**Comment by gets0ul** [comment]
@maxceem PR is done and ready for review.

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
