### ISSUE TITLE
Better position for Notification settings link

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2526]
Continued from https://github.com/appirio-tech/connect-app/issues/2522#issuecomment-422529049

@vic-topcoder 's comment

There are certain notifications we should make standard (always on) for the web, and there are some that might be optional. I want us to review what notifications are optional and what do they deliver to the end customer. We might want to expand the notification options for the managers and admins as well.

Certain notifications should also be updating the tab title: from `Topcoder Project` to `(4) Topcoder Project` which will indicate there's new activity on Topcoder. This is pretty popular UX pattern in major apps.

I am not sure if we want to expose the notification settings so prominently, but rather figure out what is not working and what is the best general starting point for the notifications. I would probably move the notification settings at the bottom of the drop down, or use a settings icon. This is really tied to how often we expect people to be modifying their notifications.

![screen shot 2018-09-18 at 1 34 52 pm](https://user-images.githubusercontent.com/8484061/45714858-ac255500-bb47-11e8-89c7-786c44f910f8.png)

So we can do this in Connect
![screen shot 2018-09-18 at 1 37 44 pm](https://user-images.githubusercontent.com/8484061/45715070-2b1a8d80-bb48-11e8-86bf-3ff37c9f5729.png)

We have a focus on settings if there are no notifications as well (empty state)
![screen shot 2018-09-18 at 1 36 00 pm](https://user-images.githubusercontent.com/8484061/45715055-248c1600-bb48-11e8-80a8-119df6571a67.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-483

**Comment by acshields** [comment]
Hi @vic-topcoder & @vikasrohit - Thanks for the mockups, I think these look great and meet the need I identified for the user to have a more intuitive pathway for modifying their notification settings.

**Comment by vic-topcoder** [comment]
So - let's add the link for Settings as the right-most item on the top of the drop-down menu. The structure will be `Mark all as read • Settings`. This should be extremely easy to do @vikasrohit

**Comment by RishiRajSahu** [comment]
done with https://github.com/appirio-tech/connect-app/commit/3f7c2f9ba911fd2727b4a859671596ce1361ce54. @vic-topcoder @acshields, could be verified in dev.
