### ISSUE TITLE
Layout issue when user enters long text to the File name and Description

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#254]
## Description

Layout issue when user enters long text to the File name and Description
## Expected Result(s)
- Must crop the title with (...)
- Display the EDIT and DELETE buttons in-line
## Actual Result
- Layout issue when user enters long text to the File name and Description
## Steps to Reproduce
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name
- Click 'Specification'
- In 'App Definition'
- Fill all the required details
- Upload 2-3 documents
- Click EDIT
- Enter long name to the File name and Description
- Click OK
## Environment
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by sdgun** [comment]
![2016-09-29_6-03-40](https://cloud.githubusercontent.com/assets/4592712/18937077/87feb6e0-860a-11e6-8d7f-77658a4eb7f0.png)

**Comment by vic-appirio** [comment]
Small layout fixes

**Comment by vic-appirio** [comment]
Do not limit the text with ellipsis, fix the breaking size of affordances (the red box in the screenshot) being too narrow. File size number and unit should be always 1 line (white-space: no-wrap).

**Comment by vic-appirio** [comment]
Fixed, pending merge
