### ISSUE TITLE
Uncaught Error: The token is invalid

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2544]
On the DEV environment, I've started getting `Uncaught Error: The token is invalid`.

This error causes the blank page to be shown without the ability to do anything:

![image](https://user-images.githubusercontent.com/146016/45996761-ece51700-c0cf-11e8-9567-59e46d34144f.png)

Here is source code where it happens:

![image](https://user-images.githubusercontent.com/146016/45996798-1140f380-c0d0-11e8-8589-0f7b575c8dfa.png)

Clearing the cache and login again resolved the issue. But after some time I started getting this error again.

I think this is kind of critical issue, as there is no way for a user to re-login except of clearing cookies. I've tried to follow a [log-out link](http://accounts.topcoder-dev.com/#!/logout?retUrl=http://local.topcoder-dev.com:3000/projects) directly, but it didn't help. Stuck with the next screen:

![image](https://user-images.githubusercontent.com/146016/45999256-bad7b300-c0d7-11e8-99d0-51bd5c5689a9.png)

On this login out page, the same error is displayed in console `Uncaught Error: The token is invalid`.

Probably this issue has to be resolved not in connect-app, but in https://github.com/appirio-tech/accounts-app.git.

FYI @RishiRajSahu @vikasrohit

**Comment by RishiRajSahu** [comment]
@maxceem I think there was an active development work going on in account app that time due which it might have caused this issue. if it got reproduced any time after that ?

**Comment by maxceem** [comment]
@RishiRajSahu I saw it today in another browser, but probably the page was loaded yesterday. I'll check one more day and will let you know.

**Comment by vikasrohit** [comment]
That means for some request(s), it is not refreshing token before making a call?

**Comment by maxceem** [comment]
That was a very strange issue. I think it didn't come to place for a refreshing token. As I even couldn't log out when that error happened, only clean the cookies helped.

I think that situation which happens here is not handled by a `try catch` so when this error happens, code stops.

But as Rishi said, there was some work done that time, so probably some situatations which aren't suppose to happen appeared.

**Comment by maxceem** [comment]
@RishiRajSahu I'm facing this error again right now in the browser I was actively working with.

![image](https://user-images.githubusercontent.com/146016/46078262-37e15600-c1c6-11e8-9cc4-e4f0b2466c36.png)

**Comment by maxceem** [comment]
The same time I was logged in another browser using another user, but this error didn't happen to me there. So looks like it's not caused by otter changes. 

Maybe as @vikasrohit suggested, token is not refreshed in some reason or refreshing causes such error.

**Comment by maxceem** [comment]
What I found out so far:
- Error happens in `decodeToken` function:
   
    ![image](https://user-images.githubusercontent.com/146016/46185021-d5de3900-c30a-11e8-9586-f855d25b5a35.png)

- It appears that the token is set to `undefined` string in some reason. So code thinks it has a token and tries to decode it but actually it doesn't.

   ![image](https://user-images.githubusercontent.com/146016/46185088-16d64d80-c30b-11e8-8a05-b6bbf572d0c6.png)

   ![image](https://user-images.githubusercontent.com/146016/46185111-32d9ef00-c30b-11e8-8a50-13e9fd6de1d7.png)

- This most likely happens inside [accounts-app](https://github.com/appirio-tech/accounts-app) as `connect-app` doesn't set coockies by itself

So far strange that only me and probably only one more guy come accross with this issue. Though this issues happens to me in two browsers Chrome and FireFox.

**Comment by maxceem** [comment]
I see two ways to solve it:
1. Try to find out why token can become `undefined` and fix it. But it can be hard to find out as code is deployed as a separate application and it could be hard to test it locally I guess.
2. Adjust code of `accounts-app` so in case of invalid token it treats user as `non-logged-in` and shows login form. As now, the only way to login back is to clear coockies. Solving this without first one will cause user to be regularly `non-logged-in` which is also not good.

**Comment by vikasrohit** [comment]
@maxceem I think @gondzo is also facing the similar issues in this release. We need to find the root cause asap.

**Comment by maxceem** [comment]
@vikasrohit is it possible to get information regarding which version of `accounts-app` is deployed for DEV and PROD environments?

![image](https://user-images.githubusercontent.com/146016/46190695-2fecf780-c327-11e8-8bd9-32d9c66a2889.png)

**Comment by gondzo** [comment]
@maxceem feature/login flow is on dev now
Master is on prod

**Comment by maxceem** [comment]
Ok, I see there were some changes done to login flow in `accounts-app` so I guess I'm leaving this issue for @gondzo as he is aware of the context of the changes.

Or let me know if you'd like me to reach to the winner of the challenge https://www.topcoder.com/challenges/30070946?tab=details who made the majority of the changes.

**Comment by gondzo** [comment]
I've reviewed the changes made there and didn't find anything that could cause this. There are no changes to connector iframe. Here is the PR to dev -> https://github.com/appirio-tech/accounts-app/pull/196

**Comment by maxceem** [comment]
I went thtough that PR and also cannot see anything which can cause such issue. Hmm...

**Comment by gondzo** [comment]
maybe identity api issue? If you manage to reproduce it again, can you check the last response from https://api.topcoder-dev.com/v3/authorizations/1

**Comment by maxceem** [comment]
Got it.

Before `Uncaught Error: The token is invalid` there is a request failed with 401:
```
GET https://api.topcoder-dev.com/v3/authorizations/1
```
response:
```
{
  "id": "1daf3e10:1663366004f:-4ef0",
  "result": {
    "success": true,
    "status": 401,
    "metadata": null,
    "content": "Unauthorized"
  },
  "version": "v3"
}
```

So the whole process looks like this:
- we call `getFreshToken` https://github.com/appirio-tech/accounts-app/blob/e6b3e3aa3775c5e13683e2ccbdb768bf3a9ade37/core/auth.js#L88
- if token is expired it calls `refreshToken` https://github.com/appirio-tech/accounts-app/blob/e6b3e3aa3775c5e13683e2ccbdb768bf3a9ade37/core/auth.js#L248
- `refreshToken` calls `fetchJSON` with url `https://api.topcoder-dev.com/v3/authorizations/1` https://github.com/appirio-tech/accounts-app/blob/e6b3e3aa3775c5e13683e2ccbdb768bf3a9ade37/core/auth.js#L22
- `fetchJSON` gets error `401` bet since recent PR we treat such requests as successful https://github.com/appirio-tech/accounts-app/blob/e6b3e3aa3775c5e13683e2ccbdb768bf3a9ade37/core/auth.js#L43-L45

The solution for this particular issue would be to remove these lines https://github.com/appirio-tech/accounts-app/blob/e6b3e3aa3775c5e13683e2ccbdb768bf3a9ade37/core/auth.js#L43-L45 

Though I guess they were added to handle some other case which may be got broken if we just remove them.
I may contact the participant who added these lines to ask him to refactor it so it sill handles his case but doesn't touch another cases as `fetchJSON` is used by many other methods.
Or maybe @gondzo may help with some input for which situation we may need these lines.

**Comment by vikasrohit** [comment]
Great!! Very good catch. I don't think those lines should be there for any
use case. It seems like it is left over of local testing by the winner of
the challenge.
@gondzo still want to make sure if really need those lines at all.

@mtwomey fyi

**Comment by maxceem** [comment]
@vikasrohit I've checked your commits for this issue https://github.com/appirio-tech/accounts-app/commit/11254bb7a0172fac4df2fc724c3c791e637e15b2

I think all the 3 lines have to be removed as the whole change which was done during work on that feature is the next:
https://github.com/appirio-tech/accounts-app/pull/196/files#diff-4b785ed24c4ee6da77c088d63be9e6fdR43
Otherwise the error will still happen as error response still sutisfies the condition:
```
{
  "id": "1daf3e10:1663366004f:-4ef0",
  "result": {
    "success": true,
    "status": 401,
    "metadata": null,
    "content": "Unauthorized"
  },
  "version": "v3"
}
```

Let me know if you'd like me to create hot-fix PRs.

**Comment by vikasrohit** [comment]
Ohk, Thanks. I have made the changes. 👍

**Comment by maxceem** [comment]
To keep track, here is a comment from **diazz** who made the changes regarding the `loginFlow` and 3 lines:
> this is require for updating user info after signup successfully (edited)
because user don't have permission for getting user info, so the result will have status 401 but it's success
i think i can handle the error at updateUserInfo function
but it need time for debugging
you can remove the
if (json.result.success && json.result.status === 401) {
             return json
           }
then catch the error in function updateUserInfo  in auth.js
if you remove these 3 lines without catch the error in updateUserInfo , the signup flow will fail and stop at signup step

And here is a comment from **vikasrohit** regarding participant reponse:
> I don’t think update user info would now return 401 even after success
it seems like he made these changes when there was some validation errors in the target api which got fixed later on.
> Let me try the new flow after the fix

**Comment by vikasrohit** [comment]
@mtwomey We have already applied this patch to the production couple of days ago.

**Comment by maxceem** [comment]
This was fixed a few months ago and there were no regressions since than, so I think it's safe to close it now.
