### ISSUE TITLE
No confirmation when deleting the files

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#255]
Description
-----------------------------------------------------------------
No confirmation when deleting the files

Expected Result(s)
-----------------------------------------------------------------
- Must have a confirmation message before deleting

Actual Result
-----------------------------------------------------------------
- No confirmation when deleting the files

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name
- Click 'Specification'
- In 'App Definition'
- Fill all the required details
- Upload 2-3 documents
- Click DELETE

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by sdgun** [comment]
![2016-09-29_5-53-25](https://cloud.githubusercontent.com/assets/4592712/18937081/91d05d5e-860a-11e6-863a-b1bfc901c356.png)

**Comment by fnisen** [comment]
Yes, let's fix this.

**Comment by vikasrohit** [comment]
Fixed with #468
