### ISSUE TITLE
Newly Added phase is not correctly setting startDate when all the remaining phase are active

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2554]
![screen shot 2018-09-27 at 2 39 57 pm](https://user-images.githubusercontent.com/11248478/46135838-c48e2180-c263-11e8-9a14-49c30393fec9.png)

Newly Added phase should have startDate as 1 day more than the latest endDate of all the phases present on the project plan page irrespective of status. But right now when  all the remaining phases are active new phase is not honouring latest endDate to set its startDate.

**Comment by maxceem** [comment]
I think this one has the same reason as https://github.com/appirio-tech/connect-app/issues/2477 so they have to be handled together.

**Comment by RishiRajSahu** [comment]
working fine on dev. closing
