### ISSUE TITLE
[$30] When we edit milestone but didn't make any changes, "Update milestone" button has to be disabled.

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2555]
### Expected behavior
When we edit a milestone but didn't make any changes, `Update milestone` button has to be disabled.

### Actual behavior
Now when we just click edit button and open edit form, we already can click `Update milestone` even without making any changes.

![image](https://user-images.githubusercontent.com/146016/46189947-ebac2800-c323-11e8-93e8-5cd8077561c2.png)

@RishiRajSahu if it's a desired fix, I think we can include it to next CF.

**Comment by afrisalyp** [comment]
Hi @maxceem, Can you please assign this ticket to me?
Thanks.

**Comment by maxceem** [comment]
Done

**Comment by afrisalyp** [comment]
Hi maxceem,
It’s done and ready for review
Here is the PR https://github.com/appirio-tech/connect-app/pull/2762

Please review. Thanks.

**Comment by maxceem** [comment]
Hi @afrisalyp I've checked you PR, please have a look https://github.com/appirio-tech/connect-app/pull/2762#pullrequestreview-195870471

**Comment by afrisalyp** [comment]
@maxceem Thanks for the review, I'll check the comments.

**Comment by RishiRajSahu** [comment]
Working fine on dev.
