### ISSUE TITLE
Copy `Submit for Review` button to the dashboard

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2559]
As follow up for #2417 we are going to copy the button at dashboard as well, to allow them quickly submit the project.
@vic-topcoder Could you please let us know a better place in the dashboard for the button?

**NOTE:** @vic-topcoder  @acshields  Implementing this would have side effect in future when we add more questions, which we don't ask on project creation form, to the project scope section. In that case, the button which resides in `Scope` tab, will not be enabled until the required questions are answered while the button at this new position would always be enabled, no matter if all required questions are filled or not. We can definitely remove this button from dashboard at that time, however, personally I am not in favour of moving UI elements, which are critical part of the overall flow, around in every release as it breaks the tutorial docs/videos and has potential of loop holes just like I described above.

cc: @RishiRajSahu

**Comment by vic-topcoder** [comment]
The button should be part of the "Files" module. Either strategy is ok with me - reuse current style from scope tab, but scaled down to fit the sidebar, or a button:

**Comment by vic-topcoder** [comment]
@acshields - FYI

I think to get this out of the door we can start with the simple button (use the XS size), and it would trigger current Filestack experience

**Comment by vikasrohit** [comment]
Just for the sake of doing it right in first attempt, @vic-topcoder could you please share a quick mock for this? There are different possibilities in placing the button in description section itself.

**Comment by vic-topcoder** [comment]
@acshields We have to modify the language to really guide the users, but the layout should be something like this:
![screen shot 2018-10-04 at 7 33 59 am](https://user-images.githubusercontent.com/8484061/46481291-ec234380-c7a7-11e8-8be2-097aa9bc3acc.png)

**Comment by vikasrohit** [comment]
@acshields Can we have the updated language as well please? I would like to cover both changes in single attempt.

**Comment by vikasrohit** [comment]
Thanks @acshields

**Comment by RishiRajSahu** [comment]
@vic-topcoder displaying the updated text for coder-bot message looks good but if we use the same text for right panel above the submit button it will be too verbose and doesn't give UX, how do you suggest to handle it ?

<img width="1439" alt="screen shot 2018-10-15 at 5 43 51 pm" src="https://user-images.githubusercontent.com/11248478/46950494-75891e80-d0a2-11e8-9de9-4896c6467620.png">

**Comment by vic-topcoder** [comment]
I would hide the project description until the customer submits the project for review. This would give them enough information on the project status and later once submitted we'll display the project description back. @acshields FYI

**Comment by RishiRajSahu** [comment]
@vic-topcoder thanks !
So to accomplish this we have to make below changes -
- [ ] Making changes on frontend(both desktop and mobile)
- [ ] Making changes for the coder-bot message appears for the newly created draft project

**Comment by maxceem** [comment]
@RishiRajSahu I've done with `Submit for Review` button, see PR https://github.com/appirio-tech/connect-app/pull/2640

I'm not sure what should be done for the second part `Making changes for the coder-bot message appears for the newly created draft project`.

**Comment by RishiRajSahu** [comment]
@maxceem could you add a image/video how it is looking ?

**Comment by RishiRajSahu** [comment]
Backend changes done via https://github.com/topcoder-platform/tc-connect-notifications/commit/badbd8c60d38ca5810879b8299b49ae405e9f121

**Comment by maxceem** [comment]
@RishiRajSahu 
- desktop https://monosnap.com/file/Whr9hJP1xI59mxIbeYfmFESVy18cEq
- mobile https://monosnap.com/file/w3EEIXZ8bwRWMuA3Dp8gtOsgVGCzVL

**Comment by RishiRajSahu** [comment]
Working fine on dev. Verified.
