### ISSUE TITLE
[$80] Host the new email template images in Connect app instead of third party

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2560]
Right now we are using third party to host couple of images used in the new email template of connect notifications. We should move them to connect-app itself as soon as possible.

fyi @gondzo @RishiRajSahu

**Comment by vikasrohit** [comment]
@gondzo could you please take care of it? We can include this change in upcoming release.

**Comment by vikasrohit** [comment]
@maxceem Would you like to include this one in next bug bash?

**Comment by maxceem** [comment]
Sure.

**Comment by maxceem** [comment]
Work here should be done in two repositories:

1. Inside repository https://github.com/topcoder-platform/tc-notifications we should check all the email templates inside folder https://github.com/topcoder-platform/tc-notifications/tree/dev/emails/src/partials and find all the images which are hosted on the third-party places. I found only one image myself `comment.jpg` which is used in multiple templates. But maybe there are others.
   
    We should put this image to the Connect App, and replace URL inside templates to the correct URL inside Connect App. Note, that inside email templates we should use variable `{{@root.connectURL}}` for Connect App domain.

   Create a PR against `dev` branch to `tc-notifcations` repo.

2. The second part should be done in Connect App.
Currently in the Connect app when we build the app, to the `dist` folder we put only files which are referenced somewhere in the app. So if we don't use images which we use in email templates, they wouldn't be included to the build.

To overcome this, we should: 
- create folder `srs/static` and put all the images from email templates there. 
- update webpack config for the Connect app, so it would copy all the files from the `src/static` to the `dist/static`. After we can refer all these files from `tc-notifications` by URL like `{{@root.connectURL}}/static`
- Note, that Connect App uses webpack config from `topcoder-react-utils` and after it updates it inside files in `config/webpack/...`. I think the best place to put it, would be `config/webpack/common.js` or `config/webpack/common-modifications.js`.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by akumar1503** [comment]
@maxceem can you assign this to me.
Thanks.

**Comment by maxceem** [comment]
sure, it's on you since you've commented

**Comment by akumar1503** [comment]
@maxceem i have tested that the files are being generated in dist/static, in connect-app. 

For test in tc-notifications, can you please provide some workflow how that can be tested?

**Comment by maxceem** [comment]
@akumar1503 thanks for testing on the connect.
I think we don't have a way to test it on `tc-notifications` service other than deploying these templates to `sendgrid `. The changes you've done to the templates look good to me. Important thing is to make sure that only one image there has to be served and there are no other images. 
In case the URL has some typos we can fix it after we deploy them and test by ourself.

**Comment by akumar1503** [comment]
@maxceem thanks. 

Just to be sure, there is an img in [template.html](https://github.com/topcoder-platform/tc-notifications/blob/dev/emails/src/template.html) using third party url, do i need to update this, it's not in partials folders as you mentioned.

**Comment by maxceem** [comment]
Great catch @akumar1503, this file also shouldn't use third-party images. As this is a common template where we insert partials from `src/partials` folder.

**Comment by akumar1503** [comment]
I have updated both the PR's, please review.

**Comment by vikasrohit** [comment]
Verified, working fine.
