### ISSUE TITLE
[$40] Sometimes notification dropdown is not opened on click

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2567]
Sometimes when clicking the notification bell icon on the right top corner, notification dropdown is not open and it looks like this:

![image](https://user-images.githubusercontent.com/146016/46294511-8c227680-c5c8-11e8-86a6-6cb407136154.png)

It looks like it can happen every second time, one click opens notifications drop-down, another click doesn't open it, see demo video https://monosnap.com/file/PZzZ0p1vOv6QWQwUNxe194xGQGMof9

Note: It can be reproduced on production.

fyi @RishiRajSahu

**Comment by RishiRajSahu** [comment]
@maxceem yeah but that only happened for me in the case when i had inspect tool opened or closed it just after inspecting some div , otherwise wasn't able to reproduce. could you refresh the page then try reproducing it ?

**Comment by maxceem** [comment]
@RishiRajSahu yes, for this project now I can always reproduce it https://connect.topcoder.com/projects/3981

- Open project in a new tab
- Dev tools are closed
- One click on the bell opens drop-down normally
- I click aside to close it
- Another click doesn't open it, same like shown in the video

**Comment by jankyzhang** [comment]
@maxceem 
please assign this to me!

**Comment by maxceem** [comment]
@jankyzhang it's on you.

To let me assign you for clearance, please, accept the invitation to this repo, which has to come to your email.
Thanks.

**Comment by jankyzhang** [comment]
@maxceem It’s done and ready for review
There are two "Pull request" for this bug.
One for appirio-tech/connect-app.
One for appirio-tech/react-components.
Thanks.

**Comment by maxceem** [comment]
@jankyzhang I've checked the PRs, please have a look https://github.com/appirio-tech/connect-app/pull/2601#pullrequestreview-164483846

**Comment by jankyzhang** [comment]
@maxceem ,
I have fixed it.
Please check.

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
