### ISSUE TITLE
[$20] Avatars in user tooltips are not loaded

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2568]
Avatars in user tooltips are not loaded, even though users have avatar defined:

![image](https://user-images.githubusercontent.com/146016/46295714-5337d100-c5cb-11e8-9bcc-d5f3f440259b.png)

In the browser console I see:

![image](https://user-images.githubusercontent.com/146016/46295737-621e8380-c5cb-11e8-9a75-a565e4ec06cb.png)

So looks like size is not defined for these avatar URLs.

fyi @RishiRajSahu

**Comment by vikasrohit** [comment]
Related issue https://github.com/appirio-tech/connect-app/issues/2576

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by maxceem** [comment]
@PrakashDurlabhji it's been almost two days since your PR was reviewed and feedback provided. Please let me know if you are willing to fix issues found during review or issue will be reopened for pick up.
Thanks.

**Comment by PrakashDurlabhji** [comment]
@maxceem yes i am willing to fix it. apology for delay. will fix it immediately.

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
