### ISSUE TITLE
[Specification] - the same image for different types of files uploaded

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#257]
Expected behavior

 - The image must be different.

Actual behavior

- The same image icon displayed (GZIP) for any types of file.

Steps to reproduce the problem

- Login into application as manager.

- Go to Dashboard.

- Edit any existing project.

- Go to Specification tab section.

- Go to Project Files (2) and upload a files: png, pdf, xls, ...

Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: pat_monahan

see attach!

![gzip](https://cloud.githubusercontent.com/assets/5114907/18931746/1fa3ad14-85d6-11e6-9357-1dfed246c32c.png)

**Comment by parthshah** [comment]
@vikasrohit assigning this to you. Could we use some sort of react svg loader to load svgs through require('') ?

**Comment by vikasrohit** [comment]
@parthshah I have committed the changes, please review the [PR](https://github.com/appirio-tech/connect-app/pull/460).

**Comment by fnisen** [comment]
Fixed with https://github.com/appirio-tech/connect-app/pull/460
