### ISSUE TITLE
Product brochures

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2572]
In the new project creation wizard design we have a link to product brochures. It is removed for now as we don't yet have the actual pdfs. 

![image](https://user-images.githubusercontent.com/3051646/46318747-d52df700-c5d7-11e8-86f0-fac526f1660d.png)

@vic-topcoder @acshields do we have plans for creating the brochures?

**Comment by acshields** [comment]
@vic-topcoder - I am connecting with Marketing on this rn and will get back soon.

**Comment by acshields** [comment]
I chatted with Marketing and they would prefer if the link lead to case studies: https://www.topcoder.com/about/customer-stories/

The language should ready: "Learn more about Topcoder's impact helping our customers achieve amazing results."

**Comment by vikasrohit** [comment]
@acshields I am not sure if customer stories are good here because these links should ideally change when user change the category from the options and intent is to show a guide or brochure of that particular product and if change the link to customer stories, it would link always to the same page for every offering. In such case, these customer stories should be linked out side of offering specific section. This is what I understand being a user, however, if marketing prefers that, we are okay with that.

**Comment by maxceem** [comment]
@RishiRajSahu as per new form design https://marvelapp.com/6a8ch8h/screen/52602222 we don't have the right side panel during project creation anymore. So there is no place for link.

**Comment by vikasrohit** [comment]
@maxceem we need to show this for non registered users, I guess. We are still showing the right section for them.

**Comment by maxceem** [comment]
@vikasrohit looks like we are already showing the correct link there:

![image](https://user-images.githubusercontent.com/146016/53325501-6f436280-391e-11e9-921f-e361851c244b.png)

The only issue - we cannot click it as it's overlayed by another block.

**Comment by RishiRajSahu** [comment]
@maxceem the link you mentioned is customer stories on registration form, we definitely needs to fix that to be clickable. Coming to the product brochures links, I think we don't need that support as per new designs as brochure links are suppose to be present aside the project form, right @vikasrohit ?

**Comment by RishiRajSahu** [comment]
@vikasrohit closing it as actual title of issue is not in scope anymore, however the issue mentioned about the link being made clickable is fixed.
