### ISSUE TITLE
[$50] Disable multiple actions possible while adding a link on a milestone

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2574]
### Expected behavior
While the manager is adding a link to a milestone, no other controls are visible/can be used, to reduce the possibility of an error.

### Actual behavior
All controls are available during adding a link (design checkpoint). In particular the Milestone controls "mark as completed" "request an extension" should be hidden while adding a link is active.
![screen shot 2018-10-02 at 4 21 14 pm](https://user-images.githubusercontent.com/8484061/46382305-65634f00-c65f-11e8-8259-a979fc6437e1.png)

**Comment by acshields** [comment]
@vic-topcoder - agreed with design choice.

**Comment by vikasrohit** [comment]
@maxceem I think requirements are clear and we can include in this our next CF challenge.

**Comment by vikasrohit** [comment]
@maxceem Great documentation there in Wiki.

Could we keep the blue line as is until `Add Link` is clicked and when the button is clicked, show the blue line till the `Add Link` and `Cancel` buttons. I think there would be a jump in any case because we are showing two/three new text boxes in the milestone when adding link.

**Comment by maxceem** [comment]
> Could we keep the blue line as is until Add Link is clicked and when the button is clicked, show the blue line till the Add Link and Cancel buttons.

@vikasrohit with our current implementation of blue line it would be a little bit hacky but we can do that.

Currently, we only can put a blue point at the center of some component. As a component for adding links `LinkList` is one component together with buttons `Add Link` and `Cancel` this will currently look like this:

![blue-line-ex](https://user-images.githubusercontent.com/146016/46529300-9eeac300-c8c8-11e8-9f8f-ee2514627a3d.png)

To achieve axactly as you asked we will have to add some property to `LinkList` to show blue point in front of buttons, which feels like not the `LinkList` component responsibility, but still ok for now I think.

**Comment by vikasrohit** [comment]
Ohk, I guess I was overthinking. I would delegate it to @vic-topcoder as usual to get design decisions.

**Comment by vic-topcoder** [comment]
Please do not change the design at this point.

**Comment by maxceem** [comment]
@vic-topcoder the main question here is where should blue line point when we hide **Mark as Completed** and **Request extension** buttons, as by default blue line points at them:

`MilestoneTypePhaseSpecification`:
![image](https://user-images.githubusercontent.com/146016/46458054-16e0bc80-c7e7-11e8-8428-d72766bc5893.png)

`MilestoneTypeProgress`:
![image](https://user-images.githubusercontent.com/146016/46458112-44c60100-c7e7-11e8-8c61-6c7b4a5304a2.png)

You may check this https://github.com/appirio-tech/connect-app/issues/2574#issuecomment-426912901 for details.

**Comment by vikasrohit** [comment]
@maxceem I think what @vic-topcoder is trying to say is that just keep it as per current understanding i.e. keep it till the middle of the component. In this case, because now the button section would be hidden, I think blue line would go till mid of the `Add Link` form component.

**Comment by maxceem** [comment]
To sum up:

- We have to hide buttons like `Mark as completed`, `Complete` and `Request Extension` when we are in the process of adding some links.
   Example with `MilestoneTypePhaseSpecification`
   - All the buttons are shown intially:
      ![image](https://user-images.githubusercontent.com/146016/46848965-6a728c00-ce1f-11e8-99b9-c9aceeaffcaf.png)
    - We clicked `Add specification` button:
       ![add-link](https://user-images.githubusercontent.com/146016/46849016-b9202600-ce1f-11e8-8604-4eb1ae92110f.png)
       - `Mark as completed` and `Request Extensions` button has to become hidden together with the blue backgound **as long as link adding/editing form is open**.
       - Blue line has to point to the gray block with adding links form.
  - When link is added we have to see all the buttons again, with the blue line point to the blue block again:
     ![image](https://user-images.githubusercontent.com/146016/46849057-0bf9dd80-ce20-11e8-9f91-e96c32dd4f22.png)
- The list of components which has to be updated:
   - `MilestoneTypePhaseSpecification`
   - `MilestoneTypeProgress`
   - `MilestoneTypeAddLinks`
   - `MilestoneTypeFinalFixes`
   To find out how to see them in real life, use this [guide](https://github.com/appirio-tech/connect-app/wiki/Milestones)
- To control blue line behavior we SHOULDN'T use CSS. Instead we have to reuse https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/timeline/DotIndicator/DotIndicator.jsx component.

**Comment by Gauravseta** [comment]
@maxceem will this be open for pickup? then can u pls assign to me if possible in future?

**Comment by maxceem** [comment]
@Gauravseta yes, it's going to be open for pick up soon. But as we've previously discussed we cannot allow participants to `book` issues. So as soon as it's open for pick the one who first claims it, will get it.
Thanks.

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by Gauravseta** [comment]
@maxceem pls give to me

**Comment by Gauravseta** [comment]
@maxceem actively working on it.i hope i will be given some extra time as its somewhat difficult.

**Comment by Gauravseta** [comment]
@maxceem i am done with MilestoneTypePhaseSpecification functionality.
now completing remaining 3

**Comment by Gauravseta** [comment]
@maxceem PR ready #2627

**Comment by maxceem** [comment]
@Gauravseta I've checked the PR, works good, just a couple of minor things before I can merge it https://github.com/appirio-tech/connect-app/pull/2627#pullrequestreview-165001815

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
