### ISSUE TITLE
[$30] Restore Coder the Bot avatar

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2576]
>Restore Coder the Bot avatar. It's gone missing somehow.

continued from https://github.com/appirio-tech/connect-app/issues/2301

**Comment by maxceem** [comment]
Looks same as https://github.com/appirio-tech/connect-app/issues/2569 so we can close one these.

**Comment by amitpatra** [comment]
I would like to pick up this.

**Comment by maxceem** [comment]
As the issue hasn't been completed during 12 hours and no comment was provided, this issue is now open for pick up.

**Comment by sumitdaga** [comment]
@maxceem 
ohk, how i found this url was because the `GET` request with this url was showing an error in the console
may it will help!

**Comment by maxceem** [comment]
@sumitdaga yeah, here are details https://github.com/appirio-tech/connect-app/issues/2569 . I remember that somehow image from connect-app end up in CDN, but I cannot recall the whole system right now.

**Comment by RishiRajSahu** [comment]
closing as merged to dev.
