### ISSUE TITLE
[$20] Checkboxes are not using the standard border

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2578]
![screen shot 2018-10-03 at 4 33 27 pm](https://user-images.githubusercontent.com/11248478/46406718-19c9a780-c72a-11e8-8f6c-49762e542d77.png)

continued from https://github.com/appirio-tech/connect-app/issues/2301

**Comment by maxceem** [comment]
@vic-topcoder could you please clarify here what is the exact mismatch which has to be fixed.

I've compared implementation with marverl design https://marvelapp.com/8a94680/screen/41372918/handoff
- unselected checkboxes looks like complitely match design
- selected checkboxes has one difference: checkboxes in design doesn't have any border, so blue color continues instead of border. While in implementation we have border for the selected checkboxes. Is this what has to be fixed here?
   
    ![image](https://user-images.githubusercontent.com/146016/46454040-01639680-c7d7-11e8-8253-13f36b48bb68.png)

     Left - implementations, Right - design.

**Comment by vic-topcoder** [comment]
Checkbox border when selected - we should use $tc-dark-blue-110, not silver (screenshot below) design vs. implementation:
![screen shot 2018-10-04 at 6 52 25 am](https://user-images.githubusercontent.com/8484061/46478689-5f29bb80-c7a2-11e8-881f-ffd026197e94.png)
![screen shot 2018-10-04 at 6 53 56 am](https://user-images.githubusercontent.com/8484061/46478691-605ae880-c7a2-11e8-917e-0c92b4aea971.png)

**Comment by PrakashDurlabhji** [comment]
@maxceem can u please assign to me thanks

**Comment by PrakashDurlabhji** [comment]
@maxceem PR raised #2599

**Comment by maxceem** [comment]
@PrakashDurlabhji PR is reviewed, please have a look https://github.com/appirio-tech/connect-app/pull/2599#pullrequestreview-164482243

**Comment by maxceem** [comment]
@PrakashDurlabhji it's been two days since your PR was reviewd and feedback provided. Please let me know if you are willing to fix issues found during review or issue will be reopened for pick up.
Thanks.

**Comment by nahidshahin** [comment]
@maxceem can I try to fix it if @PrakashDurlabhji doesn't?

**Comment by maxceem** [comment]
@nahidshahin as per our Bug Bash rules it's not allowed to claim issues before they are open for pick up or asked to be unassigned by the user, see https://www.topcoder.com/challenges/30072435 

![image](https://user-images.githubusercontent.com/146016/47061676-1abc0800-d205-11e8-85c6-c357db32e7cc.png)

As Bug Bash submission is already finished, I think this issue will be left unresolved if participant doesn't accomplish it.

**Comment by PrakashDurlabhji** [comment]
@maxceem PR updated. it shud be as expected.working on other Pr now

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
