### ISSUE TITLE
[Specification] - the text area can be horizontally resized

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#258]
Expected behavior
- The textarea must not be able to be resized horizontally.

Actual behavior
- The textarea can be resized horizontally.

Steps to reproduce the problem
- Login into application as manager.
- Edit any existing project eg. test.
- Go to Specification tab section.
- Try to resize the "Who are the users of your application?" textarea moving to the RIGHT.

Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: pat_monahan

![resize](https://cloud.githubusercontent.com/assets/5114907/18931879/bb6f7dc2-85d6-11e6-9285-0839bda6452f.png)

**Comment by vic-appirio** [comment]
disable horizontal resize of text-area.

**Comment by fnisen** [comment]
@vic-appirio could we also have the text areas auto-expand when they're full?

**Comment by vic-appirio** [comment]
Auto-expand is not a CSS feature. It is controlled with JavaScript; we'll need an engineering task/new feature request.

**Comment by fnisen** [comment]
OK, got it, thanks.

**Comment by vic-appirio** [comment]
Fixed, pending merge
