### ISSUE TITLE
[$20] Adding link for final fixes button text is different in states.

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2580]
the button text changes during different states. It should stay the same:
"Add link" becomes "Add a link".

![complete2](https://user-images.githubusercontent.com/11248478/46454195-a9229980-c7c2-11e8-8027-16094b06775b.png)
![complete](https://user-images.githubusercontent.com/11248478/46454207-b049a780-c7c2-11e8-838a-d9b34889a2d1.png)

continued from https://github.com/appirio-tech/connect-app/issues/2301

**Comment by maxceem** [comment]
@vic-topcoder is there any other cases where would you like to apply the same approach:

1. `Add specification` !== `Add link`:
   
    ![image](https://user-images.githubusercontent.com/146016/46530322-f5a5cc00-c8cb-11e8-80b4-8e0e6f64c273.png)

    ![image](https://user-images.githubusercontent.com/146016/46530335-fdfe0700-c8cb-11e8-93ab-da4034b462d1.png)

2. `Add a desgin link` !== `Add a link`:
     
     ![image](https://user-images.githubusercontent.com/146016/46530399-2e45a580-c8cc-11e8-99c8-1fa4c856d708.png)

      ![image](https://user-images.githubusercontent.com/146016/46530414-3867a400-c8cc-11e8-9ba0-69d08f8f44e3.png)

**Comment by vic-topcoder** [comment]
Correct - the label of the button should be consistent:

"Add specification link", "Add design link" as call to action (first instance, open interface to add link). Title of modal is the same as button label:

"Add specification link", or "Add design link"
buttons: "Cancel",  "Add link"

**Comment by Gauravseta** [comment]
@maxceem pls assign to me

**Comment by Gauravseta** [comment]
@maxceem PR done #2596

**Comment by maxceem** [comment]
@Gauravseta I've checked the PR, please, have a loook https://github.com/appirio-tech/connect-app/pull/2596#pullrequestreview-164481811

**Comment by RishiRajSahu** [comment]
Closing merged to dev.
