### ISSUE TITLE
`View post on Connect` in email notification leads to the dashboard instead of project plan

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2604]
### Expected behavior
When I get a notification about post under one of the phases on the project plan and click `View post on Connect` it has to open project on project plan tab with a certain phase opened on the `Discussion` tab to show the post.

### Actual behavior
When I get a notification about post under one the phases on the project plan and click `View post on Connect` it opens dashboard tab.

![image](https://user-images.githubusercontent.com/146016/46783550-46e70d00-cd5d-11e8-9416-3046c5f2a836.png)

- On the screen above there is a post which was made on the `Discussions` tab of one the phases, but the link to the post `https://connect.topcoder.com/projects/7306#feed-27895` will redirect to the dashboard tab.

**Comment by maxceem** [comment]
@RishiRajSahu it looks like these URLs are generated not in notification service but in some service which sends emails, but I cannot find out which service does it. Looks like it's `tc-email-service` but I don't see templates there which actually build these emails. Could you, please, help me with this?

**Comment by RishiRajSahu** [comment]
@maxceem I think you are looking for this https://github.com/topcoder-platform/tc-notifications/tree/dev/emails/src/partials

**Comment by maxceem** [comment]
@RishiRajSahu I've noticed that there could be one more case which we could want to fix.

We get email notifications about posts in 3 cases:
1. notification about TOPIC on the dashboard
2. notification about POST (comment) on the dashboard
3. notification about POST (comment) on the phase

So far we always send a link to the TOPIC on the dashboard (case 1).
In this issue, we have to fix it and send a correct link to the POSTs on the phase (case 3).
Should we also update the logic and send a link to the particular post instead of the topic in case 2?

**Comment by RishiRajSahu** [comment]
@maxceem yes if we could easily achieve a redirect to post instead of topic that would be great, if not let's leave a redirect to topic/discussions tab only. I remember we faced issues during redirect earlier as we are showing the link to topics in the left bar also.

**Comment by vikasrohit** [comment]
Tested after release deployment on production, working fine.
