### ISSUE TITLE
Phase header jumps when we open edit form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2606]
1. When we click the edit button on some phase to open edit form, the phase header jumps, which feels not nice and could give an impression of glitchy behavior. Note, when we expand phase, header doesn't jump as it has to be. See screencast https://monosnap.com/file/DAKDfLDd68PTmD7WpJvsUncbtQJNJZ

2. When we open edit form phase header and edit form are separated with the wide white area
    
     ![image](https://user-images.githubusercontent.com/146016/46788501-cfb97500-cd6c-11e8-806a-3e3bf8e73224.png)

     While if we expand phase, the header is separated from content with a thin gray line

     ![image](https://user-images.githubusercontent.com/146016/46788581-01cad700-cd6d-11e8-8872-bcc9923d07bf.png)

     - It feels like for edit form we either have to separate header with a thin gray line, same like when we expand pahse.
     - Or we show edit form together with the phase header without any separation.

@vic-topcoder could you provide your view here?

**Comment by vic-topcoder** [comment]
I would put this issue on hold. We're currently going through the second iteration of the phase timeline and editing interface, so this is not crucial for the performance - only managers and copilots use the editing feature, rarely.

With the next iteration editing should happen outside of the header, on the card itself. We are aiming to simplify the phase interactions and focus on a singular experience at a time. The cards would have to support different views for different user roles, but the end result should be a simplified card. Expanding and collapsing the card is the only interaction that actually matters at this point.


Preview of the mock designs:
![screen shot 2018-10-11 at 6 04 04 am](https://user-images.githubusercontent.com/8484061/46806063-7ffe8d80-cd1b-11e8-98bc-b2e5b632789b.png)

**Comment by maxceem** [comment]
Thanks for your input on our future plan!
As we are actually not going to fix this issue, as it would be solved another way, I'm closing it to reduce the number of opened issues for easy navigation.

Please, feel free to reopen it, if there is still something we have here later.
