### ISSUE TITLE
When we edit phase titles, respective topic tiles are not updated in the sidebar

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2609]
- [x] If we rename phase title, the respective topic which is associated with this phase and is listed on the sidebar is not renamed accordingly.

![phase-topics](https://user-images.githubusercontent.com/146016/46798064-6abd4980-cd83-11e8-80a9-ee1b2be64049.png)

- [x] Specifications title is also not following the consistency

![screen shot 2018-10-12 at 12 37 39 pm](https://user-images.githubusercontent.com/11248478/46853931-1f577980-ce1d-11e8-9de0-90f20ea0c9c0.png)

fyi @RishiRajSahu

**Comment by RishiRajSahu** [comment]
@maxceem added one more action item to the list.

**Comment by RishiRajSahu** [comment]
@vic-topcoder can we hide the title we are showing under the `Specification` tab for a phase or is it required ?

**Comment by vic-topcoder** [comment]
Yeah - specification topics should not be there. We are not yet showing specifications to customers and that section will change drastically, so let's just do the minimal required changes - do not spend time polishing the current specification interface.

@acshields FYI

**Comment by maxceem** [comment]
@RishiRajSahu as I see when updating the title of the phase the respective topic title is not updated by the backend, so I guess we have to fix there first and after to make sure frontend handles update properly.

**Comment by RishiRajSahu** [comment]
@maxceem agree, for frontend I have made the changes here https://github.com/appirio-tech/connect-app/pull/2635 .

**Comment by vikasrohit** [comment]
Backend changes are also done now, it would change the title of the phase topic when phase is updated, however, it is an async operation so it won't be visible on front end until state update or page refresh. However, considering the front changes done by @RishiRajSahu, we should be good to go.

**Comment by RishiRajSahu** [comment]
merged PR https://github.com/appirio-tech/connect-app/pull/2635 and backend changes done via https://github.com/topcoder-platform/tc-project-service/pull/191.
