### ISSUE TITLE
Remove Timeline Header and description

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2612]
### Expected behavior
![screen shot 2018-10-11 at 5 19 13 pm](https://user-images.githubusercontent.com/11248478/46802179-414bf000-cd7a-11e8-8db2-120129189925.png)

### Actual behavior
Timeline Header and description should not be displayed

**Comment by maxceem** [comment]
@RishiRajSahu So we just hide them visually, but they still stay in the model (backend), correct?

**Comment by RishiRajSahu** [comment]
fyi @maxceem this got reverted somehow, https://github.com/appirio-tech/connect-app/issues/2400.
Hot-fixing it.

**Comment by RishiRajSahu** [comment]
Done with https://github.com/appirio-tech/connect-app/pull/2616
