### ISSUE TITLE
[$40] Notification about project specification has wrong link

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2614]
I've got a notification about the project specification update. It has link to old `Specification` tab  https://connect.topcoder.com/projects/7306/specification in the project which only has new `Scope` tab.

So the link for this case expected to be https://connect.topcoder.com/projects/7306/scope instead.

![image](https://user-images.githubusercontent.com/146016/46802972-8af40500-cd91-11e8-9ad2-651e7a7c0dc2.png)

Note, that for old projects with the `Specification` tab, this link still should stay as `/specification`.

fyi @RishiRajSahu

**Comment by RishiRajSahu** [comment]
@maxceem agree it should be corrected and changes needed too should be straightforward.

**Comment by maxceem** [comment]
@vikasrohit @RishiRajSahu currently I don't get notification about updates on the Scope tab. But I get all other kind of notifications. Do you have any ideas from the top of your head why it could happen like that, before I start digging?

For testing I used for example this project https://connect.topcoder-dev.com/projects/7442 users customer and manager.

**Comment by vikasrohit** [comment]
@maxceem it could be because of couple of reasons:
1. We change the kafka topic name for project spec updates, so we might have missed to update it somewhere in our code OR
2. we are not listening for this notification at all in `tc-notifications` OR
3. we are not parsing this notification in connect app for rendering and similarly we might be missing it to render in email notifications.

**Comment by maxceem** [comment]
@vikasrohit I found the mismatch but not sure with the solution:
- In `tc-project-service` we have two different events:
   - `PROJECT_PRODUCT_SPECIFICATION_MODIFIED: 'connect.action.project.product.update.spec',` - called when we modify spec of particular **phase**'s product
   - `PROJECT_SPECIFICATION_MODIFIED: 'notifications.connect.project.specificationModified'` - called when we modfigy specification of the whole **project**'s product
   - see https://github.com/topcoder-platform/tc-project-service/blob/dev/src/constants.js#L90

- The same time in `tc-notifications` we handle only one of these events `SPECIFICATION_MODIFIED: 'connect.action.project.product.update.spec'` https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/constants.js#L41

As I understand this has to be fixed in `tc-notifications`:
1. `SPECIFICATION_MODIFIED` should be `notifications.connect.project.specificationModified` not `connect.action.project.product.update.spec` as it's related to **project** modification not **phase** product.
2. As we still want to get notification about modifications of **phase** products spec, we have to add this event to `tc-notifications`. There are several questios regarding it:
    - How should we display it in emails? see https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/events-config.js#L221
    - How should we display it in connect-app? see https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js#L350

**Comment by vikasrohit** [comment]
@maxceem `connect.action.project.product.update.spec` is the renamed `notifications.connect.project.specificationModified`, however, I guess ideally it should have been `connect.action.project.updated.spec`. I am fixing it now in all places.

I have update `tc-notifications` and `connect-app` to render `connect.action.project.product.update.spec` appropriately as well. I am using the templates from `notifications.connect.project.phase.update.scope` because essentially we are not going to have phase scope update event because we keep the scope of a phase under product.

So, hope after my all fixes are deployed to dev, you should be getting project and product scope events in your web panel and emails.

**Comment by maxceem** [comment]
Same for all notifications which have `goTo` === `PROJECT_SPECIFICATION`:
- EVENT_TYPE.PROJECT.SUBMITTED_FOR_REVIEW
- EVENT_TYPE.PROJECT.SPECIFICATION_MODIFIED

**Comment by maxceem** [comment]
Notifications come now, so we can proceed with this one.

@RishiRajSahu here is some tricky moment. The link to Scope/Specfication tab depends on the project version.
We list notifcations for many projects, but we don't have data for all these projects so we don't know their version old or new (`v3`). So looks like we cannot render correct link in the notifications list.

What we can do is update link for all notifications to the new project scope page:
`PROJECT_SPECIFICATION: '/projects/{{projectId}}/scope', https://github.com/appirio-tech/connect-app/blob/feature/account-settings-improvements/src/routes/notifications/constants/notifications.js#L16

And on the project details page we can check as soon as project is loaded what is the version. And if version is not `v3` and we try to navigate to `/scope` tab we should redirect to `/specification` tab. Most likely we can do it in https://github.com/appirio-tech/connect-app/blob/feature/account-settings-improvements/src/projects/detail/ProjectDetail.jsx

What do you think?

**Comment by RishiRajSahu** [comment]
@maxceem yeah the approach suggested looks good i.e. identifying the version on load of project and redirecting to respective page.

**Comment by jankyzhang** [comment]
@maxceem i would like to work on this.

**Comment by jankyzhang** [comment]
Hi @maxceem ,

It’s done and ready for review
Here is the PR #2763
Thanks.

**Comment by RishiRajSahu** [comment]
Working fine on Prod.
