### ISSUE TITLE
- Color Picker popup must display properly in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#262]
### Expected behavior
-----------------------------------------------------------------
- Color Picker popup must display properly in IE11

### Actual behavior
-----------------------------------------------------------------
- Color Picker popup is not display properly in IE11

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/345)
- Click 'Specification'
- In 'App Definition'
- Click "Design Specification"
- Click + to add color

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_2-28-56](https://cloud.githubusercontent.com/assets/4592712/18932094/8a67e082-85ec-11e6-8801-5356553a5b44.png)

#### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by vic-appirio** [comment]
Investigate if it is layout issue
