### ISSUE TITLE
New color variables in Connect App

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2632]
During the working on the challenge https://www.topcoder.com/challenges/30072639 based on the new designs https://marvelapp.com/7908ihg/screen/48326788 there were some colors found in designs which are not present in our current SCSS variables list https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss.

There are several things which we have to resolve after challenge finished and we have a list of missing color variables:
1. Get clarifications from Victor what should we do if see some colors in designs which are missing in the variables list.
2. Find all hardcoded colors in connect app which are missed from the list and add them (`connect-app` or `tc-ui`)
3. We already have some variables defined in the connect-app https://github.com/appirio-tech/connect-app/blob/dev/src/styles/_variables.scss. Consider moving them to `tc-ui`.

**Comment by maxceem** [comment]
4. Come with the approach when we have a variable in `connect-app` and after add it `tc-ui`
    First way:
    > 1.I thought of using local variables for Connect for colors which are not present in tc-ui
    > 2.considering 1 is done suppose later we add that color variable to tc-ui
    > 3.Now we have variables for same color at two places
    > 4.If two variables are present for same color at two places(Connect and tc-ui), tc-ui variable should override the local variable

   Second way:
    > other way could be to remove the local variable once we add the variable to tc-ui

**Comment by vic-topcoder** [comment]
Those new colors are temporary at the moment; I listed them during the work on the project creation update:
https://marvelapp.com/190egf26/screen/47344589
![screen shot 2018-10-18 at 8 31 24 am](https://user-images.githubusercontent.com/8484061/47166080-392b0d80-d2b0-11e8-850b-b630ae9a1c37.png)

Yes- ideally we can add those in the TC-UI and keep using the variables

**Comment by maxceem** [comment]
5. In the marvel design for new settings page top toolbar 
    ![image](https://user-images.githubusercontent.com/146016/47417077-c0451d80-d7a9-11e8-8686-e2d63a2740ff.png)

    has a color value and text color which
     - doesn't match color of top toolbar on other pages in connect
     - use colors which are not on the list https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss
      - background color `#262628`
      - text color `#EDEDF2`

**Comment by maxceem** [comment]
6. Seconds toolbar with submenu uses colors for shadow line which are not on the list:
    ![image](https://user-images.githubusercontent.com/146016/47417773-5463b480-d7ab-11e8-956d-45fa61c2f50d.png)
    - `#C3C3C8`
    - `#DCDCE0`

**Comment by maxceem** [comment]
7. Form labels use color which is not on the list

    ![image](https://user-images.githubusercontent.com/146016/47418043-e966ad80-d7ab-11e8-922e-a6ba7e92fba3.png)
    - `#47474F`

**Comment by maxceem** [comment]
8. Yellow color which higlights submitted email change is not on the list:
     ![image](https://user-images.githubusercontent.com/146016/47420142-54b27e80-d7b0-11e8-94d0-92264908c7b4.png)
     - `#FEB900`

**Comment by maxceem** [comment]
9. Green color of success validation is not on the list:
     ![image](https://user-images.githubusercontent.com/146016/47420303-af4bda80-d7b0-11e8-8da8-c33e12862403.png)
   - `#51B200`

**Comment by maxceem** [comment]
10. Reset password black title color is not on the list:
      ![image](https://user-images.githubusercontent.com/146016/47420390-e4582d00-d7b0-11e8-934a-45476c82dee7.png)
      
    - `#262628`

**Comment by maxceem** [comment]
11. Username hint under the field has a gray color not on the list:
     ![image](https://user-images.githubusercontent.com/146016/47420586-5df01b00-d7b1-11e8-8238-5e55708e39ab.png)
     
      - `#888894`

**Comment by maxceem** [comment]
@vic-topcoder In [the new design for user settings pages](https://marvelapp.com/7908ihg/screen/48326788) there are several places where some new colors are being used which are not on [the list of our colors constants](https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss).

I've added comments above with description of such places, see options 5-11. Could you pleaes advise what is the best way to deal with them?
- are they one time usage colors, which probably best to leave as hardcoded colors for one time
- or maybe it's better to add them to the list of you constants, as we are going to reuse them later
- or maybe we should replace them with the closest colors in out constant list?

**Comment by vic-topcoder** [comment]
@maxceem - I would like to move any definitions from Connect to reflect the tc-ui repo (https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss). We should not define new colors in Connect, but reuse existing color palette. This would help us change the theme in the future (when we need it).

A declaration like this redefines our gray colors:

``` scss
$gray-base    : $tc-black !default;
$gray-darkest : lighten($gray-base, 3.5%);
$gray-darker  : lighten($gray-base, 13.5%);
$gray-dark    : lighten($gray-base, 20%);
$gray         : lighten($gray-base, 33.5%);
$gray-light   : lighten($gray-base, 46.7%);
$gray-lighter : lighten($gray-base, 93.5%);
$gray-lightest: lighten($gray-base, 97.5%);
```

redefines our colors; Ideally we will populate the colors instead of calculating the issues. This is an important step of defining usage variables (example `$switch-background` or `$page-background`) that map to a color palette (like `$tc-black` or `$tc-gray-90`.

—-
The other definitions are connect-specific so I think they're fine as repo-only variables. At the time we're not building a library to be reused in the rest of the platform, I think it is ok to leave the variables (outside of the aforementioned color definitions) where they are.

Regarding typography, we should use the TC-UI, not define our own:
``` scss
$tc-body-large     		  : 20px;
$tc-heading            	: 20px;
$tc-heading-extra-small	: 14px;
```

as we have them defined in the TC-UI repo:
``` scss
// Labels
$tc-label-lg: 15px;
$tc-label-md: 13px;
$tc-label-sm: 12px;
$tc-label-xs: 11px;

// Body
$tc-body-lg: 20px;
$tc-body-md: $tc-label-lg; // 15
$tc-body-sm: $tc-label-md; // 13
$tc-body-xs: $tc-label-xs; // 11

// Headings
$tc-heading-xl: 42px;
$tc-heading-lg: 28px;
$tc-heading-md: $tc-body-lg;
$tc-heading-sm: $tc-body-md;
$tc-heading-xs: $tc-body-sm;
```

**Comment by maxceem** [comment]
@vic-topcoder thanks for the detailed explanation on this.

12. As I understand from your answer for the new colors which was introduced in the latest marvel design, we have to replace them with closest ones? Right? See options from 5 till 11 above. As they are not on the list of our constants for colors.

13. As I see we don't really use these colors, so we are safe to remove them from `connect-app`:
     ```scss
     $gray-base    : $tc-black !default;
     $gray-darkest : lighten($gray-base, 3.5%);
     $gray-darker  : lighten($gray-base, 13.5%);
     $gray-dark    : lighten($gray-base, 20%);
     $gray         : lighten($gray-base, 33.5%);
     $gray-light   : lighten($gray-base, 46.7%);
     $gray-lighter : lighten($gray-base, 93.5%);
     $gray-lightest: lighten($gray-base, 97.5%);
     ```

14. So we can replace these with variables from `tc-ui`
      ```scss
       $tc-body-large     		  : 20px; // -> $tc-body-lg
       $tc-heading            	: 20px;   // -> $tc-heading-md
       $tc-heading-extra-small	: 14px;   // -> $tc-heading-xs
      ```
      But there will be one mismtach: `$tc-heading-extra-small == 14px` in `connect-app`. While `$tc-heading-xs == 13px` in `tc-ui`.
      So if we reuse it some fonts could become too small in connect-app. Maybe for this case just remove `$tc-heading-extra-small` from connect-app and hardocde `14px` instead? There are only two places where we use `$tc-heading-extra-small`.

**Comment by vic-topcoder** [comment]
I went ahead and fixed the definitions of our typography scale; however in TC we are redefining the headings throughout the system; we must now replace any `$tc-heading*` to match the UI Kit definition - there's a mixed approach in Connect.

@maxceem - can you please help 
- remove the internal typography scale (size) definitions
- fix the reference in code to the appropriate scale from TC UI

Thanks for looking into those!

**Comment by maxceem** [comment]
@vic-topcoder

Removed all variables which are defined inside `connect-app` expect several places where we define very connect specific variables for local usage. Here are variables left in connect-app:

![image](https://user-images.githubusercontent.com/146016/47543314-2948a480-d914-11e8-9efe-06ac3b10344c.png)

I'm only thinking about `$screen-rg: 992px;` it's additional media query breaking point, which is widelly used in `connect-app`. Do you think it makes sense to add it to `tc-ui`? Or keep inside `connect-app`?

**Comment by maxceem** [comment]
Also, I've replaced all the hardcoded colors with variables (closest one if don't have exact one).
There is only one situation where I have concerns. Some shadows are defined using absoulute black color `#000000`. I'm not sure whether I should replace them with `$tc-balck`: `#151516`. Or leave at is it is.

![image](https://user-images.githubusercontent.com/146016/47543836-b0971780-d916-11e8-8134-df523b581744.png)

**Comment by maxceem** [comment]
Create a PR https://github.com/appirio-tech/connect-app/pull/2657

**Comment by vic-topcoder** [comment]
Looks good to me! Thanks for cleaning it up. For the Connect-only break point - it's fine where it is.

**Comment by maxceem** [comment]
@vic-topcoder I've created a PR to `react-components` as it cannot be built after some recent color variables updates in `tc-ui`, see https://github.com/appirio-tech/react-components/pull/303
