### ISSUE TITLE
Duplicate notification about link added to the project

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2633]
When somebody adds a links to the project I see notification about it in two different places:

![image](https://user-images.githubusercontent.com/146016/47000559-1d622300-d15b-11e8-9069-22e6b36200ea.png)

- one regular notification
- one more notification as `Coder bot` message

@RishiRajSahu just want to confirm that it's an intentional behavior.

**Comment by vikasrohit** [comment]
Yes, it is @maxceem. I guess, the `Coder Bot` message is in fact reading the regular notification to show it on the dashboard so that user don't have to open notification panel when there is a notification on the project where user is right now.

**Comment by maxceem** [comment]
@vikasrohit thanks for the clarification, so I'm closing the issue then.
