### ISSUE TITLE
Enable font antialiasing for connect pages in accounts-app

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2636]
Following from https://github.com/appirio-tech/connect-app/issues/2622

There is a difference between a new project page and registration page in Roboto font rendering:
- Connect App
   ![image](https://user-images.githubusercontent.com/146016/46900326-cc3ffe00-ced2-11e8-9ec8-6b10cb3c4fb8.png)

- Accounts App
   ![image](https://user-images.githubusercontent.com/146016/46900331-d82bc000-ced2-11e8-9fed-82c6fcfb3466.png)

The difference is because in Connect App we use `webkit-font-smoothing: antialiased;` while for accounts-app we don't.
Here is the difference in rendering for the whole page:
- `webkit-font-smoothing: antialiased` - enabled:
   ![image](https://user-images.githubusercontent.com/146016/46900447-cba86700-ced4-11e8-9527-c3ddb3a5dc5e.png)
- `webkit-font-smoothing: antialiased` - disabled:
    ![image](https://user-images.githubusercontent.com/146016/46900462-132ef300-ced5-11e8-8798-981ac2c83cdd.png)

So we have to enable font antialiasing for accounts-app on the pages related to Connect app as was decided here https://github.com/appirio-tech/connect-app/issues/2622#issuecomment-430103710.

**Comment by maxceem** [comment]
@vikasrohit I also wanted to use it, but I think we cannot. From `tc-ui` we only include this file `@import '~tc-ui/src/styles/tc-includes';` example https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/RegistrationScreen/style.scss

But `tc-includes` should NOT contain any styles only variables and mixins, otherwise, these styles will be included multiple times (each time we call @import) and lead to the growth of CSS styles, and could lead to performance issues like this https://github.com/appirio-tech/connect-app/issues/2587

**Comment by vikasrohit** [comment]
Agreed. But we can do that change in https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/mixins/_typography.scss and whenever that file is included, it would automatically have the correct fonts. And if `accounts-app` does not import the typography, it might be missing the Roboto fonts and we need to add it there.

**Comment by maxceem** [comment]
Yes, I think we can include it there. So we will repeat `webkit-font-smoothing: antialiased` [each time](https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/mixins/_typography.scss#L12-L30) when we add mixin with Roboto font, correct?

**Comment by vikasrohit** [comment]
Ideally, the mixins would included only once, right?

**Comment by maxceem** [comment]
> Ideally, the mixins would included only once, right?

Not sure what you mean.

If we modify these mixins by including `
  webkit-font-smoothing: antialiased;` like this:
```
@mixin roboto-light {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  font-weight: 300;
  webkit-font-smoothing: antialiased;
}

@mixin roboto {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  font-weight: 400;
  webkit-font-smoothing: antialiased;
}

@mixin roboto-medium {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  font-weight: 500;
  webkit-font-smoothing: antialiased;
}

@mixin roboto-bold {
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  font-weight: 700;
  webkit-font-smoothing: antialiased;
}
```

Then every time when we include this mixin in SCSS like this https://github.com/appirio-tech/connect-app/blob/dev/src/components/FileList/FileList.scss#L14
```
> h4 {
      @include roboto-medium;
      font-size: 15px;
      color: $tc-gray-50;
      line-height: 20px;
      margin-bottom: 2px;
 }
```

It will produce output CSS code like this:
```
> h4 {
      font-family: 'Roboto', Helvetica, Arial, sans-serif;
      font-weight: 700;
      webkit-font-smoothing: antialiased;
      font-size: 15px;
      color: $tc-gray-50;
      line-height: 20px;
      margin-bottom: 2px;
}
```

As an alternative we can include a rule once per app like this. Though for `accounts-app` it could be a little bit more complicated as we have to include it only for `connect` relating pages.
```
body {
    webkit-font-smoothing: antialiased;
}
```

Though as repeatig `webkit-font-smoothing: antialiased;` wouldn't increase size of output CSS that much, also repeating code is well zipped by gzip during sending by network. So I think we can go with the the approach you proposed with including this style to the mixins of Roboto fonts.

**Comment by vikasrohit** [comment]
Oh, understood. That is okay. No worries to have smoothing setting with every invocation of roboto font.

**Comment by maxceem** [comment]
@vikasrohit I gave it a try with updating `antialiasing` in `tc-ui`.

It appears that not only `connect` related pages in `accounts-app` are affected by `tc-ui`. So if I update it here we end up that some text on `non-connect` pages in `accounts-app` is antialiased while another text on that pages which is not affected by `tc-ui` would be not antialiased.

Note, that for connect related pages in `accounts-app` I still have to add additional styles to make all text antialiased as not all fonts are decorated using `tc-ui` for connect pages too.

Note 2, I still can make pages related to connect antialiased in `accounts-app` without updating `tc-ui`.

**Comment by vikasrohit** [comment]
Okay. However, I think if we are enabling antialiased for only roboto font, we should be good to enable it for both connect and non connect pages i.e. wherever(connect or non connect), we are using roboto font, it would look the same.

@vic-topcoder we need your opinion here. Would it make any difference to enable antialiased for roboto font every where it is used in connect and account app (both connect and non connect pages).

**Comment by maxceem** [comment]
@vikasrohit we can do that.

Though for `connect` related pages in accounts-app, there are many places where we use Roboto font without using `tc-ui` thus antialiasing wouldn't be enabled for these places. So we will still additionally enable antialiasing for `connect` pages where `tc-ui` is not used.

I'm not sure if there are places with Roboto font on other `non-connect` pages in accounts-app, from the first sight I don't see such places they use other fonts - fyi.

**Comment by vic-topcoder** [comment]
I had to rethink again what we're trying to achieve here.

 **Going forward I think we should remove the` -webkit-font-smoothing` overrides in all pages** to reduce rendering and performance degradation, and keep everything consistent. Chrome is my nemesis in terms of default font rendering (unfortunately!) and I think that was the reason for modifying the font rendering in the first place.

The `-webkit-font-smoothing: antialiased` does disable the LCD sub-pixel rendering so I would be cautious about that; the better setting is to leave it at "auto" everywhere.

The other CSS attribute to think about is `text-rendering: geometricPrecision` in Connect which renders the fonts much smoother (closer to the geometric outlines, especially Chrome). This one is different by default in the different browsers, so I had it enabled in Chrome for Connect. This would cause the different text rendering in our different applications.

By default I would say we do not modify the rendering in order to allow the browsers to be optimizing agains certain settings in the machine of the user (CPU, GPU, screen type, etc.).

From a design point I would love for Chrome to render as close to Safari as possible, but we live in imperfect world.

A comparison on Mac between Chrome (70) and Safari
![artboard](https://user-images.githubusercontent.com/8484061/47163463-ddaa5100-d2aa-11e8-943a-3978a7094eb9.png)

**Comment by maxceem** [comment]
Thanks, @vic-topcoder .

One more note, currently in `connect-app` we use `text-rendering: optimizeLegibility`.
Which suppose to enable kerning and optional ligatures.

Though I don't see any difference with or without it in Chrome:
- **With**:
    ![image](https://user-images.githubusercontent.com/146016/47193309-d9eafd00-d384-11e8-9de8-6a224a96dcbc.png)

    - kerning enabled
    - no ligatures

- **Without**:
    ![image](https://user-images.githubusercontent.com/146016/47193275-ad36e580-d384-11e8-8dc2-eac7b5cc37a5.png)

     - kerning enabled
     - no ligatures

So I as a conclusion from your comment I guess we are removing both:
- `-webkit-font-smoothing: antialiased`
- `text-rendering`
and let browser to display text the best way it can. Right?

**Comment by vic-topcoder** [comment]
Sounds good to me! Let's remove both and let the browser manage rendering.

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/645307f169204af3032ce8fc556c962258eb3e40

As fix is small, pushed directly to `dev`.

**Comment by vikasrohit** [comment]
I am not sure, but fonts does not look good (text is being cut due to overflow) to me on my chrome browser with latest code in dev.

<img width="1280" alt="screen shot 2018-11-03 at 6 26 24 pm" src="https://user-images.githubusercontent.com/2417632/47952488-15e1ad00-df96-11e8-92ae-fcf7af1e52fd.png">

However, if it fonts are looking good to @vic-topcoder, we can fix certain elements in app where is is overflowing now because of font rendering.

**Comment by vikasrohit** [comment]
Thanks @maxceem

**Comment by RishiRajSahu** [comment]
Working fine, closing the issue.
