### ISSUE TITLE
Notification about specification change doesn't come

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2639]
This is follow up from https://github.com/appirio-tech/connect-app/issues/2614#issuecomment-430506766

Currently, I don't get notifications about updates on the Scope tab. But I get all other kinds of notifications. It's on DEV environment.

For testing, I used, for example, this project https://connect.topcoder-dev.com/projects/7442 users `pshah_customer` and `pshah_manager`.

**Comment by maxceem** [comment]
@vikasrohit I found the mismatch but not sure with the solution:
- In `tc-project-service` we have two different events:
   - `PROJECT_PRODUCT_SPECIFICATION_MODIFIED: 'connect.action.project.product.update.spec',` - called when we modify spec of particular **phase**'s product
   - `PROJECT_SPECIFICATION_MODIFIED: 'notifications.connect.project.specificationModified'` - called when we modfigy specification of the whole **project**'s product
   - see https://github.com/topcoder-platform/tc-project-service/blob/dev/src/constants.js#L90

- The same time in `tc-notifications` we handle only one of these events `SPECIFICATION_MODIFIED: 'connect.action.project.product.update.spec'` https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/constants.js#L41

As I understand this has to be fixed in `tc-notifications`:
1. `SPECIFICATION_MODIFIED` should be `notifications.connect.project.specificationModified` not `connect.action.project.product.update.spec` as it's related to **project** modification not **phase** product.
2. As we still want to get notifications about modifications of **phase** products spec, we have to add this event `connect.action.project.product.update.spec` to `tc-notifications`. There are several questions regarding it:
    - How should we display it in emails? see https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/events-config.js#L221
    - How should we display it in connect-app? see https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js#L350

**Comment by maxceem** [comment]
It works now on `dev`. Closing it.

**Comment by vikasrohit** [comment]
Good to know that. Thanks @maxceem for handling other parts of the fix.
