### ISSUE TITLE
Enable web notification settings for copilots/managers

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2641]
Need to enable copilots/managers to be able to update their web notification settings, right now it is disabled for all users. We have to keep it disabled for only customer role users.

fyi @acshields @RishiRajSahu @maxceem

**Comment by maxceem** [comment]
@vikasrohit done via https://github.com/appirio-tech/connect-app/pull/2644

**Comment by vikasrohit** [comment]
Working in dev. Closing. Thanks @maxceem
