### ISSUE TITLE
Use constants for notifications events type instead of string

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2646]
Currently, we use string for notification events types in `connect-app`.
It causes some inconsistency as we are forgetting to update event types in all the places. For example:
- this event was renamed https://github.com/appirio-tech/connect-app/blob/b458c9ea245376ce7bce732e2595b996defc27f4/src/routes/notifications/helpers/notifications.js#L197
- this event was removed https://github.com/appirio-tech/connect-app/blob/b458c9ea245376ce7bce732e2595b996defc27f4/src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx#L37

**Comment by vikasrohit** [comment]
Yes, that is really needed to extract them as constants. @maxceem do you think you would be able to wrap this?

**Comment by maxceem** [comment]
@vikasrohit already did it.

I was thinking this issue wasn't posted to yesterday GitHub outage. Will create PR in a moment.

**Comment by maxceem** [comment]
@vikasrohit PR submitted https://github.com/appirio-tech/connect-app/pull/2651

**Comment by vikasrohit** [comment]
Awesome, Thanks @maxceem!!

**Comment by RishiRajSahu** [comment]
closing as merged to dev.
