### ISSUE TITLE
Project progress for Card-view on listing page

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2647]
Earlier we were showing circle for showing progress for active projects on Project listing page and Dashboard sidebar. But with incorporation of progress-bar on Dashboard and Project-Plan we removed the **blue circle**  for listing page as well(when switched to card-view). 

Do we want progress to be shown on project listing page when viewing in Card-view ? I'm not able to recall any discussion around project-listing page. Adding this issue to keep track of it.

@vikasrohit @vic-topcoder

**Comment by vic-topcoder** [comment]
> Do we want progress to be shown on project listing page when viewing in Card-view ? I'm not able to recall any discussion around project-listing page. Adding this issue to keep track of it.

That's a good call! I'll leave this as a secondary feature for the project cards in genera. The feedback is the cards are rarely useful for our customers, so I'll leave this out of the priorities for the time being. @acshields FYI

Closing and moving to Productboard as feature feedback.
