### ISSUE TITLE
Customer user should have milestone title highlighted on mouse hover

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2648]
### Expected behavior
There shouldn't be blue background when customer user hovers the mouse cursor over milestone title.

### Actual behavior
When we use customer user and hover mouse cursor over the milestone title we can see a blue background which is usually showed with edit button for manager user.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/146016/47335455-d675af80-d6bd-11e8-86ec-e244498e642c.png)

--

#### Environment
- OS: All
- Browser (w/version): All
- User role (client, copilot or manager): client
- Account used: phash_customer

**Comment by vikasrohit** [comment]
I think it was by design @maxceem we disabled the hover of completed milestones though. @RishiRajSahu please confirm.

**Comment by RishiRajSahu** [comment]
@maxceem yeah we have it by design, and discussed earlier also in some issue about disabling hover in case of completed milestone only.

**Comment by maxceem** [comment]
Ok, thank you for clarification. So I'm closing this issue.
