### ISSUE TITLE
Custom Feature deleted from the feature list on disabling the feature 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#265]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to Specification 
5. Go to Features
6. Add/Edit features
7. Add Custom Features
8. Add Custom Features
9. Disable custom Features
Expected Result: on disabling the Feature should not be deleted from the feature list 
Actual Result:  delete from list on disabling the feature
Environment: windows 7, chrome latest

![image](https://cloud.githubusercontent.com/assets/16131461/18932165/d4f41bc0-85ec-11e6-82e4-698cef8e9d93.png)

**Comment by fnisen** [comment]
Addressing as part of https://github.com/appirio-tech/connect-app/issues/125

**Comment by vikasrohit** [comment]
Fixed with #125 Added disable feature for custom features as well.
