### ISSUE TITLE
Showing specification link to the customer

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2652]
Currently we show the specifications milestone content to customer only once its completed, Should we provide a read only access to customer for specification link so that along with manager, customer could also have a look at specifications before the milestone is completed ?

Present Behaviour -
**Copilot/Manager/Admin**

![screen shot 2018-10-23 at 2 29 25 pm](https://user-images.githubusercontent.com/11248478/47349317-024e6080-d6d1-11e8-8fca-97ad5ca9f280.png)

**Customer**

<img width="773" alt="screen shot 2018-10-23 at 2 29 38 pm" src="https://user-images.githubusercontent.com/11248478/47349356-1abe7b00-d6d1-11e8-85bb-a838fefddde3.png">

fyi @vikasrohit @vic-topcoder @acshields

**Comment by vic-topcoder** [comment]
That's a very interesting idea :) I honestly have to think about that a bit more!

**Comment by RishiRajSahu** [comment]
@vikasrohit closing this as we have whole new UX for Connect now.
