### ISSUE TITLE
Final fixes for "Topcoder Connect - Avatar and user settings" challenge

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2654]
We've got the submission for the challenge https://www.topcoder.com/challenges/30072639

Note, that we have another version of the submission from the participant via email, not the one in the system, as there some issue suppose to be fixed.

The issues reported by Rishi after testing submission from the system:

- [x] when the request fails for updating the profile page, the page fields become empty
- [x] notification settings page has different width than other two pages
- [x] **[cannot reproduce]** unable to update the profile from local machine, getting error with trait, bad params
- [x] Multiple network calls failure while loading project listing page

   ![screen shot 2018-10-23 at 4 50 49 pm](https://user-images.githubusercontent.com/146016/47399790-d8e31280-d76c-11e8-80e1-2813efbaf478.png)

This list is constantly updating with new found issues: 

- [x] When we change something in **My Profile** and after press **Save Settings**. Data in the form for some time come to the state **before changes**, see the screencast https://monosnap.com/file/apnOUml0IaogWJDC5jCJfncAcDxtfX

- [x] During uploading of user avatar even though the button looks disabled we can press it and choose another file to upload.

- [x] Email validation and ressetting password don't work on DEV, as use wrong API URLs.

- [x] Connect logo is a little bit down (not vertically centered) on the setting pages Top Bar

- [x] Replace hardcoded colors with constants, also refer to https://github.com/appirio-tech/connect-app/issues/2632

- [x] When trying to change email server returns error. Same happens for community app on `topcoder-dev.com`
   ```
    {
       "id": "57e47e89:1669bc7e055:-7054",
       "result": {
           "success": true,
           "status": 500,
           "metadata": null,
           "content": "Cannot marshall type class com.appirio.service.member.api.Achievement without a custom marshaler or @DynamoDBDocument annotation."
       },
       "version": "v3" 
    }
   ```

- [x]  **[server side issue]** 
      Every time we try to retrieve traits for other than logging in user using `https://api.topcoder-dev.com/v3/members/pshah_customer/traits`
      Server responds with `Error 403`:
     ```
       {
          "id": "57e47e89:1669bc7e055:-6fcb",
          "result": {
             "success": true,
             "status": 403,
             "metadata": null,
             "content": "The login user must be administrator"
           },
           "version": "v3" 
      }
     ```

- [x] `Save settings` button has to be disabled if there are no changes. It has to be also done for Notifications settings page.

**Comment by maxceem** [comment]
- [ ] When we change something in **My Profile** and after press **Save Settings**. Data in the form for some time come to the state **before changes**, see the screencast https://monosnap.com/file/apnOUml0IaogWJDC5jCJfncAcDxtfX

**Comment by maxceem** [comment]
- [ ] During uploading of user avatar even though the button looks disabled we can press it and choose another file to upload.

**Comment by maxceem** [comment]
> unable to update the profile from local machine, getting error with trait, bad params

@RishiRajSahu Cannot reproduce using the latest submission patch provided by the winner. Check branch https://github.com/appirio-tech/connect-app/tree/feature/avatar-and-user-profile-settings or current PR https://github.com/appirio-tech/connect-app/pull/2655 for updated code.

**Comment by maxceem** [comment]
@RishiRajSahu one thing to discuss. We can update connect users' **First and last name**. But everywhere in the Connect app we are showing users name from the basic info. I guess we have to resolve it somehow.

**Comment by maxceem** [comment]
@RishiRajSahu I've fixed updating email on `connect-app` side. There is one note. When we get a verification email and click the link to verify email it works good, but it leads us to the Topcoder community app and looks like this:

![image](https://user-images.githubusercontent.com/146016/47541423-bdfad480-d90b-11e8-9596-03c97bd29265.png)

Instead I would expect to be lad to the `connect-app` instead.

**Comment by maxceem** [comment]
@RishiRajSahu [PR - Feature/avatar and user profile settings](https://github.com/appirio-tech/connect-app/pull/2655) updated with all final fixes required which we've discussed in Slack:
1. revert changes which has been done during changes regarding showing avatar from `connect_info`. Avatar should come form `basic_info` as before.
2. update profile settings, so it takes/saves `avatar`, `last name` and `first name` to `basic_info`

Also code was refactored to separate services and actions properly. And also service methods were put to appropriate places.

Note, that CircleCI cannot built the PR now, it's caused by recent color variables change. To fix project building [PR - fix colour variables after update in tc-ui](https://github.com/appirio-tech/react-components/pull/303) to `react-components` has to be merged first.

The only one thing left for now, is redirecting user to `connect-app` rather than to `community-app` when he clicks verification link in email.

**Comment by RishiRajSahu** [comment]
Not opting for `connect_info` (due to privacy policy regulations) for showing user name and photo, reverting the changes back to use `basic_info`, below are the changes made to  achieve that - 
1.Title, business phone, company name, company size , Business address - for them still the data will come from connect-info
2.The photoURL and name will be from basic info

**Comment by RishiRajSahu** [comment]
All the changes are pushed to dev, hence closing.
