### ISSUE TITLE
Discussions: New Post field appears out of the window.

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2661]
**Expected behavior :**
Describe : New Post field should not appears out of the post title window.

**Actual behavior
Describe.**
New Post field is appearing out of the post window. When user enter empty value in the Post title input box.

**Project Name:**
Phase and Dashboard Validation

**Screen Shot:**

![new post form moving out of the box](https://user-images.githubusercontent.com/30447858/47871752-e0707e80-de32-11e8-8c5a-3980b0b2aaa3.PNG)

**Comment by deepakanbarasan1** [comment]
@RishiRajSahu  Please fix this.

**Comment by maxceem** [comment]
@RishiRajSahu Fixed in commit https://github.com/appirio-tech/connect-app/commit/60bfa1743dc8530972df06e9d307bb5dbfa3e17b, already in DEV branch.

![image](https://user-images.githubusercontent.com/146016/47889488-3a019900-de85-11e8-802a-e9ad8d933200.png)

**Comment by RishiRajSahu** [comment]
Verified in dev. Working fine. Closing.
