### ISSUE TITLE
Post content lost if posting failed

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2663]
Whey I post a message in connect and network request fails, there is no alert and the message I entered is lost - post content is hidden as soon as the user clicks the post button.
If network request fails, there should be an alert and post editor should still be shown.

**Comment by maxceem** [comment]
@gondzo thanks for reporting this!

I can reproduce it when I'm writing a comment https://monosnap.com/file/hs9KXYG9Zz8Mm8IBoPQ6CHtbNK8xPr but it always shows an error alert for me.

**Comment by gondzo** [comment]
hmm, same here. probably I just didn't notice the alert last time.

**Comment by RishiRajSahu** [comment]
Pushed to dev. Closing.
