### ISSUE TITLE
throwing error on saving blank name of uploaded file 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#267]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to SPecification
5. go to Upload file
6. Upload a file
7. edit file name
8. same as blank

Expected Result: should ask to input the valid name
Actual Result: throwing error

Environment: windows 7, chrome latest

![image](https://cloud.githubusercontent.com/assets/16131461/18932285/5860bebe-85ed-11e6-965f-1a205255a41c.png)

**Comment by swetaipec** [comment]
throwing error on updating name

**Comment by parthshah** [comment]
@vikasrohit - assigning this to you. Let me know if you want to launch challenges to fix a bunch of these issues.

**Comment by vikasrohit** [comment]
@vic-appirio  @fnisen How to show the validation error?

@parthshah From the implementation point, we can not use Formsy form here because it would make nested forms(EditProjectForm and FileListItem). So, I guess, we need to handle the validation ourselves.

**Comment by vikasrohit** [comment]
Should we put a character limit as well on file name? We have limit of 250 for the description and description is also a required field for updating the file information.

**Comment by fnisen** [comment]
@vikasrohit can you please show a validation error right below the title, in our usual style? The copy can be: "The file name cannot be blank." 

Also: 
- Can we make description optional? 
- Let's go with 50 characters for the title limit. Good idea.

**Comment by vikasrohit** [comment]
@fnisen description is made compulsory in API. @mdesiderio can we make it optional?

**Comment by vikasrohit** [comment]
@fnisen I have changed the copy and put the max length on file name. However, I haven't remove required validation for description field because it requires changes in API. May be we can track that separately.

**Comment by vikasrohit** [comment]
@parthshah did the change in his late night today. :) So, now all requirements are done for the issue.

**Comment by fnisen** [comment]
@vikasrohit I get into an error state if I delete the entire name and then try to add a new one. I'm not able to save in that case: http://screencast.com/t/NVO5RSA2qq. 

Also, @parthshah, the description is still being required. I can't save without a description--there's an error message being thrown ("Whoops, there was a problem.")

**Comment by fnisen** [comment]
OK, description portion is now working as expected (not required), so just seeing the name issue @vikasrohit

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev now.
