### ISSUE TITLE
Dashboard is auto refreshing in every minute

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2680]
### Expected behavior
Should not refresh automatically, unless there is a new content is available

### Actual behavior
It is reloading with every get notifications call in every minute

### Steps to reproduce the problem
- Just stay on dashboard and observe

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by vikasrohit** [comment]
fyi @maxceem @RishiRajSahu

**Comment by vikasrohit** [comment]
@maxceem @RishiRajSahu Patched temporarily by disabling the auto refresh of the dashboard feeds. Needs a proper fix instead.

**Comment by RishiRajSahu** [comment]
Pushed the changes made by maxceem to handle the issue https://github.com/appirio-tech/connect-app/pull/2686
