### ISSUE TITLE
Creation of Scope Forms

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2688]
@vikasrohit @RishiRajSahu - Project intake forms need to be created for a new Topcoder partner. These forms should utilize our existing intake functionality in Connect, as this request is###  time-sensitive (we will then update the intake forms later to utilize our new form tool/scope process that we are currently planning). We need these forms added into Connect by **_Wednesday, 11/14._**  There is a hard contractual deadline of 11/17, but we want to allow two days for internal testing of the forms prior to the deadline. 

Here are the forms that need to be created:
https://docs.google.com/document/d/1WRPf1tHcqlTntl1VoQaEQdLaOdLIfxrs6v2LUrZT-xA/edit
https://docs.google.com/document/d/1CuXynSA-4fyFiCFVRZYcaKeWItlONgOZW9K47HRWnq8/edit
https://docs.google.com/document/d/1WRPf1tHcqlTntl1VoQaEQdLaOdLIfxrs6v2LUrZT-xA/edit
https://docs.google.com/document/d/17_NvP2N-z53-0S0fKvy_LUV-DvsOVvTS2uTPkI0-8e0/edit
https://docs.google.com/document/d/1LUp5WwCeGXfD1-4f5xpHvNFMiguYTRCuowKakMsQsvw/edit
https://docs.google.com/document/d/10Vx9QLF8geSpmCpiWH3JFQkzpSDM9ZjIpzAXMwPssOY/edit

**Comment by RishiRajSahu** [comment]
@acshields I see 5 unique links in the above description which means 5 forms needs to created, furthermore below are the points to confirm for being on same page - 
1. We will be creating 5 Project intake forms with deep links only(these forms will not be shown on our project catalogue)
2. I will create these forms first on dev and after final verification will proceed to PROD(which will be quicker once we have the final templates for these projects in place)
3. what are the default phases for each of the project are to be considered ? 
4. Five forms to be created are - 
- Mobile App Project Requirements Input Form 
- API Project Requirements Input Form 
- QA/Testing Project Requirements Input Form 
- Salesforce Project Requirements Input Form  
- Web App Project Requirements Input Form 

5. I have created the form for Mobile App Here with the deep link https://connect.topcoder-dev.com/new-project/zurich_mobile ,  you can have a quick look and provide early feedback, if any.

fyi @vikasrohit

**Comment by RishiRajSahu** [comment]
More updates as per the discussion on mail - 
1. PFA for BU and CostCentre fields, have kept word limit of 255 characters for each of the field
![screen shot 2018-11-14 at 2 50 45 pm](https://user-images.githubusercontent.com/11248478/48476442-0f202900-e825-11e8-86a7-3c1d21e9e2c2.png)

2. I am afraid we could directly add different logo, we might need some designer help first for that. By the way I have added the word Zurich to the form title now.
3. Removed the extra comma from the **notes** section description

**Comment by RishiRajSahu** [comment]
@acshields I have created the zurich forms for PROD as well, please find below the links for prod
https://connect.topcoder.com/new-project/kubik_mobile
https://connect.topcoder.com/new-project/kubik-api-development
https://connect.topcoder.com/new-project/kubik_sfdc_dev
https://connect.topcoder.com/new-project/kubik_website
https://connect.topcoder.com/new-project/kubik-testing

**Comment by RishiRajSahu** [comment]
@acshields Added new intake form for Design here - https://connect.topcoder.com/new-project/kubik_design

**Comment by vic-topcoder** [comment]
@acshields let's discuss what can be updated on the forms - there are several things I want to go over.

**Comment by acshields** [comment]
Hi @vic-topcoder - Per our Slack chat, these forms are customer-specific and will be upgraded at some point in the future to the new scope forms that @vikasrohit @RishiRajSahu are working on separately. These forms above do not represent that separate effort for the new scope form design.

**Comment by vic-topcoder** [comment]
gotcha, thanks!

**Comment by RishiRajSahu** [comment]
Closing as its completed.
