### ISSUE TITLE
.exe file should not be uploaded

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#269]
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to specification
5. go to project files
6. upload a .exe file

Expected Result:  should throw a validation message
Actual Result: able to upload a.exe file

Environment: windows 7, chrome latest

![image](https://cloud.githubusercontent.com/assets/16131461/18932663/1f580f26-85ef-11e6-8c94-9855e80130ab.png)

**Comment by fnisen** [comment]
Will allow this.
