### ISSUE TITLE
[Specification] - 404 Not Found  error displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#270]
Expected behavior
------------------------------------------------------------

- The GET  404 Error message is displayed when edit a project.

Actual behavior
------------------------------------------------------------

 -The error message must not be displayed.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Go to Projects and edit the project "Deloitte demo test project".

- Open Firebug tool to check the errors displayed.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: christina_uw

![error](https://cloud.githubusercontent.com/assets/5114907/18932812/b3789cc6-85da-11e6-803d-d053d75dee60.png)

**Comment by onetliviunicolae** [comment]
Obvservation

To test this issue is necessary to have Firebug tool installed if you using Mozilla Firefox, Developer Tool can be used if you use Chrome!

**Comment by parthshah** [comment]
This is expected behavior when there are no topics for a project.
