### ISSUE TITLE
Blue Action Button in Connect-generated emails not working for Outlook users

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2705]
Users who use Outlook for email management are reporting that when they receive emails triggered by events in Connect, the blue button in the email (to return the customer into Connect) is always disabled, which leads to some issues. Can you take a look into this?

**Comment by vikasrohit** [comment]
@acshields I have tried to reproduce it and able to reproduce it. I have applied a fix to a specific email template which is sent when someone posts a message in a connect project. I have tested it and it seems to be working for me. Is it possible for you or the person who reported the issue to validate this (by checking any new email which is sent for a new message in connect project)? If it is working for you, I would apply that fix in other templates as well.

**Comment by vikasrohit** [comment]
@acshields applied the fix at all other places in our notification emails where we are rendering a button for navigating back to the connect. Let me know if you still see the reports of incorrect button rendering.

fyi @gondzo @RishiRajSahu @ajefts

**Comment by acshields** [comment]
Hi @vikasrohit @gondzo @RishiRajSahu - Just reconfirmed w/ customer who is using Outlook that the fix is working.  The button now is functioning as expected.

**Comment by vikasrohit** [comment]
Thanks for the update @acshields
