### ISSUE TITLE
[$25] Reset password sending DEV Url in the mail received

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2712]
On Connect's Account page if user is hitting the request for resetting the password the mail corresponding mail received in mail-box contains the DEV URL instead of PROD.

<img width="828" alt="screen shot 2018-12-03 at 4 45 36 pm" src="https://user-images.githubusercontent.com/11248478/49370712-0bdcd680-f71b-11e8-9126-8aecf240ede8.png">

@vikasrohit

**Comment by maxceem** [comment]
To reproduce:
- login to https://connect.topcoder.com (production) with a real Topcoder user
- in the top right corner click to avatar to open dropdown and choose **Account and security**
- click **Forgot password?** and after click **Reset password**
- the email like in the first comment should come to your email address. And the link contains DEV URL https://accounts.topcoder-dev.com/ but should contain PROD one https://accounts.topcoder.com/

**Comment by PrakashDurlabhji** [comment]
@maxceem i wish to work on it

**Comment by maxceem** [comment]
Sure, it's on you.

**Comment by PrakashDurlabhji** [comment]
@maxceem i search a lot, can you please tell me where is backend repo? name of repo?

**Comment by maxceem** [comment]
Hmm, Connect App depends on several projects. Are you sure you need some other repo?

When I follow the steps to reproduce the issue I can see request which goes from Connect App. And it contains wrong URL `accounts.topcoder-dev.com` instead of `accounts.topcoder.com`. So it's I think it's Connect App which creates this wrong URL.
```
https://api.topcoder.com/v3/users/resetToken?email=maxceem%40gmail.com&resetPasswordUrlPrefix=https%3A%2F%2Faccounts.topcoder-dev.com%2Fconnect%2Freset-password
```
![image](https://user-images.githubusercontent.com/146016/51547409-2e7ca780-1ea1-11e9-80e3-597a1cba09d1.png)

This URL has param `resetPasswordUrlPrefix` now it follows to `accounts.topcoder-dev.com` for production environment but for production it should be `accounts.topcoder.com`.

For development environement it should stay `accounts.topcoder-dev.com`.

**Comment by PrakashDurlabhji** [comment]
@maxceem ready for review #2767

**Comment by maxceem** [comment]
For history:
The PR works good. For prod env connect app calls this enpoind to reset password:
```
https://api.topcoder.com/v3/users/resetToken?email=maxceem%40gmail.com&resetPasswordUrlPrefix=https%3A%2F%2Faccounts.topcoder.com%2Fconnect%2Freset-password
```

For dev env this one:
```
https://api.topcoder-dev.com/v3/users/resetToken?email=maxceem.dev%40gmail.com&resetPasswordUrlPrefix=https%3A%2F%2Faccounts.topcoder-dev.com%2Fconnect%2Freset-password
```

**Comment by maxceem** [comment]
@PrakashDurlabhji I've checked your PR, please, have a look https://github.com/appirio-tech/connect-app/pull/2767#pullrequestreview-195912687

**Comment by PrakashDurlabhji** [comment]
@maxceem sure will do it immediately.

**Comment by PrakashDurlabhji** [comment]
@maxceem it is ready

**Comment by RishiRajSahu** [comment]
@maxceem how did we verified it on prod ?

**Comment by maxceem** [comment]
@RishiRajSahu I've made a prod build and run it locally. I've checked what URL is sent to the backend, it's correct now.

**Comment by RishiRajSahu** [comment]
@maxceem thanks for the effort, let's keep it open, will close after testing on actual prod after the release.

**Comment by RishiRajSahu** [comment]
Working fine on prod and closing.
