### ISSUE TITLE
Form Rendering Issue

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2714]
<img width="589" alt="screen shot 2018-12-11 at 2 41 40 pm" src="https://user-images.githubusercontent.com/41118149/49807788-e2433100-fd52-11e8-8245-2f47b9650271.png">

The scope form was having issues rendering the budget line question.  This arose in the Zurich website scope form.

**Comment by vikasrohit** [comment]
@acshields it is happening because of the text `More than $100K` which can be fixed if we change the text to `$100K+`, if that is okay otherwise we need to find a programatic way to fix this.

**Comment by acshields** [comment]
That is fine with me. Proceed with the change to $100K+

**Comment by vikasrohit** [comment]
Fixed and patched to the production.
