### ISSUE TITLE
Dashboard Icon must properly displayed in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#272]
### Expected behavior
-----------------------------------------------------------------
Dashboard Icon must properly displayed in IE11

### Actual behavior
-----------------------------------------------------------------
Dashboard Icon layout issue in IE11; Circle is cropped from the right side

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/345)
- Check the Dashboard menu icon

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_2-57-35](https://cloud.githubusercontent.com/assets/4592712/18933058/875dc722-85f0-11e6-9b21-653043662d4f.png)

#### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by vic-appirio** [comment]
SVG loading issues - investigate

**Comment by vic-appirio** [comment]
Can't reproduce
