### ISSUE TITLE
[Projects] - when a single record available the sort option is not necessary

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#273]
Expected behavior
------------------------------------------------------------

- Do not display the sort by name option when only one record available.

Actual behavior
------------------------------------------------------------

 - Sort by name even one single record available.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Search an existing project as example Deloitte.

- After the results are displayed press on the column Name to sort ASC / DESC.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![sort-name](https://cloud.githubusercontent.com/assets/5114907/18933186/3e89f778-85dc-11e6-8a82-4c58a705a881.png)

**Comment by fnisen** [comment]
Yes, agree, not valid. It's subjective whether this functionality is leading to user confusion. In fact, users may expect the filter to be active consistently, so that they can change it in anticipation of results from an ensuing search/filter request.
