### ISSUE TITLE
[Team Management 2.0] Do we need auto complete for adding existing topcoder users

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2735]
Currently after new team management section, we are missing the auto complete feature for searching existing topcoder user while adding a user to the team. It might be an intentional feature, however, creating the issue to track the discussion.

fyi @acshields @vic-topcoder @RishiRajSahu

**Comment by vikasrohit** [comment]
@acshields as per our last discussion, we need this feature again so we are including this our bug bash.

**Comment by vikasrohit** [comment]
@maxceem one important thing to keep in mind for this feature is that we should be able to invite the member by handle even if there is no result returned for that by the api.

@acshields @vic-topcoder could you please confirm that this is an expected behaviour?

**Comment by maxceem** [comment]
To sum up:
- this featuer should work in both dialogs **Project Team** and **Topcoder Team**. We can see them by using user `pshah_manager` and opeining this project https://connect.topcoder-dev.com/projects/7839 by clicking the **Manage** link on the bottom of the left sidebar.
- we previously had autocomplete working in the previous implementation of team management feature. To check it out can use commit `a9b60bc8f2fd845d3eff82b860033f192e824ba3`. See demo https://monosnap.com/file/zmx4r3Gp4ENHgrkmG59SJmqJOXZlDh
- now we should start typing user handle with `@` to make autocomplete work. As we also can type email which don't start from `@` and they shouldn't have autocomlete
- even if there are no results returned by autocomplete we should be able to type handle ourself and invite user (unlike in previous implementention) 
- we should support navigating by keyboard (didn't have before):
   - press `down`/`up` should select next/previous suggested handle
   - pressing `Enter` should complete the typing handle with the currently selected handle
- note, that we can type several handles in the field and in **Project team** dialog we can type both handles and email.

**Comment by vikasrohit** [comment]
> * now we should start typing user handle with `@` to make autocomplete work. As we also can type email which don't start from `@` and they shouldn't have autocomlete

@maxceem we have a new requirement from the team that `@` is causing confusion to the product users, so we need to get rid of it. So, could we also get rid of `@` now along with this task? I know the side effect would be that it would make server calls even when user is typing emails, but I guess that does not harm, user might find existing user for that email in this case.

**Comment by maxceem** [comment]
@vikasrohit got it. Should we let users enter handles both ways with or without `@`? `@handle` and `handle`?

**Comment by vikasrohit** [comment]
I think drop the support for `@`, using both might be more confusing. We need to update the help text of the input as well after this.

**Comment by cagdas001** [comment]
@maxceem I'm using the `feature/team-management-autocomplete` branch, as indicated. But I can't open any project (including the [mentioned one](https://connect.topcoder-dev.com/projects/7839)) I'm getting an 404 page. Attached is the what I see

![chrome_2019-02-10_01-49-22](https://user-images.githubusercontent.com/28513447/52527568-b48b5180-2cdb-11e9-8b76-9cef63024621.png)

This is happening in both [local](http://local.topcoder-dev.com:3000) and [remote](https://connect.topcoder-dev.com) build. 

I tried on my mobile device's browser as well (which doesn't have `/etc/hosts` entry), so most likely this is a valid issue and I'm not the only one who is having this issue.

**Comment by maxceem** [comment]
Yeah, @cagdas001 looks like something got broken with project service. I'll try to get it fixed and updated to you asap.

**Comment by maxceem** [comment]
@cagdas001 it works now. Let me know if it's got broken again.

**Comment by maxceem** [comment]
This issue is has been handled by F2F challenge and the winning submission is provided by this https://github.com/appirio-tech/connect-app/pull/2829

Note, in the implementation I've asked to reuse the library we already use `react-select`, which is also used for autocomplete in attachment permissions dialog.

We still need to test it, and probably think about some UX improvements.
Also, for now, we created a separate component and didn't reuse the one which was created for autocomplete in attachment permissions dialog.
Maybe we can/should merge them. And also it could make sense use the same styles across these components.

We also use a very old version of `react-select@0.9.1` while the current version is `2.3.0`. This includes the fact that this old version causes some warnings in the browser console. So we consider updating it.

**Comment by maxceem** [comment]
@RishiRajSahu This issue is has been handled by F2F challenge and already in dev.

**Comment by RishiRajSahu** [comment]
yep, Closing it.
