### ISSUE TITLE
[Team Management 2.0] Invited Customer's not able to load listing page

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2738]
### Expected behavior
Customers should be able to see project listing page with card-view along with join button for project's invited for

### Actual behavior
It seems the invites data for project which is responsible for showing join button with card view for existing customers is not populated correctly

**Comment by RishiRajSahu** [comment]
fyi @vikasrohit @acshields @maxceem

**Comment by gondzo** [comment]
this is now fixed @RishiRajSahu - user email wasn't being loaded in frontend.
