### ISSUE TITLE
[Team Management 2.0] Handle the case when email entered to be invited is already topcoder user

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2741]
### Expected behavior
It should treat the invited user as registered user and send notification email which is intended for registered user.

### Actual behavior
It is treating the invited user as new unregistered user and sends email which is intended for unregistered user which is causing confusion to the invited user as they are now seeing a button to Register on topcoder.

### Steps to reproduce the problem
- Invite an existing topcoder user by email

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by vikasrohit** [comment]
fyi @gondzo @RishiRajSahu @acshields

**Comment by RishiRajSahu** [comment]
@vikasrohit handling it on UI side requires the handle to be fetched for the user with particular email id which I think is not the correct way, should we handle it at project service side just before send the email invites ?

**Comment by vikasrohit** [comment]
Yep, at API we need to tackle this.

**Comment by maxceem** [comment]
Created PR https://github.com/topcoder-platform/tc-project-service/pull/218 in project service repository. But I tested locally only using unit tests, as deploying and testing by real locally is quite complicated.

We will test on the DEV.
fyi @RishiRajSahu

**Comment by RishiRajSahu** [comment]
Closing as working fine and pushed to prod.
