### ISSUE TITLE
[$40] Notifications popup is not displayed

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2750]
If I have notifications in the popup and I click the mark icon to mark the notifications as read. Popup is closed and can't be opened again without refreshing the page

screenshot > https://www.screencast.com/t/d6NIV3RvW

**Comment by maxceem** [comment]
Thank you @gondzo. 
Can reproduce it in 100% attempts.

**Comment by prasadadarkar30** [comment]
@maxceem can i take this? thank you

**Comment by maxceem** [comment]
Sure, it's on you.

**Comment by prasadadarkar30** [comment]
@maxceem I wont be able to complete this, so releasing it for others. it is open for pickup again.

**Comment by rashmi73** [comment]
@maxceem i have no more issues with me, as i have already completed one. so taking this one and working on it. kindly assign it to me later. thank you.

**Comment by maxceem** [comment]
Thank you for letting us know @prasadadarkar30.

@rashmi73 assign it to you to keep it clear.

**Comment by maxceem** [comment]
As no PR was provided for 12 hours, this issue is now open for pick up.
The one who first comments can start working immediately without waiting to be assigned.

**Comment by Manoj85** [comment]
@maxceem can i work on it?

**Comment by maxceem** [comment]
@Manoj85 sure, it's on you.

**Comment by maxceem** [comment]
FYI @Manoj85 The issue could be reproducible if we click the checkmark for one particular notification to mark only one notification as read. After that, we cannot open dropdown again. See demo screencast https://monosnap.com/file/5NKlYaxYsv3CguDFBBCI2EWnQM9CHk

**Comment by Manoj85** [comment]
@maxceem 
I would not be able to complete this task. releasing it to others.

**Comment by maxceem** [comment]
Thanks for update @Manoj85.

This issue is now open for pick up. The first one who comments can start working on it without waiting for confirmation or assignment.

**Comment by saikat041** [comment]
@maxceem I want to work on it.

**Comment by Anthonymcqueen21** [comment]
What is the main issue currently

**Comment by saikat041** [comment]
@maxceem I have accepted the invitation. Thanks.

**Comment by Anthonymcqueen21** [comment]
Thank you @maxceem for the clarity

**Comment by RishiRajSahu** [comment]
Fixed.
