### ISSUE TITLE
[$30] [Team Management 2.0] Retain the value in text area if there is error in invite process

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2753]
### Expected behavior
Values (handle or emails) should be retained in case of any server error

### Actual behavior
Not retaining the previous values in case of error

### Steps to reproduce the problem
- Try adding non manager user via handle  to a manager role
- **_The error popup will appear and the values in the text area are cleared._**

fyi @maxceem @vikasrohit

**Comment by Gauravseta** [comment]
@maxceem can you please assign this to me?

**Comment by maxceem** [comment]
Done

**Comment by Gauravseta** [comment]
@maxceem 

steps to reproduce:
1. open any project details
2. on left side bar, there is invite people button , click on it popup appears.
3. enter email, click send invite
4. if error recived, email entered should be retained?

**Comment by maxceem** [comment]
You are right @Gauravseta 

There is also `Manage` button for each of the sections 
![image](https://user-images.githubusercontent.com/146016/51511398-1cb4e900-1e3c-11e9-985c-a7dcee5ce0a8.png)
Clicking both of these buttons will open a dialog where we can invite other members.
For both of dialogs, this should work.

Your steps to reproduce are correct.

**Comment by Gauravseta** [comment]
@maxceem i am not able to assign myself any issu.
can you please send invite to me?
gauravseta@gmail.com
thank you

**Comment by maxceem** [comment]
@Gauravseta we run the Bag Bush with slightly different rules than usually on the Topcoder you can check them in the challenge specification https://www.topcoder.com/challenges/30079880/?type=develop&nocache=true

Btw, I've already assigned you to this issue.

**Comment by maxceem** [comment]
@Gauravseta ok, got where the confusion comes from. That was a new participant and to be abel to assign him by myself, he has to be in the team of this repo. If a member is not in the team of the repo, I cannot assign him.

You are already in the team so I can assign you to the issues, even you cannot do it by yourself.

**Comment by Gauravseta** [comment]
@maxceem PR #2760

**Comment by Gauravseta** [comment]
@maxceem its ready for review ,i am not able to add labels

**Comment by maxceem** [comment]
@Gauravseta checked it, see comment https://github.com/appirio-tech/connect-app/pull/2760#pullrequestreview-194846550

**Comment by Gauravseta** [comment]
@maxceem logic seems to be quite difficult, need refactoring at many places.

**Comment by Gauravseta** [comment]
@maxceem updated PR

**Comment by Gauravseta** [comment]
https://github.com/appirio-tech/connect-app/pull/2760

**Comment by maxceem** [comment]
Checked, here is a review https://github.com/appirio-tech/connect-app/pull/2760#pullrequestreview-194888133

**Comment by Gauravseta** [comment]
@maxceem updated Pr

**Comment by Gauravseta** [comment]
@maxceem its ready for review

**Comment by maxceem** [comment]
Thanks @Gauravseta, here is the review https://github.com/appirio-tech/connect-app/pull/2760#pullrequestreview-195404294

**Comment by Gauravseta** [comment]
@maxceem yes it was working. let me check again

**Comment by Gauravseta** [comment]
@maxceem PR updated and ready for review

**Comment by Gauravseta** [comment]
@maxceem kindly check it is updated and working now

**Comment by RishiRajSahu** [comment]
fixed and merged to dev.
