### ISSUE TITLE
Auto select for options for checkbox group type questions

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2756]
@maxceem we need to support auto selection of one or more other options in a `checkbox-group` or `tiled-checkbox-group` type question. Essentially it is similar to disabling options when specified condition is met, similarly we can auto add the value of a an option based on another condition say `autoSelectCondition`.

**Comment by vikasrohit** [comment]
@maxceem you can pick this in CF as well if you think so.

**Comment by maxceem** [comment]
@vikasrohit yep, added it on the list to decide.

**Comment by maxceem** [comment]
@vikasrohit is there some real-world example of a template where we are going to use it?
It would help to understand what approach to use for the implemenetation. As supporting in general case for such thing could be very tricky.

**Comment by vikasrohit** [comment]
Our use case right now is for a particular questions which says "What type of deliverables you need?" and the options are: Design, Dev, QA and Deploy. We want the QA to be auto selected when user selects `Dev` to let them know that QA has to be bundled with Dev.

**Comment by maxceem** [comment]
@vikasrohit I didn't see such feature in the new form design. Do we need this feature anyway or we can leave it for now?

**Comment by vikasrohit** [comment]
It might not be depicted in the design, but we got this requirement in our meeting with product team and primary use case was to auto select the `QA` option when user selects `Development` because by default do QA for a development work. However, I am not sure if that is still a requirement because after having this implemented for the mentioned question, it might create issue with dependent questions e.g. all `QA` deliverable related questions would also become visible if we auto selects the `QA` with `Development` which is not intended as per requirements for new scope forms.

fyi @acshields

**Comment by maxceem** [comment]
@vikasrohit I realized that we don't have question type `tiled-checkbox-group`. 

1. Do I understand this correctly, that we only need to support this feature for `checkbox-group`? I don't see other question types where we can select multiple options.

2. Do you think we should `disable` autoselected options? As per requirements, we cannot unselect them if they were selected automatically.

**Comment by vikasrohit** [comment]
@maxceem we have the tiled version of checkbox component, https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Formsy/TiledCheckboxInput.jsx.

And for disabling the auto selected options, I think we need to do that, however, we don't need to force it code when auto selecting the option. Rather, we already have support for `disableCondition` so we can use both `autoSelectCondition` and `disableCondition` simultaneously to achieve the behaviour.

**Comment by maxceem** [comment]
@vikasrohit as I see from https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/SpecQuestions.jsx#L171 we don't have support for `tiled-checkbox-group` type of question yet, so I guess we have to add it, right?

Got it regarding disabling!

**Comment by vikasrohit** [comment]
Oh yes, that might be true as we never ended up in rendering this component
I any of the forms.
