### ISSUE TITLE
[$30] [Team Management 2.0] Show alert when inviting already a member via project-team dialog using handle

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2757]
### Expected behavior

| Team              | mode     | Already member  | Action        |
| ------------- |:--------:| -----------------:| ----------:|
| ProjectTeam  | handle      |   Yes                     | _**show alert**_ |

### Actual behavior
| Team              | mode     | Already member  | Action        |
| ------------- |:--------:| -----------------:| ----------:|
| ProjectTeam  | handle      |   Yes                     | _**Invite Sent again**_ |

### Steps to reproduce the problem
- Try adding topcoder user already part of **Topcoder Team** for a project via `@handle` under **Project Team** dialog

**Comment by RishiRajSahu** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
@RishiRajSahu when we invite to the Project Team, the placeholder says `Enter one or more emails separated by ';' or comma ','`. So it asks us to enter emails rather than handles.

Should we also change placeholder to `Enter one or more emails or user handles separated by ';' or comma ','`?

**Comment by maxceem** [comment]
Now this functionality already works when we try to inviter already added member to the Topocoder team https://monosnap.com/file/PN8D3YW37yvUqTwsPTybIphZva2WUT

So we should enable the same functionality for Project Team.

**Comment by RishiRajSahu** [comment]
>this functionality already works when we try to inviter already added member to the Topocoder team

@maxceem yeah we need the same for project team, and yes the placeholder needs to be updated.

**Comment by rashmi73** [comment]
@maxceem pls give this to me. thank you

**Comment by maxceem** [comment]
Done

**Comment by rashmi73** [comment]
@maxceem just some more time. will complete it on time . or just may be extended it by 15 mins

**Comment by rashmi73** [comment]
@maxceem its ready for review #2765

**Comment by maxceem** [comment]
Hi @rashmi73 

I've checked your PR, but it doesn't work for me. If you need more clarification about the task let me know.

Just to sum up:
This feature already works for **Topcoder team** dialog, see screencast https://monosnap.com/file/bDRJcdCYCRx2iTzM9Wb0TJnxS3YHo3

And we have to implement the same for **Project team** dialog, because so far instead of showing an error that member is already invited now we send an invitation, see a screencast https://monosnap.com/file/39N4pmeTtdFQ5flSm4zZVlWQwC0XlH But we shouldn't send an invitation as such member is already is a part of the topcoder team.

**Comment by rashmi73** [comment]
@maxceem needed some clarification:
As project team dialog placeholder says: "Enter one or mail email"

so user can enter handles too?

**Comment by rashmi73** [comment]
@maxceem i analyzed scenario and made appropriate changes. it is ready for review. Pr updated 
#2765

**Comment by rashmi73** [comment]
@maxceem PR updated and ready for review

**Comment by RishiRajSahu** [comment]
Fixed.
