### ISSUE TITLE
[$50] [Metadata management] JSON is cleared when there is a syntax error

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2769]
### Expected behavior
Current JSON should stay.

### Actual behavior
Current JSON is replaced with `{}` empty object.

### Steps to reproduce the problem (scenario 1)
- Go to project templates list https://connect.topcoder-dev.com/metadata/projectTemplates
- Select any template and click Maximize to edit the template JSON
- Make a syntax mistake, for example, add a comma after some value
- Select another browser tab, and after coming back to the tab with JSON. JSON will be empty

See screencast https://monosnap.com/file/hrscvjoxVMUJbPKQjVIjtalH1P4TYf

### Steps to reproduce the problem (scenario 2)
- Go to project templates list https://connect.topcoder-dev.com/metadata/projectTemplates
- Select any template and click Maximize to edit the template JSON
- Copy all the JSON to your text editor
- In your text editor make some syntax mistake in the JSON
- Copy the JSON from your text editor with the syntax mistake and paste to the JSON editor on Connect App
- Instead of pasting your JSON with a syntax error, it will become empty

See screencast https://monosnap.com/file/8xTAFe9zM3iK7mnKKZcC2t9wjVLjqQ

fyi @vikasrohit @RishiRajSahu

**Comment by vikasrohit** [comment]
Yep, @maxceem I have faced the same and its kind of known issue. Its good to get it fixed.

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by vigneshTheDev** [comment]
I would like to work on this issue

**Comment by maxceem** [comment]
Sure @vigneshTheDev

**Comment by vigneshTheDev** [comment]
Raised a PR here https://github.com/appirio-tech/connect-app/pull/2776

**Comment by vigneshTheDev** [comment]
> @vigneshTheDev
> 
> ### IMPORTANT NOTE
> As we need all these templates/products/types/categories which now exists. Please, don't edit them and don't delete them.
> If you need to update them, you can use next templates which are created specially for testing purposes:
> 
> * https://connect.topcoder-dev.com/metadata/projectTemplates/85
> * https://connect.topcoder-dev.com/metadata/productTemplates/63
> * https://connect.topcoder-dev.com/metadata/projectTypes/app-test
> * https://connect.topcoder-dev.com/metadata/productCategories/cat-test
> 
> Or you can create new templates. In particular, you can duplicate existent templates and edit/delete them after. But don't change other existent objects.

Sure. I haven't modified any of the templates.

**Comment by maxceem** [comment]
Thanks, @vigneshTheDev I've checked your PR, could you please have a look https://github.com/appirio-tech/connect-app/pull/2776#pullrequestreview-195947989
