### ISSUE TITLE
Firebug: Warning: It looks like you're using a minified copy of the development build of React. 

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#277]
Expected behavior
------------------------------------------------------------

- Do not display this error message.

Actual behavior
------------------------------------------------------------

- Do not display this error message.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Go to Dashboard.

- Complete Search field with the text "demo test project".

- Press enter to perform the search action.

- Clear field.

- Press back button browser.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: topcoder123!

see attach!

![warning](https://cloud.githubusercontent.com/assets/5114907/18933397/38721db0-85dd-11e6-917f-3fce7f8a55c6.png)

**Comment by parthshah** [comment]
Closing since, this is expected in Dev env. We don;t see this in prod build in prod env.
