### ISSUE TITLE
[$20] [Metadata management] When creating a new projectTemplate it requires to enter `id`

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2770]
### Expected behavior
When we create a new projectTemplate we shouldn't be required to enter `id`. 
`id` field should be hidden.

### Actual behavior
When we create a new projectTemplate we are required to enter `id`.

### Steps to reproduce the problem
- Go to projectTemplate list https://connect.topcoder-dev.com/metadata/projectTemplates
- Click button **Create**
- There is `id` field is displayed. And we should fill all the fields including `id` to make **Save** button active.

**Comment by vikasrohit** [comment]
Good candidate for CF @maxceem

**Comment by maxceem** [comment]
To sum up:
- We can test it using user `pshahcadmin` (see password on the challenge forum) which has access to metadata management tools
- I think it doesn't work not only for projectTemplates, but for all four tabs:
   - https://connect.topcoder-dev.com/metadata/projectTemplates
   - https://connect.topcoder-dev.com/metadata/productTemplates
   - https://connect.topcoder-dev.com/metadata/projectTypes
   - https://connect.topcoder-dev.com/metadata/productCategories
  
    so it should be fixed for all of them

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by cagdas001** [comment]
May I take this? Thanks

**Comment by maxceem** [comment]
Sure @cagdas001. You can start working on it as you've already commented.

**Comment by cagdas001** [comment]
Which branch should I target for [react-components](https://github.com/appirio-tech/react-components) ?

**Comment by cagdas001** [comment]
Ah, ok. I had missed it, `feature/connectv2` branch should be targeted.

**Comment by cagdas001** [comment]
@maxceem ready for review

https://github.com/appirio-tech/connect-app/pull/2780
