### ISSUE TITLE
[$40] [Metadata management] For projectTemplates `hidden` and `disabled` properties cannot be unset

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2771]
### Expected behavior
We should be able to unset `hidden` and `disabled` checkboxes for projectTemplates.

### Actual behavior
When we unselect checkboxes for `hidden` and `disabled` and save the template, the checkboxes become selected again.

### Steps to reproduce the problem
- Go to project templates list https://connect.topcoder-dev.com/metadata/projectTemplates
- Select any template
- In the form on the right select both `hidden` and `disabled`. Save the template. These checkboxes will stay selected as expected.
- Now unselect both checkboxes `hidden` and `disabled`. Save the template. They will become selected again, but they should stay unselected.

**Comment by vikasrohit** [comment]
Good candidate for CF, if it is not the backend issue.

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by gets0ul** [comment]
Can I work on this?

**Comment by maxceem** [comment]
Sure, assigned to be clear.

**Comment by RishiRajSahu** [comment]
Working fine.
