### ISSUE TITLE
Cannot load specification page for old projects (non v3)

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2782]
### Steps to reproduce the problem
- Navigate to the old project Specification page (`version` !== `v3) for example http://connect.topcoder-dev.com/projects/5000/specification
- The page will show loader forever, and there will an error in browser console
   ```
    TypeError: Cannot read property 'sections' of undefined
   ```

**Comment by maxceem** [comment]
Some verview for easier debugging:
- we have new projects which have `version === "v3"` and also they have a project plan with phases. Such projects have s Scope tab which works fine https://connect.topcoder-dev.com/projects/7844/scope.
- we have old project which `version !== "v3"`. Such projects have a Specification tab which now has this error http://connect.topcoder-dev.com/projects/5000/specification
- note, that on the Specification tab old projects are rendering similar form which is rendered on Scope tab for the new projects
- to render this tab both old and new project are loading project template, which has `scope` property with and object which contains `sections` property. But in this case in some reasons sections are `undefined`.
   If I'm not mistaken for old projects we find template using projectTemplate key which we keep in `project.details.products[0]`, while for new project we find projectTemplate using id which we keep in `project.templateId`.

**Comment by vikasrohit** [comment]
https://github.com/appirio-tech/connect-app/commit/862ec955b4440d92c2978ec24abaefc0735fb92a#diff-ca9fe2786836bbcd815d3686f52e6bfdR82 might be the place where it is needed to be fixed. And I think few lines from https://github.com/appirio-tech/connect-app/blob/2d748522b19db06e958df47abffeb85d7b052adc/src/projects/list/components/Projects/ProjectsGridView.jsx#L57 are the fix to do that.

**Comment by maxceem** [comment]
@vikasrohit it's fixed and the commit is already in dev, so we can test it more on dev.

**Comment by vikasrohit** [comment]
Thanks @maxceem
