### ISSUE TITLE
UI Update: Team Management Feature

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2785]
@RishiRajSahu @vikasrohit 
**Issue:** When a Copilot invites a person to the project and the invited person has not yet accepted the invitation, our current display does not indicate the status of the invited person to the person who invited them. 

![image 7](https://user-images.githubusercontent.com/41118149/51692820-f36e9700-1fba-11e9-9ef4-5927f3704a6b.png)

**Recommended Changes:**
1) When a Copilot or Manager (not Copilot Assignment Manager) invites a Copilot to a project, next to the invited person's name in the pop-up it should say "Invitation request sent to Copilot Assignment Manager for Review." In the left sidebar under Topcoder, the invited person should be reflected there as a grayed out image and when a user hovers over the image it should say "Invitation Pending." Once the Copilot Assignment Manager has approved the invitation the new Copilot should be displayed as an active member of the Topcoder team (image is no longer grayed out).
2) When a Copilot or Manager (not Copilot Assignment Manager) invites a Manager to a project, next to the invited person's name in the pop-up it should say "Invited." In the left sidebar under Topcoder, the invited person should be reflected there as a grayed out image and when a user hovers over the image it should say "Invited." Note: There are no restrictions on who can invite a Topcoder Manager to a project. Once the invited Manager has joined the project their image in the left sidebar should no longer be grayed out and they should be shown as an active member of the team.

**Comment by RishiRajSahu** [comment]
Parital requirements are implemented via #2743 and the rest are tracked here - https://github.com/appirio-tech/connect-app/issues/2837
