### ISSUE TITLE
Link Update: "About"

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#2786]
@vikasrohit @RishiRajSahu @dmessing 

**Issue:** The "About" link at the bottom of the Connect "All Projects" dashboard is broken.
**Solution:** Please update the link to redirect the user to this page - https://www.topcoder.com/about/

<img width="1431" alt="screen shot 2019-01-24 at 9 45 45 am" src="https://user-images.githubusercontent.com/41118149/51693815-e18df380-1fbc-11e9-93ed-8154b320adaa.png">
<img width="1404" alt="screen shot 2019-01-24 at 9 45 57 am" src="https://user-images.githubusercontent.com/41118149/51693821-e357b700-1fbc-11e9-858d-7e3735ea15ef.png">

**Comment by vikasrohit** [comment]
Thanks @dmessing for the hotfix.
