### ISSUE TITLE
Invite by multiple emails is failing

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2789]
### Expected behaviour
Should be able to invite more than one members by emails

### Actual behaviour
It fails with server error when one tries to invite multiple members via email. It do work when there is only email and/or multiple handles.

### Steps to reproduce the problem
- Invite multiple members via email

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by vikasrohit** [comment]
fyi @maxceem @RishiRajSahu It seems identity does not support filtering multiple users via email i.e. it does not support `ORing` the email in the filter. I guess, we need to use the member API to serve the purpose.

**Comment by acshields** [comment]
Hi @vikasrohit - We do still need to figure this one out; I have seen users try to enter several emails at once to send invites and then get frustrated when it doesn't work. Re: Matt's comments in Slack, let me/him know if you need support in working w/ the Member API to get something updated.

**Comment by vikasrohit** [comment]
Yep, replied on slack.

**Comment by vikasrohit** [comment]
Related issue in the backend https://github.com/topcoder-platform/tc-project-service/issues/246

**Comment by maxceem** [comment]
@vikasrohit It feels like there is no good solution for the backend blocker at the moment until we `identity` service supports several emails. Here is a comment with details https://github.com/topcoder-platform/tc-project-service/issues/246#issuecomment-506691842 and possible solution in the next comment. Though I'm not sure if it would work properly due to timeout restrictions.

**Comment by vikasrohit** [comment]
As I mentioned in the related issue, we agree on implementing parallel requests for multiple email invites in single user action.

**Comment by vikasrohit** [comment]
@maxceem I just tested the PR for parallel requests and it seems to work surprisingly good at least in dev env. I think we can go ahead with this fix in production. Let me know if you have any concerns with the changes.
Also, I would like to raise the default value of the maximum number of parallel requests to be `10` instead of `5` before moving ahead.

**Comment by maxceem** [comment]
@vikasrohit as long requests don't fail randomly in real life we should be good, I don't have any other concerns.

I've creased the number of parallel requests to 10 and pushed to DEV on Project Service.

**Comment by vikasrohit** [comment]
Do you think that increasing the number of parallel requests would increase the possibility of timeout of requests?

**Comment by maxceem** [comment]
@vikasrohit it's hard to say. I'm not sure what were the reasons for the delays and if increasing to 10 can affect them or no.

**Comment by vikasrohit** [comment]
I just tested the inviting 11 emails at the same time and it returned in 12.5 seconds overall. So, it seems we are good for now.
