### ISSUE TITLE
footers links   home/contact/help/privact not working

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#279]
### Expected behavior

links must be working
### Actual behavior

not working
### Steps to reproduce the problem

1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to footer links
### Screenshot/screencast

Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/18933454/844125d2-85f2-11e6-8fc8-16e57b982e37.png)
## 
#### Environment
- OS: windows 7
- Browser (w/version):chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by fnisen** [comment]
Will provide addresses.

**Comment by fnisen** [comment]
- About: https://www.topcoder.com/about-topcoder/
- Contact: https://www.topcoder.com/about-topcoder/contact/
- Help: https://help.topcoder.com/hc/en-us
- Privacy: https://www.topcoder.com/community/how-it-works/privacy-policy/
- Terms: https://connect.topcoder.com/terms

**Comment by mahestro** [comment]
Also added Help link to the user dropdown - http://take.ms/Vomvm

**Comment by fnisen** [comment]
@mahestro good catch on the user link. Can you please make one change: open all the non-Connect links (everything except terms) in a new tab? So, new subdomain = new tab. Thank you.

**Comment by fnisen** [comment]
Fixed the last part myself.
