### ISSUE TITLE
Allow editing milestone names and text fields (only) for completed milestones

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2790]
### Expected behavior
User should be able to update the name and other text fields even for completed milestones because sometimes it makes sense to update these text fields, for better documentation and conveying details to the customer, after the milestone is completed.

### Actual behavior
As of now we don't allow user to update the name or various description texts once the milestone is completed.

### Steps to reproduce the problem
- Try to edit text fields for a completed milestone

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Copilot/Manager
- Account used: N/A

**Comment by acshields** [comment]
Hi @vikasrohit - I think that it would be okay to allow the modification of milestone names after completion. Let's talk through this tomorrow - I would be interested to hear your example of when you wanted to update completed milestone text. Initial reaction though is that this should be fine.

**Comment by vikasrohit** [comment]
I think we are already working on new designs for phases which might not require this at all.
