### ISSUE TITLE
Validate both first and last name in the name field for registration form

### ISSUE THREAD

**Issue by ThomasKranitsas** [appirio-tech/connect-app#2799]
### Expected behavior
The user should enter both first and last name to be able to register.

### Actual behavior
The Connect app allows a user to register without last name.

### Steps to reproduce the problem
- Go to https://accounts.topcoder-dev.com/connect/registration
- Enter `Thomas` in the `First and last name` field

### Screenshot/screencast
https://monosnap.com/file/KzNjhhNfjrrWaPFykPtt86uCBl36b2

**Comment by vikasrohit** [comment]
It is as per design. We allow users to only enter single name, in which case we assume that to be the last name of the user because our system mandates the last name internally.

**Comment by ThomasKranitsas** [comment]
But in many places (processors or other apps like the settings page on the main site) the first name is required and there are validation errors if it's missing.

I understand that the registration page in Connect is meant to be used from customers but that doesn't mean they won't ever land to another app where the first name will be required.

Keeping data consistent across different apps will ensure there will be no errors.

**Comment by vikasrohit** [comment]
Yes, I know that. But it is as per product team. @vic-topcoder @acshields fyi

**Comment by acshields** [comment]
@ThomasKranitsas @vikasrohit - In thinking this through, I think that the customer's name should be changed so that First Name and Last Name are two separate, required fields.

**Comment by cwdcwd** [comment]
As per @vic-topcoder 

> Either works for me. By design I wanted to eliminate multiple fields - the more fields, the bigger the registration form looks. If we have a single field, I wanted parsers/processors to verify 2 names inputs.

I'm fine with either solution but what @ThomasKranitsas highlights here is that there’s no check and enforcement on there being a first and last name so we end up putting garbage data into the system. This ends up causing errors upstream with the processors that update Dynamo for the member profile and update elastic search. 

@vikasrohit can we get this addressed before it starts causing member profile issues? thanks id advance.

**Comment by vikasrohit** [comment]
Okay, I am still not convinced that these were the original requirements to ensure that both first name and last name are to be validated. If that was the case, we shouldn't have the issue https://github.com/appirio-tech/tc-connect2sf/issues/31 raised and patched. Having that issue raised and patched means that all stakeholder knew the possibility of having only single name in the field.

Anyway, as it is causing troubles now, @gondzo could you please take care of it?
fyi @mtwomey

**Comment by vikasrohit** [comment]
Patched the fix to the production, now it should not allow user to enter single name i.e. it would validate for a full name (containing at least one space between characters).

fyi @gondzo @mtwomey @cwdcwd @ThomasKranitsas
