### ISSUE TITLE
[Project] - the focus can be set near on / of button

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#280]
Expected behavior
------------------------------------------------------------

- The focus must not be set there.

Actual behavior
------------------------------------------------------------

- The focus can be set near On / Off button option,

Steps to reproduce the problem

------------------------------------------------------------

- Login into application as copilot role.

- Select Dashboard and edit the project with name Project.

- Select Specification.

- Go to Search section and press "Add / Edit Features".

- Select the template "Search".

- Press click near On / Off button.
 

Environment
------------------------------------------------------------

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![focvus1](https://cloud.githubusercontent.com/assets/5114907/18933565/15858bd8-85de-11e6-9094-1f6074510d85.png)

**Comment by vic-appirio** [comment]
disable user select in browsers through CSS
