### ISSUE TITLE
Update behaviour of add-ons question type

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2800]
### Expected behavior
We need to alter its implementation to render all subcategories and their addons for the given `category`.
![image](https://user-images.githubusercontent.com/146016/52319710-2d518b80-2a06-11e9-86c1-44f43de9d08f.png)

### Actual behavior
Now `add-ons` type question renders one plain list of checkboxes. It gets them by filtering `productTemplates` using a combination of `category` and `subCategory`
Details can be seen in the challenge where it was implemented https://www.topcoder.com/challenges/30077887/?type=develop

### There is one open question.
When we create a new project we choose what kind of deliverables we want to get at the end: `design`, `development`, `qa`, `deployment`. And we want to show only add-ons for selected deliverables.
Currently, we can easily define which add-ons to show using conditions:
```
{
  "type":"add-ons"
  "category": "generic",
  "subCategory": "cool-design",
  "condition": "(details.appDefinition.mainWork contains 'design')"
}
```

While with the new approach when we define only `category` and show products grouped by subCategories:
```
{
  "type":"add-ons"
  "category": "generic",
  "condition": "(details.appDefinition.mainWork contains 'design')"
}
```
There is a question. Will be only `category` enough to show/hide add-ons depend on the selected deliverables?

If one category can contain products for multiple deliverables, there should be some way to filter these products by selected deliverables.

fyi @vikasrohit

**Comment by vikasrohit** [comment]
one more thing @maxceem using the keyword `question` in the screenshot seems bit confusing to me. You might be thinking in context of complete template where we are rendering this add on section.

**Comment by maxceem** [comment]
> one more thing @maxceem using the keyword `question` in the screenshot seems bit confusing to me. You might be thinking in context of complete template where we are rendering this add on section.

Technically we have a question with `type="add-ons"`. So when we are rendering this screen we add a `section`, inside `section` we add a `subSection` and inside that `subSection` we add a `question` with `type="add-ons"`.
In case of a new design, it may seem like too much as we can show add-ons as a section. But in general, we can add such block anywhere. But if we implement `add-ons` as a `section` or `subSection`. We would restrict our ability to add the block with add-ons to fewer places.

**Comment by vikasrohit** [comment]
Agreed. However, I was thinking of keep the component independent of section/subsection/question and have the ability to render it independent of the actual form, if required just like project estimate component. We can pass the required properties from question/subsection when it is to to shown as question/subsection.

**Comment by maxceem** [comment]
Sure. We can extract it a separate component.
While keeping the ability to render it as `question` with type `add-ons`.

**Comment by maxceem** [comment]
@vikasrohit it's done via F2F http://www.topcoder.com/challenge-details/30083578/?type=develop&noncache=true in `feature/form-redesign` branch commit 47d8819c1548c911d7e2689a87ed3e0fe478f94f.

**Comment by vikasrohit** [comment]
Working as per requirements. Closing.
