### ISSUE TITLE
Add reference code as a column to the project list in a grid view

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2803]
From `Connect - UI/UX Enhancements` ducument.

Currently, we are showing reference code next to the project name in the style like a tag.
Instead, we should add a new column `REF` which would show reference code and remove the current tag next to the project title.

![image](https://user-images.githubusercontent.com/146016/52386695-13757e80-2ac2-11e9-970e-66768bf83dde.png)

fyi @vikasrohit

**Comment by vigneshTheDev** [comment]
So, in the new column, it will be a normal text right? (Not like a tag)

**Comment by maxceem** [comment]
Right, just normal text.

**Comment by maxceem** [comment]
@RishiRajSahu  Done via F2F 30083089 and already in dev.

**Comment by RishiRajSahu** [comment]
Yep, tested it. Closing.
