### ISSUE TITLE
Don't allow to activate project if there is no 'planned` phase

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2805]
From `Connect - UI/UX Enhancements` ducument.

#### Overview
Project plan must have at least one phase in planned status prior to project becoming active
In order to increase adoption of project plans, a project should not be able to be moved into active status until there is at least one phase in planned status.

#### Implementation
- When have any project which is no in `Active` state now.
- When we use a user which has rights to switch project to the active state like `pshah_manger`
- We open dropdown to change state

    ![image](https://user-images.githubusercontent.com/146016/52392270-049bc580-2adc-11e9-99dd-ba40ff372add.png)

- If there is no phase in `Planned` state

   ![image](https://user-images.githubusercontent.com/146016/52392298-21d09400-2adc-11e9-8c48-54afac798bd9.png)

- The option `Active` in the propdown should be disabled. And when we put mouse on it there should be tooltip shown: `To activate project there should be at least one phase in "Planned" status. Please, check "Project Plan" tab.`.

   The hidden option and tooltip should work same as for phase status dropdown:
   
    ![image](https://user-images.githubusercontent.com/146016/52392439-c9e65d00-2adc-11e9-9001-40d7e24ac807.png)

**Comment by RishiRajSahu** [comment]
Done.
