### ISSUE TITLE
should displayed the project name instead of 'Project'

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#281]
### Expected behavior
should display the name of project or text 'project shouldnot be displayed
### Actual behavior
not showing project name 
### Steps to reproduce the problem
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to project dashboard

### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/18933577/1a24d65c-85f3-11e6-91b4-72e243345e0b.png)
e
--

#### Environment
- OS: windows 7
- Browser (w/version): chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by fnisen** [comment]
OK for now. Let's reevaluate when we introduce products.
