### ISSUE TITLE
Enable file attachment edit from the left side bar

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2812]
### Expected behavior
User should be able to edit file attachment name and permissions from the left side bar

### Actual behavior
As of now only option is to update the attachment by going to Scope or Phase Specification tabs.

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by RishiRajSahu** [comment]
Working fine on prod. Closing.
