### ISSUE TITLE
Spurious project members are available in the allowed users dropdown

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2813]
### Expected behavior
Only users who are part of the team of the project, should be available in the dropdown for allowed users setting of a file attachment

### Actual behavior
It shows way more than team members when users comes to the project from the project listing page but when user directly loads the project, it shows only the team members.

### Steps to reproduce the problem
- Open project listing page
- Go to any project which has file attachment enabled
- Try to upload an attachment and notice the users available in the allowed users dropdown

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

**Comment by RishiRajSahu** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/7080f2cbe9a687dcdd79be4b2d038b149989ed01 and Working fine on prod. Closing.
