### ISSUE TITLE
Support latest rc-slider library

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2818]
If we now use the latest rc-slider library our sliders got broken:

![image](https://user-images.githubusercontent.com/146016/52618792-bec76e80-2eda-11e9-8160-0b1cbe3e5e92.png)

See https://connect.topcoder-dev.com/projects/5000/specification

It looks like it's connected with the new changes inside the lib https://github.com/react-component/slider/commit/060d8c6d3785fa19053b9b3c2f8aa716bf335e4e.

While for now we are enforcing usage of the previous library version. We might want to update to the newer version and update our component.

This task might have to be done in https://github.com/appirio-tech/react-components

**Comment by vikasrohit** [comment]
Thanks @maxceem

**Comment by RishiRajSahu** [comment]
@vikasrohit its fixed, right ?

**Comment by vikasrohit** [comment]
Nopes. We reverted the library to older version for the time being.

**Comment by maxceem** [comment]
@vikasrohit maybe we can keep it like this? We use only a small part of that library. It has a lot of features, but we use like a styled radio button instead of a slider. So there are no need to have the latest features/updates of it.

This library also is a candidate for being removed and reimplemented using standard radio buttons and CSS styles. It will save around 24kb of gzipped size of the app as per https://github.com/appirio-tech/connect-app/issues/1629#issuecomment-362572240

**Comment by vikasrohit** [comment]
Makes Sense. Lets close this.
