### ISSUE TITLE
Must display the icons of the Completed, Paused and Cancelled

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#282]
### Expected behavior
-----------------------------------------------------------------
Must display the icons of the Completed, Paused and Cancelled

### Actual behavior
-----------------------------------------------------------------
Project Status icons layout issue

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Dashboard"
- Click Status drop down
- Check the Completed, Paused and Cancelled

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_3-17-42](https://cloud.githubusercontent.com/assets/4592712/18933647/68d83f8c-85f3-11e6-9e90-2d6578ba28cb.png)

#### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by vic-appirio** [comment]
Fixed
