### ISSUE TITLE
'Save Changes' button stays enable on scope/specification

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2827]
### Expected behavior
Once the changes are saved on scope/specification page the save button should be gray-out disabled but its still stays active/blue when there are multiple sections present.

### Actual behavior
The save button stays active even after saving the changes

### Steps to reproduce the problem
1.Edit specification/scope page form with multiple sections
2.'Save Changes' becomes active/blue
3.Save the changes by hitting the button
4.Button is still active/blue
5.If we individually click each section as save then its graying out.

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):any
- Account used: any

**Comment by RishiRajSahu** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
@RishiRajSahu I saw this issue before, but I cannot reproduce it in branch `feature/form-redesign` anymore. Looks like it has been fixed on the way.

There were some changes done `react-components` which may also affect it. So if you test it, please, remove `node_modules` and run `npm i`.

**Comment by RishiRajSahu** [comment]
@maxceem sure I do the needful and test it.

**Comment by RishiRajSahu** [comment]
@maxceem its working fine. Closing.
