### ISSUE TITLE
After clicking Add Link; User must able to scroll the page down in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#283]
### Expected behavior
-----------------------------------------------------------------
After clicking Add Link; User must able to scroll the page down in IE11

### Actual behavior
-----------------------------------------------------------------
User can't scroll down the page after clicking Add Link

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Dashboard"
- Click Add Link
- Scroll the page down

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_3-20-31](https://cloud.githubusercontent.com/assets/4592712/18933763/e08d0f44-85f3-11e6-9d3a-945c0ca584dd.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by vic-appirio** [comment]
Investigate if this is layout issue

**Comment by vic-appirio** [comment]
can't replicate; also the new top navigation fixes should allow full display of the side panel. Closing.
