### ISSUE TITLE
[$50] Remove non team members from auto suggest of user tagging in topics/post

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2836]
### Expected behavior
It should not show any non team member in the dropdown list of auto suggest when posting user tries to tag some one else.

### Actual behavior
As of now, if user navigates from project listing page or any other project, it shows list of all users which were the part of the previous project or all projects listed on the listing page.

### Steps to reproduce the problem
- Open project listing page
- Navigate to any project
- Try to create new post and try tagging a user
- Notice that suggested users contains many users who are not part of the project

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by vikasrohit** [comment]
Fix is something similar to #2813

**Comment by Gauravseta** [comment]
@maxceem can you please assign this to me

**Comment by maxceem** [comment]
@Gauravseta done

**Comment by Gauravseta** [comment]
@maxceem just some more time

**Comment by Gauravseta** [comment]
@maxceem #2866 PR

**Comment by Gauravseta** [comment]
@maxceem PR updated. it will work at all places mentioned above

**Comment by RishiRajSahu** [comment]
Working fine on dev. Closing.
