### ISSUE TITLE
Account Manager role

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2838]
A new Topcoder role needs to be created for Account Managers. This will be a role used by Marketing and Sales team members. This role will:

- Help customers identify who they are talking to during project review and scope change processes

- Send targeted notifications to Account Managers when a project is ready for review/a scope change is requested

<p></p>

Other Requirements:

- This feature will require us to convert appropriate existing Topcoder users to Account Managers.

- By default, this role should receive email communication immediately when a draft project is created in Connect, and when a project is moved from 'Draft' to 'In Review'

- When a Topcoder user joins a project, we should ask them in what role are they joining the project:

  - Account Manager

  - Delivery Manager

  - Copilot

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1671664

**Comment by RishiRajSahu** [comment]
The changes have been merged and working fine in dev.
