### ISSUE TITLE
[$25] Main user avatar is loaded directly from S3 rather than from CloudFront

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2839]
### Expected behavior
Main user avatar is loaded from CloudFront in a small size https://d2nl5eqipnb33q.cloudfront.net/avatar/https%3A%2F%2Ftopcoder-dev-media.s3.amazonaws.com%2Fmember%2Fprofile%2Fpshah_manager-1539702004111.png?size=40 - `40px × 40px - 4kb`

### Actual behavior
Main user avatar is loaded directly from S3 in an original size which can be huge https://topcoder-dev-media.s3.amazonaws.com/member/profile/pshah_manager-1539702004111.png - `4552 px ×  3195px - 19.8Mb`

### Steps to reproduce the problem
Login with user `pshah_manager` which has huge size avatar.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/146016/52788967-8c19a380-309d-11e9-9ba8-2c561a5f5d83.png)

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: `pshah_manager`

**Comment by vikasrohit** [comment]
Good catch @maxceem I was not aware that we can access S3 bucket items dynamically with cloud front because I don't think we have a cloudfront distribution for the `topcoder-dev.media` bucket.

**Comment by maxceem** [comment]
@RishiRajSahu I'm including this issue to CF.

Sum up:
- We should build an avatar URL for this place, same way like we do for other places. Most likely using this function should be enough https://github.com/appirio-tech/connect-app/blob/feature/form-redesign/src/helpers/tcHelpers.js#L28

**Comment by PrakashDurlabhji** [comment]
@maxceem i want to work on this

**Comment by maxceem** [comment]
@PrakashDurlabhji sure

**Comment by PrakashDurlabhji** [comment]
@maxceem actively on it. kindly give some more time. thanks

**Comment by gautam1168** [comment]
@maxceem its been 12 hours on this one. Are you making this open for pickup?

**Comment by maxceem** [comment]
As no PR was raised during 12 hours, this issues is now open for pick up.

Note @gautam1168, please comment after this issue is open for pick up to start working on it, to follow our [Bug Bash rules](https://www.topcoder.com/challenges/30084798)

**Comment by gautam1168** [comment]
Please assign to me

**Comment by maxceem** [comment]
@gautam1168 done

**Comment by gautam1168** [comment]
whats the password for the `pshah_manager` account that is mentioned in this issue description?

**Comment by gautam1168** [comment]
@maxceem please check PR: https://github.com/appirio-tech/connect-app/pull/2868

**Comment by vikasrohit** [comment]
Verified on production. All avatar images are under 400B now.
