### ISSUE TITLE
[Focus] - do not display the focus on selected options

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#284]
Expected behavior
------------------------------------------------------------

- The focus must not be displayed there.

Actual behavior
------------------------------------------------------------

- The focus is displayed on the text options.

Steps to reproduce the problem

------------------------------------------------------------

- Login into application as connect user role.

- Edit any existing project.

- Go to Specification tab section.

- Go to Project Features and select any option.
 
Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: topcoder123!

![fvsd](https://cloud.githubusercontent.com/assets/5114907/18933787/1575105e-85df-11e6-892d-7f5f755386ea.png)

**Comment by fnisen** [comment]
I'm seeing an issue with there being no hover state when you go to turn on a feature: http://screencast.com/t/keWCTkNx

**Comment by vic-appirio** [comment]
This is another issue - hover state on all components to indicate they can be activated (switch component in particular) - we haven't updated this component. I'll create a generic issue for Didi for refactoring if you don't mind @fnisen , and close this one.
