### ISSUE TITLE
Create JSON Schema for project templates validation

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2842]
Currently, we have project templates JSON which have been evaluating for some time.
- We have some old properties which we don't use anymore.
- We have some new properties which partially duplicate old properties but have some additional features.
- It's not easy to remember which properties we have.

There are several ways to handle this situation:
1. Create some documentation.
    - but documentation has a tendency to get redundant very fast 
    - having documentation doesn't guarantee that templates following it
2. Create JSON Schemes for our project templates
    - the best part is that we can automatically validate our project templates by running some script
    - in the perfect implementation, we can built-in template validation into the template editor or even implement autocompletion based on the JSON schema if there is some editor or plugin which supports it.

What do you think @vikasrohit ?

**Comment by vikasrohit** [comment]
Yep, Agreed. We do have a documentation for all the fields which were in use at the time of writing of the doc, however, it suffers from the issue of getting outdated very fast as we are changing the template schema with almost every release to accommodate new changes/features.
I liked the idea of having JSON schema and in fact the new library we are using for creating/editing JSON templates, already supports the schema based validation while creating/editing the template. However, I am not sure how we are going to support backward compatibility with such schema based validations, versioning of schema?

**Comment by maxceem** [comment]
I think we have several ways:
1. Define scheme which covers all the possible properties for all templates if possible.
    - [+] the most easier approach
    - [-] we cannot say which properties we don't wanna use anymore
2. As you suggested having versions for schemes.
    - [+] for sure can support old and new versions
    - [+] we can control which properties we wanna use and which we don't wanna use anymore
    - [-] probably the most complicated way, as we have to define several schemes, probably add the corresponding versioning to templates by themselves. And also editor should somehow support validation of different versions
3. Probably we somehow define in JSON Schema that some properties are deprecated. But looks like this feature is not yet a part of standard as there is open issue with request of this feature https://github.com/json-schema-org/json-schema-spec/issues/74
     - [+] we can define which properties we don't wanna use anymore
     - [-] we will still need to support all variations of preperties in templates
     - [-] as this is not yet a part of standart I'm not sure how to add this feature to validators

So I guess the way with versioning is best for us.

**Comment by vikasrohit** [comment]
Yep, Agreed. Do you think you can take this after the refactoring and versioning of our metadata entities?

**Comment by maxceem** [comment]
Yes, I think I can address it together with the spec for UI editor for templates. As both of these tasks require a detailed overview of the features we have in our templates.

**Comment by maxceem** [comment]
Done in the PR https://github.com/appirio-tech/connect-app/pull/2960

**Comment by lakshmiathreya** [comment]
@RishiRajSahu pls review and mark as Pass.

**Comment by maxceem** [comment]
The schemas are created and technically this task can be marked as done.
Though our intention was to use these schemas to validate project templates in metadata editors:
![image](https://user-images.githubusercontent.com/146016/98962815-ae10b600-250f-11eb-88f2-fc18f7d64c13.png)

Just would like to raise this up so we don't lose our efforts in creating these schemas. Are we still interested in implementing validation during Project Templates editing?

**Comment by vikasrohit** [comment]
Thanks @maxceem for the update. I think yes, we are still interesting in validating the templates while editing. However, I am not sure when we will have approvals for that. Can you please log a separate issue to track those efforts.

**Comment by maxceem** [comment]
Create a follow-up issue https://github.com/appirio-tech/connect-app/issues/4192.

So this issue can be closed.
