### ISSUE TITLE
[$75] File uploading doesn't work

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2845]
### Expected behavior
After drag&drop file it should be uploaded and permission modal shown.

### Actual behavior
After drag&drop file the dialog for file uploading is closed and nothing happenes.

### Steps to reproduce the problem
- Open any project on DEV, for example https://connect.topcoder-dev.com/projects/7885
- Click **Add file** on the left sidebar. The dialog will be opened.
- Drag&drop file to the dialog.
- The dialog will disappear without nothing happened. While in console there will be a warning:
    ```
    Upload in background can be enabled only when transformations are disabled
    ```

### Screenshot/screencast
Attach or link a resource.

-- https://monosnap.com/file/4Hulfpu5Qo8W9Dn9C9zZHP3DPCjo8w

### Possible reason
Looks like this file uploading dialog has been updated recently in `react-components` https://github.com/appirio-tech/react-components/commit/2363173da102d7e69489cfa848dd66a524ee84df

#### Environment
- OS: Mac OS
- Browser (w/version): Chrome
- User role (client, copilot or manager): manager
- Account used: pshah_manager

fyi @RishiRajSahu

**Comment by vikasrohit** [comment]
Good catch @maxceem. It might be a good candidate for our next bug bash.

**Comment by gurmeetb** [comment]
@maxceem can you assign me this ?

**Comment by prasadadarkar30** [comment]
@maxceem assign it to me

**Comment by maxceem** [comment]
@gurmeetb sure, it's on you.

@prasadadarkar30 as this issue was claimed by another member first, it was assigned to him.

**Comment by maxceem** [comment]
Hey @gurmeetb just want to confirm that you are able to reproduce the issue as shown in the video.

**Comment by gurmeetb** [comment]
hey @maxceem still setting up, getting some npm issues, sorting them out...give me few mins, will post update.

**Comment by gurmeetb** [comment]
hey @maxceem finally setup the project and it seems to be working fine.

**Comment by maxceem** [comment]
Hmm, then I think we should put this issue on hold. As it looks like not everybody can reproduce this issue and we don't another way for reproducing it.

Btw @gurmeetb I wonder which issues did have during project setup? As it suppose to work without any issues: 
- clone `connect-app` repo
- run `npm install`
- run `npm start`

**Comment by gurmeetb** [comment]
hey @maxceem it was due to wrong npm version, I was using npm 8.9.4 but since I already had the repo which had already run `npm i` with npm 10, it was giving me dependency issues during `npm start`. Once I cleaned `node_modules` and ran with `npm 10x` it just worked fine. 

Note:☝️ this is not project issue but my local setup issue.

**Comment by maxceem** [comment]
We've finally found out the reason for this issue. It's because I always use an empty file for testing 🤦‍♂️

So I'm closing this issue.
