### ISSUE TITLE
[$10] Plus icon '+' visible even after logout from connect

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2848]
### Expected behavior
Plus icon to create project should not be visible after logging out of connect

### Actual behavior
Plus icon '+' visible even after logout from connect

### Steps to reproduce the problem
-  logout from Connect app
- '+' icon visible in top right corner new login button

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):any
- Account used: any

fyi @maxceem

**Comment by iversonLv** [comment]
@maxceem could I get this ticket?
Thanks.

**Comment by maxceem** [comment]
@iversonLv done

**Comment by iversonLv** [comment]
@maxceem Could you please provide a credential to log in?
I remember there is in readme.md but now there is not.

Thanks.

**Comment by maxceem** [comment]
@iversonLv sure, provided them on the forum https://apps.topcoder.com/forums/?module=Thread&threadID=932185&mc=1#2321547

**Comment by RishiRajSahu** [comment]
Working fine. Closing.
