### ISSUE TITLE
Change button language in sidebar when editing the file or viewers

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2849]
Currently, when a user wants to edit an uploaded file the button displayed a the bottom says "Edit Attachment." This is misleading for customers, as they can both edit the attachment and change the approved file viewers. I would like to update the title and the button label.

<p></p>

Title change: File Viewers (add title over the viewer box)

Please update the button to read: "Save Changes"

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1772884

**Comment by RishiRajSahu** [comment]
Done with https://github.com/appirio-tech/connect-app/commit/fc09282a87ceda16e1631c4e7ac1cad6f066e12c.
