### ISSUE TITLE
after removing the search string all projects must be displayed 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#285]
### Expected behavior

after removing the search string all projects must be displayed 
### Actual behavior

only showing the result after applying search even on removing string
### Steps to reproduce the problem

Steps:
1.) Open the application
2.) Login with username sweta.singh
3. go to project list
4. Search with  3434
5. remove string & press enter
### Screenshot/screencast

![image](https://cloud.githubusercontent.com/assets/16131461/18933901/96800f36-85f4-11e6-9976-338a3b4438f2.png)
## 
#### Environment
- OS: windows 7
- Browser (w/version): chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
Vikas re-assigning this to you since you worked on SearchBar

**Comment by vikasrohit** [comment]
>The only way to change search field value is either:

>Hit enter /click search button
>Click on "x" mark

@vic-appirio I guess, that is what there in dev right now.

**Comment by fnisen** [comment]
@vikasrohit if you manually remove value with keyboard, but don't press enter/search or click on "x" it does not persist. It does persist on Pinterest. Check it out: http://screencast.com/t/N24pHi8TA

**Comment by vikasrohit** [comment]
@fnisen Implemented that behaviour as well for the search bar. Changes are in dev now. Please let me know if you still see any difference.

**Comment by fnisen** [comment]
@vikasrohit, there is one issues/edge case I'm seeing. If I manually delete the search string and click out, the string resets to the original keyword, which is correct. However, if I delete the search string and then hit "Search," nothing happens (because we don't allow blank search), but the string doesn't reset after I click out: http://screencast.com/t/Hqi2KSty0gxv. Can you please accommodate this case? Pinterest gets around it by not having a search button.

**Comment by vikasrohit** [comment]
Done. Changes would be in dev by my EOD.

**Comment by fnisen** [comment]
@vikasrohit it's not working (unless your changes are not yet in Dev). I can still end up in the state where the keyword filter has been applied, but the keyword itself is not shown: http://screencast.com/t/j3Q6mYJBzs2.

**Comment by vikasrohit** [comment]
Yes, my bad. I was hoping that i would be able to deploy latest in dev by my EOD but was stuck in some other issues. I would update the thread again once the latest is deployed on dev.

**Comment by vikasrohit** [comment]
Now deployed and tested in dev environment. :)

**Comment by fnisen** [comment]
Yes, now it's working! : )
