### ISSUE TITLE
[$15] Indicate  'All Project Members' when specified file viewers are removed

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2850]
Once a user has uploaded a file and have specified only specific users as the approved viewers, the user needs a way to modify this selection to change the approved file viewers to 'All Project Members.'

<p></p>

Change: In the left sidebar, if a user decides to change the viewers from specified users to 'All Project Members' they can achieve this by deleting the selected specified users under the File Viewers list. If the user deletes all specified viewers the box should a display the following text, "There are no specified file viewers. File will be visible to all project members."

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1772896

**Comment by maxceem** [comment]
@ajefts as per issue desription we only should add a text if there are no members are selected. But issue title says we should add an additional option to the dropdown. Could you please clarify if adding option to dropdown is still requiered.

Regarding the text, if understand this correctly, the best place to show this text is under:

![image](https://user-images.githubusercontent.com/146016/53315381-cedd4600-38fd-11e9-9961-cc1f7e6e5dcf.png)

Text style:
```
    margin: 10px 0;
    line-height: 120%;
    font-size: 12px;
```

As there is not enough space inside the input where we enter handles and we would loose the hint of what to enter in the field:

![image](https://user-images.githubusercontent.com/146016/53315316-7c9c2500-38fd-11e9-8456-491941161f26.png)

**Comment by vikasrohit** [comment]
@maxceem yes, it seems we need to rephrase the text to accommodate  the space.

**Comment by maxceem** [comment]
@vikasrohit I propose to keep under instead of replacing placeholder. As the placeholder helps users to understand what to enter inside the field. But let me know if you prefer to replace placeholder.

**Comment by vikasrohit** [comment]
Yep, Agreed. I liked the way you suggested here:
![image](https://user-images.githubusercontent.com/146016/53315381-cedd4600-38fd-11e9-9961-cc1f7e6e5dcf.png)

May be we can use some thing like `Visible to All. Enter handles to restrict` as intermediate solution for placeholder text as well. But let us ask the product.

**Comment by RishiRajSahu** [comment]
@maxceem To sumup - 
1. We need 'All Project Members' as an option in dropdown
2. As vikas in the just preceding comment we are good the way you are suggesting, its only the matter of language we are showing is left so let's keep it as `There are no specified file viewers. File will be visible to all project members`, we will update the language once we get new update.

**Comment by maxceem** [comment]
This `All Project Members` option should be only added to suggestions at the sidebar, but not in the dialog after uploading, as we have a separate button

**Comment by RishiRajSahu** [comment]
yeah good point, could we have it consistent at both places ? could you quickly edit it via the dev tools how it will look then ?

**Comment by RishiRajSahu** [comment]
![screen shot 2019-02-26 at 5 58 58 pm](https://user-images.githubusercontent.com/11248478/53412761-4be8e800-39f0-11e9-8230-9fd8ca164323.png)

**Comment by maxceem** [comment]
Something like this:

Dialog:

![image](https://user-images.githubusercontent.com/146016/53412664-ec490780-3a04-11e9-93ab-eb3fcab48751.png)

Sidebar:

![image](https://user-images.githubusercontent.com/146016/53412777-3c27ce80-3a05-11e9-95f0-6762e6cb71ce.png)

The color is dark, because I had to stop JS so the suggestion is not closed on click outiside.

**Comment by maxceem** [comment]
After the discussion with @RishiRajSahu on Slack we come to the next change which has to be done here:
- When some file in the sidebar doesn't have any members selected in **File Viewers** we have to show the text under the field: `There are no specified file viewers. File will be visible to all project members.` as per design:

    ![image](https://user-images.githubusercontent.com/146016/53479692-87e58100-3ab4-11e9-8299-c0f28fff329c.png)

   Text style:
    ```
    margin: 10px 0;
    line-height: 120%;
    font-size: 12px;
    ```
- No other changes discussed above are required.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by rashmi73** [comment]
@maxceem give to me thanks

**Comment by maxceem** [comment]
@rashmi73 done

**Comment by rashmi73** [comment]
@maxceem PR ready #2869

**Comment by rashmi73** [comment]
@maxceem updated

**Comment by RishiRajSahu** [comment]
Done. working fine on dev.
