### ISSUE TITLE
Update "Project Team" to "Customer Team" in left sidebar

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2851]
In the left sidebar, update language of "Project Team" to "Customer Team." This will help to more clearly indicate to Topcoder users where they should be adding themselves and inviting other Topcoder users.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1797297

**Comment by RishiRajSahu** [comment]
Done with https://github.com/appirio-tech/connect-app/commit/2212cd27c1f69d8fdd82c5e07c95826fd590f92b
