### ISSUE TITLE
Remove + requirement for phone numbers

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2853]
Remove the + prefix requirement from the beginning of the phone number on the customer registration form.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1775949

**Comment by maxceem** [comment]
Sum up:
- Registration page is here https://accounts.topcoder-dev.com/connect/registration
- This change has to be done in the repo https://github.com/appirio-tech/react-components/tree/feature/connectv2 branch `feature/connectv2`

**Comment by maxceem** [comment]
@RishiRajSahu When fixing this requirement participant also removed `+` when we select a country code. Which on the one hand good for consistency, but on the other hand could be confusing, see demo video https://monosnap.com/file/0mCuiGhTXs4SRrCsyeMTfPsBSfPkGJ.

How it works now, you can check here https://accounts.topcoder-dev.com/connect/registration

What do you? Should we also not add `+` when we select country code? Or should we add it, but not require?

**Comment by RishiRajSahu** [comment]
@maxceem as per me we are good the existing way.

**Comment by RishiRajSahu** [comment]
Working fine. Closing.
