### ISSUE TITLE
Registration form Continue button is disabled

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2854]
When I enter details on the registration form **Continue** button is not got enabled until I select **I agree to receive other communications from Topcoder.** But it looks like not required. And after I unselect it the **Continue** button stays enabled.

![image](https://user-images.githubusercontent.com/146016/53311881-aea58b00-38ed-11e9-9b71-39837eda1e90.png)

See screencast: https://monosnap.com/file/IYXlOTdu4JXb0WHTUjrBRJG40Y35BG

@RishiRajSahu could please clarify which behaviour is prefered here? Is selectin **I agree to receive other communications from Topcoder.** required? Or should be **Continue** button be enabled even without selecting this checkbox?

**Comment by RishiRajSahu** [comment]
@maxceem yep agree it doesn't seem to be mandatory and as per me it should not affect the continue button, continue button should be dependent on the rest of form fields validations only.

**Comment by maxceem** [comment]
Sum up.
- **Continue** button should become enabled when we fill all required filled, and the last checkbox is not required.
- Most likely there is some issue with form validation process and selecting unselecting the last checkbox just triggers validation update.
- The just has to be done in https://github.com/appirio-tech/react-components/tree/feature/connectv2 repo, branch `feature/connectv2`

**Comment by RishiRajSahu** [comment]
Rephrased agree terms sentence to `I agree to receive marketing communications from Topcoder.` https://github.com/appirio-tech/react-components/commit/21cb49d04dc08a4b6902172a8d904393b90dd44c
