### ISSUE TITLE
[$90] Create test cases which would break our expression evaluation function

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2855]
We have a function which can parse and evaluate simple expression: https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/dependentQuestionsHelper.js#L147

And we covered with test some operations and expression formats https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/dependentQuestionsHelper.spec.js

We need want to make sure our evaluate function is robust and not getting broken in some edge cases. For this purpose we want to do 2 things:
1. [$40] Cover with tests all supported operators which don't have tests yet.
2. [$50] Create new test cases with valid expressions which would break our `evaluate` function.

**Comment by gautam1168** [comment]
please assign this to me

**Comment by maxceem** [comment]
@gautam1168 as you've already commented you can start working on it. To make it clear I've sent you an invitation to the repo, as soon as you accept it I could mark you as assigned.

**Comment by gautam1168** [comment]
Hey should I just push my code to c15 branch?

**Comment by gautam1168** [comment]
Please check PR: https://github.com/appirio-tech/connect-app/pull/2861

**Comment by maxceem** [comment]
@RishiRajSahu we have an extensive set of tests with there are 24 failing test cases and 89 passing ones.

So far this is pushed to a separate branch https://github.com/appirio-tech/connect-app/tree/cf15-evaluate to not break the tests in the main branch.

Most of the test fail, because we don't support literals:
- `Infinity`
- `null`
- `undefined`
- `NaN`
- `true`
- `false`

I guess it's not hard to add them, by pre-populating data with the variables with the same names and values. Rather than implement support of them as keywords inside parser.
```
data = {
   ...data,
  null: null,
  undefined: undefined,
  NaN: NaN,
  Infinity: Infinity,
  true: true,
  false: false,
}
```
This will fix 13 tests and we will have 11 tests failed.

The next class of errors is connected with spaces: we don't accept expressions without spaces like `a+b`.

We don't parse numbers with floating number properly, like `6.5`.

And errors connecting with comparing variables of different types, not sure why they not passed.

Do you wanna fix issues of evalute function in another issues during CF?

**Comment by RishiRajSahu** [comment]
@maxceem that's great, but I would like to not alter the data, instead we can add support of them inside the parser, I will check the commit and test-cases and will get back to you.

**Comment by RishiRajSahu** [comment]
@maxceem the tests looks good, I think we can change `it` to `xit` for the test cases which are failing and will later run a task to get all the `xit` fixed that way we are good to merge to dev. Also, you can create an additional issue to track `xit`

**Comment by maxceem** [comment]
@RishiRajSahu disabled tests and merged to `cf15`. Also, created a follow up issue to pass tests https://github.com/appirio-tech/connect-app/issues/2873

**Comment by RishiRajSahu** [comment]
Closing. Merged to dev.
