### ISSUE TITLE
[$30] Add file button is not shown on the sidebar

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2856]
1. When there are no files uploaded yet, button **+** to upload a file is not shown. But it should be shown if user have rights to upload files.

   - With user `pshah_manager` open project https://connect.topcoder-dev.com/projects/7855, button **+** is shown as expected.

      ![image](https://user-images.githubusercontent.com/146016/53314985-1e227700-38fc-11e9-8783-d3fb96783758.png)

    - With the same user open project https://connect.topcoder-dev.com/projects/7861 - there is not **+** button

        ![image](https://user-images.githubusercontent.com/146016/53315004-2bd7fc80-38fc-11e9-9099-af31e6bae7ce.png)
    
2. In mobile resolution when we open section with uploaded files now we show button with title **Add New Link**. The title should be **Upload File** instead.
     
      ![image](https://user-images.githubusercontent.com/146016/53314859-87ee5100-38fb-11e9-8fd5-5f2cb5ac687f.png)

**Comment by maxceem** [comment]
@RishiRajSahu adding this to CF.

**Comment by vikasrohit** [comment]
> 1. When there are no files uploaded yet, button **+** to upload a file is not shown. But it should be shown if user have rights to upload files.

I think the reason for that is some project are created using a template which does not have a files subsection in their scope template which is what we look for to enable the file upload for a project. So, IMO, the thing to fix would be to remove the `Files` section completely from the left bar if there is not `files` type sub section in the scope template.
I would try to get more details, from product team, about having the file upload section always available for a person who can access that no matter if we have the `files` section in the scope template.

**Comment by maxceem** [comment]
Yeah, look like you are right. [This project](http://local.topcoder-dev.com:3000/projects/5000) doesn't have files uploaded, but it has a **+** button. Note, that we also can upload files from phases so I'm not sure if we should hide it.

**Comment by vikasrohit** [comment]
Yep, I know we can upload the files from the phases but that section is right now available only for managers and copilots, and not for the customers. So, I just don't want to confuse the customers to see + option to upload the file but not find that in Scope section.

**Comment by maxceem** [comment]
@vikasrohit looks like this is an invalid issues and can be closed.

**Comment by vikasrohit** [comment]
@maxceem I think there are two things that needed to handled inn this case:

1. We have to keep the complete file section hidden if there is no files section in project's scope. https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/ProjectInfoContainer.js#L232 is the code which does this, however, I think right now it just removes the `+` button not the complete files section which makes it confusing.

2. We just need to rename the button in mobile view as per original details in the issue:
> In mobile resolution when we open section with uploaded files now we show button with title Add New Link. The title should be Upload File instead.

**Comment by maxceem** [comment]
See the last comment above for the final task.

**Comment by sumitdaga** [comment]
Please assign it to.me thanks

**Comment by maxceem** [comment]
done

**Comment by sumitdaga** [comment]
@maxceem  
Ready for review , PR at #2940

**Comment by RishiRajSahu** [comment]
@maxceem working fine on dev, but on mobile it does nothing when clicking on `Upload File`

**Comment by maxceem** [comment]
@RishiRajSahu fixed in the commit https://github.com/appirio-tech/connect-app/commit/3a3e6b01de733cd83cf06735b31f9fd54425a7e8 in `dev` branch

**Comment by RishiRajSahu** [comment]
working fine !
