### ISSUE TITLE
Must able to the scroll the page without any issue/glitches

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#286]
### Expected behavior
-----------------------------------------------------------------
Must able to the scroll the page without any issue/glitches

### Actual behavior
-----------------------------------------------------------------
Page flickers when user scroll down the page in certain scenario

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Dashboard"
- Scroll the page to the bottom
- Click Add Team Member
- Scroll up the page
- Now try to scroll down the page from mouse wheel or scroll bar

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_3-28-40](https://cloud.githubusercontent.com/assets/4592712/18933956/d8c9ed44-85f4-11e6-869b-4a7c42fa743b.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Known issue #172

**Comment by vic-appirio** [comment]
Closing as duplicate
