### ISSUE TITLE
Hide accordion summary as well when a question becomes hidden

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2862]
When parent question's answer changes which makes a question hidden, it does not hide the accordion summary though.

fyi @maxceem, I have put very minimum details right now. Let me know if you understand this otherwise I can add more details here.

**Comment by maxceem** [comment]
@vikasrohit could you please share a template which you use when experiencing this.

**Comment by vikasrohit** [comment]
You can try with http://local.topcoder-dev.com:3000/new-project/app-new-updated-designs-2. Try to choose Web Browser as one of the target device and then set the answer for progressive/responsive question and follow through all questions further to reach the summary page. Now, go back and remove the Web Browser as device and notice the accordion for progressive/responsive questions and if you try to click on that, it would throw error in console.

**Comment by maxceem** [comment]
Hmm, I couldn't reproduce it, see demo https://monosnap.com/file/zxhR3I91kfTydu3pKDAIEzNSY0jmPY

**Comment by vikasrohit** [comment]
I think this happens because of wrong react-components being referenced in my node_modules. I will verify this once we integrate our changes from your fork in react components to our repo.

**Comment by vikasrohit** [comment]
Closing for now as I am not able to reproduce it. It might be because of wrong react-components in the node_modules.
