### ISSUE TITLE
Error 404: Page not found 

### ISSUE THREAD

**Issue by NehaSharma02** [appirio-tech/connect-app#2865]
Getting 404 error on hyperlink given on text  'Learn more about Connect' on the link: https://connect.topcoder-dev.com/ 

Steps to reproduce the problem
- Click on the link https://connect.topcoder-dev.com/ 
- Click on Learn more about Connect 
- 404 Error page

@RishiRajSahu 
@RiteshTC

**Comment by vikasrohit** [comment]
@NehaSharma02 It is our dev environment and this might not have every thing working always.

**Comment by RiteshTC** [comment]
Dev Environment, not supported.
