### ISSUE TITLE
after applying search if click on Connect logo, should lands user to project listing page 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#287]
### Expected behavior

should lands user to project listing page
### Actual behavior

remain same on search result page
## 

Steps:
1.) Open the application
2.) Login with username sweta.singh
3. go to project listing page
4. Apply search 
5. remove search string from textbox
6. click on Connect icon
### Screenshot/screencast

Attach or link a resource.
## 

![image](https://cloud.githubusercontent.com/assets/16131461/18934020/22c0e010-85f5-11e6-9120-1046407ac770.png)
#### Environment
- OS: windows 7
- Browser (w/version): chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
This is working as per design. Clicking on Connect Logo does not imply resetting search filters.

**Comment by mahestro** [comment]
From a UX stand-point, clicking on the product logo generates a "refreshing" expectation in the user. It would be nice to load the "home" page everytime the logo is clicked. As if you are in project dashboard, click on the logo, it takes you to "home" (project listing).

Sometimes when clicking the logo (being in dashboard) doesn't take you the listing btw. I've experienced it.

**Comment by fnisen** [comment]
@vic-appirio what do you think about this? To me the filters should not be reset... the user may not be expecting that. We should have an explicit reset filters option later.

**Comment by vic-appirio** [comment]
Agree with @mahestro: from a UX perspective clicking on the logo is a "reload homepage" action. Any major website employs this pattern - go search on google/facebook/apple/anywhere, and after clicking the logo you'll go to the home page, resetting the search experience.

**Comment by fnisen** [comment]
@vic-appirio OK, fair point. Let's support this. 

@vikasrohit could you please implement clicking on the logo to take the user to project listings, with filters reset?

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by fnisen** [comment]
Perfect, thanks.
