### ISSUE TITLE
[Dependant questions] - skip subSections when child questions are hidden by condition

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2876]
By current logic when we click `Next` in the creating project wizard we skip sections/subSections/questions which are hidden by condition, but we don’t check if they have visible children inside.

We have to improve this behavior when we click `Next` and next `subSeciton` has all `questions` hidden by condition we should skip such `subSections`.

The case when the next `section` has all `subSections` hidden is not required for now. But if it's quite straightforward to support it also, we can implement both of these.

**Comment by vikasrohit** [comment]
@maxceem this could be a good starting point for educating the community about our template engine for rendering the forms. We would need lot of help in future in this area.

**Comment by maxceem** [comment]
Sure, @vikasrohit would you like to get it via F2F of wait until next Bug Bash?

**Comment by vikasrohit** [comment]
I guess F2F would be better to start with as it would require some learning before actually working on the issue which might go beyond the scope of a bug bash.

**Comment by maxceem** [comment]
F2F is on https://www.topcoder.com/challenges/30085491/?type=develop

**Comment by maxceem** [comment]
@vikasrohit it's done via F2F and pushed to the `feature/form-redesign` branch.

See template http://local.topcoder-dev.com:3000/new-project/skip-empty-steps for demo. It's the template you created without additional subSections conditions (before fix).

**Comment by vikasrohit** [comment]
Verified. Closing.
