### ISSUE TITLE
Must display the 'ADD" button properly

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#288]
### Expected behavior
-----------------------------------------------------------------
Must display the 'ADD" button properly

### Actual behavior
-----------------------------------------------------------------
'ADD" button is half displayed

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Dashboard"
- Scroll the page to the bottom
- Click Add Team Member
- Check the ADD button

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_3-31-58](https://cloud.githubusercontent.com/assets/4592712/18934050/4d7f924c-85f5-11e6-95eb-f6585337940a.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
Missing width settings
![screen shot 2016-10-10 at 1 08 52 pm](https://cloud.githubusercontent.com/assets/8484061/19249499/be9521c4-8eea-11e6-8b6f-6e2c5a078b15.png)
