### ISSUE TITLE
Update Design Review/Final Design Selection language

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2880]
# Overview

> Update submission selection language during the Design Review and Final Design selection milestones to be in-line with delivery process.

<p></p>

# What business need are we solving and why?

> When a customer selects preferred designs during the Design Review, the designs of the unselected submittors (in the challenge) can still be enhanced (i.e. they can still compete). The current language displayed "Selected Designs" and "Rejected Designs" is misleading to customers, as the "Rejected Designs" implies that no additional work (competition) will occur on those rejected designs when in fact the submittors of those rejected designs can still refine their designs and compete for the final design selection.

**Change Description**

- Update "Selected Designs" to read "Checkpoint Winners" 

- Update "Rejected Designs" to read "Other Designs"

<p></p>

**References**

- See attached screenshot

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1811933

**Comment by RishiRajSahu** [comment]
Done with https://github.com/appirio-tech/connect-app/commit/d9af2d6fcf2eb00326a0c72b8886dabbfdb5d0cb
