### ISSUE TITLE
[Dependant questions] - support preparedConditions

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2881]
From @vikasrohit:

If you notice the code for project estimation, https://github.com/appirio-tech/connect-app/blob/dev/src/config/projectWizard/index.js#L519, you would see that we are using a new config called `preparedConditions` which are kind of variables for various conditions and we are using these variables in actual complex conditions. So, I would like to use the same variables when we are evaluating the conditions for show/hide of sections/subsections/questions etc. This would have two benefits:
1. It would evaluate all conditions only once per re-render
2. and more importantly, it would keep all conditions in single place just like we do it in our code

**Comment by maxceem** [comment]
@vikasrohit here is how the current algorithm works:

![conditions dependency](https://user-images.githubusercontent.com/146016/53925930-a226ec80-40bc-11e9-80a2-1403aea1c765.png)

### Current alrogithm:
When any field in the form is changed (means form `data` is changed).

- 1\. Calculate condition `1`. If the value is changed then we update `data`.
- 2\. Calcualte condition `2` using updated `data`. If the value is changed then we update `data.`
- ...
- 10\. Calculate condition `10` using updated `data`.  If the value is changed then we update `data`.

#### Notes
- Condtions may only depend on the condtitions `above` inside the tree.

### New alrogithm:
If we introduce prepared conditions, the algrithm would work like this.
When any field in the form is changed (means form `data` is changed).

- 1\. Check condition `1`
   - if it doesn't have `preparedConditions` inside expression, calculate it. 
   - if it has `preparedConditions` inside expression, **REcalculate** `preparedConditions` first and after we calculate the condition.

   after, if the value is changed we update `data`.
- 2\. Check condition `2`, now it uses updated `data`.
   - if it doesn't have `preparedConditions` inside expression, calculate it using updated `data`.
   - if it has `preparedConditions` inside expression, **REcalculate** `preparedConditions` first using updated `data` and after we calculate the condition using updated `data`.

   after, if the value is changed we update `data`.
- ...
- 10\. ...
- 11\. After conditions for all nodes are calculated we should recalculate all `preparedConditions` with the updated `data` as not all `preparedConditions` was calculated during steps above. As an alternative we can recalculate only `preparedConditions` which hasn't been recalculated during steps above.

#### Notes
- Condtions may only depend on the condtitions `above` inside the tree. `preparedConditions` shouldn't add dependencies which doesn't follow this rule.
- node conditions may refer both `preparedConditions` and form data
- `preparedConditions` **cannot** refer another `preparedConditions` they may refer **only** form data

**Comment by vikasrohit** [comment]
Thanks @maxceem for the detailed notes. However, I have one confusion here.
> 1. Calculate condition 1. If the value is changed then we update data.

I don't think we are updating the data conditionally in our forms. We are just controlling the rendering of the components based on current state of the project data. In other words, we always update the project data as soon as it is changed (assuming that we are always showing only required questions in the form) and there after we just recalculate the conditions of all the components of the template and show/hide them accordingly. So, IMO, if we just recalculate all prepared conditions before evaluating the conditions for all the components of the template, we should be good. This is my interpretation of the our current logic, let me know if I am missing something here.

Also, even though if don't pre calculate the prepared conditions, we can still simplify our template by using the variables introduced in `prerparedConditions` config and just replace the variable with the actual condition mentioned for those variables. This would keep our current algorithm as is while simply the template maintenance.

**Comment by maxceem** [comment]
> if we just recalculate all prepared conditions before evaluating the conditions for all the components of the template, we should be good

The reason for such an approach is to support deep dependencies between fields.

Let's say we have a template JSON where we have 3 questions. The `question2` is shown if the value of `question1` is `true`, and the `question3` is shown when the value of the `question2` is `true`:
```
sections: [{
   subSections: [{
      questions: [{
        fieldName: "question1",
      }, {
        fieldName: "question2",
        condition: "condition2"
      }, {
        fieldName: "question3",
        condition: "condition3"
      }]
   }]
}]
preparedConditions: {
  condition2: "question1 == true"
  condition3: "question2 == true"
}
```

- Imagine at the beginning we have `question1` value is `true` and `question2` value is `true`, then:
   ```
   condition2 is true
   condition3 is true
   ```
   and all the questions are visible.
- Now we change value of the `question1` to `false`
- If we recalculate `preparedConditions` at this moment we will have:
   ```
   condition2 is false
   condition3 is true
   ```
   as a result, `question2` would hidden as expected
   but `question3` will stay visible, but it should be hidden, because if `question2` is hidden, we ignore its value so it's not true.

> Also, even though if don't pre calculate the prepared conditions, we can still simplify our template by using the variables introduced in prerparedConditions config and just replace the variable with the actual condition mentioned for those variables. This would keep our current algorithm as is while simply the template maintenance.

Yeah, this approach would work with our current algorithm. So `preparedConditions` would work like macros or `#define` in C++. We can simply replace `preparedConditions` in all the conditions in template when we load template and after keep the algorithm without changes.

**Comment by vikasrohit** [comment]
Got it. Then I would suggest only to use `preparedConditions` as macros to simply the template management. We can visit it later to improve the performance.

**Comment by maxceem** [comment]
@vikasrohit this is done via https://github.com/appirio-tech/connect-app/pull/2891

**Comment by maxceem** [comment]
@vikasrohit this is already in DEV, probably may be closed.

**Comment by vikasrohit** [comment]
Yes, working  fine. Verified.
