### ISSUE TITLE
TypeError: e.target is undefined - error message is displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#289]
Expected behavior
------------------------------------------------------------

 The error message must not be displayed in page.

Actual behavior
------------------------------------------------------------

The Firebug error message is displayed in page.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager.

- Go to Dashboard tab section.

- Open Firebug Tool application / Developer Tools and check the errors returned,
 
Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

see attach!

![etarget](https://cloud.githubusercontent.com/assets/5114907/18934080/8d7eb91e-85e0-11e6-8700-fea0a335caff.png)

**Comment by mahestro** [comment]
Known issue.
