### ISSUE TITLE
Restrict Copilot view of "Reviewed" projects

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2894]
Current State:

In the 'All Projects' dashboard Copilots have visibility to all projects on which they are participating as well as all projects in 'Reviewed' status, whether they have been invited to those projects or not.

<p></p>

Desired State:

In the 'All Projects' dashboard Copilots have visibility to all projects on which they have been invited and participated. If they have not been invited to a project in Reviewed status, they should not have visibility to it.

<p></p>

Reason for Change:

Per the new Copilot Assignment Manager process to increase Copilot assignment fairness, Copilots who have not been assigned to a project in "Reviewed" status should not be able to see projects in "Reviewed" status.

<p></p>

Change Summary:

- Restrict Copilot view of projects in Reviewed status to only those they have been invited too

- In the 'All Projects' dashboard the Copilot should be able to see all projects to which they have been invited and are participating

- Modify project search bar functionality in the 'All Projects' dashboard by removing the condition where they can be shown projects in Reviewed status

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1821958

**Comment by maxceem** [comment]
@vikasrohit do you prefer to accomplish it client-side only? Means technically copilots still could see these projects by sending a proper request to the project service. Or apply this change at project service too?

**Comment by vikasrohit** [comment]
I would like to get it done via backend changes. It would simplify the access logic in project service which would essentially make project search simple for copilots as well, we can introduce project search for copilots as well after this change.

**Comment by maxceem** [comment]
@vikasrohit

> In the 'All Projects' dashboard the Copilot should be able to see all projects to which they have been invited and are participating

As per requirements copilots should see all the projects listed on dashboard that they are invited too no matter what status is (same like for other users).

> Restrict Copilot view of projects in Reviewed status to only those they have been invited too

Another requirement as I understand related to project datils page. Copilots should be able to access them if they are invited and project in `Reviewed` status.

1. Currently, when a user is invited and clicks on the project to see details, he gets a prompt to confirm the invitation first. It feels that for copilots we should be able to see project details if copilot is invited to the project without accepting invitation.

2. What should happen when copilot clicks in the list project he has been invited to, but project is not in `Reviewed` status?

**Comment by vikasrohit** [comment]
@maxceem I think the language might be slightly confusing here. All we want now is to have the same capability for copilots as we have for customers i.e. copilots can see any project they are part of or are invited to. For invited projects, copilot need to accept the invite as with other users.
If there are cases where you think it is beneficial for a copilot to have a look on the project before accepting a project, please share your feedback with copilot manager or product manager in next Connect feature demo meeting or may be log a separate issue for that. IMO, having the ability to peek into a project before joining it can create much more troubles than the benefits. And, last thing, a copilot can leave the project, if he/she feels that he/she can not work on that project for any reason.

**Comment by maxceem** [comment]
>I think the language might be slightly confusing here. All we want now is to have the same capability for copilots as we have for customers i.e. copilots can see any project they are part of or are invited to. For invited projects, copilot need to accept the invite as with other users.

Thank you! It's clear now.

> And, last thing, a copilot can leave the project, if he/she feels that he/she can not work on that project for any reason.

After a copilot leaves the project he still [stays at as a copilot in the Direct](https://github.com/appirio-tech/connect-app/issues/2807) and should contact support to get unassigned. Otherwise, he would get notifications from Direct.

> Connect feature demo meeting or may be log a separate issue for that

Sure, I'll add this question for the next Copilot meeting.

Thanks

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/tc-project-service/pull/279

**Comment by vikasrohit** [comment]
@maxceem I think this requirement is still missing:
> Modify project search bar functionality in the 'All Projects' dashboard by removing the condition where they can be shown projects in Reviewed status

**Comment by maxceem** [comment]
Oh, yeah, forgot to comment about it. Do we really need this update as copilots still can see projects in `Reviewed` state if they are members of such projects or invited to. Looks like now this state is not differ from any other state filter.

**Comment by vikasrohit** [comment]
Agreed. However, I was under impression that we don't have the search facility for copilots yet. 😬 But I think we enabled that some time back and it skipped from my mind. I think now the requirements seems complete to me. Closing the issue.
