### ISSUE TITLE
Upload and display attachments/pictures in post

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2895]

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1335967

**Comment by maxceem** [comment]
@vikasrohit is there any additional info by provided link https://tcprod.productboard.com/feature-board/planning/features/1335967?

In particular:
1. As I understand we should be able to insert pictures in our posts as usually it works in WYSIWYG editors.
2. Regarding `display attachments` does it mean that we should be able to attach arbitrary files to the posts?

**Comment by vikasrohit** [comment]
Nopes, unfortunately there is no more details from the product board.

However, product team wants the full support of attachments/pictures in posts i.e. just like you said WYSIWYG. However, IMO, that could be tricky in first release of this feature, so I would rather like to start with minimal feature for this which is to just support attaching any document to any post and just show the attachments somewhere in thread/post card which user can download. And then we can start working on embedding few types of documents inline in the content of the post as well.

**Comment by vikasrohit** [comment]
https://www.topcoder.com/challenges/30088008/?type=develop&noncache=true

**Comment by vikasrohit** [comment]
Moving to next release as the front end changes are yet to begin.

**Comment by vikasrohit** [comment]
Feature is implemented and few enhancements are also done after initial change.
