### ISSUE TITLE
[$40] Enable 'Delete' option available for uploaded files

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2896]
Current State:

Users do not have the option to delete a file once it has been uploaded.

<p></p>

Desired State: 

User who has uploaded the file (+ Admins) have the ability to delete the files they have uploaded

<p></p>

Reason for Change:

Users can accidentally upload the incorrect file. They need a way to remove the file from the project.

<p></p>

Change Summary:

- Enable the deletion of files

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1822058

**Comment by maxceem** [comment]
Sum up:
- We have button to delete files on the scope tab, see https://connect.topcoder-dev.com/projects/7959/scope

    ![image](https://user-images.githubusercontent.com/146016/55324980-387ce100-54b6-11e9-91b7-2e53f535445d.png)

- We already show a delete button for links in the sidebar:

    ![image](https://user-images.githubusercontent.com/146016/55325011-59ddcd00-54b6-11e9-88d4-1f10543664d4.png)

- So we also have to show delete button for files in the sidebar if the file has been uploaded by the current user. Admin can see and click delete button for all files.

**Comment by prasadadarkar30** [comment]
kindly give it to me @maxceem

**Comment by maxceem** [comment]
done

**Comment by prasadadarkar30** [comment]
@maxceem opening it because not able to find exact file

**Comment by PrakashDurlabhji** [comment]
@maxceem I am taking this thanks

**Comment by PrakashDurlabhji** [comment]
@maxceem in a while PR will be raised

**Comment by gurmeetb** [comment]
@maxceem can I take this ?

**Comment by gurmeetb** [comment]
@PrakashDurlabhji are you still on it ? 

@maxceem I can take this next 🤔 ?

**Comment by PrakashDurlabhji** [comment]
@gurmeetb sorry i am active on it, few minutes

**Comment by PrakashDurlabhji** [comment]
@maxceem it is done https://github.com/appirio-tech/connect-app/pull/2952

**Comment by PrakashDurlabhji** [comment]
@maxceem PR at https://github.com/appirio-tech/connect-app/pull/2959

**Comment by PrakashDurlabhji** [comment]
@maxceem kindly review it, dont wish to lose my efforts

**Comment by maxceem** [comment]
@PrakashDurlabhji the review is done, please have a look https://github.com/appirio-tech/connect-app/pull/2959

**Comment by PrakashDurlabhji** [comment]
@maxceem MR updated with all points

**Comment by RishiRajSahu** [comment]
working fine.
