### ISSUE TITLE
[$50] Update 'File Upload' UI

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2897]
Current State:

When a user clicks the + button for file uploads in the left sidebar, a space appears where they can either drag/drop the file there or they can click a button 'Add File,' at which time a pop-up (powered by Filestack) appears where they can also drag/drop or they can leverage alternative ways of sharing the file.

<p></p>

Desired State:

I would like the user to have one method of uploading a file. My preference would be that when a user clicks the + button for file uploads the pop-up window (powered by Filestack) appears and the user can manage their upload through that interface. I would like to disable our separate drag & drop option that appears when the + button is clicked in the left sidebar, as well as hide and disable the "Add Files" button. This will result in the user being shown the pop-up screen immediately upon clicking the + button next to files.

<p></p>

Change Summary:

- Hide and disable the "drag & drop" space located in the left sidebar that appears when the user clicks the + button next to Files

- Hide and disable the "Add Files" button shown in this space when the user clicks the + button next to Files

- When a user clicks the + button next to files they should immediately be shown the pop-up window (powered by Filestack) where they can manage their upload.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1822129

**Comment by maxceem** [comment]
@vikasrohit do you prefer only hide the UI elements in the sidebar or also remove it? It looks like we are not going to use it, and just in case could restore it from the repo history.

**Comment by RishiRajSahu** [comment]
@maxceem As per me we can remove them.

**Comment by kevinkid** [comment]
Can i self assign @maxceem ?

**Comment by maxceem** [comment]
As per our current Bug Bash rules for Connect repo https://www.topcoder.com/challenges/30088391 we cannot let members self-assign to the issues.
Instead, as soon as you comment on the issue which is open for pick up it is treated as assigned to you.

To keep it clear, please accept the invitation to this repo which you must get to your email and I'll assign you to this issue to keep it clear.

Thanks.

**Comment by kevinkid** [comment]
okey am working on it

**Comment by maxceem** [comment]
As no PR has been risen for 12 hours and no update provided, this issue is now open for pick up.

**Comment by mfikria** [comment]
@maxceem i want to work on this

**Comment by maxceem** [comment]
Sure, it's on you.

**Comment by mfikria** [comment]
@maxceem resolved in #2949. Note that i've got problem when configure filestack with topcoder cname. seems FILE_PICKER_CNAME url is not reachable (https://monosnap.com/file/V34RQZaxHMPFcL39yCFcpfS84uOOeJ). So you can try to remove it for testing

**Comment by RishiRajSahu** [comment]
Working fine.
