### ISSUE TITLE
Must display the 'Project Updated" message

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#290]
### Expected behavior
-----------------------------------------------------------------
Must display the 'Project Updated" message

### Actual behavior
-----------------------------------------------------------------
Won't display the 'Project Updated" message when user add a team member

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Dashboard"
- Scroll the page to the bottom
- Click Add Team Member
- Check the ADD button

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_3-34-05](https://cloud.githubusercontent.com/assets/4592712/18934107/9d14db5a-85f5-11e6-810a-df5d90ffa0f6.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not expected. Not valid.
