### ISSUE TITLE
[$50] Cannot set property 'utm' of undefined

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2900]
### Expected behavior
Missing data/field should be handled gracefully.

### Actual behavior
Random error is being logged in Sentry:

```
/main.cb1dc01e74604a8bb36f.js in t.value at line 294:6456
/main.cb1dc01e74604a8bb36f.js in Object.i at line 33:4576
/main.cb1dc01e74604a8bb36f.js in s at line 33:2777
/main.cb1dc01e74604a8bb36f.js in Object.executeDispatchesInOrder at line 33:3506
/main.cb1dc01e74604a8bb36f.js in d at line 28:113858
/main.cb1dc01e74604a8bb36f.js in f at line 28:113984
<anonymous> in Array.forEach
/main.cb1dc01e74604a8bb36f.js in e.exports at line 77:295485
/main.cb1dc01e74604a8bb36f.js in Object.processEventQueue at line 28:115388
/main.cb1dc01e74604a8bb36f.js at line 114:27795
/main.cb1dc01e74604a8bb36f.js in Object.handleTopLevel [as _handleTopLevel] at line 114:27817
/main.cb1dc01e74604a8bb36f.js in f at line 114:49978
/main.cb1dc01e74604a8bb36f.js in c.perform at line 28:167821
/main.cb1dc01e74604a8bb36f.js in Object.batchedUpdates at line 114:49458
/main.cb1dc01e74604a8bb36f.js in Object.batchedUpdates at line 28:13803
/main.cb1dc01e74604a8bb36f.js in dispatchEvent at line 114:50759
Called from: raven.js in HTMLDocument.d
```

Exact code snippet from Sentry log details:

```
{snip} Id:r},i=3);var a=this.getRefCodeFromURL();a&&(o.details.utm={code:a}),this.setState({project:(0,d.default)({},o),dirtyProject:(0,d.default)( {snip}
```

User action breadcrumb from Sentry:

```
navigation
to	/new-project/xxxxxxx/incomplete?refCode=xxxxx
from	/new-project/xxxxxx?refCode=xxxxx
13:32:52
xhr
GET https://api.topcoder.com/v4/projects/metadata/orgConfig?filter=orgId=in(2xxxxx5,2xxxxxx1) [200]
13:32:55
ui.click
div.actions > button.tc-btn.tc-btn-default.tc-btn-md
13:32:56
exception
TypeError: Cannot set property 'utm' of undefined

```

--

#### Environment
- OS: Windows 7
- Browser (w/version): Chrome  72.0.3626
- User role (client, copilot or manager): Customer
- Account used: N/A

**Comment by maxceem** [comment]
@vikasrohit yeah, we can try to fix this, though without having a reproducible example we can do it only guessing the root of error, fixing it and waiting if the issue happens again.

**Comment by vikasrohit** [comment]
Yes, essentially all issues reported by Sentry are kind of this nature where  we have to do our best guess using the details shared by Sentry and try to reproduce it on local. Most of the time, we are getting sufficient details from Sentry to reproduce the issue e.g. in this case:


> Exact code snippet from Sentry log details:
> ```
> {snip} Id:r},i=3);var a=this.getRefCodeFromURL();a&&(o.details.utm={code:a}),this.setState({project:(0,d.default)({},o),dirtyProject:(0,d.default)( {snip}
>```
gives us sufficient hint to reproduce it.

**Comment by maxceem** [comment]
Sum up: 
- Looks like line of the error is here https://github.com/appirio-tech/connect-app/blob/dev/src/projects/create/components/ProjectWizard.jsx#L249
For this issue it would the best to do two things:
- find out the possible root of this issue
- instead of hiding the error at the line where this error has been logged, fix the issue as close to the root as possible

**Comment by Gauravseta** [comment]
@maxceem are these going to be open for pickup soon?

**Comment by maxceem** [comment]
@Gauravseta they are still under the consideration, but most likely yes.

**Comment by PrakashDurlabhji** [comment]
@maxceem i will work on this

**Comment by maxceem** [comment]
sure

**Comment by PrakashDurlabhji** [comment]
@maxceem ready https://github.com/appirio-tech/connect-app/pull/2945
