### ISSUE TITLE
[$75] Inviting Topcoder member who is part of customer team is not showing error alert

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2927]
### Expected behavior
When inviting existing project member to team it should show error alert.

### Actual behavior
When inviting existing project member to team is not showing error alert.

### Steps to reproduce the problem
- Invite customer via the email ID
- customer gets the notifications and join the topcoder and the project team
 - Later you decide to add that customer to project team as manager, so try creating invite using handle (as customer is now registered on topcoder and has 'Connect Manager' role), the invite request ends successfully without showing any error alert like 'Team members can't be invited again'

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):manager

**Comment by maxceem** [comment]
It looks like this issues can generalised to the next one:
1. When we invite a member and after we are trying to invite it again in the same dialog, we get an error as expected:

     ![image](https://user-images.githubusercontent.com/146016/55322613-6874b600-54af-11e9-8c3e-68bc04506af9.png)

2. But if we invited one member in one dialog and after we invite a member again in another dialog, we don't get an error (note: we have `pshah_copilot` invited in customer team at them moment):
    
   ![image](https://user-images.githubusercontent.com/146016/55322682-9528cd80-54af-11e9-8a86-cd0a6c574691.png)

3. If user is already a member, we can still invite him to the same team, but we should get an error message `Team members can't be invited again`

   ![image](https://user-images.githubusercontent.com/146016/55322915-25671280-54b0-11e9-915c-86a3c90c71a6.png)

4. We also can invite an existent member to another team, but should get an error message instead:
     (note: we have `pshah_copilot` as a member in customer team at them moment)
   
     ![image](https://user-images.githubusercontent.com/146016/55322990-58a9a180-54b0-11e9-9117-84b96ec4a420.png)

So the case 1 already works. And we should fix cases 2-4 to show error the same way.

**Comment by maxceem** [comment]
@RishiRajSahu I think we can check all these cases client-side and show validation error just inside the popup rather than alert, what do you think?

**Comment by RishiRajSahu** [comment]
@maxceem yep we need to handle the cases mentioned, I too meant the error alert inside the popup(which we are seeing in  **1.**). Feel free to modify the language.

**Comment by omegatao** [comment]
I will take this one

**Comment by maxceem** [comment]
@omegatao it's on you since you commented as per our Bug Bash rules. To keep it clear I can assign you to this issue in the UI. For this, please accept the invitation to this repository which you should get to your email.

**Comment by gurmeetb** [comment]
@maxceem can i pick this up if @omegatao is not able to push PR?

**Comment by omegatao** [comment]
> @maxceem can i pick this up if @omegatao is not able to push PR?

this is harder than I think, according to the rule feel free to take it.

**Comment by gurmeetb** [comment]
@omegato if you are already on it, take some more time to complete it. If not, i will take it. Thanks

**Comment by omegatao** [comment]
@gurmeetb I encountered some trouble setting up the environment, so you can take it now.

**Comment by gurmeetb** [comment]
Thanks @omegatao 

@maxceem can you kindly re-assign this to me?

**Comment by maxceem** [comment]
Thanks for update @omegatao.

It's on you @gurmeetb.

**Comment by gurmeetb** [comment]
Thanks @maxceem, working on it now.

**Comment by gurmeetb** [comment]
@maxceem just to be sure, I think case 1 & 3 are same - isn't it ?

**Comment by maxceem** [comment]
@gurmeetb

They are kind of the same. The idea is if somebody is a member of any kind of team, we shouldn't be able to invite him again in the same team (case 1) or in another team (case 3).

**Comment by gurmeetb** [comment]
@maxceem It’s done and ready for review. It was a lesser code changes but very complex logic internally, see if we can bump prize to at least $100. Thanks

**Comment by maxceem** [comment]
Thank you @gurmeetb. I'll check out if it's possible for this issue during the review.

**Comment by maxceem** [comment]
Hi @gurmeetb 

I've reviewed the PR it works good. Regarding the raising the prize I understand that code related to these dialogs in some places could a little bit tricky to understand so I can raise the prize to $75 for this issue. I guess it's maximum what I can do here as the logic is still quite straightforward - check invitations from both teams instead of one.

Thanks.

**Comment by RishiRajSahu** [comment]
Working good in dev.
