### ISSUE TITLE
Extract expression evaluate method to a separate module

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2932]
Currently, we are having `evaluate` method implemented inside Connect App https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/dependentQuestionsHelper.js

1. As we are going to use it in other repositories we should extract it to a separate repository. This method should be moved together with other helper methods inside https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/dependentQuestionsHelper.js.

2. Another thing that I would like to come back to is should we continue with our code base for this method or move to another implementation of Shunting Yard algorithm used here as we previously discussed here https://github.com/appirio-tech/connect-app/issues/2793.
   For example, for our future needs, we would have to add a new function `mapProperties`:
   ```js
   // we want to check if list of users has a user with id 1
   const data = { members: [{userId: 1, name: 'Joe'}, {userId: 2, name: 'Petr'}] };
   const expression = "(members mapProperties 'userId') contains 1";
   
   evaluate(expression, data); // should return true
   ```
    Our current code of `evaluate` method has some advantages - it supports spaces as separators, while implementation in https://github.com/Calamari/shunting-yard.js doesn't, we have to write exapression without spaces.
    Though what is good about third party `shunting-yard.js` implementation is that it has a good base code to extend for new functionality. For example to add a new method we should write one line of code like:
   ```js
   shuntingYard.addOperator('sqrt', new Operator('sqrt', 1, function(a) { return Math.sqrt(a); }));
   ```
    In our current base code of `evaluate` method we have to update code at 3 places to add a new operator. 

    IMHO, on the long run it would be better to move to that third party `shunting-yard.js` implementation now as it would be easier to add new operators/functions. We would have to clone that repo and fix issues of that lib like supporting spaces to delimit tokens. We can use our current code which already impemented some valuable fetures as reference and move them to the third party lib. As we how tests for out method, I think we can control migrating to the new library quite smoothly.

   Also, that library has some kind of parantsesis balance check which we want to implement for our evaluate version in this issue https://github.com/appirio-tech/connect-app/issues/2903. See tests of the third party lib to check if this behaviour is good for us https://github.com/Calamari/shunting-yard.js/blob/master/test/ShuntingYard.test.js#L90-L96.

@RishiRajSahu @vikasrohit how do you see it from your perspective?

**Comment by vikasrohit** [comment]
Agreed. However, I would like to take care of 2 after we move the evaluator to stand alone library and we update our connect app to use that library and we implement the authorization using the expressions/conditions, in tc-message-service.

Also, just fyi, we do have support for finding an object in an array of JSON objects with JSON query. Please see [this](https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/dependentQuestionsHelper.js#L121) for more details. We are using this feature in template 95 for addon prepared conditions.

**Comment by maxceem** [comment]
> Agreed. However, I would like to take care of 2 after we move the evaluator to stand alone library and we update our connect app to use that library and we implement the authorization using the expressions/conditions, in tc-message-service.

@vikasrohit yeah, makes sense.
Do you think we should create a new repository and extract evaluate methods first for Connect App?

**Comment by vikasrohit** [comment]
Yes, and I would like to get that library accessible via `npm install` command i.e. publish that to the npm repo. I would look for the topcoder npm access and publish that to the npm registry, once we have the scripts for doing that in the new repo.

**Comment by vikasrohit** [comment]
@maxceem created the new repo https://github.com/topcoder-platform/expression-evaluator

Also, just as reference, for the using third party library for expression parsing, I found https://github.com/soney/jsep which might be good alternative as well.

**Comment by maxceem** [comment]
@vikasrohit if https://github.com/soney/jsep library is sufficient for our needs probably we don't have to create our own repository for our implementation. Would you like explore if that library is sufficient for us and move to it instead in such case?

**Comment by vikasrohit** [comment]
I think [jsep](https://github.com/soney/jsep) is only creating expression tree for the expression. I am not sure about this. So, I think we should move with our own repo and then reference that library every where within our applications. We might need to support some addition features for the third library in future, so it is better to keep it abstract via our own library.

**Comment by maxceem** [comment]
Ok, so first we extract and reuse our lib in Connect app and Message Service for permission control. And will come back to evaluate function itself later.

**Comment by maxceem** [comment]
@vikasrohit we extracted evaluate function and use in connect app from npm in PR https://github.com/appirio-tech/connect-app/pull/2995 and already merged to DEV.

**Comment by vikasrohit** [comment]
Thanks for the update.
