### ISSUE TITLE
[$70] Newest message displays at the top of thread

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2934]
Objective: Inverse the order that messages are displayed in a thread, so that the newest message is displayed at the top of the thread and then subsequent messages are displayed in descending order from newest to oldest. The "load earlier messages" button should be moved to the bottom of the thread and will be displayed after the five most-recent messages.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1744834

**Comment by vikasrohit** [comment]
@maxceem let me know if you have any query. I would like to include it in bug bash.

**Comment by maxceem** [comment]
@vikasrohit 

1. where should we keep the field to enter a new post?
   
    ![image](https://user-images.githubusercontent.com/146016/55699787-0fe96f80-59ff-11e9-8122-3034b017b473.png)
    If we keep it at the bottom like it's done now it could be a little bit not comfortable as it would be far from the last message we are responding to.
   Not sure if it would also feel good if we move it up and would response to the latest post which would be under it.

2. Should we make the same change for Phases?
    
     ![image](https://user-images.githubusercontent.com/146016/55699891-6191fa00-59ff-11e9-919c-952afdb33281.png)

3. If we inverse the order, it looks like we would need to move this sticky date to the bottom:

    ![image](https://user-images.githubusercontent.com/146016/55699931-a74ec280-59ff-11e9-851d-324c6dbfde81.png)

4. This also should be changed in the full screen mode
    
     ![image](https://user-images.githubusercontent.com/146016/55699947-c4839100-59ff-11e9-9e95-175d6501c0c1.png)

5. Also, should be changed in mobile resolution: 
    Dashboard posts:
    ![image](https://user-images.githubusercontent.com/146016/55699984-fb59a700-59ff-11e9-8288-58a9f465b2cb.png)

    Dashboard posts (fullscreen):
    ![image](https://user-images.githubusercontent.com/146016/55700013-2fcd6300-5a00-11e9-8348-c4597dec88cc.png)

    Phase posts:
    ![image](https://user-images.githubusercontent.com/146016/55699998-10363a80-5a00-11e9-801b-5875ce4eb912.png)

**Comment by RishiRajSahu** [comment]
@maxceem 
1. Let's keep the text area as it is for now. Still if you could quickly show a mock using browser tool it would be helpful
2. Yes for phases also
3. Why is it required to move at bottom ? I think we can show the date of latest post there, please help me understand if I am missing something here
4. Yes
5. Yes

**Comment by maxceem** [comment]
3. 

![image](https://user-images.githubusercontent.com/146016/56112775-9fa69500-5f8e-11e9-8334-508736560fea.png)

**Comment by maxceem** [comment]
Note, in reversed order we show the date label under the post. Or you mean that we should show the date above the post even in the reserver order?

**Comment by maxceem** [comment]
@RishiRajSahu I think I've overthought, so we can show in such a way with posts in reserved order while keeping dates above the posts:

![image](https://user-images.githubusercontent.com/146016/56113199-be595b80-5f8f-11e9-8ad2-8166397bcce5.png)

**Comment by maxceem** [comment]
Sum up:

We should show posts in reverse order.
Order now: oldest - on the top, newest - on the bottom:
    
![image](https://user-images.githubusercontent.com/146016/56127729-6717b300-5fb0-11e9-9a46-03eccc22d40f.png)

The order we want to achieve: oldest - on the bottom, newest - on the top:
     
![](https://user-images.githubusercontent.com/146016/56113199-be595b80-5f8f-11e9-8ad2-8166397bcce5.png)

We should change the order for all the cases where we show posts:

1. Dashboard (desktop and mobile)

2. Dashboard fullscreen (desktop and mobile) when we click
    
    ![image](https://user-images.githubusercontent.com/146016/56127901-cd043a80-5fb0-11e9-9826-7d66697ab762.png)

3. Phases discussion tab (desktop and mobile)

4. `load earlier posts` should still work for all the cases 1-3 taking into account the new order:

     ![image](https://user-images.githubusercontent.com/146016/56128077-48fe8280-5fb1-11e9-8e6f-3a260768828c.png)

     See project for demo https://connect.topcoder-dev.com/projects/7527

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by gurmeetb** [comment]
plz assign me

**Comment by maxceem** [comment]
done

**Comment by gurmeetb** [comment]
@maxceem this is good chunk of code to understand and re-write in reverse order. Can i get back this MR in by tomm EOD my time, as already heading into day end here?

**Comment by gurmeetb** [comment]
@maxceem it's done and ready for review.

**Comment by maxceem** [comment]
@vikasrohit I've noticed that when we show `New posts` divider now it could mislead:

![image](https://user-images.githubusercontent.com/146016/56481928-15ad7d80-64f4-11e9-9c29-a08d2ff0140b.png)

As new posts are shown above the line now. Should we rephrase the text on the red line to `Old posts`?

**Comment by vikasrohit** [comment]
Good catch @maxceem. I can not come up with any workaround for this as of now. Lets file a issue for this so that we can take a look at it in next release. We will get it clarified with designer and product team.

**Comment by maxceem** [comment]
Created a follow-up issue https://github.com/appirio-tech/connect-app/issues/2975

**Comment by RishiRajSahu** [comment]
except the follow up issue, rest is working fine in dev.
