### ISSUE TITLE
[$35] Segment customer/copilot dashboard by project status

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2935]
Enable customer/copilots to review all of their assigned projects by same segmentation as Topcoder experience, where projects are grouped under the following subsections:

- All Projects

- Draft

- In Review

- Active

- Paused

- Cancelled

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1671992

**Comment by vikasrohit** [comment]
@maxceem I think we already have this feature enabled for copilots now, only thing to take care is the customer view.

**Comment by maxceem** [comment]
Sum up:

Customer users now don't have filters by project statues:

![image](https://user-images.githubusercontent.com/146016/55700200-ecbfbf80-5a00-11e9-9d7b-c99122c1c0a4.png)

They should have filters for project statuses like other users (see green rectangle):

![image](https://user-images.githubusercontent.com/146016/55700250-1bd63100-5a01-11e9-9d46-623a0466be4d.png)

Demo customer user: `pshah_customer`
Demo non-customer user: `pshah_manager`

**Comment by rashmi73** [comment]
@maxceem please give this to me thank you

**Comment by maxceem** [comment]
on you since your comment

**Comment by rashmi73** [comment]
@maxceem few more minutes

**Comment by rashmi73** [comment]
@maxceem ready for review https://github.com/appirio-tech/connect-app/pull/2944

**Comment by rashmi73** [comment]
@maxceem updated MR

**Comment by RishiRajSahu** [comment]
@maxceem we needed the same view as copilots for customer also, could you update as per needed ?

**Comment by maxceem** [comment]
@RishiRajSahu sure, will update

**Comment by maxceem** [comment]
@RishiRajSahu

Should we let customers to switch `My projects`?

**Comment by maxceem** [comment]
@RishiRajSahu done in this commit https://github.com/appirio-tech/connect-app/commit/44479972e0a36cb7494629b9f6d707922f8a60e8

Already in `dev` branch, and deployed to DEV.

**Comment by RishiRajSahu** [comment]
Thanks @maxceem  ! Verified this on dev working as expected. Closing.
