### ISSUE TITLE
[$60] Notification badges on project cards

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2936]
In the all project dashboard, the project card should have notification badges for the following events:

1) The count of new @ mention messages or a new post in a discussion that they have been previously mentioned in.

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1695157

**Comment by vikasrohit** [comment]
@maxceem fyi, this is about showing, on the project listing page, a separate visual cue for projects having any discussions related pending notifications.

**Comment by maxceem** [comment]
@vikasrohit 

We can take into account inside badges next things:
- `notifications.connect.project.topic.created` - new topics
- `notifications.connect.project.post.created` - new posts
- `notifications.connect.project.post.edited` - post edited
- `notifications.connect.project.post.mention` - posts the current user 

So we can form badges based on these notification types. 

But so far we cannot do this:
> The count of a new post in a discussion that they have been previously mentioned in.

We don't have such information inside notifications.

**Comment by vikasrohit** [comment]
> But so far we cannot do this:

>>The count of a new post in a discussion that they have been previously mentioned in.

Could we just show the count of unread notifications for `notifications.connect.project.post.mention` event for the user? Ideally that should represent the desired count.

**Comment by maxceem** [comment]
> Could we just show the count of unread notifications for notifications.connect.project.post.mention event for the user?

yes, we can do like this

> Ideally that should represent the desired count.

agree, but if I'm not mistaken, at the moment we only generate such notification if the user was mentioned in the current (new) post, not in the previous posts in the topic.

**Comment by vikasrohit** [comment]
> , not in the previous posts in the topic.

you mean when a user edits an old post and then mentions the user there?

**Comment by vikasrohit** [comment]
I think the logic is generic and it should work on both create and edit of a post. Even if it is not working for edit of a post for the time being, I am good with for now. We can log a separate issue for that and take care of it in next release.

**Comment by maxceem** [comment]
> you mean when a user edits an old post and then mentions the user there?

I mean regarding this one:
> new post in a discussion that they have been previously mentioned in.

If a user has been mentioned in some post and after some other user creates another post `without` mentioning, as I understand we should still count such new post even though he wasn't mentioned in this new post.

**Comment by vikasrohit** [comment]
That is tricky and I think it might not be always true that if a user is mentioned in one post then he would always be interested in every following up posts as well. If some another use wants the attention, he/she can mention the user again in the new post. That is the way Slack works as well, right?

**Comment by maxceem** [comment]
> That is the way Slack works as well, right?

Right.

Then if we don't need to support such case I think we should be fine with counting `notifications.connect.project.post.mention` notifications.

**Comment by vikasrohit** [comment]
@maxceem we can start on this one in our next bug bash. For designs, we can keep the same red dot, but with this time with a count of mentioned messages in it and place it to the right side of the project card just like we do for phase card.

**Comment by maxceem** [comment]
@vikasrohit just would like to confirm from this:

> @maxceem fyi, this is about showing, on the project listing page, a separate visual cue for projects having any discussions related pending notifications.

Should we count only `notifications.connect.project.post.mention` events? Or all events related to posts and topics, like:
- `notifications.connect.project.topic.created`
- `notifications.connect.project.topic.edited`
- `notifications.connect.project.post.created` 
- `notifications.connect.project.post.edited`
- `notifications.connect.project.post.mention`

**Comment by maxceem** [comment]
Design:

- Circle radius: 32px
- Circle background color: `$tc-red-70` from https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss
- Font: white color, 10px bold Roboto.

Wide (grid):

![image](https://user-images.githubusercontent.com/146016/57507629-885a8d80-7329-11e9-9ac5-30c810335b8e.png)

Narrow (grid):

![image](https://user-images.githubusercontent.com/146016/57507635-8d1f4180-7329-11e9-82d3-0003fad2041f.png)

Mobile (grid):

![image](https://user-images.githubusercontent.com/146016/57507672-9f00e480-7329-11e9-9126-e055557f3a4e.png)

Wide, narrow, mobile (card):

![image](https://user-images.githubusercontent.com/146016/57507737-d2437380-7329-11e9-8382-67cb24c4291f.png)

**Comment by vikasrohit** [comment]
> Should we count only notifications.connect.project.post.mention events? Or all events related to posts and topics, like:

For now we need only `notifications.connect.project.post.mention events` as per requirements, but I think there is sufficient probability of including all the events you mentioned. However, we would do that when required, for now we should be good with only mention event. Just make sure it is easily doable to add more events in future.

Also, Please add a tooltip saying `5 unread messages waiting for you` or more detailed `5 unread messages where you are mentioned`.

**Comment by maxceem** [comment]
We already have a reusable tooltip component which we should reuse here. To see an example open this project https://connect.topcoder-dev.com/projects/8032/plan. And on the **Project Plan** tab, click edit next to the phase and hover mouse on the "In Progress" status value

![image](https://user-images.githubusercontent.com/146016/57563781-420a3a80-73cc-11e9-9a1e-c79aee827540.png)

Here is this place inside the code: https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/PhaseCard/EditStageForm.jsx#L304-L320

Implementation note:
- we should create a reusable component inside https://github.com/appirio-tech/connect-app/tree/dev/src/components folder, which accept two props:
   - the number to show
   - (optional) tooltip text - if tooltip text is not provided tooltip wouldn't be shown
- this component should be reused to show this badge in all the places

**Comment by khushimehta03** [comment]
@maxceem pleaze assign it to me

**Comment by maxceem** [comment]
done

**Comment by khushimehta03** [comment]
@maxceem releasing it for others as unable to solve it, it is open again.

**Comment by rashmi73** [comment]
@maxceem i would work on this thank you

**Comment by rashmi73** [comment]
@maxceem work in progress, may need more than 12 hours as facing difficulty in running npm run build locally.

**Comment by maxceem** [comment]
@rashmi73 it's on you. What type of difficulty you have? We also don't have to run `npm run build` to work locally only `npm start`.

**Comment by rashmi73** [comment]
@maxceem it is completed raising MR, do i need to show component on phasecard or task was just to add component inside components folder?

**Comment by maxceem** [comment]
Yes, this badge has to be shown in project listing in the places shown in this comment https://github.com/appirio-tech/connect-app/issues/2936#issuecomment-491176512

**Comment by rashmi73** [comment]
@maxceem as of now all projects phase card will have badge as conditions are not applied as ticket does not describe it and also i guess requires additional configurations.

**Comment by rashmi73** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3030

**Comment by maxceem** [comment]
> @maxceem as of now all projects phase card will have badge as conditions are not applied as ticket does not describe it and also i guess requires additional configurations.

It's described in several comments. Let me sum up:
- for each project, we should show a count, how many times the user has been mentioned in posts (if user hasn't been mention - we don't show count badge).
- to know how many times user has been mentioned we can count how many notifications with type `notifications.connect.project.post.mention` user have for each project
- all the notifications are loaded inside redux store to `notifications.notifications` https://monosnap.com/file/lNwQJMnsKRUL0FJ6cYKD29c3ecQ9q2
- so first we have to filter all the notifications to count only `not read` yet, we have a method for this `filterReadNotifications` https://github.com/appirio-tech/connect-app/blob/feature/draftjs-link-editor/src/routes/notifications/helpers/notifications.js#L214
- after for each project we can find notifications using method `filterNotificationsByProjectId` https://github.com/appirio-tech/connect-app/blob/feature/draftjs-link-editor/src/routes/notifications/helpers/notifications.js#L225
- and finally, we can count how many notifications of type `notifications.connect.project.post.mention` the project has.
- to create demo notifications for testing I suggest using this project http://local.topcoder-dev.com:3000/projects/8031/plan. Use user `pshah_copilot` and create posts with mentioning user `pshah_manager` After that if you use user `phash_manger` you should see notifications about `mentioning`.

**Comment by rashmi73** [comment]
@maxceem yes working on it completing it

**Comment by rashmi73** [comment]
@maxceem Few more hours and actively working

**Comment by rashmi73** [comment]
@maxceem verification screenshot for notification filtering

![8031_1](https://user-images.githubusercontent.com/41687423/57809265-bc4b0e00-7782-11e9-96a0-fcf434a8d1d6.png)

**Comment by rashmi73** [comment]
@maxceem PR updated

**Comment by vikasrohit** [comment]
Verified.
