### ISSUE TITLE
[Project info] - invitation code text is not readable

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#294]
## Expected behavior
- The text set in Invitation Code field must be visible.
## Actual behavior
- The text set in Invitation Code field is not visible.

Steps to reproduce the problem

---
- Login into application as connect user role.
- New Project.
- App Design & Dev.
- Complete Invite Code field.
## Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![invitation-code](https://cloud.githubusercontent.com/assets/5114907/18934619/74bed906-85e3-11e6-8bc1-fe40aafd38ba.png)

**Comment by mahestro** [comment]
Valid. Should use same style and behavior as the other UI input components above.

**Comment by vic-appirio** [comment]
Fixed
