### ISSUE TITLE
Must validate the white spaces (Blank spaces)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#295]
### Expected behavior
-----------------------------------------------------------------
Must validate the white spaces (Blank spaces)

### Actual behavior
-----------------------------------------------------------------
Can enter spaces as Feature name and description

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Specification"
- Click Add/Edit Features from 'Feature requirements'
- Click 'Add Custom Features'
- Enter spaces
- Click Save Feature

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_3-57-29](https://cloud.githubusercontent.com/assets/4592712/18934702/e474c6f6-85f8-11e6-99bc-648e48d6879a.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev now.
