### ISSUE TITLE
Project timeline summary is not in sync with user selection

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2958]
Project timeline component (`ProjectEstimation`) is showing all phases enabled even if the user has not selected few of the deliverables.
fyi @RishiRajSahu @acshields

**Comment by vikasrohit** [comment]
@maxceem could you please help here? I think somehow the condition evaluation is failing here. My doubt is that it started failing after our changes for using variables for conditions in questions as well.

**Comment by maxceem** [comment]
@vikasrohit fixed and pushed to `dev` branch https://github.com/appirio-tech/connect-app/commit/c271ba6cd15e3f08f388bcdbd9bb86ac4b049ea8. Variables work good, they were not supported in the `ProjectEstimation` component.

**Comment by vikasrohit** [comment]
Got it. Thanks 👍
