### ISSUE TITLE
max length validation must be present on Custom Feature title otherwise its showing aligement  issue

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#296]
### Expected behavior
should have fixed max length char validation
### Actual behavior
showing Ui issue
### Steps to reproduce the problem
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to specifications
5. go to features sevtion
6. add/edit features
7. custom entity 
8. add char more than 300

### Screenshot/screencast

![image](https://cloud.githubusercontent.com/assets/16131461/18934634/8989db46-85f8-11e6-9582-d390930375f2.png)

--

#### Environment
- OS: windows 7
- Browser (w/version):chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
@vic-appirio can you please comment how many characters to impose?

**Comment by parthshah** [comment]
Use elipsis (...) to truncate the title while displaying the title.

**Comment by vic-appirio** [comment]
Let's limit the feature title to 40 characters. It doesn't make sense to have super long names anyway. That's what we have description for. Hiding the title behind ellipsis is not the best solution.

**Comment by vikasrohit** [comment]
@vic-appirio I have put limit on input element which does not show any error/info to the user about the limit. Should we show validation error rather?

**Comment by fnisen** [comment]
I'm good with this approach. @vic-appirio?

**Comment by vic-appirio** [comment]
Having just limit is good enough for the moment. A limit pointer is much better than error message, but we can add that later. Error message is not appropriate.

**Comment by vikasrohit** [comment]
Ok. Done
