### ISSUE TITLE
[$100] Enable editing the name of the milestone even if it is completed

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2969]
### Expected behavior
We should allow editing of text for a milestone even if it is completed.

### Actual behavior
As of now we don't allow updating anything for a completed milestones.

fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
@vikasrohit here are all the fields which we can edit for milestones which are not yet complete:

![image](https://user-images.githubusercontent.com/146016/57503487-83daa880-731a-11e9-9496-b4b09a790e29.png)

Just want to confirm. Which fields should we be able to edit when a milestone is complete?
1. Only `Name`
2. Only `Name` and `Completed text`
3. All fields but `Duration`
4. All fields

**Comment by vikasrohit** [comment]
@maxceem from the screenshot, all fields but `Duration`. Can we put validation on the backend as well for the same?

**Comment by maxceem** [comment]
@vikasrohit sure.

This task has two parts which have to be done: client-side and server-side.

1. [Client-side] We should show edit button for milestones for users who have rights to edit them event after milestone is complete. For example, `pshah_manager` can edit milestones, but `pshah_customer` cannot.
    When a milestone is completed, we can edit all the fields except of`Duration`, in other statuses we should be able to edit all the fields as it's done now.

2. [Server-side] We should add validation server-side.
     - This task has to be done in https://github.com/topcoder-platform/tc-project-service
     - Create a PR against branch `server-cf17` in `tc-project-service`.
     - We should update milestone update endpoint https://github.com/topcoder-platform/tc-project-service/blob/server-cf17/src/routes/milestones/update.js#L65
     - If user is trying to update `duration` field for a milestone which status is `completed` we should return an error code `422`, message `Duration cannot be updated for already completed milestone`.
     - create a unit test which would validate this case

**Comment by PrakashDurlabhji** [comment]
@maxceem I wish to work on this

**Comment by maxceem** [comment]
sure

**Comment by gautam1168** [comment]
@maxceem is this becoming open again?

**Comment by PrakashDurlabhji** [comment]
@maxceem PR in 10 minutes. near to complete it. thank you

**Comment by PrakashDurlabhji** [comment]
@maxceem PR raised at https://github.com/topcoder-platform/tc-project-service/pull/304

not even 10 mins required

**Comment by PrakashDurlabhji** [comment]
@maxceem frontend PR at https://github.com/appirio-tech/connect-app/pull/3025
backend PR at topcoder-platform/tc-project-service#304

Kindly provide feedback if any, everythign is ready

**Comment by maxceem** [comment]
@PrakashDurlabhji I've reviewed both PR. Please have a look.
https://github.com/appirio-tech/connect-app/pull/3025#pullrequestreview-238175828
https://github.com/topcoder-platform/tc-project-service/pull/304#pullrequestreview-238176929
