### ISSUE TITLE
[Messages / IE] - the section is displayed over when move scroll bar to the top

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#297]
Expected behavior
------------------------------------------------------------

- keep sections fixed.

Actual behavior
------------------------------------------------------------

- The section is displayed over when move the scroll bar to the top.

Steps to reproduce the problem

------------------------------------------------------------

- Login into application as copilot role.

- Edit any project.

- Select Messages.

- Use vertical scroll bar and move to the top of page.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: copilot role
Account used: cp-superstar

![ie11](https://cloud.githubusercontent.com/assets/5114907/18934932/58ce1be2-85e5-11e6-800e-5751b2ea28e6.png)

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
Either a CSS or JS issue. Investigate
