### ISSUE TITLE
Don't send notifications about private topics which users don't have access to

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2973]
We introduced Private Topics which are only visible for non-customer users.

But if we create such private topics, customer user will still get notifications about them, even though they don't have access to them and cannot see them:

![image](https://user-images.githubusercontent.com/146016/56482229-8608ce80-64f5-11e9-909e-5804a90f9ac0.png)

I guess we shouldn't create notifications about private topics, customer users don't have access to.

**Comment by vikasrohit** [comment]
This one seems similar to https://github.com/appirio-tech/connect-app/issues/2972, however, I think we need to do some code changes to fix this i.e. I don't think we can get it fixed via config changes only.

Good catch again @maxceem

**Comment by maxceem** [comment]
@vikasrohit this is fixed in https://github.com/topcoder-platform/tc-notifications/pull/117

**Comment by vikasrohit** [comment]
Verified.
