### ISSUE TITLE
Must display the Messages directly; Must not display the 'NEW STATUS POST' section  when we already have posts

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#298]
### Expected behavior
-----------------------------------------------------------------
Must display the Messages directly; Must not display the 'NEW STATUS POST' section  when we already have posts

### Actual behavior
-----------------------------------------------------------------
'NEW STATUS POST' section displayed for few seconds; even though we have posts

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Scroll down and click on a Project name (https://connectv2.topcoder-dev.com/projects/356)
- Click "Messages"
- Add some messages
- Go to "Dashboard"
- Click "Messages"
- Check when loads the page

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_4-14-59](https://cloud.githubusercontent.com/assets/4592712/18935080/59f46556-85fb-11e6-92db-b06277494407.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid. There is a 1s delay while hiding default components.

**Comment by vikasrohit** [comment]
Parth has fixed this with loading indicator fix for #149
