### ISSUE TITLE
[$15] Add hash link to the dashboard topic dates

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2981]
Currently, all the dates of the comments are hash links to these comments so we can share a link to any comment:

![image](https://user-images.githubusercontent.com/146016/56577476-b176e080-65fd-11e9-9315-70c846e44245.png)

We can add the same for the topics on the dashboard, so we could share links to the topics too:

![image](https://user-images.githubusercontent.com/146016/56577548-d8351700-65fd-11e9-9ad8-ab95e2726087.png)

**Comment by vikasrohit** [comment]
Good catch @maxceem

**Comment by maxceem** [comment]
We already have links for topics in the sidebar. So the same links we should add for topics dates:

![image](https://user-images.githubusercontent.com/146016/57503345-ee3f1900-7319-11e9-8627-560677b5fdaa.png)

Here is how we format links for topics: https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/constants/notifications.js#L18

**Comment by sumitdaga** [comment]
@maxceem  please assign it to me?

**Comment by sumitdaga** [comment]
@maxceem  PR at #3022

**Comment by vikasrohit** [comment]
Verified.
