### ISSUE TITLE
[$10] Post menu is covered by "New posts" text

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2984]
When we open a post menu it's shown under the "New posts" text:

![image](https://user-images.githubusercontent.com/146016/56643440-391b2880-66ac-11e9-89bc-b5cc8929deb9.png)

**Comment by sumitdaga** [comment]
@maxceem please assign it t ome

**Comment by maxceem** [comment]
done

**Comment by sumitdaga** [comment]
@maxceem  PR at #3021
