### ISSUE TITLE
[$10] Edit post UI has some extra left padding

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2985]
When we start editing some post on the Dashboard or on the Phase Discussion tab it has some extra padding on the left:

Dashboard:

![image](https://user-images.githubusercontent.com/146016/56643640-94e5b180-66ac-11e9-80db-071afcb90197.png)

Phases:

![image](https://user-images.githubusercontent.com/146016/56643671-a16a0a00-66ac-11e9-855f-9a391ec46596.png)

**Comment by rashmi73** [comment]
@maxceem pls give to me thanks

**Comment by rashmi73** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3023

**Comment by vikasrohit** [comment]
Verified.
