### ISSUE TITLE
[$60] Add more details in error page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2991]
Currently we show the error page whenever the application hit an error situation and user is expected to send an email to support team for the same. However, there is no other information that the user could share with the support team in such cases, which makes debugging the issue difficult.
Purpose of this tasks is to add the actual error details in the page in a way it does not fill the page with technical details and stack trace but still the user is able to copy the error details to share with support team. Couple of ideas:

1. Add button/link say `Copy error details` on the error page which copies the actual error to the clip board of the user. Now user can paste this detail in their support ticket.
2. Add a button say `Send details to support` on the error page which sends the full error details to the support email.

For now, we are inclined towards 1 as quick option to fulfill the requirement.

fyi @acshields

**Comment by vikasrohit** [comment]
@maxceem let me know if you need more details for this.

**Comment by maxceem** [comment]
For option 1:
- should we show any error details? or just a button to copy error details?
- when we copy error details using the button, should we copy only error details, or error details together with error trace?

**Comment by vikasrohit** [comment]
We should show minimum error information directly to the user, so I would like to keep the page as is except a button or link `Copy error details` somewhere on the page which does not disturb the UX. Or may be we can make the support email address a `mailto` link and if we can specify the error details as body of the mail, it can ease(only if the user has a mail client installed) the process of sending details to support.

> when we copy error details using the button, should we copy only error details, or error details together with error trace?

I would like to copy every detail about the error, we can have for the situation.

**Comment by vikasrohit** [comment]
btw, I just noticed that, currently the link of support email is wrong. I think it should be a `mailto` link

**Comment by maxceem** [comment]
Sum up:
- To see an error page we can add a line:
   ```
   return Promise.reject(new Error('demo error'));
   ```
   to https://github.com/appirio-tech/connect-app/blob/dev/src/api/projects.js#L6

   And load projects list http://local.topcoder-dev.com:3000

   ![image](https://user-images.githubusercontent.com/146016/57509118-a5915b00-732d-11e9-9f1e-8590de9fc09e.png)

- We should fix the link for `support@topcoder.com`, it should be `mailto:` as now it's broken:

    ![image](https://user-images.githubusercontent.com/146016/57508961-2e5bc700-732d-11e9-82c7-9a4d3e1b193f.png)

**Next two things we should only do for the error page with code** `500`:

- `support@topcoder.com` link should be a proper email link and when we click it, it should automatically format email subject and body, see [SO](https://stackoverflow.com/questions/4782068/can-i-set-subject-content-of-email-using-mailto)
    - `subject` should be: `Topcoder Connect Issue Report`
    - `body` should contain all the error information we have: error title/message and trace

- Add `Copy error details` button to the error page. Which should put the clipboard: 
   `Topcoder Connect Issue Report` + all the data which we put to the `body` above.

    ![image](https://user-images.githubusercontent.com/146016/57509282-09b41f00-732e-11e9-8c06-ea9faba525fb.png)

**Comment by vikasrohit** [comment]
Good sum up @maxceem Only, query is that why we need to do this only for `500` error? we should be doing this for any error code which renders this page. Isn't it?

**Comment by maxceem** [comment]
@vikasrohit yeah agree, first I thought we don't need such functionality for errors like `404` or `403`, but on the second thoughts if such error is not expected by the user, it would be also good to get details in such case. Updated comment.

**Comment by Gauravseta** [comment]
@maxceem please assign this to me

**Comment by Gauravseta** [comment]
@maxceem some more time as it is bit complicated in handling all case. PR in hour thank you

**Comment by Gauravseta** [comment]
@maxceem open now, do not wish to hold it more so that someone can work on it

**Comment by PrakashDurlabhji** [comment]
@maxceem please assign this to me, beginning work

**Comment by PrakashDurlabhji** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3027

**Comment by vikasrohit** [comment]
@maxceem I can see that the support email link is fixed and we have a button for copying the error details. However, I didn't find any use case where the we can find the actual error details in the copied error text. I know we have to set the full error object in all places wherever we are throwing errors, to get the actual error details, still do we have any case where already have such details?

**Comment by vikasrohit** [comment]
Closing the issue though as per the original requirements and we are already tracking next requirements via #3047

**Comment by maxceem** [comment]
@vikasrohit so far the full error would come only on [Project List page](http://connect.topcoder-dev.com).

To enforce this error for testing we can add a line:
```js
return Promise.reject(new Error('demo error'));
```
to https://github.com/appirio-tech/connect-app/blob/dev/src/api/projects.js#L6

It may come for other cases, but to make sure we should verify all the cases in a separate issue https://github.com/appirio-tech/connect-app/issues/3047

**Comment by vikasrohit** [comment]
Okay, we need to try to reproduce like real world as many errors as we can with #3047 so that we can be sure that what are the details we are able to retrieve from the errors.
