### ISSUE TITLE
Support markdown for various texts in Form components

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2999]
Currently our most of the form component renders the texts (e.g. label of checkbox/radio options etc) as plain text. There are requirements when we need to format some of these texts especially when the texts are very long. We can not support HTML every because it requires dangerously setting inner html of the component. We are doing this for some places, however, we don't want to do this every where in the form components.
So, another option is to support markdown in these texts and if it does not require us to dangerously set inner html of the React components, we should be able to fulfill many of the formatting requirements.

**Comment by vikasrohit** [comment]
@maxceem Let me know you thoughts.

**Comment by maxceem** [comment]
Sure. Are there any example of use cases? Best if designs. So we can define the requirements more precisely?

The reason why I'm asking about particular usage cases is because the ability of markdown are very limited in terms of styling. We can change font style to bold, but we cannot change font size any arbitraty size or change font color. So I'm not sure if markdown would fit all our needs.

**Comment by vikasrohit** [comment]
Yep, makes sense. I am worried about that too, however, I don't want take risk of introducing full fledged HTML inside every text field.
One of use cases which triggered this feature request right now is to show a bulleted list of simple texts to describe the question. As of now, it is not demanding any thing more than that.

**Comment by maxceem** [comment]
> feature request right now is to show a bulleted list of simple texts to describe the question

@vikasrohit could you please, point out which text exactly do you mean here? As we have many types of texts.

**Comment by vikasrohit** [comment]
Majorly it would `description` and new field `introduction` which we are getting added as another task #3000

**Comment by maxceem** [comment]
@vikasrohit Done in the `cf17` branch. It supports the whole markdown syntax, though at the moment have styles only for:
- ordered list
- unordered list
- bold text
- code text

![image](https://user-images.githubusercontent.com/146016/57664283-20a68a00-762a-11e9-9f16-5ffe03c50be9.png)

Please, let me know if any other styles may be needed.

**Comment by vikasrohit** [comment]
Perfect. Thanks @maxceem 

Just for reference, where do you add styles for the supported markdown element? I mean when we have support more markdown elements, what steps we need to take?

**Comment by maxceem** [comment]
Just add more child styles to this class https://github.com/appirio-tech/connect-app/blob/0711473bc1ea70cf03034d8fdc47dedbf11b814b/src/projects/detail/components/SpecQuestionList/SpecQuestionList.scss#L135-L158

**Comment by vikasrohit** [comment]
Thanks. And just to confirm, even if we don't add styles for such new elements, it would still be rendered in the intended way of the element but the it would might not be as per TC styles and might not fit well in our designs e.g. lets say if we don't have style for `ol` in it, and someone adds an `ol` element, it would still show the ordered list but the list might look a not fit to our designs.

**Comment by maxceem** [comment]
It would still render it, but most likely it would look like a regular text without any styles. Though it would depend on the global styles we have and the default styles of the elements in the browser.
Note, we have implemented styles for tag `ol`.

**Comment by vikasrohit** [comment]
> Note, we have implemented styles for tag ol.
Yep, I saw that, just taking a reverse example for better understanding.

**Comment by vikasrohit** [comment]
@maxceem do you have template where you have used the markdown?

**Comment by maxceem** [comment]
@vikasrohit oh, we've removed them recently, though I've created a demo for you https://connect.topcoder-dev.com/new-project/subtitle - check the `What do you need?` question:

![image](https://user-images.githubusercontent.com/146016/58798928-889f2d80-8636-11e9-862d-0d89a7193fd5.png)

**Comment by vikasrohit** [comment]
Thanks. I was just verifying the issue before closing. Working fine.
