### ISSUE TITLE
Need ability to show sub text of form question just below the title

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3000]
As of now we have option to show a sub text (via `description` property) for a question and it is rendered at the last of the question i.e. for checkbox and radio group type questions it is rendered after the options. In cases where the list of options is too long, we might need to render the sub text just below the question title to provide more details about what is expected from the user for the particular question. We have two options to do this:

1. Introduce new sub text (say `subTitle`) and render it just below the question title whenever it is supplied OR
2. Introduce new property (say `descriptionPosition`) for a question and render the description based on this property value (possible values might be `top` and `bottom` for now)

**Comment by maxceem** [comment]
@vikasrohit I'm thinking about adding the second option and calling it `introduction`. So we can add both at the end and at the end if want.

Does it look good? I propose to make it bigger than the description at the end.

![image](https://user-images.githubusercontent.com/146016/57565449-4e9c8c00-73e8-11e9-91ad-888ec82b43d6.png)

**Comment by vikasrohit** [comment]
Looks good. I didn't get what do you mean by size of the field? It is in
JSON, do we need any size parameter?

**Comment by maxceem** [comment]
@vikasrohit I mean the size of the font - how we display it. The description at the bottom we display very small. I think the introduction at the top we should display bigger IMO.

**Comment by vikasrohit** [comment]
Makes complete sense.

**Comment by maxceem** [comment]
This is done and pushed to `cf17` branch.

**Comment by vikasrohit** [comment]
Thanks @maxceem

**Comment by vikasrohit** [comment]
Verified.
