### ISSUE TITLE
[$5] Link in posts don't have blue link color

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3010]
Links in the posts don't have a blue color as links.

![image](https://user-images.githubusercontent.com/146016/57346570-3115bb00-7179-11e9-97f1-a3c2bf54a611.png)

**Comment by prasadadarkar30** [comment]
@maxceem Please give it to me thank you

**Comment by maxceem** [comment]
done

**Comment by prasadadarkar30** [comment]
@maxceem wont be able to complete it hence making it open.

**Comment by rashmi73** [comment]
@maxceem please assign this to me

**Comment by rashmi73** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3024

**Comment by rashmi73** [comment]
@maxceem can you please assign this to me, as I have completed this, as prasad made it open.

**Comment by rashmi73** [comment]
@maxceem any updates here?

**Comment by maxceem** [comment]
@rashmi73 fixed assignment.
