### ISSUE TITLE
[$40] Should not be able mention customers in private posts

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3011]
We have private topics/posts which customers cannot see.

We have the ability to mention users in posts and currently, we still can mention customers in private posts:

![image](https://user-images.githubusercontent.com/146016/57348063-e434e300-717e-11e9-8d37-651c81191203.png)

So customers shouldn't be listed in suggestions for mentioning in private posts.

**Comment by vikasrohit** [comment]
Thanks @maxceem for catching this. Seems valid bug. And I think you need to update the title of the issue to say `Should not` instead of `Should`.

**Comment by maxceem** [comment]
To see private topics, we can open this project https://connect.topcoder-dev.com/projects/7977 using manager user `pshah_manager`.

Users who shouldn't be listed there are the users who have `customer` role in the redux store:
`projectState.project.memebers[]`:

![image](https://user-images.githubusercontent.com/146016/57502975-73293300-7318-11e9-94ec-8beb57355c1b.png)

**Comment by applehit16** [comment]
I'll work on this one

**Comment by applehit16** [comment]
It’s done and ready for review https://github.com/appirio-tech/connect-app/pull/3028

**Comment by vikasrohit** [comment]
Not able to verify as member service is having troubles returning the member data. Closing the issue though as per @maxceem's verification.
