### ISSUE TITLE
Confirmation alert is needed before deleting attachment for a post

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3016]
This is an enhancement for currently in progress feature.

fyi @gondzo @maxceem

**Comment by maxceem** [comment]
We already have a confirmation popup which is shown when we click a button to delete a post:

![image](https://user-images.githubusercontent.com/146016/57667242-6c126580-7635-11e9-8064-7c671d0a7fdf.png)

See demo video https://monosnap.com/file/EuonvMhFY4F34wsudqOG5w6yZa5qPi

We should show a similar confirmation popup when we click a button to delete the attachment from a post. We should adjust the texts of the confirmation popup accordingly:
- title: `Are you sure you want to delete this attachment?`
- text: `This action cannot be undone.`
- buttons: `Cancel` and `Delete Attachment`

See how attachments are deleted now without any confirmation https://monosnap.com/file/FHQqyve1JBzH60Ycyb7Vl5yLJgahwo

The next project may be used for testing: https://connect.topcoder-dev.com/projects/8032

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by gondzo** [comment]
@maxceem one note on this one - the attachment is currently not deleted until you actually save the post, so maybe that should be reflected in the dialog text above? or delete the attachment immediately?

**Comment by maxceem** [comment]
Thanks, @gondzo. Not sure what is the best way here.

@vikasrohit do you have any preferences?

**Comment by PrakashDurlabhji** [comment]
@maxceem can i get to work on this as it was open? thank you

**Comment by maxceem** [comment]
@PrakashDurlabhji it's closed for now as it needs some clarification. It would be opened again as soon as we got details for this issue.

**Comment by vikasrohit** [comment]
Lets leave it out of CF for now. Thanks @gondzo for catching this. I would discuss with team and update the thread.

**Comment by maxceem** [comment]
@vikasrohit this is issue is marked for `Connect 2.4.13` release. Is there any update from the product team on this, or should we move it to the next release?

**Comment by vikasrohit** [comment]
I have asked the question to the PM, would come back to it soon. From my personal understanding, I think we should be good without the confirmation alert because we don't actually deleted the attachment until user clicks the `Save/Update` button after marking the file for deletion.

**Comment by vikasrohit** [comment]
Forgot to update it earlier. Discussed with product manager, we don't need confirmation alert as we don't remove the attachment until user hits Update button.
