### ISSUE TITLE
[$35] User should be able to delete a post attachment without making any change to the text of the post

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3017]
It seems it requires user to do some changes in post's text after user has deleted one or more files. Similarly, I think when user just wants to add more files without updating the text of the post, he/she should be able to do that as well.

fyi @gondzo @maxceem

**Comment by maxceem** [comment]
@vikasrohit It works as expected when we attach a new file as per testing. So we only have to fix this for the case when we delete a file.

When we delete a file attached to the post, the `Update post` button should become active even without making any changes to the post. And clicking the `Update post` button would only apply attachment removing.

See demo video how it works now https://monosnap.com/file/Meiax782BlaqkDCnTrBPYyjqsFsrqc - `Update post` button stays disabled even when I delete some files.

For testing the next project may be used https://connect.topcoder-dev.com/projects/8031

**Comment by maxceem** [comment]
This issue is now open fo pickup.

**Comment by akumar1503** [comment]
@maxceem i would like to work on this.
Thanks.

**Comment by maxceem** [comment]
sure

**Comment by akumar1503** [comment]
created a PR [here](https://github.com/appirio-tech/connect-app/pull/3032), please review.

**Comment by akumar1503** [comment]
@maxceem i have a doubt, please clarify. I have cloned the repo and got dev branch and started working by creating new branch.

Since i need to create PR against cf17 branch, do i had to clone from cf17 branch?

**Comment by maxceem** [comment]
> Since i need to create PR against cf17 branch, do i had to clone from cf17 branch?

Yes. You can still try to create a PR from dev branch which you use to cf17 branch. But if there are any merge conflicts you would need to resolve them.

**Comment by vikasrohit** [comment]
Verified.
