### ISSUE TITLE
Do we need to show the post attachments in the left panel?

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3018]
@acshields @vic-topcoder question for you guys.

**Comment by acshields** [comment]
Yes @vikasrohit

**Comment by vic-topcoder** [comment]
Until we build a new page where people can access all the files and links, yes, we show it.

**Comment by maxceem** [comment]
@vikasrohit should we be able to edit/delete post attachments on the left sidebar? Or should we show them here in read-only mode, same how we do for links from the posts?

**Comment by vikasrohit** [comment]
Let them editable as ideally we want the links to be editable from the left panel as well but we are limited with challenge of updating the link changes to the messages' content. In this case we don't have to change/update the post/message content if some one changes the post attachment from the left panel. So, lets keep them similar to other attachments.

**Comment by maxceem** [comment]
@vikasrohit is it ok if I merge branch https://github.com/appirio-tech/connect-app/tree/feature/list-links-from-posts where we implemented listing links form the posts on the sidebar to the `cf17` branch. So we would have to include that to our release.

The reason for this that most likely we could reuse an accordion component which we use to show links from posts for files from posts.

And just to confirm, that we should show files grouped per posts the same way as we show links. The only difference is that we can edit/delete files on the sidebar.

![](https://user-images.githubusercontent.com/146016/56420836-30a0a780-62d2-11e9-818b-406836b25fc3.png)

**Comment by vikasrohit** [comment]
Agreed on all points @maxceem

**Comment by maxceem** [comment]
Sum up:
- Can use this project for testing http://local.topcoder-dev.com:3000/projects/8031
- We already have implemented functionality to extract links from all the posts and show them on the sidebar like this:
    ![image](https://user-images.githubusercontent.com/146016/57681485-5ebfa000-7662-11e9-8e78-d907de05830a.png)
- We should do the same for files inside posts. We should show them on the sidebar grouped by topics as it's done for links.
- The only difference for files is that we should be able to delete them the same way as it's done for normal files (not from the posts). Note, that methods for deleting attachments for posts and regular files are different.

#### Notes for starting point
- We use component [LinksMenuAccordion](https://github.com/appirio-tech/connect-app/blob/cf17/src/components/LinksMenu/LinksMenuAccordion.jsx#L1) to show links grouped by topics. Most likely you should add the ability to show `delete` button in this component and use it for files.
- We use component [FileLinksMenu](https://github.com/appirio-tech/connect-app/blob/cf17/src/components/LinksMenu/FileLinksMenu.jsx#L25) for showing files

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by amitkumar98** [comment]
@maxceem Please assign this to me.

**Comment by maxceem** [comment]
@amitkumar98 You may start working on the issues since you've commented as per our Bug Bash rules. To keep it clear I would like to mark you assigned to the issue. To do so, please, accept the invitation you should get now to this repository.
Thanks.

**Comment by maxceem** [comment]
As no PR has been raised for 12 hours and no comment provided, this issue is now open for pickup.

**Comment by Gauravseta** [comment]
@maxceem please give this to me thank you

**Comment by maxceem** [comment]
sure

**Comment by Gauravseta** [comment]
@maxceem providing update in few hours.

**The only difference for files is that we should be able to delete them the same way as it's done for normal files**

can you please guide to a project which has such normal files and can be deleted.as confused on delete attachement api calls.

**Comment by maxceem** [comment]
@Gauravseta In this project, there is a file for deleting https://connect.topcoder-dev.com/projects/8031 on the sidebar 

![image](https://user-images.githubusercontent.com/146016/57818705-b7ed1800-77b7-11e9-828f-039f036ae540.png)

Note, that would need to implement the same delete button. But API call would be different. API would be same like when you delete an attachment from the post

![image](https://user-images.githubusercontent.com/146016/57818728-d7844080-77b7-11e9-86bf-f870314c7b80.png)

**Comment by Gauravseta** [comment]
@maxceem releasing it as wont be able to finish it making open.

**Comment by rashmi73** [comment]
@maxceem kindly give it to me thanks

**Comment by maxceem** [comment]
Thank you for update @Gauravseta.

It's' on you @rashmi73.

**Comment by rashmi73** [comment]
@tanks maxceem, work going on

**Comment by maxceem** [comment]
@rashmi73 are you going to complete this issue? Let me know asap, please, or I would have to unassign you.

**Comment by rashmi73** [comment]
@maxceem is this what expected? PR https://github.com/appirio-tech/connect-app/pull/3046

**Comment by maxceem** [comment]
> @maxceem is this what expected? PR #3046

@rashmi73 Provided PR doesn't implement the desired functionality. As Bag Bash time is over and you've only started working on this issue we don't have time to complete it. So I'm unassiging you from the issue for now.

Thanks.

#### Issue details
We have the ability to attach files to the posts. And in this issue, we should show all the files which we attached to the posts on the left sidebar. We should display them on the left sidebar grouped per post. We have posts on the Dashboard and Project Plan tabs.
The similar thing we already for links. We extract links from all the posts and show them on the left sidebar grouped by post like this:

![](https://user-images.githubusercontent.com/146016/57681485-5ebfa000-7662-11e9-8e78-d907de05830a.png)

**Comment by mfikria** [comment]
@maxceem please assign it to me

**Comment by mfikria** [comment]
I create a PR https://github.com/appirio-tech/connect-app/pull/3053. Todo: add delete action

**Comment by maxceem** [comment]
Thanks for update @mfikria. Do you need any feedback now? Or I can review the PR after you implement the delete action functionality?

**Comment by mfikria** [comment]
@maxceem you can review it now without delete functionality

**Comment by vikasrohit** [comment]
Working perfect as per agreed requirements https://github.com/appirio-tech/connect-app/issues/3018#issuecomment-493815637
