### ISSUE TITLE
[$80] Need to show textbox and textinput components in summary screens

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3020]
Just like other form components, We need to render the `textbox` and `textinput` components in summary screen under accordion so that it does not look bad on the summary screen.

**Comment by vikasrohit** [comment]
@maxceem

**Comment by maxceem** [comment]
@vikasrohit is there by chance an example of a project template which has `textbox` and `textinput` components in summary screen? So far I can only find with checkboxes or without a summary screen.

**Comment by vikasrohit** [comment]
@maxceem I have a new one(with id 118) for [example](https://connect.topcoder-dev.com/new-project/api_development_new) and this one is actually the real world use case which we have to push to production in near future.

**Comment by maxceem** [comment]
Sum up:
- We have various form for creating projects
- When we fill some field and click `Next`, fields are displayed in `read-optimized` mode which look like this
   - during editing:

      ![image](https://user-images.githubusercontent.com/146016/57679407-ce7f5c00-765d-11e9-9378-71d91bef5597.png)
  - after we clicked `Next`:

     ![image](https://user-images.githubusercontent.com/146016/57679425-dd660e80-765d-11e9-8bbd-8f0adaf52935.png)
  - you can see how the fields we already filled in are collapsed. You may check this [form](https://connect.topcoder-dev.com/new-project/subtitle) for demo. In this form, all the fields are collapsed when we click `Next`.
- Now we have [another form](https://connect.topcoder-dev.com/new-project/api_development_new). This form has inputs to enter texts one-line `textinput` and multiline `textbox`. They do not collapse after we click `Next`:
    ![image](https://user-images.githubusercontent.com/146016/57679743-aba17780-765e-11e9-9a6b-75ade513d911.png)
- Our task is to add support for collapsing question types `textinput` and `textbox`.

#### Implementation notes
- To collapse fields we use a special [Accordion](https://github.com/appirio-tech/connect-app/blob/feature/draftjs-link-editor/src/projects/detail/components/Accordion/Accordion.jsx#L1) component 
- This `Accordion` component detects what is inside and shows it in a collapsed way. At the moment it supports the next types of questions https://github.com/appirio-tech/connect-app/blob/feature/draftjs-link-editor/src/projects/detail/components/Accordion/Accordion.jsx#L20-L22. So we have to update this component to support two more type of questions.

    The collapsed value for texts should look like this:

     ![image](https://user-images.githubusercontent.com/146016/57680090-6762a700-765f-11e9-95c0-f9b8038e6365.png)

     And when we expand it, it should show the original question, with description, input field and so on, same like for other question types.
- Also, we should update code here https://github.com/appirio-tech/connect-app/blob/feature/draftjs-link-editor/src/projects/detail/components/SpecQuestions.jsx#L333 so the accordion component is applied for the new question types also.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by sumitdaga** [comment]
@maxceem  is it ok if i take this one and leave the other one i am assigned to now ?

**Comment by maxceem** [comment]
@sumitdaga sure, but note, you have to unassign the previous issue before picking up a new one.

**Comment by sumitdaga** [comment]
@maxceem  yes sure, thats what i asked ...leave that and take this one!

**Comment by maxceem** [comment]
done

**Comment by sumitdaga** [comment]
@maxceem  PR at #3034

**Comment by vikasrohit** [comment]
Verified.
