### ISSUE TITLE
Must display the arrow of the drop down with the container

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#303]
### Expected behavior
-----------------------------------------------------------------
Must display the arrow of the drop down with the container

### Actual behavior
-----------------------------------------------------------------
Layout issue in the arrow of the drop down

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Landscape/Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click on the third Column (Latest First)
- Check the arrow

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.
