### ISSUE TITLE
[$100] Attached file is not shown immediately when creating a post

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3031]
When I create a post and attach a file the file is not shown after I click `Post` and post is created. I have to reload the page and after I can see the file I've attached to the post. See demo video: https://monosnap.com/file/9B2cbyBzlLc7oQYE0rmDHZcofUdIaU

@vikasrohit should we include it to the CF?

**Comment by vikasrohit** [comment]
Yes, please and thanks for catching this.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by PrakashDurlabhji** [comment]
@maxceem pls give to me thanks

**Comment by maxceem** [comment]
sure

**Comment by PrakashDurlabhji** [comment]
@maxceem I investigated a lot  with efforts and actually it is not a frontend issue but a backend issue as attachements array is coming blank in reducer 
 
CREATE_PROJECT_FEED_COMMENT_SUCCESS

hence it is not displayed first time.

and when we reload the page, then in LOAD_PROJECT_FEEDS_SUCCESS has that same object of post filled with attachements property.hence we are able to see attachements.

2. coming back to CREATE_PROJECT_FEED_COMMENT, it makes a post call, response of which shall contain attachements property filled, but it is blank hence that is cause of it.

Need some time and extra efforts to solve this and PR need to be raised on backend.

**Comment by maxceem** [comment]
Thank you @PrakashDurlabhji for putting efforts into it, great finding.

@vikasrohit There is an issue with the message service:
- when we create a post with attachments:

   ![image](https://user-images.githubusercontent.com/146016/57741249-8ceac180-76ee-11e9-9dd9-7b9a26432351.png)

   It returns a response of a newly created post without attachments:

   ![image](https://user-images.githubusercontent.com/146016/57741265-a68c0900-76ee-11e9-9c07-18edd2ad4081.png)

- technically we can still fix the issue client-side as we know the ids of attachments we send to the server, se we can use them, even server doesn't return them back. But it's a hacky way and prone to inconsistency between client and server.

- Just would like to confirm, that fixing this issue on the server is the desired way to go.

**Comment by vikasrohit** [comment]
Yes, go with the server side fix.

**Comment by maxceem** [comment]
@PrakashDurlabhji as we need to get it fixed on the backend I'm going to increase the prize for this issue to $100 to cover the increased efforts. Let me know you are intereseted to fix this issue server-side.

**Comment by maxceem** [comment]
@PrakashDurlabhji you should get an invitation to the repo https://github.com/appirio-tech/tc-message-service where the issue could be fixed server-side.

**Comment by PrakashDurlabhji** [comment]
@maxceem yes I am interested in doing it and complete it. thank you

**Comment by PrakashDurlabhji** [comment]
@maxceem need aws account for local deployment of tc-message-service? I went through the https://github.com/appirio-tech/tc-message-service/blob/dev/local/README.md still somewhat confused.

**Comment by maxceem** [comment]
@PrakashDurlabhji could you please, register to this challenge https://www.topcoder.com/challenges/30090720 I've provided the config for the message service on the forum which you can use. I think no AWS account is needed at the moment.

After using that config, follow the guide starting from [Install Dependent Packages](https://github.com/appirio-tech/tc-message-service/blob/dev/local/README.md#install-dependent-packages) and ignore `node ./scripts/createDiscourseWebhookLogTable.js`.

You should be able to start message service locally this way.

let me know if you have any issues on this way.

**Comment by PrakashDurlabhji** [comment]
@maxceem thanks updating in few hours, working

**Comment by PrakashDurlabhji** [comment]
@maxceem able to run locally, with a doubt. PR in few hours.

**Comment by maxceem** [comment]
@PrakashDurlabhji are you going to complete this issue? Let me know asap, please, or I would have to unassign you.

**Comment by PrakashDurlabhji** [comment]
@maxceem yes I will complete this some time

**Comment by maxceem** [comment]
@PrakashDurlabhji Ok, how much do you think you need for this?

**Comment by PrakashDurlabhji** [comment]
@maxceem dont know what is issue suddenly.
it is getting 403 forbidden access even while hitting through postman.

Surely I feel docs provided on challenge forum and on repo are not completed sequentially, nothing is working locally.

**Comment by PrakashDurlabhji** [comment]
@maxceem this read me file does not specify  in detail how to use jwt for different users and other cases.

dont know where am I going wrong.

https://github.com/appirio-tech/tc-message-service/blob/dev/local/README.md#install-dependent-packages

**Comment by PrakashDurlabhji** [comment]
@maxceem i guess locally postgresql db is empty hence getting an error while creating posts with attachmenets via postman.

error getting is 
start request { method: 'POST', url: '/v5/topics/1/posts/create'
relation "topics" does not exist
SequelizeDatabaseError: relation "topics" does not exist

**Comment by maxceem** [comment]
> error getting is
start request { method: 'POST', url: '/v5/topics/1/posts/create'
relation "topics" does not exist
SequelizeDatabaseError: relation "topics" does not exist

@PrakashDurlabhji  You should run these commands from README to create all the tables in DB:
```
NODE_ENV=development npm run migrate
NODE_ENV=test npm run migrate
```

> @maxceem this read me file does not specify in detail how to use jwt for different users and other cases.

You can use JWT token from Connect app. But first, you should do this thing: 
1. In file `/node_modules/tc-core-library-js/lib/auth/verifier.js` add this to line 23:

    ```js
     callback(undefined, decodedToken.payload);
     return;
     ```
2. After that, you can use a token from Connect app, see https://monosnap.com/file/LZ30ATQojrDtJnC6X4gybVEOHZtLI6.

**Comment by maxceem** [comment]
Hi @PrakashDurlabhji do you have any progress with this issue? I can wait 12 hours more, but if it's not completed I would have to unassign you and handle this issue some other way. As we would have to release it soon.

Thanks.

**Comment by PrakashDurlabhji** [comment]
@maxceem i will complete this

**Comment by maxceem** [comment]
Ok, you can have 12 hours more. Issues is still on you.

**Comment by PrakashDurlabhji** [comment]
@maxceem will upate in few minutes if doubt and i did do npm run migrate but issue same

**Comment by PrakashDurlabhji** [comment]
@maxceem I do not find access to https://github.com/appirio-tech/tc-message-service.

Am I removed from the group? though I have repo locally but how will I push the change? just 8 hours are left.

**Comment by PrakashDurlabhji** [comment]
@maxceem mostly found solution but how to push now?

**Comment by maxceem** [comment]
@PrakashDurlabhji Topcoder enabled a restriction for all repositories. So everyone who didn't have 2-factor authorization enabled in their GitHub accounts got removed.

I'll invite you again but it can take some time as I have to contact a Topcoder team to do so.

To speed up the things, please send zip-archive with your submission to my email maxceem@gmail.com.

**Comment by vikasrohit** [comment]
@maxceem any help needed here for setting github permissions?

**Comment by maxceem** [comment]
@vikasrohit yes, could you, please, add `PrakashDurlabhji` again to the `tc-message-service` repository. As has been automatically removed after enabling 2FA for Topcoder repos.

**Comment by vikasrohit** [comment]
Done.

**Comment by maxceem** [comment]
Thank you @vikasrohit 

@PrakashDurlabhji you should get a new invitation for `tc-message-service` repository. To accept it you would have to enable 2-factor authorization for your GitHub account. If you have any problems with this, you can send the zip archive to my email listed above instead.

**Comment by maxceem** [comment]
Hi @PrakashDurlabhji

You can send the submission to my email `maxceem@gmail.com` or try to create a PR to `tc-message-service` as we send you an invitation. I hope you can send your work during the next 12 hours with a complete solution. Unfortunately, we cannot wait longer for this issue.

**Comment by PrakashDurlabhji** [comment]
@maxceem please check PR at https://github.com/appirio-tech/tc-message-service/pull/101

**Comment by maxceem** [comment]
Thank you @PrakashDurlabhji the fix looks great! We will try to deploy it today to the DEV to make e2e testing and make sure there are no drawbacks.

**Comment by maxceem** [comment]
@PrakashDurlabhji I've verified it on DEV and your fix for server-side works great!

There is still some issue left on the Connect now, see video https://monosnap.com/file/gEntEZedkKPGW7ZqobJzdXss9M8efJ

After we create a post with attachments, they are immediately shown in a new post. But now, when I open the dialog they stay there. Could you please have a look?

**Comment by PrakashDurlabhji** [comment]
@maxceem updating it

**Comment by maxceem** [comment]
Thanks, @PrakashDurlabhji. Hopefully, you can submit an update during next 12 hours. If you don't have time it's ok. We can count the work you've already done for this issue and this part we can handle some other way if you don't have time for this now.

**Comment by PrakashDurlabhji** [comment]
@maxceem I will do it as I am keen to complete it. update in few time

**Comment by maxceem** [comment]
Thanks, @PrakashDurlabhji. I also would like you to finish it. But the only restriction we have is time, as so far this issue is moving too slow.

**Comment by maxceem** [comment]
Hi @PrakashDurlabhji

As the second part of the front-end part hasn't been completed, we will handle the front-end part separately.
As you fixed the server-side part, we would still pay here the full amount of the issue stated in the issue $100.

The payment for the issues which you've fixed during the Bug Bash would be processed today.

Thank you.

**Comment by maxceem** [comment]
Note, this issues doesn't have related changes in the Connect app. The fix has been done server-side https://github.com/appirio-tech/tc-message-service/pull/101

**Comment by vikasrohit** [comment]
Verified.
