### ISSUE TITLE
[Specification] Must optimized for the Landscape view

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#304]
### Expected behavior
-----------------------------------------------------------------
[Specification] Must optimized for the Landscape view

### Actual behavior
-----------------------------------------------------------------
Some part of the Specification page is hidden from the screen

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Landscape Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click on a Project
- Check the page

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
iPad testing out of scope. Not valid.
