### ISSUE TITLE
[$60] Hide 403 error page when a user accepts the invite

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3040]
### Expected behavior
User should not see the 403 error page when user accepts the invite to join the project

### Actual behavior
403 error page is flashing for couple of seconds even if the user accepts the invite to join the project.

### Steps to reproduce the problem
- Send invite a user
- Login with invited user
- Try to join the project using the link shared in the notification email or just by clicking the project from the project listing page
- Observe that the 403 error page is flashed for some time even if you have accepted the invite.

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: Any

**Comment by maxceem** [comment]
The most easier way is to use user `pshah_manager` to invite user `pshah_customer` in one browser. And then use user `pshah_customer` to open the same project in another browser and accept the invitation.

See demo video https://monosnap.com/file/PSdj5Z6mPOdEo9O7hwqKdaXou391wd

Note: don't have to create a new project every time. Can just remove user and invite him again.
Can use this project for testing https://connect.topcoder-dev.com/projects/8041

**Comment by maxceem** [comment]
### IMPORTANT

please use branch `master` to work on this issue and create a PR against `master` branch.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by akumar1503** [comment]
@maxceem please assign this to me.
Thanks

**Comment by maxceem** [comment]
sure

**Comment by akumar1503** [comment]
@maxceem need more time, still working on it.

**Comment by akumar1503** [comment]
@maxceem managed to create a PR [here](https://github.com/appirio-tech/connect-app/pull/3043).

The issue was that `showUserInvited` was set to false before sending results to the server finishes successfully, in response to ACCEPT_OR_REFUSE_INVITE_PENDING action.

**Comment by maxceem** [comment]
@akumar1503 thanks, works great!

**Comment by vikasrohit** [comment]
@maxceem could you please upload a video demonstrating the fix? I am afraid that setting the `showUserInvited` flag to true might show the project content while the request is pending for acceptance or rejection.

**Comment by maxceem** [comment]
@vikasrohit here is a demo video where I'm testing using hotfix branch https://github.com/appirio-tech/connect-app/tree/hotfix/invite-403

https://monosnap.com/file/q8b1RG31m5T01JOjCPdC4Rt0jEqr7K

**Comment by vikasrohit** [comment]
Thanks for the video @maxceem. Sorry to trouble you more, but could you please create video of the use case where user rejects to join the project after getting invited?

**Comment by maxceem** [comment]
@vikasrohit here is a demo video when a user cancels the invitation https://monosnap.com/file/EiSAoGcSAstbsMAygaEMczk5aslPLe

**Comment by vikasrohit** [comment]
Thanks @maxceem for capturing the video. It looks good in video, I was just worried about showing any of the project details (even if it is momentarily) when user refuses to join the project because it seems as per change done, to fix the issue, set the flag for showing the project to `true` while the request is still pending. So, I was thinking if somehow the invite refuse request takes bit longer, would it render the project details to the user.
I think we are good as per the video.

**Comment by maxceem** [comment]
@vikasrohit hmm, it feels that it's impossible for a user to see any project data before the invitation is accepted as a user doesn't have permissions for access and backend suppose to return `403`.

**Comment by vikasrohit** [comment]
Verified.
