### ISSUE TITLE
SSO vs. Non-SSO email templates

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3050]
**Objective:** Create two separate email templates (SSO template vs. Non-SSO email template) for when unregistered users are invited to a project.

<p></p>

**Requirements:**

- When an unregistered user is invited to a project with a client who has supported SSO, they should receive an email invitation with SSO registration workflow enabled

- When an unregistered user is invited to a project with a client who does not have SSO, they should receive an email invitation that brings them through the standard platform registration process

- Remove the current email template that is sent to unregistered users when they are invited to a project, which displays both the standard registration flow as well as the SSO registration flow

<p></p>

**Acceptance Testing Plan**

- SSO

- Create a project w/ the REF code (kubik) in dev

- Then invite a member of the org (Ex. Lakshmi) w/ the SSO link

- SSO link should be shown

- Non-SSO

- Create a project in dev without a REF code

- Invite a user

- No SSO should be shown

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2221144

**Comment by RishiRajSahu** [comment]
fyi @vikasrohit @maxceem

**Comment by RishiRajSahu** [comment]
Done and pushed to dev via https://github.com/topcoder-platform/tc-project-service/pull/311 and https://github.com/topcoder-platform/tc-notifications/pull/139 . Need to update env variables when deploying to prod.

**Comment by vikasrohit** [comment]
Released to production.
