### ISSUE TITLE
[$150] Notifications dropdown red cue

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3051]
Currently, when we have some notifications we show red cue next to the notification bell in the top-right corner:

![image](https://user-images.githubusercontent.com/146016/58024390-a3f13f80-7b44-11e9-9911-334e341c8d82.png)

When we open notification dropdown, we remember the time of the last notification and hide red cue:

![image](https://user-images.githubusercontent.com/146016/58024651-46112780-7b45-11e9-9c51-119a2eb71c9b.png)

As soon as in the background some new notifications come, the red cue is shown again as there is newer notification then the time we remember.

The only thing, that we remember the time of the latest notification in the redux store. And if we reload the page, the red cue will be shown again.

See demo video https://monosnap.com/file/dFAvB5JTQsti0I0lzyCIHqPlP9kW9x

As were suggested here https://github.com/appirio-tech/connect-app/issues/3014#issuecomment-493851848 maybe we should remember the time of the latest seen notification in the session storage, to persist the status of the red cue in between page reloads.

**Comment by vikasrohit** [comment]
@acshields we need to discuss this behaviour.

**Comment by vikasrohit** [comment]
@maxceem are we marking any notification as seen as well while hiding the red cue?

**Comment by maxceem** [comment]
@vikasrohit no. By the current logic, we mark notifications as seen when we open the page which mentioned in the notifications link https://github.com/appirio-tech/connect-app/blob/dev/src/components/NotificationsDropdown/NotificationsDropdownContainer.jsx#L46-L52

**Comment by acshields** [comment]
@vikasrohit @maxceem - the suggestion by maxceem seems to make sense to me ("maybe we should remember the time of the latest seen notification in the session storage, to persist the status of the red cue in between page reloads")... @vikasrohit - are there any potential consequences to this that I am not thinking of?

**Comment by vic-topcoder** [comment]
Yes - red dot should be used as a visual cue for "new unread messages". The bell icon uses color to show notifications - it is gray when there are no notifications, and stays white when there are notifications that have not been visited. Hope that makes sense. This is because people don't follow all notifications all the time, and they need a way to discern between new notifications and unread notifications.

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder @acshields for the inputs.

@vic-topcoder so if my understanding is correct:

1. Bell icon is gray when there is no new notification to read
2. Bell icon is white when there is at least one unread notification
3. Bell icon has red cue, when there is at least one unread notification which not seen (we assume all new unread notifications to be seen as soon as user clicks on the Bell icon) yet by the user.

If the above understanding is correct, @maxceem we might need to update the logic to mark all unseen notifications seen when user clicks on the Bell icon after seeing the red cue and mark individual notification as read when the user either explicitly reads the notification. I am not able to understand the need of keeping last seen date in any type of state when we mark all unseen notifications as seen on click of Bell icon as it would automatically persist the state information in terms of unseen/seen flag. And next time when user refreshes the page or even if even if logs in a separate browser, we won't show the red icon as all unseen things are now seen.

**Comment by vic-topcoder** [comment]
@vikasrohit:

> 1. Bell icon is gray when there is no new notification to read

No, the bell icon is gray when there are NO notifications (empty)

> 2. Bell icon is white when there is at least one unread notification

No, the bell icon is white where there are 1+ notifications (already seen, the menu/page has been open), but the notification was not clicked

> 3. Bell icon has red cue, when there is at least one unread notification which not seen (we assume all new unread notifications to be seen as soon as user clicks on the Bell icon) yet by the user.

Correct

**Comment by vikasrohit** [comment]
I am bit confused now @vic-topcoder 

> No, the bell icon is gray when there are NO notifications (empty)

What I meant by `no new notification to read` is that user has marked all notifications as read explicitly or navigated to the target page/object for that notification either by clicking the notification or directly going to the page/object. We don't show read notifications anywhere, but they exists in database. So, If I understand correctly, your `NO notifications (empty)` means empty `view all notifications` page which essentially means that all notifications were marked read implicitly or explicitly.

**Comment by vic-topcoder** [comment]
Yes - in that case, when there ARE notification in the system, but they are SEEN, the bell icon is white

**Comment by maxceem** [comment]
As I understand per the discussion in the next comment is the summary of the desired behavior: https://github.com/appirio-tech/connect-app/issues/3051#issuecomment-498557397

What I'm thinking we can to this summary:
4. In case use opens two tabs and he opened the notification dropdown in one tab which markes all the notifications as seen. If the user now switches to another tab, notifications are still marked as unseen there, thus he would see a red cue. Currently, every minute we are checking for new notifications. I guess what we can do here is - when we are checking for new notifications, we also have to check if there any notifications are marked as `seen` and if so, update notifications in the Redux storage, so they would be marked as `seen` and red cue would disappear in the another tab.

5. > we assume all new unread notifications to be seen as soon as user clicks on the Bell icon

    Just to confirm, in the notifications dropdown, we show not all the notifications. But we would mark ALL the notifications as `seen` when user opens notifications dropdown.

**Comment by vikasrohit** [comment]
> when we are checking for new notifications, we also have to check if there any notifications are marked as seen 

Isn't it doing already? I mean we are fetching the latest notifications from database and if the first tab has made request of marking the notifications as seen, the next call from second tab should bring the notifications with `seen` as `true` and I think if we are showing the red cue by counting the unseen notifications, it should work as is, right?

> Just to confirm, in the notifications dropdown, we show not all the notifications. But we would mark ALL the notifications as seen when user opens notifications dropdown.

Yes, that is what we assume right now. I am not sure how other systems works for this. May be they mark only visible notifications as seen. But I think for simplicity we can mark all notifications as seen for now.

**Comment by maxceem** [comment]
> Isn't it doing already? I mean we are fetching the latest notifications from database and if the first tab has made request of marking the notifications as seen, the next call from second tab should bring the notifications with seen as true and I think if we are showing the red cue by counting the unseen notifications, it should work as is, right?

You are right, we already doing it.

**Comment by maxceem** [comment]
To sum up:
We should replace the current logic of showing red cue for the notification dropdown bell.
The new logic is described in this comment https://github.com/appirio-tech/connect-app/issues/3051#issuecomment-498557397, in particular:

Instead of the current logic, we should show a red cue if there is at least one notification which is not `seen`. 
- As soon as we open the notification dropdown, we mark all the notifications as `seen` inside the redux store and send the request to the server to mark all not `seen` notifications as `seen`. If the request is successful - all good. If the request to the server fails, we should revert the value of the `seen` in the redux store. The intention of this logic to make marking as `seen` working immediately and we don't have to wait for the response from the server. The same logic we already have when marking notifications as `read` so you can check it out for example.
- remove the current logic for showing red cue which is based on the date where we last `seen` this dropdown.

**Comment by Gauravseta** [comment]
@maxceem please give this me. thank you

**Comment by maxceem** [comment]
Sure @Gauravseta

**Comment by Gauravseta** [comment]
@maxceem working more time required

**Comment by maxceem** [comment]
Ok @Gauravseta, but if it's not completed during 24 hours, I'll have to unassign you, as we have wery tight timeline this time.

**Comment by romitgit** [comment]
@maxceem Please assign this to me if available for pick up. Thanks

**Comment by Gauravseta** [comment]
@maxceem i will release it myself if i fail to complete it, but just sometime. please.

@romitgit it is not open yet. i will notify if i fail then whoever comments usually takes it

**Comment by romitgit** [comment]
@Gauravseta No worries. Take your time. Thanks

**Comment by Gauravseta** [comment]
@maxceem releasing it for others as failed. it is open.

**Comment by PrakashDurlabhji** [comment]
@maxceem give to  me thanks

**Comment by maxceem** [comment]
Thanks for not keeping it beyond the need @Gauravseta.

@PrakashDurlabhji assigned it to you.

**Comment by PrakashDurlabhji** [comment]
@maxceem working as bit lengthy

**Comment by maxceem** [comment]
Ok, @PrakashDurlabhji.

**Comment by PrakashDurlabhji** [comment]
@maxceem PR https://github.com/appirio-tech/connect-app/pull/3153

**Comment by maxceem** [comment]
@PrakashDurlabhji please, have look on the review here https://github.com/appirio-tech/connect-app/pull/3153#pullrequestreview-258587066

**Comment by r0hit-gupta** [comment]
@maxceem please let me know if I can pick this up. It's been more than 24 hours since last feedback.

**Comment by PrakashDurlabhji** [comment]
@maxceem sory for delay, I thought it is accepted, few time required.

@r0hit-gupta will open for pickup in few hours if i fail

**Comment by vikasrohit** [comment]
@maxceem could you please summarize the behaviour which we should expect after this fix?

**Comment by maxceem** [comment]
@vikasrohit sure:
- we should see a red cue if there is at least one notification `not seen`
- as soon as we open the drop-down, all the notifications are marked as `seen` in Redux store and thus `red` cue disappears immediately. 
- In the background, we send a request to the server to mark all notifications as `seen`. If request is successful - all good. If requests to the server fail - we revert changes in the Redux and mark notification back as `not seen`, thus `red` cue comes back. Also, we show error popup that we failed to mark notifications as seen.

In general, this logic with applying `seen` status immediately and revert on error is similar to what we have when we mark notifications as `read`.

**Comment by vikasrohit** [comment]
Thanks for the details. In nutshell, once the red cue is gone (assuming successful server call) and user refreshes the page, user won't see the red cue again until next new notification which was not the case before this fix. Correct me if I am wrong.

**Comment by maxceem** [comment]
> Thanks for the details. In nutshell, once the red cue is gone (assuming successful server call) and user refreshes the page, user won't see the red cue again until next new notification which was not the case before this fix. Correct me if I am wrong.

You are correct. Also, red cue may appear again if we get new `not seen` notifications in the background without page reloading.

**Comment by vikasrohit** [comment]
Yep. I meant that by `until next new notification` 😬

**Comment by maxceem** [comment]
Right, `until next new notification` arrive.

**Comment by vikasrohit** [comment]
Working fine on production.
