### ISSUE TITLE
A project is visible in project list page even after user rejected to join the project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3056]
### Expected behavior
The project should not be visible on the project listing page once the user has denied to join the project on the Join Project modal.

### Actual behavior
A customer user (it might be true for another users as well) can see the project on the project listing page even if he/she denied to join the project on the Join Project modal.

### Steps to reproduce the problem
- Invite a customer user to a project using a manager account.
- Open the project (via project listing or direct project link) using the invited customer login
- Click on the `Cancel` button when prompted to join the project
- Observe that the project is still visible on the listing page where user is redirected after denying to join the project

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Customer (but might be true for other user types as well)
- Account used: N/A

**Comment by vikasrohit** [comment]
@maxceem @RishiRajSahu fyi

**Comment by maxceem** [comment]
Here is a demo video of the issue https://monosnap.com/file/sRqvpx0Tsy9vAqaBx9E5EXRtdB3Bm1

@vikasrohit do you think if we reload the project list when we click Cancel on the invitation, would it be a good solution? As an alternative, we can just update data in Redux store without project list reloading. But it feels that in this case reloading project list would be much robust and solid solution.

**Comment by vikasrohit** [comment]
I would be okay with page reload if that solves the problem, but for me it didn't flush the project from the listing page even after page reload. :(

**Comment by maxceem** [comment]
@vikasrohit I cannot reproduce the issues after reloading. As soon I reload the page, the project disappears from the list. See demo video https://monosnap.com/file/PckHp5fgriLx82J7rZ6cRtRvMTly2Y

Could you share any details like users you used for testing? Maybe video?

**Comment by vikasrohit** [comment]
Okay, it might be intermittent issue with ES indexing I guess. I have to debug more into logs to get more details. Will try today to get details today.

**Comment by vikasrohit** [comment]
Closing. Not able to test the issue fully because member api is not returning the results for member invites. However, it seems good because server side issue is already fixed and in case of user refusing the invite, we already reload the project listing page, which is the only pending items from the related issue #3059
