### ISSUE TITLE
Need support for mathematical expression for building block prices/time estimates

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3057]
As of now we store the building blocks in following structure:

```
{
"conditions": "( HAS_DEV_DELIVERABLE && (ONLY_ONE_OS_MOBILE || ONLY_ONE_OS_DESKTOP || ONLY_ONE_OS_PROGRESSIVE) && SCREENS_COUNT_SMALL && CA_NOT_NEEDED)",
      "price": 1000,
      "minTime": 35,
      "maxTime": 35,
      "metadata": {
        "deliverable": "dev-qa"
      }
}
```

Now when we calculate the overall estimate for the project, we just add the `price` field of all the building blocks which are allowed to stack together and whose conditions are satisfied. 

The new requirement is to have notion of `quantity` per building block i.e. there are possibilities of having more than one building block selected for a project. Quantity would be recorded via new UI element (most probably a dropdown). However, the problem is that building block is not represented on the UI as single element where we can ask the quantity for it. Rather a building block is identified when questions of the forms are answered in a way which satisfy its conditions. On the other side, this quantity can recorded via a dropdown for an add-on because addon is represented in single UI block and we can ask for its quantity easily in the UI. Using the quantity for add-ons is the primary task.
On further, analysis of requirement it appeared that we might need to either show a quantity option for our standard questions in the smart forms OR just use any another questions's answer to calculate the final price estimate for the particular building block so the building block representation might turn into something like

```
{
      "conditions": ...,
      "price": '1000 * details.testingDetails.testCount/100',
      "minTime": 35,
      "maxTime": 35,
      "metadata": {
        "deliverable": "dev-qa"
      }
}
```
The above price estimate says we would charge 1000 bucks per 100 test cases.

So, in nutshell, if we can achieve specifying formula in the `price` field of the building block json, I think we can achieve `quantity` feature for standard questions and add-ons both and we would have a generic way to specify the formula for price and time efforts.

**Comment by vikasrohit** [comment]
@maxceem @RishiRajSahu  fyi

**Comment by maxceem** [comment]
@vikasrohit done in the next PR https://github.com/appirio-tech/connect-app/pull/3060

I used a copy of the project template `95` "New app - updated design 2". Here is my copy with changed condition for testing: http://local.topcoder-dev.com:3000/new-project/subtitle
As I don't see any numeric questions so far I've used `templateId` to format the price expression 😁  

![image](https://user-images.githubusercontent.com/146016/58379752-8ad00f00-7fda-11e9-9c86-b879130c61a3.png)

So as you see I've updated price for `ZEPLIN_APP_ADDON_CA` add-on, and it's evaluted correctly to `611.7`.

And the total price is shown correctly:

![image](https://user-images.githubusercontent.com/146016/58379769-cbc82380-7fda-11e9-93c1-345c8a1fb721.png)

**Comment by vikasrohit** [comment]
Working as per current requirements.
