### ISSUE TITLE
Must not reset the "What would you like to do?" when we select a device from "Pick target device(s)"

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#306]
### Expected behavior
-----------------------------------------------------------------
Must not reset the "What would you like to do?" when we select a device from "Pick target device(s)"

### Actual behavior
-----------------------------------------------------------------
Selected data in "What would you like to do?" resets when we select a device from "Pick target device(s)"

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click '+ New Project'
- Select: What would you like to do? --> Prototype an app
- Select: Phone, Tablet --> Pick target device(s)
- Check the 'What would you like to do? '

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_7-04-23](https://cloud.githubusercontent.com/assets/4592712/18938017/041c8812-8613-11e6-96a4-2170afd433c4.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
True, IE. Valid.

**Comment by parthshah** [comment]
Downgrading this since this is IE specific. Vikas I am re-assigning this to me.

**Comment by vikasrohit** [comment]
@parthshah seems like you forgot to assign the issue. :)
