### ISSUE TITLE
Attached files stay in the create post UI

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3065]
After we create a post with attachments and open a dialog to create another new post, the previously attached files are still listed there.

![image](https://user-images.githubusercontent.com/146016/58451960-2a5ee000-8148-11e9-8215-e1cd66bd77e1.png)

See video https://monosnap.com/file/gEntEZedkKPGW7ZqobJzdXss9M8efJ

Follow up from https://github.com/appirio-tech/connect-app/issues/3031

**Comment by vikasrohit** [comment]
Working fine. Closing.
