### ISSUE TITLE
Need to support quantity for addons

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3067]
As of now, user can not specify the quantity of add-ons when configuring the project. We need to add support to let user choose multiple quantity per add-on and calculate the total price as per the quantity selected by user per addon.

**Comment by maxceem** [comment]
As now you've implemented pretty much the same what I was thinking about in you commit https://github.com/appirio-tech/connect-app/commit/79fc9b9ef4b0ce67e9d17abe28424afff2917531#diff-bcfd7970e8edc78f9946daa468a139a5

To be able to define it per `add-on` we should add ths `allowMultiple` property to each productTemplate object which represents add-on.

There are several ways to do it, which come to my mind:
1. Add a new `allowMultiple` property to the `productTemplate`. This feels like not a good solution as we also use `productTemplate` model for product templates which don't need this param.
2. Add a new `allowMultiple` property to the root of JSON inside `template` property - this sounds like a good and simple solution.
3. We can go feature and generalize add-ons quantity to any set of form fields per add-on.
     The idea is next. Do we use `template` inside `add-ons` anywhere? Or are we going to use it?
     If not, we can define a form per `add-on` inside `template` and render it for each selected `add-on`. So for now, such a form inside `template` would only contain `quantity` question to select the quantity. But potentially, we could add any form to configure particular add-on as we need. This is just an idea, not sure if it makes sense for our future plans.

**Comment by maxceem** [comment]
There is some issue in the current implementation, I'm getting error when I use the template https://connect.topcoder-dev.com/new-project/subtitle and trying to choose any add-on.

![image](https://user-images.githubusercontent.com/146016/58606351-a20a4780-82cd-11e9-885f-3ff82dfded80.png)

I've made a quick fix in the next commit https://github.com/appirio-tech/connect-app/commit/eef5e38823917195b8635706116b220d29f350be

**Comment by vikasrohit** [comment]
Thanks @maxceem for the fix and its good to have that fix in place. However, ideally code should not land into that place because if an addon is selected then only our logic [here](https://github.com/appirio-tech/connect-app/blob/eef5e38823917195b8635706116b220d29f350be/src/config/projectWizard/index.js#L594) would filter that addon block and if a block is filtered out, we should be able to find it in [addonsData](https://github.com/appirio-tech/connect-app/blob/eef5e38823917195b8635706116b220d29f350be/src/config/projectWizard/index.js#L601).

**Comment by vikasrohit** [comment]
Just made one more safe check https://github.com/appirio-tech/connect-app/commit/644c40a9e8b47628bd66889706849a29b7068c5f

**Comment by vikasrohit** [comment]
Done, closing the issue.
