### ISSUE TITLE
Messages: changes "Messages" to "Discussions"

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#307]
Let's move to using the term "Discussions" instead of "Messages" to match the term currently used in the TC forums (also, messages connote private communication). Can you please change it in the all the places highlighted below? 

The composer should say "New Discussion Post" and the placeholder copy should be: "Start a new discussion topic with the team."

<img width="1273" alt="2016-09-28_1831" src="https://cloud.githubusercontent.com/assets/12552247/18937997/2c6dd474-85aa-11e6-8b6b-a5132132b70d.png">

**Comment by vikasrohit** [comment]
Done copy changes(pending for merge because of bug hunt). Changed the url(/messages => /discussions) as well to reflect the same nomenclature.

**Comment by vikasrohit** [comment]
Changes are in dev.
