### ISSUE TITLE
[Metadata Management] New Metadata object route opens the login route for some time

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3071]
### Expected behavior
It should not render the login page/route when user is already logged in.

### Actual behavior
Login page is shown for some time while user is navigated to the new metadata screen (e.g. New project type).

I have faced the issue with New project type screen as of now, but the issue might be there for other new metadata objects as well e.g. New product categories, new project/product template.

**Comment by maxceem** [comment]
@vikasrohit it's fixed and pushed to DEV. The issue was only with the create new Project Type page.

**Comment by vikasrohit** [comment]
Verified.
