### ISSUE TITLE
Disabled project templates are still rendering the form

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3079]
### Expected behavior
Disabled project templates should not render the form. Ideally they should show 404.

### Actual behavior
They have not effect as of now

fyi @maxceem

**Comment by maxceem** [comment]
For example. This link let us create a project with project template `computer_vision_old` which is disabled https://connect.topcoder-dev.com/new-project/computer_vision_old, see 
https://monosnap.com/file/NSquUHoMZBdeqFrIZTDdqCIew4bC6F

If we try to access link to create a project with a project template which is `disabled` we should see page `404`.

**Comment by RishiRajSahu** [comment]
@maxceem have put a fix via this https://github.com/topcoder-platform/tc-project-service/commit/2d12e1cf670c0db8f484196f4abbb568a7ec7b3c

**Comment by RishiRajSahu** [comment]
it seems the fix didn't worked. strange, will check it again.

**Comment by RishiRajSahu** [comment]
Its fixed and pushed to dev.
