### ISSUE TITLE
Private posts are rendered after all non private posts

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3081]
@maxceem @RishiRajSahu I am not sure if this is intended and as per requirements or not.

**Comment by maxceem** [comment]
We did this as it looks so in provided designs, though I'm also not sure if it's good that new private posts come after the old public posts at the moment.

**Comment by acshields** [comment]
@vic-topcoder - I will let you make the final call on this one. I could understand the user benefit in either of the following scenarios:
1) Keep all discussion threads displayed in chronological (most recent discussion) order, regardless of whether they are internal or public.
2) Separating out the display of messages into two categories, interval vs. public, and displaying the messages in chronological order (most recent discussions) within each section. 


For this, what ever you think would be best is what I would like to go with.

**Comment by vic-topcoder** [comment]
Private and public posts should not be discriminated when the feed order is created. Correct behavior is to order the threads by most recent, and split them by unread and all the rest. I would think of separating them in the future as a secondary filter on the view, but not right now.

<img width="1274" alt="Screen Shot 2019-06-03 at 10 22 09 AM" src="https://user-images.githubusercontent.com/8484061/58821274-8e225680-85e9-11e9-8ffb-fcc1ace964bf.png">

**Comment by vikasrohit** [comment]
Thanks @acshields @vic-topcoder for the input. @maxceem I think we are good now with requirements, we need not to separate the private posts from public posts and they should be displayed in their usual chronological order. So, we can include this as quick fix for next CF.
Anyway, we are improving the UI of discussions in #3012 so at that time, we would have the filter for showing only admin posts as @vic-topcoder suggested above.

**Comment by maxceem** [comment]
@vikasrohit As we are implementing this in a new design via https://github.com/appirio-tech/connect-app/issues/3012 I guess we can close this issue.
