### ISSUE TITLE
DraftJs Link Plugin: make all the links inside pasted text as links

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3085]
If we paste text link `text http://some-link.com text http://some-other-link.com text` the links inside such text would stay as a text, see demo video https://monosnap.com/file/t4rxTe7goJX4NtzksncHYbv4oa0k6V. 

### The expected behavior:
- all links inside text should become links (primary, most important task)
- show the small popup for adding a title to the latest link in the text (secondary task)

**Comment by vikasrohit** [comment]
Verified on production after patch.
