### ISSUE TITLE
[$60] Need to update the project type icons after new smart of forms

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3088]
For most of the new type of projects, we are showing the generic work icons
<img width="419" alt="Screen Shot 2019-06-06 at 11 25 41 AM" src="https://user-images.githubusercontent.com/2417632/59010128-db066700-884d-11e9-854d-cb0d4a203b9e.png">
We need to fix the icons to reflect the correct project type. We might need to update the icon in the catalog as well to best match the description of the new project type.

fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
@vikasrohit here is a list of supported icon types https://github.com/appirio-tech/connect-app/blob/master/src/components/ProjectTypeIcon.jsx#L51-L115

If the icon is not found, the fallback is to the standard icon.

**Comment by vikasrohit** [comment]
@maxceem I think I have set correct values for the `icon` field of the project template as per mapping you shared, but still it is showing the generic icon. Could you please check in dev if you can see icons as we set in project templates?

**Comment by maxceem** [comment]
Can reproduce the issue.

Use for example project https://connect.topcoder-dev.com/projects/8179
It uses a template with id `212 `. Which uses icon `product-design-app-visual`:

![image](https://user-images.githubusercontent.com/146016/60569426-f491c480-9da1-11e9-9588-1be80fc16e61.png)

This icon is defined in the https://github.com/appirio-tech/connect-app/blob/master/src/components/ProjectTypeIcon.jsx#L51-L115 and should look like:

![image](https://user-images.githubusercontent.com/146016/60569463-0c694880-9da2-11e9-8789-68a978eed32a.png)

But in the project listing, it is shown as default icon:

![image](https://user-images.githubusercontent.com/146016/60569523-2f93f800-9da2-11e9-81a5-787bccadd995.png)

Also, we can define icons as a path (for backward compatibility).
For example, this project https://connect.topcoder-dev.com/projects/8178 uses templated with id `7`. Which uses icon `../../assets/icons/product-design-app-visual.svg`:

![image](https://user-images.githubusercontent.com/146016/60569719-91ecf880-9da2-11e9-8942-fc5eb5dc89c5.png)

This is the same icon as above but defined as a path. But on the project list it is also shown as a default icon instead:

![image](https://user-images.githubusercontent.com/146016/60569836-ceb8ef80-9da2-11e9-9a7f-7929aceed01a.png)

**Comment by prasadadarkar30** [comment]
@maxceem wishing to try this and complete, so request you to assign

**Comment by maxceem** [comment]
Assigned @prasadadarkar30

**Comment by prasadadarkar30** [comment]
@maxceem failed to solve it,releasing it so others can work on it.

**Comment by PrakashDurlabhji** [comment]
@maxceem kindly give to me thank you

**Comment by PrakashDurlabhji** [comment]
@maxceem PR https://github.com/appirio-tech/connect-app/pull/3144

**Comment by PrakashDurlabhji** [comment]
@maxceem can you please unassign prasad and assign me because it was completed by me thank you

**Comment by maxceem** [comment]
Assigned you @PrakashDurlabhji
