### ISSUE TITLE
Must display the 'Dashboard' icon when user click on other menus

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#309]
### Expected behavior
-----------------------------------------------------------------
Must display the 'Dashboard' icon when user click on other menus

### Actual behavior
-----------------------------------------------------------------
Won't display the 'Dashboard' icon when user click on other menus

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Now Click 'Specification' from Menu
- Check the Dashboard icon

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_11-11-15](https://cloud.githubusercontent.com/assets/4592712/18942288/7b8c79d0-8635-11e6-81b0-2558a211608d.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
investigate .svg loading under Windows

**Comment by vic-appirio** [comment]
Can't reproduce
