### ISSUE TITLE
Direct Invited Just-Registered Users to All Projects Dashboard

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3090]
**Objective:** When an unregistered user is invited to a project, then registers, they should be brought to the "All Projects" dashboard where they should then see project card(s) that they have been invited too. From here, they can click "Join Project" and access the project. This will help with the UX when unregistered users are invited to multiple projects. 

<p></p>

**Requirements:**

- Once an invited unregsitered user completes registration in the platform, they should be redirected to the "All Projects" dashboard. 

- On the "All Projects" dashboard, they should see project card(s) for all projects that they have been invited too by their registered email address.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2221079

**Comment by vikasrohit** [comment]
Now, as per discussion in team call, now we would redirect all users to `All Projects` by default.

**Comment by vikasrohit** [comment]
Verified on production.
