### ISSUE TITLE
[$20] Show different appropriate text for Managers/CPs with empty project plan

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3104]
As of now we show the same message to Manager/CPs which we show to customers when their project plan is not ready (i.e. there is no phase in the plan with `planned` and above status). Till now, it worked because we never had empty project plan for Managers/CPs, however, now we do have empty project plans after fixing https://github.com/appirio-tech/connect-app/issues/3097, so we need a better message to communicate the Manager/CP.

Here is what we show to the customers (and unintentionally to the Managers/CPs):

<img width="805" alt="Screen Shot 2019-06-10 at 4 44 51 PM" src="https://user-images.githubusercontent.com/2417632/59192121-16cb6480-8b9f-11e9-8963-21c139035fab.png">

fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
@vikasrohit what should be the message for managers and copilots?

**Comment by vikasrohit** [comment]
Will come back to you soon with official text from product team, meanwhile we can use `Project plan is empty. Please start add phases to the plan to start tracking the delivery.`

**Comment by vikasrohit** [comment]
@maxceem Got the updated text:

Header:  Build Your Project Plan

Text: Build your project plan in Connect to reflect delivery progress to the customer. Begin by clicking the "Add Phase" button, select the template that best matches your need, and modify the phase title and milestone dates prior to publishing to the customer. Important Note: To move the project into 'Active' status, you must set at least one phase in Connect's Project Plan to be in 'Planned' status, which signifies to customers that delivery planning and execution has begun.

**Comment by maxceem** [comment]
Project for testing which doesn't have phases: https://connect.topcoder-dev.com/projects/8188/plan

Users for testing:
- `pshah_manager` and `pshah_copilot` should have a new message
- `pshah_customer` should have an old message

**Comment by rashmi73** [comment]
@maxceem i would Like to work on this thanks

**Comment by maxceem** [comment]
Sure @rashmi73

**Comment by rashmi73** [comment]
@maxceem it is ready https://github.com/appirio-tech/connect-app/pull/3137

**Comment by vikasrohit** [comment]
@maxceem it is not working for me on dev. Did we miss any change to be merged?

**Comment by vikasrohit** [comment]
I found the reason and committed a fix https://github.com/appirio-tech/connect-app/commit/e90c55e353c9d7a584fc90999c5cd1d46c371a34

**Comment by maxceem** [comment]
Yep @vikasrohit, just was about to commit. I guess missed it during moving Project Plan to the Dashboard page.

**Comment by vikasrohit** [comment]
Working fine.
