### ISSUE TITLE
[Metadata Management] No success/error message when creating product categories

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3113]
We are missing success/error toasters for product category related operations.

**Comment by maxceem** [comment]
@vikasrohit toaster message is shown for me for product categories too see demo video https://monosnap.com/file/rzj3glaMH4odQdwqiGHB9TZbAJMpOc

The only thing I can see that this message is the same for all the types of metadata.

**Comment by vikasrohit** [comment]
Hmm, I am not able to reproduce it as well. Lets close this for now.
