### ISSUE TITLE
[Redesign] Files and Links

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3123]
While working on this issue https://github.com/appirio-tech/connect-app/issues/3013 we have to implement a new way to view/manage project files and links.

The current design we have looks like this:

![image](https://user-images.githubusercontent.com/146016/60012969-dd6f1a80-96af-11e9-9153-90ad6db8ef4a.png)

As `Files & Links` should be opened from the sidebar it is supposed to be open on the new page rather than Drawer to keep sidebar menu items working consistently for all the menu items. As `Dashboard` and `Discussion` menu items open new page instead of a Drawer.

There are few questions which I'd like to clarify regarding the new design:

1. In the provided design we are seeing files. How should we show links?

2. When we click items which a kind of `folders`. Should it work like regural file manager: we come into that `folder` and see files in that folder? Or should it be collapsed/expanded like now?

3. What functionality is attached to this UI element?

   ![image](https://user-images.githubusercontent.com/146016/60013361-dc8ab880-96b0-11e9-9c1f-70a2864672e8.png)

4. Previously, when we click edit button, the editing UI looked like this:

     ![image](https://user-images.githubusercontent.com/146016/60013444-1065de00-96b1-11e9-856c-40e6518d3c41.png)

     How the editing UI should look in the new design?

cc @vikasrohit

**Comment by vikasrohit** [comment]
1. I think for now we can treat links exactly same as of Files.

2. > Or should it be collapsed/expanded like now?

I didn't understand this one. Do you mean the way we are showing the links, shared in posts, in the left panel?
> Should it work like regural file manager: we come into that folder and see files in that folder?

Yes

3. I think the element is for changing the view from list to some other view. Just like regular file manager. I don't think we need to support that for our first release of this redesign. We can take care of it later. Just leave the column header empty.

4. We can show/expand this UI just below the line item in the list. And just to confirm, this edit screen would triggered via one of the options (`edit`) which appears on clicking `...` (located in right most of the line item)

**Comment by maxceem** [comment]
Thanks for answers.

1. yeah, but we have only one link to open tab: `Files & Links`. So how to show both files and link on one page? Mix them all together? Or show this UI two times on a page: one time for files and one time for links? 

2. Your answer is what I wanted to know.

**Comment by vikasrohit** [comment]
1. for now just show two separate lists (using the same component), one for Files and another for attachments. Most probably they are going to be rendered in the tabs in the new designs.

**Comment by maxceem** [comment]
@vikasrohit could you please share a link to the marvel for this new design.

1. I don't see a menu for editing/deleting files/links in this design. Would there a way to edit/delete them?

2. Should we be able to sort files/links by `Type` and `Modified` column?

3. There is an `Add new...` button which seems to be common for files and links. Is there any design on how it should work?

**Comment by vikasrohit** [comment]
> could you please share a link to the marvel for this new design.

Unfortunately, I don't yet have the marvel link with me. Trying to get that asap, but could we just do rough estimate of the designs with the png only?

1. Lets use the ellipsis icon in a third column (from the Files drawer design https://github.com/appirio-tech/connect-app/issues/3123#issue-459823560) and show the option to delete/edit.

2. That would be good to have for the next release.

3. Lets just show the current Upload file inline modal as full page modal when user clicks on the `Add new` link when user is on Files tab and similarly open the Add new link inline modal as full page modal when user clicks on the same link when on the Links tab.

**Comment by maxceem** [comment]
@vikasrohit any luck with obtaining a marvel file with a new design.

**Comment by vikasrohit** [comment]
@maxceem I don't think I would be able to provide the marvel in next few hours. May be I can provide you that within next 12 hours.
