### ISSUE TITLE
[Metadata Management] Editing JSON in "maximized" mode doesn't update JSON in small editor

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3124]
### Expected behavior
JSON in the editor should be updated.

### Actual behavior
JSON in the editor is not updated.

### Steps to reproduce the problem
- Open any project template edit form.
- Click `Maximize` button to edit the JSON.
- Edit JSON in the `maximized` mode.
- Click `Restore` button to hide `maximized` mode.
- Observe that JSON in the small editor doesn't show changes we did in the `Maximized` mode.

### Screenshot/screencast
Changed JSON in `maximized` mode:

![image](https://user-images.githubusercontent.com/146016/60015985-70f81980-96b7-11e9-98b3-46b8dc7d99f3.png)

But when click `Restore` in the small JSON editor this change is not reflected:

![image](https://user-images.githubusercontent.com/146016/60016023-908f4200-96b7-11e9-8b32-91cfb5248674.png)

Screencast: https://drive.google.com/file/d/1wKXxzJ8O1MWG3vWAQ-ZdIIOuAU6Eqdta/view (screencast was created by **jankyzhang** when working on the [challenge](https://www.topcoder.com/challenges/30093918))

#### Environment
- OS: Mac OS
- Browser (w/version): Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- User role (client, copilot or manager): manager
- Account used: `pshah_manager`

**Comment by afrisalyp** [comment]
Can you please assign me on this ticket.
Thanks.

**Comment by maxceem** [comment]
@afrisalyp assigned.

**Comment by afrisalyp** [comment]
@maxceem, still can't reproduce the problem.
I've tested on Ubuntu, Windows, and Android with the same browser version.
Does the bug appear only on Mac OS?

**Comment by maxceem** [comment]
Hmm, @afrisalyp I cannot reproduce this issue anymore too. Maybe it has been fixed with some other changes.
I'll remove this issue from the Bug Bash for now, until we can reproduce it.

**Comment by maxceem** [comment]
This issue has been fixed as part of the changes done in some challenge, so I'm closing it.
