### ISSUE TITLE
Show the addons questions in the Scope details drawer

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3125]
When editing an existing project, we are showing(in new proposed UI) the scope details in a drawer that appears after user clicks on the estimation component on the dashboard. However, that drawer does not have option to add add-ons to the project's scope which we have while project creation.

fyi @maxceem @RishiRajSahu

**Comment by maxceem** [comment]
@vikasrohit as per my testing we can add addons in the scope details drawer, see demo https://monosnap.com/file/SdRt2kcJHidS6ziUCQXZX4F7spnDet.

Do you have some example when we cannot do this?

**Comment by vikasrohit** [comment]
@maxceem Did you try the behaviour in a project where you haven't selected any addon while creating the project?

**Comment by maxceem** [comment]
Here I've created a new project http://local.topcoder-dev.com:3000/projects/8189 using link https://connect.topcoder-dev.com/new-project/subtitle-skills-api. I choose Design and Development deliverables but didn't choose any add-ons for them. After that I open the project scop in the drawer and added add-ons, see demo video https://monosnap.com/file/u8WpxgtmExKiLfwpEBKp4S3s1kyceO

**Comment by vikasrohit** [comment]
Okay. Then it might me something wrong with my template. Lets close this issue for now and revisit it later if issue appears again. BTW, I am somewhat confused about our status on drawer UI for next release. Could you please share the current understanding of drawer for next release?

**Comment by maxceem** [comment]
The drawer is ready. The only thing left is to show it on click on the project estimation instead of a demo button. It's done in the `feature/redesign` branch for now.

**Comment by vikasrohit** [comment]
Okay. However, I think we discussed to hide it for our next release as we are not going to implement it fully. I just realized that for new Messages tab which we are going to implement in 2.4.13 release, we need to show the details of the threads somewhere and we don't have any other place to show them other than the drawer or we have to leave the threads expanded by default as we have right now.

**Comment by maxceem** [comment]
> Okay. However, I think we discussed to hide it for our next release as we are not going to implement it fully. 

Right, I'm a bit confused about what was the last decision.

> I just realized that for new Messages tab which we are going to implement in 2.4.13 release, we need to show the details of the threads somewhere and we don't have any other place to show them other than the drawer or we have to leave the threads expanded by default as we have right now.

Good catch. We are implementing showing posts in the drawer, so I guess can show in a drawer. Showing them in another way with a new design would be difficult if implement them inside the drawer.

Actually, the drawer is quite ready so I guess we can release with it. Waiting for the results of Topics redesign challenge to see it in action with topics.

**Comment by vikasrohit** [comment]
I was confused as well. I just want to avoid inconsistent behavior which user may experience if we have some components shown in Drawer and others as their own page. IMO, if we show drawer for showing details page for a object, we should be using the same pattern for all other objects as well.

Having said that, lets include the Drawer wherever possible for this release. We can make quick release after this one to patch any inconsistency found.

**Comment by vikasrohit** [comment]
Working fine.
