### ISSUE TITLE
[$150] Make text fields expandable in Scope form

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3128]
After recent changes for new smart scope forms, we lost the ability to expand a text fields for better readability. We need to bring that back i.e. allow users to expand the text areas and by default render them with height of 3 rows.

fyi @acshields @maxceem

**Comment by maxceem** [comment]
@vikasrohit hmm, the fields with type `textbox` are still expanding for me, and while `textinput` fields cannot be expanded, which I guess is expected:

![image](https://user-images.githubusercontent.com/146016/60158723-4b3c5300-9824-11e9-8a52-a86fb6fe09dd.png)

- the only thing it doesn't have 3 rows height by default, I'm not sure if they have such height by default before

**Comment by vikasrohit** [comment]
I meant expanding by dragging the mouse pointer from the bottom right corner of the text box. I am not able to see that cursor any more neither when directly editing the text box during project creation nor when editing an existing project. Also, I think we did some improvement very long back where we used to show the text boxes with multiple lines to occupy the full height which fits the content by default when user is editing such fields. As of now, it just shows single line to me when I try to edit the content of the text box after expanding the accordion.

**Comment by maxceem** [comment]
> I meant expanding by dragging the mouse pointer from the bottom right corner of the text box. I am not able to see that cursor any more neither when directly editing the text box during project creation nor when editing an existing project.

currently, we are using textbox component which extends the height dynamically when we are typing. Should we disable this feature and let users extend the textboxes manually instead?

> As of now, it just shows single line to me when I try to edit the content of the text box after expanding the accordion.

I guess there could be some issues, when we expand accordion and textbox doesn't update its height dynamically. Should we fix this issues instead of changing the behavior to manual?

By any chance do you have an example of project creation form where you experience such issue? To make sure we are talking about the same cases.

**Comment by vikasrohit** [comment]
> currently, we are using textbox component which extends the height dynamically when we are typing. Should we disable this feature and let users extend the textboxes manually instead?

No, we should keep that behaviour too

> I guess there could be some issues, when we expand accordion and textbox doesn't update its height dynamically. Should we fix this issues instead of changing the behavior to manual?

Yes, we need to fix this issue as well i.e. the text box should occupy the full height to accommodate the text in it when user expands the accordion.

Here is the example project https://connect.topcoder-dev.com/projects/8139/scope. Please note that the description textbox does assume sufficient height to show most of the content, however, still there are couple of lines at the bottom which are not visible. And to view them, I can neither scroll via mouse scroll (which was my natural reaction to see that hidden content) nor I can expand(which was my second natural reaction to see the hidden content) the text to view that content.

**Comment by maxceem** [comment]
Ok, so as per discussion we should do two things here:
1. Fix the issues with authorizing textarea. They should automatically resize to show the whole text.

2. Enable manual resizing. So just in case in some situation manual resizing failed, we can still resize the textarea manually.

3. Note, that at the moment if I enable manual resizing and resize textarea so it shows the whole text. As soon as I start typing, the automatic resizing works and it resizes the textarea in a wrong way again.

**Comment by vikasrohit** [comment]
> Note, that at the moment if I enable manual resizing and resize textarea so it shows the whole text. As soon as I start typing, the automatic resizing works and it resizes the textarea in a wrong way again.

Two options:

1. If automatic resizing can take place only if the content is more than the current size of the text box and not when the text box size is greater than the content. OR
2. after fixing auto resizing I guess we should be okay even if automatically resizes after manual resizing.

**Comment by mfikria** [comment]
Please assign this to me @maxceem

**Comment by maxceem** [comment]
Done.

**Comment by mfikria** [comment]
@maxceem i've made two PR:

**Comment by maxceem** [comment]
@mfikria please, have a look on the review here https://github.com/appirio-tech/connect-app/pull/3139#pullrequestreview-258582453

**Comment by mfikria** [comment]
@maxceem need more time to resolve the review's issue

**Comment by mfikria** [comment]
@maxceem i've resolved the issues. Please, check the update. Thanks

**Comment by maxceem** [comment]
@vikasrohit the issues is fixed per our requirements set above, see demo video https://monosnap.com/file/YRaxIumwP5SMVnuu5YYKsmWEqfI7Ga

As per implementation, as soon as we set focus to the field or edit it the field is updated to show the whole text.
Though when we just opened the accordion it may truncate some part of text. Let me know if you think such a fix is enough for us.

**Comment by vikasrohit** [comment]
Looks good, couple of questions:

1. How does it work when user has expanded the text box to a height more than sufficient and then clicked inside the text box?

2. > Though when we just opened the accordion it may truncate some part of text
Is it tricky or error prone to get the fixed?

**Comment by maxceem** [comment]
> 1. How does it work when user has expanded the text box to a height more than sufficient and then clicked inside the text box?

The height would re-adjust for the current height of the text.

> 2. Though when we just opened the accordion it may truncate some part of text
> Is it tricky or error prone to get the fixed?

@mfikria what do you think about fixing such a case?

**Comment by mfikria** [comment]
@maxceem the `Textarea` component is wrapped by `HoC` component called `Formsy` so I cannot access directly the `Textarea` instance, instead I get formsy instance. Maybe it can be resolved by add id in textarea and called focus on that DOM. Not tested yet.

**Comment by vikasrohit** [comment]
> The height would re-adjust for the current height of the text.

I was hoping if we could have prevented auto height adjustment in such cases . However, if it is not straightforward, lets keep things as is.

Explicitly focusing a textbox might not work for the cases where we have multiple text boxes in the same page.

**Comment by maxceem** [comment]
This issue is fixed in two RPs:
https://github.com/appirio-tech/connect-app/pull/3139
https://github.com/appirio-tech/react-components/pull/321

There is still some edge-case issue:
it can be easily reproduced in FireFox, see demo video https://monosnap.com/file/iOeebmreBl870v73wVPYAKPZVPMKQq
The text is truncated when I quickly add lines using Enter or remove lines using Backspace.

Though it looks like efforts to fix this case would be too big.

So, for now, we can use the current fix and would log a separate issue for the left edge-case.

**Comment by maxceem** [comment]
Created a follow-up issue for the left edge-case issue: https://github.com/appirio-tech/connect-app/issues/3176

**Comment by vikasrohit** [comment]
Thanks @maxceem working better than what we have before this fix. So closing for now.
