### ISSUE TITLE
[Metadata Management] Which value show for "created at" for revisions

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3129]
New models like Forms, PriectConfigs and PlanConfigs have versions and revisions.

When we list them in the metadata editor we show the latest revision per each entity:

![image](https://user-images.githubusercontent.com/146016/60393219-49d09a80-9b44-11e9-85b6-95fc271e929a.png)

Though, as we show the revision object `created at` and `updated at` values would be always the same. This would be always true for any revision object.

The value shown in `created at` column is not valuable, we would most likely want to know the value of `created at` of the first initial `revision`.

If we want to show the initial value of `created at` we would have to retrieve the first revision object, but as we keep only limed number of revisions there would be a big chance it's removed already. 

I guess the best fix for this issue would be setting `created at` date for all the revisions to the same which `revision` 1 has at the backend.

@vikasrohit what do you think?

**Comment by vikasrohit** [comment]
@maxceem I think we are good with both `createdAt` and `updatedAt` showing the same values. We may show the `createdAt`/`updatedAt` value of revisions, in the revision history button (which we have while editing an entity with versioning) though.

**Comment by maxceem** [comment]
> createdAt/updatedAt value of revisions, in the revision history button

`createdAt`/`updatedAt` values in the revision history are also always the same as for revisions `createdAt`/`updatedAt` are always the same, so we currently show only one value in the history.

**Comment by maxceem** [comment]
I'm closing this issues, as per we are good with the current approach for now as per https://github.com/appirio-tech/connect-app/issues/3129#issuecomment-507216970
