### ISSUE TITLE
[$40] [Metadata Management] clear error in delete confirmation dialog after cancel

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3130]
### Actual behavior
When I try to delete any entity in the metadata editor I click **Delete** and enter the wrong key in the popup, I see an error as expected ("The key do not match"). But if I cancel the popup and click Delete again, when the popup reopens, the error ("The key do not match") is still showing. 

### Expected behavior
No error should be shown because the input field is now blank.

**Comment by nahidshahin** [comment]
@maxceem can I pick it?

**Comment by maxceem** [comment]
It's on you @nahidshahin.

**Comment by nahidshahin** [comment]
@maxceem can you please give the reproduce step and a screenshot. I can't follow the description.

**Comment by maxceem** [comment]
Sure @nahidshahin 

Got to metadata section:
- https://connect.topcoder-dev.com/metadata/projectTemplates
- open any item, for example https://connect.topcoder-dev.com/metadata/projectTemplates/212
- click **Delete** button and enter wrong data:

   ![image](https://user-images.githubusercontent.com/146016/60642252-cecbf480-9e61-11e9-8544-b543fed3b2e3.png)
- click **Cancel** button to close delete confirmation popup
- click **Delete** button again, you can see that error message still there, but we didn't enter any wrong data, the field is empty:

   ![image](https://user-images.githubusercontent.com/146016/60642291-f0c57700-9e61-11e9-83a8-3287ab264db1.png)
- When click **Cancel** and after **Delete** again, there should be no error message.
- This issue has to fixed for all sections in the metadata:

   ![image](https://user-images.githubusercontent.com/146016/60642328-1a7e9e00-9e62-11e9-9bc4-38d4bc30066d.png)

**Comment by nahidshahin** [comment]
@maxceem PR https://github.com/appirio-tech/connect-app/pull/3138

**Comment by RishiRajSahu** [comment]
Closing. Pushed to prod.
