### ISSUE TITLE
Project member invites via email fails when there is a case difference

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3134]
### Expected behavior
Project member invite should work in case insensitive way

### Actual behavior
It errors out when user tries to join a project where the invited email and the user's registered email in the system has different cases.

### Steps to reproduce the problem
- Invite a user with at least one different case character in their registered email
- Try to join the project with the invited user
- Observe that the system does not let the user join the project and throws error that it is not able to find the invite for the user.

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

**Comment by maxceem** [comment]
I guess it's fixed by https://github.com/topcoder-platform/tc-project-service/pull/325 right?

**Comment by vikasrohit** [comment]
Yep. It should be fixed now.
