### ISSUE TITLE
[$35] Show tooltip for accordion title

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3147]
When we show accordions some titles have a too-long name and truncated with `...` at the end:

![image](https://user-images.githubusercontent.com/146016/60701349-1029d600-9f2e-11e9-9311-d50744cd41b1.png)

We should add a tooltip with a full name for all accordion names.

To see accordions in action, the next project may be used https://connect.topcoder-dev.com/projects/8196/scope, see a [screenshot](https://monosnap.com/file/CoXqGfFSoi9IXbjqZFCFJ5XupKKUB0).

For the tooltip, we already have a component to reuse:

![image](https://user-images.githubusercontent.com/146016/60701805-8b3fbc00-9f2f-11e9-874f-baeb73a2e67f.png)

See example code https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/PhaseCard/EditStageForm.jsx#L304 and you may check it in action if you open this [page](https://connect.topcoder-dev.com/projects/8196/plan) and click an icon to edit the phase, and after hover mouse on `In Progress`, see a [screenshot](https://monosnap.com/file/3IhFMJ3314ne7EhWay81fQlI0pMY49).

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by sumitdaga** [comment]
Can intake this ?

**Comment by maxceem** [comment]
Sure @sumitdaga, assigned.

**Comment by sumitdaga** [comment]
@maxceem PR at #3148

**Comment by maxceem** [comment]
@sumitdaga please, have a look on the review here https://github.com/appirio-tech/connect-app/pull/3148#pullrequestreview-258586585

**Comment by r0hit-gupta** [comment]
@maxceem may I pick this up? It's been 2 days since last update.

**Comment by maxceem** [comment]
Hey, @sumitdaga do you think you can finish it during next 24 hours?

**Comment by maxceem** [comment]
@sumitdaga as the issue is mostly done, except a small fix requested in the https://github.com/appirio-tech/connect-app/pull/3148#pullrequestreview-258586585 the fix accepted with a small prize reducing.

**Comment by sumitdaga** [comment]
@maxceem thank you!  
i was on the road the last 2 3 days with very little connectivity!

**Comment by RishiRajSahu** [comment]
Working fine on prod.
