### ISSUE TITLE
"Save Changes" stays enabled if we don't have any change in scope form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3149]
### Expected behavior
"Save Changes" should get disabled again if we don't have any changes in the scope form. And we shouldn't get an alert popup when we try to leave the scope tab.

### Actual behavior
"Save Changes" stays enabled if we don't have any change in scope form. And we get an alert popup when we try to leave the scope tab.

### Steps to reproduce the problem
- Open scope tab https://connect.topcoder-dev.com/projects/8197/scope
- Change some field to make `Save Changes` button enabled.
- Revert the change - I mean change back as for has been initially.
- Button supposed to get disabled as there are no changes in the form but it stays enabled.

### Screenshot/screencast
https://monosnap.com/file/mka4az6YPGuZsoL5zgpgjETe6oGmC8

### Additional notes

FYI for some form it works as expected, example: https://connect.topcoder-dev.com/projects/8178/scope, see [demo video](https://monosnap.com/file/oBreGfR6TTtAHpY02Eb1bJHrxoHLjV)

--

#### Environment
- OS: Max OS
- Browser (w/version): Google Chrome
- User role (client, copilot or manager): all
- Account used: pshah_manager

**Comment by rashmi73** [comment]
give me thanks

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by maxceem** [comment]
Ok @rashmi73 assigned to you.

**Comment by maxceem** [comment]
Updated link to the demo project with the issue https://connect.topcoder-dev.com/projects/8197/scope

**Comment by rashmi73** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3150

**Comment by maxceem** [comment]
@rashmi73 please, have a look on the review here https://github.com/appirio-tech/connect-app/pull/3150#pullrequestreview-258586832

**Comment by maxceem** [comment]
Hey, @rashmi73 do you think you can finish it during next 24 hours?

**Comment by rashmi73** [comment]
@maxceem actually backend response is not having consistent model properties.

I mean even if is blank or null, still object/key-value pair shall be received,
I analyzed that response was not proper in one case whereas it was proper for other hence i added fields, but if response becomes consistent then it would be more helpful?

**Comment by maxceem** [comment]
> I mean even if is blank or null, still object/key-value pair shall be received,
I analyzed that response was not proper in one case whereas it was proper for other hence i added fields, but if response becomes consistent then it would be more helpful?

@rashmi73 That's a good catch. I guess it would a little bit hard to make response consistent for already created data at the backend. Also, I'm not sure if it's possible to make consistent for the new data also, but we will have to think about it.

@rashmi73 Do you think there can be some quick fix for one more case which I've mentioned in the review https://github.com/appirio-tech/connect-app/pull/3150#pullrequestreview-258586832 which wouldn't break anything else?

Also, could you please provide some details of what data inconsistencies we have for the case mentioned in the review. So we would think about how we can prevent such cases in the future.

Thank you.

**Comment by rashmi73** [comment]
@maxceem PR updated

**Comment by maxceem** [comment]
@vikasrohit this issue is not implemented during cf18, will handle it separately.

**Comment by maxceem** [comment]
This issue has been fixed by PR https://github.com/appirio-tech/connect-app/pull/3175 which is merged to DEV now.

**Comment by vikasrohit** [comment]
@maxceem I think I mistakenly marked this in next release, and just realized that it was release as part of 2.4.13.
