### ISSUE TITLE
[$50] Handles are not cleared after successful invites

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3155]
### Expected behavior
All emails and handles should be cleared from the text box of the invite dialog box.

### Actual behavior
Handles stays in the text box even after the successful invite operation

### Steps to reproduce the problem
- Open any project where you have access to manage customer team
- Try to invite multiple users with mix of handles and emails
- After successful invite operation, notice that handles stays in the text box while emails are cleared 

### Screenshot/screencast
<img width="1091" alt="Screen Shot 2019-07-09 at 5 31 35 PM" src="https://user-images.githubusercontent.com/2417632/60886377-6caf2d00-a26f-11e9-89ba-a41d6d39d4c6.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Customer/Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
@maxceem fyi

**Comment by vikasrohit** [comment]
Moved to next release

**Comment by maxceem** [comment]
Example project https://connect.topcoder-dev.com/projects/7442 where `pshah_manger` user can invite.

Click `Manage` link next to the `TEAM` title to invite by handles and emails:

![image](https://user-images.githubusercontent.com/146016/64679518-8c87ea80-d484-11e9-9617-477ba88ef590.png)

**Comment by rashmi73** [comment]
@maxceem please give to me thanks

**Comment by maxceem** [comment]
Sure @rashmi73

**Comment by rashmi73** [comment]
@maxceem it is done and ready https://github.com/appirio-tech/connect-app/pull/3319

**Comment by maxceem** [comment]
@vikasrohit can you still reproduce this issue on DEV? I'm trying to reproduce the original issue but cannot now.

**Comment by rashmi73** [comment]
@maxceem it was reproducible locally hence i raised PR for it. I hope efforts are not wasted this time

**Comment by vikasrohit** [comment]
@maxceem I think it is still there if we use `@` symbol before the handle. I guess the invites works as expected no matter if you use `@` or not. I remember that we removed the requirement of using `@` for inviting users via handle, but may be we are just ignoring the `@` while inviting.

**Comment by maxceem** [comment]
Thanks @vikasrohit can reproduce it.

**Comment by rashmi73** [comment]
@maxceem updated PR
