### ISSUE TITLE
Team Dialog UI distorts if user name and handles are long

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3156]
Team dialog UI to view member/invites gets distorts for long names/handles, refer the image 
<img width="667" alt="Screen Shot 2019-07-09 at 4 36 14 PM" src="https://user-images.githubusercontent.com/11248478/60956540-a724d280-a320-11e9-9180-3a353c29ac3f.png">

we need to keep fixed div width for roles switcher in right and crop the name followed by ellipses `...` to keep the details inline.

fyi @vikasrohit

**Comment by vikasrohit** [comment]
CF candidate

**Comment by suppermancool** [comment]
@RishiRajSahu done in https://github.com/appirio-tech/connect-app/pull/3163

**Comment by RishiRajSahu** [comment]
Done via https://github.com/appirio-tech/connect-app/pull/3166
