### ISSUE TITLE
Unable to scroll the dropdown on project form

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3158]
User should be able to scroll and select the desired value from the dropdown - 

<img width="1429" alt="Screen Shot 2019-07-11 at 12 24 32 PM" src="https://user-images.githubusercontent.com/11248478/61028768-2379ed00-a3d7-11e9-86a8-b9c8d676b2e1.png">

**Comment by suppermancool** [comment]
@RishiRajSahu done in https://github.com/appirio-tech/connect-app/pull/3163

**Comment by RishiRajSahu** [comment]
Fixed and pushed to Prod.
