### ISSUE TITLE
Need slider component for project form questions

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3159]
Currently we don't have slider component for our project form, we need to build a slider component with text labels at the extremes - for eg - labels should be visible like this 
<img width="438" alt="Screen Shot 2019-07-11 at 12 31 31 PM" src="https://user-images.githubusercontent.com/11248478/61029112-e2cea380-a3d7-11e9-90db-ed4f5e5cb665.png">

**Comment by maxceem** [comment]
Should be able to choose any numeric value between them? like from 1 till 100?

Or only separate value on the circls? I think we have such component.

**Comment by suppermancool** [comment]
@RishiRajSahu can i know what is input/output for this?

**Comment by RishiRajSahu** [comment]
@maxceem yep if for separate values on circles we already have component. we will go with standard slider values 1 to 100 or may be 1 to 10 could also as its more about showing the visual location of slider than the value at which it is located. this component right now will be need to get the user has inclination towards which one of the value out of two. So actual numeric value doesn't matter right now just the visual representation is important but if by having 1 to 100 range its better to show precise location whenever this component render then let's have bigger range of 1 to 100.
fyi @suppermancool

**Comment by suppermancool** [comment]
@RishiRajSahu done in 
https://github.com/appirio-tech/react-components/pull/322

Demo: https://gyazo.com/4ffc2bcc1a78ab908cd204a250bb80b0

**Comment by RishiRajSahu** [comment]
@suppermancool as I mentioned we don't need to show values, values will be the deciding factor for position of slider on the sliding bar and we will save value only. please follow this https://connect.topcoder-dev.com/new-project/ds_sprint for understanding the requirement for this slider, we need to understand inclination of user towards kind of solution. 

User inclined towards best - 
![inclined towards best](https://user-images.githubusercontent.com/11248478/61104899-99448e00-a495-11e9-90bf-244eb33f4e4d.jpg)

User inclined towards many concepts - 
![user inclined towards many concepts](https://user-images.githubusercontent.com/11248478/61104911-a06b9c00-a495-11e9-9e40-6c85f7c23e99.jpg)


ignore the tick in blue circle, we don't need tick.

**Comment by RishiRajSahu** [comment]
Done via https://github.com/appirio-tech/react-components/pull/322
