### ISSUE TITLE
[Redesign] Final Fixes

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3161]
In this issue, I would like to track the final fixes which have to be done to complete redesign in the https://github.com/appirio-tech/connect-app/tree/feature/redesign branch.

- [ ] Replace icons in the menu
- [ ] Replace "Folder" icon in the files & links manager

**Comment by maxceem** [comment]
### Replace icons in the menu

Currently, we don't have SVG files for new icons, so we use a placeholder.

Icons form the latest design cannot be extracted https://marvelapp.com/4acgiai/screen/58136217
Icons from the previous design also can be extracted not all, not enough to cover all the menu items https://marvelapp.com/3h6bdfd/screen/56595828 (only 2 icons for the menu can get from here and use them now)

#### Project Sidebar:

![image](https://user-images.githubusercontent.com/146016/61039151-cf83fe00-a400-11e9-8505-9d0e9c376598.png)

#### User Sidebar:

![image](https://user-images.githubusercontent.com/146016/61039220-eaef0900-a400-11e9-8975-e9d0c5687b5d.png)

**Comment by maxceem** [comment]
### Replace "Folder" icon in the files & links manager

We don't have an icon for the "Folder" so, for now, we show the default icon which is not intuitive. Cannot extract it from the https://marvelapp.com/4acgiai/screen/58136218.

![image](https://user-images.githubusercontent.com/146016/61039583-9c8e3a00-a401-11e9-953f-31dfb1e45b83.png)

**Comment by vikasrohit** [comment]
@maxceem I think it is done now, we can close now.

**Comment by maxceem** [comment]
Yep, closing.
