### ISSUE TITLE
[Specification] - no option to remove the color added

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#317]
## Expected behavior
- The user must be able to delete the color.
## Actual behavior
- The user don't have the option to remove the added color.
## Steps to reproduce the problem
- Login into application as manager.
- From Dashboard page edit any existing project eg. foo1.
- Select Specification tab section.
- Go to Design Specification section.
- Press "+" button for What colors do you like? (Select all that apply).
- Add the max number of colors.
- Try to remove color added before.

Environment
---

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2 
            IE 11.0
User role: manager
Account used: pat_monahan

![1](https://cloud.githubusercontent.com/assets/5114907/18944432/46700c32-862e-11e6-8df6-94cbfc207512.png)

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
@vic-appirio over to you for design

**Comment by vic-appirio** [comment]
The current implementation of the color picker and selected colors is misleading. I imagined a simpler experience that would make only singular action to have all the colors one needs.

Current behavior : User can add colors; user can select or deselect colors; user can't remove colors.

Desired outcome: User can add and remove colors. Added colors count as selected. User can't select/deselect - this action is really confusing. Changes needed - add "remove color" to the color picker.

I'll attach an updated design for the interaction. @fnisen please confirm if this experience makes sense to you.

**Comment by fnisen** [comment]
@vic-appirio I think we went with this experience b/c it was the fastest implementation. 

Of course your approach makes sense, but I don't want to do a redesign before we know whether this is a useful feature, and we haven't gotten enough data on it so far. I would just add a simple deselect ("x") to aid usability and leave it at that for now. Let's discuss in person if you disagree. Thanks.

**Comment by vic-appirio** [comment]
The easiest experience is to allow the user to remove the color on hover. The entire color palette is based on adding and removing colors to it. There's no "enable/disable" colors functionality.

This is the expected behavior for removing a color:
![remove color step 1](https://cloud.githubusercontent.com/assets/8484061/19702872/5d9ef106-9ab6-11e6-80d7-fb9595e717d4.png)
![remove color step 2](https://cloud.githubusercontent.com/assets/8484061/19702873/5da609a0-9ab6-11e6-84e2-67a063813091.png)
![remove color step 3](https://cloud.githubusercontent.com/assets/8484061/19702874/5da6fc98-9ab6-11e6-8b40-5c7e1ecc769f.png)

Specked flow: https://topcoder.invisionapp.com/share/C3934W8K6 (@fnisen can you add Vikas to the InVision? He can use the build-in build mode where all the details of the work file can be viewed/accessed)

**Comment by fnisen** [comment]
Thanks @vic-appirio. @vikasrohit have added you to InVision and that prototype. When you click into it, you should see an "Inspect mode" (with a Beta icon) that will give you styles and dimensions.

**Comment by vikasrohit** [comment]
Done. Changes are in dev. @vic-appirio @fnisen Please let me know if I have missed anything from the specs.

**Comment by fnisen** [comment]
@vikasrohit the functionality looks good, but there's an edge case bug: if a user adds 5 colors and then deletes a color, they can't add any other colors. To correct this and simplify things, let's not impose a restriction on the number of colors. Please allow "unlimited" colors, but make sure the layout looks good (we stick with 5 per row or whatever makes sense). Thanks.

**Comment by vikasrohit** [comment]
@fnisen I guess, it would be better to have some kind of limit always there. May be we can increase the limit to 10 or 20, but it should be there. Coming the bug you found, I have fixed it without changing anything on limits. I am committing the changes without any limit changes for now, please let me know if you still feel we should remove the limit or increase the limit.

**Comment by fnisen** [comment]
@vikasrohit, OK that's fine. Let's leave it like this for now. It was working fine for me most of the time, but I was able to get into an error state on one project, although I couldn't reproduce consistently, https://connectv2.topcoder-dev.com/projects/515/specification, with the option to only add four colors. 
<img width="684" alt="screen shot 2016-11-03 at 4 28 09 pm" src="https://cloud.githubusercontent.com/assets/12552247/19989422/9ae7cc48-a1e3-11e6-9a44-27c610638a0e.png"> 
Can you please double-check the logic?

**Comment by vikasrohit** [comment]
@fnisen  Found the root cause and fixed the issue. It was happening whenever user adds the same color twice from the picker. Changes are in dev.

**Comment by fnisen** [comment]
Perfect, thanks @vikasrohit!
