### ISSUE TITLE
[$45] [Metadata Management] after any error happens, navigating to any other page shows error

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3180]
This is follow up from this comment https://github.com/appirio-tech/connect-app/issues/3132#issuecomment-511789890

If there is an error in any of screen, going back to the listing page by navigating the navigation menu, it still shows the error page i.e. it does not clears up the error from Redux state.

Have to create steps to reproduce it.

**Comment by maxceem** [comment]
### Steps to reproduce
1. Use user `pshah_manager`
2. Open any object for editing, for example this Project Template https://connect.topcoder-dev.com/metadata/projectTemplates/219
3. Click **Save** button.
4. As this user doesn't have permissions to update objects the error would happen on the server as expected and it would be shown in the bottom left corner.
5. Now try to navigate to any section in the left menu. Instead of the list of object we would see error page:

    ![image](https://user-images.githubusercontent.com/146016/64675148-1f238c00-d47b-11e9-897e-13a4cecda69f.png)

### Requirements
If some error happens and after we navigate to another page we shouldn't see error page. This should be handled in a general way for any kind of error.

**Comment by vikasrohit** [comment]
Good catch. I was trying to log this issue since the day we implemented the metadata UI, but was not able to get time to log it.

**Comment by nahidshahin** [comment]
@maxceem can I try please?

**Comment by maxceem** [comment]
Hey @nahidshahin as per our Bug Bash rules, you don't have to wait to be assigned and can work on the issue as soon as you comment, see the rules https://www.topcoder.com/challenges/30102919.

So since your comment the issue was assigned to you. As during 12 hours since start you didn't provide a Pull Request and didn't requested the extension, I have to unassign this issue from you and open it for everyone.

This issue now open for pick up.

**Comment by gets0ul** [comment]
Please assign me.

**Comment by maxceem** [comment]
Done @gets0ul

**Comment by gets0ul** [comment]
@maxceem PR is done and ready for review.

**Comment by vikasrohit** [comment]
Working fine.
