### ISSUE TITLE
Intermittent - Project listings not displayed

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3182]
### Expected behavior
Project listings should be displayed upon login for each user.

### Actual behavior
Intermittently, regardless of user or browser, project listing is not displayed.

### Steps to reproduce the problem
-- Login to http://connect-qa.topcoder-dev.com
-- View Project Listing

### Screenshot/screencast
Attach or link a resource.
<img width="1346" alt="Screen Shot 2019-07-17 at 4 53 12 AM" src="https://user-images.githubusercontent.com/51733042/61336688-e2a72b80-a84f-11e9-80c9-ea142e869d1b.png">
<img width="1400" alt="Screen Shot 2019-07-17 at 4 52 51 AM" src="https://user-images.githubusercontent.com/51733042/61336689-e33fc200-a84f-11e9-9554-b13437e77d83.png">
<img width="1391" alt="Screen Shot 2019-07-17 at 4 51 32 AM" src="https://user-images.githubusercontent.com/51733042/61336690-e33fc200-a84f-11e9-95d6-c13150e66a73.png">

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: lakshmiaconnmgr

**Comment by lakshmiathreya** [comment]
@vikasrohit - I am unable to assign, update tag or set milestone etc this issue. Possibly a privilege issue for my  account?

**Comment by vikasrohit** [comment]
> @vikasrohit - I am unable to assign, update tag or set milestone etc this issue. Possibly a privilege issue for my account?

@lakshmiathreya I just added you with write permissions to the repo, now you should be able to do write operations as well.

**Comment by vikasrohit** [comment]
The issue happens intermittently because of network issue at client machine. Browser times out the requests if there is no response in 20000 milliseconds. Trying with different internet connect works in most of the cases.

**Comment by lakshmiathreya** [comment]
Ok closing the issue.
