### ISSUE TITLE
Update links to post in email notfications

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3188]
In the last release `2.4.13` we updated URLs for posts inside Connect App.

We should now update links inside post email notifications:

![image](https://user-images.githubusercontent.com/146016/61378716-98b65800-a8d8-11e9-8d27-bc8d6c25f677.png)

So far we are redirecting old links to the new links client-side so no functionality is broken.

fyi @vikasrohit

**Comment by vikasrohit** [comment]
Could you please create a corresponding ticket in `tc-notifications` as well?

**Comment by maxceem** [comment]
The corresponding issue at `tc-notifications` https://github.com/topcoder-platform/tc-notifications/issues/142

**Comment by maxceem** [comment]
This issue in `tc-notifications` is fixed via the hotfix https://github.com/topcoder-platform/tc-notifications/pull/143
