### ISSUE TITLE
Search and filter section in the header must center aligned in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#319]
### Expected behavior
-----------------------------------------------------------------
Search and filter section in the header must center aligned in IE11

### Actual behavior
-----------------------------------------------------------------
Search and filter section in the header is not center aligned

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Check the header section: Search and filter fields

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_13-01-30](https://cloud.githubusercontent.com/assets/4592712/18944765/e0172738-8644-11e6-976f-ef7c5925dfa6.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Known issue #135
