### ISSUE TITLE
Cannot upload files on the phases specifications tabs

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3195]
### Expected behavior
When click **Add File** the dialog for choosing a file shows up.

### Actual behavior
When click **Add File** nothing happens, even no error.

### Steps to reproduce the problem
- Open any project Dahsobard https://connect.topcoder-dev.com/projects/7442
- Open any phase **Specification** tab
- Click **Add File** button.
- Nothing would happen.
- This can be reproduced on DEV and on PROD.

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/146016/61526008-28304800-aa4c-11e9-82c1-1fb39b31cc6e.png)

--

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): manage / copilot
- Account used: `phahs_manager`

**Comment by maxceem** [comment]
Strange, that for a project with one phase it works in DEV https://connect.topcoder-dev.com/projects/8214 and on PROD https://connect.topcoder.com/projects/11522

**Comment by maxceem** [comment]
If we have a project with 2 or more phases, file uploading works only for the first phase, but doesn't work for other phases http://local.topcoder-dev.com:3000/projects/8214.

But for a project with many phases like this one https://connect.topcoder-dev.com/projects/7442, file uploading doesn't work for any phase.

**Comment by vikasrohit** [comment]
Good catch @maxceem Do you think we should get it fixed via f2f or we can wait to work on it in CF? IMO, we should get this wrapped before CF because we might not get enough time in this release to run a CF in parallel to other work we are doing.

**Comment by maxceem** [comment]
Run F2F https://www.topcoder.com/challenges/30096468/

**Comment by maxceem** [comment]
This issue is fixed via PR to the React Components repo https://github.com/appirio-tech/react-components/pull/325

Comment about the fix from the winner:
> the issue is caused because filestack appends the container pane that activates the filepicker based on an id which is common for all filpieckers on the page
> so it just keeps appending to the same picker
> with the fix, a unique id using lodash's uniqeId method is appended to the id each time filepicker opens

**Comment by vikasrohit** [comment]
Working fine on production.
