### ISSUE TITLE
[Search] - when filters are hide don't take them into consideration

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#320]
## Expected behavior
- Reload results when the filter is hide.
## Actual behavior
- The filter criteria are taken into consideration even the filter options are hidden.
## Steps to reproduce the problem
- Login into application as copilot.
- Complete search field with word "Demo".
- Press enter to perform search.
- Expand Filters and select Project Type=Work Project.
- Observe "No results" message.
- Press again on Filters option to hide the section.

Environment
---

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2 
            IE 11.0
User role: copilot
Account used: cp-superstar
---

![no-results](https://cloud.githubusercontent.com/assets/5114907/18945797/c7322a5c-8634-11e6-8884-63e5248f5e83.png)

**Comment by mahestro** [comment]
Not valid. Expected behavior.

**Comment by fnisen** [comment]
@vic-appirio can you please design a visual indicator to show that the filters are on?

**Comment by vic-appirio** [comment]
yes. Badge with number that illustrates filters used. 
![screen shot 2016-10-25 at 5 38 53 pm](https://cloud.githubusercontent.com/assets/8484061/19709286/2cf429bc-9ada-11e6-9d2c-5e12c0ea9e8d.png)

Specked here https://topcoder.invisionapp.com/share/VZ938K3YM#/200096146_Navigation_-_1366px (again - use the inspect beta to get the details)

**Comment by fnisen** [comment]
Thanks @vic-appirio. Ready for you @vikasrohit.

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by fnisen** [comment]
Thanks Vikas. Looks good.
