### ISSUE TITLE
[$40] Can click "trough" the file permissions dialog when uploading files

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3208]
### Expected behavior
Should click inside the permissions dialog.

### Actual behavior
Click goes under the permission dialog and causes another file uploading dialog.

### Steps to reproduce the problem
- Open any project where you can upload file, for example **Scope** page of the next project https://connect.topcoder-dev.com/projects/8216/scope
- Scroll the page so the file uploading component in the center of the screen.
- Click **Add file**, choose file to upload and click **Upload**.
- Permission dialog is shown now. If you click on the permission dialog in the places it overlaps with the file uploading component which is under, the click would be caught by file uploading component instead of the permissions dialog and new file uploading dialog would be shown.

### Screenshot/screencast
Demo video: https://monosnap.com/file/kNKiL9AU8dlur6XUfDYmCixBy3lAGl

![image](https://user-images.githubusercontent.com/146016/61680341-c158aa80-ad3b-11e9-928c-13e833af05e4.png)

--

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): any
- Account used: `pshah_manager`

**Comment by maxceem** [comment]
It would best if we fix this issue generally for the file uploading component in the `react-components` repo. So file uploading component doesn't overlap anything on top of it, not only this particular permissions dialog.

**Comment by vikasrohit** [comment]
Nice catch.

**Comment by suppermancool** [comment]
@maxceem pls assign this to me

**Comment by suppermancool** [comment]
@maxceem done in https://github.com/appirio-tech/react-components/pull/334 .

**Comment by vikasrohit** [comment]
Working fine now.
