### ISSUE TITLE
Updates with files on the scope tab are not reflected immediately

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3209]
### Expected behavior
When add, edit or delete files we should see the results immediately.

### Actual behavior
When add, edit or delete files we don't see the result of our actions immediately and should leave the Scope page and come back to see the changes.

### Steps to reproduce the problem
- Open project **Scope** page, which has file uploading component, for example, this one https://connect.topcoder-dev.com/projects/8216/scope
- Make any operation with file: add a new file, edit an existent file or delete an existent file.
- You would see the success popup in left bottom corner after all of the actions, but the list of files would stay the same.
- Go to some other page, for example, **Dashboard** and come back to the **Scope** page again. You would see that all actions are now reflected and the list of files is updated.

### Screenshot/screencast
https://monosnap.com/file/slrL4qzOhGvVO4wIGza2FyOyXNPjy8

--

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): any
- Account used: `pshah_manager`

**Comment by rashmi73** [comment]
@maxceem please give this to me thank you. I have started working on it

**Comment by maxceem** [comment]
@rashmi73 as there is no Pull Request during 12 hours. I have to open this issue for everyone to pick up.

This issue is now open for pick up.

**Comment by rashmi73** [comment]
@maxceem kindly give it to me back, as I was investigating it and came to know that it requires backend access to tc-message-service.

**Comment by rashmi73** [comment]
@maxceem can you please provide me access to https://github.com/appirio-tech/tc-message-service/

**Comment by maxceem** [comment]
I've removed it from pick up for a while. Could you please give me a hint how it requires changes in `tc-message-service`? I looks for me that it's only Connect App issue.

When we upload files we don't see them immediately, but if we reload page, we can see them.

**Comment by maxceem** [comment]
`tc-message-service` is only about messages and posts. But on the scope tab we only upload files and don't have messages or posts.

**Comment by rashmi73** [comment]
@maxceem I tested thoroughly .it is working fine now

**Comment by maxceem** [comment]
@rashmi73 do you mean you cannot reproduce the issue?

**Comment by maxceem** [comment]
Hmm, yes, looks like it works now. I also cannot reproduce this issue anymore.

**Comment by vikasrohit** [comment]
Closing for now.
