### ISSUE TITLE
[Search] - the project must be displayed as selected 

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#321]
Expected behavior
------------------------------------------------------------

- The item must be displayed as selected. 

Actual behavior
------------------------------------------------------------

- Selected item is not displayed as selected.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as copilot role.

- Expand Filters and select an item eg. Work Project.

- Expand again the items.

Environment

------------------------------------------------------------

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2 
            IE 11.0
User role: copilot role
Account used:  cp-superstar

------------------------------------------------------------

![aaa](https://cloud.githubusercontent.com/assets/5114907/18946345/22c3fbaa-8637-11e6-8115-eae9046030f9.png)

**Comment by mahestro** [comment]
It shouldn't be selected. Not valid.
