### ISSUE TITLE
[$50] Admins should be able to modify the actual start and completion dates of a milestone

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3210]
As of now, we don't allow any one to update the `actualStartDate` and `completionDate` of a milestone. We assume that CA/Copilots would always start the milestones one time and they don't need back entries. However, in practical, many time we need to update the milestones dates to a date in past when copilots/CAs forget to updates the dates of the milestones on time. To facilitate that use case for CAs/copilots we need to equip admins with feature of updating the timeline of a phase in past as per requirement by CA/copilot. Followings are the places which need to be updated for an admin:

1. Ability to update the start date of an activated phase
2. Ability to update the start date of an activated timeline
3. Ability to update `actualStartDate` and `completionDate` fields of any milestone (Please right now both of these fields are allowed in `PATCH` request for a milestone. We need to limit these fields to be updated only by admins.)

**Comment by maxceem** [comment]
1. When we edit phase we use the next form which let us edit not only start date but other properties of a phase including deleting phase:
    
    ![image](https://user-images.githubusercontent.com/146016/64672998-b4238680-d475-11e9-8014-61c20861f7e1.png)

    - So far when phase is completed, we don't show such edit form at all. So for admins we would have to show it even after phase is completed.
    - Which fields should be able admin to edit in this form after phase is completed? Only **Start Date** or any other?

2. > Ability to update the start date of an activated timeline

     So far we don't have any UI to update the start date of timeline even before it's activated. I guess ideally, the start date of timeline should be updated automatically based on the milestones inside. Though, so far we don't update the start date of timeline automatically. And actually we don't really use it. Which way to go you prefer?
     1. Fix server-side to update start date of timeline automatically.
     2. Add some UI to update timeline start date.
     3. Don't do anything.

3. > Ability to update actualStartDate and completionDate fields of any milestone

    To confirm:
     1. If milestone has `active` status, for admin users we should show `actualStartDate` for editing.
     2. If milestone has `completed` status, for admin users we should show `actualStartDate` and `completionDate` for editing.

**Comment by vikasrohit** [comment]
Yep, Agreed. And in fact we discussed internally to clean up the complexity involved in the milestones themselves. Here is summary of our new clean model:

1. Add new fields called `plannedDate` and `actualDate`
2. Ignore existing date fields e.g. `startDate`/`actualStartDate`/`endDate`/`completionDate`
3. Ignore `duration` field as well
4. In very simple words, a timeline would be a collection of milestones which act as simple points and does not have any duration
5. Now it is all upto the client how they want to use and render the timeline
6. We can also get rid of redundant date and duration fields on the timeline object as well

If you notice, this approach will make the logic of milestone management very simple e.g. we won't need any cascading updates when a new milestone is created or existing milestone is updated for any field. I would make the logic of progress calculation of the timeline very easy and straightforward.  It would make the movement of the milestones within timeline very simple as well.
Let me know what do you think about this. I would like to get this going and completed before we get the green signal for work management features. In our theory, backward compatibility is also not so much difficult in this case, we can simply do `plannedDate=startDate` and `actualDate=completionDate` for all existing milestones and our new rendering logic would render the timeline correctly even for the existing phases.

**Comment by vikasrohit** [comment]
I think parallel phases is also workable with this approach as we can add two milestones for a phase one for the start and another for the end and there can be two milestone with same date.

The backend end changes for `workstream` is already in dev, right? So, I guess, we should be okay to have this in dev as well, however, for now, lets keep the changes in separate branches for both front end and back end. And lets see how this logic works, especially for the existing timelines.

**Comment by maxceem** [comment]
> I think parallel phases is also workable with this approach as we can add two milestones for a phase one for the start and another for the end and there can be two milestone with same date.

So you mean that new milestones, would be just point marks, and we would fully decide how to use them clients side. So for the challenge phases we would need 2 milestones to define one challenge phase, something like this:
```js
[
   { 
      type: "registration-start",
      plannedDate: "12 September"
   },
   }
      type: "registration-end",
      plannedDate: "17 September"
   }
]
```

So we would also need 2 milestone types for each challenge phase, one to indicate start, and another one to indicate the end.

> The backend end changes for workstream is already in dev, right?

Right, for server-side workstream is already in dev. So we can add new changes to the new branch.

For the client side we have workstream changes separately. So the question for client-side is, should we make such changes in `dev` so we can release new milestones earlier? Or should we make changes to milestones only in `workstream` branch so we would release new milestones together with workstreams.

**Comment by vikasrohit** [comment]
> So we would also need 2 milestone types for each challenge phase, one to indicate start, and another one to indicate the end.

Yes, exactly.

For the front end, please create new branch out of dev and we would resolve the conflicts or will redo the changes in a another feature branch out of `workstreams` branch.

**Comment by maxceem** [comment]
Sum up for this issue:
1. We should let admins edit phases in any status. Currently, nobody can edit phases when phases are `delivered`.

     ![image](https://user-images.githubusercontent.com/146016/64864551-07e1cb80-d640-11e9-8504-ea9976ce364e.png)

2. Admins should be able to edit `actualStartDate` and `completionDate` fields of any milestone with the next conditions:
     1. If milestone has `active` status, for admin users we should show `actualStartDate` for editing.
     2. If milestone has `completed` status, for admin users we should show `actualStartDate` and `completionDate` for editing.

@vikasrohit for this issue we implement it as it is. While I've created a separate issue to perform milestones refactoring https://github.com/appirio-tech/connect-app/issues/3299 which should be done in a separate branch.

**Comment by vikasrohit** [comment]
Did you check if our API supports edit of these fields for the Admins? Most probably it should, but just make sure if we do. Also, I think we need to update the logic to not let non admins to update `actualStartDate` and `completionDate` from the API.

**Comment by maxceem** [comment]
> Did you check if our API supports edit of these fields for the Admins?

Yes. We support updating both fields. Though if we try to update `completionDate` there is an error in the code `entityToUpdate.completionDate.diff is not a function`.

> Also, I think we need to update the logic to not let non admins to update actualStartDate and completionDate from the API.

Will do that as a separate issue in Project Service via Bug Bash https://github.com/topcoder-platform/tc-project-service/issues/381

**Comment by Gauravseta** [comment]
@maxceem I want to work on this one.

**Comment by maxceem** [comment]
Sure @Gauravseta

**Comment by Gauravseta** [comment]
@maxceem working on . PR in few hours

**Comment by maxceem** [comment]
ok @Gauravseta

**Comment by Gauravseta** [comment]
@maxceem releasing myself as wont be able to complete it

**Comment by rashmi73** [comment]
@maxceem please give to me

**Comment by maxceem** [comment]
Thanks for update @Gauravseta 

@rashmi73 it's on you since your comment.

**Comment by rashmi73** [comment]
@maxceem point 1 is already completed.

I am confused regarding point 2 because currently:
1. I dont see any field such as "completion date" or " actual start date" when I edit any of milestone.
I have attached screenshot here which shows current UI when a milestone is edited(milestone is not completed).

![3217](https://user-images.githubusercontent.com/41687423/65355200-03ed1500-dc0f-11e9-96b1-6abc078098fd.png)

2. so do I need to add both fields here so that point 2 requirement are satisfied?

3. and If user logged in is not an Admin user then it will behave as it is behaving currently? 

4. For admin users while editing milestone with status completed, we need to show just 2 fields as editable? and rest all fields would be disabled/readonly ? because currently for completed milestone all fields are editable except duration field

**Comment by maxceem** [comment]
1. > though I am aware properties exist on milestone object, but it is not made visible on UI, am I correct?

    Right. We don't have these fields in UI yet. But we have them in the data from server.

2. yes, we should add these new fields for admins.

3. right

4. For admins we should show all the fields which we show now + 2 new fields.
    > and rest all fields would be disabled/readonly ?
    No, rest fields should be same like now - editable, except duration.

**Comment by rashmi73** [comment]
@maxceem any such similar implementation of type date?

because <FormFieldDate is giving error as it requires hardcoded propery fields "startDate" and "endDate"

**Comment by maxceem** [comment]
@rashmi73
> @maxceem any such similar implementation of type date?

Yes, we have example of date field when we edit phase, see `Start Date` field code https://github.com/appirio-tech/connect-app/blob/cf19/src/projects/detail/components/PhaseCard/EditStageForm.jsx#L286

![image](https://user-images.githubusercontent.com/146016/65368874-1e46e300-dc4f-11e9-8f1c-6c6ffdca4465.png)

You can use any name for such field.

**Comment by rashmi73** [comment]
@maxceem it is ready https://github.com/appirio-tech/connect-app/pull/3323

**Comment by rashmi73** [comment]
@maxceem kindly verify PR now

**Comment by rashmi73** [comment]
@maxceem PR update it should work fine now

**Comment by vikasrohit** [comment]
Deployed to production. Have to verify the logic yet but closing the issue for now.
