### ISSUE TITLE
[$50] Avoid reloading file icons in the Assets Library

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3211]
### Expected behavior
Icons for files should be loaded only once.

### Actual behavior
Every time when we hide/show some folder on the **Assets Library** page, the icons for files are reloading and blinking.

### Steps to reproduce the problem
- Open any project's **Assets Library** page with some files uploaded, for example, https://connect.topcoder-dev.com/projects/7977/assets
- Observe that icons for files are loaded.
- Open dev tools to watch network calls. 
- Switch to the **Links** tab and switch back to the files tab.
- Observe that icons for files are loaded again in the Network tab of the dev tools. And also visually we can see, that icons are not shown initially when we switch back to the files tab.

### Screenshot/screencast
Demo video: https://monosnap.com/file/MDgmQKiY0VUCUCukXtNqnURA1EZLsc

![image](https://user-images.githubusercontent.com/146016/61688511-cdeafc00-ad57-11e9-97d9-f15077494e8a.png)

--

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): any
- Account used: `pshah_manager`

**Comment by vikasrohit** [comment]
Good catch @maxceem

**Comment by suppermancool** [comment]
@maxceem pls assign this to me

**Comment by suppermancool** [comment]
@maxceem done in https://github.com/appirio-tech/connect-app/pull/3316

**Comment by vikasrohit** [comment]
Release to production.
