### ISSUE TITLE
[$30] Fix UI for REF on the project details page

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3212]
Very long REF goes beyond the screen.

See several examples below.

### 1. Short REF

- Looks good. On the same line as the date. Example: https://connect.topcoder-dev.com/projects/8193

   ![image](https://user-images.githubusercontent.com/146016/61703359-faad0c80-ad73-11e9-9af1-5be8a5ea2891.png)

### 2. Middle REF

- Goes to the next line and creates spaces, which looks not that good. Example: https://connect.topcoder-dev.com/projects/8192

   ![image](https://user-images.githubusercontent.com/146016/61703181-a9048200-ad73-11e9-8d38-a4fe6e28c18b.png)

### 3. Long REF

- Goes to the next line and cut by the screen, which is not good. http://connect.topcoder-dev.com/projects/8219

    ![image](https://user-images.githubusercontent.com/146016/61702947-3693a200-ad73-11e9-8ef7-73931d419773.png)

I guess we should agree on:
1. What is the expected normal maximal length for a `REF` code.
2. Find out where to put so it's showing in a good way for all lengths.

**Comment by vikasrohit** [comment]
@maxceem earlier we used to have a max length validation of 7 for ref code, however, that was lifted because of business requirements. I think the best solution is to show ellipsis for any text that exceeds width of 10 characters approximately. We should also show a tooltip with full ref code.

**Comment by maxceem** [comment]
I guess we also have to apply a similar fix for the project listing page:

![image](https://user-images.githubusercontent.com/146016/61767635-7dd36e80-ae17-11e9-9c1f-c276cfcd1517.png)

REF code in the table should be one-line only and if it's longer than one line, then it should be truncated with `...` at the end.

**Comment by vikasrohit** [comment]
Yes

**Comment by suppermancool** [comment]
@maxceem pls assign to me

**Comment by suppermancool** [comment]
@maxceem the Tooltip component don't show good if the text is too long for example:
https://gyazo.com/1985f1ad103b232bce93b0ac2238f5af

I think the default tooltip of browser look good in this case:
https://gyazo.com/3c4b1f5afe66bfd93589413d31786477

**Comment by suppermancool** [comment]
@maxceem done in https://github.com/appirio-tech/connect-app/pull/3315
I'm using the default browser tooltip because the Tooltip component don't look good for long text

**Comment by nahidshahin** [comment]
@maxceem can I work on it please ?

**Comment by maxceem** [comment]
@suppermancool I would prefer to use our customer tooltip as we use it across the project everywhere. What the issues with our custom tooltip?
I can see it goes under other elements on the page. Are there any other issues?

Note, usually the REF code would be one word without spaces.

**Comment by suppermancool** [comment]
Done in https://github.com/appirio-tech/connect-app/pull/3315

I fixed the goes under other elements problem. If the text too long it doesn't wrap and go outside the browser width.

**Comment by suppermancool** [comment]
@maxceem avoid above comment i can fix the tooltip text long problem

**Comment by suppermancool** [comment]
@maxceem done in latest commit

**Comment by RishiRajSahu** [comment]
Working fine on prod. Closing.
