### ISSUE TITLE
[$100] Tooltip is cut inside dropdown select

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3215]
### Expected behavior
Tooltip should be fully visible and go beyond the dropdown select.

### Actual behavior
Tooltip cannot go beyond the dropdown select and is cut.

### Steps to reproduce the problem
- Open any project with a phase which is not started yet, for example https://connect.topcoder-dev.com/projects/8219
- Click `edit` icon for the phase.
- Open the select for the **Status** and hover mouse to the disabled **Delivered** option.
- Observe that tooltip is shown, but it cannot go beyond the select dropdown list and it's cut.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/146016/61780613-70c57800-ae35-11e9-904f-c95373ab0186.png)

--

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): manager
- Account used: `pshah_manager`

**Comment by maxceem** [comment]
Sum up:
- this issue has to be fixed for ALL instances of the select component which is used in this form, not only for this particular form

**Comment by PrakashDurlabhji** [comment]
@maxceem I am starting on this. thanks

**Comment by PrakashDurlabhji** [comment]
@maxceem unable to solve it, please unassign me

**Comment by PrakashDurlabhji** [comment]
@maxceem dont unassign me it is done raising PR

**Comment by PrakashDurlabhji** [comment]
@maxceem please give it back to me it is done now

**Comment by maxceem** [comment]
Thanks for letting me know @PrakashDurlabhji.

This issue is open for pickup.

**Comment by maxceem** [comment]
Ok @PrakashDurlabhji assigned you back!

**Comment by PrakashDurlabhji** [comment]
@maxceem PR ready https://github.com/appirio-tech/connect-app/pull/3309

**Comment by PrakashDurlabhji** [comment]
@maxceem releasing this, it is open now

**Comment by nahidshahin** [comment]
@maxceem want to work on it, please.

**Comment by maxceem** [comment]
Thanks for update @PrakashDurlabhji 

@nahidshahin it's on you. Please, check the comments here about the possible implementation for this issue https://github.com/appirio-tech/connect-app/pull/3309

**Comment by maxceem** [comment]
As there is no update during more than 12 hours, this issue is now open for pick up.

**Comment by maxceem** [comment]
This issue may be harder than it looked initially, please, check the comments here about the possible implementation for this issue #3309

So the prize for this issue is raised to `$100`.

**Comment by codeMinter** [comment]
@maxceem please assign me this.

**Comment by maxceem** [comment]
Done @codeMinter

**Comment by codeMinter** [comment]
@maxceem not able to fix this, so opening it.

**Comment by gets0ul** [comment]
Please assign me.

**Comment by maxceem** [comment]
Sure, it's on you @gets0ul

**Comment by gets0ul** [comment]
@maxceem PRs are done and ready for review.

**Comment by RishiRajSahu** [comment]
Working fine on prod. Closing.
