### ISSUE TITLE
Notification emails showing same user name multiple times

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3216]
### Expected behavior
It should group the user name if the same user has done the multiple operations multiple times for the same project.

### Actual behavior
It is rendering user's name for every notification that is grouped for a project

### Steps to reproduce the problem
- TBD.
- TBD.
- TBD.

### Screenshot/screencast
<img width="913" alt="Screen Shot 2019-07-24 at 3 52 00 PM" src="https://user-images.githubusercontent.com/2417632/61786401-3525b080-ae2b-11e9-915e-00b6164b08bb.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by vikasrohit** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
Sum up:
- This email content is rendered using this template https://github.com/topcoder-platform/tc-notifications/blob/dev/emails/src/partials/topics_and_posts.html#L13. In particular the text which we want to update is rendered using `{{title}}` placeholder.
- `{{title}}` placeholder is defined by this line https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/notificationServices/email.js#L59
- where `EVENT_BUNDLES` is defined in https://github.com/topcoder-platform/tc-notifications/blob/dev/connect/events-config.js#L241

We need it to be done in a general way. So this feature would work for any type of event.

**Comment by codeMinter** [comment]
@maxceem please assign me this.

**Comment by maxceem** [comment]
Sure @codeMinter

**Comment by codeMinter** [comment]
Sorry @maxceem - started working on this, then realised the change is on other repo. Got pulled into something else then, give me few more hrs, working on this right now.

**Comment by maxceem** [comment]
Ok @codeMinter

**Comment by codeMinter** [comment]
@maxceem can we open this for pickup ?

**Comment by Gauravseta** [comment]
@maxceem let me give try to this. please give me. thank you

**Comment by maxceem** [comment]
Thanks for update @codeMinter.

@Gauravseta it's on you since your comment.

**Comment by maxceem** [comment]
As there is no update more than 12 hours, this issue is now open for pick up.

**Comment by Gauravseta** [comment]
@maxceem please assign me back, i will complete it else i will release myself thank you

**Comment by maxceem** [comment]
Ok @Gauravseta I'll keep it on you for 12 hours more.

**Comment by Gauravseta** [comment]
@maxceem releasing it for open

**Comment by maxceem** [comment]
Thanks for update @Gauravseta.

This issue is now open for pick up.

**Comment by sahil143** [comment]
@maxceem assign this to me

**Comment by maxceem** [comment]
Sure @sahil143

**Comment by sahil143** [comment]
```
 Kafka Consumer failed
error:  name=NoKafkaConnectionError, server=ec2-34-205-227-216.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-34-233-75-247.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-34-198-118-170.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-34-231-150-104.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-34-233-209-20.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-34-233-131-252.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-52-205-198-73.compute-1.amazonaws.com:9096, message=Connection timeout, name=NoKafkaConnectionError, server=ec2-52-4-109-80.compute-1.amazonaws.com:9096, message=Connection timeout, message=aggregate error, name=AggregateError, stack=AggregateError: aggregate error
    at SomePromiseArray._checkOutcome (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/some.js:82:17)
    at SomePromiseArray._promiseRejected (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/some.js:69:17)
    at Promise._settlePromise (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/promise.js:581:26)
    at Promise._settlePromise0 (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/sbudhwar/topcoder/tc-notifications/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5), length=8
error: Unable to connect to the database: message=ResourceRequest timed out, stack=TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/sbudhwar/topcoder/tc-notifications/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/sbudhwar/topcoder/tc-notifications/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10), name=TimeoutError
```

I have been trying to setup `tc-notifications` locally following these steps https://github.com/topcoder-platform/tc-notifications#local-deployment but I'm getting the above error with `npm start`. Any thoughts/ideas?

**Comment by maxceem** [comment]
I've provided more detailed steps to setup `tc-notifications` service on the forum, please have a look https://apps.topcoder.com/forums/?module=Thread&threadID=944657&mc=1#2368193.

Let me know if it helps, or there are any other difficulties.

**Comment by sahil143** [comment]
@maxceem releasing it for open.

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by gets0ul** [comment]
Please assign me.

**Comment by maxceem** [comment]
As there is no update more than 12 hours, this issue is now open for pick up.

**Comment by PrakashDurlabhji** [comment]
@maxceem I wish to work on it

**Comment by maxceem** [comment]
@PrakashDurlabhji sure. As we are short on time, this should be done during 12 hours or I'll have to un-assign you.

**Comment by maxceem** [comment]
@PrakashDurlabhji please, make the fixes to the PR https://github.com/appirio-tech/connect-app/pull/3307 first, so I could merge it. Thanks.

**Comment by PrakashDurlabhji** [comment]
@maxceem do i need to deploy tc-project-service too?

**Comment by maxceem** [comment]
@PrakashDurlabhji this task is in another repository https://github.com/topcoder-platform/tc-notifications

I think deploying it fully can be hard. But you still have to find some way to test it and provide a detailed guide how to do it.

Please, check this comment for details of this task https://github.com/appirio-tech/connect-app/issues/3216#issuecomment-529936721

**Comment by maxceem** [comment]
> @maxceem yea aware that tc-notifications to be deplpyed, but in doubt whether tc-project-service also needs to be?

I leave up to you. For the full testing - yes, you would have to deploy locally project service to trigger events to send notifications. But it's not required if you could figure out a simpler way for testing. 

> and the comment on forum i saw which has docker compose and all env variables, so can i replace all env variable in default.js in tc-notifications with the variable values provided in forum?

It's better if you define these environment variables in the console session before starting the tc-notifications service. This is to make sure that every place in the tc-notifications retrieve values in case not all places get values from the `default.js`.

**Comment by PrakashDurlabhji** [comment]
**if you could figure out a simpler way for testing**

yes I know its by using this command but still doubt  on some points.

docker exec -it test-kafka /usr/bin/kafka-console-producer --broker-list localhost:9092 --topic notifications.connect.project.post.created

**Comment by PrakashDurlabhji** [comment]
@maxceem i am midway. I saw code completely and came to know that originator can be tc-project-service or tc-notifications. means i can just make tc-notifications up and running then i need to trigger that code which would send email which is desired. 

Also can you please describe which kind of event is present in screenshot in issue description. like post created or post updated etc. 

it would give a more idea to solve it

**Comment by maxceem** [comment]
> Also can you please describe which kind of event is present in screenshot in issue description. like post created or post updated etc.

I'm not sure about this. The code has to be explored to find out which events trigger this email.

@PrakashDurlabhji as it's already several days this issue doesn't have a solution I have to un-assign you.

This issue is no longer in Bug Bash and would be handled in another way.

**Comment by maxceem** [comment]
This issue is done in `tc-notifications` repo via PR https://github.com/topcoder-platform/tc-notifications/pull/157

**Comment by vikasrohit** [comment]
Deployed to production.
