### ISSUE TITLE
'PROJECT NAME' and 'DESCRIPTION' Labels must display as 'Project Name' and 'Description'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#322]
### Expected behavior
-----------------------------------------------------------------
'PROJECT NAME' and 'DESCRIPTION' Labels must display as 'Project Name' and 'Description'

### Actual behavior
-----------------------------------------------------------------
'Project Name' and 'Description'

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click '+ New Projects'
- Click 'Other Work'
- Check the labels 'PROJECT NAME' and 'DESCRIPTION'
- To be consistent with the 'App Design & Dev' Tab --> 'PROJECT NAME' and 'DESCRIPTION' Labels must display as 'Project Name' and 'Description'

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_14-05-31](https://cloud.githubusercontent.com/assets/4592712/18946736/d1e3e486-864d-11e6-9ec1-5766d07e6301.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
@mahestro not a bug. As designed. All labels are ALL CAPS.

**Comment by mahestro** [comment]
In "App Design & Dev" tab, those labels are not all caps. There is  inconsistency there.
