### ISSUE TITLE
Sorting should not be applied on column if there is no data 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#323]
### Expected behavior
Sorting should not be applied on column if there is no data 
### Actual behavior
user able to apply sorting on ID 

### Steps to reproduce the problem
1. Open Application
2. Login with username sweta.singh
3. go to Project list 
4. Search for Ref keyword
5. No searched data
6. click on ID Column 

### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/18947145/7ba40b6c-864f-11e6-9c93-d97464d08db8.png)

--

#### Environment
- OS: Windows 7
- Browser (w/version): Chrome LAtest 
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
On hold. UX improvement needs confirmation.

@fnisen ?

**Comment by fnisen** [comment]
Agree, not a bug, but a UX suggestion. Similar to https://github.com/appirio-tech/connect-app/issues/273. Don't think it's likely that a user will try to sort when there are no results and get confused.

**Comment by parthshah** [comment]
Hide header.
