### ISSUE TITLE
Enhancement for Support new Project Templates format

### ISSUE THREAD

**Issue by Gauravseta** [appirio-tech/connect-app#3231]
@Gauravseta You recently participated in this challenge https://www.topcoder.com/challenges/30097730/?type=develop&noncache=true
The winner did a good job and created good reusable methods. He used another approach then you in your submission and he fixed data in the Redux store on data load see https://github.com/appirio-tech/connect-app/blob/feature/metadata-version/src/reducers/templates.js#L92-L94

But for the next step updating, this data in the Redux store will not work. So I would like to use your approach which you use in your submission:
- don’t update data inside Redux store, and update data inside components as you did. But use reusable methods which has been created by the winner of the last challenge https://github.com/appirio-tech/connect-app/blob/feature/metadata-version/src/helpers/templates.js#L36-L93

**Comment by Gauravseta** [comment]
@maxceem Kindly assign it to me thank you

**Comment by Gauravseta** [comment]
@maxceem PR https://github.com/appirio-tech/connect-app/pull/3232

**Comment by maxceem** [comment]
Closing it at it's a part of a bigger task which is tracked in Connect Phase.
