### ISSUE TITLE
'Project Type' and 'Status' drop down display in one line

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#324]
### Expected behavior
-----------------------------------------------------------------
'Project Type' and 'Status' drop down display in one line

### Actual behavior
-----------------------------------------------------------------
Layout issue in FILTER in Portrait view

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click FILTERS

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not valid. iPad
