### ISSUE TITLE
[Metadata Management] show empty value by default in selects

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3246]
### Expected behavior
Show empty value in select by default when creating new objects.

### Actual behavior
Show the first value in select by default.

### Steps to reproduce the problem
- Go to metadata editing UI http://local.topcoder-dev.com:3000/metadata/projectTemplates
- Start creating any kind of template which has select dropdown with options to choose
- By default, it would show that the first option in select is selected
- This may lead to the fact that we can easily forget to select correct values. It's better to keep them unselected by default, so user would be obligated to select them manually.
- This should be done for all kind of new templates and all selects inside them.

### Screenshot/screencast
Examples:

![image](https://user-images.githubusercontent.com/146016/62515464-f6ddb780-b854-11e9-9c0d-fb8cb156a887.png)

![image](https://user-images.githubusercontent.com/146016/62515504-0e1ca500-b855-11e9-9b7f-ad51e847f9a7.png)

**Comment by maxceem** [comment]
Done in commits https://github.com/appirio-tech/connect-app/commit/1d7b3cc3a6e4d74efc5ac57e4a432d84253cd377, https://github.com/appirio-tech/connect-app/commit/d932d1d417f3942dc830f4aea420258c0c8250ea

**Comment by lakshmiathreya** [comment]
@RishiRajSahu pls review and mark as Pass.

**Comment by maxceem** [comment]
This is done. When we creating new records we show `- Select -` instead of some random value:

![image](https://user-images.githubusercontent.com/146016/98963460-5161cb00-2510-11eb-86b4-dbaddee71cbb.png)

Also, if some existent record doesn't have a value, dropdowns also are showing `- Select -` instead of showing some random value when there is not actual value:

![image](https://user-images.githubusercontent.com/146016/98963570-70605d00-2510-11eb-8e18-771337091be9.png)

So this works good, and may be closed.

**Comment by RishiRajSahu** [comment]
Closing as working as expected.
