### ISSUE TITLE
[Tablet] Must remove the Search term from the textbox

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#325]
### Expected behavior
-----------------------------------------------------------------
[Tablet] Must remove the Search term from the textbox

### Actual behavior
-----------------------------------------------------------------
Last Search term is displayed even the user removed it from the textbox

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click SEARCH
- Type "test"
- Click SEARCH
- Now remove the text from the (x) button

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not valid. iPad
