### ISSUE TITLE
Form does not update, after approving and activating a scope change request

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3251]
### Expected behavior
The form should update itself with the updated scope values after the scope change request is activated.

### Actual behavior
The forms remains as is i.e. in old state even after the activation of the scope change request. It refreshes only after page reload.

### Steps to reproduce the problem
- Go to any project which is in `reviewed` or above statuses, please ensure that the `Target Devices` question has more than one devices selected before moving to the `reviewed` status
- Go to scope tab
- Edit couple of questions in the scope form
- Hit `Submit Change Request` button to create the request
- Hit `Approve` and then hit `Activate` buttons
- Observe the form, none of the value change specified by the change request, is not applied to the form. 

### Screenshot/screencast
N/A

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Admin (to test the flow with same login)
- Account used: N/A

**Comment by vigneshTheDev** [comment]
Hi @vikasrohit I'll look into this issue.

**Comment by vigneshTheDev** [comment]
Hi @vikasrohit, I've raised the pull request to fix this issue. Please review.

**Comment by vikasrohit** [comment]
Working fine @vigneshTheDev Thanks
