### ISSUE TITLE
Fix user avatar size (URL)

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3252]
In the new left sidebar and on the user profile page we are loading the full-sized user avatar directly from S3 

![image](https://user-images.githubusercontent.com/146016/62753792-9e4e2a80-ba9f-11e9-802e-b8865010fee9.png)

Such images may have a very big size.

Instead, we should load avatars through the cloudfront service, as we do it for use avatar in the top toolbar:

![image](https://user-images.githubusercontent.com/146016/62753846-e2412f80-ba9f-11e9-874d-c60cc9e53857.png)

Before we fixed this issue for the top toolbar https://github.com/appirio-tech/connect-app/issues/2839. We should fix this issue now for all places in Connect App where we show user avatar, if there any others not only for mentioned above.

TODO:
1. Find all the places where we load user avatars.
2. Fix all of them to load avatars using cloudfront service. And it should load image in the size which is necessary for the particular avatar image, like 35, 40, 80 and so on.

**Comment by maxceem** [comment]
We already have such issues in the past:
- https://github.com/appirio-tech/connect-app/issues/2839
- https://github.com/appirio-tech/connect-app/issues/1663

**Comment by maxceem** [comment]
This is now fixed via https://github.com/appirio-tech/connect-app/commit/0da86983999215f189d73033cfb951510cd33fa9
 and can be tested on DEV.

**Comment by nithyaasworld** [comment]
@maxceem But the quality of the cloudfront images are not looking good! Please find the difference below:

![image](https://user-images.githubusercontent.com/5114190/75220514-9cdb1a00-57c5-11ea-8d5a-c137fe6fb7a5.png)


Instead of using cloudfront (which compromises the quality), can we restrict the user from uploading images of big-sizes and always render from s3? Currently we are not restricting the user from uploading images of big-sizes.

**Comment by maxceem** [comment]
Nice catch. We can get from the CloudFront images in double resolution (`60` -> `120`) which should make them look quite the same as in original size while still keeping their size small. 

I've updated this for user avatars on the sidebar and pushed to DEV. Let me know if this looks good to you or no.

![image](https://user-images.githubusercontent.com/146016/75221967-036c3200-57de-11ea-92a1-5fec7e94d226.png)

Note, that all other user pictures are still shown from CloudFront in the 1x size, so we may think if we also should get them in 2x size too, to increase the quality.

**Comment by vikasrohit** [comment]
How much time it would take us to replace all images with 2x, if that looks better?

**Comment by maxceem** [comment]
> How much time it would take us to replace all images with 2x, if that looks better?

about 10 minutes (replace all images for user avatars)

**Comment by nithyaasworld** [comment]
Thanks @maxceem. It looks better now!

**Comment by nithyaasworld** [comment]
One more thing is that, we still show the profile pic in the below place from s3. Should we also have to change it to show from cloudfront?

![image](https://user-images.githubusercontent.com/5114190/75232235-e08d4e00-57dc-11ea-91c4-65e40a05ef47.png)

**Comment by vikasrohit** [comment]
> about 10 minutes (replace all images for user avatars)

Can you please that now as we got confirmation from @nithyaasworld that it is looking better with 2x resolution image.

**Comment by maxceem** [comment]
Yes, we should. I've updated the code to also use CloudFront for this place with double size (`80` -> `160`.

I also did some testing regarding image quality for this place, as here the image is quite big:

1. CloudFront 80px (1x)

    ![image](https://user-images.githubusercontent.com/146016/75233048-32d96980-57f3-11ea-8700-bfccc769f431.png)

2. CloudFront 160px (2x)

    ![image](https://user-images.githubusercontent.com/146016/75233117-4be21a80-57f3-11ea-87dc-ed28655da6e4.png)

3. S3 (original)

    ![image](https://user-images.githubusercontent.com/146016/75233152-5ef4ea80-57f3-11ea-9da1-9e0825a42d57.png)

**Comment by vikasrohit** [comment]
Thanks @maxceem, though, I am not able to find difference between 1x and 2x images. @nithyaasworld do you think 2x option is better than 1x?

**Comment by nithyaasworld** [comment]
Yes @vikasrohit 2x option would be better. In 1x, the girl's red shrug is blurry. Whereas in 2x, it is almost matching the colour of the S3 image.

**Comment by maxceem** [comment]
@vikasrohit @nithyaasworld I've updated all user avatars across the app to use double size photo.

It's already pushed to DEV.

**Comment by lakshmiathreya** [comment]
Pls clarify @vikasrohit @maxceem - is a size check included?

**Comment by maxceem** [comment]
> is a size check included?

@lakshmiathreya no. We still let users to upload any photos sizes. But we show all the users photos in small size automatically (not the original photo). 
To increase the quality we show all the user photos in double size. So if the place for a photo is 40 x 40 px we show photos in size 80 x 80 px.

**Comment by vikasrohit** [comment]
@lakshmiathreya I think there is a separate issue #3627  for file upload size which we haven't prioritize yet. We will prioritize it in our next release planning. This issue can be closed as the display size of profile image has been increased to 2x for better display.
