### ISSUE TITLE
[Tablet] Profile drop down menu layout issue; Logout is displayed in two lines

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#326]
### Expected behavior
-----------------------------------------------------------------
[Tablet] Must increase the width of the drop down menu

### Actual behavior
-----------------------------------------------------------------
Profile drop down menu layout issue; Logout is displayed in two lines

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click PRofile image
- Check the drop down
- Logout is displayed in two lines

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not valid. iPad
