### ISSUE TITLE
Connect Registration/Profile Page Improvements

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3263]
- [x] Mark Required Fields https://github.com/appirio-tech/connect-app/issues/3262
- [x] Split First Name & Last Name into 2 Fields

- On the **registration** page for Connect, there should now be two fields for name: First Name and Last Name.
- On the **profile** page for Connect, there should now be two fields for name: First Name and Last Name.

- [x] Update Business Number in Profile Settings

- Update 'Business phone' on the **profile** page in Connect to match the **registration** page, where the requirement for country code is called out and the dropdown of codes by country is available.

- [x] Country List Alphabetization

- Ensure the **registration** page's country list in the dropdown menu is in descending alphabetical order
- Ensure the **profile** page's country list in the dropdown menu is in descending alphabetical order

- [ ] Country List Responsive Typing

- Enable responsive typing/selection for country selection on the **registration** page.
- Enable responsive typing/selection for country selection on the **profile** page.

**Comment by RishiRajSahu** [comment]
@vigneshTheDev are you available to take up this issue ?

**Comment by vigneshTheDev** [comment]
Hi @RishiRajSahu, is registration page part of the connect-app?

**Comment by RishiRajSahu** [comment]
@vigneshTheDev Its part of accounts app https://github.com/appirio-tech/accounts-app

**Comment by vikasrohit** [comment]
It might save some time from you investigation @vigneshTheDev, registration page is part of accounts-app (angular app) as Rishi said, however, it is using a React component which is coded in https://github.com/appirio-tech/react-components/tree/feature/connectv2/components/RegistrationScreen. Angular provides props to the component and the component has the logic of UI control and then it calls the callbacks defined in the angular model.

**Comment by vigneshTheDev** [comment]
Thanks @vikasrohit. That's helpful.

**Comment by vigneshTheDev** [comment]
Hi @RishiRajSahu, could you please clarify these:

> Enable responsive typing/selection for country selection

Here, are we looking for replacing the existing control with another one that allows typing on mobile devices? Like this one: https://ibb.co/T1Rps9J?

> registration page's country list

We don't have the country list on the registration page right? we're deriving country name from the country code of business phone. Should we add the country list?

**Comment by vigneshTheDev** [comment]
> Split First Name & Last Name into 2 Fields

I see 2 traits (basic_info & connect_info) are getting updated whenever we save the profile settings. In the backend, it looks like basic info modal directly supports 'firstName' and 'lastName' fields. But connect_info model supports only 'firstNLastName' field. Check `service/src/main/java/com/appirio/service/member/api/MemberProfileBasicInfo.java` & `service/src/main/java/com/appirio/service/member/api/MemberProfileConnectInfo.java` files. 

Should we keep it that way or should we modify the connect_info model to support firstName and lastName? If we need to modify the connect_info model, please provide me access to the member service repo.

**Comment by vigneshTheDev** [comment]
> Ensure the country list in the dropdown menu is in descending alphabetical order

I'm curious why we want to display the country list in descending order instead of ascending order. Just want to understand the requirement clearly. We want to display _Zimbabwe to Afghanistan_ instead of _Afghanistan to Zimbabwe_ right?

**Comment by vigneshTheDev** [comment]
> Mark Required Fields #3262

Registration page has two more required fields: username & password. Should we mark them as well?

**Comment by RishiRajSahu** [comment]
@vigneshTheDev 
1. Yes we want responsive suggestion on the field while typing for the country names for both web/mobile.
2. Regarding country list, I have check it once myself the ultimate goal is to make registration/profile page behave similar, still I will get back to you on that. Where does country code for phone is coming ?
3. Keep connect_info model as it is, but we should be able to render it correctly on profile page of Connect as separate
4. I think its A -> Z, A being the biggest.
5. Yes mark username & password too.

**Comment by vigneshTheDev** [comment]
Thanks for the clarifications @RishiRajSahu 

2. Country code is coming from the business phone number input. Please look at these lines: 
* https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/RegistrationScreen/index.jsx#L153
* https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/RegistrationScreen/index.jsx#L66
* https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/RegistrationScreen/index.jsx#L90

**Comment by RishiRajSahu** [comment]
@vigneshTheDev so we are implicitly picking country as per phone country selected. So we can have same behaviour profile page as well, the difference would be the country filed will be populated similar to phone  country codes, ref this issue https://github.com/appirio-tech/connect-app/issues/3245 , if the country list suggest in this issue is the one used for phone number country.

Another thing, we need to take care of country update after updating our profile page because - 
1. changing the phone number code will update the country selected as well
2. changing the country will also affect phone number code

should we show some alert like `changing the phone country code would result in change of selected country as well below` ?

**Comment by vigneshTheDev** [comment]
@RishiRajSahu, we may not be able to use https://github.com/appirio-tech/ng-iso-constants/blob/dev/src/ng-iso-constants/services/iso-3166.js in connect-app directly, as it's inside an angular service. Shall we use this instead: https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/ISOCountries.js? It's exactly the same as the list in ng-iso-constants/services/iso-3166.js.

About the country update,
We can tie the country code of business phone with the country input. But if there is a scenario, where we should allow different values for country code of business phone and country selection, it'll negatively impact the UX. 
Shall we provide an option to update the country code / country selection instead of automatically changing? The flow I'm suggesting is like this:

* When the user changes the country code of business phone
* we show a hint below the business phone field asking if the user wants to update country selection as well. 
* If he confirms, we update the country selection. Otherwise, we leave it intact.

We can handle the change of country selection in a similar way.

If you don't see such scenario, we can go with automatic update as well (like you suggested). But in that case, the country selection is redundant. We can remove it and go with the registration page way of handling.

**Comment by vigneshTheDev** [comment]
Also, updating country code based on country change can be tricky, as multiple countries may share the same country code, but different area code (see: https://en.wikipedia.org/wiki/List_of_country_calling_codes#Zone_1:_North_American_Numbering_Plan). So, if we want to update business phone based on country selection, we may have to update both the country code and area code.

**Comment by RishiRajSahu** [comment]
@vigneshTheDev 

- yep if this is similar https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/ISOCountries.js use this.
- It won't be redundant, as later with Connect, user might see it easier to change country via the country selection, but agree if we have to change both country and area code then it will be tricky, but I don't think we give option of selecting area code right now, its users responsibility to fill area code manually, for eg - check the code we insert when selecting UnitedStates on registration page.

**Comment by vigneshTheDev** [comment]
@RishiRajSahu 
For the second point, yeah that's correct. Area code is not inserted automatically. So, we'll tie the country code and the country selection. Which way would you suggest? automatically updating the country code or giving a hint to the user to update?

**Comment by RishiRajSahu** [comment]
@vigneshTheDev automatically update because we always want the two to be in sync always, but do show some hint that 'one gets affected because of other' so that user knows what's happening.

**Comment by vigneshTheDev** [comment]
@RishiRajSahu Ok got it. Thanks! I'll implement the same and will raise the PR by today.

**Comment by vigneshTheDev** [comment]
Hi @RishiRajSahu, I've implemented the automatic update of country selection / country code  in profile settings page. I'm working on the same in registration page. will push soon

**Comment by vigneshTheDev** [comment]
@RishiRajSahu Please review profile settings. You can also review the registration screen except the country list related issues

**Comment by vigneshTheDev** [comment]
Hi @RishiRajSahu, I added the country selection as well. Now all the fixes are ready to be reviewed. Thanks!

**Comment by RishiRajSahu** [comment]
@vigneshTheDev sure will have a look today !

**Comment by RishiRajSahu** [comment]
@vigneshTheDev reviewed the PRs looks good to me except a single comment to address, other than that could you tell - 
1. So we don't need any changes to accounts app side, as it is using react-components ?
2. Could you point me to the logic where we have enabled the responsive country select ?

**Comment by vigneshTheDev** [comment]
@RishiRajSahu, 
1. We don't need any changes in the accounts app as the registration screen component is fully contained in the react-components.
2. I replaced the earlier dropdown with the searchable select box that allows typing and selecting: https://github.com/appirio-tech/connect-app/pull/3272/files#diff-124f6a815390e29d35c0eb7c2beb7999L151-L157. Did I misunderstood the requirement? Please let me know.

**Comment by RishiRajSahu** [comment]
@vigneshTheDev Sorry I was out since then, okay got it, actually we are using firstname and lastname from the `basic_info` trait, that's why its all good. Okay then I think we are good, I'll merge the changes to dev and will test the UI on dev.

**Comment by vigneshTheDev** [comment]
No problem :) 
Thanks for the updates @RishiRajSahu!

**Comment by vigneshTheDev** [comment]
Hi @RishiRajSahu, pushed the code related to connect app fixes:
https://github.com/appirio-tech/react-components/pull/330
https://github.com/appirio-tech/connect-app/pull/3284

**Comment by vigneshTheDev** [comment]
Hi @RishiRajSahu, pushed another commit that fixes the registration page issues: https://github.com/appirio-tech/react-components/pull/331

**Comment by RishiRajSahu** [comment]
Done and pushed to prod.
