### ISSUE TITLE
Show correct error alert on operations with project

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3266]
### Expected behavior
Error alert should contain the text of correct error from the server like: `Error updating project: <error from server>`

### Actual behavior
No matter what error happens during a request to the server, the error message is always the same and not relevant: `Please add a name for your project and then try saving again.`

### Steps to reproduce the problem
- Open any project like https://connect.topcoder-dev.com/projects/8317/scope
- Disable the internet.
- Change the project status to another.
- As there is no internet, the error would happen and error alert would be shown `Please add a name for your project and then try saving again.`
- I don't have a universal way to trigger server-side error which would return an error message. But until the next issue is fixed server-side https://github.com/topcoder-platform/tc-project-service/issues/366 anytime when we change project status we get the error from server `Unable to update project`, but instead the standard error about project name is shown.

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/146016/63143723-4c1e8380-c022-11e9-9251-fed689d8a625.png)

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): any
- Account used: `pshah_manager`

**Comment by vikasrohit** [comment]
I fixed few minutes back with https://github.com/appirio-tech/connect-app/commit/23f7986d6ae451c602edccfe3434a0ca11ab7f0f

**Comment by maxceem** [comment]
So fast @vikasrohit :-) I've tested and works good. I only suggest using some default error like `Project updating failed` instead of an empty string, in case we didn't get any error from the server or we just don't have internet.

**Comment by vikasrohit** [comment]
Yep, we can add a default string as well. I assumed that our API should always send some basic error string, but I think you are right it does not harm to add the one directly in the front end as well.

**Comment by vikasrohit** [comment]
Implemented the suggested changes https://github.com/appirio-tech/connect-app/commit/a54178735db9b589cab196f12b493f4041906245
