### ISSUE TITLE
Allow a max number of charatcers to be set in invite code

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#327]
Expected behavior
------------------------------------------------------------

- Set  a validation message for max number set in field Invite Code eg 10 characters.

Actual behavior
------------------------------------------------------------

- Any number of characters can be set.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as copilot role.

- New Project.

- Complete required fields and set in Invite code (optional) a long characters word.

- Save.

Environment

------------------------------------------------------------

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2 
            IE 11.0
User role: copilot role
Account used: cp-superstar

------------------------------------------------------------

![code-invirte](https://cloud.githubusercontent.com/assets/5114907/18948142/8bd79f82-863e-11e6-95bf-82b4e677325c.png)

**Comment by mahestro** [comment]
Valid. It breaks projects listing page as consequence.

**Comment by parthshah** [comment]
Restrict length to 25.
