### ISSUE TITLE
[$150] Show Created By for files and links list in Assets Library

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3273]
We should add `Created By` column for the files and links list in Assets Library

**Comment by vikasrohit** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
We can show it for all files, but at the moment we don't have information who created links for the project. We can still show who created links inside posts, as we know who created a post:

![image](https://user-images.githubusercontent.com/146016/63419698-d5292680-c437-11e9-99c6-80946ab9e05c.png)

Should we update the client-side code to store the information about who created links inside project data? 

Also, if we don't write some additional logic server-side, anybody could update this data in the project data. I don't think it's sensitive information, but if we want to make sure that nobody can fake `createdBy` we should validate project data server-side.

**Comment by vikasrohit** [comment]
Got it. We are storing the links in a JSON field not as a primary object so we don't have the audit fields there. I think, we should start capturing the audit fields (createdBy, createdAt, updatedBy and updatedAt) inside this JSON for every link to show the details about owner of the link.
I didn't get the validation part though. How can one fake `createdBy`? Oh, I think you mean that with `PATCH` request for the project, if we send the bookmarks field as well, it would allow any privileged user to fake the data. Yes, I think we need to do some changes in code for fixing that.

**Comment by maxceem** [comment]
If we we would store `createdBy` for links, should we restrict editing links only to users who has created such link as we do for files? If so, should admin still be able to edit any links no matter who created them?

**Comment by maxceem** [comment]
Sum up:
1. Currently, when we are creating links we store them inside `project.bookmarks` JSON in the next format:
    
    ![image](https://user-images.githubusercontent.com/146016/64605052-fa241000-d3cb-11e9-91d1-46e9fa64286c.png)

   Additionally, we should add the next properties for each link:
   - `createdAt` - creation date in format `2019-09-05T05:52:21.240Z`
   - `createdBy` - id of the user who created the link in format `22688955` (number)
   - `updatedAt` - should be updated when we `create` and `update` links
   - `updatedBy` - should be updated when we `create` and `update` links

2. Add column `Created By` on [Assets Library tab](https://monosnap.com/file/oyyG3vhfXmjntL2p9aBUMTQKtOyfpv) see [demo project]() and on the [Work Assets tab](https://monosnap.com/file/eyCsPVwJVwFkmfqfFaSAyolcjCObbX) see [demo project with works](http://local.topcoder-dev.com:3000/projects/8345/workstreams/237/works/6161)

    Show user `<FirstName> <LastName>` or `<userHandle>` with the tooltip, the same way as we do in [project list](http://local.topcoder-dev.com:3000/projects?sort=updatedAt%20desc) see [screenshot](https://monosnap.com/file/VPqb49qXUpvj9t5MSh2jz4pJxrKCMa).

    We would have to load user details by `userId` for all the users which are listed in `createdBy` or `updatedBy`, but only **if information for them has not been loaded yet**. See how we do it on the project listing page.
   
Note. That some files and links comes from the posts. In such cases we should show use `createdBy` from the post from which we extracted the file or link.

**Comment by jankyzhang** [comment]
@maxceem pls assign this to me, thanks

**Comment by maxceem** [comment]
done @jankyzhang

**Comment by jankyzhang** [comment]
@maxceem   
About the value of the fields (createdBy, createdAt, updatedBy and updatedAt) :  
We should make them the same as project's fields (createdBy, createdAt, updatedBy and updatedAt).  
Right ?    
Just like:  
link.createdBy = project.createdBy

**Comment by jankyzhang** [comment]
@maxceem,  
Please check the code.  
Thanks much.

**Comment by maxceem** [comment]
> About the value of the fields (createdBy, createdAt, updatedBy and updatedAt) :
> We should make them the same as project's fields (createdBy, createdAt, updatedBy and updatedAt).
> Right ?
> Just like:
> link.createdBy = project.createdBy

No. We should set them when we create or update them.
So when user creates a link we should set `createdBy` to the current user id, and `createdAt` to the current time and same for `updatedBy` and `updatedAt`.
Also, when we update particular link, we should update values for `updatedBy` and `updatedAt`.

For old links which already don't have the fields, don't show anything in the column, show just `-`.

**Comment by jankyzhang** [comment]
@maxceem  ,  
We need to add the fields (createdBy, createdAt, updatedBy and updatedAt) at **tc-project-service**.
then show createdBy in **connect-app**.
Right ?

**Comment by maxceem** [comment]
> We need to add the fields of bookmarks (createdBy, createdAt, updatedBy and updatedAt) at tc-project-service.

We store links as JSON object 
https://user-images.githubusercontent.com/146016/63419698-d5292680-c437-11e9-99c6-80946ab9e05c.png

So we don't have to do any changes server-side for this task. When we create a link client-side, we should add to this JSON for a new link createdBy, createdAt, updatedBy and updatedAt.

And when we update link, update its updatedBy and updatedAt.

And then show createdBy in client-side.

So all the changes for this task can be done client-side.

**Comment by jankyzhang** [comment]
@maxceem 
Thanks for the reply.  
We have update the code.
However, It fail to work due the server-side Valdiations.
![screenshot-local topcoder-dev com_3000-2019 09 21-09_47_20](https://user-images.githubusercontent.com/2173685/65366428-4554e300-dc56-11e9-8c22-ba86d4ca8dac.png)

**Comment by maxceem** [comment]
@jankyzhang I've fixed it server-side. Could you please try now.

**Comment by jankyzhang** [comment]
@maxceem , I just test it. It work well. :-)

**Comment by maxceem** [comment]
@vikasrohit after this issue is implemented as per description I can see some improvements which we can do.

1. So far we don't show `Created By` and `Modified` for folders:

    ![image](https://user-images.githubusercontent.com/146016/65853452-2956ed00-e38c-11e9-9d61-4ce341090343.png)

    1. As these folders represent posts, we can show the `Created By` for folders as `Created By` of the corresponding post. Which makes sense I think.
    2. Regarding `Modified` date it's not that straightforward.
        - If the folder contains files, we can show the `Modified` date of the latest modified file.
        - if the folder contains links we don't have date of the separate link modification inside post as we just extract links from posts in runtime. We can show the date when the post has been modified, though if we modify the post it doesn't mean that we modified the link. Though in general I think users don't modify posts so often. So we can show for links the `Modified` data of the post, and in most cases it would be the correct time.

2. For links inside the folders (posts) so far we don't show `Modified` date. The same thing like for folders of links we can show the date when the corresponding post has been modified.

**Comment by vikasrohit** [comment]
1.
  i. Yes we can show the `createdBy` of the post for the folders for now.
  ii. if the logic is not difficult to implement, we can show the `modified` date for the latest file/link as you said. However, I think we don't need to show `modified` and we can actually show the creation date instead.
2. Similar to 1.ii) we can show creation date instead of modification date.

**Comment by maxceem** [comment]
Thanks for clarifications @vikasrohit.

@jankyzhang would you like to make the improvement to this task as described in comments above:
1. Show `Created By` for the folders.
2. Show createdBy date in the `Modified` column for the files and links inside folders.

The prize for this issue can be increased for `$25` more for the improvement. The only thing this should be done today.

**Comment by vikasrohit** [comment]
> Show createdBy date in the Modified column for the files and links inside folders.

and use `Created at` as column header instead of `Modified`

**Comment by jankyzhang** [comment]
@maxceem ,  
Thanks. I am interesting to make the improvement.  
Two questions:   
1. 'Created By' for the folders according of 'feed.userid' and 'phase.createdby' . right ? 
2.How to get the 'createdBy date' for the files and links from 'feeds' and 'phaseFeeds'?

**Comment by maxceem** [comment]
1. > 'Created By' for the folders according of 'feed.userid' and 'phase.createdby' . right ?

   It should be always 'feed.userid'. The reason for this is that we would have here folders from various posts, not only from phases (later).

2. yes. 'createdBy date` should come from 'feeds'.

@jankyzhang Let me know if my answers help.

**Comment by jankyzhang** [comment]
@maxceem 
About the 'createdBy date`, Now not the 'createdAt' field in 'feed.post' . 
We should select which field  in 'feed.post' as the 'createdBy date` ? 
![screenshot-local topcoder-dev com_3000-2019 09 30-17_13_39](https://user-images.githubusercontent.com/2173685/65872181-9aa99680-e3b2-11e9-90e2-7cde3f4831b6.png)

**Comment by maxceem** [comment]
@jankyzhang use the field called `date`.

**Comment by jankyzhang** [comment]
@maxceem 
I just update the code.
Please check it.
Thanks.

**Comment by vikasrohit** [comment]
Working as per requirements on production.
