### ISSUE TITLE
[$40] Need red cue for new file or link uploaded for the project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3274]
We do not have red cue shown when there is new file or link uploaded to the project. Should we add a red cue to the left side panel against the Assets Library tab whenever there is a new file/link created in the project?

**Comment by maxceem** [comment]
@vikasrohit should we implement this or wait for product team to confirm?

**Comment by vikasrohit** [comment]
I think we can take this liberty to implement this feature, provided that we are able to generate the notification cue for both files and links and have some way to distinguish the newly added/links from others just like we do for messages.

**Comment by maxceem** [comment]
Sum up:
1. Show the number of unread notification regarding files and links on the `Assets Library` menu item:
 
   ![image](https://user-images.githubusercontent.com/146016/64604585-14a9b980-d3cb-11e9-84ac-bce06e0224bf.png)

2. Also, in the project list we are showing the total number of notifications for the project.

    ![image](https://user-images.githubusercontent.com/146016/64604650-2d19d400-d3cb-11e9-9b7a-532a84d4376d.png)

     This number has to include the number of unread notifications regarding files and links also.

3. Here are the notifications types to count https://github.com/appirio-tech/connect-app/blob/feature/workstreams/src/config/constants.js#L1050-L1051

**Comment by vikasrohit** [comment]
Do we have tooltips on these red cues? If not, we can add tooltips which describes what the number means.

**Comment by maxceem** [comment]
@vikasrohit created a separate issue for showing tooltips https://github.com/appirio-tech/connect-app/issues/3297

**Comment by suppermancool** [comment]
@maxceem pls assign this to me, thanks

**Comment by maxceem** [comment]
Sure @suppermancool

**Comment by suppermancool** [comment]
@maxceem done in https://github.com/appirio-tech/connect-app/pull/3308 .

**Comment by vikasrohit** [comment]
Verified on production.
