### ISSUE TITLE
Text is not displayed in the menu items in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#328]
### Expected behavior
-----------------------------------------------------------------
Must display the name of the menu items as other browsers

### Actual behavior
-----------------------------------------------------------------
Text is not displayed in the menu items in IE11

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project
- Check the menu

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_14-56-02](https://cloud.githubusercontent.com/assets/4592712/18948528/10eed9ae-8655-11e6-9c6d-7df795954838.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
It's expected to work like that. Not valid.
