### ISSUE TITLE
[$10] P3: Update Customer Invitation Management

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3294]
**Objective:** Streamline the customer invitations process so that there is one workflow option for sending and managing invitations.

<p></p>

**Requirements:**

- Remove the "Manage" button that customer users see next to their "Team"

- Update the button that reads 'Invite people' to read 'Manage Invitations'

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2754162

**Comment by RishiRajSahu** [comment]
@maxceem you can include this one in bug bash !

**Comment by maxceem** [comment]
Sure @RishiRajSahu.

For Topcoder team we keep the `Manage` link as it is now, right?

![image](https://user-images.githubusercontent.com/146016/65228842-dbaccb80-dad3-11e9-9e1b-1be6a274c7d5.png)

**Comment by RishiRajSahu** [comment]
@maxceem yes as we don't have any separate invite button for Topcoder team.

**Comment by sahil143** [comment]
@maxceem assign this to me

**Comment by sahil143** [comment]
@maxceem done in https://github.com/appirio-tech/connect-app/pull/3317
I have removed the `Manage` button but kept the `View` button in `Team`. If `View` button also needs to be removed, please let me know I will make the changes accordingly.

**Comment by maxceem** [comment]
Thank you for screenshots in the PR @sahil143. It looks like what we need.

**Comment by lakshmiathreya** [comment]
<img width="1108" alt="Screenshot 2019-10-01 at 4 07 42 PM" src="https://user-images.githubusercontent.com/51733042/65955409-adc96e80-e465-11e9-9aaa-c3b369a6da9c.png">
As per requirement 'Invite People'  needs to be changed to 'Manage invitations'. @RishiRajSahu

**Comment by vikasrohit** [comment]
@lakshmiathreya it was supposed to change the `Invite People` in the left panel on the project's dashboard, not at this place in dialog box itself. Now, as user is in `Manage Invitations` screen, it does not make sense to say `Manage Invitations` again instead of current text `Invite More People`. Let me know I miss understood the issue.

**Comment by RishiRajSahu** [comment]
@lakshmiathreya I got it why there is a confusion, check the first screenshot it would be clear then. Is it working fine otherwise ?

**Comment by RishiRajSahu** [comment]
Working fine, closing the issue.
