### ISSUE TITLE
P0: Registration Pages: Modify 'Marketing opt-in' Behavior

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3295]
**Objective:** Currently, users cannot complete registration until they opt-in to receive marketing communications. Users should be able to register, whether they choose to opt-in or not.

<p></p>

**Requirements:**

- Update the message wording at the bottom of the intake form to read: "I do not want to receive marketing communications from Topcoder." Therefore, if they do not check this box, they are agreeing to receive marketing communications.

- Update registration submission behavior to enable customers to complete registration, whether they choose to opt-in or opt-out of marketing communications.

- Send client marketing opt-in/out selection to SFDC

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2748431

**Comment by maxceem** [comment]
@RishiRajSahu do you know if this issue is handled as a part of https://github.com/appirio-tech/connect-app/issues/3278 via Private Task? Or this part should be handled separately, as I see it has `P0` priority.

**Comment by RishiRajSahu** [comment]
@maxceem yep !

**Comment by RishiRajSahu** [comment]
Done as part of #3278
