### ISSUE TITLE
Error: An apikey is required to initialize the Filestack client

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3296]
After removing default value for `FILE_PICKER_API_KEY` in the commit https://github.com/appirio-tech/connect-app/commit/3238c4354038aea26aa65626b8c3263ec1ffe7e9 we cannot run the Connect App locally without setting the environment variable `FILE_PICKER_API_KEY_DEV` manually. There is an error in browser console, and Connect App doesn't start:

![image](https://user-images.githubusercontent.com/146016/64592711-43b53080-d3b5-11e9-8199-40aa99305367.png)

We should either update Connect App README to guide developers to set this env variable. Or set the default value in config for local development purposes.

IMHO it's better to keep it defined in the config to keep the local setup easier. The same way as we do for other DEV env variables https://github.com/appirio-tech/connect-app/blob/feature/workstreams/config/constants/dev.js or in https://github.com/appirio-tech/connect-app/blob/feature/workstreams/src/config/constants.js#L786. So developers could run the Connect App using just one command.

@vikasrohit which way do you prefer?

**Comment by vikasrohit** [comment]
Does error go away if we supply any random key? I was just trying to avoid exposing the key in code. May be we can have free filepicker account and add it to the code or just give that key whenever required in a challenge? We might not need to set keys always in every challenge, until the file upload is involved.

**Comment by maxceem** [comment]
The app can be started with a random value.

> May be we can have free filepicker account and add it to the code

That would be good if we can provide at least free account if it's enough for the dev purposes.

> or just give that key whenever required in a challenge? We might not need to set keys always in every challenge, until the file upload is involved.

I would prefer to set the default value if possible to prevent any delays which could be caused by not providing valid key. As I would prefer to keep the setup as easy as possible.

Should I try to create a free account using my email? Or there is any Topcoder account which could be used for creating a free filepicker key so it would be controlled by Topcoder?

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/8ddaecee10b73bd75a96551a4ceb72fe8cd432ef

Closing this issue myself, as its quite trivial.
