### ISSUE TITLE
[$10] Show tooltips for red cues of project menu items.

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3297]
Follow up issue from the comment https://github.com/appirio-tech/connect-app/issues/3274#issuecomment-529875776

We are showing red cues with counters for project menu items:

![image](https://user-images.githubusercontent.com/146016/64607603-7cfb9980-d3d1-11e9-83b4-2863f1f10240.png)

We should show tooltips with explanation on numbers for each of them:
- Dashboard: `New comments`
- Messages: `New messages`
- Assets Library: `New files and links`

Also, on the project listing page we should show tooltip: `New comments, messages, files & links`

![image](https://user-images.githubusercontent.com/146016/65384462-971b6d00-dd2b-11e9-88bb-7899f0b06a06.png)

This issue should be handled after implementing red cue counter for `Assets Library` tab https://github.com/appirio-tech/connect-app/issues/3274.

Note, that we already have support for showing tooltips inside `NotificationBadge` component which is used to show this red counter, see https://github.com/appirio-tech/connect-app/blob/dev/src/components/NotificationBadge/NotificationBadge.jsx#L17-L28

**Comment by maxceem** [comment]
This issue should be handled after implementing red cue counter for `Assets Library` tab https://github.com/appirio-tech/connect-app/issues/3274.

**Comment by vikasrohit** [comment]
We also need to add tooltip to the red cue on the project listing page.

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by PrakashDurlabhji** [comment]
@maxceem i want to work on this

**Comment by maxceem** [comment]
Sure @PrakashDurlabhji

**Comment by PrakashDurlabhji** [comment]
@maxceem it is ready https://github.com/appirio-tech/connect-app/pull/3327

**Comment by PrakashDurlabhji** [comment]
@maxceem PR update

**Comment by RishiRajSahu** [comment]
Merged to prod. Closing.
