### ISSUE TITLE
New User Roles

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3298]
We need to introduce new user roles and corresponding member roles to the project team to allow better targeted notifications and features. New user roles are (with mapping to the corresponding member role in Connect team):

Business Development Representative => Account Manager _(Should be treated as current Account Manager role for all privileges in the application)_
Presales => Account Manager
Account Executive => Account Executive _(Should be treated as current Account Manager role for all privileges in the application)_
Program Manager => Program Manager _(Should be treated as current Manager role for all privileges in the application)_
Solution Architect => Solution Architect _(Should be treated as current Manager role for all privileges in the application)_
Project Manager => Project Manager _(Should be treated as current Manager role for all privileges in the application)_

**Comment by vikasrohit** [comment]
@maxceem I guess we need changes in both connect-app and project service for this, right?

**Comment by vikasrohit** [comment]
Yep, agreed about the need of migration scripts and I think I am good with that even for the near future and as of now we don't yet have any permissions in database (because we are not going to release the work management yet), so we are safe with that regard.
Coming back, I think we also need changes in the `tc-notifications` as well for modifying the notifications targets.

**Comment by vikasrohit** [comment]
@maxceem we need to wrap this one as it is also P0 for us for the next release (tentatively 26 Sept).

**Comment by maxceem** [comment]
@vikasrohit got it, thanks for emphasising it.

**Comment by maxceem** [comment]
1. @vikasrohit we have the next switches of user role in Topcoder Team dialog:

    ![image](https://user-images.githubusercontent.com/146016/64947087-eb7ea280-d87c-11e9-9f90-cdda74dc81e0.png)

    They already take quite a lot of space and if add two more options `Account Executive` and `Solution Architect`. This switch would take almost the whole width of the dialog. Should we replace these switches with a regular select?

     ![image](https://user-images.githubusercontent.com/146016/64947291-59c36500-d87d-11e9-94b7-8d0a6070210b.png)
     
     - Regular select also supports disabling options with a tooltip, which we use for `Copilot`.

2. I've noticed a new role `Project Manager` additionally to `Manager` role. What would be the difference between them? They sound like the same role.

**Comment by maxceem** [comment]
3. @vikasrohit is it possible to get users with new roles for testing on DEV? As I don't have access to admin UI I cannot create them myself.

**Comment by vikasrohit** [comment]
1. I think we have more than two new options for roles `Program Manager`/`Account Executive`/`Solution Architect`/`Project Manager`. And to accommodate them, we can try moving the selector in the next row so that it can take full horizontal space. For mobile devices (which I don't think we support now for this UI and I don't think we need to implement it right away), we can stack these options vertically. If that also does not solves the problem, let me know. I need to confirm if we can show the regular select instead. I am trying to keep the design as close to as it is right now, dropdowns are usually avoided in our designs.
May be we can remove `Observer` and `Manager` roles from the selector now. Only thing is that how to show the users in these roles for the old projects.

2. Yep, they are more or less same, we are keeping `Manager` role for backward compatibility. 

3. I would create roles in some time. Let me know on Slack which users you want to add user in those roles.

**Comment by maxceem** [comment]
1. > And to accommodate them, we can try moving the selector in the next row so that it can take full horizontal space.

    1. Yes, I think can do that way, though IMHO it's better to replace this UI component with something more compact, as we would repeat the same list of roles many times, while we are only interested in the current role of the user.

    2. Regarding mobile devices. While we don't put efforts for supporting them, many things still work on mobile. Stacking these options vertically IMHO would make the user list too high.

     3. > May be we can remove Observer and Manager roles from the selector now. Only thing is that how to show the users in these roles for the old projects.

       If we don't want these roles to be used anymore, we can hide them unless they are selected. So we would still show them if some users have these roles, but we wouldn't let users to choose them anymore. Also, then we should remove these options from the select below:

      ![image](https://user-images.githubusercontent.com/146016/64959709-5e4a4680-d89a-11e9-9ebb-7175e856d1af.png)

**Comment by vikasrohit** [comment]
i. Agreed. But for now, I am trying to not invest time in UI designs, if possible. Please feel free to switch to the dropdown, if you see any issue in fitting the role options in the single row.

ii. I guess vertical stacking for mobile is good even if it too high as vertical scrolling is expected in the mobile devices. This does not makes sense, if we finally use dropdown though. :)

iii. Yes, if we use dropdown, we can remove the `Manager` and `Observer` roles from the list if there is no user in the project with these roles.

**Comment by maxceem** [comment]
@vikasrohit there is a place where we send an event to the analytics with the current user role: https://github.com/appirio-tech/connect-app/blob/feature/new-roles/src/actions/loadUser.js#L58-L68

In this code we have some logic to determine what is main user role. I'm not sure how should we update this code after adding new roles because I don't know what the analytics system expects to get. Should we send the new roles to the analytics system? Or should we treat new "manger" roles as `ROLE_CONNECT_MANAGER`?
Note, that in the current logic we don't have a separate case for `Account Manager` which we probably also want to fix.

**Comment by maxceem** [comment]
@vikasrohit it looks like we have to replace the UI for choosing member role with Select as even on Desktop there is not enough space.

![image](https://user-images.githubusercontent.com/146016/65814600-8e88d200-e216-11e9-8345-30b629963310.png)

**Comment by maxceem** [comment]
3. We send different type of events depend on the role of user which joins the project: https://github.com/topcoder-platform/tc-project-service/blob/feature/new-roles/src/events/busApi.js#L125-L135

    Should we send a separate new event types for new user roles? Or should we send `BUS_API_EVENT.MEMBER_JOINED_MANAGER` for new "manager" roles? Or maybe we should send default `BUS_API_EVENT.MEMBER_JOINED` as it's done now.

4. So far in Project Service any user with Topcoder MANAGER level role can join project as Project MANAGER role https://github.com/topcoder-platform/tc-project-service/blob/feature/new-roles/src/routes/projectMemberInvites/create.js#L290-L307
    Just would like to confirm that with the introduction of new roles, this is still a desired behaviour.

**Comment by vikasrohit** [comment]
Sorry @maxceem for the delay in response. Here are my answers:

1. We just expect the more relevant role which user has. I guess we can send the complete roles array instead of picking up one of them, however, I am not sure as of now why we chose only one for the analytics. Assuming the same patterns, I would suggest to add new roles before https://github.com/appirio-tech/connect-app/blob/feature/new-roles/src/actions/loadUser.js#L62 so that we can send the more specific role to the analytics. However, it is not critical for the release and it can wait for next release, if that helps.

2. Go for the dropdown if it is quick and easy for us. Otherwise, can we move the switch to the next line to create some more room?

3.  For now use `BUS_API_EVENT.MEMBER_JOINED_MANAGER` only

4. Ideally we want the new specific role users to join as specific project role as well. So, when a `Solution Architect` clicks on `Join` button, he/she should be joined as `Solution Architect` to the project. For `BDR` and `Presales`, add them as `Account Executive` project roles when they click on the `Join` button.

**Comment by maxceem** [comment]
4. > Ideally we want the new specific role users to join as specific project role as well. So, when a Solution Architect clicks on Join button, he/she should be joined as Solution Architect to the project. For BDR and Presales, add them as Account Executive project roles when they click on the Join button.
    
    Just to keep it clear. The [code](https://github.com/topcoder-platform/tc-project-service/blob/feature/new-roles/src/routes/projectMemberInvites/create.js#L290-L307) I've mentioned above doesn't decide what would be the project role of the user who clicks `Join` button. This place only validates the possibility to invite user with such role using the next dialog:

     ![image](https://user-images.githubusercontent.com/146016/65858564-d3d50d00-e398-11e9-9732-cdfc7a63722e.png)

    So when we invite user we choose which role should the user have when he joins the project and this code validates which roles we can choose.

**Comment by vikasrohit** [comment]
Ohk. I got it wrong. However, the logic seems to be same for this case as well i.e. if possible we should allow adding of users to the new roles only if they posses those user roles and still keeping the manager role to assume any role for now but the new roles won't be able to take `Manager` or any other role then what they have as user role.
If it is tricky or time consuming, we can treat them as equivalent to the `Manger` role as we are doing at other places.

**Comment by maxceem** [comment]
> If it is tricky or time consuming, we can treat them as equivalent to the Manger role as we are doing at other places.

I think I would prefer to keep it as it is for now. Because updating this part would require more detailed testing and maybe writing additional unit tests to avoid any issues. So I guess it's better to keep it for the next release and test it for some time on DEV.

**Comment by nithyaasworld** [comment]
@vikasrohit @maxceem 

1. BDR (Business Development Representative) role is not an option in the user-role-switcher. Please confirm if this is expected or we should include BDR role too.
![image](https://user-images.githubusercontent.com/5114190/74482965-82f32a80-4edb-11ea-9ff7-f172c66e998e.png)


2. For some of the user roles,  (example: for Account Manager user and BDR user )User-Role switcher is not available. Please see screenshot below. Whereas for some other user roles like Connect Admin user, User-Role switcher option is available. Can you please tell me what user roles should have User-Role switching option and what users should not have this option? Thanks.

![image](https://user-images.githubusercontent.com/5114190/74483399-6acfdb00-4edc-11ea-954b-07c9075665de.png)

**Comment by maxceem** [comment]
> 1. BDR (Business Development Representative) role is not an option in the user-role-switcher. Please confirm if this is expected or we should include BDR role too.

This is a good question. We also don't allow to invite new users with this role:

![image](https://user-images.githubusercontent.com/146016/74619652-36c11800-5171-11ea-8480-afc465f96609.png)

@vikasrohit looks like it should be there.

**Comment by vikasrohit** [comment]
I think we got rid of this role (`Business Development Representative`) when we introduced new more roles like Account Executive. I have to see the requirement docs for confirmation. Lets leave it as is for now, will update after confirmation.

**Comment by vikasrohit** [comment]
@RishiRajSahu can you please confirm for @nithyaasworld  by looking at role matrix who all are able to switch the roles for other users?

**Comment by lakshmiathreya** [comment]
@vikasrohit - whats the update reg this Issue? cc @drasticdpk

**Comment by vikasrohit** [comment]
@maxceem I am not sure why my comment, which I posted (or at least tried 😉  ) is not reflecting here. But I think we should close this issue as it is very old issue and create a separate issue for tracking the pending item and following mock up might work:
<img width="716" alt="Screen Shot 2020-02-28 at 12 01 10 PM" src="https://user-images.githubusercontent.com/2417632/75673111-2b5d0900-5ca8-11ea-91c7-ae5d75b90742.png">

**Comment by vikasrohit** [comment]
@lakshmiathreya the original feature (new roles) was delivered long back in Oct 2019, so I think keeping this issue open for what it misses from the requirements, would give wrong statistics. We can create a new issue (saying as regression of this issue) and then include it in next release.

@nithyaasworld can you please create one (or may be more if the other issue you mentioned in your comment above are still issues) and close this one after referencing the issues?

@maxceem we can include this in next release. I think we can fit this new role in the switch bar, if we use its acronym only:
<img width="716" alt="Screen Shot 2020-02-28 at 12 01 10 PM" src="https://user-images.githubusercontent.com/2417632/75516276-1a02cb00-5a22-11ea-98e5-b7acf7458e17.png">
Also, include the role in the dropdown for new project

**Comment by vikasrohit** [comment]
Closing the issue.
