### ISSUE TITLE
P0: Intake 'Objective' Flag for Clients

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3300]
**Objective:** To better sort and delineate they purpose for why a client has created and submitted a project intake, which will help in data management and alert routing to appropriate client management stakeholders.

<p></p>

**Requirements:**

- Assume that the client has already clicked "New Project" internally inside Connect or from the website, and that the client has selected the specific solution they desire if the entry point was Connect/Connect's catalog.

- Once the client has selected their desired solution, a question should be displayed to them asking: "Why are you creating this project?"

- Client can select from one of these two options:

  - "I need work done"

  - "I am just exploring my options"

- After selecting either option, the client can proceed with completing and submitting the intake form.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2791709

**Comment by maxceem** [comment]
If we directly access the link to create a particular project type like https://connect.topcoder-dev.com/new-project/app, should we still show this question or no?

**Comment by vikasrohit** [comment]
Yes, if there is not saved project for the user in local storage. Otherwise, I think we assume that this question is already answered and saved to the local storage.

**Comment by maxceem** [comment]
> Yes, if there is not saved project for the user in local storage. Otherwise, I think we assume that this question is already answered and saved to the local storage.

Our wizard logic remember where we left the form. So if we left the form without answering the question, it would still show it. If already answered and clicked **Next** then wizard wouldn't show it. So should we treat this question as regular question? We just put it to the separate section. Or you see any specific logic (apart from showing to specific users)?

**Comment by vikasrohit** [comment]
Yes, that logic sounds what I have in my mind, so we are good with that.

> Or you see any specific logic (apart from showing to specific users)?

No other separate logic, just a regular question in a new section.

**Comment by maxceem** [comment]
It looks like for this issue we have to update the current implementation of permission check method. As currently we only can check the presence of roles. But for this issues we have to check that user `doesn't` have Topcoder roles. We have such ability in the method which is implemented in Project Service.

I'll make the minimal update to the permission method which is required for this task only.

**Comment by vikasrohit** [comment]
@maxceem can we add roles of the requesting user in the context of our expression evaluator while evaluating the `userPermissionCondition` (or may be we don't need this and can simply use already existing `condition` field) and then define the condition in the template as `userRoles hasLength 1 && userRoles contains 'Topcoder User'` for customer users and for topcoder employees + copilots we can have it as `!(userRoles hasLength 1 && userRoles contains 'Topcoder User')` OR `userRoles contains 'Connect Manager' || userRoles contains 'Connect Account Manager' ....` if we need to have selected roles only.

**Comment by maxceem** [comment]
@vikasrohit this sounds like a good idea. Advantage of the approach using `condition` is that we can combine user permission conditions with other conditions. The disadvantage is that rules would more wordy if we have to define several roles.

Though I've already implemented `userPermissionCondition` using another approach described here https://github.com/appirio-tech/connect-app/issues/3281#issuecomment-531255386.
So for the `userPermissionCondition` I don't use `evaluate` method, but only store the permission rule definition.

Would you like me to finish it the way I started? Or you prefer to use the way with `condition` as you are thinking that we may need to combine user permissions with other conditions?

**Comment by vikasrohit** [comment]
Lets finish it the way you have already started to not increase the timeline. We can decide on it after release, if it makes sense to move the `condition` approach.

**Comment by vikasrohit** [comment]
@maxceem are we done with the question for client? I know we are done with the question for topcoder employees.

**Comment by maxceem** [comment]
> @maxceem are we done with the question for client?

@vikasrohit will push today, mostly only testing left.

**Comment by maxceem** [comment]
@vikasrohit it's done via commit https://github.com/appirio-tech/connect-app/commit/1a2f044562b51cd78bd3cdf217ca9bd659b151b1

For testing you can use the next link which has intake question: https://connect.topcoder-dev.com/new-project/app_new_intake
You can use the next users to see the difference:
- `pshah_manager` - see question `Intake Purpose`
- `pshah_customer` - see question `Why are you creating this project?`

You may check form JSON by this link https://connect.topcoder-dev.com/metadata/projectTemplates/221

Note, that I've adopted general permissions methods from Project Service, so they support "allowRoles" and "denyRoles" which are necessary for this task, as per the way I've started it.
I've tested in several places where we already use this method that nothing is broken.

**Comment by vikasrohit** [comment]
Thanks @maxceem I have slightly changed the template to have a message section on top of the first section and store the result of the client objective flag at the same place where we are storing the same for topcoder employees.

It is working great as per my expectations. Let me share it with the product managers and come back with feedback.
Any thing pending from our side?

**Comment by maxceem** [comment]
> Any thing pending from our side?

No, it's fully done as per current description.

**Comment by vikasrohit** [comment]
Working as per requirements on production.
