### ISSUE TITLE
P3: Remove "System" Label in Left Sidebar

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3302]
**Objective:** In the left sidebar of the 'all projects' dashboard, remove the "System" label. It isn't necessary as the tabs speak to the functionality provided on their own.

<p></p>

**Requirements:**

- Remove "System" label from left sidebar in 'all projects' dashboard Connect.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2756370

**Comment by vikasrohit** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/d578535968c3534a89a5be22a2a1d68f3bb37f10
