### ISSUE TITLE
[$35] P3: Update Links in Connect

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3303]
**Objective:** In association with the launch of the new website, several links in the 'All Projects' dashboard of Connect require updating.

<p></p>

**Requirements:**

- Remove 'Getting Started' link that appears in top-bar and add it to the links displayed in the bottom-right of the screen. Replace the link with this one and relabel the link 'Our Process': topcoder.com/solutions/how-it-works/

- Remove the 'Help' link - Currently on the new website, there is not a FAQ section planned for the time being.

- Replace the 'About' link with: topcoder.com/company/

- Replace the 'Contact Us' link with: topcoder.com/contact-us/

- Replace the 'Privacy Policy' link with: topcoder.com/privacy-policy/

- No changes to the Terms link for now

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2749714

**Comment by vikasrohit** [comment]
@maxceem this can be included in the bug bash

**Comment by maxceem** [comment]
Yes, @vikasrohit will include it to the Bug Bash.

A couple of questions. 

1. Topcoder users see toolbar with the search field without links in top bar, so nothing to do with toolbar for such users:

    ![image](https://user-images.githubusercontent.com/146016/65227532-78219e80-dad1-11e9-9e97-539d1ad72483.png)

    Customers users see top with links:

    ![image](https://user-images.githubusercontent.com/146016/65227579-8d96c880-dad1-11e9-8ee6-05816de63a80.png)

    As we are removing links `Getting Started` and `Help` from the top bar for customers, should we also remove `My Projects` links from the top bar, as now we already have it on the left sidebar:

    ![image](https://user-images.githubusercontent.com/146016/65227633-ad2df100-dad1-11e9-8cfd-c4bd6be9e590.png)

2. We also have a `Help` link in the dropdown menu when we click user avatar in the top right corner:

    ![image](https://user-images.githubusercontent.com/146016/65227795-f3835000-dad1-11e9-9137-579118f08587.png)

    Should we also remove the `Help` link here?

**Comment by vikasrohit** [comment]
1. Yes, remove the `Getting Started` from the top bar for any user who can see it as of now and move it to the bottom right as said in original description.
Also, please go ahead with removal of `My Projects` link as well as it does not make sense to have duplicate links.
2. Yes, please.

Also, please verify, for any of links, the home page of the connect i.e. page which we show at connect.topcoder-dev.com when user is not logged in.

**Comment by maxceem** [comment]
We also should update links in the footer when we are not logged in:

![image](https://user-images.githubusercontent.com/146016/65228992-262e4800-dad4-11e9-92f5-ec6ff47afcaf.png)

3. When we are logged out there is also link `Learn more about Connect` which leads to `https://www.topcoder-dev.com/about-topcoder/connect/`, should we update it?

**Comment by maxceem** [comment]
4. We also have a footer on the `Notifications` page https://connect.topcoder-dev.com/notifications

     ![image](https://user-images.githubusercontent.com/146016/65229720-68a45480-dad5-11e9-9a00-6bca7f638c8d.png)

     Should we update links there, or just remove this footer?

**Comment by vikasrohit** [comment]
3. Leave that link as is for now

4. yes

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by manepal** [comment]
Hi, can you please assign this issue to me?

**Comment by maxceem** [comment]
Sure @manepal. Just would like to note, that as per our Bug Bash rules https://www.topcoder.com/challenges/30102919 your comment is enough, and you don't have to wait to be assigned, and you can start working as soon as you post a comment (if nobody commented before you).

**Comment by manepal** [comment]
@maxceem , on it. Thanks!

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by rashmi73** [comment]
@maxceem pls give to me

**Comment by maxceem** [comment]
Sure @rashmi73

**Comment by rashmi73** [comment]
@maxceem Working actively

**Comment by rashmi73** [comment]
@maxceem ready https://github.com/appirio-tech/connect-app/pull/3328

**Comment by rashmi73** [comment]
@maxceem PR update

**Comment by lakshmiathreya** [comment]
Verified links for 'About', 'Contact us', 'Privacy', 'Terms', 'Our Process' - as per requirement stated above. However, could not locate the current 'Getting Started' in Top bar in Prod - has it been removed already? Pls clarify @vikasrohit

**Comment by RishiRajSahu** [comment]
@lakshmiathreya yes its been removed as per the description of the issue, and instead 'Our Process' has been added in the right footer. 
Closing the issue as working fine.
