### ISSUE TITLE
P2: Update Empty Plan Message to Client

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3304]
**Objective:** Update the message the client sees in their project plan when their project has just been submitted and no delivery plan has been built yet to clarify expectations for the client.

<p></p>

**Requirement:**

- Update the default empty-state message of project plan that client sees to read: "We are reviewing your request. Within the next 24 hours, Topcoder will contact you to discuss next steps, including finalizing your sale and preparing our crowd to meet your needs. Once delivery is mobilized, your project plan will be updated to reflect your detailed delivery plan and will serve as your resource for engaging in key milestones and monitoring progress."

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2757160

**Comment by vikasrohit** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/88945bcb5a0045f1930b173c6ec67a2d41d1ea66
