### ISSUE TITLE
[Tablet] "Remove number" and "Cancel" buttons are not displayed in one line; and touching each other

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#331]
### Expected behavior
-----------------------------------------------------------------
[Tablet] "Remove number" and "Cancel" buttons must display in-line or Must have some space in-between if they are in two lines

### Actual behavior
-----------------------------------------------------------------
"Remove number" and "Cancel" buttons are not displayed in one line; and touching each other

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click on a Project name
- Click Dashboard
- Click Remove button from the Project Team list
- Check the buttons

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not valid. iPad
