### ISSUE TITLE
[$120] P3: Update Invited Registered User Workflow

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3311]
**Objective:** Update email templates sent to registered platform users when they are invited to a project to include 'Join Project' or 'Decline' buttons, which when clicked automatically manage their acceptance or decline of invitation in the platform. This will improve the efficiency of the workflow that exists today, wherein: An invited registered user receives an invitation email, they click the invitation link in the email, they are brought into Connect and see a pop-up for Join/Decline, and have to click on their choice in the platform.

<p></p>

**Requirements** - Workflow: 

[Imagining that users has already completed the steps of sending invitation/receiving invitation]

- Registered user receives project invitation email

- Registered user sees button options of 'Join Project' or 'Decline' in the email body

  - **Option A:** Registered user clicks 'Join Project.' User should be automatically joined to the project.

  - **Option B:** Registered user clicks 'Decline.' User should not be joined to the project and should not see the project listed on their 'all projects' dashboard on next login.

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2761674

**Comment by maxceem** [comment]
It looks like there are two parts in this issue to be done:
1. In the Connect App create links which users can follow to automatically accept and decline invitation. I'm thinking about creating the next links:
    ```
    // link to automatically accept invitation
    http://local.topcoder-dev.com:3000/projects/8369?invitation=accept

    // link to automatically decline invitation
    http://local.topcoder-dev.com:3000/projects/8369?invitation=decline
    ```
    
    So if user follows such a link we should show the loading indicator during we are sending request to the server to accept/decline the invitation.
     - If invitation is accepted we start loading the project (continue showing loader).
     - if invitation is declined we can redirect to the project listing page
     - if user is already a member of the project no matter which link we use, we just show the project
     - if user is not a member, but there is an error during invitation accept or decline we should show the error page (with error from the server)
    
    @RishiRajSahu @vikasrohit what do you think about security risks with such links?

2. After we implement the first part, we can update email template by adding these two links and button to accept and decline invitations.

**Comment by RishiRajSahu** [comment]
@maxceem I don't think there should be any security risk by creating such URLs to accept/decline the invitation, because as per my understanding we update the PENDING invites present for that user for a particular project, so even if those params are changed manually and there is no PENDING invite present for that project/member combination then there will be an error.

**Comment by maxceem** [comment]
Right, we only updating a PENDING invitation, otherwise there would be an error.

**Comment by maxceem** [comment]
Sum up:
Implement the first part of this task, described in https://github.com/appirio-tech/connect-app/issues/3311#issuecomment-533863882

For testing the next project can be used http://local.topcoder-dev.com:3000/projects/8370 or create a new project. See [demo video](https://monosnap.com/file/cJFLHSZIX21Z8xESSYxuots1PHtFcD) on how I use user `pshah_manger` to invite user `pshah_customer`.

**Comment by maxceem** [comment]
This issue is now open for pick up.

**Comment by romitgit** [comment]
Please assign this to me.

**Comment by maxceem** [comment]
Sure @romitgit

**Comment by maxceem** [comment]
As there is no update more than 12 hours, this issue is now open for pick up.

**Comment by suppermancool** [comment]
@maxceem pls assign this to me

**Comment by suppermancool** [comment]
@maxceem done in https://github.com/appirio-tech/connect-app/pull/3335

1. There is the lint error in current app, this error isn't made from my code.
2. I can't test this because i alway get 502 error when invite member: https://gyazo.com/4be73cebb64c60923f9cb59e3841ad24
3. After we implement the first part, we can update email template by adding these two links and button to accept and decline invitations. -> I'm not sure how to do this

**Comment by maxceem** [comment]
1. Thanks for letting me know. It's fixed now in `cf19`.

2. Yeah, we have to wait until Member Service is back for testing.

3.  > After we implement the first part, we can update email template by adding these two links and button to accept and decline invitations. -> I'm not sure how to do this

    No worries, this part would handled separately.

**Comment by RishiRajSahu** [comment]
@romitgit @maxceem any update on this ?

**Comment by maxceem** [comment]
@RishiRajSahu I've reviewed the [PR](https://github.com/appirio-tech/connect-app/pull/3335). In general it works good, thought there is a couple of things to improve.

**Comment by RishiRajSahu** [comment]
@maxceem are you pointing towards error page we see after waiting for few seconds on project details page ? I think that could be blocking thing..

**Comment by maxceem** [comment]
> @maxceem are you pointing towards error page we see after waiting for few seconds on project details page ? I think that could be blocking thing..

Yes, that one. PR has been updated after my last review. I'll check it now.

**Comment by RishiRajSahu** [comment]
@maxceem Okay, let me know if it works good now !

**Comment by maxceem** [comment]
@RishiRajSahu it works good now for all the positive situation. It only fails to handle a situation when there is some error happened during server request. But the rest works great.

**Comment by RishiRajSahu** [comment]
@maxceem Okay, I hope you meant some legit error, right ? and not a new error due to these changes.

**Comment by RishiRajSahu** [comment]
@maxceem Let's wait some more time for the #3310  to be concluded also.

**Comment by maxceem** [comment]
> @maxceem Okay, I hope you meant some legit error, right ? and not a new error due to these changes.

@RishiRajSahu Yes, not a new error. Just in case something went wrong on the server during request we should show the proper error. Usually, such error shouldn't happen it's to cover kind of an edge case.

**Comment by maxceem** [comment]
@RishiRajSahu we already implemented support of direct accept/decline links in Connect App and now we can update email templates.

There are two types of user login: normal and SSO:
https://github.com/topcoder-platform/tc-notifications/blob/dev/emails/src/partials/project-team.html#L114-L122

1. `Normal Login`. For the normal login we currently show one button `View project on Connect`:

    ![image](https://user-images.githubusercontent.com/146016/66292553-283b3800-e917-11e9-83a4-5ba5f17bc2f1.png)
    
    So we have to replace this button with two: `Join Project` (blue) and `Decline` (red). Right?
2. `SSO Login`. For the SSO login, we show `SSO Login` button instead of "View project on Connect".
     Should we also replace `SSO Login` button with two buttons? 
     As I can see we can pass the redirect URL to SSO Login, so we can also perform automatic accept/decline action: `{{@root.accountsAppURL}}/sso-login/?app=connect&retUrl={{@root.connectURL}}/projects/{{notifications.[0].projectId}}?invitation=accept`

**Comment by RishiRajSahu** [comment]
@maxceem ,
1. I think this flow is for registered users, so yes we would have to replace the existing button with two new buttons. 
2. Currently what do we show for registered/unregistered users respectively when invited to project ?

**Comment by maxceem** [comment]
> Currently what do we show for registered/unregistered users respectively when invited to project ?

Registered users without SSO get the next email:

![image](https://user-images.githubusercontent.com/146016/66447291-8cc5d680-ea80-11e9-8ab7-0b90b4f60fa6.png)

- if there is SSO, then the button title would be "SSO Login".

Unregistered users with SSO get an email like this:

![image](https://user-images.githubusercontent.com/146016/66447246-6869fa00-ea80-11e9-9c41-a766b8b94ecd.png)

- If there is no SSO, then there would be no second button for SSO.

**Comment by RishiRajSahu** [comment]
> As I can see we can pass the redirect URL to SSO Login, so we can also perform automatic accept/decline action:

**Comment by maxceem** [comment]
Sure @RishiRajSahu we can test it on DEV right?

Do you have an example account that supports SSO login on DEV?

**Comment by maxceem** [comment]
@RishiRajSahu I've tested for non-SSO user. It works good if the user is logged-in.

But if user is logged out, when I come to Connect App it redirects to the login page but it loses the query param `?invitation=accpet`, so after I login, it doesn't accept/decline automatically.
```
https://accounts.topcoder-dev.com/connect?retUrl=https:%2F%2Fconnect.topcoder-dev.com%2Fprojects%2F8369
```

So I've created a fix and pushed to DEV as a hotifx https://github.com/appirio-tech/connect-app/pull/3361

I've also created a hotfix PR for PROD which can be merged as soon as we test it on DEV https://github.com/appirio-tech/connect-app/pull/3362

**Comment by maxceem** [comment]
@RishiRajSahu I've tested both cases for non-SSO case:

1. Non-SSO Registered logged in user clicked join/decline
2. Non-SSO Registered logged out user clicked join/decline

It works good after the [PR](https://github.com/appirio-tech/connect-app/pull/3361) applied to DEV. Note, that for PROD there is a hotfix to apply https://github.com/appirio-tech/connect-app/pull/3362

How to test for SSO user? I have a project with refcode defined to `topcoder`, but if I try to login with my user using SSO I get an error:

![image](https://user-images.githubusercontent.com/146016/66889744-2a3b8000-f016-11e9-9de2-3ecfa3455ac9.png)

**Comment by RishiRajSahu** [comment]
@maxceem I would like @lakshmiathreya to test this in dev for SSO user.

**Comment by lakshmiathreya** [comment]
@RishiRajSahu - verified Logged in/Logged out scenarios for Join/Decline invitation for Registered SSO user.

**Comment by vikasrohit** [comment]
@RishiRajSahu can we close this?

**Comment by RishiRajSahu** [comment]
@vikasrohit yes, Closing.
