### ISSUE TITLE
Mark file & link notifications as read on Assets Library page

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3322]
Recently we implemented showing red cue for the number of new files/links added based on the number of notifications https://github.com/appirio-tech/connect-app/issues/3274.

Now we have to mark these notifications as read in some events.

So far we can manually mark notifications about new files/links on the dashboard page 

![image](https://user-images.githubusercontent.com/146016/65371065-80601200-dc68-11e9-9aee-0440c09adfd6.png)

Though, as now we are showing the red cue for the Assets Library menu item. For the consistency I think we also should mark notifications about files/links as read automatically, when we open Files and Links tabs on the Assets Library page.

@vikasrohit please, let me know if you would like this to be implemented.

**Comment by vikasrohit** [comment]
Yes, agreed. 

Another question, do we show the newly added link/file somewhat differently in the list of the files and links? I mean, red dot against such items might work.

**Comment by maxceem** [comment]
> Another question, do we show the newly added link/file somewhat differently in the list of the files and links?

We don't do that so far. I'll check if we can do that technically.

**Comment by vikasrohit** [comment]
@maxceem what is the pending question here?

**Comment by maxceem** [comment]
> Another question, do we show the newly added link/file somewhat differently in the list of the files and links? I mean, red dot against such items might work.

We don't show red cue against newly added links and files at the moment. At the moment we cannot do it technically.

1. **Links for the project**. Notifications about added links to projects, don't have any information regarding which link has been added, and in fact, links now are not first-class citizens so we don't have any id for them to identify them:

    ![image](https://user-images.githubusercontent.com/146016/73242333-a3cf3680-41df-11ea-8acf-acd4aa0949fe.png)

2. **Files for the project** We CAN show red cue for files, as we have `fileUrl` which we can use to identify which exactly files has been added:

    ![image](https://user-images.githubusercontent.com/146016/73242391-d1b47b00-41df-11ea-9cb2-9eab688dc469.png)

3. **Files and Links in posts** So far we have the only notification about newly added post:

    ![image](https://user-images.githubusercontent.com/146016/73242439-f4df2a80-41df-11ea-8430-c9754fe43c8e.png)

    Technically, we can identify links and files which have been added with a newly added post, though we have only one notification to mark as `read` - it's the notification about the new post. So to hide the red cue we would have to mark as `read` the notification for the post. We don't have another way of marking links and files from posts as `read`, so red cue would be visible for them until we see the post otherwise.

**Comment by maxceem** [comment]
This issue has been fixed via https://github.com/appirio-tech/connect-app/commit/6908dc7ef834a0b14067b5d8385acc32476e2429 and pushed to DEV.

It's ready for testing.

- When we open `Files` tab on the **Assets Library** page, **files** notifications are marked as `read`.
- When we open `Links` tab on the **Assets Library** page, **links** notifications are marked as `read`.
- When such notifications are marked as `read`, the number in the red cue next to **Assets Library** page got reduced.

See demo video https://monosnap.com/file/95pRT11LOhNImqvaDaIAyGl8ffD1VW

**Comment by nithyaasworld** [comment]
Works perfect! Verified in dev.

**Comment by vikasrohit** [comment]
Thanks @maxceem. I guess the remaining problem now is about showing/hiding the red cue against specific file/link right?

**Comment by maxceem** [comment]
> Thanks @maxceem. I guess the remaining problem now is about showing/hiding the red cue against specific file/link right?

Right, the initial issue is solved.

**Comment by vikasrohit** [comment]
Can we get that logged @maxceem ?

**Comment by maxceem** [comment]
@vikasrohit created a follow-up issue https://github.com/appirio-tech/connect-app/issues/3596

**Comment by drasticdpk** [comment]
Verified on pord env.
