### ISSUE TITLE
[$20]P2: Update Default Text Displayed in Customer Invites

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3329]
**Objective:** Update the descriptive text shown in the invitation field for customers to indicate that customers can only be invited via email address.

<p></p>

**Requirements:**

- Update default text to read: "Enter email address"

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2807587

**Comment by RishiRajSahu** [comment]
As per discussion with Ariel have to update the text to `Enter email address(es) or user handles`

**Comment by Marrri4ka** [comment]
Can you assign this task to me?

**Comment by RishiRajSahu** [comment]
@Marri4Ka you can only pickup issues tagged with `CF` and `Open For Pickup` tag. Anyway this issue is going to be tagged soon to be picked up.

**Comment by Marrri4ka** [comment]
ok.i I'll wait, already made changes. Can you grant access to push to my branch?
Github: marrri4ka
Thank you!

**Comment by RishiRajSahu** [comment]
this issue is open for pickup now.

**Comment by rashmi73** [comment]
@RishiRajSahu pls give me

**Comment by maxceem** [comment]
This issue is on you @rashmi73 

@Marrri4ka it's possible to claim the issue only after it's open for pick up so the @rashmi73 who was the first one gets the issue. You may check the full Bug Bash rules here https://www.topcoder.com/challenges/30102919?tab=details.

**Comment by rashmi73** [comment]
@maxceem it is ready https://github.com/appirio-tech/connect-app/pull/3333

**Comment by lakshmiathreya** [comment]
Default text now reads "Enter email address(es) or user handles". Verified on Dev.

**Comment by RishiRajSahu** [comment]
Working fine in prod.
