### ISSUE TITLE
[Tablet] Must able to click on 'Add a custom features' 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#333]
### Expected behavior
-----------------------------------------------------------------
[Tablet] Must able to click on 'Add a custom features' 

### Actual behavior
-----------------------------------------------------------------
'Add a custom features' is not displayed

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Check the 'Add a custom features' button

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not valid. iPad
