### ISSUE TITLE
Invitation of users with @ doesn't work PROD

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3347]
When I'm trying to invite a user in PROD to the customer team starting from `@` it doesn't work. Though it works on DEV.

Also, if I invite the same user on PROD without `@` it also works.

The reason for this, is that when we make a call to the member service to get user id by user handle we use the handle together with `@`:
```
https://api.topcoder.com/v3/members/_search/?fields=userId%2Chandle%2CphotoURL%2CfirstName%2ClastName%2Cdetails%2Cemail&query=handle%3A%40maxceem&limit=1
```

On PROD such requests returns nothing:

![image](https://user-images.githubusercontent.com/146016/65949809-795ab000-e46f-11e9-9259-6ab8b56b7834.png)

While if we send the same request without `@`:
```
https://api.topcoder.com/v3/members/_search/?fields=userId%2Chandle%2CphotoURL%2CfirstName%2ClastName%2Cdetails%2Cemail&query=handle%3Amaxceem&limit=1
```

it return one user as expected:

![image](https://user-images.githubusercontent.com/146016/65949911-a60ec780-e46f-11e9-86c0-bcb7a5ac2f43.png)

On DEV, though, even if we retrieve user with `@`:
```
https://api.topcoder-dev.com/v3/members/_search/?fields=userId%2Chandle%2CphotoURL%2CfirstName%2ClastName%2Cdetails%2Cemail&query=handle%3A%40maxceem&limit=1
```

we get the successful result:

![image](https://user-images.githubusercontent.com/146016/65950033-de160a80-e46f-11e9-84cb-75bbaf1d4757.png)

### Solution:
It looks like currently we have different versions of member service on PROD and on DEV. 
Though to not depend on the member service we can fix this client side, by always sending handle without `@` to the members service when searching for user id.

**Comment by maxceem** [comment]
@vikasrohit will add the fix to the post-release path https://github.com/appirio-tech/connect-app/pull/3346

**Comment by vikasrohit** [comment]
Lets hold on this @maxceem Ideally, I think we didn't want to get users invited with `@` in prefix. I would double check with product managers if they want to enable that feature again.

**Comment by vikasrohit** [comment]
Just read your solution though, solution to remove`@` seems logical to me and does not require product manager's approval, I guess.

**Comment by maxceem** [comment]
Fixed via https://github.com/appirio-tech/connect-app/commit/19090abdea54cb008e8d9de4b0c57f6763969354 and added to [[HOTFIX] [PROD] Post-release 2.4.15.1](https://github.com/appirio-tech/connect-app/pull/3346)

**Comment by vikasrohit** [comment]
Closing as it seems very old and should have been deployed.
