### ISSUE TITLE
[Tablet] 'Save Feature' button text half hidden and ON/OFF button overlap with the text

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#335]
### Expected behavior
-----------------------------------------------------------------
[Tablet] Must fix the Layout issues in 'Add a custom features' 

### Actual behavior
-----------------------------------------------------------------
'Save Feature' button text half hidden and ON/OFF button overlap with the text

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Click 'Add a custom features' button

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Not valid. iPad
