### ISSUE TITLE
Forward opt-in flag to the salesforce lead

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3355]
Right now we are not using the opt-in flag chosen by the customer during the registration for sending marketing communications. This flag needs to be forwarded as part of salesforce lead to be used by marketing team.

**Comment by RishiRajSahu** [comment]
fyi @vikasrohit

**Comment by vikasrohit** [comment]
@RishiRajSahu I have made changes for the same in leadInfo API https://github.com/appirio-tech/tc-connect2sf/pull/34. Let me know if it works for you in dev, we can push it to prod as well immediately after we see it working in dev.

**Comment by RishiRajSahu** [comment]
Accounts app changes pushed to PROD via https://github.com/appirio-tech/accounts-app/pull/320.

Verified working fine in PROD.
