### ISSUE TITLE
Form misbehaves when user changes project template by moving back via in form navigation

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3364]
I think we should reset the local storage data (both project and wizard data) when user selects a different project type from the catalog after moving back using back arrow in the wizard. OR we may show the same incomplete dialog before doing so.

Demo video of the issue: https://monosnap.com/file/d93O2fLEWwFc8jS51Ohxk1q6qleZoA (Thanks @maxceem for it)
One more demo: 
![screencast 2019-12-03 11-25-42](https://user-images.githubusercontent.com/2417632/70024484-3aa4bb80-15c0-11ea-9a2d-9b0fdcdb63e2.gif)

**Comment by maxceem** [comment]
Previously it was a "feature", so the common data between forms stays and shouldn't be refiled when the customer changes the project type. 

I think it would be easier to reset it when we change the project type. But if you prefer to show the "incomplete dialog", please, let me know.

**Comment by vikasrohit** [comment]
yes, recalled it now. However, even though if we keep the same feature of using the common values between forms, I guess, we need to remove the wizard state because I am seeing inconsistent wizard state when I change the project type by navigating back. 
I would ask the product managers for the approach to be used for clearing up the filled/stored data when user changes the project type by navigating back.

**Comment by maxceem** [comment]
> yes, recalled it now. However, even though if we keep the same feature of using the common values between forms, I guess, we need to remove the wizard state because I am seeing inconsistent wizard state when I change the project type by navigating back.

Yes, we would have to clear the wizard state anyway.

So I'll proceed with the task after we get the response from the product team.

**Comment by vikasrohit** [comment]
@maxceem can we achieve this:

1. If user navigates to a deep link of new project for template `A` while previously he/she has incomplete project with template `B`, we should keep showing the intermediate screen for confirming if he/she wants to continue with old project or create a new project.
2. If user navigates back to the template selection page by clicking the back button in the wizard (or the browser back button if that behaves correctly), we should not show that intermediate screen and we can reset the project data from the local storage as well. IMO, if keeping the project name, description  and ref code does not create problem, we can retain these fields otherwise if they cause the problem mentioned in this issue, we can skip retaining them as well.

**Comment by maxceem** [comment]
Just to confirm:
1. If we navigate not to the template `B` deep link but to `https://connect.topcoder-dev.com/new-project` without specifying a template deep link, then we should also show the confirmation screen right?
   - NOTE: this is how things work now, so as I understand we just have to keep this behavior.
2. Basically we need only implement this second part and keep the rest of the logic as it is now. I think it should be possible to keep the project name, description and ref code.

**Comment by vikasrohit** [comment]
Yes, you are correct on both places.

**Comment by maxceem** [comment]
Challenge for this issue is on
http://www.topcoder.com/challenge-details/30108441/?type=develop.

**Comment by maxceem** [comment]
@vikasrohit this is done and pushed to DEV and V5 branches.

**Comment by vikasrohit** [comment]
Working perfect for me. Thanks @maxceem

**Comment by vikasrohit** [comment]
unfortunately @maxceem I am unable to reproduce the exact original issue on production, do you remember what were the steps to reproduce the issue? I can see that form state is inconsistent on production after user changes the project type by navigating back using back button, however, earlier when I reported this issue I was seeing the similar inconsistent state on change in answer to a question as well.

**Comment by maxceem** [comment]
This could be only reproduced using 2 forms with a wizard, see demo video on PROD https://monosnap.com/file/d93O2fLEWwFc8jS51Ohxk1q6qleZoA

**Comment by vikasrohit** [comment]
Also, seeing one issue. Console logs following:

```
main.9f1278b9e6fe6ad04f49.js:174 Uncaught TypeError: Cannot read property 'scope' of undefined
    at t.value (main.9f1278b9e6fe6ad04f49.js:174)
    at l._renderValidatedComponentWithoutOwnerOrContext (main.9f1278b9e6fe6ad04f49.js:192)
    at l._renderValidatedComponent (main.9f1278b9e6fe6ad04f49.js:192)
    at l.performInitialMount (main.9f1278b9e6fe6ad04f49.js:192)
    at l.mountComponent (main.9f1278b9e6fe6ad04f49.js:192)
```

When user clicks on `Continue where I left off` after hits page refresh, after navigating back using back button and change the project type.

**Comment by maxceem** [comment]
Can reproduce this issue, checking...

**Comment by vikasrohit** [comment]
> This could be only reproduced using 2 forms with a wizard, see demo video on PROD

Yep, this portion is something which I am able to reproduce. However, I saw another symptom of the issue as well when I logged it here. That another symptom was the similar inconsistent state after I changed answer for an already answered question. I thought that is because of the same reason as well. However, not able to recall it now. Will try to recall the steps, if I am not able to do that, I would mark this issue closed as it solves the major part of the issue.

**Comment by maxceem** [comment]
> When user clicks on Continue where I left off after hits page refresh, after navigating back using back button and change the project type.

Fixed and pushed to DEV and V5. 
Already deployed.

**Comment by vikasrohit** [comment]
Working fine. Marking ready for QA.

**Comment by nithyaasworld** [comment]
@maxceem
Q1: Are we going to retain the data filled and use it to auto-fill the common fields across the project-types? (Currently, it is retaining the data and auto-filling the same fields if it is present in other project-types)

Below workflow doesn't seem good. Could you check please?

1. I started creating a project and filled up a few screens
2. Used the back button present in the wizard
3. Then again chose the same project type
4. I can see the screen where I was before but the data I filled up are missing.

video: 
[missing data.zip](https://github.com/appirio-tech/connect-app/files/3969985/missing.data.zip)

Expecting the wizard state to be reset too, in the above case.

**Comment by vikasrohit** [comment]
@maxceem are we able to reproduce it?

**Comment by maxceem** [comment]
Yes, this is a valid issue.
@vikasrohit when we re-choose the same Project Template, do you prefer us to reset data and wizard, the same way we do when choosing another template, or persist data and wizard state?

**Comment by vikasrohit** [comment]
I guess in this case, there should be ideally no effect on the data i.e. no reset and user should be seeing all the filled data as is. Can we create a new issue for this use case which would take care in next regular release.

**Comment by maxceem** [comment]
Created a follow-up issue https://github.com/appirio-tech/connect-app/issues/3472. So the current one may be closed.

**Comment by vikasrohit** [comment]
Thanks @maxceem. @nithyaasworld closing this one now as the other uses cases are working. Please feel free to reopen it, in case you feel the newly created issue does not capture all the misses from this issue.
