### ISSUE TITLE
[$40] Explicitly list notifications which we don't show

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3375]
## Background of the issue

We have many kinds of notifications that are created in TC Notifications service. Connect App retrieves them all and shows them as per [config](https://github.com/appirio-tech/connect-app/blob/v5-upgrade/src/routes/notifications/constants/notifications.js#L29).

In this config, we don't have rules for all notification types, as we ignore some notifications and don't want to show in Connect App.

For such notifications, we show warnings in browser console so we are aware that there are some notifications which we ignore in Connect App. As the list of such notifications grows, the quantity of ignored notifications become big and we get a big list of warnings:

![image](https://user-images.githubusercontent.com/146016/68641428-c38e8100-0545-11ea-9d92-37f967aefd61.png)

Now it's hard to notice in this list if there are any important notifications that could be ignored by accident. 

## Proposed solution

To make this feature helpful again, I propose to explicitly define the list of notification types that we ignore in the Connect App and don't show warnings for them. And only show warnings for notifications types that don't have config either to show them or to ignore them.

Here is the current list of ignored notifications:
```
connect.notification.project.topic.deleted
connect.notification.project.timeline.adjusted
connect.notification.project.timeline.milestone.transition.completed
connect.notification.project.timeline.milestone.transition.active
connect.notification.project.timeline.adjusted
connect.notification.project.member.invite.created
submission.notification.create
connect.notification.project.post.deleted
```

As we also now starting getting notifications from other services, we also can define the prefix for the notifications we are interested in. So we can ignore notifications which don't start from `connect.`. So that we don't have to list all the new notifications added in other services.

@vikasrohit what do you think? Is it safe to add the notifications listed above to the ignore list?

**Comment by vikasrohit** [comment]
Agreed with the solution of maintaining a list of ignored notifications for now. For long term, I think Sachin has added [some filter](https://github.com/topcoder-platform/tc-notifications/blob/dev/src/services/NotificationService.js#L187) in the list endpoint of notifications api, which they are using in community app to pull only notifications for the community app. We can use that feature to consume only notifications that we are concerned with for Connect.

**Comment by maxceem** [comment]
Sum up:
- Check all the comments above to grasp the general idea
- Update API request for the notification list. Now we send a request like this: `https://api.topcoder-dev.com/v5/notifications/list?read=false&per_page=1000` we should add an additional query param: `platform=connect`. This would remove notifications that don't start with `connect.notification` from the server response.
- After that, create a list of ignored notifications with rest of the notifications types that we don't show at the moment. It can be seen in the browser console https://monosnap.com/file/uniCRR57q24HziyFeEysYjpE7V5gDo.
  - create such list inside file `src/routes/notifications/constants/notifications.js`. Name such list as `IGNORED_NOTIFICATION_TYPES`.
- Now we should stop showing a warning in the browser console for such notifications that we added to the `IGNORED_NOTIFICATION_TYPES` list.

**Comment by vikasrohit** [comment]
@maxceem just recalled one optimization we can do related to the notifications call. Recently notifications service was upgraded to support platform [filter](https://github.com/topcoder-platform/tc-notifications/blob/dev/src/services/NotificationService.js#L196) in the list notifications call. May be it is out of scope this issue, we can start passing the `platform=connect` to the list notifications call to reduce the number of notifications in near future when community app starts generating notifications.

**Comment by maxceem** [comment]
Yep, @vikasrohit thank you for mentioning this, already added requirement for filtering notification in the sum up above. There are still many types of Connect notification that we don't show at the moment and should ignore.

**Comment by mangus-dev** [comment]
@bug-bash-helper assign

**Comment by mangus-dev** [comment]
Hi!

**Comment by mangus-dev** [comment]
Hi!

**Comment by mangus-dev** [comment]
Hi!

**Comment by mangus-dev** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3501 is ready for review

**Comment by maxceem** [comment]
@vikasrohit looks like some warnings are showed for notifications that just have some mismatches in the event type naming and shouldn't be ignored, but should be fixed instead:

![image](https://user-images.githubusercontent.com/146016/72955432-e4d9dc00-3dd6-11ea-8041-b3d1b6b84d78.png)

**Comment by vikasrohit** [comment]
Closing the issue for cleanup. Please feel free to create separate regression issues.
