### ISSUE TITLE
"Join Project" button doesn't work good with Project Service V5 approach

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3377]
When testing Connect App with new Project Service V5 I came across one more tricky moment caused by ES indexing delay.

When a user is invited to join a project and after goes to the project page, see invitation dialog and clicks `Join Project` he should immediately see the project.

Though, as ES is not updated immediately when user clicks `Join Project` the project data is reloaded, but user still is not a member of the project, as it’s not yet updated in ES.

I’m looking for some good solution here, but so far don’t see a good one.

What come to my mind:
1. Add `db` param to the project endpoint too, to force getting data from DB and come back to this later.
2. When user clicks `Join Project` we should try to retrieve again and again until we see that project has been updated and user is now a member.
3. When user clicks `Join Project` we can try to recreate client-side the data in redux store as if we get a good response from server with members. Though this way feels quite complex and prone to issues. Also, there are some tricky moments, which I’m not sure we can rely on or no.

**Comment by maxceem** [comment]
From @vikasrohit:

> I think 3 is better option for now because in general for every such situation where after operation A we are dependent on the delay in the sync for next operation after A, we should treat the response of the operation A as source of truth. I mean if operation A returned success (200 or 201) we should just use the response (if available, in this case a project_member record) to update the redux state and the rest would work appropriately. I don't see much complexity in this process, what kind of complexity and possible errors you are afraid of in this approach


Yeah, I absolutely agree with you and this was in mind as the way to go with all such situations. Though this particular one brings some tricky moments which I'd like to share.

When a user is **invited** to a project he CAN see the project in the list by `GET /projects`. But use DOESN'T have access to the project individually, so `GET /projects/{id}` returns `403`.

Now imagine we open the project details page of a project where the user is invited, the next things happen in the background:
- `GET /projects/{id}/members/invite/` - `200` - returns invite
- `GET /projects/{id}` - `403` - don't have access
This is correct, so we show a user invitation dialog, but don't show the project itself:

![image](https://user-images.githubusercontent.com/146016/68744214-0e37f800-062f-11ea-9247-2b5cd53d03a6.png)

Now user clicks `Join Project`:
- We send request to accept invite `PUT /projects/{id}/members/invite/` - `200` - and it response with updated invite with status `accepted` which is correct.
- Now we have to load the project, as before we got `403`, we send requests to `GET /projects/{id}` and we get `200`. But this is tricky.
   - Actually the project is not yet updated in ES in this moment, only in DB. But as permissions so far are being checked by using data from DB, our permission middleware let user get the project because it already can see that in DB user is already a member of the project, see [code](https://github.com/topcoder-platform/tc-project-service/blob/v5-upgrade/src/permissions/project.view.js#L17).
   - But after we check permission the project data is returned from ES which is not updated yet. And in the response project object still don't have a user as member - he is not yet on the list. And it still have the member in the invitation list with `pending` status, as invitation is also now yet updated in ES.

So we have some inconsistency here between how we check permissions and what data we return. In this particular case, this behavior can let us solve this issues the next way:
- after we accept invite and get project from the server we should update its data by removing invitation from the list and add the current user to the member list manually.

My concern here is: do we want to keep this inconsistency in how we check permissions using DB and retrieve data using ES in Project Service?
If, eventually, we want to switch permissions check to ES, then after accepting an invitation we cannot load project details because ES still thinks the user is not a member yet, thous should not be able to load the project.

**Comment by vikasrohit** [comment]
Hmm, tricky indeed. For now go with `after we accept invite and get project from the server we should update its data by removing invitation from the list and add the current user to the member list manually.`  and lets start a github issue where we list all issues because of fetching the data from ES and data being not available immediately. We will have separate discussion to resolve such issues.

**Comment by maxceem** [comment]
@vikasrohit I've done the fix for this client-side as discussed above, though there is one issue raise up.

To fix I have to manually create a `member` records for the project using `invite` record. Though invite record doesn't have all the fields we need in `member` record. While most of the fields are not critical, one is critical: `member.id`. We don't know it from the `invite`. But we need it client-side.

![image](https://user-images.githubusercontent.com/146016/68917838-ea97bd80-07a6-11ea-9feb-dcea60f6cbc1.png)

If we don't add it, then when if we try to `leave` the project we would get an error, because of request for leaving the project using `member.id`:
```
DELETE http://localhost:8001/v5/projects/11/members/undefined/

// we should use "member.id" in this request which we don't know
```

What I can suggest in this situation is to return `member` object inside accepted invite, like this:
```js
{
  "id": 18,
  "projectId": 11,
  "userId": 40152922,
  "email": null,
  "role": "customer",
  "status": "accepted",
  "createdAt": "2019-11-15T04:49:44.819Z",
  "updatedAt": "2019-11-15T04:50:05.730Z",
  "deletedAt": null,
  "createdBy": 40152856,
  "updatedBy": 40152856,
  "deletedBy": null,
  "member": {
    "createdAt": "2019-11-15T04:50:05.750Z",
    "deletedAt": null,
    "role": "customer",
    "updatedBy": 40152922,
    "createdBy": 40152922,
    "isPrimary": false,
    "id": 29,
    "projectId": 11,
    "userId": 40152922,
    "deletedBy": null,
    "updatedAt": "2019-11-15T04:50:05.750Z"
  }
}
```

This way we don't have to try recreating a `member` object manually from `invite` we can know the real object so on the long run this approach would be more consistent.

We already "recreating" a member object to for [another task](https://github.com/appirio-tech/connect-app/issues/3310) make buttons for "Join project"/"Decline" to work on the project listing page which also comes from ES , see [implementaion details](https://github.com/appirio-tech/connect-app/pull/3356#pullrequestreview-299171352). In that place it's enough for us, because on the project listing page we don't have the functionality to `leave` the project. But if eventually, we would like to add it, we would come across with the same issue, that our "manually created" member object doesn't have complete data, in particular, `member.id`.

So the current approach is prone to issues in the long run.

Returning `member` inside `invite` definitely fits `CQRS` pattern, but I'm not sure if it fits our `REST` architecture implementation.

**Comment by vikasrohit** [comment]
Can we do a search query (from client side) to member api to get the details of such users?

**Comment by maxceem** [comment]
> Can we do a search query (from client side) to member api to get the details of such users?

I would like to note, that we need the `id` of member record inside the `project` from `Project Service`, not the `id` of the member inside the `Member Service`. But if we use project members endpoint `{{api-url}}/projects/{{projectId}}/members` this endpoint also gets data from ES, so we would get the same response as when we call `{{api-url}}/projects/{{projectId}}` and there would be no new member yet.

**Comment by vikasrohit** [comment]
Got it @maxceem. Another idea is to recreate the member object with whatever details we have so that at least user can enter the page and let us update the member after successful load of the details page in this particular use case. I mean we can call an additional api (`{{api-url}}/projects/{{projectId}}/members`) after user has been successfully landed into the project because it would definitely give ES some time to refresh itself. And may be we can have a periodic call (like we have for notifications and in future we might use web sockets for it) to this API to get the latest members of the project. Now, we have couple of options in this polling:
1. Just do this polling when there exists at least one member in the redux state where we don't have `member.id`. This would eliminate unnecessary polling to the API.
2. Another is to keep this polling always just like notifications call, which would enable us to let user know about user addition/removal from the team without refreshing the page. It would give user nice experience of connected application.

For now I am inclined towards 1 because 2 would increase the polling and polling is not a good solution from future perspective.

**Comment by maxceem** [comment]
Sure, so I will give it a try with the first approach.

**Comment by maxceem** [comment]
It's already implemented the way with adding an artificial delay and showing the loader indicator.

It's ONLY in TEST env. As it's only for V5.

**Comment by vikasrohit** [comment]
Closing. fyi @lakshmiathreya
