### ISSUE TITLE
Update Registration Success Page Content

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3378]
Registration
Update Display & Language
---------------------------
Hi *name*,

Welcome to Connect! Your account was created successfully.

**What is Connect?**
Connect is Topcoder’s application where clients start new projects, oversee progress and collaborate with delivery teams.

**What do you want to do next in Connect?**

- [Join the projects](https://connect.topcoder.com) I’ve been invited to
- [Start a new project](https://connect.topcoder.com/new-project/) myself

---------------------------

*(1) hyperlink to dashboard
*(2) hyperlink to catalog

**Comment by RishiRajSahu** [comment]
Its done and pushed to dev. @lakshmiathreya

**Comment by nithyaasworld** [comment]
@RishiRajSahu 

It displays the username and not the name. Everything else is okay.

Is this okay?

![image](https://user-images.githubusercontent.com/5114190/70924993-83dd1c80-2050-11ea-94c7-dce952aec9b7.png)

**Comment by RishiRajSahu** [comment]
@nithyaasworld yes that's Okay.
