### ISSUE TITLE
Project has been Submitted Screen - Update Language

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3379]
Update existing text to :

Congratulations!
YOUR PROJECT HAS BEEN SUBMITTED
A member of our team will be reaching out to you shortly to finalize the scope and build your project plan.

Use the link below to share your project with members of your team. You can also access all your Topcoder projects in one place from your Connect project dashboard.

[Project Link] 

[ Copy Link ]     [ Go to project dashboard ]

**Comment by RishiRajSahu** [comment]
Its done and pushed to prod. @lakshmiathreya

**Comment by nithyaasworld** [comment]
Verified in Dev environment.

Verification screenshot:
![image](https://user-images.githubusercontent.com/5114190/70926413-167ebb00-2053-11ea-97f1-c4b00667bbf7.png)

**Comment by nithyaasworld** [comment]
Verified in Production: 

![image](https://user-images.githubusercontent.com/5114190/71054190-111a9100-2177-11ea-973f-4a3675e41e3e.png)
