### ISSUE TITLE
Long Description for 'Custom Features' must display fully

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#338]
### Expected behavior
-----------------------------------------------------------------
Long Description for 'Custom Features' must display fully

### Actual behavior
-----------------------------------------------------------------
Long Description for 'Custom Features' is not displayed fully

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Click 'Add a custom features' button
- Enter Long Description for 'Custom Features' Description
- Click Save Feature

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_16-38-26](https://cloud.githubusercontent.com/assets/4592712/18951506/2ecd466e-8663-11e6-89c6-82b351f05eb3.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by sdgun** [comment]
In IE11 page can't scroll down to see the rest of the description

**Comment by sdgun** [comment]
In Chrome; The description text is span to the right of the screen.

![2016-10-01_22-51-10](https://cloud.githubusercontent.com/assets/4592712/19015825/94f2bf56-8829-11e6-93fa-89fae0bd6bd0.png)

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
Partially fixed; good to release for beta
![screen shot 2016-10-12 at 9 28 25 am](https://cloud.githubusercontent.com/assets/8484061/19318610/448740cc-905e-11e6-871e-4efd19f8f195.png)
