### ISSUE TITLE
Allow admins to manage the Customer team as well

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3382]
As a regression issue, we found that after last release, application stopped allowing the admins to manage the customer team without joining the project. We should rectify it and allow the admins to manage both teams without joining the project.

fyi @maxceem @RishiRajSahu

**Comment by RishiRajSahu** [comment]
I think we saw this behaviour even for members as well with admin role -  https://github.com/appirio-tech/connect-app/issues/3354

**Comment by vikasrohit** [comment]
@RishiRajSahu are you doing any changes for this? If not, we can assign it to @maxceem if he has bandwidth.

**Comment by RishiRajSahu** [comment]
@vikasrohit @maxceem done via https://github.com/appirio-tech/connect-app/commit/86ee17c46a5695d2bb8e35a3a1bff0672124cf09
