### ISSUE TITLE
Copilot Manager 'approve' & 'decline' of Copilot Invite pops up 'Join Project' dialog

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3386]
### Expected behavior
Copilot Manager clicking on 'approve' or 'decline' should add/not add the Copilot to the team respectively.

### Actual behavior
Clicking on 'approve' and 'decline' pops up 'Join Project' dialog. 

### Steps to reproduce the problem
- Invited Copilot 'lakshmiacopilot' to Project La Smoke Test on Dev Environment.
- Copilot manager 'lakshmiacopmgr' received email notification to Manage Project.
- On clicking Manage Project, it led to the Copilot addition 'approve'/'decline' Dialog.
- Clicking either of them popped up 'Join Project' dialog.
<img width="1240" alt="Screenshot 2019-11-28 at 4 46 43 PM" src="https://user-images.githubusercontent.com/51733042/69804477-abd12100-1204-11ea-8659-202f36cc81f9.png">
<img width="1427" alt="Screenshot 2019-11-28 at 5 19 31 PM" src="https://user-images.githubusercontent.com/51733042/69804478-abd12100-1204-11ea-8c71-9361c4ae7d41.png">
<img width="1511" alt="Screenshot 2019-11-28 at 5 21 11 PM" src="https://user-images.githubusercontent.com/51733042/69804479-ac69b780-1204-11ea-8866-8a0371ad7b48.png">

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld

**Comment by lakshmiathreya** [comment]
The Invite flow seems to be good on connect-test01 and Prod. However, in Prod the notification email is missing.

cc @nithyaasworld @RishiRajSahu @maxceem

**Comment by vikasrohit** [comment]
@lakshmiathreya which notification email you are concerned about? To copilot or copilot manager?

**Comment by lakshmiathreya** [comment]
@vikasrohit it was to copilot manager. I changed the notification setting for the Copilot manager in Prod to Immediate from Daily. Now the Invite flow works fine in Prod too - include Notification for approval being sent to Copilot Manager. Thanks for pointing that out @RishiRajSahu. cc @nithyaasworld
