### ISSUE TITLE
Masking email to be shown under Team management container

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3388]
We need to mask the email of all other user, except for admin, to be shown under tooltip and Team dialog. for example - john.doe@gmail.com is to be masked as `****.doe@gmai*****`

fyi @maxceem

**Comment by RishiRajSahu** [comment]
@maxceem could we add this support in the same endpoint where we are augmenting data of user to add TZ and WH ?

**Comment by maxceem** [comment]
Sure, do you want to have it masked with asterisks, or just exclude from the output?
I have some concerns regarding returning it with asterisks, as client-side we may want to determine if the email is returned or no for some actions in the future, so not having email for non-admin user would be more clear way in such case.

**Comment by maxceem** [comment]
@RishiRajSahu I think I've got where I was confused. We have 2 situations when we are showing emails:
1. When we invite users by emails, we know the only email of invited person and we are showing it in the invitation list: 

    ![image](https://user-images.githubusercontent.com/146016/70021527-fcad9480-15cb-11ea-84f6-f651214cc7ae.png)

    - Currently, in such case, we are showing this email to `ALL USERS`. So as I understand, instead, we should mask it with asterisks for `NON-ADMIN` users. And shit should be done **server-side**.

     > @maxceem could we add this support in the same endpoint where we are augmenting data of user to add TZ and WH ?

     As we are also returning invites with email via project endpoints: `GET /projects` and `GET /projects/{id}` we should also mask invite emails in these endpoints too. And also, we have to maks them in endpoint `GET /projects/{id}/members/invites`.

2. Another case when we are showing emails is only for `ADMIN` users we add user emails for all users not only invited in the tooltips, like this:

   ![image](https://user-images.githubusercontent.com/146016/70021827-f835ab80-15cc-11ea-90a4-d7ce8cec8092.png)

   - We only show these emails to `ADMIN` users, and we don't show them for other users even with asterisks. So as I understand this feature should stay as it is, and current task is not abou this case.

**Comment by RishiRajSahu** [comment]
@maxceem yep current task is not about this case as it showing for Admins only so we are safe there.

**Comment by maxceem** [comment]
@RishiRajSahu should we mask only the first 4 and last 4 letters of emails as in the example you've provided? I also found the next algorithm https://stackoverflow.com/a/45944844 which masks the emails the next way:

![image](https://user-images.githubusercontent.com/146016/70031090-7c942880-15e5-11ea-8b9b-f6944850c06a.png)

**Comment by maxceem** [comment]
@RishiRajSahu I've just realized about one drawback we would have after masking emails server-side. We currently check client-side if we already invited user by email or no:

![image](https://user-images.githubusercontent.com/146016/70031398-22e02e00-15e6-11ea-99ee-67a37f45780f.png)

So this client-side validation wouldn't work anymore. We still have the server-side validation though.

**Comment by vikasrohit** [comment]
> should we mask only the first 4 and last 4 letters of emails as in the example you've provided? I also found the next algorithm https://stackoverflow.com/a/45944844 which masks the emails the next way:

@maxceem that logic is okay, however, please create our own code instead of using that same piece to avoid copyright issues.

> So this client-side validation wouldn't work anymore. We still have the server-side validation though.

We are good then.

**Comment by maxceem** [comment]
> I got an idea to solve this validation at front end as well. We might send the md5 of the actual email in the response when we are masking the email and update the validation logic to use that md5 instead of actual email.

Yeah, we can do that if you think we would like to keep client-side validation anyway. As it would somehow make the logic more complex.

1. We would have to populate `md5` hashes server-side on the fly, as we would get data from the ES or DB and we don't keep the `md5` there.
2. Also, update the client-side validation logic.

**Comment by maxceem** [comment]
> @maxceem that logic is okay, however, please create our own code instead of using that same piece to avoid copyright issues.

That code is written in PHP, so I guess there is no way to copy/paste it and have to be reimplemented in JS anyway.

**Comment by maxceem** [comment]
The challenge for masking emails is on http://www.topcoder.com/challenges/30108867

The part regarding using `md5` hash for validation would be implemented separately.

**Comment by vikasrohit** [comment]
We can handle the client side validation later as well, I  mean it is not urgent for us to include it in our next release.

**Comment by maxceem** [comment]
Emails is masked good, and server-side validation works also good, while client-side validation is skipped:

![image](https://user-images.githubusercontent.com/146016/70299861-04ba3e00-1831-11ea-827e-cfb4331b15e0.png)

So this issue is ready for testing. While I've created another issue to re-implement client-side validation https://github.com/appirio-tech/connect-app/issues/3392

**Comment by codejamtc** [comment]
Project: https://connect.topcoder-dev.com/projects/8943

https://www.screencast.com/t/IBd8mQBCoIC

topcoderconnect+Manager=Invited users `test@gmail.com`, `test2@gmail.com`, `test3@gmail.com`, `test4@gmail.com`

AccountManager = Email masked
CopilotManager = Email masked
Customer = Email masked
BDR = Email masked
Copilot = {Currently there is an error while approving Copilot, I will test this role later when it is fixed}

**Comment by maxceem** [comment]
@codejamtc 

>Copilot = {Currently there is an error while approving Copilot, I will test this role later when it is fixed} https://www.screencast.com/t/d5MPEfaF

fixed

> Manager = Email masked {Issue} Refer #3722 - email is shown as masked like ab@gl.com for all the users except: - Topcoder Admins

I'm not sure what kind of issue is there. Could you please, elaborate. Note, that the user WHO creates invite also can see email normally.

**Comment by coderhacker** [comment]
I have tested this with customer credentials but not working on prod, so it failed for customer users. need to verify for other users as well. (Admin, connect manager, manager, account manager) @codejamtc @lakshmiathreya 

[3388-prod-fail.zip](https://github.com/appirio-tech/connect-app/files/4421159/3388-prod-fail.zip)

**Comment by maxceem** [comment]
@coderhacker user who created invite still can see email without masking, because user who created invite by email already knows the email.

To verify this, please invite a user by email by one customer user, and after open the same project by another customer user, the email address should be displayed masked.

**Comment by coderhacker** [comment]
@maxceem thanks for the clarification.  yes,
[3388-prod-pass.zip](https://github.com/appirio-tech/connect-app/files/4421369/3388-prod-pass.zip)
 this working fine with the customer on prod.
