### ISSUE TITLE
Long Feature Name for 'Custom Features' is not displayed fully

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#339]
### Expected behavior
-----------------------------------------------------------------
Long Feature Name for 'Custom Features' must display fully

### Actual behavior
-----------------------------------------------------------------
Long Feature Name for 'Custom Features' is not displayed fully

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Click 'Add a custom features' button
- Enter Long Name as 'Feature Name'
- eg: Target Browsers - Chrome 50-53 on Mac & Windows Target Browsers - Chrome 50-53 on rget Browsers - Chrome 50-53 on sdsdsdssd
- Click Save Feature

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_16-43-57](https://cloud.githubusercontent.com/assets/4592712/18951677/048b845a-8664-11e6-9d17-1a9615a126a1.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.
