### ISSUE TITLE
During switching role under Topcoder Team dialog doesn't show any processing or success message

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3391]
### Expected behavior
During switching role the processing should be shown and success message after switched

### Actual behavior
No pointing change during role switching

### Steps to reproduce the problem
- Open any project you part of.
- Open Topcoder team dialog by clicking on manage.
- Trying switching to any eligible role.

#### Environment
- OS:All
- Browser (w/version):All
- User role (client, copilot or manager):All
- Account used: All

**Comment by RishiRajSahu** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
@RishiRajSahu would you like to show a loading indicator like this, when we are changing the member role?

![image](https://user-images.githubusercontent.com/146016/70301104-69c36300-1834-11ea-943d-c05127669336.png)

Also, we should show a black alert in the bottom left corner at the end of the operation: `Project member updated` (this is a general message to follow the format of other messages we have).

**Comment by vikasrohit** [comment]
Looks good to me for now.

**Comment by maxceem** [comment]
It's done and already pushed to DEV and TEST end.

**Comment by nithyaasworld** [comment]
After changing the user role, the user's name and user's Timezone info are gone.

Please find the video here: 
[role changing issue.zip](https://github.com/appirio-tech/connect-app/files/3969307/role.changing.issue.zip)

**Comment by maxceem** [comment]
This is fixed in DEV and TEST env via https://github.com/appirio-tech/connect-app/commit/5710ff4515ee122cff2263b89d15db23f5eb7299.

**Comment by maxceem** [comment]
This is fixed via https://github.com/appirio-tech/connect-app/commit/5710ff4515ee122cff2263b89d15db23f5eb7299 and ready for testing on TEST and DEV env.

**Comment by nithyaasworld** [comment]
Verified in Dev. Verification video.

[loading indicator verification.zip](https://github.com/appirio-tech/connect-app/files/3978115/loading.indicator.verification.zip)

**Comment by RishiRajSahu** [comment]
Working fine in prod.
