### ISSUE TITLE
Prod Environment: Not able to edit My Profile being a Copilot

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3396]
1. Go to connect.topcoder.com
2. Login as Copilot user (I logged in with my id: nithyaasworld)
3. Go to My Profile
4. Edit your name and check

Actual:
Issue1: Save Settings button is not enabled for the user to save the options
Issue2: Not able to edit Company Name and Phone Number as they are disabled.

Expected:
1. Save Settings button should get enabled if there is any change is done
2. User should be able to edit Company Name and Phone Number

![image](https://user-images.githubusercontent.com/5114190/70416936-27916000-1a86-11ea-8c1c-4a253ec2c5e5.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by maxceem** [comment]
I guess this issue happens as initially, we didn't have these fields mandatory, so users were created without them. On the other hand, we don't let to edit them. So we end up in the situation where some users might not have them defined and still are not able to edit them, as we don't let so.

As I understand the solution should be: if these fields are not defined, then we should let to edit them. As soon as the user define them and saves, they should become non-editable, as user already has some values for them.

@vikasrohit should we do a hotfix for this? Or just add it to the regular `dev` release, as it should be done soon?

**Comment by lakshmiathreya** [comment]
Will leave this as known issue? Pls clarify @vikasrohit @maxceem @RishiRajSahu

**Comment by vikasrohit** [comment]
> I guess this issue happens as initially, we didn't have these fields mandatory, so users were created without them. On the other hand, we don't let to edit them. So we end up in the situation where some users might not have them defined and still are not able to edit them, as we don't let so.
> 
> As I understand the solution should be: if these fields are not defined, then we should let to edit them. As soon as the user define them and saves, they should become non-editable, as user already has some values for them.
> 
> @vikasrohit should we do a hotfix for this? Or just add it to the regular `dev` release, as it should be done soon?

Yep, agreed.  I think we can plan it to be fixed as regular release.

**Comment by vikasrohit** [comment]
> Will leave this as known issue? Pls clarify @vikasrohit @maxceem @RishiRajSahu

Yes, it is known issue because of frequent requirement changes. But as suggested by @maxceem we are going to fix it with a workaround to avoid frustration for users(it should be less number of users on production who does not have such data) who has such data.

**Comment by RishiRajSahu** [comment]
@vikasrohit agree there shouldn't be more number of such users, I even thought of this fixing manually at backend, on demand, when issue raised by customer. But let's fix it as per @maxceem suggested.

**Comment by maxceem** [comment]
It's fixed by PR https://github.com/appirio-tech/connect-app/pull/3409. 

Ready to review in both DEV and TEST environments.

**Comment by nithyaasworld** [comment]
@maxceem This is still happening in Test Environment. Can you check please?

![image](https://user-images.githubusercontent.com/5114190/70848500-839a2100-1e98-11ea-9a3b-b160520ab301.png)

**Comment by maxceem** [comment]
@nithyaasworld This is another issue, which has been listed here https://github.com/appirio-tech/connect-app/issues/3397. Even though they may look similar, the reasons for them are different.

In the current issue, the problem was, that the user cannot press button **Save Settings** at all because the button is disabled. This issue has been fixed and now the user can press that button so the request is sent to the server.

The new issue which become visible now is that the server doesn't accept the data from the user. This is because such a user has wrong data in Member Service, and this is being discussed in the issue https://github.com/appirio-tech/connect-app/issues/3397

**Comment by nithyaasworld** [comment]
>As I understand the solution should be: if **these fields** are not defined, then we should let to edit them. As soon as the user define them and saves, they should become non-editable, as user already has some values for them.

@maxceem is it about the fields Business Phone and company name? If yes, we are still letting the user to edit the phone number. Please confirm if this is okay. (It seems okay to me to have the phone number editable)

![image](https://user-images.githubusercontent.com/5114190/70933649-5e590e80-2062-11ea-984f-83810c53cd0f.png)

**Comment by vikasrohit** [comment]
@RishiRajSahu @maxceem I think as per the requirements, phone should be disabled to be editable for a copilot, right?

**Comment by maxceem** [comment]
I think no, but I cannot find the issue where @RishiRajSahu pointed out the requirements for this feature.

**Comment by lakshmiathreya** [comment]
Phone number and Company name not editable. This was as per requirement right - pls clarify @RishiRajSahu

**Comment by vikasrohit** [comment]
Yes, Phone number and company are non editable for copilot if these fields has the data, otherwise it allows the copilot to update these fields for one time and then those fields would be read only.

**Comment by maxceem** [comment]
@RishiRajSahu could you please share the link with the latest requirements you've shared with me recently. I cannot find it and it feels that this requirement has been changed there or to confirm.

**Comment by nithyaasworld** [comment]
It's working as per the requirement. That is, Phone number and Company are disabled, if its available.

Marked this ticket with 'need clarification' label to track @maxceem 's [above query](https://github.com/appirio-tech/connect-app/issues/3396#issuecomment-567001277)

**Comment by vikasrohit** [comment]
@nithyaasworld you can close this. We would share the requirements with @maxceem.

**Comment by RishiRajSahu** [comment]
@maxceem @lakshmiathreya the requirements regarding rights to edit profile is here https://github.com/appirio-tech/connect-app/issues/3277

**Comment by maxceem** [comment]
Thanks, @RishiRajSahu. 

So as per recent requirements copilots should NOT be able to edit the phone while customers should be able to edit https://github.com/appirio-tech/connect-app/issues/3277

This works as required for me.

Customer:

![image](https://user-images.githubusercontent.com/146016/71393216-9229ca80-2646-11ea-8a7d-91e3bed9a6e2.png)

Copilot:

![image](https://user-images.githubusercontent.com/146016/71393230-a8378b00-2646-11ea-9de8-6b1c368fda57.png)

cc @nithyaasworld @lakshmiathreya
