### ISSUE TITLE
'FEATURE DESCRIPTION' field layout issue when we are editing 'Custom Features'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#340]
### Expected behavior
-----------------------------------------------------------------
'FEATURE DESCRIPTION' field must align with the 'FEATURE NAME' in EDIT 'Custom Features'

### Actual behavior
-----------------------------------------------------------------
'FEATURE DESCRIPTION' field layout issue when we are editing 'Custom Features'

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Click 'Add a custom features' button
- Enter Long Name as'Feature Name'
- eg: Target Browsers - Chrome 50-53 on Mac & Windows Target Browsers - Chrome 50-53 on rget Browsers - Chrome 50-53 on sdsdsdssd
- Click Save Feature
- Now OFF the slider 
- Check the 'FEATURE DESCRIPTION' field

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_16-43-46](https://cloud.githubusercontent.com/assets/4592712/18951845/db159240-8664-11e6-8c34-74a64d77ae2a.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.
