### ISSUE TITLE
Check loading the Direct project (fix or remove the call)

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3404]
We are loading the Direct project in Connect app for some reason https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/projectDashboard.js#L35.

At the moment on DEV we getting error 400:
![image](https://user-images.githubusercontent.com/146016/70519892-a3b7a080-1b77-11ea-840c-975b779e30d8.png)

For example, see project https://connect.topcoder-dev.com/projects/7442.

We should check if really still need to load the Direct project, and if no - then remove this call and all related stuff.

If we still need it, we should check what is the reason for the error and fix it.

**Comment by lakshmiathreya** [comment]
@vikasrohit @maxceem Pls let us know if this Issue is Ready for QA...

**Comment by vikasrohit** [comment]
@lakshmiathreya this issue is different from the linking of the direct project with project creation. We would debug it in later release, for now I am tagging it in 2.5.1 not 2.5.0.1

**Comment by maxceem** [comment]
Here is what information we get from the Direct project:

![image](https://user-images.githubusercontent.com/146016/71335745-2df00380-257f-11ea-9ac3-f0440b44b992.png)

It looks like we use this data in 2 methods:
- `formatOldProjectProgressProps` https://github.com/appirio-tech/connect-app/blob/master/src/helpers/projectHelper.js#L204 - no in use
- `setDuration` https://github.com/appirio-tech/connect-app/blob/master/src/helpers/projectHelper.js#L38 - in use
   1. https://github.com/appirio-tech/connect-app/blob/master/src/projects/components/projectsCard/ProjectsCardView.jsx#L40 (not really use data as called with an empty object)
   2. https://github.com/appirio-tech/connect-app/blob/master/src/projects/detail/containers/ProjectInfoContainer.js#L100 (use actual project data which is later displayed in `ProjectInfoContainer` https://github.com/appirio-tech/connect-app/blob/master/src/projects/detail/containers/ProjectInfoContainer.js#L517-L533 though I don't remember it actually displaying project duration.

**Comment by vikasrohit** [comment]
I think, overall we are not using duration from direct project. But lets leave it for now, we can take it later.

**Comment by lakshmiathreya** [comment]
@vikasrohit is this in Backlog now? In that case would like to remove the 2.5.1 milestone set for this Issue ...

**Comment by vikasrohit** [comment]
Moved to backlog

**Comment by vikasrohit** [comment]
@maxceem lets remove the direct project api calling altogether in favour of abandoning the v3 apis.

**Comment by maxceem** [comment]
@vikasrohit there is some [hidden UI](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/components/projectsCard/ProjectCardBody.jsx#L64-L68) with [respective methods](https://github.com/appirio-tech/connect-app/blob/master/src/helpers/projectHelper.js#L38-L82) to show some duration and progress information for the projects.

Should we only remove the API call with respective action while keeping the helper methods and hidden UI? Or should we remove all respective methods and hidden UI which cannot be used anymore without calling Direct API?

**Comment by vikasrohit** [comment]
Remove it completely, I don't we need data from direct to show progress anymore. We already have methods and components to  calculate and show progress based on project phases' progress.

**Comment by maxceem** [comment]
@vikasrohit it has been done via https://github.com/appirio-tech/connect-app/pull/3714 and pushed to `dev`.

I guess it cannot be tested by QA, so I've marked it as `QA Not Required`.

**Comment by vikasrohit** [comment]
@lakshmiathreya @nithyaasworld No special QA is required to validate this fix as it just removes unused code. However, one visible proof of this actually happening after the fix, can be seen in network tab of the developer tools of the browser and after the fix there should be no request made to `/v3/direct`.

**Comment by vikasrohit** [comment]
No issues seen on production after the fix, closing.
