### ISSUE TITLE
If there are multiple copilot join requests, accepting one request shows processing symbol for others too

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3406]
1. Login as Manager user and invite 2 Copilots into a project
2. Login as Copilot Manager and approve one of them and check

Actual:
Clicking approve for one-request, shows approval-processing symbol for both the requests.

[false processing.zip](https://github.com/appirio-tech/connect-app/files/3947871/false.processing.zip)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by maxceem** [comment]
It's fixed by PR #3411.

Ready to review in both DEV and TEST environments.

**Comment by nithyaasworld** [comment]
@maxceem The initial issue is fixed. But after approving, the actual names are replaced with 'Connect User'. 

This wasn't the case when I last tested this issue few days back.

![image](https://user-images.githubusercontent.com/5114190/70935061-58186180-2065-11ea-8420-d0c2d1ec14ec.png)
![image](https://user-images.githubusercontent.com/5114190/70935134-839b4c00-2065-11ea-94af-d8a7ad1e969f.png)

**Comment by maxceem** [comment]
This is now fixed and works like this: https://monosnap.com/file/7n3gwa3SEflhfanyoGZQ1trAVFrL7T.
There is now a small delay, and the first invitation is hidden and after member records is shown. This is what I can do as a quick fix for the release, removing this delay is a little bit ticky and may require quite wast refactoring and another approach.

FYI @vikasrohit 

It can be tested in TEST and DEV env.

**Comment by nithyaasworld** [comment]
It looks good to me. 

Verification video: 
[mulitple request approval by copilot manager - verification.zip](https://github.com/appirio-tech/connect-app/files/3978083/mulitple.request.approval.by.copilot.manager.-.verification.zip)

**Comment by vikasrohit** [comment]
> https://monosnap.com/file/7n3gwa3SEflhfanyoGZQ1trAVFrL7T

@maxceem I didn't understand the tricky portion here. Do you mean, hiding an invite record and then showing a member record includes unmounting of the invite component and then mounting of the member component?

**Comment by vikasrohit** [comment]
@nithyaasworld @lakshmiathreya can we close this?

**Comment by maxceem** [comment]
> @maxceem I didn't understand the tricky portion here. Do you mean, hiding an invite record and then showing a member record includes unmounting of the invite component and then mounting of the member component?

Basically, the logic here is the next:
- approve the request (send one request to the server which we wait with loader)
- after that, we are sending a another request to load updated invite list (with deleted invite)
- and also send another request to load updated member list (with an added member)

Technically it was hard to fix fast in a more elegant way, but as now we have time, we can do that if the current way looks not good enough.

**Comment by vikasrohit** [comment]
Okay. Do we really need the second step of reloading the invite list once we get 200 for the step 1?

Anyway, can you please create an issue if you think it has potential of cleaning up which can make code more maintainable or performant.

**Comment by maxceem** [comment]
I've created a new follow up issue with the possible improvements we can make https://github.com/appirio-tech/connect-app/issues/3468.
So the current issue may closed.

**Comment by vikasrohit** [comment]
Closing.
