### ISSUE TITLE
Should customer be able to edit Business Phone?

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3410]
I've noticed, that Copilots cannot edit `Bussiness phone` and `Company`:

![image](https://user-images.githubusercontent.com/146016/70602753-15ebbc00-1c30-11ea-9084-3de3a6b447d2.png)

While Customers cannot edit `Company`, but can edit `Bussiness phone`:

![image](https://user-images.githubusercontent.com/146016/70602855-4af80e80-1c30-11ea-9a1d-181bfea96414.png)

Is this expected behavior? Maybe Customer also shouldn't be able to edit `Bussiness phone`?

**Comment by RishiRajSahu** [comment]
@maxceem we made changes to profile page as per the requirements here https://github.com/appirio-tech/connect-app/issues/3277 check 5th point.

**Comment by maxceem** [comment]
Thanks for clarification @RishiRajSahu. Closing this issue as it works as per requirements.
