### ISSUE TITLE
When successfully invite user by email it's not cleared from the input

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3412]
### Expected behavior
When successfully invite a user by email it's cleared form the input.

### Actual behavior
When successfully invite a user by email it stays in the input as if we failed to invite such a user.

### Steps to reproduce the problem
- Invite any user by email (in the Customer Team), but the user should not be registered in Topcoder yet
- Observer that success alert has been shown in the bottom left corner and invitation has been added to the list. But the email still stays in the input field.

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/146016/70680876-76343980-1cd4-11ea-93f8-de66acdaaf19.png)

### User

Any non-admin user who got masked emails, for example, `pshah_manager`.

### Reason

This happens after we started masking emails in the invites. So when we get response from the server with masked email, we don't know if we should remove it from the input or no.

**Comment by RishiRajSahu** [comment]
@maxceem not reproducible, email got cleared after successful invite ?

**Comment by maxceem** [comment]
@RishiRajSahu This issue can be reproduced by any non-admin user who got masked emails, for example, `pshah_manager`. Also, probably, user shouldn't be registered in the system yet.

**Comment by RishiRajSahu** [comment]
yep just realized that and tried with my copilot user, its reproducible

**Comment by maxceem** [comment]
There are two ways to go for fixing this:
1. **Proper** Project Service has to return `emailChecksum` (md5 of email) that we can use for removing invited email from the input. This would require implementing it server-side.
2. **Incosistent**. Actually, when we invite users by email we can skip masking email in such case in Project Service as user who invited by email already know this email. Now it works like this: we invite someone by email, send it to the server, but the server returns email masked after creating the invitation. Actually, we know that email, so the server might return it as it is - not masked. The downside of such an approach is that we would have inconsistency in displaying such an invitation. As soon as we invite user by email, we would see the email unmasked, but as soon as we reload the page we would see it masked. 

@RishiRajSahu which way do you prefer?

**Comment by RishiRajSahu** [comment]
@maxceem I prefer doing it proper way.

totally separate thought, could we allow the users to see their invited user's email instead of masking them, could there be any risk with this approach? could other personB unmask Person A's invites email by just knowing the userId of personA in that approach.

**Comment by maxceem** [comment]
> totally separate thought, could we allow the users to see their invited user's email instead of masking them, could there be any risk with this approach? could other personB unmask Person A's invites email by just knowing the userId of personA in that approach.

I think we can do that. So when Project Service would mask emails it could check if the user who created each invite, and for the invite created by the current user who makes the requests such emails could be returned unmasked. I don't see security loops here and from the top of my head, this is doable.

**Comment by vikasrohit** [comment]
@maxceem just wanted to check on if we are working on this one in this release.

**Comment by maxceem** [comment]
@vikasrohit this only happens when we enable email masking, which is temporarily disabled. This would be handled together with enabling email masking again, as now we have all ready server-side to fix this.

**Comment by drasticdpk** [comment]
Same issue exist on dev env :
![image](https://user-images.githubusercontent.com/25297859/75743226-5f800a80-5d38-11ea-824a-b203a4b3a591.png)

**Comment by maxceem** [comment]
Can reproduce this issue.

@vikasrohit it happens when we invite by email already an existent user. As we no longer return email to non-admin users if we know user handle. To fix this issue in the current code we have to return the email during the creation of invite which would disappear after the page reloading.
Let me know if such a fix would be ok.

Soon, we can fix it some other way as per https://github.com/appirio-tech/connect-app/issues/3722

**Comment by vikasrohit** [comment]
@maxceem I thought we have fix for this in the today's patch release, isn't it the case?

**Comment by maxceem** [comment]
No. Initially this issue was due to masking emails. After we disabled masking it stopped being an issue. But later we stopped returning emails in create endpoint and this issue became valid again caused by a new reason.

In the latest patch we fixed other issues with email, but I wasn't aware that this issue is valid.

**Comment by vikasrohit** [comment]
@lakshmiathreya @drasticdpk moved to next release as there was some confusion about the fix. There are multiple fixes around emails.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/tc-project-service/commit/33bdb8a1463ec82171540f7c6f6465de99c7ebbe.

NOTE: now users who invited some users by "email" CAN see "email" in such cases. But if user invited another user by "handle" - still CANNOT see "email" unless a user has administrator privileges. This is as per discussion here https://github.com/appirio-tech/connect-app/issues/3722#issuecomment-593273148.

It's ready for testing on DEV.

**Comment by drasticdpk** [comment]
Verified on Dev 
1. with TC handle :
![image](https://user-images.githubusercontent.com/25297859/75851424-bb6a9200-5e11-11ea-9fe7-f0e10506ca7a.png)

2. with Email 
![image](https://user-images.githubusercontent.com/25297859/75851537-0e444980-5e12-11ea-9902-c37c6b117c18.png)

**Comment by codejamtc** [comment]
Project: https://connect.topcoder-dev.com/projects/8943/
User: `topcoderconnect+Customer`

https://www.screencast.com/t/GBDnn47G

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects/14178
CustomerUser/appirio123
Verified on prod, working as expected.

[3412-prod.zip](https://github.com/appirio-tech/connect-app/files/4421704/3412-prod.zip)
