### ISSUE TITLE
Cannot remove invitation by email after masking emails

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3413]
### Expected behavior
Should be able to remove invitation if invited by email.

### Actual behavior
Getting error from the server that invite is not found when trying to remove it.

### Steps to reproduce the problem
- Invite any user by email (in the Customer Team)
- Now click "remove" to delete just invited user.
- Observer that invite is not removed and the server returned the error `validation error: "email" must be a valid email"`

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/146016/70681051-fd81ad00-1cd4-11ea-89af-03eba9e9e72b.png)

### User

Can be reproduced with any user who has permissions to manager customer invitations, for example, Managers: `pshah_manager`.

### Reason

This happens after we started masking emails in the invites. When we remove the invite we actually UPDATE it on Project Service by marking it as "canceled". For this purpose, we use endpoint  `PUT /v4/projects/:projectId(\\d+)/members/invite` which detect the invite we want to update by `userId` or `email`. So if we send to it masked email it treats it as non-valid email.

**Comment by RishiRajSahu** [comment]
<img width="713" alt="Screen Shot 2019-12-12 at 10 02 25 AM" src="https://user-images.githubusercontent.com/11248478/70682995-a4ab1800-1cc6-11ea-865c-b98e459bb538.png">

@maxceem not even seeing remove option for copilot user

**Comment by maxceem** [comment]
@RishiRajSahu copilots don't have permissions to manage invitations for customers. Updated the issue details to use Manger user to testing.

**Comment by vikasrohit** [comment]
@maxceem are we implementing the masking in this release? Let me know if we are still blocked.

**Comment by maxceem** [comment]
@vikasrohit we've just got server-side support of all the necessary things for this feature, but we wouldn't be able to complete front-end changes for this before this release.

**Comment by codejamtc** [comment]
Project: https://connect.topcoder-dev.com/projects/8943/
User: `topcoderconnect+Customer`

https://www.screencast.com/t/TnIoJiAVId

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects/14058/
CustomerUser/appirio123

[3413-Prod.zip](https://github.com/appirio-tech/connect-app/files/4420048/3413-Prod.zip)

Verified on prod, working as expected.
