### ISSUE TITLE
'Leave Project' confirmation popup has repeated text

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3418]
1. Login as Account Manager user in Test Environment (https://connect-test01.topcoder-dev.com/
topcoderconnect+AccountManager@gmail.com )
2. Join any project
3. Then click on Leave and check the popup displayed

Actual:
Popup has repeated text. Please see screenshot below

![image](https://user-images.githubusercontent.com/5114190/70757437-919b5500-1d65-11ea-9d74-84ee5f2b8b7b.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya @maxceem

**Comment by nithyaasworld** [comment]
Also 'still' is incorrectly spelled in the popup as 'stil'

**Comment by lakshmiathreya** [comment]
cc @lakshmiathreya

**Comment by maxceem** [comment]
Fixed via https://github.com/appirio-tech/connect-app/commit/8be4d606c8fdf1d3089aff8a20f7735ba1f904d5.

Pushed and deployed to both TEST and DEV env.

![image](https://user-images.githubusercontent.com/146016/70898411-9561fc80-202f-11ea-821d-b215df4b4e0a.png)

**Comment by lakshmiathreya** [comment]
The verbiage should be "One you leave, somebody on your team has to add you back to the team for you to be able to see the project. Do you still want to leave?"

The "for you" is missed out - one of them needed to be retained.

<img width="1471" alt="Screenshot 2019-12-16 at 7 26 37 PM" src="https://user-images.githubusercontent.com/51733042/70912492-10c8ab80-203a-11ea-83dc-68c48e3da473.png">

**Comment by maxceem** [comment]
Added `for you`:

![image](https://user-images.githubusercontent.com/146016/70962113-ea991f00-20be-11ea-9e75-0f71ccdafd0e.png)

**Comment by lakshmiathreya** [comment]
Verified the corrected text.
