### ISSUE TITLE
Admin/Copilot User not able to Edit a exist project phase

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3419]
1. Login as Admin user topcoderconnect+Admin@gmail.com in the test env ( https://connect-test01.topcoder-dev.com/ )
2. For a project where this user is not a member, add a phase
3. Then click on Edit pencil icon of the added phase
4. Check

Actual:
I am not able to edit the phase. Clicking on Edit just makes the pencil icon disappear.

![image](https://user-images.githubusercontent.com/5114190/70757994-88ab8300-1d67-11ea-976d-024053c6b23f.png)

![image](https://user-images.githubusercontent.com/5114190/70758003-8fd29100-1d67-11ea-98e1-1e40b5587c90.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya @maxceem

**Comment by vikasrohit** [comment]
@maxceem it seems a valid issue and needed to addressed before the release.

**Comment by maxceem** [comment]
Fixed via https://github.com/appirio-tech/connect-app/commit/073b0a3fb4acb7e77f3656a33c80466313bedbbd.

Deployed to both TEST and DEV env.

Tested via topcoderconnect+Admin@gmail.com:

![image](https://user-images.githubusercontent.com/146016/70899783-52edef00-2032-11ea-93f7-14acf8d32a2a.png)

**Comment by lakshmiathreya** [comment]
Admin is able to Add and Delete Phases. However, Admin user is still not able to Update Phase.

**Comment by nithyaasworld** [comment]
@maxceem Being an admin user topcoderconnect+Admin@gmail.com , I am not able to edit the phase of this project https://connect-test01.topcoder-dev.com/projects/8588 

However, there is no issue if I edit the phase of a newly created project. Can you please check why? Thanks.

**Comment by lakshmiathreya** [comment]
I notice the same behavior even for Copilot user for existing projects.

**Comment by maxceem** [comment]
@nithyaasworld @lakshmiathreya I'm not sure if I found the same issues as you, but there was another issue in Webkit based browsers which caused showing: `An invalid form control with is not focusable.` in the browser console. I could reproduce it for any user.

It's now fixed and deployed to both DEV and TEST. Let me know if you still have issues with updating the phases.

**Comment by lakshmiathreya** [comment]
Verified Edits by Admin and Copilot.
