### ISSUE TITLE
'Marketplace'  Phone Image under 'Ecommerce' is wrong

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#342]
### Expected behavior
-----------------------------------------------------------------
'Marketplace'  Phone Image under 'Ecommerce' is wrong; Must display the title as 'Marketplace' in the mobile image

### Actual behavior
-----------------------------------------------------------------
'Marketplace'  Phone Image under 'Ecommerce' is wrong

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Select 'Ratings & Reviews' under 'Ecommerce' --> check the Image title
- Select 'Marketplace' under 'Ecommerce' --> check the Image title

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_17-04-58](https://cloud.githubusercontent.com/assets/4592712/18952361/f8b74c92-8666-11e6-9bfb-d0cb6d941078.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vikasrohit** [comment]
@vic-appirio I didn't found the appropriate asset in google drive.

**Comment by fnisen** [comment]
@vic-appirio same for me. Don't see a marketplace asset on Drive.

**Comment by vic-appirio** [comment]
![ecommerce](https://cloud.githubusercontent.com/assets/8484061/19658001/2221079e-99db-11e6-9362-77fa8be2394e.png)

**Comment by vikasrohit** [comment]
Thanks @vic-appirio Changes are in dev now.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Looks good. Just needed to clear cache to see it.
