### ISSUE TITLE
Delete phase is not working

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3421]
1. Login as Copilot in the Test Environment
2. Add a phase to your project and then delete it
3. Refresh the page and observe

Actual:
Phase is not getting deleted. It re-appears.

[Delete phase not working.zip](https://github.com/appirio-tech/connect-app/files/3958463/Delete.phase.not.working.zip)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya @maxceem

**Comment by vikasrohit** [comment]
@nithyaasworld is it happening every time with every user role? Just trying to make sure if it is happening in specific scenario or a generic bug.

**Comment by maxceem** [comment]
I can reproduce this issue in V5. Fixed it and deployed to TEST.
