### ISSUE TITLE
Not able to Add/Remove Phase to a Project being an Account Manager of THAT project

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3422]
1. Login as Account Manager in Test Environment
2. Go to a project where this user is part of, as an Account manager
3. Look for Add/Remove Phase option

Actual:
Add/Remove Phase option is not available for Account Manager user though he is part of that project.

Expected:
As per the Role Matrix, "Being a member of a project, every user other than customer should be able to Add/Remove phases"

![image](https://user-images.githubusercontent.com/5114190/70761129-27d57800-1d72-11ea-91a1-7495db5ea361.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya @maxceem

**Comment by vikasrohit** [comment]
Yes, that is as per requirements. Account Managers are prevented from the editing the project plan to prevent accidental updates.

**Comment by nithyaasworld** [comment]
@vikasrohit But as per the Role matrix, Being a member of a project, every user other than customer should be able to Add/Remove/Edit phases

Please confirm. Thanks.

![image](https://user-images.githubusercontent.com/5114190/71132506-aec89b80-221d-11ea-9b79-7269bcfcf72d.png)

**Comment by vikasrohit** [comment]
I am certain that we don't allow plan changes for Account Manager role, so we need to update the role matrix here. @RishiRajSahu can you please update the role matrix?

**Comment by RishiRajSahu** [comment]
@vikasrohit @nithyaasworld thanks for correction, its updated in document now. 
@nithyaasworld if looks good to you then we can close this issue.
