### ISSUE TITLE
Reconsider if copilots should be able to change project status

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3426]
Follow up from #3400

Form Vikas:
> We don't have clear understanding of what copilots are allowed to in terms of status updates. Although we haven't restricted explicitly, copilots are not able to update the project status to certain specific ones.

So we should discuss with the product team of what are the rules for copilots users, when they should be able to change project status and when should not.

**Comment by nithyaasworld** [comment]
Currently app allows copilot users to change status of the project the user is part of (as Copilot). cc: @SathyaJayabal

**Comment by RishiRajSahu** [comment]
@lakshmiathreya can we close this issue ?

**Comment by lakshmiathreya** [comment]
@RishiRajSahu yes...
