### ISSUE TITLE
[$50] [Project Service] For Account Manager, Not able to perform 'Remove' Topcoder member operation though its available

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3427]
1. Login as Account Manager in Test environment
user id: topcoderconnect+AccountManager@gmail.com
2. Go to https://connect-test01.topcoder-dev.com/projects/8572
3. Click on Manage
4.  Try to remove any of the members. Example, try to remove Copilot and check

Actual:
Account Manager is not able remove the Copilot though the user has the 'Manage' option with 'Remove' option too.

![image](https://user-images.githubusercontent.com/5114190/70831221-f9aa7380-1e17-11ea-90bd-e108785163b7.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by vikasrohit** [comment]
@nithyaasworld can we verify that if the issue not there on production as of now?

**Comment by vikasrohit** [comment]
@RishiRajSahu is account manager allowed to do team operations as per the matrix?

**Comment by RishiRajSahu** [comment]
@vikasrohit yes, Account manager shares same permissions as manager except he gets additional notification/email of new project creation.

**Comment by vikasrohit** [comment]
Okay, assuming the issue to be still there on production, moving this issue in next milestone.

**Comment by vikasrohit** [comment]
@maxceem I think we didn't start on this. Moving this to next release, let me know if you have any query for this issue to be taken care of. We should give `Account Manager` the ability to manage the team similar to other Managers.
**Fact check:** `Account Managers` are not able to manage project plan and that is as per requirements.

**Comment by maxceem** [comment]
Sum up:
- user with **Project Role** `account_manager` should be able to remove members from Topcoder Team
- this issue has to be fixed in Project Service repo https://github.com/topcoder-platform/tc-project-service branch `dev`
- user for testing is `topcoderconnect+AccountManager@gmail.com`

**Comment by gets0ul** [comment]
@bug-bash-helper assign

**Comment by gets0ul** [comment]
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/500 is ready for review

**Comment by drasticdpk** [comment]
Issue verified, here is the reference

[3427_verification.mp4.zip](https://github.com/appirio-tech/connect-app/files/4336770/3427_verification.mp4.zip)

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by lakshmiathreya** [comment]
Tested with lakshmiaAcMgr user on Prod - unable to remove member :
<img width="1260" alt="Screenshot 2020-04-02 at 3 43 34 PM" src="https://user-images.githubusercontent.com/51733042/78238510-4bc3f180-74fa-11ea-91b1-52d94b8ec691.png">

**Comment by lakshmiathreya** [comment]
'Remove' verified on Prod - working after the Ac Mgr user joined the project. Thanks for clarification @vikasrohit. Setting status to QA Pass in Prod.
