### ISSUE TITLE
Project creation Notifications are not sent

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3428]
Requirement: All Project Creation Notifications should be sent to Account Manager and ~Admin users~ Business Development Representative

Actual: Project creation notifications are not sent to Account Manager. Verified by creating projects using Account Manager's user credentials as well as Copilot user credentials.

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by maxceem** [comment]
Only Account Managers and Bussiness Development Representatives should get notifications about new projects. But user with Administrator or Connect Manager roles, shouldn't get such notifications:
![image](https://user-images.githubusercontent.com/146016/70889277-33000080-201d-11ea-8634-ea3095806d62.png)

This works as expected for me and `topcoderconnect+AccountManager@gmail.com` gets notifications about new projects in TEST env:

![image](https://user-images.githubusercontent.com/146016/70889346-5d51be00-201d-11ea-890e-cf72585c516c.png)

**Comment by vikasrohit** [comment]
@nithyaasworld can you please share the Account manager user you used to test this?

**Comment by nithyaasworld** [comment]
Thanks @maxceem @vikasrohit for checking this! 

This issue is not reproducible in Dev environment. I would like to check this in Production env and then close this.

**Comment by nithyaasworld** [comment]
Thanks @maxceem and @vikasrohit for checking!

Yeah, this is working for me too in Dev Environment.

Checked for the below users:
topcoderconnect+accountmanager@gmail.com
topcoderconnect+BDR@gmail.com  (Business Dev Representative)

However, I see lot of notification of the same type. I will raise a new bug for it.

![image](https://user-images.githubusercontent.com/5114190/71209783-70d97f00-22d2-11ea-8ca3-a5e691fc687c.png)

**Comment by nithyaasworld** [comment]
@lakshmiathreya Can you please confirm if this works in Production for Account Manager and BDR user? We can close this after your confirmation. Thanks.

**Comment by lakshmiathreya** [comment]
Verified on Prod: On new Project creation by Copilot, only Account Manager and BDR are getting notifications.

**Comment by vikasrohit** [comment]
@lakshmiathreya can we close this?
