### ISSUE TITLE
Member List UI Redesign

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3432]
Task from Rishi:
> we have a new request of adding working hours option for Connect user, so there will new optional fields on registration page where user can enter their working hours and we have to show that info in the Team section - https://marvelapp.com/4hf62ih/screen/62749170

**Comment by maxceem** [comment]
It has been implemented and pushed to DEV and TEST for testing.

**There is one known issue at the moment**:
When we click the buttons “Show All” the quantity of content in the sidebar grows and it got cut, see [demo video](https://monosnap.com/file/Ns4PVhnd3kNj9y5cvKxG5yIiTrilJt). We have to scroll up and scroll down again to see the whole content of the sidebar.

We have to fix this issue with minimal effect on the performance. The good solution is to somehow trigger stickable sidebar recalculation when we click “Show All”/”Show Less” buttons. Don’t call recalculation just every second or so on, as it most likely would lead to degradation of the performance.

The same things we have to fix when we click “Show Less” and the quantity of content shrinks which shows a big empty space in the bottom of the sidebar and it jumps when we start to scroll, see [demo video](https://monosnap.com/file/UP9t02nILbrJ3sfWg94SQ1vL09O2a4) (note, as we click “Show Less” in this demo video the second time - it works good).

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld @lakshmiathreya

**Comment by nithyaasworld** [comment]
Local time is not displayed in the same format as in the design template.

![image](https://user-images.githubusercontent.com/5114190/70935644-aed26b00-2066-11ea-9af9-5a4d3817f893.png)

**Comment by nithyaasworld** [comment]
Issue2 (major): I am not sure if this issue is related to this fix or not. Please let me know if it's not related to this fix, I will raise a new issue.

I added the users: nithyaasworld, tonyj and mess to the project https://connect-test01.topcoder-dev.com/projects/8588 as topcoder members. Then I logged into nithyaasworld from another browser window and updated the timezone.
Then again when I checked back in the first window, the newly added users nithyaasworld, tonyj and mess were missing. When I tried to add them back, I was able to add only nithyaasworld. When trying to add tonyj or mess, it says they are already part of the team, but it's not showing them.

Please check this video:
[missing members.zip](https://github.com/appirio-tech/connect-app/files/3969859/missing.members.zip)


In this video, observe that at the time 1:11, there are 3 members in the Team section of the left panel. 
And observe that at the time 1:57, there are only 2 members in the Team section.

**Comment by maxceem** [comment]
Format is fixed:

![image](https://user-images.githubusercontent.com/146016/70968935-8a61a780-20d5-11ea-80a0-fbc608502461.png)

- NOTE: for working hours instead of `EST` we should format `UTC+03:00`. There are two reasons: 
  1. It's not so clear technically how to show timezone in format `EST`
  2. I guess users don't know all the timezones in format like `EST` so IMHO, it's better to show timezone in format `UTC+03:00`

But we can change it if necessary. @RishiRajSahu please, let me know how you would prefer it to be shown.

**Comment by maxceem** [comment]
This can be tested now in DEV and TEST.

**Comment by nithyaasworld** [comment]
Just a note: Issue 2 stated in my last comment will be taken care via https://github.com/appirio-tech/connect-app/issues/3431

**Comment by nithyaasworld** [comment]
Time is not displayed if the user is just invited and not actually into the team. Can we please fix this as well? Thanks.

![image](https://user-images.githubusercontent.com/5114190/71058521-1fbc7480-2186-11ea-97df-97ac318e26a5.png)

**Comment by RishiRajSahu** [comment]
@nithyaasworld thanks for raising, btw did you tried refreshing the page before the user has accepted the invite ?

**Comment by maxceem** [comment]
@RishiRajSahu yes, backend can give us that data. We just don't show it for invites.
Should we fix it via hotfix or in regular dev?

**Comment by vikasrohit** [comment]
@maxceem We should be good with not showing timezone data for invited users for this release. We should take this as next release's regular issue as it was not clear in our original requirements in 2.5. Could you please create a new issue and tag it with 2.5.1?

**Comment by maxceem** [comment]
Created a follow up issues regarding showing this data for invites also https://github.com/appirio-tech/connect-app/issues/3452

**Comment by nithyaasworld** [comment]
Verified in Production

![image](https://user-images.githubusercontent.com/5114190/71137520-7da49700-222e-11ea-9af7-7c2d088ba7a9.png)

**Comment by nithyaasworld** [comment]
Yet to verify in production by creating a new user. 

CC: @lakshmiathreya

**Comment by lakshmiathreya** [comment]
@nithyaasworld i have verified this for new user on Prod. The display is fine. Now the Q is about showing TZ and WH for invited users. Thats being tracked separately as part of 2.5.1 #3452.

**Comment by lakshmiathreya** [comment]
shall we close this @nithyaasworld ?
