### ISSUE TITLE
Add Working Hours field on the Registration form and Profile form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3433]
Task from Rishi:
> we have a new request of adding working hours option for Connect user, so there will new optional fields on registration page where user can enter their working hours and we have to show that info in the Team section - https://marvelapp.com/4hf62ih/screen/62749170

![image](https://user-images.githubusercontent.com/146016/70847864-73883e80-1ea4-11ea-9255-7838ff84a8ff.png)

**Comment by maxceem** [comment]
Working hours for registration form is done in PRs to
- accounts-app https://github.com/appirio-tech/accounts-app/pull/328
- react-components https://github.com/appirio-tech/react-components/pull/345

Also editing working hours in Connect App is done in PR https://github.com/appirio-tech/connect-app/pull/3385

@RishiRajSahu I've just checked, but cannot see them on Account App DEV: https://accounts.topcoder-dev.com/connect/registration. Looks like cache is still not cleared for the `dev` branch.

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld

**Comment by nithyaasworld** [comment]
Working hours added during registration, is not shown in user's profile page. This is tracked here: https://github.com/appirio-tech/connect-app/issues/3437

So closing this issue.
