### ISSUE TITLE
Registered SSO User Project Invite email has Register button

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3438]
### Expected behavior
Since the SSO user is registered, the Invite email should have Join Project button.

### Actual behavior
Register button in email instead of Join Project.

### Steps to reproduce the problem
- Log in to https://connect-test01.topcoder-dev.com as Copilot.
- Invite SSO user lakshmi.athreya@wipro.com to a project that this user is not a member of. Note that this is a registered user.
- The invite email received has Register button. On clicking, the Registration page is shown. On submission of Registration page, an SSO login happens for this user, bypassing the PIN email/entry steps.

### Screenshot/screencast
Attach or link a resource.
<img width="1585" alt="Screenshot 2019-12-17 at 10 09 03 AM" src="https://user-images.githubusercontent.com/51733042/70965489-d270d200-20b5-11ea-8793-78edba29bf69.png">

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld

**Comment by vikasrohit** [comment]
@RishiRajSahu is it still happening?

**Comment by RishiRajSahu** [comment]
@lakshmiathreya is this still happening in prod ?

**Comment by lakshmiathreya** [comment]
Verified in Prod - working fine.
