### ISSUE TITLE
[Project Dashboard]Co Pilot can create project

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#344]
### Expected behavior
As  per guideline copilot should not be able to create project

### Actual behavior
Co pilot is able to create project

### Steps to reproduce the problem
Login as co-pilot
Create Project

### Screenshot/screencast
![screenshot 23](https://cloud.githubusercontent.com/assets/8684209/18958373/056d7d16-8695-11e6-9dae-211652a77bdd.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version):Google Chrome Version 53.0.2785.116 m (64-bit)
- User role :Co-Pilot
- Account used: cp-superstar

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
This is a valid use scenario. Anyone can create a project.

**Comment by fnisen** [comment]
Copilot will just be the owner in this case. They won't be able to serve as the copilot.
