### ISSUE TITLE
Some Assets missing after 2.5 upgrade

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3443]
### Expected behavior
All assets to be available after v5 upgrade.

### Actual behavior
Some assets appear to be not available after the upgrade.

### Steps to reproduce the problem
- Missing assets here:
https://connect.topcoder.com/projects/7195/assets
- Copilot reports that there were more assets earlier and now only 2 are seen.

### Screenshot/screencast
Attach or link a resource.

--
<img width="1497" alt="Screenshot 2019-12-18 at 5 56 47 AM" src="https://user-images.githubusercontent.com/51733042/71045518-37323800-215b-11ea-8415-bf2f8d2992d1.png">

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by lakshmiathreya** [comment]
cc @mtwomey @ashields @nithyaasworld @tjefts

**Comment by lakshmiathreya** [comment]
cc @ajefts

**Comment by maxceem** [comment]
Already found the root of this issue, working on the fix.

**Comment by nithyaasworld** [comment]
It looks good to me. However, I would like @lakshmiathreya to confirm as I did not see the issue earlier.

cc: @maxceem @vikasrohit

**Comment by maxceem** [comment]
The issues has been fixed: attachments wasn't added to the ES index inside the projects. So we reindexed projects with attachments.

I can see the attachments which I didn't see before in my production project.

**Comment by lakshmiathreya** [comment]
Verified assets in Prod - the missed assets now appear for the Project.
