### ISSUE TITLE
Manager part of customer team not able to access `Manage Invitations` button

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3446]
Manager who were invited to the customer team should be able to manage the invitations but currently that button is not visible.

steps to reproduce - 
1. Invite manager user to customer team
2. Login with manager user in another browser and accept the invite
3. Check customer team view - manager not able to view manage-invitations button.

**Comment by RishiRajSahu** [comment]
Potential fix https://github.com/appirio-tech/connect-app/pull/3444/commits/af18b2cf71f7dbb5d44773ab5548531f3581055a

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld

**Comment by RishiRajSahu** [comment]
@lakshmiathreya @nithyaasworld its fixed in prod, ready for QA.

**Comment by nithyaasworld** [comment]
Verified on Dev. Yet to verify on Production.

![image](https://user-images.githubusercontent.com/5114190/71077560-aafd3080-21ad-11ea-88ee-5ebb5fbf350a.png)

**Comment by lakshmiathreya** [comment]
Manager part of Customer team is able to view Manage Invitations in Prod.  
<img width="1491" alt="Screenshot 2019-12-19 at 2 35 03 PM" src="https://user-images.githubusercontent.com/51733042/71160010-c67b4080-226c-11ea-8351-db2de8d837ec.png">
