### ISSUE TITLE
[Project Dashboard]Co pilot can cancel project before active phase

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#345]
### Expected behavior

AS per guideline co pilot cannot cancel project before active phase
### Actual behavior

Co pilot can cancel project after joining any project no matter the status
### Steps to reproduce the problem

Create a project as manager
Assign owner
Set to reviewed
Join as copilot using another browser
Change project status to cancelled
### Screenshot/screencast

![screenshot 26](https://cloud.githubusercontent.com/assets/8684209/18961327/3b044bf8-869f-11e6-91a7-c6fd26a6e285.png)

![screenshot 27](https://cloud.githubusercontent.com/assets/8684209/18960071/fd2cccaa-869a-11e6-98ce-82eb6dce1cec.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/8684209/18960072/fd2ef494-869a-11e6-8f09-51257c2b41f8.png)
#### Environment
- OS: Windows 10
- Browser (w/version):Firefox Version 49
- User role :Co-pilot
- Account used: cp-superstar

**Comment by mahestro** [comment]
True, valid.

**Comment by fnisen** [comment]
Per discussion with Joey, going to keep this as allowed functionality for now.
