### ISSUE TITLE
[$30] Show Local Time and Working Hours for invited users

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3452]
Follow up from issue https://github.com/appirio-tech/connect-app/issues/3432#issuecomment-566875140

In that issue we added showing Local Time and Working Hours for **members**. As has been clarified, we should also show this data for invited users.

![image](https://user-images.githubusercontent.com/146016/71079343-0fc48500-21c6-11ea-93bc-fb2bcb6b3389.png)

**Comment by RishiRajSahu** [comment]
@maxceem didn't we ran a challenge to update data for just invited users also, without refreshing page ?

**Comment by maxceem** [comment]
@RishiRajSahu Not yet, would like to handle it as F2F or include to CF?

**Comment by maxceem** [comment]
Sum up:
- We already showing local time and working hours for the project members in the list and in the tooltip:

   ![image](https://user-images.githubusercontent.com/146016/72702665-7c002300-3b8e-11ea-98ff-84e3c6c0c05e.png)

   - see a demo project with user `maxceem` as a member http://local.topcoder-dev.com:3000/projects/8720

- We should also show local time and working hours for users if they invited, the same way in the list and in the tooltip. Now we don't show it:

   ![image](https://user-images.githubusercontent.com/146016/72702730-b5389300-3b8e-11ea-8828-8f47c537c6aa.png)

   - see a demo project with the same user `maxceem` invited http://local.topcoder-dev.com:3000/projects/8702

**Comment by Gauravseta** [comment]
@bug-bash-helper assign

**Comment by Gauravseta** [comment]
@bug-bash-helper unassign

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper assign

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3503 is ready for review

**Comment by vikasrohit** [comment]
@maxceem it does not seem to be working for me https://connect.topcoder-dev.com/projects/8515

**Comment by maxceem** [comment]
Ok, working for me also.

![image](https://user-images.githubusercontent.com/146016/73173323-14bf1180-4140-11ea-8255-834b60050f3b.png)

**Comment by lakshmiathreya** [comment]
Not working for me - @maxceem pls clarify 
<img width="1366" alt="Screenshot 2020-01-28 at 7 19 26 PM" src="https://user-images.githubusercontent.com/51733042/73269635-32a17a80-4203-11ea-9c65-f2cffceca80f.png">

**Comment by lakshmiathreya** [comment]
Seems like there is a latency - i can see TZ and Working hours for one of the invited users now:
<img width="1402" alt="Screenshot 2020-01-28 at 7 35 12 PM" src="https://user-images.githubusercontent.com/51733042/73270817-785f4280-4205-11ea-9c21-9669d4f485ea.png">

**Comment by nithyaasworld** [comment]
Yeah, I am seeing the same behaviour as Lakshmi.

![image](https://user-images.githubusercontent.com/5114190/73274554-c0816380-420b-11ea-9bba-a767b5d47386.png)
![image](https://user-images.githubusercontent.com/5114190/73274662-ef97d500-420b-11ea-9e48-4eac560aabf7.png)

**Comment by vikasrohit** [comment]
Yes, page refresh is needed get that reflected. We would enhance this in next release to get it reflected immediately after inviting the person because it would take some extra API calls to fetch the required information which might slow down the process.
@nithyaasworld Can you please log a separate enhancement issue for that?

**Comment by maxceem** [comment]
@vikasrohit I'm sorry for the late reply. We have this covered already, it would work now. The fix has been deployed to DEV.

@nithyaasworld This is ready for testing fully including the case mentioned above https://github.com/appirio-tech/connect-app/issues/3452#issuecomment-579282810

**Comment by vikasrohit** [comment]
Great!! Thanks @maxceem for the super fast turn around.

**Comment by lakshmiathreya** [comment]
@maxceem @vikasrohit pls clarify reg this Issue - it seems to conflict with #3701

**Comment by vikasrohit** [comment]
Yes, this is conflicting with #3701. We won't implement this one or rather we implemented this and then reverted it because of security/privacy concerns raised in #3701.
