### ISSUE TITLE
Correctly calculate local time for members taking into account "Daylight Saving Time"

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3458]
Follow up form the issue https://github.com/appirio-tech/connect-app/issues/3457:

![image](https://user-images.githubusercontent.com/146016/71391001-6229f980-263d-11ea-9636-2bcd87fbc585.png)

The issue is caused by the fact, that New Your supports "Daylight Saving Time", so the timezone offset vary during the year from GMT-4 to GMT-5:
![image](https://user-images.githubusercontent.com/146016/71389937-4886b300-2639-11ea-9a65-8217c5275100.png)

While we are using static list of timezones with respective time shifts:
![image](https://user-images.githubusercontent.com/146016/71389967-681ddb80-2639-11ea-8dfe-56d0d871a242.png)

So we have to use a smarter way to calculate the current time in timezones. We have to use [moment-timezone](https://www.npmjs.com/package/moment-timezone) extension for `moment` library which we already use.

The most tricky thing here is to validate somehow, that `moment-timezone` can understand our list of timezones https://github.com/appirio-tech/react-components/blob/feature/connectv2/constants/timezones.js. So we don't come up with the situation, when for some timezones in our list `moment-timezone` cannot properly calculate the local time.

**Comment by maxceem** [comment]
F2F for this issue is on http://www.topcoder.com/challenges/30111812

**Comment by maxceem** [comment]
It's done via F2F. Also, verified, that all timezones in our list are supported by the library we use to for calculating local time.

Also, now we can easily show timezone in the 3-letter format, as was initially shown in the [designs](https://marvelapp.com/4hf62ih/screen/62749170):

![image](https://user-images.githubusercontent.com/146016/71452756-97ac1f80-27c2-11ea-9dc2-6ebba9c3c765.png)

Though, I propose to keep showing timezone as UTC offset, as I guess not all the people know all the 3-letter timezones while by UTC offset everyone can read the time difference:

![image](https://user-images.githubusercontent.com/146016/71452785-db9f2480-27c2-11ea-8c07-df1baefa05fb.png)

- but on the other hand we can calculate the time difference from the actual shown local time, so let me know if you would like to show 3-letter codes instead of UTC offset.

cc @RishiRajSahu

**Comment by maxceem** [comment]
It's done in the branch https://github.com/appirio-tech/connect-app/tree/hotfix/local-timezone via PR https://github.com/appirio-tech/connect-app/pull/3473.

**Comment by RishiRajSahu** [comment]
@maxceem @vikasrohit I think this could with our next release and we can merge this to dev branch for now, do you guys agree ?

**Comment by maxceem** [comment]
Yes, I think that should be fine as I guess not so many people have entered their working hours yet, so not many users would come across with this issue.

**Comment by mahestro** [comment]
Hi guys, sorry to interrupt the flow the discussion here with a somehwat related topic.

Is the sun/moon icon meant to represent the current natural light disposition? Meaning, if it's 8:32 am in the morning, should it display a sun icon? If that's so, I think we can take advantage of this Github issue to include that fix, check: https://take.ms/2GUdr

Maybe it's a duplicate issue and I didn't see it. I can create a new issue if necessary.

Let me know.

**Comment by RishiRajSahu** [comment]
@mahestro sun/moon icon are shown as per working hours of an individual.

**Comment by maxceem** [comment]
This is done and pushed to DEV branch now.

**Comment by maxceem** [comment]
QA guidelines:
- Set `New York` timezone on your computer
- Set some project member to use `New York` timezone
- Check that Connect shows correct `local time` for this user in the member list
- Now change time on your PC to any time between April and October (summer time)
- Check that Connect shows correct `local time` for this users again
