### ISSUE TITLE
[$5] Consistent user menu items

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3459]
### Expected behavior
Show the list of menu items in the same order and probably with the same texts.

### Actual behavior
The order and texts are different for some menu items.

### Steps to reproduce the problem
- Go to the project list page and open user menu:

    ![image](https://user-images.githubusercontent.com/146016/71391462-1d06c700-263f-11ea-8c1f-2a1aa1aeea8d.png)

- Now click some "My Profile" for example. And you would see the next menu on the left:

    ![image](https://user-images.githubusercontent.com/146016/71391482-3dcf1c80-263f-11ea-981f-0fc01209649a.png)

- Observe that the order of menu items is different and texts are also different for some.

I guess it's better to keep them the same. At least the order of menu items should be the same.

**Comment by vikasrohit** [comment]
Yes, we can keep them consistent. Please follow the order of the left panel as that is the latest which we got from product managers.

**Comment by maxceem** [comment]
Should we also keep the menu items texts in sync?

- `Account & security` vs `Account and security`
- `Profile information` vs `My profile`

**Comment by vikasrohit** [comment]
- I think we can sync to `Account & security`
- I guess, here we have to keep them separate as in the left panel the profile information is already inside `My Profile`.

**Comment by maxceem** [comment]
Sum up:
- Rename to `Account and security` to `Account & security` in user menu dropdown
- Move `Account & security`  in the user menu from 2nd position to the last position as we have in the left sidebar.

**Comment by sumitdaga** [comment]
@bug-bash-helper assign

**Comment by sumitdaga** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3499 is ready for review

**Comment by nithyaasworld** [comment]
Verified in Dev.
![image](https://user-images.githubusercontent.com/5114190/73273033-55369200-4209-11ea-93d7-bf7b6ba14245.png)

**Comment by vikasrohit** [comment]
Closing the issue for cleanup. Please feel free to create separate regression issues.
