### ISSUE TITLE
[Project Dashboard]There is no confirmation when assigning owner

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#346]
### Expected behavior
When a manager assigning owner for the first time... a confirmation is required
### Actual behavior
Owner is assigned without confirmation... this cant be undone once the owner is assigned

### Steps to reproduce the problem
Create new project as manager
Assign member

### Screenshot/screencast
![screenshot 25](https://cloud.githubusercontent.com/assets/8684209/18959272/2286e678-8698-11e6-9b9c-e50e37bf860a.png)

#### Environment
- OS: Windows 10
- Browser (w/version):Google Chrome Version 53.0.2785.116 m (64-bit)
- User role :Manager
- Account used: Pat Monahan

**Comment by mahestro** [comment]
UX improvement, need approval.

@fnisen ?

**Comment by fnisen** [comment]
@mahestro let's allow b/c most of the actions in that panel have confirmations.

**Comment by vikasrohit** [comment]
Changes are in dev now.
