### ISSUE TITLE
Make links first class citizen of the data model

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3463]
As of now links which are attached to a project, are not first class citizen of the data model. In other words, they don't have a dedicated data table to store the data rather they are stored inside a field `bookmarks` of `projects` table as JSON which has limitations as follows:

1. Links are not searchable

2. Does not have easy way to query links

3. Till date we are not storing the audit fields for the links i.e. we are using the `projects` table's audit fields whenever there is some operation performed on the links which makes it difficult to identify who added or updated a particular link and when.

We have to migrate this data to a separate table so that they can be queried and audited as a normal object in the data model.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/3243055

**Comment by maxceem** [comment]
We have a requirement to [filter files and links including folders](https://github.com/appirio-tech/connect-app/issues/3464).

So far folders of links are generated by extracting links from the topics on the fly. I guess, this feature also would require us to save links to the attachment service when we create a post (extract links and save to attachment service) and also we would have to `sync`  links on posts updates.

**Comment by vikasrohit** [comment]
@maxceem we didn't merge the PR for this, right?

**Comment by maxceem** [comment]
No. It has breaking changes, so we keep it in a separate branch until we make client side changes. Currently preparing the spec for client side challenge.

**Comment by maxceem** [comment]
This was internal refactoring of the API for links. To verify this task we have to check that all the operations with links work goo:
- create link
- view link
- update link
- delete link

This can be tested on any project **Assets Library** page, for example, https://connect.topcoder-dev.com/projects/8600/assets.

**Comment by codejamtc** [comment]
https://www.screencast.com/t/iFFNtliz6

- Create link  **{Working}**
- View link  **{Working}**
- Update link  **{Working}**
- Delete link  **{Working}**

Tested using: https://connect.topcoder-dev.com/projects/9046/assets

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects?sort=lastActivityAt%20desc
CustomerUser/appirio123
Verified on prod with the above user, working as expected

[3463-prod-1.zip](https://github.com/appirio-tech/connect-app/files/4420517/3463-prod-1.zip)

**Comment by lakshmiathreya** [comment]
Verified on Prod - Links can be created/viewed/edited/searched by User and Admin - not other Manager users. @coderhacker what other scenario would you like verified in Prod via Admin/Manager users?

**Comment by coderhacker** [comment]
@lakshmiathreya just verify with Admin. I have verified with user . I can see you have verified and pass in prod
