### ISSUE TITLE
Copilots with "requested" invite can see projects in the list

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3467]
Wrapper issue for https://github.com/topcoder-platform/tc-project-service/issues/419.

fyi @lakshmiathreya we are applying it as hotfix.

**Comment by vikasrohit** [comment]
Deployed to the production.

**Comment by lakshmiathreya** [comment]
cc @nithyaasworld. Is this fixed in Dev as well?

**Comment by lakshmiathreya** [comment]
@vikasrohit is milestone 2.5.1 for this hotfix? I see other new P2s assigned to 2.5.1 milestone too?

**Comment by vikasrohit** [comment]
Following my comment https://github.com/topcoder-platform/tc-project-service/issues/419#issuecomment-568737371, updated the milestone of the issue to be 2.5.
