### ISSUE TITLE
[$80] Improve invite request accept/decline UI and code

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3468]
Follow up from https://github.com/appirio-tech/connect-app/issues/3406#issuecomment-566423188

This now works like this: https://monosnap.com/file/7n3gwa3SEflhfanyoGZQ1trAVFrL7T.
There is now a small delay, and the first invitation is hidden and after member records is shown.

Basically, the logic here is the next:
- approve the request (send one request to the server which we wait with loader)
- after that, we are sending a another request to load updated invite list (with deleted invite)
- and also send another request to load updated member list (with an added member)

So we reused existent methods to accomplish the desired feature, rather than implemented new method tailored for this particular place.

What we can improve:
- Probably we can avoid the extra request to reload all invites as we should be safe to remove invite after accept/decline request finished successfully. 
- Show the loading indicator on top of the requested invitation until the moment we are adding a newly added member.

**Comment by vikasrohit** [comment]
@maxceem I think we did not work on this, right?

**Comment by maxceem** [comment]
Didn't work.

**Comment by maxceem** [comment]
### How to reproduce:
- login with `pshah_manager` and request to invite `pshah_copilot` as `copilot` to the Topoder Team to a project https://connect.topcoder-dev.com/projects/9093

    ![image](https://user-images.githubusercontent.com/146016/79329861-3353ce00-7f21-11ea-9cb5-253be9bb6980.png)

- now login in another browser with `pshahcopmanag`, and open Topcoder Team dialog

   ![image](https://user-images.githubusercontent.com/146016/79330033-7b72f080-7f21-11ea-8130-6213165e69ad.png)

- Limit internet speed to `Slow3G` for seeing the process in details:

  ![image](https://user-images.githubusercontent.com/146016/79330152-b83ee780-7f21-11ea-950d-3cdeecaa6bb7.png)

- There could be different situations depend on the order of requests:
   1. Invitation disappears, and after some moment member appears: https://monosnap.com/file/7n3gwa3SEflhfanyoGZQ1trAVFrL7T. 
  2. Member appears first, and only after invitation disappears https://monosnap.com/file/SoHaE30ThNhFUwwVgemcqZZjuN0Gxt (see second 17):

       ![image](https://user-images.githubusercontent.com/146016/79331849-81b69c00-7f24-11ea-9979-739a24091d93.png)
      

### Expected behavior:
- we don't need to show request to reload all the invites after we `accept` or `decline` copilot invitation request, as soon as request is successfully, we can remove the invite from the list in Redux Store (at any moment we want, see the next requirement)
- we have to show the invite with a loading indicator until we load a list of members. And only remove the invite at the same moment when we loaded a new list of members, so member would appear the same time
- don't break any other existent functionality

**Comment by sumitdaga** [comment]
@bug-bash-helper assign

**Comment by sumitdaga** [comment]
@maxceem why not send `invites` and `members` data as response of `PATCH invites` api ?  
that way there will be no need to call the next two apis ?

**Comment by maxceem** [comment]
@sumitdaga the reason for this that this would be too custom logic on the server side, while we are trying to keep API general and not tailored specially for Connect App. In particular our API follow REST principles and returning member in invite endpoint doesn't fit well these principles.

So that's why we have to do find some way client side.

Note, that we have to send only one additional request to reload members. And we don't have to reload invites, as we can remove invite from redux store after accepting or declining.

**Comment by sumitdaga** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3912 is ready for review

**Comment by maxceem** [comment]
@sumitdaga here is the review, please have a look https://github.com/appirio-tech/connect-app/pull/3912#pullrequestreview-395895322

**Comment by sumitdaga** [comment]
@bug-bash-helper #3912 is ready for review

**Comment by maxceem** [comment]
@sumitdaga reviewed https://github.com/appirio-tech/connect-app/pull/3912#pullrequestreview-395907898

**Comment by sumitdaga** [comment]
@bug-bash-helper #3912 is ready for review

**Comment by maxceem** [comment]
@sumitdaga reviewed https://github.com/appirio-tech/connect-app/pull/3912#pullrequestreview-395915406

**Comment by sumitdaga** [comment]
@bug-bash-helper #3912 is ready for review

**Comment by maxceem** [comment]
### Test guidelines

To fully verify this fix and possible regressions issues we have to test 4 cases:
1. Request invite for `pshah_copilot` to Toprocer Team by `pshah_manager` and **decline** request by `pshahcopmanag`.
2. Request invite for `pshah_copilot` to Toprocer Team by `pshah_manager` and **accept** request by `pshahcopmanag`.
3. Invite `pshah_copilot` to Customer Team, then log in by `pshah_copilot` and **decline** invitation on the project listing page, see details https://github.com/appirio-tech/connect-app/pull/3912#pullrequestreview-395907898
4. Invite `pshah_copilot` to Customer Team, then log in by `pshah_copilot` and **accept** invitation on the project listing page, see details https://github.com/appirio-tech/connect-app/pull/3912#pullrequestreview-395907898

**Comment by coderhacker** [comment]
QA Comments: The issue has been verified on dev and working fine as above test guideline. please see the below reference.
[3468_dev_pass.zip](https://github.com/appirio-tech/connect-app/files/4509251/3468_dev_pass.zip)

**Comment by lakshmiathreya** [comment]
-- Verified on Prod all the 4 scenarios listed above with users lakshmiaCopilot and lakshmiaCopMgr. Additionally verified Join and Decline via email notification. 

-- Verified additionally that invites by Connect Admin and Admin users dont need approvals.
