### ISSUE TITLE
status should be sorted in status filter

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#347]
### Expected behavior
data should be in sorted format
### Actual behavior
not sorted
### Steps to reproduce the problem
1. open the Application
2. Login with copilot :cp-superstar
3. go to project list
4.  click on status filters

### Screenshot/screencast
Attach or link a resource.

--
![image](https://cloud.githubusercontent.com/assets/16131461/18960304/eaa23dd6-8686-11e6-9aac-98ec71a17c46.png)

#### Environment
- OS: windows 7
- Browser (w/version): chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
This is intentional. Not valid.
