### ISSUE TITLE
[$40] Form got reset when we come back to choosing template but didn't change template

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3472]
Follow up from https://github.com/appirio-tech/connect-app/issues/3364#issuecomment-566234263.

Previously, we've implemented, that data and wizard state of the form are reset if we come back and choose a different template. There appears to be an edge case, when we choose the same template, we should not reset them.

## Steps to reproduce

1. I started creating a project and filled up a few screens
2. Used the back button present in the wizard
3. Then again chose the same project type
4. I can see the screen where I was before but the data I filled up are missing.

video: 
[missing data.zip](https://github.com/appirio-tech/connect-app/files/3969985/missing.data.zip)

## Expected behavior

The data and wizard state should stay when we choose the same template.

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by sumitdaga** [comment]
@bug-bash-helper assign

**Comment by sumitdaga** [comment]
oh it seems the two comments were almost simultaneous ..@rashmi you can assign again as you were the first one to post the comment

**Comment by maxceem** [comment]
Yes, @sumitdaga two comments almost the same time broke the bot. I've fixed the assignment to @rashmi73.

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3504 is ready for review

**Comment by maxceem** [comment]
@rashmi73 provided fix doesn't work for me. Please, see pull request review for details https://github.com/appirio-tech/connect-app/pull/3504#pullrequestreview-347050918

**Comment by rashmi73** [comment]
@maxceem 

any dynamic way to convert plain javascript object to object having mongodb query params in it?
https://www.npmjs.com/package/react-addons-update#update

Also, different projectType will have different properties so cant hardcode to a specific project fields in my PR

I did not find any such way online to convert plain object to mongodb query param?
my logic shall work perfect, a bit guidance would be helpful.

**Comment by maxceem** [comment]
@rashmi73 you may try to replace the line:
```js
_.assign(newProject, incompleteProject)
```

with:

```js
_.assign(newProject, { $set: incompleteProject })
```

or with:

```js
_.assign(newProject, { $merge: incompleteProject })
```

Though, I'm not sure if it would work correctly or would be there any issues.

**Comment by rashmi73** [comment]
@maxceem PR update https://github.com/appirio-tech/connect-app/pull/3504

**Comment by rashmi73** [comment]
@maxceem dont know why label is not changin?

**Comment by maxceem** [comment]
@rashmi73 strange, could you please try to post a comment one more time.

**Comment by maxceem** [comment]
@rashmi73 I've just checked updated PR, it still doesn't work for me https://github.com/appirio-tech/connect-app/pull/3504#pullrequestreview-348307030. Please, provide a demo video how it works for you with the next pull request.

**Comment by maxceem** [comment]
@rashmi73 we can wait for the fix for this issue for another 12 hours, though if there is no solution until that time I would have to unassign you, as Bug Bash is almost finished, and we need this issue to be done on time.

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@maxceem I would like to give a last try again, can you please mark it open so i can assign it back thank you

**Comment by maxceem** [comment]
Ok, I've assigned you back @rashmi73. We can wait 8 hours more for the solution. Though after I would have to assign you and open it for pickup.

**Comment by maxceem** [comment]
@rashmi73 as there is no update, this issue is unassigned and now is open for pickup.

**Comment by gets0ul** [comment]
@bug-bash-helper assign

**Comment by gets0ul** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3519 is ready for review

**Comment by nithyaasworld** [comment]
@maxceem Now the previous implementation is broken. That is, if we choose a different template, it shows the form with data filled for the first template. Form data are not reset in this case.

Please find the video: 
[template not reset.zip](https://github.com/appirio-tech/connect-app/files/4123250/template.not.reset.zip)

**Comment by maxceem** [comment]
@nithyaasworld that is expected behavior. We reset all data except of project "name", "description" and "ref code" as these fields are usually common for all templates, see https://github.com/appirio-tech/connect-app/issues/3364#issuecomment-558118788.

**Comment by nithyaasworld** [comment]
Awesome! Works perfect. Verified in Dev.

**Comment by drasticdpk** [comment]
QA Verified in Production. 
![image](https://user-images.githubusercontent.com/25297859/75649898-9264c880-5c7c-11ea-9941-f322ea433a9f.png)
