### ISSUE TITLE
Admin user cannot see any project

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3475]
1. Go to Connect Dev environment ( https://connect.topcoder-dev.com ) 
2. Login as an Admin user ( tested with topcoderconnect+Admin@gmail.com)
2. Check the dashboard

Actual:
No projects are displayed

![image](https://user-images.githubusercontent.com/5114190/71549534-ff41b500-29e4-11ea-9631-52267b389ecf.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by vikasrohit** [comment]
@nithyaasworld I can see all projects using the same login and on the same environment. It might be internet connectivity issue which failed the project load call. Can you please see if you are able to reproduce it and if yes, please share the console logs.

**Comment by nithyaasworld** [comment]
Thanks @vikasrohit for checking.

Its not reproducible to me, too. I too think it could be my internet issue. Closing this.
