### ISSUE TITLE
[Firebug Error Message] - when select Messages tab section

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#348]
Expected behavior
------------------------------------------------------------

- The 404 Error message is displayed in console.

Actual behavior
------------------------------------------------------------

- Do not display this error message when select tab.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Open Firebug Tool / Developer Tool to see all server calls performed.

- Edit any existing project.

- Select Messages tab section.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![1](https://cloud.githubusercontent.com/assets/5114907/18961331/5a95a7d4-8675-11e6-92c6-d31a5b9eb357.png)

**Comment by mahestro** [comment]
Duplicate, known.
