### ISSUE TITLE
Topcoder team member details disappear when changing status of project.

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#3481]
### Expected behavior
Topcoder team member details should remain intact irrespective of status change operation.

### Actual behavior
Topcoder team member details disappear when changing status of project.

### Steps to reproduce the problem
- Open any test project .
- Change status of project.
- Observe Topcoder team view.
- Refresh the page and again observe Topcoder team view.

### Screenshot/screencast
<img width="186" alt="Screen Shot 2020-01-06 at 8 20 46 AM" src="https://user-images.githubusercontent.com/11248478/71792147-94841f80-305d-11ea-9757-9ad70619dc17.png">

--

#### Environment
- OS: any
- Browser (w/version): any
- User role (client, copilot or manager): any
- Account used: any

**Comment by RishiRajSahu** [comment]
FYI @maxceem @vikasrohit

**Comment by maxceem** [comment]
@RishiRajSahu fixed and tested locally.

Create hotfixes:
- DEV https://github.com/appirio-tech/connect-app/pull/3482
- PROD https://github.com/appirio-tech/connect-app/pull/3483

**Comment by RishiRajSahu** [comment]
Fixed and patched to prod.
