### ISSUE TITLE
Full button is not clickable (Member/Copilot); Only text is hyperlinked

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#349]
### Expected behavior
-----------------------------------------------------------------
Full button must be clickable (Member/Copilot)

### Actual behavior
-----------------------------------------------------------------
Full button is not clickable (Member/Copilot)

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Dashboard
- Click 'Add a team Member'
- Check the Member and Copilot buttons; Only text is hyperlinked

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_21-29-07](https://cloud.githubusercontent.com/assets/4592712/18961772/ca837f42-868b-11e6-9963-eb84ffb3a0ac.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Known issue #109
