### ISSUE TITLE
Default topic for a new phase is not being created

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3490]
### Expected behavior
A discussion topic from CodeBot should be created

### Actual behavior
There is no discussion thread

### Steps to reproduce the problem
- Add phase to any project
- Go to Discussions tab
- Observe that there is no default coder bot message created

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

**Comment by vikasrohit** [comment]
fyi @lakshmiathreya  @maxceem

**Comment by maxceem** [comment]
I cannot reproduce this issue on DEV https://connect.topcoder-dev.com/projects/8687 or LOCALLY. Though I can reproduce it on PROD https://connect.topcoder.com/projects/11522.

Maybe somebody can check if there is an error in the log on PROD when we are adding a new phase to help to track down the issue.

**Comment by vikasrohit** [comment]
Yep, I am checking.

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @nithyaasworld

**Comment by vikasrohit** [comment]
This should be fixed now on production. https://github.com/topcoder-platform/tc-project-service/pull/446
