### ISSUE TITLE
[$30] Default sort on 'Last Updated' column is incorrect

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3491]
1. Login to connect and check the default sort of 'Last Updated'

Actual:
Though 'Last Updated' is selected as default sort, it is not correctly sorted by 'Last Updated'

![image](https://user-images.githubusercontent.com/5114190/72325014-3812a700-36d2-11ea-8e7b-330605dc0c45.png)

**Comment by nithyaasworld** [comment]
This is first reported by macs054 when working for the [Connect Test Case creation challenge.](http://www.topcoder.com/challenge-details/30112499/?type=develop)

CC: @SathyaJayabal @lakshmiathreya

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper assign

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3502 is ready for review

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/75542608-3e719e00-5a48-11ea-8074-283e188458f5.png)
 The latest date is not reflected as it doesn't show the Year, so it's hard to figure-out which is latest without the year in it.

**Comment by maxceem** [comment]
@drasticdpk it's quite a common practice to not show the year if the date represents the current year, and only show the year for past years. But let me know if this behavior should be changed.

**Comment by vikasrohit** [comment]
@maxceem I think we are good with current implementation. One enhancement we can do is to add tooltip which can show the full date time. I am assuming that this logic of hiding the current year is not explicit in our code but is handled by the underlying library, right?

**Comment by vikasrohit** [comment]
@drasticdpk Thanks for the suggestion about missing current year, however, I think the original requirement of the issue does not mention that. So, please feel free to create an enhancement ticket referring this issue and close this one.

**Comment by maxceem** [comment]
@vikasrohit it is explicit https://github.com/appirio-tech/connect-app/blob/dev/src/projects/list/components/Projects/ProjectsGridView.jsx#L155.

**Comment by drasticdpk** [comment]
Agreed with @maxceem to not showing the year for current year.  So closing the issue.
@vikasrohit  you want add tooltip to show the full date for above scenario ? I think no need to add that functionality when we are hiding year for current year.
