### ISSUE TITLE
It gives 500 error instead of 'no search results found' message

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3492]
1. Login to connect as Copilot user
2. Click on **one of the filters: Active or In Review or Reviewed, etc**
3. Search with a keyword that doesn't have any matching result
4. Check

Actual:
It shows 500 error instead of saying 'No matching results found'.
This doesn't happen if the user is in 'All Projects' tab

![image](https://user-images.githubusercontent.com/5114190/72337321-613e3200-36e8-11ea-873a-9af671269c3d.png)

![image](https://user-images.githubusercontent.com/5114190/72337336-669b7c80-36e8-11ea-94dd-9d83efba0462.png)

**Comment by maxceem** [comment]
This has been fixed at the Project Service via https://github.com/topcoder-platform/tc-project-service/commit/58781014400994032195ce58d8fbb3831c3fad6d.

It has been pushed to DEV and ready for testing on DEV.

**Comment by vikasrohit** [comment]
Thanks @maxceem Do you think this error was a regression issue after we did the v5 release?
Nevertheless we need it as hotfix as it seems to be blocking users from searching the projects.

**Comment by maxceem** [comment]
> Do you think this error was a regression issue after we did the v5 release?

No, this issue was here before, it is a regression after refactoring of the SQL query to prevent SQL injections https://github.com/topcoder-platform/tc-project-service/commit/07ef7d600e07fb67bcc761d7fdc64476f79603fc.

> or is it just happening when there is not result for the search?

It would happen if we filter by `keyword` and `status` together at the same time. Also, if we have some search results.

> Nevertheless we need it as hotfix as it seems to be blocking users from searching the projects 

Here is a HOTFIX for PROD https://github.com/topcoder-platform/tc-project-service/pull/443
Note, that this has been already pushed to DEV.

**Comment by vikasrohit** [comment]
Thanks @maxceem.
> It would happen if we filter by keyword and status together at the same time. Also, if we have some search results.

I think it happens only when there is no result for the combination of filters. I can view projects filtered by keyword and status at the same time, however, if the search combination produces empty result set, then it shows 500 instead of empty result page.

**Comment by maxceem** [comment]
> I think it happens only when there is no result for the combination of filters. I can view projects filtered by keyword and status at the same time, however, if the search combination produces empty result set, then it shows 500 instead of empty result page.

You are right, I can see it by testing on the PROD. Before I based my reply looking at the code.

**Comment by vikasrohit** [comment]
I guess in that case, we can keep it in our regular release unless someone else thinks it as P0/P1 to be deployed as hotfix. I am closing the hotfix PR for now and also upgrading the priority of the issue to P2 from P4.

**Comment by lakshmiathreya** [comment]
@drasticdpk pls verify in Prod.

**Comment by drasticdpk** [comment]
Search test Data :
 1. " /"
2. "Sales/Marketing"
If we have Forward Slash( / ) character in our search parameter it show's 500 error.
![image](https://user-images.githubusercontent.com/25297859/75557769-c23b8280-5a68-11ea-9b94-0c5dd82304eb.png)

 Could not see search box from customer login window, is it our business /domain? please confirm.
![image](https://user-images.githubusercontent.com/25297859/75558767-6a058000-5a6a-11ea-8edd-048f8b13d73d.png)

**Comment by vikasrohit** [comment]
Yes, right now search bar does not appear for customers. It has been like this since very long, please feel free to create separate issues for the enhancements.
Further, please create separate issue for your new finding of server error in case of `/` being entered in the search box.
Closing the issue for cleanup.

**Comment by vikasrohit** [comment]
@lakshmiathreya @drasticdpk I have remove the fail label and passed one as the original requirement is passed and created separate issue #3744 for the new finding.
