### ISSUE TITLE
Duplicate notifications from Connect 

### ISSUE THREAD

**Issue by m-yadav** [appirio-tech/connect-app#3493]
### Expected behavior
When the comments are modified in connect messages section, the users should get email notification along with the updated comment

### Actual behavior
When the comments are modified in the connect messages section, the users get the notification with the old text forcing the user to think it as a duplicate email.

**Comment by vikasrohit** [comment]
fyi @lakshmiathreya

**Comment by drasticdpk** [comment]
Verified on Dev env:
![image](https://user-images.githubusercontent.com/25297859/75740095-dfa17280-5d2e-11ea-800e-c7871020dc0e.png)

**Comment by vikasrohit** [comment]
Deployed to production.

**Comment by drasticdpk** [comment]
Scenario 1 > Passed
I have updated message/comment from customer account and observe email from copilot account.

[Verificatoin_-Customer_Copilot.mp4.zip](https://github.com/appirio-tech/connect-app/files/4281390/Verificatoin_-Customer_Copilot.mp4.zip)


Scenario 2 > Failed
I have updated the message/comments from Co-pilot acc  and expect the mail at customer'e email address. 
Could not get the email while updating the comments, here is the reference video. I follow the same process as dev env, correct me If I missed any steps:
[Verification_3493.mp4.zip](https://github.com/appirio-tech/connect-app/files/4281241/Verification_3493.mp4.zip)

**Comment by vikasrohit** [comment]
@drasticdpk if you are not receiving the emails for specific customer, please note it is not an issue which we are addressing here and we have to look at that incident separately and there are few possible reasons for not receiving emails:
1. Email settings are turned off for specific user
2. The comment is on a `admin only` topic
3. from your example project's team, I can see you don't have the user `makarThapa` in the team. So, I don't think you would receive emails.

**Comment by drasticdpk** [comment]
Thank you @vikasrohit. ( Initially email setting was off so email is not getting.)
Verified on prod :
https://recordit.co/O0nRUYyhv2
