### ISSUE TITLE
[$75] [Account App] sync businessPhone validation with member api

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3494]
The current issue is used to track a task in another repository during the Bug Bash challenge.

See task details https://github.com/appirio-tech/accounts-app/issues/333

All the comments to assign, unassign and ready for review should be done here in the current issue in Connect App.

**Comment by mhikeo** [comment]
@bug-bash-helper assign

**Comment by maxceem** [comment]
As no PR has been provided for 12 hours this issue has been unassigned and now is open for pickup.

**Comment by yoution** [comment]
@bug-bash-helper assign

**Comment by yoution** [comment]
@bug-bash-helper 
https://github.com/appirio-tech/react-components/pull/346
https://github.com/appirio-tech/connect-app/pull/3507
is ready for review

**Comment by yoution** [comment]
@bug-bash-helper https://github.com/appirio-tech/react-components/pull/346  ready for review

**Comment by yoution** [comment]
@maxceem   please review these two repos, https://github.com/appirio-tech/connect-app/pull/3507 
https://github.com/appirio-tech/react-components/pull/346

**Comment by maxceem** [comment]
@yoution works mostly good. Though implementation doesn't reuse `formsy` features, that should make the code simpler, as `PhoneInput` component is already implemented as formsy component.
Please, have a look at the reviews in Connect App https://github.com/appirio-tech/connect-app/pull/3507#pullrequestreview-347112336 and in React Components repo https://github.com/appirio-tech/react-components/pull/346#pullrequestreview-347122456

**Comment by yoution** [comment]
@maxceem   https://github.com/appirio-tech/react-components/pull/347
https://github.com/appirio-tech/react-components/pull/347

i pushed again for country code validate, but the issue in registerscreen page, the country code can not show, it maybe not my problem, the code I changed may not cause the problem, please check again

**Comment by maxceem** [comment]
Thanks @yoution I'll check again tomorrow. I've already marked it as `Ready or Review`.

> but the issue in registerscreen page, the country code can not show, it maybe not my problem, the code I changed may not cause the problem, please check again

I saw on your video it works good, so it's not in issue, the reason was just because example doesn't have country list.

**Comment by maxceem** [comment]
@yoution I've checked it out, please, have a look at review https://github.com/appirio-tech/connect-app/pull/3507#issuecomment-577980713.

**Comment by nithyaasworld** [comment]
@maxceem I entered the below info when registering. But when I checked in My-Profile after completing the registration, the info I entered are not seen. Could you check please?

![image](https://user-images.githubusercontent.com/5114190/73278402-8c10a600-4211-11ea-94f3-088c440263a8.png)
![image](https://user-images.githubusercontent.com/5114190/73278574-c9753380-4211-11ea-85b4-6c173e4eb962.png)

**Comment by yoution** [comment]
@maxceem  https://github.com/appirio-tech/react-components/pull/349 please review

**Comment by maxceem** [comment]
@nithyaasworld this has been fixed and ready for testing on DEV.

**Comment by drasticdpk** [comment]
Still got the same issue in Production, the registered information is not being reflected in Profile page.
![image](https://user-images.githubusercontent.com/25297859/75651711-5718c880-5c81-11ea-9328-18d7b2d1a40f.png).

**Comment by RishiRajSahu** [comment]
@drasticdpk could you please test again should be working fine now ?

**Comment by vikasrohit** [comment]
Closing. Please feel free to create new issue for any new findings or reopen if the issue still persists.

**Comment by drasticdpk** [comment]
Verified on prod env, it is working as expected.
![image](https://user-images.githubusercontent.com/25297859/75848702-0339eb00-5e0b-11ea-99cd-b56ea64a11bf.png)
