### ISSUE TITLE
[$45] [Project Service] Adding support to search project via customer/manager handles

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3496]
The current issue is used to track a task in another repository during the Bug Bash challenge.

See task details https://github.com/topcoder-platform/tc-project-service/issues/421

All the comments to assign, unassign and ready for review should be done here in the current issue in Connect App.

**Comment by amitpatra** [comment]
@bug-bash-helper assign

**Comment by amitpatra** [comment]
@bug-bash-helper unassign

**Comment by gets0ul** [comment]
@bug-bash-helper assign

**Comment by gets0ul** [comment]
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/448 is ready for review

**Comment by vikasrohit** [comment]
@maxceem while reviewing this fix, I realized that we might need to fix the reading of `primary:true` field for determining the project's customer when rendering the customer field data on project listing page. May be we need to show all customers now in that column, just like we are showing the managers.

**Comment by maxceem** [comment]
Do you mean that in the `Customer` column of the project listing page instead of only one customer who has `isPrimary: true` we should show all the members who is in the customer team?

![image](https://user-images.githubusercontent.com/146016/73170292-f99cd380-4138-11ea-9366-827b88ca4f8c.png)

**Comment by vikasrohit** [comment]
Yes, because when you search for a customer in the filter for the Customer filter, it would show some projects where the searched user is actually a customer of the project but it is not the primary customer which makes the customer column of the project to be empty.

**Comment by maxceem** [comment]
Created a follow-up issue https://github.com/appirio-tech/connect-app/issues/3524

**Comment by nithyaasworld** [comment]
@maxceem On trying to filter with handle 'bruce13', it shows 'Rishi''s project along with projects of other managers too. Could you check please?

Same issue with Customer filter too.

Marking this with 'QA Fail in Dev' for the above reason.

![image](https://user-images.githubusercontent.com/5114190/73275505-376b2c00-420d-11ea-98dd-dca876d3e23b.png)

**Comment by maxceem** [comment]
Currently, another branch `feature/looker_reporting` is deployed for Project Service instead of `develop` so there is no fix for this issue at this moment. I would update when it's there.

**Comment by maxceem** [comment]
@nithyaasworld The Project Service on DEV has been updated. This issue can be tested now.

**Comment by nithyaasworld** [comment]
Thanks @maxceem 

When I search with 'rishi' or 'bruce', it works as expected. But when I search with 'nithya' or some other name, it shows irrelevant result. Could you check please?

![image](https://user-images.githubusercontent.com/5114190/73412906-2e26b000-4330-11ea-8daa-5b6511f649d8.png)

**Comment by maxceem** [comment]
@nithyaasworld this is fixed and ready for testing.

**Comment by nithyaasworld** [comment]
@maxceem Both customer and manager filters are not working. It is always fetching no results. Could you check please?

![image](https://user-images.githubusercontent.com/5114190/73579494-9bf5e780-44a8-11ea-875f-54c0f6537544.png)

**Comment by maxceem** [comment]
I move the similar issue from another ticket https://github.com/appirio-tech/connect-app/issues/3524#issuecomment-580940525 as it is closer to the current issue:

2: The customer filter is not working. It always fetches me no-results for valid search criteria too.
![image](https://user-images.githubusercontent.com/5114190/73579141-a2379400-44a7-11ea-9b39-ba511bdbcd61.png)
![image](https://user-images.githubusercontent.com/5114190/73579182-c2ffe980-44a7-11ea-85f1-6bd5f8b07543.png)

**Comment by maxceem** [comment]
> @maxceem Both customer and manager filters are not working. It is always fetching no results. Could you check please?

The case with "doc" (keyword) and "bruce" (manager) work for me:

![image](https://user-images.githubusercontent.com/146016/73806347-35ecc580-4804-11ea-8d7a-0a2f5cf7d625.png)

> 2: The customer filter is not working. It always fetches me no-results for valid search criteria too.

Regarding the second case with customer https://github.com/appirio-tech/connect-app/issues/3496#issuecomment-581694635.

Could we please try to do it with a new project in case there is some broken data in old project. I've invited you to a new project https://connect.topcoder-dev.com/projects/8854. Could you please accept the invite, and after try to search for this project using your user as a customer, would it work?

**Comment by vikasrohit** [comment]
@maxceem we can reindex the culprit projects, if that helps.

**Comment by nithyaasworld** [comment]
Thanks @maxceem 

I joined the project https://connect.topcoder-dev.com/projects/8854 as a customer user. I tried to filter by my name, but I got empty results. I also tried with some more keywords and they did not work as well.

But when I tried after logging in as topcoderconnect+copilot@gmail.com user, it got me results when searched with 'Topcoder', but when searched with 'tccon' (the partial username), it did not fetch me any results.

Video: 
[Customer filter issue.zip](https://github.com/appirio-tech/connect-app/files/4163443/Customer.filter.issue.zip)


As Vikas suggested, Can we also please reindex the projects if that helps? Thanks.

**Comment by maxceem** [comment]
> @maxceem we can reindex the culprit projects, if that helps.

Yes, looks like user data have not been added to many recent projects. I propose to reindex `8xxx` projects on DEV. So we can test properly if searching by customers and managers works.

After that, we would watch if for some new projects member details are not added. Maybe the request for adding member details is failing due to Member Service Request Timeout.

**Comment by vikasrohit** [comment]
Make sense. I have started reindexing all projects with id 8xxx, should be done in next 10 minutes.

**Comment by maxceem** [comment]
@vikasrohit after reindexing search looks like working well. Though I've noticed one issue. When we are searching by `manager` we are only checking users with `manager` role. Though now we have a wide set of other roles https://github.com/topcoder-platform/tc-project-service/blob/feature/es-db-compare/src/constants.js#L27-L32 and our search doesn't find project for users with other roles.

As I understand this `manager` column in reality represent Topcoder team, and when we filter, we should search not only by users with `manager` role, but by any `non-customer` role, right?

**Comment by vikasrohit** [comment]
Yes, I think that makes sense as per the current state of the `manager` column. May be in future it changes its representation and that time we might need to update the search criteria again.

**Comment by maxceem** [comment]
@vikasrohit the search for users with any kind of manager role is implemented, though I've noticed one more issue:

- Search by `handle` and `email` is case-sensitive at the moment because these fields are defined as `not_analyzed` in the ES mapping:

   ![image](https://user-images.githubusercontent.com/146016/74298419-ab1c4580-4d84-11ea-80c9-3974d2cb3b33.png)

- To let us search by user `handle` and `email` case-insensitive way, we have to remove `not_analyzed` from the mapping and reindex all the projects.

Please, let me know if you'd like to go for it.

**Comment by vikasrohit** [comment]
Good catch.
Do you remember if we need to reindex all project for any other feature in upcoming two releases? if yes, we can do this changes as well otherwise we can create a separate issue for it and include it later.

**Comment by maxceem** [comment]
We would have to reindex projects when we would migrate links to the attachments model as per https://github.com/appirio-tech/connect-app/issues/3474#issuecomment-584460683. The challenge for server-side changes for attachments is in review phase now, so after a couple of days it could be concluded and we can run client-side changes for links. So I guess it would be completed before 1st March.

So since 1 March, we would have another reason to re-index projects to upgrade links to a new model.

I'm not sure what is our current plan for releases as we postponed the previous one.

**Comment by vikasrohit** [comment]
Feb release is planned for Feb 27, 2020. Do you think we can wrap that before that?

**Comment by maxceem** [comment]
It looks like no. We can get a solution around 28 February, but it would still need some time for testing.

Also, I found a few more issues for this ticket:
- It looks like it not only searches case-sensetive way, but has some other problems finding users with handles with upper-case. It fails to find projects even if I enter the full handle for some users:

   ![image](https://user-images.githubusercontent.com/146016/74696572-eb6f3e00-5232-11ea-8710-834a0bd6996b.png)

  - I guess the problem is because of using `not_analyzed` as the same projects can be found by the name:

  ![image](https://user-images.githubusercontent.com/146016/74696643-28d3cb80-5233-11ea-9042-41410e6b8a47.png)

- Another thing. Some projects are listed as `Unclaimed` while I can find them by entering `manager`:

  ![image](https://user-images.githubusercontent.com/146016/74696715-751f0b80-5233-11ea-966b-06c46ad1ad3b.png)

  The reason is, that there is no user with `manager` role, while we are searching user with any role, not only `manager` as per https://github.com/appirio-tech/connect-app/issues/3496#issuecomment-582894603:

  ![image](https://user-images.githubusercontent.com/146016/74696737-93850700-5233-11ea-9f91-a85019d3abbd.png)

   Should we show in the `Manager` column all the users from the Topcoder Team, not only managers?

**Comment by vikasrohit** [comment]
> Another thing. Some projects are listed as Unclaimed while I can find them by entering manager:

I think that is because we are searching for all members in the topcoder team, I guess while we are showing only members with `Manager` role only.

**Comment by vikasrohit** [comment]
For now lets enable searching only for `Manager` role members only to be consistent, I would discuss the need of showing all topcoder team in the listing page to make search consistent.

**Comment by maxceem** [comment]
> For now lets enable searching only for Manager role members only to be consistent, I would discuss the need of showing all topcoder team in the listing page to make search consistent.

I've reverted PR which implemented searching by all Topcoder Team members and created a new PR https://github.com/topcoder-platform/tc-project-service/pull/479  if we want to enable it again after getting confirmation from product team.

**Comment by vikasrohit** [comment]
@maxceem got updates from product managers. We should rename the column `Manager` to `Topcoder` and search for all members in topcoder team (including copilot for now).

**Comment by maxceem** [comment]
@vikasrohit ok, I've merged the PR to Project Service, and updated column in UI - renamed and also enabled showing ALL non-customer users in Topcoder column.

**Comment by nithyaasworld** [comment]
@maxceem 

 I have logged in as nithyaasworld/appirio123 user. Following cases are failing. Can you check please?

1. In the customer search field, searching with 'maxceem' is not fetching any matching projects though there are. 

Similarly searching with the handle 'TCConnCopilot' fetches no results.

![Issue1](https://user-images.githubusercontent.com/5114190/75315465-d45eca80-5888-11ea-9c6b-cd2b6a358e86.gif)

2. In the customer search field, searching with last name: 'Jt' fetches no results, though there are:
![Issue2](https://user-images.githubusercontent.com/5114190/75315797-b6de3080-5889-11ea-9e54-273019309d7b.gif)

3. Searching with some of the handles in 'Topcoder Search' field is not fetching matching results. Example handle: TCConCopilotMgr
![Issue3](https://user-images.githubusercontent.com/5114190/75316433-5cde6a80-588b-11ea-91c8-26ac2225c93a.gif)

**Comment by maxceem** [comment]
@nithyaasworld 

> 1. In the customer search field, searching with 'maxceem' is not fetching any matching projects though there are.

Oh, that's a very interesting finding:
- when I search using `pshah_manager` user, I get results for `maxceem`:
   
   ![image](https://user-images.githubusercontent.com/146016/75409853-d2623d80-5954-11ea-8c75-f5fd7c471d30.png)

- but when I search using `nithyaasworld` user, I don't get any results for `maxceem`:

   ![image](https://user-images.githubusercontent.com/146016/75409885-ec038500-5954-11ea-997d-ebf9190e22ac.png)

> 2. In the customer search field, searching with last name: 'Jt' fetches no results, though there are:

   This was data inconsistency in DEV. I've fixed the data and search works well:

    ![image](https://user-images.githubusercontent.com/146016/75409971-44d31d80-5955-11ea-985f-29e353723e36.png)

>3 Searching with some of the handles in 'Topcoder Search' field is not fetching matching results. Example handle: TCConCopilotMgr

Yes, searching by the handle when there are capital and lowercase letters doesn't work properly.

As there are 2 issues with searching by `handle` let's keep this issue. It appears that implementing searching by `handle` requires more work to do that seemed in the beginning. So I propose to move this issue to the next release.

**Comment by vikasrohit** [comment]
@maxceem can we close this one or something remaining from the original requirements?

**Comment by maxceem** [comment]
@vikasrohit there are some issues in the current implementation. So let's keep it open and finish work in this issue, as indeed there are some broken situations.

**Comment by maxceem** [comment]
I've moved it to `2.8`.

**Comment by maxceem** [comment]
After more detailed testing it looks like there is only one real issue left: searching by the handle is currently case-sensitive https://github.com/topcoder-platform/tc-project-service/issues/499

All other issues were caused by indexing failure, like:
> In the customer search field, searching with 'maxceem' is not fetching any matching projects though there are.

@vikasrohit it looks like at least on DEV environment when we are adding new member to the project the request to member service fails somehow, so there is no `handle`, `firstName` and `lastName` for project members in ES unless we reindex the project.

Could you help me to debug it on DEV? As locally it works good:
1. We have to check that `AUTH0_CLIENT_ID` / `AUTH0_CLIENT_SECRET` are configured for `project-processor-es` on DEV
2. If Auth0 is configured then we can try to check if there are errors in log of `project-processor-es` when users accept invitations.

**Comment by maxceem** [comment]
This should be working now on DEV and can be tested.

**Comment by codejamtc** [comment]
https://www.screencast.com/t/kkKTUBaUZ

**Comment by coderhacker** [comment]
This is working fine with customer user on prod needs to verify with manager credential. @codejamtc @lakshmiathreya 

[3496-prod.zip](https://github.com/appirio-tech/connect-app/files/4421090/3496-prod.zip)

**Comment by codejamtc** [comment]
@lakshmiathreya ☝️

**Comment by lakshmiathreya** [comment]
Verified Search and display of customer/TC team handles via Admin, Copilot, Copilot Manager, Account Manager and Connect Manager roles.
