### ISSUE TITLE
[$35] [Project Service] Update Postman file

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3497]
The current issue is used to track a task in another repository during the Bug Bash challenge.

See task details https://github.com/topcoder-platform/tc-project-service/issues/429

All the comments to assign, unassign and ready for review should be done here in the current issue in Connect App.

**Comment by narekcat** [comment]
@bug-bash-helper assign

**Comment by narekcat** [comment]
@bug-bash-helper unassign

**Comment by narekcat** [comment]
Sorry couldn't find enough time to finish this issue. It is late and I'm very tired.

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper assign

**Comment by maxceem** [comment]
@PrakashDurlabhji 

As no pull request has been provided for 12 hours this issue has been unassigned and now is open for pickup.

**Comment by yoution** [comment]
@bug-bash-helper assign

**Comment by yoution** [comment]
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/449 is ready for review

**Comment by yoution** [comment]
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/449 is ready for review
