### ISSUE TITLE
[Add a Team Member] - the existing username is displayed as autocomplete

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#350]
Expected behavior
------------------------------------------------------------

- Display in autocomplete only user after correct text set.

Actual behavior
------------------------------------------------------------

- The existing username is displayed as autocomplete.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager role.

- Edit any existing project eg. Nicu {Project}.

- Use "+" button option to add a new team member.

- Set in field the text "christina_uw".

- Observe the username is returned.

- Delete the text set.

- Complete again the field.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: pat_monahan
Account used: manager role

![4](https://cloud.githubusercontent.com/assets/5114907/18962193/79c19534-8678-11e6-8e50-c269fe6457bc.png)

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
Being fixed on https://github.com/appirio-tech/connect-app/issues/351
