### ISSUE TITLE
Remove redundant "emailBundling" from notification settings

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3505]
On the notification setting page, we edit notification settings. At the moment visually we support two notification services: `web` and `email`:

![image](https://user-images.githubusercontent.com/146016/72862315-b04b1f00-3d07-11ea-8314-7842eb8812e0.png)

But in the code, we still list `emailBundling` as a third service but we never update its value, but the code still set its default value which we cannot update by UI https://github.com/appirio-tech/connect-app/blob/cf20/src/routes/settings/routes/notifications/components/NotificationSettingsForm.jsx#L138

![image](https://user-images.githubusercontent.com/146016/72862553-8e05d100-3d08-11ea-8eec-6b9e6fb69694.png)

And it looks like we actually don't use `emailBundling` service at the TC Notifications repo. The only place I found it is in constants https://github.com/topcoder-platform/tc-notifications/blob/v5-upgrade/connect/constants.js#L13. But the constant itself is never used.

So it feels that we can just remove mentions of `emailBundling` from Connect App and from Tc Notification service as we don't actually use it.

@vikasrohit do you think it would be safe, or do you know any place where it could be still possibly used?

**Comment by vikasrohit** [comment]
I think it is safe now to remove `emailBundling` as we are using the `bundlePeriod` field on the email service settings to determine if user has set the bundling or immediate action. I guess, we are setting, depending on what user has selected in the dropdown, the `bundlePeriod` for `email` service settings, in front when passing the payload to the settings API.

**Comment by vikasrohit** [comment]
Lets do it in next release.

**Comment by maxceem** [comment]
Done via dd43758ae318d1a9bbd2e933119408126637c0a4 in Connect App and https://github.com/topcoder-platform/tc-notifications/commit/98ebc428bc463e6625fa8e3d11c1094fecf2a01e in TC Notification repo.

**Comment by vikasrohit** [comment]
Just to double sure, we haven't observed any issue with notification emails after this change @maxceem, right?

**Comment by vikasrohit** [comment]
Some days earlier, Lakshmi tried to send me invite to a project in dev, but I didn't receive email notifications for such attempts. I assume that was because of some other issue with invite process which you mentioned on Slack.
Can you just try to invite me to a project in dev, using my email?

**Comment by maxceem** [comment]
> Just to double sure, we haven't observed any issue with notification emails after this change @maxceem, right?

Me and **codejam** during invite testing received email invites several times successfully.

> Can you just try to invite me to a project in dev, using my email?

I Invited you to this project https://connect.topcoder-dev.com/projects/8944

**Comment by codejamtc** [comment]
@maxceem I think it's broken, I just send an invitation to my email but didn't receive an email invitation

**Comment by maxceem** [comment]
I've got your invite @codejamtc:

![image](https://user-images.githubusercontent.com/146016/77614530-3c630800-6f3e-11ea-9aec-9279e46b2104.png)

**Comment by maxceem** [comment]
@codejamtc did you have a chance to try to get an email invitation for your account one more time?

**Comment by vikasrohit** [comment]
I received the notification for invite @maxceem, I think we are good. We can close it now.
