### ISSUE TITLE
[Add a Team Member] - the existing username is displayed as autocomplete when set focus

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#351]
## Expected behavior
- Do not display the previous founded username in popup window.
## Actual behavior
- The previous username is displayed in popup window.
## Steps to reproduce the problem
- Login into application as manager role.
- Edit any existing project eg. Nicu {Project}.
- Press "+" button to add a new team member.
- Complete field with christina_uw name.
- Delete the name after autocomplete.
- Use "x" close option to close the add team member section.
- Press again on "+" button.
- Set focus on Add Team Member field.
## Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager role
Account used: pat_monahan

![123](https://cloud.githubusercontent.com/assets/5114907/18962346/29123228-8679-11e6-8705-6dd059693ee4.png)

**Comment by mahestro** [comment]
Valid. Related to #350

**Comment by fnisen** [comment]
Didn't fix the related issue (350), so opening this one.

**Comment by vikasrohit** [comment]
Didn't get it @fnisen. If we are not going to fix #351 (which is labelled as won't fix), then we would not be fixing this one as well as it seems duplicate to me. Please let me know if I mis-interpreted this issue.

**Comment by fnisen** [comment]
@vikasrohit sorry, got some confusion because of the labels. I'd like to fix this issue, which was listed on both https://github.com/appirio-tech/connect-app/issues/350 and this ticket (351). If we are fixing it here, we don't need to fix 350, which is a duplicate and marked as won't fix. I'll close it. Anyway, this is P2, so not urgent. Please work on P0's and P1's first.

**Comment by vikasrohit** [comment]
@fnisen Done. Please let me know if the new behaviour serves the purposes.

**Comment by fnisen** [comment]
@vikasrohit yes, tested and works well. Thanks.
