### ISSUE TITLE
Filtering on tags

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3512]
Carried from #3464 
Tagging is not implemented yet, hence we can have filter on tags. We would support the filtering on tags after getting #3462 is done.

**Comment by vikasrohit** [comment]
@maxceem do you think we would be able to wrap this in this release? I can see #3462 is near to complete.

**Comment by maxceem** [comment]
Unfortunately no, we've just got them implemented server-side. But the server-side changes are breaking and require data migration. So we would have to release all the features together: links as attachments and tags.

**Comment by vikasrohit** [comment]
ok. Thanks for the update, moving to next release. @maxceem we have to move the other part of tagging feature i.e. ability to add tags to the next release as well. We want to release both features in same release.

**Comment by maxceem** [comment]
What kind of input for filtering by tags you like:
- simple input where we enter any arbitrary text, and after we are searching for attachments which have at least one tag with the substring we entered
- smart input field where we can enter tags like this:
   ![image](https://user-images.githubusercontent.com/146016/75871587-c17b6580-5e47-11ea-9981-4d146955a7da.png)

   - as we load all the attachments at the moment, we can extract all the tags, and implement autocomplete for this field
   - we can find attachments which have **ALL** entered tags or **ANY** entered tag (at least one of entered), which way would you prefer if you choose the smart input?

**Comment by vikasrohit** [comment]
I would like to go with simple text box for now because auto completing tags is not possible to support in near future, after we go for paged data in assets tab.

**Comment by codejamtc** [comment]
https://www.screencast.com/t/LfNTRRdu2GRK

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects/14177/assets
CustomerUser/appirio123

[3512-prod.zip](https://github.com/appirio-tech/connect-app/files/4420157/3512-prod.zip)
Verified on prod, working as expected.
