### ISSUE TITLE
'ADD A TEAM MEMBER' Tool tip "Create New Link" must --> 'ADD A TEAM MEMBER'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#352]
### Expected behavior
-----------------------------------------------------------------
'ADD A TEAM MEMBER' Tool tip "Create New Link" must --> 'ADD A TEAM MEMBER'

### Actual behavior
-----------------------------------------------------------------
'ADD A TEAM MEMBER' Tool tip is incorrect

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Dashboard
- Hover over the 'Add a team Member' icon

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_21-51-14](https://cloud.githubusercontent.com/assets/4592712/18962534/e10d8034-868e-11e6-997f-10d75b0af786.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.
