### ISSUE TITLE
Added links are disappeared

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3521]
1. In Production, login as copilot (I tried with my id)
2. Go to any project and add some links
3. Navigate back to the dashboard
4. Again go to the same project as in step:2 and check the links

Actual:
Added links are gone.

Expected:
Links should not disappear.

Browser: FF on windows 10

Video of the issue: 
[links are gone.zip](https://github.com/appirio-tech/connect-app/files/4115735/links.are.gone.zip)

**Comment by SathyaJayabal** [comment]
Could reproduce the issue in Chrome browser on Mac OS

**Comment by nithyaasworld** [comment]
Thanks @SathyaJayabal Marking it with p0 as the function is broken.

CC: @maxceem @vikasrohit @lakshmiathreya

**Comment by nithyaasworld** [comment]
@vikasrohit marking this with milestone 2.5 as this has been already released to production as part of #3522 Please correct me if I am wrong. Thanks.

**Comment by vikasrohit** [comment]
Yes, that is what I usually do. We would keep following that pattern, until we have new way/process.
