### ISSUE TITLE
Some projects are not showing the updated changes

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3522]
### Expected behavior
Updated data should be visible even after page refresh

### Actual behavior
For some projects, changes made by the user are lost (or at least seems to be lost), when user refreshes the page after the update.

### Steps to reproduce the problem
- Update some data in a project
- Refresh the page
- Observe if the changes made, are reflected or not

--

#### Environment
- OS: Mac OS
- Browser (w/version): Chrome
- User role (client, copilot or manager): Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
@lakshmiathreya fyi

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @nithyaasworld

**Comment by maxceem** [comment]
@vikasrohit do you have any example apart from http://connect.topcoder-dev.com/projects/8709 (DEV)?

**Comment by nithyaasworld** [comment]
@vikasrohit is https://github.com/appirio-tech/connect-app/issues/3521 because of #3522 ?

**Comment by vikasrohit** [comment]
Yes, @nithyaasworld

**Comment by nithyaasworld** [comment]
@maxceem @vikasrohit Last-Updated info is also not getting updated after adding a file or link to the project. Should this be addressed as part of this issue or this is a new issue and needs a new ticket? Thanks.

![image](https://user-images.githubusercontent.com/5114190/73170127-a3716580-4123-11ea-958d-5975298840eb.png)

**Comment by maxceem** [comment]
If all the data including the project name can be updated but only `Last updated` stays the same, then it looks like another issue, with `Last updated` only.

**Comment by nithyaasworld** [comment]
Thanks @maxceem You are right! Only the 'Last updated' stays the same. I will log a new bug. 

Closing this.
