### ISSUE TITLE
Show all customer in the "Customer" column of the project listing page

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3524]
Follow up from https://github.com/appirio-tech/connect-app/issues/3496#issuecomment-578684892

In the `Customer` column of [the project listing page](https://connect.topcoder-dev.com/projects?sort=lastActivityAt%20desc) instead of only one customer who has `isPrimary: true` we should show all the members who are in the customer team (i. e. all members with `role === "customer"`).?

![image](https://user-images.githubusercontent.com/146016/73170292-f99cd380-4138-11ea-9366-827b88ca4f8c.png)

Because when we search for a customer in the filter for the Customer filter, it would show some projects where the searched user is actually a customer of the project but it is not the primary customer which makes the customer column of the project to be empty.

**Comment by maxceem** [comment]
Basically, to implement this issue we can use the same component for showing several user avatars as we use for managers. We just should filter members using the criteria `role === "customer"`.

**Comment by yoution** [comment]
@maxceem  has pushed, please review https://github.com/appirio-tech/connect-app/pull/3531

**Comment by maxceem** [comment]
@nithyaasworld this is ready for testing.

**Comment by nithyaasworld** [comment]
@maxceem 

1: If we have more than 3 Customers for a project, we now show '+1' text (and no hyperlink on the +1 ). Please confirm if this is okay

![image](https://user-images.githubusercontent.com/5114190/73579096-79170380-44a7-11ea-8517-95214086c321.png)


2: The customer filter is not working. It always fetches me no-results for valid search criteria too.
![image](https://user-images.githubusercontent.com/5114190/73579141-a2379400-44a7-11ea-9b39-ba511bdbcd61.png)
![image](https://user-images.githubusercontent.com/5114190/73579182-c2ffe980-44a7-11ea-85f1-6bd5f8b07543.png)

**Comment by maxceem** [comment]
@nithyaasworld

> 1: If we have more than 3 Customers for a project, we now show '+1' text (and no hyperlink on the +1 ). Please confirm if this is okay

It should not be a link. It only shows that there are more customers who are not shown. The same we have for managers:

![image](https://user-images.githubusercontent.com/146016/73703543-2f3e4f80-472b-11ea-8ef3-1e7fe814701d.png)

> 2: The customer filter is not working. It always fetches me no-results for valid search criteria too.

This issue is already logged at another issue https://github.com/appirio-tech/connect-app/issues/3496#issuecomment-580942283 so we can track it there as it closer to that issue.

**Comment by drasticdpk** [comment]
Verified :
![image](https://user-images.githubusercontent.com/25297859/75648580-9db5f500-5c78-11ea-8fda-b59320656fa5.png)
