### ISSUE TITLE
Long customer names are overlapping in the Manager column

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3525]
### Expected behavior
Long customer names should not overlap in the next column

### Actual behavior
Overlapping with manager column

### Screenshot/screencast
<img width="310" alt="Screen Shot 2020-01-27 at 5 35 47 PM" src="https://user-images.githubusercontent.com/2417632/73173548-9d7f8280-412b-11ea-99bb-f4a91e68a424.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

**Comment by vikasrohit** [comment]
@maxceem can we get it fixed before this release?

**Comment by vikasrohit** [comment]
It is not happening on production.

**Comment by maxceem** [comment]
Expected behavior: the customer name should not go out of the "Customer" column, it should get cut with an ellipsis at the end `...`. It should not go to the second line.

**Comment by maxceem** [comment]
@vikasrohit I've just realized, that if we start showing all customers as avatars, same as manages, we don't have to fix this issue. We can implement another issue instead https://github.com/appirio-tech/connect-app/issues/3524.

**Comment by vikasrohit** [comment]
Yes, agreed. Closing it.
