### ISSUE TITLE
'Last Updated' info is not getting updated

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3526]
1. Go to connect Production env
2. Login as Copilot and click on any project
3. Update any information like project-title, scope, etc
4. Add files and links
5. Go back to project dashboard and check the 'Last updated' info

Actual:
Last-updated is not getting updated. 

Expected:
It should get updated with the right info.

![image](https://user-images.githubusercontent.com/5114190/73173671-ef280d00-412b-11ea-9501-cc1e28de73c2.png)

**Comment by vikasrohit** [comment]
@maxceem this issue is happening because we are not updating the `lastActivityAt` field on file upload and link creations?

**Comment by maxceem** [comment]
Hmm, looks like it's not updated even if I update project spec or add a new phase.

**Comment by vikasrohit** [comment]
Oh, that means it was broken after our v5 changes? I doubt some missing event handler or event rename.

**Comment by maxceem** [comment]
@vikasrohit this also doesn't work on PROD.

This field is updating by Project Service listening to Kafka events itself. A year ago Kafka consumer in Project Service has been moved to a separate app instance https://github.com/topcoder-platform/tc-project-service/commit/356594fc996f2d21ea5391020051f1c7e2c618c1#diff-72676a17a589f9ae10b4a659f87aafd8.

So I guess the first what we can check, is that Kafka consumer instance is successfully run on DEV/PROD environments, see the command https://github.com/topcoder-platform/tc-project-service/blob/v4/package.json#L18.

And if there are any errors in its console.

**Comment by vikasrohit** [comment]
Kafka consumers are running separately in separate ECS task which I can see running smoothly before our v5 changes. I think we are missing this `lastActivityAt` updating after the v5 changes because we didn't move the older `project-service-consumers` task (which was running that index-kafka.js). Can you please double check if we have the code for updating the `lastActivityAt` field in our v5 code?

**Comment by vikasrohit** [comment]
@maxceem I verified on production by updated the project scope, and it did updated the `lastActivityAt` field and made the project to list on the top. We might be missing certain other events, e.g. file upload or link creation for updating of the `lastActivityAt` field.

**Comment by maxceem** [comment]
@vikasrohit it's not getting updated for me on PROD even if I change project name or scope.

We have an issues on the PROD at the moment - it is showing project sorted by `updatedAt` rather than `lastActivityAt`. So if we updated anything inside the project it would be shown up because of using `updatedAt` for sorting.

Could you please try this URL https://connect.topcoder.com/projects?sort=lastActivityAt%20desc to force sorting by `lastActivityAt`. Also, please, check if the date has been actually updated for the project to the latest?

**Comment by maxceem** [comment]
> Can you please double check if we have the code for updating the lastActivityAt field in our v5 code?

Yes, wee keep al the code for updating `lastActivityAt` during V5 migration.

I run Kafka Consumer for Project Service locally, and it works good for me:

![image](https://user-images.githubusercontent.com/146016/73833881-acf67e00-4845-11ea-9e46-0b36b854d790.png)

I can see that `lastActivityAt` got updated if I change project `name`, `details` or add a new `phase` to the project.

Could you please check the log of `index-kafka.js` on DEV or PROD?
1. When was the last consumed event logged?
2. Are there any errors recently?

**Comment by vikasrohit** [comment]
@maxceem I think no one is executing the index-kafka.js that is what I am concerned when we moved to v5, we accidentally stopped the bus event consumers. We need to create separate processor or enable consumers in the projects-api itself.

**Comment by maxceem** [comment]
@vikasrohit Should we start Kafka Consumer Service for Project Service in CircleCI as we did before? https://github.com/topcoder-platform/tc-project-service/commit/012de9b3e9089cee4982b98b4e7afde3ab5c7610#diff-1d37e48f9ceff6d8030570cd36286a61L36-L41

**Comment by vikasrohit** [comment]
I think yes.
I was trying to quickly spin up a new repo (`platform-events-project-processor`) for handling all platform events which matters for project. However, I think it worths trying to instantiate the separate consumer task from the same repo for now. I would try that now first.

**Comment by vikasrohit** [comment]
@maxceem I am able to spin up the separate task for consuming the bus events (using the index-kafka.js). Logs shows it is running in good shape, how do you test that it is actually working fine?

**Comment by maxceem** [comment]
Great. I tested it on DEV, it works for me now:

![image](https://user-images.githubusercontent.com/146016/73937358-d388e780-491f-11ea-8631-c64a7499c728.png)

> how do you test that it is actually working fine?

- I do any of the actions that cause of one the next Kafka events: https://github.com/topcoder-platform/tc-project-service/blob/feature/es-db-compare/src/events/index.js#L75-L85
    - For example, the simples case is to change the project `name` or project spec.
- After, that we can check if the project `lastActivityAt` has changed or no. It can be seen by the date in the `Last Updated` column.
   - If no, I check if Kafka even was triggered or no at `lauscher` to make sure if it's issue with the consumer or even just wasn't triggered.

**Comment by maxceem** [comment]
###  Verification guide

To fully verify this issue we should test all the next cases the date in the **Last Updated** column is updated.

- Update project name
- Update project spec
- Update project description
- Change project status
- Add, edit or remove project link (on Assets Library page)
- Add, edit or remove project file (on Assets Library page)
- Add, update or remove a team member
- Add or remove a phase
- Change phase Start Time, Duration or Status

**Comment by maxceem** [comment]
@nithyaasworld, in general, we fix this issue on DEV. There are many cases when this date should get updated and it's possible that some of them could be broken.

**Comment by nithyaasworld** [comment]
@maxceem On editing a Title, its not updating the 'Last Updated' info. Everything else works Perfect!

Please find the video: 
[topic edit.zip](https://github.com/appirio-tech/connect-app/files/4184317/topic.edit.zip)

**Comment by maxceem** [comment]
@nithyaasworld great catch!

It's fixed now, deployed to DEV and ready for testing.

@vikasrohit the issue was in Message Service: it never sent event `connect.notification.project.topic.updated` https://github.com/appirio-tech/tc-message-service/issues/113 on topic update. We should not forget to deploy it during the release, or we we can deploy it as a hotfix for Message Service as the actual fix is small.

**Comment by nithyaasworld** [comment]
@maxceem I am not able to see the Messages or post new messages though I am part of the project. Can you please check? Thanks.

Video:  
[not able to post messages.zip](https://github.com/appirio-tech/connect-app/files/4195462/not.able.to.post.messages.zip)

Console Screenshot:
![image](https://user-images.githubusercontent.com/5114190/74385339-5545ad00-4e19-11ea-9b4c-25eeb3c06a6f.png)

![image](https://user-images.githubusercontent.com/5114190/74385367-67bfe680-4e19-11ea-8bf7-6992c7c3eed6.png)

**Comment by nithyaasworld** [comment]
@maxceem I am still experiencing the same issue as above. Can you check please? Thanks.

Video: 
[Not able to Post messages.zip](https://github.com/appirio-tech/connect-app/files/4217584/Not.able.to.Post.messages.zip)

**Comment by nithyaasworld** [comment]
Please let me know if this needs to be handled in a new ticket. I will create a new ticket.

**Comment by maxceem** [comment]
@vikasrohit looks like on DEV normal users without `Manager` permissions cannot load or create posts (I've tried a few projects). Could it be that that `reference_lookups` URL for `project` is not updated to V5 on DEV?

**Comment by vikasrohit** [comment]
@maxceem I thought I have updated that to v5 long back, but seems like I did that to wrong database (backup of messages database). I have update it now to point to v5, let me know if it works now for you guys. Sorry for the troubles.

**Comment by maxceem** [comment]
Thanks, Vikas, it works now.

@nithyaasworld could you, please, try one more time. This issue was due to not updated config in DEV deployment which is fixed now.

**Comment by nithyaasworld** [comment]
Thanks @maxceem and @vikasrohit.

Verified.

**Comment by lakshmiathreya** [comment]
@drasticdpk - working in Prod - pls close after you double check.

**Comment by nithyaasworld** [comment]
@maxceem @vikasrohit 

It seems we have missed this one. So editing-a-title is not updating the last-updated info. Can you check please? Thanks.

> @vikasrohit the issue was in Message Service: it never sent event connect.notification.project.topic.updated appirio-tech/tc-message-service#113 on topic update. We should not forget to deploy it during the release, or we we can deploy it as a hotfix for Message Service as the actual fix is small.

**Comment by maxceem** [comment]
@nithyaasworld it works good for me, see [dome video](https://monosnap.com/file/GQXarUPJPTk4kHaQc2OUQ1Acet0dA0)

Could you please, let me know which project do you use to reproduce this issue?

**Comment by nithyaasworld** [comment]
Hi @maxceem 

Its for the 'Edit-Title' action. The separate fix which you made [here](https://github.com/appirio-tech/connect-app/issues/3526#issuecomment-584517630)

If its still not reproducible, please let me know. I will add a video.

**Comment by nithyaasworld** [comment]
@maxceem Deepak just retested it and it worked for him. It is working for me too. Closing this.

CC: @drasticdpk
