### ISSUE TITLE
Can click Add Link when there is a Delete confirmation validation

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#353]
### Expected behavior
-----------------------------------------------------------------
Must hide the 'Add Link' when there is a Delete confirmation validation; Like 'ADD A TEAM MEMBER'

### Actual behavior
-----------------------------------------------------------------
Can click Add Link when there is a Delete confirmation validation

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Dashboard
- Add Some links
- Now click DELETE 
- Try to Click Add Links

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_21-55-34](https://cloud.githubusercontent.com/assets/4592712/18962687/7af3dde2-868f-11e6-8ab7-9a8c8872be3b.png)

In the ADD A TEAM MEMBER; it is disabled

![2016-09-29_21-56-22](https://cloud.githubusercontent.com/assets/4592712/18962723/9b1035da-868f-11e6-912e-4f45de5a6fe3.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid. Should fade as team management does.

**Comment by vikasrohit** [comment]
Fixed with latest changes for #244
