### ISSUE TITLE
'Successfully' is misspelled in the info-message

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3532]
'Successfully' is misspelled as 'Su**ccc**essfully' in the below screen

![image](https://user-images.githubusercontent.com/5114190/73297657-fa656080-4231-11ea-83eb-21e6c76122ea.png)

**Comment by maxceem** [comment]
Fixed and pushed to DEV, ready for testing.

**Comment by nithyaasworld** [comment]
Verified in dev.

![image](https://user-images.githubusercontent.com/5114190/73406534-a71c0c80-431c-11ea-8508-83037ae45100.png)

**Comment by drasticdpk** [comment]
Verified on prod env :
![image](https://user-images.githubusercontent.com/25297859/75537516-601a5780-5a3f-11ea-9adf-3046b080e46a.png)
