### ISSUE TITLE
Application & Website sub-title has dummy data

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3535]
![image](https://user-images.githubusercontent.com/42398485/73331181-9db17800-4228-11ea-97c7-5b3f0227e093.png)

1. Open the Application and Login as a valid user (Manager)
2. Go to Dashboard > All Projects
3. Click + New Project > View Solutions > 
4. Check the Sub-Title of Application & Website

**Actual:** Application & Website sub-title has dummy data

**Expected:** Should not proper sub-title

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** IE11 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
Content issue
