### ISSUE TITLE
Solution and On Deman icons are different from the design

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3536]
![image](https://user-images.githubusercontent.com/42398485/73331152-85415d80-4228-11ea-9ca1-fb50c643407f.png)

1. Open the Application and Login as a valid user (Manager)
2. Go to Dashboard > All Projects
3. Click + New Project

**Actual:** Solution and On Deman icons are different from the design

**Expected:** Should match with the design
https://marvelapp.com/cc9e4j1/screen/65344038

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** IE11 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
Content Issue
