### ISSUE TITLE
Analytics & Data Science sub-title has dummy data

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3537]
![image](https://user-images.githubusercontent.com/42398485/73331382-32b47100-4229-11ea-9079-2b5a0f8850d3.png)

1. Open the Application and Login as valid user (Manager)
2. Go to Dashboard > All Projects
3. Click + New Project > View Solutions > 
4. Check the Sub-Title of Analytics & Data Science

**Actual:** Analytics & Data Science sub-title has dummy data

**Expected:** Should not proper sub-title

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
Content Issue
