### ISSUE TITLE
Deleting the Search keyword from the field won't reset the search result

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3539]
https://www.screencast.com/t/QonaFJZHFc

1. Open the Application and Login as a valid user (Manager)
2. Go to Dashboard > All Projects
3. Click + New Project > View Solutions > 
4. Enter 'abcd' to search field > Search
5. Delete the 'abcd' (You can see Search button is disabled now)

**Actual:** Deleting the Search keyword from the field won't reset the search result

**Expected:** Should display the full list and should remove the (x) clear button from the search textbox

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** IE11 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
As per design
