### ISSUE TITLE
'ADD A TEAM MEMBER' is opened at the bottom of the list

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#354]
### Expected behavior

---

'ADD A TEAM MEMBER' option must open on top of the list; Then it is easy to add new members when the list is lengthy
### Actual behavior

---

'ADD A TEAM MEMBER' is opened at the bottom of the list
### Steps to reproduce the problem

---
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Dashboard
- Click 'ADD A TEAM MEMBER'
- Add some members (eg: 20)
- Now try to add a new team member
- The Add new member form is opened as the last option; if the list is big user needs to scroll down large list to add a new member
### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section)

---

![2016-09-29_22-04-25](https://cloud.githubusercontent.com/assets/4592712/18963005/b4fddc26-8690-11e6-9ca6-0691c3346562.png)
### Environment

---
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
This is per design. @fnisen please think if we want to add everything from the top of the list. Once you add elements at the top, you'd expect the latest element to stay on top. With Links that's valid, but for team members adding at the top would load at the bottom, so that'll break the user experience.

**Comment by fnisen** [comment]
@vic-appirio I agree. I think the issue is that you have to scroll you down--we don't scroll you down to the bottom automatically. Should we just do that?

**Comment by vic-appirio** [comment]
I'd like to take a consistent approach for adding items through the top "+" button. From my perspective we still haven't fully implemented this component the way it could be a reusable global component;

- [ ] Adding always covers the header - title transforms into module title; "+" becomes "x", the controls are always on top of the panel

- [ ] The rest of the side panel should be unaccessible while in Adding mode;

- [ ] After adding at the bottom of the list we can scroll to display the newly added member.

@fnisen let me know if that makes more sense

**Comment by fnisen** [comment]
@vic-appirio yes, it does. The one I'd like to add is focusing you right away on where you're adding the team member. You shouldn't have to scroll down to find it. Do you want to do a prototype of the expected experience?

**Comment by fnisen** [comment]
Fixed as part of these issues: 
- https://github.com/appirio-tech/connect-app/issues/465
- https://github.com/appirio-tech/connect-app/issues/526
