### ISSUE TITLE
Quality assurance options in application are different than those preent in design

### ISSUE THREAD

**Issue by FarazKhan** [appirio-tech/connect-app#3540]
### Expected behavior
Quality assurance project options should be similar to ones present in design
### Actual behavior
Quality assurance project options are different than ones specified in design
### Steps to reproduce the problem
1. Login to the app as co-pilot
2. Click on new project -> view solutions
3. Observe options available for quality assurance

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/2743246/73331628-67a4e000-428a-11ea-9312-2bb1471a87e5.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- User role (client, copilot or manager): copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: BugHunt, Functional, P1

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease

**Comment by FarazKhan** [comment]
@bug-hunt-helper remove label: Functional

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by FarazKhan** [comment]
@bug-hunt-helper remove label: UI

**Comment by SathyaJayabal** [comment]
Content issue
