### ISSUE TITLE
User is able to click on Show/Hide button even when it is disabled

### ISSUE THREAD

**Issue by varun22303270** [appirio-tech/connect-app#3541]
### Expected behavior
User should not be able to click on Show/Hide button when it is disabled

### Actual behavior
User is able to click on Show/Hide button even when it is disabled

### Steps to reproduce the problem
1. Go to https://connect.topcoder-dev.com/
2. Click on Login button
3. Click on Show button next to Password field and observe

### Screenshot/screencast
Attach or link a resource.
<img width="960" alt="error_screen" src="https://user-images.githubusercontent.com/7602356/73331740-d124ee80-428a-11ea-8d7c-4895fb681ef2.png">

--

#### Environment
- OS: Windows 10 x64
- Browser (w/version): Chrome Version 79.0.3945.130
- User role (client, copilot or manager):
- Account used:

**Comment by varun22303270** [comment]
@bug-hunt-helper add label: Functional

**Comment by SathyaJayabal** [comment]
@varun22303270 please apply all relevant labels

**Comment by varun22303270** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, P3

**Comment by SathyaJayabal** [comment]
Out of scope

**Comment by nithyaasworld** [comment]
It is 'As designed'. Lets re-open if needed.
