### ISSUE TITLE
SELECT BUDGET OR TALENT PROJECTS heading has dummy data

### ISSUE THREAD

**Issue by FarazKhan** [appirio-tech/connect-app#3542]
### Expected behavior
Application should have proper data
### Actual behavior
Application has dummy data.

### Steps to reproduce the problem
- Login to the app as co-pilot
- Click on new project -> on demand
- Observe data below 'SELECT BUDGET OR TALENT PROJECTS'

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/2743246/73332060-ac7d4680-428b-11ea-9fc2-f3cf22e16ecf.png)

--

#### Environment
- OS: windows 10
- Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- User role (client, copilot or manager): copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, FUnctional, P1

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by FarazKhan** [comment]
@bug-hunt-helper remove label: Functional

**Comment by FarazKhan** [comment]
@bug-hunt-helper add label: UI

**Comment by SathyaJayabal** [comment]
Content Issue
