### ISSUE TITLE
[Commom for all projects] UI issue on all the option buttons after user selected it

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3543]
![image](https://user-images.githubusercontent.com/42398485/73332542-a906a280-422c-11ea-99fa-ac19c6bc9111.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions
3. Click Real World Testing
4. Select an any option button from the 'Do you have test cases written?*'

**Actual:** UI issue on all the option buttons after user selected it

**Expected:** Should display the options button properly

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , what is the issue here. Can you please elaborate ?

**Comment by codejamtc** [comment]
@SathyaJayabal This is taken from IE11
![image](https://user-images.githubusercontent.com/42398485/73445594-a38a8480-4320-11ea-9849-fb7d07da1f7d.png)

The Blue dot inside the option button is not aligned properly

**Comment by SathyaJayabal** [comment]
@codejamtc , not a bug
