### ISSUE TITLE
Previous project name/Description are retained when user goes to another project

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3544]
https://www.screencast.com/t/UWZ1yic11

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions
3. Click Real World Testing
4. Enter all the details
5. Click Back
6. Click Performance Testing

**Actual:** Previous project name/Description are retained when user goes to another project

**Expected:** Should reset the data

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
This is expected behaviour. 
Ref https://github.com/appirio-tech/connect-app/issues/3472#issuecomment-579555191
