### ISSUE TITLE
Dummy Text found >> Solution Page 

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3545]
### Expected behavior
The readable text should be present.

### Actual behavior
Dummy unreadable text is present.

### Steps to reproduce the problem
- Login as Connect Manager.
-GO to the URL https://connect.topcoder-dev.com/new-project/scoped-solutions
- Go to the  APPLICATIONS & WEBSITES section and observe the small text appear below the header. 

### Screenshot/screencast
<img width="468" alt="Unreadable words  " src="https://user-images.githubusercontent.com/57211549/73333290-79d64c80-4291-11ea-8bbe-3e3ff9e9c1bd.png">

--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: Label UI, Label P3

**Comment by maxceem** [comment]
Hi @CreeyaSean to make the bot assign correct labels, please, add a new comment with the correct list of labels instead of editing the previous comment. `bug-hunt-helper` only works when a comment is added.

Thank you.

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by SathyaJayabal** [comment]
Content Issue
