### ISSUE TITLE
* symbol of the 'What do you need?' title UI issue

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3547]
![image](https://user-images.githubusercontent.com/42398485/73333809-91311d80-4230-11ea-9f4b-dc8ec72f5d1b.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions
3. Click '(User) Design, Development & Deployment' > Select
4. Fill required data > Next (App Definition)

**Actual:** * symbol of the 'What do you need?' title UI issue

**Expected:** Should display the required symbol near the text

**Environment:** Sony Xperia X Compact F5321 | Android_8.0
**Browser:** Google Chrome 79.0.3945.136

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
As per design.
