### ISSUE TITLE
Loader Issue - QA Service - Redirecting to incorrect page

### ISSUE THREAD

**Issue by Shabana3195** [appirio-tech/connect-app#3548]
### Expected behavior
User should get redirected to the Learn more page of each Topcoder's.

### Actual behavior
It is getting redirected to Connect App - My Project page.

### Steps to reproduce the problem
- Login Connect App.
- Click on 'New Project'
- Click on Solution
- Scroll down the page till 'QA Service.
- Link : https://connect.topcoder-dev.com/new-project/scoped-solutions
#### Environment
- OS: Windows
- Browser (w/version): Chrome: Version 79.0.3945.88 (Official Build) (64-bit) 
 Firefox: Version 71.0 (64-bit) Microsoft Edge 38.14393.2068.0
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by Shabana3195** [comment]
@bug-hunt-helper help: 

Can you please upload this screenshot:

![image](https://user-images.githubusercontent.com/60418973/73333947-4a274480-4291-11ea-94ed-92bffe804b4b.png)

And 

labels: Functional, P2.

**Comment by Shabana3195** [comment]
Hi :

Add label

@bug-hunt-helper add label: Functional, P2, BugHunt_JanRelease

Can you please upload this screenshot: As I'm unable to upload it

![image](https://user-images.githubusercontent.com/60418973/73333947-4a274480-4291-11ea-94ed-92bffe804b4b.png)

**Comment by SathyaJayabal** [comment]
@Shabana3195 accepted

**Comment by nithyaasworld** [comment]
Currently, Only 'Computer Vision' Category has 'Learn More' link which redirects to https://www.topcoder.com/case-studies/spacenet/.

As the initial issue is no more an issue, closing this.
