### ISSUE TITLE
Button clickable - nothing happens

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3549]
Expected behavior
Button should be clickable or something should happen

Actual behavior
Nothing is happening

Steps to reproduce the problem
Login to the app as Manager
Click on new project ->
Observe the button with lines in the screen shot
Screenshot/screencast

i
![Screen Shot 2020-01-29 at 12 14 16 PM](https://user-images.githubusercontent.com/57220292/73333887-2b28b280-4291-11ea-9889-0c0bdeb474b6.png)

--

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
Label - cant edit

BugHung_Janrelease
P3
Functional

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional,  P3

**Comment by SathyaJayabal** [comment]
Out of scope and as per design.
@akultalwar89 that button is to switch between list and grid views, and its currently selected.
