### ISSUE TITLE
Save Button is Inactive while the file is uploaded. 

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3551]
### Expected behavior
The save button should be active to proceed further.

### Actual behavior.
The Save button is still inactive.

### Steps to reproduce the problem
- login as manager
- click on project
- click on QA phase and Select specification
- drag and drop .txt file
- observe the save button.

### Screenshot/screencast
Attach or link a resource
![DIsable save button](https://user-images.githubusercontent.com/57211549/73333986-8360b400-4293-11ea-886b-eff498eec1a2.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version): Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

@bug-hunt-helper help
@bug-hunt-helper add label: Label Name Functional, Label Name P1

**Comment by SathyaJayabal** [comment]
@CreeyaSean Please use the comments section to add the labels and not the description.
Please update any of your other issues also with the correct label.

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
Out of scope

**Comment by nithyaasworld** [comment]
This is as designed.
