### ISSUE TITLE
Loader Issue - Redirecting to incorretct page - Analytics & Data Science

### ISSUE THREAD

**Issue by Shabana3195** [appirio-tech/connect-app#3552]
### Expected behavior
User should get redirected to the Learn more page of each Topcoder's.

### Actual behavior
It is getting redirected to Connect App - My Project page.

### Steps to reproduce the problem
- Login Connect App.
- Click on 'New Project'
- Click on Solution
- Scroll down the page till 'Analytics & Data Science'
- Link : https://connect.topcoder-dev.com/new-project/scoped-solutions
### Screenshot:

![image](https://user-images.githubusercontent.com/60418973/73334318-67a8de00-4292-11ea-962e-80f866c9b79d.png)

#### Environment
- OS: Windows
- Browser (w/version): Chrome: Version 79.0.3945.88 (Official Build) (64-bit) 
 Firefox: Version 71.0 (64-bit) Microsoft Edge 38.14393.2068.0
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by Shabana3195** [comment]
Hi :

Can you please add label

@bug-hunt-helper add label: Functional, P2, BugHunt_JanRelease

**Comment by SathyaJayabal** [comment]
@Shabana3195 , this will be combined with #3548 .

Closing this, will be tracked from #3548
