### ISSUE TITLE
esc test observed

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3553]
Expected behavior
esc Test should not be avialble 

Actual behavior
esc Test should not be avialble 

Steps to reproduce the problem
Go to App, 
Login using manager credential
Click on New project
Observe the X button

Screenshot/screencast
![Screen Shot 2020-01-29 at 12 26 50 PM](https://user-images.githubusercontent.com/57220292/73334465-c706ee00-4292-11ea-91a0-606198b33b33.png)

--

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
Esc test is observed in the top right with X sign.
Not a good way to show text. 

Label
Bughunt_JanRelease
P1
Functional

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 . As per design.

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  - hope you are doing well, I have never seen in an application where esc is written over a X sign. Dont you think it should be available over Hover or tool tip?

**Comment by SathyaJayabal** [comment]
<img width="1410" alt="Screenshot 2020-01-30 at 7 02 46 PM" src="https://user-images.githubusercontent.com/58783823/73453986-2815eb00-4393-11ea-9a90-ea0bb757cef4.png">

This is the design used. To have the word below the button. You can see it in this screen shot too.

**Comment by akultalwar89** [comment]
Thanks @SathyaJayabal  - esc text is not present in the Marvel App :) Can that be considered?

**Comment by SathyaJayabal** [comment]
@akultalwar89 , let me get back to you.

**Comment by SathyaJayabal** [comment]
@akultalwar89 , Sorry this is not a bug.

**Comment by akultalwar89** [comment]
No worries @SathyaJayabal  - Thanks for looking into it
