### ISSUE TITLE
Title Heading is missing >> On Demand

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3555]
### Expected behavior
The Header should be available for the user to read it.

### Actual behavior
The App name and description is available without the heading on it.

### Steps to reproduce the problem
- Login as Manager
- Go to the OnDemand detail page. 
- Select the Buy Capacity Option.
- Input the values in Name your project and Detail description Text box.
Go to the next page.

### Screenshot/screencast
Attach or link a resource.
<img width="858" alt="header missing" src="https://user-images.githubusercontent.com/57211549/73334724-91afcf80-4295-11ea-8b86-a1b4f7b858a3.png">

--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

@bug-hunt-helper help
@bug-hunt-helper add a label: Label Name Functional, Label Name P1

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
As per design.
