### ISSUE TITLE
Inconsistent Word in View Solution button compare to Marvel app design

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3559]
### Expected behavior
On Demand Detail button should be as "Create Project" as shown in Marvel app.

### Actual behavior
The Create Project is been seen as "View Solution".

### Steps to reproduce the problem
- Login as Manager.
- Click on Create New Project..
- Observe the button under On-demand section and compare with Marvel app design..

### Screenshot/screencast
Attach or link a resource.
<img width="1292" alt="Ondemand inconsistency" src="https://user-images.githubusercontent.com/57211549/73335134-9cb72f80-4296-11ea-9a57-22913f5f043f.png">

--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

@bug-hunt-helper help
@bug-hunt-helper add label: Label Name UI, Label Name P1

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by SathyaJayabal** [comment]
Content issue
