### ISSUE TITLE
Text overlapping on All project page

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3561]
Expected behavior
Text shouldnot over lap, even image is overlapping

Actual behavior
text and image overlapping

Steps to reproduce the problem
Login to the app as Manager
Click on  All project ->
Observe the Text overlapping

screenshot
![Screen Shot 2020-01-29 at 12 50 17 PM](https://user-images.githubusercontent.com/57220292/73335714-23b7d800-4296-11ea-941d-289e8d2a7ae3.png)

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 out of scope and existing issue

closing this, will be tracked in #3637
