### ISSUE TITLE
Copilot Notification didnot popup.

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3563]
### Expected behavior
The copilot should get the notification once he gets invited to the project.

### Actual behavior
Copilot didn't get the notification after inviting to the project.

### Steps to reproduce the problem
- Login as manager
- select a project
- click on manage in the left nav bar
- add copilot and send an invite
- login as copilot and click on the notification bell icon
- observe the notification thread

### Screenshot/screencast
Attach or link a resource.
![verification 1](https://user-images.githubusercontent.com/57211549/73335715-3df2b580-4298-11ea-8a94-e8c566e64700.png)
![bug_2 no notification to copilot for invited project](https://user-images.githubusercontent.com/57211549/73335716-3df2b580-4298-11ea-9d85-475bda663c34.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version): 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: opcoderconnect+Manager@gmail.com

@bug-hunt-helper help
@bug-hunt-helper add label: Label Name Functional, Label Name P1

**Comment by CreeyaSean** [comment]
> The copilot should get the notification once he gets invited to the project.

@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@CreeyaSean , out of scope

**Comment by SathyaJayabal** [comment]
closing. as per design
