### ISSUE TITLE
Server error 500 > While creating a project using long project name and description

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3564]
![image](https://user-images.githubusercontent.com/42398485/73335774-e28fdb80-4235-11ea-87d4-6f3ce61c627c.png)

https://www.screencast.com/t/GkuuGsJjYln

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions
3. Click 'Data Visualization' > Select
4. Enter long text to the Name and Description
5. Fill all the other textboxes with long texts
6. Create the project

**Actual:** Server error 500 > While creating a project using long project name and description

**Expected:** Should enforce a char limit for the fields

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@codejamtc , can you please upload a video of this issue

**Comment by codejamtc** [comment]
@SathyaJayabal This is a common issue for all the projects. Here is the video https://www.screencast.com/t/PqT8RFz56m

[Log.txt](https://github.com/appirio-tech/connect-app/files/4127780/Log.txt)

**Comment by SathyaJayabal** [comment]
@codejamtc , Thank you for the video

**Comment by SathyaJayabal** [comment]
@codejamtc , This issues was already reported here #3562 

Closing as this will be tracked in #3562
