### ISSUE TITLE
Save My Project - Unable to click the button

### ISSUE THREAD

**Issue by Shabana3195** [appirio-tech/connect-app#3565]
### Expected behavior
User should able to save the save the project after clicking on 'Save my project'.

### Actual behavior
Unable to save the project

### Steps to reproduce the problem

- Login Connect App.
- Click on 'New Project'
- Click on On Demand
- Enter the fields displayed
- Click on next
- Select Quality Assurance and click on next
- Select the budget capacity and click on next
- Click on 'Save my project'

### Screenshot: 

![image](https://user-images.githubusercontent.com/60418973/73335673-0d118100-4296-11ea-89cd-46a0559f1476.png)

#### Environment

- OS: Windows
- Browser (w/version): Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
- Firefox: Version 71.0 (64-bit) Microsoft Edge 38.14393.2068.0
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by Shabana3195** [comment]
@bug-hunt-helper add label: Functional, P1, BugHunt_JanRelease

**Comment by SathyaJayabal** [comment]
@Shabana3195 please add a video of the behaviour.

**Comment by vikasrohit** [comment]
@SathyaJayabal it is working for me, following the exact same steps.

**Comment by SathyaJayabal** [comment]
@vikasrohit , I could reproduce it. Let me post a video

**Comment by SathyaJayabal** [comment]
[save project.mov.zip](https://github.com/appirio-tech/connect-app/files/4127701/save.project.mov.zip)

**Comment by SathyaJayabal** [comment]
@vikasrohit , It happens when you enter a number more than hundred in the Budget capacity field in the previous screen.

**Comment by vikasrohit** [comment]
Ohk, that means it is  a validation error and the button should be disabled but somehow it is looking enabled while actually being disabled.

fyi @maxceem

**Comment by vikasrohit** [comment]
Reducing the severity as it is happening only for bad data and does not appear to be because of recent changes.

**Comment by SathyaJayabal** [comment]
@Shabana3195 , accepted

**Comment by lakshmiathreya** [comment]
Not relevant with the current design.
