### ISSUE TITLE
[$10] [Common to all projects] Title and Description UI issue

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3568]
![image](https://user-images.githubusercontent.com/42398485/73336595-d6a51900-4237-11ea-84ac-183144626362.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Click 'Performance Testing' > Select
4. Enter 'dasdasdsadasdasdafsdfdsdsgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg' for all 3 fields
5. Click Next

**Actual:** Title and Description UI issue

**Expected:** Should trim the long text

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc accepted

**Comment by lakshmiathreya** [comment]
Long names need to be wrapped around. Issue seen currently.

**Comment by vikasrohit** [comment]
@maxceem candidate for CF

**Comment by maxceem** [comment]
Sum up:
- Long strings should be wrapped to the next lines without cut.

**Comment by iversonLv** [comment]
@maxceem Can I take this?
Thanks.

**Comment by iversonLv** [comment]
@bug-bash-helper assign

**Comment by iversonLv** [comment]
Fixed image:  
Which do you want?  
This is break-all, so the long word will break at last    
![image](https://user-images.githubusercontent.com/4952611/76300712-2b888480-62f8-11ea-9a86-10a8ffb64ab2.png)

This is break-word, so the long word will first break into 2nd line as there is no enough place for it to stay at 1st line, also, it will still break at last, notice it breaks into 3rd line as well  
![image](https://user-images.githubusercontent.com/4952611/76300645-08f66b80-62f8-11ea-9568-afc3182a4a76.png)

**Comment by iversonLv** [comment]
@maxceem

**Comment by maxceem** [comment]
@iversonLv first one with `break-all`

**Comment by maxceem** [comment]
Sorry, @iversonLv let's use the second one better with `break-word`.

**Comment by iversonLv** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3759 is ready for review

**Comment by drasticdpk** [comment]
Verified on Dev Env :
![image](https://user-images.githubusercontent.com/25297859/76508231-29e4cb00-6476-11ea-9d77-b92a3e1c21ee.png)

**Comment by satkanhub** [comment]
Working as expected. Video for reference

[3568.zip](https://github.com/appirio-tech/connect-app/files/4326747/3568.zip)

**Comment by codejamtc** [comment]
https://monosnap.com/file/9JpJ6Cx0986iu9h7gLRVqLot1mYVc5

**Comment by lakshmiathreya** [comment]
Title wrapping doesnt work when Project Title has no separators: 
<img width="1467" alt="Screenshot 2020-07-29 at 6 46 09 PM" src="https://user-images.githubusercontent.com/51733042/88806812-8569e800-d1ce-11ea-82a5-57f6cf52957f.png">

Wrapping has been fixed as mentioned earlier and works when there is hyphen separator between words in the Title:
<img width="1471" alt="Screenshot 2020-07-29 at 6 47 58 PM" src="https://user-images.githubusercontent.com/51733042/88806888-a6323d80-d1ce-11ea-8bde-7efa2497b84f.png">

**Comment by maxceem** [comment]
Case with underscore https://github.com/appirio-tech/connect-app/issues/3568#issuecomment-665669128
Fixed by 894ce6abfab64a33398cb69ba2a00d32ba2d9fa4

**Comment by drasticdpk** [comment]
Prod verified. 

![image](https://user-images.githubusercontent.com/25297859/103527934-345fcd80-4eab-11eb-85d5-e1514e753795.png)
