### ISSUE TITLE
headings should be aligned in one line

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3569]
Expected behavior
Alignment issue on Project Table

Actual behavior
Alignment Issue is seen

Steps to reproduce the problem
Login to the app as Manager
Click on All project ->
Observe the text alignment

### Screenshot/screencast
![Screen Shot 2020-01-29 at 1 06 06 PM](https://user-images.githubusercontent.com/57220292/73336621-4e0a9500-4298-11ea-9b6a-1991ff9a23d0.png)
![Screen Shot 2020-01-29 at 1 07 36 PM](https://user-images.githubusercontent.com/57220292/73336670-709cae00-4298-11ea-84e9-ad994ec03f54.png)

--

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 out of scope

**Comment by nithyaasworld** [comment]
This issue is fixed via another ticket.

![image](https://user-images.githubusercontent.com/5114190/73626066-7960fb80-466d-11ea-8123-61c5aa9399a9.png)
