### ISSUE TITLE
 selecting device as  Phone , displaying  text on dashboard as Iphone 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#357]
### Expected behavior
Should displayed Phone or ios, Android & Hybrid
### Actual behavior
Showing only Ios

### Steps to reproduce the problem
1. open the Application
2. Login with copilot :cp-superstar
3.  create new project
4. Pick Phone as device
5. Redirect to Dashboard
6. on dashboard dispalying only phone text
### Screenshot/screencast
Attach or link a resource.

--
![image](https://cloud.githubusercontent.com/assets/16131461/18963239/b73fa892-8691-11e6-8f15-92017c9cadea.png)

![image](https://cloud.githubusercontent.com/assets/16131461/18963257/c683237e-8691-11e6-9bc6-6e470be112a1.png)

#### Environment
- OS: windows 7
- Browser (w/version): chrome latest
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
Valid.

**Comment by vikasrohit** [comment]
Parth fixed it with #362
