### ISSUE TITLE
Skill dropdown is partially hidden

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3571]
![image](https://user-images.githubusercontent.com/42398485/73337468-01906c80-423a-11ea-84c0-60ddb9976025.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Engage Talent
3. Go to 'Your Talent Requirements'
4. Click on 'What skills are important for your team to have?*' field

**Actual:** Skill dropdown is partially hidden

**Expected:** Should open the dropdown upwards so that user can see more data in the dropdown

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , As per design. The scroll bar can be used to view more data.

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by lakshmiathreya** [comment]
Works fine on MacOS and iOS. @SathyaJayabal pls verify on Win/IE.

**Comment by SathyaJayabal** [comment]
Scroll bar can be used to access the drop down items.
