### ISSUE TITLE
The Text is getting overlap in Oldest first filter option.

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3572]
### Expected behavior
The am/pm should display properly.

### Actual behavior
The am/pm has been overlapped. .

### Steps to reproduce the problem
- login as Copilot Manager
- Create new Project. .
- GO to the Project List.
- Click the Oldest First Filter and observe 

### Screenshot/screencast
Attach or link a resource.
![overlap2](https://user-images.githubusercontent.com/57211549/73337311-24536d00-429c-11ea-88ef-8280caeae4fe.png)
![overlap1](https://user-images.githubusercontent.com/57211549/73337312-24536d00-429c-11ea-97f7-f7c4e1d33d5e.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version): 79.0.3945.130 (Official)
- User role (client, copilot or manager): Copilot-Manager
- Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by SathyaJayabal** [comment]
@CreeyaSean . Out of scope.
