### ISSUE TITLE
UI issue in the 'I'm not using anything, but would love a recommendation' answer

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3573]
![image](https://user-images.githubusercontent.com/42398485/73338180-a2cbf280-423b-11ea-807e-28d0d8deecd0.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Engage Talent
3. Go to 'Are you using a specific tool to manage work?*' > 'I'm not using anything, but would love a recommendation' answer

**Actual:** UI issue in the 'I'm not using anything, but would love a recommendation' answer

**Expected:** Checkbox and text should display in a single row

**Environment:** Sony Xperia X Compact F5321 | Android_8.0
**Browser:** Google Chrome 79.0.3945.136

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by SathyaJayabal** [comment]
Happens with all checkboxes

**Comment by codejamtc** [comment]
![B1](https://user-images.githubusercontent.com/42398485/73505437-213da700-4398-11ea-8115-dd811b528eac.png)
![B2](https://user-images.githubusercontent.com/42398485/73505438-213da700-4398-11ea-9d0e-588dc1c805f1.png)
@SathyaJayabal

**Comment by SathyaJayabal** [comment]
@codejamtc , thank you for the screenshots
