### ISSUE TITLE
Icons overlapping with Text, It should only show icons instead of text

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3574]
Expected behavior
View All projects - Last Updated should not overlap with comments, should be over it

Actual behavior
Overlapping with other tiles or headings

Steps to reproduce the problem
Login to the app as Manager
Click on All project ->
Click on Last Updated 
It overlaps the tiles.

Screenshot - 
![Screen Shot 2020-01-29 at 1 37 03 PM](https://user-images.githubusercontent.com/57220292/73338490-b6f40c00-429c-11ea-8654-d275dfff4d0c.png)

Environment -
Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional,

**Comment by SathyaJayabal** [comment]
@akultalwar89 , out of scope

**Comment by nithyaasworld** [comment]
Confirming that this issue is seen in smaller screens.
