### ISSUE TITLE
Inlined SVG files got broken (empty, blank)

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3575]
Follow up from https://github.com/appirio-tech/connect-app/issues/3407#issuecomment-579529858 issue number 2.

If SVG file uses ids for `mask` and/or for `defs` such ids may get collied because SVG files are inlined and ids inside SVGs are global for the whole HTML.

For example, we have an issue that the same icon first time is shown good:

![image](https://user-images.githubusercontent.com/146016/73338162-f2003a80-42b0-11ea-8185-781bde18ba18.png)

But the next times it's shown blank (broken):

![image](https://user-images.githubusercontent.com/146016/73338205-0ba18200-42b1-11ea-9baa-9f2d8bbfad98.png)

Here are related issues found on the internet:
- https://github.com/gregberge/svgr/issues/150
- https://github.com/gregberge/svgr/issues/152

Workarounds from these issues don't help us, unfortunately. So the only working solution was to edit the code of SVG file manually, so it doesn't use ids and masks.

We may still come across such issues in the future, as so far the solution may be applied only per SVG files that have such an issue. Probably, we can also ask designers to provide SVG files without masks if possible.

**Comment by maxceem** [comment]
This is actually a part of https://github.com/appirio-tech/connect-app/issues/3407#issuecomment-579529858.
I've logged this issue separately, so it would be easier to find it if we have similar issues in the future.

**Comment by RishiRajSahu** [comment]
@maxceem good research ! :+1:

**Comment by vikasrohit** [comment]
Closing. Please feel free to create new issues for any regression.

**Comment by chaitanya71998** [comment]
make your fill using ids unique, in the svg component, so that react will render each svg component
