### ISSUE TITLE
[$15] Esc button is hidden blocking it's functionality.

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3576]
### Expected behavior
Ecs button should be seen and should function well.

### Actual behavior
The esc button is hidden and not letting to click on it..

### Steps to reproduce the problem
- Login and Manager.
- GO to the OnDemand detail page. 
- Add the required field to create a project. 
- GO to Project Dashboard.
-  Click on Add New Phase under Dev Iteration. 
- Observe the esc button placement.

### Screenshot/screencast
Attach or link a resource.
<img width="1309" alt="Button hidden" src="https://user-images.githubusercontent.com/57211549/73338427-af356700-429e-11ea-98fd-4b77933a5c41.png">

--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@CreeyaSean , out of scope

**Comment by nithyaasworld** [comment]
Expecting https://github.com/appirio-tech/connect-app/issues/3577 also to get fixed as part of this ticket's fix.

**Comment by codejamtc** [comment]
@maxceem @vikasrohit I can still reproduce this issue

![image](https://user-images.githubusercontent.com/42398485/78958680-72f86100-7aae-11ea-9c32-8e25787fb2dc.png)

**Comment by maxceem** [comment]
Sum up:
- use user `pshah_manger`
- got to project https://connect.topcoder-dev.com/projects/9093 and click `Add phase` - observer that buttons are cut
- fix this issue carefully, and make sure the fix doesn't break other places, for example:
  - Create new project pages https://connect.topcoder-dev.com/new-project/
- check that mobile size is not broken

**Comment by sjbr** [comment]
@bug-bash-helper assign

**Comment by sjbr** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3913 is ready for review

**Comment by coderhacker** [comment]
QA Comment: The issue has been fixed and working in all browsers in dev env.
https://connect.topcoder-dev.com/new-project/app_new_intake
User login: topcoderconnect+Customer/appirio123
topcoderconnect+AccountManager/appirio123
topcoderconnect+Copilot/appirio123
topcoderconnect+Manager/appirio123
topcoderconnect+CopilotManager/appirio123
topcoderconnect+bdr/appirio123
topcoderconnect+Customer/appirio123
topcoderconnect+Observer/appirio123

Chrome: 
![image](https://user-images.githubusercontent.com/62358241/79837233-bae08780-83ce-11ea-9706-8865357177f9.png)

Firefox: 
![image](https://user-images.githubusercontent.com/62358241/79837155-a9977b00-83ce-11ea-9b33-b6ce83086e35.png)

Edge:
![image](https://user-images.githubusercontent.com/62358241/79837270-c633b300-83ce-11ea-9a5e-f1be2d7327a4.png)

**Comment by drasticdpk** [comment]
Verified on Prod evn.
