### ISSUE TITLE
Connect Home button is not visible clearly and the logo is missing.

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3577]
Expected behavior
connect logo Home button should be visible with it's logo.

Actual behavior
The connect home button is hidden and the logo is not seen.

Steps to reproduce the problem
- Login and Manager.
- GO to the OnDemand detail page.
- Add the required field to create a project.
- GO to Project Dashboard.
- Click on Add New Phase under Dev Iteration.
- Observe the connect home button placement.

### Screenshot/screencast
Attach or link a resource.
<img width="946" alt="connect hidden" src="https://user-images.githubusercontent.com/57211549/73339060-ff60f900-429f-11ea-80c8-e0e9c2bd786d.png">
--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment]
@CreeyaSean , out of scope

**Comment by nithyaasworld** [comment]
Same as https://github.com/appirio-tech/connect-app/issues/3576
