### ISSUE TITLE
Project Details are copied over to Application/Website as well

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3578]
Expected behavior
project details entered should not get copied in Application website details

### Actual behavior
It is copying everything written in project name, description to Application websites as well..

Steps to reproduce the problem
Create a new project
select  View solution
Enter Project details in any option
click back, Scroll down to the applications/websites .
Observe the text writted in projects are seen in name and other fields here as well.

Screenshot/screencast
![Screen Shot 2020-01-29 at 1 57 29 PM](https://user-images.githubusercontent.com/57220292/73339722-5914f380-429f-11ea-9fab-074cb6fc41ee.png)

--

Environment
Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 As per design. 

https://github.com/appirio-tech/connect-app/issues/3472#issuecomment-579555191

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  - But here the template is different - I checked test case 34721-  It says on the same template - 
One is On demand and one is solution-

If i add project name and description in on demand - it is getting replicated in other template in Solutions as well. they both are different.

**Comment by SathyaJayabal** [comment]
@akultalwar89 , the requirement is to copy the name and description across all templates.

**Comment by akultalwar89** [comment]
@SathyaJayabal  - slightly confusing :) maybe because i am not very clear with the project details. 

I thought - We have two separate Wizards - 
Like on demand and solutions - 
As on demand has internal templates and 
Solutions have different templates

If i fill project detaails oin any template in On demand - It should not be copied on Solution Template - 
Just my point of view- 
Rest its all how project demands it :)
![Screen Shot 2020-01-30 at 10 50 43 PM](https://user-images.githubusercontent.com/57220292/73473764-54416400-43b3-11ea-84ab-db71d9881ac1.png)
