### ISSUE TITLE
Copy links/Go to project dashboard buttons are too close to the bottom border

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3579]
![1](https://user-images.githubusercontent.com/42398485/73340405-4919f700-4240-11ea-9799-a7a8adda76e9.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Engage Talent
3. Fill all the mandatory data > Create a Project

**Actual:** Copy links/Go to project dashboard buttons are too close to the bottom border

**Expected:** Should have small padding from the bottom

**Environment:** iPhonr 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc accepted
