### ISSUE TITLE
'How many test cases do you need?*' question is displayed even though user didn't select anything from the 'What do you need us to help you with?*'

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3581]
![image](https://user-images.githubusercontent.com/42398485/73340983-54b9ed80-4241-11ea-9948-7dce44181279.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > QA Services
3. Click Next
4. Select 'Structured Testing (Test Case Creation and/or Execution)'
5. Check the last question

**Actual:** 'How many test cases do you need?*' question is displayed even though user didn't select anything from the 'What do you need us to help you with?*'

**Expected:** Should display the 'How many test cases do you need?' question if user select an answer to the above question

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
