### ISSUE TITLE
Button Save Changes disable after the file is uploaded  in the Specification tab. 

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3582]
### Expected behavior
Describe.

### Actual behavior
"Save changes" button is still disable even after the file has been uploaded. .

### Steps to reproduce the problem
- Login and Manager.
- GO to the OnDemand detail page.
- Add the required field to create a project.
- GO to Project Dashboard.
- Click on Add New Phase under Dev Iteration.
- Go to the Specification Tab. 
- Upload the file in the by drag and drop. 
- Observe the Save Changes button. 

### Screenshot/screencast
Attach or link a resource.
<img width="931" alt="save changes function" src="https://user-images.githubusercontent.com/57211549/73342172-202c4d00-42a6-11ea-9cb7-0fe5a28e8f7f.png">

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by CreeyaSean** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@CreeyaSean , out of scope

**Comment by nithyaasworld** [comment]
As designed.
