### ISSUE TITLE
Structured Testing > Test Case creation project timeline dates are not visible

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3583]
![image](https://user-images.githubusercontent.com/42398485/73342559-6fda2c80-4244-11ea-95de-50e4820b6560.png)

https://www.screencast.com/t/rP7ArMAe

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > QA Services
3. Click Next
4. Select Structured Testing > Test Case Execution > Up to 150 test cases
5. Click Next
6. Select mandatory data > Next > Next
7. Expand the Work Required field > Deselect 'Test Case execution' and select 'Test Case creation'

**Actual:** Structured Testing > Test Case creation project timeline dates are not visible

**Expected:** Should display as 3-6 days

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by nithyaasworld** [comment]
Project timeline is no more shown for the 'QA Services'

![image](https://user-images.githubusercontent.com/5114190/75329687-0f232b80-58a6-11ea-85e8-dd973904130b.png)
