### ISSUE TITLE
User can go to the next page without selecting an answer to the 'How many test cases do you need?*'

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3584]
![image](https://user-images.githubusercontent.com/42398485/73343009-6604f900-4245-11ea-8439-04e3a92d8561.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > QA Services
3. Click Next
4. Select Structured Testing > Test Case Execution > Up to 150 test cases
5. Click Next
6. Expand the 'Work Required' field > Deselect 'Test Case Execution' and select 'Test Case Creation'
7. Click Back (You can see 'How many test cases do you need?*' selection is removed because 'Test Case Creation' won't have 150 test cases option
8. Don't select anything > click Next
9. Check the 'Test Case/Screen Count value = 150 (It is incorrect because there is no option for 150, only 50 and 100 are there)

**Actual:** User can go to the next page without selecting an answer to the 'How many test cases do you need?*'

**Expected:** Should validate the answer

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by nithyaasworld** [comment]
Not able to reproduce with the updated catalog UI

**Comment by nithyaasworld** [comment]
... as the updated UI has no difference for 'Test Case Creation and Execution'.
