### ISSUE TITLE
Error: performUpdateIfNecessary: Unexpected batch number (current 1345, pending 1321)

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#359]
Expected behavior
------------------------------------------------------------

- The error message is displayed in console.

Actual behavior
------------------------------------------------------------

- Do not display this error message in console.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Edit any existing own project.

- Select Specification.

- Go to Project Features section.

- Check Email Login, Camera (Audio & Video).

- Open Firebug tool and check the errors.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![test1](https://cloud.githubusercontent.com/assets/5114907/18963717/bd927598-867e-11e6-8177-d0ef57861c05.png)

**Comment by mahestro** [comment]
Valid.

**Comment by vikasrohit** [comment]
Not able to reproduce after changes for #125
