### ISSUE TITLE
'What is right for me?' popup window has a scrollbar

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3590]
![image](https://user-images.githubusercontent.com/42398485/73344420-f6dcd400-4247-11ea-94d2-88b249cae0e5.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > QA Services (23-08-2019)
3. Fill all the mandatory fields > Next 
4. Click 'What is right for me?'

**Actual:** 'What is right for me?' popup window has a scrollbar

**Expected:** No need of a scrollbar

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc accepted,
