### ISSUE TITLE
[Common - Whole app] Delete icon used to collapse the expanded field is not displayed

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3591]
![image](https://user-images.githubusercontent.com/42398485/73344900-b6ca2100-4248-11ea-8973-54f17efdb041.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > QA Services (23-08-2019)
3. Fill all the mandatory fields > Next 
4. Fill all the mandatory fields > Next
5. Expand a collapsed field

**Actual:** Delete icon used to collapse the expanded field is not displayed

**Expected:** Should display the field collapse button

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by SathyaJayabal** [comment]
Please also fix #3665
