### ISSUE TITLE
Solution and On Demand  have buttons with different text from the design

### ISSUE THREAD

**Issue by kalindipandey** [appirio-tech/connect-app#3593]
### Expected behavior
The text on the button below the Solutions and On-Demand tabs should be same
[](https://marvelapp.com/cc9e4j1/screen/65344038)
### Actual behavior
The text on the button below the Solutions and On-Demand tabs is different
### Steps to reproduce the problem
1. Open the Application and Login as a valid user (Copilot)
2. Go to Dashboard > All Projects
3. Click on "+ New Project"

### Screenshot/screencast
![bug 1](https://user-images.githubusercontent.com/46349625/73346215-7f409080-42ab-11ea-84fa-690670c6a847.jpg)

--

#### Environment
- OS: micromax LI351568W ; Windows10
- Browser (w/version): Chrome Version 79.0.3945.130
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by kalindipandey** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by SathyaJayabal** [comment]
@kalindipandey , content issue. not in scope
