### ISSUE TITLE
Please answer text area content not fully visible

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3595]
### Expected behavior
Text area content should be visible

### Actual behavior
Text area content not fully visible

### Steps to reproduce the problem
1. Open the Application and Login as valid user (Manager)
2.  All project > Please answer a few basic questions about your project and, as an option, add links to supporting documents in the “Notes” section. If you have any files to upload, you’ll be able to do so later > read more 
3. Observe the Please answer text area

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73347092-03dfde80-42ad-11ea-8bc5-0563e6f41013.png)

#### Environment
- OS: Windows 10
- Browser (w/version): Chrome 79.0.3945.130
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by SathyaJayabal** [comment]
@Krishna1507 , as per design. The input si for reference code and is not expected to be long.
