### ISSUE TITLE
"Expected Deliverables" and "Learn More" are missing from some solution list and available in some; Not the same as the design

### ISSUE THREAD

**Issue by kalindipandey** [appirio-tech/connect-app#3597]
### Expected behavior
There should be consistent behavior and should be the same as the design. "Expected Deliverables" and "Learn More"  should be there in each solution.

### Actual behavior
"Expected Deliverables" and "Learn More" are missing from some of the solutions options.

### Steps to reproduce the problem
1. Open the application
2. Login as copilot
3. Click on "+New Project"
4. Click on "View Solutions" in the Solutions option
5. Scroll down to see in some cards "Expected Deliverables" and "Learn more" is present while it is 
    not present in other cards

### Screenshot/screencast
![Bug2](https://user-images.githubusercontent.com/46349625/73351010-2295a380-42b4-11ea-9e46-80de793c89d9.jpg)
--

#### Environment
- OS: micromax LI351568W ; Windows10
- Browser (w/version):  Chrome Version 79.0.3945.130
- User role (client, copilot or manager):  copilot
- Account used:  topcoderconnect+Copilot@gmail.com

**Comment by kalindipandey** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@kalindipandey , content issue.
