### ISSUE TITLE
Back button redirect to the main page rather than redirected page

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3598]
### Expected behavior
Back should go to the same tab from where we select

### Actual behavior
Back button redirects to the default page

### Steps to reproduce the problem
- 1. Open the Application and Login as valid user (CopilotManager)
- 2.  New Project > view Solution > ANALYTICS & DATA SCIENCE
- 3.  Tap on select of Data Visualization
- 4.  Tap on back button and observe its redirect to All solution page

### Screenshot/screencast
https://drive.google.com/open?id=14MxfYyX8_ax4k42qOBrt24Fda0rKl4Fi

#### Environment
- OS: Windows 10
- Browser (w/version): Chrome Version 79.0.3945.130
- User role (client, copilot or manager): CopilotManager
- Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@Krishna1507 as per design
