### ISSUE TITLE
"Lorem Ipsum" text under the Header "SELECT BUDGET OR TALENT PROJECTS"

### ISSUE THREAD

**Issue by kalindipandey** [appirio-tech/connect-app#3599]
### Expected behavior
There should be proper text instead of Lorem Ipsum text for placeholders
### Actual behavior
"Lorem Ipsum" text is present below the header

### Steps to reproduce the problem
1. Open the application
2. Login as copilot
3. Click on "+New Project"
4. Click on "View Solutions" in the "On Demand" option
5. Check the text below the header "SELECT BUDGET OR TALENT PROJECTS"
### Screenshot/screencast
![Bug3](https://user-images.githubusercontent.com/46349625/73352419-14955200-42b7-11ea-9dd6-82d3382e671d.jpg)

--

#### Environment
- OS:  micromax LI351568W ; Windows10
- Browser (w/version):  Chrome Version 79.0.3945.130
- User role (client, copilot or manager):  copilot
- Account used:  topcoderconnect+Copilot@gmail.com

**Comment by kalindipandey** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@kalindipandey content issue.
