### ISSUE TITLE
Even though user clear the username from the textbox using (x) button, Can add the user by clicking the ADD button

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#360]
### Expected behavior

---

Must validate the field before entering the user
### Actual behavior

---

Even though user clear the username from the textbox using (x) button, Can add the user by clicking the ADD button
### Steps to reproduce the problem

---
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Dashboard
- Click Add New team member
- Select a user
- Click (x) clear button
- Click ADD
### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section)

---

![2016-09-29_22-25-36](https://cloud.githubusercontent.com/assets/4592712/18963790/f6cc9298-8693-11e6-9dc1-3d158f382cc4.png)
### Environment

---
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid (win).

**Comment by fnisen** [comment]
@vikasrohit this issue comes up in Win 7/IE 11. Can you please run a challenge to handle the browser "X" action to fully clear the form?

**Comment by vikasrohit** [comment]
@fnisen I guess it is the same reason which caused troubles with project creation form as well. We can simply remove the X button in IE11 which should be a quick fix.

**Comment by fnisen** [comment]
👍  thank you.

**Comment by vikasrohit** [comment]
@fnisen Haven't fixed the issue yet. 😬 Will do that today.

**Comment by vikasrohit** [comment]
Done now. :)

**Comment by fnisen** [comment]
Working well--thanks!
