### ISSUE TITLE
Pop up box text alignment is not poper

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3600]
### Expected behavior
Text alignment should be proper

### Actual behavior
Popup text alignment is not proper

### Steps to reproduce the problem
- 1. Open the Application and Login as valid user (Manager)
- 2.  Go to Data Visualization tab > select 
- 3. Traverse till where we find text box with header "What will qualify this data visualization project as a success for you?"
-4. Click on the 'What are common success indicators?' link and observer the text alignment

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73353204-e0bb2c00-42b8-11ea-93ed-cb987bde1b36.png)

#### Environment
- OS: Windows 10
- Browser (w/version): Chrome Version 79.0.3945.130
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment]
@Krishna1507 , duplicate #3558
