### ISSUE TITLE
Topcoder logo is moving when traverse over the tabs

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3602]
### Expected behavior
Logo should be fixed

### Actual behavior
Logo is moving while traversing over tab

### Steps to reproduce the problem
-  Open the Application and Login as the valid user (Manager)
-   Click New Project > View solution
-   Tap on the available options (All Solutions, Quality Assurance, Applications & Websites, Analytics & Data Science)
-   Observe the logo

### Screenshot/screencast
https://drive.google.com/open?id=12cFGfCdlLC8sfEp4v35_iQkMF5bvj0N-

#### Environment
- OS: Windows 10
- Browser (w/version): IE 11/ 11.592.18362.0
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@Krishna1507 , Related to #3601
