### ISSUE TITLE
Prepaid budget increment/decrement selector missing in IE11

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3605]
### Expected behavior
Increment icon should be available

### Actual behavior
No increment/decrement selector found 

### Steps to reproduce the problem
- Open the Application and Login as valid user (Manager).
- Click + New Project > On Demand >Buy Capacity.
-  Observe purchase text box 

### Screenshot/screencast
IE11- 
![image](https://user-images.githubusercontent.com/23450398/73360872-d05f7d00-42c9-11ea-959b-909a82589ff9.png)

Firefox:-
![image](https://user-images.githubusercontent.com/23450398/73360911-e2412000-42c9-11ea-9e03-034f9eb206e9.png)

#### Environment
- OS: Windows 10
- Browser (w/version): IE11 
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@Krishna1507 , accepted
