### ISSUE TITLE
Purchase budget capacity textbox accepting string value

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3606]
### Expected behavior
Budget capacity text box must be accepted only integer value

### Actual behavior
Budget capacity text box accept char.

### Steps to reproduce the problem
- Open the Application and Login as valid user (Manager).
- Click + New Project > On Demand >Buy Capacity.
-  Enter char and integer is accepted.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73361241-9347ba80-42ca-11ea-95b1-0738e50eea25.png)

#### Environment
- OS: Windows 10
- Browser (w/version): IE11
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@Krishna1507 , accepted.

**Comment by nithyaasworld** [comment]
@maxceem The screen described in the bug has been removed in the New Catalog. However I am able to navigate to the above screen using the URL (https://connect.topcoder-dev.com/new-project/prepaid_budget) and still reproduce this issue. 

Should we remove the URL-navigation as well or that is okay?
