### ISSUE TITLE
Clearing the numeric fields and click next will automatically assign 1 to that field

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3607]
![image](https://user-images.githubusercontent.com/42398485/73362300-3b7a6680-426c-11ea-9e21-b10d1fb5803d.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Fill all the mandatory fields > Next 
4. Select all the options > Next
5. Enter numbers to the numeric fields 
6. Click clear button of one of the field >Next

**Actual:** Clearing the numeric fields and click next will automatically assign 1 to that field

**Expected:** Should validate the field. Should not assign 1 automatically

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@codejamtc , as per design
