### ISSUE TITLE
[Web-Chrome] Cancelled & Paused Are Overlapping REF Dropdown

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3608]
### Expected behavior
Cancelled & Paused Should Not Overlap

### Actual behavior
Cancelled & Paused Are Overlapping REF Dropdown

### Steps to reproduce the problem
1. Login With Credential topcoderconnect+Copilot@gmail.com

2. Click On More.

3. See Screencast & Screenshot Then Observe.

### Screenshot/screencast
[Cancelled & Paused.mp4.zip](https://github.com/appirio-tech/connect-app/files/4128372/Cancelled.Paused.mp4.zip)
[Cancelled & Paused.png.zip](https://github.com/appirio-tech/connect-app/files/4128377/Cancelled.Paused.png.zip)

--

#### Environment
- OS: 
[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4128387/Mac.Version.png.zip)

- Browser (w/version):
[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4128391/Chrome.Version.png.zip)

- User role (client, copilot or manager): Copilot
- Account used:  topcoderconnect+Copilot@gmail.com

**Comment by devsreekrishna** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@devsreekrishna , out of scope
