### ISSUE TITLE
Can submit the project without entering any values to the 'budget' fields

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3609]
https://www.screencast.com/t/CE6ifggyi5
![image](https://user-images.githubusercontent.com/42398485/73363153-c576ff00-426d-11ea-81e3-10a00b456b51.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Fill all the mandatory fields > Next 
4. Select all the options > Next
5. Enter numbers to the numeric fields > Next
6. Click on a numeric field and clear the filed (It will show as N/A)
7. Click Save my Project

**Actual:** Can submit the project without entering any values to the 'budget' fields

**Expected:** Should validate the fields.

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by SathyaJayabal** [comment]
related #3613

**Comment by SathyaJayabal** [comment]
Values should be limited to increments of 1. No decimal vales/negative values/null values should be allowed. Values only from 1 to 100 should be accepted.

**Comment by nithyaasworld** [comment]
This is no more an issue with the updated UI

CC: @SathyaJayabal
