### ISSUE TITLE
Error: Request failed with status code 404 when delete message textarea

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#361]
Expected behavior
------------------------------------------------------------

- Do not display this error message in console.

Actual behavior
------------------------------------------------------------

- The Error: Request failed with status code 404 message is displayed in console.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Open Firebug Tool / Developer Tools and check the server calls.

- Select Messages tab section.

- Delete the Coder the Bot popup window using "x" close button.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![error](https://cloud.githubusercontent.com/assets/5114907/18963922/814ebac8-867f-11e6-9655-f1e8b39b9f8f.png)

**Comment by mahestro** [comment]
Known.
