### ISSUE TITLE
Budget amount hide over the cross icon

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3610]
### Expected behavior
Amount should not hide over the cross

### Actual behavior
Amount hide over the cross

### Steps to reproduce the problem
   - Open the Application and Login as valid user (Manager).
   - Click + New Project > On Demand >Buy Capacity.
   - Enter char and integer is accepted.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73364426-96de4000-42d0-11ea-8cf1-96a0b4ddc84c.png)

#### Environment
- OS: Android 10
- Browser (w/version): Edge 44.11.4.4140
- User role (client, copilot or manager): Manager
- Account used:  topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment]
@Krishna1507 , This is an edge case.
