### ISSUE TITLE
Back Button is missing from "CREATE A NEW PROJECT" page

### ISSUE THREAD

**Issue by kalindipandey** [appirio-tech/connect-app#3611]
### Expected behavior
Back button should be there on "CREATE A NEW PROJECT" page as per the designs
[](https://marvelapp.com/cc9e4j1/screen/65344038)

### Actual behavior
The "Back" button is missing from the "CREATE A NEW PROJECT" page
### Steps to reproduce the problem
1. open the application 
2. login as copilot role
3. Click on +New Project
4. Check for the Back button with a back arrow sign is missing from there which is in the design
### Screenshot/screencast
![Bug5](https://user-images.githubusercontent.com/46349625/73364515-ba08ef80-42d0-11ea-99fa-e7806f2bab70.jpg)

--

#### Environment
- OS: micromax LI351568W ; Windows10
- Browser (w/version): Chrome Version 79.0.3945.130
- User role (client, copilot or manager): copilot
- Account used:  topcoderconnect+Copilot@gmail.com

**Comment by kalindipandey** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@kalindipandey , as per design. The esc button is enough to go back.
