### ISSUE TITLE
"Your Project Estimate" page does not have any time estimates

### ISSUE THREAD

**Issue by kalindipandey** [appirio-tech/connect-app#3612]
### Expected behavior
"Your Project Estimate" page should have any time estimates
### Actual behavior
"Your Project Estimate" page does not have any time estimates
### Steps to reproduce the problem
1. Open the application
2. Login as copilot Role
3.  Click on "view Solutions" in "On Demand" option 
4.  Click on Select in Buy Capacity Option
5.  Project name - Testing;    Description: testing
6.  Click Next
7. Select  Design and Quality Assurance options
8.  Click Next
9.  Click Next
10.  "Your Project Estimate" page does not have any time estimates

### Screenshot/screencast
![Bug6](https://user-images.githubusercontent.com/46349625/73366056-503e1500-42d3-11ea-9f03-4c276188b2c9.jpg)

--

#### Environment
- OS:  micromax LI351568W ; Windows10
- Browser (w/version):  Chrome Version 79.0.3945.130
- User role (client, copilot or manager):  copilot
- Account used:  topcoderconnect+Copilot@gmail.com

**Comment by kalindipandey** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@kalindipandey accepted

**Comment by nithyaasworld** [comment]
Cannot reproduce in the updated UI

CC: @SathyaJayabal
