### ISSUE TITLE
So many decimal places displayed as budget if user enter decimal values

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3613]
![image](https://user-images.githubusercontent.com/42398485/73368090-083cd500-4276-11ea-82e3-d2036bbd1f74.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Fill all the mandatory fields > Next 
4. Select 'QA' the options > Next
5. Enter 0.1 to the numeric field =$700 (Correct)
6. Enter 1.1 to the numeric field = $3,850.0,000,000,000,005

**Actual:** So many decimal places displayed as budget if user enter decimal values

**Expected:** Should display the correct value = $3,850

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
Related to #3609 . Values should be limited to increments of 1. No decimal vales/negative values/null values should be allowed.
cc @codejamtc
