### ISSUE TITLE
Pressing Enter opens up the picklist

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3616]
Expected behavior
using enter button on keyboard shouldnt open the picklist values dropdown

Actual behavior
Pressing Enter on Keyboard opens up Picklist dropdown on any selection

Steps to reproduce the problem
Create a new project
select View solution(Project detail
Enter Project name, description, 
Next page - enter detail
go to next page and enter values and press enter on keyboard and observe.

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot - 
![Screen Shot 2020-01-29 at 9 32 06 PM](https://user-images.githubusercontent.com/57220292/73373570-da3fab00-42de-11ea-81af-0c95635a8e4b.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted
