### ISSUE TITLE
Text is not centrally placed - description and Project name

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3617]
Expected behavior
using enter button on keyboard shouldnt open the picklist values dropdown

Actual behavior
Pressing Enter on Keyboard opens up Picklist dropdown on any selection

Steps to reproduce the problem
Create a new project
select View solution(Project detai)
Enter Project name, description with long text
Next page - observe the text placement - 

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot

**Comment by akultalwar89** [comment]
![Screen Shot 2020-01-29 at 9 34 16 PM](https://user-images.githubusercontent.com/57220292/73373890-5639f300-42df-11ea-8fa8-8508f623419b.png)

Expected - Text should be centrally placed, doesnt look aligned while viewing on next page.

@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , edge case. works fine with normal words.
