### ISSUE TITLE
Currency columns should not have option selection

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3618]
Expected behavior
If user adds value more than 10000 , it clicks on option selection then it removes the entered value.

Actual behavior
It removes the enterred number. if user clicks on scroll option.

Steps to reproduce the problem
Create a new project
select View solution(Project detail
Enter Project name, description,
Next page - enter detail
go to next page and enter values '100000' and observe small selection button, click on it
It removes the value and keep it to 100 or 99

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot - 

![Screen Shot 2020-01-29 at 9 49 47 PM](https://user-images.githubusercontent.com/57220292/73375103-51763e80-42e1-11ea-8dcd-9f2bc03c085d.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 related to #3609
