### ISSUE TITLE
Error character mistake 

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3619]
Expected behavior
Please , - should not have , after please.

Actual behavior
, is present between the sentence 

Steps to reproduce the problem
Create a new project
select View solution(Project detail)
Enter Project detail , - https://connect.topcoder-dev.com/new-project/talent-as-a-service
Observe the error message. 

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot -
![Screen Shot 2020-01-29 at 9 56 45 PM](https://user-images.githubusercontent.com/57220292/73375831-6901f700-42e2-11ea-8074-879ecd05a351.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
related #3570 .
@akultalwar89

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  - This is not coming on everypage - I have seen that this is coming on different pages.
If you will see in the screen shot it was fine

So if same issue is not coming on all the pages , then single fix wont work on all pages, it is usually considered as different issues :) 
![Screen Shot 2020-01-31 at 10 30 40 AM](https://user-images.githubusercontent.com/57220292/73513751-e168d500-4414-11ea-9cde-c010f108af9e.png)

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  - just wanted to check on this one.

**Comment by SathyaJayabal** [comment]
Ok, I will accept this.
