### ISSUE TITLE
on selecting Android watch & Apple watch both, on dashboard panel should displayed watch os & Android wear Or Apple & Android watch

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#362]
### Expected behavior
on selecting Android watch & Apple watch both, on dashboard panel should displayed watch os & Android wear Or Apple & Android watch
### Actual behavior
showing as ios watch & Android wear
### Steps to reproduce the problem
1. open the Application
2. Login with copilot :cp-superstar
3. select device as Android watch & Apple watch
4. go to Dashbaord panel
### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/18963817/11b21150-8694-11e6-969a-9ffd06dbf76b.png)

![image](https://cloud.githubusercontent.com/assets/16131461/18963951/855b18cc-8694-11e6-8485-9a46f9efb69f.png)

#### Environment
- OS: windows 7
- Browser (w/version): Firefox 35.1
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
Change Android wear -> android watch
