### ISSUE TITLE
Other value is expective without anything in description

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3620]
Expected behavior
If user is allowed to add no other value or sentence . then in the next page - it should show blank value not N/A

Actual behavior
blank value is accepted and showing as N/A in next page

Steps to reproduce the problem
Create a new project
select View solution(Project detail)
Select Client Request - 
Enter Project name, description,
Next page - select Other and leave it as blank
user is able to go on to next page and it shows N/A - should be blank.

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot -
![Screen Shot 2020-01-29 at 10 14 43 PM](https://user-images.githubusercontent.com/57220292/73377271-c7c87000-42e4-11ea-8beb-f3fe6f44c4db.png)
![Screen Shot 2020-01-29 at 10 14 32 PM](https://user-images.githubusercontent.com/57220292/73377293-cdbe5100-42e4-11ea-8e85-d02f5c390ed1.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , as per design.
