### ISSUE TITLE
different space between different pages 

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3621]
Expected behavior
Extra space - It should be unified across all places

Actual behavior
Extra space is seen

Steps to reproduce the problem
Create a new project
select View solution(Project detail)
Select Client Request -
Enter Project name, description,
Next page - observe the page UI
Go to next page - observe the difference in space between name and descrption.

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot -
![Screen Shot 2020-01-29 at 10 19 39 PM](https://user-images.githubusercontent.com/57220292/73377803-a6b44f00-42e5-11ea-9aff-a4e11bff97bf.png)
![Screen Shot 2020-01-29 at 10 22 14 PM](https://user-images.githubusercontent.com/57220292/73377936-d9f6de00-42e5-11ea-9db7-f1cbc0ff01d0.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted
