### ISSUE TITLE
Other and help descption accepting spaces as blank values

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3622]
Expected behavior
Spaces should not be considered as charaters - should have some value or blank

Actual behavior
Accepting Spaces

Steps to reproduce the problem
Create a new project
select View solution(Project detail)
Select Client Request -
Enter Project name, description,
Next page - select Other and Help enter Space from keyboard
It accepts blank value

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot -
![Screen Shot 2020-01-29 at 10 25 08 PM](https://user-images.githubusercontent.com/57220292/73378352-7ae59900-42e6-11ea-82b8-e7738e536408.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 as per design
