### ISSUE TITLE
Skills column - Error character mistake

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3623]
Expected behavior
Please , - should not have , after please.

Actual behavior
, is present between the sentence

Steps to reproduce the problem
Create a new project
select View solution(Project detail)
Enter Project detail , go to next pages https://connect.topcoder-dev.com/new-project/talent-as-a-service
Observe the error message.

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot -
![Screen Shot 2020-01-29 at 10 29 36 PM](https://user-images.githubusercontent.com/57220292/73378679-ffd0b280-42e6-11ea-8ba0-7942bc19af37.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akinwale , related to #3570

**Comment by akultalwar89** [comment]
hi @SathyaJayabal  - similar to my other bug - the error message was not present in all the places . the validation issue is different for different pages or templates. this wont get fix with one fix for all. 
so i raised them differently.

i mean- if a page has 4 field validations and all of them have issue then i raised 1 for the page -

**Comment by akultalwar89** [comment]
I am asking you to check because - as a QA - i spent time to check all the different pages to see if they have this error issue in the field validation or not.

**Comment by SathyaJayabal** [comment]
Ok, I will accept this
