### ISSUE TITLE
[$40] [Chrome] Didnt have direct link to login page when user try some link to dashboard without login

### ISSUE THREAD

**Issue by degraphic** [appirio-tech/connect-app#3624]
#### Expected behavior
When Link of https://connect.topcoder-dev.com/settings/profile access on browser, should have direct link to login page when user not login

#### Actual behavior
When Link of https://connect.topcoder-dev.com/settings/profile access on browser, im not going to login page
#### Steps to reproduce the problem

 1. Open the Browser then type https://connect.topcoder-dev.com/settings/profile (without login with credential)
 2. Then we can see blank page and not redirect to login page

#### Screenshot/screencast
![Screen Shot 2020-01-29 at 23 58 09](https://user-images.githubusercontent.com/4364214/73378883-e8e48d00-42f3-11ea-817c-19515d326bc0.png)

#### Environment

    OS: MacOs Mojave 10.14.6
    Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
    User role (client, copilot or manager): none
    Account used: none

**Comment by degraphic** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@degraphic , out of scope

**Comment by lakshmiathreya** [comment]
Redirect to Accounts Login page should be implemented for all direct link accesses ...

**Comment by maxceem** [comment]
This should be fixed for all the pages:
- https://connect.topcoder-dev.com/settings/profile
- https://connect.topcoder-dev.com/settings/notifications
- https://connect.topcoder-dev.com/settings/account

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3761 is ready for review

**Comment by satkanhub** [comment]
Working as expected. QA Passed.

[3624.zip](https://github.com/appirio-tech/connect-app/files/4333414/3624.zip)


@drasticdpk @lakshmiathreya Please update the status, seems I do not have access.

**Comment by coderhacker** [comment]
https://connect.topcoder-dev.com/settings/profile
https://connect.topcoder-dev.com/settings/notifications
https://connect.topcoder-dev.com/settings/account

All the above three links working as expected.

**Comment by coderhacker** [comment]
https://connect.topcoder.com/settings/profile
https://connect.topcoder.com/settings/notifications
https://connect.topcoder.com/settings/account
CustomerUser/appirio123
Verified on prod, working as expected.
[3624-prod.zip](https://github.com/appirio-tech/connect-app/files/4420363/3624-prod.zip)
