### ISSUE TITLE
Disabled button background is different in IE11

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3625]
![image](https://user-images.githubusercontent.com/42398485/73379181-72aa4100-4287-11ea-9b59-2c2cd6978495.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity > Select
3. Fill all the fields > Next 
4. Check the next button color

**Actual:** Disabled button background is different in IE11

**Expected:** Should display in gray

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , not a bug
