### ISSUE TITLE
Escape button is not closing What is right for me info page.

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3626]
Expected behavior
excape button should close down the hover page

Actual behavior
esc button is not closing the page

Steps to reproduce the problem
Create a new project
select View solution(Project detail)
Enter Project detail , on the budget page - https://connect.topcoder-dev.com/new-project/prepaid_budget - red line what is right for me 
it opens over the page - esc button doesnt work.

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot -
![Screen Shot 2020-01-29 at 10 37 05 PM](https://user-images.githubusercontent.com/57220292/73379377-28a57780-42e8-11ea-9259-ed7674faf12e.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , related #3556

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  -  This is a different link, it should be considered as different bug?
Thank you

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted

**Comment by akultalwar89** [comment]
Thank you @SathyaJayabal  - do we need to reopen this one

**Comment by SathyaJayabal** [comment]
@akultalwar89 , no need. it will be tracked by the other issue

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  - this should be functional right?

**Comment by SathyaJayabal** [comment]
yes, right
