### ISSUE TITLE
Multiline textboxes leading spaces should be trimmed when user comes back to the same page again

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3628]
![image](https://user-images.githubusercontent.com/42398485/73380194-37a90d00-4289-11ea-82cc-1865d58405b1.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity > Select
3. Fill all the fields > Enter leading spaces with a text to the description > Next 
4. Click Back

**Actual:** Multiline textboxes leading spaces retained when user comes back to the same page again

**Expected:** Multiline textboxes leading spaces should be trimmed when user comes back to the same page again

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UX, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , as per design
