### ISSUE TITLE
Must display as -x selectedAfter deleting a Project Feature (-x selected --> - -x selected)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#363]
### Expected behavior
-----------------------------------------------------------------
Must display as -x selected

### Actual behavior
-----------------------------------------------------------------
After deleting a Project Feature (-x selected --> - -x selected)

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Click Add/Edit Features
- Click Add a Custom features button
- Add 2-3 items
- Check the 'Project Features - x selected' 
- Now Select a Custom feature
- Delete it
- Check the 'Project Features - x selected' (-x selected --> - -x selected)

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_22-43-22](https://cloud.githubusercontent.com/assets/4592712/18964353/2945a1ea-8696-11e6-967b-69a97f91bc2e.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vikasrohit** [comment]
Not able to reproduce after changes for #125
