### ISSUE TITLE
[$30] Welcome Back! screen close button UI issue

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3630]
![1](https://user-images.githubusercontent.com/42398485/73381953-447b3000-428c-11ea-9700-5f187c61b2b3.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity > Select
3. Fill all the fields > Next 
4. Click ECS
5. Click + New Project

**Actual:** Welcome Back! screen close button UI issue

**Expected:** Should display the top right corner above the Welcome back! title

**Environment:** iPhone 5s | iOS 12.2

**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted.

**Comment by lakshmiathreya** [comment]
Issue is observed currently ...

**Comment by vikasrohit** [comment]
@maxceem CF candidate

**Comment by maxceem** [comment]
Sum up:
- While fixing this issue on small screens, the fix shouldn't break it on the big screens.

**Comment by tcchhabra** [comment]
@bug-bash-helper assign

**Comment by tcchhabra** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3756 is ready for review

**Comment by maxceem** [comment]
@tcchhabra there is some feedback for the fix, please have a look https://github.com/appirio-tech/connect-app/pull/3756#pullrequestreview-372516548

**Comment by tcchhabra** [comment]
@maxceem the requirement clearly said `Environment: iPhone 5s | iOS 12.2` so I didn't test other resolutions. Just made sure it is not broken for browser, I guess the video shared is broken before my fix too.

**Comment by maxceem** [comment]
@tcchhabra Ah, sorry for the confusion. The `Environment: iPhone 5s | iOS 12.2` is where the issue has been found to make sure we can reproduce it.

Though we have to fix the issue in general. It can be reproduced on various mobile resolutions, not only on iPhone 5s.

**Comment by tcchhabra** [comment]
@bug-bash-helper #3756 is ready for review

**Comment by maxceem** [comment]
@tcchhabra fix works good now for this page, but it breaks close button on other pages, see https://github.com/appirio-tech/connect-app/pull/3756#pullrequestreview-373259998

**Comment by tcchhabra** [comment]
@bug-bash-helper #3756 is ready for review

**Comment by maxceem** [comment]
@tcchhabra the new update doesn't fix the issue and moves title instead of the button, and also still causes some other pages to update, please see feedback https://github.com/appirio-tech/connect-app/pull/3756#pullrequestreview-374110980

**Comment by maxceem** [comment]
@tcchhabra prize raised to $50 as the fix would request some CSS class restructure.

**Comment by tcchhabra** [comment]
@bug-bash-helper #3756 is ready for review

**Comment by tcchhabra** [comment]
@maxceem fixed with minimal changes. It works fine on my side, testing for iPhone 5/X/iPad/Laptop for both welcome back and new project screens. Await your feedback 🤞

**Comment by drasticdpk** [comment]
Verified on Dev Env:
![image](https://user-images.githubusercontent.com/25297859/76754520-63854100-67aa-11ea-9e37-d8db222687ab.png)
[3630_verificatoin.mp4.zip](https://github.com/appirio-tech/connect-app/files/4337918/3630_verificatoin.mp4.zip)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/78249369-d6cdc900-74b3-11ea-872d-8ea4b1a7fa5c.png)
![image](https://user-images.githubusercontent.com/42398485/78249386-dfbe9a80-74b3-11ea-9939-1bb2379cee38.png)
