### ISSUE TITLE
[$50] Able to add same skill multiple time using space

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3634]
### Expected behavior
Should be update auto when same skill add with space

### Actual behavior
Same skill added multiple time in engage talent option

### Steps to reproduce the problem
- Open the Application and Login as valid user (Manager).
- Click + New Project > On Demand > Engage Talent > select.
- Fill and Traverse till "What skills are important for your team to have?.
- Able to add same skill multiple time with space

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73387807-1aab2300-42f7-11ea-8b7e-fcd63e028bf0.png)

#### Environment

   - OS: Windows 10 pro
   - Browser (w/version): IE11/11.592.18362.0
   - User role (client, copilot or manager): Manager
   - Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@Krishna1507 accepted

**Comment by SathyaJayabal** [comment]
Type the already added skill name, add a space and you will be able to select the same skill again.

**Comment by nithyaasworld** [comment]
Its still failing for me in production. But I am not able to add it multiple times. But I am able to add it 2 times with the help of space. 
![image](https://user-images.githubusercontent.com/5114190/75518647-6e5c7980-5a27-11ea-8995-8875ae71fd73.png)

**Comment by vikasrohit** [comment]
@maxceem I don't think we did anything to fix this in the release. This one seems not yet planned for a release. Moving next release.

**Comment by Giri-Suman** [comment]
@bug-bash-helper assign

**Comment by Giri-Suman** [comment]
@bug-bash-helper unassign

**Comment by Giri-Suman** [comment]
@bug-bash-helper assign

**Comment by Giri-Suman** [comment]
@bug-bash-helper

**Comment by maxceem** [comment]
@Giri-Suman I've fixed the issue and opened it for pick up.

**Comment by gets0ul** [comment]
@Giri-Suman @maxceem Is this open? Thanks

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@gets0ul and I commented at same time

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3762 is ready for review

**Comment by maxceem** [comment]
@rashmi73 the fix works good, but looks like there is now redundant code, can we remove it? https://github.com/appirio-tech/connect-app/pull/3762#pullrequestreview-373271601

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3762 is ready for review

**Comment by drasticdpk** [comment]
Still having same issue. User can add same skills( two times)  by typing space and tab key on already selected skills. 
Here is the reference.

![image](https://user-images.githubusercontent.com/25297859/76756813-8d406700-67ae-11ea-8592-a142e24d12ab.png)

[3634_Verification.mp4.zip](https://github.com/appirio-tech/connect-app/files/4338059/3634_Verification.mp4.zip)

**Comment by vigneshTheDev** [comment]
@maxceem, This issue is fixed. Please review: https://github.com/appirio-tech/connect-app/pull/3813/files

**Comment by maxceem** [comment]
@codejamtc This is fixed for tabs now and ready for testing.

**Comment by codejamtc** [comment]
https://www.screencast.com/t/1SXBN7rI5M

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
Verified on prod and working as expected.
[3634_prod.zip](https://github.com/appirio-tech/connect-app/files/4419645/3634_prod.zip)
