### ISSUE TITLE
All the Custom features deleted in the list; Not only the selected item

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#364]
### Expected behavior
-----------------------------------------------------------------
Must delete only the selected Custom features

### Actual behavior
-----------------------------------------------------------------
All the Custom features deleted in the list

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Click Add/Edit Features
- Click Add a Custom features button
- Add 4-5 items
- Select an item
- Click Delete Custom Feature
- Confirm the deletion from the popup
- Now the popup is still there; click delete button 4-5 times
- Cancel the popup and check the list; all the items deleted

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_22-43-13](https://cloud.githubusercontent.com/assets/4592712/18964400/57651bf0-8696-11e6-8140-ec229a7ee4b4.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid for bugs count, but won't be fixed. It's related to #210
