### ISSUE TITLE
Solution Tiles mismatch - APPLICATIONS & WEBSITES between Marvel and app

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3644]
Expected behavior
Tiles mismatch between Marvel and App - APPLICATIONS & WEBSITES 

Actual behavior
Mismatch - APPLICATIONS & WEBSITES between marvel and app

Steps to reproduce the problem
Create a new project
select View solution -  Look for all the option
https://connect.topcoder-dev.com/new-project/scoped-solutions
Observe the tiles 

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 2 43 26 PM](https://user-images.githubusercontent.com/57220292/73436388-7239a500-4370-11ea-9df0-eb9870cfc9a7.png)
![Screen Shot 2020-01-30 at 2 42 30 PM](https://user-images.githubusercontent.com/57220292/73436389-7239a500-4370-11ea-8b9d-31f7c1f24e26.png)

**Comment by akultalwar89** [comment]
Apologies here is the difference - 
![Screen Shot 2020-01-30 at 2 44 02 PM](https://user-images.githubusercontent.com/57220292/73436466-91d0cd80-4370-11ea-8119-9fb517ec8c18.png)

@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , content issue
