### ISSUE TITLE
Different spelling mistake - 

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3645]
Expected behavior
spelling mistake - different

Actual behavior
spelling mistake

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option
https://connect.topcoder-dev.com/new-project/scoped-solutions
Observe the tiles

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 2 43 26 PM](https://user-images.githubusercontent.com/57220292/73436495-a319da00-4370-11ea-986b-d38592d52e16.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted

**Comment by nithyaasworld** [comment]
No more an issue. Closing this.
