### ISSUE TITLE
LOREM IPSUM - different in app and Marvel 

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3646]
Expected behavior
Text missing from App and marvel - LOREM IPSUM - should be long as in Marvel

Actual behavior
Text missing from App and marvel - LOREM IPSUM -

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option
https://connect.topcoder-dev.com/new-project/scoped-solutions
observe the text in screen shot

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 3 00 51 PM](https://user-images.githubusercontent.com/57220292/73437066-af526700-4371-11ea-9425-cb95a2fe1e31.png)
![Screen Shot 2020-01-30 at 3 00 46 PM](https://user-images.githubusercontent.com/57220292/73437069-af526700-4371-11ea-8423-53c6c4d2e453.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , content issue
