### ISSUE TITLE
Text missing in application/website tile

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3647]
Expected behavior
Text missing from App and marvel - application and website

Actual behavior
Text missing from App and marvel - application and website

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option
https://connect.topcoder-dev.com/new-project/scoped-solutions
observe the text in screen shot

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 3 06 22 PM](https://user-images.githubusercontent.com/57220292/73437366-39023480-4372-11ea-80da-3d4ff974c700.png)
![Screen Shot 2020-01-30 at 3 06 11 PM](https://user-images.githubusercontent.com/57220292/73437368-39023480-4372-11ea-96ba-6982caa2c810.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , content issue
