### ISSUE TITLE
Header is missing from app

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3648]
Expected behavior
Header is missing as avialable in Marvel

Actual behavior
Header should be present.

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option
https://connect.topcoder-dev.com/new-project/scoped-solutions
Observe the header is missing

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 3 13 30 PM](https://user-images.githubusercontent.com/57220292/73437886-263c2f80-4373-11ea-92c7-3dd71bfae672.png)
![Screen Shot 2020-01-30 at 3 13 19 PM](https://user-images.githubusercontent.com/57220292/73437887-263c2f80-4373-11ea-9df4-be3ff7cc942a.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , as per design
