### ISSUE TITLE
Engage Talent pages - link is missing - What is right for me?

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3649]
Expected behavior
Link should be present like other pages - What is right for me?

Actual behavior
link is missing 

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option - https://connect.topcoder-dev.com/new-project/prepaid_budget
Link is missing - What is right for me?

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 3 18 10 PM](https://user-images.githubusercontent.com/57220292/73438371-f17ca800-4373-11ea-94fb-bbc5f89e7b1d.png)
![Screen Shot 2020-01-30 at 3 17 56 PM](https://user-images.githubusercontent.com/57220292/73438372-f2153e80-4373-11ea-9db2-77a6456e8d31.png)

**Comment by akultalwar89** [comment]
https://connect.topcoder-dev.com/new-project/prepaid_budget

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , as per design
