### ISSUE TITLE
[Common] 'Project Features' phone image is partially hidden from the bottom

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#365]
### Expected behavior

---

Must able to scroll the page to see the full image
### Actual behavior

---

[Common] 'Project Features' phone image is partially hidden from the bottom
### Steps to reproduce the problem

---
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Click Add/Edit Features
- Click 'Help'
- Check the phone image
### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section)

---

![2016-09-29_22-47-49](https://cloud.githubusercontent.com/assets/4592712/18964508/cd9c8466-8696-11e6-923b-ae8fd0c4f9d2.png)
### Environment

---
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
We need a better layout system to be able to scale the feature preview image; current system is not able to scroll or easily scale the feature preview image. Will fix after beta launch

**Comment by vic-appirio** [comment]
Bouncing that one out to Didi: We need to fix a bit of the rendering, so that the feature preview is going to be responsive; current model isn't supporting that.

**Comment by vic-appirio** [comment]
Not completely functional. The image is not displayed correctly during resizing the image. Furthermore, the text of the feature gets squashed a bit too much - we need some minimal width there.

See attached screenshots (Safari, Chrome on Mac):

![screen shot 2016-11-18 at 3 39 18 pm](https://cloud.githubusercontent.com/assets/8484061/20450542/23f77ec0-ada6-11e6-8570-bf16327fbb27.png)
![screen shot 2016-11-18 at 3 39 37 pm](https://cloud.githubusercontent.com/assets/8484061/20450545/2410f7ce-ada6-11e6-918e-bb4b9af0d4ac.png)
![screen shot 2016-11-18 at 3 39 44 pm](https://cloud.githubusercontent.com/assets/8484061/20450544/240e4f42-ada6-11e6-8b34-ddec232defe9.png)
![screen shot 2016-11-18 at 3 38 15 pm](https://cloud.githubusercontent.com/assets/8484061/20450543/240df5ec-ada6-11e6-80d5-1ed274c6ff18.png)
