### ISSUE TITLE
Tabs sequence not match as per design

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3650]
### Expected behavior
The sequence of tabs should the same as per design

### Actual behavior
The sequence of tabs are not same as per design

### Steps to reproduce the problem
- Open the Application and Login as valid user (Customer).
- Click + New Project
- Observe the sequence has changed On Demand and Solutions.
- As per design sequence is Solutions then On Demand

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73445605-10356b80-4381-11ea-887b-ce4b049ffae0.png)

#### Environment
   - OS: Windows 10 
   - Browser (w/version): IE11 
   - User role (client, copilot or manager): Customer
   - Account used: topcoderconnect+Customer@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@Krishna1507 , content issue
