### ISSUE TITLE
[$20] Engage Talent Icons image are not properly aligned (IE11)

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3651]
### Expected behavior
Engage talent whole page icon  should be aligned 

### Actual behavior
Engage talent whole page icons are not aligned 

### Steps to reproduce the problem
- Open the Application and Login as valid user (Customer).
- Click + New Project > On Demand 
-  Observe the engage talent page icons 
- Icon image overlapped over the text

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73445999-f8121c00-4381-11ea-8942-c96ab467906a.png)

#### Environment
   - OS: Windows 10 
   - Browser (w/version): IE11 
   - User role (client, copilot or manager): Customer
   - Account used: topcoderconnect+Customer@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment]
@Krishna1507 , accepted

**Comment by nithyaasworld** [comment]
This is still an issue but in a different way. Screenshot below:

![image](https://user-images.githubusercontent.com/5114190/75333190-b35ba100-58ab-11ea-994c-afc7742e5fc2.png)

**Comment by vikasrohit** [comment]
we haven't done anything to fix the issue.

@maxceem if it is easily possible to fix it for IE11, we can take it in next CF and if it is tricky, we can skip fixing it if it is not an issue with Microsoft Edge.

**Comment by nqviet** [comment]
@bug-bash-helper assign

**Comment by nqviet** [comment]
@bug-bash-helper PR (https://github.com/appirio-tech/connect-app/pull/3757/commits/36db96f8d9cd24166b09714c99d93f373594ac9f) is ready for review

**Comment by maxceem** [comment]
@nqviet please create a separate pull request for this issue. Don't combine fixes for several issues into one pull request. Here is feedback for this issue https://github.com/appirio-tech/connect-app/pull/3757#pullrequestreview-373243786

**Comment by maxceem** [comment]
@nqviet the waves still look broken for me in IE11 https://github.com/appirio-tech/connect-app/pull/3789#pullrequestreview-374731458

**Comment by maxceem** [comment]
Works good after restarting the app:

![image](https://user-images.githubusercontent.com/146016/76684568-e93cab80-6647-11ea-97e7-fcc9ea1695f6.png)

**Comment by drasticdpk** [comment]
Verified on Dev Env
![image](https://user-images.githubusercontent.com/25297859/76755963-ec9d7780-67ac-11ea-8998-6d7aa023b6ba.png)

**Comment by codejamtc** [comment]
Verified in `Prod`: ❌ Fail - The Topcoder icon alignment issues
**User:** CustomerUser

![image](https://user-images.githubusercontent.com/42398485/78255325-c53cef00-74bc-11ea-8f9a-a300df454328.png)

![image](https://user-images.githubusercontent.com/42398485/78255678-4300fa80-74bd-11ea-88b5-367101de8930.png)
![image](https://user-images.githubusercontent.com/42398485/78255694-485e4500-74bd-11ea-865a-ab3a08d0733c.png)

![image](https://user-images.githubusercontent.com/42398485/78255711-4e542600-74bd-11ea-9121-9dce1460ca46.png)
![image](https://user-images.githubusercontent.com/42398485/78255726-53b17080-74bd-11ea-8189-7be3f6b657a5.png)
![image](https://user-images.githubusercontent.com/42398485/78255742-57dd8e00-74bd-11ea-8e71-e9edef1beb11.png)
![image](https://user-images.githubusercontent.com/42398485/78255773-62982300-74bd-11ea-98f6-39d98bd3f121.png)
![image](https://user-images.githubusercontent.com/42398485/78255789-675cd700-74bd-11ea-9f31-ac665b328b2d.png)

**Comment by maxceem** [comment]
@codejamtc do you mean Topcoder logo icon on the left?

![image](https://user-images.githubusercontent.com/146016/78256887-cc3a2080-7501-11ea-93c6-3afd2bc7bd76.png)

If so, this wasn't in the scope of this issue. In this issue, we only fixed position of the icons inside blue shapes, as per description https://github.com/appirio-tech/connect-app/issues/3651#issue-557433257.

Please, feel free to create a separate issue for the next `2.9` milestone for the new issue.

**Comment by codejamtc** [comment]
@maxceem Sure
