### ISSUE TITLE
Prepaid bugdet is coming wrong -  addtional +21 and already showing twenty 0

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3652]
Expected behavior
It should have showed the whole number of 1000000000000000 or 1e+21

Actual behavior
Currently number is coming as - $1.0,000,000,000,000,001e+21

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option
add project name and then next page 
select Development, data science and then all value -> 100000000000000000 and 10 in both columns
Observe prepaid budget above - wrong value coming

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 5 01 00 PM](https://user-images.githubusercontent.com/57220292/73446328-90100580-4382-11ea-8779-47098eafe248.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
related to #3613

**Comment by akultalwar89** [comment]
@SathyaJayabal  - the issue is different here - It is not about decimal - it is about exponentialnumber. if developer will fix the decimal place then too exp - 'e' is something that he/she would need to fix.
the result that i showed was without  decimal

**Comment by SathyaJayabal** [comment]
@akultalwar89 , the input field must accept only integers from 1 to 100. That should fix all the issues regarding this specific input field.
