### ISSUE TITLE
[Engage talent]Resources hours and Part-time resources hours should only accept integer

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3655]
### Expected behavior
Resources hours and Part-time resources hours should only accept integer

### Actual behavior
Resources hours and Part-time resources hours are accepting integer + char

### Steps to reproduce the problem

    Open the Application and Login as valid user (Manager)
    Click + New Project > On Demand > Engage Talent
    Go to 'Your Talent Requirements'
    Fill the Resources hours and Part-time resources hours 
### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73447100-0cefaf00-4384-11ea-8826-ba708b430059.png)

#### Environment
    OS: Windows 10
    Browser (w/version): IE11
    User role (client, copilot or manager): Customer
    Account used: topcoderconnect+Customer@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
related #3557
