### ISSUE TITLE
[Common] Category title is not center-aligned

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3656]
![5](https://user-images.githubusercontent.com/42398485/73447467-67592300-4324-11ea-8f9d-9c8b7be89dfd.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > Real World Testing
3. Check the title (Check other items as well)

**Actual:** Category title is not center-aligned

**Expected:** Category title should be center aligned

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted.
