### ISSUE TITLE
 [Buy Capacity] budget capacity accepting the negative value

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3657]
### Expected behavior
Increment icon should be available

### Actual behavior
No increment/decrement selector found 

### Steps to reproduce the problem
- Open the Application and Login as valid user (Customer).
- Click + New Project > On Demand >Buy Capacity.
-  In Prepaid budget page "How much design budget capacity would you like to purchase?" and "How much development budget capacity would you like to purchase?" accept negative value

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73447784-7c19d300-4385-11ea-8cba-152b58db949e.png)

#### Environment
- OS: Windows 10
- Browser (w/version): IE11 
- User role (client, copilot or manager): Customer
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@Krishna1507 , related #3606
