### ISSUE TITLE
Search result Shows no result - should show a message no results found

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3658]
Expected behavior
should display a message that no results found for . search new result something as per design standards

### Actual behavior
currently it shows blank screen . does not display any message

 Steps to reproduce the problem
Go to new project then Solutions -
https://connect.topcoder-dev.com/new-project/scoped-solutions
When user search for anything and no result found -
Should display a message - 

Screenshot/screencast
![Screen Shot 2020-01-30 at 7 37 06 PM](https://user-images.githubusercontent.com/57220292/73456534-0c611380-4398-11ea-9cd2-a1144972e7b8.png)

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , duplicate #3538
