### ISSUE TITLE
Search Hover Tool Tip - text is not correct - has code value

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3659]
Expected behavior
Hover tooltip should be normal text like Search.  it is like Code value currently -

Actual behavior
Tooltip value should be correct , not code

Steps to reproduce the problem
Go to new project then Solutions -
https://connect.topcoder-dev.com/new-project/scoped-solutions
hover/Tooltip - should be as search or not have anything like code

Screenshot/screencast
![Screen Shot 2020-01-30 at 8 27 06 PM](https://user-images.githubusercontent.com/57220292/73460709-eee37800-439e-11ea-9ee3-94534586b09e.png)

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted
