### ISSUE TITLE
[Common] 'Project Features' List have a horizontal scroll bar

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#366]
### Expected behavior
-----------------------------------------------------------------
'Project Features' List must not have a horizontal scroll bar

### Actual behavior
-----------------------------------------------------------------
[Common] 'Project Features' List have a horizontal scroll bar

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Click Add/Edit Features
- Check the 'Project Features' List
- It has a horizontal scroll bar (Compare with Chrome - It doesn't have)

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

![2016-09-29_22-50-22](https://cloud.githubusercontent.com/assets/4592712/18964582/21864166-8697-11e6-97d7-fa2ed135247d.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid, IE.
