### ISSUE TITLE
Quality Assurance small text given is different language in App and marvel

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3660]
Expected behavior
Text missing from App and marvel - LOREM IPSUM - It should be same across all icons.
Somewhere it is in english somewhere other language. 

Actual behavior
 It should be same across all icons.
Somewhere it is in english somewhere other language. 

Steps to reproduce the problem
Create a new project
select View solution - Look for all the option
https://connect.topcoder-dev.com/new-project/scoped-solutions
observe the text in screen shot

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 8 38 28 PM](https://user-images.githubusercontent.com/57220292/73461744-aa58dc00-43a0-11ea-907e-507e718d65cd.png)
![Screen Shot 2020-01-30 at 8 38 15 PM](https://user-images.githubusercontent.com/57220292/73461745-aa58dc00-43a0-11ea-92f6-36a68575f7fa.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , content issue
