### ISSUE TITLE
colour of front page tiles are different between browsers, safari and chrome - it should be same.

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3661]
Expected behavior
Colour of tiles are different between broswer- it should be same

Actual behavior
Different colour ,

Steps to reproduce the problem
Create a new project
https://connect.topcoder-dev.com/new-project/
colour different between safari browser and chrome

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) also Safari browser
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot

![Screen Shot 2020-01-30 at 9 11 56 PM](https://user-images.githubusercontent.com/57220292/73464766-6d431880-43a5-11ea-88f9-e2c09bb8a447.png)
![Uploading Screen Shot 2020-01-30 at 9.11.46 PM.png…]()

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by akultalwar89** [comment]
![Screen Shot 2020-01-30 at 9 11 46 PM](https://user-images.githubusercontent.com/57220292/73464837-8350d900-43a5-11ea-90aa-abdbfcbca100.png)

**Comment by SathyaJayabal** [comment]
@akultalwar89 , related  #3654
