### ISSUE TITLE
Hover value not coming in Chrome, but present in Safari - 

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3662]
Expected behavior
Hover tool tip not coming in Chrome -

Actual behavior
not coming in chrome tooltip

Steps to reproduce the problem
Create a new project
select View solution - go to create new project - 
https://connect.topcoder-dev.com/new-project/talent-as-a-serviceink is missing - 
Tooltip is not coming in Chrome

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) / and Safari
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 9 37 45 PM](https://user-images.githubusercontent.com/57220292/73467210-06bff980-43a9-11ea-808b-621f5f64c749.png)
![Screen Shot 2020-01-30 at 9 37 38 PM](https://user-images.githubusercontent.com/57220292/73467212-07589000-43a9-11ea-910c-65363e2ab5ea.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@akultalwar89 , not a bug
