### ISSUE TITLE
Arrow sign different in different browsers - it should be same in size and design

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3663]
Expected behavior
Arrow sign different , should be same in different browsers - Chrome and safari

Actual behavior
different arrow signs and lengh and design seen

Steps to reproduce the problem
Create a new project
select View solution - go to create new project -
https://connect.topcoder-dev.com/new-project/talent-as-a-serviceink is missing -
Arrow sign different present  in Chrome

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) / and Safari
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot -
![Screen Shot 2020-01-30 at 9 42 13 PM](https://user-images.githubusercontent.com/57220292/73467552-7a620680-43a9-11ea-8079-698b7853508c.png)
![Screen Shot 2020-01-30 at 9 42 01 PM](https://user-images.githubusercontent.com/57220292/73467555-7a620680-43a9-11ea-869b-251bc0b0910f.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P4

**Comment by SathyaJayabal** [comment]
@akultalwar89 , not a bug

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  -  Not sure about this one but i raised it because of consistancy issue.
