### ISSUE TITLE
Tooltip in Long Column Titles are not seen in Chrome but available in safari

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3664]
Expected behavior
 tool tip for Long Column Titles are not coming in Chrome -

Actual behavior
Tool tip for Column names not coming in chrome

Steps to reproduce the problem
Create a new project
select View solution - go to create new project -
https://connect.topcoder-dev.com/new-project/talent-as-a-serviceink is missing -
Column names Tooltip is not coming in Chrome

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) / and Safari
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 9 46 55 PM](https://user-images.githubusercontent.com/57220292/73468364-aaf67000-43aa-11ea-8481-52e51a29367f.png)
![Screen Shot 2020-01-30 at 9 46 33 PM](https://user-images.githubusercontent.com/57220292/73468367-aaf67000-43aa-11ea-9837-b85cfd1db1ed.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , not a bug

**Comment by akultalwar89** [comment]
Hi @SathyaJayabal  - Tooltip should be avaialble in Chrome as well. I can see that in safari -
I am saying it because i didnt notice it in chrome - but when i was going throught pages in safari i noticed it. It is a valid point because tooltip is a option when a developer build a page in the for of UI?.

**Comment by SathyaJayabal** [comment]
Tool tips are present in chrome.
