### ISSUE TITLE
Cross sign is not coming in Safari 

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3665]
Expected behavior
Observe Cross sign in Safari browser, 

Actual behavior
Safari cross sign is not coming 

Steps to reproduce the problem

Create a new project
select View solution - go to create new project -
https://connect.topcoder-dev.com/new-project/talent-as-a-serviceink is missing -
Observe cross sign in Safari

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) / and Safari
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 9 53 59 PM](https://user-images.githubusercontent.com/57220292/73468676-2c4e0280-43ab-11ea-9d03-43f62822f8f5.png)
![Screen Shot 2020-01-30 at 9 53 46 PM](https://user-images.githubusercontent.com/57220292/73468677-2ce69900-43ab-11ea-9e34-8f227b3b9483.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , related #3591

**Comment by akultalwar89** [comment]
hi @SathyaJayabal  - Mobile and Web is not different? usually we keep the layouts and bugs as different when it comes to mobile or web?

**Comment by SathyaJayabal** [comment]
The same issue across different platforms and browsers will be considered as one bug.
