### ISSUE TITLE
Colour missing from Tiles in Solution selection page in safari

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3668]
Expected behavior
colour should be present in safari

Actual behavior
colour missing from tiles in safari

Steps to reproduce the problem
Create a new project
https://connect.topcoder-dev.com/new-project/
click on view solution -then search page
View difference between browsers

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) also Safari browser
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screenshot-
![Screen Shot 2020-01-30 at 10 17 55 PM](https://user-images.githubusercontent.com/57220292/73470756-64a31000-43ae-11ea-9cca-98fb46cd3206.png)
![Screen Shot 2020-01-30 at 10 17 45 PM](https://user-images.githubusercontent.com/57220292/73470760-653ba680-43ae-11ea-82c7-75a9a34a205e.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P4

**Comment by SathyaJayabal** [comment]
@akultalwar89  related #3654
