### ISSUE TITLE
 [Common] Spacing in between the questions in the same section are not similar

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3669]
![image](https://user-images.githubusercontent.com/42398485/73471301-c469ce80-434e-11ea-9726-c205c94d9ca0.png)
![image](https://user-images.githubusercontent.com/42398485/73471350-dcd9e900-434e-11ea-95b7-aa87f4b6e44e.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > Data Visualization
3. Complete all the questions and go to 'Your Project Estimate' page
4. Expand one section item and check the space
4. Expand another section item and check the space

**Actual:** Spacing in between the questions in the same section are not similar

**Expected:** Should maintain similar spacing

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
