### ISSUE TITLE
after Adding Project feature if user upload the file without making save changes , added features remove 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#367]
### Expected behavior
added features should not be removed on uploading File 

### Actual behavior
Added features removed on uploading file without making save changes
### Steps to reproduce the problem
1. open the Application
2. Login with copilot :cp-superstar
3.  Create new Project
4. go to Specifications
5. Go to Feature Sections
6. Add/Edit features
7. Add Features to SPecifications
8. Upload file 
9. Now click on Save button 
10 .Added features remove

### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/18964786/053c878a-8698-11e6-8238-b8312980d461.png)

![image](https://cloud.githubusercontent.com/assets/16131461/18964831/31fb7b5a-8698-11e6-807a-2478d3912325.png)

--

#### Environment
- OS: windows 7
- Browser (w/version): Chrome latest 53 
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment]
True, valid. After loading the file it marks it as "Skip question" (checkbox on).

**Comment by parthshah** [comment]
This will be resolved once we implement auto-save on project spec. I'm not fixing this right now.

**Comment by fnisen** [comment]
@parthshah this is a pretty bad bug b/c we're losing customer input. I think we need to fix before GA.
