### ISSUE TITLE
Basic Detail page has back button which is in disabled mode

### ISSUE THREAD

**Issue by tchackerc** [appirio-tech/connect-app#3670]
### Expected behavior
Basic detail page should have only one back button,not require disabled button on first screen.

### Actual behavior
Basic Detail page has back button which is in disabled mode

### Steps to reproduce the problem
Open the Application
 Login as Customer user
click on new project button
click on vie solutions tab on demand section.
click on select tab
observe

### Screenshot/screencast
https://connect.topcoder-dev.com/new-project/prepaid_budget

![chrome_3Et1xn1whU](https://user-images.githubusercontent.com/60475043/73471624-abddd080-43af-11ea-99a5-1e8f6a55103c.png)

--

#### Environment
- OS: window 7
- Browser (w/version): chrome/Version 79.0.3945.130
- User role (client, copilot or manager): customer
- Account used: topcoderconnect+Customer@gmail.com

**Comment by tchackerc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@tchackerc , not a bug

**Comment by tchackerc** [comment]
Can you please explain how?

**Comment by tchackerc** [comment]
As per my suggestion it should be only continue button.As you have it in solution section.it is not valid for first page.

**Comment by SathyaJayabal** [comment]
the back button is not disabled. it takes the user back to the Create a project page.

**Comment by tchackerc** [comment]
May I know when it gets enabled?

**Comment by SathyaJayabal** [comment]
please try with the link you posted above. its always enabled.

**Comment by tchackerc** [comment]
Please see the below back button. And let me know

**Comment by tchackerc** [comment]
As you can see in the screenshot,I have marked 2 back button.Check the second one.

**Comment by SathyaJayabal** [comment]
@tchackerc , accepted.
