### ISSUE TITLE
By default arrows are missing from chrome - but present in safari - should have same behavior

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3671]
https://connect.topcoder-dev.com/new-project/prepaid_budget

Expected behavior
Observe Arrow sign in Safari browser present but missing from chrome

Actual behavior
signs missing in chrome by default

Steps to reproduce the problem

Create a new project
select View solution - go to create new project -
https://connect.topcoder-dev.com/new-project/prepaid_budget
Observe the arrow sign by default present in Safari and missing in Chrome

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) / and Safari
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

Screen shot
![Screen Shot 2020-01-30 at 10 29 09 PM](https://user-images.githubusercontent.com/57220292/73471964-3f170600-43b0-11ea-94fd-6737e25302bc.png)
![Screen Shot 2020-01-30 at 10 28 58 PM](https://user-images.githubusercontent.com/57220292/73471965-3f170600-43b0-11ea-9023-7a08b45863b8.png)

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted
