### ISSUE TITLE
Tooltip missing in Safari, but present in Chrome - Value arrows

### ISSUE THREAD

**Issue by akultalwar89** [appirio-tech/connect-app#3672]
### Expected behavior
Tooltip is missing in Safari in value button

### Actual behavior
Tool tip is missing in safari in value button

### Steps to reproduce the problem
After hovering on the Arrows, tooltip should come in safari

### Screenshot/screencast

![Screen Shot 2020-01-30 at 10 36 18 PM](https://user-images.githubusercontent.com/57220292/73472492-25c28980-43b1-11ea-824a-5866ed836e79.png)
![Screen Shot 2020-01-30 at 10 36 03 PM](https://user-images.githubusercontent.com/57220292/73472493-25c28980-43b1-11ea-977f-e864332f5bed.png)

Environment
OS: Macbook Air 10.15.2
Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit) / and Safari
User role (client, copilot or manager): topcoderconnect+CopilotManager@gmail.com
Account used: topcoderconnect+CopilotManager@gmail.com

**Comment by akultalwar89** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P3

**Comment by SathyaJayabal** [comment]
@akultalwar89 , accepted
