### ISSUE TITLE
[$10] [Common] Section title is not visible in mobile

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3673]
![6](https://user-images.githubusercontent.com/42398485/73473056-b6697d00-4351-11ea-8bb1-0b0ce10b70ea.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > Data Visualization

**Actual:** Section title is not visible in mobile

**Expected:** Should display the section headings. In this case "Data Visualization"

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by tcchhabra** [comment]
@bug-bash-helper assign

**Comment by tcchhabra** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3758 is ready for review

**Comment by drasticdpk** [comment]
Verified on Dev Env
![image](https://user-images.githubusercontent.com/25297859/76514968-e2177100-6480-11ea-980c-147bee8f3094.png)

**Comment by satkanhub** [comment]
Working as expected. Video for reference.

[3673.zip](https://github.com/appirio-tech/connect-app/files/4326639/3673.zip)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/78236257-58ffc280-749f-11ea-9371-4f2b8e12e51d.png)
