### ISSUE TITLE
Learn more link redirect to home screen

### ISSUE THREAD

**Issue by tchackerc** [appirio-tech/connect-app#3674]
### Expected behavior
It should redirect to detail of same text.

### Actual behavior
Learn more link redirect to home screen

### Steps to reproduce the problem
- login to application as custmer
-go to right corner of screen and click on new project
- select solution and click on view solution.
- Click on Learn more

### Screenshot/screencast
![2](https://user-images.githubusercontent.com/60475043/73473770-56a3be00-43b3-11ea-9e56-6f9071bf844c.png)

--

#### Environment
- OS: windows 7
- Browser (w/version): chrome/ Version 79.0.3945.130 
- User role (client, copilot or manager): Customer
- Account used: topcoderconnect+Customer@gmail.com

**Comment by tchackerc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment]
@tchackerc , duplicate #3548
