### ISSUE TITLE
[Web-Chrome] For Forget Password When Entering Email ID Its Showing Error

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3675]
### Expected behavior
While Fill Password It Should Send Email To Email ID

### Actual behavior
While Filling Password It Is Showing An Error As We weren't able to send a reset link because of a system error. Please try again or contact support@topcoder.com.

### Steps to reproduce the problem
1. Open App

2. Click On Login 

3. Select Login As topcoderconnect+Manager@gmail.com

4. Click On Forget Password Then Fill Valid Email ID

5. Click On Get Reset Link Then See & Observe

6. See Screencast & Screenshot 

### Screenshot/screencast

[Forget Password.mp4.zip](https://github.com/appirio-tech/connect-app/files/4135354/Forget.Password.mp4.zip)

[Forget Password.png.zip](https://github.com/appirio-tech/connect-app/files/4135355/Forget.Password.png.zip)

#### Environment
- OS: 

[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135360/Mac.Version.png.zip)

- Browser (w/version):

[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135362/Chrome.Version.png.zip)

- User role (client, copilot or manager): Manager

- Account used: topcoderconnect+Manager@gmail.com

**Comment by devsreekrishna** [comment]
BugHunt_JanRelease, Functional, P1

**Comment by devsreekrishna** [comment]
BugHunt_JanRelease Functional P1

**Comment by devsreekrishna** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@devsreekrishna , out of scope

**Comment by nithyaasworld** [comment]
This happens when the entered email id **doesn't exist in the system.** but works good for a valid email id.

I will open a new issue for this.
