### ISSUE TITLE
[Web-Chrome] While Country Is India It Should Show Error When Selecting Different Time Zone

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3677]
### Expected behavior
It Should Show Error While Country & Time Zone Is Different

### Actual behavior
Its Not Showing Error While Country & Time Zone Is Different

### Steps to reproduce the problem
1. Go To App

2. Login As topcoderconnect+Manager@gmail.com

3. Click On Profile

4. Select Profile Information & Fill TimeZone

5. While Country Is India It Is Selecting  Different Time Zone As Asia/Kathmandu

6. See Screencast & screenshot & Observe

### Screenshot/screencast

[While Country Is India Its accepting Kathmandu Time Zone.mp4.zip](https://github.com/appirio-tech/connect-app/files/4135582/While.Country.Is.India.Its.accepting.Kathmandu.Time.Zone.mp4.zip)

[While Selecting.png.zip](https://github.com/appirio-tech/connect-app/files/4135587/While.Selecting.png.zip)

#### Environment
- OS: 

[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135592/Mac.Version.png.zip)

- Browser (w/version):

[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135594/Chrome.Version.png.zip)

- User role (client, copilot or manager): Manager

- Account used:  topcoderconnect+Manager@gmail.com

**Comment by devsreekrishna** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@devsreekrishna , out of scope

**Comment by nithyaasworld** [comment]
Not an issue.
