### ISSUE TITLE
[Web-Chrome] There Is No Dropdown But Its Showing Drop Down Options Automatically

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3678]
### Expected behavior
If There Is No Drop Down It Should Not Not Show Drop Down Options

### Actual behavior
There Is No Dropdown But Its Showing Drop Down Options Automatically

### Steps to reproduce the problem

1. Go To App 

2. Login As topcoderconnect+Manager@gmail.com

3. Click On Profile Then Select Profile Information

4. Click On Local Time Zone As There Is No Drop Down Its Showing Drop Down Options Automatically

5. See Screencast & Screenshot 

### Screenshot/screencast

[There Is No Drop Down.mp4.zip](https://github.com/appirio-tech/connect-app/files/4135660/There.Is.No.Drop.Down.mp4.zip)

[There Is.png.zip](https://github.com/appirio-tech/connect-app/files/4135661/There.Is.png.zip)

#### Environment
- OS:

[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135664/Mac.Version.png.zip)

- Browser (w/version):

[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135666/Chrome.Version.png.zip)

- User role (client, copilot or manager): Manager

- Account used: topcoderconnect+Manager@gmail.com

**Comment by devsreekrishna** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@devsreekrishna , out of scope

**Comment by nithyaasworld** [comment]
Not an issue
