### ISSUE TITLE
[Web-Chrome] As Normal Working Hours Are For 9Hrs. Only It Should Automatically Change End Timing For 9Hrs. 

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3679]
### Expected behavior

As Normal Working Hours Are For 9Hrs. Only It Should Automatically Change End Timing For 9Hrs. 
### Actual behavior

As Normal Working Hours Are For 9Hrs. Only Its Not Changing End Time For 9Hrs.

### Steps to reproduce the problem

1. Go To App

2. Login As topcoderconnect+Manager@gmail.com

3. Click On Profile Then Select Profile Information

4. See Normal Working Hours. Its Showing Start Time As 09:00 & End Time As 18:00

5. Click On Normal Working Hours. Fill Start Time As 08:00 Then See Its Not Changing End Time As 17:00. Its Still Showing End Time As 18:00.

6. See Screencast & Screenshot

### Screenshot/screencast

[Schedule.mp4.zip](https://github.com/appirio-tech/connect-app/files/4135716/Schedule.mp4.zip)

[Schedule.png.zip](https://github.com/appirio-tech/connect-app/files/4135722/Schedule.png.zip)

#### Environment

- OS:

[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135723/Mac.Version.png.zip)

- Browser (w/version):

[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135735/Chrome.Version.png.zip)

- User role (client, copilot or manager): Manager

- Account used: topcoderconnect+Manager@gmail.com

**Comment by devsreekrishna** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment]
@devsreekrishna , out of scope

**Comment by nithyaasworld** [comment]
Not an issue
