### ISSUE TITLE
[Web-Chrome] Drop Down Box Is Overlapping With Drop Down Options

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3680]
### Expected behavior

Drop Down Box Should Not Overlap With Drop Down Options.

### Actual behavior

Drop Down Box Is Overlapping With Drop Down Options

### Steps to reproduce the problem

1. Go To App.

2. Login With topcoderconnect+Manager@gmail.com

3. Click On Notification Setting Then Click On Every Other Day Drop Down & Observe.

4. Every Other Day Drop Down Is Overlapping With Drop Down Options.

5. See Screenshot

### Screenshot/screencast

[Overlapping.png.zip](https://github.com/appirio-tech/connect-app/files/4135786/Overlapping.png.zip)

#### Environment

- OS:

[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135789/Mac.Version.png.zip)

- Browser (w/version):

[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135791/Chrome.Version.png.zip)

- User role (client, copilot or manager): Manager

- Account used: topcoderconnect+Manager@gmail.com

**Comment by devsreekrishna** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P1

**Comment by SathyaJayabal** [comment]
@devsreekrishna , out of scope
