### ISSUE TITLE
[Chrome]Save settings button should didnt have proper padding bottom on mobile view 320px

### ISSUE THREAD

**Issue by degraphic** [appirio-tech/connect-app#3681]
#### Expected behavior
When we try open in mobile view, the save settings button should have proper padding bottom

#### Actual behavior
When we try open in mobile view, the save settings button should didnt have proper padding bottom

#### Steps to reproduce the problem

1. Open the Browser then type https://connect.topcoder-dev.com/	and login with credential
2. Then click "My Profile" on the top
3. Then inspect element then choose responsive view

#### Screenshot/screencast
https://drive.google.com/open?id=1Na2CDp0cHsCHxYsIbJZOvjToxpJep8EP

#### Environment

    OS: MacOs Mojave 10.14.6
    Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
    User role (client, copilot or manager): copilot
    Account used:  topcoderconnect+Copilot@gmail.com

**Comment by degraphic** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment]
@degraphic , out of scope

**Comment by nithyaasworld** [comment]
Very trivial
