### ISSUE TITLE
UI issue in the validation tooltip

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3682]
![A1](https://user-images.githubusercontent.com/42398485/73504528-4d0b5d80-4395-11ea-8fc6-9c3c137be06c.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Go to Budget screen > Enter 100, 1001, 100, 100 to the fields > Click Next
4. Expand the 1001 field and click Save My project

**Actual:** UI issue in the validation tooltip. Left side spacing issue

**Expected:** Should display small spacing from the left

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
