### ISSUE TITLE
Loading animation partially hidden

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3683]
https://www.screencast.com/t/F4aKXk43gUg

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Select an option
4. Go to Budget screen > Enter 100 to the fields > Click Next
5. Click Save My project
6. Check the loading animation

**Actual:** Loading animation partially hidden

**Expected:** Should display center of the screen

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
