### ISSUE TITLE
Space between the header and the content are too much compared to the first screen on the same flow

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3685]
https://www.screencast.com/t/wtTUMlUrF2

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > On Demand > Buy Capacity
3. Select an option, Scroll the page up and see the spacing
4. Tap Next, Scroll the page up and see the spacing
5. Go to Budget screen > Enter 100 to the fields > Click Next, Scroll the page up and see the spacing

**Actual:** Space between the header and the content are too much compared to the first screen on the same flow

**Expected:** Should reduce the spacing

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , not a bug
