### ISSUE TITLE
[Common issue for all projects] Switching the orientation if user is on project form will move all the content up

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3686]
https://www.screencast.com/t/FIeiGfunh0C

1. Open the Application and Login as valid user (Manager)(portrait)
2. Click + New Project > On Demand > Buy Capacity
3. Select all 4 options, Scroll the page down
4. Switch to Landscape view

**Actual:** Switching the orientation if the user is on project form will move all the content up

**Expected:** Should focus the current on the visible screen area

**Environment:** iPhone 5S | iOS 12.2
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
