### ISSUE TITLE
UI issue in the Solutions > QA Services section

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3687]
https://www.screencast.com/t/q6UD0pvI

1. Open the Application and Login as valid user (Manager)(portrait)
2. Click + New Project > Solutions
3. Go to 'QA Services section'
4. Go to 'Analytics and Data Science'

**Actual:** UI issue in the Solutions > QA Services section

**Expected:** Should display the layout like others, for example, check Data Science and Analytics section

**Environment:** iPad Air 2 | iOS 12.4.1
**Browser:** Safari 12

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
