### ISSUE TITLE
Project timeline is not displayed for below QA services

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3688]
https://www.screencast.com/t/JZIklAncv

1. Open the Application and Login as valid user (Manager)(portrait)
2. Click + New Project > Solutions > QA Services (23-08-2019)
3. Fill all the mandatory fields > Next
4. Select Any service from the below list;

Regression Testing
End-User Acceptance Testing/Beta Testing
Compatibility Testing
Exploratory Testing
Accessibility Testing
Localization/Language Testing
Functional/Feature Testing
User Sentiment Analysis
Regression Automation

5. Complete all the steps and check the 'Your project timeline'

**Actual:** Project timeline is not displayed for below QA services

**Expected:** Should display the timeline as 3-6 days

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted

**Comment by SathyaJayabal** [comment]
please fix also #3689

**Comment by nithyaasworld** [comment]
This is no more an issue in the new catalog. Hence closing this.

**Comment by nithyaasworld** [comment]
Verification video: 
[3688 issue verification.zip](https://github.com/appirio-tech/connect-app/files/4254317/3688.issue.verification.zip)
