### ISSUE TITLE
Date repeated in the table in two columns (Projects, Status Date)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#369]
### Expected behavior
-----------------------------------------------------------------
Must not repeat the data in two columns (Projects, Status Date)

### Actual behavior
-----------------------------------------------------------------
Date repeated in the table

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Check the (Projects, Status Date) columns

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_23-07-48](https://cloud.githubusercontent.com/assets/4592712/18965148/9552e4ee-8699-11e6-95f9-ec71fdf837c0.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid. UX improvement: created date vs last update date.

**Comment by parthshah** [comment]
Change copy Status update -> Last updated

**Comment by parthshah** [comment]
fixed
