### ISSUE TITLE
There is no link to go back to the connect if user encounters Server Error 500

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3691]
https://www.screencast.com/t/npMZjb6rN

1. Open the Application and Login as valid user (Manager)(portrait)
2. Click + New Project > Solutions > QA Services (23-08-2019)
3. Enter a long name and description
4. Fill the rest of the details and create a project
5. When the Server Error 500 is shown; try to go back (Need to use browser 

**Actual:** There is no link to go back to the connect if user encounters Server Error 500

**Expected:** Should have a link to go to connect dashboard

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P4

**Comment by SathyaJayabal** [comment]
@codejamtc , accepted
