### ISSUE TITLE
Drop-down content hide from below 

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3693]
### Expected behavior
Tab content shoud properly visible.

### Actual behavior
Drop-down content hide from below when collaspe. 

### Steps to reproduce the problem
- Open the Application and Login as valid user (Customer).
- Click + New Project > QA & Testing: Basic Details > App Definition  
-  Observe the "What kind of support do you want on your project?*" content after the next
-  Content hide from below

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73515219-92be3980-441a-11ea-9831-2603ad1d1c5e.png)

#### Environment
   - OS: Windows 10 
   - Browser (w/version): IE11 
   - User role (client, copilot or manager): Customer
   - Account used: topcoderconnect+Customer@gmail.com

**Comment by Krishna1507** [comment]
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment]
@Krishna1507 , accepted
