### ISSUE TITLE
Don't request Org Configs if user doesn't have org ids

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3698]
Currently, for users who don't have orgids we still are requesting Org Configs and getting error 400:

![image](https://user-images.githubusercontent.com/146016/73911148-39f41280-48ec-11ea-8c80-231e840c7779.png)

We can avoid this extra call if we stop requesting Org Configs in case the user doesn't have any org ids.

@vikasrohit could you please confirm that this would be the desired behavior?

**Comment by vikasrohit** [comment]
Yes, we should not make that call if we don't have any org id (group id) for the user. Thanks for logging it. I am marking it in 2.5.2 for now, please feel free to suggest if have enough for that milestone.

**Comment by vikasrohit** [comment]
@maxceem is it possible to include this in current release? It is not critical to have, so we can move it to next release, if we haven't started or if it makes sense to collect this issue for next CF.

**Comment by maxceem** [comment]
We didn't start yet. As it's good for CF and not critical, I propose to leave for the next release via CF.

**Comment by maxceem** [comment]
This is done via c0908dbebb1e913babd8942728ea0ec4f62bf5da and pushed to DEV.

Ready for testing.

**Comment by drasticdpk** [comment]
Verified on Dev env :
![image](https://user-images.githubusercontent.com/25297859/76512557-fd807d00-647c-11ea-8be8-3883c4a6a88f.png)

Reference Issue : 
https://github.com/appirio-tech/connect-app/issues/3736

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects?sort=lastActivityAt%20desc
CustomerUser/appirio123
Verified on prod, working as expected.

![image](https://user-images.githubusercontent.com/62358241/78235438-45cc1180-74f6-11ea-9d7e-2317e1cc9f0d.png)
