### ISSUE TITLE
Project creation: full device deselection should not be allowed

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#37]
After a user selects a device (one or more), they should not be allowed to get into a state when no devices are selected, which currently will generate an error message. If only one device is selected, it can be deselected only by selecting an alternate device.

**Comment by mahestro** [comment]
Challenge live https://www.topcoder.com/direct/contest/detail.action?projectId=30055195

**Comment by mahestro** [comment]
Done - https://www.topcoder.com/direct/contest/downloadSoftwareSubmission.action?projectId=30055195&submissionId=515254

Needs to be merged.

**Comment by fnisen** [comment]
@mahestro can you merge yourself (open a pull request)? Or do you need someone from our team to do it? If so, please assign to @vikasrohit

**Comment by mahestro** [comment]
Was about to mention that. I can starting merging... if you're not afraid of me breaking things.. @ajefts will have material to keep writing the book of "mahestro breaks things"

**Comment by fnisen** [comment]
I'm not worried, go ahead. : ) And anyway, you haven't broken anything in Connect itself yet.

**Comment by mahestro** [comment]
Perfect, it will be my pleasure. To merge, not to break things btw.
