### ISSUE TITLE
[Filter] - All Statuses option must be set first in item list

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#370]
Expected behavior
------------------------------------------------------------

- The All Statuses item must be first option in item list.

- This is the general behavior for drop down list also see "Project Type", All Types item is displayed first!

Actual behavior
------------------------------------------------------------

- The All Statuses item is displayed as second option.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager user role.

- Press on "Filters" option.

- Expand Status drop down list.

- Observe the second option with name "All Statuses".

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager user role
Account used: pat_monahan

![all-statuses](https://cloud.githubusercontent.com/assets/5114907/18965174/bc3f2884-8684-11e6-8c73-a1611ceb7d0d.png)

**Comment by mahestro** [comment]
It's intentional. Sorry, not valid.
