### ISSUE TITLE
Don't show full name, working hours and local time for invited users

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3701]
This is only for invited users.

If we know user handle - show handle (big instead of name).
If we don't know handle - show email (big instead of name).

![image](https://user-images.githubusercontent.com/146016/73935413-6d9a6100-491b-11ea-91d6-3d3eaa6dada9.png)

This task should be also done in Project Service - it should not return full name, working hours and local time for invited users.

**Comment by vikasrohit** [comment]
@maxceem do you think we would be able to wrap this in Feb release?

**Comment by maxceem** [comment]
> @maxceem do you think we would be able to wrap this in Feb release?

Yes, we can. Should we still show the photo? It feels a photo is also private information and should not be shown for invited users.

**Comment by vikasrohit** [comment]
Lets not show any info other than handle or email (if invited via email), for the invited users.

**Comment by maxceem** [comment]
This is done client-side https://github.com/appirio-tech/connect-app/commit/291570c017fa18ddffcf19e06bd0072c6adc56c5 and server-side https://github.com/topcoder-platform/tc-project-service/commit/e24ea3a5bf759da1564badc8051b15ca4701d6e4.

It has been deployed to DEV and ready for testing.

**Comment by nithyaasworld** [comment]
@maxceem 

1. When invited using handle, it shows a dummy email.
![image](https://user-images.githubusercontent.com/5114190/75231063-d66a5000-57da-11ea-814b-92fe286e512d.png)

2. When invited using email, it shows both email and handle. Please confirm if its okay to show **handle** if the user is invited by email.

![image](https://user-images.githubusercontent.com/5114190/75231194-0c0f3900-57db-11ea-88df-ad03796a3883.png)

**Comment by nithyaasworld** [comment]
3. After accepting the invitation, it shows full name, handle and working hours. But Email is not shown. Please confirm if this is okay.

![image](https://user-images.githubusercontent.com/5114190/75234366-7bd3f280-57e0-11ea-9244-b091c10e5aff.png)

**Comment by vikasrohit** [comment]
@nithyaasworld 
1 .the dummy email is a masked email which we in dev environment all existing users at the time of data load in dev. However, we should not see the email of an invited user if user is invited via handle. I thought we fixed that @maxceem with https://github.com/topcoder-platform/tc-project-service/pull/466 and https://github.com/topcoder-platform/tc-project-service/pull/467.
2. Showing handle for a user invited via email is okay I guess for now, but I would like to ask @maxceem if we can get rid of that as well, if possible. We want to keep the rule simple, for invites user would see what he/she used to invite user.
3. Yes, email should not be shown (except the case where user is invited via email only) for any user except admins.

**Comment by maxceem** [comment]
@nithyaasworld 1 and 2 the email shouldn't be shown to non-admin users. I cannot reproduce this issue with `pshah_manager`. Could you, please, let me know which user did you use for testing so you can see emails in invitations?

@vikasrohit regarding 2. At the moment it's not easy to quickly change this. But if we need this we can move towards it during migrating to RESTful invitation API. There is one feature though, which relies on knowing the handle. client-side we validate that already invited is not invited the second time. If we don't do such validation then we could invite the same user by email and by the handle. We can still have this validation server-side though.

**Comment by vikasrohit** [comment]
@maxceem I am okay with showing handle for now. Lets create separate issue to track the hiding of handle for invites by email. I think we can still show validation errors on client side, once we have the md5 of emails available in the responses of `/members` and `/invites` endpoints. At that point, we can equate the md5 of member's email with md5 of invite's email.

**Comment by maxceem** [comment]
Created a follow-up issue to not show handle https://github.com/appirio-tech/connect-app/issues/3722

**Comment by maxceem** [comment]
@nithyaasworld 1 and 2 the email shouldn't be shown to non-admin users. I cannot reproduce this issue with pshah_manager. Could you, please, let me know which user did you use for testing so you can see emails in invitations?

**Comment by lakshmiathreya** [comment]
Verified on Prod: handle or email is seen based on whats used in the invite. Once User accepts - Full name, working hours and local time is shown. @vikasrohit Pls clarify if this is as per reqmt.

**Comment by vikasrohit** [comment]
> handle or email is seen based on whats used in the invite. Once User accepts - Full name, working hours and local time is shown. @vikasrohit Pls clarify if this is as per reqmt.

Yes, exactly.

**Comment by nithyaasworld** [comment]
Verified this in Dev Env:

No:2 will be addressed via https://github.com/appirio-tech/connect-app/issues/3722

No:3 Email is not shown even to Admin users **after the user has accepted the invite.** Created a new ticket https://github.com/appirio-tech/connect-app/issues/3732

No:1 was initially verified using Admin user credentials. So its not a valid issue.
