### ISSUE TITLE
'You're Invited' button is removed only after a page-refresh

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3702]
1. Login as Copilot in **Dev env**
2. Click on a project which has 'You're invited' button
3. Join the project
4. Click the back button present in the UI 
5. Check that UI still shows 'You're invited' button for the project this user just joined. It disappears only after a page-refresh.

Expected:
'You're invited' button should get disappeared after step:4 above. It should not require the user to refresh the page to get it disappeared.

video: 
[button not going.zip](https://github.com/appirio-tech/connect-app/files/4167581/button.not.going.zip)

**Comment by RishiRajSahu** [comment]
@nithyaasworld @drasticdpk this works fine now, could you please close this by validating you side as well ?

**Comment by vikasrohit** [comment]
@RishiRajSahu closing the issue for now. Please reopen the issue if the issue still persists.
