### ISSUE TITLE
Specification tab for v2 projects are not loading

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3707]
### Expected behavior
Specification tab should load 

### Actual behavior
It is showing empty page without any error in console

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Connect Manager
- Account used: N/A

**Comment by vikasrohit** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
@vikasrohit I've tried the project `5000` and it works well for me:

![image](https://user-images.githubusercontent.com/146016/74926526-fed80000-5410-11ea-8fee-4c81d39bdd95.png)

Do you have an example of a project where you see an empty page on the specification tab?

**Comment by maxceem** [comment]
For v2 projects we don't set `templateId`, but we have to set product template key inside details field. Do you know if the project which doesn't have specification tab loaded the product template key is specified?

**Comment by vikasrohit** [comment]
That was the key. I followed up with project owners and found that they are not sending the `products` in details json now when creating projects via api. I have asked them to add it back which should fix the situation.
Closing the issue for now. Thanks for debugging.
