### ISSUE TITLE
[Search] - ignrore two or more blankspaces

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#371]
## Expected behavior
- Ignore the blank spaces in search text.
## Actual behavior
- The results are not displayed even the text is correct but contain two blank spaces.
## Steps to reproduce the problem
- Login into application as pat_monahan role.
- From Dashboard section complete search field with "Other Work  test" (two blank spaces added after Work word).
- Press enter to perform the search.
- To observe results set the text "Other Work test" and perform the searching.
## Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager role
Account used: pat_monahan

![a](https://cloud.githubusercontent.com/assets/5114907/18965446/f4cfca72-8685-11e6-9e35-0ed94fc72b54.png)

![2](https://cloud.githubusercontent.com/assets/5114907/18965450/fceda328-8685-11e6-804b-7e54a20fd76c.png)

**Comment by mahestro** [comment]
Valid. Can be improved.

**Comment by parthshah** [comment]
Vikas - assigning this to you since this is related to Search bar that you worked on.

**Comment by vikasrohit** [comment]
@fnisen @parthshah Do we really want to remove double spaces in front end? Ideally it should the search engine which should optimize itself for this case. I guess when tokens are generated in search engine, double or more spaces should behave as single space.

**Comment by fnisen** [comment]
Ooh, agree, seems like back end should handle it. @parthshah?

**Comment by parthshah** [comment]
Ah .. i thought this was for search with just spaces, no?

**Comment by fnisen** [comment]
The specific issue is when you search for a phrase, but insert extra spaces between your keywords.

**Comment by fnisen** [comment]
@parthshah is this going to be addressed as part of your search upgrade? I've also seen issues with search not being able to handle special characters, such as apostrophe.
