### ISSUE TITLE
P2: Update Reviewed Project Status Logic

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3719]
**Objective:** Automate Reviewed to Cancelled logic based upon SFDC event trigger, to keep project pipeline clean.

<p></p>

**Requirements:**

- When a Salesforce opportunity is put into "Lost" status, the Connect project should be moved from Reviewed to Cancelled status and apply the reason code provided by Salesforce.

<p></p>

**Enablement Notes:**

Connect must be able to understand the association between a SFDC lead (created when a new project was created) and a SFDC opportunity (when the lead is marked as Qualified and is converted into a lead).

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/3660446

**Comment by vikasrohit** [comment]
Tested, project is being cancelled on opty lost.
