### ISSUE TITLE
Don't show "handle" for users invited by "email

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3722]
Follow up from https://github.com/appirio-tech/connect-app/issues/3701#issuecomment-591389279

The main idea of this ticket:
- if a user has been invited by `handle` we only show `handle` for such invitations, but we don't show `email` (except of Topcoder Admins)
- if a user has been invited by `email` we only show `email` for such invitations, but we don't show `handle` (except of Topcoder Admins) 
   - `email` is shown as masked like `a***b@g***l.com` for all the users except:
       - Topcoder Admins
       - user WHO created invite by `email`, can still see the email fully

**Comment by maxceem** [comment]
> I am okay with showing handle for now. Lets create separate issue to track the hiding of handle for invites by email. I think we can still show validation errors on client side, once we have the md5 of emails available in the responses of /members and /invites endpoints. At that point, we can equate the md5 of member's email with md5 of invite's email.

I just would like to note that we don't know the "email" of members client-side. So to implement such validation logic we would have to also add "hadhEmail" to members.

**Comment by vikasrohit** [comment]
Yes, we should be good with hash of the email.

**Comment by maxceem** [comment]
We only need email hash for client-side validation that when we invite a new member there is no invite with such email and there is existent member with such email as we had such requirement before.

Though, if it's not critical, then it would much more straightforward to remove this client-side validation as we still have server-side validation.

If so, then I guess we should also remove `hashEmail` for invites, which we recently added server-side in a separate branch.

**Comment by maxceem** [comment]
Actually, there is one case, where we still need `hashEmail` https://github.com/appirio-tech/connect-app/issues/3413. It's when we invite several users by email, we get response from the server and we should know which emails were successfully invited, to remove them from the input.

And here is the issues where we are tracking client-side validation of invites by email https://github.com/appirio-tech/connect-app/issues/3392 which are considering to skip.

But again, in CREATE invite endpoint we still have to return `hashEmail` to identify which invites were created successffully.

**Comment by vikasrohit** [comment]
Hmm, reading both of your concerns, I think we might end up with showing hash of emails (only for invites using email) only for invite creation endpoint. What do you think?

**Comment by maxceem** [comment]
> Hmm, reading both of your concerns, I think we might end up with showing hash of emails (only for invites using email) only for invite creation endpoint. What do you think?

It feels for me, that the complexity of having `hashEmail` is more that benefit of client-side validation while we already having server-side validation. 
So I like the approach where we don't add `hashEmail` at all, remove client-side validation and only return `hashEmail` in the create invite endpoint so we can remove already invited emails from the input.

**Comment by vikasrohit** [comment]
Yes, leave the `hashEmail` for now to avoid any security concern. Further, I think we can remove requirement of `hashEmail` even for the create invite endpoint by passing a unique random id in the payload for each invite object and preserve it on server side, return it in server response as well and finally on front end use this id again to identify which invites got success and which failed. Is it something you think is possible?
I know passing additional id in post body might not align with REST nomenclature but I think we can name that variable which clearly conveys its use e.g. `nonce` or `seq_no` or similar.

**Comment by maxceem** [comment]
@vikasrohit yeah, this is possible though it feels for me quite the same as if we return `hashEmail` only for create invite endpoint.

On the second though, what if we avoid using any of `hashEmail` and `nonce` for create invite endpoint and just return `email` in the create invite endpoint as it is? The user who invited a user by `email` does already knows the email. This way we wouldn't introduce any additional logic for this particular case.

If we go this way, there would appear only one inconsistency: when we just invited someone by email we can see the email, but after we reloaded the page the email became masked. Though we can also fix this and we can show `email` in the invitations to the users WHO created these invitations. I guess this would be quite comfortable and consistent approach:
- users who invite other users by email can see invites with full email so it would be always clear for users whom they already invited
- but users cannot see emails in invites they didn't invite (email for other invites would be masked)

**Comment by vikasrohit** [comment]
> I guess this would be quite comfortable and consistent approach:
users who invite other users by email can see invites with full email so it would be always clear for users whom they already invited
but users cannot see emails in invites they didn't invite (email for other invites would be masked)

I think we discussed this earlier somewhere. The only negative of this approach is that we have to be sure that we don't leak the any other information in any case for invite endpoint which allows a bad user to fetch more information about the invited person. But I think that is the risk we have to live with. So, please go ahead with your suggested approach.

**Comment by maxceem** [comment]
@vikasrohit this is implemented in the branch `feature/restful-invites`. Though I've noticed one disadvantage during testing the implementation:

![image](https://user-images.githubusercontent.com/146016/77307787-f5d99780-6d0a-11ea-87f3-363fa64a5f7a.png)

Do you think we should anything about it?

**Comment by codejamtc** [comment]
Project: https://connect.topcoder-dev.com/projects/8943/
Users: 

Invitations sent via ``
Manager ``
A user without administrative privileges ``

https://www.screencast.com/t/NSwbciWej

- [ ] - If a user has been invited by `handle` we only show `handle` for such invitations, but we don't show `email` (except of Topcoder Admins) - {Fixed}
- [ ] - If a user has been invited by `email` we only show `email` for such invitations, but we don't show `handle` (except of Topcoder Admins) - {Fixed}
   - `email` is shown as masked like `a***b@g***l.com` for all the users except:
       - [ ] - Topcoder Admins - {I can see an issue here, when we invite a member via `email` and check that project member team using an admin user. The email is still displayed as masked}

![image](https://user-images.githubusercontent.com/42398485/77434786-60dcaa00-6daf-11ea-8cad-12f8f064ecb9.png)

Video Timeline 1:50 - 3:03  (Issue 2:47)(Issue 2:55)
       - [ ] - user WHO created invite by `email`, can still see the email fully - {This is full-filled}

**Comment by maxceem** [comment]
@codejamtc only user with `administrator` role can see email without masking, you may use `topcoderconnect+Admin@gmail.com` user. Users with `Connect Admin` role like `topcoderconnect+AccountManager` still can see email only with a mask.

**Comment by codejamtc** [comment]
@maxceem This is what I can see when I logged in as `topcoderconnect+Admin@gmail.com`

https://connect.topcoder-dev.com/projects/8943

![image](https://user-images.githubusercontent.com/42398485/77451464-b53d5500-6dc2-11ea-93d7-f3b1846fce4a.png)

**Comment by lakshmiathreya** [comment]
As seen by Admin user on Dev:
<img width="1633" alt="Screenshot 2020-03-25 at 5 54 29 PM" src="https://user-images.githubusercontent.com/51733042/77536238-0da74c00-6ec2-11ea-84eb-b39718de96b0.png">

**Comment by lakshmiathreya** [comment]
As described above - Verified the same scenarios on Prod with Copilot, Admin, Copilot manager, Connect Manager and Account Manager roles:
1. If a user has been invited by handle we only show handle for such invitations, but we don't show email (except of Topcoder Admins) 
2. If a user has been invited by email we only show email for such invitations, but we don't show handle (except of Topcoder Admins) 
3. email is shown as masked like a***b@g***l.com for all the users except:
Topcoder Admins
4. user WHO created invite by email, can still see the email fully
