### ISSUE TITLE
[$50] [Project ES Processor] User who creates the project cannot be used to search project by

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3723]
This issue has to be fixed in https://github.com/topcoder-platform/project-processor-es
This issue is relative to https://github.com/appirio-tech/connect-app/issues/3496

When we create a project using Project Service API the user who creates the project is automatically added as a member fo the project.

Though if we try to search this project by such a user `firstName`, `lastName`, `handle` or `email` we wouldn't find this project.

The reason for this is, that when we create a project we send a Kafka event with newly added project and `project-processor-es` adds such a project to the ES index, together with the list of members (where we have one user who creates the project).

Though when we add any member in ES index, we have to additionally augment member object with user details, see https://github.com/topcoder-platform/project-processor-es/blob/feature/bulk-milestone-updates/src/services/ProcessorServiceProjectMember.js#L58-L72.

So we should do the same, when we create a new project and add additional details to the member object.

For this purpose, we have to create some reusable utility method, which can be used to added user details in both places: when we create a project and when we add a member.

**Comment by narekcat** [comment]
@bug-bash-helper assign

**Comment by narekcat** [comment]
@bug-bash-helper  https://github.com/topcoder-platform/project-processor-es/pull/28  is ready for review

**Comment by codejamtc** [comment]
@maxceem I can't see the changes on `dev`

https://www.screencast.com/t/Wwr1QaWj

Created a new project using `topcoderconnect+Customer@gmail.com`

`firstName` = `Topcoder Edit`
`lastName` = `Connect Test`
`handle` = `TopConnCustomer`
`email` = `topcoderconnect+Customer@gmail.com`

Logged in as `Manager` and perform the search via the above parameters to the search


https://www.screencast.com/t/Wwr1QaWj

**Comment by maxceem** [comment]
@vikasrohit could you please help me here.

I can see, that when I create a project on DEV, the first/lastname and email are not populated for the user who created the project.
But locally it works for me.

Could you please, check the logs of `project-processor-es` during project creating, there should be some of these logs records: https://github.com/topcoder-platform/project-processor-es/blob/develop/src/common/helper.js#L175-L188

**Comment by narekcat** [comment]
Hello @maxceem .  Must I add fix this issue or there will be new bug bush for that ?

**Comment by maxceem** [comment]
Hi @narekcat. No need to add a fix, thanks. It works locally for me, not sure why it doesn't work when deployed to the DEV environemnt, we would debug it first.

**Comment by narekcat** [comment]
Ok @maxceem .

**Comment by vikasrohit** [comment]
@maxceem it seems it is failing to fetch details with member api:

```
Cannot populate member (userId:xxxxxxxxxx) with user details.
```

Did we merge the fix, where it was not passing `userId:` in query param, we made to project-processor-es on production?

**Comment by maxceem** [comment]
@vikasrohit that fix was for Project Service, project-processor-es already uses correct request https://github.com/topcoder-platform/project-processor-es/blob/feature/link-attachments/src/common/helper.js#L155

**Comment by maxceem** [comment]
@vikasrohit is there any error details in the next log `Error during populating member ...`?

**Comment by vikasrohit** [comment]
@maxceem it should now be fixed. I think there were some env variables missing for the project processor es. I just added them and rebuilt the processor.

**Comment by maxceem** [comment]
@codejamtc this should work good now. Could you please test it again.

**Comment by codejamtc** [comment]
@maxceem I can't see the changes on `dev`

Created a new project using `topcoderconnect+Customer@gmail.com`
https://connect.topcoder-dev.com/projects/9044

`firstName` = `TC Customer First` 
`lastName` = `TC Customer Last`

- Sometimes I can see the search list displays projects that `topcoderconnect+Customer@gmail.com` is not part of (eg: https://connect.topcoder-dev.com/projects/8600)

`handle` = `TopConnCustomer` **(Not working)**
`email` = `topcoderconnect+Customer@gmail.com` **(Not working)**

Logged in as `Manager` and perform the search using the above parameters to the search

https://www.screencast.com/t/BZ3Pmzv2Z

**Comment by maxceem** [comment]
> Sometimes I can see the search list displays projects that topcoderconnect+Customer@gmail.com is not part of (eg: https://connect.topcoder-dev.com/projects/8600)

When we search using the search field:

![image](https://user-images.githubusercontent.com/146016/77996379-2edec100-7336-11ea-8d9c-c62b66a5e4d2.png) the search is performed not only by users but also by project `name`, `description`, `type` and `ref code`. That's why some other projects can be found, not only by members.

> handle = TopConnCustomer (Not working)
> email = topcoderconnect+Customer@gmail.com (Not working)

Should be working now, could you, please, try again.

**Comment by codejamtc** [comment]
https://www.screencast.com/t/lONsy6ttxC0I

**Comment by codejamtc** [comment]
@lakshmiathreya This is not an admin account limitation, In the `Customer` account there are fewer test data to test this one.

**Comment by lakshmiathreya** [comment]
@codejamtc this seems similar to your observation in Dev. Pls move to Prod QA Pass if so. <img width="1656" alt="Screenshot 2020-04-03 at 5 31 22 AM" src="https://user-images.githubusercontent.com/51733042/78310848-b746a700-756c-11ea-8585-e6e21ad185ac.png">
<img width="1680" alt="Screenshot 2020-04-03 at 5 31 56 AM" src="https://user-images.githubusercontent.com/51733042/78310851-bca3f180-756c-11ea-899b-91d1a83c1d8c.png">
