### ISSUE TITLE
"Send Invite" button gets disabled

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3724]
1. Login as any user (Example: Manager)
2. Click on any project the user is part of and Click on 'Manage Invitations' present under Team section
3. Enter email id of a customer who **has not signed up** with Topcoder and click 'Send Invite'

Actual:
Nothing happened. Send Invite button just got disabled. I am also not seeing any failed api calls. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/5114190/75415267-1fdcab80-5951-11ea-9744-073313a93a73.png)

**Comment by nithyaasworld** [comment]
CC: @maxceem @vikasrohit @lakshmiathreya 

This was found during Smoke test yesterday by macs054

**Comment by vikasrohit** [comment]
@maxceem what was the reason for this?

**Comment by nithyaasworld** [comment]
Just noticed that the invitation is actually sent to the email entered. Just that the UI is stuck with a disabled 'Send Invite' button.

![image](https://user-images.githubusercontent.com/5114190/75416091-6c28eb00-5953-11ea-9549-af705c95e7fd.png)

**Comment by maxceem** [comment]
@nithyaasworld the reason was at the backend. It returned the wrong response which caused this to break, though the actual operation succeded.

It's already fixed and pushed to DEV and ready for testing.

**Comment by nithyaasworld** [comment]
Thanks @maxceem for the quick response. Verified with both existing and non-existing user emails.

**Comment by nithyaasworld** [comment]
Verified in Production.
