### ISSUE TITLE
Show refresh dialog when looker session is expired for reports

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3727]
Remove refreshing session by the timer, and show the modal with **Refresh** button instead, when the looker session is expired.

**Comment by maxceem** [comment]
Done as a HOTFIX via PRs:
- DEV: https://github.com/appirio-tech/connect-app/pull/3728
- PROD: https://github.com/appirio-tech/connect-app/pull/3729

**Comment by nithyaasworld** [comment]
@maxceem How should we test this in Production? Thanks.

CC: @drasticdpk @lakshmiathreya

**Comment by maxceem** [comment]
> @maxceem How should we test this in Production? Thanks.

@vikasrohit, could you please, assist here, as I'm not sure how to do this. I only could properly test it locally with mock data.

**Comment by maxceem** [comment]
A new requirement from Vikas:

> Yes, please go with full page refresh because I don't see this modal to be in operation for most of the users. Can you also raise an event to analytics to track such modal popup occurance. I am trying to get some idea about how many time this pop up actually shows i.e. how many times people actually keep the reporting tab opened for long time.
