### ISSUE TITLE
[Search] - infinite loading displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#373]
Expected behavior
------------------------------------------------------------

- Return the project available or return the invalid message.

Actual behavior
------------------------------------------------------------

- Infinite loading is displayed.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager role.

- Complete search field from the top with a name of existing project "!@#$%^&*()_+{}|":?><>??".

- Press enter to perform search.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager role
Account used: pat_monahan

![infinte](https://cloud.githubusercontent.com/assets/5114907/18965876/a16b63a8-8687-11e6-9a6a-fea99a369484.png)

**Comment by mahestro** [comment]
Valid.
