### ISSUE TITLE
Email is not shown for Admin users too

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3732]
Email is not shown in the Tooltip even for Admin users.

Tested in Dev environment with Admin user credential.

![image](https://user-images.githubusercontent.com/5114190/75539087-aec7f180-5a3f-11ea-9db4-1d441466850c.png)

**Comment by nithyaasworld** [comment]
[Requirement:](https://github.com/appirio-tech/connect-app/issues/3701#issuecomment-590834615)
[
3. Yes, email should not be shown (except the case where user is invited via email only) **for any user** except admins. ](url)

**Comment by nithyaasworld** [comment]
cc: @maxceem

**Comment by lakshmiathreya** [comment]
@drasticdpk

**Comment by drasticdpk** [comment]
Verified on Dev Server
User Role : Admin 
![image](https://user-images.githubusercontent.com/25297859/75697620-76414580-5cd5-11ea-971e-fdadbf46ba6b.png)

User Role : Copilot Manager ( other than Admin) 
![image](https://user-images.githubusercontent.com/25297859/75697964-f49de780-5cd5-11ea-943d-106dd504207e.png)

**Comment by vikasrohit** [comment]
This has been deployed to production. and there is one change in original requirements: admins means administrator users which does not include `Connect Admin` role. Please contact @lakshmiathreya for credentials.

**Comment by vikasrohit** [comment]
Closing. It seems to work fine for me.
