### ISSUE TITLE
[$30] Sun icon shows online when it should show offline

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3733]
At the left sidebar we are showing users with their local time and working hours. When it's currently working hours of the user we are showing `SUN` icon. And when it's not working hour now, we should show the `MOON` icon.

Somehow I can see for my user the SUN is shown, though it's past working hours at the moment:

![image](https://user-images.githubusercontent.com/146016/75540563-39681b00-5a57-11ea-881d-e71e64e40717.png)

**Comment by sumitdaga** [comment]
@bug-bash-helper assign

**Comment by sumitdaga** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3753 is ready for review

**Comment by maxceem** [comment]
@sumitdaga small improvement required https://github.com/appirio-tech/connect-app/pull/3753#pullrequestreview-372501628

**Comment by sumitdaga** [comment]
@maxceem  fixed!

**Comment by sumitdaga** [comment]
@bug-bash-helper #3753 is ready for review

**Comment by satkanhub** [comment]
PASSED
![image](https://user-images.githubusercontent.com/51492004/76691705-0d02f000-664e-11ea-968f-d15fdbb033e3.png)

PASSED
![image](https://user-images.githubusercontent.com/51492004/76691716-518e8b80-664e-11ea-9355-5f7b93fc68f4.png)

FAILED
![image](https://user-images.githubusercontent.com/51492004/76691722-6a973c80-664e-11ea-8aa5-0f4e7f63536d.png)

PASSED
![image](https://user-images.githubusercontent.com/51492004/76691731-8bf82880-664e-11ea-83f6-401b02600ce6.png)


Please review the fix again. QA Failed.
[3733.zip](https://github.com/appirio-tech/connect-app/files/4333437/3733.zip)

@drasticdpk @lakshmiathreya @maxceem Could you please update the status, as I do not have the access.

**Comment by maxceem** [comment]
This is indeed not applied on DEV. Will update today.

**Comment by satkanhub** [comment]
Working as expected.

[3733 New.zip](https://github.com/appirio-tech/connect-app/files/4340321/3733.New.zip)

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects/14178/
CustomerUser/appirio123
Verified on prod, working as expected.

![image](https://user-images.githubusercontent.com/62358241/78259788-c1d85080-751a-11ea-83ed-8886d195c3e0.png)
