### ISSUE TITLE
Update Project Type icons

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3737]
New icons [connect-catalog-icons.zip](https://github.com/appirio-tech/connect-app/files/4274447/connect-catalog-icons.zip)

**Comment by satkanhub** [comment]
All the project icons to be updated, as mentioned in the zip file.

![image](https://user-images.githubusercontent.com/51492004/76554450-37aa4880-6496-11ea-8c16-2eae7df2a0bd.png)

**Comment by maxceem** [comment]
Done via a138e75c304e5bf5bd558288bbfd9be596bc3cbb

Icons are also updated on DEV environment for all visible project templates to match the requirements.

**Comment by maxceem** [comment]
After release, the icons should be also updated on PROD for Project Template and Project Types, fyi @vikasrohit.

**Comment by vikasrohit** [comment]
@maxceem do we need to update the icons name in templates? I was assuming that we kept the icons name same as they are currently.

**Comment by maxceem** [comment]
Ah, yes, I've updated the names in templates, so new icon names do not collide with old names which we still use on for the phases.

![image](https://user-images.githubusercontent.com/146016/77042408-958ae300-69f6-11ea-91e5-42b4627eacac.png)

Is that ok? Or is it too hard, and we should revert them back and use old names for icons so we don't have to update project templates on PROD?

**Comment by codejamtc** [comment]
@maxceem I can't see the changes on `dev` https://connect.topcoder-dev.com/new-project/scoped-solutions. [https://github.com/appirio-tech/connect-app/issues/3737#issuecomment-601025026]

Old blue icons are displayed. The new icons are light green provided https://github.com/appirio-tech/connect-app/files/4274447/connect-catalog-icons.zip 

https://www.screencast.com/t/9upnNwL7o9N

**Comment by maxceem** [comment]
> I can't see the changes on dev https://connect.topcoder-dev.com/new-project/scoped-solutions. as mentioned here #3737 (comment)

@codejamtc we only updated icons for each Project Type, but not the background color. We use a blue background because we currently use the **blue** theme for Connect App, and we didn't switch to a new **green** color scheme which is used in the new design. So in all the places where new design uses green color we replace it with our current blue color.

> I can see phase names and icons are updated according to the comment here #3737 (comment)

These icons weren't updated, we use old icons there. So this screen shows old icons, and this is as per current requirements. fyi.

**Comment by codejamtc** [comment]
@maxceem I will check the icons again and update

**Comment by codejamtc** [comment]
@maxceem Other than `02_buy_capacity.svg` and `10_salesforce_implementation.svg`, all the other icons are updated

**Comment by maxceem** [comment]
> @maxceem Other than 02_buy_capacity.svg and 10_salesforce_implementation.svg, all the other icons are updated

We don't have such Project Templates on DEV at the moment. So there is no place where to update them.

**Comment by codejamtc** [comment]
@maxceem Do we have `add-phase` icon design assets to compare. I have compared the icons with the screenshot you have provided but there are more. (Since I am new to this project, I don't have any idea about the old icons) Sorry about that.

**Comment by maxceem** [comment]
> @maxceem Do we have add-phase icon design assets to compare. I have compared the icons with the screenshot you have provided but there are more. (Since I am new to this project, I don't have any idea about the old icons) Sorry about that.

That's ok, no worries. We don't have the design for the `add-phase` screen as it was done long time ago. We have an older version of the Connect App here https://connect-test01.topcoder-dev.com/projects/8944/add-phase. So you may check that icons now didn't change in comparison with the older version.

**Comment by codejamtc** [comment]
@maxceem Thanks
`add-phase` screen icons and text + all the other icons - verified (Currently I don't have permission to change the labels) 

I don't know if @bug-bash-helper QA Pass In Dev will work

**Comment by maxceem** [comment]
@codejamtc I've invited you to the repository. Please, check your email for the invite and accept it to get permissions for changing labels.

**Comment by coderhacker** [comment]
![image](https://user-images.githubusercontent.com/62358241/78244884-17edc980-7504-11ea-8bcf-26542f763c52.png)
![image](https://user-images.githubusercontent.com/62358241/78244921-289e3f80-7504-11ea-8a8b-d57171b023b7.png)

**Comment by codejamtc** [comment]
@lakshmiathreya ☝️

**Comment by lakshmiathreya** [comment]
@codejamtc The same Project Type icons are seen in Prod - must be evident from the Customer User login too... pls let me know what specifically you'd like me to verify on Prod via Manager/Admin user for this Issue.
