### ISSUE TITLE
New flag for hiding the project estimator

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3739]
As of now with `hidePrice` flag we are hiding only price in estimator component, we need another flag for hiding the complete estimator component. Right now we are hiding it by renaming the type of the `estimation` component because it shows the component if and only if it finds a component of type `estimation`.

**Comment by vikasrohit** [comment]
@maxceem fyi

**Comment by maxceem** [comment]
@vikasrohit should we only hide on the Dashboard page if flag `hideEstimation` is set to `true`?

![image](https://user-images.githubusercontent.com/146016/76185672-dfabe180-620a-11ea-88e6-e75e39b35560.png)

Or should we also hide it during the project creation process?

**Comment by vikasrohit** [comment]
I guess, hiding from every where would be better because in that case we won't have to remove or alter the estimation component in the template and we can hide the component while still keeping its configuration in the template.

**Comment by maxceem** [comment]
Ok. @vikasrohit do we have any template on DEV which you would like to use this feature for? So I would add this flag there and we would use it for testing?

**Comment by vikasrohit** [comment]
`talent-as-a-service` category should be using this feature

**Comment by maxceem** [comment]
Sum up:
- when we render **project creation form**, URL example https://connect.topcoder-dev.com/new-project/talent-as-a-service we might show Estimation component

  ![image](https://user-images.githubusercontent.com/146016/76382510-edd93980-6393-11ea-9d20-07b7af795f93.png)

   The same component after would be rendered inside the **project dashboard page**, URL example http://local.topcoder-dev.com:3000/projects/8910

   ![image](https://user-images.githubusercontent.com/146016/76382459-cbdfb700-6393-11ea-8d2c-75adfa56264a.png)

- if Project Template has flag `hideEstimation` this block should be hidden everywhere.

    ![image](https://user-images.githubusercontent.com/146016/76382598-34c72f00-6394-11ea-8084-e96e1d15ce0c.png)

**Comment by maxceem** [comment]
@vikasrohit this is done and pushed to DEV, see demo video https://monosnap.com/file/QVv7xTjHV2HsAvleHA54ZHyaF6GNlv

Added flag `hideEstimation`.

For the demo, I've slightly updated the `talent-as-a-service` Project Template:
![image](https://user-images.githubusercontent.com/146016/76383295-59240b00-6396-11ea-9f89-350ecce36b9b.png)

![image](https://user-images.githubusercontent.com/146016/76383358-853f8c00-6396-11ea-9132-ba70d12107cc.png)

![image](https://user-images.githubusercontent.com/146016/76383377-9a1c1f80-6396-11ea-8c09-34f50ece64c9.png)

**Comment by vikasrohit** [comment]
Thanks @maxceem I think I wrongly suggested the `talent-as-a-service` category for this issue, I read your question asking sample template in context of #3666. For this issue, I think we have App and QA forms which needs the flag `hideEstimation`.

**Comment by maxceem** [comment]
Ah, ok. Would like me to apply this flag to some other template and remove the changes I did to `talent-as-a-service`?

**Comment by drasticdpk** [comment]
@maxceem @vikasrohit can you please guide us which template has to choose to meet the above scenario. cc @lakshmiathreya

**Comment by maxceem** [comment]
@drasticdpk please, use template https://connect.topcoder-dev.com/new-project/talent-as-a-service for now. I've enabled the estimation section there. So for testing you may create a projects now with estimation section enabled, and observe, that estimation sections present during creating and on the dashboard page.

After, that change the `hideEstimation` to `true` https://monosnap.com/file/OX74jxRZYP2OETrbGghNug3YvwsxgS. And now during creating there should be no estimation component visible.
Also, this component would be hidden on the dashboard page for ALL projects which use this template, no matter created before or after disabling.

**Comment by drasticdpk** [comment]
Reference Project : https://connect.topcoder-dev.com/projects/8921
Template : https://connect.topcoder-dev.com/metadata/projectTemplates/225
[3739_verification.mp4.zip](https://github.com/appirio-tech/connect-app/files/4347441/3739_verification.mp4.zip)

**Comment by maxceem** [comment]
@vikasrohit do we use this flag anywhere on production for QA team to verify it?

**Comment by vikasrohit** [comment]
@maxceem @drasticdpk @lakshmiathreya I have verified it on production and it is working fine. I have applied this flag to an old hidden template (app-old).
