### ISSUE TITLE
[Project Dashboard]Add member filtering

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#374]
### Expected behavior

The member tab should filter out managers and co-pilot and the co-pilot tab should only display  available co-pilot
### Actual behavior

No matter which tab a chosen it will list all user and add according to tab
### Steps to reproduce the problem

Go to project dashboard
Add member by typing username
 wait list to appear 
### Screenshot/screencast

![screenshot 29](https://cloud.githubusercontent.com/assets/8684209/18966127/a19d87b8-86b2-11e6-9f25-07d3f44920be.png)
![screenshot 31](https://cloud.githubusercontent.com/assets/8684209/18966128/a3485480-86b2-11e6-98fa-00a283cc5b82.png)
#### Environment
- OS: Windows 10
- Browser (w/version):Google Chrome Version 53.0.2785.116 m (64-bit)
- User role :Manager
- Account used: Pat Monahan

**Comment by mahestro** [comment]
This is a desired behavior. Project roles are meant to work like that.

Not valid.

**Comment by fnisen** [comment]
Current implementation allows for role flexibility/assignment. Members can be regular members or copilots on a project.
