### ISSUE TITLE
[$50] [Project Service] Search option is not giving the right search result.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3740]
### Expected behavior
The search option should give the  actual search result when the user search for anything. .

### Actual behavior
It is showing "D’oh! Something went wrong" error message even though the same name exist in the project list..

### Steps to reproduce the problem
- Login as topcoderconnect+manager@gmail.com.
- See the project being listed in the dashboard.
- Apply the search for any project with the special character as"/"
- For example apply filter for "ABC/D", "/". 
- Observe the result.

### Screenshot/screencast
Attach or link a resource.
--
![search filter](https://user-images.githubusercontent.com/25297859/75673120-46307d00-5caa-11ea-9ed5-2904ea4adfe8.png)

![image](https://user-images.githubusercontent.com/25297859/75673106-3fa20580-5caa-11ea-80d1-69053ddac0a9.png)

#### Environment
- OS: Windows 
- Browser (w/version): Chrome- Version 80.0.3987.122 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+manager@gmail.com

**Comment by vikasrohit** [comment]
Closing the duplicate issue #3744,  which I created previously.

**Comment by maxceem** [comment]
Sum up:
- This issue most likely has to be fixed in Project Service repo https://github.com/topcoder-platform/tc-project-service branch `cf21`

**Comment by tcchhabra** [comment]
@bug-bash-helper assign

**Comment by tcchhabra** [comment]
@bug-bash-helper unassign

**Comment by tcchhabra** [comment]
@bug-bash-helper assign

**Comment by tcchhabra** [comment]
@bug-bash-helper setting up project service repo so need some more time, maybe next 5-6 hrs more.

**Comment by tcchhabra** [comment]
@maxceem few more mins, testing the fix, sorry it took time to setup project service.

**Comment by tcchhabra** [comment]
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/503 fixing lint issue finally

**Comment by tcchhabra** [comment]
@bug-bash-helper topcoder-platform/tc-project-service#503 is ready for review

**Comment by maxceem** [comment]
@tcchhabra the proposed solution has some issues, please have a look https://github.com/topcoder-platform/tc-project-service/pull/503#pullrequestreview-374060990

**Comment by maxceem** [comment]
@tcchhabra any update to this issue?

**Comment by tcchhabra** [comment]
> @tcchhabra any update to this issue?

still with ES search (it was late at night here yesterday so couldn't wind up), tests are too huge and take a long time to run, anyway I can only run specific test blocks only to speed up process...

**Comment by tcchhabra** [comment]
@bug-bash-helper topcoder-platform/tc-project-service#503 is ready for review

**Comment by drasticdpk** [comment]
Verified on Dev Env 
![image](https://user-images.githubusercontent.com/25297859/76739260-1302e900-6794-11ea-9a29-3df5fce1065a.png)
![image](https://user-images.githubusercontent.com/25297859/76739337-2910a980-6794-11ea-850f-ffaff4cfbdec.png)

**Comment by coderhacker** [comment]
Pass this case '/'

![image](https://user-images.githubusercontent.com/62358241/78160556-c42aa400-7461-11ea-8ae6-5d6204fc4422.png)

Fail This Case 'ABC/D'
![image](https://user-images.githubusercontent.com/62358241/78160838-2683a480-7462-11ea-9e70-1460669eb33e.png)

**Comment by coderhacker** [comment]
@lakshmiathreya @codejamtc

**Comment by codejamtc** [comment]
@coderhacker I think `ABC/D` returns partial matches here

8166 - Has `abc` in the project title
7845 - Has `abc` in the project title
7633- Has `abc` in the ref code
7431- Has `abc` in the project title
7403 - Has `abc` in the ref code

![image](https://user-images.githubusercontent.com/62358241/78160838-2683a480-7462-11ea-9e70-1460669eb33e.png)

**Comment by lakshmiathreya** [comment]
Verified in Prod.
<img width="1676" alt="Screenshot 2020-04-02 at 4 19 33 PM" src="https://user-images.githubusercontent.com/51733042/78241369-e07c1e80-74fd-11ea-9a8a-331926a6fbcb.png">
