### ISSUE TITLE
The updated time is taking the user machine time rather than Server time.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3741]
### Expected behavior
Once the modification is made, the system should show the actual time of Server time.

### Actual behavior
The time shown is taken from the user system/machine time .

### Steps to reproduce the problem
- Login in as Manager.
- Go to the Assets Library .
- Go to the Link button.
- Update the information by Editing. 
- Save the changes. 
- Observe the time being reflected for the LINKs. 

Note : The machine time was  reduce by 2 hrs in my machine, and updated the file and link. 

### Screenshot/screencast
Attach or link a resource.
![time-machine](https://user-images.githubusercontent.com/25297859/75674298-e5567400-5cac-11ea-9b59-748108062ad8.png)
![time-actual](https://user-images.githubusercontent.com/25297859/75674306-e7b8ce00-5cac-11ea-8088-bc363e377ff9.png)

--

#### Environment
- OS: Windows
- Browser (w/version): Version 80.0.3987.122 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+manager@gmail.com

**Comment by maxceem** [comment]
For files, it should already work. For links, it would be fixed as a part of https://github.com/appirio-tech/connect-app/issues/3463.

But let's keep this issue and validate after https://github.com/appirio-tech/connect-app/issues/3463 is done.

**Comment by codejamtc** [comment]
Checked for Links and Files
https://www.screencast.com/t/W5NTjSj3BzZ

**Comment by coderhacker** [comment]
https://connect.topcoder.com/projects/14178/assets
CustomerUser/appirio123
Verified on prod, working as expected.


[3741-prod.zip](https://github.com/appirio-tech/connect-app/files/4421521/3741-prod.zip)
