### ISSUE TITLE
Show files and links from phases in Assets Library

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3748]
### Expected behavior
Files and links from messages inside phases are shown in Assets Library

### Actual behavior
Files and links from messages inside phases are NOT shown in Assets Library

### Steps to reproduce the problem
- Create a phase.
- Add a message on the **Discussions** tab of the phase with a link and attachment.
- Change status of the phase to **Planned** or **In Progress**
- Got the **Assets Library** page and observe that there is no folder with files and links from the phase.
- See a demo project https://connect.topcoder-dev.com/projects/8600/assets

### Screenshot/screencast
Phase with a message with link and file:

![image](https://user-images.githubusercontent.com/146016/75957387-e548b500-5ef4-11ea-9b54-787ebd4537f4.png)

Is not shown in Assets Library:

![image](https://user-images.githubusercontent.com/146016/75957428-f396d100-5ef4-11ea-909c-e27394fec9ab.png)

**Comment by maxceem** [comment]
This is fixed via 69cebb39fd111e29091318c9abadffd574b3e25a together with the related issues:
- Show files and links from phases in Assets Library
- Hide a button to remove files and links from phases in Assets Library
- Fix showing folder "Created By" for files when it created by CoderBot

This has been deployed to DEV and ready for testing.

**Comment by drasticdpk** [comment]
1. Verified  : Show files and links from phases in Assets Library
![image](https://user-images.githubusercontent.com/25297859/76517853-2ce7b780-6486-11ea-81e5-e87b1626acb6.png)
2. Verified : Hide a button to remove files and links from phases in Assets Library
![image](https://user-images.githubusercontent.com/25297859/76518135-ae3f4a00-6486-11ea-8ffc-036c15a81f38.png)
3. Need to confirm : Fix showing folder "Created By" for files when it created by CoderBot 
 In parent grid, created by is showing as **CoderBot** but if you go inside it, there is showing user name instead of coderBot , please confirm. cc @maxceem 
![image](https://user-images.githubusercontent.com/25297859/76518231-d7f87100-6486-11ea-99c2-cbc81feae679.png)

**Comment by maxceem** [comment]
> Need to confirm : Fix showing folder "Created By" for files when it created by CoderBot
In parent grid, created by is showing as CoderBot but if you go inside it, there is showing user name instead of coderBot , please confirm. cc @maxceem

@drasticdpk The thing is the "folder" comes from the "topic" which was created for a phase by a `CoderBot` **automatically**.
While files inside phase any person can create.
So the "topic" which is equal to "folder" for phase would be always created by `CoderBot`. 

We can think to show something else if necessary instead of `CoderBot`. Though I would suggest creating for this another issue to consider it.

**Comment by vikasrohit** [comment]
Showing `CoderBot` is okay as we are already showing it for the various automated system messages.

**Comment by drasticdpk** [comment]
As per above clarification, working as expected i.e it is passed.

**Comment by codejamtc** [comment]
@lakshmiathreya Need admin privileges to add documents/Links to the phases (Can't create a user using `Customer` account.

**Comment by codejamtc** [comment]
Verified in `Prod`: 🆗 Pass
**User:** CustomerUser
https://monosnap.com/file/zXnC2uaChsStgj8D6t19J1nISrAwBk

**Comment by lakshmiathreya** [comment]
Asset inside the Phase is visible only to Copilot and not Project members though it indicates Shared with all Members. Pls clarify @vikasrohit @maxceem <img width="1680" alt="Monosnap 2020-04-03 02-44-16" src="https://user-images.githubusercontent.com/51733042/78301225-6926a900-7556-11ea-9792-81344df21b3b.png">

**Comment by lakshmiathreya** [comment]
Copilot view: <img width="1680" alt="Monosnap 2020-04-03 02-56-42" src="https://user-images.githubusercontent.com/51733042/78301681-13063580-7557-11ea-9055-3f075c37d8e1.png">

**Comment by lakshmiathreya** [comment]
@codejamtc could you post the Customer User view for this Project?

**Comment by codejamtc** [comment]
@maxceem @lakshmiathreya https://www.screencast.com/t/x5tRcRLbrgr

**Comment by lakshmiathreya** [comment]
Seems like Project Member can only see the Phase and Assets if Phase is moved from Draft to Planned. @codejamtc pls add Customer screenshot and set to Prod QA Pass now. cc @maxceem @vikasrohit 
<img width="1598" alt="Screenshot 2020-04-03 at 4 10 15 AM" src="https://user-images.githubusercontent.com/51733042/78306475-143c6000-7561-11ea-9b0e-3fdd232fe634.png">

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/78306540-3efaca00-7509-11ea-8206-c4efe4e77563.png)
