### ISSUE TITLE
[$75] Focus filter input when we open it

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3749]
Follow up from https://github.com/appirio-tech/connect-app/issues/3730

When we show the filter in the table on the [project listing page](https://connect.topcoder-dev.com/projects?sort=lastActivityAt%20desc):
![image](https://user-images.githubusercontent.com/146016/76181948-ea13ae80-61fd-11ea-88d1-b42211ac175e.png)

or at the [Assets Library page](https://connect.topcoder-dev.com/projects/8600/assets):
![image](https://user-images.githubusercontent.com/146016/76181965-fef04200-61fd-11ea-9461-613fe08f4b9d.png)

We should automatically focus the field, so the user can immediately start typing:
![image](https://user-images.githubusercontent.com/146016/76181871-a6b94000-61fd-11ea-9731-5509ffc6a053.png)

This should work for all the fields except "Data" fields.

**Comment by romitgit** [comment]
@bug-bash-helper assign

**Comment by maxceem** [comment]
As no pull request has been provided for 12 hours, this issue is now open for pickup.

**Comment by sanju-singh** [comment]
@bug-bash-helper assign

**Comment by sanju-singh** [comment]
what do you mean by 'except "Data" fields.' which fields exactly. This has to be done for grid filter only, right?

**Comment by maxceem** [comment]
I mean that we should not focus "Date" fields on the Assets Library page:
![image](https://user-images.githubusercontent.com/146016/76399881-5e934c80-63ba-11ea-8a95-c663656bfec3.png)

But we should focus fields in other filters:

![image](https://user-images.githubusercontent.com/146016/76399915-6c48d200-63ba-11ea-99df-63494d4fd32f.png)

**Comment by sanju-singh** [comment]
@bug-bash-helperhttps://github.com/appirio-tech/connect-app/pull/3771 is ready for review

**Comment by sanju-singh** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3771 is ready for review

**Comment by maxceem** [comment]
@sanju-singh there is a couple of issues in the current implementation, please have a look https://github.com/appirio-tech/connect-app/pull/3771#pullrequestreview-373278165

**Comment by sanju-singh** [comment]
@bug-bash-helper #3771 is ready for review

**Comment by satkanhub** [comment]
Video for reference
[3749.zip](https://github.com/appirio-tech/connect-app/files/4326048/3749.zip)

**Comment by sanju-singh** [comment]
@satkanhub , I think you are checking on the wrong branch, you are supposed to take the changes provided in the pull request, merge it locally and then test.

**Comment by maxceem** [comment]
@sanju-singh please, have a look on feedback https://github.com/appirio-tech/connect-app/pull/3771#pullrequestreview-374218685

**Comment by sanju-singh** [comment]
Sorry, I missed that somehow. 
@bug-bash-helperhttps://github.com//pull/3771 is ready for review

**Comment by sanju-singh** [comment]
@bug-bash-helper https://github.com//pull/3771 is ready for review

**Comment by sanju-singh** [comment]
@bug-bash-helper #3771 is ready for review

**Comment by drasticdpk** [comment]
Verified, here is the reference.
[3749_verification.mp4.zip](https://github.com/appirio-tech/connect-app/files/4336805/3749_verification.mp4.zip)

**Comment by codejamtc** [comment]
Verified in `Prod`: 🆗 Pass
**User:** CustomerUser

https://monosnap.com/file/lrVLkjzrVTMS5Z4VMmdB6v4i7n2no9
