### ISSUE TITLE
If it is a Work Project; There is a blank space in between the Project title and Status

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#375]
### Expected behavior
-----------------------------------------------------------------
If it is a Work Project; Must remove the blank space

### Actual behavior
-----------------------------------------------------------------
If it is a Work Project; There is a blank space in between the Project title and Status

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click '+ New Project'
- Select 'Work Project'
- Fill all the required fields and create a project
- Check near the 'Work Project' title

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_23-45-47](https://cloud.githubusercontent.com/assets/4592712/18966469/e34121a2-869e-11e6-9179-dc61c16cb32a.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid. Styling improvement needed.
