### ISSUE TITLE
[$30] User should not be able to apply/changes filter in edit mode

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3750]
Follow-up from https://github.com/appirio-tech/connect-app/issues/3730

On the Assets Library page we can apply filters to the files and links, see page https://connect.topcoder-dev.com/projects/8600/assets

- When we don't have any filter and start editing, we should not be able to apply filter.
- When we apply filter and start editing, we should not be able to change the filter.

![image](https://user-images.githubusercontent.com/146016/76182047-48409180-61fe-11ea-8e07-4eaeb7524162.png)

- We should not be able to click column filters when are editing a file or link.

![image](https://user-images.githubusercontent.com/146016/76182141-ba18db00-61fe-11ea-8768-20d62da7ed1d.png)

**Comment by nqviet** [comment]
@bug-bash-helper assign

**Comment by nqviet** [comment]
@bug-bash-helper PR https://github.com/appirio-tech/connect-app/pull/3757 is ready for review

**Comment by maxceem** [comment]
@nqviet please create a separate pull request for this issue. Don't combine fixes for several issues into one pull request. Here is feedback for this issue https://github.com/appirio-tech/connect-app/pull/3757#pullrequestreview-373243786

**Comment by maxceem** [comment]
Thanks for creating a separate PR for this issue @nqviet. Please have a look on the feedback https://github.com/appirio-tech/connect-app/pull/3783#pullrequestreview-373293379

**Comment by satkanhub** [comment]
Video for reference
[3750.zip](https://github.com/appirio-tech/connect-app/files/4326219/3750.zip)

**Comment by nqviet** [comment]
It seems the patch has not been applied yet. (my side: https://take.ms/pKHB5)

**Comment by maxceem** [comment]
> It seems the patch has not been applied yet. (my side: https://take.ms/pKHB5)

this ticket is not ready for testing by QA team

**Comment by maxceem** [comment]
@nqviet, please let me know your Topcoder handle to process the payment for the issues you have solved.

Thanks.

**Comment by nqviet** [comment]
@maxceem my TC handle is nqv2018

**Comment by codejamtc** [comment]
URL: https://connect.topcoder-dev.com/projects/8942/assets
User:  `topcoderconnect+Manager@gmail.com`

https://www.screencast.com/t/PwypEuoepo79

- When we don't have any filter and start editing, we should be able to apply filter. **Not Fixed** - _User can't apply a filter when we are in edit mode_
- When we apply filter and start editing, we should not be able to change the filter. **- Fixed**
- We should not be able to click column filters when are editing a file or link. **- Fixed**

cc @maxceem

**Comment by maxceem** [comment]
@codejamtc sorry, there is a typo in the description, it should be "When we don't have any filter and start editing, we should **not** be able to apply filter." so the first requirement looks also fixed.

**Comment by codejamtc** [comment]
@maxceem Thanks for the clarification

- When we don't have any filter and start editing, we should be able to apply filter. **Fixed** 
- When we apply filter and start editing, we should not be able to change the filter. **- Fixed**
- We should not be able to click column filters when are editing a file or link. **- Fixed**

**Comment by coderhacker** [comment]
Verified on dev working as expected.

**Comment by coderhacker** [comment]
Verified on prod, working as expected.
[3750_prod.zip](https://github.com/appirio-tech/connect-app/files/4419796/3750_prod.zip)
