### ISSUE TITLE
[$50] Do not allow selecting "from" date after "to" date

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3752]
Follow-up from https://github.com/appirio-tech/connect-app/issues/3730

On the Assets Library page we can apply filters to the files and links, see page https://connect.topcoder-dev.com/projects/8600/assets

We can filter by "Date" by choosing "from" date and "to" date. Currently, we can enter any arbitrary dates. Instead of this, we should not allow choosing "from" date after "to" and "to" date before "from". 

![image](https://user-images.githubusercontent.com/146016/76279963-70e28d00-62cb-11ea-9e0c-de7356d6ba0e.png)

For this purpose, we can use "min" and "max" attributes of the input and dynamically update them, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date.

- We should allow settings "from" the same as "to"
- We should allow settings only one of the fields "from" or "to" as we do now

**Comment by tcchhabra** [comment]
Please assign me this

**Comment by maxceem** [comment]
@tcchhabra please check the Bug Bash rules here https://www.topcoder.com/challenges/30118814?tab=details. We use a bot to assign issues.

**Comment by tcchhabra** [comment]
@bug-bash-helper

**Comment by tcchhabra** [comment]
> @tcchhabra please check the Bug Bash rules here https://www.topcoder.com/challenges/30118814?tab=details. We use a bot to assign issues.

thanks, looks like bot isn't awake 😉

**Comment by tcchhabra** [comment]
@bug-bash-helper assign

**Comment by tcchhabra** [comment]
@maxceem can you help clarify a bit on requirement
- we should not allow choosing "from" date after "to" and "to" date before "from".
- We should allow settings "from" the same as "to"
- We should allow settings only one of the fields "from" or "to" as we do now

This looks confusing, since we allow them to choose either, can you help clarify this once ?

**Comment by maxceem** [comment]
@tcchhabra the requirements look correct for me. Could you, please specify what is confusing?

I will try say them other words:
- we should be able to select only "from" or "to" date, so we don't require to enter 2 dates, one is enough for filtering
- if we enter 2 dates, then "from" and "to" can be equal, but "form" cannot be after "to"

**Comment by tcchhabra** [comment]
> @tcchhabra the requirements look correct for me. Could you, please specify what is confusing?
> 
> I will try say them other words:
> 
> * we should be able to select only "from" or "to" date, so we don't require to enter 2 dates, one is enough for filtering
> * if we enter 2 dates, then "from" and "to" can be equal, but "form" cannot be after "to"

Thanks - got confused with either one and then both values. Now clear.

**Comment by tcchhabra** [comment]
@maxceem one more question - I am not able to push PR branch. can you help ?

```
ERROR: Permission to appirio-tech/connect-app.git denied to tcchhabra.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by maxceem** [comment]
@tcchhabra that's right, to create a pull request you have to fork our repository and after create a pull request for your fork. You may check this guide on how to do it https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by tcchhabra** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3754 is ready for review

**Comment by maxceem** [comment]
@tcchhabra here is the review of the PR, please have a look https://github.com/appirio-tech/connect-app/pull/3754#pullrequestreview-372513997

**Comment by tcchhabra** [comment]
ah I misunderstood not allow means, if user selects to, we should allow them to select from. Will fix it now.

**Comment by tcchhabra** [comment]
@bug-bash-helper #3754 is ready for review

**Comment by drasticdpk** [comment]
Verified on Dev Env :
![image](https://user-images.githubusercontent.com/25297859/76507003-281a0800-6474-11ea-97a2-8269efb4df2c.png)

**Comment by satkanhub** [comment]
Working as expected, verification video for reference.

[3752.zip](https://github.com/appirio-tech/connect-app/files/4326292/3752.zip)

**Comment by codejamtc** [comment]
Verified in `Prod`: 🆗 Pass - When user type the date instead of selecting it (Selecting is blocked) it will show a validation (Red Border with a tooltip)
**User:** CustomerUser

https://monosnap.com/file/r9tyOmhLwROgpcl0hRxnKpvxb6xO1A
https://monosnap.com/file/RTsHV076wdEFu5kic6CAcmukKzp9Aq

- We should not allow choosing "from" date after "to" and "to" date before "from".
- We should allow settings "from" the same as "to"
- We should allow settings only one of the fields "from" or "to" as we do now
