### ISSUE TITLE
[$45] [Project Service] Fix searching projects by handle

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3755]
The current issue is used to track a task in another repository during the Bug Bash challenge.

https://github.com/topcoder-platform/tc-project-service/issues/499

All the comments to assign, unassign and ready for review should be done here in the current issue in Connect App.

**Comment by gets0ul** [comment]
@bug-bash-helper assign

**Comment by gets0ul** [comment]
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/501 is ready for review

**Comment by codejamtc** [comment]
@maxceem 

⚠️ If an exact match is not expected this ticket is `Fixed`, but if we are expecting the exact match of the handle then this is `Fail` (eg: `vikasrohit` will return `vikasrohit` and `vikasrohit5` + `maxceem-dev` will return `maxceem-dev` and `maxceem`

https://www.screencast.com/t/rJrq6QNR0OAc

**Comment by vikasrohit** [comment]
Yes, that is accepted @codejamtc. We don't have much strict requirements around it, as long as user is able to search the intended projects, we should be good. However, if you see in some practical cases, it might create a problem for users, we can log it as enhancement for upcoming releases.

**Comment by codejamtc** [comment]
@vikasrohit Noted, Thanks

**Comment by codejamtc** [comment]
@lakshmiathreya This is not an admin account limitation, In the `Customer` account there are fewer test data to test this one.

**Comment by lakshmiathreya** [comment]
@codejamtc pls move this to Prod QA Pass based on my Prod update in #3723 - the same results are valid here too right?
