### ISSUE TITLE
[Project Dashboard] Specification and Message Tab 

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#376]
### Expected behavior
Specification and Message Tab should be hidden if a manager/co-pilot havent joined
The content of this tab should also be hidden

### Actual behavior
Specification and Message Tab is visible and clickable
The content of the tab are also visible

### Steps to reproduce the problem
Click on any project 
Notice that that message and specification tab are visible and clickable

### Screenshot/screencast
![screenshot 34](https://cloud.githubusercontent.com/assets/8684209/18966520/1caf74f6-86b4-11e6-957a-bd51c3ac276a.png)
![screenshot 36](https://cloud.githubusercontent.com/assets/8684209/18966522/1cbff614-86b4-11e6-8375-dd33f4ec8810.png)
![screenshot 32](https://cloud.githubusercontent.com/assets/8684209/18966521/1cba013c-86b4-11e6-9dcb-f241e4e6a370.png)

#### Environment
- OS: Windows 10
- Browser (w/version):Google Chrome Version 53.0.2785.116 m (64-bit)
- User role :Manager
- Account used: Pat Monahan

**Comment by mahestro** [comment]
Makes sense. On hold for confirmation.

**Comment by mahestro** [comment]
Not valid. It's the expected behavior.
