### ISSUE TITLE
[$50] [Project Processor ES] Throw error if no invite has been removed when it should

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3764]
The current issue is used to track a task in another repository during the Bug Bash challenge.

https://github.com/topcoder-platform/project-processor-es/issues/29

All the comments to assign, unassign and ready for review should be done here in the current issue in Connect App.

**Comment by maxceem** [comment]
This issue has to be fixed in another repository https://github.com/topcoder-platform/project-processor-es branch **develop**.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by narekcat** [comment]
@bug-bash-helper assign

**Comment by narekcat** [comment]
@bug-bash-helper https://github.com/topcoder-platform/project-processor-es/pull/28 is ready for review
