### ISSUE TITLE
Messages tab does not load when an author is inactive

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3765]
### Expected behavior
Should load page properly with `Connect User` as placeholder data for inactive user

### Actual behavior
As of now, it fails to load the page if a user, who has made some post, is inactive

**Comment by maxceem** [comment]
Fixed via 836d92a4a5c57c9f7aa43addad7ea26bb8d368ac

![image](https://user-images.githubusercontent.com/146016/76394779-fc821980-63b0-11ea-834d-b64367e796e4.png)

Hotfixes are created:
- DEV https://github.com/appirio-tech/connect-app/pull/3766
- PROD https://github.com/appirio-tech/connect-app/pull/3767

**Comment by lakshmiathreya** [comment]
@drasticdpk

**Comment by lakshmiathreya** [comment]
Verified and closed by Vikas/Maxceem
