### ISSUE TITLE
[$25] Profile Icon doesn’t display the default image in Avatar.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3770]
### Expected behavior
The Avatar should display default image. .

### Actual behavior
The blank icon is being displayed in the Avatar.

### Steps to reproduce the problem
1.	Login as any user which doesn’t have the Display Picture uploaded yet. 
2.	Go to My Profile section>> Personal Information>>Avatar 

### Screenshot/screen-cast
Attach or link a resource.
![No default Image](https://user-images.githubusercontent.com/25297859/76410716-81bcfc80-63b8-11ea-85b9-75ba66f91d7c.png)

--

#### Environment
- OS: Windows-10
- Browser (w/version): Chrome/ Version 80.0.3987.122 (Official Build) (64-bit))
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+copilot@gmail.com

**Comment by maxceem** [comment]
Sum up:
- user for testing `maxceem13` (password on the forum), or create a new user using https://accounts.topcoder-dev.com/connect/registration

**Comment by iversonLv** [comment]
@bug-bash-helper assign

**Comment by iversonLv** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3906 is ready for review

**Comment by coderhacker** [comment]
QA Comment: This is fixed and working as expected. please see the below reference.

User details: taxt123412/Test@1234 

![image](https://user-images.githubusercontent.com/62358241/79836246-88825a80-83cd-11ea-96ea-69c551e69600.png)

**Comment by drasticdpk** [comment]
FYI @coderhacker , please don't share the user credential in Github issue. If required please list down the required steps and upload image/video for reference purpose. cc @lakshmiathreya

**Comment by coderhacker** [comment]
@drasticdpk : Sure, Updated my comments as per the above comments.

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 for `Customer` account

![image](https://user-images.githubusercontent.com/42398485/80572963-c29ebe00-89c4-11ea-844c-4ad0d682cf30.png)

@drasticdpk @lakshmiathreya Please check using Manager/Copilot and Admin accounts

**Comment by drasticdpk** [comment]
@codejamtc @lakshmiathreya,  here I have verified from customer role. 
![image](https://user-images.githubusercontent.com/25297859/80584487-763d9780-8a31-11ea-8ada-2d60fbab9c98.png)
