### ISSUE TITLE
[$35] Some of the buttons doesn’t get highlighted on mouse hovering.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3773]
### Expected behavior
The button should get highlighted when the mouse gets hover on it. .

### Actual behavior
The button is not getting focused while hovering the mouse.  

Note : Please implement this feature across all the buttons. 

### Steps to reproduce the problem
1.	Login as Copilot user. 
2.	Go to the dashboard.
3.	Go to Top Right header “+New Project” . 
4.	Hover the mouse over “+New Project” button. 

### Screenshot/screencast
Attach or link a resource.

--
![mousehover](https://user-images.githubusercontent.com/25297859/76411652-56d3a800-63ba-11ea-8754-9f4b558c7f1d.png)

#### Environment
- OS: Windows-10
- Browser (w/version): Chrome/ Version 80.0.3987.122 (Official Build) (64-bit))
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+copilot@gmail.com

**Comment by maxceem** [comment]
Sum up:
- we have a default **hover** style for buttons, for example, see **Save settings** button on https://connect.topcoder-dev.com/settings/profile:

   ![hover](https://user-images.githubusercontent.com/146016/79345848-52128e80-7f3a-11ea-8e56-d58081eaa3cf.gif)

- in other places, where we show the standard button we have to **reuse** our global styles as we do for **Save settings** button. Also, we have to make sure we don't break it.
   
- if a button has some additional styles we have to keep them (but also keep standard hover effect)

- places to fix:
   - **New project** on https://connect.topcoder-dev.com/projects?sort=lastActivityAt%20desc

      ![image](https://user-images.githubusercontent.com/146016/79346386-f7c5fd80-7f3a-11ea-8ae4-8629d755d07f.png)

  - **Add new phase** on the project page https://connect.topcoder-dev.com/projects/8600

     ![image](https://user-images.githubusercontent.com/146016/79346429-0c09fa80-7f3b-11ea-8cd3-fd6b4bd62659.png)

  - **Add new..** on the Assets Library page https://connect.topcoder-dev.com/projects/8600/assets:

      ![image](https://user-images.githubusercontent.com/146016/79346791-6efb9180-7f3b-11ea-8a9e-48116d256b39.png)

      - replace it with standard blue button same like **Save settings** (use the same size class).

**Comment by maxceem** [comment]
@drasticdpk I found 3 places with missing hover styles. Please, let me know if you find any other places.

Note: blue links don't have a hover class since long time ago, I don't know why.

**Comment by drasticdpk** [comment]
@maxceem I think you have listed all button which is not hovering properly. I strongly recommend for dev team to reuse global styles so we will not miss the standard  as mentioned above.
> in other places, where we show the standard button we have to reuse our global styles as we do for Save settings button. Also, we have to make sure we don't break it.

**Comment by Vips19** [comment]
@bug-bash-helper assign

**Comment by Vips19** [comment]
@bug-bash-helper #3910 is ready for review

**Comment by maxceem** [comment]
@Vips19 there are some issues with the solution, please, have a look at the review https://github.com/appirio-tech/connect-app/pull/3910#pullrequestreview-395884217

**Comment by Vips19** [comment]
@bug-bash-helper #3910 is ready for review

**Comment by maxceem** [comment]
@Vips19 reviewed https://github.com/appirio-tech/connect-app/pull/3910#pullrequestreview-395908596.

**Comment by Vips19** [comment]
@maxceem can i raise a new branch with the necessary changes only

**Comment by maxceem** [comment]
@Vips19 yes, can.

**Comment by Vips19** [comment]
@bug-bash-helper #3933  is ready for review

**Comment by maxceem** [comment]
@Vips19 the review is ready, please have a look https://github.com/appirio-tech/connect-app/pull/3933#pullrequestreview-395990222

**Comment by Vips19** [comment]
@bug-bash-helper #3933 is ready for review

**Comment by coderhacker** [comment]
QA Testing comment: All the above-reported issues are fixed now 

Only found one place is not working. please find below details:
![3773_fail](https://user-images.githubusercontent.com/62358241/79835588-8ff53400-83cc-11ea-802e-8785a60ba8e7.gif)

**Comment by maxceem** [comment]
@coderhacker good catch. Could you please log a new issue for this case.

It wasn't included in this issue initially, and technically, we need to apply a different fix for this place.

**Comment by coderhacker** [comment]
@maxceem I have created new issue https://github.com/appirio-tech/connect-app/issues/3945
and linked with this issue.
@lakshmiathreya @drasticdpk

**Comment by Vips19** [comment]
@maxceem #3945 can be fixed with a small fix

**Comment by maxceem** [comment]
@Vips19 thanks, we will handle it in the next milestone I think.

**Comment by Vips19** [comment]
@maxceem ok sure

**Comment by drasticdpk** [comment]
Verified on above mentioned button on prod env.
New Project, Add New Phase, ASSETS LIBRARY, Go to Project Dashboard button.
