### ISSUE TITLE
[$10] Toggle button is not working for Copilot and customer users. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3774]
### Expected behavior
The toggle button should function accordingly while clicking on an off.

### Actual behavior
There is no difference in the project list even after clicking the My Projects toggle button.   
Suggestion: If this doesn’t imply for Copilot/Customer or other roles then we don’t need to have this feature for them.

### Steps to reproduce the problem
1.	Login as Copilot/customer user. 
2.	Go to the dashboard.
3.	Go to Top Right header menu.
4.	Click on Toggle Button of “My Projects”

### Screenshot/screencast
Attach or link a resource.
![off](https://user-images.githubusercontent.com/25297859/76414033-a4521400-63be-11ea-9856-97b2e8abccd3.png)
![On](https://user-images.githubusercontent.com/25297859/76414035-a61bd780-63be-11ea-85e8-12b83b019a92.png)

--

#### Environment
- OS: Windows-10
- Browser (w/version): Chrome/ Version 80.0.3987.122 (Official Build) (64-bit))
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+copilot@gmail.com

**Comment by vikasrohit** [comment]
Good catch @drasticdpk . I will add this to feature planning board so that we can get product manager's feedback.

**Comment by vikasrohit** [comment]
Got confirmation from product manager, we are good with removing the switch for customers and copilots for now. Not urgent, so we can keep it in release 2.9.

**Comment by maxceem** [comment]
Sum up:
- add a new permission `SEE_MY_PROJECTS_FILTER` as per https://github.com/appirio-tech/connect-app/blob/dev/docs/permissions-guide/permissions-guide.md

**Comment by iversonLv** [comment]
@bug-bash-helper assign

**Comment by iversonLv** [comment]
@bug-bash-helper unassign

**Comment by ijxsid** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@maxceem I would like to work on it

**Comment by simranb86** [comment]
@bug-bash-helper assign

**Comment by ijxsid** [comment]
@bug-bash-helper unassign

**Comment by simranb86** [comment]
@bug-bash-helper assign

**Comment by simranb86** [comment]
@maxceem FYI ☝️

**Comment by rashmi73** [comment]
@maxceem I commented first after ijxsid unassigned himself, so kindly assign this to me. you can verify above i commented

**Comment by rashmi73** [comment]
@maxceem here is screenshot for verification 
and I have completed this issue already

<img width="922" alt="connect1" src="https://user-images.githubusercontent.com/41687423/79387696-c0cb0880-7f89-11ea-9b53-8a47e451709c.PNG">

**Comment by simranb86** [comment]
> @maxceem I commented first after ijxsid unassigned himself, so kindly assign this to me. you can verify above i commented

LOL - It may be none of us, Bug Bash you need to track when ticket becomes Open for Pickup I guess. So when you commented, it was not Open for pickup. So stay around and keep looking for that tag, else it goes to person who requests Bug bash bot - could be neither of us get it. Always play fair.

**Comment by rashmi73** [comment]
@simranb86 I commented after ijxsid unassigned himself, it was not luckily, i saw he unassigned himself, just he did not comment "bug-bash-helper unassign" that is how bot works, and i understood that he forgot to follow the procedure and directly unassigned himself.

**Comment by rashmi73** [comment]
@maxceem waitign for your comment

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by maxceem** [comment]
@rashmi73 @simranb86 as per our Bug Bash rules to keep it fair for everyone, only issues which are marked as `Open for Pickup` could be picked up. At the moment we don't accept manual assigning by commenting.

**Comment by simranb86** [comment]
@bug-bash-helper assign

**Comment by simranb86** [comment]
@maxceem I see a field isCustomer but nothing to different copilot and manager, are they like PowerUsers ?

**Comment by maxceem** [comment]
@simranb86 please, don't use `isCustomer` and powerUsers variables anymore. Instead:
- add a new permission `SEE_MY_PROJECTS_FILTER` as per https://github.com/appirio-tech/connect-app/blob/dev/docs/permissions-guide/permissions-guide.md
- and after use it to show or no show `My Projects` filter

So this permission rules would let to see `My Project` filter only to the users who have one of the next roles: https://github.com/appirio-tech/connect-app/blob/dev/src/config/constants.js#L658-L668

We don't include the roles `Topcoder User` and `Connect Copilot` and customers and copilots would not see it.

Let me know if you would have any more questions.

**Comment by simranb86** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3917 is ready for review

**Comment by simranb86** [comment]
> @simranb86 please, don't use `isCustomer` and powerUsers variables anymore. Instead:
> 
> * add a new permission `SEE_MY_PROJECTS_FILTER` as per https://github.com/appirio-tech/connect-app/blob/dev/docs/permissions-guide/permissions-guide.md
> * and after use it to show or no show `My Projects` filter
> 
> So this permission rules would let to see `My Project` filter only to the users who have one of the next roles: https://github.com/appirio-tech/connect-app/blob/dev/src/config/constants.js#L658-L668
> 
> We don't include the roles `Topcoder User` and `Connect Copilot` and customers and copilots would not see it.
> 
> Let me know if you would have any more questions.

done.

**Comment by maxceem** [comment]
@simranb86 here is the review, please have a look https://github.com/appirio-tech/connect-app/pull/3917#pullrequestreview-395897677

**Comment by simranb86** [comment]
@bug-bash-helper #3917 is ready for review

**Comment by drasticdpk** [comment]
Prod Verified for Customer and Copilot Role.
![image](https://user-images.githubusercontent.com/25297859/80570804-281d9980-8a1b-11ea-96ba-992edc61c94f.png)

@lakshmiathreya  Please confirm from manager Role and close the issue.

**Comment by lakshmiathreya** [comment]
Toggle button working as expected for Manager users:
<img width="1632" alt="Screenshot 2020-04-29 at 4 29 09 PM" src="https://user-images.githubusercontent.com/51733042/80588789-9a4fa780-8a36-11ea-84ae-fe585ce7d783.png">
<img width="1430" alt="Screenshot 2020-04-29 at 4 30 05 PM" src="https://user-images.githubusercontent.com/51733042/80588850-bd7a5700-8a36-11ea-93d9-ea1ec8593d1e.png">

**Comment by drasticdpk** [comment]
@maxceem , need confirmation for Copilot manger Role. Here could not see toggle button for Copilot Manager too.
> users for testing:
pshah_customer - shouldn't see
pshah_copilot - shouldn't see
pshah_manager - should see

![image](https://user-images.githubusercontent.com/25297859/80591647-c0c51100-8a3d-11ea-86e6-ebc3541b8e0f.png)

**Comment by maxceem** [comment]
@drasticdpk This looks like an issue, only copilots and customers shouldn't see it. Other users should see it.

**Comment by lakshmiathreya** [comment]
@drasticdpk we will need to set this to QA Fail in Dev and Prod right?

**Comment by drasticdpk** [comment]
@lakshmiathreya  QA Fail in Prod/Dev

**Comment by codejamtc** [comment]
Fixed in `Dev`: 🆗 

![image](https://user-images.githubusercontent.com/42398485/80707633-e8ed5800-8aaf-11ea-85d9-514fd3c6f971.png)

**Comment by drasticdpk** [comment]
Any idea how can we verify this issue for prod env with Copilot Manger Role ? Since we don't have user credential with Copilot Manager Role ? cc @lakshmiathreya @maxceem @vikasrohit

**Comment by drasticdpk** [comment]
With reference to Dev env verification, I am closing it. Let us know if we have any way to verify on prod env.
