### ISSUE TITLE
[$15] User is able to click on the  tabs that are already selected. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3775]
### Expected behavior
User should not be able to select the same tab that is being focused already..

### Actual behavior
User can select the same tabs even it’s being selected already..

### Steps to reproduce the problem
1.	Login as any user. 
2.	Go to the Main Page.
3.	Click on Active tab of the Project Grid view.
4.	Again click on the same tab “Active tab”. 
5.	Observe the server request

### Screenshot/screencast
Attach or link a resource.
![selected tab](https://user-images.githubusercontent.com/25297859/76414868-41fa1300-63c0-11ea-84c9-776c05bf60e5.png)

--

#### Environment
- OS: Windows-10
- Browser (w/version): Chrome/ Version 80.0.3987.122 (Official Build) (64-bit))
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+copilot@gmail.com

**Comment by maxceem** [comment]
Sum up:
- cursor should be `default` instead of `pointer` for already selected tab
- when we click already selected tab the request should not be sent to the server
- this should be also fixed for mobile view

    ![image](https://user-images.githubusercontent.com/146016/79315340-6e4b0700-7f0b-11ea-979f-c3f74a1d1024.png)

**Comment by iversonLv** [comment]
@bug-bash-helper assign

**Comment by iversonLv** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3907 is ready for review

**Comment by codejamtc** [comment]
Fixed in Desktop: 🆗 https://monosnap.com/file/hnHKgwhtRNCYGXoXsKyYq8bo6ZA146
Fixed in Mobile: 🆗https://monosnap.com/file/l2gDkNGs1s1D6z9DNPK9RFhEfo3oic

**Comment by drasticdpk** [comment]
prod Verified.
![image](https://user-images.githubusercontent.com/25297859/80570002-bee95680-8a19-11ea-9b86-28eae84cdb15.png)
