### ISSUE TITLE
My Profile name is written in small letter. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3778]
From the Left Navigation Menu>>Click on My Profile.
Problem :  My Profile is written as My profile.
Suggestion: It should read like My Profile
Benefit: It gives consistency in the header format. 

### Screenshot/screencast
Attach or link a resource.
![UX-My profile](https://user-images.githubusercontent.com/25297859/76415836-0d875680-63c2-11ea-8781-20ddb3420edd.png)

--

#### Environment
- OS: Windows-10
- Browser (w/version): Chrome/ Version 80.0.3987.122 (Official Build) (64-bit))
- User role (client, copilot or manager): Copilot
- Account used: topcoderconnect+copilot@gmail.com

**Comment by maxceem** [comment]
Done via 42d25b4bed6c2129a95fa9de4bb74753858b6d4e

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/79342172-6c287e80-7ef2-11ea-95f7-6bd06c37c39b.png)

**Comment by drasticdpk** [comment]
Verified on prod 
![image](https://user-images.githubusercontent.com/25297859/80570997-8c405d80-8a1b-11ea-9cf2-e4226a081ecb.png)
