### ISSUE TITLE
[Features] - the textarea can be resized under the section

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#379]
Expected behavior
------------------------------------------------------------

- The textarea must not be able to be resized under the section and must be kept in the section.

Actual behavior
------------------------------------------------------------

- The textarea can be resized under the image phone section.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Considering an existing project with REQUIREMENTS INCOMPLETE.

- Finish Requirements.

- Select for Define Features.

- From GENERAL BUILDING BLOCKS select Notifications.

- Resize textarea moving to the right.

- Observe as the textarea in moved under the phone image,

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![1](https://cloud.githubusercontent.com/assets/5114907/18970584/7456abf8-869a-11e6-8846-f7e05d2eb100.png)

**Comment by mahestro** [comment]
Valid.
