### ISSUE TITLE
Project creation: enforce character limit for Project Name

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#38]
Is there a limit to the number of characters the API can support? If so, let's enforce it by not allowing the user to enter more... the cursor should just stop.

**Comment by fnisen** [comment]
@mdesiderio can you please comment here if there is a limit?

**Comment by parthshah** [comment]
Max project name can be 255 characters long.

**Comment by fnisen** [comment]
Thanks @parthshah. What about Project Description?

**Comment by parthshah** [comment]
No limit as such.

**Comment by mahestro** [comment]
Limit to project name only so.

How you guys want to handle the limitation? By using the maxlength attribute in the input or by post-writing validation (with a reddish message)?

**Comment by fnisen** [comment]
@mahestro maxlength attribute please. 

cc @vic-appirio

**Comment by mahestro** [comment]
Ok. Seems an easy fix.

Any particular considerations for implementation? Should we define this limitation as a constant or just put the holy number in the component definition?

I usually like encapsulating values in constants as much as possible if I know it will be reused in other components. For what I've seen in the project development, some of these attributes definition are being put directly in the components declaration, except for css classes names ofc.

Let me know what you think.

**Comment by fnisen** [comment]
@mahestro sounds like it should be constant, but I don't know whether the implementation with components declaration was intentional or just something we didn't think about. @parthshah usually decides stuff like this, but let's go with your recommendation if he doesn't weigh in.

**Comment by mahestro** [comment]
Ok. I can create the constant implementation for now. We can change it after Parth's final revision.

**Comment by parthshah** [comment]
@mahestro constants are great. There are only a couple of places where we collect Project name though and both those forms are in the same src directory. We just need to add the maxlength attribute in a couple of places. 
https://github.com/appirio-tech/connect-app/blob/dev/src/projects/create/components/AppProjectForm.jsx#L91
This won't impact all text field input components just the ones with the attribute.
