### ISSUE TITLE
[Features] - when set an existing name and the validation message is displayed set disable buttons

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#380]
Expected behavior
------------------------------------------------------------

- Display buttons as disable.

Actual behavior
------------------------------------------------------------

- The buttons are displayed as enable.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- In Your Projects considering an existing project with requirements incomplete.

- Finish Requirements.

- Press Select to Define Features.

- Define A New Feature and set the name: Test.

- Define again a new feature and set the same name Test.

- Observe as even the validation message is displayed the buttons are enable.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![buttons](https://cloud.githubusercontent.com/assets/5114907/18970853/a72c2e30-869b-11e6-8dba-d28cfb576422.png)

**Comment by mahestro** [comment]
Not valid. Wrong environment.
