### ISSUE TITLE
Invite member email is cut

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3801]
Invite non-topcoder user by email, see that it's cut in the Customer Team dialog

![image](https://user-images.githubusercontent.com/146016/76740204-7a2a9880-67a8-11ea-943a-092870fc9aed.png)

**Comment by codejamtc** [comment]
Project: https://connect.topcoder-dev.com/projects/8943/
User: `topcoderconnect+Customer@gmail.com` (This user created the project `8943`)

https://www.screencast.com/t/g3KgLTk0XTT

**Comment by codejamtc** [comment]
Re-verified
![image](https://user-images.githubusercontent.com/42398485/78172930-848d9900-741c-11ea-993b-5fc1e523b145.png)

**Comment by codejamtc** [comment]
Verified in `Prod`: 🆗 Pass
**User:** CustomerUser

![image](https://user-images.githubusercontent.com/42398485/78261191-890d8c80-74c4-11ea-8824-e90bae784f14.png)
