### ISSUE TITLE
Can start TAAS project when full-time resource hours are set to zero

### ISSUE THREAD

**Issue by mtwomey** [appirio-tech/connect-app#3802]
### Expected behavior
Can start TAAS project

### Actual behavior
Cannot start a new TAAS project if Fulltime Resource Hours is set to zero

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/7715262/76795235-b654fd80-6796-11ea-8f1b-307f2dd00eaf.png)

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vikasrohit** [comment]
Related issue https://github.com/appirio-tech/connect-app/issues/3557

**Comment by vikasrohit** [comment]
@mtwomey fixed the issue, now you should be able to enter 0 to any of the resource hours fields.

**Comment by lakshmiathreya** [comment]
@vikasrohit the Issue is fixed in Prod today - a hotfix ? Wondering how it'd be part of the 2.8 milestone?

**Comment by lakshmiathreya** [comment]
@drasticdpk - fyi
