### ISSUE TITLE
Don't show firstname, lastname and email for any users

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3804]
In general: we should stop requesting and showing first name and last name of users client-side and show the handle instead everywhere.
- don’t request firstName and lastName in all endpoints client-side from the _search endpoint 
- show handle instead of full name everywhere Client-side
- don’t request firstName and lastName in all endpoints server-side from the _search endpoint so we never return it to the client-side

**Comment by maxceem** [comment]
Hotfixes have been deployed to DEV:
- client-side: don’t request firstName and lastName in all endpoints client-side from the _search endpoint
- server-side: don't return `firstName`, `lastName` and `email` to non-admin users

@vikasrohit this is ready for testing on DEV.

PRs for PROD:
- clinet-side: https://github.com/appirio-tech/connect-app/pull/3805
- server-side: https://github.com/topcoder-platform/tc-project-service/pull/510

**Comment by lakshmiathreya** [comment]
@drasticdpk
