### ISSUE TITLE
Use updated RESTful invite API

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3809]
We updated invite related API on the Project Service as per https://github.com/topcoder-platform/tc-project-service/issues/437 via PR https://github.com/topcoder-platform/tc-project-service/pull/517.

Now we have to update the client-side to use this updated API. It has been done via challenge http://www.topcoder.com/challenge-details/30118162/?type=develop and concluded in the next PR https://github.com/appirio-tech/connect-app/pull/3807.

As all API endpoints have been updated we have to test all the operations related to invites:
- create invite and remove invites to the **Customer Team** by email and handle
- create invite and remove invites to the **Topcoder Team** by handle
- accept and reject invite on the Project Listing page / Project Dashboard page or by link from email
- request / reject / accept invite for **copilots** to the **Topcoder Team** by handle

**Comment by codejamtc** [comment]
- Create invite and remove invites to the Customer Team by email and handle - **{Fixed}**

**Project:** https://connect.topcoder-dev.com/projects/8943
**User:** `topcoderconnect+Manager@gmail.com`
**Other users tested:** `topcoderconnect+Customer@gmail.com`,

https://www.screencast.com/t/FJIGqoltWb

- Create invite and remove invites to the Topcoder Team by handle - **{Can invite to the Topcoder team by handle but I can't see any option to remove the invite, Logged in as the `owner` (`topcoderconnect+Customer@gmail.com`) and checked, Logged in as `Admin` (topcoderconnect+Admin@gmail.com) and checked} same issue**

**Project:** https://connect.topcoder-dev.com/projects/8943
**User:** `topcoderconnect+Manager@gmail.com`

https://www.screencast.com/t/Lfj9DlNx5W

- Accept and reject invite on the Project Listing page / Project Dashboard page or by link from email



- Request / reject / accept invite for copilots to the Topcoder Team by handle

**Comment by codejamtc** [comment]
When I accept/decline the invitation via email or Project Dashboard, I am getting 404 page after accepting/declining the invitation

https://www.screencast.com/t/UeZTIy5Mj1gK

4:02 - 4:03 - Accept using Dashboard
3.:06 - 3:09 - Decline using Email
6:10 - 6:23 - Accept using Email

**Comment by maxceem** [comment]
@codejamtc this should be now fixed on DEV.

Please, kindly test all the cases:
- [ ] Accept using Dashboard
- [ ] Decline using Dashboard 
- [ ] Accept using Email
- [ ] Decline using Email 
- [ ] Click Accept link using Email after the invite is already accepted (should just open the page and remove `?invitation=accept` from the URL)
- [ ] Click Decline link using Email after the invite is already accepted (should just open the page and remove `?invitation=decline` from the URL)
- [ ] Click Accept link using Email after the invite is already declined (should show error)
- [ ] Click Decline link using Email after the invite is already declined (should show error)

**Comment by codejamtc** [comment]
@maxceem Still the testing is in progress

1. Add a team member using `handle` {Accpet/Decline using Connect Dashboard, Project Dashboard, Email} 

- When I accept the invite from the email it will automatically load the project dashboard but won't how the invited member on the `Teams` section? 

https://www.screencast.com/t/nqr4HKt73 [7:13]

2. Add a team member using `email`  {Accpet/Decline using Connect Dashboard, Project Dashboard, Email} 

- **In-progress**

3. Click Accept link using Email after the invite is already accepted (should just open the page and remove ?invitation=accept from the URL)

- **In-progress**

4. create the invite and remove invites to the Topcoder Team by the handle

- **In-progress**

5. Request/reject / accept an invite for copilots to the Topcoder Team by the handle

- **In-progress**

6. Click Decline link using Email after the invite is already accepted (should just open the page and remove ?invitation=decline from the URL)

- **In-progress**
 
7. Click Accept link using Email after the invite is already declined (should show error)

- **In-progress**

8. Click Decline link using Email after the invite is already declined (should show error)

- **In-progress**

**Comment by maxceem** [comment]
> When I accept the invite from the email it will automatically load the project dashboard but won't how the invited member on the Teams section?

Checking...

**Comment by maxceem** [comment]
> Add a team member using handle {Accpet/Decline using Connect Dashboard, Project Dashboard, Email}
> When I accept the invite from the email it will automatically load the project dashboard but won't how the invited member on the Teams section?
> https://www.screencast.com/t/nqr4HKt73 [7:13]

@codejamtc I cannot reproduce this issue. Could you, please try to reproduce it 3 times and let me know how many times it would happen for you out of 3 attempts.

**Comment by codejamtc** [comment]
@maxceem Ok
Please check Point 2

**Comment by codejamtc** [comment]
> > Add a team member using handle {Accpet/Decline using Connect Dashboard, Project Dashboard, Email}
> > When I accept the invite from the email it will automatically load the project dashboard but won't how the invited member on the Teams section?
> > https://www.screencast.com/t/nqr4HKt73 [7:13]
> 
> @codejamtc I cannot reproduce this issue. Could you, please try to reproduce it 3 times and let me know how many times it would happen for you out of 3 attempts.

It's working, I have updated the ticket

**Comment by maxceem** [comment]
> Add a team member using handle {Accpet/Decline using Connect Dashboard, Project  Dashboard, Email}
> When I accept the invite from the email it will automatically load the project dashboard but won't how the invited member on the Teams section?
> https://www.screencast.com/t/nqr4HKt73 [7:13]

@vikasrohit this issue was reproduced once but neither I nor **codejamtc** can reproduce it again. I suspect that the issue happened due to a delay in indexing newly created member in ES. Currently, we are waiting 5 additional seconds. So it looks like sometimes, but rarely, this could be not enough. FYI

**Comment by codejamtc** [comment]
@maxceem Still the testing is in progress

1. Add a team member using `handle` {Accpet/Decline using Connect Dashboard, Project Dashboard, Email} 

https://www.screencast.com/t/nqr4HKt73 

- [x] When I accept the invite from the email it will automatically load the project dashboard but won't how the invited member on the `Teams` section [7:13]? 

- Verified above again, working- https://www.screencast.com/t/CbibXjuoaov

2. Add a team member using `email`  {Accpet/Decline using Connect Dashboard, Project Dashboard, Email} 

- When I invite a team member via email `topcoderconnect+Customer@gmail.com` I can't see Invite/Decline option on the Connect Dashboard but I can see the project. If I open it by clicking or using email it shows me a 404 error (Checked 3 times)

https://www.screencast.com/t/whuCwzkOJHF
https://www.screencast.com/t/reuwTwXqV
https://www.screencast.com/t/ZMaGB6vkTVH

3. create the invite and remove invites to the Topcoder Team by the handle

- **Pass** - https://www.screencast.com/t/LHLVmuaoEOR

4. Request/reject / accept an invite for copilots to the Topcoder Team by the handle

- **Pass** - https://www.screencast.com/t/W8z7PzHdz

**I can see a small issue though when I (Copilot) leave from the project {3:00}, the application reloads and navigates to the project listing page but I can see the project on the list {3:02}**

5. Click Accept link using Email after the invite is already accepted (should just open the page and remove ?invitation=accept from the URL)

- **Pass** - https://www.screencast.com/t/GKVYJ3Ncjz

6. Click Decline link using Email after the invite is already accepted (should just open the page and remove ?invitation=decline from the URL)

- **Pass** - https://www.screencast.com/t/1SpG9XQkh
 
7. Click Accept link using Email after the invite is already declined (should show error)

- **Pass** - https://www.screencast.com/t/4UzILANUG

8. Click Decline link using Email after the invite is already declined (should show error)

- **Pass** - https://www.screencast.com/t/cBI9do1b

**Comment by maxceem** [comment]
> Add a team member using email {Accpet/Decline using Connect Dashboard, Project Dashboard, Email} ❌
> When I invite a team member via email topcoderconnect+Customer@gmail.com I can't see Invite/Decline option on the Connect Dashboard but I can see the project. If I open it by clicking or using email it shows me a 404 error (Checked 3 times)
> https://www.screencast.com/t/whuCwzkOJHF
> https://www.screencast.com/t/reuwTwXqV
> https://www.screencast.com/t/ZMaGB6vkTVH

This should be fixed now, please check again.

**Comment by maxceem** [comment]
@codejamtc Regarding 
> I can see a small issue though when I (Copilot) leave from the project {3:00}, the application reloads and navigates to the project listing page but I can see the project on the list {3:02}

This issue is not connected with the current changes and it existed before, so I created a separate issue https://github.com/appirio-tech/connect-app/issues/3825

**Comment by codejamtc** [comment]
https://github.com/appirio-tech/connect-app/issues/3809#issuecomment-607318668 - Verified

https://www.screencast.com/t/x3bXKfic8x

**Comment by codejamtc** [comment]
@lakshmiathreya Invite to Topcoder Team requires Admin privileges

**Comment by lakshmiathreya** [comment]
On Prod for TC team - Verified Invites by handle (handle only for TC members invites), Accept and Decline via Email, Project Dashboard and Connect Dashboard for all Manager and Copilot roles. 

Verified Removal via Connect Dashboard. Admin is unable to remove in some cases. Will log a different Issue for that.
