### ISSUE TITLE
[Enter Your Brand Url] - the blank spaces are not ignored 

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#381]
Expected behavior
------------------------------------------------------------

- The blank spaces set in field are not ignored.
 
Actual behavior
------------------------------------------------------------

- Ignore the blank spaces set in field.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- In Dashboard section consider an existing project with requirements incomplete.

- Finish Requirements.

- Press "Select" for GET STYLE FROM URL.

- Set focus on field and add a blank space.

- Set a valid url eg. http://test.com

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

**Comment by mahestro** [comment]
Not valid. Environment.
