### ISSUE TITLE
[$50] Skills - don't allow to create a new entry when there is existent value

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3816]
### Expected behavior
Don't show the second option for creating a new skill, when there is already an existent option on the list.

### Actual behavior
Can see duplicate option to create a new skill, when there is already existent one.

### Steps to reproduce the problem
- Use the link https://connect.topcoder-dev.com/new-project/talent-as-a-service for creating a new project
- In the question **What skills are important for your team to have?** enter some skill via keyboard which is already on the list, for example `Zepto.js`.
- Observe, that at this moment we can choose 2 same options: the one which we enter by keyboard, and the one which already exists on the list:

   ![image](https://user-images.githubusercontent.com/146016/77919678-2a6ac780-72a6-11ea-8ad1-111803c4227c.png)

### Notes
- we shouldn't show the same options the second time even if we enter it using another letter case, like `zepto.js` or `ZEPTO.JS` or another case
- we should make sure that we show the only existent item on the list not the one which we created manually (existent item has `name` and `id`, but custom values only have `name` when we submit form)
- see how it's done for members ([screenshot](https://monosnap.com/file/DG1azOZjYtpQ8DGweDa51OaALQHvnw)), where we don't show duplicate option:
 
  - when I type not fully, can see the existent item and custom:

     ![image](https://user-images.githubusercontent.com/146016/77920038-9c431100-72a6-11ea-8128-377e42a4587c.png)

   - as soon as I type the same value, only one item on the list:

      ![image](https://user-images.githubusercontent.com/146016/77920067-a6fda600-72a6-11ea-8b3f-120927ddcc5b.png)

### References

https://github.com/appirio-tech/connect-app/issues/3634

**Comment by maxceem** [comment]
As a part of this issue, please, also fix this one https://github.com/appirio-tech/connect-app/issues/3851

**Comment by narekcat** [comment]
@bug-bash-helper assign

**Comment by abdullatku** [comment]
since 12 hours is already past, can i take this

**Comment by maxceem** [comment]
@narekcat as PR has not been raised for 12 hours, you are now unassigned from this issue.

This issue is now open for pickup.

**Comment by abdullatku** [comment]
@bug-bash-helper assign

**Comment by abdullatku** [comment]
@bug-bash-helper #3923 is ready for review

**Comment by maxceem** [comment]
@abdullatku the review is ready, please have look https://github.com/appirio-tech/connect-app/pull/3923#pullrequestreview-395982360

**Comment by codejamtc** [comment]
https://monosnap.com/file/IrW7b6UxyqZ4ufz7pBoCLkNYrjhONU

**Comment by codejamtc** [comment]
No issue in `Production`: 🆗 
https://monosnap.com/file/z4tTv5iPI9AHdsP4ju9f6UzjNnL2NN
