### ISSUE TITLE
Wrong country calling code for Canada

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#3819]
### Expected behavior
It should apply `+1` as calling country code

### Actual behavior
It is applying `+238` as calling country code

### Steps to reproduce the problem
- On profile settings page, try to set country to Canada for business phone field
- Observe it adds `+238` instead of `+1`
- It makes the phone validation to fail and no number makes the validation happy

### Screenshot/screencast
<img width="715" alt="Screen Shot 2020-03-31 at 3 53 54 PM" src="https://user-images.githubusercontent.com/2417632/78015996-d6c0b280-7367-11ea-9143-1a0f6d0be1fe.png">

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used: N/A

**Comment by maxceem** [comment]
The issue in our old module https://github.com/appirio-tech/ng-iso-constants.

Several countries have incorrect 2-letter codes like Canada, maybe more https://github.com/appirio-tech/ng-iso-constants/blob/dev/src/ng-iso-constants/services/iso-3166.js#L51-L55, see correct ones https://www.iban.com/country-codes.

The is already issues listed for that repo https://github.com/appirio-tech/ng-iso-constants/issues/10.

Working on a quick fix at least for our case.

**Comment by maxceem** [comment]
This is done via 2 PRs to `ng-iso-constants`:
- DEV https://github.com/appirio-tech/ng-iso-constants/pull/11
- PROD https://github.com/appirio-tech/ng-iso-constants/pull/12

See demo of the fix:

![countries-demo](https://user-images.githubusercontent.com/146016/78020534-4fb90d80-735a-11ea-8e51-08909263c63d.gif)

2 PRs to `react-components`:
- DEV https://github.com/appirio-tech/react-components/pull/354
- PROD https://github.com/appirio-tech/react-components/pull/353

Works good on the example page http://localhost:8080/WizardExamples when deployed locally:

![image](https://user-images.githubusercontent.com/146016/78021037-26e54800-735b-11ea-9565-94b89e78cc25.png)

2 PRs to `connect-app`:
- DEV https://github.com/appirio-tech/connect-app/pull/3820
- PROD https://github.com/appirio-tech/connect-app/pull/3821

Works good on the profile settings page http://local.topcoder-dev.com:3000/settings/profile when deployed locally:

![image](https://user-images.githubusercontent.com/146016/78021857-9c054d00-735c-11ea-9800-e34bc953d289.png)

**Comment by maxceem** [comment]
2 more PRs would be created for `accounts-app` after we publish an updated version of npm package https://www.npmjs.com/package/appirio-tech-ng-iso-constants.

**Comment by maxceem** [comment]
2 PRs to `accounts-app`:
- DEV https://github.com/appirio-tech/accounts-app/pull/336
- PROD https://github.com/appirio-tech/accounts-app/pull/337

How to apply fix:
1. Merge PR to `accounts-app` it should fix the country code on the Registration page. We should make sure that during deploying the cache is cleared and new version of `ng-iso-constants` is downloaded. But as we updated `package.json` it should work.
2. Merge PR to `connect-app` it should fix the country code on User Profile Settings page.
3. Merge PRs to `react-components` - we don't use it anywhere except of demo example which we run during local work, so it can be only tested locally.

**Comment by codejamtc** [comment]
After investigating the above threads I can see the `country` tag changes to `CAN` when we select it but 

1. After selecting the country `Canada`, `USA` is displayed on the list.
2. In Dropdown current selection `Canada` is not selected on the dropdown in Gray

https://www.screencast.com/t/13YlNidFLGh

**Comment by vikasrohit** [comment]
@codejamtc I think the issue you are seeing is already logged as separate issue #3823 which seems to be there before any fix we applied. So, we are taking it as separate fix.

**Comment by maxceem** [comment]
> After investigating the above threads I can see the country tag changes to CAN when we select it but

> After selecting the country Canada, USA is displayed on the list.
> In Dropdown current selection Canada is not selected on the dropdown in Gray

@codejamtc This is not an issue, though I understand that it looks confusing. The logic here is the next one:
- Canada and USA have the same phone code `+1`
- When there is already a phone number and we change the country code from India to USA, the code is changed to `+1`
- But this code also belongs to Canada. So the script now check the full phone number and understands that this phone number belongs to USA, so it changes the selected country to USA instead of Canada.

We might think if we should let users choose a country which is wrong for the phone number or no but at the moment our logic that we detect what country user live in by the phone number.

**Comment by codejamtc** [comment]
@maxceem Got it
