### ISSUE TITLE
Must disable the 'Save Changes' button when user first access it

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#382]
### Expected behavior
-----------------------------------------------------------------
Must disable the 'Save Changes' button when user first access it

### Actual behavior
-----------------------------------------------------------------
'Save Changes' button enabled when user first access it

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Select "Specification"
- Check the  'Save Changes' buttons in all section
- In this point it is already saved as DRAFT, So no need to save the Specification with No data 

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-30_11-26-21](https://cloud.githubusercontent.com/assets/4592712/18982045/e082d35e-8700-11e6-8ffc-04e14fa97075.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.
