### ISSUE TITLE
Switching country for the same phone code

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3822]
We have a registration form https://accounts.topcoder-dev.com/connect/registration (open in incognito mode) where we can enter a business phone with country code.

![image](https://user-images.githubusercontent.com/146016/78107556-62851e00-73fe-11ea-96c5-433ef0309e04.png)

- Enter some USA phone number like "+1 91 99999999" you would see the country code is detected as the USA.

- Now enter a Canadian phone number like "+1 514 5555555". As soon as the number is entered and valid, it would be replaced with the previous USA number  "+1 91 99999999", see [demo video](https://monosnap.com/file/uIRYEpVaHGJKchUf4y4sEAtZKJfnal). If we reload the page and directly enter Canadian phone number "+1 514 5555555" it would be detected correctly, and wouldn't be removed.

### Expected behavior

When we enter a Canadian phone number after the USA or vise-verse the number is not removed, and the country is detected correctly.

**Comment by maxceem** [comment]
Fix has been implemented via F2F challenge https://www.topcoder.com/challenges/30121485.

Hotfix created for `react-components` repo:
- DEV https://github.com/appirio-tech/react-components/pull/355
- PROD https://github.com/appirio-tech/react-components/pull/356

**Comment by codejamtc** [comment]
Fixed: https://www.screencast.com/t/MVhKFUJvLH
