### ISSUE TITLE
Customer names won't display within the table row

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#383]
### Expected behavior
-----------------------------------------------------------------
Must display the Customer names within the table row

### Actual behavior
-----------------------------------------------------------------
Customer names won't display within the table row

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Check the Customer column

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-30_11-57-49](https://cloud.githubusercontent.com/assets/4592712/18982617/283af4e8-8705-11e6-849e-d4719007d447.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Duplicate #181
