### ISSUE TITLE
[$35] Double scrolling in phone code dropdown

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3832]
Follow up from https://github.com/appirio-tech/connect-app/issues/3823#issuecomment-607322697

Two scrollbars displayed One is scrollable and the other one is disabled and not in use

![image](https://user-images.githubusercontent.com/146016/78217995-bad32300-74c5-11ea-82b2-f081d7c3dd01.png)

### Expected behavior

- There should not be the second scrollbar and shouldn't be any space on the right from the scrollbar.
- The height should stay as it is. Note, that in here we use shorter height, while in other places we use default height which is higher.
- As this list of countries is shown using our reusable dropdown component. We should reuse the scrollbar of the dropdown and don't implement another scrollbar if possible.
- Preferably fix it in https://github.com/appirio-tech/react-components repository so this fix would be applied in all places we use this component.

**Comment by maxceem** [comment]
@codejamtc in which browser do you see 2 scrollbars?

**Comment by codejamtc** [comment]
@maxceem Chrome 80.0.3987.149

**Comment by maxceem** [comment]
Sum up:
This issue might need to fixed in two repositories:
- this repo
- [https://github.com/appirio-tech/react-components](react-components) repo branch `feature/connectv2-dev`

**Comment by Giri-Suman** [comment]
@bug-bash-helper

**Comment by Giri-Suman** [comment]
@bug-bash-helper assign

**Comment by Giri-Suman** [comment]
@bug-bash-helper #3908  is ready for review

**Comment by Giri-Suman** [comment]
@bug-bash-helper <#3908> is ready for review

**Comment by codejamtc** [comment]
@maxceem Not fixed: ❌ https://monosnap.com/file/2ZAnyaPijTIEIyDhKBuHSzEFSUgxWh

![image](https://user-images.githubusercontent.com/42398485/79775895-84d1d380-82fa-11ea-9822-b106ff20e900.png)

**Comment by maxceem** [comment]
@codejamtc I've re-applied the fix. Could you please, check again.

**Comment by codejamtc** [comment]
@maxceem Yes, fixed 🆗 

![image](https://user-images.githubusercontent.com/42398485/79777964-a2ed0300-82fd-11ea-9356-2991dffd1bba.png)

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 Used `Customer` account
![image](https://user-images.githubusercontent.com/42398485/80569567-d0e9db80-89be-11ea-8612-b1bb0c00b3f0.png)

@drasticdpk @lakshmiathreya Please check it on `Manager` and `Copilot` Logins

**Comment by lakshmiathreya** [comment]
Looks fine with Manager logins on Prod.
