### ISSUE TITLE
Invite test@test.com using emial will create multiple invites

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3834]
### Expected behavior
Should not create multiple requests

### Actual behavior
Invite test@test.com using email will create multiple invites

### Steps to reproduce the problem
- Login as Customer
- Click on a project from the project listing page
- Click "Dashboard"
- On "Customer team" > Click 'Manage Invitations'
- Enter 'test@test.com' 
- Click 'Send Invite'

### Screenshot/screencast

https://www.screencast.com/t/fP8OW738eHg

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  TopConnCustomer

**Comment by maxceem** [comment]
@codejamtc moved this issue to the next release, as `2.8` is already released.

**Comment by maxceem** [comment]
I think it has the same root as https://github.com/appirio-tech/connect-app/issues/3944

**Comment by vikasrohit** [comment]
@maxceem do you think it is because of bad data in dev env? If not, I think we need to take this on priority as it might appear for some customer.

**Comment by maxceem** [comment]
@vikasrohit I moved it to the current milestone. Have to check what is the reason.

**Comment by maxceem** [comment]
@codejamtc I cannot reproduce this issue anymore, though I can reproduce another one https://github.com/appirio-tech/connect-app/issues/3944.

Could you please let me know if you still can reproduce this issue?

**Comment by codejamtc** [comment]
@maxceem Yes, can't reproduce anymore
https://monosnap.com/file/4OUdoXgsknxzNQM0wswpGQmWowHlXr

**Comment by codejamtc** [comment]
@maxceem Can reproduce in `Prod` ❌ 

https://monosnap.com/file/n4tGywGUACWwHzzFtTY7eNo73ucyvo

**Comment by maxceem** [comment]
Can reproduce in PROD too:

![image](https://user-images.githubusercontent.com/146016/79892349-1f213c80-840b-11ea-82b8-c99fdcebb8f5.png)

Thank you!

**Comment by maxceem** [comment]
This issue is fixed, but as it can be only reproduced on PROD, we could test it only after the release.

**Comment by vikasrohit** [comment]
@maxceem though the solution looks good to me, it won't work on production because I found multiple users with that same email. So, I think your new filter would still keep them all. I think there are two steps needed to fix the situation:

1. Make only one user with that email active and make rest inactive/disabled.
2. In our api, lets ask for status field when looking up for emails and use that to filter out users who are not active (`status!=='A'`)

**Comment by maxceem** [comment]
> because I found multiple users with that same email

Oh, didn't expect that.

> In our api, lets ask for status field when looking up for emails and use that to filter out users who are not active (status!=='A')

This sound good, will try it out.

**Comment by maxceem** [comment]
@vikasrohit for searching by email we are using Identity Service `https://api.topcoder-dev.com/v3/users?fields=handle,id,email&filter=email=test@test.com`.

Could you please point me on to the repository of this service, so I would check if we can filter by status, I cannot find it, not sure if I have access.

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 
https://monosnap.com/file/lAjpngsP3nsJzssfSRGPsUHBr4cXkK

**Comment by vikasrohit** [comment]
@maxceem did we apply any fix for this issue?

**Comment by maxceem** [comment]
Yes, but it's not enough. We have to additionally filter users by `status` and exclude not active users. It works good on DEV, but on PROD, such request hangs. So we didn't apply the full fix and waiting for the Member Service team to clarify this behaviour.

**Comment by vikasrohit** [comment]
Yep, agreed on that, however, I am concerned that when didn't apply that fix, how this is working fine now on production, I can still see multiple users with same email on production.

**Comment by maxceem** [comment]
> how this is working fine now on production, I can still see multiple users with same email on production.

@vikasrohit it doesn't work for me.

@codejamtc this issue failed for me in PROD 

![image](https://user-images.githubusercontent.com/146016/80591345-3ae99b80-8a26-11ea-85e1-d913974aa25f.png)

**Comment by codejamtc** [comment]
@maxceem Yes, I can see it now. https://monosnap.com/file/bZIrIRs5aPn44KnUWCbPfGsBRjpxc6 (But I when I test it earlier, that worked for me, maybe because the test@test.com is already there and I had to remove it to test the issue - https://monosnap.com/file/lAjpngsP3nsJzssfSRGPsUHBr4cXkK)
