### ISSUE TITLE
[$10] "You're about to edit an attachment" section overlap with the header while scrolling

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3835]
### Expected behavior
Should not overlap

### Actual behavior
"You're about to edit an attachment" section overlap with the header while scrolling

### Steps to reproduce the problem
- Login as Customer
- Click on a project from the project listing page
- Click "Assets Library" > Files
- Click 'Add New' and browse a file
- Click on the sub-menu on the file row > Edit
- Scroll the screen up

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78243587-a97c1d80-74a9-11ea-87c3-3dfa1e1f56f8.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Customer
- Account used:  `TopConnCustomer`

**Comment by maxceem** [comment]
@codejamtc moved this issue to the next release, as `2.8` is already released.

**Comment by maxceem** [comment]
Sum up:
- the same should be fixed when editing links

   ![image](https://user-images.githubusercontent.com/146016/79427546-8a16e180-7fcd-11ea-94af-81060c5c1757.png)

- good project for demo https://connect.topcoder-dev.com/projects/8600/assets

**Comment by maxceem** [comment]
This issue is open for pickup.

**Comment by Vips19** [comment]
@bug-bash-helper assign

**Comment by Vips19** [comment]
@bug-bash-helper #3916  is ready for review

**Comment by codejamtc** [comment]
Fixed: 🆗 https://monosnap.com/file/PFDb17gxJI5EJzOKGO4dDvwJ3Bw6El

**Comment by drasticdpk** [comment]
Verified on prod.
![image](https://user-images.githubusercontent.com/25297859/80568183-4208ad80-8a16-11ea-8833-74a672b54001.png)
![image](https://user-images.githubusercontent.com/25297859/80568223-59e03180-8a16-11ea-9469-23b9d09bec11.png)
