### ISSUE TITLE
User can't download the file attached 

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3839]
### Expected behavior
Should be able to download the file.

### Actual behavior
After changing the file name, the user can't download the file

### Steps to reproduce the problem
- Login as Customer
- Click on a project that has permission
- Click "Assets Library"
- Upload a file (Word.doc) and select 'Member X' from the 'OR ONLY SPECIFIC PEOPLE' section > Click 'Share with selected members
- Click on the file to download

File Used: 
[CSVFile_119kb (1).zip](https://github.com/appirio-tech/connect-app/files/4424034/CSVFile_119kb.1.zip)

### Screenshot/screencast

https://monosnap.com/file/QuyKkv3m0AkS4DcySjK8p5XE18ivVc

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Customer
- Account used:  CustomerUser

**Comment by maxceem** [comment]
This is fixed as a hotfix in Project Service:
- DEV https://github.com/topcoder-platform/tc-project-service/pull/526 (already merged to DEV)
- PROD https://github.com/topcoder-platform/tc-project-service/pull/527

**Comment by maxceem** [comment]
@codejamtc thank you for catching it! We already fixed this issue on DEV and PROD, could you please verify?

**Comment by codejamtc** [comment]
@maxceem File download is working
