### ISSUE TITLE
[$45] User needs to refresh the page to see the updated link count

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3841]
### Expected behavior
It should automatically update link file count when the user closes the message thread

### Actual behavior
User needs to refresh the page to see the updated link count

### Steps to reproduce the problem
- Login as Customer
- Click on a project that has permission
- Click "Messages"
- Click on a message thread that has 1 file and 1 link
- Click Edit Post > Add a file and insert a link > Click 'Update Post'
- Check the count

### Screenshot/screencast

https://monosnap.com/file/b0dWLGvOiXQz74ySKfywQ9y0ZIKti7

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Customer
- Account used:  CustomerUser

**Comment by maxceem** [comment]
This issue is open for pickup.

**Comment by sumitdaga** [comment]
@bug-bash-helper assign

**Comment by sumitdaga** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3919 is ready for review

**Comment by maxceem** [comment]
@sumitdaga review is done https://github.com/appirio-tech/connect-app/pull/3919#pullrequestreview-395916075

**Comment by sumitdaga** [comment]
@bug-bash-helper #3919 is ready for review

**Comment by maxceem** [comment]
### Test guidelines

We have to test 2 cases:
1. Edit message adding new link as per this issue https://github.com/appirio-tech/connect-app/issues/3841#issue-592902684
2. Add a new message to the topic with a link, see https://github.com/appirio-tech/connect-app/pull/3919#pullrequestreview-395916075

**Comment by maxceem** [comment]
Thanks for finding and fixing a new case @sumitdaga https://github.com/appirio-tech/connect-app/pull/3919#issuecomment-615895428.

The prize for the issue is increased to $45.

**Comment by codejamtc** [comment]
https://monosnap.com/file/OrIP1NuePfrwJhKCJBrlnXkMdsQN0s

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 
https://monosnap.com/file/Q7JSv2tzoTzhnknyxerUiyl3Q4GNY6
