### ISSUE TITLE
[$15] UI issue when we invite a member with a long email

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3842]
### Expected behavior
The email should be trimmed 

### Actual behavior
UI issue when we invite a member with a long email

### Steps to reproduce the problem
- Login as Customer
- Click on a project that has permission
- Click "Manage Incitations"
- Enter 'pablodiegojosfranciscodepaulajuannepomuceno@gmail.com' > Send Invite

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78304741-05c05b00-7505-11ea-8a47-b1e3717abb24.png)
![image](https://user-images.githubusercontent.com/42398485/78304759-0e189600-7505-11ea-8a38-958e55a39899.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Customer
- Account used:  CustomerUser

**Comment by maxceem** [comment]
In the tooltip we have to make sure, that:
- **email** or **username** is cut, so the `Invite` level is visible (currently it's not):

   invite by **username**:

   ![image](https://user-images.githubusercontent.com/146016/79425161-f4c61e00-7fc9-11ea-8d89-6c597f88084a.png)

   invite by **email**:

   ![image](https://user-images.githubusercontent.com/146016/79425752-d6aced80-7fca-11ea-9be9-5d7b9467b3b3.png)

- when **email** or **username** is cut, we should show an ellipsis `...` at the end

In the dialog:
- if we invite user by email, it's already cut, but we have to show elliplisi `...` at the ned, now we don't show it:

   ![image](https://user-images.githubusercontent.com/146016/79425627-a49b8b80-7fca-11ea-84b0-688f2549fd87.png)

**Comment by maxceem** [comment]
This issue is open for pickup.

**Comment by nahidshahin** [comment]
@bug-bash-helper assign

**Comment by nahidshahin** [comment]
@bug-bash-helper #3918 is ready for review

**Comment by codejamtc** [comment]
Fixed 🆗 https://monosnap.com/file/bqlWIXPlKGDzn24ogu2veH4GNxGN26

![image](https://user-images.githubusercontent.com/42398485/79773260-d5dfc880-82f6-11ea-9c84-3d3fca5ee327.png)

![image](https://user-images.githubusercontent.com/42398485/79773285-e132f400-82f6-11ea-9971-cd866c026b77.png)

**Comment by codejamtc** [comment]
Partial QA pass in `Production`: ⚠️ 

![image](https://user-images.githubusercontent.com/42398485/80568903-72702d80-89bd-11ea-8210-5f97a3fb2479.png)

![image](https://user-images.githubusercontent.com/42398485/80569052-b82cf600-89bd-11ea-965b-24931b3e6404.png)

**Failed in Firefox** @maxceem @vikasrohit 

![image](https://user-images.githubusercontent.com/42398485/80569096-d2ff6a80-89bd-11ea-8e01-b0559c59816a.png)

**Comment by maxceem** [comment]
@vikasrohit how to proceed if issue indeed failed in some case? 
Create a new issue for the next release? 
Or just keep the current issue as failed and fix it in the next release again?
Or fix it as a hotfix?

**Comment by codejamtc** [comment]
Fixed in `Dev`: 🆗 

![image](https://user-images.githubusercontent.com/42398485/80708593-914fec00-8ab1-11ea-9314-8d7ac594bede.png)

**Comment by drasticdpk** [comment]
Same issue on prod env /Firefox.
@maxceem how do we know if the issue is ready for prod testing  or not ? Can we add new label 'Ready For Prod QA', please suggest.
![image](https://user-images.githubusercontent.com/25297859/80985674-420e1080-8e4f-11ea-9773-f85cbff74fe7.png)

**Comment by maxceem** [comment]
@drasticdpk I guess we can let you know on Slack when it's ready for testing as we don't have a special label for this.

**Comment by maxceem** [comment]
@vikasrohit @lakshmiathreya should we have a special label for such situations?

**Comment by drasticdpk** [comment]
QA Fail prod prod.
![image](https://user-images.githubusercontent.com/25297859/81170404-57537e00-8fba-11ea-8ab5-55d076c26227.png)

**Comment by maxceem** [comment]
@drasticdpk issues in milestone `2.9.1` https://github.com/appirio-tech/connect-app/milestone/92 are not yet deployed to PROD.

**Comment by vikasrohit** [comment]
> Can we add new label 'Ready For Prod QA', please suggest.

@drasticdpk @maxceem I don't think we need such label, it would just increase the work for dev team. We are already making notifications about release in Slack with the details of release which has the milestone as well, so it should be pretty straightforward to start testing for certain milestone on prod after we have notified the successful release in Slack.

**Comment by drasticdpk** [comment]
Verified on prod env 
![image](https://user-images.githubusercontent.com/25297859/81264381-03e83b00-9061-11ea-9ae5-07642e32a437.png)
> We are already making notifications about release in Slack with the details of release which has the milestone as well, so it should be pretty straightforward to start testing for certain milestone on prod after we have notified the successful release in Slack.

Ok noted cc @vikasrohit

**Comment by lakshmiathreya** [comment]
Admin view in Prod :
<img width="1360" alt="Screenshot 2020-05-07 at 1 03 41 PM" src="https://user-images.githubusercontent.com/51733042/81266908-3e52d780-9063-11ea-8607-9f2f034b9c76.png">
