### ISSUE TITLE
[$10] Customer and Topcoder dropdown filter overlap with the user avatar's on the table

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3843]
### Expected behavior
Should open the filter above the user avatar

### Actual behavior
Customer and Topcoder dropdown filter overlap with the user avatar's on the table

### Steps to reproduce the problem
- Login as Customer
- Switch to List view
- Click on Customer and Topcoder dropdown

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78305101-bfb7c700-7505-11ea-8022-d66eb730b03d.png)
![image](https://user-images.githubusercontent.com/42398485/78305106-c5151180-7505-11ea-9400-05ff4cdf6862.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Customer
- Account used:  CustomerUser

**Comment by maxceem** [comment]
The same time it works good in a similar place on the Assets Library page https://connect.topcoder-dev.com/projects/8600/assets

![image](https://user-images.githubusercontent.com/146016/79424673-30acb380-7fc9-11ea-925c-7560d746247d.png)

We have to make sure, that while fixing this issue we don't break something else.

**Comment by maxceem** [comment]
This issue is now open for pickup.

**Comment by Giri-Suman** [comment]
@bug-bash-helper assign

**Comment by Giri-Suman** [comment]
@bug-bash-helper #3925 is ready for review

**Comment by maxceem** [comment]
@Giri-Suman the review is ready, please have a look https://github.com/appirio-tech/connect-app/pull/3925#pullrequestreview-395988272

**Comment by Giri-Suman** [comment]
@bug-bash-helper #3925 is ready for review

**Comment by codejamtc** [comment]
https://monosnap.com/file/1gQoSGoOEs2eWpRwV3mvum307lGZWz

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 
https://monosnap.com/file/3eVPgGBIMBjZTaNMfYEzEdxBBtu7fH
