### ISSUE TITLE
UI issue when the user opens the "Add New File" upload popup when there is an edit file model active

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3849]
### Expected behavior
Should not appear the model below the edit form and then move up. Sometimes the screen flickers, Some items are displayed above the overlay initially, check File Asset menu

### Actual behavior
UI issue when the user opens the "Add New File" upload popup when there is an edit file model active

### Steps to reproduce the problem
- Login as Manager
- Click on a project that has permission
- Click "Assets Library" > Files Tab
- Edit a File
- To Upload a file Click 'Add New...' button
- Observe

### Screenshot/screencast

https://www.screencast.com/t/dUOET4r4V

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
What is the expected behaviour in this case @codejamtc @lakshmiathreya ? Consider the case where user has some unsaved changes in the edit form.

**Comment by codejamtc** [comment]
@vikasrohit I think when the file upload opens; it should open above the edit window. Now it is opening behind the edit form and then moved back to the top cc @lakshmiathreya 

> Consider the case where user has some unsaved changes in the edit form. 

If a user added a new file it will be added to the list but that process should not close the edit window (thay way it is easy)

If we try to close the edit window when user click on `Add new`, then we need to display a message for unsaved data and the process will be more complex

**Comment by vikasrohit** [comment]
> I think when the file upload opens; it should open above the edit window. Now it is opening behind the edit form and then moved back to the top 
I don't think that is a problem as it rendering it self finally on top of the edit form. I think it is its animation effect that is causing that view. Anyway, it renders itself in correct position, so I think we are good with that.
Please log a separate issue for the behavioral part that we discussed. I mean how it is behaving right now when user adds a file when edit form is already open. We can then decide how to fix that situation.
