### ISSUE TITLE
C# tag displayed twice

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3851]
### Expected behavior
Should display only one time

### Actual behavior
C# tag displayed twice

### Steps to reproduce the problem
- Login as Manager
- Click 'Create New Project' > Talent as a Service (TaaS) 
- Go to 'What skills are important for your team to have?*'
- Type `c#` and add to the list
- Type `C#` and add to the list

### Screenshot/screencast

https://www.screencast.com/t/qDQRG18qHSi

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
@maxceem I saw somewhere we fixed such issue with duplicate tags. Is this different?

**Comment by maxceem** [comment]
Look like the fix we have doesn't take into account lowe/uppercase, i. e. it treats tags with different letter case as different tags.

**Comment by vikasrohit** [comment]
Okay, @maxceem  do you think it would cause any trouble with making it case insesitive?

**Comment by maxceem** [comment]
@vikasrohit no, it should be good to make it case-insensitive.

**Comment by vikasrohit** [comment]
ok, keeping it for 2.10 milestone.

**Comment by maxceem** [comment]
This should be fixed as a part of https://github.com/appirio-tech/connect-app/issues/3816

**Comment by codejamtc** [comment]
https://monosnap.com/file/IrW7b6UxyqZ4ufz7pBoCLkNYrjhONU

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 

![image](https://user-images.githubusercontent.com/42398485/80574306-3641ca80-89c7-11ea-8a51-c017e846c93e.png)
