### ISSUE TITLE
"What are common success indicators?" popup content UI issue

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3852]
### Expected behavior
"In Topcoder’s history, data visualization project success has often been based on the following attributes:" text should align properly

### Actual behavior
"What are common success indicators?" popup content UI issue

### Steps to reproduce the problem
- Login as Manager
- Click 'Create New Project' > Data Visualization
- Go to 'What will qualify this data visualization project as a success for you?'
- Click 'What are common success indicators?' hyperlink

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78598689-58f02180-7815-11ea-9d8f-52a414f7f8e1.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
Data is updated on both dev and production.

**Comment by codejamtc** [comment]
@vikasrohit Yes
![image](https://user-images.githubusercontent.com/42398485/78897899-8537b800-7a38-11ea-85f9-c5172cf5fa90.png)
