### ISSUE TITLE
Assets Library > Files folder icon and text is not aligned properly

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3854]
### Expected behavior
Should display the icon and text in-line

### Actual behavior
Assets Library > Files folder icon and text is not aligned properly

### Steps to reproduce the problem
- Login as Manager
- Click on a project > Assets Library {https://connect.topcoder-dev.com/projects/9057/assets}
- Select files and check the folders
 

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78626724-3251db00-7855-11ea-99eb-e3fd3f1d7a2a.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
@codejamtc @maxceem  we don't space to render it in single line, however, we may use ellipsis for such fixed texts `Only Topcoder Members` and show the full text in tooltip

**Comment by codejamtc** [comment]
@vikasrohit In meant (This is a trivial one)

![image](https://user-images.githubusercontent.com/42398485/78679854-5b538980-78b0-11ea-8ebe-75cbb6d508b4.png)

**Comment by vikasrohit** [comment]
okay. You think, vertically middle alignment is better than top one, right? We can do that as well. @maxceem lets keep it 2.9.

**Comment by maxceem** [comment]
> You think, vertically middle alignment is better than top one, right?

I would suggest to vertically align icons with the first line only. As now icons are slightly more down than the middle of the first line.

**Comment by vikasrohit** [comment]
oh, I think they aligned even right now in that term. It looks bit off because of some icons does not occupy the full square grid.

**Comment by maxceem** [comment]
Fixed via 1d5e2ec1015e632f26ceeca12d98cc9a7eb8a7cb

I've fixed alignment with the first line, so it looks like this (see project https://connect.topcoder-dev.com/projects/8600/assets for demo):

![image](https://user-images.githubusercontent.com/146016/79341637-c9ddba80-7f34-11ea-822a-313d92961b14.png)

![image](https://user-images.githubusercontent.com/146016/79341754-f1348780-7f34-11ea-98ff-41d2cc1c5c2c.png)

![image](https://user-images.githubusercontent.com/146016/79341680-d8c46d00-7f34-11ea-8a21-b9ba2584aea9.png)

Let me know if it looks good to you or no @codejamtc @vikasrohit.

**Comment by codejamtc** [comment]
https://monosnap.com/file/YF8CGewQPffNDnR8F7LVoqWZFxGCgZ

**Comment by drasticdpk** [comment]
verified on Prod 
![image](https://user-images.githubusercontent.com/25297859/80569564-e7bd1c00-8a18-11ea-8efa-583259856fee.png)
