### ISSUE TITLE
Permissions regression testing

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3856]
#### Make regression testing after internal work is done but functionality should work as before

We've made the first step to improve how we handle the permissions internally as per https://github.com/appirio-tech/connect-app/issues/2841 via https://github.com/appirio-tech/connect-app/pull/3847.

The code to handle permissions has been updated for a couple of places, though functionality shouldn't be changed, so now we have to make sure the functionality works as before.

Here is the guide on how to test the places with updated logic https://docs.google.com/document/d/1XZpUstQcIXnegAGtthSIqNTGiHbskwPKp9lw-D6qhQY/edit#
- On our main DEV website, we have a version WITHOUT changes https://connect.topcoder-dev.com/
- The updated version has been deployed to TEST website https://connect-test01.topcoder-dev.com/

So we can use both these versions of the website and make sure that after the update it works the same as before

For these places, we created a central place to list permissions https://htmlpreview.github.io/?https://github.com/appirio-tech/connect-app/blob/feature/permissions/docs/permissions.html. We are planning to move all the permissions in this central place with time.

**Comment by codejamtc** [comment]
I am going to test this one cc @maxceem

**Comment by codejamtc** [comment]
Ref: https://docs.google.com/document/d/1XZpUstQcIXnegAGtthSIqNTGiHbskwPKp9lw-D6qhQY/edit#

1. "Connect Admin" or "administrator" user can see "Manage" button for Topcoder Team, and inside Topcoder Team dialog can see "Remove" button and invite new members WITHOUT JOINING the project (see Join Button is visible): 🆗 
**User:** `topcoderconnect+Admin@gmail.com` (He is not part of Project `9057`)
**URL:** https://connect-test01.topcoder-dev.com/projects/9057
**Compared with:** https://connect.topcoder-dev.com/projects/9057

https://monosnap.com/file/bOMy35l8NCd2za2gencxgiwCUHQeRu

2. Other users cannot manage Topcoder Team and can only see "View" button without the ability to invite new members or remove: 🆗 
**User:** `topcoderconnect+AccountManager@gmail.com` (He is not part of Project `9057`)
**URL:** https://connect-test01.topcoder-dev.com/projects/9057
**Compared with:** https://connect.topcoder-dev.com/projects/9057

https://monosnap.com/file/Pl6FLYDqJLvpbUHJ1pGe5VhIuXcaui

3. When users are a part of the Topcoder Team, they also can see the "Manage" link, invite new members and remove members: ❌ 
**User:** `topcoderconnect+Manager@gmail.com` (He is part of Project `9057`)
**URL:** https://connect-test01.topcoder-dev.com/projects/9057
**Compared with:** https://connect.topcoder-dev.com/projects/9057

https://monosnap.com/file/m0cYiktATKiBbcwVtlPREpbf0UFYyT

- In `connect-test01.topcoder-dev.com`, I can see only the `View` option for `Manager` (He is part of Project `9057`). 

Then I thought `pshah_manager` is the original owner with `Manager` permission and `TCConManager` is added as `Manager` to the project after (I can see Leave option). Then I logged in with `pshah_manager` but I still can't see Manage option and invite new members and remove members.

https://monosnap.com/file/kBZPEU3EWSz2e4fqrCx1DyxV4tcoQu

4. "Connect Manager" can edit phone and company name 🆗 
**User:** `topcoderconnect+Manager@gmail.com` 
**URL:** https://connect-test01.topcoder-dev.com/projects/9057
**Compared with:** https://connect.topcoder-dev.com/projects/9057

5. Customer aka "Topcoder User" can edit company name but not the phone number: (This must be a typo) actually it should be **Customer aka "Topcoder User" can edit the phone number but not the company name:** 🆗 
**User:** `topcoderconnect+Customer@gmail.com`
**URL:** https://connect-test01.topcoder-dev.com/projects/9057
**Compared with:** https://connect.topcoder-dev.com/projects/9057

6. Copilot "Connect Copilot" cannot edit phone or company name: ⚠️ 
**User:** `topcoderconnect+Copilot@gmail.com`
**URL:** https://connect-test01.topcoder-dev.com/projects/9057
**Compared with:** https://connect.topcoder-dev.com/projects/9057

- Even though the two fields are displayed as disabled users can still change the country code by dropdown. So we have to disable it even though we can't save it

https://monosnap.com/file/sr0iapyrRFVZsZCNel54I2TEUXvfPI

7. Project 'manager' user can edit phases when they are not completed, but cannot edit completed: ❌
**User:** `pshah_manager` 
**URL:** https://connect-test01.topcoder-dev.com/projects/9056
**Compared with:** https://connect.topcoder-dev.com/projects/9056

- Here 'Manager' user can't edit phases when they are not completed

![image](https://user-images.githubusercontent.com/42398485/78703282-84cfdd80-78cf-11ea-9693-efffe3d83e9c.png)

8. 'customer' project members cannot edit phases in any state: 🆗 
**User:** `pshah_customer` 
**URL:** https://connect-test01.topcoder-dev.com/projects/9056
**Compared with:** https://connect.topcoder-dev.com/projects/9056

9. Admins can edit phases even if they are completed: 🆗 
**User:** `topcoderconnect+Admin@gmail.com` 
**URL:** https://connect-test01.topcoder-dev.com/projects/9056
**Compared with:** https://connect.topcoder-dev.com/projects/9056

https://monosnap.com/file/KFGK09JkwCpDAP1tIfpZVoXYyVYXcp

**Comment by maxceem** [comment]
@codejamtc cases 3 and 7 should be fixed now, could you please check them again.

Regarding issue 6 for copilots, as it's not directly connected with permissions, but an issue with the control element we use, could you please create a separate issue for this.

**Comment by codejamtc** [comment]
7 - {Fixed} 🆗 
![image](https://user-images.githubusercontent.com/42398485/78991665-16716200-7aff-11ea-944a-ee6cc4f7279c.png)

3 - {Fixed} 🆗 
![image](https://user-images.githubusercontent.com/42398485/78991766-51739580-7aff-11ea-8bf5-42365052ca9b.png)

**Comment by maxceem** [comment]
@codejamtc did this pass QA on TEST, or you are still testing something?

**Comment by codejamtc** [comment]
@maxceem I am checking others also to check whether anything is broken :)

**Comment by codejamtc** [comment]
@maxceem Pass 🆗

**Comment by maxceem** [comment]
Thank you @codejamtc for comprehensive testing, it helped to find a critical issue.

**Comment by vikasrohit** [comment]
Thanks @codejamtc for the regression testing.

**Comment by vikasrohit** [comment]
@codejamtc @lakshmiathreya closing the issue for now as it seems some specific use case is pending for testing. Please feel free to reopen it if it fails for that use case.
