### ISSUE TITLE
[$40] Sometimes when the user doesn't have permission to edit file/links; app shows the Remove/Edit options.

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3858]
### Expected behavior
Should remove those two options if that user doesn't have permission to edit/delete

### Actual behavior
Sometimes when the user doesn't have permission to edit file/links; app shows the Remove/Edit options. Instead, it will show an error message. So to be consistent with the other locations should remove the options

### Steps to reproduce the problem
- Login as Manager
- Click on a project > Assets Library {https://connect.topcoder-dev.com/projects/9057/assets
- Select Links > In `test` {04/02/2020 6:25 AM} Click on the sub-menu > Edit
- Change the name and click Edit link

### Screenshot/screencast

https://www.screencast.com/t/Z69rFgP39

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by maxceem** [comment]
Sum up:
- Only users WHO created link can edit/delete them. So we only have to show `...` menu if the current user created such a link, we already do this for files.
- Additionally to the user WHO created file or link, administrators can edit files and links. So please, fix it for both files and links, so administrators also can see the menu to edit/delete files and link.
   - add a new permission `MANAGE_NOT_OWN_ATTACHMENT` as per https://github.com/appirio-tech/connect-app/blob/dev/docs/permissions-guide/permissions-guide.md. Only users with topcoder roles `administrator` and `Connect Admin` should have this permission.
   - use this permission to show the menu for admins, additionally to the users WHO created an attachment
   - as we cannot share a user with admin credentials, for testing, you may manually add user role you want to test with on this line https://github.com/appirio-tech/connect-app/blob/cf-22/src/actions/loadUser.js#L56, like this:
     ```js
     if (!currentUser.roles) {
       currentUser.roles = []
     }
     currentUser.roles.push(ROLE_ADMINISTRATOR)
     ```
     See screenshot:

     ![image](https://user-images.githubusercontent.com/146016/79429980-eaf3e900-7fd0-11ea-911b-c91632f59011.png)

**Comment by maxceem** [comment]
This issue is open for pickup.

**Comment by rashmi73** [comment]
@bug-bash-helper assign

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3926 is ready for review

**Comment by maxceem** [comment]
@rashmi73 the review is ready, please have a look https://github.com/appirio-tech/connect-app/pull/3926#pullrequestreview-395988992

**Comment by rashmi73** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3926 is ready for review

**Comment by codejamtc** [comment]
Verified: 🆗 Only the file/link owner can edit/remove the asset + Connect Admin

**Edit:** https://monosnap.com/file/UDGyecp2d4VGEwsrwV0w8g8z7csW97
**Remove:** https://monosnap.com/file/2m4uBSCuxlPMmsuvkxZph5piwog4b8

**Comment by codejamtc** [comment]
Verified: 🆗 Only the file/link owner can edit/remove the asset 
@lakshmiathreya @drasticdpk Please check using Admin account and Manager account
https://monosnap.com/file/fMJsSXcmDsZUyAovTHAtzAqEkuV0KC

**Comment by lakshmiathreya** [comment]
Verified on Prod - only File/Link owner or Admin/Connect Admin has edit permission.

**Comment by drasticdpk** [comment]
Verified for prod with copilot Role.
