### ISSUE TITLE
[App Design & Dev] - the selected sections are not displayed bold

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#386]
Expected behavior
------------------------------------------------------------

- Display with bold text the selected text section.

Actual behavior
------------------------------------------------------------

- The selected text section is not displayed with bold text. 

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager.

- New Project.

- Move the horizontal slider to the left.

- Observe the text of section,

Environment
------------------------------------------------------------
Operating System(s): Windows 7 Professional / 64 bit
Browser(s):  IE 11.0
User role: connect user role
Account used: christina_uw

![1](https://cloud.githubusercontent.com/assets/5114907/18984641/632e47b6-86fc-11e6-8ca4-46d446ccf3d7.png)

**Comment by onetliviunicolae** [comment]
Observation

- The text is displayed as bold if the user press on the name eg. press on Prototype an app!

**Comment by mahestro** [comment]
True, good observation. Valid.
