### ISSUE TITLE
[$25] Clicking on the 'Read more' link will redirect the page to an incorrect one.

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3868]
### Expected behavior
Should redirect the page to `https://connect.topcoder-dev.com/projects/8699/scope`

### Actual behavior
Clicking on the 'Read more' link will redirect the page to an incorrect one. The current link is pointed to `https://connect.topcoder-dev.com/projects/8699/specification` but I can't see any sub-page with the `/specification`.

### Steps to reproduce the problem

- Login as Manager
- Turn ON the 'My Projects' toggle
- Go to 'Grid view' > Click 'read more' from the 'sasasasas3212121' Projects
- Hovering over the link will show the link as `https://connect.topcoder-dev.com/projects/8699/specification`
- Check the page that loads (Check the page loads when user click on the `read more` link inside the project dashboard)

### Screenshot/screencast

https://monosnap.com/file/hChO70u92zVZGS3VnvOdGulufyw6my

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
@codejamtc both links are valid. Old (I don't defined parameter to say old, but it about more than year) projects which has specifications tab while we changed after that to be Scope. So, there is internal redirection happening for that. However, for consistency, it should have same link at both `read more` links, one at Card View and another in projects details page.
@maxceem can you please confirm and close the issue if it does not need any fix.

**Comment by codejamtc** [comment]
@vikasrohit Agree, redirection is happening but to the wrong place right. 

https://connect.topcoder-dev.com/projects/9074/specification >> https://connect.topcoder-dev.com/projects/9074 NOT to the https://connect.topcoder-dev.com/projects/9074/scope

**Comment by maxceem** [comment]
There appear to be 2 issues:
1. Link is wrong, it should lead to `/scope` for this project, it's fixed via 309ef038d16f83c690f92ec6b907befd99cf5bc7

2. When we click the `read more` link on the card there is double link:
     - the whole card is link to the project Dashboard page
     - `read more` is link to the project Spec/Specification page

    So when we click `read more` link, we first open Spec/Specification page and immediately after that Dashboard page.

So now we have to fix the 2nd issue, when we click `read more` link, it should let the outer link to on the whole card to be processed. And we should get to the Spec/Specification page.
But if we click on the card outside the `read more` link, then we should open the project dashboard as it's done now.

**Comment by codejamtc** [comment]
@maxceem 

1. I check the fix, When I click `read more` I can see the URL as https://connect-test01.topcoder-dev.com/projects/9074/specification 
2. But when I click on it the page redirects to `Dashboard`, not to `Scope`
Is my understanding correct?

https://monosnap.com/file/WufreGo4WK3wvLXx9lDdoAU7lCtq6Y

**Comment by maxceem** [comment]
@codejamtc please, use DEV env for testing of this issue https://connect.topcoder-dev.com/projects. The TEST env is only for testing Permission Regression issue.

**Comment by maxceem** [comment]
> But when I click on it the page redirects to Dashboard, not to Scope
Is my understanding correct?

Yes, this issue is not fixed yet, it's part 2 of this issue.

**Comment by codejamtc** [comment]
@maxceem Sorry wrong URL in the comment, I will fix it

**Comment by vikasrohit** [comment]
> So now we have to fix the 2nd issue, when we click read more link, it should let the outer link to on the whole card to be processed. And we should get to the Spec/Specification page.

@maxceem you meant, *should NOT let*, right?

As the part 1 is already fixed in current code, I would like to get the part 2 wrapped as well.

**Comment by maxceem** [comment]
Sum up:
- implement the second fix as per https://github.com/appirio-tech/connect-app/issues/3868#issuecomment-612020855
- If you login with `pshah_manager` user and filter by `Paused` status, there would be projects with `scope` and `specification` links for testing, see URL https://connect.topcoder-dev.com/projects?sort=lastActivityAt%20desc&status=paused

    ![image](https://user-images.githubusercontent.com/146016/79319422-f7b10800-7f10-11ea-8ce6-7b561ea016d0.png)

   scroll a bit down:

    ![image](https://user-images.githubusercontent.com/146016/79319470-08617e00-7f11-11ea-988d-1b90e0d7779c.png)

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper assign it to me

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3914 is ready for review

**Comment by maxceem** [comment]
@PrakashDurlabhji here is the review, please, have a look https://github.com/appirio-tech/connect-app/pull/3914#pullrequestreview-395896879

**Comment by PrakashDurlabhji** [comment]
@maxceem found a solution which is simpler

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3934 is ready for review

**Comment by maxceem** [comment]
@PrakashDurlabhji the review is ready, please have a look https://github.com/appirio-tech/connect-app/pull/3934#pullrequestreview-395991805

**Comment by Giri-Suman** [comment]
@maxceem can i take it ?

**Comment by maxceem** [comment]
@Giri-Suman no, this issue is not open for pickup. The current participant sill may fix it.

**Comment by Giri-Suman** [comment]
@maxceem, but its more than 22 hrs.

**Comment by maxceem** [comment]
Yeah, it's preferably to provide a fix asap. But as review could be done at any moment, it could be the night at the participant timezone, so we give more time for fixing issues found during the review.

**Comment by Giri-Suman** [comment]
@maxceem yea got it.

**Comment by maxceem** [comment]
@PrakashDurlabhji will you be able to complete this issue? If you couldn't make it for 24 hours, I would have to unassign you.

**Comment by PrakashDurlabhji** [comment]
@maxceem sorry i forgot its in my pending list, I thought its completed. just 20mins max

**Comment by PrakashDurlabhji** [comment]
@maxceem https://github.com/appirio-tech/connect-app/issues/3868 is ready for review

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper #3868 is ready for review

**Comment by maxceem** [comment]
@PrakashDurlabhji one of the issues still not fixed https://github.com/appirio-tech/connect-app/pull/3934#pullrequestreview-396377516

**Comment by PrakashDurlabhji** [comment]
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3934 is ready for review

**Comment by codejamtc** [comment]
@maxceem Fixed 🆗 
https://monosnap.com/file/U378E8HLb5LDtOMooEGNTQ0UUhglVz

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 
https://monosnap.com/file/jQTRFZ1ZxmCDxxPGGfsXwZSVXUO6bS
