### ISSUE TITLE
`What kind of application would like to test` dropdown is too close to the label

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3869]
### Expected behavior
Should have space between the controllers

### Actual behavior
`What kind of application would like to test` dropdown is too close to the label

### Steps to reproduce the problem

- Login as Manager
- Turn ON the 'My Projects' toggle
- Tap on a project and open it {https://connect.topcoder-dev.com/projects/8699}
- Tap Scope: https://connect.topcoder-dev.com/projects/8699/scope
- Expand the `What kind of application would like to test`

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78921850-2899c480-7a5b-11ea-9b0b-bfa7024b7525.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
@codejamtc this project was created from a template which is no longer in use. Essentially, we don't use dropdown unless there is no other option, for project template forms. Closing the issue.
