### ISSUE TITLE
[Edit Project] - add button is not full visible

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#387]
Expected behavior
------------------------------------------------------------

- The Add button must be full visible.

Actual behavior
------------------------------------------------------------

- The Add button is not full visible.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Edit an existing project ex. 30.09.

- Press "+" button to add a new team member.

- Compete Add Team Member field with test.

- Select the user "test007" from the autocomplete list.

Environment
------------------------------------------------------------

Operating System(s): Windows 7 Professional / 64 bit

Browser(s):  IE 11.0

User role: connect user role

Account used: christina_uw

Observation

- Maybe on other IE 11.0 web browsers or other operating systems the button is correct displayed but on my system appear in this way!

![add](https://cloud.githubusercontent.com/assets/5114907/18986662/80bf5cac-8706-11e6-9bf1-d14eb909699a.png)

**Comment by mahestro** [comment]
Valid.
