### ISSUE TITLE
Creating a Solution > QA > Regression Testing will add a `Dev Iteration` phase to the project

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3870]
### Expected behavior
Should not add any phase or better to add a QA Iteration

### Actual behavior
Creating a Solution > QA > Regression Testing will add a `Dev Iteration` phase to the project

### Steps to reproduce the problem

- Login as Manager
- Click `+ New Project` > Solution > QA > Regression Testing
- Create a `Regression Testing` project and open it {https://connect.topcoder-dev.com/projects/9073}
- Check the phases

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78926167-3e5eb800-7a62-11ea-9651-561446039c3a.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
@codejamtc it is again data issue in dev env. However, I have fixed the data as well in dev for this particular issue. Let me know if you still see the issue.

**Comment by codejamtc** [comment]
@vikasrohit Just checked I can still see the `Dev Iteration`
https://connect.topcoder-dev.com/projects/9089

**Comment by vikasrohit** [comment]
Try now.

**Comment by codejamtc** [comment]
@vikasrohit Working
