### ISSUE TITLE
'Price' option displayed above the project phases

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3871]
### Expected behavior
'Price' option should be removed. That option is no relevance to there

### Actual behavior
'Price' option displayed above the project phases

### Steps to reproduce the problem

- Login as Manager
- From the Project listing page turn ON "My Projects"
- Select a project from the list {https://connect.topcoder-dev.com/projects/9057}
- Check above the phases

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78927431-84b51680-7a64-11ea-93b4-09feb5684dbc.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
@codejamtc `Price` label was for the price that we used to show in each phase card if user has entered some value to the `Price` field, however, I think we stopped showing that price soon after its implementation, so I have hidden the label for now.

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 

![image](https://user-images.githubusercontent.com/42398485/80571827-dd703300-89c2-11ea-9fb4-213ed598ec3c.png)
