### ISSUE TITLE
'Ref Code' won't have a char limit and a long Ref code will overflow the Ref code tooltip

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3872]
### Expected behavior
Should have a character limit for the `Ref Code`/ or should fix the tooltip for long `Ref Code`

### Actual behavior
'Ref Code' won't have a char limit and a long `Ref Code` will overflow the Ref code tooltip

### Steps to reproduce the problem

- Login as Manager
- From the Project listing page turn ON "My Projects"
- Select a project from the list {https://connect.topcoder-dev.com/projects/9074/}
- Go to Scope > Expand the `Ref Code` and enter "codejam23432454543243243423655" > Save Changes
- Hover over the Ref code (Near the Project creation date)

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78928279-f0e44a00-7a65-11ea-9c11-b7b212842131.png)
![image](https://user-images.githubusercontent.com/42398485/78951535-18540a80-7a98-11ea-8f91-d8388e3056fa.png)

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `TCConManager`

**Comment by vikasrohit** [comment]
Related issue https://github.com/appirio-tech/connect-app/issues/3884. @codejamtc I am assuming that https://github.com/appirio-tech/connect-app/issues/3884 is happening only on Firefox, right?

**Comment by codejamtc** [comment]
@vikasrohit Yes

**Comment by maxceem** [comment]
This issue would be fixed as a part of https://github.com/appirio-tech/connect-app/issues/3872

**Comment by codejamtc** [comment]
IE11
![image](https://user-images.githubusercontent.com/42398485/79755285-8097bd00-82de-11ea-8814-7d178905ee9b.png)

FF
![image](https://user-images.githubusercontent.com/42398485/79755319-8d1c1580-82de-11ea-9c6e-7efc1ec1e54f.png)

**Comment by codejamtc** [comment]
Partially QA pass in `Production`: ❌ 

Tooltip Failed in Project listing page:

![image](https://user-images.githubusercontent.com/42398485/80574004-a3089500-89c6-11ea-854c-b6838f8f63ae.png)


FF:

![image](https://user-images.githubusercontent.com/42398485/80573385-799b3980-89c5-11ea-851d-b278e85b4ee8.png)

IE11:

![image](https://user-images.githubusercontent.com/42398485/80573476-a5b6ba80-89c5-11ea-9deb-51e6c5894a9a.png)

**Comment by maxceem** [comment]
> Tooltip Failed in Project listing page:

Good catch @codejamtc. Can we create a separate issue for this case, as in the current issue, we only included the tooltip of the Project Details page.

**Comment by drasticdpk** [comment]
@codejamtc please create new issue for above finding and close this issue.

**Comment by lakshmiathreya** [comment]
Verified in Safari, Firefox and Chrome on Prod for Manager and Admin accounts. Char limit and Tootip in Project Details page is working as expected. 
<img width="1260" alt="Screenshot 2020-04-29 at 11 06 19 PM" src="https://user-images.githubusercontent.com/51733042/80627811-15808000-8a6e-11ea-96ae-55ad85cb587a.png">
