### ISSUE TITLE
Duplicate "Wireframe" phases displayed on the "Add A New Phase"

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3875]
### Expected behavior
Should remove one from the list

### Actual behavior
Duplicate "Wireframe" phases displayed on the "Add A New Phase"

### Steps to reproduce the problem

- Login as Manager
- From the Project listing page turn ON "My Projects"
- Select a project from the list {https://connect.topcoder-dev.com/projects/8627}
- Select "Dashboard > Add New Phase
- Check the list

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78954181-e5fadb00-7aa0-11ea-93a7-7e1866ed5fbb.png)
![image](https://user-images.githubusercontent.com/42398485/78954188-ef844300-7aa0-11ea-9b94-09efc0275113.png)

#### Environment
- OS: HP Pavilion x360 15.6 inch; Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
This is a data issue in dev and it is expected to be there as we need many testing templates in there. Closing it.
