### ISSUE TITLE
"Warning: You are about to manually change the start/end date of this phase.." message is displayed even though the user is not editing the Start and End dates

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3878]
### Expected behavior
Should not display that message if the user is not editing the start and end dates

### Actual behavior
"Warning: You are about to manually change the start/end date of this phase.." message is displayed even though the user is not editing the Start and End dates

### Steps to reproduce the problem

- Login as Manager
- From the Project listing page turn ON "My Projects"
- Select a project from the list {https://connect.topcoder-dev.com/projects/9046/}
- Select the 'Dashboard' Click 'Edit' button of a phase
- Change the title name and check there is a message

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/78956167-0b8ae300-7aa7-11ea-9df5-fb7fc9288160.png)

#### Environment
- OS: HP Pavilion x360 15.6 inch; Window 10
- Browser (w/version): Chrome 80.0.3987.163
- User role (client, copilot or manager): Manager
- Account used:  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
Thanks @codejamtc for reporting and moving it to 2.10. However, I am marking it as won't fix because we are going to revamp the work management feature and the current UI of phases and its logic might not be there after that.
