### ISSUE TITLE
[Project Features] - TypeError: Cannot read property 'categoryId' of undefined

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#388]
Expected behavior
------------------------------------------------------------

- The error message must not be displayed in console.

Actual behavior
------------------------------------------------------------

- The error message "Cannot read property 'categoryId' of undefined" is displayed in console.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as copilot role.

- Open Developer Tools and select console.

- Edit an existing project "ex. Work Project".

- Select Specification.

- In Feature requirements section press Add / Edit Features.

- Select Invitation enable and set a text in field.

- Select Introductions and try to set Yes.

Environment
------------------------------------------------------------
Operating System(s): Windows 7 Professional / 64 bit
Browser(s):  Chrome 
User role: copilot role
Account used: cp-superstar

![22](https://cloud.githubusercontent.com/assets/5114907/18989385/60ac59ac-8714-11e6-8860-a3a2ab9b8a88.png)

**Comment by onetliviunicolae** [comment]
Observation

- The error message appear when select any else feature set some in textfield and select another proejct!

**Comment by mahestro** [comment]
Known from third-party integrated overlay.
