### ISSUE TITLE
Button Show Hide color not working properly on login screen

### ISSUE THREAD

**Issue by coderhacker** [appirio-tech/connect-app#3881]
### Expected behavior
The button color should be working based on the show and hide toggle .

### Actual behavior
The show and hide button color is not synced with password

### Steps to reproduce the problem
1. Launch https://connect.topcoder-dev.com
2. Enter the User name and Password
3. The show and hide button color is not synced with password

Please see the attached video to replicate the issue.
### Screenshot/screencast
Attach or link a resource.

[show-hide-color-sync-issue.zip](https://github.com/appirio-tech/connect-app/files/4459815/show-hide-color-sync-issue.zip)
--

#### Environment
- OS: Window 10
- Browser (w/version): All latest version
- User role (client, copilot or manager): All 
- Account used: 
topcoderconnect+Customer@gmail.com
topcoderconnect+AccountManager@gmail.com
topcoderconnect+Copilot@gmail.com
topcoderconnect+Manager@gmail.com
topcoderconnect+CopilotManager@gmail.com
topcoderconnect+bdr@gmail.com
topcoderconnect+Customer@gmail.com
topcoderconnect+Observer@gmail.com

**Comment by vikasrohit** [comment]
Moving to Backlog as we are going to get rid of Connect specific registration page in this or its next release.
