### ISSUE TITLE
[$40] Don't let choose "Observer" role

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3882]
Lets prevent users from selecting Observer role for new team members or changing from existing roles to Observer. And just show the Observer roles for the members who are already in that role.

![image](https://user-images.githubusercontent.com/146016/78970043-19754e00-7b11-11ea-8afa-af8ff10e2b0c.png)

![image](https://user-images.githubusercontent.com/146016/78970166-5b05f900-7b11-11ea-8b04-4aad4e4a0261.png)

**Comment by abdullatku** [comment]
@bug-bash-helper assign

**Comment by abdullatku** [comment]
@bug-bash-helper #3911 is ready for review

**Comment by codejamtc** [comment]
https://monosnap.com/file/Rd7I3hxAFAg9wCsSG0M3LmVyubcjCw

**Comment by vikasrohit** [comment]
@codejamtc @lakshmiathreya closing the issue for now as it seems some specific use case is pending for testing. Please feel free to reopen it if it fails for that use case.
