### ISSUE TITLE
Timeline tab is displayed for some phases (First to Finish) but no data on it

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3886]
### Expected behavior
If Timeline tab is not relevant for a specific phase, it should be removed from the phase

### Actual behavior
Timeline tab is displayed for some phases (First to Finish) but no data on it

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9077}
- Go to 'Dashboard' > Edit a phase (First to Finish/Design First to Finish)
- Check the Timeline

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/79057388-b70e7180-7c26-11ea-834b-80b460891e12.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 80.0.3987.163
**- User role (client, copilot or manager):** Manager
**- Account used:**  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
@codejamtc it is bad data in dev which appears to be there because of experiments we do in dev env.
