### ISSUE TITLE
'Paid to date (US$)' displays the spinner even though it is disabled

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3887]
### Expected behavior
Should hide the spinner. Check with the other browsers (Chrome and Edge)

### Actual behavior
'Paid to date (US$)' displays the spinner even though it is disabled

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9074}
- Go to 'Dashboard' > Edit a phase (QA Iteration)
- Check the 'Paid to date (US$)'

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/79057572-541dda00-7c28-11ea-941d-1825e653f520.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75
**- User role (client, copilot or manager):** Manager
**- Account used:**  `topcoderconnect+Manager@gmail.com`

**Comment by vikasrohit** [comment]
@codejamtc marking it as won't fix because the phase cards are going to be revamped soon and the concerned field is already deprecated and not in use.
