### ISSUE TITLE
[$15] 'Close' icon is not properly displayed (Rendered)

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3891]
### Expected behavior
Should display the close button

### Actual behavior
'Close' icon is not properly displayed (Rendered)

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list { https://connect.topcoder-dev.com/projects/9074 }
- Go to 'Dashboard' > Expand a phase (First to Finish)
- Go to 'Specification' tab
- Expand the 'Description' or 'What type of question...' and check the button

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/79058519-c4325d00-7c34-11ea-8268-0ea5618e514a.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by maxceem** [comment]
Sum up:
- I can reproduce the same issue on macOS in Chrome and Firefox, probably other browsers too. We have to fix it in all modern browsers: Firstfox, Chrome, Safari, Edge, Opera and Internet Explorer 11.
- the interesting thing that I cannot reproduce it in another project like https://connect.topcoder-dev.com/projects/9093/scope, but can reproduce in the project mentioned in this issue https://connect.topcoder-dev.com/projects/9074.
- `pshah_manger` used could be used for testing

**Comment by maxceem** [comment]
This issue is open for pickup.

**Comment by Vips19** [comment]
@bug-bash-helper assign

**Comment by Vips19** [comment]
@bug-bash-helper #3922  is ready for review

**Comment by maxceem** [comment]
@Vips19 the review is ready, please, have a look https://github.com/appirio-tech/connect-app/pull/3922#pullrequestreview-395918387.

**Comment by Vips19** [comment]
@bug-bash-helper #3922 is ready for review

**Comment by codejamtc** [comment]
https://monosnap.com/file/fOonx3sqx0fwaYBYzoOuXTXoP0T6zG

**Comment by drasticdpk** [comment]
verified on prod with Chrome/Firefox browser.
