### ISSUE TITLE
Intermittent error of API timeout

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3899]
### Expected behavior
App should be loading perfectly without timeout error. 

### Actual behavior
Reported by Copilot - timeout issue.

### Steps to reproduce the problem
- TBD.
- TBD.
- TBD.

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by maxceem** [comment]
This issue was previously logged here https://github.com/appirio-tech/connect-app/issues/3703 but we didn't find any solution.

Now it's solved by https://github.com/appirio-tech/connect-app/pull/3897

**Comment by drasticdpk** [comment]
with reference to above discussion , I am closing this issue. 
I have verified on 3G Fast/Slow network too and it is working as expected.
![image](https://user-images.githubusercontent.com/25297859/79315061-44e9a580-7f22-11ea-9357-f42f95e4c48e.png)
