### ISSUE TITLE
[Project Features] - Search is not enable when is set yes

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#390]
Expected behavior
------------------------------------------------------------

- Enable the right image section when set feature as yes.

Actual behavior
------------------------------------------------------------

- The right section is not enable when is set yes.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as copilot role.

- Edit any existing project.

- Select Specification and press Add / Edit Features.

- Select Search feature.

- Press the on / off button to enable.

Environment
------------------------------------------------------------
Operating System(s): Windows 7 Professional / 64 bit
Browser(s):  IE 11.0
User role: connect user role
Account used: christina_uw

![111](https://cloud.githubusercontent.com/assets/5114907/18989576/5c69be7e-8715-11e6-85f4-111a2191985e.png)

**Comment by mahestro** [comment]
It's a fixed image, it's expected to behave like that. Not a bug.
