### ISSUE TITLE
UI breaking in firefox after project creation

### ISSUE THREAD

**Issue by coderhacker** [appirio-tech/connect-app#3901]
### Expected behavior
reference UI should be the same as Chrome. 
### Actual behavior
UI breaking in firefox after project creation

### Steps to reproduce the problem
Step 1- Go to url https://connect.topcoder-dev.com/projects/9095/.
Step 2- login with user : topcoderconnect+CopilotManager/appirio123
Step 3- Please refer attached screenshot.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/62358241/79330876-e2030900-7f37-11ea-89fc-85d5e539b657.png)
![image](https://user-images.githubusercontent.com/62358241/79330889-e7f8ea00-7f37-11ea-87ff-3e4843dae01f.png)
![image](https://user-images.githubusercontent.com/62358241/79330942-02cb5e80-7f38-11ea-98e7-19e1c7f450c3.png)

--

#### Environment
- OS:  Windows 10
- Browser (w/version): Firefox (latest version)
- User role (client, copilot or manager): All
- Account used: topcoderconnect+CopilotManager

**Comment by maxceem** [comment]
@coderhacker it looks like a duplicate of https://github.com/appirio-tech/connect-app/issues/3884

**Comment by coderhacker** [comment]
Closing as per above comments
