### ISSUE TITLE
Improve performance of create project form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3903]
The performance of the form for creating new projects is quite poor.

We have a component to enter skills [SkillsQuestion](https://github.com/appirio-tech/connect-app/blob/bdbb8910cab2ad2638661d61f780f729f6102578/src/projects/detail/components/SkillsQuestion/SkillsQuestion.jsx). This component is shown as a part of the project creation form, see [URL](https://connect.topcoder-dev.com/new-project/talent-as-a-service) and [screenshot](https://monosnap.com/file/cMOgimCzWfKfhRHZQ1GuEaHQ03Syaq). Recently we implemented a new component [TalentPickerQuestion](https://github.com/appirio-tech/connect-app/blob/5c27f2c01b1a3f0ed30f58f4289bc6a71947db14/src/projects/detail/components/TalentPickerQuestion/TalentPickerQuestion.jsx) which shows the SkillsQuestion component multiple times, see [URL](https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists) and [screenshot](https://monosnap.com/file/tj5YQHdN5JxNYZ8Og7Iuj3yVStp2gE). Though after showing it multiple times it become clear that form now works very slow, see demo [video](https://monosnap.com/file/Zgh7hhbuDSA0HroeekugHurSRAQj2a).

Here are performance testing results:
- No Skill component - 42ms ([video](https://monosnap.com/file/zbu4QskDMd1K6rVHKqlJLkZrpKkXhW))
- 1 Skill component - 352ms ([video](https://monosnap.com/file/8Iu7yxbGS0LCV1Pq1LusUKGkTCS2e5))
- 5 Skill components - 709ms ([video](https://monosnap.com/file/slqDvbNIM90KUEpgB0bBkx7nD6AInY))
- 10 Skill components - 1.38s ([video](https://monosnap.com/file/Nwgtwi6exR2GGZAPNJT3OWQHMCwYVI))
- 20 Skill components - 2.54s ([video](https://monosnap.com/file/GHhYxf7vP85l5NLwAfm3JDIpK2gWxq))

We have to fix **SkillsQuestion** and/or **TalentPickerQuestion**, so the the reaction of the form taken no longer than 100ms.

**Comment by maxceem** [comment]
It was fixed via F2F https://www.topcoder.com/challenges/30122011/?type=develop with afterward task for refactoring.

The speed of one form action is around 50ms now.

Here is the pull request https://github.com/appirio-tech/connect-app/pull/3894.

A few more code improvements could be done as per comment https://github.com/appirio-tech/connect-app/pull/3895#pullrequestreview-393844954

**Comment by vikasrohit** [comment]
@maxceem closing it. Let me know if anything is pending for this.
