### ISSUE TITLE
Specification and Message pages opens focused below section of the page

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#391]
### Expected behavior
-----------------------------------------------------------------
Specification and Message pages must open focused at top when user navigates from Dashboard

### Actual behavior
-----------------------------------------------------------------
Specification and Message pages opens focused below section of the page

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/438)
- Now in the Dashboard
- Scroll down
- Click Specification OR Message Tabs

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-30_16-35-16](https://cloud.githubusercontent.com/assets/4592712/18989851/f17f1b74-872b-11e6-887b-030f6c726d1c.png)
![2016-09-30_16-35-26](https://cloud.githubusercontent.com/assets/4592712/18989852/f1b24242-872b-11e6-9084-c1251ddabfc9.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Known issue, part of the same bug #148
