### ISSUE TITLE
Some Formatting tools won't show in Dashboard and Message pages sometimes in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#392]
### Expected behavior
-----------------------------------------------------------------
Formatting tools must show in Dashboard and Message pages

### Actual behavior
-----------------------------------------------------------------
Some Formatting tools won't show in Dashboard and Message pages sometimes in IE11

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/438)
- Now in the Dashboard OR Message pages
- Check the Comment section formatting tool bar

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-30_16-37-28](https://cloud.githubusercontent.com/assets/4592712/18989948/82db7d6a-872c-11e6-8c70-495f90db7162.png)
![2016-09-30_16-37-15](https://cloud.githubusercontent.com/assets/4592712/18989949/83429e0a-872c-11e6-8015-edbb304159ba.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
True, valid.
