### ISSUE TITLE
Support invite unregistered users by email case-insensetive

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3929]
When we invite unregistered user by email like `test@topcoder.com`, and after user is registering with email using uppercase, like `TEST@TOPCODER.COM`.

If user tries to open the project he was invited to, he would get error 404:

![image](https://user-images.githubusercontent.com/146016/79568105-f244f080-80bd-11ea-8f19-33d0a89e8c0a.png)

Expected behavior, is use can see the invitation dialog:

![image](https://user-images.githubusercontent.com/146016/79568145-02f56680-80be-11ea-8a04-9e40b9d995a0.png)
 
Both buttons to `Cancel` and `Join project` should work good.

**Comment by maxceem** [comment]
This issue is fixed by:
- commit in Project Service https://github.com/topcoder-platform/tc-project-service/commit/f0fe7bf61a386e84ba106097cbc27ba0872ab7bb
- and in Connect App commit 6a6bf0107da9b6adbf49b8bce9aad9d894ac4c5e

**Comment by maxceem** [comment]
Test guidelines:
- to test the fix properly we have to test that user whos just registered with uppercase email can click `Cancel` and `Join project` buttons successfully. So for testing 2 new users would have to be registered with uppercase email.

**Comment by codejamtc** [comment]
@maxceem https://monosnap.com/file/836sIsFAIPgFh7OZXAaaYQk5bNQpL3

**Comment by drasticdpk** [comment]
Prod Verified with project Smoke test 2.7.1.
