### ISSUE TITLE
Project Features: not able to turn on Email And All other feature in IE 11

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#393]
### Expected behavior
Should be able to turn on Email & All other features 

### Actual behavior
not able to Enable features 

### Steps to reproduce the problem
1. Open Application 
2. LOgin as Manager 
3. Create new project
4. Go to Specifications
5. Go to Project features Section
6. Email Login features 
7. Try to Enable Features 

### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/18990438/7845c1a0-872f-11e6-9903-6983c870fc3e.png)

--

#### Environment
- OS: Windows 7
- Browser (w/version): IE 11, 1366*768 
- User role (client, copilot or manager):Manager 
- Account used:

**Comment by mahestro** [comment]
Can't reproduce - http://take.ms/oZ3kz
