### ISSUE TITLE
Customer cannot remove another customer from the team

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3932]
When I use a customer use who is not `isPrimary` I still can see buttons to remove other Customer Team members:

![image](https://user-images.githubusercontent.com/146016/79628774-b7d66480-814c-11ea-9b78-674a3075f96f.png)`

But if I try to remove any of them, I would get an error from Project Service:

![image](https://user-images.githubusercontent.com/146016/79628789-db99aa80-814c-11ea-9132-7ae82642905e.png)

The reason for this is that we use different permissions client-side and server-side:
- client-side, we show `remove` button for all customer users who is a member of the project
- server-side, we only allow removing other customers for the customer user who has `isPrimary` flag set to `true` (former `owner` role).

We have to synchronize permission between server and client. Which way should we follow @vikasrohit?

### Steps to reproduce

- User one `customer` user to create a new project
- Now invite the second `customer` user
- Use the second `customer` user to accept invite, and now try to remove the first customer user by the second one - it would fail. While removing the second customer user by the first one would succeed.

**Comment by vikasrohit** [comment]
Just get rid of `isPrimary` check we have from any where. We don't have this notion any more. All customers are equal as of now.

**Comment by maxceem** [comment]
> Just get rid of isPrimary check we have from any where. We don't have this notion any more. All customers are equal as of now.

Got it. Then I think we have to remove it everywhere, so I've logged a separate issue for a general task https://github.com/appirio-tech/connect-app/issues/3939

**Comment by maxceem** [comment]
This is fixed via https://github.com/topcoder-platform/tc-project-service/pull/555 and can be tested.

**Comment by codejamtc** [comment]
Fixed. 🆗 

https://monosnap.com/file/k0pt0Wbp6UTDqAdnHx8bcykQSmOFZN
