### ISSUE TITLE
[Messages] "Close" button won't work when user click on it

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#394]
### Expected behavior
-----------------------------------------------------------------
Must close the 'NEW STATUS POST' OR Must remove 'Close' button if it is not required

### Actual behavior
-----------------------------------------------------------------
"Close" button won't work when user click on it

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/438)
- Now in the Message pages
- Click (+)
- Now click (x) button

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-30_17-00-41](https://cloud.githubusercontent.com/assets/4592712/18990437/74dca0b0-872f-11e6-831b-bb070a809ebb.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
Should already be fixed in local.

**Comment by vikasrohit** [comment]
Fixed with #142
