### ISSUE TITLE
A long list of invitees that are not relevant to the current operation, adds to the list

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3944]
### Expected behavior
Should not add unwanted invitees to the list

### Actual behavior
A long list of invitees that are not relevant to the current operation, adds to the list

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9149}
- Go to Client Team > Manage Invitations (There should be no any current invitations)
- Enter topcoderconnect+Customer@gmail.  > Send Invite and check the message

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/79810735-48719800-8339-11ea-97d4-e55331c6d4fc.png)

https://monosnap.com/file/DqrMSMcrM38VlWpdt0OVbsDBqoEeAO

[Log.txt](https://github.com/appirio-tech/connect-app/files/4506910/Log.txt)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by maxceem** [comment]
I think it has the same root as https://github.com/appirio-tech/connect-app/issues/3834.

**Comment by maxceem** [comment]
@codejamtc this is fixed now. If we try to invite such a user we would get an error:

![image](https://user-images.githubusercontent.com/146016/79956954-88e02b80-8489-11ea-9f25-d3de7edc195d.png)

- note, as this is incorrect email, we treat it as a user handle

**Comment by codejamtc** [comment]
Fixed: 🆗 https://monosnap.com/file/Z2bPUwd4JlNZm5Tux2GucTDCzITPto

**Comment by codejamtc** [comment]
QA pass in `Production`: 🆗 
https://monosnap.com/file/fTHs80dsgBqGAljRGpvy89W9Sb7JS5
