### ISSUE TITLE
When user select the "Messages" from the list; posts related to that Message won't see

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#395]
### Expected behavior
-----------------------------------------------------------------
When user select the bottom messages from "Messages" section; Related posts are displayed on top
So "Messages" list must be a scroll-able section to view the posts

### Actual behavior
-----------------------------------------------------------------
When user select the "Messages" from the list; posts related to that Message won't see

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/438)
- Now in the Message pages
- Click (+) and Add 10-15 Messages
- Now scroll the Last message on the list
- Select it
- Check the posts related to them
- User must scroll up to see them (This is not easy)

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-30_17-14-19](https://cloud.githubusercontent.com/assets/4592712/18990756/a9dfbe80-8731-11e6-9b8f-c6efee1371e5.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
@parthshah this one is not working for me.

**Comment by fnisen** [comment]
@vic-appirio looks like we'll need layout changes to make this happen, so assigning to you. Let's discuss.

**Comment by vic-appirio** [comment]
We need to support independent scrolling of the left and right sides of the screen. Navigation should be accessible independently of the message feeds.

**Comment by fnisen** [comment]
@vic-appirio yes, agree. Can you please illustrate how this would work, and we'll get the work rolling?

**Comment by vic-appirio** [comment]
Follow the Facebook's messages page model; pretty standard: https://youtu.be/aQeKPyBuh4A

**Comment by fnisen** [comment]
Thanks @vic-appirio. @vikasrohit over to you.

**Comment by vikasrohit** [comment]
@vic-appirio @fnisen I have done the changes for achieving the desired behaviour. However, I had to remove the sticky behaviour to not have overflow issue when page is scrolled to the bottom. And, I guess, in after scrolls bar we don't need sticky behaviour anyway. Please let me know if you think otherwise for sticky behaviour.

**Comment by fnisen** [comment]
@vikasrohit it's looking good. Just one change please: can you exclude the top "Discussions" panel from the rest of the scroll, so that the user doesn't have to scroll all the way back to create a new thread? 

@vic-appirio please chime in if you have anything else.

**Comment by vikasrohit** [comment]
Thanks for noticing that @fnisen Done, Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit sorry, one more thing on this. I'm on scrolling on the left-hand panel, the scroll bar drops through, it doesn't bump, as it should when I've reached the end of the component. Here is what I mean: http://screencast.com/t/YtKshmaOD

**Comment by vikasrohit** [comment]
Thanks @fnisen for noticing. Fixed and deployed in dev.

**Comment by fnisen** [comment]
Looks great. Thanks @vikasrohit!
