### ISSUE TITLE
Talent Picker Component - Issue: value is not updated in read-optimized mode

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3951]
### Expected behavior
The value should be updated in read-optimized mode when we change values inside the component.

### Actual behavior
The value is not updated.

### Steps to reproduce the problem
- Open this project creation form https://connect.topcoder-dev.com//new-project/talent-as-a-service-specialists
- Fill the fields of Talent Picker Component and click **Next**

   ![image](https://user-images.githubusercontent.com/146016/79949267-f1291000-847d-11ea-9df4-cf583020a6ef.png)

- After clicking Next, see how the values are displayed in "read-optimized" mode:

   ![image](https://user-images.githubusercontent.com/146016/79949323-11f16580-847e-11ea-8cb8-9e09bf3dad31.png)

- Now open the question again by clicking the tick on the right and change the quantity of some people: expected behavior, the quantity is also updated in read optimized mode, when we change it in the Talent Picker Component, but it's not:

   ![image](https://user-images.githubusercontent.com/146016/79949592-73b1cf80-847e-11ea-9b8d-04d878b3396e.png)

### Screenshot/screencast

Demo video https://monosnap.com/file/CF0pwjMYVmHv90U6jrCR3OMcQgQ7sT

**Comment by codejamtc** [comment]
Fixed: 🆗 https://monosnap.com/file/iAiGdSks8l3dEZmkY95Zr81lgM0oso
Used: `Manager`  | URL: https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists

**Comment by codejamtc** [comment]
@maxceem Customer use can't access the direct link 
https://connect.topcoder.com/new-project/talent-as-a-service-specialists"

**Comment by codejamtc** [comment]
Fixed: 🆗 https://monosnap.com/file/4acfxuquiseytkDVl2v4CMdoJomA17
Used: `Customer`  | URL: https://connect.topcoder.com/new-project/talent-as-a-service-v1.2
