### ISSUE TITLE
[Dashboard] - Request failed with status code 500(…) error message

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#396]
Expected behavior
------------------------------------------------------------

- Do not display this error message.

Actual behavior
------------------------------------------------------------

- The 500 error message is displayed in console.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager.

- Open Developer Tool in Chrome.

- Edit any existing project and check the server calls.

Environment
------------------------------------------------------------
Operating System(s): Windows 7 Professional / 64 bit
Browser(s):  IE 11.0
User role: manager user role
Account used: pat_monahan

see attach!

![erro1](https://cloud.githubusercontent.com/assets/5114907/18994287/c32b56f8-872f-11e6-8c2b-70b8e360c9e6.png)

**Comment by mahestro** [comment]
Known.
