### ISSUE TITLE
Account Manager can't change the project status after joining the project

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3960]
### Expected behavior
Should be able to change the project status since he is holding a manager role (Only Managers and Copilots can change the project statuses)

### Actual behavior
Account Manager can't change the project status after joining the project 

@vikasrohit @acshields please confirm. Thanks

### Steps to reproduce the problem

- Login as Account Manager
- Select a project from the list {https://connect.topcoder-dev.com/projects/9173}
- Go to Topcoder Team > Join Project > Join Project button
- Check the Administration section and try to change the project status

### Screenshot/screencast

https://monosnap.com/file/8eOPc2rbeoFD9P3WkB52YxVmciA7Gz

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):**  Account Manager
**- Account used:**  `TCConAccountMgr`

**Comment by maxceem** [comment]
@codejamtc `Connect Account Manager` user joins a project as `account_manager` not `manager`

![image](https://user-images.githubusercontent.com/146016/81931762-45de2780-95f3-11ea-8137-8578ec7aa1ec.png)

This is as per our current roles matrix

![image](https://user-images.githubusercontent.com/146016/81931845-64dcb980-95f3-11ea-9d08-4c7eb68f39a2.png)

Currently, such users cannot change project status. I'm closing this issue, but feel free to reopen it if you think some requirement is missed there.
