### ISSUE TITLE
Show detailed error during switching member role

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3963]
Follow up from https://github.com/appirio-tech/connect-app/issues/3962#issuecomment-619923888

Now if user tries to change to the role they are not allowed, the error message would be shown, see a demo video https://monosnap.com/file/ir4B3T1vl6Cov5rkVkYOAptAY7w23y

Now we have to fix the error message to directly indicate what is the problem as now it's to general:

![image](https://user-images.githubusercontent.com/146016/80367520-ed3d2980-8893-11ea-82ab-06da2f79ef0f.png)

**Comment by maxceem** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/146016/80368883-1494f600-8896-11ea-9053-150c44948228.png)

Demo video: https://monosnap.com/file/RhaUw8TF7L0aqraPOX1DW8wo9QnMgl

**Comment by codejamtc** [comment]
@maxceem 

Checked: 🆗 `Manager` tried to change the user role to `Account Executive`, `Program Manager`, `Solution Architect` and `Project Manager` and he/she will get an error
https://monosnap.com/file/H8RHKNH6KEnfuwSdqJL66SLNbjzro6

Checked: 🆗 `Manager` tried to join into the account as `Account Executive`, `Program Manager`, `Solution Architect` and `Project Manager` and he/she will get an error.
https://monosnap.com/file/kKhulfua0lh2SwKfWmlTeTCPwhkY7k

Checked: 🆗 A User tries to join to a project as `Manager` will get an error. And the same user joined to a project as `Program Manager` and tried to change the role to `Account Executive`, `Solution Architect`. `Manager` or `Project Manager` role will get an error.

He can either switch to `Connect Account Manager` role and back to `Program Manager` without an error.

https://monosnap.com/file/jYrkF5Wzf1D4eZT408iAhSVhOKmGgJ

**Comment by vikasrohit** [comment]
>According to the matrix Manager can't join a project as Connect Account Manager and can't switch the role from Manager >> Connect Account Manager

@codejamtc Did you mean `Connect Account Manager` can't join as `manager` and `Connect Account Manager` can't join as `manager`? If that is the case, it is correct and expected behaviour.

**Comment by codejamtc** [comment]
@vikasrohit Yes, I think this ticket is `Pass`

**Comment by lakshmiathreya** [comment]
Prod verification for detailed messages done for Switching Roles - for Copilot, Copilot Mgr, Connect Account Manager, Connect Manager and Admin.
