### ISSUE TITLE
Talent Picker Component - default value as "0"

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3964]
Follow up from https://github.com/appirio-tech/connect-app/issues/3950#issuecomment-619934701

When we unfocus "people" or "duration" field and there is no value, then set "0" as a value automatically.

**Comment by codejamtc** [comment]
Fixed in `Dev`: 🆗 
URL: https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists

https://monosnap.com/file/SuFWWsZXm0y21tpKIdrjFScIVERuie

**Comment by drasticdpk** [comment]
Verified on prod env.
![image](https://user-images.githubusercontent.com/25297859/81273349-790e3d00-906e-11ea-9bc2-587ac669a6e6.png)
