### ISSUE TITLE
Talent Picker Component - additional validation

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3965]
Add additional validation. If inside any row we set at least one value "people", "duration" or "skills" but we didn't fill all the fields, then we have to show validation error: "Please, fill all the fields for the positions you would like to add.". And the same time, show missing fields in red like do we on user profile https://connect.topcoder-dev.com/settings/profile
 
![image](https://user-images.githubusercontent.com/146016/80690157-11d51380-8ad7-11ea-8b5b-19f6b88774a8.png)

**Comment by coderhacker** [comment]
Fix this issue as well:  if people and duration are empty just filled only skills, the next button is active.
![image](https://user-images.githubusercontent.com/62358241/80455619-baee0380-8949-11ea-9148-fb666369e81c.png)

Updated comments here #3950

**Comment by vikasrohit** [comment]
> if people and duration are empty just filled only skills, the next button is active.

The issue is about taking care of this situation as well.

**Comment by coderhacker** [comment]
@maxceem seems this is not fixed please see below screen 

![image](https://user-images.githubusercontent.com/62358241/80711046-5b405580-8b0d-11ea-9737-7f463c3e82b7.png)

![image](https://user-images.githubusercontent.com/62358241/80711067-63989080-8b0d-11ea-82ea-7897620980af.png)

@drasticdpk

**Comment by maxceem** [comment]
Thanks @coderhacker, I've missed this requirement:::

> I am able to enter an unlimited value of people and duration. There should be some limitation validation.

@vikasrohit should we put some maximum value?

**Comment by vikasrohit** [comment]
Though we don't have explicit requirement of max value on this field, but lets put a max value for now to be 10000 because I don't what should be the realistic max value for it.

**Comment by lakshmiathreya** [comment]
@vikasrohit is this in 2.9.1 list? I was able to enter 10001 as number and save the project ... perhaps we could move this to 2.10?

**Comment by maxceem** [comment]
@lakshmiathreya @coderhacker this is fixed now on DEV and ready for testing.

**Comment by lakshmiathreya** [comment]
Max value of 10000 working as expected in Prod for People and Duration fields.
