### ISSUE TITLE
Permissions regression testing 2

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3966]
**Make regression testing after internal work is done but functionality should work as before**

We did some internal refactoring at the server side (Project Service, PR https://github.com/topcoder-platform/tc-project-service/pull/555).

The code to handle permissions has been updated in some places, though functionality shouldn't be changed, so now we have to make sure the functionality works as before.

The most important part to test is customer invitations/members workflows:
1. as a customer invite another **non-existent** customer via email
2. as a customer invite another customer via handle
3. as a topcoder member invite **existent** customer via email
4. as a topcoder member invite customer via handle
5. as a customer remove another customer invite
6. as a topcoder member remove customer invite
7. as a **existent** customer decline invite via email (NOTE: here and below it's enough to decline or accept invite in one place - Project Dashboard page, don't need to test decline/accept inside email or on Project Listing page)
8. as a **non-existent** customer accept invite via email
9. as a customer decline invite via handle
10. as a customer accept customer via handle
11. as a customer member "leave" the project
12. as a customer member "remove" another customer member from the project
13. as a topcoder member "remove" another customer member from the project

**Comment by maxceem** [comment]
During the refactoring we found a couple of issues, and they have been fixed via separate issues:
- [Don't allow users to change roles which they are now allowed](https://github.com/appirio-tech/connect-app/issues/3962)
- [Show detailed error during switching member role](https://github.com/appirio-tech/connect-app/issues/3963)

**Comment by vikasrohit** [comment]
Thanks for the detailed plan for testing @maxceem

**Comment by codejamtc** [comment]
@maxceem 

1. As a customer invite another non-existent customer via email: 🆗 
2. As a customer invites another customer via handle: 🆗 
3. As a Topcoder member invite existent customer via email: 🆗 
4. As a Topcoder member invite customer via handle: 🆗 
5. As a customer remove another customer invite: 🆗 
6. As a Topcoder member remove customer invite: 🆗 

https://monosnap.com/file/Z4N0Jw0TDTjRYa0AiC2qNLj2jiHKjy

7. As an existent customer decline invites via email (NOTE: here and below it's enough to decline or accept the invite in one place - Project Dashboard page, don't need to test decline/accept inside an email or on Project Listing page): 🆗 
8. As a non-existent customer accept invite via email: 🆗 
9. As a customer decline invites via handle: 🆗 
10. As a customer accept customer via handle: 🆗 
11. As a customer member "leave" the project: 🆗 
12. As a customer member "remove" another customer member from the project: 🆗 
13. As a Topcoder member "remove" another customer member from the project: 🆗 

https://monosnap.com/file/9hvm27PiBQygdPIO8AGuY6jZRZD8q1

**Comment by lakshmiathreya** [comment]
Verified Invite and Remove scenarios in Prod with Admin, Connect Account Manager, Copilot Manager and Connect Manager.
