### ISSUE TITLE
Past talent category skill list is shown even after the user changed the talent 

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3968]
### Expected behavior
Should display the skill list according to the new talent selected

### Actual behavior
Past talent category skill list is shown even after the user changed the talent 

### Steps to reproduce the problem

- Login as Manager
- Go to https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists
- From the first talent dropdown select 'Design' > People=1, Months=1, Skills=Graph Theory
- Click 'Next' and go to 'What skills are important for your team to have?*'
- Expand the dropdown and it will show skills related to Design
- Now Click Back and go to 'Talent' again and change the talent from 'Design'  >  'Data Scientist' (Remove Design data and replace it with Data Science data)
- Click Next and go to 'What skills are important for your team to have?*'
- Expand the dropdown
- Still shows the Design skills

### Screenshot/screencast

https://monosnap.com/file/tiWrios7Qp836cBqD1A4tsksLw5i1j

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** FF 75 | Chrome 80.0.3987.163
**- User role (client, copilot or manager):**  Manager
**- Account used:**  `TCConManager`

**Comment by maxceem** [comment]
@codejamtc thanks for checking on this. Though this project template https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists is solely for various testing purposes, it's not a real project template. And the questions inside don't have a special configuration to respect each other.

As far as I know in real project template the old question `What skills are important for your team to have?*` would not be used together with a new Talent Picker Component. Talent Picker Component would replace that question. We keep them both, just to make sure that new component doesn't break old component if we still use it somewhere.

I'm closing this issue for now, but feel free to reopen it if I missed something.
