### ISSUE TITLE
Invitation Cancel  if user click other than Join Project Button 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3972]
### Expected behavior
Invitation should be cancel only if user click on cancel button.

### Actual behavior
Invitation is cancelling when user makes click other than Join Project button.

### Steps to reproduce the problem
- Invite  the user to Join the Project
- Login from the user ( which was invited )
- Click the invitation confirmation window (other than join project button.)

### Screenshot/screencast
https://monosnap.com/file/vLohqvg2P6gRdyozPToXsi1disn0MA
![image](https://user-images.githubusercontent.com/25297859/80579401-b0a33680-8a29-11ea-99e5-d03e1f2f8ed4.png)

#### Environment
- OS: macOS
- Browser (w/version): Google Chrome/ FireFox
- User role (client, copilot or manager): Client

**Comment by drasticdpk** [comment]
cc @maxceem

**Comment by maxceem** [comment]
@vikasrohit should we fix it as a hotfix in `2.9` or include in the next `2.10` release?

**Comment by vikasrohit** [comment]
I think saw this issue before this release as well, so I guess it should be okay to have it as regular release. However, lets create hotfix branch for 2.9.1 and do these changes there and if needed we would merge it master for hotfix otherwise we would just merge it to dev.

**Comment by maxceem** [comment]
@vikasrohit what should happen if we click outside the dialog?
1. Nothing
2. Got back to the project listing page?

**Comment by vikasrohit** [comment]
Nothing. Because I would like user to explicitly click on Cancel to decline the invite.

**Comment by codejamtc** [comment]
Fixed in `Dev`: 🆗 

https://monosnap.com/file/tZf6g0P2CoCCcclyismssHN9LRLo7L

**Comment by drasticdpk** [comment]
Still having same issue : Fail on prod env.
https://monosnap.com/file/7UrKDgKRKYJ8yqL4vRpQJ90Wr8Hs2F

**Comment by maxceem** [comment]
@drasticdpk issues in milestone `2.9.1` https://github.com/appirio-tech/connect-app/milestone/92 are not yet deployed to PROD.

**Comment by drasticdpk** [comment]
Verified on prod 
![image](https://user-images.githubusercontent.com/25297859/81263436-5e809780-905f-11ea-8a2f-41eeedde8c9d.png)
