### ISSUE TITLE
Don't show attachments which are not allowed for the user

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3983]
Currently, if we limit file permissions, users who are not allowed to download files can still see them listed:

![image](https://user-images.githubusercontent.com/146016/81147845-d4afcc00-8f83-11ea-8020-5d2de573cc2e.png)

### Steps to reproduce

1. Join project with 3 users.
1. Using **user 1** create a file on the **Assets Library** page.
2. Assign permissions to see the file to **user 2** only.
3. Load **Assets Library** page using **user 3** who didn't created the file and who is not listed in allowed users.
4. **user 3** would be able to **see** the file, though they wouldn't be able to download it.

### Question

Should we also not show files which are not shared with the current user? So if user cannot download file they also shouldn't see it.

cc @vikasrohit

**Comment by vikasrohit** [comment]
Makes sense. Lets hide the attachments which are not shared with the logged in user.

**Comment by maxceem** [comment]
This is done by https://github.com/topcoder-platform/tc-project-service/pull/571 and https://github.com/topcoder-platform/tc-project-service/commit/61aa6a2635c7a1c4846097404f8ba7d73d515882 in Project Service and is ready for testing on DEV.

QA guidelines:
1. user who created attachment can always see it
2. by default all other users also can see attachments
3. if we explicitly set a list of users who can see attachment, then only these users can see it, exception users with `Connect Admin` and `administrator` roles, they can see all the attachments.

Example project https://connect.topcoder-dev.com/projects/16525/assets

**Comment by codejamtc** [comment]
Fixed in `Dev`: 🆗 
https://monosnap.com/file/zbbCUr36H4hMsFhbxu6Kk8PqrDJJ8a
