### ISSUE TITLE
Show email of members to admin users

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3988]
Some time ago we temporary disabled showing email of members to anyone.

After making some backend fixes, we re-enabled showing email for members, but only to users with `administrator` role can see it.

### `administrator` users

- project listing page:

   ![image](https://user-images.githubusercontent.com/146016/81263514-76005600-9048-11ea-8847-d13402b36f1f.png)

- project details pages:

   ![image](https://user-images.githubusercontent.com/146016/81263711-d68f9300-9048-11ea-9da5-61a1d700b91b.png)

### all other users

- project listing page:

   ![image](https://user-images.githubusercontent.com/146016/81263741-ea3af980-9048-11ea-99c2-a0899e9eb4fe.png)

- project details pages:

    ![image](https://user-images.githubusercontent.com/146016/81263676-c7104a00-9048-11ea-806d-ab5ef77b0f2e.png)

**Comment by drasticdpk** [comment]
Verified with Other Role :
**Challenge Listing page** 
![image](https://user-images.githubusercontent.com/25297859/81265490-e7e59900-9062-11ea-8a52-19a2720fbe91.png)

**project details pages:**

![image](https://user-images.githubusercontent.com/25297859/81265662-34c96f80-9063-11ea-92ac-a80d1f520525.png)

**Comment by lakshmiathreya** [comment]
Admin user view:
<img width="916" alt="Screenshot 2020-05-07 at 12 53 01 PM" src="https://user-images.githubusercontent.com/51733042/81266074-c1732e00-9061-11ea-9383-45d4ab2fa832.png">

**Comment by lakshmiathreya** [comment]
Email not visible to Connect Admin:
<img width="1299" alt="Screenshot 2020-05-07 at 1 00 16 PM" src="https://user-images.githubusercontent.com/51733042/81266688-d13f4200-9062-11ea-86f6-c5c1aa55298d.png">
