### ISSUE TITLE
UI issue on the project card; if there are so many users and the invitation button is active

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3992]
### Expected behavior
Should limit the number of avatars and increase +x record

### Actual behavior
UI issue on the project card; if there are so many users and the invitation button is active

### Steps to reproduce the problem

- Login as Account Executive
- Check the Project Card

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/81630448-3e3c3a00-93cb-11ea-9896-0e8a1e0e431c.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.129
**- User role (client, copilot or manager):**  Account Exe
**- Account used:**  `TCConAccountExe`

**Comment by maxceem** [comment]
Limited to showing a maximum of 4 avatars, so there is a space for invitation button:

![image](https://user-images.githubusercontent.com/146016/82050559-03831c00-96c1-11ea-900e-1946bd6adacb.png)

Done by https://github.com/appirio-tech/connect-app/commit/31e4a3bda7d4e0e6ddad960a25d634544e7b30bb

Ready for review.

**Comment by codejamtc** [comment]
Fixed: 🆗 

![image](https://user-images.githubusercontent.com/42398485/82053529-1e36a000-9683-11ea-82f5-a4b113a7193a.png)
