### ISSUE TITLE
Bring project type info on Project page

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4004]
We need to have the project type icon/Text on the project page so that it would be helpful in chameleon integration for our app. We used to have Icon earlier and its been gone with last updates/requirements. 

@maxceem @vikasrohit @acshields

**Comment by RishiRajSahu** [comment]
I think we would need to have text mentioniong the type of project, as icon is just and svg which doesn't contain any info about project-type or does it ? @vikasrohit

**Comment by acshields** [comment]
Having text included would be a great addition. We can use the scope form’s title to supply the text in the project.

**Comment by vikasrohit** [comment]
@acshields I would not like to do any change specific to chameleon. I mean having a text might help in chameleon management but it might not look good in UI and specially might require consistent copy updates and fixes. I would suggest to only use icon with name of the template as tooltip, I think chameleon would be able to pick that.

**Comment by maxceem** [comment]
@vikasrohit do we have some agreement on which way to implement this?

**Comment by RishiRajSahu** [comment]
@maxceem I have proposed to put some basic code changes and get the UI changes reviewed to know whether that should work for chameleon or not from Product team. So will try to do it today.

**Comment by lakshmiathreya** [comment]
![Monosnap 2020-05-27 21-12-59](https://user-images.githubusercontent.com/51733042/83042296-1f8ea200-a05f-11ea-8d15-8c2a47a2fdef.jpg)
