### ISSUE TITLE
'Compatibility Testing' project icon is displayed in white so it is not visible in project listing page

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4006]
### Expected behavior
- Should display the icon in blue color

### Actual behavior
- 'Compatibility Testing' project icon is displayed in white so it is not visible in project listing page

### Steps to reproduce the problem

- Login as Manager
- Click 'Create Project' > Select 'Compatibility Testing'
- Create a project
- Go to the Project listing page and check the icon

**Please note this may be in production as well**

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/81855116-7dca6980-9524-11ea-8ced-69ff41bbebb2.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):**  Manager
**- Account used:**  `TCConManager`

**Comment by RishiRajSahu** [comment]
fixed and pushed to dev via https://github.com/appirio-tech/connect-app/commit/6d80d2d3d0ca31519f741dd88b0a3c7a7dcfa3a5

cc: @lakshmiathreya

**Comment by lakshmiathreya** [comment]
Icon is visible in Dev.
<img width="1512" alt="Screenshot 2020-07-23 at 2 48 20 PM" src="https://user-images.githubusercontent.com/51733042/88270731-b7bda600-ccf3-11ea-94be-9f593984e58b.png">
<img width="1389" alt="Screenshot 2020-07-23 at 2 49 02 PM" src="https://user-images.githubusercontent.com/51733042/88270736-bbe9c380-ccf3-11ea-9f35-ca2937ddcf6b.png">

**Comment by RishiRajSahu** [comment]
Done.
