### ISSUE TITLE
While creating a 'Compatibility Testing' project the form title shows as "Accessibilty Testing"

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4007]
### Expected behavior
- Should display as 'Compatibility Testing'

### Actual behavior
- While creating a 'Compatibility Testing' project the form title shows as "Accessibilty Testing"

### Steps to reproduce the problem

- Login as Customer
- Click '+ New Project' > Select 'Compatibility Testing'
- Select 'Quality Assurance' > Press 'Select' button from 'Compatibility Testing'
- Set Why are you starting this project today? = I need work done
- Click Next
- Check the title

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/81856034-cafb0b00-9525-11ea-837e-454866835a01.png)

https://monosnap.com/file/HnU4aY0M0FJVOY8TKjg4R1fmCmyATf

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):**  Customer
**- Account used:**  `CustomerUser`

**Comment by maxceem** [comment]
@RishiRajSahu this issue in the PROD metadata which I cannot fix by myself. Could you, please, help me with this.

**Comment by vikasrohit** [comment]
Fixed on production.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/81934983-8028d400-95b5-11ea-98e4-2c34086ad985.png)

**Comment by drasticdpk** [comment]
Verified with manager Role for prod env.
