### ISSUE TITLE
'Accessibility Testing' project title has a spelling mistake (Accessibilty Testing)

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4008]
### Expected behavior
- Should display as 'Accessibility Testing'
- Should be - https://connect.topcoder-dev.com/new-project/qa_accessibility_testing

### Actual behavior
- 'Accessibility Testing' project title has a spelling mistake (Accessibilty Testing)
- URL also has that spelling issue - https://connect.topcoder-dev.com/new-project/qa_accessibilty_testing

### Steps to reproduce the problem

- Login as Manager
- Click '+ New Project' > Select 'Accessibility Testing'
- Check the title "Accessibilty Testing"

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/81856386-5a082300-9526-11ea-977f-4672199edc4b.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):**  Manager
**- Account used:**  `TCConManager`

**Comment by maxceem** [comment]
Fixed in DEV data.
An old URL with a typo also works for backward compatibility.

**Comment by codejamtc** [comment]
Fixed in `Dev` - 🆗 
![image](https://user-images.githubusercontent.com/42398485/81935199-deee4d80-95b5-11ea-852c-7bb037183cca.png)

In `Prod` I can see `Acceptance/Beta Testing` instead `Accessibility Testing' ❌ @maxceem @vikasrohit 

![image](https://user-images.githubusercontent.com/42398485/81935232-ee6d9680-95b5-11ea-9ffb-7c823c4a3c56.png)
