### ISSUE TITLE
'Functional Feature Testing' project title displayed as 'User Sentiment Testing' 

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4009]
### Expected behavior
- Should display as 'Functional Feature Testing'

### Actual behavior
- 'Functional Feature Testing' project title displayed as 'User Sentiment Testing' 

### Steps to reproduce the problem

- Login as Customer
- Click '+ New Project' > Click 'View Solutions' from the Solutions
- Select 'Quality Assurance' > Press 'Select' button from 'Functional Feature Testing'
- Set 'Why are you starting this project today?' = I need work done
- Click Next
- Check the title "User Sentiment Testing"

### Screenshot/screencast

https://monosnap.com/file/jNRzbYQpWPbSEWjNAlyol8Fwrw5W9T

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):**  Customer
**- Account used:**  `CustomerUser`

**Comment by vikasrohit** [comment]
Fixed on production.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/81935518-5e7c1c80-95b6-11ea-8fa8-8fe5b1dd7b75.png)

**Comment by drasticdpk** [comment]
Verified with manager Role.
