### ISSUE TITLE
'Exploratory Testing' project title displayed as 'Accessibility Testing' 

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4010]
### Expected behavior
- Should display as 'Exploratory Testing'

### Actual behavior
- 'Exploratory Testing' project title displayed as 'Accessibilty Testing' 

### Steps to reproduce the problem

- Login as Customer
- Click '+ New Project' > Click 'View Solutions' from the Solutions
- Select 'Quality Assurance' > Press 'Select' button from 'Exploratory Testing'
- Set 'Why are you starting this project today?' = Submitting Client Request
- Click Next
- Check the title "Accessibilty Testing"

### Screenshot/screencast

https://monosnap.com/file/GgbkisCFbim0D70WmHBYrWdbEBk4H5

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):**  Customer
**- Account used:**  `CustomerUser`

**Comment by vikasrohit** [comment]
Fixed on prod.

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/81936654-37264f00-95b8-11ea-8434-cb21581f5047.png)

**Comment by drasticdpk** [comment]
Verified  form manger Role.
