### ISSUE TITLE
There is an another 'Create a new project' button at the bottom of the project list in Grid view

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4012]
### Expected behavior
- Should remove it because it is a duplicate, + New project button is on the header already

### Actual behavior
- There is an another 'Create a new project' button at the bottom of the project list in Grid view

### Steps to reproduce the problem

- Login as Manager
- Go to Project listing page
- Go to Grid view and scroll down to the last item 

cc @vikasrohit 

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/81865975-292eea80-9534-11ea-98d5-f41277974d04.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by vikasrohit** [comment]
as per design.
