### ISSUE TITLE
[Bulk Milestone Updates] Regression Testing

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4018]
We did some internal refactoring how milestones with timelines work:

![image](https://user-images.githubusercontent.com/146016/81893291-05ac8400-95b6-11ea-9623-5c4e844b022a.png)

**The expected outcome is that functionality didn't change.** The only difference is that now we are making fewer server requests as mentioned in the test cases below.

To validate that milestones functionality didn't change after refactoring we deployed 2 versions of the application:
- https://connect.topcoder-dev.com/ - **before** refactoring
- https://connect-test01.topcoder-dev.com/ - **after** refactoring - NOTE, this version has limitations, only test functionality related to **milestones** in this version.

### How to create a project for testing

See [video](https://monosnap.com/file/iQCDr8UZRSvs9fk0wlEmyyr1akqgvn) on how to do it:
- using user `pshah_customer` (or another Customer) create a new project
- using user `pshah_manager` (or another Manager) join project, add a new phase "Development Iteration (3 Milestones)", and change status of the phase to "In Progress"

### Test cases

Here are the most important cases to validate:
- **Complete milestone** - when we complete a milestone the next one becomes active and the start date set to the current date, see [video](https://monosnap.com/file/PpSKZjRQh2VBF5WycLcEdYVUcV8Bks). We have to make only 1 server request instead of 3.
- **Edit milestone duration** - when we update the duration of a milestone, the start date of the next milestone should be updated accordingly, see [video](https://monosnap.com/file/lMuGG7HtG25zVcZ7FymrNfPHaV5vzo). We have to make only 1 server request instead of 2.
- **Edit actual start date and completion date by admins** - when we update actual start date or completion date, the duration is updated automatically, see [video](https://monosnap.com/file/EOY4nY1fD9wuFt7HlAaf1osxiMoXOi). We have to make only 1 server request instead of 2. (Use a user with `administrator` role for testing this case).
- **Approve extension** - when we approve extension, the duration should be increased on that number of days, and the next milestone start date should move accordingly, see [video](https://monosnap.com/file/OfsehWxgNugyduncLNtQ5xD8giX6fu). We have to make only 1 server request instead of 2.
- **Submit final fixes** - when a user requests final fixes, the new "Files Fixes" milestone should show up with the final fixes description, see [video](https://monosnap.com/file/Glj5oBxsCCdEqyCrY9WeTSU6ndJbFH). We have to make only 1 server request instead of 2.
- **Complete final fixes** - when we complete final fixes, the milestone becomes completed and the last milestone also becomes completed. Also, the link we add in the final fixes milestone, appears in the Delivery milestone, see [video](https://monosnap.com/file/RH30TEsdwHHKhg0JegeDwwprXZZKnT). We have to make only 2 server requests instead of 4.
- **"RUX Iteration" milestone should work as it is now** - In particular, when we are adding links in "Add Links" milestone they appear in "Design Final Selection" milestone, see [video](https://monosnap.com/file/UDQEk45vKo527uu4Mut9XCIBtf6CgI).

### Notifications

It is not shown in the test videos above, but during all these test cases we also have to validate that notifications come as before when we perform various actions.
As we are marking notifications as read (and remove them) as soon as user see what was changed in the UI, it's important during testing notifications go to **Project Listing** page by the user who should get notifications. If we stay on the Project Details page, notifications could come but immediately disappear which might look like it didn't come.

See 2 example videos in the **Known issues** issues below, which are showing how we make actions by `pshah_manager` on the **Project Details** page, but we check notifications by the `pshah_customer` on the **Project Listing** page.

### Popups

During all the actions we are showing various popups in the bottom left corner. They are also supposed to work for milestones the same after refactoring.

![image](https://user-images.githubusercontent.com/146016/81894402-54f3b400-95b8-11ea-9d86-4a0e34c1d01c.png)

### Known issues

- Notification `updated the phase timeline` doesn't come when we mark milestones as complete or update duration or update actual start/complete dates.

    ![image](https://user-images.githubusercontent.com/146016/81895307-a0a75d00-95ba-11ea-8d63-48e5dfb66f37.png)

   see before https://monosnap.com/file/eKEMvlsh5yD8nXQxKfLgI2GLCVHeC6, after https://monosnap.com/file/vDH1lXlf4pqYNS6IyHjxq1QPgjWrgv

### Issues Labeling

Please, mark all the issues found during this testing with the milestone `2.10` and project `Bulk Milestone Updates`

![image](https://user-images.githubusercontent.com/146016/81895825-da2c9800-95bb-11ea-8189-74a4663e2425.png)

### PS

Our main aim during this testing is found differences in how milestones work before and after refactoring. Existent issues in how the milesontes work at https://connect.topcoder-dev.com/ could be logged separately, though they are not a priority right now.

**Comment by coderhacker** [comment]
QA update: Regression testing is in-progress. the final result very posted very soon. Thanks

**Comment by coderhacker** [comment]
QA Comments:  Regression testing has been done for this issue and this is a pass from QA., not any issues identified during regression testing, please find attached video file for the pass test case.

File Name: Regression_testing_4018_pass.mp4
file location : https://1drv.ms/v/s!ApYBYkEksnlSgbUusD1M0dD8RBcimA?e=iqWGHp
