### ISSUE TITLE
[Inviting users] - Regression testing

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4019]
We did some internal refactoring regarding user invites. The refactoring is not big, but to make sure there are no side-effect issues, it would be good test the next important cases:
1. invite a user to the **Customer Team** user by `handle`
2. invite an existent user to the **Customer Team** user by `email`
3. invite a NON-existent user to the **Customer Team** user by `email`

**Comment by codejamtc** [comment]
- Invite a user to the Customer Team user by handle. 🆗 
- Invite an existent user to the Customer Team user by email. 🆗 
- Invite a NON-existent user to the Customer Team user by email. 🆗 

https://monosnap.com/file/PvBLBZw8R6HJGSWEoOv6z155wgyBeC
