### ISSUE TITLE
[Messages] Different times displayed in Messages list and Message section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#402]
### Expected behavior

---

[Messages] Must display the same time in both locations
### Actual behavior

---

Different times displayed in Messages list and Message section
### Steps to reproduce the problem

---
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/438)
- Now in the Message (Must have 5-10 Messages)
- Enter (+) Add New Message
- Create a Message
- Wait for 1min 30sec
- Select the First Message
- Check the Time in the message list --> 1min
- Now check the message content time --> 2 minutes ago
### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section)

---

![2016-10-01_8-38-43](https://cloud.githubusercontent.com/assets/4592712/19011452/0e70ccb4-87b3-11e6-9c4e-b243d936c2cc.png)
### Environment

---
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
![screen shot 2016-10-13 at 6 11 31 pm](https://cloud.githubusercontent.com/assets/12552247/19372397/87dab530-9170-11e6-9d05-a1eba8b84352.png)

Still seeing this discrepancy. @parthshah, moving to you b/c you took over messaging. Please reassign if appropriate.

**Comment by fnisen** [comment]
Going to put this on hold b/c we're likely to rework this section.
