### ISSUE TITLE
Any Status to Active

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4048]
**Requirements**

- ~When any challenge or task is launched in association with the Connect project, the project status should be moved to active.~

- Remove existing logic that requires a project plan phase to move to Planned or In Progress status before a project can be moved into Active status.

- ~For all projects in existing Connect, if there is an active challenge or task then the project should be moved to Active status.~

**Comment by ajefts** [comment]
Link to subfeature: https://tcprod.productboard.com/feature-board/planning/features/4662310

**Comment by lakshmiathreya** [comment]
Newly created Project goes to "In Review" - 
<img width="1430" alt="Screenshot 2020-07-16 at 4 51 53 PM" src="https://user-images.githubusercontent.com/51733042/88281377-3111c480-cd05-11ea-9bd9-1c09a28c6311.png">

**Comment by lakshmiathreya** [comment]
Verified that Project Status can be moved to Active without need for a Phase to be in Progress state. 
<img width="1623" alt="Screenshot 2020-07-27 at 3 49 29 PM" src="https://user-images.githubusercontent.com/51733042/88531647-cb814900-d020-11ea-98d2-255f3b1650e5.png">

**Comment by RishiRajSahu** [comment]
Done.
