### ISSUE TITLE
White spaces are recognized as valid input for NOTES

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#405]
### Expected behavior

---

Must validate the White spaces for NOTES
### Actual behavior

---

White spaces are recognized as valid input for NOTES
### Steps to reproduce the problem

---
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Add white spaces for all the NOTES
- Click Save Changes
- Check the checklist
### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section)

---

![2016-10-01_20-23-18](https://cloud.githubusercontent.com/assets/4592712/19014819/f539142e-8814-11e6-87d2-d4398a22eff5.png)
### Environment

---
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment]
Valid.

**Comment by vikasrohit** [comment]
Should be very trivial. I can handle it.

**Comment by vikasrohit** [comment]
Done. Changes should be in dev by EOD.
