### ISSUE TITLE
Update segment script to support user consent

### ISSUE THREAD

**Issue by jswheeler** [appirio-tech/connect-app#4051]
### Expected behavior
Describe.
The connect app should support the segment 4.1.0 javascript app to support user consent (below).
```
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var t=analytics.methods[e];analytics[t]=analytics.factory(t)}analytics.load=function(e,t){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+e+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=t};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("o9nnBWWDraSZHiuruzcSfaNVJFphGq5G");
  analytics.page();
  }}();
</script>
```

Additionally,
The following process should be followed to implement consent manager
https://github.com/segmentio/consent-manager#standalone-script

Specifically:

- The consent code should be included on the same page as this analytics script
- The analytics.load function should b[e commented out](https://github.com/segmentio/consent-manager#usage).
- The [cookieDomain](https://github.com/segmentio/consent-manager#cookiedomain) string should be set to topcoder.com

### Actual behavior
Describe.
The current app is version 4.0.0.

### Steps to reproduce the problem
Load any page.

### Screenshot/screencast
Attach or link a resource.
this file needs to be updated.
https://github.com/appirio-tech/connect-app/blob/9998e03d406b35d52d0c1440cee7a10cbb02d527/src/index.jsx

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by RishiRajSahu** [comment]
@acshields The analytics.js version has been updated to latest on prod. https://github.com/appirio-tech/connect-app/pull/4097

**Comment by RishiRajSahu** [comment]
@jswheeler The analytics script of segment has been updated to latest version and patched to prod.
Regarding the `Additionally` part you have mentioned in the issue could you please clarify more ? I think this should be handled at centrally somehow, as consent manager window/popup needs to contains some text which suppose to be uniform across apps. 


```var bannerSubContent = 'You can change your preferences at any time.'
    var preferencesDialogTitle = 'Website Data Collection Preferences'
    var preferencesDialogContent =
      'We use data collected by cookies and JavaScript libraries to improve your browsing experience, analyze site traffic, deliver personalized advertisements, and increase the overall performance of our site.'
    var cancelDialogTitle = 'Are you sure you want to cancel?'
    var cancelDialogContent =
      'Your preferences have not been saved. By continuing to use our website, you՚re agreeing to our Website Data Collection Policy.'
```


fyi @mtwomey

**Comment by jswheeler** [comment]
@RishiRajSahu yes, this is being configure per app. It's not a requirement to have all the implementation be in sync. If this is completed, please close this issue. cc: @acshields

**Comment by jswheeler** [comment]
@RishiRajSahu if this is deployed, please close this issue. cc: @acshields

**Comment by RishiRajSahu** [comment]
@jswheeler Its done, the script was updated and deployed long back via this https://github.com/appirio-tech/connect-app/pull/4097/files , If nothing to add more, feel free to close the issue.

**Comment by jswheeler** [comment]
@RishiRajSahu
