### ISSUE TITLE
Not able to download the assets clicking the link

### ISSUE THREAD

**Issue by jagadeeswaras** [appirio-tech/connect-app#4052]
### Expected behavior
Describe.
Clicking the url, should be able to download proper zip file

### Actual behavior
Describe.
 Click on the url, it download some junk file, which is not a proper zip file.

### Steps to reproduce the problem
- Click the url - https://connect.topcoder.com/projects/14408
- click on download link
- Check the file in downloads folder which is junk

### Screenshot/screencast
<img width="1252" alt="Screenshot 2020-06-26 at 11 45 14 AM" src="https://user-images.githubusercontent.com/65228480/85854089-aabc9e00-b7ab-11ea-8f76-1c0d596debc9.png">
<img width="1114" alt="Screenshot 2020-06-26 at 11 46 58 AM" src="https://user-images.githubusercontent.com/65228480/85854104-af815200-b7ab-11ea-9742-82b525b5ecfc.png">

--

#### Environment
- OS: Mac
- Browser (w/version): Latest chrome browser
- User role (client, copilot or manager): All roles
- Account used:

**Comment by RishiRajSahu** [comment]
@lakshmiathreya it should be fixed in dev. I'm not finding ready-for-qa tag, so please check it.

**Comment by lakshmiathreya** [comment]
Zip downloaded as expected on clicking the File icon and the Asset Link. However, clicking on the download icon leads to the same Issue as seen currently:
<img width="1606" alt="Screenshot 2020-07-23 at 8 56 11 PM" src="https://user-images.githubusercontent.com/51733042/88305496-35e77000-cd27-11ea-8d55-d5f6072ac371.png">
<img width="1471" alt="Screenshot 2020-07-23 at 8 56 53 PM" src="https://user-images.githubusercontent.com/51733042/88305505-397af700-cd27-11ea-9b28-df1c33e6e856.png">

**Comment by lakshmiathreya** [comment]
Project link: https://connect.topcoder-dev.com/projects/9074

**Comment by RishiRajSahu** [comment]
@lakshmiathreya  Actually the issue was just about link click, but good to know another issue also. Actually I logged in with admin role so wasn't seeing the download icon. but now have fixed that also.

**Comment by lakshmiathreya** [comment]
Download icon working fine.

**Comment by RishiRajSahu** [comment]
Done.
