### ISSUE TITLE
V1: Navigation from Project to Work Manager

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4054]
**Desired Behavior**
Inside a Connect Project on the left sidebar above the "View Direct Project" hyperlink, display a hyperlink that is labeled "Launch Work Manager" that opens the Work Manager application when opened.

**Project-Type Exemptions**

- This feature is not needed on TaaS projects

**User Roles**

- Only Topcoder & Copilot users should see this button on all solution (managed-delivery) projects

**Comment by RishiRajSahu** [comment]
@acshields done and pushed to dev.
fyi @vikasrohit

**Comment by lakshmiathreya** [comment]
1. Work Manager navigation is seen for TaaS projects :
<img width="1480" alt="Screenshot 2020-08-28 at 5 37 16 PM" src="https://user-images.githubusercontent.com/51733042/91559168-317d2b00-e955-11ea-8c64-da6d96c32781.png">

**Comment by lakshmiathreya** [comment]
2. Work manager navigation is seen for Non-TC Copilot - this is as expected:
![screencapture-connect-topcoder-dev-projects-16604-2020-08-28-17_59_38](https://user-images.githubusercontent.com/51733042/91560110-e532ea80-e956-11ea-84d3-d1fba79376fb.png)

**Comment by lakshmiathreya** [comment]
3. Navigation not seen for non TC user - this is as expected:
<img width="1659" alt="Screenshot 2020-08-28 at 5 47 46 PM" src="https://user-images.githubusercontent.com/51733042/91560246-1f9c8780-e957-11ea-9064-95ce22c42027.png">

**Comment by lakshmiathreya** [comment]
Topcoder member is not able to see the Work Manager navigation - @RishiRajSahu @acshields - pls clarify visibility for all TC roles:
<img width="1661" alt="Screenshot 2020-08-28 at 7 17 23 PM" src="https://user-images.githubusercontent.com/51733042/91568613-292bec80-e963-11ea-8164-2830acf8d305.png">

**Comment by acshields** [comment]
@lakshmiathreya and @RishiRajSahu - Clarifying for above:

- Client users should not see Work Manager link (or Direct/SFDC as well)
- Copilot users should see Work Manager link (and Direct/SFDC as well)
- All Topcoder users (Admins, Managers, Account Executive, etc.) should see Work Manager link (and Direct/SFDc as well)

**Comment by RishiRajSahu** [comment]
@acshields yep the rules are applied as per you mentioned only, @lakshmiathreya regarding disabling for TaaS will fix it.

**Comment by lakshmiathreya** [comment]
<img width="1389" alt="Screenshot 2020-09-02 at 11 53 45 AM" src="https://user-images.githubusercontent.com/51733042/91939357-4ff77380-ed13-11ea-8861-dfc5da398483.png">

**Comment by lakshmiathreya** [comment]
WM Navigation link working fine for Admin and the currently Roles implemented: Manager, Project Manager, Program Manager, Solution Architect, Copilot. 
@acshields - pls clarify - if this is the expected list or should we add all other Internal TC roles?

**Comment by RishiRajSahu** [comment]
created followup issue https://github.com/appirio-tech/connect-app/issues/new
