### ISSUE TITLE
Won't display the 'Specification' icon in the menu sometimes

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#406]
### Expected behavior
-----------------------------------------------------------------
Must display the 'Specification' icon in the menu

### Actual behavior
-----------------------------------------------------------------
Won't display the 'Specification' icon in the menu sometimes

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Add white spaces for all the NOTES
- Click Save Changes
- Check the checklist

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_20-31-32](https://cloud.githubusercontent.com/assets/4592712/19014875/46925b04-8816-11e6-83b1-525f852d69cf.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
Closing
