### ISSUE TITLE
FAQ content - Hyperlinks to be highlighted 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4060]
### Expected behavior
Hyperlinks in the FAQ content should be highlighted.

### Actual behavior
There is no highlighting.

### Steps to reproduce the problem

<img width="1680" alt="Monosnap 2020-07-21 12-44-35" src="https://user-images.githubusercontent.com/51733042/88024830-fa934880-cb50-11ea-97b5-2cafef179b4d.png">

- TBD.
- TBD.

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by RishiRajSahu** [comment]
<img width="805" alt="Screenshot 2020-07-21 at 5 21 46 PM" src="https://user-images.githubusercontent.com/11248478/88059448-7c4f9a00-cb82-11ea-973a-67e402b8fa1e.png">


Have to add custom formatting for `hyperlink` types node when converting document to react-component.

**Comment by lakshmiathreya** [comment]
All hyperlinks highlighted as expected. 
<img width="1632" alt="Screenshot 2020-07-23 at 2 55 09 PM" src="https://user-images.githubusercontent.com/51733042/88271284-8c878680-ccf4-11ea-9d29-dd58f897e9a3.png">

**Comment by RishiRajSahu** [comment]
Done.
