### ISSUE TITLE
Remove footer links from Connect which are part of Dashboard FAQs

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4061]
### Expected behavior
With integration to contentful, the footer links are now part of FAQs `HOW TOPCODER WORKS` present on the dashboard page. So to remove the redundant and non-required urls remove the footer links 

### Actual behavior
Footer links are present on Connect app

### Screenshot/screencast
<img width="485" alt="Screenshot 2020-07-21 at 6 37 04 PM" src="https://user-images.githubusercontent.com/11248478/88058523-347c4300-cb81-11ea-8ec8-f45446299fbe.png">

--

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):any
- Account used: any

**Comment by RishiRajSahu** [comment]
@acshields just to confirm we need to remove these five links only right ?

**Comment by RishiRajSahu** [comment]
@acshields just to confirm we need to remove these five links only, right ?

**Comment by acshields** [comment]
@RishiRajSahu - yes, please remove all five of those hyperlinks as they will now be handled in the FAQ section. We can keep the Topcoder 2020 copyright in the footer.

**Comment by RishiRajSahu** [comment]
Pushed to dev with https://github.com/appirio-tech/connect-app/pull/4065

**Comment by RishiRajSahu** [comment]
Done.
