### ISSUE TITLE
Update Design Phase Templates Winner Selections in Project Plan

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4063]
**Current Version:** In project plan's design phase users must select three winners during design review/final design review milestones.

**Update Requested:** Design process has changed, and now only two winners must be selected. Please update all design project plan templates to only mandate two winners.

**Comment by RishiRajSahu** [comment]
@acshields Sure will update it , Just to confirm we just need to update option to select winners-designs and there is no change in the way we select checkpoint-review designs(we have condition of selecting minimum 5 checkpoint designs), right ?

**Comment by lakshmiathreya** [comment]
Winners updated to top 2 from top 3:- 

<img width="1474" alt="Screenshot 2020-07-24 at 5 31 18 PM" src="https://user-images.githubusercontent.com/51733042/88504805-606d4d80-cff3-11ea-9c9f-f7c6bf7d180d.png">
<img width="1389" alt="Screenshot 2020-07-24 at 5 21 46 PM" src="https://user-images.githubusercontent.com/51733042/88504799-59463f80-cff3-11ea-8d17-42ffcdc9b6bd.png">
<img width="1424" alt="Screenshot 2020-07-24 at 5 24 36 PM" src="https://user-images.githubusercontent.com/51733042/88504802-5e0af380-cff3-11ea-9ff6-5a48954d3d55.png">

**Comment by RishiRajSahu** [comment]
Done.
