### ISSUE TITLE
All Projects Dashboard FAQ - spelling error - 'Tocoder' 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4066]
### Expected behavior
Answer to "What are Topcoder's Standard Terms?" should be:-
Review Topcoder's Standard Terms here.

### Actual behavior
Answer is :- 
Review Tocoder's Standard Terms here.

### Steps to reproduce the problem
- TBD.
- TBD.
<img width="1632" alt="Screenshot 2020-07-23 at 2 55 09 PM" src="https://user-images.githubusercontent.com/51733042/88271706-3109c880-ccf5-11ea-9cd4-52068d1d6ee9.png">
- TBD.

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by RishiRajSahu** [comment]
@lakshmiathreya Corrected.

**Comment by lakshmiathreya** [comment]
<img width="1450" alt="Screenshot 2020-07-23 at 6 04 55 PM" src="https://user-images.githubusercontent.com/51733042/88286888-193f3e00-cd0f-11ea-8152-dcb01b3cf564.png">

**Comment by RishiRajSahu** [comment]
Done.
