### ISSUE TITLE
All Projects Dashboard FAQ - doesnt load Content when there is search term in toolbar

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4067]
### Expected behavior
~Should load All Projects Dashboard FAQ Content for All Projects Listing queries including Keyword Search.~
The ProjectSearch Toolbar doesn't apply to FAQ page so should be removed from FAQ page.

### Actual behavior
Project Listing is displayed instead of FAQ Content.

### Steps to reproduce the problem
REF - https://drive.google.com/file/d/19Mh8DKIiXq1ERoWRv_apJN0JXOd3FXr4/view?usp=sharing

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):any
- Account used: any

**Comment by RishiRajSahu** [comment]
@lakshmiathreya actually we don't have to have the search bar on top when loading FAQ pages as that search doesn't apply to FAQs. So have created the Custom Topbar for FAQs. Changes will in dev soon for testing.

**Comment by lakshmiathreya** [comment]
@RishiRajSahu - This isn'd about Search applying to FAQ content. When we have a listing generated by a Keyword search - you still see the FAQ tab - if you click on that - it just reloads the Project listing instead of the FAQ content.

**Comment by RishiRajSahu** [comment]
Done.
