### ISSUE TITLE
Reports tab doesn't work if we have some search term present in projectSearch ToolBar

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4069]
### Expected behavior
Reports tab should always work.

### Actual behavior
If there is some keyword searched in project search tool bar, them Reports tab is not working

### Steps to reproduce the problem
- Go to project listing page and search for any keyword to filter projects.
- Click on Reports Tab in the left hand navigation.
- Reports page is not opening.

#### Environment
- OS:any
- Browser (w/version):any
- User role (client, copilot or manager):any
- Account used: any

fyi @vikasrohit

**Comment by maxceem** [comment]
@RishiRajSahu done via https://github.com/appirio-tech/connect-app/pull/4123

**Comment by lakshmiathreya** [comment]
Search term seems to be disabling loading of Reports tab.
<img width="1472" alt="Screenshot 2020-09-23 at 6 08 45 AM" src="https://user-images.githubusercontent.com/51733042/93951330-a16baf00-fd63-11ea-9eed-2a3e4f6ab8b3.png">
<img width="1680" alt="Screenshot 2020-09-23 at 6 10 28 AM" src="https://user-images.githubusercontent.com/51733042/93951339-a6306300-fd63-11ea-8292-942f8a0482e5.png">

**Comment by maxceem** [comment]
@lakshmiathreya could you please test the issues which are now `Ready for QA` on **TEST01** environment https://connect-test01.topcoder-dev.com/ not on the regular **DEV** environment https://connect.topcoder-dev.com/

**Comment by lakshmiathreya** [comment]
Verified Reports tab with search term present in Prod.
