### ISSUE TITLE
Update Data Visualization Intake Form

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4073]
On this question "Are we using existing designs or creating new ones?" update the answer options to be:

- Use existing designs
- Create new designs
- Both

<img width="523" alt="Screen Shot 2020-07-28 at 2 24 45 PM" src="https://user-images.githubusercontent.com/41118149/88712151-e2867080-d0de-11ea-9ca9-b6eaab94d639.png">

Form link: https://connect.topcoder.com/new-project/data-visualization

**Comment by RishiRajSahu** [comment]
Done. Can be verified here https://connect.topcoder.com/new-project/data-visualization

fyi @acshields @lakshmiathreya

**Comment by acshields** [comment]
@RishiRajSahu - One small change request. Can you capitalize "Both"?

<img width="661" alt="Screen Shot 2020-08-11 at 10 47 11 AM" src="https://user-images.githubusercontent.com/41118149/89922206-571fdb80-dbc4-11ea-8c38-fba4a8d70bf6.png">

Once that change is in place, this form can be pushed to prod as soon as convenient for you/lakshmi.

**Comment by RishiRajSahu** [comment]
Done and pushed to prod.
