### ISSUE TITLE
Add Tooltip to Regression Testing Intake Form Question

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4074]
Include a tooltip on this question: "Briefly describe the application we will be testing."

Tooltip Title: Helpful Guidance
Tooltip Copy: Include the list of features/functionalities in scope, links to reference documentation, browser versions, devices, and platforms, to be considered for testing.

Form link: https://connect.topcoder.com/new-project/qa-regression

**Comment by RishiRajSahu** [comment]
Done, could be reviewed here https://connect.topcoder.com/new-project/qa-regression-v1.0
@acshields @lakshmiathreya

**Comment by acshields** [comment]
@RishiRajSahu - I reviewed this new intake form and it looks good. Please push to prod when it is workable for you/lakshmi.

**Comment by RishiRajSahu** [comment]
Pushed to prod.
