### ISSUE TITLE
Update Notes Question on Regression Testing Intake Form

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4078]
Form link: https://connect.topcoder.com/new-project/qa-regression

### Update 1
After the "Briefly describe the application we will be testing." question and before the "Notes" question, add another question with these details:
- Question: "After any code fixes are complete, do you want us to retest the failed cases?"
- Answer: [Yes/No Toggle Button]

### Update 2
Update the "Notes" question with the following changes:
- Relabel "Notes" to read: "Additional Details" 
- Update sub-text to read: "Include any additional details, such as the testing goal, delivery timelines, access restrictions, and preferred tools,  that would help with execution."

**Comment by RishiRajSahu** [comment]
Done, could be reviewed here https://connect.topcoder.com/new-project/qa-regression-v1.0
@acshields @lakshmiathreya

**Comment by acshields** [comment]
@RishiRajSahu - I reviewed this new intake form and it looks good. Please push to prod when it is workable for you/lakshmi.

**Comment by RishiRajSahu** [comment]
Pushed to prod.
