### ISSUE TITLE
Updates on Accessibility Testing Intake Form

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4079]
### Update 1
Currently, when the user selects "Accessibility Testing" testing on the catalog, they are brought to the correct URL (https://connect.topcoder.com/new-project/qa-accessibility-testing) but the form's header refers to acceptance/beta testing. We need to do the following update so the labels are correct:
- Update Header to read: Accessibility Testing
<img width="1143" alt="Screen Shot 2020-07-29 at 11 54 00 AM" src="https://user-images.githubusercontent.com/41118149/88829431-3605c680-d192-11ea-8379-9e5f97970ca4.png">

### Update 2
The first question is incorrect. Please remove the existing question and update to these two questions:
- Question 1: "What do you need as a part of your end-user acceptance/beta testing" question to read: "Will the accessibility testing cover more than 10 screens?"
- Question 1 Answer: [Yes/No Radio Button]
- Question 2 (Dependent on Question 1): If the user selects "Yes" in the previous question, this second question should be presented and read as follows: "How many screens require testing?"
- Question 2 Answers: [Radio Button range, shown below]
10-20
20-30
30-40
40-50
50+

### Update 3
Add in a new question, after the previous question(s), which will be presented as follows:
- Question: "What level of accessibility conformance do you want to achieve?"
- Answer Options: [Radio Buttons, options shown below]
A
AA
AAA

### Update 4
Add a tooltip to the question, "Briefly describe the application we will be testing."
- Tooltip Title: "Recommended Guidance"
- Tooltip Copy: "Provide details on the list of unique URLs, browser versions, and mobile devices in the scope of testing."

### Update 5
After the "Briefly describe the application we will be testing." question and before the "Notes" question, add another question with these details:
- Question: "After any code fixes are complete, do you want us to retest the failed cases?"
- Answer: [Yes/No Toggle Button]

### Update 6
Update the "Notes" question with the following changes:
- Relabel "Notes" to read: "Additional Details"
- Update sub-text to read: "Include any additional details, such as the testing goal, delivery timelines, access restrictions, and preferred tools, that would help with execution."

**Comment by RishiRajSahu** [comment]
@acshields @lakshmiathreya the changes are here https://connect.topcoder.com/new-project/qa-accessibility-testing-v1.1 to review.

**Comment by RishiRajSahu** [comment]
@acshields I have created a new label for tracking form update requests :) Hope we would be able to follow this method !

**Comment by acshields** [comment]
@RishiRajSahu - I reviewed this new intake form and it looks good. Please push to prod when it is workable for you/lakshmi.

**Comment by RishiRajSahu** [comment]
Done and pushed to prod.

**Comment by RishiRajSahu** [comment]
@lakshmiathreya please review here https://connect.topcoder.com/new-project/qa-accessibility-testing
