### ISSUE TITLE
Allow only max 4096 characters to be set in textarea

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#408]
Expected behavior

- Allow only texts with length smaller than 4096 characters.

Actual behavior

 - Any length of text can be set in field.

Steps to reproduce the problem

- Login as connect user role.

- New Project.

- Select Prototype an app.

- Select Desktop.

- Complete Project Name.

- Set in Description textarea a text with length more than 4096 characters.

Environment
- OS: Windows 7
- Browser (w/version): IE 11, Mozilla Firefox 49.0.1, Chrome 49.0.2623
- User role: copilot
- Account used: christina_uw
- Usefull tool to be used for check the number of characters: http://www.lettercount.com/

see attach!

![2016-10-01_1812](https://cloud.githubusercontent.com/assets/5114907/19014941/a9d0d9fc-8802-11e6-9416-1efdacd93888.png)

**Comment by mahestro** [comment]
Limit needed. Valid.

**Comment by parthshah** [comment]
No limits enforced.
