### ISSUE TITLE
Replicate Project FAQs on Zurich & CS Projects

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4081]
Replicate project FAQs for TaaS, DS, QA, Design & Dev onto Zurich and CS projects.

**Comment by acshields** [comment]
@RishiRajSahu - Update: The account executive for Zurich wants to review the FAQs with them before they are made live on production (to be clear, they do want FAQs - it's just a review to see if all the questions apply). So continue with the association of FAQLists to Zurich projects. Let's just hold on publishing the FAQs until I get final confirmation on the FAQItems content.

**Comment by RishiRajSahu** [comment]
@acshields associating the FAQList would mean publishing them, so let's wait for them to review. meanwhile ariel could you just place **FAQlist name** for corresponding zurich forms in this sheet https://docs.google.com/spreadsheets/d/1P01THFCESuy1qmJ77KExOj_QxOc9BVOyMmb9dpOyl3A/edit?ts=5f0f5007#gid=1726726308, you can get **FAQlist name** from ID-mapping tab of the sheet.

**Comment by acshields** [comment]
@RishiRajSahu - I have updated the spreadsheet.

**Comment by acshields** [comment]
@RishiRajSahu can you publish these FAQ pages to PROD, please?

**Comment by RishiRajSahu** [comment]
This is done.
