### ISSUE TITLE
Add "Provide Application Feedback" Capability to Projects App

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4085]
### Update 1 
On the 'all projects dashboard' of connect.topcoder.com, add a button underneath the "How Topcoder Works" tab in the left sidebar.
- Label the button: "Give Application Feedback"
- This button should clickable, but it will not trigger any additional application actions. Instead, this button will serve as an anchor and trigger for a Chameleon survey where the user can provide and submit application feedback.
- This button should be viewable to all application users.

### Update 2
On the 'all projects dashboard' of connect.topcoder.com, underneath the "Give Application Feedback" button in the left sidebar, include the following:
- Text that reads: "Have an urgent issue?"
- Text that reads: "E: support@topcoder.com"
- This should be viewable to all application users.

### Update 3
Inside a project, add the following in the left sidebar:
- Add a section-break line underneath the "Join Project" button in Topcoder Team
- Add a button in the new section.
- Label the button: "Give Application Feedback"
- This button should clickable, but it will not trigger any additional application actions. Instead, this button will serve as an anchor and trigger for a Chameleon survey where the user can provide and submit application feedback.
- This button should be viewable to all application users.

### Update 4
Inside a project, underneath the "Give Application Feedback" button in the left sidebar, include the following:
- Text that reads: "Have an urgent issue?"
- Text that reads: "E: support@topcoder.com"
- This should be viewable to all application users.

**Comment by maxceem** [comment]
@RishiRajSahu this issue looks clear, but I'm not sure how to trigger Chameleon survey. Could you help me to understand on how to call it?

- Regarding the UI for these elements, as there are no designs provided I might create UI by reusing and adapting some existent elements.

**Comment by acshields** [comment]
@maxceem - You don't need to worry about enabling Chameleon. We already have the script installed and Chameleon is the 3rd-party tool. All I need is a clickable button that I can anchor the Chameleon survey too, so when a user clicks on this part of the screen it will trigger the Chameleon survey I set up to open.

**Comment by maxceem** [comment]
@acshields @RishiRajSahu should we add some icon for the **Provide Application Feedback** link? I didn't find any suitable one so I use the same as for **How Topcoder Works**.

So far it looks like this.

### Project List Sidebar

![image](https://user-images.githubusercontent.com/146016/93072536-339bf500-f68a-11ea-92ac-1ba800babf64.png)

### Project Details Sidebar

![image](https://user-images.githubusercontent.com/146016/93075745-e8381580-f68e-11ea-983a-5681c558eb63.png)

Please, let me know if you would like to adjust anything.

**Comment by maxceem** [comment]
@RishiRajSahu done via https://github.com/appirio-tech/connect-app/pull/4122

**Comment by lakshmiathreya** [comment]
All 4 Updates verified for multiple User roles. 
![Uploading Screenshot 2020-09-23 at 1.50.22 PM.png…]()

**Comment by lakshmiathreya** [comment]
Verified all 4 updates in Prod.

**Comment by acshields** [comment]
@RishiRajSahu - Per my Slack message, I just discovered that Chameleon is not going to be able to support the required survey experience. 

In order to support the goal of collecting App Feedback from users, I have now created a Google Form (https://forms.gle/zL2GsdLACB5KyTT18) that I would like hyperlinked to this "App Feedback" button. Please update this button functionality so that once clicked, it opens the hyperlinked Google Form.

**Comment by lakshmiathreya** [comment]
Verified on Prod the Google For for App Feedback:

<img width="1680" alt="Screenshot 2020-09-30 at 4 51 55 PM" src="https://user-images.githubusercontent.com/51733042/94679379-9dc8c100-033d-11eb-832d-3f227f6b4fee.png">
<img width="1680" alt="Screenshot 2020-09-30 at 4 52 30 PM" src="https://user-images.githubusercontent.com/51733042/94679396-a3bea200-033d-11eb-86fe-253fba60232e.png">
