### ISSUE TITLE
Typed Unsent Message Deletes If Another User Posts Before Sending

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4096]
Bug Description: If a user posts a message as another user is writing a message in a discussion thread, the message that the user is writing is deleted as the discussion thread refreshes.

Solution: The unsent typed message should be saved as a draft while the discussion thread refreshes.

<img width="671" alt="Screen Shot 2020-08-21 at 9 54 34 AM" src="https://user-images.githubusercontent.com/41118149/90904187-90123a00-e394-11ea-8e20-97c076c1926b.png">

**Comment by lakshmiathreya** [comment]
Unable to verify this since Message notifications are failing:
<img width="1680" alt="Screenshot 2020-09-24 at 6 30 59 AM" src="https://user-images.githubusercontent.com/51733042/94089069-bf064a80-fe2f-11ea-9ae4-3ada5c92f42f.png">

**Comment by maxceem** [comment]
@lakshmiathreya could you please try one more time with another project, maybe there is some corrupted data in that project. The error you've got is not connected with the changes in this issue.

For example, it works well for me in this project connect-test01.topcoder-dev.com/projects/9093, see video https://monosnap.com/file/Wn8TmMsD1YfHIJlKBki4XXVOFiVksK

**Comment by lakshmiathreya** [comment]
Verified with another project - Messages are retained when another User posts in parallel ... 
<img width="1453" alt="Screenshot 2020-09-24 at 6 49 52 PM" src="https://user-images.githubusercontent.com/51733042/94150503-d88ead00-fe96-11ea-8963-f9535ebc9281.png">

**Comment by lakshmiathreya** [comment]
Messages interleaved between users in parallel verified in Prod.
<img width="1294" alt="Screenshot 2020-09-29 at 6 55 38 PM" src="https://user-images.githubusercontent.com/51733042/94564478-a52c9380-0285-11eb-965a-bf849de04991.png">
