### ISSUE TITLE
Line spacing of the same word in Custom Features is too big

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#410]
### Expected behavior
-----------------------------------------------------------------
Must reduce the line spacing of the same word in Custom Features

### Actual behavior
-----------------------------------------------------------------
Line spacing of the same word in Custom Features is too big

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Click 'Add/Edit Features'
- Scroll down and click 'Add a custom feature' button
- Enter a Long feature name (eg: Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features)
- Click Save Changes
- Check the Left side panel

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_20-52-03](https://cloud.githubusercontent.com/assets/4592712/19014997/f5879ee2-8818-11e6-85ea-0d84ba593413.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment]
Valid.
