### ISSUE TITLE
Segment Profile Information by User Role

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4103]
### Current State
All Projects App users have the same required profile information, regardless of their user role.

### Future State
Projects App users have different required profile information depending on their user role.

### Update 1 - Client Total Profile
_Required Account Information (*Captured during account registration)_
- First Name
- Last Name
- Account Email
- Account Username
- Account Password

_Required Progressive Profile Information_ 
- Job Title
- Business Phone
- Business Email
- Company Name
- Company URL

_Optional Progressive Profile Information_ 
- Profile Picture
- Timezone
- Normal Work Hours

Notes:
The "Country" field will be removed from the client user profile.
The "Company URL" will be added as a new required profile question. The field should be labeled "Company URL" and the answer will be a free text field where the user can paste or type a URL.

### Update 2 - Copilot Total Profile
_Required Account Information (*Captured during account registration)_
- First Name
- Last Name
- Account Email
- Account Username
- Account Password

_Required Progressive Profile Information_ 
- Timezone
- Normal Work Hours

_Optional Progressive Profile Information_
- Profile Picture

### Update 3 - Topcoder Employee Total Profile
_Required Account Information (*Captured during account registration)_
- First Name
- Last Name
- Account Email
- Account Username
- Account Password

_Required Progressive Profile Information_ 
- Job Title
- Timezone
- Normal Work Hours

_Optional Progressive Profile Information_
- Profile Picture

**Comment by dmessing** [comment]
@acshields does Business Email change their log in information or their main email?

**Comment by dmessing** [comment]
I think Country might be a required account field we have to capture for some legal reasons, but maybe we can look at that

**Comment by dmessing** [comment]
Is account registration different than member account registration?

**Comment by maxceem** [comment]
1. Do I understand it correctly, that **Topcoder Employee** are the users who have one of the next roles?

    - Connect Manager
    - Connect Admin
    - administrator
    - Connect Account Manager
    - Business Development Representative
    - Presales
    - Account Executive
    - Program Manager
    - Solution Architect
    - Project Manager

2. As we are removing `Country` and adding `Company URL` should we also update the user profile accordingly, right?

    ![image](https://user-images.githubusercontent.com/146016/92474798-1926cf00-f1e5-11ea-9c64-39e0b6887319.png)

**Comment by RishiRajSahu** [comment]
1. Yes, you are correct
2. Yes we would have to keep it consistent for clients everywhere, But I guess we should first check whether traits support adding a new field company URL or not ? could you try that via postman ?

**Comment by maxceem** [comment]
> But I guess we should first check whether traits support adding a new field company URL or not ? 

@RishiRajSahu good catch. The trait doesn't support the company URL, see https://github.com/appirio-tech/ap-member-microservice/blob/dev/service/src/main/java/com/appirio/service/member/api/MemberProfileConnectInfo.java.

**Comment by acshields** [comment]
@RishiRajSahu - Just following up on your Slack message regarding "Country." Noted that this will be kept as a required profile attribute for all users in the background. To reconfirm, "Country" would be captured during account registration, and then in Projects App's progressive profile completion, this field should already be captured and should not trigger a prompt to complete.

**Comment by acshields** [comment]
> Is account registration different than member account registration?

@dmessing - Account registration happens before progressive profile completion. During account registration, a new user identifies whether they are registering as a client or a community member (if client is selected, the Business Client user role gets applied. They then complete the account registration form (First/Last Name, Country, Email Address, Username, Password) - the account registration form questions are the same for all new users.

Then, in Projects App during progressive profile completion, we would prompt the user to complete profile information if they have incomplete required fields (Ex. For client, we also need to capture Job Title, Company Name, Company URL, Business Email, Business Phone).

**Comment by maxceem** [comment]
@RishiRajSahu 

As mentioned by **acshields**

> To reconfirm, "Country" would be captured during account registration, and then in Projects App's progressive profile completion, this field should already be captured and should not trigger a prompt to complete.

So the `Country` would be required, but because it suppose to be captured by the initial user registration, it wouldn't be asked during progressive registration in Connect.
But currently when I register a new user, I enter `Country` but it is not populated in `basic_info`. So it would be asked during progressive registration again. Probably it's an issue in Member Service.

**Comment by RishiRajSahu** [comment]
@maxceem yeah seems to be an issue with member service and I guess this is already reported to them `https://github.com/topcoder-platform/community-app/issues/4707` 

but just wanted to confirm Once country is updated on Connect profile, we are keeping country consistent/same in both `basic_info` and `connect` traits ?

**Comment by maxceem** [comment]
@RishiRajSahu no, we don't keep it in sync in Connect. In Connect we only update `country` in `connect_info`, but not in `basic_info`:

![image](https://user-images.githubusercontent.com/146016/93894442-66339680-fcf7-11ea-90d4-615afd069838.png)

**Comment by maxceem** [comment]
@RishiRajSahu fyi, I've made `country` required in the user profile so in case it's missing in user data we ask user for it, otherwise we cannot save data to the server. See commit 74222c6067d519a4745e8fc0d3f0c2665479e6f8.

**Comment by maxceem** [comment]
@RishiRajSahu this is done via https://github.com/appirio-tech/connect-app/pull/4131

Now User Profile has different set of fields depend on user roles.

**NOTE** As **Country** is required by the Member Service so it's added to all user profiles as required field.

#### Client Total Profile

![image](https://user-images.githubusercontent.com/146016/94147375-e08e2300-fe7d-11ea-833b-ea3086926914.png)

Note, that as per previous requirements some fields are disabled:
- clients cannot edit `Company Name` once entered
- Also, clients cannot change `Bussiness Email` by themself for now see related issue https://github.com/appirio-tech/connect-app/issues/4107

#### Copilot Total Profile

![image](https://user-images.githubusercontent.com/146016/94147333-d2d89d80-fe7d-11ea-9153-60339f1989dd.png)

#### Topcoder Employee Total Profile

![image](https://user-images.githubusercontent.com/146016/94147236-b5a3cf00-fe7d-11ea-9b0f-301647270464.png)

**Comment by maxceem** [comment]
@lakshmiathreya this is ready for QA now.

**Comment by lakshmiathreya** [comment]
Segmented Profile Information shows correct fields for each User role type:
<img width="1433" alt="Screenshot Progressive profile Ac mgr + Con mgr create Project" src="https://user-images.githubusercontent.com/51733042/94390517-88eb0280-0170-11eb-9916-c3cae7e6bdec.png">
<img width="1429" alt="Screenshot Progressive profile Ac mgr + Con mgr open Project" src="https://user-images.githubusercontent.com/51733042/94390535-91dbd400-0170-11eb-9b8f-e0301b2270ec.png">
<img width="1231" alt="Screenshot Progressive Profile Account Manager create Project" src="https://user-images.githubusercontent.com/51733042/94390541-943e2e00-0170-11eb-9221-d509e7b4dbea.png">
<img width="1309" alt="Screenshot Progressive Profile Account Manager open Project" src="https://user-images.githubusercontent.com/51733042/94390551-986a4b80-0170-11eb-9158-0f627d9978db.png">
<img width="1332" alt="Screenshot Progressive Profile Client member create Project" src="https://user-images.githubusercontent.com/51733042/94390563-9e602c80-0170-11eb-87c0-622911dc069b.png">
<img width="1408" alt="Screenshot Progressive Profile Client member open Project" src="https://user-images.githubusercontent.com/51733042/94390570-a28c4a00-0170-11eb-98cd-e8a2f2dc29e9.png">
<img width="1375" alt="Screenshot Progressive profile Copilot create Project" src="https://user-images.githubusercontent.com/51733042/94390578-aa4bee80-0170-11eb-9f48-4970e0f0db89.png">
<img width="1432" alt="Screenshot Progressive profile Copilot open Project" src="https://user-images.githubusercontent.com/51733042/94390583-addf7580-0170-11eb-81ee-dd9a8b1a83f5.png">

**Comment by maxceem** [comment]
@lakshmiathreya 

- `Timezone` is not populated due to the specific issue with `Asia/Kalkata` timezone, see comment https://github.com/appirio-tech/connect-app/issues/4109#issuecomment-700494557 for details.
- `Country` is not populated due to the issue in Member Service which asks country during registration but doesn't populate `basic_info` trait.

**Comment by lakshmiathreya** [comment]
@maxceem - Country missing - could you log an in Issue with Member Service and update it here?

**Comment by maxceem** [comment]
@lakshmiathreya @RishiRajSahu logged-in an issue for the **Member Service** https://github.com/appirio-tech/ap-member-microservice/issues/302.
Also, a possibly related issue at the Community App: https://github.com/topcoder-platform/community-app/issues/4707

**Comment by lakshmiathreya** [comment]
Verified Segmentation of Profiles based on Roles on Prod:
<img width="1307" alt="Screenshot 2020-09-29 at 11 41 33 AM" src="https://user-images.githubusercontent.com/51733042/94581922-a8a22980-0249-11eb-9fec-78c5ab3f8515.png">
<img width="1263" alt="Screenshot 2020-09-29 at 11 43 52 AM" src="https://user-images.githubusercontent.com/51733042/94581947-afc93780-0249-11eb-9869-b0aecc8cc35b.png">
<img width="1232" alt="Screenshot 2020-09-29 at 11 45 59 AM" src="https://user-images.githubusercontent.com/51733042/94581957-b35cbe80-0249-11eb-9702-b316024a866d.png">
