### ISSUE TITLE
New Progressive Profile Completion Scenario: Opens a Project

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4105]
### Scenario
A user has been invited to a project. If they have incomplete required profile information, the following should occur:
1. The user opens a project
2. Once inside the project, the user sees a pop-up window with the following included:
- Header Confirmation Message: "Welcome to [Project Name]"
- Sub-Header Profile Prompt: "Complete your profile now."
- Body: [Display Incomplete Required Profile Fields]
- A "Close" button in the top-right of the pop-up window, where the user can opt-out if desired.
- A "Save" button at the bottom of the pop-up window body, which when clicked will save the profile information.
3. Once the "Save" or "Close" buttons are clicked, the pop-up window should close.

**Comment by maxceem** [comment]
Do I understand this correctly, that this should happen once per project? So each time user joins another project user would receive such a popup (as long as the user has an incomplete profile).
- If the user opens the project the second time, no popup is shown even the profile is incomplete.

**Comment by RishiRajSahu** [comment]
@maxceem yes, its should be asked for every new project invite only, and once user has filled/opted-out for a certain project it should not be asked when user open the projects later.

**Comment by maxceem** [comment]
Ok, so every time user opens any project, the user would see this popup, as long as the profile is incomplete.

**Comment by acshields** [comment]
@maxceem - Yes. Essentially, what we discussed in a meeting yesterday was:

- Any time a user opens a project AND they have incomplete required profile information, they should see the pop-up to complete their profile information.
- The user can choose to opt-out of providing their profile information at this time, if desired. However, if they choose to opt-out, the next time they open any project they will be prompted again. This will happen until the user provides the required profile information.
- The opt-out choice when opening a project is different from our other progressive registration scenario when a user is creating a new project. When a user is creating a new project, they will be required to provide the incomplete profile information before they can submit the intake (no change to this other scenario). Just wanted to call out that in the open a project scenario, the logic will be different and a user can choose to opt-out.

**Comment by lakshmiathreya** [comment]
Verified that:
-- Everytime the User attempts to open a Project - they are prompted to complete their profile. 
-- They are given an option to opt out.
-- However, when they open it next, they are prompted to complete profile again.
-- Once the profile is complete, they are not prompted when they open the project next.

**Comment by lakshmiathreya** [comment]
Verified the above on Prod.
