### ISSUE TITLE
New Progressive Profile Completion Scenario: First Time in Projects App

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4106]
### Scenario
The user has logged into Projects App (connect.topcoder.com) for the first time ever. When this happens, the following should occur:
1. The user has logged into connect.topcoder.com for the first time in that user account's history.
2. The user sees a pop-up window appear, with the following included:
- Header Confirmation Message: "Welcome to Topcoder!"
- Sub-Header Profile Prompt: "To get started, begin by completing your profile."
- Body: [Display Incomplete Required Profile Fields]
- A "Close" button in the top-right of the pop-up window, where the user can opt-out if desired.
- A "Save" button at the bottom of the pop-up window body, which when clicked will save the profile information.
3. Once the "Save" or "Close" buttons are clicked, the pop-up window should close.

**Comment by vikasrohit** [comment]
@RishiRajSahu @acshields should we show the popup on project open instead of login of user? I mean, when user opens any project link which he/she has access to and we don't see the required information filled in his/her profile, we can show that modal.

**Comment by RishiRajSahu** [comment]
Yep @vikasrohit agree, having progressive flow triggered for first time login is a not a easier check to put directly by connect ? that's how will we decide in Connect itself that this is the first time login and wrt UX also putting a progressive trigger on Dashboard page doesn't seem good to me as if user opts out every time it will be visible again on every login? Let's discuss this with @acshields 
Other than that after logging into Connect following Scenarios are possible - 
1. User is invited to connect, see a project with join/decline button- this is handled by https://github.com/appirio-tech/connect-app/issues/4105
2. User is going to create a project in Connect - on submitting a project we are already asking this, right @maxceem  ?

**Comment by maxceem** [comment]
> 2. User is going to create a project in Connect - on submitting a project we are already asking this, right @maxceem ?
Right

**Comment by RishiRajSahu** [comment]
@acshields I think we can close this issue as its already been taken care by #4105 and project-submission already.

**Comment by acshields** [comment]
@RishiRajSahu @maxceem - Yes, we can close this issue as we will not be proceeding with it after our discussion yesterday. I will proceed with closing the issue.
