### ISSUE TITLE
Profile Timezone Enhancement

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4109]
**Enhancement:** Retrieve user's timezone from the https// request and prefill into profile.

### Update - Workflow
- When user logs into Projects App, retrieve their timezone from the https request and prefill this data onto their profile.
Here is a reference article: https://stackoverflow.com/questions/22479407/how-to-get-clients-time-zone-in-java-from-httpservletrequest#:~:text=there%20are%202%20ways%20we%20get%20browser's%20timezone%20from%20request%20object.&text=return%20of%20above%20can%20be,%3D%20absOffset%60%3B%20buffer.
- A user can choose to manually override the pre-filled timezone if desired by selecting an alternate timezone from the dropdown menu.

**Comment by maxceem** [comment]
At which place should we prefill user timezone? 

If we prefill user timezone on the regular user profile page https://connect.topcoder-dev.com/settings/profile it might bring confusion, as visually user would see that timezone is already selected on the profile, so user wouldn't click "Save" button, and it would not be saved. And other people would not see user timezone

![image](https://user-images.githubusercontent.com/146016/92471245-48870d00-f1e0-11ea-8296-1bd82601f349.png)

So I guess we only have to prefill the timezone when we know for sure that user would click "Save" button. So the places are:
1. connect user registration form https://accounts.topcoder.com/connect/registration
2. incomplete profile during project creation
3. incomplete profile during first login https://github.com/appirio-tech/connect-app/issues/4106

**Comment by RishiRajSahu** [comment]
@maxceem yep all the 3 places are correct, and on profile page user should see the saved one or empty(if not filled yet).

**Comment by maxceem** [comment]
Thanks, @RishiRajSahu. Btw do we still have to support a separate registration form for Connect https://accounts.topcoder.com/connect/registration. It looks like if we open Connect app https://connect.topcoder.com/ and click a link to register in login form, we would see a standard Topcoder register form

![image](https://user-images.githubusercontent.com/146016/92568578-0b765580-f288-11ea-9878-3db14c411794.png)

**Comment by acshields** [comment]
@RishiRajSahu and @maxceem - following up on our meeting call yesterday with clarifying notes.

When a user is first prompted for progressive profile completion, the app should fetch their current timezone from their browser.
The user can either leave the timezone as-is, or they can manually update the timezone from a dropdown list if the timezone that was returned was not accurate or is not their primary timezone (for example, maybe the user is in Mexico on a trip but their primary timezone is in China).
After completing the progressive profile completion, the user's timezone does not need to be automatically updated each time the user logs in. However, the user can go and manually update their timezone at any time.

**Comment by lakshmiathreya** [comment]
Timezone is not being picked automatically:
<img width="1667" alt="Screenshot 2020-09-23 at 8 05 30 PM" src="https://user-images.githubusercontent.com/51733042/94027202-37d9b800-fdd8-11ea-97b7-77fcfa9ea953.png">

**Comment by maxceem** [comment]
@lakshmiathreya as per the discussion above timezone has to be only autodetected during **progressive profile** which is shown if profile is incomplete:
- when a user tries to open any project
- when a user tries to create a new project

On the user profile page, we don't use autodetection for timezone even if it's empty.

**Comment by lakshmiathreya** [comment]
These are the forms that are presented for Progressive profile completion:
<img width="1220" alt="Screenshot 2020-09-24 at 2 20 25 PM" src="https://user-images.githubusercontent.com/51733042/94123654-b33b7800-fe71-11ea-9f55-f12d367f1177.png">
<img width="1034" alt="Screenshot 2020-09-24 at 2 23 42 PM" src="https://user-images.githubusercontent.com/51733042/94123676-b8002c00-fe71-11ea-9298-c3555667b657.png">

**Comment by lakshmiathreya** [comment]
- Timezone is not captured
- I included the screenshot of the Profile earlier to indicate that after Profile completion - Timezone is still not filled in.

**Comment by lakshmiathreya** [comment]
The above scenario is for user opening a project.

**Comment by maxceem** [comment]
@lakshmiathreya as per https://github.com/appirio-tech/connect-app/issues/4104 we only show `required` and incomplete fields in this form now. For the customers users `Timezone` is not required.

Could you please, try this with some user who has special Topcoder roles, so the `Timezone` field would be required and shown.

**Comment by maxceem** [comment]
@lakshmiathreya you may use this `Account Executive` user for testing: `pshahaccex` (with out standard password). For this user timezone is reuired so it is shown and prefilled:

![image](https://user-images.githubusercontent.com/146016/94136254-576ef000-fe6d-11ea-9e94-ec4841d13e4b.png)

**Comment by lakshmiathreya** [comment]
@maxceem pls clarify - the #1 requirement above - adding Timezone during registration is no longer a requirement?

**Comment by maxceem** [comment]
@lakshmiathreya right, as was clarified by Ariel:

![image](https://user-images.githubusercontent.com/146016/94143395-6e670f80-fe78-11ea-897e-e537ea2b945b.png)

- So we only have to prefill timezone during progressive profile completion
- We should NOT prefill it on the User Profile Page https://connect-test01.topcoder-dev.com/settings/profile
- And during initial user registration we don't ask for timezone at all anymore

**Comment by lakshmiathreya** [comment]
Verified with Roles where Timezone is mandatory. 
<img width="1658" alt="Screenshot 2020-09-24 at 7 12 22 PM" src="https://user-images.githubusercontent.com/51733042/94153148-0c1f0680-fe9a-11ea-9895-f429020b9b16.png">

**Comment by lakshmiathreya** [comment]
@maxceem timezone is mandatory for Account Manager - however, it did not get pre populated when the user Opened a Project.
<img width="1452" alt="Screenshot 2020-09-25 at 2 21 20 PM" src="https://user-images.githubusercontent.com/51733042/94254526-87d58d80-ff44-11ea-9eac-08491e29f321.png">

**Comment by RishiRajSahu** [comment]
@lakshmiathreya timezone is mandatory for all Topcoder roles , ref https://github.com/appirio-tech/connect-app/issues/4103 . It must be empty because user hasn't filled it during progressive trigger

**Comment by lakshmiathreya** [comment]
yes @RishiRajSahu - I intentionally didnt fill it in order to test automation timezone filling which didnt happen during progressive registration. Hence I got a doubt reg this field being mandatory. Will use #4103 as reference and verify both these Issues.

**Comment by maxceem** [comment]
@RishiRajSahu 
This issue is a very particular. This happens because `Calcutta` was renamed to `Kolkata` in 2001. Browsers still detect this timezone as `Asia/Calcutta` while in our timezone list we only allow `Asia/Kolkata`.
As a result during progressive registration value `Asia/Calcutta` saved to the server, but as we don't allow this value to be shown in frontend, it is shown as unselected:

![image](https://user-images.githubusercontent.com/146016/94523952-9d93cd00-023a-11eb-9f78-65794cd09c10.png)

If I'm in another timezone it works well https://monosnap.com/file/oEwTZQZm7oNHAxp3LYjpWqpBpcCvhp. Also, if I hardcode `Asia/Kolkata` for testing it also works https://monosnap.com/file/HboTSWCyYt4JKHJPg35792NtQsAvpA

### Solution

I think the best solution would be during autodetecting check if the detected value is allowed (on the list) in our frontend. If it's not on the list we should keep it empty to force user to choose any value from the list manually. So in such cases cannot automatically detect the timezone.

**Comment by RishiRajSahu** [comment]
@maxceem 
yes, leave the ignore the autodetected timezone if its not in the list.

**Comment by maxceem** [comment]
@RishiRajSahu fixed via 496e69189c9d70d6bd13449495c08c8aa95518cf

Now for `Kolkata` timezone it not prefilled at all as browser cannot detect it properly, so user would be required to enter it:

![image](https://user-images.githubusercontent.com/146016/94526746-a9818e00-023e-11eb-8e50-dda0f324a337.png)

If the timezone is on the list, then it's autodetected and prefilled:

![image](https://user-images.githubusercontent.com/146016/94526930-efd6ed00-023e-11eb-8a45-b15250b6f9e4.png)

**Comment by lakshmiathreya** [comment]
yes @maxceem - as suggested by Rishi I changed to New York and it is auto detecting correctly now.
<img width="1623" alt="Screenshot 2020-09-29 at 3 43 45 AM" src="https://user-images.githubusercontent.com/51733042/94528355-42e07e00-0206-11eb-9a0c-166b4c523397.png">

**Comment by lakshmiathreya** [comment]
Timezone being auto detected and set correctly during progressive profile completion - verified on Prod.
