### ISSUE TITLE
Search field contain + sign for spaces when redirect

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#411]
Expected behavior

- The "+" sign must not be available in search field.

Actual behavior

- The "+" sign button is displayed in field.

Steps to reproduce the problem

- Login into application as connect user role.

- Complete search field with text "Hello nyet".

- Press enter to perform search.

- New Project.

- Complete required fields and save.

- Observe the search text set in field.

Environment
- OS: Windows 7
- Browser (w/version): IE 11.0, Mozilla Firefox 49.0.1, Chrome 49.0.2623.112 m
- User role (client, copilot or manager): copilot
- Account used: christina_uw

see attach!

![plus-sign](https://cloud.githubusercontent.com/assets/5114907/19015014/3f755e28-8804-11e6-95e5-6bf6d1fdb916.png)

**Comment by mahestro** [comment]
Valid.
