### ISSUE TITLE
Login/Registration pages needs to be adapted for Connect

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4112]
With new Login/Registration flow for Connect, we have few updates needs to be done which arise due to the below use case -

1. Connect home page - user clicks on Login and then switches to registration from there, the regSource is lost in URL which means user will be redirected to community app upon successful activation 
2. Connect home page - user clicks for Registration and then switches for login page, the retURL is lost which means user will be landed to community page upon successful login.

Fyi - @mtwomey

**Comment by RishiRajSahu** [comment]
@lakshmiathreya with new auth0 changes, Let's verify this one also.

**Comment by lakshmiathreya** [comment]
-- Verified that new User registration and activation via Login and Start Project routes redirect successfully to Connect Home page. 
-- Also, verified the new User is set with default Business role. 

@RishiRajSahu - on the Connect home page - both the 'Login' and 'Start Project' buttons have the same url: https://accounts-auth0.topcoder-dev.com/?regSource=tcBusiness&retUrl=https://connect-test01.topcoder-dev.com/. Please clarify what you mean by switching from Registration to Login and vice versa?

**Comment by RishiRajSahu** [comment]
@lakshmiathreya earlier we had different pages for both signup and login with different url, and we had signup page link on login page and login page link on signup page, so regSource was getting lost when switching between pages via those link.
with new dialog, we have common url for both signup/login and then dialog has tabs to switch between these options and url remains intact so as per me we are good with this.
