### ISSUE TITLE
Add all manager roles for visibility of navigation links

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4113]
Currently only limited set of managers are able to view the navigation links(direct, sfdc, WM). Need to add all manager roles to be able to see these links.

fyi @lakshmiathreya

**Comment by RishiRajSahu** [comment]
@lakshmiathreya with new single manager role these links should be visible to all managers.

**Comment by lakshmiathreya** [comment]
yes @RishiRajSahu since all members of Manager team have to be assigned an additional Connect Manager role - visibility of navigation links is available for all members.

**Comment by lakshmiathreya** [comment]
https://github.com/appirio-tech/connect-app/issues/4101

**Comment by lakshmiathreya** [comment]
Verified on Prod: Manager Roles have visibility once they are additionally set with Connect manager role.
<img width="1639" alt="Screenshot 2020-09-29 at 5 34 45 PM" src="https://user-images.githubusercontent.com/51733042/94556032-1cf4c100-027a-11eb-9afd-18263b2edbdd.png">
