### ISSUE TITLE
New Intake Form: Beacon

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4129]
### Context
A new project solution intake form needs to be created for Data Science.

### Catalog: Pathway, Copy Content, Visibility
**Display Pathway:** + New Project > + Solution > Data Science Section
**Title:** Beacon
**Catalog Description:** Get your problem unstuck, de-risked, and solved to exacting standards with this wayfinding solution. First, we bring your early-stage, thorny problems and tap into direct feedback from Topcoder crowd experts to define your problem statement, identify performance metrics, and estimate solution performance. Then, a bounty-driven, pay-for-performance competition is launched to produce the results you need without unnecessary risks.
**Catalog Expected Deliverables:**
- Report of crowd-generated recommendations
- Tested algorithm/model or application that meets performance criteria
- Analysis and documentation for winning solution
**Form Visibility:** Catalog/form can be viewed by all registered users.

### Intake Form
**Objective Flags:** No changes.

**Intro**
- Name your project: [Free Text Field]
- What are the objectives of your data science project?: [Free Text Response]
- Reference Code: [Free Text Response]

**Main Body**
- **Question 1:** Describe the problem’s background.  What ambiguities or sticking points do you need resolved?
- **Question 1, Answer 1 Format:** [Free Text Response]

- **Question 2:** Are there academic papers or other sources that should be considered as inputs for your project?
- **Question 2, Answer 1 Format:** [Yes/No Toggle Button], defaulted to No.
- **Question 2, Answer 2 Format:** If “Yes” is selected, display a [Free Text Response] field with this text displayed over the field: “Please list source URLs”

- **Question 3:** Describe the relevant data (format/structure) you can share with crowd participants.
- **Question 3, Answer 1 Format:** [Free Text Response]

- **Question 4:** What is the approximate best fit for your data set size?  
- **Question 4, Answer 1 Format:** [Radio Buttons]
-Less than 100MB
-100MB - 10GB
-10GB - 50GB
-More than 50GB
-More than 1TB

- **Question 5:** Where is your data located?  
- **Question 5, Sub-Text:** Please provide URLs, if possible.
- **Question 5, Answer 1 Format:** [Free Text Response]

- **Question 6:** Is your data licensed, subject to any patent, export or treaty restrictions, or are there other roadblocks of which Topcoder should be aware?
- **Question 6, Answer 1 Format:** [Yes/No Toggle Button], defaulted to No.
- **Question 6, Answer 2 Format:** If Yes is selected, display [Free Text Entry] field.

- **Question 7.A:** Approximately what percent of your data is labeled?  
- **Question 7.A, Answer 1 Format:** [Radio Buttons]
-0%
-10%
-20%
-30%
-40%
-50%
-60%
-70%
-80%
-90%
-100%

_Note: Only display Question 7.B if the user selected any answer option other than “100%” in Question 7.A._
- **Question 7.B:** Can Topcoder help label your data?
- **Question 7.B, Answer 1 Format:** [Yes/No Toggle Button], defaulted to Yes.

- **Question 8.A:** Solutions are delivered as command line programs.  Will you need your output to be further prepared for production use?
- **Question 8.A, Answer 1 Format:** [Radio Buttons]
-Yes, I will need results fitted with a GUI, deployed as an API, etc. 
-No, I will work with the command line results.

_Note: Only display Question 8.B if the user selected “Yes, I will need results fitted with a GUI, deployed as an API, etc.” in Question 8.A._
- **Question 8.B:** Describe how you will interact with and deploy your results.
- **Question 8.B, Answer 1 Format:** [Free Text Entry]

- **Question 9:** Please provide any additional notes/context you believe is important for us to know. 
- **Question 9, Answer 1 Format:** [Free Text Entry]

**Comment by RiteshTC** [comment]
@acshields 
This form has been created and is available in dev for review.
<img width="1198" alt="Beacon" src="https://user-images.githubusercontent.com/5771673/97000538-7936c200-1554-11eb-8de2-129dde3c21a9.png">
