### ISSUE TITLE
"Work project" must be --> "Work Project". 'p' must be capitalized to be consistent with the other labels

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#413]
### Expected behavior
-----------------------------------------------------------------
"Work project" must be --> "Work Project". 'p' must be capitalized to be consistent with the other labels

### Actual behavior
-----------------------------------------------------------------
"Work project"

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click FILTER
- Project Type: Work Project
- Status: Cancelled
- Check the 'Work project' label

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_21-02-28](https://cloud.githubusercontent.com/assets/4592712/19015073/6d348cd8-881a-11e6-9d43-9042f61d5ac4.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
Valid to file this as a bug, but I like keeping sentence case for the labels in the listing.
