### ISSUE TITLE
Console error on all pages of Connect app [Auth0]

### ISSUE THREAD

**Issue by sandhiyakavi** [appirio-tech/connect-app#4133]
Description:
Getting fav icon console error on all page of the Connect app https://connect-auth0.topcoder-dev.com/

Screenshot:

![image (4)](https://user-images.githubusercontent.com/55895538/94247852-ab0a3800-ff58-11ea-841c-61993215cdf1.png)

It doesn't happen in dev Env https://connect.topcoder-dev.com/

![image (5)](https://user-images.githubusercontent.com/55895538/94247981-d2f99b80-ff58-11ea-9d1f-15a6791e15fa.png)

**Comment by lakshmiathreya** [comment]
cc @RishiRajSahu

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi as discussed, this is due to new side-testing env. Please verify on https://connect.topcoder-dev.com and close this issue.

**Comment by sandhiyakavi** [comment]
Verified. Error is not displayed.

![image](https://user-images.githubusercontent.com/55895538/96431607-b8a49c00-123e-11eb-90aa-b7c7e0b8e069.png)
