### ISSUE TITLE
Remove need of user being required to be Connect Manager

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4135]
- As Connect Manager user role has higher privileges we would need to remove the requirement of this role, and user with any valid Topcoder user role could be invited to project as manager with project level manager role.

- We would need to filter permissions also on backend, i.e. allow only Connect Manager user role to have `read:all_projects` permissions.

FYI - @acshields @vikasrohit

**Comment by maxceem** [comment]
@RishiRajSahu got some questions during code reviewing:

1. Currently, all the users with **Topcoder Roles** `Connect Account Manager` and `Business Development Representative` would get notifications about new projects created and projects move to `reviewed` status even if such users are NOT members of the project.

   After this task is done, such users would lose permission to view the projects if they don't have `Connect Manager` role. Should we change anything here? Or we can always expect that such users have both roles `Connect Account Manager`  + `Connect Manager` or `Business Development Representative` + `Connect Manager`?

2. `Connect Copilot Manager` users should be able to manage copilots for projects even without joining. After this task is done, they would also loose permissions to view the projects if they don't have `Connect Manager` role too. Should we do anything about this, or we can always expect `Connect Copilot Manager` users to also have `Connect Manager` role?

    Also, `Connect Copilot Manager` users get notifications when an invite is `requested` or `rejected` even when they are not the members of the project.

**Comment by RishiRajSahu** [comment]
@maxceem yep they should have `Connect Manager` roles to see the project/all-projects.

**Comment by maxceem** [comment]
Done via https://github.com/topcoder-platform/tc-project-service/pull/586.

This can be deployed without any changes in the client-side and should work well.

**Comment by lakshmiathreya** [comment]
@RishiRajSahu - is Connect Mgr role mandatory for Project Mgr role addition?
<img width="1153" alt="Screenshot 2020-11-02 at 7 03 26 PM" src="https://user-images.githubusercontent.com/51733042/97874223-b06c5680-1d3e-11eb-8012-398cc08b48fe.png">
<img width="1218" alt="Screenshot 2020-11-02 at 7 03 40 PM" src="https://user-images.githubusercontent.com/51733042/97874231-b5c9a100-1d3e-11eb-948f-c1de65084895.png">

**Comment by lakshmiathreya** [comment]
Addition worked after Connect Mgr role was added:
<img width="1680" alt="Screenshot 2020-11-02 at 7 22 12 PM" src="https://user-images.githubusercontent.com/51733042/97875712-d2ff6f00-1d40-11eb-9be8-2ebf54bcad47.png">
<img width="1680" alt="Screenshot 2020-11-02 at 7 22 19 PM" src="https://user-images.githubusercontent.com/51733042/97875767-e6123f00-1d40-11eb-8070-20197348c729.png">

**Comment by maxceem** [comment]
@lakshmiathreya we **should** be able to invite any kind of manager user without `Connect Manager` role to the Topcoder Team. It doesn't work yet, because the fix for this issue is not deployed yet.

@RishiRajSahu FYI, the fix for this issue is not yet merged to `dev` https://github.com/topcoder-platform/tc-project-service/pull/586/files

**Comment by RishiRajSahu** [comment]
@maxceem yep, I didn't merged intentionally but seems wrong feature branch is deployed by me. Deploying the correct feature now.
@lakshmiathreya should be in deployed in couple of minutes.

**Comment by lakshmiathreya** [comment]
-- Verified that all TC Roles can now be invited without need for addition of Connect Manager role to them.
-- This leads to Copilot Manager role becoming redundant - will log that as a new issue.
