### ISSUE TITLE
Connect home page not opening on mobile browser

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4137]
Below are the details for Safari browser
![Screenshot 2020-09-29 at 3 53 11 PM](https://user-images.githubusercontent.com/11248478/94546991-46a6eb80-026c-11eb-84b7-cb9148c2267f.png)
![Screenshot 2020-09-29 at 3 52 53 PM](https://user-images.githubusercontent.com/11248478/94547005-4b6b9f80-026c-11eb-818e-5fe9b47473cc.png)

**Comment by RishiRajSahu** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
@RishiRajSahu fixed as a hotfix:
- DEV https://github.com/appirio-tech/connect-app/pull/4138
- PROD https://github.com/appirio-tech/connect-app/pull/4139
