### ISSUE TITLE
No RESET button to reset the filter and Search data

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#414]
### Expected behavior
-----------------------------------------------------------------
Need to have a RESET button to reset the filter and Search data

### Actual behavior
-----------------------------------------------------------------
No RESET button to reset the filter and Search data

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Search the text 'Project'
- Click FILTER
- Project Type: App Development
- Status: Completed
- User needs to first clear the search text and then reset the 'Project Type' and 'Status' filters manually

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_21-09-51](https://cloud.githubusercontent.com/assets/4592712/19015116/7204a8aa-881b-11e6-9b64-97bb33a1b1a1.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment]
It's expected. Not a bug.
