### ISSUE TITLE
Hide Work Manager Hyperlink in Prod for All Users

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4140]
@RishiRajSahu - please hide the "Work Manager" (hyperlink in project left sidebar) for all users in Production for now, until we are able to release Work Manager.

**Comment by lakshmiathreya** [comment]
Verified in Prod:
<img width="1666" alt="Screenshot 2020-09-30 at 4 42 17 PM" src="https://user-images.githubusercontent.com/51733042/94678655-758c9280-033c-11eb-8ccc-f784cbdf4bc8.png">
<img width="1679" alt="Screenshot 2020-09-30 at 4 43 48 PM" src="https://user-images.githubusercontent.com/51733042/94678670-7ae9dd00-033c-11eb-87bf-9f0780db42d6.png">
<img width="1663" alt="Screenshot 2020-09-30 at 4 44 23 PM" src="https://user-images.githubusercontent.com/51733042/94678675-7cb3a080-033c-11eb-8244-d979a0519338.png">
