### ISSUE TITLE
Can't update profile

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#4141]
### Expected behavior
Should be able to update the profile

### Actual behavior
Can't update the profile - 'Invalid country' error message appears

### Steps to reproduce the problem
Open any project - update profile popup appears. Enter all the data and click save. Problematic field is the country name `Bosnia and Hercegovina` - some tc services use the name `Bosnia and Hercegowina` (with w instead of v) so that might be the reason

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/3051646/94605438-67396a80-0299-11eb-9f0e-8af10278da8f.png)

--

**Comment by gondzo** [comment]
aparently the country name in member service is `Bosnia & Herzegowina` - I changed it manually and don't get this popup anymore - hope it doesn't cause any further issues with connect

**Comment by acshields** [comment]
@maxceem @RishiRajSahu - can this be resolved before 1/15?

**Comment by maxceem** [comment]
@gondzo I've tried to set the country `Bosnia and Hercegovina` (with `v`) in Connect UI and it works good for me:

![image](https://user-images.githubusercontent.com/146016/103515518-8981ec00-4e77-11eb-834b-87ddadc5c20b.png)

As I understand the issue happened to you was like this:
- Some TC service set country to `Bosnia & Herzegowina` (with `w`) for you.
- When you tried to update other profile fields in Connect it sent already defined value for country `Bosnia & Herzegowina` (with `w`) but Member Service doesn't accept it.
- So if I understand it correctly, we cannot fix this issue in Connect. If some service sets some invalid value for your profile that is not accepted by Member Service Connect cannot automatically fix such values when saving data. 

Please, let me know if my understanding is correct or issue that happened to you was different and you think we can fix it in Connect somehow.
