### ISSUE TITLE
auth0: Not able to open the Project detail page directly through url 

### ISSUE THREAD

**Issue by sandhiyakavi** [appirio-tech/connect-app#4144]
Description:
 1. Without logging in ,Go to the project detail page.(https://connect-auth0.topcoder-dev.com/projects/8655)
2. Enter credentials in the Login pop up and click login button.
3. The main Dashboard page is displayed instead of the particular project detail page.
4. Again try to access the project detail page.

Expected result:
1. If the user entered the project detail url (https://connect-auth0.topcoder-dev.com/projects/8655), after login user should land on the same project detail page.
2. After login also user should be able to access the project detail page through url .

[Dev_accessprojectdetailpage_fails.zip](https://github.com/appirio-tech/connect-app/files/5305092/Dev_accessprojectdetailpage_fails.zip)
[Prod_accessing_projectdetailpage.zip](https://github.com/appirio-tech/connect-app/files/5305097/Prod_accessing_projectdetailpage.zip)

**Comment by sandhiyakavi** [comment]
cc: @sachin-maheshwari @lakshmiathreya

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi this is also side-testing env specific issue. Please verify on our regular env i.e https://connect.topcoder-dev.com and close this.

**Comment by sandhiyakavi** [comment]
Verified. Working as expected.

[Connect_projectdetails.zip](https://github.com/appirio-tech/connect-app/files/5401054/Connect_projectdetails.zip)
