### ISSUE TITLE
BDR role should always see Salesforce Lead link

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4145]
### Expected behavior
If a user is viewing a project in connect and they have the "Business Develop Representative" role, they should always see the "Salesforce Lead" link in the sidebar without needing to join the project.

![image](https://user-images.githubusercontent.com/3812270/94951993-37fe4580-04b3-11eb-9776-3cb3bec09b4e.png)

**Comment by ajefts** [comment]
fyi @acshields

**Comment by maxceem** [comment]
@RishiRajSahu according to this task https://github.com/appirio-tech/connect-app/issues/4135 only `Connect Manager` users could see projects without joining. 

Does it mean that in order for `Business Develop Representative` to see the project with "Salesforce Lead" such a user should have both roles `Connect Manager` and `Business Develop Representative`?

**Comment by lakshmiathreya** [comment]
@RishiRajSahu @acshields - whats the resolution for this?

**Comment by RishiRajSahu** [comment]
@lakshmiathreya the BDR should have connect manager role, if he wants to see the project's data without joining.

**Comment by RishiRajSahu** [comment]
As per our last discussion, as @acshields mentioned we need to show direct/salesforce link to all TC users.

**Comment by maxceem** [comment]
This is already implemented this way:
- all members of the **Topcoder Team** can see these links
- `Connect Manager` and admins can see these links without joining the project
- copilots also can see these links
- customers **cannot** see these links

@RishiRajSahu please, let me know if the current behavior is desired or there are any changes to make?

**Comment by acshields** [comment]
@maxceem - when you are saying "Topcoder Team," are you meaning the user roles like:
-Account Executive
-Account Representative/Business Development Representative (can't remember the title)
-Program Manager
-Project Manager
...etc.

Essentially, all of our users should see this link except for Clients.

**Comment by maxceem** [comment]
yes, @acshields I mean the roles you've mention above. Anyone who can be a part of Topcoder Team:

![image](https://user-images.githubusercontent.com/146016/99803970-f1d47280-2b42-11eb-9afa-6e5e94bc65fb.png)

> Essentially, all of our users should see this link except for Clients.

This is exactly as it's done now.

**Comment by acshields** [comment]
@maxceem - awesome, then that should be good.

**Comment by maxceem** [comment]
Resolution:
- Not fix needed here
- user should have role Connect Manager role to see a project without joining according to https://github.com/appirio-tech/connect-app/issues/4135
   - so BDR role is not enough to see a project without joining
- role `Connect Manager` is already enough to see saleseforce link
  - so at the end, BDR role doesn't add more privileges. If we need a user to see salaseforce link without joining such user should have `Connect Manager` and that's all

FYI @lakshmiathreya @ajefts

**Comment by drasticdpk** [comment]
@maxceem , 

For BDR (After Joining the project)

![image](https://user-images.githubusercontent.com/25297859/103010433-778f7780-4560-11eb-9b4e-2ec1faef838e.png)


For  **Connect Manger**  Role

![image](https://user-images.githubusercontent.com/25297859/103009753-5bd7a180-455f-11eb-9ddc-3695bcf5d00b.png)

![image](https://user-images.githubusercontent.com/25297859/103009949-9e00e300-455f-11eb-8cb4-d2e5fc3d4baf.png)


**For Customer Role**

![image](https://user-images.githubusercontent.com/25297859/103010069-ca1c6400-455f-11eb-8662-5d3d8838f44e.png)

**Comment by drasticdpk** [comment]
**Prod Verification**
I am testing this scenario with copilot acc too.
![image](https://user-images.githubusercontent.com/25297859/103524929-7df9e980-4ea6-11eb-97bd-0c9c48d668bf.png)
