### ISSUE TITLE
Clicking on empty locations will load the project details page

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#415]
### Expected behavior
-----------------------------------------------------------------
Must load only; when user click on the project name

### Actual behavior
-----------------------------------------------------------------
Clicking on empty locations will load the project details page

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on the marked area of the screenshot

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_21-27-41](https://cloud.githubusercontent.com/assets/4592712/19015221/fb2cb8a0-881d-11e6-87b5-92f23bda640c.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
Not valid: by design the whole area should load the project, not only the title.
