### ISSUE TITLE
Client Profile: New Required Field - "Acknowledge Topcoder Terms"

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4154]
### Update 1
Add a new required field to the client user profile, which requires them to accept or decline Topcoder's client terms. When the client's response to this required field is captured, the data should also be date-stamped.

### Update 2
This new required field should be presented as follows to the client user:
**Field Label:** Topcoder Terms
_Note: "Topcoder Terms" should be displayed as a hyperlink, which when clicked opens this page: https://connect.topcoder.com/terms_
**Two Buttons**: [Accept] and [Decline]

### Update 3
This new required field should be included in both progressive profile completion scenarios
- During the project intake scenario
- During the "clicked into" project scenario
No changes to the existing progressive profile completion behavior are needed, outside of the inclusion of this field as a new required field.

**Comment by RishiRajSahu** [comment]
The change would require new attribute being added to connect_traits in member-service.

**Comment by maxceem** [comment]
Once the client selected "Accept" or "Decline" can he open profile settings and change his decision?

**Comment by RishiRajSahu** [comment]
@maxceem its once acceptable and readonly henceforth.

**Comment by maxceem** [comment]
@RishiRajSahu then the task looks clear. As soon we have a place in [connect-traits](https://github.com/appirio-tech/ap-member-microservice/blob/dev/service/src/main/java/com/appirio/service/member/api/MemberProfileConnectInfo.java) to save the value, we can do this.

**Comment by maxceem** [comment]
@RishiRajSahu this is done via 2 PRs:
- React Components https://github.com/appirio-tech/react-components/pull/360 - should be merged first
- Connect App https://github.com/appirio-tech/connect-app/pull/4185

**Comment by maxceem** [comment]
### @QA quidelines

1. Using customer user, when we open any project, we have to see Incomplete Profile where we can accept/reject terms. **Accept** terms and click save. This incomplete dialog shouldn't be shown anymore on project loading.
   - After accepting, if we go to the user profile page, we should see that terms are marked as `accepted`.
2. The same like above, but this time we should `reject` terms during progressive registration. We would need another user for this test, as we can only accept/reject terms once per user.
3. Using another customer user we can open user use profile settings page and accept or reject user terms and click "save". After that we cannot change our decision.
4. Other non-customer users should see Topcoder Terms field.

**Comment by maxceem** [comment]
This is ready for testing in TEST01 environment https://connect-test01.topcoder-dev.com/settings/profile.

**Comment by lakshmiathreya** [comment]
> ### QA quidelines
> 1. Using customer user, when we open any project, we have to see Incomplete Profile where we can accept/reject terms. **Accept** terms and click save. This incomplete dialog shouldn't be shown anymore on project loading.
>    
>    * After accepting, if we go to the user profile page, we should see that terms are marked as `accepted`.
> 2. The same like above, but this time we should `reject` terms during progressive registration. We would need another user for this test, as we can only accept/reject terms once per user.
> 3. Using another customer user we can open user use profile settings page and accept or reject user terms and click "save". After that we cannot change our decision.
> 4. Other non-customer users should see Topcoder Terms field.

Verified 1., 2., 3. In item 4 above - @maxceem I believe you mean non customer user _should not_ see Topcoder Terms field? It is not seen currently for such users.

**Comment by lakshmiathreya** [comment]
Regarding the terms link - has this requirement changed? This link is not seen on the Profile page. @maxceem please clarify.

**Comment by lakshmiathreya** [comment]
'Topcoder Terms' is hyperlinked to the Terms page. Clicking that opens a new tab as expected.

**Comment by maxceem** [comment]
> @maxceem I believe you mean non customer user should not see Topcoder Terms field? It is not seen currently for such users.

right, @lakshmiathreya I meant `should NOT see`.

**Comment by lakshmiathreya** [comment]
Terms field not visible in Prod.
![Uploading Screenshot 2020-11-17 at 11.43.10 AM.png…]()

**Comment by maxceem** [comment]
Also, there is some issue with CSS on PROD, for some reason, it's not updated for me, so styles got slightly broken on PROD:
![image](https://user-images.githubusercontent.com/146016/99388037-a0777980-28dd-11eb-8330-cb1dd5156565.png)

**Comment by lakshmiathreya** [comment]
Terms verified on Prod.
![Uploading Screenshot 2020-12-01 at 2.52.41 PM.png…]()

**Comment by lakshmiathreya** [comment]
In Progressive Registration, Terms field is not fully visible.
<img width="1680" alt="Screenshot 2020-12-01 at 4 26 53 PM" src="https://user-images.githubusercontent.com/51733042/100732803-45707700-33f3-11eb-8400-256182920d23.png">

**Comment by lakshmiathreya** [comment]
Will log a different P4 for scrolling issues in rare cases. Verified that Terms field is visible and is updated correctly.
