### ISSUE TITLE
All Intake Form Update: Update Topcoder Employee Objective Flag [Submitting Client Request] Behavior

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4156]
### Update 1
Projects App should consume "client account name" (i.e. company name) data from SFDC.

### Update 2
Update the Topcoder Employee objective flag response for [Submitting Client Request] on all intake forms to follow this workflow:

1. Topcoder Employee sees "Why are you submitting this request?" question
2. Topcoder Employee selects "Submitting Client Request"
3. Topcoder Employee is asked "Is this a new or existing client?" and sees these answer options: [New Client] [Existing Client]

If the Topcoder Employee selects "New Client," they are asked the following: "Select the client account name, or select 'no account created yet'" The Topcoder Employee can then:
- Search in a dropdown menu with responsive text entry and select the matching client account name
- Click a checkbox that reads "Client account has not been created yet"

If the Topcoder Employee selects "Existing Client," they are asked the following: "Select the client account name." The Topcoder Employee can then:
- Search in a dropdown menu with responsive text entry and select the matching client account name

**Note: Copilots should still see the "Submitting Client Request" answer option, but they should not see any of the subsequent questions related to the client account name.**

### Update 3
These Topcoder Employee responses should be included as a part of the project intake event data, which can be consumed by SFDC.

**Comment by RishiRajSahu** [comment]
@acshields I'm not sure how we are gonna get the client names list, do we have to depend upon some other service call for the same ? 
rest seems doable.

**Comment by acshields** [comment]
@RishiRajSahu - I think you will need to talk to Sumit on this. I know that the data is available in SFDC, but what I don't know is how we can it from there.
