### ISSUE TITLE
Title is displayed as 'Welcome to undefined'

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4157]
![image](https://user-images.githubusercontent.com/42398485/96687898-24514b00-139e-11eb-95b2-af0c8a484f16.png)

### Steps to reproduce the problem

- Login as Normal Account
- Go to a Project - https://connect.topcoder-dev.com/projects/16653
- Click 'Manage Invitations' from the Customer team
- Add `codejamdev1` > Send Invitations
- Click `Decline` from the email
- Click `Join Project` from the email

### Actual behavior
- Title is displayed as 'Welcome to undefined'

### Expected behavior
- Should display the title properly

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 86.0.4240.111
**- User role (client, copilot or manager):** Normal Account
**- Account used:**  `codejamdev1`

**Comment by lakshmiathreya** [comment]
![Uploading Screenshot 2020-11-09 at 9.22.20 AM.png…]()

**Comment by lakshmiathreya** [comment]
Happening at first login after new registration ... @maxceem need to fix this pls ...

**Comment by maxceem** [comment]
This is fixed by https://github.com/appirio-tech/connect-app/commit/9c832e74b68f8468cf3facf921058564461cf8c3.

Solution: don't show profile incomplete dialog if the user cannot load the project.

**Comment by RishiRajSahu** [comment]
from Slack - 

> It was happening because the dialog was shown without waiting for the project to be loaded. So if user doesn't have access to the project the dialog still shown, but we cannot load project to show the project title.
> we are waiting for project to be loaded and show this dialog only if user has access to the project

fyi @maxceem
