### ISSUE TITLE
'ANALYTICS & DATA SCIENCE' button is partially hidden

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4159]
![image](https://user-images.githubusercontent.com/42398485/96706490-4786f500-13b4-11eb-852c-d983e06ce2f9.png)

### Steps to reproduce the problem

- Login as Manager
- Go to a Project listing and Click +
- Check 'ANALYTICS & DATA SCIENCE'

### Actual behavior
- 'ANALYTICS & DATA SCIENCE' button is partially hidden

### Expected behavior
- Should display properly

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 86.0.4240.111
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by RishiRajSahu** [comment]
that was transient issue of dev.
