### ISSUE TITLE
When user change the pagination; page won't focus on the first row of the table

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#416]
### Expected behavior
-----------------------------------------------------------------
When user change the pagination; page must focus on the first row of the table

### Actual behavior
-----------------------------------------------------------------
When user change the pagination; page won't focus on the first row of the table

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- In the FILTER
- Project Type: App Development
- Status: Draft
- Now In the 3rd column Set: Latest First
- Scroll down and go to the 2nd in the pagination

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_21-36-32](https://cloud.githubusercontent.com/assets/4592712/19015298/2ccb9e70-881f-11e6-9c54-e54e7cfb3670.png)

http://screencast.com/t/SGiqt2X4ig

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Known-related #148
