### ISSUE TITLE
Error while creating an 'ANALYTICS & DATA SCIENCE' project

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4160]
![image](https://user-images.githubusercontent.com/42398485/96706785-a8aec880-13b4-11eb-952b-1bf4176f6b1e.png)

### Steps to reproduce the problem

- Login as Manager
- Go to a Project listing and Click +
- Select 'ANALYTICS & DATA SCIENCE'
- Enter the name as 'ANALYTICS & DATA SCIENCE' and then fill all the mandatory data
- Click create

```
Failed to load resource: the server responded with a status of 400 ()
15:45:37.185 main.41da3a3e7ebcb91c4288.js:130 Uncaught (in promise) Error: Request failed with status code 400
    at e.exports (main.41da3a3e7ebcb91c4288.js:130)
    at e.exports (main.41da3a3e7ebcb91c4288.js:231)
    at XMLHttpRequest.f.onreadystatechange (main.41da3a3e7ebcb91c4288.js:130)
```

### Actual behavior
- Error while creating an 'ANALYTICS & DATA SCIENCE' project

### Expected behavior
- Should display an error
#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 86.0.4240.111
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by RishiRajSahu** [comment]
@codejamtc this was intake form under development and this must be happening on dev env.
I don't know how it fall as part of testing for you ?
