### ISSUE TITLE
Project Plan: Image Display Prior to Plan Set-Up

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4164]
### Client Display
Prior to any phases being set-up, these users should see the following on the project's dashboard tab:
Screen X: Icon Image
- The header text on the icon should read: "Your Project Plan Is Being Built"
- The sub-header text on the icon should read: "Here you will see your delivery timeline and milestones"

_Note: The client does not see the [Build Project Plan] or [Launch Work] buttons._

**Comment by RishiRajSahu** [comment]
@acshields seems we just need to remove the text message we currently show and put an new image which we will be getting via design.
