### ISSUE TITLE
Login page is not loading

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#4171]
![image](https://user-images.githubusercontent.com/42398485/97135214-b4640b80-1775-11eb-806a-7bb6f873ac69.png)

### Steps to reproduce the problem

- Open the URL https://accounts-auth0.topcoder.com/?retUrl=https://connect.topcoder.com
- Observe

### Actual behavior
- Login page is not loading

### Expected behavior
- Should display an error

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome IE11

**Comment by sachin-maheshwari** [comment]
@codejamtc can you please check if connect-app is working on IE (with current flow) ?

**Comment by sachin-maheshwari** [comment]
@codejamtc please move it tc-auth-lib, not related to connect-app.

**Comment by codejamtc** [comment]
@sachin-maheshwari Sure
