### ISSUE TITLE
QA for RabbitMQ removal from projects api

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#4172]
We recently removed the RabbitMQ as event bus from projects api which was using it for some use cases and we haven't touched it at the time of v5 migration to prevent too much changes and regressions. We have now implemented the same under the issue https://github.com/topcoder-platform/tc-project-service/issues/584. Purpose of this issue is to do some regression testing around the potential application use cases which can get affected because of these changes.

**Comment by vikasrohit** [comment]
@maxceem can you please add some guideline for QA?

**Comment by maxceem** [comment]
### QA Guidelines

- In general, everything should work as before in the Connect App, as we did internal refactoring which should not change any functionality. Below I would describe tests cases in the areas where we did the most changes in the code.
- The **Last Updated Date** ([screenshot](https://monosnap.com/file/T5rJwV2GsqH2hkeM4RBQ3PTEVhY3P3)) should get updated when we:
   - update project specification
   - add/update/remove attachment (enough to test with either link or file)
   - add/remove a member
   - add/update/remove phase
   - create/update thread
   - create/update post
- When we create a new phase there should always be a CoderBot post:

   ![image](https://user-images.githubusercontent.com/146016/97169243-68738f80-1792-11eb-82e7-dfecf3ee940c.png)

- When we complete all the milestones inside the phase, the phase status should be changed to "Delivered". This can be tested by adding "Development Iteration (3 Milestones)" phase (many other phase templates are broken).

    ![image](https://user-images.githubusercontent.com/146016/97169825-63fba680-1793-11eb-8be7-693a21b4eea2.png)

**Comment by lakshmiathreya** [comment]
Verified The Last Updated Dates for:
-- update project specification
-- add/update/remove attachment (enough to test with either link or file)
-- add/remove a member
-- add/update/remove phase
-- create/update thread
-- create/update post
Verified CoderBot post for new phase addition
Verified Phase Status changing to 'Delivered'
Smoke test completed

**Comment by vikasrohit** [comment]
Thanks for the confirmation @lakshmiathreya
