### ISSUE TITLE
Reload of certain pages results in error

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4173]
Reload of the same page works in Prod but is broken in Staging:
<img width="1163" alt="Screenshot 2020-10-28 at 9 34 38 AM" src="https://user-images.githubusercontent.com/51733042/97390384-b7d8cd80-1902-11eb-85b5-e18be4f3ce42.png">
<img width="1146" alt="Screenshot 2020-10-28 at 9 34 46 AM" src="https://user-images.githubusercontent.com/51733042/97390389-bdceae80-1902-11eb-943d-7835da08c14c.png">

**Comment by lakshmiathreya** [comment]
cc @drasticdpk @SathyaJayabal @RishiRajSahu @nkumar-topcoder

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya That is not related to connect app, please try to understand. That is related to infra. I think you should close this issue. As this is temporary staging env, filing issue on that, doesn't make sense to me.

**Comment by lakshmiathreya** [comment]
@sachin-maheshwari we would like to make sure this wont happen on Prod - pls let us know who can fix this Infra issue.
