### ISSUE TITLE
Copilot Manager unable to Add Copilot to Project Team - Test Env

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4178]
<img width="1680" alt="Copilot Addition by Copilot Manager" src="https://user-images.githubusercontent.com/51733042/98086061-3950d280-1ea4-11eb-8a94-dcaf21c6af0c.png">

**Comment by maxceem** [comment]
Can confirm this issue, will fix it.

**Comment by lakshmiathreya** [comment]
User - TCConCopilotMgr:
<img width="1680" alt="Screenshot 2020-11-04 at 9 11 19 PM" src="https://user-images.githubusercontent.com/51733042/98132530-85bb0300-1ee2-11eb-8232-730ed3717ac9.png">
