### ISSUE TITLE
Copilot Manager doesnt receive Private post messages 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4179]
The notification is seen yet the message is not: user lakshmiacopmgr
<img width="1680" alt="Copilot mgr not seeing Priv Notification" src="https://user-images.githubusercontent.com/51733042/98219036-83a08500-1f72-11eb-9da3-b6a09bf525eb.png">

Here is the same message as seen by Connect Manager: user TCConManager
<img width="1680" alt="Screenshot 2020-11-05 at 2 24 50 PM" src="https://user-images.githubusercontent.com/51733042/98219198-b5b1e700-1f72-11eb-805b-814f671e27fb.png">

**Comment by maxceem** [comment]
@lakshmiathreya I cannot reproduce this issue. Could you please try one more time in case recent changes fixed it?

![image](https://user-images.githubusercontent.com/146016/98339288-25c47980-2014-11eb-9b5a-7995eadbe3b9.png)
