### ISSUE TITLE
Projects - ReactReconciler.js:64 Uncaught TypeError: Cannot read property 'getHostNode' of null

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#418]
Expected behavior

- Do not dislay this error message in console.

Actual behavior

- The error message is displayed in Developer Tool Console.

Steps to reproduce the problem

- Login into application as copilot role.

- Search the project name Proj 12(https://connectv2.topcoder-dev.com/projects/115).

- Edit the project.

- Go to App Definition.

- Select Projects text from the top left corner of screen(Projects / Proj 12).

- Open Developer Tools and check the server calls.

Environment
- OS: Windwos 7
- Browser (w/version): Chrome 49.0.2623.112 m
- User role (client, copilot or manager): copilot
- Account used: cp-superstar

see attach!

![error](https://cloud.githubusercontent.com/assets/5114907/19015389/33abd6fa-880c-11e6-83f5-2f8ae495db33.png)

**Comment by mahestro** [comment]
Known.
