### ISSUE TITLE
Users with Topcoder manager roles except of Connect Manager should not see projects by links

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4182]
### Expected behavior
Copilot Manager and other managers should not see projects by link without having Connect Manager role (when not a member).

### Actual behavior
Copilot Manager and other Topcoder managers can see project by link even without having Connect Manager role (when not a member).

### Steps to reproduce the problem
- Using user without `Connect Manger` role, but with some other Topcoder manager role like `Copilot Manager`, try accessing some project where you are NOT a member by the direct link, like https://connect-test01.topcoder-dev.com/projects/16530
- Project would be opened, but shouldn't.

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/146016/98340517-265e0f80-2016-11eb-8836-39b1aab867a9.png)

![image](https://user-images.githubusercontent.com/146016/98340576-3b3aa300-2016-11eb-8979-0d4e086e967c.png)

**Comment by maxceem** [comment]
This is fixed now by https://github.com/topcoder-platform/tc-project-service/commit/4f7dab193b52a85cc1e5719a671716e2d9841fdf:

![image](https://user-images.githubusercontent.com/146016/98346562-cddf4000-201e-11eb-8e6b-1660fdd95b3f.png)

**Comment by maxceem** [comment]
@lakshmiathreya this is ready for review.

**Comment by lakshmiathreya** [comment]
Verified that non Project Management team members (Copilot Manager and other TC Managers) are unable to see Projects via direct link. Only exceptions are Admin, Connect Admin and Connect Manager.
