### ISSUE TITLE
Removing Copilot from Project

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4183]
Update existing logic so that these users can remove a Copilot from a project, at any time:

- Admin
- Connect Admin
- Connect Manager
- Copilot Manager
- All Other TC Roles

**Comment by lakshmiathreya** [comment]
cc @maxceem

**Comment by maxceem** [comment]
I would recommend including it in the next release, as it would also require updating of the code of Project Service and it cannot be fixed just by changing permission config. Just to make sure that we have enough time for proper testing.

**Comment by RishiRajSahu** [comment]
@maxceem yep its for November release so we have enough time.

**Comment by RishiRajSahu** [comment]
@acshields additional info for above work
- show confirmation message before delete
- send notification to copilot about their removal ?

**Comment by acshields** [comment]
Also notes to updated behavior on the "remove" capability:

For any Topcoder Employee user who has visibility to a project, if a Copilot is on the project then:
- They should see the "Manage" button
- When clicked, they should see the pop-up window with the joined Copilot(s) names and should see a clickable "Remove" button next to their name.
- All users except the TC Copilot Managers should not see the "search handle/invite copilot" feature at the bottom of the pop-up window

**Comment by RishiRajSahu** [comment]
@acshields just for implementation clarity, 
We have to hide the invited members from all users except TC Copilot managers. 
TC Copilot managers would see both the invited/joined members.

**Comment by maxceem** [comment]
### QA Guidelines

Here are the main tests cases:
1. `Copilot Manager` should be able to invite copilots without joining a project (to see a project such user should also have `Connect Manager` role)
2. `Copilot Manager` should be able to remove copilots **invite** without joining a project
3. `Copilot Manager` should be able to remove copilot **member** without joining a project
4. Any member of **Topcoder Team** should be able to remove copilot **invite**
5. Any member of **Topcoder Team** should be able to remove copilot **member**
6. Copilots should **not** be able to remove other copilot **invites** or **members**
7. Customers should **not** be able to remove other copilot **invites** or **members**

**Comment by drasticdpk** [comment]
@maxceem , 
For point 1, I want to verify with **Copilot Manager** Role (topcoderconnect+copilotmanager@gmail.com), how can I check this user has  Connect Manager Role or not ?
If not, how can I add the new Role ?

**Comment by maxceem** [comment]
To check user role you may use https://jwt.io/
- Copy token from Dev Tools https://monosnap.com/file/MZSpX287ckmRrjirsGAgYLw3dWctKR.
- Paste it to https://jwt.io/ https://monosnap.com/file/ZwX5ecBfpc3efNfsOhy63zL1zEwFGA

You may use `pshah_manager` user for testing. It has `Connect Manager` role.

> If not, how can I add the new Role ?

You can ask Lakshmi, me or Rishi.

**Comment by lakshmiathreya** [comment]
topcoderconnect+copilotmanager@gmail.com doesn't have Connect Manager role.

**Comment by drasticdpk** [comment]
Thank you @maxceem @lakshmiathreya . 
sure for now I will use **pshah_manager** for testing purpose.

**Comment by lakshmiathreya** [comment]
pshah_manager is Connect Manager and Copilot ... not sure if this is a good user for testing ...

**Comment by drasticdpk** [comment]
**Verification**
1. **Customer**  
![image](https://user-images.githubusercontent.com/25297859/103073956-b0772d00-45f0-11eb-9d53-6de6bf949cfb.png)

2. **Admin** 
Can remove:

![image](https://user-images.githubusercontent.com/25297859/103074216-4448f900-45f1-11eb-8e65-ec624f2f10a6.png)

Copilot got the notification.
![image](https://user-images.githubusercontent.com/25297859/103074367-8c681b80-45f1-11eb-9fe6-792c88ff0c9b.png)

3.  **TCConAdmin**

![image](https://user-images.githubusercontent.com/25297859/103074935-ba9a2b00-45f2-11eb-9f62-a969512d71b8.png)

4. **TCConManager**

![image](https://user-images.githubusercontent.com/25297859/103075320-76f3f100-45f3-11eb-8e13-3254c1af31de.png)

4. **TCConCopilotMgr**
![image](https://user-images.githubusercontent.com/25297859/103075691-3648a780-45f4-11eb-96bb-c915e92bd453.png)

5. Verification for invited copilot ( i.e  not joined yet.)

![image](https://user-images.githubusercontent.com/25297859/103076234-5d53a900-45f5-11eb-8b47-fe425031afb9.png)

**Comment by drasticdpk** [comment]
> * All users except the TC Copilot Managers should not see the "search handle/invite copilot" feature at the bottom of the pop-up window

@maxceem still **Copilot Managers** able to see "search handle/invite copilot", please confirm.
**Reference** :
https://monosnap.com/file/TWZJkVAytj8JoMr0UbixN3WR9rIzW7

**Comment by maxceem** [comment]
@drasticdpk that's exactly what is needed, just other words ;-)

Sum up:
- **Copilot Managers** and admins **should** see "search handle/invite copilot"
- other users should **not** sse "search handle/invite copilot"

**Comment by drasticdpk** [comment]
Ok noted @maxceem
