### ISSUE TITLE
Internal Project Intake form error 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4184]
<img width="1680" alt="Screenshot 2020-11-10 at 11 21 44 AM" src="https://user-images.githubusercontent.com/51733042/98634054-a6eb7b80-2348-11eb-9e32-46b894b65995.png">

**Comment by RishiRajSahu** [comment]
@lakshmiathreya should be fixed, compare with prod to test.

**Comment by maxceem** [comment]
@RishiRajSahu this is done via 2 PRs:
- React Components https://github.com/appirio-tech/react-components/pull/360 - should be merged first
- Connect App https://github.com/appirio-tech/connect-app/pull/4185
