### ISSUE TITLE
Unable to add Phases to Project 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4187]
### Expected behavior
TC managers should be able to Add and Edit Project Phases.

### Actual behavior
The Addition and Edits appear to work but are not persisted.

Tried with brand new and old projects with multiple TC manager roles.

**Comment by lakshmiathreya** [comment]
cc @mtwomey @acshields

**Comment by maxceem** [comment]
We have to deploy an updated version of ES Processor to PROD https://github.com/topcoder-platform/project-processor-es/pull/51. Otherwise, phases are not added/updated in ES in PROD.

**Comment by lakshmiathreya** [comment]
@maxceem would you be deploying the updated ES processor now?

**Comment by maxceem** [comment]
@lakshmiathreya I don't have permissions to deploy on PROD. So we need the help of Vikas or Rishi.

**Comment by lakshmiathreya** [comment]
cc @vikasrohit can you help?

**Comment by lakshmiathreya** [comment]
cc @rootelement

**Comment by rootelement** [comment]
Merged, deploying.

**Comment by lakshmiathreya** [comment]
Phase addition working now in Prod. Thanks @maxceem and @jcori!
