### ISSUE TITLE
Sometimes 'Project Updated' message is display two instance

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#419]
### Expected behavior
-----------------------------------------------------------------
'Project Updated' message must display only one instance

### Actual behavior
-----------------------------------------------------------------
Sometimes 'Project Updated' message is display two instance

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Dashboard
- Add 10-15 Links
- Now click Delete and confirm
- Quickly click Delete and confirm again
- Quickly click Delete and confirm again
- Check the message: 'Project Updated'

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_22-07-48](https://cloud.githubusercontent.com/assets/4592712/19015507/8a9a6816-8823-11e6-9665-8ff66d825ec0.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
This is OK. Both actions are confirmed if they're done in quick succession.
