### ISSUE TITLE
Unregistered User - Invite email - Registration url redirects to old Accounts Registration page

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4191]
- Invite an unregistered user to a Project via their email.
- Login to the unregistered account. 
- Click on the Register button in the invite email.
- It redirects to the Old Account app page. 
<img width="1680" alt="Screenshot 2020-11-17 at 12 26 37 PM" src="https://user-images.githubusercontent.com/51733042/99382879-281bb300-28f3-11eb-9e21-a1eeff2a2eea.png">

- Should redirect to the Auth0 Registration page.

**Comment by lakshmiathreya** [comment]
On Prod, the Register link redirects to Dev Registration page.

<img width="1680" alt="Screenshot 2020-12-01 at 2 36 43 PM" src="https://user-images.githubusercontent.com/51733042/100719783-17833680-33e3-11eb-96b3-e0d54d4b219f.png">
<img width="1680" alt="Screenshot 2020-12-01 at 2 35 29 PM" src="https://user-images.githubusercontent.com/51733042/100719766-13efaf80-33e3-11eb-9385-a525e8657a27.png">
<img width="1680" alt="Screenshot 2020-12-01 at 2 35 03 PM" src="https://user-images.githubusercontent.com/51733042/100719732-0afede00-33e3-11eb-98c2-1e09de7d040c.png">

**Comment by RishiRajSahu** [comment]
@lakshmiathreya should be fixed now.

**Comment by lakshmiathreya** [comment]
Verified on Prod - redirect to Prod Auth and Connect working fine.
