### ISSUE TITLE
TaaS Project Redirect

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4195]
Until the new micro front-end architecture is fully implemented, created TaaS projects will display in the Projects App (connect.topcoder.com) all projects dashboard list. Users will need to be redirected from here to the TaaS App version of the project.

### Updates
When a TaaS (type = TaaS, "Engage Talent" intake form) project is created, the user should see the following in the Projects App (connect.topcoder.com) all projects dashboard list:
- Project ID
- Project Icon
- Project Name
- REF Code (If Available)
- Project Status
- A button that reads "View Project"
- When clicked the TaaS App version of the project should open in a new tab.

The following data does not need to be displayed for these projects:
- Last Updated
- Customer (Team)
- Topcoder (Team)

**Comment by wdprice** [comment]
@acshields - suggest moving the button from the dashboard/list page to the project view page (maybe in place of milestones?)

Reasoning is that project access controls are currently handled in Connect, and if we want to add/remove users we need to be able to get to that screen still.

**Comment by acshields** [comment]
@wdprice @RishiRajSahu - Agreed on this approach. 

### revised requirements
1. Hide project plan on TaaS projects
2. On the dashboard tab of a project, where project plan would have been displayed, show a large button that reads: "Go to your Talent Team"

@wdprice - I am also thinking of other things within the project that we can hide/update, so as not to confuse the experience. My proposals:
- Hide Assets Library
- Hide FAQs (?): These FAQs are curated for TaaS right now, but would folks be coming here to look at them?
- Hide Reports (?): These reports are curated for TaaS right now, but would folks be coming here to look at them?
- Relabel "Scope" to "Talent Team Requests"

**Comment by maxceem** [comment]
Done as per https://github.com/appirio-tech/connect-app/issues/4195#issuecomment-738091407 in branch `feature/taas-jobs` now deployed to DEV env.

Example project link https://connect.topcoder-dev.com/projects/16716

Let me know if you would like to have any design improvements:

![image](https://user-images.githubusercontent.com/146016/101060236-dd0eca80-3597-11eb-85a1-94d3ccbe51a8.png)

**Comment by RishiRajSahu** [comment]
@maxceem that's great, I have tried quick changes as well for the same 
<img width="1439" alt="Screenshot 2020-12-03 at 10 20 20 PM" src="https://user-images.githubusercontent.com/11248478/101060868-e018b380-35b5-11eb-9dd1-919771e7ed6b.png">

Still @acshields confirmation is required.

**Comment by acshields** [comment]
Looks good - only change I could request: Can we make the button/text larger to take up more of the screen space (so there is less weird empty space?)

**Comment by maxceem** [comment]
What about this? See live demo https://connect.topcoder-dev.com/projects/16716

![image](https://user-images.githubusercontent.com/146016/101073334-f586e100-35a7-11eb-871a-3bee4b9c6bf1.png)

**Comment by acshields** [comment]
Works for me, thanks @maxceem

**Comment by maxceem** [comment]
@acshields we have some question before releasing it.

Should we apply this change only to the newly created TaaS Projects?

Or should we also apply this to all TaaS Projects which were previously created using our current TaaS form? https://connect.topcoder-dev.com/new-project/talent-as-a-service

**Comment by acshields** [comment]
@maxceem - Let me ask Will Price. I am not sure if he is planning to support previously created TaaS projects in the new TaaS App.

**Comment by acshields** [comment]
@maxceem - Just received confirmation from Will that he would want this applied for both historical TaaS projects and all new TaaS projects moving forward :)

**Comment by drasticdpk** [comment]
1. User is redirect to dev env instead of prod env.
Reference : 
![image](https://user-images.githubusercontent.com/25297859/106148646-652cdd00-61a1-11eb-862c-0cb6d583548f.png)

2. @maxceem below changes has not implement yet , right ?
> https://github.com/appirio-tech/connect-app/issues/4195#issuecomment-738091407
> Hide Assets Library
>Hide FAQs (?): These FAQs are curated for TaaS right now, but would folks be coming here to look at them?
> Hide Reports (?): These reports are curated for TaaS right now, but would folks be coming here to look at them?
> Relabel "Scope" to "Talent Team Requests"

3. In my acc, i dot have pervious project with type TAAS, so I may not able to verify it. Any idea. ?
Thank you !

**Comment by maxceem** [comment]
1. User is redirect to dev env instead of prod env.

This is already fixed on PROD.

> 2. @maxceem below changes has not implement yet , right ?

yes, for now there was not a strong requirement to make any other changes.

>3 In my acc, i dot have pervious project with type TAAS, so I may not able to verify it. Any idea. ?

yeah, I'm not sure how to test it on PROD, I don't have access to old TaaS projects on PROD either.

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/106153193-63b1e380-61a6-11eb-919a-4d535303dc28.png)

**Comment by drasticdpk** [comment]
Ok noted @maxceem. 
Based on above communication this is is verified on prod.
