### ISSUE TITLE
New DS Intakes Mapping to FAQs Lists

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4196]
@RishiRajSahu - I know I have to provide you with the FAQ mapping for the three new DS intake forms. However, I can't track down the link to the Contentful repo where the FAQ lists are housed. Can you share it here? Then I will review & tell you the mapping.

**Comment by RishiRajSahu** [comment]
@acshields I have DM'ed you the url.

**Comment by acshields** [comment]
@RishiRajSahu - thank you.

For the Beacon, Prediction, and Algorithm intakes/project types, I have created 3 new FAQLists titled Beacon, Prediction, Algorithm, respectively. I haven't published the lists yet - can you do that once the mapping is in place?

**Comment by RishiRajSahu** [comment]
Done.
