### ISSUE TITLE
Infinite loop cause by Auth when run locally

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4199]
At the moment when I try to set up Connect App locally, I get infinite loop of errors caused by Auth library, see demo video https://monosnap.com/file/p6YodFZESEy7HIvpyziBHNU6fQNaZo

This caused by this error https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin.

![image](https://user-images.githubusercontent.com/146016/99672124-ad31d400-2a7b-11eb-937f-9654890f4e1d.png)

**Comment by maxceem** [comment]
This is a general issue with the TC Auth library so I've logged an issue there https://github.com/topcoder-platform/tc-auth-lib/issues/98

**Comment by acshields** [comment]
@maxceem - I see your note above. Is there anything for us to fix inside of Projects App at this time? Wondering if I should tag it to January if there A) is something we need to do and B) we can get it done before 1/15.

CC @RishiRajSahu

**Comment by maxceem** [comment]
@acshields I forgot to close this issue in Connect App, it was solved in the Auth lib https://github.com/topcoder-platform/tc-auth-lib/issues/98. So I'm closing this one.

**Comment by acshields** [comment]
Awesome - thanks, @maxceem!
