### ISSUE TITLE
[Project Files] - the delete button is available after the submit is performed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#420]
Expected behavior

- The delete button must not be enable after a project is submitted.

Actual behavior

- The delete icon button must not be available.

Steps to reproduce the problem

- Login into application as copilot role.

- Add New Project(Prototype an app / Desktop).

- Set required data and Create Project.

- Edit previous project created.

- Go to Specification.

- Set Skip for all data in App Definition.

- In Project Files press Add File button.

- Select any file from local computer and Upload.

- Complete all required fields until Submit for Review button is enable.

- Press "Submit for Review".

- Go to Project Files (1) section.

- Observe the delete icon available.

Environment
- OS: Windows 7
- Browser (w/version): Chrome  49.0.2623.112 m
- User role (client, copilot or manager): copilot role
- Account used: cp-superstar

see attach!

![delete-available](https://cloud.githubusercontent.com/assets/5114907/19015522/e0f78b90-880e-11e6-89c6-d804d9c3a2d8.png)

**Comment by mahestro** [comment]
It's expected. Not a bug.
