### ISSUE TITLE
Project Plan: Phase Status Logic

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4203]
### Summary
We are amending how phase status logic works. The user performing set-up will no longer be required to indicate the overall status of a phase in a dropdown menu, and instead the status (once published) will be dynamically maintained by using the date data provided.

### A Published Phase's Status Logic Rules
Once a phase has been published by the user performing set-up, the following conditional logic rules should apply for status management:
- If a phase is published and the earliest start date on the timeline has not passed, the phase status = "Planned"
- If a phase is published, the earliest start date on the timeline has passed, and the latest end date on the timeline has not passed, the phase status = "Active"
- If a phase is published and the latest end date on the timeline has passed, the phase status = "Complete"

### A Draft Phase's Status Logic Rules
If a phase is still in Draft (i.e. has not been published), then no conditional logic rules apply (it should continue to remain in Draft status, even if dates have passed).

**Comment by RishiRajSahu** [comment]
@lakshmiathreya @drasticdpk this must also valid, as this is covered via new phase/milestone logic. Let me know if anything as per the description doesn't holds.

**Comment by maxceem** [comment]
@RishiRajSahu this is not implemented yet.

**Comment by maxceem** [comment]
@RishiRajSahu Done via ccf55e95dc7cbbaea0a89c7fe9daa07463374e19

![image](https://user-images.githubusercontent.com/146016/103086105-58d6c280-45ec-11eb-9cfd-d35f04bac24e.png)

Have one concern. If the last milestone date is passed, but the milestone itself is not completed. How should we show phase in such a case:

![image](https://user-images.githubusercontent.com/146016/103086179-976c7d00-45ec-11eb-916c-0bb677ded862.png)

**Comment by maxceem** [comment]
2. The second question. Now instead of "Active" status we are showing progress indicator. Should we change this somehow?

![image](https://user-images.githubusercontent.com/146016/103086319-fe8a3180-45ec-11eb-9972-193baec2536b.png)

**Comment by maxceem** [comment]
> 2. The second question. Now instead of "Active" status we are showing progress indicator. Should we change this somehow?

After discussion with Rishi on Slack, showing "Active" label under the progress indicator for active phases as we don't have an icon:

![image](https://user-images.githubusercontent.com/146016/103088163-9cccc600-45f2-11eb-8f87-51fff908d78f.png)

**Comment by RishiRajSahu** [comment]
@maxceem Few scenarios to mention -
1. Last date of phase is passed but still there are uncompleted milestone(s).
2. Last date of last milestone is passed i.e. its completed but phase's end-date still not passed.

If we are leaving the phases and milestones to be fully managed by user that should be user's responsibility to manage dates

Let's add active text below the progress indicator

**Comment by maxceem** [comment]
> If we are leaving the phases and milestones to be fully managed by user that should be user's responsibility to manage dates

@RishiRajSahu does it mean that we should leave it as it is?

![image](https://user-images.githubusercontent.com/146016/103088331-2aa8b100-45f3-11eb-93b1-e2a30aadc4f2.png)

**Comment by RishiRajSahu** [comment]
@acshields should we let it upto user to correctly manage dates ? or could you suggest some other logic for phase completion ?
Currently phase dates are managed as below on UI 
>Phase's dates are the startDate of the first milestone and endDate of the last milestone

**Comment by acshields** [comment]
@RishiRajSahu - Please follow-up to let me know where I may be off-base here, but here are my thoughts:
I want the user to manage the dates (re: our previous conversations on not trying to over-complicate the logic).
However, I wonder whether we can have these two automations in place for the overall status:
1) On the start date (first milestone start date), the phase moves to "Active"
2) On the end date (last milestone end date), the phase moves to "Complete"

What complications could this cause?

**Comment by lakshmiathreya** [comment]
cc @drasticdpk 
@RishiRajSahu @maxceem - Acc to Phase Status logic rules - this phase should be in Planned actually - it moved to Planned just momentarily and moved to Active after that... Also, start date of Phase doesnt match actual Start date of First Milestone ...
<img width="1680" alt="Screenshot 2020-12-25 at 9 52 28 AM" src="https://user-images.githubusercontent.com/51733042/103119031-8e84b580-4697-11eb-942f-14b72a1d9d9c.png">

**Comment by lakshmiathreya** [comment]
Moving Status to Completed only based on Date - despite incomplete Milestones - need to review - not sure if that's the right logic ... 
<img width="1680" alt="Screenshot 2020-12-25 at 10 04 42 AM" src="https://user-images.githubusercontent.com/51733042/103119299-d48e4900-4698-11eb-852b-91f6b241402b.png">

**Comment by drasticdpk** [comment]
Agreed with @lakshmiathreya . 
@maxceem  can you please us to sum up the requirement, will test accordingly. 
Today default milestone also not created for for planned phase. 
![image](https://user-images.githubusercontent.com/25297859/103130493-02898280-46c5-11eb-9284-deadb3d872e5.png)
@maxceem  -ve testing and exploratory testing result will share on different issue is it fine. ? cc @lakshmiathreya

**Comment by maxceem** [comment]
> @RishiRajSahu @maxceem - Acc to Phase Status logic rules - this phase should be in Planned actually - it moved to Planned just momentarily and moved to Active after that... Also, start date of Phase doesnt match actual Start date of First Milestone ...

At the moment to show phase dates we use dates from milestones and we ignoring dates in the phase:

![image](https://user-images.githubusercontent.com/146016/103131370-28a12980-46a9-11eb-8114-edd76dd65f4d.png)

![image](https://user-images.githubusercontent.com/146016/103131402-4b334280-46a9-11eb-9071-fc361fde8203.png)

This is the logic we previously had with old milestones and we just keep it for new milestones too. I think this logic is confusing and there are 2 ways to go:
1. Remove dates from the phase as we actually don't use them, and only use dates from the milestones.
2. Keep dates in phase and use them instead of dates of the milestones. So it would be up to Copilot how keep these dates in sync or don't keep.

@acshields maybe you would like to give us some input on this.

**Comment by maxceem** [comment]
> Today default milestone also not created for for planned phase.

@drasticdpk good catch, this is a known issue that happens from time to time and we are trying to track it. This is listed here https://github.com/appirio-tech/connect-app/issues/4222#issuecomment-748984627 - issue 4.

When you have this issue please report the **projectId** and **phase** where you've got it. Also, please, note the time when you had it, so we would track it server logs.

**Comment by drasticdpk** [comment]
@maxceem ,  
Here is my finding

**Reference**  : https://monosnap.com/file/hF2KVLNC1X5TI87XjiCl0GAw9KMs4y
So, if you put future date for phase but not reporting milestone, we are having this issue.
Possible solution > to overcome this issue, Can we make a system, where phase start date <= Reporting Milestone  start date ?
Note : I noticed page is not autoloading while creating planned phase. See video at 0:30 seconds. 
**Project** : https://connect.topcoder-dev.com/projects/16828
**User** : TCConnCopilot

**Comment by RishiRajSahu** [comment]
@maxceem regarding this https://github.com/appirio-tech/connect-app/issues/4203#issuecomment-750856925 got confirmation from @acshields 
```Let's let the user handle it. If something was missed, they can still edit the date and the phase will just revert from "Complete" to "Active" until the new end date arrives.```

**Comment by maxceem** [comment]
> @maxceem regarding this #4203 (comment) got confirmation from @acshields
> Let's let the user handle it. If something was missed, they can still edit the date and the phase will just revert from "Complete" to "Active" until the new end date arrives.

So as I understand user is responsible for controlling it, and we don't have to fix it in UI. If such situation happens, it's responsibility of the user to update the last milestone date, so the phase is shown as "Acitve" instead of "Completed".

@RishiRajSahu @acshields could you also, please, review this https://github.com/appirio-tech/connect-app/issues/4203#issuecomment-751225492. As it's related to "Completed"/"Active" status logic.

**Comment by RishiRajSahu** [comment]
@maxceem mentioning this
```when creating the phase the start date for the first milestone i.e. the default reporting milestone is same as the start date of the phase created ```
and as user has full control over managing dates now, let's go with option 2.

**Comment by maxceem** [comment]
> @maxceem ,
> Here is my finding
> Reference : https://monosnap.com/file/hF2KVLNC1X5TI87XjiCl0GAw9KMs4y
> So, if you put future date for phase but not reporting milestone, we are having this issue.
> Possible solution > to overcome this issue, Can we make a system, where phase start date <= Reporting Milestone start date ?
> Note : I noticed page is not autoloading while creating planned phase. See video at 0:30 seconds.
> Project : https://connect.topcoder-dev.com/projects/16828
> User : TCConnCopilot

Thank you, @drasticdpk. It's fixed now, you may try again.

**Comment by maxceem** [comment]
> @maxceem mentioning this
when creating the phase the start date for the first milestone i.e. the default reporting milestone is same as the start date of the phase created
> and as user has full control over managing dates now, let's go with option 2.

If we prefer giving full control over managing dates to the user, then on the second though I think there is option 3:
- Keep it as it is: we are showing dates based on milestones as we do now. And user can update phase dates to keep it in sync with milestone dates if they want. This way it would be compatible with old existent phases.

**Comment by lakshmiathreya** [comment]
Accepting that current implementation is as expected based @acshields inputs on Slack. Allowing User to control Phase status via dates.

**Comment by drasticdpk** [comment]
**Prod verification**

![image](https://user-images.githubusercontent.com/25297859/103524705-1e9bd980-4ea6-11eb-8819-3307be401742.png)
