### ISSUE TITLE
TaaS Intake Form - Remove optional skills question

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4205]
With new TaaS-api integration to our TaaS intake form, we don't need optional skills as the api doesn't support it for the first release.
Create a new intake form with optional skills question removed.

fyi @acshields

**Comment by RishiRajSahu** [comment]
@acshields moving it to Jan as this will go with TaaS app release.

**Comment by maxceem** [comment]
@RishiRajSahu as we have another task with much more wast changes https://github.com/appirio-tech/connect-app/issues/4206, should we close the current ticket and only implement what is described in another task?

**Comment by RishiRajSahu** [comment]
@maxceem agree #4206 is bigger piece but that doesn't contain requirement of removing optional skills, so Let this ticket open. I will add the optional-skills removal there also.

**Comment by drasticdpk** [comment]
@RishiRajSahu , please let us know I can we do QA for this.

**Comment by maxceem** [comment]
@drasticdpk this was done as a part of https://github.com/appirio-tech/connect-app/issues/4206.

![image](https://user-images.githubusercontent.com/146016/104295021-9f6f5c80-54c8-11eb-8a83-17f4a194abb9.png)

**Comment by drasticdpk** [comment]
Verified.

![image](https://user-images.githubusercontent.com/25297859/104300012-094e2d00-54ee-11eb-9671-890df7efc089.png)

**Comment by drasticdpk** [comment]
Verified on Prod Env.
![image](https://user-images.githubusercontent.com/25297859/106144076-cd78c000-619b-11eb-975e-a4b1a0dd6676.png)
