### ISSUE TITLE
Show explicit error instead of infinite loading when Project Template is not found

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4207]
Follow up from https://github.com/topcoder-platform/tc-project-service/issues/582#issuecomment-703654821

At the moment when I open a project which has `templateId` which points to the `ProjectTemplate` which is not found I see an infinite loading page because Project Template is not found, and we don't know how to display the project (https://connect.topcoder-dev.com/projects/6450):

![image](https://user-images.githubusercontent.com/146016/95087586-8cf7c100-072a-11eb-8b87-5cbf329a1ac4.png)

We have gracefully handle this situation. For example, show some explicit error message.

**Comment by RishiRajSahu** [comment]
https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/projects/update.js#L210 we would have to handle it based on what backend returns in such cases.

**Comment by maxceem** [comment]
@RishiRajSahu would this work?

![image](https://user-images.githubusercontent.com/146016/101765434-f8269080-3ae9-11eb-857b-5accb9dd6665.png)

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/pull/4208

**Comment by drasticdpk** [comment]
Verified : 
![image](https://user-images.githubusercontent.com/25297859/103741469-3b105100-5021-11eb-9c0f-2b1fcf89e197.png)
@maxceem  I have verified this issue based on the [discussion](https://github.com/topcoder-platform/tc-project-service/issues/582#issuecomment-703654821)  , let me know for anything.

**Comment by drasticdpk** [comment]
@RishiRajSahu @maxceem ,  Can you please assist me to verify this issue on prod env ?

**Comment by maxceem** [comment]
I don't think we know any project with broken Project Template. Actually this error shouldn't happen. It can only happen if we accidently deleted Project Template which is being used by some project. And we should not do it.

Maybe @RishiRajSahu is aware of some old project, because I have access to a limited number of project in PROD.

**Comment by RishiRajSahu** [comment]
@drasticdpk yeah It can't be tested on project, as we never deleted any template on prod. If Dev worked fine that should be fine.

**Comment by drasticdpk** [comment]
Ok noted @RishiRajSahu @maxceem

**Comment by RishiRajSahu** [comment]
Closing.
