### ISSUE TITLE
Some HTML tags accepted in Comments fields

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#422]
### Expected behavior
-----------------------------------------------------------------
Must restrict the HTML tags in Comments fields

### Actual behavior
-----------------------------------------------------------------
Some HTML tags accepted in Comments fields

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Dashboard
- In the POST; Add a comment like below

<strong>This text is strong</strong>
<br />
<p></p>
<hr>

- Click POST

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_22-22-27](https://cloud.githubusercontent.com/assets/4592712/19015644/9a5c0410-8825-11e6-8108-c3d40f344ad3.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
We are now supporting markdown. Closing this bug.
