### ISSUE TITLE
Project Plan: Phase Set-Up & Editing + Milestone Types

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4222]
This issue is to combine all the work which has to be done by 2 issues:
- Project Plan: Phase Set-Up & Editing https://github.com/appirio-tech/connect-app/issues/4057
- Project Plan: Milestone Types https://github.com/appirio-tech/connect-app/issues/4083

As we combine all the work done in both these tickets, here we could track all the issues during QA.

This was implemented by 2 challenges:
- https://www.topcoder.com/challenges/d57c6f7c-2e17-4021-8d5e-5f6c2cc7c97f?tab=details
- https://www.topcoder.com/challenges/eb107e10-19e0-40d5-a1a4-ada8ae2fc25a

#### QA Guidelines

- We have to test all the functionality from points of view of 3 kinds of users:
  Customer, Manager and Copilot

**Comment by maxceem** [comment]
Known issues:
1. When we create a new phase and click "Publish" the first milestone should be activated immediately, but it doesn't get get activated.
2. When I activate the existent phase, sometimes it activates not the first milestone https://monosnap.com/file/hjFyxnaMqYyrc3nq5vipTnOnXXhdUU

**Comment by drasticdpk** [comment]
1. Unable to add attachment > Reporting > Specification 
    
![image](https://user-images.githubusercontent.com/25297859/103011351-dd303380-4561-11eb-98a6-1498a8f62008.png)

2. Completed text is missing 
    
![image](https://user-images.githubusercontent.com/25297859/103011890-ce964c00-4562-11eb-9d01-4241f1a55519.png)

Project : https://connect.topcoder-dev.com/projects/16820
Phase : **4222 phase1**

**Comment by maxceem** [comment]
There is one more issue on the Project Service:
- Actual Start Date is not set for the first milestone when we publish phase during creating https://github.com/topcoder-platform/tc-project-service/issues/604

**Comment by maxceem** [comment]
@drasticdpk 

> 1. Unable to add attachment > Reporting > Specification

There would be no file uploading. Please, create a new phase, we no more add this field.

> 2. Completed text and Reported text is missing

We implemented this text as per https://github.com/appirio-tech/connect-app/issues/4083#issuecomment-750343875

Could you please, check now.

**Comment by maxceem** [comment]
> Actual Start Date is not set for the first milestone when we publish phase during creating topcoder-platform/tc-project-service#604

This is fixed client side by 673f7ed1e23ddbe89978ec3ae64457afc3f2caaf

**Comment by drasticdpk** [comment]
**Verified**. 

![image](https://user-images.githubusercontent.com/25297859/103082696-d5749b80-4602-11eb-9ae2-d93466e6b9fd.png)

**Comment by drasticdpk** [comment]
Prod Verified.

![image](https://user-images.githubusercontent.com/25297859/103521368-bac2e200-4ea0-11eb-87dc-50e6acc30a89.png)
