### ISSUE TITLE
Copilot permission for Project Status

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4225]
At the moment copilot can edit project status.

![image](https://user-images.githubusercontent.com/146016/102988689-fbc00b80-451c-11eb-986e-d897dc362ebf.png)

Visually it looks like copilot can update project to any status, but in reality if copilot tries to change project to "active" it would fail, see https://github.com/appirio-tech/connect-app/issues/4057#issuecomment-750031790

- I suggest review which status could copilot update to.
- And disable status which copilot cannot choose in this dropdown. Visualy it could look like this:

   ![image](https://user-images.githubusercontent.com/146016/102989615-940ac000-451e-11eb-885f-15c08b0b2f43.png)

- Alternatively, we may not allowing to change project status to copilots at all.

FYI @RishiRajSahu

**Comment by maxceem** [comment]
Additional note.
At the moment we have functionality - when we publish any phase and project is not yet active, we change project status to active. Copilots can publish phases, but copilots cannot activate project which leads to this issue https://github.com/appirio-tech/connect-app/issues/4057#issuecomment-750031790

To fix this issue, when we publish phase by copilot we no longer activate the project. This is done via b05991fbcc31642b190810fc1fc2e3d8f902a7af

**Comment by RishiRajSahu** [comment]
@maxceem from the code it looks we are now using centralized method of permissions unable to find any specific change in the code https://github.com/appirio-tech/connect-app/commit/b05991fbcc31642b190810fc1fc2e3d8f902a7af which fix the issue, So what will be the behaviour now, 

1. Copilot can publish the phase but project will not be activated , or 
2. Copilot can publish the phase but project will be activated , or 
3. Copilot cannot publish the phase

**Comment by maxceem** [comment]
@RishiRajSahu after the fix behavior is like:
1. Copilot can publish the phase but project will not be activated

**Comment by RishiRajSahu** [comment]
@maxceem for now it looks good, but let's keep this open I will discuss with @acshields

**Comment by acshields** [comment]
@maxceem @RishiRajSahu -

Trying to catch up on this one. If I am understanding things right, then:
1. I thought we had removed the requirement for at least one phase to be "published" (planned/active in our old model) before the project can be moved to "Active" status. If it's still in place, then we should remove this requirement so that a project can be moved to "Active" status at any time.
2. For Copilots, I agree with the approach of graying out the project statuses that they cannot manage. The project status changes a Copilot can do are:
-Move a project to Active
-Move a project to Complete

**Comment by RishiRajSahu** [comment]
@acshields 
1. You are right we removed that dependency on phase, but we do have a feature that if project is not active and if any phase is marked active/publish the project will automatically move to active.
2. @maxceem we have to update according to this.

**Comment by RishiRajSahu** [comment]
@maxceem as per latest update we would need point 2 from here https://github.com/appirio-tech/connect-app/issues/4225#issuecomment-750792437

**Comment by maxceem** [comment]
1. Is done via 754d851a0383f701ee5192e086c7f7123709b705 in Connect App and via https://github.com/topcoder-platform/tc-project-service/commit/819d4479f0defedd05198a5f78a63b70ce5424d2 in Project Service

   - **QA**: if Copilot publish phase, in non-active project, then project should activated automatically.
   
2. Is done via 02b67c894041ac251e0a2e6ec6bd24c9158f1b4d in Connect App

    - **QA** Copilot should only be able to choose "Acitve" and "Completed" status. Managers and Admins should be able to choose any status.

        ![image](https://user-images.githubusercontent.com/146016/103207895-1ec93180-4908-11eb-8cf3-db1c5e6cbede.png)

This is ready for QA.

**Comment by drasticdpk** [comment]
**Verified** 

https://monosnap.com/file/njyvL1tmbydDE6vU1HMvllcLyGryr8

**Comment by drasticdpk** [comment]
**Verified on Prod Env.**

![image](https://user-images.githubusercontent.com/25297859/103524298-6bcb7b80-4ea5-11eb-8d8a-a40b3d620e48.png)
