### ISSUE TITLE
ON/OFF button overlap with the long 'Feature name' text

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#424]
### Expected behavior
-----------------------------------------------------------------
Must not overlap

### Actual behavior
-----------------------------------------------------------------
ON/OFF button overlap with the long 'Feature name' text

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Specification
- Click 'Add a custom feature'
- Enter Long name
- eg: Lorem ipsum dolor sit amet, ius et suscipit mnesarchum Lorem ipsum dolor sit amet, ius et 
- Click Save Feature
- Check the ON/OFF button

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_22-34-20](https://cloud.githubusercontent.com/assets/4592712/19015715/43df048c-8827-11e6-9178-cd7dd62cac75.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.
