### ISSUE TITLE
Cannot load old V2 projects

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4258]
At the moment old v2 projects cannot be loaded:

- see example project https://connect.topcoder-dev.com/projects/5000

![image](https://user-images.githubusercontent.com/146016/104295783-8dda8480-54c9-11eb-9bbf-61d4a6ce2dd1.png)

**Comment by vikasrohit** [comment]
Closing the issue as I have verified the reported projects(https://connect.topcoder.com/projects/658 and https://connect.topcoder.com/projects/24777) being loading successfully now.
