### ISSUE TITLE
Layout issue in the Delete confirmation popup; when we have long 'Feature name'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#426]
### Expected behavior
-----------------------------------------------------------------
Must display the 'Feature Name' in two lines; OR Must set max limit for the 'Feature name'

### Actual behavior
-----------------------------------------------------------------
Layout issue in the Delete confirmation popup; when we have long 'Feature name'

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Specification
- Click 'Add a custom feature'
- Enter Long Feature name
- eg: Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
- Click Save Feature
- Select the Feature
- Click Delete custom feature
- Check the delete confirmation popup

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_22-39-45](https://cloud.githubusercontent.com/assets/4592712/19015774/5a74aa16-8828-11e6-9032-4c687ca3f663.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by vic-appirio** [comment]
feature name limited to 40 chars.
