### ISSUE TITLE
New "Project Defaults" Tab & Screen in a Project

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4267]
### Update 1
- Add a new tab inside of projects that is labeled "Project Settings"
- Display this tab under the FAQs tab.

### Update 2
When clicked, the screen should show this [desktop design](https://marvelapp.com/prototype/bge9gab/screen/75960918) and [mobile](https://marvelapp.com/prototype/7hg6b9f/screen/75960686). Some notes on the design:
- There are additional screens designed here, which we do not need to worry about right now. For defaults, use screens 6-7 in desktop and 9-10 in mobile.
- We don't need to worry about matching the full UI as designed (colors). 
- The billing account field currently appears as text. This should be a responsive dropdown menu instead.
- The terms (Enforce Topcoder NDA) should be updated to match the field structure defined in [Git Issue 4273](https://github.com/appirio-tech/connect-app/issues/4273).

**Comment by acshields** [comment]
@vikasrohit - I have attached the designs.

**Comment by lakshmiathreya** [comment]
Pls clarify @maxceem @vikasrohit - Update 1 - verified - Assuming its "Project Defaults" tab - not "Project Settings" ... Update 2 - doesnt seem to be added yet. cc @drasticdpk

**Comment by drasticdpk** [comment]
I agreed with @lakshmiathreya , it seems it is not updated yet. cc @maxceem

**Comment by lakshmiathreya** [comment]
@vikasrohit pls clarify ... cc @drasticdpk

**Comment by vikasrohit** [comment]
@lakshmiathreya @drasticdpk  I think all updates are included. The shared screen have group display management as well which we are separately tracking via https://github.com/appirio-tech/connect-app/issues/4270 and we have agreed on not following UI theme because we have to adhere to current designs. Further for the terms field (which is separately tracked via https://github.com/appirio-tech/connect-app/issues/4273) UI is changed to a switch button (which is right now best adapted as radio input)

**Comment by vikasrohit** [comment]
Let me if anything else is pending here from implementation

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/106453715-d32f1800-64b1-11eb-9d57-bb04efd83f3b.png)
![image](https://user-images.githubusercontent.com/25297859/106453827-fb1e7b80-64b1-11eb-8c27-f94750c45f8d.png)

> The billing account field currently appears as text. This should be a responsive dropdown menu instead.

Note : Based on the above discussion it is verified. Can open for anything.

**Comment by vikasrohit** [comment]
There is separate issue (#4269 ) for tracking BA which haven't marked as ready for review.
