### ISSUE TITLE
New "Project Defaults" User Role Permissions

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4268]
### Update 1
In a project, only these user roles can view, access, and edit the Project Defaults tab:
- Copilot
- Admin
- Connect Manager
- Copilot Manager
- Project Manager
- Program Manager
- Account Manager
- BDR
- Account Executive
- Presales
- Solution Architect

**Comment by lakshmiathreya** [comment]
Verified User Role permissions for Admin, Manager, Copilot and User roles. cc @drasticdpk pls update the Role matrix accordingly for Project Defaults feature.

**Comment by drasticdpk** [comment]
Verified with beta flag.
![image](https://user-images.githubusercontent.com/25297859/106450893-e7711600-64ad-11eb-8501-64afcd4a0ee8.png)
