### ISSUE TITLE
Warning message:  performUpdateIfNecessary: Unexpected batch number

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#427]
Expected behavior

 - Tags must be set ON as feature of application. 

Actual behavior

 - Tags can not be set ON.
   
Steps to reproduce the problem

    Login into application as copilot role.

    Edit the project phone - https://connectv2.topcoder-dev.com/projects/414/specification.

    Open Developer Tool.

   Select Specification section.

   Add / Edit Features.

   Select Tags and try to set ON.

   Complete some text in field.

   Select another feature and set ON.

   Observe the error calls!

Environment

    OS: Windows 7
    Browser (w/version): Chrome 49.0.2623.112 m
    User role (client, copilot or manager): copilot
    Account used: cp-superstar

**Comment by mahestro** [comment]
Known console behavior.
