### ISSUE TITLE
"Project Defaults": Groups Display & Management

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4270]
### Update A
Display the project's group question as follows on the "Project Defaults" screen:
- Field Label: "Intended Work Groups"
- Field Data: [Responsive Text Field]

### Update B
When the user types into the responsive text field, the returned options should only be the groups that they have access too.

**Comment by vikasrohit** [comment]
@acshields we don't get Salesforce BA id when we lookup from our platform's BA API. So, we would need changes in SFDC to lookup for the BA in SFDC based on provided platform BA id.

**Comment by acshields** [comment]
@vikasrohit - was this comment supposed to be in regards to the issue(s) for billing account, and not for groups? If it was for groups, I am not understanding how a BA plays a role for that.

**Comment by vikasrohit** [comment]
@acshields sorry for the confusion, yes your are right my comment was in context of billing account https://github.com/appirio-tech/connect-app/issues/4269. I would comment in that issue for my intended concern.

However, I guess Update 2 is not necessary in this issue as well because groups does not have link to BAs as well.

**Comment by acshields** [comment]
@vikasrohit - updated to remove original "Update 2." Now reqs are labeled Update A and B and they should be accurate.

**Comment by maxceem** [comment]
@vikasrohit at the moment Project object doesn't have a designated place to store assigned groups.

We have 2 ways to go:
1. Create a new field `groups` in the `project` model to store the list of Groupd ids as array of string. See how we store `terms` https://github.com/appirio-tech/connect-app/issues/4273#issuecomment-765292459.
2. Store groups in the `details` field which is JSON and we can add any fields there.

I guess groups are kind of fundamental thing of projects and would hardly be dropped, so creating a separate field might have sense.

**Comment by vikasrohit** [comment]
Yes, agreed. we should make it first class citizen of the Project object because we might need to query projects based on groups.

**Comment by maxceem** [comment]
@vikasrohit I guess I found where we previously stored groups `challengeEligibility.groups` https://github.com/topcoder-platform/tc-project-service/blob/develop/src/events/projects/index.js#L114.

Though this field also only accepted `numbers`.

Should we update the type of it and reuse it? Or add a new one, what do you think?

**Comment by vikasrohit** [comment]
`challengeEligibility` is also one of the tech debt field which we are not using for any project. Even if it was set for some of the project initially, we are not reading it anywhere. So, we should be safe to introduce new field or reuse the same. However, I think having a dedicated field for groups make more sense to me. We could also think about create a new table called `project_defaults` OR `challenge_eligibility`, however, given the current requirements, I don't see any benefit of that. So, to avoid over engineering, I would suggest to go with a simple `groups` field which can accept array of UUIDs.

**Comment by maxceem** [comment]
Sum up:
- We already implemented such a filed in Work Manager
  - see live demo on the page https://challenges.topcoder-dev.com/projects/16668/challenges/602bb38e-cd7a-4afd-9a9d-c645b24a12de/edit
  - demo video https://monosnap.com/file/1t1zeD5W1JKJI4JluWXVdPi1V0rTr8
  - see related code in Work Manager https://github.com/topcoder-platform/work-manager/blob/81485ee57b4f39dbd17c7d775dd659f3a77e7beb/src/components/ChallengeEditor/Groups-Field/index.js
  - note, that in Work Manager we use `react-select` version 3, while in Connect App we are using older version 2.4. I think we can still implement the same behaviour using our current version 2.4, as we already have a similar behavior when inviting member on the page https://connect.topcoder-dev.com/projects/16952, see demo https://monosnap.com/file/Bvo2BniKI6EorMfR2fNOygGCMFdORX. The only difference is that when inviting member we are allowing manually adding handles not from the list, while for groups we should not allow it.
- For Groups API check Work Manger code https://github.com/topcoder-platform/work-manager/blob/scheduling-api-changes/src/services/challenges.js#L58-L67
- This field should work the same as in Work Manager i. e.:
   - don't show any groups until we entered something into the field
   - when we enter something, send request to the server, and get only groups which match the entered word from the server
   - use denounce for autocomplete to avoid too many server request, config delay `AUTOCOMPLETE_DEBOUNCE_TIME_MS` like we do in Work Manager https://github.com/topcoder-platform/work-manager/blob/scheduling-api-changes/src/components/ChallengeEditor/Groups-Field/index.js#L13-L25

**Comment by maxceem** [comment]
This issue ready for testing on DEV.

QA guidelines:
- Project Defaults tab would be only shown if we add `beta=true` flag to the URL like https://connect.topcoder-dev.com/projects/16839?beta=true
- The tab with Project Defaults doesn't require this flag and can be accessed by the direct link https://connect.topcoder-dev.com/projects/16839/settings

**Comment by drasticdpk** [comment]
Verified on Dev

![image](https://user-images.githubusercontent.com/25297859/107222803-79909580-6a3d-11eb-9b99-cacc7a045cd1.png)

**Comment by drasticdpk** [comment]
Verified on prod 
![image](https://user-images.githubusercontent.com/25297859/107626330-bea70880-6c85-11eb-81b4-65ece3e80836.png)
