### ISSUE TITLE
"Project Defaults": Terms Display & Management

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4273]
### Update A
Display the project's terms options as follows on the "Project Defaults" screen:
- Field Label: "Enforce Topcoder NDA"
- Field Data: [Yes/No Radio Buttons]
-Enforce Topcoder NDA [Hyperlinked to Topcoder NDA: https://www.topcoder.com/challenges/terms/detail/c41e90e5-4d0e-4811-bd09-38ff72674490]

### Update B
The user should be able to change selected defaults.

**Comment by vikasrohit** [comment]
@acshields I don't think we need the Update 2 in this story, I don't see any relation between Terms and BA.

**Comment by acshields** [comment]
@vikasrohit - correct. I was copy/pasting content and failed to delete that part. I have updated the spec.

**Comment by maxceem** [comment]
We would have to define NDA Terms ID in the config for DEV and PROD.

For DEV, we can use this one `7245bb7d-d7c9-45a0-9603-d5ff05af0977` (Appirio NDA v2.0) or you may suggest another one.

For PROD we need this to be provided.

**Comment by maxceem** [comment]
@vikasrohit we have some API issue with terms.

Projects have a property `terms: []` which accepts the array numbers, as legacy terms had number ids.
New V5 Terms have ids as uuids like "7245bb7d-d7c9-45a0-9603-d5ff05af0977".

So if I try to set V5 terms ids, Projects API would return error:
```js
{
    "message": "validation error: \"0\" must be a number"
}
```

There are several things to consider:
1. We can update the validation rule and accept strings for `terms` but should we do this? Because as a result the `terms` property would contain old terms ids for old projects and new terms ids for new projects. Wouldn't it break third party services that might consume this field value?

2. I'm not sure if ES index would allow storing string in this array as we already storing numbers in this array. I guess yes, but we have to check it.

**Comment by vikasrohit** [comment]
> For PROD we need this to be provided.

We can copy it from https://github.com/topcoder-platform/work-manager/blob/develop/config/constants/production.js#L27

For `terms` field in Projects API, I don't think we are using that anywhere, it is a left over of initial projects api and I don't think we would have any project with any real data in that field. So, we should be safe to refactor that field now. We can do complete reindexing to change the data types.

**Comment by maxceem** [comment]
Sum up:
- if user enables NDA, then we should add NDA term to the terms array of the project `terms`. If use disables NDA, then we should remove NDA terms from the `terms` array if present.
- we should add a new ENV variable `DEFAULT_NDA_UUID` to https://github.com/appirio-tech/connect-app/tree/3051ef4c250bca7c42c209d648a259fae35a46a0/config/constants. For DEV and QA env the value is `e5811a7b-43d1-407a-a064-69e5015b4900` (https://github.com/topcoder-platform/work-manager/blob/develop/config/constants/development.js#L27) and for PROD the value is `c41e90e5-4d0e-4811-bd09-38ff72674490` (https://github.com/topcoder-platform/work-manager/blob/develop/config/constants/production.js#L27)

**Comment by maxceem** [comment]
This would need some code improvements, but functionality works good.

The fix includes fixes for issues:
- https://github.com/appirio-tech/connect-app/issues/4268
- https://github.com/appirio-tech/connect-app/issues/4267
- and current one

QA guidelines:
- Project Defaults tab would be only shown if we add `beta=true` flag to the URL like https://connect.topcoder-dev.com/projects/16839?beta=true
- The tab with Project Defaults doesn't require this flag and can be accessed by the direct link https://connect.topcoder-dev.com/projects/16839/settings

**Comment by lakshmiathreya** [comment]
![image (1)](https://user-images.githubusercontent.com/51733042/106389316-b25eb800-6408-11eb-94ac-4c7346d30cb3.png)

**Comment by drasticdpk** [comment]
Verified 
![image](https://user-images.githubusercontent.com/25297859/106453155-f9a08380-64b0-11eb-915b-5ed70e743f5e.png)

**Comment by maxceem** [comment]
@vikasrohit at the moment for showing NDA field we are wrapping radio buttons inside the accordion:

![image](https://user-images.githubusercontent.com/146016/106932160-11317380-6720-11eb-8652-faf90ad696ad.png)

Would it be fine if don't do that, and just show radio buttons directly without accordion:

![image](https://user-images.githubusercontent.com/146016/106932124-04ad1b00-6720-11eb-8ae7-441890a6a419.png)

It would make our code more universal, we are currently working on the code improvements for this field, to make this form easier to be extended with other fields. And supporting accordion for every field type adds some drawbacks. So if the accordion is not required I would prefer to drop it. Also, as I understand in the new design when we update we wouldn't have an accordion, and we have just update update styles for the Radio Group.

**Comment by acshields** [comment]
@maxceem @vikasrohit - I am good with your alternate presentation suggestion, Maxceem.

**Comment by vikasrohit** [comment]
@maxceem I am good with it, my only concern is that if we want to make things consistent with our intake forms where we are using accordions to show summarized form because when reviewing or editing a form data, accordions are giving nice summary in lesser space then a full fledged form. Project Defaults/Settings also seems something where user might want to look at all of information filled in the form within single view port when the number of fields in the form grow larger.
Having said that,  I am good with current suggestion, we (especially @acshields)  just have to think if we want to have the summary view of forms.

**Comment by maxceem** [comment]
@vikasrohit we could always add accordion to the form. Though I don't see a perfect technical solution for it now, without binding things which would be nicer to keep fully independent, but we can choose the less evil approach if we are sure that we need accordion.

Another concern I have regarding putting efforts into it is that if we eventually update Connect to a new design, I guess it would use the same UI elements as the new UI for WM: https://marvelapp.com/prototype/12jie1b9/screen/74769452. And accordion is not used there. The designer is using another approach for hiding extra information.

**Comment by maxceem** [comment]
@drasticdpk we've refactored the code of this issue and slightly updated UI, so it would good if re-test it again.

This is now ready to be tested on DEV as per https://github.com/appirio-tech/connect-app/issues/4273#issuecomment-769123525.

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/107223111-e60b9480-6a3d-11eb-9543-afba3e6aa42a.png)

**Comment by drasticdpk** [comment]
verified on prod
![image](https://user-images.githubusercontent.com/25297859/107626594-23faf980-6c86-11eb-87cf-ad399376f7da.png)
![image](https://user-images.githubusercontent.com/25297859/107626637-337a4280-6c86-11eb-974d-32c87090f45b.png)
