### ISSUE TITLE
Billing Account Functional Workflow: Testing

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4274]
Test the workflow for billing accounts between Salesforce and Projects App for these scenarios:
- A Client project (ID'd by objective flags: "I need work done now," "I am exploring my options," "Submitting client request") opportunity has an active billing account in Salesforce, and that billing account is reflected in the associated project.
- An Internal project (ID'd by objective flag: "Internal project") opportunity has an active billing account in Salesforce, and that billing account is reflected in the associated project.

**Comment by vikasrohit** [comment]
@acshields we (Sumit,Nikita and me) has already tested `I need work done now,` flow last week and it seems to work as expected. And IMO, the other values of Objective Flag should also behave the same as SFDC does not distinguish between these for the purpose of creating Opty and BA.

**Comment by acshields** [comment]
@vikasrohit - you are correct that on our end, there should be no difference in the workflow between client vs. internal projects. However, my call out on the two use cases above is more to ensure that the Salesforce workflow is operating as expected.

For example:
- Client Workflow: In SFDC, Nikita has different automations in place to determine whether the request should be created as a lead vs. immediately converted to an opportunity, and who the lead/opportunity should be routed too. 
- Internal Workflow: In SFDC, Nikita has all internal projects being assigned to Mess as owner. We just need to test that he is then able to convert it to an oppty & assign a BA as normal in SFDC.

**Comment by vikasrohit** [comment]
Agreed. We can make more tests for those remaining situations.
