### ISSUE TITLE
Remove Billing Account ID Display in Left Sidebar

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4275]
### Update 1
Because the billing account will now be displayed on the "Project Defaults" tab, we no longer need to display this information statically in the project's left sidebar. Please remove this display.

**Comment by maxceem** [comment]
Done via https://github.com/appirio-tech/connect-app/commit/9b2d9fdf4789ae79c49729e20acc2400bf3dc20f

@drasticdpk ready for QA.

**Comment by drasticdpk** [comment]
Verified on dev env
![image](https://user-images.githubusercontent.com/25297859/108683768-2b3dc500-751a-11eb-86e4-78492a267eec.png)

**Comment by drasticdpk** [comment]
Prod verified 
![image](https://user-images.githubusercontent.com/25297859/108823582-bb4a4000-75e8-11eb-9f8b-ed12961d5519.png)
