### ISSUE TITLE
What if user mistakenly make project status complete 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4278]
There should be functionality for admin to re-activate the project. 

**Reference Issue :**
https://github.com/appirio-tech/connect-app/issues/4225

And still copilot can create the challenge from direct app even the project was completed from connect app.
**Reference** 

https://connect.topcoder-dev.com/projects?sort=lastActivityAt%20desc&status=completed 

![image](https://user-images.githubusercontent.com/25297859/105143063-716ec580-5b23-11eb-8091-a9edcee5d3f3.png)
![image](https://user-images.githubusercontent.com/25297859/105143153-92cfb180-5b23-11eb-85e7-73f176e4448c.png)

**Comment by maxceem** [comment]
@drasticdpk yep, we already have this request from Ariel https://github.com/appirio-tech/connect-app/issues/4262 it should be ready by `Feb 26`.
