### ISSUE TITLE
Update Request Copilot link

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4283]
Currently, the "Request Copilot" link in the left nav of projects app is pointing to a Google Form.  Please update it to use this URL instead:

https://topcoder.typeform.com/to/YJ7AL4p8#handle=xxxxx&projectid=xxxxx

The 2 params should be populated with the appropriate data:

- handle = the handle of the logged in user
- projectid = the ID of the current project where the request is being made from.

**Comment by ajefts** [comment]
@acshields This would be a huge help if we could get it in next week.

**Comment by acshields** [comment]
@maxceem @vikasrohit - Tony has this small request for us to take on. Is this something we can get done and released this week?

**Comment by vikasrohit** [comment]
@acshields I have made the changes in dev and these would be included in our demo release for Projects Defaults project.

**Comment by acshields** [comment]
@ajefts - FYI :)

**Comment by lakshmiathreya** [comment]
Request Copilot form looks good. One suggestion - we should probably auto close the Request form tab once the Final submit happens? Currently the Tab is left open and redirects to the Connect login page. I can log a different Issue for that ... marking this as pass ...

**Comment by acshields** [comment]
@lakshmiathreya - great catch for the auto-close. What is the Issue # for the one you created, so I can prioritize it accordingly?

**Comment by vikasrohit** [comment]
@acshields @ajefts it is deployed to prod.
