### ISSUE TITLE
Update TaaS Projects with Display Text

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4289]
Add this text above the TaaS App button in TaaS projects: "This project is a Talent as a Service Project. Click this button to navigate to a TaaS focused experience where you can get information specific to your TaaS team."

![image (27)](https://user-images.githubusercontent.com/41118149/106312772-0c4e5a80-621c-11eb-94e5-327a7e227340.png)

**Comment by maxceem** [comment]
@acshields we can use UI like for Project Plan. Ariel, would you like to put some text as a title? Or we can just add text without a title.

![image](https://user-images.githubusercontent.com/146016/106449026-36a64f00-648c-11eb-8114-95e827dcb51d.png)

**Comment by acshields** [comment]
@maxceem -

No title is required. However, I caught one text fix in Will's original text-body post that would be good to get updated. Please update the body text to read: "This is a Talent as a Service project. Click this button to navigate to a TaaS focused experience where you can get information specific to your TaaS team."

**Comment by drasticdpk** [comment]
@vikasrohit , 
it is not fixed yet right ? 
![image](https://user-images.githubusercontent.com/25297859/107632876-3463a200-6c8f-11eb-839d-da4e45f5e4b2.png)

**Comment by maxceem** [comment]
It's fixed in PR https://github.com/appirio-tech/connect-app/pull/4293 but it's not deployed anywhere yet, as there is no confirmation yet (as per Slack discussion on `connectqa` channel)

**Comment by lakshmiathreya** [comment]
@maxceem can we move this out of this milestone pls?

**Comment by vikasrohit** [comment]
@lakshmiathreya I was doing exactly that right now. :)

**Comment by vikasrohit** [comment]
@acshields moved it out of `Project Defaults`, please move in to the appropriate one.

**Comment by acshields** [comment]
@vikasrohit - we should talk about how to handle these exception cases in Git (i.e. we get a request during our project cycle that does get approved, where should I put it). My concern is if I put it in the next "bug fix/quick win" round it will get missed until we are actually into that period of time, even though it's being requested for sooner.

**Comment by maxceem** [comment]
@vikasrohit I can see it implemented by Rishi but it's not yet merged https://github.com/appirio-tech/connect-app/pull/4293. I guess we want to include it into the current release, we only have to merge it and pass for QA.

**Comment by vikasrohit** [comment]
@acshields we are releasing this one in today's release.
