### ISSUE TITLE
Loading animation is not playing in IE11; Only BLUE circle displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#429]
### Expected behavior
-----------------------------------------------------------------
Must play the loading animation; It only display a BLUE circle

### Actual behavior
-----------------------------------------------------------------
Loading animation is not playing in IE11; Only BLUE circle displayed

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click FILTER
- Click My Projects OR Open a Project from the list
- Check the loading blue circle carefully
- Comapre with the Chrome

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_23-10-39](https://cloud.githubusercontent.com/assets/4592712/19015978/4e4fd360-882c-11e6-84fc-250a63fbb766.png)

http://screencast.com/t/9NR5dRReAef

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
@vic-appirio can you please check this out?

**Comment by vic-appirio** [comment]
.SVG animations are not played under IE. We need to change the loader with .GIF

**Comment by fnisen** [comment]
@vic-appirio can Didi do this or should I assign to Vikas?
