### ISSUE TITLE
Observation and suggestion for description fields

### ISSUE THREAD

**Issue by coderhacker** [appirio-tech/connect-app#4308]
### Expected behavior
During description fields testing. I have observed a couple of suggestions. please find a below-attached screenshot with points

1.  border showing in red
2.  There is not any font color and background change option in the editor.
![image](https://user-images.githubusercontent.com/62358241/108718426-694fde80-7544-11eb-84df-8e19f0c9828d.png)
3.  There is not sub and sup option in the editor
![image](https://user-images.githubusercontent.com/62358241/108718515-8389bc80-7544-11eb-8bd1-c84dc23e8d82.png)
4. there is not an option for row and cell add and delete.
![image](https://user-images.githubusercontent.com/62358241/108718599-a1572180-7544-11eb-9c80-41fdd99c32e7.png)

--

#### Environment
- OS: Win 10
- Browser (w/version): all browsers and devices
- User role (client, copilot or manager): copilot
- Account used:

**Comment by maxceem** [comment]
> 1 border showing in red

Hmm, I don't have such an issue. We can investigate this.

@coderhacker we are using an editor which lets us store the data in Markdown format. Markdown format has various limitation, which doesn't allow us to add these features to the editor.

>2. There is not any font color and background change option in the editor.

Markdown doesn't support colors.

> 3. There is not sub and sup option in the editor

Markdown doesn't support sub and sup indexes.

> 4. there is not an option for row and cell add and delete.

If I click right mouse button I can see options to add/remove rows and columns on macOS. Couly you please check if you have such options or no?

![image](https://user-images.githubusercontent.com/146016/108720878-094c3e80-752a-11eb-85d7-728e01ccda54.png)
