### ISSUE TITLE
Typo: Design/Dev Intake Form

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4309]
<img width="681" alt="Screen Shot 2021-02-18 at 4 26 24 PM" src="https://user-images.githubusercontent.com/41118149/108769413-ce3c1200-750d-11eb-86e1-bdd0b6543f6d.png">

Remove extra "s's" at the end, to read: "Design add-ons" on the design/dev intake form.

**Comment by maxceem** [comment]
@vikasrohit this issue has to be fixed inside the Project Template. I don't have permission for this on PROD.

**Comment by vikasrohit** [comment]
Fixed on production.

**Comment by drasticdpk** [comment]
@vikasrohit  can you please guide us how can we verity it 
cc @lakshmiathreya

**Comment by coderhacker** [comment]
This is passed on dev 
![image](https://user-images.githubusercontent.com/62358241/111488256-180bc700-875f-11eb-97b1-1cdd7325b237.png)

**Comment by coderhacker** [comment]
![image](https://user-images.githubusercontent.com/62358241/111488796-949ea580-875f-11eb-9092-4721a6ebc1a3.png)

**Comment by coderhacker** [comment]
this is pass on prod 
![image](https://user-images.githubusercontent.com/62358241/111489803-79806580-8760-11eb-994c-1b060072841f.png)

**Comment by coderhacker** [comment]
![image](https://user-images.githubusercontent.com/62358241/111490154-c9f7c300-8760-11eb-8cf8-f8b028687bdc.png)
