### ISSUE TITLE
Remove 2 options from TaaS Intake Form

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4328]
remove the following values from the Role dropdown: `QA Tester`  and `QA Engineer`
 
 Before:
 
![image](https://user-images.githubusercontent.com/146016/108870582-ec366f00-7600-11eb-9de6-8934d4954cec.png)
 
 After:
 
![image](https://user-images.githubusercontent.com/146016/108870506-d9239f00-7600-11eb-8a6c-56aba20d6b74.png)

**Comment by maxceem** [comment]
This is done as HOTFIX:
- DEV https://github.com/appirio-tech/connect-app/pull/4313
- PROD https://github.com/appirio-tech/connect-app/pull/4314

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. The two options are removed.

![image](https://user-images.githubusercontent.com/55895538/109753159-14d3ef80-7c25-11eb-8005-196ebbe6a0d1.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

<img width="960" alt="4 options_prod" src="https://user-images.githubusercontent.com/55895538/109783673-96d80e80-7c4d-11eb-803a-c0b262f71e09.png">
