### ISSUE TITLE
When we click on the URL posted on the description; it is redirected to an invalid url 

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4329]
**Testing URL:** http://connect.topcoder-dev.com/new-project/taas-jobs

When we create a job using TaaS Intake form, then when we navigate in TaaS App and click the links, it's broken. The same issue we have in TaaS App 

- When we click on the URL posted on the description; it is redirected to `https://platform.topcoder-dev.com/taas/myteams/16873/positions/www.google.com` and displayed an error '"id" must be a valid GUID'

https://user-images.githubusercontent.com/42398485/108969022-881ab600-76a7-11eb-939e-cbb0222b18f0.mp4

**Comment by maxceem** [comment]
This is fixed and pushed to DEV by https://github.com/appirio-tech/connect-app/pull/4330

It's included in the PROD hotfix https://github.com/appirio-tech/connect-app/pull/4314

**Comment by sandhiyakavi** [comment]
Verified on Dev Env.

Clicking the links of the Job description in Taas app are redirecting to the correct url.


https://user-images.githubusercontent.com/55895538/109753888-5add8300-7c26-11eb-8274-5d6571cea465.mp4

**Comment by sandhiyakavi** [comment]
Verified on Prod. Working as expected.


https://user-images.githubusercontent.com/55895538/109783118-fb469e00-7c4c-11eb-9215-ec2627a32931.mp4

**Comment by lakshmiathreya** [comment]
This issue had prompted us to release a hotfix - needed immediate resolution - hence the correct priority should have been P0.
