### ISSUE TITLE
Page goes to the 'Specification' page when we add 'New Feature' in certain scenario

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#433]
### Expected behavior
-----------------------------------------------------------------
Must in the 'Project Features' window

### Actual behavior
-----------------------------------------------------------------
Page goes to the 'Specification' page when we add 'New Feature' in certain scenario

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Specification
- Click 'Add a custom feature'
- Don't Enter name
- Click ON --> Click on SAVE FEATURE button
- Try to close the popup by clicking the (x) button on top right
- Enter a name and description
- Click SAVE FEATURE

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_23-31-59](https://cloud.githubusercontent.com/assets/4592712/19016129/4936e546-882f-11e6-80ac-8f864450a004.png)

http://screencast.com/t/2JpQC01Ky4

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by fnisen** [comment]
No longer happening after changes to feature picker.
