### ISSUE TITLE
 Markdown Editor quick improvements #126

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4331]
Same like inside TaaS app we should remove some features from the editor which cause problems to us:

- Table - because cannot be converted properly to RCRM (in theory can, but somehow doesn't work)
- Tasks - because don't need and cannot be displayed in RCRM
- Indent - because of https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097
- Outdnet - because of https://github.com/topcoder-platform/taas-app/issues/100#issuecomment-785131097

Editor before:

![image](https://user-images.githubusercontent.com/146016/109140252-12751f80-7765-11eb-9f5e-1a74ded19d13.png)

After:

![image](https://user-images.githubusercontent.com/146016/109140530-58ca7e80-7765-11eb-8fde-660a0316bff7.png)

**Comment by maxceem** [comment]
This is fixed and pushed to DEV by https://github.com/appirio-tech/connect-app/pull/4330

It's included in the PROD hotfix https://github.com/appirio-tech/connect-app/pull/4314

**Comment by sandhiyakavi** [comment]
Verified in Dev. The features Table, Tasks, Indent and outdent are removed.

![image](https://user-images.githubusercontent.com/55895538/109752720-426c6900-7c24-11eb-81eb-ee14d7aea43e.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod. Table, Tasks, Indent and Outdent are removed.

<img width="960" alt="prod_removed" src="https://user-images.githubusercontent.com/55895538/109783530-714b0500-7c4d-11eb-8d83-8fefb9336e68.png">
