### ISSUE TITLE
Project Plan Template: Remove Discussions Moving Forward

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4335]
**Update**

- Remove the Discussions tab from all phases as a move-forward solution
- Historical Discussions on phases created prior to this release must remain visible

**Comment by SathyaJayabal** [comment]
@vikasrohit , verified the following in dev
1. Discussions not displayed for phases in the projects using the beta flag (new solution).
<img width="788" alt="Screenshot 2021-04-14 at 1 51 09 PM" src="https://user-images.githubusercontent.com/58783823/114678727-27b00880-9d29-11eb-9a66-256a131a1995.png">

2. Historical Discussions on phases created earlier work fine. User is able to add/view posts and attach files. 
<img width="761" alt="Screenshot 2021-04-14 at 1 54 00 PM" src="https://user-images.githubusercontent.com/58783823/114678751-2da5e980-9d29-11eb-957e-d03c6812d138.png">

**Comment by drasticdpk** [comment]
Verified.

**1. Remove the Discussions tab from all phases as a move-forward solution with bata=true project creation**

![image](https://user-images.githubusercontent.com/25297859/115723064-51a7a180-a39f-11eb-81f0-d8c8328a30e6.png)

**2. Historical Discussions on phases created prior to this release must remain visible** for old project

![image](https://user-images.githubusercontent.com/25297859/115723227-79970500-a39f-11eb-9682-29c7cfa3afc8.png)
