### ISSUE TITLE
Project Plan Template: Hide/Disable Timeline & Milestones

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4336]
**Update**

Hide and disable the "Timeline" tab and by consequence all milestone types on a project plan phase. This means:

- Moving forward from release, the "Timeline" tab should not be shown.
- Moving forward from release, the "Add Milestone" button should not be shown.
- Moving forward from release, the vertical timeline display of milestones, corresponding milestone text, etc. should not be shown. 
- Historical milestones on phases created prior to this release must still be displayed.

**Comment by SathyaJayabal** [comment]
@vikasrohit , verified the following
"Timeline" tab is not  shown in new project cerated with beta flag
<img width="783" alt="Screenshot 2021-04-14 at 3 44 27 PM" src="https://user-images.githubusercontent.com/58783823/114694582-51246080-9d38-11eb-8b9c-069cdfae6eb1.png">

"Add Milestone" button should is not shown in create phase or edit phase screens
<img width="761" alt="Screenshot 2021-04-14 at 3 45 12 PM" src="https://user-images.githubusercontent.com/58783823/114694719-76b16a00-9d38-11eb-9484-0d8c6f92a251.png">

The vertical timeline display of milestones, corresponding milestone text, etc. is not be shown.


Historical milestones on phases created prior to older projects are still displayed. The user can view/add/edit milestones.
<img width="759" alt="Screenshot 2021-04-14 at 3 47 18 PM" src="https://user-images.githubusercontent.com/58783823/114695104-dc055b00-9d38-11eb-9224-ae4fbcccbb35.png">

**Comment by drasticdpk** [comment]
Verified

![image](https://user-images.githubusercontent.com/25297859/115724472-b283a980-a3a0-11eb-858e-0891e9c30082.png)

![image](https://user-images.githubusercontent.com/25297859/115723928-30938080-a3a0-11eb-8ceb-a2d5dde716b8.png)



![image](https://user-images.githubusercontent.com/25297859/115724016-4739d780-a3a0-11eb-8328-b2a5ef7517aa.png)

**Comment by drasticdpk** [comment]
@SathyaJayabal , we can see full date in prod mode for phase desc please confirm,
![image](https://user-images.githubusercontent.com/25297859/115724741-f24a9100-a3a0-11eb-98cb-6d28db3b86cf.png)

**Comment by SathyaJayabal** [comment]
@drasticdpk , this is fine
https://github.com/appirio-tech/connect-app/issues/4350#issuecomment-824002131
