### ISSUE TITLE
Project Plan Template: Update Set-Up Requirements

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4337]
**Update**
These should be the only inputs when setting up a template:
Row 1 (*Required) - **"Title"**: [Text Field]
Row 2 (*Optional & New Field) - **"Description"**: [Large Text Field]
Row 3 (*Required) -
**"Start Date"**: [Date Entry]
**"End Date"**: [Date Entry]

**Comment by acshields** [comment]
Additonally note/context:
- A user should be able to view all fields on a phase (title, description, start date, end date) without having to click onto it.
- The functionality to add a milestone to a phase, change it's type, and enter multiple dates on the phase's timeline should be hidden/disabled. Ultimately, the only date information required will be one start and end date for the entire phase.

**Comment by SathyaJayabal** [comment]
@vikasrohit , according to the requirement description is  optional.
`Row 2 (*Optional & New Field) - "Description": [Large Text Field]`

I am not bale to create a phase without description value. the loading indicator keeps on displaying
<img width="1440" alt="Screenshot 2021-04-14 at 3 22 47 PM" src="https://user-images.githubusercontent.com/58783823/114691414-4a481e80-9d35-11eb-93e3-c3950fea06a1.png">

On editing an existing phase and removing the description we get the following error
<img width="1440" alt="Screenshot 2021-04-14 at 3 24 05 PM" src="https://user-images.githubusercontent.com/58783823/114691603-795e9000-9d35-11eb-8706-b4f52a5bde60.png">

**Comment by vikasrohit** [comment]
Ok, good catch. We need to fix it.

**Comment by mirzailhami** [comment]
Frontend UI was already fit the requirement above. Need to fix at the backend side for [phase request](https://api.topcoder-dev.com/v5/projects/17250/phases).

![Screen Shot 2021-04-16 at 08 46 40](https://user-images.githubusercontent.com/8240895/114960338-066a2c00-9e91-11eb-9527-63c9e108d793.png)

**Comment by vikasrohit** [comment]
@mirzailhami we can set the description field to `null` instead of sending empty to by pass the validation. We had the description field from long time back in api but we never used to send it from front end. So, I guess we can manage it from front end only.

**Comment by mirzailhami** [comment]
@vikasrohit using `null` did not work. It asked a `string`. So can we use " " `string` instead?

**Comment by vikasrohit** [comment]
For we might go with workaround, however, it does not seem right to me as we adding spaces. If it was empty string, it would have been okay. I guess we might slight changes in the API [validation](https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/phases/update.js#L16).

**Comment by SathyaJayabal** [comment]
Verified, We are able to create phase without entering description

**Comment by vikasrohit** [comment]
@mirzailhami can you please log a separate issue to track the changes we need to properly fix this issue? I mean instead of passing spaces we should be fixing the API endpoint to allow empty or null values.

**Comment by mirzailhami** [comment]
@vikasrohit logged.

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/115725490-9c2a1d80-a3a1-11eb-82b8-f8ef4a494f2c.png)
