### ISSUE TITLE
Project Plan Template: Phase Status Logic

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4339]
### Displayed Statuses
**_During the set-up of a phase, the creator should have these two decision options:_**
**“Save Draft”**
- If the creator does not want to publish the phase for client visibility, they can click “Save Draft”
- The phase should display a “Draft” label
**“Publish”**
- If the creator wants to publish the phase for client visibility, they can click “Publish”
- The phase status that displays will be determined by the logic explained below
- Clicking “Publish” will not override the start date entered by the creator, if its on a date in the future

**_Once published, the phase will display the following based upon user role:_**
**“Published”**
Once a phase is published, the Topcoder Employee and Copilot users should see a label that reads "Published." This will serve as a visual indication that the client can see the phase.  
**No Text Display**
Once a phase is published, the Client users do not need to see the "Published" label. 

### Hidden/Disabled Statuses
Because at this time we are not able to automate phase status logic (moving it from planned to active to complete) using the scheduler API, the best move forward approach will be to either remove these phase status hide/disable them from user view. Ultimately, the objectives with this change are as listed below:
- Copilot/Topcoder Employee users do not need to manually maintain a status of the phase after it is published
- Clients do not view an inaccurate status (i.e. it says "planned" but the start date has already passed). Because there is no automation we can have in place at this time, it would then be better to not display a status at all.

**Comment by vikasrohit** [comment]
@acshields do we need to keep the automation logic where we activate the challenge as soon as we publish/activate any phase in the project plan?

**Comment by vikasrohit** [comment]
@acshields one more thing, how would we mark a phase complete now?

**Comment by acshields** [comment]
@vikasrohit 

**Re: "do we need to keep the automation logic where we activate the challenge as soon as we publish/activate any phase in the project plan?"**

I am leaning towards "no" on this for two reasons, but want your input:
1. We are not going to be displaying the "active" status on the front-end, so I am not sure of what benefit this would give users.
2. If I am remembering correctly, this is the same logic that automatically changes the phase's dates once I publish it (for example, I put the start date as 4/10, but I publish the phase on 4/8 so the start date is overridden to 4/8). I received feedback from users that this behavior was confusing to them, so I specifically want to avoid continuing it.

**Re: how would we mark a phase complete now?**
Same thought as point 1 from above... If we aren't showing those statuses, does it matter? (it might due to a technical constraint I'm unaware of, which is why I want your feedback, but from the experience side I don't think this matters. People can see the dates). 

_Note for the future:_
As you know, I hope to use the scheduler service and synced challenge/task data to automate statuses in the future, at which time we would display them on the UI again. Examples of that conditional logic would be:
- When the earliest start date of a challenge/task synced to a phase arrives, move the phase to "active"
- When the latest end date of a challenge/task synced to the phase arrives, move the phase to "complete"
Just sharing this context as a note on where I want this feature to go in the future, so whatever we decide now doesn't conflict/prevent this.

**Comment by SathyaJayabal** [comment]
@vikasrohit , verified the following
1. User has two options while creating a phase, "Save Draft" and "Publish"
<img width="762" alt="Screenshot 2021-04-14 at 1 38 14 PM" src="https://user-images.githubusercontent.com/58783823/114676339-d43cbb00-9d26-11eb-93b3-d0f787f9f7dc.png">

2. When user selects "Save Draft", phase is created in draft status. Phase status is displayed as "Draft"
<img width="765" alt="Screenshot 2021-04-14 at 1 39 10 PM" src="https://user-images.githubusercontent.com/58783823/114676354-d7d04200-9d26-11eb-9762-b78f6848efdd.png">

3. Copilot is able to view the draft phases, but not the customer. Customer is able to view only published phases
<img width="1440" alt="Screenshot 2021-04-14 at 1 41 01 PM" src="https://user-images.githubusercontent.com/58783823/114676592-1239df00-9d27-11eb-8cdd-e79ee5b03eb1.png">

4. When user selects "publish" either while creating the phase or while editing a phase, the phase status is updated to published. 
<img width="767" alt="Screenshot 2021-04-14 at 1 42 21 PM" src="https://user-images.githubusercontent.com/58783823/114676763-444b4100-9d27-11eb-911f-725c6d49efe6.png">

5. If the start date of the phase is in the future, the publish does not override the start date of the phase.
https://user-images.githubusercontent.com/58783823/114677019-84aabf00-9d27-11eb-82a9-43398ff51d4e.mov

6. Customer is able to view published phases. They are also able to see the status as published. They should not be able to see the published text. A new issue created for this 
https://github.com/appirio-tech/connect-app/issues/4348

**Comment by drasticdpk** [comment]
**1. User has two options while creating a phase, "Save Draft" and "Publish"**

![image](https://user-images.githubusercontent.com/25297859/115711435-3afb4d80-a393-11eb-9933-eaec13bede5a.png)


**2. When user selects "Save Draft", phase is created in draft status. Phase status is displayed as "Draft"**

![image](https://user-images.githubusercontent.com/25297859/115712292-50bd4280-a394-11eb-8be9-f50e84aaf0ac.png)
 
**3. Copilot is able to view the draft phases, but not the customer. Customer is able to view only published phases**

![image](https://user-images.githubusercontent.com/25297859/115712768-e5c03b80-a394-11eb-9989-72b271150390.png)

**4. When user selects "publish" either while creating the phase or while editing a phase, the phase status is updated to published.** 

![image](https://user-images.githubusercontent.com/25297859/115712896-1607da00-a395-11eb-88f6-905aa684c585.png)

**For customer Role** 


![image](https://user-images.githubusercontent.com/25297859/115713154-6a12be80-a395-11eb-9b8d-c52ec953fd78.png)
