### ISSUE TITLE
[$40] Update: 'Manager' Copilot Invitation Permissions

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4341]
### Update 1
If there are no Copilots on a project, users in the Manager role should:
- Only see the "Request Copilot" button.
- Not see the "Manage" button. 

### Update 2
- If there is a Copilot on the project, users in the Manager role should:
- Continue to see the "Request Copilot" button.
- See the "Manage" button. When this button is clicked, the Manager user should:
-View the Copilots who are currently on the project
-View the "Remove" button next to the Copilots on the project
-Should not see the "Invite Copilot" capability at the bottom of the pop-up

Note: These conditions will not apply to users who have the Manager role and the Admin or TC Copilot Manager role. For those users, the permissions/capabilities of the Admin/TC Copilot Manager will supersede the Manager's permissions.

**Comment by vikasrohit** [comment]
> Should not see the "Invite Copilot" capability at the bottom of the pop-up

@acshields just to confirm, this is the only thing that is not implemented yet on production for Update 2, right? Every else from Update 2 is working as written.

**Comment by acshields** [comment]
@vikasrohit - yes, I believe that only 2 isn't updated. Just listed 1 in case I was wrong (it's not updated, or there is a bug) and so we can have it updated.

**Comment by vikasrohit** [comment]
Ok, specifically I meant that first two points of the Update 2 are also present as required, only point#3 is something which need to fix.

**Comment by acshields** [comment]
Yep!

**Comment by vikasrohit** [comment]
@acshields to be double sure, do we want to show the `Invite Copilot` button (in the Manage copilots popup) for the admins?

**Comment by vikasrohit** [comment]
@acshields it seems we already have whatever you listed in update 2, requirements. In other words current logic only allows admin and copilot manager to see the `Invite more copilots` section. Do you have any user which does not fall in this category and still seeing this section?

**Comment by drasticdpk** [comment]
Still having  manage button for Manager role .



Reference  : 
Project : https://connect.topcoder-dev.com/projects/17335 
User : topcoderconnect+copilotmanager@gmail.com  

![image](https://user-images.githubusercontent.com/25297859/118398110-e20f9400-b676-11eb-8f14-2d1d8e4396b2.png)

topcoderconnect+manager@gmail.com

![image](https://user-images.githubusercontent.com/25297859/118398274-96111f00-b677-11eb-8f9d-76a41e490657.png)

Let us know for anything. @mirzailhami

**Comment by mirzailhami** [comment]
@vikasrohit I re-run this build and deploy was successful, but connect.topcoder-dev.com is still not updating, am I missed something?

![image](https://user-images.githubusercontent.com/8240895/118401535-4854e080-b690-11eb-94d9-0b8ea5555d4b.png)

**Comment by vikasrohit** [comment]
Yes, I just made the feature branch depoyable.

**Comment by vikasrohit** [comment]
@drasticdpk just deployed the feature branch to dev env. Please retest now.

**Comment by drasticdpk** [comment]
Verified on Dev env,
![image](https://user-images.githubusercontent.com/25297859/118439512-ddde8780-b705-11eb-86e9-e83fddc1afe5.png)
![image](https://user-images.githubusercontent.com/25297859/118440314-35c9be00-b707-11eb-9b64-a13895ac7e46.png)

**Comment by drasticdpk** [comment]
@lakshmiathreya , 
We need manager role to verify this issue, please assist on this.

**Comment by lakshmiathreya** [comment]
Manager role sees only Request Copilot in Prod:
<img width="1680" alt="Screenshot 2021-05-18 at 3 59 08 PM" src="https://user-images.githubusercontent.com/51733042/118636700-9681f500-b7f2-11eb-8553-29506691d3a7.png">

**Comment by lakshmiathreya** [comment]
Manager role sees Manage and Request Copilot - only give Remove option:

<img width="1680" alt="Screenshot 2021-05-18 at 4 05 44 PM" src="https://user-images.githubusercontent.com/51733042/118637596-9d5d3780-b7f3-11eb-8a00-1cbbb0631c05.png">

**Comment by lakshmiathreya** [comment]
Additional screenshots: Admin Role - 
<img width="1680" alt="Screenshot 2021-05-18 at 5 32 43 PM" src="https://user-images.githubusercontent.com/51733042/118647596-25950a00-b7ff-11eb-932c-8257eaba9b9e.png">
Copilot Manager Role - 
<img width="1680" alt="Screenshot 2021-05-18 at 5 35 30 PM" src="https://user-images.githubusercontent.com/51733042/118647880-7a388500-b7ff-11eb-94f3-e141d4ccbda5.png">
