### ISSUE TITLE
Editing of Phase Start date and End date is not working as expected

### ISSUE THREAD

**Issue by SathyaJayabal** [appirio-tech/connect-app#4346]
1. Edit Phase
2. Update the start and end dates of the phase
Expected: Phase dates must be updated based on user input
Actual: Phase duration is always 4 days and the updated dates are not reflected.

https://user-images.githubusercontent.com/58783823/114514085-89547200-9c58-11eb-9a25-e9ac8d329a88.mov

**Comment by vikasrohit** [comment]
Thanks for catching it, I am expecting such issues.

**Comment by vikasrohit** [comment]
@SathyaJayabal it is fixed and deployed to dev

**Comment by SathyaJayabal** [comment]
@vikasrohit , works fine now. 

Does the total days get calculated only based on published phases?
<img width="774" alt="Screenshot 2021-04-14 at 12 12 53 PM" src="https://user-images.githubusercontent.com/58783823/114665553-d1d46400-9d1a-11eb-9861-8255146efb4c.png">

**Comment by vikasrohit** [comment]
Yes, @maxceem please correct me if I am wrong here.

**Comment by maxceem** [comment]
You are right @vikasrohit. Only active and completed phases are counted there https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/projectHelper.js#L112

**Comment by drasticdpk** [comment]
Verified.

![image](https://user-images.githubusercontent.com/25297859/115726695-ae588b80-a3a2-11eb-8aed-4cb4ef9f24b8.png)
