### ISSUE TITLE
Phase description not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [appirio-tech/connect-app#4347]
As per this requirement, the phase description must be displayed.
https://github.com/appirio-tech/connect-app/issues/4337#issuecomment-809631244

Actual: Phase description is not displayed
<img width="780" alt="Screenshot 2021-04-13 at 1 07 30 PM" src="https://user-images.githubusercontent.com/58783823/114514733-3af3a300-9c59-11eb-8aad-9f4003a22c07.png">

**Comment by SathyaJayabal** [comment]
Verified on dev. Description field is displayed.
<img width="767" alt="Screenshot 2021-04-20 at 9 12 12 AM" src="https://user-images.githubusercontent.com/58783823/115334200-93c2be80-a1b8-11eb-84f2-d7ad3af8ecac.png">

**Comment by drasticdpk** [comment]
Verified 

![image](https://user-images.githubusercontent.com/25297859/115715785-38e7bd80-a398-11eb-9165-61d6bd94e05b.png)
