### ISSUE TITLE
Customer must not see the status of the phase

### ISSUE THREAD

**Issue by SathyaJayabal** [appirio-tech/connect-app#4348]
Based on this req, the customer team must not see the published status. Since they do not see the draft status too, we could remove the status column for the customers.
https://github.com/appirio-tech/connect-app/issues/4339#issue-826435818

```
No Text Display
Once a phase is published, the Client users do not need to see the "Published" label.
```

**Comment by vikasrohit** [comment]
@SathyaJayabal can you please add screenshot of how it is looking for the customer right now?

**Comment by SathyaJayabal** [comment]
@vikasrohit 
<img width="789" alt="Screenshot 2021-04-15 at 9 54 36 AM" src="https://user-images.githubusercontent.com/58783823/114813887-a3b15b80-9dd0-11eb-968b-5a94406c18d8.png">

**Comment by SathyaJayabal** [comment]
@mirzailhami @vikasrohit , The status label has been removed, but the phase status is still visible for the customers.
example:
https://connect.topcoder-dev.com/projects/17270

Customer user: tester1234
<img width="1440" alt="Screenshot 2021-04-20 at 9 31 38 AM" src="https://user-images.githubusercontent.com/58783823/115335717-66c3db00-a1bb-11eb-906f-2fcda2a52fa4.png">

**Comment by vikasrohit** [comment]
@mirzailhami we need to hide actual phase status as well from customers.

**Comment by mirzailhami** [comment]
> @mirzailhami we need to hide actual phase status as well from customers.

Ok, @diwosuwanto working on it.

**Comment by SathyaJayabal** [comment]
I dont see the fix yet @mirzailhami , is it deployed ?

**Comment by mirzailhami** [comment]
@SathyaJayabal deployed was not successful. Could you check pls @vikasrohit.
![Screen Shot 2021-04-20 at 21 59 04](https://user-images.githubusercontent.com/8240895/115418573-c950c180-a223-11eb-825e-1b1b4055b0e9.png)

**Comment by vikasrohit** [comment]
@mirzailhami there is a lint error https://app.circleci.com/pipelines/github/appirio-tech/connect-app/472/workflows/019b14dc-c006-41ef-a306-bc935dd7c868/jobs/5677

**Comment by SathyaJayabal** [comment]
@mirzailhami @vikasrohit , the phase status must be removed only for the new simplified projects for the customer. Older phases should still display the phase statuses.

Example: This is an older project 
https://connect.topcoder-dev.com/projects/16573/

The customer must see the phase status details
Manager View:
<img width="780" alt="Screenshot 2021-04-21 at 2 27 07 PM" src="https://user-images.githubusercontent.com/58783823/115526497-b8e52900-a2ad-11eb-8960-d41ede384745.png">

Customer view. The phase statuses must be displayed here.
<img width="774" alt="Screenshot 2021-04-21 at 2 27 24 PM" src="https://user-images.githubusercontent.com/58783823/115526516-be427380-a2ad-11eb-80ac-7ff5dea8ec55.png">

**Comment by vikasrohit** [comment]
You are right @SathyaJayabal. @mirzailhami we need to fix it.

**Comment by vikasrohit** [comment]
@mirzailhami I am pushing a commit for it.

**Comment by vikasrohit** [comment]
@SathyaJayabal can you please retest it?

**Comment by SathyaJayabal** [comment]
@vikasrohit , i dont see it yet
<img width="788" alt="Screenshot 2021-04-21 at 4 38 53 PM" src="https://user-images.githubusercontent.com/58783823/115544353-1da97f00-a2c0-11eb-9a86-b8d81df9f305.png">

**Comment by vikasrohit** [comment]
ohk, which user you are using for testing?

**Comment by vikasrohit** [comment]
@SathyaJayabal can you please share the test user details on Slack?

**Comment by vikasrohit** [comment]
Try now @SathyaJayabal Please try different combination of phase status, project version (simple vs existing) and customer/non-customer

**Comment by SathyaJayabal** [comment]
@vikasrohit , now the published status for manager view(simplified project) is displayed with a progress indicator, which was not there before. Other combinations are good.
<img width="770" alt="Screenshot 2021-04-21 at 7 08 05 PM" src="https://user-images.githubusercontent.com/58783823/115563213-ec877980-a2d4-11eb-894f-687864a206ef.png">

**Comment by vikasrohit** [comment]
@SathyaJayabal fixed the progress status.

**Comment by SathyaJayabal** [comment]
@vikasrohit , now the `published` text is also missing for Manager(simplified project). Other combinations are good.
<img width="759" alt="Screenshot 2021-04-22 at 1 27 09 PM" src="https://user-images.githubusercontent.com/58783823/115677779-76cfec00-a36e-11eb-828a-b4fa10481dc2.png">

**Comment by vikasrohit** [comment]
Oh crap!! This is confusing 😕 Let fix it. Thanks for noticing these, really appreciated.

**Comment by vikasrohit** [comment]
Deployed to dev for testing.

**Comment by SathyaJayabal** [comment]
Manager role: simplified project
<img width="759" alt="Screenshot 2021-04-22 at 3 19 55 PM" src="https://user-images.githubusercontent.com/58783823/115694210-4728e000-a37e-11eb-92d0-2382c7c79d70.png">
Manager Role: old project
<img width="759" alt="Screenshot 2021-04-22 at 3 20 13 PM" src="https://user-images.githubusercontent.com/58783823/115694246-4f811b00-a37e-11eb-9167-6692395ea55c.png">
Customer role: simplified project
<img width="765" alt="Screenshot 2021-04-22 at 3 21 06 PM" src="https://user-images.githubusercontent.com/58783823/115694398-717a9d80-a37e-11eb-924e-244c6312fbf2.png">
Customer Role: old project
<img width="757" alt="Screenshot 2021-04-22 at 3 21 50 PM" src="https://user-images.githubusercontent.com/58783823/115694452-7e978c80-a37e-11eb-9101-3d6b2b8e0edc.png">

**Comment by drasticdpk** [comment]
Verified :
**Customer role** 

![image](https://user-images.githubusercontent.com/25297859/115713107-5a937580-a395-11eb-962d-184bd75200cf.png)

**Copilot role** 

![image](https://user-images.githubusercontent.com/25297859/115713255-844c9c80-a395-11eb-882b-ddcede3ff93c.png)
