### ISSUE TITLE
Additional "Description" Field Updates

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4349]
**Update**
Set-Up/Editing: Increase the size (height) of the "Description" field during set-up so the user providing the description knows they can enter a few sentence description and can easily edit any typos. 

<img width="720" alt="Screen Shot 2021-04-14 at 3 06 34 PM" src="https://user-images.githubusercontent.com/41118149/114786490-0bb16480-9d33-11eb-9619-817e66ea10f8.png">

**Question**
Is there a character limit on the new "Description" field?

**Comment by vikasrohit** [comment]
> Is there a character limit on the new "Description" field?

Yes, 255. This limit is at both front end and backend.

**Comment by acshields** [comment]
@vikasrohit can we also add subtext that reads: "255 character maximum" under the "Description" header?

**Comment by SathyaJayabal** [comment]
@mirzailhami , The size of the description box is increased. Pending fixes.

- Implement FE limitation of 255 characters. IE user should not be able to enter more than 255 characters on the text area.
<img width="1440" alt="Screenshot 2021-04-20 at 9 11 47 AM" src="https://user-images.githubusercontent.com/58783823/115335248-6c6cf100-a1ba-11eb-94e1-6aae5f3000e2.png">

- add subtext that reads: "255 character maximum" under the "Description" header

**Comment by mirzailhami** [comment]
@diwosuwanto is working on this issue and can`t find an easy way to use maxLength attribut. @vikasrohit I think we need to update [connectv2 TextArea](https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Formsy/Textarea.jsx) component and add new attribut `maxLength={maxLength}` for [AutoresizeTextarea](https://github.com/appirio-tech/react-components/blob/97ba97c96d73ed5985c4d2800e967eb418555e74/components/Formsy/Textarea.jsx#L64) and [textarea](https://github.com/appirio-tech/react-components/blob/97ba97c96d73ed5985c4d2800e967eb418555e74/components/Formsy/Textarea.jsx#L78). I can see maxLength already in [TextInput](https://github.com/appirio-tech/react-components/blob/97ba97c96d73ed5985c4d2800e967eb418555e74/components/Formsy/TextInput.jsx#L74), but cant find it in TextArea.

**Comment by vikasrohit** [comment]
Sounds reasonable to me. One more thing to try before adding maxLength support to the TextArea, can we increase the height of the textinput instead? I mean we can use TextInput instead of TextArea for description field because as of now it is limited to 255 characters only which is not a big number to use text area. If we can render the text input as bigger text input, we can avoid extra changes for now. Otherwise, please go ahead and add support for maxLength to TextArea.

**Comment by mirzailhami** [comment]
@vikasrohit  Currently we dont have AutoresizeTextarea in TextBox component, using TextBox with multiline support will need to update component too.

I already send [PR](https://github.com/appirio-tech/react-components/pull/361).

**Comment by vikasrohit** [comment]
@mirzailhami I have merged the PR. Do we have changes ready for using the maxLength in connect app?

**Comment by mirzailhami** [comment]
@vikasrohit ok thanks. It is working now with 255 maxLength. @diwosuwanto is adding subtext below "Description" header now and will send PR soon.

**Comment by mirzailhami** [comment]
@vikasrohit Is it ok using this here instead of below "Description" label? Just realized that label was coming from component, and we dont need to update component using this solution.

![Screen Shot 2021-04-21 at 20 35 40](https://user-images.githubusercontent.com/8240895/115563112-63c30a80-a2e1-11eb-9130-8892b350b2be.png)

**Comment by vikasrohit** [comment]
Yes, this one is perfect. No issues. @acshields your thoughts?

**Comment by vikasrohit** [comment]
@SathyaJayabal this one is also ready for review. Should be last before prod release.

**Comment by SathyaJayabal** [comment]
@vikasrohit , i dont see the character limit subtext.

FE validation for 255 characters is good.
<img width="766" alt="Screenshot 2021-04-22 at 3 16 43 PM" src="https://user-images.githubusercontent.com/58783823/115693780-dda8d180-a37d-11eb-8109-7ae74773ab79.png">

**Comment by mirzailhami** [comment]
@SathyaJayabal I can see it here.

![Screen Shot 2021-04-22 at 16 55 49](https://user-images.githubusercontent.com/8240895/115695165-bce77880-a38b-11eb-890e-f0d5fd4137a3.png)

**Comment by SathyaJayabal** [comment]
@mirzailhami , sorry, it should have a cache issue. I see it now.
<img width="771" alt="Screenshot 2021-04-22 at 3 34 44 PM" src="https://user-images.githubusercontent.com/58783823/115696451-5577fb80-a380-11eb-8f0a-fef197b9f096.png">
cc @vikasrohit

**Comment by drasticdpk** [comment]
verified 

Reference 

![image](https://user-images.githubusercontent.com/25297859/115715573-ff16b700-a397-11eb-89d7-cf8e6d7db496.png)



![image](https://user-images.githubusercontent.com/25297859/115715513-edcdaa80-a397-11eb-9330-4576cca6d8c5.png)
