### ISSUE TITLE
Previously entered text for 'Questions and Specifications' is display

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#435]
### Expected behavior
-----------------------------------------------------------------
Previously entered text for 'Questions and Specifications' must not display when we save the settings with the 'Skip...." and then uncheck it

### Actual behavior
-----------------------------------------------------------------
Previously entered text for 'Questions and Specifications' is display

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (eg: ABCD) and go to Specification
- In 'Questions and Specifications'
- What is the goal of your application? How will people use it? --> Test
- Who are the users of your application? --> Test
- Fill all the other required data
- Click Save Changes
- Now Go Back to the Projects Table
- Select the same Project (eg: ABCD)
- Go to Specification
- In 'Questions and Specifications'
- What is the goal of your application? How will people use it? --> Skip question - I have a document (will upload at end of section)
- Who are the users of your application? --> Skip question - I have a document (will upload at end of section)
- Click Save Changes
- Now Go Back to the Projects Table
- Select the same Project (eg: ABCD)
- Now In 'Questions and Specifications'
- Un-Check the "Skip question - I have a document (will upload at end of section)"
- Check the textboxes

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_23-44-50](https://cloud.githubusercontent.com/assets/4592712/19016205/12bfeb96-8831-11e6-9cac-6cfe02f7b959.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
Working as expected.
