### ISSUE TITLE
[$40] Phase description must allow empty or null values instead of space string

### ISSUE THREAD

**Issue by mirzailhami** [appirio-tech/connect-app#4358]
### Expected behavior
Optionally allow phase description to be empty or null at API endpoint for phases patch request.

### Actual behavior
Does not allow phase description to be empty or null at API endpoint. Now in the FE, we use space string to allow empty description but it will need to be updated later (based on [this](https://github.com/appirio-tech/connect-app/issues/4337#issuecomment-822309458)). 

### Steps to reproduce the problem
1. Add New Phase
2. Enter title
3. Select Start Date & End Date
4. _Leave the description empty_
5. Save Draft

### Screenshot/screencast
![Screen Shot 2021-04-16 at 08 46 40](https://user-images.githubusercontent.com/8240895/114960338-066a2c00-9e91-11eb-9527-63c9e108d793.png)

**Comment by vikasrohit** [comment]
@mirzailhami we need changes in tc-project-service (some where [here](https://github.com/topcoder-platform/tc-project-service/blob/develop/src/routes/phases/update.js#L16) and in Connect app both for this. Issue assignee might have to create PRs for the both repos if required. It all depends on the solution created by the assigned, all we want is to get rid of the workaround of passing empty spaces.

**Comment by mirzailhami** [comment]
@vikasrohit  No need to update tc-project-service. PR sent for this issue. The error caused by `description` without string value. Reproduce here:
```
curl -d '{"name":"Phase name", "description":"", "status": "Draft"}' -H "Content-Type: application/json" -X POST https://untitled-ryiz6nkgo0qb.runkit.sh/phases
```

It should not pass the `description` into payload if it has no value/empty/null. Verification here:
```
curl -d '{"name":"Phase name", "status": "Draft"}' -H "Content-Type: application/json" -X POST https://untitled-ryiz6nkgo0qb.runkit.sh/phases
```

Console log: https://runkit.com/logs/mirzailhami/60a16ba3eef5c8001a9c4fd9/branches/master

**Comment by vikasrohit** [comment]
Good to know that, I was expecting something like this because we had the support for `description` field in API from very long back but we did not have `description` field in UI, so if it was working there, it should work now as well.

btw, just curious, these `runkit` links, does not expose your security token to users without authentications, right?

**Comment by mirzailhami** [comment]
No it does not. Just a nodeJS virtual server to run Javascript on web (seems like stackblitz for TS). I saw the description was already in `optional()`, just curious why it throw error. Using this runkit would be faster to debug than running `npm i` locally in our machine.

**Comment by drasticdpk** [comment]
Verified on Dev env 
![image](https://user-images.githubusercontent.com/25297859/118444292-a58e7780-b70c-11eb-9409-62e7c0896e4d.png)

**Comment by drasticdpk** [comment]
Verified on Prod env
![image](https://user-images.githubusercontent.com/25297859/118631542-50776200-b7ef-11eb-9df4-6ea44028a7d8.png)
