### ISSUE TITLE
Uploading a File is required; But can save changes the project without it

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#436]
### Expected behavior
-----------------------------------------------------------------
Must validation the file upload

### Actual behavior
-----------------------------------------------------------------
Uploading a File is required; But can save changes the project without it

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project (eg: https://connectv2.topcoder-dev.com/projects/459/specification)
- Go to Specification
- In 'Questions and Specifications'
- What is the goal of your application? How will people use it? --> Skip question - I have a document (will upload at end of section)
- Who are the users of your application? --> Skip question - I have a document (will upload at end of section)
- Fill all the other required data
- Click Save Changes without uploading a File
- Because previously user Skip questions in 'Questions and Specifications' and opted to upload a file; Sp file upload must validate when user click on Save Changes

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_23-49-51](https://cloud.githubusercontent.com/assets/4592712/19016232/c8ad98d6-8831-11e6-9182-8165a892de49.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment]
Valid.

**Comment by parthshah** [comment]
This is working as expected.
