### ISSUE TITLE
Few Project Tabs missing for new projects

### ISSUE THREAD

**Issue by SathyaJayabal** [appirio-tech/connect-app#4361]
In the simplified project, Scope, Reports and assets library are missing
<img width="1440" alt="Screenshot 2021-04-20 at 4 22 30 PM" src="https://user-images.githubusercontent.com/58783823/115384772-0a7dad00-a1f5-11eb-8614-798c17889e3c.png">
Instead we have a specification tab which loads a blank page

<img width="1437" alt="Screenshot 2021-04-20 at 4 23 34 PM" src="https://user-images.githubusercontent.com/58783823/115384845-1f5a4080-a1f5-11eb-84a4-d7eaf6d4b59f.png">
<img width="1440" alt="Screenshot 2021-04-20 at 4 24 03 PM" src="https://user-images.githubusercontent.com/58783823/115385840-3c434380-a1f6-11eb-81a8-8755f9726fd9.png">

cc @vikasrohit

**Comment by vikasrohit** [comment]
@SathyaJayabal Fix deployed to dev.

**Comment by SathyaJayabal** [comment]
@vikasrohit , the scope link is redirected to "specification" link and loads a blank page in the simplified project. Thats not the case in the existing projects.

example:
Simplified projects
https://connect.topcoder-dev.com/projects/17276/
https://connect.topcoder-dev.com/projects/17274
click on scope link

Existing Project
https://connect.topcoder-dev.com/projects/17275/scope

**Comment by vikasrohit** [comment]
Thanks @SathyaJayabal for catching it. Fixed and deployed to dev.

**Comment by SathyaJayabal** [comment]
@vikasrohit , looks good now
<img width="1440" alt="Screenshot 2021-04-21 at 4 41 12 PM" src="https://user-images.githubusercontent.com/58783823/115544602-6b25ec00-a2c0-11eb-8bb8-303d81df0704.png">

**Comment by drasticdpk** [comment]
Verified 
![image](https://user-images.githubusercontent.com/25297859/115714012-616eb800-a396-11eb-83f7-e3b568d94864.png)
