### ISSUE TITLE
[$10] Cancel button in Add Milestone form does not work

### ISSUE THREAD

**Issue by mirzailhami** [appirio-tech/connect-app#4362]
### Expected behavior
Should close/hide the form.

### Actual behavior
It did not close the form.

### Steps to reproduce the problem
- Click on phase card
- Click "Add Milestone" button
- Click "Cancel" button

### Screenshot/screencast
![Screen Shot 2021-04-21 at 21 39 01](https://user-images.githubusercontent.com/8240895/115572753-66762d80-a2ea-11eb-8c33-3bb9dd234c69.png)

**Comment by vikasrohit** [comment]
Thanks @mirzailhami for noticing the bug. Could you please add more details like which environment (prod vs dev) you are seeing this issue. Also, which type (manager or copilot) of user is seeing this issue?

**Comment by SathyaJayabal** [comment]
@vikasrohit , I can see it both prod and dev. Click on a phase and try to add a milestone.

**Comment by vikasrohit** [comment]
That means it is not regression out of current changes.

**Comment by mirzailhami** [comment]
@vikasrohit Both in prod & dev, testing using copilot role.

**Comment by drasticdpk** [comment]
Verified on Dev Mode 
Reference : 
https://monosnap.com/file/sAi07gmBEVUf8OrwFxPQ1olNxOxykI
![image](https://user-images.githubusercontent.com/25297859/118397690-fb174580-b674-11eb-8e1d-88bf4ae2470b.png)

**Comment by drasticdpk** [comment]
Verified on Prod env
![image](https://user-images.githubusercontent.com/25297859/118631655-71d84e00-b7ef-11eb-8f98-afc2614f1912.png)
