### ISSUE TITLE
Keep selected section when back

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#437]
Expected behavior

Keep selected section when back tab.
 
Actual behavior

The selected section is not kept.
   
Steps to reproduce the problem

    Login into application as manager role.

   New Project.

   Select Prototype an app section.

   Select the tab section with name Other Work.

   Select the previous tab App Design & Dev back.

Environment

    OS: Windows 7
    Browser (w/version): IE 11.0
    User role (client, copilot or manager): manager
    Account used: pat_monahan

![1](https://cloud.githubusercontent.com/assets/5114907/19016249/4e14dd5a-881d-11e6-803c-2702458423c6.png)

**Comment by mahestro** [comment]
Not a bug. It's expected.

**Comment by fnisen** [comment]
Will address this when we create the new product "menu/catalog"
