### ISSUE TITLE
Provide a way to edit Project Name & Description

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#438]
While project name is visible on connect UI, description provided when project is first created is not displayed on Project Details view. Neither of these fields are editable from Connect UI.

**Comment by vic-appirio** [comment]
Let's start with the project description first. Project name shouldn't be editable after creation. We need to add the project settings section as well.

![screen shot 2016-10-07 at 1 03 03 pm](https://cloud.githubusercontent.com/assets/8484061/19203850/6d0c0b78-8c8e-11e6-9530-fd9b79e2323e.png)

**Comment by fnisen** [comment]
Being addressed by https://github.com/appirio-tech/connect-app/issues/469
