### ISSUE TITLE
Show billing account expiration alert in project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#4380]
To prevent over billing and wrong BA charged for challenges, we need to visually show some alert to the user when they are in the Connect and the BA associated to the project is inactive.

- [x]  Display pop-up message to Topcoder Employees and Copilots when they access the project, until the expired billing account is updated
- [x] Display an “!” icon on the Project Settings tab until the expired billing account is updated
- [x] Display the word “Expired” in red text next to the billing account field and show as disabled

**Comment by vikasrohit** [comment]
fyi @ajefts

**Comment by drasticdpk** [comment]
@vikasrohit , 
To meet the above scenario , please provide us one project which billing account is expired. 

**suggestion**
Can we alert to user before X no. of remaining date instead of after expired.

**Comment by vikasrohit** [comment]
> Can we alert to user before X no. of remaining date instead of after expired.

Not in scope yet due to technical limiatations.

**Comment by vikasrohit** [comment]
You can use https://connect.topcoder-dev.com/projects/17236/, it should have a BA that is inactive.

**Comment by drasticdpk** [comment]
Verified. 
https://user-images.githubusercontent.com/25297859/120204750-e330eb80-c248-11eb-8ca6-8aa6f6ffb6e8.mp4

here is regression of this requirement 
- This warning message never disappear, it only should be display only expired billing acc. 
![image](https://user-images.githubusercontent.com/25297859/120206589-1b392e00-c24b-11eb-8b65-8cd431c2e69b.png)

**Comment by vikasrohit** [comment]
Good observation @drasticdpk please log it as separate issue and we would discuss how to handle it in coming weeks.

**Comment by vikasrohit** [comment]
@drasticdpk can you please log separate follow up issue for it? We can track it separately sa we didn't have clear requirements for the case where there is no billing account.

**Comment by drasticdpk** [comment]
Verified on Prod mode 
![image](https://user-images.githubusercontent.com/25297859/121492623-bde56f80-c9f6-11eb-83a7-c48a6a5d516c.png)
