### ISSUE TITLE
Can't Upload Project Attachments

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4385]
### Expected behavior
Should be able to upload an asset to a project.

### Actual behavior
Getting the following error:  

![image](https://user-images.githubusercontent.com/3812270/119556559-2d0f6280-bd6d-11eb-819d-1acbadab4833.png)

- 2 users have tested and get the same response on this project:  https://connect.topcoder.com/projects/28237/assets
- I've also tried it on another project with the same result.

### Steps to reproduce the problem
- Visit a project.
- Click Assets
- Upload file
- Click the "Share with All Project Members" button

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/3812270/119556722-54fec600-bd6d-11eb-940d-bd4df8156543.png)

--

**Comment by ajefts** [comment]
fyi @mtwomey

**Comment by drasticdpk** [comment]
@vikasrohit , 
I am unable to replicate the scenario , for me it is working as expected.

**Reference**
![image](https://user-images.githubusercontent.com/25297859/119608955-8384ab80-be16-11eb-99e8-0189f47af3ff.png)

**Comment by vikasrohit** [comment]
@ajefts I tried to upload the file to the same project, and it seems to work for me as well. can you please retry, may be someone from the team has fixed the S3 buckets or something.
