### ISSUE TITLE
This warning message never disappear for billing acc.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4391]
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/120637387-8fafdf00-c48e-11eb-86a3-ae6885f09c89.png)

https://connect.topcoder-dev.com/projects/17236/
https://github.com/appirio-tech/connect-app/issues/4380#issuecomment-851523455

**Comment by vikasrohit** [comment]
Thanks @drasticdpk

**Comment by vikasrohit** [comment]
@drasticdpk this is ready for testing.

**Comment by drasticdpk** [comment]
Verified on Prod mode 
![image](https://user-images.githubusercontent.com/25297859/121492922-0a30af80-c9f7-11eb-8a96-c55d301fc66f.png)
![image](https://user-images.githubusercontent.com/25297859/121495139-16b60780-c9f9-11eb-9513-5f0156ecc2b3.png)

Note: There is no other billing account loaded, so I am making pass. If anything we can re-open this issue.

**Comment by vikasrohit** [comment]
![](https://user-images.githubusercontent.com/25297859/121495139-16b60780-c9f9-11eb-9513-5f0156ecc2b3.png)

In this image, @drasticdpk Ideally there would be NO alert icon in the left menu as well, if there is no BA is attached to a project. You might have removed the BA from the drop down to test the fix, in that case the left menu might show the alert but as soon as you save and refresh the page, the alert in the left menu should go away as well.
