### ISSUE TITLE
Fix automation script- Phase Creation

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4392]
We have some changes on Phase creation screen, so test case is getting fail, Please fix it. 
Branch : connect-automation

Reference : 
![image](https://user-images.githubusercontent.com/25297859/121171373-26f1a980-c876-11eb-8372-43ec5bbea2ef.png)

**Comment by nursoltan-s** [comment]
Fixed with this PR: https://github.com/appirio-tech/connect-app/pull/4396

![Uploading screencapture-file-Users-nursoltan-s-workspace-connect-app-connect-automation-test-results-TestResult-html-2021-06-09-15_35_32.png…]()

**Comment by drasticdpk** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/25297859/121347416-e57cff00-c946-11eb-9714-22167c5dc03d.png)

**Comment by lakshmiathreya** [comment]
@drasticdpk can you add milestone for this pls?
