### ISSUE TITLE
[$30] Copilot Feedback Form

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4399]
New Feature:

Add a feature to allow a project user to leave feedback for the copilots on the project. 

We have a typeform to handle the capture of the feedback:  https://topcoder.typeform.com/to/vgqiBXdk#copilot=xxxxx&projectid=xxxxx&submitter=xxxxx

Let's add a link/action next to each copilot so that a project user can leave individual feedback for each copilot:
![image](https://user-images.githubusercontent.com/3812270/123826697-02657c00-d8ce-11eb-931c-f43182910041.png)

Note that the TypeForm URL needs to have the copilot handle, project_id, and handle of the person submitting the feedback.

Nice to have:  Do not provide the feedback option to Copilots on the project.  If the current user is a copilot on the project, then hide the feedback links.

**Comment by vikasrohit** [comment]
@yoution can you please wrap this one quickly?

**Comment by yoution** [comment]
@vikasrohit please assign to me

**Comment by yoution** [comment]
@vikasrohit please review

**Comment by vikasrohit** [comment]
@yoution it looks good. Can you please style the Feedback button to look like `Manage` button and also please change `Feed Back` to `Feedback` or better can we use the icon for feedback which is there down at the bottom for the application feedback link?

**Comment by yoution** [comment]
@vikasrohit 
how about this one?
![image](https://user-images.githubusercontent.com/3863914/124921863-7240d880-e02b-11eb-9b98-19296effbead.png)

**Comment by yoution** [comment]
change to this style, please review https://github.com/appirio-tech/connect-app/pull/4404
on the other hand, there is no payment in this ticket 
![image](https://user-images.githubusercontent.com/3863914/124925632-3a3b9480-e02f-11eb-8f74-fbe8a7cdf9f6.png)

**Comment by vikasrohit** [comment]
@yoution screenshot looks good, I have just merged it to feature branch. Will check on dev and come back to you.

I have also updated the prize money for it, let me know if it is not okay.

**Comment by lakshmiathreya** [comment]
-- Verified Copilot feedback form for Manager role.
-- @vikasrohit the form is visible for Copilot role as well - pls clarify regarding this.

**Comment by lakshmiathreya** [comment]
-- Team member is able to see the feedback form as well - pls clarify regarding this.

**Comment by vikasrohit** [comment]
> -- @vikasrohit the form is visible for Copilot role as well - pls clarify regarding this.
@lakshmiathreya good catch here. We haven't thought of role based access yet. We can log it as separate issue and handle it later.

> -- Team member is able to see the feedback form as well - pls clarify regarding this.

I think that is in fact the requirement, we want any project member to be able to do so, however, we just need to confirm about copilots. Most probably we won't allow copilots to give feedback for themselves. :) @ajefts what are your thoughts?

**Comment by lakshmiathreya** [comment]
yes @vikasrohit - Team member feedback is the primary intent I guess. Just need clarification regarding form visibility for Copilot.

**Comment by vikasrohit** [comment]
Lets log a separate issue for that, we will get it fixed in next cycle.

**Comment by lakshmiathreya** [comment]
The form visibility needs to be Role based. Closing the Issue - pending fix for Copilot role visibility tracked in https://github.com/appirio-tech/connect-app/issues/4420
