### ISSUE TITLE
Dead link in Connect Terms page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#4405]
The link under the privacy section of the page https://connect.topcoder.com/terms  is a dead link .

under privacy, should go here: https://www.topcoder.com/policy
​
![unnamed](https://user-images.githubusercontent.com/2417632/125029165-dfde1a80-e0a6-11eb-9d87-fde45165230a.png)
![unnamed (1)](https://user-images.githubusercontent.com/2417632/125029172-e10f4780-e0a6-11eb-8fbc-20b9646bfd54.png)

**Comment by lakshmiathreya** [comment]
Verified Privacy link in Connect Terms page.
