### ISSUE TITLE
Set milestone of challenge - work manager

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4414]
As a Work Manager user creating/editing a challenge, I can assign the challenge to a milestone.  The list of milestones is based on the milestones of the project. 

As a user, I can click "Add New Milestone", which will take me to Connect to add the milestone within the project.

Prototype:  https://marvelapp.com/prototype/660ha87/screen/80538282

**Comment by drasticdpk** [comment]
Verified on Dev env 

**Reference**:

Challenge : https://connect.topcoder-dev.com/projects/18173

![image](https://user-images.githubusercontent.com/25297859/128654535-b2e511d2-e6fa-4fa6-9b1d-c589ee838752.png)

Edit Milestone Window : 
![image](https://user-images.githubusercontent.com/25297859/128654774-f8813655-4fd4-484c-a787-9a77c6fdbafe.png)

**Comment by drasticdpk** [comment]
Prod verified 
![image](https://user-images.githubusercontent.com/25297859/129568077-7c5b707c-02a5-484b-a2cc-599a2b849edf.png)
