### ISSUE TITLE
View Challenges In Milestone - Connect

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4415]
As a copilot/manager/admin, I can view a list of challenges that are in a milestone. I do this by expanding the milestone to see a list of challenges.  Clicking on a challenge will open that challenge in Work Manager.

The user will not have the ability to edit/create challenges from within Connect.

Example Prototype:  https://marvelapp.com/prototype/83f28df/screen/78966156

**Comment by drasticdpk** [comment]
@elkhawajah ,
Can you link me specific project where I can meet above scenario ?

**Comment by elkhawajah** [comment]
> @elkhawajah ,
> Can you link me specific project where I can meet above scenario ?

https://connect.topcoder-dev.com/projects/18166/

**Comment by drasticdpk** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/25297859/128655209-4acc40ba-fccf-4b21-a6c3-b7b0d1dffe73.png)

Let's open the Challenge in new window instead of same window. please confirm @RishiRajSahu @ajefts

**Comment by RishiRajSahu** [comment]
@elkhawajah on click of both `view challenges` and on challenge itself please open them in new window.

**Comment by drasticdpk** [comment]
verified 
![image](https://user-images.githubusercontent.com/25297859/131644053-78a65226-094b-4ffa-9c61-45e7c12a03e6.png)
