### ISSUE TITLE
[TaaS] Restrict the duration field on Jobs to a 4 week minimum

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#4417]
Task from Will:

> I know we have a new intake tool, and once it's ready for primetime I want to retire the Connect form, but in the meantime we need to do a quick update to the Connect intake form.
> We need to restrict the duration field on Jobs to a 4 week minimum.

**Comment by sandhiyakavi** [comment]
Verified on Dev Env

![image](https://user-images.githubusercontent.com/55895538/125729229-26cb4e5b-55be-4702-9d8a-468c9ba2ed0f.png)
![image](https://user-images.githubusercontent.com/55895538/125729340-610599dc-c451-40aa-8076-93b182f65073.png)

**Comment by lakshmiathreya** [comment]
cc @coderhacker

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/125888983-957073c7-09a0-41e1-8b57-473fe7a5595a.png)
![image](https://user-images.githubusercontent.com/55895538/125889239-79e559b2-70bf-417d-9a4d-4d28ee907c1d.png)
