### ISSUE TITLE
Add New Milestone button is missing If user try to save milestone with  -ve value in BUDGET field 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4424]
**Reference** 

https://user-images.githubusercontent.com/25297859/126793410-d8e841ad-cbec-4aec-b5f9-307a03bae186.mp4

**Possible Solution**   

![image](https://user-images.githubusercontent.com/25297859/126793908-a4f6c1ab-0fc3-42bf-bd1f-0e234d1afa8c.png)

**Comment by elkhawajah** [comment]
@drasticdpk ready for QA

**Comment by drasticdpk** [comment]
Verified on Dev 
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/126932696-cffab719-5e8a-48e4-89ee-afc0e1b4b8bd.png)

**Comment by drasticdpk** [comment]
Verified on Prod

![image](https://user-images.githubusercontent.com/25297859/126964774-752d1608-54a0-4862-85a9-4aad153540a3.png)
