### ISSUE TITLE
Milestone with Draft status  is showing for Customer view. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4428]
Reference 
![image](https://user-images.githubusercontent.com/25297859/126936563-a6900b87-1d7d-4abe-8b55-560572322f45.png)

https://user-images.githubusercontent.com/25297859/126936897-0354ddb3-13fa-43c5-9e43-339922027613.mp4

Finding : Initially Milestone with draft status is not showing but once there is active status then other milestone ( draft ) status are also showing.

**Comment by drasticdpk** [comment]
please confirm above scenario cc @RishiRajSahu @lakshmiathreya @ajefts

**Comment by RishiRajSahu** [comment]
@elkhawajah @drasticdpk seems to be a bug. draft phases were not shown to customer earlier.

**Comment by drasticdpk** [comment]
Verified on Dev env.
![image](https://user-images.githubusercontent.com/25297859/127964267-476cf778-3810-42a7-86a0-682a2cb00b7d.png)

**Comment by drasticdpk** [comment]
Verified on Prod

![image](https://user-images.githubusercontent.com/25297859/129567327-3510e09b-2192-47eb-909e-b200668fc971.png)
