### ISSUE TITLE
Remove White Space In Milestone Table

### ISSUE THREAD

**Issue by elkhawajah** [appirio-tech/connect-app#4432]
Because of copilots removal, we need to fix the content to occupy the full table width
![image](https://user-images.githubusercontent.com/1621715/126984459-86cd7867-5075-42af-93a6-61d8f04d6ce3.png)

**Comment by drasticdpk** [comment]
Customer view ( where we have hide the Action Column ) 

![image](https://user-images.githubusercontent.com/25297859/126985239-d326790b-9531-4ff0-acd8-ab8a3f360808.png)

**Comment by drasticdpk** [comment]
Verified on dev env,
![image](https://user-images.githubusercontent.com/25297859/127960335-5c477c3a-b7b6-4ae5-93c5-4ef3e884f564.png)

![image](https://user-images.githubusercontent.com/25297859/127960596-8e1ddc9a-5995-47e1-a924-3c77f76d0d4c.png)

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/129566840-2407b6f8-1195-49f6-a131-ad14e274eb6a.png)
