### ISSUE TITLE
Milestone Management : Budget Tracking

### ISSUE THREAD

**Issue by elkhawajah** [appirio-tech/connect-app#4433]
Make budget field progressive based on challenge spends

- [ ] Remove the budget field and adjust width

**Comment by RishiRajSahu** [comment]
@elkhawajah as per recent discussion we are going to remove budget field from milestones.

**Comment by drasticdpk** [comment]
Verified. 
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/128514345-7880ce4d-d8a7-4522-aade-d86a278112b3.png)

**Comment by drasticdpk** [comment]
Prod verified.
![image](https://user-images.githubusercontent.com/25297859/129566324-e23ce3b6-c9c2-42d5-83b6-c7ea309747db.png)
