### ISSUE TITLE
Milestone Management : Copilots 

### ISSUE THREAD

**Issue by elkhawajah** [appirio-tech/connect-app#4439]
We allow linking a milestone to copilots, so that we can tell which copilot worked on what milestones. Also it will allow to give access/permission in future for specific milestones to copilots instead the full project.

Initially the version is to allow linking copilots to a milestone.

**Comment by elkhawajah** [comment]
Bugs :
- [ ] Exclude email from member copilots popup, The phases api, is returning members array that include the id, photoURL, and handle, use that to render the details of member, don't render the email address. 
- [ ] When adding copilots, when clicking to save, it show copilot for a second then disappear, when refresh it will show it.

**Comment by nqviet** [comment]
@elkhawajah 
for `it show copilot for a second then disappear`, it is an backend issue:
(while get/list phase(s) returns `members` field, `update phase` does not return this field. After updating successfully, the phase is reloaded with backend data and the members field is null)
![Untitled](https://user-images.githubusercontent.com/36178659/127442387-cd4c1921-9ecb-4654-8c5a-d2fa8fd13330.png)

**Comment by drasticdpk** [comment]
Verification : 
![image](https://user-images.githubusercontent.com/25297859/128513094-b58a9fb9-4228-46f6-adf7-8f4f0f3ed963.png)

![image](https://user-images.githubusercontent.com/25297859/128513308-367a2da9-1343-4008-ba12-8ad6d4da4115.png)

**Comment by drasticdpk** [comment]
Prod verification
![image](https://user-images.githubusercontent.com/25297859/129566607-923b8b4d-12fa-4133-88e7-dcf8fed3ebd0.png)
![image](https://user-images.githubusercontent.com/25297859/129566647-bbf01bb0-3459-4c29-a13d-25b0f8cc7fb1.png)
