### ISSUE TITLE
Milestone Management: Customer Approval

### ISSUE THREAD

**Issue by elkhawajah** [appirio-tech/connect-app#4440]
The feature is to allow customer to approve milestones added to the TC connect project.

The idea is to show customer the project plan, consisting of milestones and challenges running under these milestones, along with timeline and budget.

So customer will review the milestones, and approve or reject.

The user story :
- Copilot/PM adds or update milestones
- Copilot/PM move the Milestone to 'In Review' status once ready
- Customer will receive email notification about the new milestones approval once per day or once per week
- Customer will view the milestones in project page, and approve individually the milestones, or can bulk approve the milestones
- If a milestone is approved, it will move to Reviewed status.
- PM/Copilot will be notified about the result of the approval.
- If the Milestone is rejected, it will have new status : Rejected After Review.
- If the milestone is rejected, PM/Copilot based on feedback can fix it and send it back to the customer for approval.

Nice to have :
- We can have approve/reject/require more information during approval, so that if a customer rejects a milestone then it is cancelled, while if it requires more information, then PM/Copilot assigned to make fixes within specific X of days with email notification reminders
- It is good to have KPI/SLA defined for each stage in the approval lifecycle so that once the assigned user is late to take the action, they will be remindered via email/notifications so nothing get abondened

**Comment by drasticdpk** [comment]
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/129888252-d64de9e0-ffe9-444e-9895-a593d3219c14.png)

**Comment by elkhawajah** [comment]
@drasticdpk do you have any update about this fix ?

**Comment by drasticdpk** [comment]
Customer Approval flow has been verified. However there are couple issue which is found in our regression. 
I have logged over there : https://github.com/appirio-tech/connect-app/issues/4474

**Comment by drasticdpk** [comment]
> If the Milestone is rejected, it will have new status : Rejected After Review.

@elkhawajah  it seems Rejected status is missing from our flow. 
![image](https://user-images.githubusercontent.com/25297859/131802950-1dc2e987-f47e-4c28-aaaa-99c845e2d36f.png)

cc @RishiRajSahu

**Comment by drasticdpk** [comment]
Prod Verified
![image](https://user-images.githubusercontent.com/25297859/132285706-81071a7f-c1a0-47ad-8fe4-24f5452570f2.png)

Note : we have some suggestions, we will address once design confirmed 
https://github.com/appirio-tech/connect-app/issues/4480#issuecomment-911311611
cc @RishiRajSahu
