### ISSUE TITLE
Feedback : Milestone Management View

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4451]
**Reference** 

![image](https://user-images.githubusercontent.com/25297859/128668959-c8e03cbe-f4e0-45b7-b525-0bd7bc0bf79c.png)

**Comment by RishiRajSahu** [comment]
1. let's use PROJECT(S)

**Comment by RishiRajSahu** [comment]
1. let's use PROJECT(S)
2. @drasticdpk could you give example of what you mean ?
3. @elkhawajah please align that
4. @drasticdpk we would be needing that in customer approval workflow

@elkhawajah I have another question, what if we select multiple checkboxes and then try to add copilot, will that copilot be added to all milestones ? what if that copilot is already part of some milestone out of those which selected ?
@drasticdpk did you verified this behaviour ?

**Comment by elkhawajah** [comment]
> @elkhawajah I have another question, what if we select multiple checkboxes and then try to add copilot, will that copilot be added to all milestones ? what if that copilot is already part of some milestone out of those which selected ?

If copilot is part of one of the selected milestones, then modal will show common copilots across these milestones, and drop down will list ones even if they are part of one of the selected, then user can add the copilot to all.

**Comment by RishiRajSahu** [comment]
@elkhawajah thanks, @drasticdpk please QA this also.

**Comment by yoution** [comment]
@elkhawajah 
![image](https://user-images.githubusercontent.com/3863914/129341634-f8fed3be-6f38-43ca-82c4-062bdffd88e6.png)
what does it mean?

**Comment by yoution** [comment]
can you give me three title names?

**Comment by RishiRajSahu** [comment]
@elkhawajah @yoution just updated the tooltip to say "Delete selected milestones" , "Add copilot(s)", "Move Milestones" .

**Comment by drasticdpk** [comment]
> @elkhawajah thanks, @drasticdpk please QA this also.

@elkhawajah let us know once the code is merged, I will verify it.

**Comment by drasticdpk** [comment]
Prod verified.
![image](https://user-images.githubusercontent.com/25297859/129565450-09571289-d874-44aa-9018-7dd03951d00a.png)
