### ISSUE TITLE
Dashboard/Status updates: initial post being "double-posted"

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#446]
![screen shot 2016-10-05 at 3 15 16 pm](https://cloud.githubusercontent.com/assets/12552247/19133749/b77dfc88-8b0e-11e6-821e-3014137bd91b.png)
 
User: pat_monahan; Project: 311

- Initial post is "double-posted" as both original comment and follow-up

**Comment by parthshah** [comment]
Should be fixed now.
