### ISSUE TITLE
Close Add copilot dialog when clicking outside

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#4460]
When clicking outside the right handside add copilot drawer, it should be closed.
![Screenshot 2021-08-16 at 5 28 42 PM](https://user-images.githubusercontent.com/11248478/129560448-b045f081-9914-46f7-b48b-723ba5ef7018.png)

fyi @elkhawajah

**Comment by drasticdpk** [comment]
@elkhawajah  we are unable to add copilot, please have a look. 

**Reference**

https://user-images.githubusercontent.com/25297859/131637351-6d27bde2-d1fa-4648-ab18-3eeff6cf6729.mp4

**Comment by RishiRajSahu** [comment]
@elkhawajah @drasticdpk why this was never tested in Dev env ?

**Comment by elkhawajah** [comment]
@drasticdpk you can QA please

**Comment by drasticdpk** [comment]
Verified on Dev
![image](https://user-images.githubusercontent.com/25297859/131688590-1196af2d-b290-4a76-9b60-7e4219cd4085.png)

**Comment by drasticdpk** [comment]
> @elkhawajah @drasticdpk why this was never tested in Dev env ?

@elkhawajah  let's add `Read for QA` once you merged the code to **dev branch** so QA Team can pick that issue for QA.
Also request you to add possible label for each issue. For reporting purpose we will need it.
![image](https://user-images.githubusercontent.com/25297859/131691089-97496a1b-97c6-40b8-97d8-dacdf04ab336.png)

**Comment by drasticdpk** [comment]
Verified on prod mode 

![image](https://user-images.githubusercontent.com/25297859/131698439-2d1210d9-158d-4a5c-9b35-3953a383d512.png)
