### ISSUE TITLE
Customer Approval - Regression Testing 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4474]
- Disable Double click for every Button. 
- Update Toaster message as well As Milestone rejected successfully 
- Unable to Reject Milestone  >> Let’s disable done button until user does not enter any text.

Reference : 

https://user-images.githubusercontent.com/25297859/131284306-8054b15a-6ce0-4fc1-9295-1de0bacc62ff.mp4

cc @RishiRajSahu

**Comment by elkhawajah** [comment]
@drasticdpk you can QA

**Comment by drasticdpk** [comment]
QA Verified on Dev Env. 
cc @elkhawajah

**Comment by drasticdpk** [comment]
Prod verified successfully.
