### ISSUE TITLE
Dashboard/Feature picker: Deselecting feature moves user out of feature view

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#448]
Something changed with the feature selector pill. Previously it would turn the feature on and off, keeping the user on the feature screen, but hiding or opening the notes. Now the user is completely taken off the feature, which is incorrect: http://screencast.com/t/iZkYRmW3nW.

This is the behavior we want to maintain: http://screencast.com/t/C8czC2sv

**Comment by vikasrohit** [comment]
Fixed. Changes are in dev.
