### ISSUE TITLE
 Notification Content at Customer Approval Flow. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4484]
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/132374489-76b1cbef-c756-4289-a4f1-4e8133340ca1.png)

**Scenario**
1. If there is only one milestone and it is approved by customer. 
  > Message should be "Milestone has been approved by the customer."

2. If we have 3 milestone, out of them 2 is already on Active state. Once another remaining milestone is approved by customer, now it is showing "All the milestone(s) has been approved by the customer" is it expected ?

3. Is it possible to list the milestones that were approved in the notification?
Reference Communication : https://topcoder.slack.com/archives/CBYPB0YBF/p1631021077012700?thread_ts=1630986905.010400&cid=CBYPB0YBF

Please suggest. 
cc @ajefts @RishiRajSahu

**Comment by RishiRajSahu** [comment]
Let's do like -

**Comment by RishiRajSahu** [comment]
we just have to update the existing text to -
```
The following milestone(s) has been approved:  
 - m1
 - m2
```

So it will include all the scenarios of 1 or more milestones being approved.

**Comment by elkhawajah** [comment]
Created a PR

**Comment by drasticdpk** [comment]
**Reference** 
![image](https://user-images.githubusercontent.com/25297859/133238235-fae1a718-0f67-4d04-8632-e47974ad39b3.png)

![image](https://user-images.githubusercontent.com/25297859/133237366-0b211c8a-44f8-4fff-adba-fb5308415580.png)

**Comment by drasticdpk** [comment]
@elkhawajah please confirm.

**Comment by drasticdpk** [comment]
> we just have to update the existing text to -
> 
> ```
> The following milestone(s) has been approved:  
>  - m1
>  - m2
 
@elkhawajah  here the  m1 and m2 are approved milestone right ?

**Comment by drasticdpk** [comment]
Verified on dev mode. 
Reference 
![image](https://user-images.githubusercontent.com/25297859/133398250-52074a55-08b2-4158-a0e8-854bc04cf5d9.png)
