### ISSUE TITLE
Unable to remove copilot from Milestone 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4494]
**Reference** 

https://user-images.githubusercontent.com/25297859/133742564-5aebbe68-1d83-408d-9697-9f0125f9869d.mp4

QQ : @elkhawajah 
 1. Have we implemented the Copilot remove functionality in the Milestone Module  ? If yes please link me details requirement. 
 2. From which Role, User can remove the copilot, please confirm. 
  cc @RishiRajSahu

**Comment by drasticdpk** [comment]
Verified 
![image](https://user-images.githubusercontent.com/25297859/134835337-1b0507c5-50b2-4618-bf24-b8a567d25959.png)

@elkhawajah 
> From which Role, User can remove the copilot, please confirm.
Let's confirm before got go prod for this, so we can update our test case accordingly.

**Comment by elkhawajah** [comment]
Anyone who joined project as PM/Copilot can manage the milestones including copilots.

**Comment by drasticdpk** [comment]
**Verification** 
![image](https://user-images.githubusercontent.com/25297859/135254617-825621fa-ec75-4730-af6a-6467a7eb178b.png) 
![image](https://user-images.githubusercontent.com/25297859/135254798-0db2a75f-e352-49b0-b4c5-a791be629d47.png)
