### ISSUE TITLE
Let's hide checkbox at milestone grid for completed and Cancelled project. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4495]
**Reference** : 

Project : https://connect.topcoder-dev.com/projects/18049 
![image](https://user-images.githubusercontent.com/25297859/133743692-6022a74a-f51e-4411-822f-6477c03933e5.png)

![image](https://user-images.githubusercontent.com/25297859/133744833-9404cbb9-0a3f-4366-9cba-fa14be74e222.png)

cc @RishiRajSahu

**Comment by drasticdpk** [comment]
For customer view, only display the Action column if there is any milestone in-review status. 
![image](https://user-images.githubusercontent.com/25297859/133764136-03f8c8cf-558c-4f18-89fe-7fc027c607b7.png)

**Comment by nursoltan-s** [comment]
https://github.com/appirio-tech/connect-app/pull/4500

**Comment by drasticdpk** [comment]
> For customer view, only display the Action column if there is any milestone in-review status.
> ![image](https://user-images.githubusercontent.com/25297859/133764136-03f8c8cf-558c-4f18-89fe-7fc027c607b7.png)

Still we see action column if there is no any in-review status milestone , please confirm. 
![image](https://user-images.githubusercontent.com/25297859/134835965-168834a5-15d3-4406-a4cf-41fa4c6b334f.png)

**Comment by drasticdpk** [comment]
Verified on Dev env.
![image](https://user-images.githubusercontent.com/25297859/135076210-eddb67d5-3f0a-43c4-a884-b008a9d5c856.png)

**Comment by drasticdpk** [comment]
Verified.
![image](https://user-images.githubusercontent.com/25297859/135255176-27b45b61-e4e4-45de-8cf8-2fe59814ced1.png)
