### ISSUE TITLE
Challenge disappear in Milestone grid  after adding copilot.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4496]
**Precondition** 
Milestone should be added on respective challenge through WM.

**Reference**
https://connect.topcoder-dev.com/projects/18796 

https://user-images.githubusercontent.com/25297859/133755825-0776c4a0-b316-4234-b6c7-d163c430b623.mp4

Note : After deletion of copilot, challenge should be still visible on grid. 

cc @RishiRajSahu

**Comment by nursoltan-s** [comment]
https://github.com/appirio-tech/connect-app/pull/4499

**Comment by drasticdpk** [comment]
Verified on Dev env
![image](https://user-images.githubusercontent.com/25297859/134836534-da8b6123-771c-4078-96fe-58d09392c73e.png)

**Comment by coderhacker** [comment]
This is fixed on production 

https://user-images.githubusercontent.com/62358241/135256459-370f53de-310c-4e5e-a4e3-13d1320b2c90.mp4
