### ISSUE TITLE
Start Date is missing for completed Milestone. 

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4497]
**Reference** : 
![image](https://user-images.githubusercontent.com/25297859/133763504-f07da3d7-3304-4225-9047-f2a808483bf4.png)

https://connect.topcoder-dev.com/projects/18049

**Comment by nursoltan-s** [comment]
https://github.com/appirio-tech/connect-app/pull/4498

**Comment by drasticdpk** [comment]
Verified. 
![image](https://user-images.githubusercontent.com/25297859/134836741-628b287c-64d0-4661-bef5-dd12f1bf8c43.png)

**Comment by coderhacker** [comment]
This is fixed Production 
![image](https://user-images.githubusercontent.com/62358241/135255895-016aaea6-2914-4f0d-bc0b-519c19220e52.png)
