### ISSUE TITLE
Project creation: remove placeholder text from "Project name", "Description", "Reference code"

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#45]
Not needed when the fields are labeled

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/177715475605024

**Comment by vikasrohit** [comment]
Btw, if we are doing this for App project form, we have to do it for 'Other work' form as well, right?

**Comment by vikasrohit** [comment]
Done. Waiting for green signal to get it merged into dev.

**Comment by fnisen** [comment]
@vikasrohit yes please, remove it from both forms and merge when ready. Thank you.
