### ISSUE TITLE
For customer view, only display the Action column if there is any milestone in-review status.

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#4511]
Reference : 
![image](https://user-images.githubusercontent.com/25297859/135076999-d4ff1b8f-826b-4ddd-b52a-c2984e9d8204.png)

Note : For more details https://github.com/appirio-tech/connect-app/issues/4495#issuecomment-927453525

**Comment by elkhawajah** [comment]
https://github.com/appirio-tech/connect-app/pull/4509 deployed this to dev, you can check once CircleCI finish deployment.

**Comment by drasticdpk** [comment]
Verified on Dev env.
![image](https://user-images.githubusercontent.com/25297859/135135472-89f84693-8406-43e1-b45f-2e8b647c6f61.png)

![image](https://user-images.githubusercontent.com/25297859/135136343-c7c2d424-2065-4fa6-b13e-2934fe5b7ad8.png)

**Comment by drasticdpk** [comment]
Reference 
![image](https://user-images.githubusercontent.com/25297859/135257274-af4edf08-261b-4348-885a-c8b2fa778411.png)
![image](https://user-images.githubusercontent.com/25297859/135257368-bae94852-5530-4dfd-97d9-faac1ba339e0.png)
