### ISSUE TITLE
Messaging: replying to a message thread throws an error

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#453]
Every five replies or so, one of them will throw an error. Some examples: 
- http://take.ms/lASDY
- http://screencast.com/t/i7DWcLSyq

It's happening much more regularly than would be normal.

cc @vikasrohit, @mahestro

**Comment by parthshah** [comment]
There is a limit on the number of posts a user can make in Dev. @mdesiderio is there such a limit in Production too? If there is, we should make sure we relax the limit. But I doubt we'll have super engaged users posting 10s of messages every minute.

**Comment by parthshah** [comment]
I am downgrading this bug as it's unlikely we'll see this in Prod.

**Comment by fnisen** [comment]
OK, fair.

**Comment by fnisen** [comment]
Not able to reproduce in Prod. Closing.
