### ISSUE TITLE
Dashboard/Status updates: update posts showing an unnecessary avatar icon

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#455]
<img width="754" alt="screen shot 2016-10-10 at 9 59 28 am" src="https://cloud.githubusercontent.com/assets/12552247/19244251/46991ce4-8ed0-11e6-87b1-3d166c3fbb8a.png">

Icon highlighted above should be removed.

**Comment by vikasrohit** [comment]
Changes are in dev.
