### ISSUE TITLE
Connect- Top nav bar disappears when moving mouse over the menu

### ISSUE THREAD

**Issue by jmgasper** [appirio-tech/connect-app#4596]
Steps

Go to https://connect.topcoder-dev.com/projects?sort=lastActivityAt desc

Hover over customer or talent

Move the mouse pointer over to the drop down menu

Expected: The menu should not disappear

Actual: The menu disappears

https://user-images.githubusercontent.com/21790/221288854-ce941a8a-3ba9-4e37-bbda-c95c17e65e5d.mp4

**Comment by suppermancool** [comment]
@jmgasper done in 
[issue-4596.patch](https://github.com/appirio-tech/connect-app/files/10829716/issue-4596.patch)

this patch again commit cbbf8fae9650461638e4f202937629f808a37294 (dev branch)
