### ISSUE TITLE
Posts bold formatting is not working.

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#462]

**Comment by fnisen** [comment]
Seems to work if I use the "strong" tag. Is this what you intended?

**Comment by parthshah** [comment]
![image](https://cloud.githubusercontent.com/assets/1987710/22572288/3fc420ca-e958-11e6-80af-931beef21928.png)

@vikasrohit - should we run a challenge for this?

**Comment by vikasrohit** [comment]
@parthshah Yes, we can run a challenge for this, however, I am not sure how well our community is equipped with discourse knowledge. If have discourse skill in community, we can definitely get it fixed via community, otherwise I can look into it.

**Comment by fnisen** [comment]
Working now during my testing, so going to close.
