### ISSUE TITLE
Team management: "member/copilot" switch not visible when there are 3+ team members

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#465]
Please see video: http://screencast.com/t/JJpw9r5lcB. Similar thing happens when I remove a member--the dialog window is cut off.

**Comment by fnisen** [comment]
Related issue, in case you want to tackle them together: https://github.com/appirio-tech/connect-app/issues/466

**Comment by fnisen** [comment]
@vikasrohit: http://screencast.com/t/FgI3Dpckq9. This is happening to me on Mac/Chrome 53. When the dialog is at the bottom of the screen, it often gets "stuck," and I cannot scroll down further. I can get it unstuck by resizing the window.

**Comment by vikasrohit** [comment]
Okay, I guess, I am able to reproduce the situation, however, I am able to get over it if I try to scroll in reverse direction after it gets stuck. And it does not seem to happen frequently to me. May be we can use community for this purpose. It seems sticky behaviour of the left panel is causing this trouble.

**Comment by fnisen** [comment]
@vikasrohit yes, please use the community. If you need a copilot, @mahestro is out for a few days, so you can work with talesforce or pick your favorite. Or you can assign to someone if appropriate. Your pick.

**Comment by vikasrohit** [comment]
Related issue #245

**Comment by vikasrohit** [comment]
@fnisen I have got it fixed via community. Can you please once check it with your use case? Further, it seems this issue(mentioned in #245) was consistently there for Windows environment, so it would better if you can give a try on Windows environment as well. Please I have verified it on Windows/IE and Windows/Chrome environments in browserstack, but I am not sure how it would behave on real Window machine.

**Comment by fnisen** [comment]
@vikasrohit it's mostly working. I can scroll down and the switch is visible, but I'm not automatically scrolled down to enter a username. So, if the team panel is long and I click the "+" at the top, I won't know that the entry component has opened at the bottom: http://screencast.com/t/QfeJ69WkZV8q. Also, "Add a Team Member" should be left-aligned, per the design. Thank you.

**Comment by vikasrohit** [comment]
Okay. Got it. But I guess that is separate issue and not in the scope of this issue. I would create separate issue to better track it.

**Comment by vikasrohit** [comment]
Separate issue, #526, created to track it.
