### ISSUE TITLE
Team management: "member/copilot" switch fixes

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#466]
A few UX changes please: 

- style the active item as primary button
- make the whole button clickable, not just the text
- remove the hover state from the selected (blue) item

![pasted image at 2016_10_13 04_47 pm](https://cloud.githubusercontent.com/assets/12552247/19371091/29861566-9165-11e6-9f5f-d94cb8e3460f.png)

cc @vic-appirio

**Comment by vikasrohit** [comment]
@fnisen I have fixed the styles, however, I didn't get
> remove the hover state from the selected (blue) item
I didn't find any hover state on selected switch. However there was a inner box shadow for the selected item which was not looking good to me, so I have remove that. Please let me know if you want that back.

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit sorry for the delay. Here is what I mean by "remove the hover state from the selected (blue) item": 
- When "Copilot" is selected, as in the image above, if I hover over "Copilot" on the switch, I see the hand, meaning it is clickable. However, when I click, nothing happens (which is working as it should)
- Because "Copilot" is not "clickable," there should not be a "hand" hover state when I mouser over it
- When "Copilot" is selected, my only option is clicking "Member," which should show the hover state hand, as it does now.

**Comment by vikasrohit** [comment]
@fnisen Fixed the cursor style as well. Changes should be in dev.

**Comment by fnisen** [comment]
Perfect! Thanks @vikasrohit. Working well in dev.
