### ISSUE TITLE
Links: critical problems with view and validation

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#467]
"Add" button is obscured (similar to https://github.com/appirio-tech/connect-app/issues/465) and validation requires "http://," which is not intuitive. Can we be more permissive with URLs, similar to how "Add a Link" works on the member profile? If that's too hard, let's turn off validation for now and fix soon.

**Comment by vikasrohit** [comment]
@fnisen I am not able to reproduce the obscured thing for Add button as well for #465. Are you testing that in mobile? I have 10+ members in team and I am able to see the member/copilot switch for #465 and similarly 'Add Link' button is always visible to me.
However, I have done the changes for relaxing the URL validation to be similar to what we have in member profile page.

**Comment by fnisen** [comment]
Thanks @vikasrohit. I'll close this and let's track the other issue via 465. I wasn't viewing it on mobile--just regular Mac/Chrome. Will try to figure out how to reproduce consistently.
