### ISSUE TITLE
Add project "Description" to Dashboard and Specifications

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#469]
https://drive.google.com/drive/folders/0B1LbmKnex41fUUg2dWtXMHgtWms?usp=sharing

Can you please add the Description we capture during new project creation to two places: 

- Dashboard: 4 lines plus "read more" link that goes to the Specification (you can ignore the other new stuff shown in the design)
- Specification: a description section at the top, which can be edited and saved (ignore the device icons shown in the design for now)

**Comment by vikasrohit** [comment]
@fnisen I am not sure how to achieve the 4 line text ellipsis. We can truncate the text based on number of characters but I guess it is difficult to do this based on #lines because #lines depends on screen resolution.

**Comment by vic-appirio** [comment]
https://github.com/ShinyChang/React-Text-Truncate probably?

**Comment by fnisen** [comment]
Just for reference, a CSS approach: http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/, https://css-tricks.com/line-clampin/

**Comment by vikasrohit** [comment]
Thanks @vic-appirio and @fnisen for the link. Filipp, however, the pure css solutions still have limits e.g. putting 'read-more' text in place of ellipsis requires one more hack or may not be possible. I have used the javascript version.
Changes are in dev.

**Comment by fnisen** [comment]
Thanks @vikasrohit. It's is working.
