### ISSUE TITLE
Frame: replace Connect logo in nav with attached

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#47]
[logo-connect-web.svg.zip](https://github.com/appirio-tech/connect-app/files/460452/logo-connect-web.svg.zip)

**Comment by vikasrohit** [comment]
Tracking with asana here https://app.asana.com/0/95614844085038/177715475605004

**Comment by vikasrohit** [comment]
Done. Waiting for green signal to get it merged into dev.
