### ISSUE TITLE
General: load copilot and manager roles into Connect

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#476]
Here are the lists:
[ConnectCopilots.xls.zip](https://github.com/appirio-tech/connect-app/files/531305/ConnectCopilots.xls.zip)

[tc-managers-1.xlsx.zip](https://github.com/appirio-tech/connect-app/files/531306/tc-managers-1.xlsx.zip)

**Comment by parthshah** [comment]
Loaded TC Managers. @ajefts, a few accounts - you, vbailey, me & sudo are marked as admins. So I didn't add manager role to them.

I haven't added any more Connect Copilots. I am guessing the existing list using Connect V1 is still good.

**Comment by fnisen** [comment]
@parthshah sounds good regarding copilots. Already agreed with Joey that we would start with the current group.
