### ISSUE TITLE
Use React version of SVG loader to dynamically load the SVGs as React components

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#481]
Vic's [comments](https://github.com/appirio-tech/connect-app/pull/460#issuecomment-253869628):

I think that we can save ourselves time and effort if we can just dump the appropriate .svg files and dynamically convert them to react components. After some research of different approaches out there, [svg-react-loader](https://github.com/jhamlet/svg-react-loader/blob/version-0.4.0/README.md) seems like the best candidate for our tasks:
- design can dump/update/maintain the appropriate .svg files
- developers can request the icons in a consistent way, just need to know the correct filename
- icon properties could be handled by react-css-modules via `styleName` dynamically, which will limit the need to parameterize the .svg properties (consistency through reuse of global icon css classes).

Detailed [article for this approach](https://diessi.ca/blog/svg-images-as-react-components-with-webpack/);
Another [work-around for .SVG icon systems](http://blog.goguardian.com/nerds/an-odyssey-to-find-a-sustainable-icon-system-with-svgs-in-react)

As per performance - I have no idea which approach will be the fastest. My goal would be to load only 1 SVG and modify it properties instead of switching multiple static .svg or .png images.

**Comment by vic-appirio** [comment]
Assigning Luis to look into integrating the svg react loader

**Comment by vic-appirio** [comment]
Merging it as part of the scaffolding issue task list
