### ISSUE TITLE
Specification: preview/download project files

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#486]
We currently don't have a way to access files after they've been uploaded. 

Can we allow clicking on the file to open a preview (using OS), and then download, or if preview is too difficult, download directly?

**Comment by fnisen** [comment]
@parthshah discovered an edge case. The file is not clickable when it's first uploaded. The user must refresh the page before they can click on it.

**Comment by parthshah** [comment]
Good catch. 
But one could argue that if you already have the file ... why do you need to download it 😼 . 
Should be fixed with a backend fix now.

**Comment by fnisen** [comment]
Thanks. Working fine in Dev. True... I think it's needed not for downloading, but to check that the upload worked correctly. We see this all the time on the member side: designers especially go to download all of their files after submitting to make sure they got processed correctly. This is an extreme example, but I think users would want to double-check occasionally.
