### ISSUE TITLE
Dashboard/Project info: hover state for Status dropdown should be disabled for customer role

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#49]
Only manager and copilot roles can change the Status; for them the hover state over the dropdown should be supported. For the customer role, it should be disabled.

**Comment by mahestro** [comment]
Challenge live https://www.topcoder.com/direct/contest/detail.action?projectId=30055193

**Comment by mahestro** [comment]
Done - https://www.topcoder.com/direct/contest/downloadSoftwareSubmission.action?projectId=30055193&submissionId=231024

Needs to be merged.

**Comment by fnisen** [comment]
@mahestro as on the other issue, please merge when ready.
