### ISSUE TITLE
Team management: add managers to Direct project when they join via Connect

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#491]
Not sure if this was planned already or if you guys discussed. Putting it down so we don't forget.

**Comment by parthshah** [comment]
@ajefts let me know once the APIs are in place. We can run the necessary challenges through the community to keep this in sync.

**Comment by ajefts** [comment]
will do @parthshah 

Going to run a challenge shortly for it...

**Comment by parthshah** [comment]
Being tracked here - topcoder-platform/tc-project-service#34
