### ISSUE TITLE
[Team Management] Buttons are not center aligned in assign owner modal

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#492]
<img width="357" alt="screen shot 2016-10-20 at 3 06 24 pm" src="https://cloud.githubusercontent.com/assets/2417632/19554569/d9eab85a-96d6-11e6-918f-d8a131cccc32.png">

**Comment by vikasrohit** [comment]
Changes are in dev now.

**Comment by fnisen** [comment]
<img width="385" alt="screen shot 2016-10-24 at 4 42 57 pm" src="https://cloud.githubusercontent.com/assets/12552247/19699554/a2334690-9aa8-11e6-94af-859b456d15fe.png">

@vikasrohit, there is a copy/functionality issue on the card. In the design, the new owner's name is listed. The card message is shown as: "This will make [first name last name] the new project owner." However, currently the name is just skipped. https://files.slack.com/files-pri/T03R80JP7-F2TLB50DP/d81f44f7-2147-4cae-83f9-625bc48b9683.png Can you please add the name to the copy and change the copy to be: 

Title: "You are about to assign a new project owner"
Message: "[Name] will become responsible for the project and be able to add and remove team members. Are you sure you want to proceed?"

**Comment by vikasrohit** [comment]
Done. Please check the changes in dev.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Looks great!
