### ISSUE TITLE
Issue with downloading the web fonts - server might not be setup correctly.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#501]
### Expected behavior

Fonts should be served from the servers without problems.
### Actual behavior

An error appears when downloading the fonts - the files are somehow not being able to be parsed by the chrome. Such behavior doesn't appear at my local environment; according to a quick Google search the problem is either the files, or the server. The previous mention of local environment not causing problems leads me to thing we haven't setup the server to correctly serve/parse web font files.
### Screenshot/screencast

![screen shot 2016-10-26 at 11 22 08 am](https://cloud.githubusercontent.com/assets/8484061/19739213/ec7df666-9b6e-11e6-973a-1ddb35524153.png)
## 
#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by parthshah** [comment]
@vikasrohit it seems like we are *not* pushing web fonts to S3. Cloudfront/S3 doesn't complain with a 404 since to work with SPAs we handle 404s by returning index.html.Once we push fonts to S3, we'll probably have to make sure those fonts are referenced with the correct path/url.

**Comment by parthshah** [comment]
See this - https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/
@vic-topcoder what do you think of this loading style?

**Comment by vic-topcoder** [comment]
https://davidwalsh.name/cdn-fonts and MIME type fixer; https://github.com/dailymuse/s3-content-type-fixer

**Comment by fnisen** [comment]
@vikasrohit can this be addressed in a bug bash or do you need to fix it directly?

**Comment by vikasrohit** [comment]
@fnisen I think it would take some time as some investigation is involved as well as it might require trial and error approach. So, if we have sufficient number of issues for a challenge, we add this to them. Otherwise, I can pick it after completing salesforce integration thing which I am expecting would take about a week.
