### ISSUE TITLE
Dashboard/Project info: add link to Direct project, visible for Manager and Copilot roles

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#51]
@vic-appirio could you please create a quick design for this and attach here? We can't put this link in the "Links" section b/c it will only be visible to "internal" roles. Thank you.

cc @ajefts

**Comment by mahestro** [comment]
Quick crazy idea: we could have pinned links, colored or icon distinguished. To keep the same semantics.

**Comment by fnisen** [comment]
@mahestro it's a good idea... but in the "nice to have" territory, so we won't implement this month

**Comment by vikasrohit** [comment]
We can add these links the QuickLinks section (icon next to the the nav links) in topbar.

**Comment by fnisen** [comment]
@vikasrohit we need a project-level link, which will be unique per project, so we'll quickly have a lot of links... to many to include in the nav.

**Comment by vic-appirio** [comment]
![ef8a12df-23d0-49b6-90c8-f7893c869576](https://cloud.githubusercontent.com/assets/8484061/18489112/11225334-79b1-11e6-81c3-57c8a486c014.png)

Speck and Sketch files here: https://drive.google.com/drive/folders/0B1LbmKnex41fZnJ4Rkozcl94VUk?usp=sharing

**Comment by mahestro** [comment]
Easy cake.
