### ISSUE TITLE
Project creation: "Other work" option not visible to regular customer role

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#515]
When creating a new project, customers should see both tabs on the creation modal: "App Design & Dev" and "Other Work." Right now only App Design & Dev is shown (now both tabs are only visible to manager roles).

**Comment by vikasrohit** [comment]
@fnisen Can you please let me know with which user account you are facing this problem? From code, I can see that it now allows all roles to created both type of projects. It was committed by Vic in [this](https://github.com/appirio-tech/connect-app/commit/b9e237f159451c72dac318c8081964bbcc990699) git commit.

**Comment by fnisen** [comment]
@vikasrohit OK, I see the issue. This works correctly in dev, but not in prod. Were Vic's changes merged to prod? It's not working correctly on any customer (non-admin, non-manager, non-copilot) prod account.

**Comment by vikasrohit** [comment]
Changes seems to be there in master branch which is what should be in production. So, I am not sure how the issue is there on production. The only possible cause I can predict right now is that the users, facing the problem, don't have `Topcoder User` enabled on their account.

cc: @parthshah @ajefts

**Comment by parthshah** [comment]
Adding @sudoster - all users should have Topcoder User role by default. @sudoster  can you confirm that Identity service adds this role when an account is created?
@fnisen do you have sample accounts that are not seeing this tab? We can verify the roles for those user accounts.

**Comment by fnisen** [comment]
Yes, let's use my prod test account: beta_1/abcd1234. 
<img width="1179" alt="screen shot 2016-11-08 at 9 19 44 am" src="https://cloud.githubusercontent.com/assets/12552247/20109372/9cf7c65a-a594-11e6-8449-43785dfcc152.png">

**Comment by parthshah** [comment]
I manually added Topcoder User role to beta_1 user and I am able to see "Other work" tab. @sudoster should we assign this bug to you? All existing and new topcoder users should have "Topcoder User" role (role_id: 6).

**Comment by fnisen** [comment]
Fixed as part of this Asan task: https://app.asana.com/0/inbox/95457977915342/213496207959150/167544071523792
