### ISSUE TITLE
Dashboard: status updates showing up in reverse chronological order

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#516]
On this project, the new updates have been pushed down and the Coder cards show up first: https://connectv2.topcoder.com/projects/48

**Comment by parthshah** [comment]
@vikasrohit - can you please look into this. Hopefully it's straightforward.

**Comment by vikasrohit** [comment]
@parthshah It seems by the time our system posted the coder messages, Matt has already posted his post. Here is the dump of the API response:

<pre>
`{
  "version": "v4",
  "result": {
    "success": true,
    "status": 200,
    "content": [
      {
        "id": 168,
        "date": "2016-11-04T11:32:34.505Z",
        <b>"lastActivityAt": "2016-11-06T04:58:24.913Z",</b>
        "title": "Hey there, I'm ready with the next steps for your project!",
        ...
      },
      {
        "id": 167,
        "date": "2016-11-04T11:32:33.681Z",
        <b>"lastActivityAt": "2016-11-06T04:58:24.907Z",</b>
        "title": "Hello, Coder here! Your project has been created successfully",
        ...
      },
      {
        "id": 170,
        "date": "2016-11-04T14:08:32.210Z",
        <b>"lastActivityAt": "2016-11-06T04:58:24.907Z",</b>
        "title": "Welcome to the project @Systic!!",
        ..
      }
    ],
  }
}`
</pre>
Few things to notes here:
1. We are explicitly doing chronological sorting(in front end) the topics on lastActivityAt date which I think API is already doing, don't understand why we need explicit sorting at frontend again.
2. And lastActivityAt field of system topics are also being updated whenever someone new from the team views the topic. Source of truth for this is the presence of posts array, for system topics, which says 'xxx joined discussion'. So even system topics are being updated and they can come on top of the chronological order.

**Comment by fnisen** [comment]
@parthshah can you please check this out? Would like to get this one working by the GA.

**Comment by parthshah** [comment]
@vikasrohit as part of email notifications through discourse fix, I've updated the code to add all the team members when the topic is created. So we *shouldn't* (with an Exception listed below) have the problem of lastActivityAt field being updated when someone is added to the topic. 
Exception: If a user is added to the topic after the topic was created. This can occur in the following scenario - User A is newly added to the team and visits the dashboard or discussion page. User A gets added to all the topics for that project. lastActivityAt time would get updated for all those topics in that case. I am not sure how to work around this scenario TBH 😞 . 
We somehow need to provide a secondary sort param.

**Comment by vikasrohit** [comment]
Okay. However, the exception case seems to be there frequently because most of the projects would keep having new team members as project progresses. Right?

**Comment by parthshah** [comment]
Would it? Once the project has started the team shouldn't change a whole lot unless there are managers being swapped etc. In any case, adding a second sort criteria should help, right?

**Comment by vikasrohit** [comment]
Yes, second search criteria should help, however, what it would be? If we are able to find a good second sort param (which ideally should be a date of latest post, with type being 'post', date for the topic), we can use it as first sort param itself. Why to use it as second sort param. 😬

**Comment by fnisen** [comment]
Guys, looks like we dropped this one, so bumping it. What still needs to be done?

**Comment by vikasrohit** [comment]
I think we are still having this issue, able to see the issue for https://connect.topcoder.com/projects/222

**Comment by fnisen** [comment]
@mahestro's view of the Dashboard: 

![yalltours - topcoder 2016-12-14 11 am-30-45](https://cloud.githubusercontent.com/assets/12552247/21193248/7db2962c-c1e0-11e6-924b-8f2a227883b4.png)

The first few posts are out of order, even ignoring the Coderbot posts

**Comment by parthshah** [comment]
Let me try to clarify (maybe for my own sanity :) ) - there are 2 entities here topics and comments. 
Earlier discussion on this thread was about sorting topics. The last message from @fnisen is about sort order for comments within the topic. This is most likely a separate issue, so moving it here - See #587

Back to sort order of topics, lastActivityAt, I'll try making a change in the API to ignore user-joined type of posts to calculate lastActivityAt. That should help.

**Comment by parthshah** [comment]
this should be resolved now. Please re-open if you think otherwise.

**Comment by fnisen** [comment]
Yup, haven't seen this lately. Thank you.
