### ISSUE TITLE
Dashboard/Links: need to confirm link deletion

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#54]
Currently deleting links (by clicking the trash icon) is instant. We should confirm deletion, as shown in the design: 
![273e50e4-0a5a-411d-9df9-011e075005c3](https://cloud.githubusercontent.com/assets/12552247/18332608/e343a4d8-751c-11e6-94da-a1293164447e.png)

**Comment by vikasrohit** [comment]
@fnisen @vic-appirio  Mocks shows the delete confirmation modal to be there before the first link link in the list just like the modal for adding a new link. However, for team management we are showing the delete confirmation modal just below the member we deleting. So, to be consistent, I am rendering the modal just below the link user is deleting. If you guys see it differently, please let me know, I would update it accordingly.

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/178277611234933

**Comment by vikasrohit** [comment]
Done. Waiting for green signal to get it merged into dev.

**Comment by fnisen** [comment]
@vikasrohit yes, good catch, let's go with your approach! Please merge when ready.

**Comment by fnisen** [comment]
@vikasrohit tried this just now and link deletion is not working at all in Chrome (I don't see the trash icon). It is working in Firefox. Perhaps the user role is making a difference (I'm signed in as different users on different browsers), but anyone from the project should be able to add and remove links, regardless of role.
