### ISSUE TITLE
Project Details: notify user when they are leaving Specification tab without saving changes

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#541]
### Expected behavior
When there are unsaved changes (any change in the form or feature picker) and a user clicks on another tab, they should be notified that there are unsaved changes and confirm that they want to leave

### Actual behavior
User is not notified and all changes are lost

**Comment by vikasrohit** [comment]
Got it fixed by community. Winner: utkarshkukreti

**Comment by fnisen** [comment]
![screen shot 2016-11-18 at 11 31 02 am](https://cloud.githubusercontent.com/assets/12552247/20443709/ce4c4352-ad82-11e6-8f67-7e705da39c9a.png)

@vikasrohit can you please make one small change: the default should be "Cancel," not "OK"

**Comment by vikasrohit** [comment]
Sorry @fnisen This is default rendering of the browser. We can't override this behaviour. Even we can't guarantee that our message will be displayed. It is completely upto the browser to use the message to render the alert. e.g. Two different kind of alerts will be shown when user moves away from the page:
1. When user moves within application (our custom message is shown)
2. When user tries to close the tab or tries to logout (which is actually an external link), browser shows its own alert with default message which can't customize.

**Comment by fnisen** [comment]
OK, got it, no problem. Thanks for the explanation @vikasrohit.
