### ISSUE TITLE
Project Specifications || Save buttons should be disabled when form is pristine

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#542]
### Expected behavior
1. Make a change to the spec of any project (say in the notes) 
2. Hit save; button should be disabled (greyed out) and should remain in that state after successful update. In case of error it should turn blue again.
As obvious, buttons should be disabled on page load as well because the form is in pristine state.

### Actual behavior
1. Make a change to the spec of any project (say in the notes) 
2. Hit save; button is temporarily disabled (greyed out), but then enabled(blue) again
3. Hit save again; button is now disabled(greyed out) and stays disabled until you make a change

### Steps to reproduce the problem
1. Login as a user who can edit a project
2. Go to the specifications tab of any editable project
3. Follow the steps mentioned in 'Actual behavior' section

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any role that allows editing a project
- Account used: N/A

**Comment by vikasrohit** [comment]
For background please see https://github.com/appirio-tech/connect-app/issues/252#issuecomment-260040993

**Comment by vikasrohit** [comment]
Got it fixed by community. Winner: utkarshkukreti

**Comment by fnisen** [comment]
Working well. Thank you.
