### ISSUE TITLE
Change project name search to project keyword search

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#543]
Project API now supports 'keyword' filter that searches across name, description & invite code fields. Please update the front end code accordingly. 
Sample API Request

```curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJhZG1pbmlzdHJhdG9yIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJwc2hhaDEiLCJleHAiOjE5NzE3Mzk3NTAsInVzZXJJZCI6IjQwMTM1OTc4IiwiaWF0IjoxNDcxNzM5MTUwLCJlbWFpbCI6InBzaGFoK3Rlc3QxQGFwcGlyaW8uY29tIiwianRpIjoiZTYzMDM5MzctMTNiYS00OTlmLWJjMGQtYTkwYmE5NDlmN2E2In0.RVpnTzjsDGjaFxLlx-iRq-3edSVRqPkv-r4pdETpZO4" -H "Cache-Control: no-cache" -H "Postman-Token: 1b4fcc64-8550-14af-d7f0-966468326bd9" "https://api.topcoder-dev.com/v4/projects/?fields=name%2Cid%2Cdescription&filter=keyword%3D1234"```

@fnisen fyi

**Comment by vikasrohit** [comment]
@parthshah Done. Changes should be in dev. Just fyi, if any user has bookmarked a link with search filter, it would break i.e. user has to delete the bookmark and bookmark it again after this change.

**Comment by fnisen** [comment]
Very nice you guys @parthshah and @vikasrohit! Working well. Thank you.
