### ISSUE TITLE
NPM Install error

### ISSUE THREAD

**Issue by imvetri** [appirio-tech/connect-app#544]
### Expected behavior
Describe. npm install should download all the packages for the project

### Actual behavior
Describe. npm install results in 

npm ERR! fetch failed https://registry.npmjs.org/react-datetime/-/react-datetime-2.7.4.tgz

### Steps to reproduce the problem
- Git clone the project
- run npm install

### Screenshot/screencast
Attach or link a resource.
![npm_install_error](https://cloud.githubusercontent.com/assets/6542274/20420450/e7faaf36-ad83-11e6-8068-a5d1945701b1.png)
--

#### Environment
- OS: Mac - El Captain
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vikasrohit** [comment]
Thanks for noticing it. It seems to be because of https://github.com/YouCanBookMe/react-datetime/issues/197. I tried to hardcode the version for react-datetime, however, that didn't fix it for me. We will continue to look into it.

**Comment by vikasrohit** [comment]
Committed a temporary fix in dev branch. We would remove this fix when react-datetime is fixed.
