### ISSUE TITLE
General: All owners wiped from projects in production

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#548]
Something weird happened in Connect that I noticed just now--all owners were removed. No owners are showing up in the "customer" column on the project listing and project teams don't have anyone with the "Owner" label on the team management panel. 

You'll notice that some projects do have an owner when you look at the listing. I added all of these manually.

**Comment by vikasrohit** [comment]
@fnisen I did try to debug it. However, I am not able to identify the cause. Can you please let me know any example where you remember that the project had owner earlier but not now and who was the owner at that time. It would help me in debugging the issue.

@parthshah Do you see any problem with this code?
src/projects/reducers/project.js
<pre>
`// in case this member was marked as owner unset any other member that was owner
 const updatedMembers = _.cloneDeep(state.project.members)
  _.forEach(updatedMembers, m => {
      if (m.role === action.payload.role) m.isPrimary = false
 })`
</pre>

**Comment by fnisen** [comment]
@vikasrohit a good example is this project: https://connect.topcoder.com/projects/77. "adamf321" was the owner (I made him the owner again today). He was still on the team, but no longer had the "Owner" title. 
Another example: https://connect.topcoder.com/projects/76; owner was "bluedotdental" (made him owner again today)

**Comment by vikasrohit** [comment]
@fnisen I am not yet comfortable with roles logic in connect. Right now I am working on #551, which would give me better understanding about how Team Management's roles are working. May be after that I would be able to debug the issue. Right now I am not able to reproduce the issue in dev.

**Comment by fnisen** [comment]
Going to close this for now b/c it hasn't reoccurred.
