### ISSUE TITLE
Team management: increase Manager functionality

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#551]
I'd like to add to the Manager use cases in the team management functionality. 

1. A Manager should be able to add another Manager; e.g., if a Manager adds a team member that also has a system Manager role, the newly added manager should show up with the "Manager" title. Currently, they would just show up as a regular team member (currently, they have to join themselves in order to have the Manager title). 

2. A Manager should be able to reassign ownership to another team member. Currently, this can only be done by the existing owner.

**Comment by vikasrohit** [comment]
@fnisen If allow managers to assign ownerships, I guess, we can(should) safely remove the confirmation alert which show when a manager adds a customer for the first time in a project. https://github.com/appirio-tech/connect-app/issues/346 implemented that confirmation modal.

**Comment by vikasrohit** [comment]
@fnisen For first requirement, I need the role of the member being added to the team. I have tried almost all possible ways (getting it from members ES index, member service or user services) to get the role of the member, however, I failed to do so. Without role, there is only way to achieve the requirement which is to add a new tab in the switch i.e. Manager|Member|Copilot. However, this approach will also require getting role of the user to prevent adding a customer as Manager.

@parthshah Can you please let me know if we have a way to get the role of the user (non logged in).

**Comment by vikasrohit** [comment]
@sudoster Can you help me out here?

**Comment by sudo-tc** [comment]
I believe the current limitation is correct from security perspective. Non admin user should NOT be able to manage (change, create, view) OTHER user's roles.

We should not be exposing this feature bare to JavaScript, but provide necessary logic to change other user's role in the server side. The server logic should expose API that "ultimately" change other user's role, but the change should be done from server credential (which has admin JWT) and checking that API caller actually has ability to change other user's role and is valid change.

**Comment by vikasrohit** [comment]
Thanks @sudoster I think I can manage it in the backend.

**Comment by fnisen** [comment]
Agree, we don't want to do role management as part of this feature. 

@vikasrohit I would prefer the basic implementation of this if possible: when a Manager is added to the project, they're automatically added as a Manager. I don't want to get into the scenarios of having a Manager act as a Member or Copilot on the project because I think that will cause confusion. If you're not able to get the role, let's discuss, but maybe we don't implement this for now.

**Comment by parthshah** [comment]
@vikasrohit  - we already have current logged in user's role accessible in FE. Can we not use that information to determine if we need to show 'Owner' role option when adding members. We don't want to change the user's TC role, just his/her project role, correct?

**Comment by vikasrohit** [comment]
@parthshah Yes, agree we have logged in user's role but that won't be useful for adding a user as Manager for the project because in this case we need to determine the role of the user being added which we are not able to get.
@fnisen IMO, we need the role of the user being added to achieve the functionality. I think I can manage that in server side without exposing anything on front end. I can start working on this after web to lead functionality.

**Comment by vikasrohit** [comment]
@sudoster @parthshah @fnisen Sorry, but I was not able to find any API from which I can retrieve the user's role even using the admin token from the backend. Without role, I won't be able to implement this feature.

**Comment by vikasrohit** [comment]
@sudoster @parthshah @fnisen Discussed with Kohata-san about this, and we don't think that there is any endpoint to get role of a non logged in user. So, without that I am not sure how to automatically add a Topcoder Manager as Manager in connect project.

**Comment by parthshah** [comment]
Ok, thanks for working through this @ykohata & @vikasrohit.
@fnisen if this is a high enough priority, @sudoster would you want to add such an endpoint for 'admin' users to retrieve user roles in identity service?

**Comment by fnisen** [comment]
Yes, would like to have this working if it's not too complicated to add the endpoint.

**Comment by vic-topcoder** [comment]
@mtwomey - keep this for discussion/history. This is a reported bug we want to fix - user roles & permissions
