### ISSUE TITLE
General: restore terms of service page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#557]
### Expected behavior
"Terms" footer link takes user to terms of service

### Actual behavior
"Terms" footer link goes to 404 page

We lost the terms of service page during the switch from v1 to v2. The original page is available here: https://github.com/appirio-tech/work-app/blob/7f568e0043a7de02209c0296478303b05cc52455/app/views/terms.jade. Can you please restore it?

**Comment by vikasrohit** [comment]
@fnisen I have added a new page under v2 app. I have tried to copy as is, however, we don't have Proxima Nova font now, so I have to use roboto for that. Please have a look on the new page in dev and let me know if any more update it needed.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Looks good.
