### ISSUE TITLE
Dashboard/Project info/Team management: Member search seems inaccurate

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#56]
Not able to find/add Petr to the project, even though his account exists in Dev: https://www.topcoder-dev.com/members/petr/

**Comment by mahestro** [comment]
Not sure if we should handle this through community. Seems like an API issue to me.

**Comment by fnisen** [comment]
@mdesiderio assigning to you please. Let me know if you're not the correct person to handle it.
