### ISSUE TITLE
General: Redirect connectv2.topcoder.com to connect.topcoder.com

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#561]

**Comment by parthshah** [comment]
@vikasrohit - can you please add a redirect route in connect-app.

**Comment by vikasrohit** [comment]
@parthshah I didn't get how to add redirect route for the home page of the same app. I mean, shouldn't it be done in nginx? It would stuck in infinite loop if I do it in connect app. Please let me know if I misunderstood things here.

**Comment by parthshah** [comment]
connect subdomain is directly being served through Route53 no nginx is involved today. We could technically have supply nginx support connectv2 sub-domain but I rather not add to the mess there. 
I was hoping we could add a snippet in connect-app,  maybe in root routes, to check if the host is connectv2... and if so issue a permanent redirect to connect.

**Comment by vikasrohit** [comment]
Okay. Done. Although, I am not able to see any troubles right now with these changes, we might need to revert the changes, if they cause any problem after deployment on production. In case, I am not available at that time, we just need to remove the onEnter callback from the root route.

**Comment by fnisen** [comment]
👍
