### ISSUE TITLE
Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by koukimetal** [appirio-tech/connect-app#563]
### Expected behavior
In dev branch, Some page should appear http://localhost:3000

### Actual behavior
I got white page.

### Steps to reproduce the problem
npm i
npm start

Many `Cannot resolve module 'react/lib/ReactMount'` appear

### Screenshot/screencast
Attach or link a resource.

--

I found https://github.com/mjohnston/react-native-webpack-server/issues/45
I changed version of react-hot-loader from `^1.3.0` to `3.0.0-beta.6`

Then I got another errror

>Module build failed: Error: React Hot Loader: The Webpack loader is now exported separately. If you use Babel, we recommend that you remove "react-hot-loader" from the "loaders" section of your Webpack configuration altogether, and instead add "react-hot-loader/babel" to the "plugins" section of your .babelrc file. If you prefer not to use Babel, replace "react-hot-loader" or "react-hot" with "react-hot-loader/webpack" in the "loaders" section of your Webpack configuration.

So I removed `react-hot` from `loaders`

Then I got usual page.

I'd like to confirm this problem happens for everyone and whether this fix is correct.
If it's correct, I'll send a pull request.

#### Environment
- OS: mac 10.10.5
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vikasrohit** [comment]
Valid issue. Thanks for reporting.

**Comment by vikasrohit** [comment]
Temporary solution, until 3.x release of `react-hot-loader` is not published, is https://github.com/gaearon/react-hot-loader/issues/417#issuecomment-261548082
