### ISSUE TITLE
Dashboard/Project info/Team management: Copilot role not shown on team panel

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#57]
Have added a copilot to my project (https://www.topcoder-dev.com/members/jasoncopilot/), but he is not being identified as a copilot, as show in the design. Not sure if this is an issue with how the new Connect copilot role is being assigned or a bug.

![screen shot 2016-09-07 at 5 11 08 pm](https://cloud.githubusercontent.com/assets/12552247/18332753/18acee6c-751e-11e6-8e3f-b7b18bbdae7f.png)
![screen shot 2016-09-07 at 5 11 24 pm](https://cloud.githubusercontent.com/assets/12552247/18332758/23d2d18a-751e-11e6-95ef-81eef9242db0.png)

**Comment by vikasrohit** [comment]
I think it was intentional. When a user is power user i.e. he/she can add/delete members from the project, we are not showing the member's role because we have to render the buttons to allow user to perform those power operations. If one login with non power role, he/she can see the member's roles. It is how it is coded right now, please let me know if we need to handle it some other way.

cc: @parthshah

**Comment by fnisen** [comment]
@vikasrohit it's true that only managers and copilots can add copilots (as shown in permissions chart below), but everyone should be able to see the role. So, everyone on the project should be seeing the three possible roles: owner, manager, copilot. 

<img width="537" alt="screen shot 2016-09-09 at 11 48 20 am" src="https://cloud.githubusercontent.com/assets/12552247/18398920/a20a15d4-7683-11e6-8af0-55a3a1f8a95c.png">

**Comment by mahestro** [comment]
Will you take care of this @vikasrohit?

**Comment by fnisen** [comment]
@mahestro: not sure of the context of your question, so let's take this approach please: 
- if you can fix the bug via community (challenge, task, private task, etc.), please do that
- if not, please direct it back to us, either to someone specifically who you know can fix it, such as Vikas, or back to me for triage. 
Thank you.

**Comment by mahestro** [comment]
I wasn't sure if it was addressed to me or vikas :)

I will send it through the comm.

**Comment by mahestro** [comment]
Live https://www.topcoder.com/direct/contest/detail?projectId=30055196

**Comment by mahestro** [comment]
Done - https://www.topcoder.com/direct/contest/downloadSoftwareSubmission.action?projectId=30055196&submissionId=515256

Merge needed.

**Comment by parthshah** [comment]
So we always want to show member's role on the project in team management? Even for current logged in member? I believe the current implementation is as per design - https://drive.google.com/drive/folders/0B1LbmKnex41fc2MxS0lnakIxZlU.
