### ISSUE TITLE
Project listing: page navigation is missing in Dev

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#573]
<img width="1274" alt="screen shot 2016-12-08 at 5 08 07 pm" src="https://cloud.githubusercontent.com/assets/12552247/21033929/fc41df10-bd68-11e6-8f6d-6f0c77588246.png">

Not sure what happened and am worried we'll push this bug out to Prod.

**Comment by vikasrohit** [comment]
@fnisen It seems something has changed in project API. Its returning only 20 records now for pshah_manager user. @parthshah Are you aware of any such change in the API?

**Comment by parthshah** [comment]
Good catch. This was introduced with the latest changes around project search (not in production yet). Missed this in testing community code. This should be fixed now.
