### ISSUE TITLE
Dashboard/Project Info/Team management: need a state for user who leaves the project

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#58]
After a user leaves the project, from the team management panel, they remain on the project dashboard, rather than getting a confirmation message and being taken to another page (e.g., the Home/Projects Overview page). 

@vic-appirio: can we handle this by showing a toaster message confirmation and taking the user to the Listing page?

**Comment by vic-appirio** [comment]
Would be nice to white out the whole screen and then reload the home page. This would communicate that the space is being "deactivated" for the user, instead of a simple toaster message. Our new notifications are displayed on top of the navigation bar, and that I think is not enough.

**Comment by fnisen** [comment]
@vic-appirio so summarizing: user leaves --> screen goes white if we need loading time --> user directed to Home/Projects Overview (cards or listing)

**Comment by mahestro** [comment]
I have another proposal. How about:
- user leaves
- user directed to projects page
- a notification is displayed in projects page with "you've successfully left the project" sort of message.

??

**Comment by fnisen** [comment]
@mahestro that sounds like a good approach, as well. 

@vic-appirio can you please weigh in? You and Luis can make the final call.

**Comment by vic-appirio** [comment]
This is a good idea, @mahestro. Let's just do that - display a notification after the user is on the projects page.

**Comment by mahestro** [comment]
All right. I think we depend on the notifications implementation #52. You want me to tackle that down as well?

**Comment by fnisen** [comment]
@vic-appirio is Didi going to handle #52 on her own or do you need @mahestro to help?

**Comment by fnisen** [comment]
bump for @vic-appirio

**Comment by vic-appirio** [comment]
We might need some implementation on the component. We have final speck, but I'm not sure how the component code looks like. Go ahead an dispatch a notification for the moment, the alert styling shouldn't inhibit the fix.

**Comment by fnisen** [comment]
@mahestro OK, over to you.

**Comment by parthshah** [comment]
I can take this one.

**Comment by parthshah** [comment]
@fnisen - do we need a message / notification when an owner/manager removes another user from a project?

**Comment by mahestro** [comment]
Thanks @parthshah. This one is already in progress (pvt task). You want me to cancel it? I can check the amount of progress.

**Comment by parthshah** [comment]
@mahestro your call.. just trying to help close some of these issues :)

**Comment by fnisen** [comment]
Weird... Parth's last comment came through by email, but not on the actual issue. Anyway, @mahestro no need to cancel, unless you want Parth's help. 

Also, @parthshah, yeah, we're missing a lot of "non-critical" notifications. Started keeping a list here for post-beta: https://app.asana.com/0/100118202245271/184154465299368
