### ISSUE TITLE
Ignore 'user-joined' type posts in Topic comments

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#585]
@vikasrohit can you make sure 'user-joined' type of posts are ignored in Topic comments. 
Here's an example: 
https://connect.topcoder.com/projects/222

![image](https://cloud.githubusercontent.com/assets/1987710/21153102/e360d362-c11d-11e6-90f0-9c30df476958.png)

**Comment by vikasrohit** [comment]
@parthshah We already have the check to omit all non 'post' type posts. It seems we are getting few empty 'post' type posts from the API.
<img width="1280" alt="github 585" src="https://cloud.githubusercontent.com/assets/2417632/21171853/8639f7f4-c1f4-11e6-97be-5eae97a56e33.png">

**Comment by parthshah** [comment]
That is strange. Can we ignore posts by system and body is empty. There might be system posts that we want to display in the future but they should all have some data

**Comment by vikasrohit** [comment]
Done. Merged changes into dev, however, due to some strange reason, travis is not able to build the branch.
