### ISSUE TITLE
Comments Sort order within a topic is incorrect

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#587]
https://cloud.githubusercontent.com/assets/12552247/21193248/7db2962c-c1e0-11e6-924b-8f2a227883b4.png

See attached file for sample data.
[post.json.txt](https://github.com/appirio-tech/connect-app/files/652542/post.json.txt)

fyi @fnisen

**Comment by fnisen** [comment]
This is the project referenced in the screenshot: https://connect.topcoder.com/projects/222

**Comment by vikasrohit** [comment]
Done. Merged changes into dev, however, due to some strange reason, travis is not able to build the branch.
