### ISSUE TITLE
General: need super basic Connect home page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#59]
Currently going to connectv2.topcoder-dev.com when logged out takes you to a page like this: 
![screen shot 2016-09-07 at 5 19 12 pm](https://cloud.githubusercontent.com/assets/12552247/18332932/605f97e0-751f-11e6-80c6-0404f4e214cf.png)
... not a good experience. The marketing site currently just links to connect.topcoder.com, which takes the user to a log in. Can we put together a super simple home page (maybe starring Coder?) so that the user at least knows they've come to the right place?

**Comment by vic-appirio** [comment]
I'll design some login screen with general explanation of what Connect is; we agreed to replicate the experience of FB landing page when logged out.

**Comment by fnisen** [comment]
@vic-appirio sounds good. One note: don't embed Reg or Login into the page, as Facebook does. We have to direct the user to the accounts app for Reg and Login. Just use Reg and Login links on the landing page.
