### ISSUE TITLE
Status update: a comment post remains in the composer window after being posted

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#596]
<img width="744" alt="screen shot 2016-12-22 at 11 40 43 am" src="https://cloud.githubusercontent.com/assets/12552247/21444518/1fa75746-c863-11e6-9f7b-266b46a12491.png">
This is happening with status updates.

**Comment by vikasrohit** [comment]
Thanks @fnisen for noticing this. It was a regression after fix for the #166 Fixed now, please let me know if you still face any issue related to this.

**Comment by fnisen** [comment]
@vikasrohit yes, found one more. After creating a new thread and posting, there browser still thinks there is content in the composer window: http://www.screencast.com/t/KefrpwHYWgq

**Comment by fnisen** [comment]
@vikasrohit yes, found one more. After creating a new thread and posting, the browser thinks there is still content in the composer window: http://www.screencast.com/t/KefrpwHYWgq. Seeing this in prod and dev (try this project: http://connect.topcoder-dev.com/projects/438/discussions).

**Comment by vikasrohit** [comment]
Thanks again @fnisen for the careful observations. I don't know how I missed that, I am doing regression around the feature every time.

**Comment by fnisen** [comment]
Thanks @vikasrohit. No worries.
