### ISSUE TITLE
Should clear the text editor content once it has been posted

### ISSUE THREAD

**Issue by talesforce** [appirio-tech/connect-app#602]
### Expected behavior
Currently, if I enter any text in 'Create a new comment' box and hit 'Post', it should clear the text box

### Actual behavior
It does not clear the text box even though the same message has already been posted. It is very confusing not to clear the text box and I ended up submitting duplicates for the same message

### Steps to reproduce the problem
Follow about

### Screenshot/screencast
Follow above

--

#### Environment
- OS: Sierra
- Browser (w/version): All
- User role (client, copilot or manager): Copilot
- Account used: talesforce

**Comment by vikasrohit** [comment]
Should be fixed now (in dev) as fix for issue mentioned in https://github.com/appirio-tech/connect-app/issues/596#issuecomment-269366828 has been deployed in dev.

**Comment by fnisen** [comment]
Thanks for reporting @talesforce. As Vikas mentioned, this was fixed as part of https://github.com/appirio-tech/connect-app/issues/596 and will be out in the next release.
