### ISSUE TITLE
Handle missing/deleted user for feeds/comments

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#603]
### Expected behavior
Should render the project dashboard or Discussions tab, when any of them has a feed/comment for which API is somehow failing to load userId field.

### Actual behavior
It stuck in loading state and throws errors in console.

### Steps to reproduce the problem
- There is not specific step to reproduce. Only way is to remove, in API response, userId field for any feed or its comment. May be we show the missing/deleted user as "Deleted User" with a default avatar.

### Screenshot/screencast
Right now it can be reproduced for http://connect.topcoder-dev.com:3000/projects/273
<img width="1280" alt="screen shot 2016-12-28 at 5 00 38 pm" src="https://cloud.githubusercontent.com/assets/2417632/21521039/2ebdd672-cd1f-11e6-8613-00da6ee8759e.png">

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Anyone who has access to project dashboard
- Account used: N/A

**Comment by vikasrohit** [comment]
@fnisen It is not a critical issue, however, I think it can happen if there is some issue/error in messaging API, considering the issues with user creation in discourse. Better would be handle that gracefully, so that users can at least see the page and identify the issue. 

cc: @parthshah @ajefts

**Comment by fnisen** [comment]
@vikasrohit so would the approach be to capture the error response and render some kind of default message? Should we expand the handling to any kind of API failure (not just related to user creation)?

**Comment by vikasrohit** [comment]
I think we are already handling those kind of errors. However, the error situation I mentioned is after a post/comment is successfully created. I am not sure, why message api is not returning userId field for some comments for my project (http://connect.topcoder-dev.com/projects/273), but it seems like either the user who posted those comments is somehow deleted from the discourse or may be the messaging api is not able to lookup a valid topcoder user for the discourse user who created those comments. In any case, to handle the situation, we need to show those missing users as 'Deleted User' or something more informative.

**Comment by parthshah** [comment]
There was a bug in the service awhile ago, it might have been related to that. I think this shoudl be fixed now. Please re-open if you have more recent use cases.
