### ISSUE TITLE
General: default avatar appears differently in nav and team management panel

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#61]
For users without an avatar, the default should be the first two letters of the username, not capitalized, on a randomly generated primary color background, as shown below. Currently, the team management panel shows the default as the combination of the first letter of the first name and the first letter of the last name; the nav shows the first letter of the username. Both of these are incorrect (different background colors are used in different places, as well).

@vic-appirio we've ended up being messy here. Right now tc-app uses your username in the nav, whereas we want to use your real name. We should standardize on what we display and use that to inform the avatar

![b3f2a941-1ff4-494e-a218-e91a5959ca28](https://cloud.githubusercontent.com/assets/12552247/18333513/8ea256b0-7524-11e6-86a4-51cfe6df2a6d.png)

**Comment by vikasrohit** [comment]
@fnisen we were aware of the incorrect avatar in topbar, I can fix that to make it look like avatar in team management panel. So after this change it would have avatar with first letter of first name and first letter of the last name. Further, the difference in background color is due to the difference in name used for generating the avatar so it should also be fixed with the change.
Please let me know if you guys like to generate avatar based on first two characters of the username.

**Comment by vic-appirio** [comment]
Avatar on top navigation doesn't need to reflect the full avatar - it is a simplified version of the full avatar. The structure was like this:
(full avatar)
[  img   ]  <full name>
[  img   ]  <username>

short avatar should be just <full name> on top. This is in the context of Connect being a business-focused product; whereas Topcoder is community-focused app, thus <username> has a historical significant use.

**Comment by vikasrohit** [comment]
@vic-appirio Didn't get what do you mean by full avatar and where we are showing that.

Anyway, I have fixed the topbar to have the avatar in the same format as we are showing in the team management component.

**Comment by fnisen** [comment]
Thanks @vikasrohit!

@vic-appirio I'm also confused by what you meant. Will follow up with you offline.

**Comment by fnisen** [comment]
@vikasrohit discussed with Vic; here's how it should work:

1. Top nav: Use image + first and last name (instead of username, as currently); shown in the design above
2. Team management panel: Use image + first and last name + username (this is what is being done currently, so no change)
3. If there's no space in some area, we can just use image (cut first and last name and username)

When there is no image, let's default to initials from first name and last name for the avatar (as you said would happen after this change). Thank you.

**Comment by vikasrohit** [comment]
Done. Please let me know if you still feel it is not correct.
