### ISSUE TITLE
In UI, handle Direct project not being set

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#610]
When a Connect project is first created, a corresponding Direct project is created, as well. However, if the call to Direct fails, the user (Manager or copilot) will not know that a Direct project doesn't exist. Parth is now handling this case on the backend. Can we please also support this in the UI by changing the copy for the Direct link on the Dashboard? When successfully created, the link says "Project in Topcoder Direct." For the error case, let's say "No Direct project. Please contact support."

@parthshah FYI

**Comment by vikasrohit** [comment]
@fnisen @parthshah We are already checking if direct project id exists in the API response, and if it is, then only we show the direct project link. So, I am not sure how can there be a case where direct project creation failed but we have direct project id in API response.

**Comment by vikasrohit** [comment]
@fnisen just a bump up

**Comment by fnisen** [comment]
@vikasrohit OK, I think I understand. So, when there is no Direct project, you show the copy instead?

**Comment by vikasrohit** [comment]
Yes. When there is no direct project, I am showing "No Direct project. Please contact support." as link, which opens email client on clicking it.

**Comment by fnisen** [comment]
@vikasrohit, looks like no Direct projects are being created in Dev, so it's easy to verify. 
Can you please tweak the copy to say: "No Direct project created. Please contact support."

**Comment by vikasrohit** [comment]
Changes should be in dev by EOD.

**Comment by fnisen** [comment]
@vikasrohit I'm sorry for the hassle, but now the copy is stretched over two lines in the component, which looks bad. Let's get rid of the "please." New copy: "Direct project not linked. Contact support."

![screen shot 2017-03-10 at 12 01 02 pm](https://cloud.githubusercontent.com/assets/12552247/23811138/87469de0-0589-11e7-81c6-79bbc56b8f72.png)

**Comment by vikasrohit** [comment]
Done. Changes should be in dev by EOD.

**Comment by fnisen** [comment]
Working in Dev. Thank you.
