### ISSUE TITLE
Avatar issue in prod

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#611]
My avatar is frequently shifting between my image and my initials (see below). 

![screen shot 2017-01-03 at 4 31 42 pm](https://cloud.githubusercontent.com/assets/12552247/21628417/36c8ac66-d1d4-11e6-8eb0-ce517bec5740.png)

**Comment by vikasrohit** [comment]
@fnisen Can you please let me know few steps to reproduce this? I tried refreshing the project 222 and 303 multiple times, but I am not able reproduce the issue.

**Comment by fnisen** [comment]
@vikasrohit I don't know. My avatar has mostly disappeared recently, but don't know what could have triggered it.

**Comment by vikasrohit** [comment]
Okay. But I am not able to reproduce it with your FN_Manager account. I am refreshing the page multiple times but still able to see your correct avatar for Filipp Nisenzoun user.
