### ISSUE TITLE
Auto reload project topics 

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#615]
Users need to refresh the page to get the latest topics. Either reload the topics when specific actions are taken or poll for changes. We'll have to manage the use case when a user is adding a new post / comment, they should not lose focus.
fyi @fnisen , @vikasrohit

**Comment by vikasrohit** [comment]
>Either reload the topics when specific actions are taken
I am not sure how it would solve the case where some other user added new post/comment to the same project as in this case there is no action performed by the viewing user and he/she still has to reload the page manually. IMO, polling or opening a web socket are the only options.

**Comment by parthshah** [comment]
Definitely recommend polling, over the other approach, but just wanted to give options. Right now a project has been changed from draft to submitted state or any other state, once has refresh the page to see the system notification. 
fyi - @fnisen
