### ISSUE TITLE
Dashboard: comment post overflowing container

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#619]
Happening on several projects: 

https://connect.topcoder.com/projects/954
https://connect.topcoder.com/projects/975

<img width="926" alt="screenshot" src="https://cloud.githubusercontent.com/assets/12552247/22838941/31bce320-ef7c-11e6-8c59-3d03ac6a1e46.png">

Reported by Joey

**Comment by vikasrohit** [comment]
@fnisen It is happening because of <pre> tag which is not letting the sentence to break. What we can do to handle this case gracefully is to put horizontal scroll bar in per such message/post. Is that acceptable?

**Comment by fnisen** [comment]
@vikasrohit yes, please go ahead.

**Comment by vikasrohit** [comment]
Fixed and deployed to dev.
