### ISSUE TITLE
Project Listing: Style fixes

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#62]
Project Listing is the advanced view for power users in Connect where they can access all projects, and quickly get updates on a project status. This is the main page of Connect v2.

![72290a35-36a6-4133-abf5-d1617b29bab3](https://cloud.githubusercontent.com/assets/8484061/18399492/2214eff4-7686-11e6-9a39-49616e4e927f.png)

The main navigation — including the advanced filters — is not part of this fix. We focus only on the List view (table).

Speck is here: https://drive.google.com/drive/folders/0B1LbmKnex41fVVJwVzJvVFFIVE0?usp=sharing

**Comment by mahestro** [comment]
These styles were cleaned and updated.
