### ISSUE TITLE
Fix/refactor dumb icon components for the new product wizard

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#621]
We should be using only .SVG images and never render .PNG from .SVG. All state changes of the SVG should be handled as CSS modifications of SVG properties (fill, stroke, etc.).

What needs to be refactored: 
![screen shot 3](https://cloud.githubusercontent.com/assets/8484061/23195321/951c8184-f867-11e6-9cba-0107e7c81879.png)

We have several unnecessary components for the new project wizard:

ProjectAppVisualDesign.jsx
ProjectDesign.jsx
ProjectDevelopment.jsx
ProjectDevelopmentCode.jsx
ProjectPrototype.jsx
ProjectPrototypeDemo.jsx
ProjectPrototypeTechincal.jsx
ProjectWireframes.jsx
XMark.jsx

We need to refactor the use of those with SVG Loader. The component rendering the appropriate details should be good enough to handle the correct icon name passed as part of `~/src/config/projectWizard/index.js` → used in `~/src/projects/create/components/ProjectWizard.jsx`

**Comment by gondzo** [comment]
This has been handled in the integration challenge. The component loading the svg icons is src/components/SVGIconImage.jsx
