### ISSUE TITLE
New project - frame fixes

### ISSUE THREAD

**Issue by sirakovaDimitrina** [appirio-tech/connect-app#622]
- [x] New product wizard frame has an extra close button
- [x] Background is not on full screen
- [x] Inputs not to spec
- [x] Cards layout issues

**Comment by fnisen** [comment]
Guys, I think this is already addressed above, but the new frame unnecessarily takes over the page, unlike the old one, which stood out. Can we please stick with the previous design? 
<img width="1201" alt="screen shot 2017-03-02 at 11 05 47 am" src="https://cloud.githubusercontent.com/assets/12552247/23522583/60007bd6-ff38-11e6-8ead-5d42de90416d.png">

**Comment by vic-topcoder** [comment]
Closing as initial styles have been integrated. Fixes are tracked with new issues
