### ISSUE TITLE
Allow comments for System generated messages / status updates.

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#623]
Any reason to not allow project members to comment on system generated topics / posts? Now that we have system notifications / updates on most project events such as members joining etc., it would be nice to allow users to leave a welcome message to that same thread.

**Comment by vikasrohit** [comment]
From my understanding, the reason behind not allowing comments on system generated posts is that they are mostly one way in nature i.e. they convey some notification or update for the users. Another reason being a user can't interact with system user, at least until we have some AI in place. 😬 
However, as you mentioned now we have more events which are posted by the system user such as members joining, we can definitely enable user for commenting on such posts. But still the question remains is that if we should allow commenting on all status updates by system user or just specific ones? My opinion would be to allow commenting on all system updates.

**Comment by vikasrohit** [comment]
Please see https://connect.topcoder.com/projects/908. It seems we have a loop hole which allows user to comment of system user's posts.

**Comment by parthshah** [comment]
Project member's can respond via email just not through Connect 🤦‍♂️

**Comment by vic-topcoder** [comment]
I think we had a conversation about a month ago and we agreed to allow comments on system messages. This would be a nice way to capture request/questions/feedback from customers, as well as to greet new members, or just to piggy back and say hello when you're added to a project.

**Comment by fnisen** [comment]
OK, it's settled. @vikasrohit assigning to you to implement. Please support responses via email and Connect. Thank you.

**Comment by vikasrohit** [comment]
Roger that @fnisen :)
@parthshah just to confirm, we don't need any change to support commenting on system messages via email because it is already supported. 😬

**Comment by vikasrohit** [comment]
Changes should be in dev by EOD.
