### ISSUE TITLE
Dashboard link validation too restrictive

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#626]
Joey is reporting not being able to add a valid URL in the Connect links: http://topcoder.work:3500/ (note: this is a demo server run by Harry Wynn; the link is not working currently, but was live earlier)

<img width="394" alt="screen shot 2017-02-27 at 8 51 24 am" src="https://cloud.githubusercontent.com/assets/12552247/23385218/78332172-fd03-11e6-8f79-f2f1090fc2a1.png">

**Comment by vikasrohit** [comment]
We are not allowing port in the URL, that is why it is giving validation error. Are we sure we want to allow non standard ports in URL? I can't think of any side effect of it right now, but I am not sure if would not open doors for any kind of hacking. I have made changes(right now allowed only reasonable range of ports i.e. ports from double digit to five digit range) and create PR for the same, will merge it if we are sure to allow ports in the URL.
PR: https://github.com/appirio-tech/react-components/pull/120

**Comment by fnisen** [comment]
@parthshah @sudoster do you guys see any issue with doing this?

**Comment by parthshah** [comment]
Nope that should be fine. We already have no-follow and no-referrer attributes added.

**Comment by fnisen** [comment]
@vikasrohit can you please deploy this one?

**Comment by vikasrohit** [comment]
Okay. Should be on dev by EOD today.

**Comment by fnisen** [comment]
@vikasrohit did this make it out?

**Comment by vikasrohit** [comment]
Oh! sorry missed it in the release logs. Doing it right away.

**Comment by fnisen** [comment]
Thank you sir!
