### ISSUE TITLE
Project specification page - Add support for text area autosize

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#628]
For all text areas on the project specification page(s) we should add third-party text area resize plugin, https://github.com/andreypopp/react-textarea-autosize or something similar. The idea is to make reading the page easy without the need to resize the text area (or scroll through it) all the time.

**Comment by ThomasKranitsas** [comment]
@vic-topcoder @gondzo I created a PR on the `react-components` repo but I don't have write access there to merge it so please merge it. Thanks!

**Comment by vic-topcoder** [comment]
@ThomasKranitsas I see the code being added, but didn't see it used in the connect specification. What's the current status? (checking on feature/productsv1)

**Comment by gondzo** [comment]
@vic-topcoder it's merged now #690

**Comment by fnisen** [comment]
@ThomasKranitsas @gondzo not working for me, on this project: https://connect.topcoder-dev.com/projects/1014/specification in Firefox.

**Comment by fnisen** [comment]
Also working after redeployment.
