### ISSUE TITLE
Allow Managers to delete newly created projects

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#629]
Currently when a Manager creates a new project, they don't see the Delete button on the Dashboard (which a regular user would see)

**Comment by vikasrohit** [comment]
@fnisen Right now it is explicitly restricted to the owner of the project to allow deletion of a project in the draft mode. I am adding the project managers to the whitelist of the users to delete a draft project.
Also, IMO, we should ask for the reason of project deletion as well just like we do for the project cancellation.

**Comment by parthshah** [comment]
@vikasrohit delete action should be enabled only if the logged in user is the creator of the projector (createdBy field) and the project status is draft.

**Comment by fnisen** [comment]
Guys, our original thinking for deletion was allowing someone to get rid of a project before anyone else got involved... essentially a way to play around with project creation and not have anyone else know about it. Once a manager is involved, the customer is effectively canceling the project. Submitting the project for review or talking to a manager moves the project into the funnel; it cannot be deleted b/c it's a real project at that point. With that in mind, I think the scenarios we should support are: 

1. Current scenario: customer creates project; can delete while project is in draft. Once project is submitted for review, can no longer delete (a manager effectively joins the project at that point). 
2. - Add special case: when a manager joins the project, even if it's in draft, it cannot be deleted (b/c once a manager joins, it's effectively "In Review")
3. New scenario: Manager creates the project; can delete while project is in draft and there is no customer on the project (manager is "playing around" with project creation). Once manager adds a customer, the customer becomes the owner. At this point, neither the manager or owner/customer can delete the project; again, it's effectively moved to "In Review." 

What do you think? cc @vic-topcoder

**Comment by vic-topcoder** [comment]
Agree with @fnisen : We should allow managers to have more freedom in the system; including appointing project owners/changing project owners, deleting projects, changing project status, etc. Manager in essence is our ultimate administrator, so limiting them is not good.

Is there a case when we need to delete a project after it's been reviewed? If a project is being abandoned after review, what do we do with it? Do we move it to "canceled" status? or we expand the status types and not implement the drop-down for canceled "reason"?

**Comment by fnisen** [comment]
Thanks @vic-topcoder. A manager is not exactly the same as an admin though: they're just the reviewer/admin for a project, not for the entire system. 

Once a project is reviewed, it has to be canceled, not deleted. If the customer doesn't respond, we just mark that as the reason for the cancellation.

**Comment by fnisen** [comment]
@vikasrohit, @vic-topcoder has convinced me that I'm trying to be too fine with the scenarios and the underlying problem is really Managers using Prod for demos. So, let's not implement this. We can get Managers to move demos to other environments or figure out how to exclude them from the demo. Sorry for the extra work.

**Comment by vikasrohit** [comment]
No problem. Deleting branch.
