### ISSUE TITLE
Screen number options in project specification

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#638]
### Expected behavior
The maximum number of screens in the project specification should be 10, not 7.

### Actual behavior
Maximum number of screens is 7

### Steps to reproduce the problem
Create a project and go to the project specification page

### Screenshot/screencast

![image](https://cloud.githubusercontent.com/assets/3051646/23482107/2ffb63b6-fece-11e6-953c-5a02c9af0fc9.png)

--

#### Environment
- OS:all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by fnisen** [comment]
@gondzo don't worry about the exact numbers for now; we'll finalize those at the end, but please remove the skip option from this one. It cannot be skipped b/c it's tied to the price calculator.
