### ISSUE TITLE
Changing screen limit after defining some screens

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#639]
### Expected behavior
If user defined 7 screens it should not be possible to select option of 3 screens in 'No of screens' 

### Actual behavior
The options for lower number of screens are enabled and can be saved

### Steps to reproduce the problem
create a project and go to the project specification page

### Screenshot/screencast
![image](https://cloud.githubusercontent.com/assets/3051646/23482277/c3fb3fa0-fece-11e6-8714-3f732f83f17a.png)

--

#### Environment
- OS:all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by fnisen** [comment]
@ThomasKranitsas, @gondzo Not working for me on this project: https://connect.topcoder-dev.com/projects/1014/specification. Have 4 screens created, but can still switch to the 1-3 option.

**Comment by fnisen** [comment]
Working after redeployment. Closing.
