### ISSUE TITLE
Mandatory fields missing *

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#640]
### Expected behavior
Red * should be displayed for mandatory fields in the new screen section.

### Actual behavior
No feedback that the field is mandatory

### Steps to reproduce the problem
Create a project and go to the project specification page

### Screenshot/screencast
https://cl.ly/2Q1u033y341c

--

#### Environment
- OS: all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by fnisen** [comment]
@ThomasKranitsas this one is not working. I think the issue was that the code change was not made to all the project templates. Here is an example of a project that's not working: https://connect.topcoder-dev.com/projects/1014. Use these credentials: pat_monahan/topcoder123! in Firefox.

**Comment by ThomasKranitsas** [comment]
@fnisen Oh, I see.. The issue is that if for example a subSesction of type `questions` has the attribute `required: true` the questions of that subSection do NOT inherit that attribute.. Should I create a PR for this or should I fix it after the bug hunt has been completed?

**Comment by fnisen** [comment]
@ThomasKranitsas you can create a PR. Worst case we'll wait to merge.
