### ISSUE TITLE
Checkmark for selected screen number option

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#641]
### Expected behavior
Checkmark should be selected for the selected option in the No of screens section

### Actual behavior
Checkmark is not displayed

### Steps to reproduce the problem
create a project and go to the project specification page

### Screenshot/screencast
https://cl.ly/0R2T033b303q

--

#### Environment
- OS:all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by vic-topcoder** [comment]
This is a component-related issue. @gondzo can you make it a task for the winners who created the component? We need to update/use the same component from project creation inner pages on the project specification

**Comment by fnisen** [comment]
@ThomasKranitsas, @gondzo this is not working for me. I'm testing in Firefox, on this project: https://connect.topcoder-dev.com/projects/1014/specification/.

**Comment by fnisen** [comment]
Checking again after deployment fixes: working fine.
