### ISSUE TITLE
Style the project quick quote details in the left navigation

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#642]
The project quick quote is not up to speck in the left navigation/project specification page.

Current:
![screen shot 5](https://cloud.githubusercontent.com/assets/8484061/23490271/5d12ae80-feac-11e6-9771-112ad79eb8b9.png)

Expected:
![screen shot 6](https://cloud.githubusercontent.com/assets/8484061/23490275/62e53a12-feac-11e6-971d-ede1224eaeeb.png)

**Comment by fnisen** [comment]
@vic-topcoder can you please clarify who should be responsible for this?
Also, let's please keep "days" as we have it currently. "d" is not standard.

**Comment by vic-topcoder** [comment]
reassign to @gondzo if functionality is needed

**Comment by ThomasKranitsas** [comment]
@gondzo what exactly do I have to fix here?

**Comment by gondzo** [comment]
you can skip this one, it's handled by @sirakovaDimitrina

**Comment by vic-topcoder** [comment]
@sirakovaDimitrina: log in at your local environment with customer credentials.

Style the currency symbol according to spec.

![screen shot 7](https://cloud.githubusercontent.com/assets/8484061/23634431/06fd08de-027f-11e7-9de0-3af52c08b929.png)

**Comment by vic-topcoder** [comment]
@sirakovaDimitrina we should style only the `<span>$</span>` to be tc-gray, the rest of the text should be black.
![screen shot 11](https://cloud.githubusercontent.com/assets/8484061/23683956/baae2260-0350-11e7-9e03-18e622d25321.png)
![screen shot 11](https://cloud.githubusercontent.com/assets/8484061/23683963/c00b4454-0350-11e7-8024-daa00f9df673.png)

Expected:
![screen shot 13](https://cloud.githubusercontent.com/assets/8484061/23683979/cfcedeb4-0350-11e7-9db4-4b2cd961bd55.png)
