### ISSUE TITLE
Number of screens card should render text instead of SVG

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#643]
Fix the component to generate text instead of SVG in the component (`div` or `span`). This will allow us to style it correctly.

Current:
![screen shot 7](https://cloud.githubusercontent.com/assets/8484061/23490315/baf359f0-feac-11e6-9627-4c81eb66abb0.png)
![screen shot 8](https://cloud.githubusercontent.com/assets/8484061/23490321/c7163630-feac-11e6-9c64-5d9563680418.png)

**Comment by fnisen** [comment]
@vic-topcoder can you please verify this one?

**Comment by vic-topcoder** [comment]
Fixed - generates a Span
