### ISSUE TITLE
Unify the components used in New Project wizard and Project Specification page

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#644]
Inputs, card selector components, text areas should be reused on both sections; styled by only 1 CSS file per component. Make sure the components behave the same on all pages that (re)use them.

![specification-compoentns---specification](https://cloud.githubusercontent.com/assets/8484061/23490389/413aae50-fead-11e6-9670-a48c3293326c.png)

**Comment by ThomasKranitsas** [comment]
@vic-topcoder So I should update the `New project` page to use `react-components` instead of duplicate local components, right?

**Comment by vikasrohit** [comment]
Sorry for interrupting @vic-topcoder.

@ThomasKranitsas Yes, we should try to reuse existing components as far as possible. If you need more functionality or different appearance of the same component, please enhance the same component in backward compatible way. I have given an example of such case in your query in #674

**Comment by fnisen** [comment]
Any update on this one?

**Comment by ThomasKranitsas** [comment]
I'll try to update this ticket tomorrow as I was busy with some personal stuff yesterday & today...
This will require some effort as the components from the `New Project` wizard are completely different (from implementation POV) than the components from `react-components`

**Comment by fnisen** [comment]
OK, no worries. @vikasrohit do we need this done before launch?

**Comment by ThomasKranitsas** [comment]
@fnisen @gondzo I won't be able to finish this one. Can you assign it to someone else or open it for the bug bash?

**Comment by gondzo** [comment]
@all this one is available for pickup

**Comment by fnisen** [comment]
Changing to P2 b/c this doesn't need to be done before release.
