### ISSUE TITLE
Support text area classname for empty state

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#647]
For empty/filled textarea provide additional classname to be able to switch styles.

@sirakovaDimitrina please explain which classes are needed in which cases.

**Comment by vic-topcoder** [comment]
@gondzo - please reassign to @sirakovaDimitrina after the textarea supports classname changes based on status (empty/filled) for CSS fixes.

**Comment by ThomasKranitsas** [comment]
@gondzo how about this one? Will I or @sirakovaDimitrina handle it?

**Comment by vic-topcoder** [comment]
We need to add `.empty` when the text area has no content, and when it has it should be the other style. There's another ticket #628 for text area autoresize that @ThomasKranitsas can help with - this will make the text area render as paragraph text almost in read mode.

#646 is for fixing the text area style to be different from the inputs (to match specification)

**Comment by sirakovaDimitrina** [comment]
The textarea control should utilise the same functionality from the input control from “New Project” page. When the textarea is empty, it should have a CSS class name `.empty`.

**Comment by ThomasKranitsas** [comment]
I need a clarification on this..

The form fields (Textarea, TextInput etc) are from the https://github.com/appirio-tech/react-components repo while the TextInputs in the `New Project` page are from the `TextInput` component inside the https://github.com/appirio-tech/connect-app repo. Should I replace the component used in the `New Project` page with the TextInput component from the `react-components` repo and update the components there to use the `.empty` class where there is no content?

**Comment by sirakovaDimitrina** [comment]
Yes, That is right. When input and textarea has no content you should use .empty class.

**Comment by vikasrohit** [comment]
@ThomasKranitsas Yes, we should always try to reuse the components from react-components repo, unless it is substantially different from what is required. In all other cases, we should try to reuse it as is or modify/enhance it such that it backward compatible and still serves the new requirements e.g. SearchBar is one of the components which is used in both members app and connect app and it has different look/appearance in both applications. Best solution in this case would be to support themes in the SearchBar component and use different themes in members and connect apps.
Hope this clarifies things.

**Comment by ThomasKranitsas** [comment]
Currently only the `project name` & `ref code` fields in the project wizard have the `.empty` class because they use a component from the same repo.

The `TextInput` component in the `react-components` repo doesn't support the `.empty` class.

I need to add support the `.empty` class for both `TextInput` & `Textarea` components, correct?

**Comment by ThomasKranitsas** [comment]
@vic-topcoder  @gondzo please check this PR in `react-components`

**Comment by ThomasKranitsas** [comment]
You can modify the package.json to fetch react components from `ThomasKranitsas/react-components.git#support-empty-class` to test it in the `connect-app` repo

**Comment by fnisen** [comment]
@vic-topcoder can you please check this one?

**Comment by vic-topcoder** [comment]
@gondzo do we have the fix pushed to the original `react-components` repo?

**Comment by gondzo** [comment]
@vic-topcoder yes > https://github.com/appirio-tech/react-components/pull/125

**Comment by vic-topcoder** [comment]
Great, thanks!

**Comment by vic-topcoder** [comment]
Fixed.
![screen shot 4](https://cloud.githubusercontent.com/assets/8484061/23776041/90edbf76-04e0-11e7-95b1-a1e7263019cd.png)

**Comment by vic-topcoder** [comment]
When the specification page loads, several instances of the text area do not get the `.empty` class name. Once I go and enter text which I delete, the `.empty` classname is added and the text area is styled correctly. Reopening the issue for further fixing the initial rendering state

**Comment by ThomasKranitsas** [comment]
@vic-topcoder I see what you mean... I know what's causing that.. I'll fix it later today

**Comment by fnisen** [comment]
@vic-topcoder moving to you for testing

**Comment by vic-topcoder** [comment]
Works like a charm. The only thing we should remove is the transition of the side when growing the text area, there's an awkward scroll viewable when you press enter. That's a P3 if you ask me.

**Comment by fnisen** [comment]
@vic-topcoder OK, please file if you think that's worth fixing.
