### ISSUE TITLE
Remove notes from design/development/screens sections 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#648]
On project specification (v2) we should keep notes only on the main section (App Definition).

**Comment by vikasrohit** [comment]
Just to confirm it should be done for all type of products, right? I mean this change is not limited to any specific product offering?
And how we would support backward compatibility with this change? I mean any older project which has notes specified in any section other than `App Definition` would not be visible on front end. The data would still be there in database.
cc: @fnisen

**Comment by vic-topcoder** [comment]
Correct - for all product types we aim at keeping notes in the first section. I was thinking to follow what Parth said yesterday - make a new version of the spec document for all new projects. We're moving description and device selection in the specification document going forward, rather than the project creation wizard. Versioning the project specification would ensure all old instances will still display the data as designed, but new ones will have the correct sections. Once the old projects are completed, it'll be not a problem. Not sure if we'll ever do a retroactive project upgrade/consolidate the information. Also - moving forward we might modify the project specifications on different products as this is still very early stage of what questions we ask and need, and there's bound to be an evolution in the specification.

@parthshah @fnisen - chime in if I'm wrong or missing anything

**Comment by parthshah** [comment]
That's what I was hoping we would do. Since there are breaking changes, we should be creating a new version for non-AVD projects as well, `topcoder.v2.0.0.js`. All new non-AVD projects should default to this specification once the project has been launched. All new projects **must** have spec version in the details section. Any project that doesn't have a spec version can be defaulted to `topcoder.v1.js`.

**Comment by fnisen** [comment]
@vikasrohit talked with Parth and Vic about this. Please do set up the versioning. However, don't delete the notes sections for now. We'll review the intake with Vic and finalize in a few days, so that we only make the change once.

**Comment by vikasrohit** [comment]
Okay, roger that.

**Comment by vikasrohit** [comment]
Created separate issue #659 for better tracking.

**Comment by fnisen** [comment]
All, confirming here that we will remove "Notes" from the "App Screens" section for sure, as referenced on #637 b/c it wasn't meant to be there to begin with (it's a new section). More info on "Notes" in other parts of the spec to come later.

**Comment by gondzo** [comment]
@fnisen Should we close this for now ?

**Comment by fnisen** [comment]
@gondzo @vikasrohit should handle this one. Vikas, have you set up versioning? If so, we can close this one.

**Comment by vikasrohit** [comment]
@fnisen Yes, we have versioning in place. Do we need to remove Notes from all section except the Project Information section?

**Comment by fnisen** [comment]
@vikasrohit no, not for now. I'll close this one.
