### ISSUE TITLE
Visual fixes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#649]
We have to do some small fixes on the specification layout to bring it 100% to spec.

Side by side comparison:
![screen shot 17](https://cloud.githubusercontent.com/assets/8484061/23491787/50ef026c-feb5-11e6-8e8d-cd7b2cdf332c.png)
![screen shot 18](https://cloud.githubusercontent.com/assets/8484061/23491790/52614b0a-feb5-11e6-8a75-2835d0ecee1a.png)

Section title font color must be darker;
Check spacing between elements;
Fix development specification styles;

**Comment by vic-topcoder** [comment]
Section title isn't the correct color `tc-gray-70`
![screen shot 6](https://cloud.githubusercontent.com/assets/8484061/23634077/5a89054a-027d-11e7-8271-fafd77271a16.png)

**Comment by vic-topcoder** [comment]
fixed

**Comment by fnisen** [comment]
@vic-topcoder please double-check if needed or close.
