### ISSUE TITLE
Specification content order/structure fixes

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#650]
Make sure the content on the page represents the structure/order as per design. @fnisen please advise if we have to modify anything.

![transition-v1-v2-spec---app-visual-design---v21](https://cloud.githubusercontent.com/assets/8484061/23491912/2b117a10-feb6-11e6-84fc-0a422b706059.png)
![transition-v1-v2-spec---general---v21](https://cloud.githubusercontent.com/assets/8484061/23491913/2b28ad02-feb6-11e6-85a8-e0280e368be9.png)

**Comment by fnisen** [comment]
Please hold on this one. I need to review the content still.

**Comment by fnisen** [comment]
@vikasrohit can you please restructure the initial project selection screens and the intake forms according to this document: https://docs.google.com/a/appirio.com/document/d/11d2uXJTg_zeVTviUTI1sM5BWfKLIluC56AnKbSv7wl4/edit?usp=sharing. Please let me know if it would be helpful to discuss on my Tuesday morning (I can do it at 7:30, 8am, or later).

**Comment by vikasrohit** [comment]
I will ping you @fnisen in your morning today.

**Comment by vikasrohit** [comment]
@fnisen I am not able to access the doc now. Is it deleted? Also, please let me know your feedback for the changes so that we can update the spec templates as needed.

**Comment by gondzo** [comment]
@vikasrohit try this link https://docs.google.com/document/d/11d2uXJTg_zeVTviUTI1sM5BWfKLIluC56AnKbSv7wl4/edit
(both are working for me)

**Comment by vikasrohit** [comment]
Thanks @gondzo however, my comments are lost in that document and if I try to reply using email to those comments, they are bouncing back.

**Comment by fnisen** [comment]
@vikasrohit not sure what happened with the access. I've reshared with both of your email accounts. I replied to your questions yesterday, so please let me know if you can't see my answers, and I'll just post here.

**Comment by fnisen** [comment]
@vikasrohit still seeing some issues in the App Definition section:
1. On the right side of the page, the "App Definition" section should be named after the product (e.g., not App Definition, but Wireframes); but still call it "App Definition" in the Specifications module
2. Brief description should come after target devices
3. Also, "brief description" does not need initial helper text. Right now that text says "No project description," which is not helpful. : )

**Comment by k-tempest** [comment]
Sorry, it's too complicated for me.

**Comment by vikasrohit** [comment]
@gondzo I am removing it from bug bash. I can handle it.

**Comment by vikasrohit** [comment]
@fnisen How do you like to handle the generic products i.e. 'Others - Design' and 'Others - Development'?

**Comment by vikasrohit** [comment]
for 3rd point, problem is that description is required field in the API so the winner of the challenge used a dummy text instead which is saved to database for every project created. We should update API to mark description field optional if we like to remove that dummy text.

cc: @parthshah

**Comment by fnisen** [comment]
@vikasrohit for the titles, let's call the sections "Design" and "Development" and on the left-hand panel, say "Design Definition" and "Development Definition" (or Dev Definition, if it doesn't fit)

Regarding the dummy text - we do want to require a description, but not at the time of project creation. If we end up having the dummy text there saved instead of a real description, it's not helpful. @parthshah could we make that change in the API?

**Comment by parthshah** [comment]
Sure. I'll make the change.

**Comment by gondzo** [comment]
fixing this will fix #736

**Comment by vikasrohit** [comment]
Done. @fnisen Please let me know if you think there is any more improvement we can do here in the scope of this task, otherwise we can create separate tasks for new individual bugs/improvements related to this task.

**Comment by vikasrohit** [comment]
Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit "Other Design" was supposed to use the current design intake (meaning the one in production right now). Currently it has screen selection and other unnecessary stuff. Opening another ticket. https://github.com/appirio-tech/connect-app/issues/839
