### ISSUE TITLE
New project modal: links at bottom of the page need to be wired

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#651]
<img width="783" alt="screen shot 2017-03-02 at 11 15 22 am" src="https://cloud.githubusercontent.com/assets/12552247/23522931/ae3b9c4e-ff39-11e6-8af7-f0a2076dbf59.png">

- "Create an empty project" should create a "Work Project."
- "Get in touch" should link here: http://crowdsourcing.topcoder.com/piqued_by_crowdsourcing

**Comment by vikasrohit** [comment]
Working on this.

**Comment by vikasrohit** [comment]
@fnisen for "Create an empty project" link do we need another screen to intake project name and description or we should force (by force I mean apply validation when user clicks on the link) user to fill the project name field in the current modal?

**Comment by fnisen** [comment]
@vikasrohit good point. We need a design for this. Let me get Vic's opinion here.

**Comment by vic-topcoder** [comment]
Good point, @vikasrohit. For the links to work, we should have the project name valid - similar to category selector cards. Let's manage the links the same way as the cards. No secondary intake form should appear. Empty project is the catch-all experience (work project).

**Comment by fnisen** [comment]
@vikasrohit Vic and I discussed this one. Let's get rid of the "Empty project" link entirely to avoid confusion. We'll add it as a project option under one of the main menus later. Can you please make the copy: "Looking for something else? Get in touch with us." (And link the "get in touch"). Thank you.

**Comment by vic-topcoder** [comment]
I'll add an issue for "get in touch with us" link not being blue by default as a style

**Comment by vic-topcoder** [comment]
Captured at #766

**Comment by fnisen** [comment]
Closing this. Needed changes captured in linked ticket.
