### ISSUE TITLE
Project name should be editable when project is first created

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#654]
Can you please make the project name editable at first? It should then become uneditable after the project moves to "In Review" (either by the user submitting or the status changing). The idea here is for the user to be able to adjust in case they make a typo... but for the name to not change once we're tracking it internally.

**Comment by vikasrohit** [comment]
Done. Changes should be in dev by EOD. @fnisen Please let me know if you face any issue with the changes.

**Comment by fnisen** [comment]
Tested a bunch of scenarios and everything is working well. Thank you.
