### ISSUE TITLE
Project Details: Style fixes

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#66]
The Project Details page is where the user(s) create the final specification of the project - type of work needed, design and development specifications.

![d0cabc28-0bb9-479f-8965-cd6022383028](https://cloud.githubusercontent.com/assets/8484061/18399781/99bfe238-7687-11e6-9083-af0cf5bffff1.png)

The Feature Selector is not part of this page; although it is displayed as a modal overlay, it is a separate issue/view.

Specification is here: https://drive.google.com/drive/folders/0B1LbmKnex41fT3JRTE5YMUdBWEE?usp=sharing

**Comment by mahestro** [comment]
This is ready and looks BEAUTIFUL.

https://connectv2.topcoder-dev.com/projects/261/specification/
