### ISSUE TITLE
Reference code should not be editable once project is submitted for review

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#671]
Once project has been submitted for review, both name and reference code should not be editable. Name is working correctly, but reference code is still editable right now.

**Comment by vikasrohit** [comment]
Done. Should be in dev by EOD.

**Comment by fnisen** [comment]
Not able to check this b/c the "Submit for Review" button is currently not working in Dev.

**Comment by fnisen** [comment]
Working in Dev. Closing.
