### ISSUE TITLE
Saving product type into project.details

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#672]
### Expected behavior
Product type (2nd step choice in the create project wizard) should be saved to details.products field. It should be an array field with only one element for now - the subtype for the current project.

Files that should be updated :
creating a project > https://github.com/appirio-tech/connect-app/blob/feature/productsv1/src/projects/create/components/ProjectWizard.jsx#L50
reading the product type > https://github.com/appirio-tech/connect-app/blob/feature/productsv1/src/projects/detail/containers/SpecificationContainer.jsx#L55 - should check if details.products[0] exists and load the specification template, otherwise fall back to topcoder.v1

### Actual behavior
Type is just saved to the project.type field.

### Steps to reproduce the problem
Create a new project
--

#### Environment
- OS:all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by fnisen** [comment]
@vikasrohit can you please weigh in on this one?

**Comment by vikasrohit** [comment]
Sorry @fnisen missed to update the github, however, we (me and Samir) had discussion about this. This is valid and critical issue which is required before go for bug hunt.

**Comment by fnisen** [comment]
@gondzo I'm not going to test this one b/c it's not a user issue. Can you please verify yourself or ask @vikasrohit is you need another opinion. Thank you.

**Comment by gondzo** [comment]
Looks good.
