### ISSUE TITLE
Selected card still has blue hover state

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#674]
### Expected behavior
Should retain normal state appearance on hover

### Actual behavior
Blue outline on hover
![screen shot 3](https://cloud.githubusercontent.com/assets/8484061/23634659/41ffdcb2-0280-11e7-9bb0-517bfeab9a6a.png)

**Comment by vic-topcoder** [comment]
Screen selector card still has blue hover state when selected. I guess this is due to the new fixes in the code to render text as text, not svg.

![screen shot 14](https://cloud.githubusercontent.com/assets/8484061/23684009/fa60289a-0350-11e7-9c6e-3cc40ecb945d.png)

Expected:
![screen shot 15](https://cloud.githubusercontent.com/assets/8484061/23684119/844b557a-0351-11e7-9a61-22c7add3749e.png)

**Comment by fnisen** [comment]
@vic-topcoder I don't see this working in Dev. Was this fixed, but not merged yet?

**Comment by fnisen** [comment]
@gondzo can you please check what happened with this one? We may have overwritten styles b/c of our deployment issues.

**Comment by fnisen** [comment]
Nevermind. Looks like the original issue was fixed, but there is a different bug, which we can track here: https://github.com/appirio-tech/connect-app/issues/773
