### ISSUE TITLE
Restructure + restyle "skip  question" component

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#675]
Due to improvements in the UX, we restructured the component.

![transition-v1-v2-skip-question-component](https://cloud.githubusercontent.com/assets/8484061/23634826/32f94388-0281-11e7-8b05-583a8a127cfd.png)

- [ ] Move checkbox at bottom of the component

- [ ] Move description underneath the text area/input

- [ ] Style according to the latest version

Live specification is here: https://drive.google.com/drive/folders/0B1LbmKnex41feVhsemtsYjN1SGs?usp=sharing

**Comment by sirakovaDimitrina** [comment]
@gondzo Restructure issue -- In order to make restructure we have to change layout on the react control, current li structure is title,  child component, description. The description have to be between the components in the design.

Style according issue -- I make new class .checkbox-item-checked which have to apply when according is checked. Please see the attache picture.
![screen shot 2017-03-07 at 11 47 26 pm](https://cloud.githubusercontent.com/assets/10530059/23679393/774dc044-0390-11e7-9f5c-609bd298cb21.png)

**Comment by vic-topcoder** [comment]
@gondzo - reassign to @sirakovaDimitrina after we have the structure so she can finish the styling, please.

**Comment by fnisen** [comment]
@gondzo @ThomasKranitsas this is not looking correct in Dev. See below in Dev and Vic's design at the top of the ticket.
![screen shot 2017-03-09 at 3 55 20 pm](https://cloud.githubusercontent.com/assets/12552247/23776082/e8f2cb26-04e0-11e7-9cfa-3d253730ce6d.png)

**Comment by ThomasKranitsas** [comment]
@fnisen I haven't worked on this yet...

**Comment by vic-topcoder** [comment]
Ping me when you have this one finished, so I can reassign for styling. Thanks!

**Comment by fnisen** [comment]
👍

**Comment by ThomasKranitsas** [comment]
@vic-topcoder I restructured the component.
Once @gondzo merge my code you can assign this to @sirakovaDimitrina so she can finish the styling.

**Comment by gondzo** [comment]
@sirakovaDimitrina The component is restructured per the above. 
![image](https://cloud.githubusercontent.com/assets/3051646/23874309/62bf305a-0835-11e7-8814-a91f5d85a5ac.png)
The checbox still doesn't get the  .checkbox-item-checked class when checked. I'll add that shortly

**Comment by gondzo** [comment]
@sirakovaDimitrina the .checkbox-item-checked is now added

**Comment by sirakovaDimitrina** [comment]
cc @fnisen  fixes #675

**Comment by fnisen** [comment]
Thanks @sirakovaDimitrina. Noticing one bug: the description is being repeated. Can you please fix?
![screen shot 2017-03-14 at 1 05 24 pm](https://cloud.githubusercontent.com/assets/12552247/23920234/174f4bd2-08b7-11e7-8dd0-5d35185e852f.png)

**Comment by fnisen** [comment]
@vic-topcoder, @sirakovaDimitrina seeing another issue https://github.com/appirio-tech/connect-app/issues/842. Not sure if it was already there or was introduced. If it's outside of your scope, please comment on the ticket.

**Comment by ThomasKranitsas** [comment]
Hey @fnisen I think the `double description` was introduced by my changes..

**Comment by vikasrohit** [comment]
Just to close the loop, I have reported this issue as #836 and already have [PR](https://github.com/appirio-tech/connect-app/pull/837) for that. The PR is merged and issue is closed.
