### ISSUE TITLE
Wire "quick quote" feature on Specification

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#677]
Options and pricing for intake and corresponding quick quote:
**Wireframe**:
1.10 screens, 7-10 days: $5,000
2. 15 screens, 10-12 days: $7,000
**Application Visual Design** (both Concepts and Production)
1. 1-3 screens, 5-7 days: $5,000
2. 4-8 screens, 7-10 days: $7,000
3. 9-15 screens, 8-10 days: $8,500

**Comment by vikasrohit** [comment]
@fnisen Right now we have only AVD as real product, others just fall back to default template. So should we create separate templates for wireframe and avd (concepts) product?

**Comment by vikasrohit** [comment]
Further, till now, we were estimating the price based on per page pricing and multiplying that with number of screens selected. However, from the description above, it seems it is not simple linear equation for estimating the pricing. It is kind of fixed price for the number of screens selection, right?

**Comment by fnisen** [comment]
@vikasrohit 
- Yes, so we should have 5 templates I think: Wireframes, AVD - Concepts, AVD - Product (all 3 of these will be the same structure), Default Design (as we have now), Default Development (as we have now)
- Yes, it will be fixed price based on the selected range. The user has 2 options for Wireframe and 3 options for AVD (both types) and each option corresponds to a price. We won't do a per-screen multiplier. I'm not sure why we can't enforce a limit if we have a range. The limit is just the top of the range (e.g., if you select "4-8," you can't create more than 8 screens).

**Comment by vikasrohit** [comment]
For limiting the screens in the app screens section, it would require us to put extra validation for minimum screens as well in this case, right? I mean if user selected 4-8 screens, we have to ask for minimum of 4 screens and maximum of 8 screens. Or is it fine to have only a maximum screens validation?

**Comment by fnisen** [comment]
Good point. Max validation is fine for now. Let me see how everything is working later today and follow up with another ticket if needed.

**Comment by vikasrohit** [comment]
PR https://github.com/appirio-tech/connect-app/pull/746 is created but waiting for bug hunt to conclude before getting it merged into dev. @gondzo  has created separate issue #700  for fixing the validation for App Screens section.

**Comment by fnisen** [comment]
Thanks @vikasrohit

**Comment by vikasrohit** [comment]
Sorry @fnisen Referenced wrong PR here. Changes were already in dev for this feature. Closing the ticket.

**Comment by fnisen** [comment]
@vikasrohit can we change the price dynamically as soon as the option is selected? Right now it looks like you only make the API call when the user hits "Save"
