### ISSUE TITLE
Landing page (not logged in) with broken layout

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#678]
### Expected behavior
The white portion of the page (body) should be evenly centered in the viewport.

### Actual behavior
Currently the container is left-aligned.

### Screenshot/screencast
![screen shot 4](https://cloud.githubusercontent.com/assets/8484061/23638336/f0d8ee44-0295-11e7-998a-43b123ec4988.png)

**Comment by vikasrohit** [comment]
Fixed, changes should be in dev by EOD.

**Comment by fnisen** [comment]
Working in Dev.
