### ISSUE TITLE
Specification-App Screen: priority drop down is not using system component

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#679]
Per Vic: Current drop-down doesn't respect edge of viewport or height available → this makes for sub-optimal user experience. Either we use the system rendered select or updated component that renders correct for the aforementioned constraints.

**Comment by vic-topcoder** [comment]
Current drop-down doesn't respect edge of viewport or height available → this makes for sub-optimal user experience. Either we use the system rendered `select` or updated component that renders correct for the aforementioned constraints.

**Comment by vic-topcoder** [comment]
@vikasrohit reassign as needed

**Comment by vikasrohit** [comment]
@vic-topcoder @fnisen This is our custom dropdown from our components repo. It even does not support the key navigation properly for the options yet as it is custom rendered. So, we have to enhance the component to support the rendering based on viewport and allow key navigation for the options. Though we can use community to do that, I think would take 2-3 days at least. So, IMO, we should go for default select option for now. I can try styling that default select to look something we want.

**Comment by vic-topcoder** [comment]
Why not use React Dropdown in this case? It is syllable and fits within the need of the system - it is a select after all. More - it can be styled to fit our needs. It does fit within the viewport and supports keyboard: http://jedwatson.github.io/react-select/. Or use simple select which the system will render. We can style either with the help of Didi. This task should take no more than 1 hour

**Comment by vikasrohit** [comment]
If we use react-select, then I guess it should not take much time. However, with browser standard select, it is not that straightforward to customize it across browsers.

**Comment by fnisen** [comment]
@vikasrohit so what's the final call? Will you fix this?

**Comment by vikasrohit** [comment]
IMO, we should tackle it later the products release. We can fix it in minor releases after this major release.

**Comment by fnisen** [comment]
@vikasrohit yes, agree about doing it after the products release (I had marked it as P2--we don't need to finish P2s before releasing). I'll keep it assigned to you. Thanks.
