### ISSUE TITLE
Pages with message: Style fixes

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#68]
Empty pages and error pages should provide ways for users to decide where to go next, or recover from an error.

![ce4c4e8f-c954-485c-9760-ca3d60eca5f9](https://cloud.githubusercontent.com/assets/8484061/18400446/ca59f2f0-768a-11e6-907d-71dc77aab594.png)

![f18d7946-8ca9-4132-8755-b92b357a5ebb](https://cloud.githubusercontent.com/assets/8484061/18400447/ca5abbfe-768a-11e6-9080-d9fc5fe8b2f9.png)

Spec is here: https://drive.google.com/drive/folders/0B1LbmKnex41fX3ZxRTdnZlhERTg?usp=sharing

**Comment by mahestro** [comment]
These pages are done.

- Error: https://connectv2.topcoder-dev.com/error
- Walkthrough: https://connectv2.topcoder-dev.com/projects/walkthrough

A small note though. The + button from walkthrough doesn't take the app anywhere. Maybe we should take it to Create Project.
