### ISSUE TITLE
Permalink for status post and discussions message

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#682]
It would be really nice to have a permalink available for each post (would be great to have it on every comment as well but right now we don't support rendering the specific comment by a direct link) which users can copy and share with team mates in case they want to refer to some previous discussions. It comes handy when discussing things on other communication channels like slack.

fyi @fnisen @parthshah

**Comment by fnisen** [comment]
Yeah, I like it. Not critical for now, but would be nice.

**Comment by vikasrohit** [comment]
@vic-topcoder Can you please suggest a basic design for this? Or Can I add a simple icon just next to the post title (on Discussions page) and add the permalink there? For the later, I would need your help for a permalink icon in svg format.

@fnisen I don't remember exactly what was the problem, but we don't have support to go to the specific post on the Dashboard page. We have this functionality working for the Discussions page only. So, I guess permalink feature would also work on Discussions page right now. I can take a look on the issue with Dashboard page.

**Comment by parthshah** [comment]
Why do we need a design change? As user's click on the discussions tab and select a different topic we should change the URL with topicId url param & potentially also commentId to reflect the selected topic + post combo?. The same can apply to Dashboard page as well.

**Comment by vikasrohit** [comment]
Thanks @parthshah for the idea for having topic id in the URL itself as URL param. However, that would work for Discussions page only because we don't have a way to select a particular feed on dashboard. Hence user won't have any way to change the URL to copy the specific feed URL.
However, I think on dashboard we can use the timestamp field to have the permalink just like github is doing for its comments on issues.

**Comment by vikasrohit** [comment]
bump up

**Comment by parthshah** [comment]
I prefer not to use `projects/{id}/status/{feedId}` , it's better to use anchor tag. Does this help - http://stackoverflow.com/questions/40280369/use-anchors-with-react-router?

**Comment by vikasrohit** [comment]
Okay. I will check the anchor implementation again. The only problem last time faced was the delay or inability in scrolling to the specific feed when user directly changes the feed id in the hash. May be that is browser's behaviour. One of those cases was when I change the feed id in the hash after `CMD + L` command, I guess it works well when user clicks in URL box and then changes the feed id. I would deploy the changes to dev and let you guys check the behaviour.

**Comment by vikasrohit** [comment]
@fnisen @parthshah This feature is deployed to dev for testing. Please let me know your feedback. If it seems good, I can merge changes into dev. Please note, right now I haven't worked on creating permalinks for comments of feeds/messages. I think it would require more efforts because we have to auto expand the collapsed comments in case someone has referred a comment which is not loaded on the page load.

**Comment by vikasrohit** [comment]
@fnisen @parthshah did you guys get chance to verify the changes? Should I move the changes into dev?

**Comment by vikasrohit** [comment]
bump 😬

**Comment by fnisen** [comment]
@vikasrohit sorry this got lost. The current implementation seems good to me. @parthshah is it OK to deploy?

**Comment by parthshah** [comment]
Yep .. should be good to deploy. Vikas .. please merge and deploy to master when you get a chance.

**Comment by vikasrohit** [comment]
Merged and deployed to dev. We can promote these changes to prod with next release or should I make a new specific release for this?

**Comment by fnisen** [comment]
Next release is fine. Just include it in the notes please.

**Comment by vikasrohit** [comment]
@fnisen  Just realized that we would be releasing the new logged out flow in next release and I think we don't have any other feature planned before that. In that case it can make sense to deploy this feature as minor release update. It would make the next release more focused to the logged out flow of the project creation.
