### ISSUE TITLE
Team Management: Style fixes

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#69]
Team management is part of the core experience for Connect v2. Team management is accessible on the Dashboard left pane.

![d81f44f7-2147-4cae-83f9-625bc48b9683](https://cloud.githubusercontent.com/assets/8484061/18400916/c05019ae-768c-11e6-8f5e-53b452ff7b35.png)

Spec is here: https://drive.google.com/drive/folders/0B1LbmKnex41fcDROZnFWTWxDVk0?usp=sharing

**Comment by mahestro** [comment]
@vic-appirio amigo, the design we coded a few weeks ago had the plus button for adding in the top right of the panel (http://take.ms/ZsZHV). This version here doesn't have it. Should it be changed?
