### ISSUE TITLE
device/screen select card should include a checkbox as per design. Missing.

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#695]
Current:
![screen shot 16](https://cloud.githubusercontent.com/assets/8484061/23684155/bac7e2a8-0351-11e7-9cd4-c879df88bb97.png)

Expected:
![screen shot 17](https://cloud.githubusercontent.com/assets/8484061/23684162/c9a54cde-0351-11e7-8ba6-c35c6195e84c.png)

**Comment by fnisen** [comment]
Already covered here: https://github.com/appirio-tech/connect-app/issues/641
