### ISSUE TITLE
[$30] Project Name should be focused immediately after rendering the project creation form

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#696]
fyi @gondzo @fnisen

**Comment by fnisen** [comment]
@vikasrohit can you please add a screenshot for this one?

**Comment by vikasrohit** [comment]
@fnisen screen shot may not help here because it is bug in the flow. So, may be a video would help here. However, it does not need both either, one can simply click on New Project link and start typing to notice the issue. IMO, if one starts typing immediately after clicking the New Project button, it should reflect in project name field.
