### ISSUE TITLE
[$40] Screens limit

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#700]
### Expected behavior
When number of screens is selected in format a-b (like 4-8), higher number is used as limit in the app screens section

### Actual behavior
First number (a) is used as screens number limit

### Steps to reproduce the problem
create AVD project and go to specification page

#### Environment
- OS:all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by vikasrohit** [comment]
Just to be double sure, we have to support both type of values i.e. individual values or range values and put the limit on the number of screens that can be added.

**Comment by fnisen** [comment]
@gondzo please use more descriptive titles for issues

**Comment by gondzo** [comment]
Related issue #767

**Comment by fnisen** [comment]
Working in Dev.
