### ISSUE TITLE
Can create a Project without a Project Name

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#702]
Description
-----------------------------------------------------------------
Can create a Project without a Project Name

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click '+ New Project'
- Enter spaces for the 'Project Name'
- Check the 'Development' buttons
- Select 'Prototype'
- Click Create Project

Expected Result(s)
-----------------------------------------------------------------
- Must validate the project name before posting

Actual Result
-----------------------------------------------------------------
- Can create a Project without a Project Name

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2](https://cloud.githubusercontent.com/assets/4592712/23720946/4191e7c4-0466-11e7-8db1-5c2f82b133d2.png)

**Comment by gondzo** [comment]
same as #701
