### ISSUE TITLE
[$50] 'Required' fields are not  marked in (*) in the side menu

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#703]
Description
-----------------------------------------------------------------
'Required' fields are not  marked in (*) in the side menu

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design] - Newly Created
- Click 'Specification' tab
- Scroll down and check the 'Design Specification' and 'Development Specification' items

Expected Result(s)
-----------------------------------------------------------------
- 'Required' fields in the 'Design Specification' and 'Development Specification' sections must marked in (*) in the side menu

Actual Result
-----------------------------------------------------------------
- All the 'Design Specification' and 'Development Specification' items are marked with (*) in the content area but they are not marked in (*) in the menu area

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![3](https://cloud.githubusercontent.com/assets/4592712/23721136/e15193a4-0466-11e7-8fb4-382f2af9f630.png)

**Comment by fnisen** [comment]
This one is messy implementation. To clarify: the Design Spec and Development Spec sections are not required. There should not be any asterisks for any parts of those sections. So, the fix is that the asterisks should be removed in the body of the spec.

**Comment by iit2009060** [comment]
@gondzo  I am not able to assign issue.

**Comment by iit2009060** [comment]
@gondzo what is the environment section.How can I login it.

**Comment by gondzo** [comment]
@iit2009060 see the challenge forums for test credentials

**Comment by iit2009060** [comment]
https://github.com/appirio-tech/connect-app/pull/797

**Comment by iit2009060** [comment]
@gondzo I will be paid for this issue.

**Comment by gondzo** [comment]
yes
