### ISSUE TITLE
Upload file: same file should not be upload twice

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#704]
Upload file: same file should not be upload twice

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. create project
4. Open Specification 
5. go to project files
6. upload same file twice

**Expected Result:**

same file should not be upload twice

**Actual Result:**
able to upload same file twice

Environment:
Windows 7, 
Chrome 53

![image](https://cloud.githubusercontent.com/assets/16131461/23721204/07c00a3e-0467-11e7-9db3-b32cd5acba49.png)

**Comment by gondzo** [comment]
Not really a bug, it's ok to upload multiple files with same file name
