### ISSUE TITLE
Project Estimate is not displayed in the Specification tab

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#705]
Description
-----------------------------------------------------------------
Project Estimate is not displayed in the Specification tab

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click '+ New Project'
- Create a Development Project
- Go to Specification
- Check the Project Estimate 
- Eg: https://connect.topcoder-dev.com/projects/964/specification

Expected Result(s)
-----------------------------------------------------------------
- Project Estimate section must display in the Specification tab

Actual Result
-----------------------------------------------------------------
- Project Estimate is not displayed in the Specification tab

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![a](https://cloud.githubusercontent.com/assets/4592712/23732905/e008ea9e-049b-11e7-8242-82d5d6b0ad14.png)
![a1](https://cloud.githubusercontent.com/assets/4592712/23732906/e008f386-049b-11e7-8b14-25afe3737012.png)

**Comment by gondzo** [comment]
@fnisen we should display project estimate for design projects only ?

**Comment by fnisen** [comment]
@gondzo yes, that's correct. We can allow this if the requirements weren't clear, but only 3 design project types will get quotes: Wireframes + both AVDs.
