### ISSUE TITLE
Discussion: showing the incorrect time "0 sec "on discussion 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#706]
Discussion: showing the incorrect time "0 sec "on discussion 
If user start to post or reply on post showing the correct timing

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. Create New project
4. Add Specifaction
5. go to discussion
6. Add a post
7. Reply a comment on post

**Expected Result:**

should display the correct timing

**Actual Result:**

showing the wrong timing, 
Environment:
Windows 7, 
Chrome 53

![image](https://cloud.githubusercontent.com/assets/16131461/23721550/35e1e3c8-0468-11e7-9c39-3cb92e7f1532.png)

**Comment by gondzo** [comment]
Not really a bug and it's out of scope for this bug hunt.
