### ISSUE TITLE
New Selection 'Check-mark' is not displayed when user select items in 'What font style do you prefer? (Pick one)' section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#707]
Description
-----------------------------------------------------------------
New Selection 'Check-mark' is not displayed when user select items in 'What font style do you prefer? (Pick one)' section

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click on a Project (https://connect.topcoder-dev.com/projects/956/specification)
- Click 'Specification' tab
- Scroll down and come to the Questions > What font style do you prefer? (Pick one)
- Check one of the Serif OR Sans Serif options

Expected Result(s)
-----------------------------------------------------------------
- Must display a blue checkmark when user selects Serif or Sans Serif options
- Check the TC Project: https://www.topcoder.com/challenge-details/30056425/?type=develop&noncache=true
- Screen: https://marvelapp.com/3e8bab3/screen/24348735

Actual Result
-----------------------------------------------------------------
- New Selection 'Checkmark' is not displayed when user select items in 'What font style do you prefer? (Pick one)' section

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![4](https://cloud.githubusercontent.com/assets/4592712/23721922/63da3cfc-0469-11e7-87dc-8d653966f7fb.png)

**Comment by gondzo** [comment]
Already fixed, but wasn't in the known issues list. Counts for the bug hunt.
