### ISSUE TITLE
Project Feature Selector Bug

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#71]
1. The current implementation of the features selector shows a 'X' icon to close it that collides with the user dropdown.
2. There is a very long scroll bar that has a strange behavior. It goes down (to the end of the parent window that calls the feature selector) but it actually does not perform a change in the current view. Just give it a try and you'll see.

![pm-33-17](https://cloud.githubusercontent.com/assets/729632/18420030/703ff00e-7869-11e6-9cbb-0def00b385c3.png)

**Comment by fnisen** [comment]
@mahestro this feature isn't done yet. @vikasrohit is still working on it.

**Comment by fnisen** [comment]
Going to close for now; can reopen when Vikas is done.

**Comment by vikasrohit** [comment]
Thanks @mahestro for catching the issues. I can fix the overlapping thing. However, I am not sure if I would be able to fix the scrollbar thing. I guess, scrollbar is there because the page behind the modal is too long and the scroll bar is for that. If it can be avoided, that would be great.

**Comment by fnisen** [comment]
@vikasrohit, @mahestro similar to how the project creation page was designed, the feature selector should take over the page. The page behind the modal should not be visible.

**Comment by vikasrohit** [comment]
In that case, we have to rather move the Feature Picker to its own page instead of being a modal.
