### ISSUE TITLE
message should be correct if leave discussion page without posting added topic

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#712]
message should be correct if leave discussion page without posting added topic, 

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. create a new project
4. Add all specification
5. go to discussion 
6. Add topic & Comment 
7. leave page without posting topic

**Expected Result:**
should be displayed a correct message

**Actual Result:**
showing the wrong message

Environment:
Windows 7, 
Chrome 53

![image](https://cloud.githubusercontent.com/assets/16131461/23721902/54a1dde4-0469-11e7-950e-5f9b84abb09e.png)

**Comment by fnisen** [comment]
We're not able to adjust this because it's a browser message.
