### ISSUE TITLE
Project team member name not displayed

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#715]
**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. create project
4. go to dashboard
5. go to project team
6. Add a team member
7. make owner of the project

**Expected Result:**
name should be displayed correctly

**Actual Result:**
Project team member name not displayed,

Environment:
Windows 7, 
Chrome 53

![image](https://cloud.githubusercontent.com/assets/16131461/23722049/e6613f40-0469-11e7-9f8d-eed65c6e71fa.png)

**Comment by fnisen** [comment]
This is happening because the name is masked in the Dev environment.
