### ISSUE TITLE
Can create duplicate Custom Features with the same name

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#717]
Description
-----------------------------------------------------------------
Can create duplicate Custom Features with the same name

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click on a Project (https://connect.topcoder-dev.com/projects/956)
- Click 'Specifications' Tab
- Scroll down and click on 'Add/Edit Features' button in the 'Feature requirements' section
- Scroll down and click on 'Add a custom feature'
- Enter a name (eg: TT) and click 'Save Feature'
- Click 'Add a custom feature'
- Enter a name (eg: TT) and click 'Save Feature'

Expected Result(s)
-----------------------------------------------------------------
- Must validate the duplicate 'Custom Features' name

Actual Result
-----------------------------------------------------------------
- Can create duplicate Custom Features with the same name 
- Both items selected by default

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by fnisen** [comment]
Same as https://github.com/appirio-tech/connect-app/issues/721
