### ISSUE TITLE
topcoder footer shown on filter page 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#719]
### Expected behavior
should show at bottom 

### Actual behavior
footer  text shown on filter result page 

### Steps to reproduce the problem
- Login As manager
- click filter button
- see result page 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-09 01-52-46](https://cloud.githubusercontent.com/assets/3225433/23722395/3164792a-046b-11e7-916b-dbf0f68b9e37.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
@vikasrohit can you please check this out? It's happening on all browsers.

**Comment by vikasrohit** [comment]
@fnisen I am not facing this issue on mac for any browser. It might be issue with Windows platform for all browsers. @gondzo We can put this one in a UI bucket for our coming bug bash.

**Comment by vikasrohit** [comment]
Able to reproduce it but with different steps. It is reproducible when user opens the Discussions tab of any project and then moves to the Project listing page.
Applied a fix for this which should be in dev by EOD.
