### ISSUE TITLE
General: Double footer issue

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#72]
Hey amigo @vic-appirio. With the side panel footer update, I realize we have two footers on this scenario. It's ok in any other page except in the ones that use this side panel.

What are your thoughts? Do you want to remove the one from the side panel? That seems to be a good option since there is already a footer at the very bottom. Let me know.

![pm-57-21](https://cloud.githubusercontent.com/assets/729632/18420099/2399a482-786b-11e6-816c-f54c5e342c29.jpg)

**Comment by fnisen** [comment]
By the way, per my doc, the footer links should be (in order): About, Contact, Help, Privacy, Terms

**Comment by vic-appirio** [comment]
Let's get rid of the big footer when we're on a 2 column page, please!

**Comment by vic-appirio** [comment]
Updated footer and project links speck: https://drive.google.com/drive/folders/0B1LbmKnex41fZnJ4Rkozcl94VUk?usp=sharing

**Comment by mahestro** [comment]
Understood!

**Comment by fnisen** [comment]
<img width="383" alt="screen shot 2016-09-19 at 5 38 55 pm" src="https://cloud.githubusercontent.com/assets/12552247/18653627/fa7b377a-7e8f-11e6-97d0-46e82b29822d.png">

@mahestro the footer links somehow morphed into the above. It should be About, Contact, Help, Privacy, Terms, with copyright below, if you need more space, as Vic has it in the design.

**Comment by mahestro** [comment]
I see it was never changed actually to what was designed. Good catch. I'll fix it.
