### ISSUE TITLE
Can remove the 'Feature name' when user is editing the record

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#720]
Description
-----------------------------------------------------------------
Can remove the 'Feature name' when user is editing the record

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click on a Project  (https://connect.topcoder-dev.com/projects/956)
- Click 'Specifications' Tab
- Scroll down and click on 'Add/Edit Features' button in the 'Feature requirements' section
- Scroll down and click on 'Add a custom feature'
- Enter a name (eg: TT) and click 'Save Feature'
- Click EDIT button
- Delete the name
- Click Save Changes

Expected Result(s)
-----------------------------------------------------------------
- Must validate the 'Feature name' when user is editing the record

Actual Result
-----------------------------------------------------------------
- Can remove the 'Feature name' when user is editing the record
- After that two empty items created

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![11](https://cloud.githubusercontent.com/assets/4592712/23722472/79e1529a-046b-11e7-95cf-40d5e83917e6.png)

**Comment by fnisen** [comment]
We should turn off the Save button when the name field is blank or has spaces.
