### ISSUE TITLE
Duplicate custom feature created when user edit the record and save changes without changing anything

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#721]
Description
-----------------------------------------------------------------
Duplicate custom feature created when user edit the record and save changes without changing anything

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click on a Project (https://connect.topcoder-dev.com/projects/956)
- Click 'Specifications' Tab
- Scroll down and click on 'Add/Edit Features' button in the 'Feature requirements' section
- Scroll down and click on 'Add a custom feature'
- Enter a name (eg: TT) and click 'Save Feature'
- Click on 'Add a custom feature'
- Click EDIT
- Don't change anything
- Click Save Changes

Expected Result(s)
-----------------------------------------------------------------
- Must not create duplicate items

Actual Result
-----------------------------------------------------------------
- Duplicate custom feature created when user edit the record and save changes without changing anything

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![13](https://cloud.githubusercontent.com/assets/4592712/23722592/f1694804-046b-11e7-8db5-8ea66b88f983.png)

**Comment by fnisen** [comment]
We don't mind if the user wants to create two identically-named features for some reason.
