### ISSUE TITLE
goto page validation missing 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#724]
### Expected behavior
should validate the filed 

### Actual behavior
goto page validation missing 

### Steps to reproduce the problem
- Login As manager
- click filter button
- see Pagination 
- click ... button
- see goto page option

- enter value as "dfgdfg"

- see

### Screenshot/screencast
![screenshot-connect topcoder-dev com 2017-03-09 02-01-23](https://cloud.githubusercontent.com/assets/3225433/23722712/6e94ff4e-046c-11e7-9135-4269a8b4897e.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
@gondzo I can't reproduce in Chrome, so this must be only an issue with Firefox or non-Chrome browsers.
