### ISSUE TITLE
error on adding file from google drive

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#725]
error on adding file from google drive

Steps to Reproduce:

1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. create new project
4. go to specification
5. go to files section
6. upload file from google drive

Expected Result:
should be able to add file from googledrive

Actual Result:
error on adding file from google drive

Environment:
Windows 7,
Chrome

![image](https://cloud.githubusercontent.com/assets/16131461/23722699/6566783a-046c-11e7-97e6-1e307f42a748.png)

**Comment by fnisen** [comment]
@gondzo can you please try reproducing this bug?
