### ISSUE TITLE
[$20] '+ New Project' button displayed in gray color after closing the popup

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#726]
Description
-----------------------------------------------------------------
'+ New Project' button displayed in gray color after closing the popup

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click '+ New Project'
- Click ESC
- Check the '+ New Project' button

Expected Result(s)
-----------------------------------------------------------------
- '+ New Project' button must display in white color after closing the popup

Actual Result
-----------------------------------------------------------------
- '+ New Project' button displayed in gray color after closing the popup

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![14](https://cloud.githubusercontent.com/assets/4592712/23722851/f345767e-046c-11e7-8b2a-7bb7f592c09a.png)

**Comment by rrandom** [comment]
@gondzo, please assign this to me
