### ISSUE TITLE
[$30] error if update project without project name on specification page

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#727]
error if update project without project name on specification page.

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: Manager: pat_monahan / topcoder123!
3. create project
4. go to specification 
5. add all app definition field
6. Delete project name
7. save changes

**Expected Result:**
should be displayed a validation message to add project name

**Actual Result:**
error on update project without project name

Environment:
Windows 7, 
Chrome 

![image](https://cloud.githubusercontent.com/assets/16131461/23722837/e5e86018-046c-11e7-836d-7533ecb16ba1.png)

**Comment by fnisen** [comment]
Change the validation message to: "Please add a name for your project and then try saving again."

**Comment by k-tempest** [comment]
I'm working on it. Cannot remove Open for Pickup label because I'm not added to the project yet.

**Comment by iit2009060** [comment]
@gondzo  can I pick this issue, it is still labeled as Open for Pick up.

**Comment by gondzo** [comment]
@iit2009060 no, there is already a pull request by @k-tempest
@k-tempest please assign tihs one to yourself after ou join the project
