### ISSUE TITLE
'Search' is not working properly

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#729]
Description
-----------------------------------------------------------------
'Search' is not working properly

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Enter 'abc' as the search term
- Click Search
- Now check the results

Expected Result(s)
-----------------------------------------------------------------
- Must display only the projects that matches the search term
- But in this case it will display matching Ref codes also

Actual Result
-----------------------------------------------------------------
- When user search using a search term it will display non-relevant projects to the search term

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![16](https://cloud.githubusercontent.com/assets/4592712/23723194/4851a6aa-046e-11e7-911f-10d6630c2c56.png)

**Comment by fnisen** [comment]
That's as designed. Our thinking was that it was useful for the user to see both types of matches.
