### ISSUE TITLE
Dashboard/Project info: Cancel "X" for Links component

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#73]
I accidentally hit create a link and I wanted to cancel it but I couldn't. I think it would be useful to add a cancel button here. Wdyt?

![cancel](https://cloud.githubusercontent.com/assets/729632/18420491/0f824ed2-7874-11e6-9319-4d4d34f05a9f.png)

**Comment by fnisen** [comment]
Good point. @vic-appirio your call.

**Comment by vic-appirio** [comment]
We should have a cancel button next to the add link. Per design the Add Link modal covers the top of the component header, and the plus button transforms into a "x" mark. Implementation is not as per design.

**Comment by vic-appirio** [comment]
/Users/victorgeorge/Desktop/Screen Shot 2016-09-13 at 12.14.40 PM.png

**Comment by fnisen** [comment]
@vic-appirio oh snap! 

@mahestro can you please implement the "x" to cancel?

**Comment by mahestro** [comment]
You're right @vic-appirio. I didn't catch it at first. In progress.
