### ISSUE TITLE
Different behaviors when user tries to upload 0 bytes files

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#730]
Description
-----------------------------------------------------------------
Different behaviors when user tries to upload 0 bytes files

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design]  (https://connect.topcoder-dev.com/projects/960)
- Click 'Specification' tab
- Scroll down and come to the 'Project Files'
- Click 'Add File'
- Drag and drop a 0 bytes file --> IE11 (Error)
- Drag and drop a 0 bytes file --> Chrome (File uploaded)

Expected Result(s)
-----------------------------------------------------------------
- If the 0 bytes file are not supported must display the same error in Google Chrome

Actual Result
-----------------------------------------------------------------
- IE displays an error message "Your browser doesn't support uploading folders - please use the latest version of Google Chrome or select individual files to upload" when user tries to upload 0 bytes files

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
Google Chrome
![17 1- chrome](https://cloud.githubusercontent.com/assets/4592712/23723421/1e503ac8-046f-11e7-9373-30ee0fbcdf56.png)

IE11
![17 2 -ie11](https://cloud.githubusercontent.com/assets/4592712/23723422/1e843440-046f-11e7-8ef8-f25cfe71cff4.png)

**Comment by fnisen** [comment]
I think this is an issue with Filestack, which will likely be addressed when we upgrade to the new version. cc @parthshah
