### ISSUE TITLE
[$40] Can enter empty spaces for 'Notes' in 'App Definition', 'Design Specification' or 'Development Specification'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#731]
Description
-----------------------------------------------------------------
Can enter empty spaces for 'Notes' in 'App Definition', 'Design Specification' or 'Development Specification'

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design]  (https://connect.topcoder-dev.com/projects/960/specification)
- Click 'Specification' tab
- Add spaces for the 'Notes' in 'App Definition', 'Design Specification' or 'Development Specification'
- Click Save Changes

Expected Result(s)
-----------------------------------------------------------------
- Must validate the empty space for Notes

Actual Result
-----------------------------------------------------------------
- Can enter empty spaces for 'Notes' in 'App Definition', 'Design Specification' and 'Development Specification'

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![18](https://cloud.githubusercontent.com/assets/4592712/23723507/7eacf1e0-046f-11e7-8ab5-007034ed0c7c.png)

**Comment by gondzo** [comment]
@fnisen do we need validation for notes (notes aren't required any more)

**Comment by fnisen** [comment]
@gondzo no, no validation needed b/c they're not required. Thanks for checking.
