### ISSUE TITLE
[$30] Clearing the 'Project' name from the (x) button will still enable the below items and after click on a item will display the project name again

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#732]
Description
-----------------------------------------------------------------
Clearing the 'Project' name from the (x) button will still enable the below items

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click '+ New Project'
- Enter 'Project Name'
- Select 'Development'
- Click on 'Project Name'
- Click (x) Clear

Expected Result(s)
-----------------------------------------------------------------
- When user clear the 'Project Name' from (x) clear icon must disable the below items

Actual Result
-----------------------------------------------------------------
- Clearing the 'Project' name from the (x) button will still enable the below items and after click on a item will display the project name again

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![19](https://cloud.githubusercontent.com/assets/4592712/23723732/526602ec-0470-11e7-9604-fb6e15fa9bde.png)

**Comment by gondzo** [comment]
IE bug

**Comment by fnisen** [comment]
@sdgun knows he can catch us on IE from past experience. 👍

**Comment by rrandom** [comment]
Please assign this to me. Thanks

**Comment by rrandom** [comment]
@gondzo , The (x) clear button for <input /> is a IE feature and Chrome does not have it. Should I only disable it on IE or implement the clear button for <input /> to all browsers?

**Comment by gondzo** [comment]
@rrandom disable in IE as we already have the clear input button
