### ISSUE TITLE
if we made change only development specification, only development section "Save button" should be enable

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#734]
if we made change only development specification, only development section "Save button" should be enable.

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: cp-superstar / topcoder123!
3. create new project
4. go to specification 
5. add all specification correctly
6. made change on development specification

**Expected Result:**

only particular section save button should be enable 

**Actual Result:**
all section " App Definition, Design specification, Development specification save button enabled, 

Environment:
Windows 7, 
Chrome 

![image](https://cloud.githubusercontent.com/assets/16131461/23724374/7a792276-0472-11e7-870e-a7ef077f4c87.png)

**Comment by fnisen** [comment]
This is as designed. Save button is meant to work across sections. I can see the expectation for this bug, so I'll allow it. However, we designed for the other case: the user may think that Save works across sections, and we don't want them to unexpectedly lose unsaved changes.
