### ISSUE TITLE
error on marking the status as cancel from the completed

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#735]
error on marking the status as cancel from the completed

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: cp-superstar / topcoder123!
3. create project
4. add all specification correctly
5. submit for review
6. login with manager pat_monahan / topcoder123!
7. mark the status active
8. change status active to completed
9. mark status completed to cancel

**Expected Result:**
should be able to mark cancel status

**Actual Result:**
throwing error on marking status as cancel  from completed

Environment:
Windows 7, 
Chrome latest

![image](https://cloud.githubusercontent.com/assets/16131461/23724623/6d6adf88-0473-11e7-897a-7ed19521e21d.png)

**Comment by fnisen** [comment]
This is a known bug that's being worked on (outside the scope of this bug hunt).
