### ISSUE TITLE
[$30] Newly created items displayed 1 of 5, but none of the steps completed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#736]
Description
-----------------------------------------------------------------
Newly created items displayed 1 of 5, but none of the steps completed

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design] (https://connect.topcoder-dev.com/projects/967)
- Click on 'Specification' tab
- Check the Questions (1 of 5)

Expected Result(s)
-----------------------------------------------------------------
- Must display 0 of 5, because after creating the project none of the Questions completed

Actual Result
-----------------------------------------------------------------
- Newly created items displayed 1 of 5, but none of the steps completed

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![20](https://cloud.githubusercontent.com/assets/4592712/23725107/46dd9df4-0475-11e7-9299-fa76841cf3b7.png)

**Comment by gondzo** [comment]
Fixed already but wasn't in the known issues list

**Comment by fnisen** [comment]
@gondzo has the fix been deployed already? I can't get that project to show 0 out of 5.

**Comment by gondzo** [comment]
I can't either. My mistake, it's not fixed

**Comment by gondzo** [comment]
The fix is working, but I'd rather not merge it as it will be handled by fixing #650 
@fnisen agree ?

**Comment by fnisen** [comment]
@gondzo yes, sounds good. We can merge if 650 does not address it for some reason.
