### ISSUE TITLE
[$30] 'Screen name' and 'What are the things the user can do on this screen?' sections are accepting spaces

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#737]
Description
-----------------------------------------------------------------
'Screen name' and 'What are the things the user can do on this screen?' sections are accepting spaces

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design] (https://connect.topcoder-dev.com/projects/960)
- Click on 'Specification' tab
- Select 9-15 for 'How many screens do you need designed?'
- Scroll down and click on 'Define another screen'
- Enter spaces for 'Screen name' and 'What are the things the user can do on this screen?'
- click Save Changes

Expected Result(s)
-----------------------------------------------------------------
- Must validate the spaces for the 'Screen name' and 'What are the things the user can do on this screen?' sections

Actual Result
-----------------------------------------------------------------
- 'Screen name' and 'What are the things the user can do on this screen?' sections are accepting spaces

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![21](https://cloud.githubusercontent.com/assets/4592712/23725676/7bda9302-0477-11e7-97c6-20ffc84f5bbe.png)

**Comment by gondzo** [comment]
Related issue #767
