### ISSUE TITLE
if click on "Read more" link of project description lands user to specification page

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#738]
if click on "Read more" link of project description lands user to specification page

**Steps to Reproduce:**
1. Open the Application
2. Login with valid credentials: cp-superstar / topcoder123!
3. create new project
4. go to specification page
5. add a long project description
6. go to dashboard page
7. click on read more link

**Expected Result:**
all description should be displayed on the dashboard or should lands user to description tab on specification page

**Actual Result:**
should lands user to specification page

Environment:
Windows 7, 
Chrome 

![image](https://cloud.githubusercontent.com/assets/16131461/23725885/49155852-0478-11e7-9599-6698ec549a66.png)

**Comment by fnisen** [comment]
This is working as designed.
