### ISSUE TITLE
Dashboard/Team management: component not fully displayed at the bottom of the page

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#74]
When you try to search members to add them to the team management, you can't see the whole list of users from the autocomplete box. I think there might be a conflict with the sticky behavior.

Plus, as suggestion, I think a loading indicator would be nice to have, in the search component. My first impression when I type and it took more than 5sec to show me some results was that it wasn't working.

![mem](https://cloud.githubusercontent.com/assets/729632/18420528/ed9bd314-7874-11e6-9179-540cf480c94a.jpg)

**Comment by fnisen** [comment]
@mahestro good point. I saw this too, but not can't find where I filed it. Anyway, @vic-appirio assigning to you for triage. Seems like a styling issue.

**Comment by vic-appirio** [comment]
This is more than styling - it requires the drop-down component to actually be aware of viewport border proximity so it can switch direction. This is functional issue, reassigning to @vikasrohit, or we can run a code fix F2F. @mahestro: do you think Sky_ can fix this - it is a feature enhancement, for popup to detect viewport and orient itself accordingly.  This behavior applies for all popups/dropdown/tooltips.

**Comment by fnisen** [comment]
@mahestro assigning to you. Please let us know if you need Vikas to help.

**Comment by vikasrohit** [comment]
Yes, this one is a good candidate for the community.

**Comment by mahestro** [comment]
In progress.
