### ISSUE TITLE
[$30] Layout issue in 'Duration' and 'Quick Quote' in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#740]
Description
-----------------------------------------------------------------
Layout issue in 'Duration' and 'Quick Quote' in IE11

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design] (https://connect.topcoder-dev.com/projects/961)
- Click on 'Specification' tab
- Select 4-8 for 'How many screens do you need designed?'
- Click Save Changes
- Check the 'Duration' and 'Quick Quote' numbers

Expected Result(s)
-----------------------------------------------------------------
- Must display the values in-front of the text
- As displayed in the Google Chrome

Actual Result
-----------------------------------------------------------------
- 'Duration' and 'Quick Quote' numbers are not displayed inline with the text in IE11

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![23](https://cloud.githubusercontent.com/assets/4592712/23727321/973a132e-047d-11e7-8e26-5cd684922d7c.png)

**Comment by fnisen** [comment]
Related to this, the fonts in the screen selector are also not according to style: https://www.screencast.com/t/V1Is9bCG

**Comment by Colinh84** [comment]
@fnisen the layout issue is fixed in my MR, however the font issue you noted is a server-side problem. If you load https://connect.topcoder-dev.com in ANY browser, the font files are not able to load from the server and all the font request response headers are returned with:
```
Server:AmazonS3
Via:1.1 74cedfead34bc01fa7b9b82fd94d496b.cloudfront.net (CloudFront)
X-Amz-Cf-Id:YRKmEuqgNvXiPhrmYTmYnZj_PsRzsGO4JOHbmQnCHUmfzp1tEpM0Uw==
X-Cache:Error from cloudfront
```

I tested with my local deployment in IE11 and all fonts are loaded and rendered correctly.

**Comment by fnisen** [comment]
Thanks a lot @Colinh84. @gondzo you can test and merge this one w/o the font fix. 

@parthshah can you please have a look at our CloudFront setup, based on the note above?

**Comment by fnisen** [comment]
Per @parthshah, the font problems are a known issue, already tracked here: https://github.com/appirio-tech/connect-app/issues/501
