### ISSUE TITLE
New Screens: "How many screens do you need designed?" and "Which is your primary device target?" are not displayed in old Projects

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#741]
Description
-----------------------------------------------------------------
New Screens: "How many screens do you need designed?" and "Which is your primary device target?" are not displayed in old Projects

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Old Project [Design] (https://connect.topcoder-dev.com/projects/875/specification)
- Click on 'Specification' tab
- Check the "How many screens do you need designed?" and "Which is your primary device target?" sections
- Open a New Project [Design] (https://connect.topcoder-dev.com/projects/963/specification)
- Check the above sections

Expected Result(s)
-----------------------------------------------------------------
- Must display the "How many screens do you need designed?" and "Which is your primary device target?" sections in old Projects

Actual Result
-----------------------------------------------------------------
- New Screens: "How many screens do you need designed?" and "Which is your primary device target?" are not displayed in old Projects

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
New Project:
![24 2](https://cloud.githubusercontent.com/assets/4592712/23732061/e9bccc4a-0496-11e7-9bd2-e2b75a0af8f7.png)
Old Project:
![24 1](https://cloud.githubusercontent.com/assets/4592712/23732060/e9bc594a-0496-11e7-803f-241cc0c72b49.png)

**Comment by gondzo** [comment]
This is by design. Old projects will use the same intake form template.
@fnisen For the old projects there is no way to change target device selection (it was on the create project page before, not the project specification page). Is this intended ?

**Comment by fnisen** [comment]
@gondzo yes, correct, this is as designed. Old projects should function as they did previously.
