### ISSUE TITLE
'Development Specification' section displayed in old design projects

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#742]
Description
-----------------------------------------------------------------
'Development Specification' section displayed in old design projects

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Old Project [Design] (https://connect.topcoder-dev.com/projects/875/specification)
- Click on 'Specification' tab
- Check the "Development Specification' section
- Open a New Project [Design] (https://connect.topcoder-dev.com/projects/963/specification)
- Check the above sections --> No such section displayed

Expected Result(s)
-----------------------------------------------------------------
- 'Development Specification' section must removed in old design projects

Actual Result
-----------------------------------------------------------------
- 'Development Specification' section displayed in old design projects

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
New Project:
![25 1](https://cloud.githubusercontent.com/assets/4592712/23732188/a395bdf2-0497-11e7-8e36-f52b87b29756.png)

Old Project:
![25 2](https://cloud.githubusercontent.com/assets/4592712/23732189/a39625c6-0497-11e7-9225-575295f19094.png)

**Comment by gondzo** [comment]
This isn't a bug. All old projects use the same template.
