### ISSUE TITLE
'Which is your primary device target' section missing in Old Prototype projects

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#743]
Description
-----------------------------------------------------------------
'Which is your primary device target' section missing in Old Prototype projects

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Old Project [Design & Prototype] (https://connect.topcoder-dev.com/projects/883/specification)
- Click on 'Specification' tab
- Check the "Which is your primary device target' section -> No
- Open a New Project [Dev > Prototype] (https://connect.topcoder-dev.com/projects/964/specification)
- Check the above sections

Expected Result(s)
-----------------------------------------------------------------
- Must display the 'Which is your primary device target' section in Old Prototype projects

Actual Result
-----------------------------------------------------------------
- 'Which is your primary device target' section missing in Old Prototype projects

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![26 1](https://cloud.githubusercontent.com/assets/4592712/23732355/a082e68e-0498-11e7-886a-618bff459e63.png)
![26 2](https://cloud.githubusercontent.com/assets/4592712/23732356/a08541e0-0498-11e7-88e8-369f1642dee9.png)

**Comment by gondzo** [comment]
All old projects use the same template.
