### ISSUE TITLE
Delete 'App Screens' won't remove the '* required' checkmark

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#744]
Description
-----------------------------------------------------------------
Delete 'App Screens' won't remove the '* required' checkmark

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project (https://connect.topcoder-dev.com/projects/983/specification)
- Click on 'Specification' tab
- Go to 'App Screens'
- Click 'Define another screen'
- It will auto save the section and marked as completed
- Now delete the 'App Screens'

Expected Result(s)
-----------------------------------------------------------------
- Delete 'App Screens' must remove the '* required' checkmark

Actual Result
-----------------------------------------------------------------
- Delete 'App Screens' won't remove the '* required' checkmark

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![27](https://cloud.githubusercontent.com/assets/4592712/23732637/3be31170-049a-11e7-8099-03202097b1e2.png)

**Comment by gondzo** [comment]
The sidebar is updated when the project is saved, ie you have to click the save project button in the section you updated.
