### ISSUE TITLE
Multiple 'Project Updated' messages displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#745]
Description
-----------------------------------------------------------------
Multiple 'Project Updated' messages displayed

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project (https://connect.topcoder-dev.com/projects/983/specification)
- Click on 'Specification' tab
- Go to 'App Screens'
- Click 'Define another screen'
- Click 'Define another screen'
- Click 'Define another screen'
- Check the message

Expected Result(s)
-----------------------------------------------------------------
- Must display only one message

Actual Result
-----------------------------------------------------------------
- Multiple 'Project Updated' messages displayed when user add App Screens

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![28](https://cloud.githubusercontent.com/assets/4592712/23732692/9b838bfa-049a-11e7-87e8-830532bd1d8d.png)

**Comment by fnisen** [comment]
@sdgun what's your expectation as a user? Only one message even though you've clicked the button multiple times?

**Comment by sdgun** [comment]
@fnisen Clicking on 'Define another screen' each time will display a popup message. Instead if we can save added/edited 'Define screens' using the below 'Save Changes' button (Blue button) we can get rid of this multiple messages.

**Comment by fnisen** [comment]
@sdgun thanks, good point. @gondzo I think this may already be addressed by fixes we're doing here: https://github.com/appirio-tech/connect-app/issues/767.
