### ISSUE TITLE
Should be asked for confirmation before deleting the Screen

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#747]
### Expected behavior
Should ask before for the confirmation before deleting the screen

### Actual behavior
delet screen without asking for confirmation 

### Steps to reproduce the problem
1. Open the Application
2. Login with manager : pat_monahan / topcoder123!
3. Create a new design project
4. go to Specification
5. go to App Screens
6. Add new screen
7. Delete Screen

### Screenshot/screencast
![image](https://cloud.githubusercontent.com/assets/16131461/23738950/f3ea35d8-04c1-11e7-80c5-409f19feff28.png)

--

#### Environment
- OS: windows 7
- Browser (w/version):IE 11
- User role (client, copilot or manager): manager 
- Account used: pat_monahan / topcoder123!

**Comment by swetaipec** [comment]
![image](https://cloud.githubusercontent.com/assets/16131461/23738962/05fe3846-04c2-11e7-994c-19d9f22bb848.png)

**Comment by gondzo** [comment]
@fnisen is the delete contirmation required ?

**Comment by fnisen** [comment]
@gondzo no, not required. Can give credit for this one b/c it's a reasonable expectation, but no need to fix.
