### ISSUE TITLE
After user decrease the screen count from 'How many screens do you need designed?'' still previously added 'App Screen' displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#748]
Description
-----------------------------------------------------------------
After user decrease the screen count from 'How many screens do you need designed?'' still previously added 'App Screen' displayed

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project (https://connect.topcoder-dev.com/projects/960/specification)
- Click on 'Specification' tab
- Select 4-8 from 'How many screens do you need designed?'
- Click Save Changes from that section
- Go to 'App Screens'
- Click 'Define another screen'
- Add 4 screens
- Now 1-3 from 'How many screens do you need designed?'
- Go to 'App Screens'

Expected Result(s)
-----------------------------------------------------------------
- If user selected 9-15 screens and added maximum allowed screens from the 'App Screens' and reduce the screen count must reduce the added 'App Screens'

Actual Result
-----------------------------------------------------------------
- After user decrease the screen count from 'How many screens do you need designed?'' still previously added 'App Screen' displayed

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by gondzo** [comment]
the lower screen number options are disabled and can't be selected
