### ISSUE TITLE
Dashboard/Team management: search validation message incorrect when user already on team

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#75]
When adding a username that is already added in the team it says "This username doesn't exist". Which is semantically wrong. The username exists, the event is that his user is already added.

I think we should either change the message and format, or to allow displaying added members in the search result with a tag or some distinction.

![mahestro](https://cloud.githubusercontent.com/assets/729632/18420586/10637752-7876-11e6-8faf-68db8142fba9.jpg)

**Comment by vic-appirio** [comment]
@fnisen please advise on the content copy. From a design standpoint, we shouldn't display such errors when people are on the same team - the check is against @username.

**Comment by fnisen** [comment]
@vic-appirio can we show this validation with the message "This person is already part of your team."?

**Comment by vikasrohit** [comment]
Tracking with asana task https://app.asana.com/0/95614844085038/181122346682547

**Comment by vikasrohit** [comment]
@fnisen @vic-appirio I am done with the changes, please let me know if you guys like to have that in dev. I am not merging the changes in dev yet because of the demo today and we are not sure with the solution as well.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Please merge.

**Comment by vikasrohit** [comment]
@fnisen changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit just slight tweak: can you please add a period at the end of the error message? That's consistent with our current style for other messages.

**Comment by vikasrohit** [comment]
Done. Changes are in dev.

**Comment by fnisen** [comment]
Thanks @vikasrohit. That works, but I found a new issue: https://github.com/appirio-tech/connect-app/issues/147. Not urgent.
