### ISSUE TITLE
no need to show "Define Another Screen"  if user already added define screen 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#750]
### Expected behavior
Define another screen button should not be displayed 

### Actual behavior
Button display in the disable mode 

### Steps to reproduce the problem
1. Open the application
2. login with manager pat_monahan / topcoder123!
3. Create new design project
4. go to Specification 
5. Select How many screens do you need designed? as "1-3 screen "
6. go to add app screen
7. Add 1 screen

#### Environment
- OS: windows 7 
- Browser (w/version): IE 11
- User role (client, copilot or manager): manager
- Account used:  pat_monahan / topcoder123!

**Comment by swetaipec** [comment]
![image](https://cloud.githubusercontent.com/assets/16131461/23739927/2db8ffce-04c7-11e7-8bc7-d09b68f87e0e.png)

**Comment by gondzo** [comment]
the disabled button has a tooltip message saying why no additional screens can be added.
