### ISSUE TITLE
[$50] 'Screen name' and 'Answer' block validation won't display to all the sections

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#751]
Description
-----------------------------------------------------------------
'Screen name' and 'Answer' block validation won't display to all the sections

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project (https://connect.topcoder-dev.com/projects/960/specification)
- Click on 'Specification' tab
- Select 9-15 from 'How many screens do you need designed?'
- Click Save Changes from that section
- Go to 'App Screens'
- Click 'Define another screen'
- Add 9 screens
- Add 'Screen name' and 'Answer' to the first 3 items
- Click Save Changes from that section
- Now scroll up and delete the first 2 screens
- Scroll down and check the below items
- Validation displayed only for two items

Expected Result(s)
-----------------------------------------------------------------
- Must display the validation for all the items

Actual Result
-----------------------------------------------------------------
- 'Screen name' and 'Answer' block validation won't display to all the sections

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/V1Is9bCG

**Comment by fnisen** [comment]
@gondzo this looks pretty messy. What are the current rules for validation?

**Comment by Colinh84** [comment]
@gondzo Need a bit of clarification here. When are these validation errors supposed to appear? Currently, they do not show up for any screen field that does not have content, and only appear when a field that has content and is saved has its content deleted.

**Comment by gondzo** [comment]
@Colinh84 that's fine - we don't want all fields to have validation errors by default.

**Comment by Colinh84** [comment]
@gondzo So then the correct thing to do here is to not show any validation errors when the screens are deleted, since the remaining screens never had content in the first place?

**Comment by gondzo** [comment]
correct

**Comment by gondzo** [comment]
@Colinh84 Can you handle #767 as well since it's related to this one and we'd get merge conflicts if we handle them separately ? Take a look at the comments too as there are a few items there too.

**Comment by Colinh84** [comment]
@gondzo I could, but it looks like that issue is already assigned to somebody else..

**Comment by gondzo** [comment]
@Colinh84 I've created a new issue with items from the comments in 767 and assigned it to you #834 
You can still handle #767 when #834 is complete

**Comment by Colinh84** [comment]
@gondzo ok

**Comment by vikasrohit** [comment]
@Colinh84  #767 is no longer valid for pickup.

**Comment by gondzo** [comment]
this isn't an issue anymore as we changed the component for defining screens. Also, you can't save the changes unless all screens pass validation. closing!
