### ISSUE TITLE
New project pop up automaticaly closed  while  we move scroll bar down 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#752]
### Expected behavior
should show pop up properly 

### Actual behavior
new project pop up automaticaly closed  while  we move scroll bar down 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Click Scroll button

### Screenshot/screencast

https://www.screencast.com/t/EAczqYwg

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by garntsev** [comment]
Excuse me, how to login as manager?
Haven't found info about test manager account in README.md.

**Comment by gondzo** [comment]
see > https://apps.topcoder.com/forums//?module=Thread&threadID=899463&start=0

**Comment by garntsev** [comment]
Not able to reproduce both in Windows:

- OS: Windows 10
- Browsers (w/version): Firefox 52.0 and Google Chrome Version 56.0.2924.87
- User role (client, copilot or manager): Manager
- Account used: pat_monahan

and Linux:

- OS: Linux MInt 17 (Linux home 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)
- Browsers (w/version): 51.0.1 (64-bit) and Google Chrome Version 56.0.2924.87 (64-bit)
- User role (client, copilot or manager): Manager
- Account used: pat_monahan

Should I post links to screencasts here where I am not able to reproduce this bug?

**Comment by fnisen** [comment]
@gondzo I was able to reproduce this on Mac/Chrome earlier, but am not seeing it now. Are you finding it consistently in certain environments?
