### ISSUE TITLE
REF  code accepts  7 characters 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#753]
### Expected behavior
make REF  limt is 5 characters  (based on req https://www.topcoder.com/challenge-details/30056425/?type=develop&noncache=true) 

### Actual behavior
it accepts 7 characters 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter value as "1234567" in REF 
-

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-09 16-23-36](https://cloud.githubusercontent.com/assets/3225433/23747228/ef505430-04e4-11e7-8cec-547620223b9b.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
Bug is correct, but don't need to fix b/c we changed the requirement at some point to allow 7 characters.
