### ISSUE TITLE
[$30] IE 11 -- textbox disabled scroll bar shown 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#755]
### Expected behavior
should show text box properly 

### Actual behavior
disbled scroll bar shown along with text box 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design
- Click Wireframe
- Goto Project Specfication 
- See Guidelines field 

### Screenshot/screencast

![2017-03-09_1646](https://cloud.githubusercontent.com/assets/3225433/23748192/91300b9e-04e8-11e7-9680-6bcc5cb6b38f.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):IE 11
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
@karthikbecse @gondzo not sure I understand the issue here. Is it not clear that you're in a text box because there is no outline?

**Comment by gondzo** [comment]
The scrollbar is not needed. Shown only in IE.

**Comment by karthikbecse** [comment]
i am working
