### ISSUE TITLE
unable to add another  App Screens 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#757]
### Expected behavior
Should enable "add another screen " button 

### Actual behavior
add screen button is diabled 

### Steps to reproduce the problem
- Login As manager

- click New Project 
- Enter valid values 
- Click Design
- Click Wireframe
- Goto Project Specfication 
- Click 15 Screens 
- Now See App Screens Section

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-09 17-04-03](https://cloud.githubusercontent.com/assets/3225433/23748662/907bccae-04ea-11e7-9a7f-c8227082a9c2.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):IE 11
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment]
you need to save the screens number before adding new screens
