### ISSUE TITLE
[$40] Can't add 'App Screens' when user selects '1' from "Other Design"

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#758]
Description
-----------------------------------------------------------------
Can't add 'App Screens' when user selects '1' from "Other Design"

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Create a Project > Design > Other Design
- Example Project (https://connect.topcoder-dev.com/projects/963/specification)
- Click on 'Specification' tab
- Select '1' from 'How many screens do you need designed?'
- Scroll down and click Save Changes button
- Check the 'Define another screen' button in 'App Screens' 

Expected Result(s)
-----------------------------------------------------------------
- Must able to add 1 screen

Actual Result
-----------------------------------------------------------------
- Can't add 'App Screens' when user selects '1' from "Other Design"

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![32](https://cloud.githubusercontent.com/assets/4592712/23749091/7e552f6e-04ec-11e7-9f4a-b1ba92d278b6.png)

**Comment by gondzo** [comment]
already fixed by earlier commits
