### ISSUE TITLE
Changing the screen number from 'How many screens do you need designed?' won't enable the 'Save Changes' button

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#759]
Description
-----------------------------------------------------------------
Changing the screen number from 'How many screens do you need designed?' won't enable the 'Save Changes' button

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Create a Project > Design > Other Design
- Example Project (https://connect.topcoder-dev.com/projects/999/specification)
- Click on 'Specification' tab
- Select '1' from 'How many screens do you need designed?'
- Scroll down and click Save Changes button
- Select '3' from 'How many screens do you need designed?'
- Scroll down and check the 'Save Changes' button

Expected Result(s)
-----------------------------------------------------------------
- Must enable the 'Save Changes' button

Actual Result
-----------------------------------------------------------------
- Changing the screen number from 'How many screens do you need designed?' won't enable the 'Save Changes' button

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![33](https://cloud.githubusercontent.com/assets/4592712/23749078/765bd0ba-04ec-11e7-8061-d9f94a5d42d8.png)

**Comment by sdgun** [comment]
'Save Changes' button won't enable when user changes the settings in any section

**Comment by gondzo** [comment]
Can't reproduce.
