### ISSUE TITLE
Project listing: some sub-set of projects is being exposed to all users

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#76]
Logged in to Connect for the first time with an account that should not have been associated with any projects, but saw some projects in my listing:

<img width="1276" alt="screen shot 2016-09-11 at 5 55 25 pm" src="https://cloud.githubusercontent.com/assets/12552247/18421958/9ec3a562-7849-11e6-9f0d-e88ec6a98c9a.png">

**Comment by parthshah** [comment]
This must be a bug in api layer. Please move this bug to https://github.com/appirio-tech/tc-project-service/issues.

**Comment by fnisen** [comment]
Likely related to the issues I was seeing here: https://github.com/appirio-tech/connect-app/issues/60

**Comment by parthshah** [comment]
@fnisen Is there a user in dev I can use to reproduce this issue?

**Comment by fnisen** [comment]
Going to close this as a duplicate of #60.
