### ISSUE TITLE
If user select 5 screen from the "How many screens do you need designed?" , not able to add screen 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#760]
### Expected behavior
should be able to add screen on selecting 5 in How many screens do you need designed?

### Actual behavior
not able to add screen , 

### Steps to reproduce the problem
1.  Open Application
2 . login with manager   pat_monahan / topcoder123!
3. Create new Design project
4. select Other option 
5. go to specification 
6.  go to How many screens do you need designed?
7. select 5 
8. go to add App screen

### Screenshot/screencast
![image](https://cloud.githubusercontent.com/assets/16131461/23749777/d8cd467c-04ef-11e7-9271-9e084ad14ebf.png)
![image](https://cloud.githubusercontent.com/assets/16131461/23749779/dcc1d9b4-04ef-11e7-867c-795d97568f9a.png)

--

#### Environment
- OS:windows 7
- Browser (w/version): Chrome latest 
- User role (client, copilot or manager): manager 
- Account used: pat_monahan / topcoder123!

**Comment by gondzo** [comment]
need to save screen number section first.
