### ISSUE TITLE
 colors picker not working properly 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#763]
### Expected behavior
should show  colors picker  properly 

### Actual behavior
 colors picker not working properly 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Development 
- Click Prototype
- Goto Project Specfication 
- See  What colors do you like? (Select all that apply)
- Click Add Button
- Select Color 
- See 

### Screenshot/screencast
https://www.screencast.com/t/evfMkv9Il

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment]
it's not intendet do drag&drop, just click the color picker.

**Comment by karthikbecse** [comment]
@gondzo  kindly check it again it is different from other browsers

**Comment by karthikbecse** [comment]
@gondzo  watch this video https://www.screencast.com/t/1PO5QQB2

**Comment by karthikbecse** [comment]
@fnisen can you check  this bug ?

**Comment by gondzo** [comment]
ok, it's a bug, but still out of scope
