### ISSUE TITLE
Question is wrong  when we click Website Development

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#764]
### Expected behavior
should show  Build responsive or regular websites options 
 

### Actual behavior
it shows all 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Development 
- Click Website Development
- Goto Project Specfication 
- See  Which is your primary device target?

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-09 18-35-52](https://cloud.githubusercontent.com/assets/3225433/23751472/8cdd5cae-04f7-11e7-8ced-f10336bf3948.png)
--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment]
those are not related
