### ISSUE TITLE
[$20] text area auto-size issues

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#768]
### Expected behavior
The text area grows with text, but when deleting text it doesn't shrink back. Currently the `<textarea>` tag has property `rows="3"` but it should be initialized with only 1 row and allow to grow.

### Screenshot/screencast
![screen shot 6](https://cloud.githubusercontent.com/assets/8484061/23776473/71b37f9e-04e3-11e7-85e0-5c157d741725.png)
![screen shot 5](https://cloud.githubusercontent.com/assets/8484061/23776477/74fd637c-04e3-11e7-894d-5f81abd06f68.png)
![screen shot 4](https://cloud.githubusercontent.com/assets/8484061/23776479/780b1fe6-04e3-11e7-8ba4-b033c50b7233.png)

Expected
![screen shot 8](https://cloud.githubusercontent.com/assets/8484061/23776483/7dc5906a-04e3-11e7-8eea-c428864d03fb.png)

We should initialize the specification text-area with 1 row. Css style should have min-height 45px (line-height is 25px - fixed).

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by iit2009060** [comment]
@gondzo  How to make change in the  TextArea.jsx which is present in node_modules as it is included in the git ignore.

**Comment by iit2009060** [comment]
https://github.com/appirio-tech/connect-app/pull/831/

**Comment by iit2009060** [comment]
@gondzo  On which branch I need to create request for the repo appirio-tech/react-components  .As changes to row number will be made in this repo.

**Comment by gondzo** [comment]
see https://github.com/appirio-tech/connect-app/wiki/Bug-Bash-Rules
it's feature/connectv2

**Comment by iit2009060** [comment]
@gondzo  Unable to push branch cut out of  feature/connect/v2 
fatal: unable to access 'https://github.com/appirio-tech/react-components.git/': The requested URL returned error: 403

**Comment by gondzo** [comment]
@iit2009060 have you forked the react-components repository ? if not, fork it, create a branch in your repository and create a pull request

**Comment by iit2009060** [comment]
Ok Sure.

**Comment by iit2009060** [comment]
@gondzo Pull request for this issue  https://github.com/appirio-tech/react-components/pull/133 .  
https://github.com/appirio-tech/connect-app/pull/831.
