### ISSUE TITLE
Missing project type icons on dashboard

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#769]
### Expected behavior
Reuse the icons from new project wizard to reflect the correct project type on the dashboard.

### Actual behavior
Currently the dashboard icon section is empty.
![screen shot 11](https://cloud.githubusercontent.com/assets/8484061/23776681/98479450-04e4-11e7-9cb0-5851e27c34b8.png)

### Screenshot/screencast
![screen shot 10](https://cloud.githubusercontent.com/assets/8484061/23776609/1c7907d2-04e4-11e7-9a49-564d09c10012.png)

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by vikasrohit** [comment]
@vic-topcoder In current version (production), we are rendering icons based on target devices. And in the current implementation we have moved the target devices in project specs section, so I guess one has to select target device from the specs questions and hit save to reflect the correct icon in the left panel.
Or let me know if we new design for showing project type icons instead along with showing target devices.
