### ISSUE TITLE
[$30] Project creation: both project-type tabs should be visible to all user roles

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#77]
All users should see "App Design & Dev" & "Other Work" at the top of the Project Creation page

**Comment by mahestro** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30055198/?type=develop&noncache=true

**Comment by mahestro** [comment]
Done - http://www.topcoder.com/direct/contest/downloadSoftwareSubmission.action?projectId=30055200&submissionId=515257

Will merge tomorrow with all the others pending for a merge.

**Comment by mahestro** [comment]
BTW, the main reason why it's not behaving properly is because the data is hardcoded, not pulled from API yet.

For this task I focused in cleaning the search component, fixing a couple of bugs it had and preparing it for the transformation for the new nav. If we want to address the data binding we'd need to create another issue.

**Comment by parthshah** [comment]
@fnisen, curious, what's the rationale behind this change? Do we want anyone to be able to create a generic project?

**Comment by fnisen** [comment]
@parthshah 
1. Regarding making the “Other work” tab visible to everyone… during demos, we’d get the question of “where do I go if I want to create an API, etc.” So we need a place for “other” stuff and it’s more natural to have it in a different tab, rather part of the slider (b/c the slider only address App Design & Dev)
2. Ideally we would expose "Other work" to everyone and allow them to still complete the project details, but modify the copy of the questions or section titles, which is still right now focused on "Apps." Is this easily doable right now? 
3. We could later have another tab for an "empty project," which could be filled with personal challenges... or we simply turn on the challenge creation for copilot and manager roles and not worry about keeping it under certain projects.

@mahestro by the way, this is not working right now. 
<img width="1136" alt="screen shot 2016-09-16 at 5 25 22 pm" src="https://cloud.githubusercontent.com/assets/12552247/18604532/94725788-7c32-11e6-8d80-6a6b866fe2c1.png">

**Comment by mahestro** [comment]
I just went through it with PM, copilot and customer roles. I could create projects from "Other Work" tab. Can you please double check or provide more details?

**Comment by fnisen** [comment]
@mahestro still not working for me. Login as christina_uw/topcoder123! in Chrome. Click "+New Project." Don't see tabs--only see the main project creation screen in the screenshot above.

**Comment by fnisen** [comment]
@parthshah need your input please on my comment from 3 days ago above. Thanks in advance.

**Comment by mahestro** [comment]
Thanks for the extra info on the user. I caught it now. Fixed (to merge).
