### ISSUE TITLE
[$20] Specification: selected screens card should not have blue type on hover

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#773]
### Expected behavior
Numbers on card should remain black on hover; only the outline of the card should be blue.

### Actual behavior
Numbers on card are blue. 

![screen shot 2017-03-10 at 10 56 08 am](https://cloud.githubusercontent.com/assets/12552247/23808873/50ffdbe2-0580-11e7-8b43-1deadcd4514b.png)

**Comment by shubhendusaurabh** [comment]
@gondzo There is no "Ready For Review" label. Is "ready" the correct one?

**Comment by gondzo** [comment]
There is now
