### ISSUE TITLE
[$40] Getting unnecessary unsaved changes warning (regression)

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#778]
### Expected behavior
User should not be warned against unsaved changes if project has been saved

### Actual behavior
User is warned there are unsaved changes
![screen shot 2017-03-10 at 4 30 42 pm](https://cloud.githubusercontent.com/assets/12552247/23818341/f353ff26-05ae-11e7-905f-b4a26d1362cf.png)

### Steps to reproduce the problem
- Access project https://connect.topcoder-dev.com/projects/1030/specification
- Use account pat_monahan/topcoder123!
- Make changes to project spec and click Save. Observe "Project updated" message. Click on Dashboard link.

### Screenshot/screencast
See above

--

#### Environment
- OS: Mac 10.5
- Browser (w/version): Chrome latest
- User role (client, copilot or manager): manager
- Account used: pat_monahan/topcoder123!

**Comment by rrandom** [comment]
Can't repreduce.

**Comment by gondzo** [comment]
visit the above link, add a new screen, save the project and click the dashboard link > the unsaved changes alert is displayed

**Comment by gondzo** [comment]
@rrandom

**Comment by fnisen** [comment]
@shubhendusaurabh how is it going with this issue? Will you be able to finish today?

**Comment by shubhendusaurabh** [comment]
sorry won't be able to finish this.

**Comment by fnisen** [comment]
@shubhendusaurabh how much more time do you need? You can hold on to this issue still--not need to drop it.

**Comment by shubhendusaurabh** [comment]
@fnisen I gave it a try, but it looked tough in my limited React knowledge.

**Comment by fnisen** [comment]
OK, thanks @shubhendusaurabh

**Comment by ThomasKranitsas** [comment]
@fnisen I can imagine what the issues might be here but can you confirm that this is only for the `App screens` section?

**Comment by fnisen** [comment]
@ThomasKranitsas it's not isolated from what I can tell. If I make changes in the "Definition" section (top section) and then try to navigate to a new tab within Connect (e.g., Dashboard), I still get the warning

**Comment by gondzo** [comment]
Yes, app screens section only. App screens field isn't updated in the form
after its submitted. You can verify that by comparing
this.refs.form.getPristineValues () and this.refs.form.getCurrentValues ()
in EditProjectsForm.jsx

**Comment by fnisen** [comment]
Thanks @gondzo!

**Comment by gondzo** [comment]
@fnisen I can't reproduce it in other sections. If you change project description, then save and then click Dashboard link, there is no warning

**Comment by fnisen** [comment]
@gondzo OK, I see. Just tested some more: 
- it will happen if the App Screen section was edited at some point
- Even if you exit the project, come back, and edit another section, the error comes up (as long as the App Screen section was edited previously)

**Comment by fnisen** [comment]
All right, now working correctly. Thank you!
