### ISSUE TITLE
[$40] Required fields are marked incorrectly

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#779]
### Actual behavior
![screen shot 2017-03-10 at 5 01 11 pm](https://cloud.githubusercontent.com/assets/12552247/23818750/30f1ce72-05b3-11e7-95df-43db3e8c3f99.png)

Notes and Project files are marked as required in the section, but not in the navigation (on the left side). 

### Expected behavior
- Notes are never required. Please remove asterisk in main section (for all project types). 
- Files become required if any Questions are skipped. Please dynamically add asterisk in that case, both in the main section and in the left-hand panel

**Comment by gondzo** [comment]
@fnisen Notes remain required for the old projects ?

**Comment by fnisen** [comment]
@gondzo no, Notes were never a required section for old (see below) or new projects. Don't know why it was implemented as required. 

![screen shot 2017-03-14 at 9 34 01 am](https://cloud.githubusercontent.com/assets/12552247/23911274/86ccff4a-0899-11e7-93d1-e07d39eb1ea0.png)
