### ISSUE TITLE
Dashboard: Project Status / States

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#78]
Hey @vic-appirio, you might want to take a look at this. All of the possible status of a project. We have design only for draft, working, cancelled and completed according to the spec/design. You want to create other ones for: in review, reviewed and paused?

![status](https://cloud.githubusercontent.com/assets/729632/18440220/8cd89cf8-7908-11e6-8aac-724fe437e783.jpg)

**Comment by fnisen** [comment]
@mahestro, @vic-appirio here is the full list of states, which is what should be in the API: (also mentioned in my testing doc, what a great resource : ) )

Status types in filter (in order):
- Draft (customer has created project, but not submitted for review)
- In Review (customer has submitted for review [by TC manager])
- Reviewed (project has been qualified [by TC manager] and is ready for copilots to claim it) 
- Active (copilot assigned; challenge will be or have been launched)
- Completed (challenges finished, customer has received output and paid)
- Canceled (customer canceled project after creating it or project was not qualified after being In Review)

Also, I wanted to add these to the filter in listings, which would be aggregations: 
- Open: default status; all projects not in Completed or Canceled status
- All: all projects regardless of status

**Comment by mahestro** [comment]
Juicy...

1. What is this "working" state we have right now? Should be removed? It's in the app fooling around with us.
2. Same with Paused. Should be removed as well most likely. Wdyt?
3. I've seen a status called "Stalled" in direct. Not sure if we're importing that one here in connect.

**Comment by fnisen** [comment]
Vic loves using copy placeholders that seem real, but are not. : ) You can get rid of "Working." I'm pretty sure we're using Canceled for Paused/Stalled/Canceled. Can you please just double-check that it's not in the API? The names of the statuses in the FE should match exactly what's in the API.

**Comment by vic-appirio** [comment]
@mahestro: We should reuse the generic status indicator for all possible statuses - there are 4 groups:

1. Not working (gray): the project is created, but hasn't been launched yet (draft, in review, reviewed)
2. Active (green): the project is being worked on
3. Issue exists (red): there's something wrong, we have to fix it (paused, delayed, etc.). 
4. Completed (black): canceled or completed projects - we're all done with the project, no work is pending.

**Comment by mahestro** [comment]
We're pulling from the API for sure, because right now it's working. You can set states and the changes stay in there after refreshing the browser.

We need to make sure to match the API field names.

**Comment by mahestro** [comment]
Understood @vic-appirio. I think I can get this enhanced with those comments. I'll assign the issue to me.

@fnisen, one last thing.
1. We have the "All the statuses" in the filter currently. I think that would replace your "All". We could just rename it to "All".
2. Is there a particular order you want to see? In the dropdown and in the filter (they should match either way,to keep consistency ~ content and order).
3. I know you kind of mentioned the reply to the following question but I just want to make sure. In case there are differences in the names of the API with what you stated which one we follow? Let's say, "Canceled" corresponds to "Eliminated" in the API. In this hypothetical case, should we stick to what the API states? Or wildly modify the API?

Funny how I say "one last thing" and the list is longer than the amount of times I've broken connect 👯

**Comment by fnisen** [comment]
@mahestro 
1. Yes, agree. 
2. Status types in filter (in order): (let me know if you disagree)
- Open (default)
- All
- Draft
- In Review
- Reviewed
- Active
- Completed
- Canceled
Let's persist the filter, too?
3. Hmm... can you point these out if you come across them and we'll decide which one to use? Ideally they'd be uniform, for when we allow API-based project creation and access.

**Comment by mahestro** [comment]
All right. Sounds good, agree with #2.

I'll put this in the queue for fixes!

**Comment by fnisen** [comment]
@mahestro just want to clarify: when this goes live, it should effect both the status on the Dashboard and in the Search filter, correct?

**Comment by mahestro** [comment]
Yes, that's what I have in mind. Same values and same order.

**Comment by parthshah** [comment]
Paused is a valid status that is different from Cancelled. We don't have any use cases for it at the moment. Other an just an indicator to co-pilots to put this project on hold for the time being i.e. don't launch any challenges etc. Quite okay if we want to remove the option from FE.

**Comment by mahestro** [comment]
@fnisen @parthshah I was checking to launch a task and realized that statuses are hardcoded right now, not coming from the API. I thought it was wired to the API because I could still see changes after reloading the pages, but I let myself be fooled like a child :)

I could prepare the component for the icons but I'd actually prefer to do it after wiring this to avoid reworking. Who could do that for me?

![project status](https://cloud.githubusercontent.com/assets/729632/18558330/f4a300e6-7b72-11e6-970a-8089da4966d8.png)
![project status2](https://cloud.githubusercontent.com/assets/729632/18558331/f4b5be20-7b72-11e6-8aaf-455fb42d2dd1.png)

**Comment by mahestro** [comment]
Thanks for jumping in @appirio-jenkins.

Correct me if I'm wrong, but I think it would be better to define those values just once in the app, then re-use it whenever it's needed instead of repeating them at every page/component we want to use them.

**Comment by parthshah** [comment]
Not sure why posting to an issue through email marks the user as 'appirio-jenkins'.
Yep, good point, we can move this to config/constants.js file.

**Comment by fnisen** [comment]
@parthshah good point about Paused. Let's keep it out for now, as you suggested, and then put it in if it comes up as a needed scenario.

**Comment by mahestro** [comment]
Oh no. It's already implemented :p

**Comment by fnisen** [comment]
Implemented, in the front end? OK, that's fine. Don't tear it out if it's already there.

**Comment by mahestro** [comment]
Yeah, but it's ok. I'll take it out after finishing this pack of fixes.

**Comment by fnisen** [comment]
Please just deploy first and let me check it out....
