### ISSUE TITLE
REF code accepts Special  characters

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#782]
### Expected behavior
Should show an error 

### Actual behavior
it accepts Special characters

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter   REF  value as "@#$!#$" 
- See 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-11 18-02-11](https://cloud.githubusercontent.com/assets/3225433/23823265/f87f3836-0684-11e7-9322-b6a5ac82f538.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
There are no restrictions in the UI regarding Ref code.

**Comment by karthikbecse** [comment]
![screenshot-www topcoder com 2017-03-14 10-06-03](https://cloud.githubusercontent.com/assets/3225433/23886094/0919067a-089e-11e7-9ab1-8f5f487bbfa4.png)
@fnisen  see the  [contest page]( https://www.topcoder.com/challenge-details/30056425/?type=develop&noncache=true)

**Comment by fnisen** [comment]
@karthikbecse fair point. However, "character" is used in the general sense, meaning 5 characters of any kind. A special character is still a type of character. (The bug on the character limit has already been filed).
