### ISSUE TITLE
Project Estimate missing in old projects 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#783]
### Expected behavior
Should show Project Estimate 

### Actual behavior
Project Estimate missing in old projects 

### Steps to reproduce the problem
- Login As manager
- click Old Project (https://connect.topcoder-dev.com/projects/105/specification)
- Goto Project Specfication 
- Fill All details 
- click Save changes 
- see Side Menu 

### Screenshot/screencast
![screenshot-connect topcoder-dev com 2017-03-11 17-58-05](https://cloud.githubusercontent.com/assets/3225433/23823241/67cab982-0684-11e7-846a-29a85c460955.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by karthikbecse** [comment]
#### Note
old design project

**Comment by gondzo** [comment]
this is working as it should. old projects will show the same info.
