### ISSUE TITLE
question section not highlited properly 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#784]
### Expected behavior
Shoud show Question section instead of project info 

### Actual behavior
while click Question  it highlights project info section 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design
- Click Wireframe
- Goto Project Specfication 
- In projectSpec  Sidebar 

- Click Questions

-see

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-11 17-51-51](https://cloud.githubusercontent.com/assets/3225433/23823201/90599b94-0683-11e7-9403-a921db4e5536.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
Project info is the first part of the Questions section in that current structure.
