### ISSUE TITLE
Specfication  body missing question heading

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#785]
### Expected behavior
should show  question  heading 

### Actual behavior
There is no question heading 

### Steps to reproduce the problem
- Login As manager
- click Old Project 
- Goto Project Specfication 
- In Specifications side Menu
- See App Definition 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-11 17-47-33](https://cloud.githubusercontent.com/assets/3225433/23823179/f4d6e870-0682-11e7-89e3-4fbe0c99137f.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
Known issue: https://github.com/appirio-tech/connect-app/issues/650

**Comment by karthikbecse** [comment]
@fnisen  there is no word about question heading see the bug #650 once again 

![screenshot-connect topcoder-dev com 2017-03-14 10-51-39](https://cloud.githubusercontent.com/assets/3225433/23886953/c088841a-08a4-11e7-8f52-0926443079b3.png)

**Comment by fnisen** [comment]
@karthikbecse please check out my comment here: https://github.com/appirio-tech/connect-app/issues/650#issuecomment-284608188. In the linked doc, I define what the sections should be.

**Comment by fnisen** [comment]
Let me research your appeal a little more. I'll get back to you.

**Comment by gondzo** [comment]
@fnisen Can we close this ?

**Comment by fnisen** [comment]
@gondzo yes, this is working as designed, so there's nothing to fix. However, I can see how not having the Questions section is confusing, so I'm OK counting this one.
