### ISSUE TITLE
Old projects have  unwanted note section 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#786]
### Expected behavior
Shoud hide Note section in  sidebar 

### Actual behavior
Old projects have  unwanted note section 

### Steps to reproduce the problem
- Login As manager
- click Old Project 
- Goto Project Specfication 
- See  Specifications side Menu 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-11 16-58-23](https://cloud.githubusercontent.com/assets/3225433/23823119/979773ba-0681-11e7-8cf6-63e267288abb.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by karthikbecse** [comment]
#### Note
old design project

**Comment by gondzo** [comment]
this is working fine. old projects will have the same views.
