### ISSUE TITLE
Project Info filled by default (No description provided)

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#790]
### Expected behavior
should show placeholder instead of value 

### Actual behavior
Project Info  filled by deault  (No description provided)

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design
- Click Wireframe
- Goto Project Specfication 
-see Project Info 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-11 18-53-48](https://cloud.githubusercontent.com/assets/3225433/23823613/3828aed4-068c-11e7-9aa5-ba191ecd2962.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
Known issue: https://github.com/appirio-tech/connect-app/issues/650#issuecomment-285817825

**Comment by karthikbecse** [comment]
@gondzo  is this vald for bug hunt beacuse  referenced  bug tiltle and description is different almost check the bug timeing and comment timing 3 days ago

**Comment by gondzo** [comment]
yes, it will count towards your score
