### ISSUE TITLE
text block bacrground color is different 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#791]
### Expected behavior
should show text block properly 

### Actual behavior

text block bacrground color is changing when  we delete entered value 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design
- Click Wireframe
- Goto Project Specfication 
- Answer this question "What is the goal of your application? How will people use it?"
- delete all character in the text block 
- See Background color 

### Screenshot/screencast

https://www.screencast.com/t/kHPrl1iUnt

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0 
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment]
same as #800
