### ISSUE TITLE
old Project  "Which is your primary device target?" question   missing  

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#792]
### Expected behavior
Shoud show  the question 

### Actual behavior
 "Which is your primary device target?" question   missing  

### Steps to reproduce the problem
- Login As manager
- click Old Project 
- Goto Project Specfication 
- See  Specifications Body 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-11 19-07-34](https://cloud.githubusercontent.com/assets/3225433/23823704/39d3f868-068e-11e7-9189-1dff1fa4d769.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by karthikbecse** [comment]
#### Note
old design project

**Comment by gondzo** [comment]
this is working fine. old projects will have the same view.
