### ISSUE TITLE
old Project "How many screens do you need designed?" question missing

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#793]
### Expected behavior
Shoud show  the question 

### Actual behavior
 "How many screens do you need designed?" question   missing  

### Steps to reproduce the problem
- Login As manager
- click Old Project 
- Goto Project Specfication 
- See  Specifications Body 

### Screenshot/screencast

![2017-03-11_1911](https://cloud.githubusercontent.com/assets/3225433/23823723/bba25984-068e-11e7-9c9f-88b78d625630.png)
--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by karthikbecse** [comment]
#### Note
old design project

**Comment by gondzo** [comment]
this is working as designed.
