### ISSUE TITLE
App Screens section is missing 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#794]
### Expected behavior
Shoud show App Screens section 

### Actual behavior
App Screens section is missing 

### Steps to reproduce the problem
- Login As manager
- click Old Project 
- Goto Project Specfication 
- See  Specifications Body 

### Screenshot/screencast

https://www.screencast.com/t/cgAXIRiXer

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by karthikbecse** [comment]
####Note 
Design Specification shown insted of App Screens section

**Comment by gondzo** [comment]
this is working as designed
