### ISSUE TITLE
[IE11] delete icon shown 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#798]
### Expected behavior
Hide delete icon 

### Actual behavior
delete icon shown  

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Development
- Click Prototype
- Goto Project Specfication 
- In App Definition -Fill all require values 
- In Design Specification filed 
- Click add colors upto 5
- Delete 3rd  one 
- See 

### Screenshot/screencast

https://www.screencast.com/t/8d0ZViaak

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):IE 11
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

#### Note
behavior is different from other browsers

**Comment by karthikbecse** [comment]
@gondzo  it is valid bug but your not counted for the contest

**Comment by gondzo** [comment]
It is counted in the out of scope section, as color picker is previous functionality and isn't updated in this series of contests
