### ISSUE TITLE
meaningless alt for icons 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#799]
### Expected behavior
Should change alt for icons 

### Actual behavior
icon alt is meaningless 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Development
- Click Prototype
- Goto Project Specfication 
- In App Definition -Fill all require values 
- In Design Specification filed 
- Move What icon style do you prefer? (Pick one)
- hover the icon 
- see alt 

### Screenshot/screencast

![sf](https://cloud.githubusercontent.com/assets/3225433/23825238/019c996e-06ac-11e7-8f2f-f4981342b30b.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

####Note 
All icons

**Comment by fnisen** [comment]
@vic-topcoder let's define what the alt-text should be

**Comment by vic-topcoder** [comment]
All Alt are description/tooltip for screen readers;

It should guide the user towards taking an action. 

Should be "Select `item description`" as a tooltip

devices: Mobile Phone, Tablet, Desktop, Wearable

fonts: Serif typeface, Sans-serif typeface

icons: flat icons, thin line icons, solid line icons
