### ISSUE TITLE
 Screen text box background color is changed 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#800]
### Expected behavior
Should not change background color

### Actual behavior
 Screen text box background color is changed  

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design 
- Click App Visual Design - Production
- Goto Project Specfication 
- In App Definition -Fill all require values 
- In App Screen  section 
- Add new Screen 
- Add one screen 
-  Now  Enter   Screen name 
- Enter  value   What are the things the user can do on this screen?
- See Screen name  background color 

### Screenshot/screencast

![2017-03-11_2331](https://cloud.githubusercontent.com/assets/3225433/23825650/8094049e-06b3-11e7-85bc-5ec15120d48d.png)
![2017-03-11_2332](https://cloud.githubusercontent.com/assets/3225433/23825651/80971940-06b3-11e7-8f03-8927f967fff7.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
@vic-topcoder is this working as designed?

**Comment by vic-topcoder** [comment]
This is by design. Empty text area/inputs are colored to be distinguished, while text area with content is blended with the background to support better reading experience. This is a solution until we have a better editing/viewing rendering of the specification document enabled. Not bug
