### ISSUE TITLE
save changes button works for all section 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#801]
### Expected behavior
Should not change other section button 

### Actual behavior
Both of the button disabled 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design 
- Click App Visual Design - Production
- Goto Project Specfication 
- In App Definition -Fill all require values 
-Click Save changes 

- See App Screens Save changes  button And Design Guidelines Save changes  button

### Screenshot/screencast

https://www.screencast.com/t/8u07rWCc

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment]
working as designed. clicking any save button will save all sections
