### ISSUE TITLE
can add more screen  

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#802]
### Expected behavior
Disable other screen option after  save changes 

### Actual behavior
Can change No of screen 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design 
- Click App Visual Design - Production
- Goto Project Specfication 
- In App Definition -Fill all require values with (4-8 screens)
- Click Save changes 
- Add new Screen 
- Add four screen 
- Now select  (1-3 screens )
- Click Save changes 
- see 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-12 00-09-19](https://cloud.githubusercontent.com/assets/3225433/23825887/7012558a-06b8-11e7-8738-06c2401c7dc2.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment]
this is expected. you need to remove some of the screens to select lower screen count option

**Comment by karthikbecse** [comment]
@gondzo  watch the screenshot closely it is disabled but it is seleted also check quick quote cost

**Comment by karthikbecse** [comment]
@fnisen can you check  this bug ?

**Comment by gondzo** [comment]
@karthikbecse right, I didn't notice the disabled option is selected. Valid bug.
@fnisen I don't know what is the right approach in this case - maybe add validation for the entire project object before saving (ie, not validate at question level only, but validate questions based on answers to other questions). For example we could validate screens number answer and actual number of screens added. Same goes for skip question and project files.
@vikasrohit any ideas ?

**Comment by fnisen** [comment]
@gondzo @karthikbecse I can see the bug in the screenshots, but can't reproduce. @karthikbecse can you please provide a video? Also, it doesn't seem like a validation issue--you're just not supposed to be able to select a disabled option.

**Comment by gondzo** [comment]
@fnisen 
1. Create a new project and select 4-8 screens option and save changes
2. Define 4 new screens (but don't save)
3. Change the selection to 1-3 screens and save
The selected option is disabled

**Comment by fnisen** [comment]
Thanks @gondzo. 
@vikasrohit do we need to consider implementing auto-save? Is there another "easy" approach?

**Comment by vikasrohit** [comment]
@fnisen With changes made for #858 we are able to reflect changes in one section to another section. I think we can utilize that feature now to refresh the number of screens options on the fly i.e. every time a user add/deletes a screen, the number of screens question (in fact all other questions) would re-render themselves and may update itself based on dirty project values. I have tried this on my local machine today, and it seems to work. However, again we have to do some regression testing with these changes as there might be side effects of this change.
[PR](https://github.com/appirio-tech/connect-app/pull/863) is created, feel free to merge it into dev if you would like to play with the changes in dev. I guess it is best time to play with changes as we already have changes for #858 in dev.

**Comment by vikasrohit** [comment]
Changes are in dev. Merging the [PR](https://github.com/appirio-tech/connect-app/pull/863) considering the PR waiting for so long in pending state. We can do regression testing in dev.
