### ISSUE TITLE
screen limit is not working properly 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#804]
### Expected behavior
should allow to add 4- 8 screens 

### Actual behavior
only can add 4 screens after Button is disabled 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design 
- Click App Visual Design - Production
- Goto Project Specfication 
- In App Definition -Fill all require values with (4-8 screens)
- Click Save changes 
- Add new Screen 
- Add four screen 
- see define another Screen button 

### Screenshot/screencast
![screenshot-connect topcoder-dev com 2017-03-12 00-14-31](https://cloud.githubusercontent.com/assets/3225433/23825939/1b593148-06b9-11e7-9adf-1555a9f89102.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
Known issue: https://github.com/appirio-tech/connect-app/issues/767 and bugs linked from that ticket
