### ISSUE TITLE
[upload file]  can rename  the extension 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#805]
### Expected behavior
Should not change file extension

### Actual behavior
Can chnage file extension too 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design 
- Click App Visual Design - Production
- Goto Project Specfication 
- In App Definition -
- upload image file
- in list click edit 
- See 

### Screenshot/screencast

![screenshot-connect topcoder-dev com 2017-03-12 00-20-47](https://cloud.githubusercontent.com/assets/3225433/23825981/e6fc44fc-06b9-11e7-9d77-1ba8b542c41f.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by fnisen** [comment]
User can rename the file as desired. That doesn't effect ability to view or download.
