### ISSUE TITLE
App Screen  section is enabled for another managers 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#807]
### Expected behavior
Should  disable App Screen  section

### Actual behavior

App Screen  section is enabled for another managers 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design 
- Click App Visual Design - Production
- Goto Project Specfication 
- In App Definition -Fill all require values 
- In App Screen  section 
- Add new Screen 
- Click Save changes 

Another Manager Login(pshah_manager)
- click Project 
- Click specification
- Click App Screens 
- change screen name 
- click save changes 

### Screenshot/screencast

https://www.screencast.com/t/nVyIECadZ

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

#### Note
values are not changed but filed is enabled

**Comment by fnisen** [comment]
@karthikbecse fair point, but this is working as expected. The second user won't see changes unless they refresh their page.
