### ISSUE TITLE
Can't add a new project in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#811]
Description
-----------------------------------------------------------------
Can't add a new project in IE11

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click on + Create Project
- Try to enter the name

Expected Result(s)
-----------------------------------------------------------------
- Must able to add a project

Actual Result
-----------------------------------------------------------------
- Can't add a new project in IE11 (After new build)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pshah_manager
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2017-03-12_5-37-23](https://cloud.githubusercontent.com/assets/4592712/23827915/fe4ec874-06e5-11e7-9bd3-2aa7aa442448.png)

**Comment by sdgun** [comment]
https://www.screencast.com/t/A30vHCqmt

**Comment by gondzo** [comment]
@sdgun I can't reproduce the issue, IE works fine for creating the projects
