### ISSUE TITLE
Clicking BACK button won't display the selected main stream project type (Design or Development)

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#812]
Description
-----------------------------------------------------------------
Clicking BACK button won't display the selected main stream project type (Design or Development)

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Click on + Create Project
- ENter Name and click Desin
- Click Wireframe from the next screen
- Click Back
- You can see the name is there but the type is deselected

Expected Result(s)
-----------------------------------------------------------------
- Must mark the selected project because peoject name is also there

Actual Result
-----------------------------------------------------------------
- Clicking BACK button won't display the selected main stream project type (Design or Development)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pshah_manager
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2017-03-12_5-46-47](https://cloud.githubusercontent.com/assets/4592712/23827949/517765a0-06e7-11e7-8566-7d6fef43069b.png)

**Comment by gondzo** [comment]
well, by going back the user canceled their selection on the first screen, so this is how it's supposed to be IMO

**Comment by fnisen** [comment]
Agree with @gondzo. There is actually not state when Dev or Design categories are selected. Clicking on either moves you to the next screen. Closing.
