### ISSUE TITLE
Change project type name in Dashboard panel

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#827]
<img width="390" alt="screen shot 2017-03-13 at 10 41 47 am" src="https://cloud.githubusercontent.com/assets/12552247/23867625/c1b1c250-07d9-11e7-9537-8bb1e0cc287d.png">

Change project name (above) to match specific project type (rather than generic Design or Dev name)

**Comment by vikasrohit** [comment]
You mean specific product type?

**Comment by fnisen** [comment]
Yes, product type == project type == project template. Had assigned it to myself so I can edit the wording later.

**Comment by vikasrohit** [comment]
Yes for now the equation is valid as number of products per project is exactly one for now. When we have multiple products per project, we have to map product type to the spec template, which are doing already.
