### ISSUE TITLE
Tech Debt issues after Products MVP release

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#832]
- [x] Use TextInput component from react-component repo instead of creating another [one](https://github.com/appirio-tech/connect-app/blob/dev/src/components/TextInput/TextInput.jsx) in connect-app
~~- [ ] Get rid of form under form element for projects with App Screens section~~ (#1388)
~~- [ ] Remove [old forms](https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Forms) implementation from react-components repo.~~ (#1389)

**Comment by gondzo** [comment]
- [ ] Refactor SpecQuestions and SpecScreenQuestions to remove duplicate code.

**Comment by vic-topcoder** [comment]
@vikasrohit @gondzo - let's review if this is still valid and if so, break down to action items for community to fix
@mtwomey FYI

**Comment by vikasrohit** [comment]
@vic-topcoder closing the issue as I have created separate issues for the pending items.
