### ISSUE TITLE
[$20] Error if updating project without project description on specification page

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#835]
Updating project without project description on specification page will result in error with no info about the details. Same as #727 but for project description.

**Comment by vikasrohit** [comment]
@gondzo Fix for this issue would require fixing in API for PATCH requests which I have already requested to @parthshah. So, I guess, there is no front end change is require to fix this. Please correct me if I missed anything here.

**Comment by parthshah** [comment]
API changes are in dev & prod topcoder-platform/tc-project-service/issues/50

**Comment by fnisen** [comment]
I'm not seeing this issue after the API changes. Please let me know and reopen if you're able to reproduce it.
