### ISSUE TITLE
Requirements asterisks (*) are misaligned in body of spec document

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#838]
![screen shot 2017-03-14 at 10 59 06 am](https://cloud.githubusercontent.com/assets/12552247/23915094/459f4f3a-08a5-11e7-867e-3337195d911f.png)

**Comment by vic-topcoder** [comment]
Not sure what is the requirement here

**Comment by ThomasKranitsas** [comment]
@vic-topcoder notice how the `*` on the **How many screens..** question has some margin from the question while the `*` on the `Project Name` appears right after the letter `e` (no margin)...

So I guess the * should either have the same margin or should not have margin at all :)

**Comment by fnisen** [comment]
@sirakovaDimitrina can I give this one to you? As @ThomasKranitsas, the issue is that the asterisks are not at a consistent spacing from the rest of the text.

**Comment by sirakovaDimitrina** [comment]
@fnisen  Ok i will fix this issue

**Comment by sirakovaDimitrina** [comment]
@fnisen This issue is fixed

**Comment by fnisen** [comment]
Thank you @sirakovaDimitrina
