### ISSUE TITLE
"Other design" product should be using old design project template

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#839]
@gondzo or @vikasrohit can you please update this with the necessary template numbers so it's easy for a member to fix (or feel free to fix directly).

**Comment by gondzo** [comment]
@fnisen this is fixed and merged

**Comment by fnisen** [comment]
@gondzo I'm getting a blank screen on that type of project. 
![screen shot 2017-03-14 at 6 03 45 pm](https://cloud.githubusercontent.com/assets/12552247/23929073/a59d5c52-08e0-11e7-9718-9474ac574f86.png)

**Comment by fnisen** [comment]
Changing to P0 b/c the open bug is making the that project type unusable.

**Comment by ThomasKranitsas** [comment]
@fnisen the issue is because the `details.appDefinition.numberScreens` field is missing from the `topcoder.v1` template but is required to calculate the quick quote.
I'm not sure how we should handle this.

**Comment by gondzo** [comment]
@ThomasKranitsas there should be no quick quote for this type. Just edit ProjectSpecSidebar#getProjectEstimateSection to not return VisualDesignProjectEstimateSection component

**Comment by ThomasKranitsas** [comment]
@gondzo ok I'll push a commit in few minutes

**Comment by fnisen** [comment]
Thanks guys. Now working correctly!
