### ISSUE TITLE
Project Creation: Replace .svg icons with the correct .jsx icon components

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#84]
The device icons currently used in the project creation view are the old .svg icons. We have .jsx icon components from react-components/icons. Please update when you have time - they'll improve rendering "IconTechOutline*.jsx"

**Comment by vic-appirio** [comment]
We can do that as part of the code refactoring after beta launch. De-escalating.

**Comment by vic-appirio** [comment]
Reassigning to @mahestro  as we're working on an automated SVG Loader plugin implementation in a parallel branch. Once this is done, there will be no need for @vikasrohit to actually do anything manually.

**Comment by vikasrohit** [comment]
I think it would be good candidate for community. @gondzo what do you think?
