### ISSUE TITLE
Screen description validation using incorrect blue color

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#840]
![screen shot 2017-03-14 at 12 08 10 pm](https://cloud.githubusercontent.com/assets/12552247/23918125/f39eae4c-08ae-11e7-97b7-c24e6b19a683.png)
(Result of not quite correct implementation here: https://github.com/appirio-tech/connect-app/issues/737)

**Comment by vic-topcoder** [comment]
I think those are error states in the `tc-ui` repo. Error state on focus should persist - maybe missing class?

**Comment by fnisen** [comment]
@sirakovaDimitrina would you be able to handle this one?

**Comment by vikasrohit** [comment]
@vic-topcoder I think we always had focus state override all states including error states.
@fnisen I don't think it is because of #737

**Comment by sirakovaDimitrina** [comment]
@fnisen Yes, I will check this issue

**Comment by fnisen** [comment]
@sirakovaDimitrina I'm still seeing this one. Does it need to be merged? 
![screen shot 2017-03-17 at 3 30 27 pm](https://cloud.githubusercontent.com/assets/12552247/24065213/adee63ae-0b26-11e7-8652-208e676f0ad3.png)

**Comment by fnisen** [comment]
@sirakovaDimitrina I'm still seeing this issue. Does the fix need to be merged? 

![screen shot 2017-03-17 at 3 30 27 pm](https://cloud.githubusercontent.com/assets/12552247/24065234/ccc0536e-0b26-11e7-98b8-f8d2b3129fc7.png)

**Comment by sirakovaDimitrina** [comment]
@fnisen I made the changes in the MAIN input style. The styles are in the react component repo. I do not know if they are merged.

**Comment by vikasrohit** [comment]
I got it. @sirakovaDimitrina We need to do changes in [this](https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/Formsy/FormFields.scss) FormFields.scss. File from Forms folder is old discarded implementation which we are not using any more.

@parthshah I am adding removal of this Forms folder in tech debt. Do you remember if we are using, by any chance, that old form implementation anywhere.

**Comment by sirakovaDimitrina** [comment]
@vikasrohit  Thank you for this information. I will move the changes in the new class which we use for the input in the connect-app repo.
