### ISSUE TITLE
Ownership changed email

### ISSUE THREAD

**Issue by rsial2** [appirio-tech/connect-app#860]
1. System is repeated twice. (FN: This is where Coder Bot should appear.)
2. missing an "&", so the sentence should read "Your project has a new owner & Hugo Robles..." (FN: We missed a period here. "Your project has a new owner. Hugo Robles....")
3. Project title is not being picked up. (FN: it's not being resolved in the app, nor by email).

![image](https://cloud.githubusercontent.com/assets/5807576/24062953/9604d5f2-0b2b-11e7-98f1-4709266750b8.png)

**Comment by parthshah** [comment]
1. should be resolved now. 
2 & 3 can be tracked through #topcoder-platform/tc-connect-notifications/issues/70

**Comment by rsial2** [comment]
Thanks Parth
