### ISSUE TITLE
Clicking "submit for review" on Dashboard will prompt user to save changes

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#869]
### Steps to reproduce the problem
- Create project or go to existing draft project and complete intake form
- Do not save changes
- Click "Submit for review"
- See message asking whether changes should be saved

### Expected behavior
- When user clicks "Submit for review," we should automatically save changes and take the user to the Dashboard, where they can see the confirmation message
- Upon clicking "Save for Review", the user is currently taken to the Dashboard when changes are Saved, but not otherwise

**Comment by vikasrohit** [comment]
I can handle it however, if we are about to launch a challenge and we can group this one into some bucket, it would be good to get it resolved by community.
