### ISSUE TITLE
Add posts formatting to comments/replies for Dashboard and Discussions

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#870]
The composer has formatting options when starting a new post, in both Dashboard and Discussion sections:
![screen shot 2017-03-27 at 1 45 28 pm](https://cloud.githubusercontent.com/assets/12552247/24377269/ad612654-12f3-11e7-9b05-a3dc92156279.png)

But those options are missing when replying/commenting in both sections:
![screen shot 2017-03-27 at 1 45 57 pm](https://cloud.githubusercontent.com/assets/12552247/24377281/ba1ac2ec-12f3-11e7-9b4f-c34f213e4c58.png)

**Comment by vikasrohit** [comment]
@fnisen we can put this one in a bucket for bug bash challenges if we have couple more issues with discussions/messages.

**Comment by fnisen** [comment]
Now working.
