### ISSUE TITLE
Manager does not get manager access immediately after joining the project

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#873]
### Expected behavior
Manager should be visible as Team Member on Dashboard. Manager should be able to edit specifications of the project.

### Actual behavior
Manager is not displayed as Team Member on Dashboard. Manager is NOT able to edit the specifications of the project without refreshing the page.

### Steps to reproduce the problem
- Open a project where you are not already part of the team
- Click on the Join button to join as manager
- Notice that user is displayed as Manager in the team
- Now to go to Specifications page, till this time manager is able to edit the specs
- Now go back to dashboard, notice that user is not the team any more and Join button is visible again
- Go to specifications page, notice that now all fields of the form are readonly

--

#### Environment
- OS: All
- Browser (w/version): All
- User role (client, copilot or manager): Manager
- Account used: pshah_manager

**Comment by vikasrohit** [comment]
fyi, @parthshah @fnisen

**Comment by vikasrohit** [comment]
@fnisen do you want this fix as hotfix on server or as a regular fix when we push next release?

**Comment by vikasrohit** [comment]
bump up

**Comment by fnisen** [comment]
@vikasrohit sorry for the delay. Hotfix please.

**Comment by vikasrohit** [comment]
Deployed to prod on Apr 14, 2017.

**Comment by vikasrohit** [comment]
Closing the issue to clean up the list. @fnisen Please let me know if the issue resurfaces or is not fixed.
