### ISSUE TITLE
Links in Discussions are not loading correctly

### ISSUE THREAD

**Issue by rsial2** [appirio-tech/connect-app#881]
See screenshot below:
![image](https://cloud.githubusercontent.com/assets/5807576/24958794/343e3a4a-1f56-11e7-8418-b16e97faa4a9.png)

**Comment by gondzo** [comment]
This one can't be fixed without changing the tc challenge page site. 
URL preview relies on meta tags in html of the linked page, and since tc challenge page is angular based it has only placeholders in those tags and populates them only when it loads the challenge details from the api. The only solution here is to build server side rendering support for the topcoder challenge pages.

**Comment by rsial2** [comment]
Then we should build something server side - from a user and product perspective, it looks really really bad.

**Comment by fnisen** [comment]
@ajefts please see Rash's comment above. Last time we discussed this with Parth, he didn't think much could be done before we rebuilt the challenge details pages. @gondzo is suggesting these libraries could help: https://github.com/ng-consult/ng1-server (Angular 1.3+); https://universal.angular.io/ (Angular 2)

**Comment by vikasrohit** [comment]
@gondzo just curious, if fragments can help us here.

**Comment by mtwomey** [comment]
@ajefts Can you weigh in on this one when you hava a sec please?

**Comment by gondzo** [comment]
This one should be solved with recent updates to the challenge pages. they don't contain any opengraph tags so the links are not expanded at all. Related issue in the new challenge pages https://github.com/topcoder-platform/community-app/issues/566

@mtwomey @vic-topcoder are we OK to close this one ?

**Comment by birdofpreyru** [comment]
@gondzo try now: related meta-tags have been added to challenge listing and details pages.

**Comment by gondzo** [comment]
thanks @birdofpreyru . Looks good
![image](https://user-images.githubusercontent.com/3051646/32586595-3f729390-c4b8-11e7-98cc-95b26fe5916e.png)

The preview image might be smaller, but I guess that is something we can handle in the app if needed. @rsial2 OK to close this one ?
