### ISSUE TITLE
Style the ProjectOutline component as per specs

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#889]
This task is to style the ProjectOutline component as per specs provided by Vic.

**Note:** This component right now uses the `VisualDesignProjectEstimateSection` component for rendering the project estimates and the same component is being used by `ProjectSpecSidebar` component to render the estimates in Specification Tab of the project. So, fixing style for `VisualDesignProjectEstimateSection` for fixing style of `ProjectOutline` component, would also affect the view in `ProjectSpecSidebar` component.

**Comment by vikasrohit** [comment]
@vic-topcoder Can you please check with Didi if she needs anything else to get started on this? I can make any DOM/Javascript changes required. The changes are in [feature/deep-links](https://github.com/appirio-tech/connect-app/tree/feature/deep-links) branch.

**Comment by vikasrohit** [comment]
@vic-topcoder @fnisen Can you please verify if anything pending for this?

**Comment by vikasrohit** [comment]
bump up 😬

**Comment by vic-topcoder** [comment]
The style seems ok, but there are still problems with the sticky state of the side bar!

![screen shot 5](https://user-images.githubusercontent.com/8484061/29057333-7944a916-7bbe-11e7-9a50-7201bec47ed4.png)
![screen shot 6](https://user-images.githubusercontent.com/8484061/29057334-7954314c-7bbe-11e7-80d5-c1b0c6ed281c.png)

**Comment by vic-topcoder** [comment]
@vikasrohit - Can we fix the sticky at some point? The position isn't right and once the side bar is updated through the main form, the element isn't sticky anymore.

**Comment by vikasrohit** [comment]
@gondzo Can we have it addressed with community?

**Comment by gondzo** [comment]
yes, we'll probably have a round of fixes for the messaging updates so we can handle this one as well.

**Comment by vikasrohit** [comment]
cool, you can label it for your reference.

**Comment by fnisen** [comment]
@gondzo assigning to you for follow up

**Comment by vikasrohit** [comment]
Created separate issue #1105 for better tracking. This issue was only for styling of the component and it seems that is already fixed.
