### ISSUE TITLE
Project Details: Specification panel not showing any logic

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#89]
As the user goes into project details and answers questions, the specifications panel on the left should update showing what has been completed and allowing a user to "Submit for Review" (the button is active) when they've filled out the required info. In my tests, the panel was showing almost no logic, as if it hadn't been wired. See attached design for reference (and compare vs. implementation):

More details:
1. Only App Definition is required as a section
2. In App Definition/Questions, we should show the number of questions completed (or skipped) as 1 of 3 and so on; explicitly checking skip is the same as answering
3. If a question is skipped, the Files section becomes mandatory; i.e., a user must answer all 3 questions or upload a doc (of any kind) if they have skipped any questions
4. For all sections, if any question has been completed, we should show the number (e.g., 2 of 3)
5. If notes or files has been completed, we should show a check mark
6. The "Submit for Review" button should activate once all required sections have been completed

![d0cabc28-0bb9-479f-8965-cd6022383028](https://cloud.githubusercontent.com/assets/12552247/18537597/a45a232e-7abb-11e6-8021-fe5a24ee95cb.png)

**Comment by parthshah** [comment]
I believe the left panel is wired to the saved project data, and doesn't take unsaved changes in to account. That said there could be a bug with that logic as well. Do we want it to reflect un-saved changes as well? Won't that be confusing especially since we don't have auto-save currently?

**Comment by parthshah** [comment]
@fnisen need your input here. Thanks

**Comment by fnisen** [comment]
@parthshah sorry for the delay. I agree with you--it should reflect only saved changes. I've tested with Saving Changes and the logic is still not working. 

@mahestro can you please use my checklist above (under More Details) to test the fix?

**Comment by mahestro** [comment]
Great! I'll give it a careful look tomorrow morning!

**Comment by mahestro** [comment]
I went through it today with /projects/292/specification. Found the following:

- Amount of progress is not updated. At first arrival it says 0 of 3 for App Definition > Questions and Specifications. Once I enter text in "What is the goal of your application? How will people use it?" and hit the save button, it replaces the "0 of 3" by a checkmark. If three are required it should be progressively incrementing the amount, 1 of 3, 2 of 3 and checkmark.
- If I delete my notes and hit save again, it should be required again but instead it thinks it still has valid content (showing checkmark).
- Skipping questions doesn't influence the progress in the left panel (keeps the checkmark).
- The Submit for Review button never appears even if I complete every single field of the page.
- In Dev Specs, I'm not sure what is required. It's not like App Definition which has a * on "Questions".

**Comment by fnisen** [comment]
@mahestro yes, your testing matches what I was seeing. Nothing is required for Dev Spec. It's an optional section, per the design linked in the first comment above.

**Comment by mahestro** [comment]
@fnisen @parthshah I can launch this as a F2F challenge if you agree. To test out and make sure it works as expected.

**Comment by fnisen** [comment]
@mahestro yup, works for me. Please go ahead.

**Comment by mahestro** [comment]
@parthshah took it.

**Comment by fnisen** [comment]
OK, I'm expecting to see some magic. 😄

**Comment by fnisen** [comment]
@parthshah maybe your changes aren't in dev yet, but this isn't working right now.

For example, I skipped all three questions, yet Files does not become required (see below). Also, if I fill out design questions and save, they are not reflected in the panel. Can you please work through my specs above and check all the scenarios? 

<img width="1154" alt="screen shot 2016-09-23 at 5 09 46 pm" src="https://cloud.githubusercontent.com/assets/12552247/18804528/15f52848-81b1-11e6-8470-af992f8a8ad2.png">
