### ISSUE TITLE
Style incomplete project confirmation component as per specs

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#890]
The component is being created via #886

**Comment by vikasrohit** [comment]
@vic-topcoder Can you please check with Didi if she needs anything else to get started on this? I can make any DOM/Javascript changes required. The changes are in [feature/deep-links](https://github.com/appirio-tech/connect-app/tree/feature/deep-links) branch.

**Comment by sirakovaDimitrina** [comment]
@vikasrohit Can you please tell me how i can reach to "project confirmation component"

**Comment by vikasrohit** [comment]
@sirakovaDimitrina You need to try creating a project and fill some project details on details form. Thereafter instead of clicking the Continue button, just reload the page and it should save the project in local storage which in turn ask you, on page load, about completing existing project or create new one.
Other hack to render that page is to change default step of the wizard by replacing `WZ_STEP_SELECT_PROD_TYPE` with `WZ_STEP_INCOMP_PROJ_CONF` in [ProjectWizard.jsx#58](https://github.com/appirio-tech/connect-app/blob/feature/deep-links/src/projects/create/components/ProjectWizard.jsx#L58)
