### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/connect-app#9]

**Comment by vic-appirio** [comment]
![favicon-connect-01](https://cloud.githubusercontent.com/assets/8484061/18495415/9596d45c-79d2-11e6-8cfe-d6ed27a9c6f7.png)

[favicon-connect-01.zip](https://github.com/appirio-tech/connect-app/files/471010/favicon-connect-01.zip)
Favicon in various sizes for full device support.

**Comment by fnisen** [comment]
@parthshah do we need this done? Not sure of the background for this issue.

**Comment by fnisen** [comment]
Guys, the current favicon is looking pixilated on my Macbook, which really jumps out when compared to other apps I have running in parallel. Can we please use higher resolution when appropriate?

**Comment by vikasrohit** [comment]
@fnisen @vic-appirio Do you guys need me to wrap this up? or is this working already?

**Comment by vic-appirio** [comment]
Try with this one, regenerated to include all different sizes:

[favicon.ico.zip](https://github.com/appirio-tech/connect-app/files/570312/favicon.ico.zip)

**Comment by fnisen** [comment]
@vikasrohit bumping this one please. Can you triage and either finish or close?

**Comment by vikasrohit** [comment]
@vic-topcoder Can we have png of the favicon? Actually, I tried to use already existing [library](https://github.com/jantimon/favicons-webpack-plugin) for generating favicon and putting that into html. However, it does not accept image in ico format.

**Comment by vic-topcoder** [comment]
@vikasrohit did you try the original attached favicon-connect-01.zip at the top? It contains all the .PNG images for different platforms/devices/sizes

**Comment by vikasrohit** [comment]
@vic-topcoder Used highest resolution favicon image from that archive. `favicon-webpack-plugin` would take care of generating the icons for other devices and browsers.
Changes should be in dev by EOD.

**Comment by vic-topcoder** [comment]
@vikasrohit - did we implement all the icon sizes from the attached .zip file? If yes, please close the issue

**Comment by vikasrohit** [comment]
@vic-topcoder I have just used one image from the archive.

**Comment by vic-topcoder** [comment]
OK. Closing this issue.
