### ISSUE TITLE
Carriage Returns (Enter) does not add new lines when posting messages

### ISSUE THREAD

**Issue by talesforce** [appirio-tech/connect-app#902]
### Expected behavior
Carriage Returns (Enter) should add new lines when posting messages

### Actual behavior
Carriage Returns (Enter) does not add new lines when posting messages

### Steps to reproduce the problem
1. Respond on any thread. Press 'Enter' a few times
2. It shows new lines while in edit view
3. When it has been posted, the new lines disappear 

### Screenshot/screencast

E.g. Edit view - https://cl.ly/3G2A2z0R3E2Q - new lines are shown
Posted view - https://cl.ly/3v3v401G3E45 - new lines disappear

The view appears very cluttered
--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager):
- Account used: Any

**Comment by fnisen** [comment]
Working well, closing.
