### ISSUE TITLE
Project Details: Color picker should not have colors set by default and have limit on colors

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#91]
<img width="611" alt="screen shot 2016-09-14 at 8 52 30 pm" src="https://cloud.githubusercontent.com/assets/12552247/18537886/721c108c-7abd-11e6-8044-c55a36e357e1.png">

Currently the color picker has 5 colors preselected by default. Let's eliminate those and simply have the "+" to start, so that the default colors are not included in every project. Also, currently the user can add unlimited colors, leading to a strange UI, as shown above. Let's either limit the color selections to a reasonable number (@mahestro, your call here as to how many would be useful) or clean up the UI to allow unlimited addition correctly.

**Comment by mahestro** [comment]
I like the idea of limiting the colors. As a copilot I'd like to catch the 2~3 main colors. I'd set it to 5 colors total, in case the project is carnival-like and has many colors, which I doubt. There are notes just in case.
