### ISSUE TITLE
Mobile styles for new connect reg flow.

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#913]

**Comment by vikasrohit** [comment]
@sirakovaDimitrina Can you please take care of it when you get time? I guess this is not critical for the release, though, hence moving it out of project and milestone.
fyi, @fnisen @vic-topcoder

**Comment by vic-topcoder** [comment]
Do we need mobile for Connect, or this is for all instances of registration? I.e. - will be used on Topcoder as well? We haven't designed the mobile view or register as I assumed we're going to keep the current styles on Topcoder. What's the case - are we going to have 1 style for all apps, or 2 different style instances for Topcoder and Connect?

**Comment by fnisen** [comment]
@vic-topcoder I think this is just mobile for Connect registration, which is your new design. Member/Topcoder reg is staying the same and already works on mobile. We are going to have 2 different styles (Topcoder and Connect) for now, at least for this release.

**Comment by fnisen** [comment]
Adding it back to project, but not a blocker for this release (P2)
