### ISSUE TITLE
Update button functionality on Connect front page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#915]
Current page: 
<img width="1239" alt="screen shot 2017-06-29 at 10 32 03 am" src="https://user-images.githubusercontent.com/12552247/27701634-595d1ab0-5cb6-11e7-83ca-c9ff532fe6af.png">

Updates: 
1. Add "Login" button to top right corner. Make it white, so it's not emphasized
2. Change "Register for free" to "Start a project" and link it to project creation
3. Change "Learn about crowdsourcing" as Vic describes below

**Comment by vic-topcoder** [comment]
Can we just replace it with a link? Blue color, regular link.

Drop the `.btn` class from the link and style it to be a regular link. Make sure the holding <div> is center-aligned.

``` SCSS
    text-align: center;
    color: #1a85ff;
    font-family: Roboto;
    font-size: 13px;
    margin: 0 auto;
    display: inline-block;
    margin-top: 10px;
```
![pasted_image_at_2017_06_29_04_27_pm](https://user-images.githubusercontent.com/8484061/27714768-f6a62bf0-5ce7-11e7-877c-4b4107feb345.png)

**Comment by vikasrohit** [comment]
Done. Please let me know if any other change is required.
FYI, for now I haven't updated the button style for Login button, it is right now a secondary button which is gray. Logically, it seems fine to me as it is actually a secondary CTA, I guess. If it is needed to be converted to white one, that is default button theme of tc-ui, please let me know.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Let me run this by @vic-topcoder when he's back.

**Comment by fnisen** [comment]
@vikasrohit can you please convert to white one (per Vic): 

![pasted image at 2017_07_05 02_27 pm](https://user-images.githubusercontent.com/12552247/27887476-cd202b02-6195-11e7-979b-1a17046df09e.png)

**Comment by vikasrohit** [comment]
Done.
