### ISSUE TITLE
Style buttons according to UI kit on Connect front page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#917]
Styling doesn't seem correct currently (screenshot below). Can you please modify it once this issue is completed: https://github.com/appirio-tech/connect-app/issues/915

<img width="1239" alt="screen shot 2017-06-29 at 10 32 03 am" src="https://user-images.githubusercontent.com/12552247/27701967-5d50a208-5cb7-11e7-93ff-256bbe7df35c.png">

**Comment by sirakovaDimitrina** [comment]
@fnisen  This task is ready.

**Comment by fnisen** [comment]
Thanks @sirakovaDimitrina. @vic-topcoder can you please check and then push to Dev?

**Comment by vic-topcoder** [comment]
The button styles are dependent on the `tc-ui` repo, so the latest changes should be on dev now.
