### ISSUE TITLE
Change design for Single Sign On option

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#918]
Can you please review the placement of the SSO button on the registration form (below)? A user may not notice it until they've started filling out the form. Is there a better way to present it?

<img width="539" alt="screen shot 2017-06-29 at 10 44 14 am" src="https://user-images.githubusercontent.com/12552247/27702123-f015b682-5cb7-11e7-8118-51c96151b7d4.png">

**Comment by vic-topcoder** [comment]
I wouldn't put the SSO under the register button. The SSO is a login option, and should be on the login, not the registration page?

**Comment by vic-topcoder** [comment]
We should use tabs to switch the experience from email to SSO registration/login:

Discussed with @fnisen over Slack. @fnisen please resolve accordingly

![register-sso_1](https://user-images.githubusercontent.com/8484061/27714862-685319f2-5ce8-11e7-9fcb-710f6169e541.png)
![register-sso_2](https://user-images.githubusercontent.com/8484061/27714861-684c0e0a-5ce8-11e7-928f-8d5a1865818c.png)

**Comment by vikasrohit** [comment]
@vic-topcoder @fnisen SSO is a registration option as well. We require each SSO user to register once to get their handle. Once user enter the SSO email and hits register, we log user in into their SSO account (which is Wipro for now) and take user back to the registration page with their profile information filled. Its just like the Social registration we have on community registration page.

@ajefts please chime in.

**Comment by fnisen** [comment]
@ajefts do we need to support SSO for Wipro right now?

**Comment by vikasrohit** [comment]
@fnisen @vic-topcoder I may not be correct from general UX point of view, however, from my personal perception, the tabs are causing me to miss the SSO option more than a separate button in the same page.
Further, as I said after we log user in into their SSO account, we redirect user back to our registration page to fill more information (handle, country etc) and to do that we have to open the 'Use Email' tab after redirection. Now it makes me (as a user) confuse how I am registering in, when I started I used 'Use SSO' tab and now after login into my ADFS account, I am presented with 'Use Email' option.

**Comment by fnisen** [comment]
Fair point. Let's put this on hold unless we know we need SSO right now.

**Comment by vikasrohit** [comment]
So you mean, we should remove the SSO registration and login buttons from connect flows? They are there on production right now, so we might have update stakeholders, if we want to remove.

**Comment by fnisen** [comment]
Right, that's what I'm trying to figure out from Tony right now. I'm not sure that anyone is currently using SSO. Let me get back to you on this one.
