### ISSUE TITLE
Remove helper text on Registration form

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#919]
The form now has field labels, so helper text is not needed: 

<img width="538" alt="screen shot 2017-06-29 at 10 50 28 am" src="https://user-images.githubusercontent.com/12552247/27702401-cd4927b4-5cb8-11e7-85fc-07e743d6ecb5.png">

**Comment by vikasrohit** [comment]
@fnisen took liberty to update other forms as well in connect flows in accounts app.
