### ISSUE TITLE
Project Details: "Thin Line" and "Solid Line" options are mislabeled

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#92]
<img width="654" alt="screen shot 2016-09-14 at 8 52 53 pm" src="https://cloud.githubusercontent.com/assets/12552247/18537964/f5cfcd38-7abd-11e6-8459-bc58ff040525.png">

**Comment by mahestro** [comment]
Right! The one on the right is thin line. The one in the middle I know it as "filled". Need advice from the design god @vic-appirio :) Wdyt?

**Comment by vic-appirio** [comment]
Thin line is the one at the right side - just line work. Solid Line is to be called only Solid. So yes, swap the two as per the original design speck.
![screen shot 2016-09-16 at 12 49 08 pm](https://cloud.githubusercontent.com/assets/8484061/18599202/fdaf6c94-7c0b-11e6-95fd-6793345a2307.png)

**Comment by mahestro** [comment]
Thanks for the confirmation! Ready to be fixed.
