### ISSUE TITLE
Country form field and drop-down component not working correctly

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#920]
Several issues: 

1. Validation message is too close to form field
2. Validation and dropdown are active at the same time
3. Drop down overlaps with form field and is too narrow (should stretch the length of the field)

<img width="472" alt="screen shot 2017-06-29 at 10 53 17 am" src="https://user-images.githubusercontent.com/12552247/27702575-5f0ce5aa-5cb9-11e7-8faf-b89fc06ce34a.png">

**Comment by fnisen** [comment]
Validation is not quite working. I can select "United States," then go back to edit it (remove "es" for example), and I don't get a validation error.

**Comment by vikasrohit** [comment]
Fixed.

**Comment by fnisen** [comment]
Not working for me still. Validation goes away if I click out of the country field and into some other field.

**Comment by vikasrohit** [comment]
@fnisen After changes for #950, it does not seem to happen for me. Please let me know if still happens to you. It might be an edge case which I am not able to reproduce.

**Comment by fnisen** [comment]
Yes, it's working for me now! Thank you.
