### ISSUE TITLE
Password tip component not working

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#922]
The password tip component has been hardcoded:

<img width="787" alt="screen shot 2017-06-29 at 11 17 58 am" src="https://user-images.githubusercontent.com/12552247/27703602-c128514a-5cbc-11e7-8413-07dbceab2d23.png">

It should actually serve as an active checklist:
<img width="797" alt="screen shot 2017-06-29 at 11 24 16 am" src="https://user-images.githubusercontent.com/12552247/27703877-a11b4528-5cbd-11e7-8083-6eeeec94f604.png">

**Comment by vikasrohit** [comment]
Done.
