### ISSUE TITLE
Password field not using new "show" button

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#923]
### Expected behavior (per design)

<img width="374" alt="screen shot 2017-06-29 at 11 34 05 am" src="https://user-images.githubusercontent.com/12552247/27704310-0f2f567a-5cbf-11e7-8e00-1997748a21bc.png">
<img width="341" alt="screen shot 2017-06-29 at 11 34 15 am" src="https://user-images.githubusercontent.com/12552247/27704311-10aeae38-5cbf-11e7-9ded-ff253d5de6e2.png">

**Comment by vikasrohit** [comment]
@fnisen It would affect community login as well. https://github.com/appirio-tech/connect-app/issues/927#issuecomment-312183201

**Comment by fnisen** [comment]
@vikasrohit no need for extra logic. Let's just change it to show the button in both places.

**Comment by vikasrohit** [comment]
👍

**Comment by vikasrohit** [comment]
Done

**Comment by fnisen** [comment]
Hmm... not seeing it: 

<img width="1183" alt="screen shot 2017-07-03 at 9 25 07 am" src="https://user-images.githubusercontent.com/12552247/27801195-8c5829d2-5fd1-11e7-8ea6-46570cc1f635.png">

**Comment by vikasrohit** [comment]
@fnisen Button is there but style is off. Show button is looking like it is the primary CTA. This is happening because of CSS conflicts, I have to nest the new styles in a wrapper class to apply them on specific pages only. Hence those styles are not visible in member side, but the DOM changes are there which is causing troubles. For now, I have copy pasted the same styles again to member side on adhoc basis, but that is not good to maintain in long term.

**Comment by vikasrohit** [comment]
One more issue found, Member Login page is using different component for password field than what we are using in registration pages. I guess, that was done to have separate validations on the password field. On registration pages we usually have the validations on password field to follow certain guidelines, however, on login page we don't.  So, if I use the same component there, it would apply the password pattern validation on login page as well. Would that be acceptable? or other thing we can do is that replicate the same UI again (with adhoc styles) in login page's password component as well.

**Comment by fnisen** [comment]
@vikasrohit the way it's working now looks good. 

I don't quite understand the validation question. On Login, the password validation happens only on the server, correct? On Registration, there is validation on the front end, which is shown in the password tip component. So, I think the validation has to be differently implemented, if I'm understanding your question correctly.

Yes, please do clean up the styles for long-term maintainability. You can do it now or set yourself a tech debt task for later.

**Comment by vikasrohit** [comment]
@fnisen Okay. My concern about validation was that if put front end validation of password (we don't show tooltip though) on login page as well. If we do that, the Login button won't be enabled until user enters a password which satisfied our password requirements. Anyway, that is not the case now, it simply enables the Login button as soon as user enter any text in the password field.

For clean up of styles, we need to sync both member and connect pages and remove dependency on appirio-styles repo. It would take some time. We can do that when we show similar UI for member side as well.

**Comment by vikasrohit** [comment]
Can we close this @fnisen ?

**Comment by fnisen** [comment]
@vikasrohit I agree--we shouldn't have front-end validation of password for Login (only for Registration). It's just that the server validation response for Login should be specific, saying whether the issue is username or password. The way it's working now is fine. 

OK, it's up to you now to track tech debt issues and tell me when you need capacity to fix them. : ) 

Closing.
