### ISSUE TITLE
Registration form typeface is not correct size

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#924]
Typeface seems to be 15px, but should be 13px, per spec (yes, I could tell the different without the inspector tool : ) ): 

<img width="1012" alt="screen shot 2017-06-29 at 11 40 13 am" src="https://user-images.githubusercontent.com/12552247/27704573-e887b5b6-5cbf-11e7-9fab-cf7c2eb9813b.png">

**Comment by vikasrohit** [comment]
Its 13px @fnisen :)

<img width="1280" alt="screen shot 2017-06-30 at 3 50 43 pm" src="https://user-images.githubusercontent.com/2417632/27731745-f4a69e74-5dab-11e7-9ecb-5a6aeea6356f.png">

line height is 30px instead of 20px, I guess.

Anyway assigning to Didi for more accurate inspection.

**Comment by fnisen** [comment]
All right, either way. Either the size of the entry field or the typeface is incorrect. Proportions look wrong to me.

**Comment by sirakovaDimitrina** [comment]
@fnisen, @vikasrohit The last version of the registration form which i sent to @vic-topcoder is according to specification.
![registration](https://user-images.githubusercontent.com/10530059/27751671-0c857f1c-5de6-11e7-8182-3e58bf7689b2.PNG)

**Comment by sirakovaDimitrina** [comment]
@fnisen, @vikasrohit The specification which i have from @vic-topcoder, We have  four different  size of the input and button controls. 
xs: height: 20px; font-size:12px;
sm: height: 30px; font-size:13px;
md: height: 40px; font-size:15px;
lg: height: 50px; font-size:20px;

**Comment by fnisen** [comment]
@sirakovaDimitrina thank you for investigating. Let me check on this with Vic once he's back in a few days.

**Comment by vikasrohit** [comment]
@fnisen Your eyes are not deluding you. They were correct, font was MerriWeahterSans coming from css conflicts of apprio-styles and tc-ui. Fixed now. :)

**Comment by fnisen** [comment]
Perfect, thank you! 🎉
