### ISSUE TITLE
Email tips component is missing 

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#925]
### Please add the password tips component:
<img width="775" alt="screen shot 2017-06-29 at 11 22 54 am" src="https://user-images.githubusercontent.com/12552247/27704675-392e4462-5cc0-11e7-8582-8805078b6418.png">

### Change the second line:
 "We'll occassionally...." with "We'll send you messages related to your account and project activities"

### Remove this text:
<img width="457" alt="screen shot 2017-06-29 at 11 27 10 am" src="https://user-images.githubusercontent.com/12552247/27704677-3a2b4626-5cc0-11e7-84f4-c392bf631aee.png">

**Comment by fnisen** [comment]
@vikasrohit styling for email tips is different from the rest of the tips components. Can you please set uniform style for all of them? Feel free to direct to Didi if needed.

**Comment by vikasrohit** [comment]
Okay. @sirakovaDimitrina can you please take care of it?

**Comment by fnisen** [comment]
@vic-topcoder FYI

**Comment by vic-topcoder** [comment]
@fnisen can you add a screenshot what's the difference/missing component? Which instance of the registration page that is? thanks

**Comment by sirakovaDimitrina** [comment]
@vikasrohit , @fnisen The tooltip is added and I removed the below text in the register.html
[register.zip](https://github.com/appirio-tech/connect-app/files/1143175/register.zip)

**Comment by fnisen** [comment]
Thanks @sirakovaDimitrina. Can you please push it to Dev?

**Comment by vikasrohit** [comment]
@fnisen Can you please try once again? I have tried to sync with design.

**Comment by fnisen** [comment]
Beautiful, thanks.
