### ISSUE TITLE
Restyle "Forgot Password" to match new styles

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#926]
### Current style
<img width="730" alt="screen shot 2017-06-29 at 11 51 49 am" src="https://user-images.githubusercontent.com/12552247/27705046-7549ea22-5cc1-11e7-965a-c9b7fc3f6ee4.png">

**Comment by vic-topcoder** [comment]
We should reuse the existing styles to rearrange the login page, really.

Help text: "We’re going to send you an email shortly with a link to reset your password. Please allow for some time or check your spam folders. If you still need help, contact support here" - @fnisen please advise on copy.

![reset password](https://user-images.githubusercontent.com/8484061/27709979-f47cfb8e-5cd2-11e7-8189-59e7b9fd725c.png)

**Comment by vikasrohit** [comment]
@vic-topcoder I guess we should have a link to Back to Login page to allow users to go back if remember the password. It happens many times with me when I recalled the password when landed on reset password page. 😬

**Comment by fnisen** [comment]
@vikasrohit 

1. I thought about adding username reset a while back, when we originally worked on this feature. It's not a good idea because your username is public, so anyone can reset your password. Let's stick to only email address.
2. Please just use the same copy as the member side. The two features can be identical, except for styling.
3. Right now the Login link is still in the right-hand corner. Let's just keep that? @vic-topcoder 

<img width="1273" alt="screen shot 2017-06-30 at 9 04 05 am" src="https://user-images.githubusercontent.com/12552247/27744314-e26fa922-5d73-11e7-8b75-eb4eef41e9df.png">

**Comment by vikasrohit** [comment]
Done. Please let me know we still need any further copy changes. I have copied copy from member side for the header only, the message is retained same as it contains link to support in addition.

**Comment by fnisen** [comment]
@vikasrohit working fine, but I'm noticing some validation issues. Will file a separate bug for that.
