### ISSUE TITLE
"Show" button missing on Login password form

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#927]
### Actual behavior
<img width="515" alt="screen shot 2017-06-29 at 12 01 19 pm" src="https://user-images.githubusercontent.com/12552247/27705470-c7695dc8-5cc2-11e7-872a-4d0179044062.png">

### Expected
<img width="297" alt="screen shot 2017-06-29 at 12 02 36 pm" src="https://user-images.githubusercontent.com/12552247/27705501-e882dffc-5cc2-11e7-964b-6b3dbcf00bc8.png">

**Comment by vikasrohit** [comment]
@fnisen @vic-topcoder Yes, I missed to use the toggle password input box here. Would fix that. However, right now it has the checkbox instead of a button to show the password. If we do that change, it would affect the community site as well as it is a common directive/component.

**Comment by fnisen** [comment]
Let's do it--one common button component. https://github.com/appirio-tech/connect-app/issues/923#issuecomment-312302962

**Comment by vikasrohit** [comment]
Done.

**Comment by fnisen** [comment]
@vikasrohit when I click on the button, it changes size--"Show" and "Hide" are different dimensions. Can you please make them both 50x30px?

**Comment by vikasrohit** [comment]
Done. Have to make it 75x30 instead, because text is not fitting in with current padding values.

**Comment by fnisen** [comment]
@vic-topcoder is this OK with you?

**Comment by fnisen** [comment]
Fine with Vic.
