### ISSUE TITLE
Login: be specific about validation error

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#929]
### Currently on the customer side we don't tell you whether your account or password is incorrect
<img width="558" alt="screen shot 2017-06-29 at 12 05 10 pm" src="https://user-images.githubusercontent.com/12552247/27705670-7fa28608-5cc3-11e7-921b-582c3891beb2.png">

---
### But we do tell you on the member side, which is useful: 
<img width="617" alt="screen shot 2017-06-29 at 12 08 41 pm" src="https://user-images.githubusercontent.com/12552247/27705751-bb9f0442-5cc3-11e7-8641-5630b2d9c762.png">

**Comment by vikasrohit** [comment]
Oh, I see. It is consistent. However, IMO, we should follow the connect approach of not letting user what exactly was wrong to prevent brute force attacks.

**Comment by fnisen** [comment]
@vikasrohit I researched this when we originally implemented Login a few years ago. This is just going to create a bad user experience. To prevent a brute force attack we need API limits. Also, our usernames are already public, and we have a member search, so anyone can use that to harvest user names if they were malicious. I'm strongly in favor of the member-side experience... unless someone can give me a good security argument.

**Comment by vikasrohit** [comment]
Done.

**Comment by fnisen** [comment]
Vikas, it's working, but the styling is inconsistent (see below). Can you please make them both according to style?

<img width="537" alt="screen shot 2017-07-03 at 9 58 06 am" src="https://user-images.githubusercontent.com/12552247/27802024-283f2a68-5fd6-11e7-9154-b1b7c0956c0d.png">

<img width="539" alt="screen shot 2017-07-03 at 9 57 56 am" src="https://user-images.githubusercontent.com/12552247/27802032-298a988a-5fd6-11e7-8c92-05e3a4d95a09.png">

**Comment by vikasrohit** [comment]
Oh, missed that. Seems typo. Done now.
