### ISSUE TITLE
Create URL for the "Select Your Project Page"...

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#931]
...so we can link to it from a marketing page (with a logged out user)

**Comment by vikasrohit** [comment]
http://connect.topcoder-dev.com/new-project/

**Comment by fnisen** [comment]
That page is behind Login still. Can you please make it public?

**Comment by fnisen** [comment]
@vikasrohit getting a 404 on this one. Can you please wire it to the "Start a new project" button from the Connect front page?

**Comment by vikasrohit** [comment]
Button is wired from the connect home page, however, it was bug which was not allowing the URL to open. Should be fixed now.
