### ISSUE TITLE
Handle wrong product id in the deep link

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#933]
Handle the case where the deep link is having wrong project id (may be a typo by marketing user or some body trying to break our system). I think we should just present the product type selection screen in this case and update the URL to exclude the wrong product param altogether.

**Comment by fnisen** [comment]
Maybe we should just 404 in this case? If marketing is doing the setup, they should test the links anyway.

**Comment by vikasrohit** [comment]
Done. Redirecting user now to 404.
