### ISSUE TITLE
Restyle "Reset Password" to match new styles

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#934]
This is the page which is loaded when user clicks on reset password link in his/her email.

cc: @fnisen @vic-topcoder

**Comment by vikasrohit** [comment]
I have tried to style it similar to forgot password page.  Here are screen shots after restyle. Please let me know if anything else needed.

<img width="1280" alt="screen shot 2017-06-30 at 12 26 13 pm" src="https://user-images.githubusercontent.com/2417632/27724382-5ae00d8c-5d8f-11e7-9362-bca4ba044e8c.png">


<img width="1280" alt="screen shot 2017-06-30 at 12 24 34 pm" src="https://user-images.githubusercontent.com/2417632/27724341-248fc4d4-5d8f-11e7-92f4-f0c34de1d09c.png">

@fnisen  @vic-topcoder  I have also taken the liberty to remove the automatic redirection to the login page after successful reset of password. IMO, user was not getting any information if the password update was successful or not. So, I have instead rendered a success message and provided the link to login. If it might create bad UX, please let me know I can revert the changes.

**Comment by fnisen** [comment]
@vikasrohit yes, I don't want to create extra steps for the user. Can you please keep the login redirection and just show a confirmation system message? I think that's what we had previously, at least on the member side. In fact, I tried to test this, but the Reset Password flow was not working for me: https://www.screencast.com/t/n46cZGGuy. It would seem like I was stuck on the reset screen, after creating a new password... until I reloaded the Dashboard and would be logged in. Can you please look into that, as well.

**Comment by vikasrohit** [comment]
We can not show the confirmation message along with redirection because by the time browser would try to render that message, it already has been redirected to login. It does not informs the user that if password reset was successful or not.

That issue on production, seems to be because some HTTPs and HTTP conflict. It is working fine on local with new flow at least. Still, I would check.

**Comment by vikasrohit** [comment]
@fnisen Got idea of redirecting user with message. However, I don't think it is working in member side though right now. It might be there before we moved the login/reg to separate app. We can add that behaviour again to member side as well. However, it would be nice if we can do that after this release, you can create an issue for that in accounts-app.

Need more help from @vic-topcoder to style this:
<img width="1280" alt="screen shot 2017-07-03 at 12 32 45 pm" src="https://user-images.githubusercontent.com/2417632/27781717-daf06abc-5fec-11e7-914c-f2ac30d64318.png">

Changes are in dev.

**Comment by fnisen** [comment]
@vikasrohit is it possible to login the user (redirect to connect app) and then throw a toaster message in connect app confirming the change? 

I don't like the extra login; worst case we can just not show the confirmation. (Confirmed this with @vic-topcoder).

**Comment by vikasrohit** [comment]
We can try that, but I would suggest we should do it after the release.

**Comment by fnisen** [comment]
OK, sounds good. Created issue to track that: https://github.com/appirio-tech/connect-app/issues/951. For now, can you please just automatically redirect and login the user, without the toaster message?

**Comment by vikasrohit** [comment]
@fnisen Created separate issue for this because this issue is more concerned about the style of the form and this feature might go under shadow of styling issue.
I guess we can safely close this now.

**Comment by fnisen** [comment]
Agree, closing.
