### ISSUE TITLE
Drop down menus with inconsistent style

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#938]
We have to style all the drop downs uniformly, and no links should be underlined.

![screen shot 3](https://user-images.githubusercontent.com/8484061/27885026-5b43e67c-618b-11e7-9eeb-d1d9e8f9deb5.png)
![screen shot 4](https://user-images.githubusercontent.com/8484061/27885027-5b58e478-618b-11e7-8113-51cc186bcc40.png)

FYI @gondzo

**Comment by vic-topcoder** [comment]
We have to hunt all the CSS and use the uniform styles from tc-ui (if they exist).

**Comment by fnisen** [comment]
@gondzo it's not correct. Compare 
<img width="129" alt="screen shot 2017-07-10 at 2 39 51 pm" src="https://user-images.githubusercontent.com/12552247/28041290-b37ea426-657d-11e7-8f48-ce16d487d9c8.png"> 
vs. 
<img width="232" alt="screen shot 2017-07-10 at 2 39 39 pm" src="https://user-images.githubusercontent.com/12552247/28041314-cb5087ea-657d-11e7-9b25-749f5d4d3d0c.png">

The carrot is protruding through the callout.

**Comment by gondzo** [comment]
Updated the styles for dropdown
![image](https://user-images.githubusercontent.com/3051646/28082284-58c295ec-6672-11e7-8839-c0dba14e1fb4.png)

**Comment by fnisen** [comment]
<img width="207" alt="screen shot 2017-07-12 at 12 48 27 pm" src="https://user-images.githubusercontent.com/12552247/28142174-8a80412c-6714-11e7-9ffb-9ed5556a6dfb.png">

@gondzo two notes please: 
- You don't need the separator for this one; the separator is only used to divide logical groups "Help" and "Logout" are not related actions, so they use the separator, whereas Edit and Delete Comment are related, so they don't need one. 
- The carrot is still not done correctly. It should be smoothly integrated with the border, like in the user menu. Also, it should not overlap with the icon to which it's pointing.

**Comment by fnisen** [comment]
Looking good, thank you.
