### ISSUE TITLE
Post deletion warning - fix design/UX

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#939]
When deleting a post we should use an alert (modal) instead of the current implementation. I'll attach the design in a bit.

Do not do this:
![screen shot 10](https://user-images.githubusercontent.com/8484061/27886277-3a6f0670-6190-11e7-8e4f-19d41fc2a324.png)

**Comment by vic-topcoder** [comment]
@gondzo - please follow the design for post or comment deletion.

![delete modal warning](https://user-images.githubusercontent.com/8484061/27943000-6843992a-6290-11e7-9cca-ffbeb933f578.png)
[delete modal.zip](https://github.com/appirio-tech/connect-app/files/1129966/delete.modal.zip)

**Comment by fnisen** [comment]
<img width="609" alt="screen shot 2017-07-10 at 3 06 12 pm" src="https://user-images.githubusercontent.com/12552247/28042252-5bd42ada-6581-11e7-8ad4-d8fd4ff79546.png">
@gondzo  please follow Vic's design exactly: centring tagline, rounded corners, button distance, etc.

**Comment by gondzo** [comment]
Done
![image](https://user-images.githubusercontent.com/3051646/28083184-d8d7306a-6674-11e7-9138-05ba0bcf8553.png)

**Comment by fnisen** [comment]
Thank you.
