### ISSUE TITLE
Cancel button while editing post

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#940]
When in edit mode for post/comments, we need to change the "cancel" button to be a ghost link. This button style actually is missing from the UI Kit right now, I'll add it, so @sirakovaDimitrina can update the tc-ui, and @gondzo can modify the code to use the appropriate styling.

Current implementation:
![screen shot 10](https://user-images.githubusercontent.com/8484061/27886400-b3ced69e-6190-11e7-848f-18619a017ed9.png)

Expected:
![screen shot 11](https://user-images.githubusercontent.com/8484061/27886412-b8856734-6190-11e7-8e62-1836d38b6bc9.png)

**Comment by sirakovaDimitrina** [comment]
@fnisen, @gondzo we have style for the link buttons in the new UI kit. You can use this class ".tc-btn-link"

**Comment by gondzo** [comment]
It's done already in the test01 branch

**Comment by fnisen** [comment]
<img width="216" alt="screen shot 2017-07-10 at 2 37 23 pm" src="https://user-images.githubusercontent.com/12552247/28041209-61baefe6-657d-11e7-8f6b-2d879aaa1b67.png">

@gondzo the two typefaces are inconsistent size. Please make them according to style.

**Comment by gondzo** [comment]
Updated font size for both.
![image](https://user-images.githubusercontent.com/3051646/28082211-1c2dd5b0-6672-11e7-9450-c4e2196e94f1.png)

**Comment by vic-topcoder** [comment]
@gondzo - did you use the proper classes for both buttons, or you edited the CSS? We have a new "link" button class for all sizes, just both buttons should be using the `.tc-btn-sm`.

**Comment by vic-topcoder** [comment]
The CSS should make the button size the same. The correct combo is `.tc-btn .tc-btn-link .tc-btn-sm`
![screen shot 1](https://user-images.githubusercontent.com/8484061/28145550-f481b3f4-6727-11e7-9006-38074f4b9602.png)

**Comment by fnisen** [comment]
@gondzo I'm still seeing the issue from before: "Cancel" looks correct in terms of proportion, but dims when moused over, instead of activating. It's clickable, but should be going from dim to active, not vice versa.

**Comment by fnisen** [comment]
Looking good.
