### ISSUE TITLE
Editing/posting with wrong background

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#942]
When editing or composing a new post, there's a wired gray background, on hover and selected state. Those should be removed.

Current:
![screen shot 12](https://user-images.githubusercontent.com/8484061/27886484-2034cc44-6191-11e7-985e-9576c716d156.png)
![screen shot 4](https://user-images.githubusercontent.com/8484061/27886517-3fbcf5e6-6191-11e7-8cc0-b0d209d6adcb.png)

Expected:
![screen shot 7](https://user-images.githubusercontent.com/8484061/27886533-5e01b9c4-6191-11e7-94ce-9340c7ad41a9.png)
![screen shot 8](https://user-images.githubusercontent.com/8484061/27886535-5fd41bfc-6191-11e7-8563-debd47156552.png)

**Comment by fnisen** [comment]
Background color is gone/correct, but now the composer window is misaligned. Should be left-aligned.

<img width="741" alt="screen shot 2017-07-10 at 2 44 27 pm" src="https://user-images.githubusercontent.com/12552247/28041449-4f7143b6-657e-11e7-9c54-7b6fdad06ffb.png">

**Comment by gondzo** [comment]
Removed padding on the text area
![image](https://user-images.githubusercontent.com/3051646/28082252-40fd9b6e-6672-11e7-9c49-2ba9c761d102.png)

**Comment by fnisen** [comment]
Looks good.
