### ISSUE TITLE
Unsaved edit alert copy is not correct (typo)

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#944]
There's a typo in the system alert when navigating away from unsaved post edit. 
![screen shot 5](https://user-images.githubusercontent.com/8484061/27886629-d155b4fc-6191-11e7-8998-42e10e995340.png)

We should use better language:

"You haven't saved your edits. Leaving this page would discard all edits. Are you sure you want to leave?"

@fnisen please advise on the copy, please.

**Comment by fnisen** [comment]
@gondzo can you please change to: "You haven't posted your message. If you leave this page, your message will not be saved. Are you sure you want to leave?"

**Comment by gondzo** [comment]
Done.
