### ISSUE TITLE
Edit icon is inserted as a CSS background, should be .SVG

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#945]
When adding icons to the front-end, please make sure we add them as .SVG. This allows us to modify states and properties via CSS. There's a plugin that wraps .SVG into a React container - @vikasrohit please advise on which is the correct way to add the external .SVG as react components.

![screen shot 3](https://user-images.githubusercontent.com/8484061/27890290-9ad74426-61a6-11e7-8068-747b9f3a647c.png)
![screen shot 4](https://user-images.githubusercontent.com/8484061/27890289-9ad4daa6-61a6-11e7-9f63-c6d7d7cb95d8.png)

**Comment by fnisen** [comment]
Looks good to me. @vic-topcoder please chime in it's still not correct.
