### ISSUE TITLE
[$20] Connect post link - fix color

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#946]
After the latest update to the connect post date (permalink to posts), the link is way too visible. Please make it gray again (as per design).
![screen shot 14](https://user-images.githubusercontent.com/8484061/27890320-d1253722-61a6-11e7-84a1-7435d325d6e9.png)

**Comment by mtwomey** [comment]
Additional comment - it's the blue "a month ago" in the image above.

**Comment by mockmew** [comment]
can I assign this?

**Comment by gondzo** [comment]
Looks good. Thanks.
