### ISSUE TITLE
Formatting bar is adding icons as background

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#947]
We should use .SVG icons as part of the markup, not as CSS background. Please add the appropriate icons as .SVG wrapped in React so we can modify the states/properties accordingly.

The states of the icons are also wrong, please fix accordingly.

Current:
![screen shot 13](https://user-images.githubusercontent.com/8484061/27890397-3ded4976-61a7-11e7-8e99-b6890a2793c9.png)
![screen shot 3](https://user-images.githubusercontent.com/8484061/27890399-41179192-61a7-11e7-9cb1-7840ce822c36.png)

Expected:
![screen shot 5](https://user-images.githubusercontent.com/8484061/27890552-3c22cb06-61a8-11e7-9c73-9e99d52ec5e0.png)

**Comment by gondzo** [comment]
@vic-topcoder can we have the svg icons for all the tools in the formatting bar? They aren't exported at > https://drive.google.com/drive/folders/0B1LbmKnex41femttcVlPbVZobjA

**Comment by vic-topcoder** [comment]
Here are the icons. Let me know if they work.
[icons-formatting.zip](https://github.com/appirio-tech/connect-app/files/1129951/icons-formatting.zip)

**Comment by fnisen** [comment]
Working correctly now, thanks.
