### ISSUE TITLE
wrong hover and misaligned components - user management

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#948]
On connect dashboard, user management section's buttons is misaligned and the hover states are not properly implemented.

Current:
![bug](https://user-images.githubusercontent.com/8484061/27890619-b3485642-61a8-11e7-899e-0dba1d4c800a.png)

Expected (per design):
![screen shot 3](https://user-images.githubusercontent.com/8484061/27890641-d4f9e03a-61a8-11e7-8280-b6e5079f3159.png)
On hover the icons would appear and cover the user role designation, which currently collides with the action for the user.

FYI @vikasrohit we might need your help on that (importing .SVGs properly).

**Comment by sirakovaDimitrina** [comment]
@vic-topcoder The task is ready. Vic please check it.

**Comment by vic-topcoder** [comment]
Did add a small interaction as per design. Now it looks good to me.
