### ISSUE TITLE
Button copy is not vertically centered

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#949]
Copy is out of alignment on this button (on connect.topcoder-dev.com):

<img width="347" alt="screen shot 2017-07-06 at 10 52 26 am" src="https://user-images.githubusercontent.com/12552247/27925357-4bebe11c-6239-11e7-832d-013337a36e35.png">

**Comment by vic-topcoder** [comment]
We're working on the buttons. There is some issue with browser rendering and Sketch file spec; we'll have it covered

**Comment by fnisen** [comment]
Thanks @vic-topcoder!

**Comment by sirakovaDimitrina** [comment]
@fnisen  and @vic-topcoder  The task is ready.

**Comment by fnisen** [comment]
@vic-topcoder can you push to Dev please?
