### ISSUE TITLE
Validate Connect Registration form on front end

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#950]
Per discussion here: https://github.com/appirio-tech/connect-app/issues/937#issuecomment-313342915

"Register" button should become active only if all validations have passed, similar to how the member registration form works. Validations should appear next to the form field, not at the top, as currently.

**Comment by vikasrohit** [comment]
@fnisen Tried to put all validations on front end and mimic the behaviour from the member side experience. But it is bit tricky to handle all validations especially because we have few custom async validators as well for validating username and emails. And country field validation adds more to the complexity. Still, it seems now more or less like member side experience. Please check and let me know if you still find any issue with it.

**Comment by fnisen** [comment]
@vikasrohit thank you, it's looking better. I found a few issues: 

1. Validation styling is incorrect (too large; doesn't match with country validation) 
<img width="427" alt="screen shot 2017-07-08 at 12 02 53 pm" src="https://user-images.githubusercontent.com/12552247/27988385-6a365e7a-63d5-11e7-85ad-4167f63d1ea8.png">

2. Getting "that username is not allowed" validation, but it's unclear why. Would only expect it for "admin", "system", and similarly sensitive usernames: 

<img width="429" alt="screen shot 2017-07-08 at 12 04 11 pm" src="https://user-images.githubusercontent.com/12552247/27988428-46c724d2-63d6-11e7-97ca-b4b560eb285f.png">

<img width="411" alt="screen shot 2017-07-08 at 12 04 23 pm" src="https://user-images.githubusercontent.com/12552247/27988429-4c0f2066-63d6-11e7-8170-207dc5e56cff.png">

3. Can get email validation into a state with no message, like so: 
<img width="468" alt="screen shot 2017-07-08 at 12 04 53 pm" src="https://user-images.githubusercontent.com/12552247/27988433-5bde205a-63d6-11e7-9709-846877014f25.png">

**Comment by vikasrohit** [comment]
@fnisen 

1. fixed the style for errors in username and email validations.
2. The actual reason of not allowing the username is returned via API in text format which might not be good for UX perspective e.g. if you enter `system` it returns `The entered username is not allowed. Please choose another one`, if you enter `admin` it returns `Please choose another username, not starting with admin.` and if you enter `sky_` it returns `username must end with a letter or a number`. I can concatenate this reason with a constant string or can show this reason only for username validation but it is difficult to modify the reason copy that is coming from server. If it was another code/enum instead, we could have detected that show the more appropriate copy instead.
I would suggest to enhance the current copy instead to give a generic overview of not allowed usernames. Again, I am always skeptical in showing the exact reason of security validations, to end users. 😬 
3. Can't reproduce for now. We can take care of it after release, I guess.

I think now we can close this issue and create a separate one for tracking these minor style issues.

**Comment by fnisen** [comment]
@vikasrohit 

On 2. understand about the reason codes--that's fine. My question was actually why those two usernames in particular "sky_" and "be" were not being allowed. We have members with those usernames: https://www.topcoder.com/members/be/, https://www.topcoder.com/members/sky_/. 

On 3. can you please literally enter "filipp@be.co."? You should see it.

**Comment by vikasrohit** [comment]
For 2, **sky_** is not allowed because now _username must end with a letter or a number_ and for **be** the reason is _Length of Handle in character should be between 3 and 15_

**Comment by vikasrohit** [comment]
For 3, @fnisen this is happening because of HTML 5 validations. Our regex validation for valid email is different than standard HTML 5 email validation. For now, we can use same error message for both our custom email validation and HTML 5 email validations. That would make sure we don't have empty error block.
Should we allow this email (filipp@be.co.) pattern?

**Comment by fnisen** [comment]
@vikasrohit for 2, are those two restrictions in our identity service? I haven't heard of them before. If so, we should say that explicitly in our rules. Right now we are saying we allow usernames with 2 characters and don't have a restriction of username not ending with an underscore. Can you please tell me all of the username rules we have currently from the API, and I will modify the copy?

For 3, we shouldn't allow an email address to end in a dot. So, "filipp@ge.co." should generate an error ("filipp@ge.co" is OK). What are the differences with our regex validation and HTML 5 validation? I'm OK with skipping HTML 5 validation, if ours is a more restrictive subset. If there are some HTML 5 rules we don't cover with our validation, we can just use the same error message for both validations.

**Comment by vikasrohit** [comment]
@fnisen we need @ykohata -san's help here to get all rules that are in place for for username validations.

Our email validation regex, on front end, is quite simple which simply enforces <any_string>@<any_string>.<any_string>, so it would allow "filipp@ge.co." as well. I am not sure what exactly the regex is used for HTML 5 email field, what I found is `[a-z0-9!#$%&'*+/=?^_`{|}~.-]+@[a-z0-9-]+(\.[a-z0-9-]+)*`, however, this one also allowing "filipp@ge.co.", if I directly test against this regex. However, when I put HTML 5 email validation, it does not allow "filipp@ge.co." , may be angular is doing some trick here. Further, our backend is also validating email pattern and in this case (when our front end regex allows trailing dot and we have disabled HTML 5 validation), our backend validation triggers that error. So, I guess we are good in terms of email validation now.

**Comment by fnisen** [comment]
OK, let me check with Kohata-san on the reg ex. 

For the email validation, can you please just show our error message for both validations then?

**Comment by ykohata** [comment]
@fnisen @vikasrohit 

The rules for handles are following:

** Topcoder Rules **
- length: 3 <= length <= 15
- a handle which contains a blank is not allowed.
- a handle which contains any char except for [a-zA-Z0-9] and -_.{}[] is not allowed.
- a handle consists of only -_.{}[] is not allowed.
- a handle which starts with "admin" is not allowed.
- a handle which contains invalid words is not allowed.

** Discourse Rules **
https://github.com/discourse/discourse/blob/master/app/models/username_validator.rb

**Comment by vikasrohit** [comment]
@fnisen by both you meant, our front end and HTML 5 validations or our front end and backend validations? We have setup for handling our front end and backend validations. But I have disabled HTML 5 validations for email.

**Comment by fnisen** [comment]
@vikasrohit OK, that's fine. The error message is working correctly now for "filipp@be.co."

**Comment by fnisen** [comment]
Thanks @ykohata!

Do we allow trailing special characters though? For example, "sky_" is not currently passing validation, even though it was allowed at some point in the past.

Also, what do you mean by "invalid words"?

**Comment by ykohata** [comment]
@fnisen 
Sorry for the late reply.
> Do we allow trailing special characters though? For example, "sky_" is not currently passing validation, even though it was allowed at some point in the past.

We introduced the same validation of Discourse which blocks handles which end with special characters like "_".
We have a list of invalid words in a table in Informix. Handles which contain any word registered in that table are not allowed.

**Comment by fnisen** [comment]
Thank you @ykohata!

**Comment by vikasrohit** [comment]
Can we close this @fnisen?

**Comment by fnisen** [comment]
Yes, thanks for checking.
