### ISSUE TITLE
Password Reset: show toaster message after logging in user after reset

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#951]
Following up on the discussion here: https://github.com/appirio-tech/connect-app/issues/934#issuecomment-313241985

**Comment by vikasrohit** [comment]
I think we can close this one @fnisen as we are now showing the message on Login page if somehow the application is not able to automatically login the user after password reset. The message is not shown as toaster though, it is a generic green box above the form. I think we are already tracking the toaster thing somewhere in github, if not we can create issue for that.

**Comment by fnisen** [comment]
Agree. Couldn't find an existing issue for the toaster, so created one here: https://github.com/appirio-tech/accounts-app/issues/155
