### ISSUE TITLE
PIN entry: incorrect validation style

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#953]
@sirakovaDimitrina can you please fix format to be similar to what we use for Login and Reg please: 

<img width="587" alt="screen shot 2017-07-06 at 11 37 11 am" src="https://user-images.githubusercontent.com/12552247/27988563-35824474-63d9-11e7-9cad-873c3589aa36.png">

Please let me know if this is not strictly a styling issue.

**Comment by sirakovaDimitrina** [comment]
@gondzo, @fnisen The styling of error messages you can find in the register-code-error.html. The style used for this class is "error-block"

**Comment by fnisen** [comment]
Thanks @sirakovaDimitrina. @vikasrohit - back to you.

**Comment by vikasrohit** [comment]
Should be done now. Please let me know if it is still having issues.

**Comment by fnisen** [comment]
@vikasrohit styling is correct; two notes please: 
1. Change the error copy: 
![screen shot 2017-07-25 at 2 54 18 pm](https://user-images.githubusercontent.com/12552247/28595576-45c6343a-7149-11e7-9fdf-2fa511457551.png)

Change to: "That PIN is incorrect. Please check that you entered the one you received."

2. When the PIN is entered correctly, the status copy says that you're being logged in and redirected you to your project. I like that part! However, the user may not necessarily have a project (if they went through registration only, not project creation). So, please either make that dynamic (saying "redirecting to project" only if they have one) or take out that part entirely, if it's easier.

**Comment by vikasrohit** [comment]
Done. Changes are in branch https://github.com/appirio-tech/accounts-app/tree/feature/copy-change-pin-verification. We can merge this once the bug hunt is over.

**Comment by fnisen** [comment]
@vikasrohit bug hunt is completed. Can you please merge and let me know when it's ready for testing?

**Comment by vikasrohit** [comment]
Merged. Should be on dev now.

**Comment by fnisen** [comment]
Looking good!
