### ISSUE TITLE
PIN entry: overall styling and styling of confirmation message

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#954]
Seems like we're mixing typefaces and the confirmation message does not match UI kit. @sirakovaDimitrina can you please clean this up? 

<img width="607" alt="screen shot 2017-07-06 at 11 28 46 am" src="https://user-images.githubusercontent.com/12552247/27988578-b092e588-63d9-11e7-822e-16701eb52826.png">

@vic-topcoder FYI

**Comment by vikasrohit** [comment]
I might be wrong, but I didn't find the success confirmation styling in prototype at that time. 😬

**Comment by fnisen** [comment]
@vikasrohit yeah, not your fault. Don't think we had it at the time.

**Comment by sirakovaDimitrina** [comment]
@fnisen  Please see the attached file with the styling for confirmation message, which you can find in the "register-verify-new-email-confirmation.html". I also made  some changes for styling buttons.
[register-1.zip](https://github.com/appirio-tech/connect-app/files/1137063/register-1.zip)

**Comment by sirakovaDimitrina** [comment]
@fnisen, @vic-topcoder Please see the attached file
[register.zip](https://github.com/appirio-tech/connect-app/files/1137086/register.zip)

**Comment by vikasrohit** [comment]
Applied success styles to pin verification and reset password pages both.

**Comment by vic-topcoder** [comment]
Ah, that's my bad - it's a new variable for text only - I extended the palette but didn't reflect it as a variable in tc-ui. I am planing to do it today.

**Comment by vic-topcoder** [comment]
@vikasrohit please replace `$tc-green` with `$tc-green-110` — this is the new variable for green text only (optically corrected to match elements using `$tc-green`. → https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss#L75

**Comment by vikasrohit** [comment]
Thanks @vic-topcoder! Done.

**Comment by fnisen** [comment]
@sirakovaDimitrina please don't close. I'll do that once I've tested.
