### ISSUE TITLE
UX for change project type

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#955]
@vic-topcoder the "Change Project type" option resets your form (all previous information is wiped out). Should we: 

1. Confirm with the user that they indeed want to restart (I think this is OK)
or
2. Keep info that carries over from form to form (e.g., Name, Ref code)

<img width="1196" alt="screen shot 2017-07-08 at 1 10 41 pm" src="https://user-images.githubusercontent.com/12552247/27988743-e614ba6a-63de-11e7-9fb5-dc970475d936.png">

**Comment by vic-topcoder** [comment]
We should keep the common information the same: name, ref. code, text areas.

**Comment by fnisen** [comment]
Created issue for Vikas: https://github.com/appirio-tech/connect-app/issues/1037
