### ISSUE TITLE
Register button doesn't work after creating new project

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#956]
Vikas, I'm getting a weird bug. If I start a new project from scratch (logged out), fill out the spec, then fill out the registration form, the "Register" button does not work. Here is a video: https://screencast.com/t/IHmBsxl7i. 

Can you please fix this one before any others b/c without I can't test the flow end-to-end?

**Comment by vikasrohit** [comment]
Done. It was happening only when country was selected using mouse operation, if user was selecting country using keyboard, it was working fine. Fixed now. Let me know if you still face the issue.

**Comment by fnisen** [comment]
Working now, thanks.
