### ISSUE TITLE
Auto login user after successful password reset

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#958]
Following up on the discussion here: https://github.com/appirio-tech/connect-app/issues/934#issuecomment-313241985

Separate ticket #951  to show toaster message on redirected URL after auto login.

**Comment by vikasrohit** [comment]
fyi @fnisen @vic-topcoder Created separate issue for this because #934 was more concerned about the style of the form and this feature might go under shadow of styling issue.

**Comment by fnisen** [comment]
@vikasrohit is this ready for testing?

**Comment by vikasrohit** [comment]
Yes

**Comment by fnisen** [comment]
@vikasrohit after I enter an email address and hit "Reset," the app hangs for a while and then I get this: 

<img width="590" alt="screen shot 2017-07-24 at 11 15 29 am" src="https://user-images.githubusercontent.com/12552247/28537981-7cd38f92-7061-11e7-927f-4345b7e94d57.png">

Console shows a 504

**Comment by fnisen** [comment]
Talked to Samir about the issue above. Looks like the problem is with identity services.

**Comment by vikasrohit** [comment]
As dev env is fixed now, it should be working now.

**Comment by fnisen** [comment]
Yes, it's working. Love the "Logging you in..." dialogue. Well done! 👍

**Comment by vikasrohit** [comment]
Thanks @fnisen I improvised these status dialogs because it was confusing for me, as user, what is happening now especially when internet speed is on lower side. Further, it might help support team if a user faces issue and reports with screen shot. We can identify where the problem could be because these statuses behaves like checkpoints of the whole process.
