### ISSUE TITLE
Copy issue for incomplete project confirmation page

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#959]
@vic-topcoder @fnisen please note that we don't have the username available to show in this screen 
<img width="953" alt="screen shot 2017-07-10 at 11 32 30 am" src="https://user-images.githubusercontent.com/2417632/28004650-b049bb0c-6563-11e7-8cb6-391d4356a509.png">

Should we use a generic title instead?

**Comment by vic-topcoder** [comment]
Yes, let's use "Welcome back!" @fnisen - feel free to comment

**Comment by fnisen** [comment]
Agree + a few minor changes: 

"Welcome back!"
"You started a project with us recently." (Change to "started" and add ".")
"Do you want to continue where you left off or create a new project?" (remove ",")

Vikas, assigning back to you for the changes.

**Comment by vikasrohit** [comment]
Done.
