### ISSUE TITLE
Project creation: delay between project being created and Manager seeing it

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#96]
In our demo today, it took at least a few minutes for a newly created project to show up on the Manager view. When a regular user was added to a project, it showed up right away, though. Is this just typical dev API instability or could it be a sign of something more serious?

**Comment by parthshah** [comment]
Nope there shouldn't be any delay. The only thing I can think of is maybe the browser was caching the API call. Are you able to reproduce this behavior?

**Comment by fnisen** [comment]
Nope, not able to reproduce. Will close, thanks.
