### ISSUE TITLE
Reset Password malfunctioning in prod (on member side)

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#961]
Not related to the current release, but discovered it when testing. Reset Password flow was not working for me: https://www.screencast.com/t/n46cZGGuy. It would seem like I was stuck on the reset screen, after creating a new password... until I reloaded the Dashboard and would be logged in. Can you please look into that, as well?

**Comment by vikasrohit** [comment]
Fixed. Should be in dev by EOD.

**Comment by fnisen** [comment]
@vikasrohit as I said here https://github.com/appirio-tech/accounts-app/issues/164#issuecomment-325311877, something is going wrong with the reset links in Dev.
