### ISSUE TITLE
Clear local storage after new project successfully submitted

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#965]
As a user, after I submit a project successfully, if I go back to "connect.topcoder-dev.com" and start a new project, I'm still asked whether I want to continue where I left off.

**Comment by vikasrohit** [comment]
@fnisen its working for me https://screencast.com/t/n7vDg0AKMg.  It might be some edge case, if you can identify that, it would be helpful for fixing.

**Comment by vikasrohit** [comment]
@fnisen I tried again, but it is still working fine for me. I am pretty much sure there is some specific condition that has to met to reproduce this issue. Can you please help in identifying it?

**Comment by vikasrohit** [comment]
@fnisen are you still seeing the issue?

**Comment by fnisen** [comment]
@vikasrohit I could reproduce this in Chrome with my current cache, but not in Safari, when I started with a "clean" cache. Let me do some more testing later. For now, I'll downgrade to a P2.
