### ISSUE TITLE
Edit post icon is misaligned

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#967]
<img width="733" alt="screen shot 2017-07-10 at 2 52 57 pm" src="https://user-images.githubusercontent.com/12552247/28041779-875995a2-657f-11e7-820b-4eeaca77b5e3.png">

Please raise the icon, as per design.

**Comment by gondzo** [comment]
Should be good now.
![image](https://user-images.githubusercontent.com/3051646/28082146-eeb43eee-6671-11e7-9296-6ab486409d0c.png)
