### ISSUE TITLE
Restyle "Deleting..." message when deleting posts

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#970]
Current implementation:
<img width="586" alt="screen shot 2017-07-12 at 12 59 05 pm" src="https://user-images.githubusercontent.com/12552247/28137397-fee18df4-6701-11e7-94d2-27d2035a205c.png">

**Comment by vic-topcoder** [comment]
I'd do a complete element cover and display a message centered:
![screen shot 1](https://user-images.githubusercontent.com/8484061/28157051-18aa72ec-676a-11e7-8b2d-e703d037bd09.png)
[deleting post.zip](https://github.com/appirio-tech/connect-app/files/1144488/deleting.post.zip)

**Comment by vic-topcoder** [comment]
@gondzo - feel free to ask @sirakovaDimitrina for CSS styling help.

**Comment by vic-topcoder** [comment]
Is this implemented?

**Comment by fnisen** [comment]
Don't think so. @gondzo?

**Comment by gondzo** [comment]
Not done yet. 
I'm thinking we can do it with a round of fixes for the post editor updates

**Comment by fnisen** [comment]
Yup, that's fine.

**Comment by fnisen** [comment]
Looks correct now.
