### ISSUE TITLE
SSO support in new logged out project creation flow

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#973]
As of now, if it is an SSO user we were showing the same PIN verification screen. Ideally, SSO user should be directly logged in after successful registration as they are already verified users.

**Comment by vikasrohit** [comment]
fyi @fnisen @vic-topcoder @ajefts

**Comment by fnisen** [comment]
@ajefts @vikasrohit for now, can we turn off SSO in Connect and funnel all SSO users to the member flow? That way we can refine the flow in one place first and avoid creating a dependency on the new project creation launch?

**Comment by vikasrohit** [comment]
As discussed over slack, @fnisen should we remove SSO option from connect flows?

**Comment by fnisen** [comment]
@vikasrohit I'm confused about the current state of SSO implementation. If a user clicks on that option, will they go through the new SSO that's on the member side or will they still use Connect's "old" SSO? If they'll use the new SSO, we can keep it. If not, let's turn it off. I just don't want to manage two SSO experiences... it's already complicated as it is.

**Comment by vikasrohit** [comment]
@fnisen yes, there is lot of confusion going on around SSO stuff and it is going through significant changes. I agree with your https://github.com/appirio-tech/connect-app/issues/973#issuecomment-317501050  to remove any sso option from connect flows and come back later when it is more stable.

**Comment by fnisen** [comment]
OK, please go ahead and remove.

**Comment by vikasrohit** [comment]
Done. Removed for now.

**Comment by fnisen** [comment]
Thank you. Looks good.
