### ISSUE TITLE
'Username or email' field is not highlighted when user enter without inputting anything

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#976]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login'

- Don't enter anything and click login

- Observe the validation and error message "That password is incorrect. Please check that you entered the right one."

Actual Result(s)
-----------------------------------------------------------------
- Won't highlight the 'Username or email' field
- Error message is not meaningful "That password is incorrect. Please check that you entered the right one."

Expected Result(s)
-----------------------------------------------------------------
- Must highlight the 'Username or email' field in red
- Error message" Username and password is empty

URL where the Bug Appears
-----------------------------------------------------------------
http://accounts.topcoder-dev.com/connect

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![3](https://user-images.githubusercontent.com/4592712/28535122-d2f14a36-70c0-11e7-9d19-1f9f635bfe2b.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by sdgun** [comment]
In here only password field is highlighted, so must highlight both because user didn't enter anything an the error message must be more meaningful so that user understand the scenario correctly. > "Username and password is Required!'

**Comment by rushikesh90** [comment]
The form is using novalidate attribute. Can I remove that?

**Comment by gondzo** [comment]
No, just update validation function to highlight username and display the error message if it's invalid

**Comment by rushikesh90** [comment]
@gondzo I feel it will be better idea to disable login button just like register page when username or password is empty. What do you think?

**Comment by gondzo** [comment]
That's fine.

**Comment by fnisen** [comment]
Looks like the original bug has been fixed, but the right approach would be to disable the Log in button, as @rushikesh90 mentioned. I've already asked for that fix here https://github.com/appirio-tech/connect-app/issues/1013
