### ISSUE TITLE
Loading animation is played below the text controllers

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#977]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login'

- Don't enter anything and click login

- Observe the loading animation

Actual Result(s)
-----------------------------------------------------------------
- Loading animation is played below the text controllers

Expected Result(s)
-----------------------------------------------------------------
- Must play the loading animation above the text controllers

URL where the Bug Appears
-----------------------------------------------------------------
http://accounts.topcoder-dev.com/connect

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by sdgun** [comment]
![4](https://user-images.githubusercontent.com/4592712/28535265-5dae7324-70c1-11e7-928f-594fc5769da8.jpg)

**Comment by sdgun** [comment]
![6](https://user-images.githubusercontent.com/4592712/28539032-e444fc26-70cd-11e7-8ab6-04f14ff822fa.jpg)

**Comment by fnisen** [comment]
@vic-topcoder what's the right UX here? The spinners are "on top" now, but that doesn't look much better to me.

**Comment by vic-topcoder** [comment]
Ideally we should provide a "loading/busy" state for the field that is being processed at the time. A global spinner does not make sense. I'd rather see it removed entirely. While loading the field should change state to indicate the process. We can design a quick "loading/busy" state with @sirakovaDimitrina, but I'll keep this as P2 and do it after release. For the time being - let's hide the spinner (it is not the same one we use inside Connect anyway).

**Comment by fnisen** [comment]
OK, creating new issue to track that: https://github.com/appirio-tech/connect-app/issues/1094 Closing this one.
