### ISSUE TITLE
2 char username is not allowed; validation displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#978]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register for free

- Enter all the required data

- Enter Qa as username

Actual Result(s)
-----------------------------------------------------------------
- 2 char username is not allowed; validation displayed

Expected Result(s)
-----------------------------------------------------------------
- Must allow 2 char usernames; hover over the username field and check (it must be 2-15 chars long)

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![5 1](https://user-images.githubusercontent.com/4592712/28535512-461e44b8-70c2-11e7-9859-5b12af554049.jpg)
![5 2](https://user-images.githubusercontent.com/4592712/28535513-462278e4-70c2-11e7-9dc3-ebbf50441f1a.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by rushikesh90** [comment]
@gondzo The error is not from UI because of length smaller than 2. It is coming from API_URL which defaults to https://api.topcoder.com. 
The url path is as follows:
{API_URL}/users/validateHandle?handle=#{encodeURIComponent(handle)}

Any idea where can I debug this.

**Comment by vikasrohit** [comment]
@gondzo we need to update the copy of tooltip here. Please see https://github.com/appirio-tech/connect-app/issues/950#issuecomment-317936987 for more details on current validations on handle.
cc: @fnisen

**Comment by gondzo** [comment]
thanks @vikasrohit, I missed that one.
@rushikesh90 just update the tooltip to say minimal length is 3 instead of 2

**Comment by rushikesh90** [comment]
This is already updated in latest branch

**Comment by fnisen** [comment]
Thanks all.
