### ISSUE TITLE
Whitespace is accepted as input

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#981]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com  
Click Start a project  
Select any project type  
Select a device target and fill out all the text field with spaces
Click Continue

### Expected behavior  
Space as input should not be allowed. 

### Actual behavior  
No validation for input and it accepts whitespaces.

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by fnisen** [comment]
Working well, thanks.
