### ISSUE TITLE
Connect logo in login screen is unclickable

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#982]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com  
Click Start a project.  
Select any project type.
Fill all the details and press Continue.
You will be directed in a login or create account screen.
Look for the Connect logo and click on it.

### Expected behavior  
Clicking on the Connect logo should direct to the main Connect page. 

### Actual behavior  
Connect logo is unclickable

### Screenshot/screencast
![logo](https://user-images.githubusercontent.com/1199534/28536120-489c3152-70d9-11e7-8a3b-38a34b927614.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment]
@fnisen Does a link to main page make sense here (user is logged out anyway). Maybe a link to the marketing page ?

**Comment by fnisen** [comment]
Yeah, don't think so. That wasn't meant to be a clickable logo in the design. We'd like to keep the user focused on registering or logging in at that point. They can always use the back button.

**Comment by macs054** [comment]
The logo in the registration and login screen from the design prototype is clickable so that's where I based it on.

**Comment by gondzo** [comment]
OK, closing this one. It's counted for the bug hunt.
