### ISSUE TITLE
[Layout] topcoder logo is missing in 'Select your project type' section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#983]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start Project'

- Check the top left corner for the logo

Actual Result(s)
-----------------------------------------------------------------
- topcoder logo is missing in 'Select your project type' section

Expected Result(s)
-----------------------------------------------------------------
- Must display the topcoder logo
- Ref: https://projects.invisionapp.com/share/QJBRJ4ITF#/screens/234311826

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/new-project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![5](https://user-images.githubusercontent.com/4592712/28536204-8eb9c7ea-70c4-11e7-9ca6-4b1323f08059.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit)

- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by gondzo** [comment]
this is a modal window so it doesn't need standard header&footer

**Comment by sdgun** [comment]
@gondzo Please check the protptype provided in the bug hunt spec here https://projects.invisionapp.com/share/QJBRJ4ITF#/screens/234311826


It displays the logo in this particular page so this must be a UI issue. Please check again

https://projects.invisionapp.com/m/share/QJBRJ4ITF#/234311826

**Comment by gondzo** [comment]
you're right. I was looking at the logged in screens.

**Comment by fnisen** [comment]
This one is fixed technically, but getting some logo inconsistencies now. Have asked Didi to address here: https://github.com/appirio-tech/connect-app/issues/1003
