### ISSUE TITLE
FEEDBACK click gives Error

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#985]
### Expected behavior
On Clicking feedback, error shouldn't be there.

### Actual behavior
On clicking feedback button, error message is being displayed.

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com/
- Click 'Feedback' button present at right side of window,

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28536385-11d4e3da-70c5-11e7-85fa-8ac0b957b49f.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1, IE11 Version 11.0.9600.18739
- User role (client, copilot or manager): Unlogged
- Account used: NA

**Comment by gondzo** [comment]
@fnisen do we need feedback widget working in dev? I guess this is just a wrong api key for topcoder-dev

**Comment by fnisen** [comment]
Yeah, don't need feedback widget in dev, which is why it's not set up.
