### ISSUE TITLE
'Project Outline' section overlap with the footer

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#987]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start a Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Enter long description for 'Description' field

- Scroll down the page and check the 'Project Outline' section and footer (right side)

Actual Result(s)
-----------------------------------------------------------------
- 'Project Outline' section overlap with the footer

Expected Result(s)
-----------------------------------------------------------------
- 'Project Outline' section must not overlap with the footer

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/new-project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![8](https://user-images.githubusercontent.com/4592712/28536456-410a8fd8-70c5-11e7-846e-c69b28f32e50.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11

- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by sirakovaDimitrina** [comment]
@fnisen I can not reproduce this issue. The footer is missing.

**Comment by fnisen** [comment]
@sirakovaDimitrina steps to reproduce:
1. Go to connect.topcoder-dev.com; click "Start a project"
2. Select Wireframe
3. Enter about a dozen lines in the "Description" field and look at the project outline unit (on the right-hand side). Now scroll down. You will see it bumps into the footer.
