### ISSUE TITLE
Long 'Project Name' will goes beyond the screen area in 'PROJECT OUTLINE' section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#988]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start a Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Enter long name for 'Project Name' field (eg: Lorem ipsum dolor sit amet, eos id tamquam complectitur definitiones, accusam )

- Check the name in 'PROJECT OUTLINE' section

Actual Result(s)
-----------------------------------------------------------------
- Long 'Project Name' will goes beyond the screen area

Expected Result(s)
-----------------------------------------------------------------
- Must display the long name in multiple lines

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/new-project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![9](https://user-images.githubusercontent.com/4592712/28536461-4dc40a92-70c5-11e7-8824-fa856a813986.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** IE11

- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by gondzo** [comment]
related to #979

**Comment by vic-topcoder** [comment]
Seems like styles are not loading correctly. Background gray is wrong.
