### ISSUE TITLE
Project Details/Feature Picker: selected features are not being saved

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#99]
- Open feature picker modal (e.g., on this project: https://connectv2.topcoder-dev.com/projects/286/)
- Select several features
- Close modal
- Features are not shown on the project details/feature requirements section, as shown in design below. Also, if I open the feature picker again, it shows that no features were selected. 

![d0cabc28-0bb9-479f-8965-cd6022383028](https://cloud.githubusercontent.com/assets/12552247/18569495/cc937056-7b57-11e6-87f4-ca7547a5e9b7.png)

**Comment by mahestro** [comment]
@vikasrohit, make sure to pull/update from dev. I uploaded changes to this page, both jsx and scss.

**Comment by vikasrohit** [comment]
@fnisen I think this issue happens only when the user has not filled any other form field before updating the features. I would fix that.

**Comment by fnisen** [comment]
@vikasrohit yes, you're right

**Comment by vikasrohit** [comment]
@fnisen It appears if user does not save the project with at least one question answered. Anyway, I have fixed the issue and tracking it in asana https://app.asana.com/0/95614844085038/181122346682552

**Comment by vikasrohit** [comment]
Changes are in dev and working fine. @fnisen please verify.

**Comment by fnisen** [comment]
Thanks @vikasrohit. Working fine for me!
