### ISSUE TITLE
[$20] Inconsistency in highlighting of 'Start A Project' button.

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#990]
### Expected behavior
The highlighting pattern of 'Start a Project' should be consistent, whenever mouse pointer hovers over it.
### Actual behavior
In chrome highlighting pattern is correct,However, text in button changes color in Firefox while button stays inactive in IE.

### Steps to reproduce the problem
- Go to URL https://connect.topcoder-dev.com/
- Bring mouse pointer over a 'Start a Project' Button.

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/20595047/28536743-44685c68-70c6-11e7-9db5-314033d17274.png)
![image](https://user-images.githubusercontent.com/20595047/28536759-4fe14bcc-70c6-11e7-8e0a-6173fc21bb22.png)
![image](https://user-images.githubusercontent.com/20595047/28536883-a546054e-70c6-11e7-95af-22618b65d434.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1, IE11 Version 11.0.9600.18739
- User role (client, copilot or manager): Not Logged In
- Account used: -NA-

**Comment by vic-topcoder** [comment]
@sirakovaDimitrina - check if we have all the correct gradient CSS for buttons. Not sure what would be the issue here

**Comment by sirakovaDimitrina** [comment]
@vic-topcoder The text in the button is not in vertical center.

**Comment by mkesselaers** [comment]
@vic-topcoder , this one needs to be closed, isn't it?
As far as I can see, it was already resolved with https://github.com/appirio-tech/connect-app/issues/1074

**Comment by gondzo** [comment]
@mkesselaers No, the difference is still present. Check the behavior in chrome vs firefox and IE

**Comment by mkesselaers** [comment]
@tosha5252, If you are unable to solve it in the 12 hours, please assign it to me. (night is calling 😃 )

**Comment by mkesselaers** [comment]
@gondzo , Can I pick it up? It has been 19 hours now

**Comment by gondzo** [comment]
yes, it's available for pickup again

**Comment by mkesselaers** [comment]
Due to time constraints, I will not be able to work on this ticket for now

**Comment by kevinkid** [comment]
I might work on it if i solve #1026 on time . Sorry for picking it up @mkesselaers

**Comment by gondzo** [comment]
looks good.
