### ISSUE TITLE
Blank Screen on clicking 'Start a Project' button.

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#991]
### Expected behavior
On clicking 'Start a Project' button, the next content screen should open.

### Actual behavior
Blank screen opens.

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com/.
- Click on 'Start a Project' button.

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/20595047/28537049-3379aafa-70c7-11e7-973d-b90b905ec8d8.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): IE11 Version 11.0.9600.18739
- User role (client, copilot or manager): Not logged In
- Account used: -NA-

**Comment by gondzo** [comment]
I can't reproduce this

**Comment by Kvm87** [comment]
I can reproduce it now as well.I can mail a video if you ask.Thanks!!!

**Comment by gondzo** [comment]
Please do, I've tried several times.

**Comment by Kvm87** [comment]
I have replied with attachment through email.Please confirm if you get it.Thanks!
