### ISSUE TITLE
Page position retained when user goes into the next page

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#992]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start a Project'

- Scroll the page (important)

- Click on 'Create Project' button from 'Software Development' in the Dashboard ("Select your project type")

- Check the page position

Actual Result(s)
-----------------------------------------------------------------
- Page position retained when user goes into the next page

Expected Result(s)
-----------------------------------------------------------------
- Must open the top part of the page always when user goes into a new page

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/new-project

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![12](https://user-images.githubusercontent.com/4592712/28537177-9eb3cd78-70c7-11e7-8dfc-593684fd3f3b.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by fnisen** [comment]
Working correctly. Thanks!
