### ISSUE TITLE
Restored session applies to all project pages

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#993]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com  
Click Start a project  
Select any project type  
Fill in any details
Close the tab. You will be asked to leave or stay, press leave.
Go to https://connect.topcoder-dev.com again
Click Start a project  
Click Continue Where I left off
Click Change project type
Select any of the project type, notice it's content

### Expected behavior  
Other project type should have empty fields except from the one you worked on. 

### Actual behavior  
All project type pages has been filled with the restored session.

### Screenshot/screencast
https://youtu.be/7-Ko8om2Hmg

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by fnisen** [comment]
@macs054 just to clarify, why is your user expectation that all the data should be cleared? For example, if you've entered a project name and reference code, wouldn't it be helpful for those to be copied over?

**Comment by macs054** [comment]
@fnisen I think it should only just be saved to the specific project type that you worked on, that's how I looked at it at least.

**Comment by fnisen** [comment]
yeah, it's a reasonable expectation, but our thinking was to err on the side of not clearing data (b/c we're not 100% sure what the user would expect and it seems worse to lose data). Let's count this, but I'm leaning toward leaving it the way it is. @gondzo what do you think?

**Comment by gondzo** [comment]
I'd leave it the way it is now as well.

**Comment by fnisen** [comment]
Sounds good.
