### ISSUE TITLE
No textbox resize function in IE and Edge

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#997]
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com using IE or Edge
Click Start a project  
Select any project type  
See the text areas and try to resize by dragging the bottom right corner

### Expected behavior  
The text area should have a resize function.

### Actual behavior  
The text area does not have a resize function.

### Screenshot/screencast
IE
![ie drag](https://user-images.githubusercontent.com/1199534/28538562-37d75196-70e1-11e7-9442-967ee97a5706.png)

Edge
![edge drag](https://user-images.githubusercontent.com/1199534/28538596-52f2dec8-70e1-11e7-83c9-208acbe2b417.png)

FF
![ff drag](https://user-images.githubusercontent.com/1199534/28538635-76953e3e-70e1-11e7-91ce-616472037a5b.png)

Chrome
![chrome drag](https://user-images.githubusercontent.com/1199534/28538659-8fd44aac-70e1-11e7-8f3a-18e3d6ded0a2.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment]
this is a browser feature in chrome and firefox. IE/Edge don't support this
