### ISSUE TITLE
'PROJECT OUTLINE' section won't stop with the left-side section when scrolling

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#998]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com 

- Login using pshah_manager/topcoder123

- Click 'Start a Project'

- Click on 'Create Project' button from 'Software Development' in the Dashboard ("Select your project type")

- Fill all the required data

- Scroll the page up and see the 'PROJECT OUTLINE' section and left side section

Actual Result(s)
-----------------------------------------------------------------
- 'PROJECT OUTLINE' section won't stop with the left-side section when scrolling

Expected Result(s)
-----------------------------------------------------------------
- 'PROJECT OUTLINE' section must stop in-line to the left-side section when scrolling up

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/projects/?page=1&sort=createdAt+desc

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![13](https://user-images.githubusercontent.com/4592712/28538758-060c0616-70cd-11e7-89b7-153f878abbd4.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Manager
- **Account used:** pshah_manager/topcoder123

**Comment by vic-topcoder** [comment]
That one might not be a CSS-related issue, but the "sticky" layout plugin. @sirakovaDimitrina please check and reassign to @gondzo if that's the case.
